// 간이 학습 질문 — Book No. M20 묶음. 사람이 아니라 AI 가 한 번 쓰고 굳힌 파일이다.
window.ACT = window.ACT || {};
var ACT = window.ACT;
ACT["M2001"] = { s: "Ten kinds of spiders and insects use a variety of musical instruments to make calypso music.",
  q: ["What instrument did your favorite bug play in the calypso band?",
      "Have you ever played a musical instrument?",
      "What instrument would you like to play in a bug band?"],
  h: ["네가 가장 좋아하는 벌레는 칼립소 악단에서 어떤 악기를 연주했나요?",
      "너는 악기를 연주해 본 적이 있나요?",
      "네가 벌레 악단에서 연주하고 싶은 악기는 무엇인가요?"] };
ACT["M2002"] = { s: "This book tells the reader about their five senses with simple words and sparkling pictures.",
  q: ["Which of your five senses did you read about in this book?",
      "Which sense do you use the most every day?",
      "Which of your five senses do you like the best?"],
  h: ["이 책에서 다섯 가지 감각 중 어떤 것에 대해 읽었나요?",
      "너는 매일 어떤 감각을 가장 많이 쓰나요?",
      "네가 가장 좋아하는 감각은 무엇인가요?"] };
ACT["M2003"] = { s: "Bill Bird can't tie his boots again! This book contains three delightful stories about the trials of young Bill Bird and his new boots.",
  q: ["What trouble did Bill Bird have with his new boots?",
      "Have you ever had trouble tying your shoes?",
      "What would you say to help Bill Bird tie his boots?"],
  h: ["빌 버드는 새 장화 때문에 어떤 어려움을 겪었나요?",
      "너는 신발끈을 묶는 데 어려움을 겪은 적이 있나요?",
      "빌 버드가 장화를 묶도록 어떤 말로 도와주고 싶나요?"] };
ACT["M2004"] = { s: "While looking through the car window on the way home from Grandpa's house, a child describes, in rhyming verse, a variety of colorful vehicles.",
  q: ["What colorful vehicle did the child see from the car window?",
      "Have you ever looked out a car window and counted vehicles?",
      "What vehicle would you like to see on your way home?"],
  h: ["아이는 차창 밖에서 어떤 색깔의 탈것을 보았나요?",
      "너는 차창 밖을 보며 탈것을 세어 본 적이 있나요?",
      "집에 가는 길에 어떤 탈것을 보고 싶나요?"] };
ACT["M2005"] = { s: "Penguin, Giraffe, and Toucan each dislike something about themselves. But they learn that it is their differences that allow them to help one another.",
  q: ["펭귄, 기린, 투칸 중에서 어떤 동물이 가장 기억에 남나요?",
      "나는 내 모습 중에서 마음에 안 드는 부분이 있나요?",
      "내가 가진 다른 점으로 친구를 도와준 적이 있다면 적어 보세요."],
  h: ["", "", ""] };
ACT["M2006"] = { s: "Matthew and Jessica learn at last the value of co-operation, but only after turning mother into a frog.",
  q: ["What happened to Matthew and Jessica's mother in this book?",
      "Have you ever had trouble sharing or working with someone?",
      "Why is it important to cooperate with your family?"],
  h: ["이 책에서 매튜와 제시카의 엄마에게 무슨 일이 일어났나요?",
      "너는 누군가와 협력하는 데 어려움을 겪은 적이 있나요?",
      "가족과 협력하는 것이 왜 중요한지 네 생각을 적어 보세요."] };
ACT["M2007"] = { s: "D. W. is determined to get her training wheels off her bike. She wants to learn to ride a two-wheeler.",
  q: ["What did D.W. want to take off her bike?",
      "Have you ever learned to ride a bike?",
      "What would you say to cheer D.W. on?"],
  h: ["디더블유는 자전거에서 무엇을 떼어 내고 싶어 했나요?",
      "너는 자전거 타는 법을 배워 본 적이 있나요?",
      "디더블유를 응원한다면 어떤 말을 해 주고 싶나요?"] };
ACT["M2008"] = { s: "Let's guess who causes the boat to sink when five animal friends of varying sizes decide to go for a row.",
  q: ["Which animal do you think sank the boat?",
      "Have you ever ridden in a boat with friends?",
      "What animal would you like to take on a boat ride?"],
  h: ["네 생각에는 어떤 동물이 배를 가라앉게 했을까요?",
      "너는 친구들과 배를 타 본 적이 있나요?",
      "배를 탈 때 함께 데려가고 싶은 동물은 무엇인가요?"] };
ACT["M2009"] = { s: "The school principal bakes a gingerbread cookie and brings it to school in his lunchbox. When the principal opens his lunchbox, the gingerbread kid runs away. Can people catch him?",
  q: ["Why did the gingerbread kid run away from the principal?",
      "Have you ever tried to catch something that ran away?",
      "How would you catch the gingerbread kid?"],
  h: ["생강빵 아이는 왜 교장 선생님에게서 도망쳤나요?",
      "너는 도망가는 것을 잡아 본 적이 있나요?",
      "네가 생강빵 아이를 잡는다면 어떻게 잡을 건가요?"] };
ACT["M2010"] = { s: "Mr. Grumpy and his friends all go for a drive. But when it rains and the car gets stuck no one wants to get out and push.",
  q: ["미스터 검피의 자동차는 비가 올 때 왜 멈췄나요?",
      "나는 비 오는 날 밖에서 곤란했던 적이 있나요?",
      "자동차가 멈췄을 때 나라면 친구들에게 어떻게 도와달라고 말했을지 적어 보세요."],
  h: ["", "", ""] };
ACT["M2011"] = { s: "A little girl's dog has too many puppies. Will the girl keep all of her puppies to the end?",
  q: ["How many puppies did the little girl's dog have?",
      "Have you ever seen a mother animal with babies?",
      "If you had too many puppies, what would you do?"],
  h: ["여자아이의 강아지는 새끼를 몇 마리나 낳았나요?",
      "너는 새끼를 낳은 동물을 본 적이 있나요?",
      "네게 강아지가 너무 많이 생긴다면 어떻게 할 건가요?"] };
ACT["M2012"] = { s: "In order not to be eaten, an inchworm measures a robin's tail, a flamingo's neck, a toucan's beak, a heron's legs, and a nightingale's song.",
  q: ["자벌레는 잡아먹히지 않으려고 무엇을 재었나요?",
      "나는 무언가의 길이를 재어 본 적이 있나요?",
      "내가 자벌레라면 무엇을 재고 싶은지 적어 보세요."],
  h: ["", "", ""] };
ACT["M2013"] = { s: "Nancy is looking forward to Pajama Day at school. She is all set to wear her new nightgown for the day. But, when Bree and Clara show up in matching pink polka-dot pajamas, Nancy feels left out.",
  q: ["How did Nancy feel when her friends wore matching pajamas?",
      "Have you ever felt left out like Nancy?",
      "What pajamas would you wear on Pajama Day?"],
  h: ["친구들이 똑같은 잠옷을 입고 왔을 때 낸시는 기분이 어땠나요?",
      "너는 낸시처럼 소외된 기분을 느껴 본 적이 있나요?",
      "네가 잠옷의 날에 입고 싶은 잠옷은 어떤 모습인가요?"] };
ACT["M2014"] = { s: "A homeless dog living in a New York City park follows a woman to Broadway Barks, where he is adopted by a little girl and finds a new home.",
  q: ["Where did the homeless dog find a new home?",
      "Have you ever wanted to help an animal without a home?",
      "What would you name the dog if you adopted him?"],
  h: ["집 없는 강아지는 어디에서 새 집을 찾았나요?",
      "너는 집 없는 동물을 도와주고 싶었던 적이 있나요?",
      "네가 그 강아지를 입양한다면 어떤 이름을 지어 줄 건가요?"] };
ACT["M2015"] = { s: "This book depicts the development of a tadpole.",
  q: ["What does a tadpole grow into, as this book shows?",
      "Have you ever seen a tadpole or a frog?",
      "What do you want to learn more about tadpoles?"],
  h: ["이 책에서 올챙이는 자라서 무엇이 되나요?",
      "너는 올챙이나 개구리를 본 적이 있나요?",
      "올챙이에 대해 더 알고 싶은 것을 한 가지 적어 보세요."] };
ACT["M2016"] = { s: "Flora the fairy fears Rufus the cat. But when she goes to visit her grandparents, some fairy magic helps her overcome her fear.",
  q: ["What did Flora the fairy fear?",
      "Have you ever been afraid of an animal?",
      "What would help you overcome a fear like Flora did?"],
  h: ["요정 플로라는 무엇을 무서워했나요?",
      "너는 어떤 동물을 무서워한 적이 있나요?",
      "플로라처럼 두려움을 이겨내려면 나에게 무엇이 도움이 될까요?"] };
ACT["M2017"] = { s: "Madeline, smallest and naughtiest of the 12 little charges of Miss Clavel, wakes up one night with an ache of appendicitis.",
  q: ["What happened to Madeline one night?",
      "Have you ever felt very sick at night?",
      "What would you do to help a friend who is sick?"],
  h: ["매들린에게 어느 날 밤 무슨 일이 일어났나요?",
      "너는 밤에 많이 아팠던 적이 있나요?",
      "아픈 친구를 돕기 위해 네가 할 수 있는 일을 적어 보세요."] };
ACT["M2018"] = { s: "When Little Critter tries to find the perfect present to thank Miss Kitty Little, he runs into difficulties.",
  q: ["What was Little Critter trying to find for Miss Kitty Little?",
      "Have you ever given a present to your teacher?",
      "What present would you give to your favorite teacher?"],
  h: ["리틀 크리터는 키티 리틀 선생님을 위해 무엇을 찾으려고 했나요?",
      "너는 선생님께 선물을 드려 본 적이 있나요?",
      "네가 가장 좋아하는 선생님께 드리고 싶은 선물은 무엇인가요?"] };
ACT["M2019"] = { s: "Arthur thinks his little sister is pesky. But one day, he learns that she can be helpful.",
  q: ["What did Arthur learn about his little sister?",
      "Do you have a younger brother or sister? What are they like?",
      "How can a younger sibling be helpful?"],
  h: ["아서는 여동생에 대해 무엇을 알게 되었나요?",
      "너는 남동생이나 여동생이 있나요? 어떤 모습인가요?",
      "동생이 도움이 될 수 있는 방법을 한 가지 적어 보세요."] };
ACT["M2020"] = { s: "Pictures of animals wearing clothes show why this would be a ridiculous custom for animals.",
  q: ["Which animal wearing clothes did you find the funniest?",
      "Have you ever put clothes on a pet or a toy animal?",
      "What animal would look silly in clothes to you?"],
  h: ["옷을 입은 동물 중에 가장 웃겼던 동물은 무엇인가요?",
      "너는 애완동물이나 인형 동물에게 옷을 입혀 본 적이 있나요?",
      "네 생각에 옷을 입으면 우스꽝스러울 것 같은 동물은 무엇인가요?"] };
ACT["M2021"] = { s: "The cats call Sausage the dog a coward. They tease him into spending the night in a haunted house.",
  q: ["Why did the cats tease Sausage?",
      "Have you ever been teased or dared to do something scary?",
      "Would you spend the night in a haunted house? Why?"],
  h: ["고양이들은 왜 소시지를 놀렸나요?",
      "너는 무서운 일을 해 보라고 놀림받거나 도전받은 적이 있나요?",
      "너라면 귀신 나오는 집에서 밤을 보낼 수 있을까요? 이유도 적어 보세요."] };
ACT["M2022"] = { s: "This book is about the adventures of a little city boy on a very snowy day. He experiences the joys of the day.",
  q: ["What joy did the boy experience on the snowy day?",
      "What do you like to do on a snowy day?",
      "What is your favorite memory of snow?"],
  h: ["눈 오는 날 남자아이는 어떤 즐거움을 경험했나요?",
      "너는 눈 오는 날 무엇을 하는 것을 좋아하나요?",
      "눈에 대한 너의 가장 좋은 기억을 적어 보세요."] };
ACT["M2023"] = { s: "Morris the Moose goes to school and learns ABC, numbers, spellings, singing, and many other things. After an exciting day at school, Morris is thrilled with all that he has learned.",
  q: ["What did Morris the Moose learn at school?",
      "What is your favorite subject to learn at school?",
      "What would you like to learn like Morris did?"],
  h: ["무스 모리스는 학교에서 무엇을 배웠나요?",
      "너는 학교에서 배우는 과목 중 무엇을 가장 좋아하나요?",
      "모리스처럼 네가 배워 보고 싶은 것을 적어 보세요."] };
ACT["M2024"] = { s: "Despite pleas from his court, a fun-loving king does not get out of his bathtub to rule his kingdom.",
  q: ["빗것 왕은 왜 욕조에서 나오지 않았나요?",
      "나는 목욕을 오래 하고 싶었던 적이 있나요?",
      "내가 왕이라면 욕조 안에서 무엇을 하고 싶은지 적어 보세요."],
  h: ["", "", ""] };
ACT["M2025"] = { s: "Little Critter visits his grandparents on their farm and helps by doing many fun jobs.",
  q: ["What jobs did Little Critter help with on the farm?",
      "Have you ever visited a farm?",
      "What job on a farm would you like to try?"],
  h: ["리틀 크리터는 농장에서 어떤 일들을 도왔나요?",
      "너는 농장에 가 본 적이 있나요?",
      "농장에서 네가 해 보고 싶은 일은 무엇인가요?"] };
ACT["M2026"] = { s: "There was once a king called Percy who liked pink color very much. One day he announces that all his subjects have to dress in pink, just like Percy.",
  q: ["What color did King Percy make everyone wear?",
      "What is your favorite color?",
      "If you were king or queen, what rule would you make?"],
  h: ["퍼시 왕은 모두에게 어떤 색 옷을 입게 했나요?",
      "네가 가장 좋아하는 색은 무엇인가요?",
      "네가 왕이나 여왕이라면 어떤 규칙을 만들고 싶나요?"] };
ACT["M2027"] = { s: "This book introduces the things that bring good luck and the things that bring bad luck.",
  q: ["What is one thing in this book that brings good luck?",
      "Do you believe in lucky or unlucky things?",
      "What is something you think brings you good luck?"],
  h: ["이 책에서 행운을 가져온다고 한 것 한 가지는 무엇인가요?",
      "너는 행운이나 불운을 가져오는 것을 믿나요?",
      "네게 행운을 가져다준다고 생각하는 것을 한 가지 적어 보세요."] };
ACT["M2028"] = { s: "It's raining, and Pete's in a bad mood. His father tries making a pizza for him... or out of him?",
  q: ["Why was Pete in a bad mood?",
      "What does your family do to cheer you up when you're sad?",
      "What game would you like to play with your dad on a rainy day?"],
  h: ["피트는 왜 기분이 안 좋았나요?",
      "네가 슬플 때 가족은 너를 어떻게 기분 좋게 해 주나요?",
      "비 오는 날 아빠와 하고 싶은 놀이를 적어 보세요."] };
ACT["M2029"] = { s: "When the Witch visits the school and uses her magic, an ordinary school day becomes special.",
  q: ["What did the Witch do to make the school day special?",
      "Have you ever had a special day at school?",
      "If you had magic for a day at school, what would you do?"],
  h: ["마녀는 학교 날을 특별하게 만들기 위해 무엇을 했나요?",
      "너는 학교에서 특별한 날을 보낸 적이 있나요?",
      "학교에서 하루 동안 마법을 쓸 수 있다면 무엇을 하고 싶나요?"] };
ACT["M2030"] = { s: "A hound rescues a schoolgirl from the Seine, becomes a beloved school pet, is chased away by the trustees, and returns with a surprise.",
  q: ["How did the hound help the schoolgirl?",
      "Have you ever been rescued or helped by an animal?",
      "What surprise do you think the hound brought back?"],
  h: ["그 사냥개는 여학생을 어떻게 도와주었나요?",
      "너는 동물에게 도움을 받은 적이 있나요?",
      "그 사냥개가 가져온 깜짝 선물은 무엇이었을지 상상해서 적어 보세요."] };
ACT["M2031"] = { s: "This book shows new lyrics to the tune of Neil Sedaka's song \"Calendar Girl,\" in which a dinosaur hatches in January and gets bigger.",
  q: ["When did the dinosaur hatch in this book?",
      "Have you ever wished for a pet dinosaur?",
      "What would you name your dinosaur pet?"],
  h: ["이 책에서 공룡은 언제 알을 깨고 나왔나요?",
      "너는 애완 공룡을 갖고 싶었던 적이 있나요?",
      "네가 공룡을 키운다면 어떤 이름을 지어 줄 건가요?"] };
ACT["M2032"] = { s: "A ticket on the Magic Train takes the reader from outer space to underwater.",
  q: ["Where did the Magic Train take the reader?",
      "Have you ever ridden on a train?",
      "Where would you like the Magic Train to take you?"],
  h: ["매직 트레인은 독자를 어디로 데려갔나요?",
      "너는 기차를 타 본 적이 있나요?",
      "매직 트레인이 너를 어디로 데려다주면 좋겠나요?"] };
ACT["M2033"] = { s: "Crocodile wants to eat Hen. But every time he tries to eat her, Hen makes him confused by calling him 'brother'.",
  q: ["What word did Hen use to confuse Crocodile?",
      "Have you ever used clever words to get out of trouble?",
      "What clever trick would you use if a crocodile wanted to eat you?"],
  h: ["암탉은 악어를 헷갈리게 하려고 어떤 말을 썼나요?",
      "너는 꾀를 내서 곤란한 상황을 벗어난 적이 있나요?",
      "악어가 너를 잡아먹으려 한다면 어떤 꾀를 쓰고 싶나요?"] };
ACT["M2034"] = { s: "Froggy is afraid of swimming in the water. In this story, his mother helps Froggy learn how to swim.",
  q: ["Who helped Froggy learn to swim?",
      "Have you ever been afraid to try something new like swimming?",
      "Who helps you when you are afraid to try something new?"],
  h: ["누가 프로기가 수영을 배우도록 도와주었나요?",
      "너는 수영처럼 새로운 것을 시도하기 무서웠던 적이 있나요?",
      "새로운 것이 무서울 때 누가 너를 도와주나요?"] };
ACT["M2035"] = { s: "Sausage, the dog, eats up a hat, a book, and a cuddly toy. Now he is sent to obedience school.",
  q: ["What things did Sausage eat up?",
      "Have you ever gotten in trouble like Sausage?",
      "What would you teach Sausage at obedience school?"],
  h: ["소시지는 무엇들을 먹어 치웠나요?",
      "너는 소시지처럼 말썽을 부려 혼난 적이 있나요?",
      "훈련 학교에서 소시지에게 무엇을 가르치고 싶나요?"] };
ACT["M2036"] = { s: "Johnny Lion stays home alone and reads his very first book about the adventures of another young lion just like himself.",
  q: ["What did Johnny Lion read about?",
      "What is your favorite book to read by yourself?",
      "What book would you like to read about an adventure?"],
  h: ["조니 라이언은 무엇에 대한 책을 읽었나요?",
      "너 혼자 읽기 좋아하는 책은 무엇인가요?",
      "네가 읽고 싶은 모험 이야기 책을 한 가지 적어 보세요."] };
ACT["M2037"] = { s: "This book uses rhyming text and amusing illustrations to describe how germs attack our bodies to cause illness.",
  q: ["세균은 우리 몸에 어떻게 들어와 병을 일으킨다고 했나요?",
      "나는 감기나 병에 걸려 본 적이 있나요?",
      "세균이 몸에 들어오지 않게 내가 할 수 있는 일을 적어 보세요."],
  h: ["", "", ""] };
ACT["M2038"] = { s: "Summer is almost over and second grade is about to begin. This is not good news for Annie. This is the first year Annie will not be in the same class as her best friends. She worries about starting second grade with a new teacher.",
  q: ["Why was Annie worried about second grade?",
      "Have you ever worried about starting a new school year?",
      "What would you say to comfort Annie?"],
  h: ["애니는 왜 2학년이 되는 것을 걱정했나요?",
      "너는 새 학년이 시작될 때 걱정했던 적이 있나요?",
      "애니를 위로한다면 어떤 말을 해 주고 싶나요?"] };
ACT["M2039"] = { s: "Although Henry's cousin Annie likes his dog Mudge, when she gets her own pet she decides that a bunny will be perfect for her.",
  q: ["What pet did Annie decide was perfect for her?",
      "What pet would be perfect for you?",
      "Why do you think that pet would suit you?"],
  h: ["애니는 자신에게 어떤 동물이 딱 맞다고 결정했나요?",
      "너에게 딱 맞는 애완동물은 무엇일까요?",
      "그 애완동물이 너에게 맞는 이유를 적어 보세요."] };
ACT["M2040"] = { s: "A little stray dog appears at a family picnic, and the kids play with him all afternoon. They even name him Willy. After a few days, the family returns to where they first met Willy to look for him.",
  q: ["아이들은 길 잃은 강아지에게 어떤 이름을 지어 주었나요?",
      "나는 길에서 동물을 만나 본 적이 있나요?",
      "내가 윌리를 만난다면 어떻게 해 주고 싶은지 적어 보세요."],
  h: ["", "", ""] };
ACT["M2041"] = { s: "Arthur has to work on his Town Project for school. Even before he comes up with a plan, his friends ask him if he can help them with their projects.",
  q: ["What project did Arthur have to work on?",
      "Have your friends ever asked you for help with homework?",
      "How do you feel when a friend asks for your help?"],
  h: ["아서는 어떤 프로젝트를 해야 했나요?",
      "친구가 숙제를 도와달라고 부탁한 적이 있나요?",
      "친구가 도움을 요청할 때 너는 어떤 기분이 드나요?"] };
ACT["M2042"] = { s: "Who will draw a sword and become a king? A group of boasting grown men fails. Now, it's young Arthur's turn to give a try.",
  q: ["Who finally succeeded in drawing the sword?",
      "Have you ever succeeded at something after others tried and failed?",
      "What would you do if you became king or queen?"],
  h: ["결국 누가 검을 뽑는 데 성공했나요?",
      "다른 사람들이 실패한 일을 너는 성공해 본 적이 있나요?",
      "네가 왕이나 여왕이 된다면 무엇을 하고 싶나요?"] };
ACT["M2043"] = { s: "You will have to buy him popcorn, if you take a mouse to a movie.",
  q: ["What did the mouse want when he went to the movies?",
      "Have you ever gone to the movies?",
      "What would you bring a mouse if you took it to the movies?"],
  h: ["쥐는 영화관에서 무엇을 원했나요?",
      "너는 영화관에 가 본 적이 있나요?",
      "쥐를 영화관에 데려간다면 무엇을 사 줄 건가요?"] };
ACT["M2044"] = { s: "Police Constable Bert likes Police Constable Marigold. Police Constable Marigold likes acting tough, fierce dogs and catching burglars. She does NOT like Police Constable Bert.",
  q: ["What does Police Constable Marigold like to do?",
      "Have you ever liked someone who didn't notice you?",
      "What would you say to help Bert and Marigold become friends?"],
  h: ["마리골드 순경은 무엇을 하기 좋아하나요?",
      "너는 상대가 알아채지 못하는데도 누군가를 좋아했던 적이 있나요?",
      "버트와 마리골드가 친구가 되도록 어떤 말을 해 주고 싶나요?"] };
ACT["M2045"] = { s: "This story describes the playfulness of a capricious wind. The wind blows hard and carries everything out to the sea. Will it ever change its mind and stop what it's been doing?",
  q: ["What did the wind carry out to the sea?",
      "Have you ever seen the wind blow something away?",
      "What would you do if the wind tried to blow your things away?"],
  h: ["바람은 무엇을 바다로 날려 보냈나요?",
      "너는 바람이 무언가를 날려 버리는 것을 본 적이 있나요?",
      "바람이 네 물건을 날려 버리려 한다면 어떻게 할 건가요?"] };
ACT["M2046"] = { s: "When Arthur shows up with his glasses on, his classmates tease him. But he can't stop wearing them because, without his glasses, he gets in all kinds of trouble.",
  q: ["Why couldn't Arthur stop wearing his glasses?",
      "Have you or a friend ever worn glasses?",
      "What would you say to Arthur's classmates who teased him?"],
  h: ["아서는 왜 안경을 그만 쓸 수 없었나요?",
      "너나 친구가 안경을 써 본 적이 있나요?",
      "아서를 놀린 친구들에게 어떤 말을 해 주고 싶나요?"] };
ACT["M2047"] = { s: "Mary Clare divides treats into halves, thirds, or other fractional parts to make sure that each of her friends or family members can enjoy an equal share.",
  q: ["메리 클레어는 간식을 나눌 때 어떤 방법을 썼나요?",
      "나는 무언가를 친구와 똑같이 나눠 본 적이 있나요?",
      "내가 나누어 주고 싶은 간식을 한 가지 적어 보세요."],
  h: ["", "", ""] };
ACT["M2048"] = { s: "Three owl chicks, Sarah, Percy, and Bill, are awakened one night to find their mother is missing.",
  q: ["What did the owl babies find missing one night?",
      "Have you ever felt worried when you couldn't find your mom?",
      "What would you say to comfort the owl babies?"],
  h: ["아기 올빼미들은 어느 밤 무엇이 없어진 것을 알았나요?",
      "엄마를 못 찾아서 걱정한 적이 있나요?",
      "아기 올빼미들을 위로한다면 어떤 말을 해 주고 싶나요?"] };
ACT["M2049"] = { s: "Mrs. Teaberry sends over some special treats when Mr. Putter catches a cold, hoping he gets better soon.",
  q: ["What did Mrs. Teaberry send when Mr. Putter caught a cold?",
      "Has anyone brought you something special when you were sick?",
      "What treat would you bring a sick friend?"],
  h: ["미스터 퍼터가 감기에 걸렸을 때 미시즈 티베리는 무엇을 보내 주었나요?",
      "네가 아팠을 때 누군가 특별한 것을 가져다준 적이 있나요?",
      "아픈 친구에게 어떤 간식을 가져다주고 싶나요?"] };
ACT["M2050"] = { s: "It's Halloween, and SpongeBob is determined to scare everyone this year. All he has to do is dress up like the Flying Dutchman.",
  q: ["What did SpongeBob dress up as to scare everyone?",
      "What have you dressed up as for Halloween?",
      "What costume would you like to wear next Halloween?"],
  h: ["스폰지밥은 모두를 놀라게 하려고 무엇으로 변장했나요?",
      "너는 할로윈에 무엇으로 변장해 보았나요?",
      "다음 할로윈에 입고 싶은 옷차림을 적어 보세요."] };
ACT["M2051"] = { s: "Owen, the mouse, loves his fuzzy yellow blanket. He takes it everywhere he goes. But soon, he will begin school. His parents are in despair.",
  q: ["What did Owen love and take everywhere?",
      "Do you have a favorite toy or blanket like Owen's?",
      "What would you say to help Owen's parents solve the problem?"],
  h: ["오웬은 무엇을 좋아해서 어디든 가지고 다녔나요?",
      "너에게도 오웬의 담요처럼 가장 좋아하는 물건이 있나요?",
      "오웬의 부모님을 돕기 위해 어떤 방법을 생각해 볼 수 있을까요?"] };
ACT["M2052"] = { s: "This book introduces eleven different dinosaurs: their diet, their size, their names, and their characteristics.",
  q: ["Which dinosaur from this book do you remember best?",
      "Have you ever seen a dinosaur in a museum or a picture?",
      "Which dinosaur would you like to learn more about?"],
  h: ["이 책에 나온 공룡 중에 가장 기억에 남는 공룡은 무엇인가요?",
      "너는 박물관이나 그림에서 공룡을 본 적이 있나요?",
      "더 알고 싶은 공룡을 한 가지 적어 보세요."] };
ACT["M2053"] = { s: "This book is a simple retelling of the tale about the clever cat who helps his poor master win fame, fortune, and a beautiful princess.",
  q: ["What did the clever cat help his master win?",
      "Have you ever helped a friend get something they wanted?",
      "What clever plan would you make to help a friend?"],
  h: ["영리한 고양이는 주인이 무엇을 얻도록 도와주었나요?",
      "너는 친구가 원하는 것을 얻도록 도와준 적이 있나요?",
      "친구를 돕기 위해 네가 생각한 영리한 계획을 적어 보세요."] };
ACT["M2054"] = { s: "A little blue spot and a little yellow spot are best friends. When they hug each other, what color are they?",
  q: ["What color did Little Blue and Little Yellow become when they hugged?",
      "Do you have a best friend like Little Blue and Little Yellow?",
      "What color would you and your best friend make together?"],
  h: ["리틀 블루와 리틀 옐로우는 서로 안았을 때 무슨 색이 되었나요?",
      "너에게도 리틀 블루와 리틀 옐로우 같은 가장 친한 친구가 있나요?",
      "너와 가장 친한 친구가 만나면 어떤 색이 될 것 같나요?"] };
ACT["M2055"] = { s: "A boy imagines a world in which dinosaurs perform beneficial public services.",
  q: ["What kind of service did a dinosaur do in the boy's imagination?",
      "Have you ever imagined dinosaurs coming back to life?",
      "What job would you like a dinosaur to do for you?"],
  h: ["소년의 상상 속에서 공룡은 어떤 도움을 주었나요?",
      "너는 공룡이 다시 살아난다면 어떨지 상상해 본 적이 있나요?",
      "공룡이 너를 위해 해 주었으면 하는 일을 적어 보세요."] };
ACT["M2056"] = { s: "A hungry garden spider builds a web and patiently waits to catch something tasty for its lunch.",
  q: ["정원 거미는 점심을 잡으려고 무엇을 만들었나요?",
      "나는 거미줄을 본 적이 있나요?",
      "내가 거미라면 점심으로 무엇을 잡고 싶은지 적어 보세요."],
  h: ["", "", ""] };
ACT["M2057"] = { s: "A spoof of the fairy tale Sleeping Beauty. In this version, the good fairies all make good wishes for the beautiful baby princess, but the one bad fairy makes a very bad wish.",
  q: ["What did the bad fairy do for the baby princess?",
      "Have you ever wished good things for someone?",
      "What good wish would you make for a new baby?"],
  h: ["나쁜 요정은 아기 공주를 위해 무엇을 했나요?",
      "너는 누군가를 위해 좋은 소원을 빌어 본 적이 있나요?",
      "새로 태어난 아기를 위해 어떤 좋은 소원을 빌어 주고 싶나요?"] };
ACT["M2058"] = { s: "Yet as soon as Lisa sees him, she knows that he's the bear for her. Her mother, though, thinks he's a little shopworn--he's even missing a button!",
  q: ["What was missing from Corduroy the bear?",
      "Do you have a favorite stuffed animal like Corduroy?",
      "What would you do to help Corduroy find his button?"],
  h: ["곰 인형 코듀로이에게는 무엇이 없었나요?",
      "너에게도 코듀로이 같은 좋아하는 인형이 있나요?",
      "코듀로이가 단추를 찾도록 어떻게 도와주고 싶나요?"] };
ACT["M2059"] = { s: "This book shows us the anatomy, behavior, and life cycle of land and sea turtles.",
  q: ["What did you learn about land or sea turtles?",
      "Have you ever seen a turtle?",
      "Would you rather have a land turtle or a sea turtle? Why?"],
  h: ["육지 거북이나 바다 거북에 대해 무엇을 배웠나요?",
      "너는 거북이를 본 적이 있나요?",
      "육지 거북과 바다 거북 중 어느 쪽을 키우고 싶나요? 이유도 적어 보세요."] };
ACT["M2060"] = { s: "Mr. Carter mistakes the literal-minded Amelia Bedelia for the new teacher, and class is never the same.",
  q: ["카터 선생님은 아멜리아 베델리아를 누구로 착각했나요?",
      "나는 누군가를 다른 사람으로 착각한 적이 있나요?",
      "아멜리아 베델리아가 선생님이 되면 어떤 수업이 될지 상상해서 적어 보세요."],
  h: ["", "", ""] };
ACT["M2061"] = { s: "Froggy is very excited about his first sleepover at Max's house. But he finds it difficult to fall asleep when a series of events sends him and Max back and forth between their houses.",
  q: ["Why did Froggy find it hard to fall asleep?",
      "Have you ever had a sleepover at a friend's house?",
      "What would you bring to a sleepover?"],
  h: ["프로기는 왜 잠들기 어려웠나요?",
      "너는 친구 집에서 자 본 적이 있나요?",
      "친구 집에서 잘 때 가져가고 싶은 물건을 적어 보세요."] };
ACT["M2062"] = { s: "This book describes the ways you use your hands every day with simple words and sparkling illustrations.",
  q: ["What is one way this book said you use your hands?",
      "What do you use your hands for the most?",
      "What is something special your hands can make?"],
  h: ["이 책에서 손을 어떻게 쓴다고 했나요? 한 가지를 적어 보세요.",
      "너는 손을 가장 많이 쓰는 일이 무엇인가요?",
      "네 손으로 만들 수 있는 특별한 것을 적어 보세요."] };
ACT["M2063"] = { s: "Nancy is making the cover of her very first book report and she wants it to be very fancy. She uses beads, fringe, and a fancy border. But she is running out of time to write about the book.",
  q: ["What did Nancy use to make her book report cover fancy?",
      "Have you ever spent too much time decorating instead of finishing your work?",
      "What would you use to decorate your own book report?"],
  h: ["낸시는 독후감 표지를 화려하게 만들려고 무엇을 썼나요?",
      "너는 꾸미는 데 시간을 너무 써서 할 일을 못 끝낸 적이 있나요?",
      "네가 독후감을 꾸민다면 무엇을 쓰고 싶나요?"] };
ACT["M2064"] = { s: "There was once a king and queen. They lived with their son Hugo in a big castle. Hugo has every toy he could wish for, but he's still very lonely. What he needs is a wild hullabaloo!",
  q: ["Why was Hugo lonely even though he had every toy?",
      "Have you ever felt lonely even with lots of toys?",
      "What would you do with Hugo to have a wild hullabaloo?"],
  h: ["휴고는 장난감이 많았는데도 왜 외로웠나요?",
      "너는 장난감이 많은데도 외로웠던 적이 있나요?",
      "휴고와 함께 신나는 소동을 벌인다면 무엇을 하고 싶나요?"] };
ACT["M2065"] = { s: "Two children learn the important lessons of eating healthy and avoiding junk food.",
  q: ["What did the children learn about eating well?",
      "What healthy food do you like to eat?",
      "What junk food do you think you should eat less of?"],
  h: ["아이들은 잘 먹는 것에 대해 무엇을 배웠나요?",
      "네가 좋아하는 건강한 음식은 무엇인가요?",
      "네가 조금 덜 먹어야 한다고 생각하는 정크푸드를 적어 보세요."] };
ACT["M2066"] = { s: "Winnie gets tired of winter and uses magic to bring summer and sunshine to her house.",
  q: ["What did Winnie use magic to bring to her house?",
      "Do you get tired of winter like Winnie?",
      "If you had magic, what season would you bring?"],
  h: ["위니는 마법으로 집에 무엇을 가져왔나요?",
      "너도 위니처럼 겨울이 지겹게 느껴진 적이 있나요?",
      "너에게 마법이 있다면 어떤 계절을 가져오고 싶나요?"] };
ACT["M2067"] = { s: "When Harry gets too dirty, his family doesn't recognize him until he takes a bath.",
  q: ["Why didn't Harry's family recognize him?",
      "Have you ever gotten so dirty that you needed a bath right away?",
      "What would you say to Harry after his bath?"],
  h: ["해리의 가족은 왜 해리를 못 알아보았나요?",
      "너는 너무 더러워져서 바로 씻어야 했던 적이 있나요?",
      "목욕을 마친 해리에게 어떤 말을 해 주고 싶나요?"] };
ACT["M2068"] = { s: "Beth admires her friend Molly's courage; but on a visit to Molly's country home, Beth surprises herself with her own bravery when the two become lost within the maze of a cornfield.",
  q: ["When did Beth surprise herself with her own bravery?",
      "Have you ever surprised yourself by being brave?",
      "What is one brave thing you would like to do?"],
  h: ["베스는 언제 자신의 용감함에 스스로 놀랐나요?",
      "너는 스스로 용감했던 것에 놀란 적이 있나요?",
      "네가 해 보고 싶은 용감한 일을 한 가지 적어 보세요."] };
ACT["M2069"] = { s: "Tom the cat bakes snacks and tries to divide them evenly for himself and his two friends. This book includes division activities.",
  q: ["What did Tom the cat bake and try to share?",
      "Have you ever shared snacks equally with friends?",
      "What snack would you like to bake and share?"],
  h: ["고양이 톰은 무엇을 구워서 나누려고 했나요?",
      "너는 친구들과 간식을 똑같이 나눠 본 적이 있나요?",
      "네가 구워서 나누고 싶은 간식을 적어 보세요."] };
ACT["M2070"] = { s: "If a hungry mouse shows up on your doorstep, you might want to give him a cookie. And if you give him a cookie, he'll ask for a glass of milk. What will he ask for next?",
  q: ["What did the mouse ask for after the cookie?",
      "Have you ever given a snack to someone and they asked for more?",
      "What do you think the mouse will ask for next?"],
  h: ["쥐는 쿠키를 먹은 다음 무엇을 달라고 했나요?",
      "누군가에게 간식을 주었더니 더 달라고 한 적이 있나요?",
      "쥐가 다음에는 무엇을 달라고 할지 상상해서 적어 보세요."] };
ACT["M2071"] = { s: "Hairy Maclary, a small black dog, uses a series of slick maneuvers to protect his bone from his crew of five kooky canines.",
  q: ["What did Hairy Maclary try to protect from the other dogs?",
      "Have you ever had to protect something you didn't want to share?",
      "What trick would you use to protect your favorite thing?"],
  h: ["헤어리 매클래리는 다른 개들로부터 무엇을 지키려고 했나요?",
      "너는 나누고 싶지 않은 물건을 지켜야 했던 적이 있나요?",
      "네가 가장 아끼는 것을 지키기 위한 방법을 적어 보세요."] };
ACT["M2072"] = { s: "A girl who loves baseball worries that the ballet class will ruin her reputation with the other members of her baseball team.",
  q: ["What was the girl worried about?",
      "Have you ever worried what your friends would think about something you liked?",
      "What two different things do you enjoy doing, like baseball and ballet?"],
  h: ["여자아이는 무엇을 걱정했나요?",
      "너는 친구들이 네가 좋아하는 것을 어떻게 생각할지 걱정해 본 적이 있나요?",
      "야구와 발레처럼 네가 좋아하는 서로 다른 두 가지를 적어 보세요."] };
ACT["M2073"] = { s: "When a princess who behaves like a dragon meets a dragon who behaves like a princess, there are unexpected results.",
  q: ["How did the princess in this book behave?",
      "Have you ever met someone who was different from what you expected?",
      "What would you say to a dragon who acted like a princess?"],
  h: ["이 책의 공주는 어떻게 행동했나요?",
      "너는 예상과 다른 사람을 만난 적이 있나요?",
      "공주처럼 행동하는 용에게 어떤 말을 해 주고 싶나요?"] };
ACT["M2074"] = { s: "At Pirate School, Pete learns to act like a pirate and fight it out. But when he and a classmate discover the buried treasure at the same time, pirate rules do not seem to work, and the amusing results are observed by everyone.",
  q: ["What did Pete and his classmate find at the same time?",
      "Have you ever found something at the same time as a friend?",
      "What would you do if you and a friend found treasure together?"],
  h: ["피트와 반 친구는 동시에 무엇을 발견했나요?",
      "너는 친구와 동시에 무언가를 발견한 적이 있나요?",
      "친구와 함께 보물을 찾는다면 어떻게 할 건가요?"] };
ACT["M2075"] = { s: "Jack brings home his class hamster for the holidays, and Sausage, the dog, is very jealous. But when the cats start talking about eating the hamster, Sausage can't just stand back and watch.",
  q: ["What did Sausage do when the cats wanted to eat the hamster?",
      "Have you ever protected a small animal or a friend?",
      "What would you do to protect a class pet?"],
  h: ["고양이들이 햄스터를 먹으려 하자 소시지는 어떻게 했나요?",
      "너는 작은 동물이나 친구를 지켜 준 적이 있나요?",
      "학급 반려동물을 지키기 위해 네가 할 수 있는 일을 적어 보세요."] };
ACT["M2076"] = { s: "No matter how or where he tries, Mr. Bear can't fall asleep. Will he sleep at last?",
  q: ["베어 아저씨는 왜 잠들지 못했나요?",
      "나는 잠이 안 와서 힘들었던 적이 있나요?",
      "베어 아저씨가 잠들도록 내가 도와줄 방법을 적어 보세요."],
  h: ["", "", ""] };
ACT["M2077"] = { s: "Two wolves discover that they are very different. But they also learn that they can still be friends.",
  q: ["How were the two wolves different from each other?",
      "Do you have a friend who is very different from you?",
      "Why can two very different friends still get along?"],
  h: ["두 늑대는 서로 어떻게 달랐나요?",
      "너와 많이 다른 친구가 있나요?",
      "서로 많이 다른 친구도 왜 잘 지낼 수 있을지 네 생각을 적어 보세요."] };
ACT["M2078"] = { s: "Henry, feeling lonely on a street without any other children, finds companionship and love in a big dog named Mudge.",
  q: ["Who did Henry find companionship with?",
      "Have you ever felt lonely and found a friend, even a pet?",
      "What would you like to do with a big dog like Mudge?"],
  h: ["헨리는 누구와 함께 지내며 외로움을 달랬나요?",
      "너는 외로울 때 친구나 반려동물을 만나 본 적이 있나요?",
      "머지 같은 큰 강아지와 함께 하고 싶은 일을 적어 보세요."] };
ACT["M2079"] = { s: "Five little monkeys decide to sell the family car, and they start washing it first.",
  q: ["What did the five little monkeys wash before selling it?",
      "Have you ever helped wash a car?",
      "What would you do first if you had to sell something?"],
  h: ["다섯 마리 원숭이는 팔기 전에 무엇을 씻었나요?",
      "너는 세차를 도와 본 적이 있나요?",
      "무언가를 팔기 전에 네가 가장 먼저 할 일을 적어 보세요."] };
ACT["M2080"] = { s: "When Mr Trim, the class teacher, wakes up feeling unwell, Miss Jumble is sent in as a supply teacher.",
  q: ["Why was Miss Jumble sent to the class?",
      "Have you ever had a substitute teacher?",
      "What kind of substitute teacher would you like to have?"],
  h: ["미스 점블은 왜 교실에 오게 되었나요?",
      "너는 보결 선생님과 수업해 본 적이 있나요?",
      "네가 만나고 싶은 보결 선생님은 어떤 모습인가요?"] };
ACT["M2081"] = { s: "Froggy gets the very first bike that he has dreamed of. In this story, he learns to ride his new bike with encouragement from his friends and family.",
  q: ["Who encouraged Froggy to learn to ride his bike?",
      "Who taught you to ride a bike, or helped you learn something new?",
      "What would you say to encourage a friend learning to ride a bike?"],
  h: ["누가 프로기가 자전거를 배우도록 응원해 주었나요?",
      "너에게 자전거 타는 법이나 새로운 것을 가르쳐 준 사람은 누구인가요?",
      "자전거를 배우는 친구를 응원한다면 어떤 말을 해 주고 싶나요?"] };
ACT["M2082"] = { s: "Muffy and Francine are best friends. But when Muffy lets Francine take the blame for something, their friendship is put at risk.",
  q: ["What did Muffy let Francine do?",
      "Have you ever been blamed for something you didn't do?",
      "What would you say to a friend who let you take the blame?"],
  h: ["머피는 프랜신이 무엇을 하게 두었나요?",
      "너는 하지 않은 일로 오해를 받은 적이 있나요?",
      "네가 대신 혼나게 둔 친구에게 어떤 말을 해 주고 싶나요?"] };
ACT["M2083"] = { s: "Mouse escapes his predators by telling them he is on his way to meet his friend the gruffalo, a horrible creature. The gruffalo, however, is just in Mouse's imagination, or is it?",
  q: ["Who did Mouse say he was going to meet?",
      "Have you ever made up a story to stay safe or get out of trouble?",
      "What would a scary creature you imagine look like?"],
  h: ["쥐는 누구를 만나러 간다고 말했나요?",
      "너는 안전하기 위해 이야기를 지어낸 적이 있나요?",
      "네가 상상하는 무서운 생명체는 어떤 모습인지 적어 보세요."] };
ACT["M2084"] = { s: "Mr. Putter thinks he is too old for birthday celebrations. So, on his birthday, he invites Mrs. Teaberry and Zeke over for a quiet cup of tea.",
  q: ["Who did Mr. Putter invite for his birthday?",
      "How do you like to celebrate your birthday?",
      "What wish would you make on your birthday?"],
  h: ["미스터 퍼터는 생일에 누구를 초대했나요?",
      "너는 생일을 어떻게 보내는 것을 좋아하나요?",
      "생일에 네가 빌고 싶은 소원을 적어 보세요."] };
ACT["M2085"] = { s: "This book recounts events in the life of George Washington that focus on his love for animals.",
  q: ["What did this book say George Washington loved?",
      "Do you love animals like George Washington did?",
      "What would you do to take care of a general's dog?"],
  h: ["이 책은 조지 워싱턴이 무엇을 사랑했다고 했나요?",
      "너도 조지 워싱턴처럼 동물을 사랑하나요?",
      "장군의 강아지를 돌본다면 무엇을 해 주고 싶나요?"] };
ACT["M2086"] = { s: "This book relates the excitement Henry Ford caused as he drove the 'horseless carriage' he created.",
  q: ["What did Henry Ford drive in this book?",
      "Have you ever watched a race?",
      "What would you like to invent, like Henry Ford did?"],
  h: ["헨리 포드는 이 책에서 무엇을 운전했나요?",
      "너는 경주를 본 적이 있나요?",
      "헨리 포드처럼 네가 만들어 보고 싶은 것을 적어 보세요."] };
ACT["M2087"] = { s: "When Kitten mistakes the full moon for a bowl of milk and tries to reach it, she ends up being tired, wet, and hungry.",
  q: ["What did Kitten mistake the full moon for?",
      "Have you ever mistaken one thing for another?",
      "What would you do to help Kitten feel better?"],
  h: ["새끼 고양이는 보름달을 무엇으로 착각했나요?",
      "너는 어떤 것을 다른 것으로 착각한 적이 있나요?",
      "새끼 고양이의 기분이 나아지도록 무엇을 해 주고 싶나요?"] };
ACT["M2088"] = { s: "Everything in Winnie's house is black, including her cat. When she has trouble seeing her cat, she decides to use just a little magic.",
  q: ["Why did Winnie have trouble seeing her cat?",
      "Have you ever had trouble finding something because of its color?",
      "What magic would you use to solve a problem like Winnie's?"],
  h: ["위니는 왜 고양이를 잘 보지 못했나요?",
      "너는 색깔 때문에 무언가를 찾기 힘들었던 적이 있나요?",
      "위니와 같은 문제를 해결하려면 어떤 마법을 쓰고 싶나요?"] };
ACT["M2089"] = { s: "This book describes about the many kinds of sharks.",
  q: ["What kind of shark did you learn about in this book?",
      "Have you ever seen a shark in an aquarium or on TV?",
      "What shark would you like to learn more about?"],
  h: ["이 책에서 어떤 상어에 대해 배웠나요?",
      "너는 수족관이나 텔레비전에서 상어를 본 적이 있나요?",
      "더 알고 싶은 상어를 한 가지 적어 보세요."] };
ACT["M2090"] = { s: "Freddy is playing football at school, and he has trouble avoiding fights. But, in the end, He learns to use his anger to play better.",
  q: ["What did Freddy learn to do with his anger?",
      "Have you ever felt angry while playing a game?",
      "What do you do when you feel angry?"],
  h: ["프레디는 화가 났을 때 그 마음을 어떻게 쓰는 법을 배웠나요?",
      "너는 게임을 하다가 화가 난 적이 있나요?",
      "네가 화가 났을 때 무엇을 하는지 적어 보세요."] };
ACT["M2091"] = { s: "This story is about a boy who loves stars so much. He devises a plan to catch one of his own.",
  q: ["What plan did the boy make to catch a star?",
      "Have you ever wished you could catch something impossible, like a star?",
      "What would you do with a star if you caught one?"],
  h: ["남자아이는 별을 잡으려고 어떤 계획을 세웠나요?",
      "너는 별처럼 잡을 수 없는 것을 잡고 싶었던 적이 있나요?",
      "별을 잡는다면 무엇을 하고 싶나요?"] };
ACT["M2092"] = { s: "Lou Lou decides to wear a fat hat to lunch, and it upsets her friend very much.",
  q: ["What did Lou Lou wear that upset her friend?",
      "Have you ever worn something that surprised your friends?",
      "What would you say to make Lou Lou's friend feel better?"],
  h: ["루루가 쓴 무엇이 친구를 화나게 했나요?",
      "너는 친구들을 놀라게 한 옷이나 물건을 입거나 써 본 적이 있나요?",
      "루루의 친구 기분이 나아지도록 어떤 말을 해 주고 싶나요?"] };
ACT["M2093"] = { s: "Harry the dog hates his birthday sweater with roses on it. He discovers an ingenious way to get rid of it.",
  q: ["What did Harry hate about his birthday sweater?",
      "Have you ever gotten a gift you didn't like?",
      "What clever way would you use to get rid of something you don't like?"],
  h: ["해리는 생일 선물 스웨터의 무엇이 싫었나요?",
      "너는 마음에 들지 않는 선물을 받아 본 적이 있나요?",
      "싫은 것을 없애기 위한 영리한 방법을 적어 보세요."] };
ACT["M2094"] = { s: "This story describes how Charlie makes a beautiful new red cloak.",
  q: ["What color cloak did Charlie make?",
      "Have you ever made your own clothes or craft?",
      "What would you like to make, like Charlie made his cloak?"],
  h: ["찰리는 무슨 색 망토를 만들었나요?",
      "너는 옷이나 물건을 직접 만들어 본 적이 있나요?",
      "찰리가 망토를 만든 것처럼 네가 만들어 보고 싶은 것을 적어 보세요."] };
ACT["M2095"] = { s: "A monkey has lost her mother in the jungle and is assisted to find her mother by a butterfly. Can the monkey go back to her mother?",
  q: ["Who helped the monkey look for her mother?",
      "Have you ever gotten lost and needed help finding your way?",
      "What would you do to help the monkey find her mother?"],
  h: ["누가 원숭이가 엄마를 찾도록 도와주었나요?",
      "너는 길을 잃어서 도움이 필요했던 적이 있나요?",
      "원숭이가 엄마를 찾도록 어떻게 도와주고 싶나요?"] };
ACT["M2096"] = { s: "Arthur embarks on his own pet-sitting business. He is determined to prove that he can handle a dog of his own.",
  q: ["What business did Arthur start?",
      "Have you ever taken care of a pet, yours or someone else's?",
      "What would you need to start a pet-sitting business like Arthur's?"],
  h: ["아서는 어떤 일을 시작했나요?",
      "너는 네 반려동물이나 다른 사람의 반려동물을 돌본 적이 있나요?",
      "아서처럼 반려동물 돌보기 일을 시작하려면 무엇이 필요할지 적어 보세요."] };
ACT["M2097"] = { s: "Nancy loves to use fancy words and is proud to be the best speller in her class.  But when a spelling quiz is harder than Nancy thought, she is faced with a tough decision.",
  q: ["What was Nancy proud of being in her class?",
      "Have you ever faced a test that was harder than you expected?",
      "What fancy word do you like to use?"],
  h: ["낸시는 반에서 무엇을 잘한다고 자랑스러워했나요?",
      "너는 생각보다 어려운 시험을 본 적이 있나요?",
      "네가 좋아하는 멋진 단어를 한 가지 적어 보세요."] };
ACT["M2098"] = { s: "It's almost Class Picture Day. Robby is the only kid in his class with all his baby teeth. He writes a letter to the Tooth Fairy.",
  q: ["Who did Robby write a letter to?",
      "Have you ever lost a tooth?",
      "What would you write in a letter to the Tooth Fairy?"],
  h: ["로비는 누구에게 편지를 썼나요?",
      "너는 이가 빠진 적이 있나요?",
      "이빨 요정에게 편지를 쓴다면 무엇이라고 쓰고 싶나요?"] };
ACT["M2099"] = { s: "Little Critter chooses the best topic ever for his science project - caterpillars! Now he has to finish it in time for the big science fair.",
  q: ["What did Little Critter choose for his science project?",
      "Have you ever done a school project you were excited about?",
      "What would you choose for your own science project?"],
  h: ["리틀 크리터는 과학 프로젝트로 무엇을 골랐나요?",
      "너는 신나게 했던 학교 프로젝트가 있나요?",
      "네가 과학 프로젝트로 고르고 싶은 주제를 적어 보세요."] };
