// 간이 학습 질문 — Book No. M22 묶음. 사람이 아니라 AI 가 한 번 쓰고 굳힌 파일이다.
window.ACT = window.ACT || {};
var ACT = window.ACT;
ACT["M2200"] = { s: "A very literal-minded housekeeper Amelia is in charge of a surprise wedding shower. She gets mixed up and turns the entire party into an uproarious mess.",
  q: ["What mistake did Amelia Bedelia make that seemed the funniest to you?",
      "Have you ever misunderstood what someone asked you to do?",
      "If you were planning a surprise party, what would you be careful about?"],
  h: ["아멜리아 베델리아가 한 실수 중에 가장 웃겼던 건 무엇이었나요?",
      "누군가의 부탁을 잘못 이해한 적이 있나요?",
      "네가 깜짝 파티를 계획한다면 무엇을 조심하고 싶나요?"] };
ACT["M2201"] = { s: "This book presents two simple stories about very noisy neighbors who finally compromise to get along with one another.",
  q: ["What do you think the neighbors were doing that made so much noise?",
      "Have you ever had a noisy neighbor or heard a loud noise from next door?",
      "What would you say to a neighbor who is too noisy?"],
  h: ["이웃들이 무엇을 해서 그렇게 시끄러웠을 것 같나요?",
      "시끄러운 이웃이 있거나 옆집에서 큰 소리를 들어본 적이 있나요?",
      "너무 시끄러운 이웃에게 뭐라고 말하고 싶나요?"] };
ACT["M2202"] = { s: "Nate the Great goes to San Francisco where he solves a mystery for his cousin Olivia, who is also a detective.",
  q: ["What clues do you think Nate used to solve the mystery?",
      "Have you ever tried to solve a mystery or find something that was lost?",
      "If you were a detective, what case would you want to solve?"],
  h: ["네이트는 어떤 단서를 써서 수수께끼를 풀었을 것 같나요?",
      "잃어버린 것을 찾거나 수수께끼를 풀어본 적이 있나요?",
      "네가 탐정이라면 어떤 사건을 풀어보고 싶나요?"] };
ACT["M2203"] = { s: "Did you know that snakes pick up smells with their tongues? This book describes fun and fantastic facts about snakes.",
  q: ["What fact about snakes did you find the most surprising?",
      "Have you ever seen a snake in real life or at a zoo?",
      "What is one question you still want to know about snakes?"],
  h: ["뱀에 대한 사실 중에 가장 놀라웠던 것은 무엇인가요?",
      "실제로나 동물원에서 뱀을 본 적이 있나요?",
      "뱀에 대해 더 알고 싶은 것을 한 가지 적어보세요."] };
ACT["M2204"] = { s: "In this book, Captain Pepper and his crew go on an adventure in search of the perfect pirate pet.",
  q: ["What kind of pet do you think would make a good pirate pet?",
      "Do you have a pet, or what pet would you like to have?",
      "If you went on a pirate adventure, what animal would you bring with you?"],
  h: ["어떤 동물이 좋은 해적의 반려동물이 될 것 같나요?",
      "너는 반려동물이 있나요, 아니면 어떤 반려동물을 키우고 싶나요?",
      "네가 해적 모험을 떠난다면 어떤 동물을 데려가고 싶나요?"] };
ACT["M2205"] = { s: "When a dragon threatens to disrupt the life of the townspeople, a little girl challenges the scaly creature to a math match.",
  q: ["What do you think happened during the math match with the dragon?",
      "Do you like math? What kind of math problems do you enjoy?",
      "If you had to challenge a dragon to a game, what game would you choose?"],
  h: ["용과의 수학 대결에서 무슨 일이 일어났을 것 같나요?",
      "너는 수학을 좋아하나요? 어떤 수학 문제를 좋아하나요?",
      "네가 용에게 게임으로 도전한다면 어떤 게임을 고르고 싶나요?"] };
ACT["M2206"] = { s: "History comes to life on the page as readers learn the story of the Pilgrims hosting the first Thanksgiving.",
  q: ["What did the Pilgrims do to celebrate the first Thanksgiving?",
      "What do you do with your family on Thanksgiving or a special holiday?",
      "What food would you want to eat at a Thanksgiving feast?"],
  h: ["청교도들은 첫 추수감사절을 어떻게 기념했나요?",
      "너는 추수감사절이나 특별한 명절에 가족과 무엇을 하나요?",
      "추수감사절 잔치에서 네가 먹고 싶은 음식은 무엇인가요?"] };
ACT["M2207"] = { s: "Deep in the swamp, a baby alligator crawls out of its broken shell. This book presents the early months in the life of a newborn alligator. Let's follow it through its first adventures.",
  q: ["What did the baby alligator do in its first months?",
      "Have you ever seen a baby animal? What was it like?",
      "What baby animal would you like to learn more about?"],
  h: ["아기 악어는 태어난 후 처음 몇 달 동안 무엇을 했나요?",
      "아기 동물을 본 적이 있나요? 어땠나요?",
      "더 알고 싶은 아기 동물을 한 가지 적어보세요."] };
ACT["M2208"] = { s: "Thelma and Frances are friends, although Thelma often puts Frances into trouble. When she tricks Frances into buying her tea set, Frances decides to teach her a lesson about friendship.",
  q: ["What trick did Thelma play on Frances?",
      "Has a friend ever tricked you or treated you unfairly?",
      "What would you do if a friend tricked you like Thelma did?"],
  h: ["델마는 프랜시스에게 어떤 속임수를 썼나요?",
      "친구가 너를 속이거나 불공평하게 대한 적이 있나요?",
      "델마처럼 친구가 너를 속인다면 너는 어떻게 하겠나요?"] };
ACT["M2209"] = { s: "Miles and the Swamp Band are a big hit at the Alligator Ball, but is it the music or the band that the alligators find interesting? How will Miles get out of the woods?",
  q: ["What do you think the alligators liked most, the music or the band?",
      "Have you ever played music or listened to a band you liked?",
      "If you were in Miles's band, what instrument would you want to play?"],
  h: ["악어들은 음악과 밴드 중에 무엇을 더 좋아했을 것 같나요?",
      "음악을 연주하거나 좋아하는 밴드의 노래를 들어본 적이 있나요?",
      "네가 마일즈의 밴드에 있다면 어떤 악기를 연주하고 싶나요?"] };
ACT["M2210"] = { s: "Nate and his dog Sludge solve a case on Halloween night and find themselves locked in a haunted house.",
  q: ["What do you think Nate found inside the haunted house?",
      "Have you ever been to a place that felt spooky or scary?",
      "What would you do if you got locked in a haunted house?"],
  h: ["네이트는 유령의 집 안에서 무엇을 찾았을 것 같나요?",
      "무섭거나 으스스하게 느껴지는 곳에 가본 적이 있나요?",
      "네가 유령의 집에 갇힌다면 어떻게 하겠나요?"] };
ACT["M2211"] = { s: "In this exciting book, kids will learn about the physical characteristics, behavior, and habitats of different kinds of bats.",
  q: ["What did you learn about how bats live?",
      "Have you ever seen a bat, in real life or in a picture?",
      "What is one thing you would like to ask about bats?"],
  h: ["박쥐가 어떻게 사는지에 대해 무엇을 알게 되었나요?",
      "실제로나 사진으로 박쥐를 본 적이 있나요?",
      "박쥐에 대해 물어보고 싶은 것을 한 가지 적어보세요."] };
ACT["M2212"] = { s: "This book tells of Thomas Jefferson's trip to France in 1784 and all the exotic foods he learned about and then introduced to America, including ice cream, macaroni and cheese, and tomatoes.",
  q: ["Which food that Thomas Jefferson brought to America do you like the most?",
      "Have you ever tried ice cream, macaroni and cheese, or tomatoes?",
      "What new food would you like to try someday?"],
  h: ["토마스 제퍼슨이 미국에 소개한 음식 중에 가장 좋아하는 것은 무엇인가요?",
      "아이스크림, 마카로니 앤 치즈, 토마토를 먹어본 적이 있나요?",
      "언젠가 먹어보고 싶은 새로운 음식을 적어보세요."] };
ACT["M2213"] = { s: "When Mary comes to live in a lonely house on the Yorkshire moors, she discovers an invalid cousin.",
  q: ["Who do you think Mary discovered in the lonely house?",
      "Have you ever moved to a new place or visited somewhere unfamiliar?",
      "If you found a secret garden, what would you want to do there?"],
  h: ["메리는 외딴 집에서 누구를 발견했을 것 같나요?",
      "새로운 곳으로 이사하거나 낯선 곳을 방문한 적이 있나요?",
      "네가 비밀의 정원을 찾는다면 그곳에서 무엇을 하고 싶나요?"] };
ACT["M2214"] = { s: "This book follows the journey of a humpback whale as he swims from the Caribbean Sea to the far north of the Atlantic Ocean.",
  q: ["What do you think the humpback whale saw on its long journey?",
      "Have you ever been on a long trip or journey?",
      "Where would you like to travel if you could swim like a whale?"],
  h: ["혹등고래는 긴 여행에서 무엇을 보았을 것 같나요?",
      "긴 여행을 떠나본 적이 있나요?",
      "네가 고래처럼 헤엄칠 수 있다면 어디로 여행하고 싶나요?"] };
ACT["M2215"] = { s: "Mr. and Mrs. Rogers need to prepare for Great-Aunt Myra's visit. A very literal-minded housekeeper Amelia follows their instructions with humorous results.",
  q: ["What funny thing do you think Amelia Bedelia did while preparing for the visit?",
      "Have you ever helped your family get ready for a guest?",
      "If a guest were coming to your house, what would you do to prepare?"],
  h: ["아멜리아 베델리아는 방문을 준비하면서 어떤 웃긴 일을 했을 것 같나요?",
      "손님을 맞이하기 위해 가족을 도와본 적이 있나요?",
      "손님이 너희 집에 온다면 무엇을 준비하고 싶나요?"] };
ACT["M2216"] = { s: "Sara is a girl who has everything. She goes to Miss Minchin's London school. But her life changes after her father dies. Now, she is left in poverty.",
  q: ["How do you think Sara's life changed after her father died?",
      "Has something ever happened that changed your life in a big way?",
      "If you were Sara, how would you try to stay hopeful?"],
  h: ["아버지가 돌아가신 후 사라의 삶은 어떻게 바뀌었을 것 같나요?",
      "네 삶을 크게 바꾼 일이 있었나요?",
      "네가 사라라면 어떻게 희망을 잃지 않으려 할 것 같나요?"] };
ACT["M2217"] = { s: "This book describes facts about penguins and details about the lives of emperor penguins.",
  q: ["What fact about emperor penguins did you find most interesting?",
      "Have you ever seen a penguin, at a zoo or in a video?",
      "What would you like to ask an emperor penguin if you could?"],
  h: ["황제펭귄에 대한 사실 중에 가장 흥미로웠던 것은 무엇인가요?",
      "동물원이나 영상에서 펭귄을 본 적이 있나요?",
      "황제펭귄에게 물어볼 수 있다면 무엇을 물어보고 싶나요?"] };
ACT["M2218"] = { s: "Nate has to solve the riddle of Rosamond's strange poem in order to find Annie's missing house key.",
  q: ["What do you think the riddle in Rosamond's poem meant?",
      "Have you ever lost a key or something important?",
      "How would you solve a riddle to find something you lost?"],
  h: ["로자먼드의 시에 담긴 수수께끼는 무슨 뜻이었을 것 같나요?",
      "열쇠나 중요한 물건을 잃어버린 적이 있나요?",
      "잃어버린 것을 찾기 위해 수수께끼를 어떻게 풀어보겠나요?"] };
ACT["M2219"] = { s: "Mouldylocks, a giant, decides it is time for him to find himself a good wife. He puts three Clares- Great Big Clare, Tiny Wee Clare, and Medium-sized Clare- to the test, in turn, to see who might be the right one.",
  q: ["How do you think Mouldylocks tested the three Clares?",
      "Have you ever had to choose between three things or people?",
      "What quality would you look for in a good friend?"],
  h: ["몰디락스는 세 명의 클레어를 어떻게 시험해봤을 것 같나요?",
      "셋 중에서 하나를 골라야 했던 적이 있나요?",
      "좋은 친구에게서 어떤 점을 찾고 싶나요?"] };
ACT["M2220"] = { s: "This book describes the fateful days in 79 A.D. when Mt. Vesuvius erupted and the people of Pompeii perished.",
  q: ["What do you think happened to the people of Pompeii when the volcano erupted?",
      "Have you ever learned about a volcano or seen one in a picture?",
      "What would you do if you saw a volcano starting to erupt?"],
  h: ["화산이 폭발했을 때 폼페이 사람들에게 무슨 일이 일어났을 것 같나요?",
      "화산에 대해 배우거나 사진으로 본 적이 있나요?",
      "화산이 폭발하기 시작하는 걸 본다면 너는 어떻게 하겠나요?"] };
