// 간이 학습 질문 — Book No. M30 묶음. 사람이 아니라 AI 가 한 번 쓰고 굳힌 파일이다.
window.ACT = window.ACT || {};
var ACT = window.ACT;   // catalog.js 와 같은 다리: Node(check-act.js)의 Function 가짜 window 에서는 window.ACT 를 쓰고 그냥 ACT 는 못 쓴다
ACT["M3001"] = { s: "George goes to the animal shelter and sees cute puppies. He accidentally lets all the dogs out of their cages when he tries to pet them.",
  q: ["What did George accidentally do when he tried to pet the puppies?",
      "Have you ever visited an animal shelter or seen puppies up close?",
      "What would you do if all the dogs got out of their cages?"],
  h: ["조지가 강아지를 쓰다듬으려다가 실수로 무엇을 했나요?",
      "너는 동물 보호소에 가 보거나 강아지를 가까이서 본 적이 있나요?",
      "강아지들이 모두 우리에서 나왔다면 너는 어떻게 하겠나요?"] };
ACT["M3002"] = { s: "Marvin Redpost has long been wondering why he doesn't look like anyone in his family. Now he has the answer. He's Robert-the prince kidnapped at birth.",
  q: ["Why has Marvin been wondering about his family?",
      "Have you ever wondered if you look like someone in your family?",
      "What would you think if you found out you were a prince?"],
  h: ["마빈은 왜 오랫동안 궁금해했나요?",
      "너는 가족 중 누군가와 닮았는지 궁금했던 적이 있나요?",
      "네가 왕자라는 사실을 알게 된다면 어떤 기분일까요?"] };
ACT["M3003"] = { s: "From a one-inch baby rabbit to a 100-pound baby rhinoceros, baby animals are shown through spectacular photos, while readers learn fascinating facts about these animals' young in the wild.",
  q: ["Which baby animal in the book do you remember best?",
      "Have you ever seen a baby animal in real life?",
      "Which baby animal would you like to learn more about?"],
  h: ["이 책에 나온 아기 동물 중에 가장 기억에 남는 동물은 무엇인가요?",
      "너는 실제로 아기 동물을 본 적이 있나요?",
      "네가 더 알고 싶은 아기 동물은 무엇인가요?"] };
ACT["M3004"] = { s: "Big mean Bertha bullies everyone, especially Billie. But when Billie gets a dog, the tables are turned.",
  q: ["What changed for Billie after she got a dog?",
      "Have you ever felt scared of someone who was mean to you?",
      "What would you do if a bully was bothering your friend?"],
  h: ["빌리가 강아지를 얻은 뒤 무엇이 달라졌나요?",
      "너는 너에게 못되게 구는 사람 때문에 무서웠던 적이 있나요?",
      "친구를 괴롭히는 사람이 있다면 너는 어떻게 하겠나요?"] };
ACT["M3005"] = { s: "Zack takes home a scruffy cat from the animal shelter, who talks and claims to be reincarnation of Zack's grandfather.",
  q: ["What does the cat that Zack brings home claim to be?",
      "Have you ever had a pet that felt like part of your family?",
      "What would you say to a cat if it could really talk to you?"],
  h: ["잭이 데려온 고양이는 자신이 무엇이라고 주장하나요?",
      "너는 가족처럼 느껴지는 반려동물을 키워 본 적이 있나요?",
      "고양이가 정말 말을 할 수 있다면 너는 무엇을 물어보고 싶나요?"] };
ACT["M3006"] = { s: "Alice the anteater wants to become a film star in Hollywood. She leaves the jungle to pursue her dream.",
  q: ["What does Alice the anteater want to become?",
      "Have you ever had a big dream you wanted to follow?",
      "What would you leave behind to follow your dream?"],
  h: ["개미핥기 앨리스는 무엇이 되고 싶어 하나요?",
      "너는 꼭 이루고 싶은 큰 꿈이 있었나요?",
      "네 꿈을 이루기 위해 무엇을 남겨두고 떠날 수 있나요?"] };
ACT["M3007"] = { s: "Roscoe Riley comes up with a plan to keep the bee antennae on the first graders' heads and help the drummers stay in their seats for the open house performance.",
  q: ["What plan does Roscoe come up with for the performance?",
      "Have you ever been in a school performance or show?",
      "What plan would you make to help your class in a show?"],
  h: ["로스코는 공연을 위해 어떤 계획을 세웠나요?",
      "너는 학교 공연이나 발표회에 나가 본 적이 있나요?",
      "너라면 반 친구들을 도우려고 어떤 계획을 세우겠나요?"] };
ACT["M3008"] = { s: "SpongeBob can't wait for his six-month checkup at the dentist. That morning he discovers not only has Patrick never gone to the dentist, but he's never even brushed his teeth.",
  q: ["What does SpongeBob discover about Patrick that morning?",
      "Do you go to the dentist for a checkup?",
      "What would you tell Patrick about brushing his teeth?"],
  h: ["스폰지밥은 그날 아침 패트릭에 대해 무엇을 알게 되었나요?",
      "너는 치과에 가서 검진을 받아 본 적이 있나요?",
      "패트릭에게 양치질에 대해 무엇이라고 말해 주고 싶나요?"] };
ACT["M3009"] = { s: "Freddy hates being the middle kid in the family. But he gets a part in the school play and shows everyone how special he is.",
  q: ["What does Freddy get that shows he is special?",
      "Are you the oldest, the middle, or the youngest in your family?",
      "What is one thing that makes you special?"],
  h: ["프레디는 무엇을 받게 되어 자신이 특별하다는 것을 보여 주었나요?",
      "너는 가족 중에서 첫째, 둘째, 아니면 막내인가요?",
      "너를 특별하게 만드는 한 가지는 무엇인가요?"] };
ACT["M3010"] = { s: "Nine-year-old Gregory paints pictures representing the life of the Mexican American old man known as Uncle Pancho and attempts to save his house.",
  q: ["What does Gregory paint pictures about?",
      "Have you ever tried to help someone with a painting or drawing?",
      "What would you paint to help someone you care about?"],
  h: ["그레고리는 무엇에 대한 그림을 그렸나요?",
      "너는 그림으로 누군가를 도와준 적이 있나요?",
      "네가 아끼는 사람을 돕기 위해 어떤 그림을 그리고 싶나요?"] };
ACT["M3011"] = { s: "This book introduces the environment and endangered animals.",
  q: ["What kind of animals does this book introduce?",
      "Have you heard of an animal that is endangered?",
      "What would you do to help protect an endangered animal?"],
  h: ["이 책은 어떤 동물을 소개하나요?",
      "너는 멸종 위기에 처한 동물에 대해 들어 본 적이 있나요?",
      "멸종 위기 동물을 지키기 위해 너는 무엇을 하고 싶나요?"] };
ACT["M3012"] = { s: "A band of monkeys steals a street vendor's caps while he is asleep.",
  q: ["What do the monkeys steal from the street vendor?",
      "Have you ever fallen asleep somewhere you didn't plan to?",
      "What would you do if monkeys stole your things?"],
  h: ["원숭이들은 거리 상인에게서 무엇을 훔쳤나요?",
      "너는 계획하지 않은 곳에서 잠든 적이 있나요?",
      "원숭이들이 네 물건을 훔쳐 갔다면 너는 어떻게 하겠나요?"] };
ACT["M3013"] = { s: "This book is a time-travel fantasy in which two children named Jack and Annie encounter dinosaurs when their magic tree house whisks them to the prehistoric past. Book #1",
  q: ["Who do Jack and Annie meet when the tree house takes them to the past?",
      "Have you ever imagined traveling back in time?",
      "If you had a magic tree house, where would you want to go?"],
  h: ["매직 트리 하우스가 잭과 애니를 과거로 데려갔을 때 누구를 만났나요?",
      "너는 시간을 거슬러 여행하는 상상을 해 본 적이 있나요?",
      "네게 마법의 나무집이 있다면 어디로 가고 싶나요?"] };
ACT["M3014"] = { s: "How do we learn about the world around us? One good way is to use our senses. Our senses give us five different ways to explore the world.",
  q: ["How many senses does this book say we have?",
      "Which of your senses do you use the most every day?",
      "What is something you like to see, hear, or smell?"],
  h: ["이 책에서 우리에게 몇 가지 감각이 있다고 했나요?",
      "너는 매일 어떤 감각을 가장 많이 쓰나요?",
      "네가 보거나 듣거나 냄새 맡기 좋아하는 것은 무엇인가요?"] };
ACT["M3015"] = { s: "Bobby is a shy boy until he gets a beagle puppy named Lucy, who helps him to make new friends.",
  q: ["How does Lucy help Bobby?",
      "Have you ever felt shy about making new friends?",
      "What would help you make a new friend?"],
  h: ["루시는 보비를 어떻게 도와주나요?",
      "너는 새 친구를 사귀는 게 부끄러웠던 적이 있나요?",
      "새 친구를 사귀는 데 무엇이 도움이 될까요?"] };
ACT["M3016"] = { s: "This book explains what the sun is, where it is located in the universe, what it is made of, and its importance to life on Earth.",
  q: ["What does this book explain about the sun?",
      "Have you ever looked up at the sun or felt its warmth?",
      "What do you want to know more about the sun?"],
  h: ["이 책은 태양에 대해 무엇을 설명하나요?",
      "너는 태양을 올려다보거나 따뜻함을 느껴 본 적이 있나요?",
      "태양에 대해 더 알고 싶은 것은 무엇인가요?"] };
ACT["M3017"] = { s: "This book describes the loss of the 'unsinkable' palace and the recent discovery of its wreckage.",
  q: ["What does this book describe about the Titanic?",
      "Have you ever heard the story of the Titanic before?",
      "What would you like to know about the Titanic?"],
  h: ["이 책은 타이타닉호에 대해 무엇을 설명하나요?",
      "너는 타이타닉호 이야기를 들어 본 적이 있나요?",
      "타이타닉호에 대해 더 알고 싶은 것은 무엇인가요?"] };
ACT["M3018"] = { s: "George tries making pancakes at a fundraiser for the children's hospital, and he causes quite a stir.",
  q: ["What does George try to make at the fundraiser?",
      "Have you ever tried cooking or baking something?",
      "What would you like to cook for a fundraiser?"],
  h: ["조지는 모금 행사에서 무엇을 만들려고 했나요?",
      "너는 요리나 빵을 만들어 본 적이 있나요?",
      "모금 행사를 위해 너는 무엇을 만들고 싶나요?"] };
ACT["M3019"] = { s: "The class learns how plants grow when they go on a field trip to Phoebe's old school.",
  q: ["What does the class learn on their field trip?",
      "Have you ever planted a seed or grown a plant?",
      "What plant would you like to grow?"],
  h: ["학생들은 현장 학습에서 무엇을 배웠나요?",
      "너는 씨앗을 심거나 식물을 키워 본 적이 있나요?",
      "네가 키워 보고 싶은 식물은 무엇인가요?"] };
ACT["M3020"] = { s: "A duck-hunting family learns a lesson when an eight-year-old girl turns her magic finger on them.",
  q: ["What does the eight-year-old girl use on the duck-hunting family?",
      "Have you ever felt bad for an animal that was being hunted or hurt?",
      "If you had a magic finger, what lesson would you teach someone?"],
  h: ["여덟 살 여자아이는 오리 사냥 가족에게 무엇을 사용했나요?",
      "너는 사냥당하거나 다친 동물을 보고 안타까웠던 적이 있나요?",
      "너에게 마법의 손가락이 있다면 누구에게 어떤 교훈을 주고 싶나요?"] };
ACT["M3021"] = { s: "Some sharks can bite 300 times harder than a person and can hear prey in the water from 3,000 feet away. Find out these impressive hunters, from the tiny pygmy shark to the giant whale shark.",
  q: ["How much harder can some sharks bite than a person?",
      "Have you ever seen a shark in real life or in an aquarium?",
      "Which shark from the book would you like to learn more about?"],
  h: ["어떤 상어는 사람보다 몇 배나 세게 물 수 있나요?",
      "너는 실제로나 수족관에서 상어를 본 적이 있나요?",
      "이 책에 나온 상어 중에 더 알고 싶은 상어는 무엇인가요?"] };
ACT["M3022"] = { s: "Emily Clark just moved. She doesn't like her new house. She doesn't like her new town. Then one night she wakes up to find a horse in her backyard?a ghost horse!",
  q: ["What does Emily find in her backyard one night?",
      "Have you ever moved to a new house or town?",
      "What would you do if you found a horse in your backyard?"],
  h: ["에밀리는 어느 날 밤 마당에서 무엇을 발견했나요?",
      "너는 새로운 집이나 동네로 이사한 적이 있나요?",
      "마당에서 말을 발견한다면 너는 어떻게 하겠나요?"] };
ACT["M3023"] = { s: "Monsters are supposed to misbehave. But Rosie plays nicely with everyone and teaches her family that good manners do come in handy.",
  q: ["What does Rosie teach her family?",
      "Have you ever used good manners to help someone?",
      "What good manners do you try to use every day?"],
  h: ["로지는 가족에게 무엇을 가르쳐 주었나요?",
      "너는 예의 바른 행동으로 누군가를 도와준 적이 있나요?",
      "너는 평소 어떤 예의 바른 행동을 하려고 노력하나요?"] };
ACT["M3024"] = { s: "This introduction to solids explains how they are different from liquids and gases, describes how solids can change, and discusses the different forms of matter.",
  q: ["What does this book explain about solids?",
      "Can you name something solid you can see around you right now?",
      "What is one solid thing you would like to learn more about?"],
  h: ["이 책은 고체에 대해 무엇을 설명하나요?",
      "지금 네 주변에서 고체인 것을 하나 말할 수 있나요?",
      "네가 더 알고 싶은 고체는 무엇인가요?"] };
ACT["M3025"] = { s: "In this book, Bertie tries to prove the grumpy school custodian is a vampire.",
  q: ["What does Bertie try to prove about the school custodian?",
      "Have you ever thought someone might be something they are not?",
      "What would you do to prove your idea about someone?"],
  h: ["버티는 학교 관리인에 대해 무엇을 증명하려고 했나요?",
      "너는 누군가가 사실 다른 무언가라고 생각해 본 적이 있나요?",
      "네 생각을 증명하려면 너는 무엇을 하겠나요?"] };
ACT["M3026"] = { s: "When a lonely little beaver hears someone else crying on the other side of the pond, he begins his touching quest for a friend.",
  q: ["What does the little beaver hear on the other side of the pond?",
      "Have you ever felt lonely and wished for a friend?",
      "What would you do to find a new friend?"],
  h: ["작은 비버는 연못 건너편에서 무엇을 들었나요?",
      "너는 외로워서 친구를 바랐던 적이 있나요?",
      "새 친구를 찾기 위해 너는 무엇을 하겠나요?"] };
ACT["M3027"] = { s: "It's Halloween. The third-graders in Miss Mackle's class enjoy a day of Halloween surprises, including Harry's unusual costume.",
  q: ["What does Harry wear that surprises his classmates?",
      "Have you ever worn a costume for Halloween?",
      "What costume would you like to wear?"],
  h: ["해리는 친구들을 놀라게 한 어떤 옷을 입었나요?",
      "너는 할로윈에 분장을 해 본 적이 있나요?",
      "네가 입고 싶은 분장은 무엇인가요?"] };
ACT["M3028"] = { s: "The class is learning all about water and then get to take a field trip through the water cycle.",
  q: ["What does the class take a field trip through?",
      "Have you ever seen rain, snow, or a river?",
      "What part of the water cycle would you like to see up close?"],
  h: ["학생들은 현장 학습으로 무엇을 통과해 여행했나요?",
      "너는 비, 눈, 혹은 강을 본 적이 있나요?",
      "물의 순환 중에서 가까이 보고 싶은 부분은 무엇인가요?"] };
ACT["M3029"] = { s: "Roscoe cannot wait to tap dance in the school talent show until some older boys make fun of him and he questions whether tap dancing is just for girls.",
  q: ["What do the older boys do that makes Roscoe question tap dancing?",
      "Have you ever been made fun of for something you liked to do?",
      "What would you say to someone who makes fun of what you like?"],
  h: ["나이 많은 남자아이들이 무엇을 해서 로스코가 탭댄스에 의문을 품게 되었나요?",
      "너는 좋아하는 것 때문에 놀림을 받은 적이 있나요?",
      "네가 좋아하는 것을 놀리는 사람에게 너는 무엇이라고 말하고 싶나요?"] };
ACT["M3030"] = { s: "Christmas is coming and SpongeBob follows Mr. Krabs's order to decorate, putting up light after light, until the power goes out.",
  q: ["What happens after SpongeBob puts up light after light?",
      "Have you ever helped decorate for a holiday?",
      "What decoration would you like to put up for Christmas?"],
  h: ["스폰지밥이 전등을 계속 달자 무슨 일이 일어났나요?",
      "너는 명절을 위해 장식을 도와준 적이 있나요?",
      "크리스마스를 위해 네가 달고 싶은 장식은 무엇인가요?"] };
ACT["M3031"] = { s: "Andrew, who desperately wants to have freckles, uses a \"freckle juice\" recipe offered by his classmate Sharon.",
  q: ["What does Andrew want to have, and what does he use to try to get it?",
      "Have you ever wanted to look like someone else?",
      "What is something about yourself you like just the way it is?"],
  h: ["앤드류는 무엇을 갖고 싶어 했고, 그것을 얻으려고 무엇을 사용했나요?",
      "너는 다른 사람처럼 보이고 싶었던 적이 있나요?",
      "지금 그대로 좋아하는 네 모습 한 가지는 무엇인가요?"] };
ACT["M3032"] = { s: "George runs away from the zoo out of curiosity. He explores the big city, takes a job washing window, and ends up a movie star.",
  q: ["What job does George take in the big city?",
      "Have you ever explored a new place out of curiosity?",
      "What job would you like to try if you were curious like George?"],
  h: ["조지는 큰 도시에서 어떤 일을 하게 되나요?",
      "너는 호기심 때문에 새로운 곳을 탐험해 본 적이 있나요?",
      "조지처럼 호기심이 생긴다면 너는 어떤 일을 해 보고 싶나요?"] };
ACT["M3033"] = { s: "Francine's hand-me-down bike is stolen. Arthur and his friends all help to find the thief.",
  q: ["What do Arthur and his friends help Francine find?",
      "Have you ever lost or had something of yours go missing?",
      "What would you do to help a friend find something stolen?"],
  h: ["아서와 친구들은 프랜신을 도와 무엇을 찾으려고 했나요?",
      "너는 물건을 잃어버리거나 없어진 적이 있나요?",
      "도둑맞은 물건을 찾는 친구를 도우려면 너는 무엇을 하겠나요?"] };
ACT["M3034"] = { s: "This book tells how and why some animals can grow new body parts.",
  q: ["What does this book explain about some animals?",
      "Have you ever seen an animal lose or grow back a body part?",
      "Which animal would you like to learn can grow new body parts?"],
  h: ["이 책은 어떤 동물에 대해 무엇을 설명하나요?",
      "너는 동물이 몸의 일부를 잃거나 다시 자라는 것을 본 적이 있나요?",
      "새로운 몸의 부분을 만들 수 있다는 동물에 대해 더 알고 싶은 것은 무엇인가요?"] };
ACT["M3035"] = { s: "Unhappy to be the only one in his class who still has not lost a tooth, first-grader Freddy tries to find a way to solve the problems but then is faced with another problem.",
  q: ["Why is Freddy unhappy at the start of the book?",
      "Have you ever lost a tooth?",
      "What would you do to solve Freddy's problem?"],
  h: ["프레디는 왜 이야기 처음에 속상해했나요?",
      "너는 이가 빠져 본 적이 있나요?",
      "프레디의 문제를 풀기 위해 너라면 무엇을 하겠나요?"] };
ACT["M3036"] = { s: "Pinky learns the importance of identity as he defends his favorite color, pink, and his friendship with a girl, Rex, from the neighborhood bully.",
  q: ["What two things does Pinky defend in this book?",
      "Have you ever had to stand up for something you like?",
      "What would you say to someone who teases you for what you like?"],
  h: ["핑키는 이 책에서 무엇 두 가지를 지켜 냈나요?",
      "너는 네가 좋아하는 것을 지켜야 했던 적이 있나요?",
      "네가 좋아하는 것을 놀리는 사람에게 너는 무엇이라고 말하고 싶나요?"] };
ACT["M3037"] = { s: "When Cousin Odd Todd arrives, he upsets Even Steven, who likes everything to come in even numbers. This book includes activities and games.",
  q: ["What does Even Steven like everything to come in?",
      "Do you like even numbers or odd numbers better?",
      "What is something you like to count in your daily life?"],
  h: ["이븐 스티븐은 모든 것이 어떤 숫자로 오는 것을 좋아하나요?",
      "너는 짝수와 홀수 중 어떤 것을 더 좋아하나요?",
      "너는 평소 무엇을 세는 것을 좋아하나요?"] };
ACT["M3038"] = { s: "The magic tree house whisks Jack and Annie off deep into the ocean. When they are searching for the answer to the riddle, they encounter a starving shark and a giant octopus. Will Jack and Annie end up being dinner? Or will the dolphins save the day? Book #9",
  q: ["What two sea creatures do Jack and Annie encounter in the ocean?",
      "Have you ever seen dolphins, sharks, or an octopus?",
      "What would you do if you met a giant octopus in the ocean?"],
  h: ["잭과 애니는 바닷속에서 어떤 두 생물을 만나나요?",
      "너는 돌고래, 상어, 문어를 본 적이 있나요?",
      "바닷속에서 거대한 문어를 만난다면 너는 어떻게 하겠나요?"] };
ACT["M3039"] = { s: "A witch finds room on her broom for all the animals that ask for a ride, and they repay her kindness by saving her from a dragon.",
  q: ["How do the animals repay the witch's kindness?",
      "Have you ever shared something of yours with others?",
      "What would you do to repay someone's kindness?"],
  h: ["동물들은 마녀의 친절에 어떻게 보답했나요?",
      "너는 네 것을 다른 사람과 나눠 본 적이 있나요?",
      "누군가의 친절에 보답하려면 너는 무엇을 하겠나요?"] };
ACT["M3040"] = { s: "Dink writes to his favorite author, mystery writer Wallis Wallace, and invites him to visit Green Lawn. When the big day arrives, Wallace is nowhere to be found. Dink and his friends start to investigate the apparent kidnapping.",
  q: ["Who does Dink invite to visit Green Lawn?",
      "Have you ever written a letter to someone you admire?",
      "What would you do first if you were investigating a mystery like Dink?"],
  h: ["딩크는 누구를 그린 론에 초대했나요?",
      "너는 존경하는 사람에게 편지를 써 본 적이 있나요?",
      "딩크처럼 사건을 조사한다면 너는 먼저 무엇을 하겠나요?"] };
ACT["M3041"] = { s: "This book provides information about the planets in Earth's solar system, discussing their size, how they move, and their location in relation to the sun.",
  q: ["What does this book tell you about the planets?",
      "Have you ever looked up at the night sky and thought about planets?",
      "Which planet would you like to learn more about?"],
  h: ["이 책은 행성에 대해 무엇을 알려 주나요?",
      "너는 밤하늘을 보며 행성을 생각해 본 적이 있나요?",
      "네가 더 알고 싶은 행성은 무엇인가요?"] };
ACT["M3042"] = { s: "Stephen, who is crazy about cereal, participates in a competition to design a new cereal. His entry, Brick-a-Breck, wins him a prize, and he even becomes a TV celebrity.",
  q: ["Stephen designs a brand-new cereal for a competition. If you could design your own cereal, what would you name it, what would be inside it, and why do you think people would want to eat it? Write a few sentences about your invention.",
      "Think about a contest or competition you have joined or watched, like a school contest or a cooking show. What was it like to compete or to watch, and how did you feel about winning or losing?",
      "Stephen becomes a TV celebrity because of his cereal idea. Do you think being famous for something you made would be exciting or stressful? Explain your thinking with your own reasons."],
  h: ["스티븐은 대회를 위해 완전히 새로운 시리얼을 만들었어요. 네가 시리얼을 만든다면 이름은 무엇으로 짓고, 안에 무엇을 넣고, 사람들이 왜 먹고 싶어 할지 몇 문장으로 적어 보세요.",
      "학교 대회나 요리 프로그램처럼 네가 참가하거나 지켜본 대회를 떠올려 보세요. 참가하거나 지켜볼 때 어땠고, 이기거나 졌을 때 기분이 어땠는지 적어 보세요.",
      "스티븐은 시리얼 아이디어로 TV 스타가 되었어요. 네가 만든 것 때문에 유명해진다면 신날 것 같은지 아니면 부담스러울 것 같은지, 그렇게 생각하는 이유와 함께 적어 보세요."] };
ACT["M3043"] = { s: "A jewelry store in town has been robbed. Cam and her friend Eric believe the police have caught an innocent man. They decide to take the situation into their own hands and find out who robbed the jewelry store.",
  q: ["What do Cam and Eric believe about the man the police caught?",
      "Have you ever thought someone was wrongly blamed for something?",
      "What would you do to prove someone is innocent?"],
  h: ["캠과 에릭은 경찰이 잡은 남자에 대해 무엇이라고 생각했나요?",
      "너는 누군가 억울하게 혼나는 것을 본 적이 있나요?",
      "누군가 무죄라는 것을 증명하려면 너는 무엇을 하겠나요?"] };
ACT["M3044"] = { s: "One fine day a fox travels into the woods. To fulfill his thirst, this jaunty red fox steals milk from an old farm woman.",
  q: ["What does the fox steal to fulfill his thirst?",
      "Have you ever taken something without asking?",
      "What would you say to the fox about taking the milk?"],
  h: ["여우는 목을 축이려고 무엇을 훔쳤나요?",
      "너는 허락 없이 무언가를 가져간 적이 있나요?",
      "우유를 가져간 여우에게 너는 무엇이라고 말해 주고 싶나요?"] };
ACT["M3045"] = { s: "Zack starts turning into a cat when the spirit of an ancient Egyptian cat goddess is accidentally transferred into his body.",
  q: ["What starts happening to Zack in this book?",
      "Have you ever imagined turning into an animal?",
      "What animal would you like to turn into and why?"],
  h: ["이 책에서 잭에게 어떤 일이 일어나기 시작하나요?",
      "너는 동물로 변하는 상상을 해 본 적이 있나요?",
      "네가 변하고 싶은 동물은 무엇이고 그 이유는 무엇인가요?"] };
ACT["M3046"] = { s: "Excited about holding onto his position as the best speller in the second grade, Pinky has an embarrassing accident but is cheered up by his best friend Rex.",
  q: ["Who cheers Pinky up after his embarrassing accident?",
      "Have you ever felt embarrassed in front of your class?",
      "What would you do to cheer up a friend who felt embarrassed?"],
  h: ["핑키가 창피한 일을 겪은 뒤 누가 그를 위로해 주었나요?",
      "너는 반 친구들 앞에서 창피했던 적이 있나요?",
      "창피해하는 친구를 위로하려면 너는 무엇을 하겠나요?"] };
ACT["M3047"] = { s: "Sue Ellen's diary is missing. What will happen if the diary falls into the wrong hands?",
  q: ["What is missing in this book?",
      "Have you ever written in a diary or a secret notebook?",
      "What would you do if you found someone else's diary?"],
  h: ["이 책에서 무엇이 사라졌나요?",
      "너는 일기나 비밀 노트를 써 본 적이 있나요?",
      "다른 사람의 일기를 발견한다면 너는 어떻게 하겠나요?"] };
ACT["M3048"] = { s: "This book explains how liquids are different from solids and gases, describes how liquids can change, and discusses the different forms of matter.",
  q: ["What does this book explain about liquids?",
      "Can you name a liquid you drank or used today?",
      "What is one thing you want to know more about liquids?"],
  h: ["이 책은 액체에 대해 무엇을 설명하나요?",
      "너는 오늘 마시거나 사용한 액체를 하나 말할 수 있나요?",
      "액체에 대해 더 알고 싶은 것은 무엇인가요?"] };
ACT["M3049"] = { s: "Alice the anteater reads a magazine about Christmas, and she travels to the North Pole to ask Santa Claus a very important question.",
  q: ["Where does Alice travel to, and who does she want to ask a question?",
      "Have you ever wanted to ask Santa Claus a question?",
      "What important question would you ask Santa Claus?"],
  h: ["앨리스는 어디로 여행을 가고, 누구에게 질문하고 싶어 하나요?",
      "너는 산타클로스에게 무언가 물어보고 싶었던 적이 있나요?",
      "네가 산타클로스에게 묻고 싶은 중요한 질문은 무엇인가요?"] };
ACT["M3050"] = { s: "Zack is worried when his grandmother starts getting younger and younger. How is it happening and how can he stop it?",
  q: ["What is happening to Zack's grandmother?",
      "Have you ever worried about someone in your family?",
      "What would you do if someone you love kept getting younger?"],
  h: ["잭의 할머니에게 무슨 일이 일어나고 있나요?",
      "너는 가족 중 누군가가 걱정되었던 적이 있나요?",
      "사랑하는 사람이 점점 어려진다면 너는 어떻게 하겠나요?"] };
ACT["M3051"] = { s: "Bear has large land, but he is too lazy to work. Hare, who needs a job to feed his hungry children, strikes a clever deal with the rich Bear.",
  q: ["What kind of deal does Hare make with Bear?",
      "Have you ever made a deal or agreement with someone?",
      "What clever deal would you make to solve a problem?"],
  h: ["토끼는 곰과 어떤 거래를 하나요?",
      "너는 누군가와 거래나 약속을 해 본 적이 있나요?",
      "문제를 풀기 위해 너라면 어떤 영리한 거래를 하겠나요?"] };
ACT["M3052"] = { s: "The students learn about food chains in the ocean.",
  q: ["What do the students learn about in the ocean?",
      "Have you ever learned about what animals eat in the ocean?",
      "What ocean animal would you like to learn more about in a food chain?"],
  h: ["학생들은 바다에서 무엇에 대해 배우나요?",
      "너는 바닷속 동물이 무엇을 먹는지 배운 적이 있나요?",
      "먹이사슬에서 네가 더 알고 싶은 바다 동물은 무엇인가요?"] };
ACT["M3053"] = { s: "In this book, Horrid Henry tries to be perfect for one day, learns to dance, argues with his sworn enemy Moody Margaret, and goes on holiday.",
  q: ["What does Henry try to be for one day?",
      "Have you ever tried really hard to be good for a whole day?",
      "What would be hard for you about trying to be perfect for a day?"],
  h: ["헨리는 하루 동안 무엇이 되려고 애썼나요?",
      "너는 하루 종일 착하게 지내려고 애써 본 적이 있나요?",
      "하루 동안 완벽해지려고 할 때 너에게 가장 어려운 것은 무엇일까요?"] };
ACT["M3054"] = { s: "When everything keeps going wrong, Katie Carew is fed up. She wishes that she could be anyone but herself. Will her wish come true? Book #1",
  q: ["What does Katie wish for when everything goes wrong?",
      "Have you ever had a day when everything went wrong?",
      "If you could be anyone else for a day, who would you choose and why?"],
  h: ["모든 일이 잘못될 때 케이티는 무엇을 바랐나요?",
      "너는 모든 일이 잘못되는 날을 겪어 본 적이 있나요?",
      "하루 동안 다른 사람이 될 수 있다면 누가 되고 싶고 그 이유는 무엇인가요?"] };
ACT["M3055"] = { s: "This book is about a ladybug’s whole cycle of growth and development.",
  q: ["What is this book about?",
      "Have you ever seen a ladybug?",
      "What do you want to know about how a ladybug grows?"],
  h: ["이 책은 무엇에 관한 책인가요?",
      "너는 무당벌레를 본 적이 있나요?",
      "무당벌레가 어떻게 자라는지 너는 무엇이 궁금한가요?"] };
ACT["M3056"] = { s: "When first-grader Freddy decides to try out for peewee hockey, his school bully Max decides to also try out for the one slot left on the team.",
  q: ["What does Freddy try out for?",
      "Have you ever tried out for a team or a club?",
      "What would you do if a bully tried out for the same team as you?"],
  h: ["프레디는 무엇을 위해 오디션을 보나요?",
      "너는 팀이나 동아리에 들어가려고 도전해 본 적이 있나요?",
      "너를 괴롭히는 아이가 같은 팀에 들어오려 한다면 너는 어떻게 하겠나요?"] };
ACT["M3057"] = { s: "A class discussion of ancestors reveals that Sidney and Ida both have connections to the sea. And the third-graders in Miss Mackle's class go on a boat trip on the Connecticut River.",
  q: ["What trip does the class go on?",
      "Have you ever been on a boat trip?",
      "What would you like to see on a boat trip?"],
  h: ["학생들은 어떤 여행을 떠나나요?",
      "너는 배를 타고 여행해 본 적이 있나요?",
      "배 여행에서 네가 보고 싶은 것은 무엇인가요?"] };
ACT["M3058"] = { s: "Deirdre is having a sleepover party, but when Deirdre's City Girls doll, Hollywood Heather, goes missing. But there is a detective in the room who can help the girls make sense of this mystery.",
  q: ["What goes missing at Deirdre's sleepover party?",
      "Have you ever been to a sleepover party?",
      "What would you do to solve the mystery of the missing doll?"],
  h: ["디어드리의 파자마 파티에서 무엇이 사라졌나요?",
      "너는 파자마 파티에 가 본 적이 있나요?",
      "사라진 인형을 찾기 위해 너는 무엇을 하겠나요?"] };
ACT["M3059"] = { s: "This book provides information about muscles and how they work in the human body, looks at different types of muscles, and includes tips on how to take care of muscles.",
  q: ["What does this book give tips about?",
      "What do you do to keep your muscles healthy, like exercise or sports?",
      "What is one way you want to take care of your muscles?"],
  h: ["이 책은 무엇에 대한 조언을 주나요?",
      "너는 근육을 건강하게 하려고 운동이나 스포츠를 하나요?",
      "네가 근육을 돌보고 싶은 방법 한 가지는 무엇인가요?"] };
ACT["M3060"] = { s: "An apple tree is willing to share all it has with a boy it loves.",
  q: ["What is the tree willing to share with the boy?",
      "Have you ever shared everything you had with someone you love?",
      "What would you like to share with someone you love?"],
  h: ["나무는 소년과 무엇을 나누려고 하나요?",
      "너는 사랑하는 사람과 네가 가진 모든 것을 나눠 본 적이 있나요?",
      "사랑하는 사람과 나누고 싶은 것은 무엇인가요?"] };
ACT["M3061"] = { s: "When a hermit crab outgrows his old shell, he moves into a new one and decorates it with the various sea creatures he meets in his travels.",
  q: ["What does the hermit crab do when he outgrows his old shell?",
      "Have you ever outgrown something, like clothes or shoes?",
      "How would you decorate a new house or shell?"],
  h: ["소라게는 껍데기가 작아지자 무엇을 했나요?",
      "너는 옷이나 신발이 작아진 적이 있나요?",
      "새 집이나 껍데기를 꾸민다면 너는 어떻게 꾸미고 싶나요?"] };
ACT["M3062"] = { s: "This book explains the purpose and functions of the human heart, describes how to keep a heart healthy, and includes instructions for a related activity.",
  q: ["What does this book explain about the heart?",
      "What do you do to keep your heart healthy?",
      "What is one thing you learned or want to learn about the heart?"],
  h: ["이 책은 심장에 대해 무엇을 설명하나요?",
      "너는 심장을 건강하게 하려고 무엇을 하나요?",
      "심장에 대해 네가 배웠거나 더 알고 싶은 것은 무엇인가요?"] };
ACT["M3063"] = { s: "When Katie gets into trouble for breaking school rules, she magically turns herself into the school's principal and eliminates all the rules. Book #5",
  q: ["What does Katie do when she turns into the principal?",
      "Have you ever thought a rule was unfair?",
      "If you were the principal for a day, what would you change?"],
  h: ["케이티는 교장 선생님이 되었을 때 무엇을 했나요?",
      "너는 어떤 규칙이 불공평하다고 생각한 적이 있나요?",
      "네가 하루 동안 교장 선생님이라면 무엇을 바꾸고 싶나요?"] };
ACT["M3064"] = { s: "When Josh discovers a nest of young falcons in the forest, he and his friends start visiting every day until the morning they find it empty! Then the kids look for the person who stole a peregrine falcon from its nest.",
  q: ["What do Josh and his friends find empty one morning?",
      "Have you ever discovered a nest or watched baby animals?",
      "What would you do if you found a nest was empty?"],
  h: ["조쉬와 친구들은 어느 날 아침 무엇이 비어 있는 것을 발견했나요?",
      "너는 둥지를 발견하거나 아기 동물을 지켜본 적이 있나요?",
      "둥지가 비어 있는 것을 발견한다면 너는 어떻게 하겠나요?"] };
ACT["M3065"] = { s: "Shackleton tries to find a way to rescue his crew when they run into dangerous waters on their journey to reach the South Pole.",
  q: ["What does Shackleton try to do for his crew?",
      "Have you ever had to find a way out of a difficult situation?",
      "What would you do to help your team in danger?"],
  h: ["섀클턴은 대원들을 위해 무엇을 하려고 애썼나요?",
      "너는 어려운 상황에서 빠져나갈 방법을 찾아야 했던 적이 있나요?",
      "위험에 처한 팀을 돕기 위해 너는 무엇을 하겠나요?"] };
ACT["M3066"] = { s: "A poor but clever traveler finds a way to get the townspeople to share their food with him. This story is based on a classic tale set in Germany at the end of the Thirty Years War.",
  q: ["How does the traveler get the townspeople to share their food?",
      "Have you ever shared a meal with a group of people?",
      "What clever idea would you use to get people to share?"],
  h: ["여행자는 마을 사람들이 음식을 나누도록 어떻게 했나요?",
      "너는 여러 사람들과 음식을 나눠 먹어 본 적이 있나요?",
      "사람들이 나누게 만들려면 너는 어떤 영리한 생각을 쓰겠나요?"] };
ACT["M3067"] = { s: "Sunflowers have tall, sturdy stems and huge heads. This book describes a sunflower's whole cycle of growth.",
  q: ["What kind of stems and heads do sunflowers have?",
      "Have you ever seen a sunflower or grown a flower?",
      "What do you want to know about how a sunflower grows?"],
  h: ["해바라기는 어떤 줄기와 꽃머리를 가지고 있나요?",
      "너는 해바라기를 보거나 꽃을 키워 본 적이 있나요?",
      "해바라기가 어떻게 자라는지 너는 무엇이 궁금한가요?"] };
ACT["M3068"] = { s: "Captain Cutlass can't see and needs to wear glasses. But he hides the fact because he's too afraid his fellow pirates will make him walk the plank.",
  q: ["Why does Captain Cutlass hide the fact that he needs glasses?",
      "Have you ever hidden something because you were worried what others would think?",
      "What would you say to Captain Cutlass about wearing glasses?"],
  h: ["커틀라스 선장은 왜 안경이 필요하다는 사실을 숨겼나요?",
      "너는 다른 사람이 어떻게 생각할지 걱정되어 무언가를 숨긴 적이 있나요?",
      "안경을 쓰는 것에 대해 커틀라스 선장에게 너는 무엇이라고 말해 주고 싶나요?"] };
ACT["M3069"] = { s: "A bulletin board fell on Stanley. It didn't hurt; it just made him flat. When he got used to being only 14 mm thick, Stanley enjoyed it. He did things no one else could do. Funny things, scary things.",
  q: ["A bulletin board falls on Stanley and makes him flat, but he learns to enjoy doing things no one else can do. If you suddenly became flat like a piece of paper, what fun or strange things would you try to do, and why?",
      "Stanley turns something that could have been scary or sad into something enjoyable. Write about a time something unexpected or strange happened to you and how you felt about it afterward.",
      "The book says Stanley does \"funny things, scary things\" because he is flat. Do you think there are good and bad sides to being different from everyone else? Explain your thinking."],
  h: ["스탠리는 게시판에 눌려 납작해지지만, 아무도 할 수 없는 일들을 하며 즐거워해요. 네가 갑자기 종이처럼 납작해진다면 어떤 재미있거나 신기한 일을 해 보고 싶은지, 그 이유와 함께 적어 보세요.",
      "스탠리는 무섭거나 슬플 수도 있었던 일을 즐거운 일로 바꾸었어요. 너에게 갑자기 뜻밖의 이상한 일이 일어났던 때를 떠올리고, 그때 나중에 어떤 기분이 들었는지 적어 보세요.",
      "책에서는 스탠리가 납작하기 때문에 \"재미있는 일, 무서운 일\"을 겪는다고 해요. 다른 사람들과 다르다는 것에 좋은 점과 나쁜 점이 둘 다 있다고 생각하나요? 네 생각을 이유와 함께 적어 보세요."] };
ACT["M3070"] = { s: "The magic tree house sends Jack and Annie back to Ancient Greece to retrieve a lost story. There they witness the very first Olympic games. Book #16",
  q: ["What do Jack and Annie witness in Ancient Greece?",
      "Have you ever watched the Olympics on TV?",
      "What Olympic event would you like to watch in person?"],
  h: ["잭과 애니는 고대 그리스에서 무엇을 목격하나요?",
      "너는 TV로 올림픽을 본 적이 있나요?",
      "네가 직접 보고 싶은 올림픽 경기는 무엇인가요?"] };
ACT["M3071"] = { s: "Ferdinand is a little bull who would rather just sit and smell the flowers than fight.",
  q: ["What does Ferdinand like to do instead of fighting?",
      "Have you ever preferred a quiet activity over an exciting one?",
      "What quiet thing do you like to do like Ferdinand?"],
  h: ["퍼디난드는 싸우는 대신 무엇을 하기를 좋아하나요?",
      "너는 신나는 일보다 조용한 일을 더 좋아한 적이 있나요?",
      "퍼디난드처럼 네가 좋아하는 조용한 일은 무엇인가요?"] };
ACT["M3072"] = { s: "Marvin is nervous when he hears that the president of the United States is coming to visit his class. He worries that he will make fun of himself in front of the president and everyone watching.",
  q: ["Why is Marvin nervous about the president's visit?",
      "Have you ever been nervous about meeting someone important?",
      "What would you do to calm down before meeting someone important?"],
  h: ["마빈은 왜 대통령의 방문에 긴장했나요?",
      "너는 중요한 사람을 만나는 게 긴장되었던 적이 있나요?",
      "중요한 사람을 만나기 전에 너는 어떻게 마음을 가라앉히겠나요?"] };
ACT["M3073"] = { s: "This book describes how gases are different from liquids and solids, explains how gases are created and change, and discusses the different forms of matter.",
  q: ["What does this book describe about gases?",
      "Can you name a gas you know about, like the air you breathe?",
      "What is one thing you want to know more about gases?"],
  h: ["이 책은 기체에 대해 무엇을 설명하나요?",
      "네가 숨 쉬는 공기처럼, 너는 알고 있는 기체를 하나 말할 수 있나요?",
      "기체에 대해 더 알고 싶은 것은 무엇인가요?"] };
ACT["M3074"] = { s: "Arthur is excited about the Brain coming to stay at his house for the whole weekend. But when the Brain starts acting a little too much like the perfect family member, Arthur is jealous.",
  q: ["Why does Arthur become jealous of the Brain?",
      "Have you ever felt jealous of a friend or family member?",
      "What would you do if you felt jealous like Arthur?"],
  h: ["아서는 왜 브레인을 질투하게 되었나요?",
      "너는 친구나 가족을 질투한 적이 있나요?",
      "아서처럼 질투가 난다면 너는 무엇을 하겠나요?"] };
ACT["M3075"] = { s: "Room 2B is working on a dragon project, but it leads to a war between two good friends, Harry and Song Lee.",
  q: ["What does the dragon project lead to between Harry and Song Lee?",
      "Have you ever had a disagreement with a good friend?",
      "What would you do to make up with a friend after a fight?"],
  h: ["용 프로젝트는 해리와 송리 사이에 무엇으로 이어지나요?",
      "너는 좋은 친구와 다툰 적이 있나요?",
      "싸운 뒤 친구와 화해하려면 너는 무엇을 하겠나요?"] };
ACT["M3076"] = { s: "Zack used to be in control of his own body. But that was before someone else?someone who's been dead almost one hundred years?took over.",
  q: ["Who takes over Zack's body?",
      "Have you ever felt like you weren't in control of something?",
      "What would you do if someone else took over your body for a day?"],
  h: ["누가 잭의 몸을 차지하게 되나요?",
      "너는 무언가를 스스로 통제할 수 없다고 느낀 적이 있나요?",
      "다른 누군가가 하루 동안 네 몸을 차지한다면 너는 어떻게 하겠나요?"] };
ACT["M3077"] = { s: "Green snakes live in fields and gardens, and they have skin that feels dry. This book describes a green snake’s whole cycle of growth and development.",
  q: ["Where do green snakes live, and what does their skin feel like?",
      "Have you ever seen a snake in a field, garden, or zoo?",
      "What do you want to know about how a green snake grows?"],
  h: ["초록뱀은 어디에 살고, 그 피부는 어떤 느낌인가요?",
      "너는 들판이나 정원, 동물원에서 뱀을 본 적이 있나요?",
      "초록뱀이 어떻게 자라는지 너는 무엇이 궁금한가요?"] };
ACT["M3078"] = { s: "When Katie accidentally wishes on a shooting star, she turns into her best friend Suzanne's baby sister. Book #3",
  q: ["What does Katie turn into after her wish?",
      "Have you ever made a wish on a star?",
      "What would you wish for on a shooting star?"],
  h: ["소원을 빈 뒤 케이티는 무엇으로 변하나요?",
      "너는 별똥별에 소원을 빌어 본 적이 있나요?",
      "별똥별에 빈다면 너는 무엇을 소원으로 빌고 싶나요?"] };
ACT["M3079"] = { s: "Dr. De Soto, a dentist mouse, and his wife, who is also his assistant. When a fox with a very painful toothache showed up at their office, they had quite a decision to make.",
  q: ["What decision do Dr. De Soto and his wife have to make?",
      "Have you ever had to make a hard decision about helping someone?",
      "What would you do if a dangerous animal asked you for help?"],
  h: ["드 소토 박사와 아내는 어떤 결정을 내려야 했나요?",
      "너는 누군가를 돕는 일로 어려운 결정을 내려야 했던 적이 있나요?",
      "위험한 동물이 네게 도움을 청한다면 너는 어떻게 하겠나요?"] };
ACT["M3080"] = { s: "Dink's neighbor can't find her canary. Ruth Rose's cat, Tiger, has also disappeared. Then the kids hear about two more missing critters. Dink and his friends investigate why pets are mysteriously disappearing all over town.",
  q: ["What do Dink and his friends investigate in this book?",
      "Have you ever lost track of a pet or helped look for one?",
      "What would you do to help find missing pets in your town?"],
  h: ["딩크와 친구들은 이 책에서 무엇을 조사하나요?",
      "너는 반려동물을 잃어버리거나 찾는 것을 도와준 적이 있나요?",
      "마을에서 없어진 반려동물들을 찾기 위해 너는 무엇을 하겠나요?"] };
ACT["M3081"] = { s: "This book explains the purpose and functions of the lungs, describes how to maintain healthy lungs, and includes instructions for a related activity.",
  q: ["What does this book explain about the lungs?",
      "What do you do to keep your lungs healthy?",
      "What is one thing you learned or want to learn about the lungs?"],
  h: ["이 책은 폐에 대해 무엇을 설명하나요?",
      "너는 폐를 건강하게 하려고 무엇을 하나요?",
      "폐에 대해 네가 배웠거나 더 알고 싶은 것은 무엇인가요?"] };
ACT["M3082"] = { s: "Freddy is unhappy about playing the turkey in his first-grade Thanksgiving Day play, especially with Max bullying and teasing him.",
  q: ["What part does Freddy play in the Thanksgiving play?",
      "Have you ever had a part in a school play you didn't like at first?",
      "What would you say to Freddy to help him feel better?"],
  h: ["프레디는 추수감사절 연극에서 어떤 역할을 맡았나요?",
      "너는 처음에 마음에 들지 않았던 역할을 학교 연극에서 맡아 본 적이 있나요?",
      "프레디의 기분을 풀어 주려면 너는 무엇이라고 말해 주고 싶나요?"] };
ACT["M3083"] = { s: "Arthur and his friends take a popularity test in a magazine for fun. But then, something strange happens to Sue Ellen and Fern.",
  q: ["What do Arthur and his friends take for fun?",
      "Have you ever taken a quiz or test just for fun?",
      "What would you do if something strange happened after a fun quiz?"],
  h: ["아서와 친구들은 재미로 무엇을 해 보나요?",
      "너는 그냥 재미로 퀴즈나 테스트를 해 본 적이 있나요?",
      "재미있는 퀴즈를 한 뒤 이상한 일이 생긴다면 너는 어떻게 하겠나요?"] };
ACT["M3084"] = { s: "This book is about Sammy Sosa's life and his baseball career. In 1998, Sammy Sosa, along with Mark McGwire, broke the long-standing record of most home runs hit in a season.",
  q: ["Sammy Sosa broke a long-standing home run record in 1998. Write about a goal you have worked hard toward, and explain what you did to get closer to it, the way Sammy Sosa trained for baseball.",
      "This book tells the story of Sammy Sosa's life and career. If someone wrote a book about your life so far, what would be the most important events to include, and why would you choose them?",
      "Breaking a record means doing something better than anyone has done before. Do you think breaking records is important, or is trying your best more important than being the best? Explain your opinion."],
  h: ["새미 소사는 1998년에 오랫동안 깨지지 않던 홈런 기록을 깼어요. 새미 소사가 야구 연습을 했던 것처럼, 네가 열심히 노력해 온 목표를 하나 떠올리고 그 목표에 가까워지기 위해 무엇을 했는지 적어 보세요.",
      "이 책은 새미 소사의 삶과 야구 인생 이야기를 담고 있어요. 누군가 지금까지의 네 인생에 대한 책을 쓴다면, 어떤 일들을 꼭 넣어야 한다고 생각하는지, 그 이유와 함께 적어 보세요.",
      "기록을 깬다는 것은 지금까지 누구보다 더 잘 해낸다는 뜻이에요. 너는 기록을 깨는 것이 중요하다고 생각하나요, 아니면 최선을 다하는 것이 최고가 되는 것보다 더 중요하다고 생각하나요? 네 생각을 이유와 함께 적어 보세요."] };
ACT["M3085"] = { s: "In this book, Horrid Henry invents the time machine, endures Peter's revenge, and dines at a fancy restaurant, and is forced to go on a hike by his horrible parents.",
  q: ["What does Henry invent in this book?",
      "Have you ever imagined building your own invention?",
      "If you invented a time machine, when would you travel to?"],
  h: ["헨리는 이 책에서 무엇을 발명하나요?",
      "너는 네 발명품을 만드는 상상을 해 본 적이 있나요?",
      "네가 타임머신을 발명한다면 언제로 가 보고 싶나요?"] };
ACT["M3086"] = { s: "A young boy sent on an errand over Hemlock Mountain. There may be bears on the mountain, but with the help of the big iron pot he borrows, he completes his errand.",
  q: ["What does the boy borrow to help him complete his errand?",
      "Have you ever done an errand that made you a little nervous?",
      "What would you bring with you if you had to cross a mountain with bears?"],
  h: ["소년은 심부름을 마치기 위해 무엇을 빌렸나요?",
      "너는 조금 긴장되는 심부름을 해 본 적이 있나요?",
      "곰이 있는 산을 건너야 한다면 너는 무엇을 챙기고 싶나요?"] };
ACT["M3087"] = { s: "Do you know bats are the only mammals that can fly? It's time to learn about this flying mammal.",
  q: ["What is special about bats compared to other mammals?",
      "Have you ever seen a bat in real life?",
      "What do you want to know more about bats?"],
  h: ["박쥐는 다른 포유류와 비교해서 무엇이 특별한가요?",
      "너는 실제로 박쥐를 본 적이 있나요?",
      "박쥐에 대해 네가 더 알고 싶은 것은 무엇인가요?"] };
ACT["M3088"] = { s: "Looking for adventure, a snail hitches a ride on a humpback whale and then rescues his friend, the humpback whale from being stuck on a sandy beach.",
  q: ["The tiny snail ends up rescuing the giant whale, even though the whale seems much stronger. Write about a time you or someone you know helped a person or animal that seemed much bigger or stronger, and what happened.",
      "The snail goes looking for adventure by hitching a ride on the whale. If you could hitch a ride on any animal to go on an adventure, which animal would you choose, where would you go, and what would you hope to see?",
      "Do you think it matters how big or small you are when it comes to helping someone? Use what happens between the snail and the whale to explain your answer."],
  h: ["작은 달팽이가 자기보다 훨씬 크고 강해 보이는 고래를 구해 줘요. 너나 네가 아는 사람이 훨씬 크거나 강해 보이는 사람이나 동물을 도와준 적이 있다면, 그때 무슨 일이 있었는지 적어 보세요.",
      "달팽이는 모험을 찾아 고래를 타고 여행을 떠나요. 네가 어떤 동물을 타고 모험을 떠날 수 있다면 어떤 동물을 고르고, 어디로 가고, 무엇을 보고 싶은지 적어 보세요.",
      "누군가를 돕는 데 있어서 크기나 힘이 중요하다고 생각하나요? 달팽이와 고래 사이에 있었던 일을 예로 들어 네 생각을 설명해 보세요."] };
ACT["M3089"] = { s: "Jack and Annie are sent back in time to a Hawaiian Island where they encounter a tsunami. Book #28",
  q: ["What natural event do Jack and Annie encounter on the Hawaiian Island?",
      "Have you ever learned about a tsunami or a big wave?",
      "What would you do to stay safe if you saw a tsunami coming?"],
  h: ["잭과 애니는 하와이 섬에서 어떤 자연 현상을 만나나요?",
      "너는 해일이나 큰 파도에 대해 배운 적이 있나요?",
      "해일이 오는 것을 본다면 너는 안전하게 있기 위해 무엇을 하겠나요?"] };
ACT["M3090"] = { s: "This book provides information about Earth's moon, discussing its size, surface, movement, and phases and takes a look at the moons of other planets.",
  q: ["What does this book discuss about Earth's moon?",
      "Have you ever looked up at the moon at night?",
      "What do you want to know more about the moon?"],
  h: ["이 책은 지구의 달에 대해 무엇을 다루나요?",
      "너는 밤에 달을 올려다본 적이 있나요?",
      "달에 대해 네가 더 알고 싶은 것은 무엇인가요?"] };
ACT["M3091"] = { s: "Henry loves books. The thing is, he loves to eat them, not read them.",
  q: ["What does Henry love to do with books instead of reading them?",
      "Do you love books? What do you love to do with them?",
      "What would you say to Henry about reading books instead?"],
  h: ["헨리는 책을 읽는 대신 무엇을 하기 좋아하나요?",
      "너는 책을 좋아하나요? 책으로 무엇을 하기 좋아하나요?",
      "책을 읽으라고 헨리에게 너는 무엇이라고 말해 주고 싶나요?"] };
ACT["M3092"] = { s: "George, a fourth-grader, starts his school year as the new boy and vows to become a model student instead of the class clown. But when the magic overtakes him, it turns him back into a trouble-maker. Book #1",
  q: ["What does George vow to become at the start of the school year?",
      "Have you ever tried to change how you act at school?",
      "What would you do if it was hard to keep a promise like George's?"],
  h: ["조지는 학년 초에 무엇이 되겠다고 다짐했나요?",
      "너는 학교에서 행동을 바꿔 보려고 한 적이 있나요?",
      "조지처럼 약속을 지키기 어렵다면 너는 어떻게 하겠나요?"] };
ACT["M3093"] = { s: "This book describes the various parts of the brain and how it functions to enable people to think, feel, move, and remember.",
  q: ["What does the brain help people do, according to this book?",
      "What is something you remember really well?",
      "What do you want to know more about how the brain works?"],
  h: ["이 책에 따르면 뇌는 사람이 무엇을 하도록 도와주나요?",
      "네가 정말 잘 기억하는 것은 무엇인가요?",
      "뇌가 어떻게 작동하는지 너는 무엇이 더 궁금한가요?"] };
ACT["M3094"] = { s: "One morning after a thunderstorm, the Lambchop family is surprised to discover that Stanley is suddenly invisible.",
  q: ["What happens to Stanley one morning?",
      "Have you ever wished you could be invisible?",
      "What would you do if you were invisible for a day?"],
  h: ["어느 날 아침 스탠리에게 무슨 일이 일어나나요?",
      "너는 투명 인간이 되고 싶었던 적이 있나요?",
      "하루 동안 투명 인간이 된다면 너는 무엇을 하겠나요?"] };
ACT["M3095"] = { s: "This book recounts how the Greeks used a wooden horse to win the Trojan War.",
  q: ["What did the Greeks use to win the war?",
      "Have you ever come up with a clever trick to solve a problem?",
      "What clever trick would you invent to solve a hard problem?"],
  h: ["그리스인들은 전쟁에서 이기기 위해 무엇을 사용했나요?",
      "너는 문제를 풀기 위해 영리한 방법을 생각해 낸 적이 있나요?",
      "어려운 문제를 풀기 위해 너는 어떤 영리한 방법을 만들어 내고 싶나요?"] };
ACT["M3096"] = { s: "When Freddy falls out of a tree and breaks his arm, he finds inspiration for his oral report on nocturnal animals.",
  q: ["What happens to Freddy that gives him an idea for his report?",
      "Have you ever gotten an idea for schoolwork from something that happened to you?",
      "What nocturnal animal would you like to give a report on?"],
  h: ["프레디에게 무슨 일이 일어나서 발표 아이디어를 얻게 되었나요?",
      "너는 너에게 일어난 일에서 숙제 아이디어를 얻은 적이 있나요?",
      "네가 발표하고 싶은 야행성 동물은 무엇인가요?"] };
ACT["M3097"] = { s: "A bear cub and a little girl each mistakes the other's mother for its own.",
  q: ["A bear cub and a little girl each follow the wrong mother by mistake. Write about a time you got confused or followed the wrong thing, like a person, a path, or an idea, and how you figured out your mistake.",
      "Think about why the bear cub and the little girl might have made this mistake. What do you think it would feel like to suddenly realize you were following the wrong mother?",
      "Do you think mistakes like this can only happen with people you don't know well, or could it happen with someone close to you too? Explain your thinking with an example."],
  h: ["아기 곰과 어린 여자아이는 실수로 서로 다른 엄마를 자기 엄마로 착각해요. 너는 사람이나 길, 생각 등 잘못된 것을 따라갔다가 실수를 알아차린 적이 있다면, 그때 어떻게 실수를 알게 되었는지 적어 보세요.",
      "아기 곰과 여자아이가 왜 이런 실수를 했을지 생각해 보세요. 갑자기 엄마를 잘못 따라가고 있었다는 것을 알게 된다면 어떤 기분일 것 같나요?",
      "이런 실수는 잘 모르는 사람하고만 생길 수 있을까요, 아니면 가까운 사람과도 생길 수 있을까요? 예를 들어 네 생각을 설명해 보세요."] };
ACT["M3098"] = { s: "This book discusses Earth's age, place in the solar system, layers, seasons, and why there is day and night.",
  q: ["What does this book discuss about Earth?",
      "What is your favorite season, and why?",
      "What do you want to know more about the Earth?"],
  h: ["이 책은 지구에 대해 무엇을 다루나요?",
      "네가 가장 좋아하는 계절은 무엇이고 이유는 무엇인가요?",
      "지구에 대해 네가 더 알고 싶은 것은 무엇인가요?"] };
ACT["M3099"] = { s: "Arthur feels jealous when Buster spends all of his time with his new friend, Mike.",
  q: ["Why does Arthur feel jealous in this book?",
      "Have you ever felt jealous when your friend spent time with someone else?",
      "What would you do if you felt jealous like Arthur?"],
  h: ["아서는 왜 이 책에서 질투를 느끼나요?",
      "너는 친구가 다른 사람과 시간을 보낼 때 질투를 느낀 적이 있나요?",
      "아서처럼 질투가 난다면 너는 무엇을 하겠나요?"] };
