// 간이 학습 질문 — Book No. M31 묶음. 사람이 아니라 AI 가 한 번 쓰고 굳힌 파일이다.
window.ACT = window.ACT || {};
var ACT = window.ACT;
ACT["M3100"] = { s: "Cam surprises her parents with the 40th birthday party. But when Granny and Gramps call from the airport and say they've been robbed, her parents rush to the airport immediately. Cam follows them to solve the case.",
  q: ["What happened when Granny and Gramps called from the airport?",
      "Have you ever helped solve a problem like Cam did?",
      "What would you do if you were planning a birthday party?"],
  h: ["그래니와 그램스가 공항에서 전화했을 때 무슨 일이 있었나요?",
      "너도 캠처럼 문제를 해결하는 것을 도와준 적이 있나요?",
      "네가 생일 파티를 준비한다면 무엇을 하고 싶나요?"] };
ACT["M3101"] = { s: "This book states the life and work of Picasso, discussing the different styles in which he worked.",
  q: ["What did you learn about Picasso's life and work?",
      "Have you ever tried drawing or painting in a different style?",
      "What style would you like to try if you were an artist?"],
  h: ["피카소의 삶과 작품에 대해 무엇을 배웠나요?",
      "너도 다른 방식으로 그림을 그려 본 적이 있나요?",
      "네가 화가라면 어떤 스타일을 해 보고 싶나요?"] };
ACT["M3102"] = { s: "The town is building a new park for a panda and her baby. But soon, the baby is kidnapped for a million-dollar ransom. Dink and his friends investigate the kidnapping of the new baby panda at the zoo.",
  q: ["Why was the baby panda kidnapped?",
      "Have you ever seen a panda at a zoo?",
      "What would you do to help find the missing panda?"],
  h: ["아기 판다는 왜 납치되었나요?",
      "너는 동물원에서 판다를 본 적이 있나요?",
      "사라진 판다를 찾기 위해 너라면 무엇을 하겠나요?"] };
ACT["M3103"] = { s: "Miss Daisy's weird teaching methods surprise the second grade students, especially reluctant learner A.J.",
  q: ["Why do you think A.J. was surprised by Miss Daisy's teaching methods? Write a few sentences.",
      "Have you ever had a teacher who did things differently? Write about that experience.",
      "If you could teach a class for one day, what fun method would you use? Explain your idea."],
  h: ["A.J.는 왜 미스 데이지의 가르치는 방법에 놀랐을까요? 몇 문장으로 적어 보세요.",
      "너도 특별하게 가르치는 선생님을 만난 적이 있나요? 그 경험을 적어 보세요.",
      "네가 하루 동안 수업을 한다면 어떤 재미있는 방법을 쓰고 싶나요? 네 생각을 적어 보세요."] };
ACT["M3104"] = { s: "Ms. Frizzle's class learns about the weather when the bus becomes a flying weather station and takes the class right into the storm clouds.",
  q: ["What did the class learn about the weather?",
      "Have you ever seen a big storm?",
      "What would you want to see if you flew into a storm cloud?"],
  h: ["반 친구들은 날씨에 대해 무엇을 배웠나요?",
      "너는 큰 폭풍을 본 적이 있나요?",
      "네가 폭풍 구름 속을 날아간다면 무엇을 보고 싶나요?"] };
ACT["M3105"] = { s: "A hypnotist's show turns out to be way more than Zack bargains for when he is pulled out of the audience, put into a trance, and his body is taken over by the spirit of someone from the past.",
  q: ["What happened to Zack during the hypnotist's show?",
      "Have you ever watched a magic show?",
      "What would you do if your body was taken over by someone else's spirit?"],
  h: ["최면술사의 공연에서 잭에게 무슨 일이 일어났나요?",
      "너는 마술 쇼를 본 적이 있나요?",
      "네 몸을 다른 누군가의 영혼이 차지한다면 너는 어떻게 하겠나요?"] };
ACT["M3106"] = { s: "Gustav Mole is born in a musical family. Gustav's musical education is rich and diverse, covering a wide variety of genres and styles.",
  q: ["What kind of music education did Gustav Mole have?",
      "Have you ever learned to play a musical instrument or sing?",
      "What kind of music would you like to learn?"],
  h: ["구스타브 몰은 어떤 음악 교육을 받았나요?",
      "너는 악기를 배우거나 노래를 배워 본 적이 있나요?",
      "너는 어떤 음악을 배우고 싶나요?"] };
ACT["M3107"] = { s: "While sailing in his tin bathtub, Toby encounters a lonely giant who guards an island. He finds out that the giant is seeking the sound that will wake up the inhabitants.",
  q: ["What was the giant looking for?",
      "Have you ever sailed or floated on water in something unusual?",
      "What sound do you think could wake up the island?"],
  h: ["거인은 무엇을 찾고 있었나요?",
      "너는 특이한 것을 타고 물 위에 떠 본 적이 있나요?",
      "섬을 깨울 수 있는 소리는 무엇일지 네 생각을 적어 보세요."] };
ACT["M3108"] = { s: "Francine's friends help her get the lead in the third-grade play. She becomes so intent on the play that she almost ruins it.",
  q: ["How did Francine's friends help her?",
      "Have you ever been in a school play or performance?",
      "What advice would you give Francine?"],
  h: ["프란신의 친구들은 그녀를 어떻게 도와주었나요?",
      "너는 학교 연극이나 공연에 참여해 본 적이 있나요?",
      "프란신에게 어떤 조언을 해 주고 싶나요?"] };
ACT["M3109"] = { s: "Mama and Papa Bear are eager to explore the wonders of Bear Country, but the cubs would rather be anywhere but the backseat of the family car!",
  q: ["How did the cubs feel about the car trip?",
      "Have you ever been on a long car trip?",
      "What would make a long car trip fun for you?"],
  h: ["아기 곰들은 자동차 여행에 대해 어떻게 느꼈나요?",
      "너는 긴 자동차 여행을 해 본 적이 있나요?",
      "긴 자동차 여행을 재미있게 만드는 것은 무엇일까요?"] };
ACT["M3110"] = { s: "At Green Lawn elementary school becomes involved in a mystery when the skeleton in the nurse's office, Mr. Bones, disappears.",
  q: ["What went missing at the school?",
      "Have you ever solved a mystery or found something that was lost?",
      "Where do you think Mr. Bones went?"],
  h: ["학교에서 무엇이 사라졌나요?",
      "너는 미스터리를 풀거나 잃어버린 것을 찾아본 적이 있나요?",
      "미스터 본즈는 어디로 갔을 것 같나요?"] };
ACT["M3111"] = { s: "This book discusses the importance of bones in the human body and looks at what bones are made of, how they help people move, and how to take care of them.",
  q: ["How do bones help people move?",
      "How do you take care of your bones?",
      "What is one new fact about bones you want to remember?"],
  h: ["뼈는 사람이 움직이는 것을 어떻게 도와주나요?",
      "너는 뼈를 어떻게 돌보고 있나요?",
      "뼈에 대해 새로 알게 된 사실 한 가지를 적어 보세요."] };
ACT["M3112"] = { s: "After Katie unintentionally gets Lucille the lunch lady fired, she tries to get the principal to rehire her. Book #2",
  q: ["Why did Katie try to talk to the principal?",
      "Have you ever made a mistake and tried to fix it?",
      "What would you say to the principal to help Lucille?"],
  h: ["케이티는 왜 교장 선생님과 이야기하려 했나요?",
      "너는 실수를 하고 그것을 고치려고 해 본 적이 있나요?",
      "루실을 돕기 위해 교장 선생님께 무슨 말을 하고 싶나요?"] };
ACT["M3113"] = { s: "The students learn about volcanoes under the water.",
  q: ["What did the students learn about volcanoes?",
      "Have you ever seen a picture or video of a volcano?",
      "What would you like to know about underwater volcanoes?"],
  h: ["학생들은 화산에 대해 무엇을 배웠나요?",
      "너는 화산 사진이나 영상을 본 적이 있나요?",
      "바닷속 화산에 대해 더 알고 싶은 것은 무엇인가요?"] };
ACT["M3114"] = { s: "Seven children are turned into seven types of food, and only their mother is able to break the spell.",
  q: ["What happened to the seven children?",
      "Who broke the spell?",
      "If you were turned into a food, what food would you want to be?"],
  h: ["일곱 아이들에게 무슨 일이 일어났나요?",
      "누가 마법을 풀었나요?",
      "네가 음식으로 변한다면 어떤 음식이 되고 싶나요?"] };
ACT["M3115"] = { s: "Ms. Hannah wears dresses made out of potholders and collects garbage. Plus she's making A.J. the partner of smelly Andrea. This is the worst art class ever!?",
  q: ["What did Ms. Hannah wear and collect?",
      "Have you ever had a partner in class that you didn't want?",
      "What would you make in art class with old potholders?"],
  h: ["미스 한나는 무엇을 입고 무엇을 모았나요?",
      "너는 원하지 않는 짝과 함께 해 본 적이 있나요?",
      "낡은 냄비 받침으로 미술 시간에 무엇을 만들고 싶나요?"] };
ACT["M3116"] = { s: "By using her ability to count, a clever monkey outwits the hungry crocodiles that stand between her and a banana tree.",
  q: ["How did the monkey outwit the crocodiles?",
      "Have you ever used counting to solve a problem?",
      "What would you do if crocodiles were blocking your way?"],
  h: ["원숭이는 어떻게 악어들을 속였나요?",
      "너는 숫자를 세어서 문제를 해결해 본 적이 있나요?",
      "악어들이 네 길을 막고 있다면 어떻게 하겠나요?"] };
ACT["M3117"] = { s: "In this loving story of a motherless family, a tall, plain woman comes to stay with them.",
  q: ["Why did the woman come to stay with the family?",
      "Have you ever met someone new who joined your family or class?",
      "What would you want to ask Sarah if you met her?"],
  h: ["그 여자는 왜 그 가족과 함께 지내러 왔나요?",
      "너는 가족이나 반에 새로 온 사람을 만나 본 적이 있나요?",
      "세라를 만난다면 무엇을 물어보고 싶나요?"] };
ACT["M3118"] = { s: "Every time Andrew Clancy tells another whopper, his butt grows bigger. Will it ever stop?",
  q: ["What happens every time Andrew tells a lie?",
      "Have you ever told a lie and felt bad about it?",
      "Why do you think it's important to tell the truth?"],
  h: ["앤드류가 거짓말을 할 때마다 무슨 일이 일어나나요?",
      "너는 거짓말을 하고 미안한 마음이 든 적이 있나요?",
      "진실을 말하는 것이 왜 중요하다고 생각하나요?"] };
ACT["M3119"] = { s: "Papa Bear and the cubs really prefer not to do their chores. They learn a lesson when Mama Bear decides not to do the chores either.",
  q: ["What lesson did Papa Bear and the cubs learn?",
      "What chores do you help with at home?",
      "What would happen if no one in your house did chores for a day?"],
  h: ["파파 베어와 아기 곰들은 어떤 교훈을 얻었나요?",
      "너는 집에서 어떤 집안일을 돕나요?",
      "하루 동안 아무도 집안일을 하지 않으면 무슨 일이 생길까요?"] };
ACT["M3120"] = { s: "Written as a report by a student, this biography profiles the life and artworks of Degas.",
  q: ["What did you learn about Degas's life and artworks?",
      "Have you ever seen a painting of dancers?",
      "If you wrote a report about an artist, who would you choose?"],
  h: ["드가의 삶과 작품에 대해 무엇을 배웠나요?",
      "너는 춤추는 사람들을 그린 그림을 본 적이 있나요?",
      "네가 화가에 대한 보고서를 쓴다면 누구를 고르고 싶나요?"] };
ACT["M3121"] = { s: "Angelina was excited about the arrival of a new baby. But her excitement turns into jealousy when she feels left out as her little sister becomes the center of attention.",
  q: ["Why did Angelina feel jealous?",
      "Have you ever felt left out?",
      "What would you say to Angelina to help her feel better?"],
  h: ["안젤리나는 왜 질투를 느꼈나요?",
      "너는 소외된다고 느낀 적이 있나요?",
      "안젤리나의 기분이 나아지도록 무슨 말을 해 주고 싶나요?"] };
ACT["M3122"] = { s: "A skateboarding principal offers incentives to his students to motivate them to learn more.",
  q: ["What did the principal do to motivate the students? Write a few sentences about it.",
      "What kind of reward would motivate you to study harder? Explain your idea.",
      "If you were the principal for a day, what fun rule would you make? Write about it."],
  h: ["교장 선생님은 학생들에게 동기를 주기 위해 무엇을 했나요? 몇 문장으로 적어 보세요.",
      "네가 공부를 더 열심히 하도록 동기를 주는 보상은 무엇일까요? 네 생각을 적어 보세요.",
      "네가 하루 동안 교장 선생님이 된다면 어떤 재미있는 규칙을 만들고 싶나요? 적어 보세요."] };
ACT["M3123"] = { s: "This book explains how spiders make silk and use it in various ways.",
  q: ["How do spiders make and use silk?",
      "Have you ever seen a spider web?",
      "What would you use spider silk for if you had some?"],
  h: ["거미는 실을 어떻게 만들고 어떻게 쓰나요?",
      "너는 거미줄을 본 적이 있나요?",
      "네가 거미줄을 가지고 있다면 무엇에 쓰고 싶나요?"] };
ACT["M3124"] = { s: "Arthur's class is holding a poetry contest, but no one seems interested except Fern. She dares her classmates to write a poem or enroll in the poetry club for a whole year!",
  q: ["What did Fern dare her classmates to do?",
      "Have you ever written a poem?",
      "What would you write a poem about?"],
  h: ["펀은 반 친구들에게 무엇을 하도록 도전했나요?",
      "너는 시를 써 본 적이 있나요?",
      "너는 무엇에 대한 시를 쓰고 싶나요?"] };
ACT["M3125"] = { s: "His friend Alex tries to help George stop the magic burps that take control and cause him to do wild and crazy things. But when George gets to spends the day at a water park, his magic burps put him into trouble again. Book #5",
  q: ["What happened when George's magic burps came back at the water park?",
      "Have you ever been to a water park?",
      "If you had magic burps, what would you want them to do?"],
  h: ["조지가 워터파크에서 마법의 트림을 했을 때 무슨 일이 일어났나요?",
      "너는 워터파크에 가 본 적이 있나요?",
      "네가 마법의 트림을 한다면 어떤 일이 일어나면 좋겠나요?"] };
ACT["M3126"] = { s: "This book explains what asteroids and comets are, how they are formed, how they move through space, and what scientists can learn from them.",
  q: ["What are asteroids and comets, and how do they move?",
      "Have you ever looked up at the night sky?",
      "What would you want to ask a scientist about space?"],
  h: ["소행성과 혜성은 무엇이고 어떻게 움직이나요?",
      "너는 밤하늘을 올려다본 적이 있나요?",
      "우주에 대해 과학자에게 무엇을 물어보고 싶나요?"] };
ACT["M3127"] = { s: "This book has all kinds of fun facts about large lizards from around the world, including their physical characteristics, habitat, and life cycle.",
  q: ["What did you learn about giant lizards?",
      "Have you ever seen a lizard?",
      "Which giant lizard would you like to learn more about?"],
  h: ["거대한 도마뱀에 대해 무엇을 배웠나요?",
      "너는 도마뱀을 본 적이 있나요?",
      "어떤 거대한 도마뱀에 대해 더 알고 싶나요?"] };
ACT["M3128"] = { s: "Nancy and her friends think there is nothing more fun than ice cream in the summer. They find out that a local ice-cream shop is hosting a contest. When a friend's recipe goes missing, Nancy investigates.",
  q: ["What went missing in the story?",
      "Have you ever entered a contest?",
      "What ice cream flavor would you invent for the contest?"],
  h: ["이야기에서 무엇이 사라졌나요?",
      "너는 대회에 나가 본 적이 있나요?",
      "대회를 위해 어떤 아이스크림 맛을 만들고 싶나요?"] };
ACT["M3129"] = { s: "Elizabeth Brown likes reading books best. She also loves collecting books she loves. The only problem is that her library has gotten too big.",
  q: ["What was Elizabeth Brown's problem?",
      "Do you like collecting books or other things?",
      "What would you do if you had too many books?"],
  h: ["엘리자베스 브라운의 문제는 무엇이었나요?",
      "너는 책이나 다른 것을 모으는 것을 좋아하나요?",
      "책이 너무 많아지면 너는 어떻게 하겠나요?"] };
ACT["M3130"] = { s: "This story is of a timid boy who gets sent to an adventure center and ends up having fun.",
  q: ["What happened to the timid boy at the adventure center?",
      "Have you ever been nervous about trying something new?",
      "What adventure would you like to try?"],
  h: ["소심한 소년은 모험 센터에서 무슨 일을 겪었나요?",
      "너는 새로운 것을 해 보기 전에 긴장한 적이 있나요?",
      "너는 어떤 모험을 해 보고 싶나요?"] };
ACT["M3131"] = { s: "When Link Baxter, SuperBully, moves into the neighborhood, Jake Drake takes matters into his own hands and stops Link's reign of terror.",
  q: ["What did Jake Drake do about the bully?",
      "Have you ever seen someone being bullied?",
      "What would you do if a bully moved into your neighborhood?"],
  h: ["제이크 드레이크는 괴롭히는 아이에 대해 무엇을 했나요?",
      "너는 누군가 괴롭힘을 당하는 것을 본 적이 있나요?",
      "괴롭히는 아이가 네 동네로 이사 온다면 너는 어떻게 하겠나요?"] };
ACT["M3132"] = { s: "Three times a voice comes to Isaac in his dreams. He journeys to the capital city to look for a treasure.",
  q: ["Why did Isaac journey to the capital city?",
      "Have you ever had an interesting dream?",
      "What treasure would you like to search for?"],
  h: ["아이작은 왜 수도로 여행을 떠났나요?",
      "너는 흥미로운 꿈을 꾼 적이 있나요?",
      "너는 어떤 보물을 찾고 싶나요?"] };
ACT["M3133"] = { s: "The shortest kid in the 2nd grade, James Moody, also known as Stink, learns all about the shortest president of the United States, James Madison, when they celebrate Presidents' Day at school.",
  q: ["What did Stink learn about President James Madison?",
      "Have you ever felt short or different from your classmates?",
      "What is something good about being different?"],
  h: ["스팅크는 제임스 매디슨 대통령에 대해 무엇을 배웠나요?",
      "너는 친구들과 다르거나 작다고 느낀 적이 있나요?",
      "다르다는 것의 좋은 점은 무엇일까요?"] };
ACT["M3134"] = { s: "Lucky knows that the lottery ticket his grandfather sends him for Christmas turns out to be a million-dollar winner. But it was stolen. Dink and his friends help Lucky find the culprit who stole the winning lottery ticket.",
  q: ["What did Dink and his friends help Lucky do?",
      "Have you ever lost something important and looked for it?",
      "What would you do with a million dollars if you won it?"],
  h: ["딩크와 친구들은 럭키를 위해 무엇을 도왔나요?",
      "너는 중요한 것을 잃어버리고 찾아본 적이 있나요?",
      "네가 백만 달러에 당첨된다면 무엇을 하고 싶나요?"] };
ACT["M3135"] = { s: "This book presents the life and work of Henri Matisse in the form of a student's school report.",
  q: ["What did you learn about how Matisse made art?",
      "Have you ever cut paper shapes to make art?",
      "What would you like to make by cutting paper?"],
  h: ["마티스가 어떻게 작품을 만들었는지 무엇을 배웠나요?",
      "너는 종이를 오려서 작품을 만들어 본 적이 있나요?",
      "종이를 오려서 무엇을 만들고 싶나요?"] };
ACT["M3136"] = { s: "Cam and Eric go to the movies with Cam's parents on a snowy winter day. While they are watching the movie, someone steals the second reel of the film. The theater manager thinks he's caught the thief, but Cam doesn't think so. Can Cam catch the real thief?",
  q: ["Why did Cam think the manager caught the wrong person?",
      "Have you ever gone to the movies on a snowy day?",
      "What clue would you look for to find the real thief?"],
  h: ["캠은 왜 관리인이 엉뚱한 사람을 잡았다고 생각했나요?",
      "너는 눈 오는 날 영화를 보러 간 적이 있나요?",
      "진짜 도둑을 찾기 위해 어떤 단서를 찾아보고 싶나요?"] };
ACT["M3137"] = { s: "This book presents the wonders of electricity and lightning. You can learn what different cultures once believed lightning to be and how Benjamin Franklin proved what it really is.",
  q: ["What did Benjamin Franklin prove about lightning?",
      "Have you ever seen lightning during a storm?",
      "What did people long ago believe lightning was, and what do you think now?"],
  h: ["벤저민 프랭클린은 번개에 대해 무엇을 증명했나요?",
      "너는 폭풍우 속에서 번개를 본 적이 있나요?",
      "옛날 사람들은 번개를 무엇이라 믿었고, 너는 지금 어떻게 생각하나요?"] };
ACT["M3138"] = { s: "Arthur's class goes on a field trip to the Middle Ages Fair and competes against Glenbrook Academy. His class loses every challenge and the only event left is to pull a sword from a stone.",
  q: ["What was the last challenge Arthur's class had left?",
      "Have you ever competed in a game or contest with another class or team?",
      "Do you think Arthur's class can pull the sword from the stone? Why?"],
  h: ["아서네 반에게 남은 마지막 도전은 무엇이었나요?",
      "너는 다른 반이나 팀과 경기나 대회를 해 본 적이 있나요?",
      "아서네 반이 바위에서 검을 뽑을 수 있을까요? 왜 그렇게 생각하나요?"] };
ACT["M3139"] = { s: "When Alice Rumphius gets old enough, she travels the world and does the one thing her grandfather told her to do-make the world more beautiful.",
  q: ["What did Alice's grandfather tell her to do?",
      "Have you ever traveled somewhere new?",
      "What would you do to make the world more beautiful?"],
  h: ["앨리스의 할아버지는 그녀에게 무엇을 하라고 했나요?",
      "너는 새로운 곳으로 여행을 가 본 적이 있나요?",
      "세상을 더 아름답게 만들기 위해 너는 무엇을 하고 싶나요?"] };
ACT["M3140"] = { s: "This book explores the life of Vincent Van Gogh.",
  q: ["What did you learn about Van Gogh's life?",
      "Have you ever seen a painting of sunflowers or stars?",
      "If you painted the sky, what would you put in it?"],
  h: ["반 고흐의 삶에 대해 무엇을 배웠나요?",
      "너는 해바라기나 별을 그린 그림을 본 적이 있나요?",
      "네가 하늘을 그린다면 무엇을 그려 넣고 싶나요?"] };
ACT["M3141"] = { s: "When everyone wakes up a bit grumpy, the mood in the Bear house is anything but happy.",
  q: ["Why do you think everyone in the Bear house was grumpy? Write a few sentences.",
      "Write about a time when you woke up feeling grumpy. What happened?",
      "What can a family do to fix a grumpy morning? Explain your idea."],
  h: ["베어 가족은 왜 모두 짜증이 났을까요? 몇 문장으로 적어 보세요.",
      "네가 짜증 난 채로 일어났던 때를 적어 보세요. 무슨 일이 있었나요?",
      "짜증 난 아침을 풀기 위해 가족이 할 수 있는 일은 무엇일까요? 네 생각을 적어 보세요."] };
ACT["M3142"] = { s: "By the power of the magic tree house, Jack and Annie are sent back to the time of the American Revolution. They happened to meet General George Washington and help him during his famous crossing of the Delaware River. Book #22",
  q: ["Who did Jack and Annie meet, and what did they help with?",
      "Have you ever learned about a famous person from history?",
      "If you could travel back in time, which event would you want to see?"],
  h: ["잭과 애니는 누구를 만났고 무엇을 도왔나요?",
      "너는 역사 속 유명한 사람에 대해 배운 적이 있나요?",
      "네가 시간 여행을 한다면 어떤 사건을 보고 싶나요?"] };
ACT["M3143"] = { s: "When Arnold wants to know what makes his hot cocoa become cold, Ms. Frizzle takes the class for a ride on the Magic School Bus to find the answer.",
  q: ["What question did Arnold have, and how did the class try to answer it? Write a few sentences.",
      "Write about a time you wondered why something got hot or cold.",
      "If you rode the Magic School Bus to the Arctic, what would you want to see? Explain."],
  h: ["아놀드는 어떤 질문이 있었고, 반 친구들은 어떻게 답을 찾으려 했나요? 몇 문장으로 적어 보세요.",
      "네가 무언가 뜨거워지거나 차가워지는 이유가 궁금했던 때를 적어 보세요.",
      "네가 매직 스쿨버스를 타고 북극에 간다면 무엇을 보고 싶나요? 적어 보세요."] };
ACT["M3144"] = { s: "A magical train ride on Christmas Eve takes a boy to the North Pole to get a special present from Santa Claus.",
  q: ["Where did the train take the boy, and why?",
      "Have you ever ridden on a train?",
      "What present would you want to get from Santa?"],
  h: ["기차는 소년을 어디로 데려갔고, 왜였나요?",
      "너는 기차를 타 본 적이 있나요?",
      "산타에게 어떤 선물을 받고 싶나요?"] };
ACT["M3145"] = { s: "The Clue Crew gets the chance to visit a movie set, thanks to one of Mr. Drew's connected clients, but fun turns to business when the film's star, Fluffington, disappears.",
  q: ["What happened to the film's star, Fluffington? Write a few sentences about it.",
      "Write about a time a fun day suddenly turned into a problem you had to solve.",
      "If you visited a movie set, what would you want to see or do? Explain your idea."],
  h: ["영화의 스타인 플러핑턴에게 무슨 일이 일어났나요? 몇 문장으로 적어 보세요.",
      "즐거운 하루가 갑자기 네가 풀어야 할 문제로 바뀌었던 때를 적어 보세요.",
      "네가 영화 촬영장을 방문한다면 무엇을 보거나 하고 싶나요? 네 생각을 적어 보세요."] };
ACT["M3146"] = { s: "This book explains what stars are, their size, number, groupings, and types.",
  q: ["What did you learn about the size and types of stars?",
      "Have you ever looked at stars in the night sky?",
      "What would you like to learn more about stars?"],
  h: ["별의 크기와 종류에 대해 무엇을 배웠나요?",
      "너는 밤하늘에서 별을 본 적이 있나요?",
      "별에 대해 더 알고 싶은 것은 무엇인가요?"] };
ACT["M3147"] = { s: "The new school librarian, Mrs. Roopy, has multiple personality disorder because she keeps pretending to be famous people.",
  q: ["What did Mrs. Roopy keep pretending to be?",
      "Have you ever pretended to be someone famous?",
      "Who would you want to pretend to be for a day?"],
  h: ["루피 선생님은 계속 누구인 척했나요?",
      "너는 유명한 사람인 척해 본 적이 있나요?",
      "너는 하루 동안 누가 되어 보고 싶나요?"] };
ACT["M3148"] = { s: "Dink, Josh, and Ruth Rose love visiting their friend Sammi, the prince of Costra. While visiting, there's been a robbery on the island. Dink and his friends help catch the thieves who have stolen gold from Sammi's parents.",
  q: ["What did Dink and his friends help catch?",
      "Have you ever visited a friend who lived somewhere special?",
      "What would you do if you found out gold was stolen from your friend's family?"],
  h: ["딩크와 친구들은 무엇을 잡는 것을 도왔나요?",
      "너는 특별한 곳에 사는 친구를 방문해 본 적이 있나요?",
      "친구 가족의 금이 도둑맞았다는 것을 알게 된다면 너는 어떻게 하겠나요?"] };
ACT["M3149"] = { s: "This book is an illustrated version of a song pointing out that in spite of our differences, we are all the same in God's view.",
  q: ["이 책은 서로 다르더라도 우리는 같다고 노래해요. 이 책에서 나온 다른 점 중에 기억나는 것이 있나요?",
      "나와 다른 점이 있는 친구를 만난 적이 있나요?",
      "내가 친구에게 하고 싶은 말을 한 가지 적어 보세요."],
  h: ["", "", ""] };
ACT["M3150"] = { s: "Oliver Tolliver, who lives alone in his little house with just one of everything, discovers that it is more fun to share with a friend.",
  q: ["What did Oliver Tolliver discover about sharing? Write a few sentences.",
      "Write about something you shared with a friend and how it felt.",
      "If you had just one of everything, what would you want a friend to share with you? Explain."],
  h: ["올리버 톨리버는 나누는 것에 대해 무엇을 깨달았나요? 몇 문장으로 적어 보세요.",
      "친구와 무언가를 나누었던 경험과 그때 기분을 적어 보세요.",
      "네가 모든 것을 하나씩만 가지고 있다면, 친구가 무엇을 나눠 주면 좋겠나요? 적어 보세요."] };
ACT["M3151"] = { s: "Chip finds a rusty, old box in his bedroom. Not knowing what to do with the box, he gives it away for the school fair. Then strange things begin to happen around him.",
  q: ["What began to happen after Chip gave away the box?",
      "Have you ever found something old and wondered about it?",
      "What do you think is inside the strange box?"],
  h: ["칩이 상자를 넘겨준 뒤 무슨 이상한 일이 일어나기 시작했나요?",
      "너는 오래된 물건을 발견하고 궁금해한 적이 있나요?",
      "이상한 상자 안에는 무엇이 있을 것 같나요?"] };
ACT["M3152"] = { s: "The children go through the door with Mr Mortlock and find themselves in a timeless place.",
  q: ["Where did the children find themselves after going through the door?",
      "Have you ever imagined what's behind a mysterious door?",
      "What would you want to find in a timeless place?"],
  h: ["아이들은 문을 지나간 뒤 어디에 있게 되었나요?",
      "너는 신비한 문 뒤에 무엇이 있을지 상상해 본 적이 있나요?",
      "시간이 없는 곳에서 너는 무엇을 발견하고 싶나요?"] };
ACT["M3153"] = { s: "Wilf travels back in time to search for a part missing from the TimeWeb, a remarkable time-traveling device. Mortlock, the Time Guardian, needs it to defeat the Virans. Will Wilf succeed and complete the task?",
  q: ["What did Wilf need to find, and why?",
      "Have you ever helped someone find something important?",
      "Do you think Wilf will succeed? Why or why not?"],
  h: ["윌프는 무엇을 찾아야 했고 왜였나요?",
      "너는 누군가가 중요한 것을 찾는 것을 도와준 적이 있나요?",
      "윌프가 성공할 것 같나요? 왜 그렇게 생각하나요?"] };
ACT["M3154"] = { s: "Neena goes on a solo mission to try and find the Matrix.",
  q: ["What was Neena's mission?",
      "Have you ever done something difficult all by yourself?",
      "What would help you feel brave on a solo mission?"],
  h: ["니나의 임무는 무엇이었나요?",
      "너는 혼자서 어려운 일을 해 본 적이 있나요?",
      "혼자 임무를 할 때 용기를 얻기 위해 무엇이 도움이 될까요?"] };
ACT["M3155"] = { s: "The Cell gives power to the Time Web, making traveling through time possible. Everything will be ruined if the Virans find it. Three kids go back in time to find the Cell, but will they all return safely?",
  q: ["Why did the three kids go back in time?",
      "Have you ever worked together with friends to protect something important?",
      "Do you think they will return safely? Why?"],
  h: ["세 아이는 왜 시간을 거슬러 갔나요?",
      "너는 친구들과 함께 중요한 것을 지키기 위해 힘을 합친 적이 있나요?",
      "그들이 안전하게 돌아올 것 같나요? 왜 그렇게 생각하나요?"] };
ACT["M3156"] = { s: "Biff and Chip must go into the future to get the key to make the Time Web work.",
  q: ["Where did Biff and Chip go, and what did they need to get?",
      "Have you ever needed a special key or tool to finish something?",
      "What do you think the future looks like in this story?"],
  h: ["비프와 칩은 어디로 갔고 무엇을 가져와야 했나요?",
      "너는 무언가를 끝내기 위해 특별한 열쇠나 도구가 필요했던 적이 있나요?",
      "이 이야기 속 미래는 어떤 모습일 것 같나요?"] };
ACT["M3157"] = { s: "Now that Time Web is working correctly, the children can start working as Time Runners, assisting Mortlock in defeating the Virans. However, their first task at Ancient Rome reveals they still have much to learn.",
  q: ["What did the children learn on their first task in Ancient Rome?",
      "Have you ever learned that you still had more to learn while doing something new?",
      "What would you want to know about Ancient Rome?"],
  h: ["아이들은 고대 로마에서의 첫 임무에서 무엇을 배웠나요?",
      "너는 새로운 일을 하면서 아직 배울 것이 더 많다고 느낀 적이 있나요?",
      "고대 로마에 대해 무엇을 알고 싶나요?"] };
ACT["M3158"] = { s: "Tyler tells the other children about his past and where came from.",
  q: ["What did Tyler tell the other children about?",
      "Have you ever told someone about where you came from or your past?",
      "What would you want to know about Tyler's past?"],
  h: ["타일러는 다른 아이들에게 무엇에 대해 이야기했나요?",
      "너는 네가 어디서 왔는지, 네 과거에 대해 누군가에게 이야기해 본 적이 있나요?",
      "타일러의 과거에 대해 무엇을 알고 싶나요?"] };
ACT["M3159"] = { s: "When Biff, Wilf, and Kipper go back in time to old London during Queen Elizabeth's time, they are surprised to meet the famous writer William Shakespeare and even the Queen at the theater.",
  q: ["Who did Biff, Wilf, and Kipper meet at the theater?",
      "Have you ever been to a theater or watched a play?",
      "What would you ask Shakespeare if you met him?"],
  h: ["비프와 윌프, 키퍼는 극장에서 누구를 만났나요?",
      "너는 극장에 가 보거나 연극을 본 적이 있나요?",
      "셰익스피어를 만난다면 무엇을 물어보고 싶나요?"] };
ACT["M3160"] = { s: "Chip and Wilf try to stop a Viran from putting HMS Victory in danger.",
  q: ["What were Chip and Wilf trying to stop?",
      "Have you ever tried to stop something bad from happening?",
      "Why do you think HMS Victory is important?"],
  h: ["칩과 윌프는 무엇을 막으려고 했나요?",
      "너는 나쁜 일이 일어나는 것을 막으려고 해 본 적이 있나요?",
      "HMS 빅토리호가 왜 중요하다고 생각하나요?"] };
ACT["M3161"] = { s: "The Virans aim to attack and bring chaos to history during World War Two. Can Wilma, Nadim, and Kipper prevent the Virans from carrying out their plan?",
  q: ["What were the Virans trying to do during World War Two?",
      "Have you ever learned about World War Two in school?",
      "What do you think Wilma, Nadim, and Kipper should do first?"],
  h: ["바이란들은 2차 세계대전 동안 무엇을 하려고 했나요?",
      "너는 학교에서 2차 세계대전에 대해 배운 적이 있나요?",
      "윌마와 나딤, 키퍼는 먼저 무엇을 해야 할까요?"] };
ACT["M3162"] = { s: "Neena travels to 8th century Baghdad to try to stop a Viran's evil plan.",
  q: ["What was Neena's mission in 8th century Baghdad? Write a few sentences.",
      "Write about a time you had to be brave to stop something bad.",
      "If you traveled to 8th century Baghdad, what would you want to see there? Explain."],
  h: ["니나가 8세기 바그다드에서 맡은 임무는 무엇이었나요? 몇 문장으로 적어 보세요.",
      "네가 나쁜 일을 막기 위해 용기를 내야 했던 때를 적어 보세요.",
      "네가 8세기 바그다드로 여행을 간다면 무엇을 보고 싶나요? 적어 보세요."] };
ACT["M3163"] = { s: "Biff and Chip are in the midst of a battleground where Vikings and Saxons are facing off. King Alfred the Great desires peace, but the Viran is determined to stop him.",
  q: ["What did King Alfred want, and who was trying to stop him? Write a few sentences.",
      "Write about a time you wanted peace between two people or groups who were arguing.",
      "If you were King Alfred, what would you do to bring peace? Explain your idea."],
  h: ["알프레드 왕은 무엇을 원했고, 누가 그것을 막으려 했나요? 몇 문장으로 적어 보세요.",
      "다투는 두 사람이나 집단 사이에 평화를 바랐던 때를 적어 보세요.",
      "네가 알프레드 왕이라면 평화를 가져오기 위해 무엇을 하겠나요? 네 생각을 적어 보세요."] };
ACT["M3164"] = { s: "Neena and Wilf face one of their hardest challenges yet in ancient Greece. A Viran is trying to prevent the rebuilding of the Parthenon. Can they stop him before it's too late?",
  q: ["What was the Viran trying to prevent in ancient Greece? Write a few sentences.",
      "Write about a time you worked hard to rebuild or fix something.",
      "Why do you think the Parthenon is important to protect? Explain your thinking."],
  h: ["바이란은 고대 그리스에서 무엇을 막으려 했나요? 몇 문장으로 적어 보세요.",
      "무언가를 다시 짓거나 고치기 위해 열심히 노력했던 때를 적어 보세요.",
      "파르테논 신전을 지키는 것이 왜 중요하다고 생각하나요? 네 생각을 적어 보세요."] };
ACT["M3165"] = { s: "Nadim and Neena travel back to the year 1666 and discover they are at the beginning of the Great Fire of London. Will they be able to foil the sinister scheme of the Viran?",
  q: ["What event did Nadim and Neena discover the beginning of? Write a few sentences.",
      "Write about a time you were surprised to discover something was just beginning.",
      "What would you do first if you discovered a fire was starting? Explain your plan."],
  h: ["나딤과 니나는 무엇의 시작을 발견했나요? 몇 문장으로 적어 보세요.",
      "무언가가 막 시작되고 있다는 것을 알고 놀랐던 때를 적어 보세요.",
      "불이 나기 시작한 것을 발견한다면 너는 가장 먼저 무엇을 하겠나요? 네 계획을 적어 보세요."] };
ACT["M3166"] = { s: "The Time Runners battle to stop a fiendish Viran plan to steal the Scottish Stone of Destiny. If they fail, the history of Scotland could be at stake.",
  q: ["What were the Time Runners trying to stop, and why did it matter? Write a few sentences.",
      "Write about a time you protected something valuable to you or your family.",
      "Why do you think a stone could be important to a country's history? Explain your thinking."],
  h: ["타임 러너들은 무엇을 막으려 했고, 그것이 왜 중요했나요? 몇 문장으로 적어 보세요.",
      "너나 가족에게 소중한 것을 지켰던 때를 적어 보세요.",
      "돌 하나가 한 나라의 역사에 왜 중요할 수 있다고 생각하나요? 네 생각을 적어 보세요."] };
ACT["M3167"] = { s: "Chip, Kipper, and Wilma chase the Virans, plotting to destroy bridges, trains, and lives. Can the Time Runners stop the Virans and save the Industrial Revolution?",
  q: ["What were the Virans plotting to destroy? Write a few sentences about it.",
      "Write about a time you chased after something or someone to fix a problem.",
      "Why do you think bridges and trains were important during the Industrial Revolution? Explain."],
  h: ["바이란들은 무엇을 파괴하려고 계획했나요? 몇 문장으로 적어 보세요.",
      "문제를 해결하기 위해 무언가나 누군가를 쫓아갔던 때를 적어 보세요.",
      "산업 혁명 시기에 다리와 기차가 왜 중요했다고 생각하나요? 네 생각을 적어 보세요."] };
ACT["M3168"] = { s: "the Virans strike closer to the Time Runners than ever before in this exciting adventure set at the time of the slave trade in the Caribbean.",
  q: ["What time and place is this adventure set in? Write a few sentences about what you know.",
      "Write about a time something felt closer and more serious than before.",
      "What questions do you have about this part of history? Explain your thinking."],
  h: ["이 모험은 언제, 어디에서 일어나나요? 네가 아는 것을 몇 문장으로 적어 보세요.",
      "무언가가 예전보다 더 가깝고 심각하게 느껴졌던 때를 적어 보세요.",
      "이 역사에 대해 어떤 질문이 생기나요? 네 생각을 적어 보세요."] };
