// 간이 학습 질문 — Book No. M40 묶음. 사람이 아니라 AI 가 한 번 쓰고 굳힌 파일이다.
window.ACT = window.ACT || {};
var ACT = window.ACT;
ACT["M4001"] = { s: "Ms. Frizzle takes the class all over the United States looking for bats.",
  q: ["What did the class look for in this book?",
      "Have you ever seen a bat?",
      "What do you want to know about bats?"],
  h: ["이 책에서 반 친구들은 무엇을 찾아다녔나요?",
      "너는 박쥐를 본 적이 있니?",
      "너는 박쥐에 대해 무엇이 궁금하니?"] };
ACT["M4002"] = { s: "When fears take over Geronimo's life, his friends decide to cure him. Book #5",
  q: ["What did Geronimo's friends decide to do for him?",
      "What are you afraid of?",
      "How do you want your friends to help you?"],
  h: ["제로니모의 친구들은 그를 위해 무엇을 하기로 했나요?",
      "너는 무엇을 무서워하니?",
      "친구들이 너를 어떻게 도와주면 좋겠니?"] };
ACT["M4003"] = { s: "After her father loses his job, Lydia Grace goes to live with her uncle. She brings a suitcase full of seeds and her love of gardening to the big city.",
  q: ["What did Lydia Grace bring with her to the city?",
      "Have you ever grown a plant or flower?",
      "What do you want to grow if you have seeds?"],
  h: ["리디아 그레이스는 도시로 갈 때 무엇을 가져갔나요?",
      "너는 식물이나 꽃을 키워 본 적이 있니?",
      "씨앗이 있다면 너는 무엇을 키우고 싶니?"] };
ACT["M4004"] = { s: "Leroy Brown, aka Encyclopedia Brown, uses his computer-like brain to help solve ten puzzling crimes. This ten-year-old boy detective opens his detective agency and solves cases ranging from a Civil War sword to a trapeze artist's inheritance.",
  q: ["Which case in this book sounds more interesting to you, the Civil War sword case or the trapeze artist's inheritance case? Explain why in a few sentences.",
      "Have you ever tried to solve a mystery or figure out a tricky problem in your own life? Write about what happened.",
      "If you opened your own detective agency like Leroy Brown, what kind of cases would you want to solve? Write a few sentences about your idea."],
  h: ["이 책에 나온 사건 중 남북전쟁 칼 사건과 공중곡예사 유산 사건 중 어느 쪽이 더 궁금한가요? 이유를 몇 문장으로 써 보세요.",
      "너는 살면서 수수께끼나 어려운 문제를 풀어 본 적이 있나요? 그때 무슨 일이 있었는지 적어 보세요.",
      "너도 리로이처럼 탐정 사무소를 연다면 어떤 사건을 풀고 싶나요? 네 생각을 몇 문장으로 적어 보세요."] };
ACT["M4005"] = { s: "Amber enters fourth grade. She faces some changes in her life as her best friend moves away and her parents get a divorce.",
  q: ["What two big changes does Amber face in this book?",
      "Has a friend of yours ever moved away?",
      "What would you do to feel better after a big change?"],
  h: ["앰버는 이 책에서 어떤 두 가지 큰 변화를 겪나요?",
      "너의 친구가 이사를 간 적이 있니?",
      "큰 변화를 겪은 뒤 기분이 나아지려면 너는 무엇을 하고 싶니?"] };
ACT["M4006"] = { s: "This is a biography of Mexican artist Frida Kahlo, written as a child's school report.",
  q: ["What country was the artist Frida Kahlo from?",
      "Have you ever written a report about a person?",
      "What artist or person do you want to write a report about?"],
  h: ["화가 프리다 칼로는 어느 나라 사람이었나요?",
      "너는 어떤 사람에 대한 보고서를 써 본 적이 있니?",
      "너는 어떤 화가나 인물에 대해 보고서를 쓰고 싶니?"] };
ACT["M4007"] = { s: "Little Willy hopes to pay the back taxes on his grandfather's farm with the money from a dogsled race he enters.",
  q: ["Why does Little Willy enter the dogsled race? Explain his reason in a few sentences.",
      "Have you ever tried hard to help your family with a problem? Write about it.",
      "If you needed to win a race to help someone you love, how would you get ready? Write your plan."],
  h: ["리틀 윌리는 왜 개썰매 경주에 나가나요? 그 이유를 몇 문장으로 써 보세요.",
      "너는 가족을 돕기 위해 열심히 노력해 본 적이 있니? 그때 이야기를 적어 보세요.",
      "네가 사랑하는 사람을 돕기 위해 경주에서 이겨야 한다면, 어떻게 준비할지 계획을 적어 보세요."] };
ACT["M4008"] = { s: "Peter Hatcher has a terrible problem- his two-year-old little brother, Fudge. Fudge often humiliates and infuriates Peter. Living with his little brother makes Peter feel like a fourth grade nothing.",
  q: ["What is Peter's problem in this book?",
      "Do you have a younger brother or sister who bothers you?",
      "What do you do when you feel angry at your family?"],
  h: ["피터의 문제는 무엇인가요?",
      "너를 귀찮게 하는 동생이 있니?",
      "가족에게 화가 날 때 너는 무엇을 하니?"] };
ACT["M4009"] = { s: "This is the story of the historic march on Washington, D.C. on August 28, 1963. This book highlights Martin Luther King, Jr's. famous speech with simple text and full-color photos.",
  q: ["What did Martin Luther King, Jr. do on August 28, 1963?",
      "Have you ever heard someone give a famous speech?",
      "What is something important you want to say to many people?"],
  h: ["마틴 루터 킹 목사는 1963년 8월 28일에 무엇을 했나요?",
      "너는 유명한 연설을 들어 본 적이 있니?",
      "네가 많은 사람들에게 하고 싶은 중요한 말은 무엇이니?"] };
ACT["M4010"] = { s: "What's the only cure for the meanest grandmother in the world? George creates a fierce and fantastic bubbling brew, the perfect cure.",
  q: ["What does George make to cure his grandmother? Describe what you think it might be like, using clues from the summary.",
      "Has anyone in your family ever been mean or grumpy to you? Write about how you felt and what you did.",
      "If you could make a magic medicine, what would you want it to do? Write a few sentences about your invention."],
  h: ["조지는 할머니를 고치기 위해 무엇을 만드나요? 요약에 나온 단서를 가지고 그게 어떤 모습일지 상상해서 적어 보세요.",
      "가족 중 누군가 너에게 심술궂게 대한 적이 있니? 그때 기분이 어땠고 어떻게 했는지 적어 보세요.",
      "네가 마법의 약을 만든다면 어떤 효과가 있으면 좋겠니? 네가 만든 약을 몇 문장으로 적어 보세요."] };
ACT["M4011"] = { s: "Mr. Caruthers wants Abigail and her friends to travel back in time to keep history on track. In this book, he asks the third-graders to convince President Lincoln not to quit abolishing slavery.",
  q: ["What do the third-graders travel back in time to do?",
      "Have you ever tried to convince someone to keep going?",
      "What person from history would you like to meet?"],
  h: ["3학년 아이들은 시간을 거슬러 가서 무엇을 하나요?",
      "너는 누군가에게 포기하지 말라고 설득해 본 적이 있니?",
      "너는 역사 속 어떤 인물을 만나 보고 싶니?"] };
ACT["M4012"] = { s: "This book introduces the history of Earth's observation of the red planet since ancient times. The book explores the results of modern scientific studies carried out by telescopes, satellites, and landing probes. It also speculates on a future human landing.",
  q: ["What tools have scientists used to study Mars, according to this book? Explain in a few sentences.",
      "Have you ever looked at the stars or planets in the sky? Write about what you saw or wondered.",
      "Do you think people will land on Mars one day? Write your opinion and why you think so."],
  h: ["이 책에 따르면 과학자들은 화성을 연구하기 위해 어떤 도구를 썼나요? 몇 문장으로 설명해 보세요.",
      "너는 밤하늘의 별이나 행성을 본 적이 있니? 무엇을 보았고 무엇이 궁금했는지 적어 보세요.",
      "언젠가 사람이 화성에 착륙할 수 있을 것 같니? 네 생각과 이유를 적어 보세요."] };
ACT["M4013"] = { s: "Gooney Bird Greene loves to be the center of attention. She likes to entertain her teacher and fellow second-graders by telling true stories about herself, including how she got her unique name. Book #1",
  q: ["What does Gooney Bird like to tell her classmates?",
      "Do you like telling stories about yourself?",
      "What true story about you would you like to tell your class?"],
  h: ["구니 버드는 반 친구들에게 무엇을 즐겨 이야기하나요?",
      "너는 네 이야기를 하는 것을 좋아하니?",
      "네가 반 친구들에게 들려주고 싶은 너에 관한 진짜 이야기는 무엇이니?"] };
ACT["M4014"] = { s: "While staying at the beach for the summer, Polly and her younger brother Sam find a message in a bottle, providing them and their brother with exciting and scary adventures.",
  q: ["What do Polly and Sam find at the beach?",
      "Have you ever found something surprising outside?",
      "What would you do if you found a message in a bottle?"],
  h: ["폴리와 샘은 바닷가에서 무엇을 발견하나요?",
      "너는 밖에서 놀라운 것을 발견해 본 적이 있니?",
      "네가 병 속 편지를 발견한다면 어떻게 할 거니?"] };
ACT["M4015"] = { s: "The Little House first stood in the country. But when the city, with all its buildings and traffic, gradually grows around her, the house feels unhappy.",
  q: ["How does the Little House's feeling change from the beginning of the story to later, according to the summary? Explain what causes that change.",
      "Have you ever watched a quiet place slowly change and become busier? Write about what you noticed.",
      "If you were the Little House, what would you want someone to do to help you? Write your idea."],
  h: ["리틀 하우스의 마음은 이야기 처음부터 나중까지 어떻게 달라지나요? 무엇이 그 변화를 만들었는지 설명해 보세요.",
      "너는 조용하던 곳이 점점 바빠지는 것을 본 적이 있니? 무엇을 보았는지 적어 보세요.",
      "네가 리틀 하우스라면 누군가 너를 위해 무엇을 해 주면 좋겠니? 네 생각을 적어 보세요."] };
ACT["M4016"] = { s: "Ms. Frizzle takes her class to Antarctica to learn about penguins, icebergs, and the South Pole.",
  q: ["Where does Ms. Frizzle take her class in this book?",
      "Have you ever learned about a cold place?",
      "What do you want to know about penguins?"],
  h: ["프리즐 선생님은 반 친구들을 어디로 데려가나요?",
      "너는 추운 곳에 대해 배운 적이 있니?",
      "너는 펭귄에 대해 무엇이 궁금하니?"] };
ACT["M4017"] = { s: "Amber is in deep trouble. She finds her schoolwork is suffering. She is unhappy with her mom dating someone.",
  q: ["What two problems does Amber have in this book?",
      "Has your schoolwork ever gotten hard because of something else going on?",
      "What do you do to make your schoolwork better?"],
  h: ["앰버는 이 책에서 어떤 두 가지 문제를 겪나요?",
      "다른 일 때문에 공부가 힘들어진 적이 있니?",
      "공부를 더 잘하기 위해 너는 무엇을 하니?"] };
ACT["M4018"] = { s: "This book looks at the history of ballet and the story of Swan Lake.",
  q: ["What two things does this book teach about, based on the summary? Explain what you might learn from each part.",
      "Have you ever watched or tried a dance like ballet? Write about that experience.",
      "If you could watch one famous ballet, would it be Swan Lake or another one? Write your opinion and why."],
  h: ["이 책은 요약에 따르면 어떤 두 가지를 다루나요? 각 부분에서 무엇을 배울 수 있을지 설명해 보세요.",
      "너는 발레 같은 춤을 보거나 춰 본 적이 있니? 그 경험을 적어 보세요.",
      "네가 유명한 발레 공연을 하나 본다면 백조의 호수를 보겠니, 다른 것을 보겠니? 네 생각과 이유를 적어 보세요."] };
ACT["M4019"] = { s: "Garfield the cat and Odie the dog accidentally get locked in the museum one night, and strange things start happening.",
  q: ["Where do Garfield and Odie get locked in?",
      "Have you ever been somewhere strange at night?",
      "What would you do if you were locked in a museum?"],
  h: ["가필드와 오디는 어디에 갇히게 되나요?",
      "너는 밤에 낯선 곳에 있어 본 적이 있니?",
      "네가 박물관에 갇힌다면 무엇을 할 거니?"] };
ACT["M4020"] = { s: "Abigail and her friends have to convince Professor Bell not to give up on his invention, the telephone.",
  q: ["What invention does Professor Bell almost give up on in this book? Explain why the kids need to stop him.",
      "Have you ever wanted to give up on something you were working on? Write about what happened.",
      "What would you say to Professor Bell to convince him not to give up? Write your own speech."],
  h: ["벨 교수는 이 책에서 어떤 발명품을 거의 포기하려 하나요? 아이들이 왜 그를 막아야 하는지 설명해 보세요.",
      "너는 무언가를 하다가 포기하고 싶었던 적이 있니? 그때 이야기를 적어 보세요.",
      "네가 벨 교수에게 포기하지 말라고 한다면 어떤 말을 하고 싶니? 네가 할 말을 적어 보세요."] };
ACT["M4021"] = { s: "Although wetlands don't necessarily need to be covered in water all year long, most areas are pretty wet. Whether they are freshwater or tidal, they play a key role in the health of the Earth.",
  q: ["What role do wetlands play, according to this book? Explain in a few sentences.",
      "Have you ever visited a wet, natural place like a marsh, pond, or riverbank? Write about what you saw.",
      "Why do you think it is important to protect wetlands? Write your opinion."],
  h: ["이 책에 따르면 습지는 어떤 역할을 하나요? 몇 문장으로 설명해 보세요.",
      "너는 늪이나 연못, 강가처럼 물기 많은 자연을 가 본 적이 있니? 무엇을 보았는지 적어 보세요.",
      "습지를 보호하는 것이 왜 중요하다고 생각하니? 네 생각을 적어 보세요."] };
ACT["M4022"] = { s: "A young girl named Mary Lennox arrives in Yorkshire to live with her uncle when her parents die. With the help of her friends and her sickly cousin, she transforms the secret garden, which she found in her uncle's mansion, into a place of beauty and happiness.",
  q: ["What does Mary Lennox do to the secret garden with the help of her friends and cousin? Explain in a few sentences.",
      "Have you ever worked with a friend or family member to fix up or take care of a place? Write about it.",
      "If you found a secret, hidden garden, what would you want to do with it? Write your idea."],
  h: ["메리 레녹스는 친구와 사촌의 도움으로 비밀의 화원을 어떻게 바꾸나요? 몇 문장으로 설명해 보세요.",
      "너는 친구나 가족과 함께 어떤 장소를 고치거나 돌본 적이 있니? 그 이야기를 적어 보세요.",
      "네가 숨겨진 비밀 화원을 발견한다면 그곳으로 무엇을 하고 싶니? 네 생각을 적어 보세요."] };
ACT["M4023"] = { s: "On this time-travel day, Abigail and her friends meet Mr. Disney. They discover that Mr. Disney wants to quit making the first animated movie with sound. The kids have to convince him to follow his dream.",
  q: ["What does Mr. Disney want to quit making?",
      "Have you ever wanted to quit something important?",
      "What dream do you want to follow?"],
  h: ["디즈니 씨는 무엇을 만드는 것을 그만두고 싶어하나요?",
      "너는 중요한 일을 그만두고 싶었던 적이 있니?",
      "너는 어떤 꿈을 따라가고 싶니?"] };
ACT["M4024"] = { s: "This book describes what fire is, how it burns, and how fires can both help and harm the areas they affect.",
  q: ["According to this book, how can fire both help and harm the places it touches? Explain with examples from the summary or your own ideas.",
      "Have you ever seen fire, like a campfire or a candle? Write about what you saw and how you felt.",
      "Why do you think it is important to be careful with fire? Write your opinion."],
  h: ["이 책에 따르면 불은 닿는 곳에 어떻게 도움도 되고 해도 될 수 있나요? 요약이나 네 생각에서 예를 들어 설명해 보세요.",
      "너는 모닥불이나 촛불 같은 불을 본 적이 있니? 무엇을 보았고 어떤 기분이었는지 적어 보세요.",
      "불을 다룰 때 왜 조심해야 한다고 생각하니? 네 생각을 적어 보세요."] };
ACT["M4025"] = { s: "From eating too much chocolate, Henry breaks out in brown bumps that help him foil some hijackers and teach him a lesson about his behaviors.",
  q: ["What happens to Henry after he eats too much chocolate, and how does it end up helping him? Explain in a few sentences.",
      "Have you ever eaten too much of your favorite food? Write about what happened.",
      "What lesson do you think Henry learns by the end of the book? Write your opinion."],
  h: ["헨리는 초콜릿을 너무 많이 먹은 뒤 어떻게 되고, 그것이 어떻게 그에게 도움이 되나요? 몇 문장으로 설명해 보세요.",
      "너는 네가 좋아하는 음식을 너무 많이 먹어 본 적이 있니? 그때 무슨 일이 있었는지 적어 보세요.",
      "헨리는 이야기 끝에 어떤 교훈을 얻었을 것 같니? 네 생각을 적어 보세요."] };
ACT["M4026"] = { s: "Ms. Frizzle teaches her class about insects and their world.",
  q: ["What does Ms. Frizzle teach her class about in this book? Write a few sentences about what you think they might learn.",
      "Have you ever looked closely at an insect, like an ant or a butterfly? Write about what you noticed.",
      "What insect do you want to learn more about, and why?"],
  h: ["프리즐 선생님은 이 책에서 반 친구들에게 무엇을 가르치나요? 그들이 무엇을 배웠을지 몇 문장으로 적어 보세요.",
      "너는 개미나 나비 같은 곤충을 자세히 본 적이 있니? 무엇을 알아차렸는지 적어 보세요.",
      "너는 어떤 곤충에 대해 더 알고 싶니? 이유도 적어 보세요."] };
ACT["M4027"] = { s: "A fictional student's report presents information on George Washington Carver, who became an expert on peanuts and other plants, and taught others at the famous college for African Americans.",
  q: ["What was George Washington Carver an expert in, and what did he do with that knowledge? Explain in a few sentences.",
      "Have you ever become really good at something after studying or practicing it a lot? Write about it.",
      "What subject would you like to become an expert in, like Carver did with plants? Write your idea."],
  h: ["조지 워싱턴 카버는 무엇의 전문가였고, 그 지식으로 무엇을 했나요? 몇 문장으로 설명해 보세요.",
      "너는 열심히 공부하거나 연습해서 정말 잘하게 된 것이 있니? 그 이야기를 적어 보세요.",
      "카버가 식물의 전문가가 된 것처럼, 너는 어떤 분야의 전문가가 되고 싶니? 네 생각을 적어 보세요."] };
ACT["M4028"] = { s: "Mr. Fox saves his family and his animal friends when he outsmarts three farmers who are hunting him.",
  q: ["How does Mr. Fox save his family and friends in this book? Explain in a few sentences.",
      "Have you ever had to think of a clever plan to solve a problem? Write about it.",
      "If three farmers were hunting you, what clever plan would you make? Write your idea."],
  h: ["폭스 씨는 이 책에서 어떻게 가족과 친구들을 구하나요? 몇 문장으로 설명해 보세요.",
      "너는 문제를 풀기 위해 영리한 계획을 세워 본 적이 있니? 그 이야기를 적어 보세요.",
      "만약 세 농부가 너를 쫓는다면 너는 어떤 영리한 계획을 세울 거니? 네 생각을 적어 보세요."] };
ACT["M4029"] = { s: "Geronimo desperately wants a relax and goes on vacation. But he finds himself in a flea-ridden old hotel sharing a room with a bunch of Gerbil Scouts. Book #9",
  q: ["Where does Geronimo end up staying on his vacation?",
      "Have you ever gone on a vacation that didn't go as planned?",
      "What is your idea of a perfect vacation?"],
  h: ["제로니모는 휴가에서 어디에 묵게 되나요?",
      "너는 계획대로 되지 않은 휴가를 가 본 적이 있니?",
      "너에게 완벽한 휴가는 어떤 모습이니?"] };
ACT["M4030"] = { s: "This book tells oceans cover 70 percent of the Earth's surface, providing humans with a variety of plant and animal life to learn about.",
  q: ["How much of the Earth's surface do oceans cover, and what do they give us to learn about, according to this book? Explain in a few sentences.",
      "Have you ever visited the ocean or a beach? Write about what you saw there.",
      "What ocean animal or plant would you like to learn more about, and why?"],
  h: ["이 책에 따르면 바다는 지구 표면의 몇 퍼센트를 차지하고, 우리에게 무엇을 배울 거리로 주나요? 몇 문장으로 설명해 보세요.",
      "너는 바다나 해변에 가 본 적이 있니? 그곳에서 무엇을 보았는지 적어 보세요.",
      "너는 어떤 바다 동물이나 식물에 대해 더 알고 싶니? 이유도 적어 보세요."] };
ACT["M4031"] = { s: "Jake Drake, who's been crazy about computers all his life, wants to win the grand prize in the school's first science fair. Now, he must beat the class know-it-alls Marsha and Kevin.",
  q: ["What does Jake want to win, and who does he have to beat to get it? Explain in a few sentences.",
      "Have you ever competed with someone to win a prize or a contest? Write about what happened.",
      "If you entered a science fair, what project would you want to make? Write your idea."],
  h: ["제이크는 무엇을 이기고 싶어하고, 그것을 위해 누구를 이겨야 하나요? 몇 문장으로 설명해 보세요.",
      "너는 상이나 대회를 두고 누군가와 겨뤄 본 적이 있니? 그때 무슨 일이 있었는지 적어 보세요.",
      "네가 과학 대회에 나간다면 어떤 프로젝트를 만들고 싶니? 네 생각을 적어 보세요."] };
ACT["M4032"] = { s: "After the pharaoh dies, Neria's father gives her the job of mummifying the pharaoh's cat, which is still alive.",
  q: ["What job does Neria's father give her?",
      "Have you ever been given a strange or difficult job to do?",
      "What would you do if you had to do Neria's job?"],
  h: ["네리아의 아버지는 그녀에게 어떤 일을 맡기나요?",
      "너는 이상하거나 어려운 일을 맡아 본 적이 있니?",
      "네가 네리아의 일을 맡게 된다면 어떻게 할 거니?"] };
ACT["M4033"] = { s: "This book features humorous episodes that are taken place in the classroom on the thirtieth floor of Wayside School. Book #1",
  q: ["Where does this book take place?",
      "Have you ever heard a funny story about a classroom?",
      "What funny thing could happen in your classroom?"],
  h: ["이 책은 어디에서 일어나는 이야기인가요?",
      "너는 교실에서 일어난 재미있는 이야기를 들어 본 적이 있니?",
      "너의 교실에서는 어떤 재미있는 일이 일어날 수 있을까?"] };
ACT["M4034"] = { s: "This book provides an introduction to scientific concepts involved in individual sports, such as aerodynamics in bicycling, friction in speed skating, and thrust in tennis.",
  q: ["What scientific ideas does this book connect to sports like bicycling, speed skating, and tennis? Explain in a few sentences.",
      "Have you ever played or watched one of these individual sports? Write about your experience.",
      "What sport would you like to understand better using science, and why?"],
  h: ["이 책은 자전거 타기, 스피드 스케이팅, 테니스 같은 운동에 어떤 과학 개념을 연결하나요? 몇 문장으로 설명해 보세요.",
      "너는 이런 개인 운동을 해 보거나 본 적이 있니? 그 경험을 적어 보세요.",
      "너는 어떤 운동을 과학으로 더 잘 이해하고 싶니? 이유도 적어 보세요."] };
ACT["M4035"] = { s: "Rob, who passes the time in his rural Florida community by wood carving, is drawn by his friend, Sistine, into a plan to free a tiger in the cage.",
  q: ["What plan does Sistine draw Rob into? Explain in a few sentences.",
      "Have you ever been convinced by a friend to do something big or brave? Write about it.",
      "Do you think it is right to free an animal from a cage? Write your opinion and why."],
  h: ["시스틴은 롭을 어떤 계획으로 끌어들이나요? 몇 문장으로 설명해 보세요.",
      "너는 친구가 크고 용감한 일을 하자고 설득한 적이 있니? 그 이야기를 적어 보세요.",
      "우리에 갇힌 동물을 풀어 주는 것이 옳다고 생각하니? 네 생각과 이유를 적어 보세요."] };
ACT["M4036"] = { s: "This book describes how Edmund Hillary and Tenzing Norkey became the first human beings to reach the top of the world by climbing Mount Everest.",
  q: ["What did Edmund Hillary and Tenzing Norgay do that no one had done before? Explain in a few sentences.",
      "Have you ever tried something really hard, like climbing or a long walk? Write about what happened.",
      "What is the highest or hardest goal you would like to reach one day? Write your idea."],
  h: ["에드먼드 힐러리와 텐징 노르가이는 이전에 아무도 하지 못한 어떤 일을 해냈나요? 몇 문장으로 설명해 보세요.",
      "너는 오르기나 긴 걷기처럼 정말 힘든 일을 해 본 적이 있니? 그때 무슨 일이 있었는지 적어 보세요.",
      "너는 언젠가 이루고 싶은 가장 높고 어려운 목표가 있니? 네 생각을 적어 보세요."] };
ACT["M4037"] = { s: "Did you know that Leonardo da Vinci who painted the Mona Lisa also invented an early version of a helicopter and a tank, and that he planned to execute the Time Warp Trio for spying on his inventions?",
  q: ["What did Leonardo da Vinci invent, besides painting the Mona Lisa?",
      "Have you ever spied or peeked at something in secret?",
      "What invention would you like to create like da Vinci?"],
  h: ["레오나르도 다빈치는 모나리자를 그린 것 말고 또 무엇을 발명했나요?",
      "너는 몰래 무언가를 훔쳐본 적이 있니?",
      "너는 다빈치처럼 어떤 발명품을 만들고 싶니?"] };
ACT["M4038"] = { s: "Leroy Brown, aka Encyclopedia Brown, uses his computer-like brain to help solve ten puzzling crimes. In this book, Encyclopedia Brown solves ten new baffling mysteries, including The Case of the Talking House.",
  q: ["What is one of the mysteries Encyclopedia Brown solves in this book? Explain what you find interesting about it.",
      "Have you ever used clues to figure something out, like Encyclopedia Brown does? Write about it.",
      "If a house could talk, like in \"The Case of the Talking House,\" what do you think it would say? Write your idea."],
  h: ["백과사전 브라운이 이 책에서 푸는 사건 중 하나는 무엇인가요? 그 사건이 왜 흥미로운지 설명해 보세요.",
      "너는 백과사전 브라운처럼 단서를 가지고 무언가를 알아낸 적이 있니? 그 이야기를 적어 보세요.",
      "\"말하는 집 사건\"처럼 집이 말을 할 수 있다면 무슨 말을 할 것 같니? 네 생각을 적어 보세요."] };
ACT["M4039"] = { s: "This book describe scientific concepts that make it possible for rides at amusement parks to work, focusing on force and motion.",
  q: ["What two scientific ideas does this book focus on to explain how amusement park rides work? Explain in a few sentences.",
      "Have you ever ridden a roller coaster or another amusement park ride? Write about how it felt.",
      "If you could design your own amusement park ride, what would it be like? Write your idea."],
  h: ["이 책은 놀이공원 기구가 작동하는 원리를 설명하기 위해 어떤 두 가지 과학 개념에 집중하나요? 몇 문장으로 설명해 보세요.",
      "너는 롤러코스터나 다른 놀이기구를 타 본 적이 있니? 그때 느낌이 어땠는지 적어 보세요.",
      "네가 놀이기구를 하나 만든다면 어떤 모습일까? 네 생각을 적어 보세요."] };
ACT["M4040"] = { s: "When Garfield and Odie go to a medieval fair with Jon, they get magically transported back to real medieval times.",
  q: ["What happens to Garfield and Odie at the medieval fair? Explain in a few sentences.",
      "Have you ever been to a fair or festival that felt like another time or place? Write about it.",
      "If you were magically sent back to medieval times, what would you want to do there? Write your idea."],
  h: ["가필드와 오디는 중세 축제에서 무슨 일을 겪나요? 몇 문장으로 설명해 보세요.",
      "너는 다른 시대나 장소처럼 느껴지는 축제에 가 본 적이 있니? 그 이야기를 적어 보세요.",
      "네가 마법으로 중세 시대로 보내진다면 그곳에서 무엇을 하고 싶니? 네 생각을 적어 보세요."] };
ACT["M4041"] = { s: "When Thea discovers a treasure map, she drags Geronimo and Trap into a treasure hunt adventure. Book #1",
  q: ["What does Thea find that starts the adventure?",
      "Have you ever gone looking for something hidden?",
      "What treasure would you like to find?"],
  h: ["테아는 무엇을 발견해서 모험이 시작되나요?",
      "너는 숨겨진 것을 찾아본 적이 있니?",
      "너는 어떤 보물을 찾고 싶니?"] };
ACT["M4042"] = { s: "Hannah, a blind girl living in Michigan in the late 19th century, doesn't go to school until a new teacher comes to board at their house.",
  q: ["What changes for Hannah when the new teacher comes to live at her house? Explain in a few sentences.",
      "Have you ever had a teacher who changed something important for you? Write about it.",
      "What do you think school might have been like for a blind girl in the late 1800s? Write your ideas."],
  h: ["새 선생님이 한나의 집에 오면서 한나에게 무엇이 달라지나요? 몇 문장으로 설명해 보세요.",
      "너에게 중요한 것을 바꿔 준 선생님이 있었니? 그 이야기를 적어 보세요.",
      "1800년대 말, 앞을 보지 못하는 여자아이에게 학교는 어떤 모습이었을 것 같니? 네 생각을 적어 보세요."] };
ACT["M4043"] = { s: "Abigail and her friends can't believe that Babs Magee has convinced Ben Franklin to quit! They have to stop Babs from making a mess of history and keep it on track.",
  q: ["What has Babs Magee convinced Ben Franklin to do, and why is that a problem for history? Explain in a few sentences.",
      "Have you ever had to fix a mistake that someone else made? Write about it.",
      "If you had to convince Ben Franklin not to quit, what would you say to him? Write your own words."],
  h: ["밥스 마기는 벤 프랭클린에게 무엇을 하도록 설득했고, 그것이 왜 역사에 문제가 되나요? 몇 문장으로 설명해 보세요.",
      "너는 다른 사람이 저지른 실수를 고쳐야 했던 적이 있니? 그 이야기를 적어 보세요.",
      "네가 벤 프랭클린에게 그만두지 말라고 설득한다면 어떤 말을 하고 싶니? 네 말로 적어 보세요."] };
ACT["M4044"] = { s: "This book profiles the life of the Theodore Roosevelt, from his sickly childhood, which he over came to become a robust outdoorsman, the 26th president of the United States.",
  q: ["How does Theodore Roosevelt's life change from his childhood to becoming president? Explain in a few sentences.",
      "Have you ever overcome being sick or weak to become stronger at something? Write about it.",
      "What do you admire most about Theodore Roosevelt's story? Write your opinion."],
  h: ["시어도어 루스벨트의 삶은 어린 시절부터 대통령이 되기까지 어떻게 달라지나요? 몇 문장으로 설명해 보세요.",
      "너는 아프거나 약했던 것을 이겨 내고 더 강해진 적이 있니? 그 이야기를 적어 보세요.",
      "시어도어 루스벨트의 이야기에서 너는 무엇이 가장 대단하다고 느껴지니? 네 생각을 적어 보세요."] };
ACT["M4045"] = { s: "Allen Brewster turns himself into a human plant as part of a project for the Science Fair.",
  q: ["What does Allen Brewster do for his Science Fair project? Explain in a few sentences based on the summary.",
      "Have you ever done a science project you were proud of or nervous about? Write about it.",
      "If you could turn into anything for a science project, what would you choose? Write your idea."],
  h: ["앨런 브루스터는 과학 대회 프로젝트로 무엇을 하나요? 요약을 바탕으로 몇 문장으로 설명해 보세요.",
      "너는 자랑스럽거나 긴장되었던 과학 프로젝트를 해 본 적이 있니? 그 이야기를 적어 보세요.",
      "과학 프로젝트를 위해 무엇으로 변할 수 있다면 너는 무엇을 고를 거니? 네 생각을 적어 보세요."] };
ACT["M4046"] = { s: "Thanks to his clever slave, forgetful Archimedes creates one amazing invention after another in order to foil the attack of the Romans.",
  q: ["Who helps Archimedes create his inventions?",
      "Have you ever forgotten something important, like Archimedes does?",
      "What invention would you make to stop an attack?"],
  h: ["아르키메데스가 발명품을 만들도록 누가 도와주나요?",
      "너는 아르키메데스처럼 중요한 것을 잊어버린 적이 있니?",
      "너라면 공격을 막기 위해 어떤 발명품을 만들 거니?"] };
ACT["M4047"] = { s: "Clementine is shocked at the news that her favorite teacher, Mr. D'Matz, will be leaving for a trip to Egypt and be absent for the remainder of the year. She devises a scheme to get rid of the substitute to get Mr. D'Matz to stay.",
  q: ["What scheme does Clementine come up with, and why does she make this plan? Explain in a few sentences.",
      "Have you ever been upset that a favorite teacher or person was leaving? Write about how you felt.",
      "Do you think Clementine's plan is a good idea? Write your opinion and why."],
  h: ["클레멘타인은 어떤 계획을 세우고, 왜 그런 계획을 세우나요? 몇 문장으로 설명해 보세요.",
      "너는 좋아하는 선생님이나 사람이 떠난다는 것에 속상했던 적이 있니? 그때 기분이 어땠는지 적어 보세요.",
      "클레멘타인의 계획이 좋은 생각이라고 생각하니? 네 생각과 이유를 적어 보세요."] };
ACT["M4048"] = { s: "This book narrates the preparations and activities which culminated in man's first landing on the moon in July 1969.",
  q: ["What event does this book tell the story of, and when did it happen? Explain in a few sentences.",
      "Have you ever watched or heard about a big, historic moment? Write about it.",
      "If you could travel to the moon, what would you want to do or see there? Write your idea."],
  h: ["이 책은 어떤 사건을 이야기하고, 그 일은 언제 일어났나요? 몇 문장으로 설명해 보세요.",
      "너는 크고 역사적인 순간을 보거나 들어 본 적이 있니? 그 이야기를 적어 보세요.",
      "네가 달에 갈 수 있다면 그곳에서 무엇을 하거나 보고 싶니? 네 생각을 적어 보세요."] };
ACT["M4049"] = { s: "Having been changed into a frog by a hag, a frog-prince makes the best of his new life as he mates, raises a family.",
  q: ["What is the frog-prince's new life like?",
      "Have you ever had to start a new life or situation you didn't choose?",
      "What would you do if you turned into a frog?"],
  h: ["개구리 왕자의 새로운 삶은 어떤 모습인가요?",
      "너는 네가 고르지 않은 새로운 상황을 시작해야 했던 적이 있니?",
      "네가 개구리로 변한다면 무엇을 할 거니?"] };
ACT["M4050"] = { s: "Deserts may seem like harsh places, but they support plant and animal life. This book describes hot and cold deserts alike, as well as semi-arid and coastal deserts.",
  q: ["What kinds of deserts does this book describe, and what surprising fact does it tell about them? Explain in a few sentences.",
      "Have you ever visited or seen pictures of a desert? Write about what you saw or imagined.",
      "What plant or animal do you think could survive in a desert, and why?"],
  h: ["이 책은 어떤 종류의 사막들을 설명하고, 사막에 대해 어떤 놀라운 사실을 알려주나요? 몇 문장으로 설명해 보세요.",
      "너는 사막에 가 보거나 사진으로 본 적이 있니? 무엇을 보았거나 상상했는지 적어 보세요.",
      "어떤 식물이나 동물이 사막에서 살아남을 수 있을 것 같니? 이유도 적어 보세요."] };
ACT["M4051"] = { s: "When the Grace children go to stay at their Great Aunt Lucinda's worn Victorian house, they discover a field guide to faeries and other creatures and begin to have some unusual experiences.",
  q: ["What do the Grace children discover at their great aunt's house? Explain in a few sentences.",
      "Have you ever stayed at a relative's house and found something interesting or unusual? Write about it.",
      "If you found a field guide to faeries, what creature would you hope to see first? Write your idea."],
  h: ["그레이스 아이들은 큰이모할머니의 집에서 무엇을 발견하나요? 몇 문장으로 설명해 보세요.",
      "너는 친척 집에 머물면서 흥미롭거나 특이한 것을 발견해 본 적이 있니? 그 이야기를 적어 보세요.",
      "네가 요정 도감을 발견한다면 어떤 생명체를 가장 먼저 보고 싶니? 네 생각을 적어 보세요."] };
ACT["M4052"] = { s: "Jake plans to get rid of his goody-goody reputation. And when he is called into the principal's office, he does as his plan. But maybe, he's gone too far?",
  q: ["What is Jake's plan, and what happens when he tries to carry it out? Explain in a few sentences.",
      "Have you ever tried to change how people see you? Write about what you did.",
      "Do you think Jake goes too far with his plan? Write your opinion and why."],
  h: ["제이크의 계획은 무엇이고, 그것을 실행하려 할 때 무슨 일이 일어나나요? 몇 문장으로 설명해 보세요.",
      "너는 사람들이 너를 보는 방식을 바꾸려 해 본 적이 있니? 그때 무엇을 했는지 적어 보세요.",
      "제이크가 계획을 너무 지나치게 실행했다고 생각하니? 네 생각과 이유를 적어 보세요."] };
ACT["M4053"] = { s: "This book shows tropical and temperate rainforests and the differences between these two unique biomes. Rainforests are filled with wonder and mystery.",
  q: ["What are the two kinds of rainforests this book talks about, and how are they different? Explain in a few sentences.",
      "Have you ever seen a rainforest, in real life or in pictures or videos? Write about what you saw.",
      "What mystery or wonder of the rainforest would you most like to explore, and why?"],
  h: ["이 책이 이야기하는 두 가지 열대우림은 무엇이고, 어떻게 다른가요? 몇 문장으로 설명해 보세요.",
      "너는 열대우림을 실제로나 사진, 영상으로 본 적이 있니? 무엇을 보았는지 적어 보세요.",
      "열대우림의 어떤 신비로움을 가장 탐험해 보고 싶니? 이유도 적어 보세요."] };
ACT["M4054"] = { s: "A prince and his whipping boy have many adventures when they trade places by accident.",
  q: ["What happens by accident to the prince and his whipping boy?",
      "Have you ever traded places or roles with someone, even for fun?",
      "What would you like or dislike about trading places with a prince?"],
  h: ["왕자와 매맞는 소년에게 우연히 무슨 일이 일어나나요?",
      "너는 재미로라도 누군가와 자리를 바꿔 본 적이 있니?",
      "왕자와 자리를 바꾼다면 무엇이 좋고 무엇이 싫을 것 같니?"] };
ACT["M4055"] = { s: "Fourth-grader Hank is excitedly preparing for a magic show at the Rock 'N Bowl with his friends, Ashley and Frankie. But his creative alternative to an English essay lands him in detention, and he is grounded the week of the show. Book #1",
  q: ["Why does Hank end up in detention and grounded during the week of his magic show? Explain in a few sentences.",
      "Have you ever gotten into trouble for a creative idea that didn't turn out the way you planned? Write about it.",
      "If you were Hank, what would you do to still be part of the magic show? Write your idea."],
  h: ["행크는 마술쇼가 있는 주에 왜 벌을 받고 외출 금지가 되나요? 몇 문장으로 설명해 보세요.",
      "너는 창의적인 생각이 계획대로 되지 않아 곤란해진 적이 있니? 그 이야기를 적어 보세요.",
      "네가 행크라면 마술쇼에 참여하기 위해 무엇을 할 거니? 네 생각을 적어 보세요."] };
ACT["M4056"] = { s: "This book profiles Amelia Earhart, who was the first woman to fly solo across the Atlantic Ocean.",
  q: ["What did Amelia Earhart do that no woman had done before? Explain in a few sentences.",
      "Have you ever wanted to be the first person to do something? Write about your idea.",
      "What do you think it takes to be brave like Amelia Earhart? Write your opinion."],
  h: ["아멜리아 에어하트는 여성 최초로 어떤 일을 해냈나요? 몇 문장으로 설명해 보세요.",
      "너는 무언가를 처음으로 해내는 사람이 되고 싶었던 적이 있니? 네 생각을 적어 보세요.",
      "아멜리아 에어하트처럼 용감해지려면 무엇이 필요하다고 생각하니? 네 생각을 적어 보세요."] };
ACT["M4057"] = { s: "When a 12-year-old boy gets Grandpa's old lawnmower, he begins mowing lawns and earns a bit of money. Then a neighbor convinces the boy to expand his summer lawn mowing business. He accepts the offer and quickly learns about the beauty of capitalism.",
  q: ["How does the boy's lawn mowing turn into a bigger business? Explain in a few sentences.",
      "Have you ever earned money by doing a small job? Write about what you did.",
      "If you started your own small business like the boy in this book, what would it be? Write your idea."],
  h: ["소년의 잔디 깎기는 어떻게 더 큰 사업으로 커지나요? 몇 문장으로 설명해 보세요.",
      "너는 작은 일을 해서 돈을 벌어 본 적이 있니? 무엇을 했는지 적어 보세요.",
      "이 책의 소년처럼 네가 작은 사업을 시작한다면 어떤 사업을 하고 싶니? 네 생각을 적어 보세요."] };
ACT["M4058"] = { s: "This book tells the powerful forces of water as it pertains to floods and blizzards.",
  q: ["How does this book connect floods and blizzards through the power of water? Explain in a few sentences.",
      "Have you ever experienced a big storm, flood, or snowstorm? Write about what happened.",
      "What do you think people should do to stay safe during a flood or blizzard? Write your ideas."],
  h: ["이 책은 물의 힘을 통해 홍수와 눈보라를 어떻게 연결하나요? 몇 문장으로 설명해 보세요.",
      "너는 큰 폭풍이나 홍수, 눈보라를 겪어 본 적이 있니? 그때 무슨 일이 있었는지 적어 보세요.",
      "홍수나 눈보라에서 안전하게 지내려면 어떻게 해야 한다고 생각하니? 네 생각을 적어 보세요."] };
ACT["M4059"] = { s: "Ten-year-old India Opal Buloni describes her first summer in the town of Naomi, Florida, and all the good things that happen to her because of her dog Winn-Dixie.",
  q: ["What happens to Opal because of her dog Winn-Dixie?",
      "Have you ever had a pet that brought good things into your life?",
      "What would you name a dog if you had one, and why?"],
  h: ["오팔에게는 강아지 윈딕시 덕분에 무슨 일이 일어나나요?",
      "너의 삶에 좋은 일을 가져다준 반려동물이 있었니?",
      "네가 강아지를 키운다면 어떤 이름을 지어 주고 싶니? 이유도 적어 보세요."] };
ACT["M4060"] = { s: "This book is a brief biography of the woman who lived for other people.",
  q: ["What does the phrase \"lived for other people\" suggest Clara Barton spent her life doing? Explain your thinking in a few sentences.",
      "Have you ever done something kind for other people, without expecting anything back? Write about it.",
      "What do you think it means to live for other people? Write your opinion."],
  h: ["\"다른 사람을 위해 살았다\"는 말은 클라라 바튼이 삶을 어떻게 보냈다는 뜻일까요? 몇 문장으로 네 생각을 설명해 보세요.",
      "너는 보답을 바라지 않고 다른 사람에게 친절을 베푼 적이 있니? 그 이야기를 적어 보세요.",
      "\"다른 사람을 위해 산다\"는 것은 어떤 의미라고 생각하니? 네 생각을 적어 보세요."] };
