// 간이 학습 질문 — Book No. S20 묶음. 사람이 아니라 AI 가 한 번 쓰고 굳힌 파일이다.
window.ACT = window.ACT || {};
var ACT = window.ACT;
ACT["S2001"] = { s: "Amazing amphibians jump from the pages of this easy nonfiction reader featuring incredible cut-paper frogs in every color, shape, and size.",
  q: ["이 책에 나온 개구리 그림 중에서 어떤 색이나 모양이 가장 기억에 남나요?",
      "나는 개구리를 실제로 본 적이 있나요? 어디에서 보았나요?",
      "내가 좋아하는 개구리 색깔이나 모양을 한 가지 적어 보세요."],
  h: ["", "", ""] };
ACT["S2002"] = { s: "This book explains what stars are, and shows what people have thought about them in different times and places.",
  q: ["What have people thought about stars in different times and places?",
      "Have you ever looked up at the stars at night?",
      "Write one thing you wonder about stars."],
  h: ["사람들은 시대와 장소에 따라 별을 어떻게 생각해 왔나요?",
      "나는 밤에 별을 올려다본 적이 있나요?",
      "별에 대해 내가 궁금한 것을 한 가지 적어 보세요."] };
ACT["S2003"] = { s: "The 100th day of school at Frank N. Stein Elementary School is the best day of the year for all the monsters except Jane Brain. This book shows us fun and spooky ways of counting to one hundred.",
  q: ["What are some spooky ways this book shows for counting to one hundred?",
      "Have you ever celebrated the 100th day of school?",
      "Write one spooky or fun way you would like to count to one hundred."],
  h: ["이 책은 백까지 세는 무섭고 재미있는 방법으로 무엇을 보여 주나요?",
      "나는 학교에서 100일째 되는 날을 기념해 본 적이 있나요?",
      "내가 백까지 세어 보고 싶은 재미있는 방법을 한 가지 적어 보세요."] };
ACT["S2004"] = { s: "Have you ever seen a hailstone with a turtle frozen inside? Hard to believe but it's true. The weather can be very weird. Let’s learn about the weirdest weather ever and what makes it happen.",
  q: ["What is one weird kind of weather this book talks about?",
      "Have you ever seen strange weather where you live?",
      "Write one weird weather you would like to see."],
  h: ["이 책에 나온 이상한 날씨 중 한 가지는 무엇인가요?",
      "나는 우리 동네에서 이상한 날씨를 본 적이 있나요?",
      "내가 보고 싶은 이상한 날씨를 한 가지 적어 보세요."] };
ACT["S2005"] = { s: "Benny brags about being good at so many things. But when Benny gets to camp, he's not very good at anything. When some campers get into trouble, can Benny be the best at saving the day?",
  q: ["What does Benny brag about being good at?",
      "Have you ever bragged about something you could do?",
      "Write one thing you are good at."],
  h: ["베니는 자신이 무엇을 잘한다고 자랑했나요?",
      "나는 내가 잘하는 것을 자랑해 본 적이 있나요?",
      "내가 잘하는 것을 한 가지 적어 보세요."] };
ACT["S2006"] = { s: "Whales are endlessly interesting to kids. This book presents some of the facts and mysteries about whales, including the different species, what they eat, and how they breathe.",
  q: ["What does this book tell you about how whales breathe?",
      "Have you ever seen a whale, in real life or in a picture?",
      "Write one thing you want to know about whales."],
  h: ["이 책은 고래가 어떻게 숨을 쉬는지 무엇을 알려 주나요?",
      "나는 고래를 실제로 보거나 사진으로 본 적이 있나요?",
      "고래에 대해 내가 궁금한 것을 한 가지 적어 보세요."] };
ACT["S2007"] = { s: "A math teacher coaches the Fractions team and helps them learn while they play to become 'number one' in soccer.",
  q: ["What does the Fractions team learn while they play soccer?",
      "Have you ever played on a sports team?",
      "Write one sport you would like to play."],
  h: ["프랙션스 팀은 축구를 하면서 무엇을 배우나요?",
      "나는 스포츠 팀에서 뛰어 본 적이 있나요?",
      "내가 해 보고 싶은 운동을 한 가지 적어 보세요."] };
ACT["S2008"] = { s: "Danny meets a dinosaur at the museum. They agree that it would be wonderful to play together and spend an unforgettable day in the city.",
  q: ["Where does Danny meet the dinosaur?",
      "Have you ever visited a museum?",
      "Write one thing you would like to do with a dinosaur for a day."],
  h: ["대니는 어디에서 공룡을 만났나요?",
      "나는 박물관에 가 본 적이 있나요?",
      "하루 동안 공룡과 함께 하고 싶은 일을 한 가지 적어 보세요."] };
ACT["S2009"] = { s: "Father Bear returns from a long fishing trip. Little Bear is ready to welcome him--even if he doesn't bring the toy Little Bear has been hoping for!",
  q: ["What did Little Bear hope Father Bear would bring home?",
      "Have you ever waited for someone to come home from a trip?",
      "Write how you welcome someone who comes home."],
  h: ["리틀 베어는 아빠 곰이 무엇을 가져오기를 바랐나요?",
      "나는 누군가 여행에서 돌아오기를 기다려 본 적이 있나요?",
      "누군가 집에 돌아왔을 때 내가 어떻게 맞이하는지 적어 보세요."] };
ACT["S2010"] = { s: "Little Bear’s adventures include Little Bear playing in the snow in the perfect outfit, taking a trip to the moon, and having a wonderful birthday party.",
  q: ["What does Little Bear do in the snow?",
      "Have you ever played outside in the snow?",
      "Write what you would wear to play in the snow."],
  h: ["리틀 베어는 눈 속에서 무엇을 하나요?",
      "나는 눈이 올 때 밖에서 놀아 본 적이 있나요?",
      "눈 속에서 놀 때 내가 입고 싶은 옷을 적어 보세요."] };
ACT["S2011"] = { s: "Little Bear enjoys the summer he spends with his new friend. But when summer ends, his new friend must leave. Little Bear is very sad. Will he find a way to stay close to his new friend even when she is far away?",
  q: ["What does Little Bear do when his new friend must leave?",
      "Have you ever had a friend who moved away or left?",
      "Write one way to stay close to a friend who is far away."],
  h: ["새 친구가 떠나야 할 때 리틀 베어는 어떻게 했나요?",
      "나는 떠나가는 친구가 있었던 적이 있나요?",
      "멀리 있는 친구와 가깝게 지내는 방법을 한 가지 적어 보세요."] };
ACT["S2012"] = { s: "Little Bear likes to visit his grandparents. He likes Grandmother's cooking and Grandfather's hat. But best of all, he loves listening to their stories!",
  q: ["What does Little Bear love best about visiting his grandparents?",
      "Do you like to visit your grandparents?",
      "Write one story you would like your grandparents to tell you."],
  h: ["리틀 베어가 할머니 할아버지 댁에서 가장 좋아하는 것은 무엇인가요?",
      "나는 할머니 할아버지 댁에 가는 것을 좋아하나요?",
      "할머니 할아버지께 듣고 싶은 이야기를 한 가지 적어 보세요."] };
ACT["S2013"] = { s: "Sammy the seal leaves the zoo for the day. He explores the city and learns to read while visiting a class of first-graders.",
  q: ["What does Sammy the seal do when he leaves the zoo?",
      "Have you ever explored a new place?",
      "Write one place you would like to explore for a day."],
  h: ["새미는 동물원을 떠나서 무엇을 하나요?",
      "나는 새로운 곳을 둘러본 적이 있나요?",
      "하루 동안 둘러보고 싶은 곳을 한 가지 적어 보세요."] };
ACT["S2014"] = { s: "Barney is a street peddler who sells fruits and vegetables. He is kind enough to give horseback rides to the children on his route. When progress brings elevated trains to the area, Barney's horse becomes frightened of the noise and runs away.",
  q: ["What does Barney's horse get scared of?",
      "Have you ever seen a scared animal?",
      "Write one loud sound that might scare an animal."],
  h: ["바니의 말은 무엇 때문에 놀랐나요?",
      "나는 놀란 동물을 본 적이 있나요?",
      "동물을 놀라게 할 것 같은 시끄러운 소리를 한 가지 적어 보세요."] };
ACT["S2015"] = { s: "After Harry sees \"real\" horses that are free to run and kick, he gives his imaginary horse its freedom. Will his trusty horse choose to leave him?",
  q: ["What does Harry do after he sees the real horses?",
      "Have you ever had a favorite toy or imaginary friend?",
      "Write what you would do if your toy could run free like a real horse."],
  h: ["해리는 진짜 말들을 본 뒤에 무엇을 했나요?",
      "나는 좋아하는 장난감이나 상상 속 친구가 있었나요?",
      "내 장난감이 진짜 말처럼 자유롭게 뛸 수 있다면 어떻게 할지 적어 보세요."] };
ACT["S2016"] = { s: "An old lighthouse keeper named Sam lives by the seaside with his wife, Rose. Every day, when seagulls come for a visit they feed and treat them like their own children. Will the gulls be able to find Sam and Rose even after they move away?",
  q: ["How do Sam and Rose treat the seagulls?",
      "Have you ever fed or taken care of a wild animal or bird?",
      "Write what you think happens when Sam and Rose move away."],
  h: ["샘과 로즈는 갈매기들을 어떻게 대했나요?",
      "나는 야생 동물이나 새를 먹이거나 돌본 적이 있나요?",
      "샘과 로즈가 이사 가면 어떻게 될지 내 생각을 적어 보세요."] };
ACT["S2017"] = { s: "Mrs. Brice has 25 mice. All of the mice but one do everything together. This clever mouse's difference comes in handy when the mice meet a cat.",
  q: ["How is one of Mrs. Brice's mice different from the others?",
      "Do you have a friend who is different from everyone else in a good way?",
      "Write one way being different can be helpful."],
  h: ["브라이스 부인의 쥐 한 마리는 다른 쥐들과 어떻게 달랐나요?",
      "나에게는 다른 사람들과 다르게 특별한 친구가 있나요?",
      "다른 것이 도움이 될 수 있는 경우를 한 가지 적어 보세요."] };
ACT["S2018"] = { s: "Silly Tilly cannot find her bonnet on Easter morning and nearly fails to let the Easter Bunny into the house.",
  q: ["What does Tilly lose on Easter morning?",
      "Have you ever lost something important right before you needed it?",
      "Write one thing you do when you cannot find something."],
  h: ["틸리는 부활절 아침에 무엇을 잃어버렸나요?",
      "나는 꼭 필요할 때 중요한 물건을 잃어버린 적이 있나요?",
      "물건을 찾지 못할 때 내가 하는 일을 한 가지 적어 보세요."] };
ACT["S2019"] = { s: "Silly Tilly is so forgetful that she even forgets it is Valentine's Day.",
  q: ["What does Silly Tilly forget in this book?",
      "Have you ever forgotten a special day?",
      "Write one thing you could do to remember a special day."],
  h: ["실리 틸리는 이 책에서 무엇을 잊어버렸나요?",
      "나는 특별한 날을 잊어버린 적이 있나요?",
      "특별한 날을 기억하기 위해 내가 할 수 있는 일을 한 가지 적어 보세요."] };
ACT["S2020"] = { s: "Oscar Otter is building his very own slide, far up in the mountains so that no one can bother him. But the sly fox, his enemy, is watching him.",
  q: ["What is Oscar Otter building in the mountains?",
      "Have you ever built something you were proud of?",
      "Write what you think the fox might do."],
  h: ["오스카 오터는 산속에서 무엇을 만들고 있나요?",
      "나는 자랑스러워하는 무언가를 만들어 본 적이 있나요?",
      "여우가 어떻게 할 것 같은지 내 생각을 적어 보세요."] };
ACT["S2021"] = { s: "Silly Tilly Mole, who is forgetful, is on hand to ruin her Thanksgiving dinner. But her friends rescue her with the tasty treats they bring.",
  q: ["How do Tilly's friends help her on Thanksgiving?",
      "Have your friends ever helped you when something went wrong?",
      "Write one dish you would like to bring to a Thanksgiving dinner."],
  h: ["틸리의 친구들은 추수감사절에 어떻게 그녀를 도와주었나요?",
      "무언가 잘못되었을 때 친구들이 나를 도와준 적이 있나요?",
      "추수감사절 저녁에 내가 가져가고 싶은 음식을 한 가지 적어 보세요."] };
ACT["S2022"] = { s: "Harold is the smallest player on his little league team. He is always left sitting on the bench. One day his coach gives him a chance to play during a very important game.",
  q: ["Why does Harold usually sit on the bench?",
      "Have you ever waited for a chance to show what you can do?",
      "Write what you think Harold does when he finally gets to play."],
  h: ["해럴드는 왜 늘 벤치에 앉아 있었나요?",
      "나는 내 실력을 보여 줄 기회를 기다려 본 적이 있나요?",
      "해럴드가 드디어 경기에 나가면 어떻게 할지 내 생각을 적어 보세요."] };
ACT["S2023"] = { s: "Nancy, who adores stars, is excited about her class trip to the planetarium. But when it starts to rain she is afraid that she might not be able to see the stars.",
  q: ["낸시는 별을 정말 좋아해요. 비가 오면 별을 못 볼까 봐 걱정했지요. 나는 무언가를 못 하게 될까 봐 걱정한 적이 있나요?",
      "나는 별을 본 적이 있나요? 어디에서 보았나요?",
      "내가 가 보고 싶은 천체 관측소(플라네타리움)에서 하고 싶은 것을 적어 보세요."],
  h: ["", "", ""] };
ACT["S2024"] = { s: "Shy classmate Lionel has become Nancy's partner for the school talent show. The only problem is that they don't have any of the same talents. Will they ever come up with a perfect solution for both of them?",
  q: ["낸시와 라이오넬은 장기자랑에서 같은 재주가 없었어요. 두 사람은 어떻게 문제를 해결했을 것 같나요?",
      "나는 친구와 함께 무언가를 준비해 본 적이 있나요?",
      "내가 장기자랑에 나간다면 무엇을 보여 주고 싶은지 적어 보세요."],
  h: ["", "", ""] };
ACT["S2025"] = { s: "When Mother and Father Frog go out for a party, Ms. Turtle comes to babysit the three little frogs. They love her so much because she is the best babysitter ever.",
  q: ["Why do the three little frogs love Ms. Turtle?",
      "Have you ever had a babysitter you liked?",
      "Write one thing a good babysitter should do."],
  h: ["개구리 세 마리는 왜 터틀 선생님을 좋아했나요?",
      "나는 좋아하는 돌봄 선생님이 있었나요?",
      "좋은 돌봄 선생님이 해야 할 일을 한 가지 적어 보세요."] };
ACT["S2026"] = { s: "While Little Bear is tidying up the attic, his grandfather tells him his exploits as a sea captain.",
  q: ["What does Little Bear's grandfather tell him about?",
      "Have you ever heard a story from your grandparents about when they were young?",
      "Write one question you would ask a sea captain."],
  h: ["리틀 베어의 할아버지는 무엇에 대해 이야기해 주었나요?",
      "나는 할머니 할아버지의 젊었을 때 이야기를 들어 본 적이 있나요?",
      "선장님께 묻고 싶은 질문을 한 가지 적어 보세요."] };
ACT["S2027"] = { s: "Sam the lamb is having trouble sneezing. He only gets as far as 'Baa...ahhh...' and can't finish his 'choo'.",
  q: ["What sound can Sam the lamb not finish?",
      "Have you ever had trouble finishing a sneeze?",
      "Write what you think helps Sam finish his sneeze."],
  h: ["샘은 어떤 소리를 끝까지 내지 못했나요?",
      "나는 재채기를 끝까지 하지 못한 적이 있나요?",
      "샘이 재채기를 끝낼 수 있게 도와줄 방법을 적어 보세요."] };
ACT["S2028"] = { s: "Joe's pet dinosaur Betsy is too big to do some activities. Her size causes some trouble. But a formidable task lets her prove that sometimes bigger is better.",
  q: ["What kind of trouble does Betsy's big size cause?",
      "Have you ever had a pet or toy that was too big or too small for something?",
      "Write one good thing about being big."],
  h: ["베시가 몸집이 커서 생긴 문제는 무엇이었나요?",
      "나는 너무 크거나 작아서 불편했던 물건이 있었나요?",
      "몸집이 큰 것의 좋은 점을 한 가지 적어 보세요."] };
ACT["S2029"] = { s: "On a spring vacation, Arthur goes on an overnight camping trip in the woods behind his house. Violet is camping out as well, but her friends don't like Arthur around. So Arthur decides to collect slimy things and surprise her.",
  q: ["What does Arthur collect to surprise Violet?",
      "Have you ever gone camping?",
      "Write one slimy or creepy thing you have seen outside."],
  h: ["아서는 바이올렛을 놀라게 하려고 무엇을 모았나요?",
      "나는 캠핑을 가 본 적이 있나요?",
      "밖에서 본 끈적하거나 신기한 것을 한 가지 적어 보세요."] };
ACT["S2030"] = { s: "It's Christmas. Arthur plans to make his parents special Christmas cookies as a present. But his cookies are hard as rocks!",
  q: ["What happens to Arthur's Christmas cookies?",
      "Have you ever tried to cook or bake something?",
      "Write one gift you would like to make for someone."],
  h: ["아서가 만든 크리스마스 쿠키는 어떻게 되었나요?",
      "나는 요리나 빵 만들기를 해 본 적이 있나요?",
      "누군가에게 만들어 주고 싶은 선물을 한 가지 적어 보세요."] };
ACT["S2031"] = { s: "Arthur and his sister Violet decide to sell all their old toys, even Arthur's Honey Bear, in a Tag Sale. Will Arthur say goodbye to his dear old friend?",
  q: ["What does Arthur decide to sell in the Tag Sale?",
      "Have you ever had to say goodbye to a favorite toy?",
      "Write what you think Arthur decides about Honey Bear."],
  h: ["아서는 중고 장터에서 무엇을 팔기로 했나요?",
      "나는 좋아하는 장난감과 헤어져 본 적이 있나요?",
      "아서가 허니 베어를 어떻게 했을지 내 생각을 적어 보세요."] };
ACT["S2032"] = { s: "Arthur is writing a letter to his pen pal. He writes that he wants to have a little brother. He thinks having little sisters isn't fun at all. They don't do things like karate and wrestling, do they?",
  q: ["What does Arthur write to his pen pal that he wants?",
      "Have you ever written a letter to someone?",
      "Write one thing you would tell a pen pal about yourself."],
  h: ["아서는 펜팔 친구에게 무엇을 갖고 싶다고 썼나요?",
      "나는 누군가에게 편지를 써 본 적이 있나요?",
      "펜팔 친구에게 나에 대해 말해 주고 싶은 것을 한 가지 적어 보세요."] };
ACT["S2033"] = { s: "Arthur is positive that he will win the Super Chimp Comics contest. He's also positive his sister Violet can't read. But Violet can read. She even wins the first-grade reading competition and a prize.",
  q: ["What is Arthur positive about at the start of the book?",
      "Have you ever been surprised by what someone else could do?",
      "Write one thing you are practicing to get better at."],
  h: ["아서는 처음에 무엇을 확신했나요?",
      "나는 누군가의 실력에 놀란 적이 있나요?",
      "내가 더 잘하려고 연습하고 있는 것을 한 가지 적어 보세요."] };
ACT["S2034"] = { s: "Aunt Eater loves mysteries. She sees mysterious adventures everywhere and she sets off to solve the cases.",
  q: ["What does Aunt Eater love to do?",
      "Have you ever tried to solve a mystery?",
      "Write one mystery you would like to solve."],
  h: ["앤트 이터는 무엇을 하는 것을 좋아하나요?",
      "나는 수수께끼를 풀어 본 적이 있나요?",
      "내가 풀어 보고 싶은 수수께끼를 한 가지 적어 보세요."] };
ACT["S2035"] = { s: "The world's greatest detective, Big Max, is off to find a king's missing elephant.",
  q: ["What is Big Max looking for?",
      "Have you ever looked for something that was lost?",
      "Write how you would look for a missing elephant."],
  h: ["빅 맥스는 무엇을 찾고 있나요?",
      "나는 잃어버린 것을 찾아본 적이 있나요?",
      "잃어버린 코끼리를 어떻게 찾을지 적어 보세요."] };
ACT["S2036"] = { s: "Buzby, the cat, goes out to look for his first job and finds a job as a busboy at a hotel. He makes all kinds of mistakes and ends up in a special job.",
  q: ["What job does Buzby first find at the hotel?",
      "Have you ever tried something new and made mistakes while learning?",
      "Write one job you would like to try."],
  h: ["버즈비는 호텔에서 처음 어떤 일을 찾았나요?",
      "나는 새로운 것을 하다가 실수해 본 적이 있나요?",
      "내가 해 보고 싶은 일을 한 가지 적어 보세요."] };
ACT["S2037"] = { s: "Mrs. Meech's blueberry pie is missing. She calls on private eyes Wizard, Skinny, Tubby, and Snitch to help her find out!",
  q: ["What food goes missing in this book?",
      "Have you ever had food go missing that you were saving?",
      "Write who you think took the pie."],
  h: ["이 책에서 어떤 음식이 사라졌나요?",
      "나는 아껴 두었던 음식이 없어진 적이 있나요?",
      "누가 파이를 가져갔을지 내 생각을 적어 보세요."] };
ACT["S2038"] = { s: "Private eyes Wizard, Skinny, Tubby, and Snitch believe boys are better than girls. The girls try to take over the boys' clubhouse and the mystery unfolds.",
  q: ["What do the private eyes believe about boys and girls?",
      "Have you ever disagreed with a friend about who is better at something?",
      "Write what you think about boys and girls being equally good at things."],
  h: ["탐정들은 남자아이와 여자아이에 대해 무엇을 믿었나요?",
      "나는 누가 더 잘하는지 친구와 다퉈 본 적이 있나요?",
      "남자아이와 여자아이가 똑같이 잘할 수 있다는 것에 대한 내 생각을 적어 보세요."] };
ACT["S2039"] = { s: "Finally, Mrs. Rogers has had enough, so Amelia Bedelia must look for a new job. Will she ever find the right place to belong?",
  q: ["What does Amelia Bedelia need to look for in this book?",
      "Have you ever had to look for something new, like a new class or a new team?",
      "Write where you think is the right place for Amelia Bedelia."],
  h: ["아멜리아 베델리아는 이 책에서 무엇을 찾아야 했나요?",
      "나는 새로운 것을 찾아야 했던 적이 있나요?",
      "아멜리아 베델리아에게 알맞은 곳이 어디일지 적어 보세요."] };
ACT["S2040"] = { s: "Frog and Toad set out for adventures in the woods. They are always there for each other.",
  q: ["What kind of friends are Frog and Toad to each other?",
      "Do you have a friend who is always there for you?",
      "Write one adventure you would like to go on with a friend."],
  h: ["개구리와 두꺼비는 서로에게 어떤 친구인가요?",
      "나에게는 항상 곁에 있어 주는 친구가 있나요?",
      "친구와 함께 가 보고 싶은 모험을 한 가지 적어 보세요."] };
ACT["S2041"] = { s: "This book presents five further adventures of two best friends, Frog and Toad. They plant a garden, test their bravery, and share cookies. Whatever they do, they do together.",
  q: ["What are some things Frog and Toad do together in this book?",
      "Have you ever planted something with a friend or family member?",
      "Write one thing you would like to do together with a friend."],
  h: ["개구리와 두꺼비가 이 책에서 함께 한 일은 무엇인가요?",
      "나는 친구나 가족과 함께 무언가를 심어 본 적이 있나요?",
      "친구와 함께 해 보고 싶은 것을 한 가지 적어 보세요."] };
ACT["S2042"] = { s: "Grasshopper is on a journey and meets many busy creatures who wonder why Grasshopper isn't as busy as they are. But, he is happy just walking down the road.",
  q: ["Why are the creatures Grasshopper meets surprised by him?",
      "Do you ever enjoy just walking or taking your time?",
      "Write what makes you feel happy even when you are not busy."],
  h: ["메뚜기가 만난 동물들은 왜 놀랐나요?",
      "나는 그냥 천천히 걷는 것을 즐긴 적이 있나요?",
      "바쁘지 않아도 나를 행복하게 만드는 것을 적어 보세요."] };
ACT["S2043"] = { s: "This book features five humorous tales about Owl and his house where there is always room for visitors.",
  q: ["What kind of house does Owl have?",
      "Do you like having visitors come to your house?",
      "Write one funny thing you think happens in Owl's house."],
  h: ["부엉이의 집은 어떤 집인가요?",
      "나는 우리 집에 손님이 오는 것을 좋아하나요?",
      "부엉이의 집에서 일어날 것 같은 재미있는 일을 적어 보세요."] };
ACT["S2044"] = { s: "The prehistoric police pair, detective Dinosaur and Officer Pterodactyl search for a lost baby and find a home for a stray kitten. But after cracking the case, Detective Dinosaur loses his way in a dark park.",
  q: ["What two things do Detective Dinosaur and Officer Pterodactyl do in this book?",
      "Have you ever helped find something or someone that was lost?",
      "Write what you would do if you lost your way in the dark."],
  h: ["다이너소어 형사와 프테로닥틸 경관은 이 책에서 어떤 두 가지 일을 했나요?",
      "나는 잃어버린 것이나 사람을 찾는 것을 도운 적이 있나요?",
      "어두운 곳에서 길을 잃으면 나는 어떻게 할지 적어 보세요."] };
ACT["S2045"] = { s: "Mr. Ladybug asks Inspector Hopper to solve the mystery of missing Mrs. Ladybug. When they are at the blueberry bushes, they hear a voice crying for help.",
  q: ["Where do Mr. Ladybug and Inspector Hopper hear a voice crying for help?",
      "Have you ever helped someone who was calling for help?",
      "Write who you think is crying for help."],
  h: ["레이디버그 씨와 하퍼 탐정은 어디에서 도와달라는 소리를 들었나요?",
      "나는 도움을 요청하는 사람을 도와준 적이 있나요?",
      "누가 도움을 요청했을지 내 생각을 적어 보세요."] };
ACT["S2046"] = { s: "Amelia goes camping for the first time. She tries her best to do exactly as she is told to do. As usual, everything gets mixed up in the end.",
  q: ["아멜리아는 시키는 대로 하려다가 일이 뒤죽박죽 되었어요. 어떤 일이 뒤죽박죽 되었을지 상상해서 적어 보세요.",
      "나는 캠핑을 가 본 적이 있나요?",
      "캠핑을 갈 때 내가 챙기고 싶은 물건을 한 가지 적어 보세요."],
  h: ["", "", ""] };
ACT["S2047"] = { s: "Mrs. Rogers sends Amelia Bedelia to the station and tells her to pick up the conductor for the school concert. But Amelia brings back the train conductor. As usual, Amelia Bedelia takes everything literally and gets things all mixed up.",
  q: ["Who does Amelia Bedelia bring back instead of the music conductor?",
      "Have you ever misunderstood what someone asked you to do?",
      "Write one word that could be understood in two different ways."],
  h: ["아멜리아 베델리아는 음악 지휘자 대신 누구를 데려왔나요?",
      "나는 누군가의 부탁을 잘못 이해한 적이 있나요?",
      "두 가지 뜻으로 이해될 수 있는 낱말을 한 가지 적어 보세요."] };
ACT["S2048"] = { s: "Amelia Bedelia shows Mr. and Mrs. Rogers her family album and describes what her relatives do. They are amused to meet her special family.",
  q: ["What does Amelia Bedelia show Mr. and Mrs. Rogers?",
      "Does your family have a photo album you like to look at?",
      "Write one family member you would put in a family album."],
  h: ["아멜리아 베델리아는 로저스 부부에게 무엇을 보여 주었나요?",
      "우리 가족에게도 즐겨 보는 사진첩이 있나요?",
      "가족 사진첩에 넣고 싶은 가족 한 명을 적어 보세요."] };
ACT["S2049"] = { s: "Eight baby mice arrive in the mice family, and their father gets to understand why their mother has wanted a bigger house.",
  q: ["Why did the mice mother want a bigger house?",
      "Has your family ever needed more space for something new?",
      "Write one thing a big family needs a lot of."],
  h: ["엄마 쥐는 왜 더 큰 집을 원했나요?",
      "우리 가족도 새로운 것을 위해 더 넓은 공간이 필요했던 적이 있나요?",
      "대가족에게 많이 필요한 것을 한 가지 적어 보세요."] };
ACT["S2050"] = { s: "When Jack and Bunny are having a picnic on the docks, they meet Ramon snooping around looking for his missing lawn chair. The animal detectives set out to solve the case.",
  q: ["What is Ramon looking for when Jack and Bunny meet him?",
      "Have you ever helped a friend look for something they lost?",
      "Write where you think the lawn chair went."],
  h: ["잭과 버니가 라몬을 만났을 때 라몬은 무엇을 찾고 있었나요?",
      "나는 친구가 잃어버린 것을 찾는 걸 도와준 적이 있나요?",
      "정원 의자가 어디로 갔을지 내 생각을 적어 보세요."] };
ACT["S2051"] = { s: "When Melvin's fluffy dice goes missing, Bunny and Jack, the animal detectives, take the case to investigate.",
  q: ["What does Melvin lose in this book?",
      "Have you ever lost a small favorite object?",
      "Write one clue you would look for to find something missing."],
  h: ["멜빈은 이 책에서 무엇을 잃어버렸나요?",
      "나는 아끼는 작은 물건을 잃어버린 적이 있나요?",
      "없어진 물건을 찾을 때 내가 살펴볼 단서를 한 가지 적어 보세요."] };
ACT["S2052"] = { s: "Captain and Matey, two silly pirates who disagree frequently, go on an adventure, together with their faithful parrot. They sing and dance, hunt for buried treasure, and rescue a stranded pirate. In their quest, they find something more important than gold.",
  q: ["What do Captain and Matey find that is more important than gold?",
      "Have you ever gone on an adventure with a friend even though you disagreed sometimes?",
      "Write what you think is more important than gold."],
  h: ["캡틴과 메이티는 금보다 더 중요한 무엇을 찾았나요?",
      "가끔 다투면서도 친구와 함께 모험을 해 본 적이 있나요?",
      "금보다 더 중요하다고 생각하는 것을 적어 보세요."] };
ACT["S2053"] = { s: "Detective Dinosaur and Officer Pterodactyl solve the mystery of the missing hat, the case of the squeaky shoe, and the mystery of the loud clanging at night.",
  q: ["What three mysteries do Detective Dinosaur and Officer Pterodactyl solve?",
      "Have you ever heard a strange noise at night?",
      "Write what you think is making the loud clanging sound."],
  h: ["다이너소어 형사와 프테로닥틸 경관은 어떤 세 가지 수수께끼를 풀었나요?",
      "나는 밤에 이상한 소리를 들어 본 적이 있나요?",
      "시끄러운 쨍그랑 소리를 낸 것이 무엇일지 적어 보세요."] };
ACT["S2054"] = { s: "The regular baseball game is over, but yet to come the annual Big Game between two teams of mice, the Mighty Mites and the Boomers. Excitement is in the air.",
  q: ["What is the name of the two mice baseball teams?",
      "Have you ever felt excited before a big game or event?",
      "Write which team you would want to cheer for and why."],
  h: ["두 쥐 야구팀의 이름은 무엇인가요?",
      "나는 큰 경기나 행사를 앞두고 신났던 적이 있나요?",
      "내가 응원하고 싶은 팀과 그 이유를 적어 보세요."] };
ACT["S2055"] = { s: "This book is a collection of poems about ordinary things that may not be so ordinary at all.",
  q: ["What kind of things do these poems talk about?",
      "Have you ever noticed something ordinary that seemed special?",
      "Write one ordinary thing near you and make it sound special."],
  h: ["이 시들은 어떤 것들에 대해 이야기하나요?",
      "나는 평범해 보이던 것이 특별해 보인 적이 있나요?",
      "내 주변의 평범한 물건을 한 가지 골라 특별하게 표현해 보세요."] };
ACT["S2056"] = { s: "Zounds the vulture announces that trouble is coming. Wizard and his dog Wart get ready for the worst. But when Trouble finally arrives, they are surprised!",
  q: ["How do Wizard and Wart get ready for Trouble?",
      "Have you ever gotten ready for something you thought would be scary?",
      "Write what you think \"Trouble\" turns out to be."],
  h: ["위저드와 워트는 트러블을 맞이할 준비를 어떻게 했나요?",
      "나는 무서울 것 같은 일을 준비해 본 적이 있나요?",
      "'트러블'이 무엇으로 밝혀질지 내 생각을 적어 보세요."] };
ACT["S2057"] = { s: "This book features spooky and funny ghostly tales from folklore.",
  q: ["What kind of tales does this book have?",
      "Have you ever heard a ghost story?",
      "Write one spooky story you know or can imagine."],
  h: ["이 책에는 어떤 이야기들이 담겨 있나요?",
      "나는 귀신 이야기를 들어 본 적이 있나요?",
      "내가 아는 무서운 이야기나 상상한 이야기를 한 가지 적어 보세요."] };
ACT["S2058"] = { s: "This book contains seven scary stories based on traditional stories and folktales from various countries.",
  q: ["Where do the stories in this book come from?",
      "Have you ever heard a scary story from a family member?",
      "Write one thing that scares you a little."],
  h: ["이 책의 이야기들은 어디에서 왔나요?",
      "나는 가족에게 무서운 이야기를 들어 본 적이 있나요?",
      "나를 조금 무섭게 하는 것을 한 가지 적어 보세요."] };
ACT["S2059"] = { s: "Arthur is surprised to find out that Muffy is having her party on the same day as his. All of his friends must decide which party to attend.",
  q: ["What problem do Arthur's friends have about the two parties?",
      "Have you ever had two fun things happen on the same day?",
      "Write which party you would choose and why."],
  h: ["아서의 친구들은 두 파티에 대해 어떤 고민이 있었나요?",
      "나는 같은 날 재미있는 일이 두 가지 겹친 적이 있나요?",
      "내가 어느 파티에 가고 싶은지와 그 이유를 적어 보세요."] };
ACT["S2060"] = { s: "It's almost Valentine's Day. Arthur is determined to crack the case on who his secret admirer is. Can it be Fern or even Sue Ellen?",
  q: ["What is Arthur trying to figure out in this book?",
      "Have you ever received a card or note from someone you didn't know?",
      "Write who you think Arthur's secret admirer is."],
  h: ["아서는 이 책에서 무엇을 알아내려고 했나요?",
      "나는 누가 보냈는지 모르는 카드나 쪽지를 받아 본 적이 있나요?",
      "아서의 비밀 친구가 누구일지 내 생각을 적어 보세요."] };
ACT["S2061"] = { s: "Arthur sees an advertisement for the doggy treat timer. He sets up a plan to earn enough money to buy it for his dog.",
  q: ["What does Arthur want to buy for his dog?",
      "Have you ever saved up money to buy something?",
      "Write one way you could earn money."],
  h: ["아서는 강아지를 위해 무엇을 사고 싶어 했나요?",
      "나는 무언가를 사려고 돈을 모아 본 적이 있나요?",
      "내가 돈을 벌 수 있는 방법을 한 가지 적어 보세요."] };
ACT["S2062"] = { s: "Arthur is having a magic show for the April Fool's Day assembly. But he's a bit worried about remembering his tricks.",
  q: ["What is Arthur worried about before his magic show?",
      "Have you ever been nervous before performing in front of others?",
      "Write one magic trick you would like to perform."],
  h: ["아서는 마술 쇼를 하기 전에 무엇을 걱정했나요?",
      "나는 사람들 앞에서 무언가 할 때 떨렸던 적이 있나요?",
      "내가 해 보고 싶은 마술을 한 가지 적어 보세요."] };
ACT["S2063"] = { s: "It is pouring. Arthur makes efforts to turn the seemingly disastrous family vacation into a success.",
  q: ["What problem does the rain cause for Arthur's family vacation?",
      "Have you ever had a rainy day ruin your plans?",
      "Write one thing you could do on a rainy vacation day."],
  h: ["비는 아서네 가족 여행에 어떤 문제를 일으켰나요?",
      "비 때문에 계획이 망가진 적이 있나요?",
      "비 오는 여행날에 할 수 있는 일을 한 가지 적어 보세요."] };
ACT["S2064"] = { s: "Arthur is excited about a new puppy, Pal. But he gets worried when Pal tears the living room apart and wets on everything.",
  q: ["What trouble does the new puppy Pal cause?",
      "Have you ever had a pet cause trouble at home?",
      "Write what you would teach a new puppy."],
  h: ["새 강아지 팔은 어떤 말썽을 일으켰나요?",
      "나는 우리 집 반려동물 때문에 곤란했던 적이 있나요?",
      "새 강아지에게 가르쳐 주고 싶은 것을 한 가지 적어 보세요."] };
ACT["S2065"] = { s: "What would be better than a sleepover in the backyard with Buster and the Brain? But what thrills Arthur more is the rumor that a spaceship has landed in the neighborhood.",
  q: ["What rumor excites Arthur during the sleepover?",
      "Have you ever had a sleepover with friends?",
      "Write what you would do if a spaceship landed near your house."],
  h: ["잠자리 파티 동안 아서를 신나게 한 소문은 무엇이었나요?",
      "나는 친구들과 함께 잠자리 파티를 해 본 적이 있나요?",
      "우리 집 근처에 우주선이 착륙한다면 나는 어떻게 할지 적어 보세요."] };
ACT["S2066"] = { s: "Arthur's parents tell big news that they are going to have another baby. Arthur isn't sure he is happy about it.",
  q: ["What news do Arthur's parents share with him?",
      "Do you have a younger brother or sister, or would you like one?",
      "Write how you think Arthur feels about the new baby."],
  h: ["아서의 부모님은 어떤 소식을 전했나요?",
      "나에게 동생이 있나요, 아니면 동생이 생기면 좋겠나요?",
      "아서가 새 아기에 대해 어떤 기분일지 적어 보세요."] };
ACT["S2067"] = { s: "It is Halloween! The Halloween party at school gets Arthur a bit frightened. But when D.W. wanders off into the scariest house on the street for trick-or-treating, he gets the courage to go in and rescue her.",
  q: ["What does Arthur do when D.W. wanders into the scariest house?",
      "Have you ever been scared but still helped someone?",
      "Write what you would wear for Halloween."],
  h: ["D.W.가 가장 무서운 집에 들어갔을 때 아서는 어떻게 했나요?",
      "나는 무서웠지만 누군가를 도와준 적이 있나요?",
      "내가 핼러윈에 입고 싶은 옷을 적어 보세요."] };
ACT["S2068"] = { s: "It is almost Christmas, but Arthur hasn't decided what to get for Santa yet.",
  q: ["What has Arthur not decided yet in this book?",
      "Have you ever had trouble deciding what gift to give someone?",
      "Write what you would give Santa if you could."],
  h: ["아서는 이 책에서 아직 무엇을 정하지 못했나요?",
      "나는 선물로 무엇을 줄지 정하기 어려웠던 적이 있나요?",
      "산타에게 선물을 준다면 무엇을 줄지 적어 보세요."] };
ACT["S2069"] = { s: "Arthur kindly helps cleaning around the house before he goes out to play.",
  q: ["What does Arthur do before he goes out to play?",
      "Do you help clean at home?",
      "Write one chore you can do to help your family."],
  h: ["아서는 놀러 나가기 전에 무엇을 했나요?",
      "나는 집에서 청소를 돕나요?",
      "가족을 도울 수 있는 집안일을 한 가지 적어 보세요."] };
ACT["S2070"] = { s: "It's D.W.'s birthday. Arthur gives her the best birthday present ever.",
  q: ["Whose birthday is it in this book?",
      "Have you ever given someone a great surprise gift?",
      "Write what you think Arthur's present for D.W. is."],
  h: ["이 책에서 누구의 생일인가요?",
      "나는 누군가에게 멋진 깜짝 선물을 준 적이 있나요?",
      "아서가 D.W.에게 준 선물이 무엇일지 적어 보세요."] };
ACT["S2071"] = { s: "Arthur and his friends participate in a jelly bean hunt and celebrate Easter.",
  q: ["What do Arthur and his friends hunt for in this book?",
      "Have you ever gone on an egg hunt or treasure hunt?",
      "Write your favorite jelly bean flavor."],
  h: ["아서와 친구들은 무엇을 찾으러 다녔나요?",
      "나는 달걀 찾기나 보물찾기를 해 본 적이 있나요?",
      "내가 가장 좋아하는 젤리빈 맛을 적어 보세요."] };
ACT["S2072"] = { s: "This book provides easy-to-read, and rhyming text that describes a game of hide-and-seek among the animals in a house.",
  q: ["What game do the animals play in this book?",
      "Have you ever played hide-and-seek?",
      "Write your favorite hiding spot."],
  h: ["이 책에서 동물들은 어떤 놀이를 했나요?",
      "나는 숨바꼭질을 해 본 적이 있나요?",
      "내가 가장 좋아하는 숨는 자리를 적어 보세요."] };
ACT["S2073"] = { s: "In a child's imagination, animals do wacky things, such as ducks riding bikes, yaks skiing, and fish eating bagels.",
  q: ["What wacky thing do the ducks do in this book?",
      "Have you ever imagined an animal doing something silly?",
      "Write one silly thing you would like an animal to do."],
  h: ["이 책에서 오리들은 어떤 엉뚱한 일을 하나요?",
      "나는 동물이 엉뚱한 일을 하는 모습을 상상해 본 적이 있나요?",
      "동물이 했으면 하는 엉뚱한 일을 한 가지 적어 보세요."] };
ACT["S2074"] = { s: "Henny Penny and her friends are on their way to tell the king that the sky is falling when they encounter a starving fox.",
  q: ["What do Henny Penny and her friends want to tell the king?",
      "Have you ever believed something was true that turned out not to be?",
      "Write what you would do if you met a hungry fox."],
  h: ["헤니 페니와 친구들은 왕에게 무엇을 말하고 싶었나요?",
      "나는 사실이 아닌 것을 진짜라고 믿었던 적이 있나요?",
      "배고픈 여우를 만나면 나는 어떻게 할지 적어 보세요."] };
ACT["S2075"] = { s: "In this hilarious sequel to the beloved If You Give a Mouse a Cookie, the young host is again run ragged by a surprise guest.",
  q: ["Who is the surprise guest that keeps the host busy?",
      "Have you ever had a guest who wanted a lot of things?",
      "Write what you would give a moose if it visited you."],
  h: ["주인공을 바쁘게 만든 뜻밖의 손님은 누구인가요?",
      "나는 많은 것을 원하는 손님을 맞아 본 적이 있나요?",
      "무스가 우리 집에 온다면 무엇을 줄지 적어 보세요."] };
ACT["S2076"] = { s: "Illustrations and rhyming text describe the activities of animals living in and near a small pond.",
  q: ["What kind of animals live in and near the pond in this book?",
      "Have you ever visited a pond?",
      "Write one animal you would like to see at a pond."],
  h: ["이 책에서 연못 안과 근처에는 어떤 동물들이 살고 있나요?",
      "나는 연못에 가 본 적이 있나요?",
      "연못에서 보고 싶은 동물을 한 가지 적어 보세요."] };
ACT["S2077"] = { s: "As beloved Little Gorilla grows up, he discovers that love grows with him.",
  q: ["What does Little Gorilla discover as he grows up?",
      "Have you noticed how people's love for you grows as you grow up?",
      "Write one way your family shows they love you."],
  h: ["리틀 고릴라는 자라면서 무엇을 깨달았나요?",
      "나는 내가 자라면서 사랑받는 것을 더 느낀 적이 있나요?",
      "우리 가족이 나를 사랑한다는 것을 보여 주는 방법을 한 가지 적어 보세요."] };
ACT["S2078"] = { s: "Three mice discover jars of yellow, blue, and red paint and explore the world of color.",
  q: ["What three colors of paint do the mice discover?",
      "Have you ever mixed colors together?",
      "Write what color you get when you mix two colors."],
  h: ["쥐들은 어떤 세 가지 색의 물감을 발견했나요?",
      "나는 색깔을 섞어 본 적이 있나요?",
      "두 색깔을 섞으면 어떤 색이 되는지 적어 보세요."] };
ACT["S2079"] = { s: "This book tells the story of what happens when Mr. Gumpy allows too many animals to ride in his boat.",
  q: ["검피 아저씨의 배에는 동물들이 너무 많이 탔어요. 무슨 일이 일어났을 것 같나요?",
      "나는 배를 타 본 적이 있나요?",
      "내가 배를 탄다면 함께 태우고 싶은 동물을 한 가지 적어 보세요."],
  h: ["", "", ""] };
ACT["S2080"] = { s: "After helping her mother weed, water, and chase the rabbits from their garden, a young girl imagines her dream garden complete with what she likes.",
  q: ["What does the girl imagine for her dream garden?",
      "Have you ever helped in a garden?",
      "Write what you would want in your dream garden."],
  h: ["여자아이는 꿈의 정원에 무엇이 있으면 좋겠다고 상상했나요?",
      "나는 정원 가꾸는 것을 도와본 적이 있나요?",
      "내 꿈의 정원에 있었으면 하는 것을 적어 보세요."] };
ACT["S2081"] = { s: "This book collects three short stories recounting the adventures of Piggy Pie Po, the smartest, foolishest, messiest pig in the world.",
  q: ["피기 파이 포는 가장 똑똑하고, 가장 엉뚱하고, 가장 지저분한 돼지예요. 나라면 어떤 별명을 갖고 싶나요?",
      "나는 엉뚱한 행동을 해 본 적이 있나요?",
      "내가 가장 좋아하는 돼지 이야기를 상상해서 적어 보세요."],
  h: ["", "", ""] };
ACT["S2082"] = { s: "While kids imitate the sounds of the zookeeper, a wide range of zoo animals make their distinctive sounds for each other.",
  q: ["What do the zoo animals do for each other in this book?",
      "Have you ever visited a zoo?",
      "Write one animal sound you can imitate."],
  h: ["이 책에서 동물원 동물들은 서로에게 무엇을 해 주나요?",
      "나는 동물원에 가 본 적이 있나요?",
      "내가 흉내 낼 수 있는 동물 소리를 한 가지 적어 보세요."] };
ACT["S2083"] = { s: "In this sequel to THE GRUFFALO, the Gruffalo's child goes out to look for the Big Bad Mouse she has heard so much about.",
  q: ["Who does the Gruffalo's child go looking for?",
      "Have you ever gone looking for something you only heard stories about?",
      "Write what you think the Big Bad Mouse looks like."],
  h: ["그루팔로의 아이는 누구를 찾으러 갔나요?",
      "나는 이야기로만 들었던 것을 직접 찾아 나선 적이 있나요?",
      "무서운 생쥐가 어떻게 생겼을지 상상해서 적어 보세요."] };
ACT["S2084"] = { s: "A wizard's hat flies changing people into different animals when it lands on their heads.",
  q: ["What happens when the magic hat lands on someone's head?",
      "Have you ever worn a hat that made you feel different?",
      "Write what animal you would want the magic hat to turn you into."],
  h: ["마법 모자가 누군가의 머리 위에 떨어지면 어떻게 되나요?",
      "나는 모자를 쓰고 다른 기분이 들었던 적이 있나요?",
      "마법 모자가 나를 어떤 동물로 바꿔 주면 좋을지 적어 보세요."] };
ACT["S2085"] = { s: "There are a snoring granny, a dreaming child, a dozing dog and cat in the napping house. All is at peace until the appearance of an unexpected visitor and before you know it, no one is sleeping!",
  q: ["Who is sleeping in the napping house at the start?",
      "Have you ever been woken up by something unexpected?",
      "Write who you think the unexpected visitor is."],
  h: ["낮잠 자는 집에서 처음에 누가 자고 있었나요?",
      "나는 뜻밖의 일로 잠에서 깬 적이 있나요?",
      "뜻밖의 손님이 누구일지 내 생각을 적어 보세요."] };
ACT["S2086"] = { s: "This book tells a child's love of the sun and the amazing ways in which it helps the earth and the life upon it.",
  q: ["이 책은 태양이 지구를 어떻게 돕는지 말해 줘요. 태양이 우리를 돕는 방법 중 아는 것이 있나요?",
      "나는 해가 쨍쨍한 날 무엇을 하는 것을 좋아하나요?",
      "내가 가장 좋아하는 별이나 하늘의 것을 적어 보세요."],
  h: ["", "", ""] };
ACT["S2087"] = { s: "This book follows the progress of a hungry little caterpillar as it eats its way through a large amount of food.",
  q: ["What does the caterpillar do as it grows?",
      "Have you ever eaten a lot of your favorite food in one day?",
      "Write what food you would eat if you were a hungry caterpillar."],
  h: ["애벌레는 자라면서 무엇을 하나요?",
      "나는 좋아하는 음식을 하루에 많이 먹어 본 적이 있나요?",
      "내가 배고픈 애벌레라면 무엇을 먹고 싶은지 적어 보세요."] };
ACT["S2088"] = { s: "A very quiet cricket who wants to rub his wings together to make a sound as do so many other animals finally achieves his wish.",
  q: ["What sound does the cricket want to make?",
      "Have you ever wanted to do something that others could already do?",
      "Write how you think the cricket feels when he finally makes a sound."],
  h: ["귀뚜라미는 어떤 소리를 내고 싶어 했나요?",
      "나는 다른 사람들이 이미 할 수 있는 것을 나도 하고 싶었던 적이 있나요?",
      "귀뚜라미가 드디어 소리를 냈을 때 기분이 어땠을지 적어 보세요."] };
ACT["S2089"] = { s: "This book uses illustrations and simple text to show what the world looks like from a variety of different view.",
  q: ["What does this book show about looking at the world?",
      "Have you ever looked at something from a different view, like up high or down low?",
      "Write what you think the world looks like from up in the sky."],
  h: ["이 책은 세상을 보는 것에 대해 무엇을 보여 주나요?",
      "나는 높은 곳이나 낮은 곳에서 무언가를 다르게 본 적이 있나요?",
      "하늘 위에서 보면 세상이 어떻게 보일지 적어 보세요."] };
ACT["S2090"] = { s: "Willy dreams of being a movie star, a singer, a sumo wrestler, an artist, a giant, and other splendid and active figures.",
  q: ["윌리는 영화배우, 가수, 스모 선수 같은 것을 꿈꿔요. 나는 무엇이 되는 꿈을 꾸나요?",
      "나는 밤에 재미있는 꿈을 꾼 적이 있나요?",
      "내가 되고 싶은 멋진 모습을 한 가지 적어 보세요."],
  h: ["", "", ""] };
ACT["S2091"] = { s: "When aliens come to visit the Earth, it is just because they want to play with freshly laundered underpants of all shapes and sizes.",
  q: ["Why do the aliens come to visit Earth?",
      "Have you ever laughed at a silly idea in a book?",
      "Write one silly thing you think aliens might love."],
  h: ["외계인들은 왜 지구를 찾아왔나요?",
      "나는 책 속의 엉뚱한 생각을 보고 웃은 적이 있나요?",
      "외계인이 좋아할 것 같은 엉뚱한 것을 한 가지 적어 보세요."] };
ACT["S2092"] = { s: "This book describes a celebration for every month of the year.",
  q: ["What does this book describe for every month?",
      "What is your favorite celebration during the year?",
      "Write one celebration you look forward to."],
  h: ["이 책은 매달 무엇을 설명하나요?",
      "나는 일 년 중 어떤 기념일을 가장 좋아하나요?",
      "내가 기다리는 기념일을 한 가지 적어 보세요."] };
ACT["S2093"] = { s: "Duck's truck gets stuck in the muck. Who will help him get it out?",
  q: ["What happens to Duck's truck?",
      "Have you ever gotten stuck somewhere and needed help?",
      "Write who you think helps Duck get his truck out."],
  h: ["오리의 트럭은 어떻게 되었나요?",
      "나는 어딘가에 갇혀서 도움이 필요했던 적이 있나요?",
      "누가 오리의 트럭을 꺼내 주었을지 내 생각을 적어 보세요."] };
ACT["S2094"] = { s: "This book shows vegetables being planted and growing. The vegetables are picked and used in making delicious soup in the end.",
  q: ["What happens to the vegetables at the end of this book?",
      "Have you ever helped grow or pick a vegetable?",
      "Write one vegetable you would put in your own soup."],
  h: ["이 책의 끝에서 채소들은 어떻게 되나요?",
      "나는 채소를 기르거나 딴 적이 있나요?",
      "내가 만드는 수프에 넣고 싶은 채소를 한 가지 적어 보세요."] };
ACT["S2095"] = { s: "Olivia is an energetic pig, whether she is at home getting ready for the day or enjoying the beach.",
  q: ["What two places does Olivia do things in this book?",
      "What do you like to do to get ready for the day?",
      "Write what you would do at the beach."],
  h: ["올리비아는 이 책에서 어떤 두 곳에서 지내나요?",
      "나는 하루를 시작할 때 무엇을 하는 것을 좋아하나요?",
      "바닷가에서 하고 싶은 일을 적어 보세요."] };
ACT["S2096"] = { s: "Archie can't find his cat to enter the neighborhood pet show. What must he do to win a prize when his cat goes missing?",
  q: ["What problem does Archie have before the pet show?",
      "Have you ever lost track of a pet, even for a little while?",
      "Write what you think Archie brings to the pet show instead."],
  h: ["애완동물 대회 전에 아치에게 무슨 문제가 생겼나요?",
      "나는 반려동물을 잠깐이라도 잃어버려 본 적이 있나요?",
      "아치가 대신 무엇을 데려갔을지 내 생각을 적어 보세요."] };
ACT["S2097"] = { s: "One little girl, one smart hat, a sudden gust of wind ? and we're off on a whole hatful of adventures!",
  q: ["What causes Rosie's adventure to begin?",
      "Have you ever chased something that blew away in the wind?",
      "Write where you think Rosie's hat goes."],
  h: ["무엇 때문에 로지의 모험이 시작되었나요?",
      "나는 바람에 날아간 것을 쫓아가 본 적이 있나요?",
      "로지의 모자가 어디로 날아갔을지 내 생각을 적어 보세요."] };
ACT["S2098"] = { s: "This book describes some childhood memories of Boomer Esiason, NFL quarterback.",
  q: ["Whose childhood memories does this book describe?",
      "Have you ever heard a grown-up talk about their childhood?",
      "Write one memory from your own childhood you would like to share."],
  h: ["이 책은 누구의 어린 시절 기억을 그리나요?",
      "나는 어른이 어릴 때 이야기를 들려주는 것을 들어 본 적이 있나요?",
      "다른 사람에게 들려주고 싶은 내 어린 시절 기억을 한 가지 적어 보세요."] };
ACT["S2099"] = { s: "A kind duck is overwhelmed with too much work. Taking pity on him, the rest of the animals get together and chase the lazy farmer out of town.",
  q: ["What do the animals do to help the overworked duck?",
      "Have you ever helped someone who had too much work to do?",
      "Write one way you could help a tired friend."],
  h: ["동물들은 힘들어하는 오리를 돕기 위해 무엇을 했나요?",
      "나는 할 일이 너무 많은 누군가를 도와준 적이 있나요?",
      "지친 친구를 도울 수 있는 방법을 한 가지 적어 보세요."] };
