// 간이 학습 질문 — Book No. S23 묶음. 사람이 아니라 AI 가 한 번 쓰고 굳힌 파일이다.
window.ACT = window.ACT || {};
var ACT = window.ACT;   // catalog.js 와 같은 다리: Node(check-act.js)의 Function 가짜 window 에서는 window.ACT 를 쓰고 그냥 ACT 는 못 쓴다
ACT["S2300"] = { s: "This book recounts the life of Balto, the sled dog who saved Nome, Alaska, in 1925 from a diphtheria epidemic by delivering medicine through a raging snowstorm.",
  q: ["What did Balto deliver through the snowstorm?",
      "Have you ever tried to finish something hard, like Balto did?",
      "Do you think Balto was a hero? Why or why not?"],
  h: ["발토는 눈보라 속에서 무엇을 배달했나요?",
      "너도 발토처럼 힘든 일을 끝까지 해낸 적이 있나요?",
      "발토가 영웅이라고 생각하나요? 왜 그런가요?"] };
ACT["S2301"] = { s: "Alexander Graham Bell is at the World's Fair with his amazing invention but wonders if anyone will stop and listen.",
  q: ["What did Alexander Graham Bell bring to the World's Fair?",
      "Have you ever shown something you made to other people?",
      "Do you think people will stop and listen to Bell's machine? Why?"],
  h: ["알렉산더 그레이엄 벨은 세계 박람회에 무엇을 가져왔나요?",
      "너는 네가 만든 것을 다른 사람에게 보여 준 적이 있나요?",
      "사람들이 벨의 기계 소리에 귀 기울일 것 같나요? 왜 그런가요?"] };
ACT["S2302"] = { s: "This book retells a simple story of Christopher Columbus' first voyage to America.",
  q: ["Where did Christopher Columbus sail to in this book?",
      "Have you ever gone on a long trip?",
      "What do you think was the hardest part of his voyage?"],
  h: ["이 책에서 크리스토퍼 콜럼버스는 어디로 항해했나요?",
      "너는 긴 여행을 떠나 본 적이 있나요?",
      "그의 항해에서 가장 힘들었을 부분은 무엇이었을까요?"] };
ACT["S2303"] = { s: "Little Witch goes to school for the first time and takes her classmates on a broomstick ride.",
  q: ["What did Little Witch do with her classmates?",
      "Do you remember your first day at school?",
      "Would you like to ride a broomstick with Little Witch? Why?"],
  h: ["작은 마녀는 반 친구들과 무엇을 했나요?",
      "너의 학교 첫날이 기억나나요?",
      "작은 마녀와 함께 빗자루를 타고 싶나요? 왜 그런가요?"] };
ACT["S2304"] = { s: "This book introduces dolphins and their physical characteristics, behavior, social structure, intelligence, and interaction with humans.",
  q: ["What did you learn about dolphins in this book?",
      "Have you ever seen a dolphin, in real life or on TV?",
      "What is the most interesting thing about dolphins to you?"],
  h: ["이 책에서 돌고래에 대해 무엇을 알게 되었나요?",
      "너는 실제로나 TV에서 돌고래를 본 적이 있나요?",
      "돌고래에 대해 가장 흥미로운 점은 무엇인가요?"] };
ACT["S2305"] = { s: "Little Witch’s family is not at all helpful when she is learning to read, so she hides her books and reads by flashlight until late at night. She becomes so sleepy that she cannot stay awake during the day.",
  q: ["Why did Little Witch get so sleepy during the day?",
      "Do you like to read books before you sleep?",
      "What advice would you give Little Witch about reading at night?"],
  h: ["작은 마녀는 왜 낮에 그렇게 졸렸나요?",
      "너는 잠자기 전에 책 읽는 것을 좋아하나요?",
      "밤에 책 읽는 작은 마녀에게 어떤 조언을 해 주고 싶나요?"] };
ACT["S2306"] = { s: "This book discusses the kinds of sharks and their behavior.",
  q: ["What kinds of sharks did you read about in this book?",
      "Are you scared of sharks, or do you like them?",
      "What is one new fact about sharks that surprised you?"],
  h: ["이 책에서 어떤 상어들에 대해 읽었나요?",
      "너는 상어가 무섭나요, 아니면 좋아하나요?",
      "상어에 대해 놀라웠던 새로운 사실 한 가지는 무엇인가요?"] };
ACT["S2307"] = { s: "A little girl helps break the spell on her toy nutcracker and changes him into a handsome prince.",
  q: ["What happened to the nutcracker in this story?",
      "Do you have a favorite toy like the nutcracker?",
      "Do you think the girl was brave to help the nutcracker? Why?"],
  h: ["이 이야기에서 호두까기 인형에게 무슨 일이 일어났나요?",
      "너에게도 호두까기 인형처럼 아끼는 장난감이 있나요?",
      "소녀가 호두까기 인형을 도운 것이 용감하다고 생각하나요? 왜 그런가요?"] };
ACT["S2308"] = { s: "Little Witch, as punishment for cleaning up her room, has to stay home on Halloween night, but manages to have a good time anyway.",
  q: ["Why did Little Witch have to stay home on Halloween night?",
      "Have you ever been punished and still had fun?",
      "Do you think the punishment was fair? Why or why not?"],
  h: ["작은 마녀는 왜 핼러윈 밤에 집에 있어야 했나요?",
      "너는 벌을 받으면서도 재미있게 지낸 적이 있나요?",
      "그 벌이 공평했다고 생각하나요? 왜 그런가요?"] };
ACT["S2309"] = { s: "While riding in the car with Buzz and his father, Fly Guy gets blown out the window and comes back by riding in all kinds of vehicles.",
  q: ["What kinds of vehicles did Fly Guy ride to get back home?",
      "Have you ever ridden in a car, bus, or train?",
      "Which vehicle in this book would you like to ride the most?"],
  h: ["플라이 가이는 집에 돌아오기 위해 어떤 탈것들을 탔나요?",
      "너는 자동차나 버스, 기차를 타 본 적이 있나요?",
      "이 책에 나온 탈것 중 가장 타 보고 싶은 것은 무엇인가요?"] };
ACT["S2310"] = { s: "This book follows a female armadillo as she forages for food, builds a home, and prepares for the birth of her baby pups.",
  q: ["What did the mother armadillo do to get ready for her babies?",
      "Have you ever helped get a home ready for a new baby or pet?",
      "What do you think is the hardest part of being an armadillo mom?"],
  h: ["엄마 아르마딜로는 아기를 맞이하기 위해 무엇을 했나요?",
      "너는 새로운 아기나 반려동물을 위해 집을 준비하는 것을 도운 적이 있나요?",
      "아르마딜로 엄마로 사는 것 중 가장 힘든 부분은 무엇일까요?"] };
ACT["S2311"] = { s: "Walter has not only lost a tooth, he's also managed to lose his lost tooth. His chances of getting his quarter look slim, and the tooth fairy assigned to pick up the tooth is in hot water.",
  q: ["What did Walter lose, besides his tooth?",
      "Have you ever lost something important, like a tooth?",
      "How do you think Walter can find his lost tooth?"],
  h: ["월터는 이빨 말고 또 무엇을 잃어버렸나요?",
      "너는 이빨처럼 소중한 것을 잃어버린 적이 있나요?",
      "월터가 잃어버린 이빨을 어떻게 찾을 수 있을까요?"] };
ACT["S2312"] = { s: "Roger's friend Kenneth uses an unusual sea vehicle of his own design to take them to an underwater cave, where a cache of old loot gathered by the mermaids turns out to contain a lot of very valuable, old baseball cards.",
  q: ["What did Roger and Kenneth find in the underwater cave?",
      "Do you collect anything special, like baseball cards?",
      "Would you like to explore an underwater cave? Why or why not?"],
  h: ["로저와 케네스는 물속 동굴에서 무엇을 발견했나요?",
      "너는 야구 카드처럼 특별하게 모으는 것이 있나요?",
      "물속 동굴을 탐험해 보고 싶나요? 왜 그런가요?"] };
ACT["S2313"] = { s: "Otto the alligator and his Uncle Tooth search for a ghost in Boogle Bay.",
  q: ["What are Otto and Uncle Tooth looking for in Boogle Bay?",
      "Have you ever looked for something scary or mysterious?",
      "Do you think they will really find a ghost? Why or why not?"],
  h: ["오토와 투스 삼촌은 부글 만에서 무엇을 찾고 있나요?",
      "너는 무섭거나 신비한 것을 찾아본 적이 있나요?",
      "그들이 정말로 유령을 찾을 것 같나요? 왜 그런가요?"] };
ACT["S2314"] = { s: "Winnie the witch is off to the seaside with her cat Wilbur. While she is having a whale of a time, Wilbur struggles to avoid getting wet.",
  q: ["What did Winnie and Wilbur do at the seaside?",
      "Do you like going to the beach or the sea?",
      "Do you think Wilbur will get wet in the end? Why?"],
  h: ["위니와 윌버는 바닷가에서 무엇을 했나요?",
      "너는 바다나 해변에 가는 것을 좋아하나요?",
      "윌버가 결국 물에 젖을 것 같나요? 왜 그런가요?"] };
ACT["S2315"] = { s: "Winnie the witch zooms into space and finds the perfect planet for a picnic. But she gets into trouble when some naughty space rabbits munch her rocket.",
  q: ["What did the space rabbits do to Winnie's rocket?",
      "Have you ever imagined going to space?",
      "What would you bring on a picnic in space?"],
  h: ["우주 토끼들은 위니의 로켓에 무슨 짓을 했나요?",
      "너는 우주에 가는 것을 상상해 본 적이 있나요?",
      "우주에서 소풍을 간다면 무엇을 가져가고 싶나요?"] };
ACT["S2316"] = { s: "Winnie is getting ready for the Witches' Magic Show. But she accidentally puts her wand in the washing machine with her party dress.",
  q: ["Where did Winnie accidentally put her magic wand?",
      "Have you ever put something in the wrong place by accident?",
      "What do you think will happen to Winnie's wand?"],
  h: ["위니는 실수로 마법 지팡이를 어디에 넣었나요?",
      "너는 실수로 물건을 엉뚱한 곳에 넣은 적이 있나요?",
      "위니의 지팡이는 어떻게 될까요?"] };
ACT["S2317"] = { s: "Dirk Bones, THE GHOSTLY TOMBS newspaper reporter, starts investigating when a ghost family fears that they are being haunted.",
  q: ["What is Dirk Bones's job in this story?",
      "Have you ever been curious about something spooky?",
      "Do you think the ghost family is really being haunted? Why?"],
  h: ["이 이야기에서 더크 본스의 직업은 무엇인가요?",
      "너는 으스스한 것이 궁금했던 적이 있나요?",
      "유령 가족이 정말로 괴롭힘을 당하고 있는 것 같나요? 왜 그런가요?"] };
ACT["S2318"] = { s: "Arthur has to write his own story as a homework assignment. It seems that he isn't exactly sure what to write.",
  q: ["What homework does Arthur have to do in this book?",
      "Have you ever had trouble deciding what to write?",
      "What story would you tell Arthur to write about?"],
  h: ["이 책에서 아서는 어떤 숙제를 해야 하나요?",
      "너는 무엇을 써야 할지 몰라 고민한 적이 있나요?",
      "아서에게 어떤 이야기를 써 보라고 하고 싶나요?"] };
ACT["S2319"] = { s: "Arthur is tired of being the only kid in his class who still has all his baby teeth. He can't wait for his loose tooth to fall out.",
  q: ["Why is Arthur tired of his teeth?",
      "Have you ever lost a tooth? How did it feel?",
      "What advice would you give Arthur while he waits?"],
  h: ["아서는 왜 자기 이빨 때문에 지쳤나요?",
      "너는 이빨이 빠진 적이 있나요? 기분이 어땠나요?",
      "기다리고 있는 아서에게 어떤 조언을 해 주고 싶나요?"] };
ACT["S2320"] = { s: "Nate the Great meets a new case to solve. Rosamond's money box is missing and she wants him to find it.",
  q: ["What is missing in Nate the Great's new case?",
      "Have you ever helped find something that was lost?",
      "Where do you think Rosamond's money box could be?"],
  h: ["네이트 더 그레이트의 새 사건에서 무엇이 사라졌나요?",
      "너는 잃어버린 물건을 찾는 것을 도와준 적이 있나요?",
      "로자먼드의 돈 상자는 어디에 있을 것 같나요?"] };
ACT["S2321"] = { s: "Nearly identical best friends doubt their friendship when they bet on who will lose the next tooth.",
  q: ["두 친구는 무엇을 두고 내기를 했나요?",
      "너는 친한 친구와 다투거나 내기를 한 적이 있나요?",
      "두 친구가 다시 사이좋게 지내려면 어떻게 해야 할까요?"],
  h: ["", "", ""] };
ACT["S2322"] = { s: "This book helps children identify safety issues and avoid potentially dangerous situations that can happen at home.",
  q: ["What kind of safety does this book teach about home?",
      "What rule do you follow to stay safe at home?",
      "What is one dangerous thing you should watch out for at home?"],
  h: ["이 책은 집에서 어떤 안전에 대해 알려 주나요?",
      "너는 집에서 안전하게 지내기 위해 어떤 규칙을 지키나요?",
      "집에서 조심해야 할 위험한 것 한 가지는 무엇인가요?"] };
ACT["S2323"] = { s: "This book teaches children the importance of learning to swim and advises on following safety rules in pools.",
  q: ["What safety rules does this book teach about water?",
      "Can you swim? How did you learn?",
      "What rule do you think is the most important near water?"],
  h: ["이 책은 물에 대해 어떤 안전 규칙을 알려 주나요?",
      "너는 수영을 할 수 있나요? 어떻게 배웠나요?",
      "물 근처에서 가장 중요한 규칙은 무엇이라고 생각하나요?"] };
ACT["S2324"] = { s: "This book advises children to observe safety rules when riding their bikes or traveling in their parents’ cars.",
  q: ["What safety rules does this book talk about on the road?",
      "Do you wear a helmet when you ride a bike?",
      "What safety rule do you always try to follow?"],
  h: ["이 책은 도로에서 어떤 안전 규칙을 이야기하나요?",
      "너는 자전거를 탈 때 헬멧을 쓰나요?",
      "너가 항상 지키려고 하는 안전 규칙은 무엇인가요?"] };
ACT["S2325"] = { s: "This book covers basic issues of safety outdoors and helps children to foster a sense of responsibility.",
  q: ["What does this book teach about staying safe outdoors?",
      "What do you do to stay safe when you play outside?",
      "Why do you think it is important to be responsible outdoors?"],
  h: ["이 책은 밖에서 안전하게 지내는 법에 대해 무엇을 알려 주나요?",
      "너는 밖에서 놀 때 안전을 위해 무엇을 하나요?",
      "밖에서 책임감 있게 행동하는 것이 왜 중요할까요?"] };
ACT["S2326"] = { s: "Children learn all about the benefits of exercise from their grandmother and start to feel much healthier.",
  q: ["Who taught the children about exercise in this book?",
      "What kind of exercise do you like to do?",
      "How do you feel after you exercise?"],
  h: ["이 책에서 아이들에게 운동을 알려 준 사람은 누구인가요?",
      "너는 어떤 운동을 좋아하나요?",
      "운동을 하고 나면 기분이 어떤가요?"] };
ACT["S2327"] = { s: "After visiting the zoo and seeing how the animals groom themselves, two little boys decide practicing personal hygiene is not so bad after all.",
  q: ["What did the boys learn at the zoo about staying clean?",
      "What do you do every day to keep clean?",
      "Why do you think keeping clean is important?"],
  h: ["소년들은 동물원에서 깨끗함에 대해 무엇을 배웠나요?",
      "너는 깨끗하게 지내기 위해 매일 무엇을 하나요?",
      "깨끗하게 지내는 것이 왜 중요할까요?"] };
ACT["S2328"] = { s: "Marta worries about her loose tooth, but her mother explains that everyone loses their baby teeth. She also teaches Marta the importance of looking after her teeth.",
  q: ["What does Marta's mother teach her about teeth?",
      "How do you take care of your teeth?",
      "What would you say to Marta to make her feel better?"],
  h: ["마르타의 엄마는 이빨에 대해 무엇을 가르쳐 주나요?",
      "너는 이빨을 어떻게 관리하나요?",
      "마르타의 기분이 나아지게 어떤 말을 해 주고 싶나요?"] };
ACT["S2329"] = { s: "This book teaches children how to behave and how others react to good manners.",
  q: ["What does this book teach about good manners?",
      "What is one polite word or phrase you use every day?",
      "Why do you think good manners matter?"],
  h: ["이 책은 좋은 예절에 대해 무엇을 알려 주나요?",
      "너가 매일 쓰는 공손한 말 한 가지는 무엇인가요?",
      "좋은 예절이 왜 중요할까요?"] };
ACT["S2330"] = { s: "This book discusses why children want to look after other people.",
  q: ["What does this book talk about, based on the title?",
      "Have you ever helped take care of someone?",
      "Why do you think it feels good to help others?"],
  h: ["제목을 보면 이 책은 무엇에 대한 이야기 같나요?",
      "너는 누군가를 돌봐 준 적이 있나요?",
      "다른 사람을 도우면 왜 기분이 좋아질까요?"] };
ACT["S2331"] = { s: "This book discusses why kids blame other people and how this action affects others.",
  q: ["What does this book explain about blaming other people?",
      "Have you ever blamed someone else by mistake?",
      "What do you think you should do instead of blaming others?"],
  h: ["이 책은 남을 탓하는 것에 대해 무엇을 설명하나요?",
      "너는 실수로 다른 사람을 탓한 적이 있나요?",
      "남을 탓하는 대신 어떻게 해야 할까요?"] };
ACT["S2332"] = { s: "A young girl learns what too many fatty and sugary foods can do to one's health.",
  q: ["What does the girl learn about fatty and sugary foods?",
      "What healthy food do you like to eat?",
      "Why do you think eating well is important?"],
  h: ["소녀는 기름지고 단 음식에 대해 무엇을 배웠나요?",
      "너는 어떤 건강한 음식을 좋아하나요?",
      "잘 먹는 것이 왜 중요할까요?"] };
ACT["S2333"] = { s: "A young girl learns everyone benefits when she lends a helping hand.",
  q: ["What does the girl learn happens when she helps others?",
      "Have you ever helped someone and felt good about it?",
      "Why do you think helping others matters?"],
  h: ["소녀는 남을 도우면 어떤 일이 일어난다고 배웠나요?",
      "너는 누군가를 도와주고 기분이 좋았던 적이 있나요?",
      "다른 사람을 돕는 것이 왜 중요할까요?"] };
ACT["S2334"] = { s: "Joe learns that he can get into trouble when he doesn't listen to others.",
  q: ["What happens to Joe when he doesn't listen?",
      "Do you find it easy or hard to listen to others?",
      "Why do you think listening is important?"],
  h: ["조는 남의 말을 듣지 않으면 어떤 일이 생기나요?",
      "너는 다른 사람의 말을 듣는 것이 쉬운가요, 어려운가요?",
      "남의 말을 듣는 것이 왜 중요할까요?"] };
ACT["S2335"] = { s: "Children in Miss Wade's class learn why it is important to protect nature.",
  q: ["What does Miss Wade's class learn about nature?",
      "What do you do to help protect nature?",
      "Why do you think protecting nature is important?"],
  h: ["웨이드 선생님 반 아이들은 자연에 대해 무엇을 배웠나요?",
      "너는 자연을 지키기 위해 무엇을 하나요?",
      "자연을 지키는 것이 왜 중요할까요?"] };
ACT["S2336"] = { s: "On their visit to a recycling center, the children learn some ways to recycle and reuse things.",
  q: ["What did the children learn at the recycling center?",
      "What do you recycle at home?",
      "Why do you think recycling is a good habit?"],
  h: ["아이들은 재활용 센터에서 무엇을 배웠나요?",
      "너는 집에서 무엇을 재활용하나요?",
      "재활용이 왜 좋은 습관일까요?"] };
ACT["S2337"] = { s: "After his neighbor helps a boy imagine what would happen if the world ran out of water, he puts some water-saving strategies in place.",
  q: ["What did the boy imagine about the world running out of water?",
      "What do you do to save water?",
      "Why do you think saving water is important?"],
  h: ["소년은 세상에 물이 없어진다면 어떨지 어떻게 상상했나요?",
      "너는 물을 아끼기 위해 무엇을 하나요?",
      "물을 아끼는 것이 왜 중요할까요?"] };
ACT["S2338"] = { s: "When literal-minded Amelia plays baseball, things are all mixed up and the results are very funny.",
  q: ["What happens when Amelia Bedelia plays baseball?",
      "Have you ever misunderstood what someone told you to do?",
      "What is the funniest part you can imagine from this story?"],
  h: ["아멜리아 베델리아가 야구를 하면 무슨 일이 벌어지나요?",
      "너는 누군가 시킨 것을 잘못 알아들은 적이 있나요?",
      "이 이야기에서 가장 재미있을 것 같은 부분은 무엇인가요?"] };
ACT["S2339"] = { s: "The Bear family goes on a class trip to a honey farm. Brother is excited to go on a sticky adventure with Mama, Papa, and Sister Bear.",
  q: ["Where does the Bear family go on their class trip?",
      "Have you ever gone on a class trip? Where did you go?",
      "What do you think was the stickiest part of the honey farm trip?"],
  h: ["베어 가족은 소풍으로 어디에 가나요?",
      "너는 소풍을 가 본 적이 있나요? 어디에 갔나요?",
      "꿀 농장 소풍에서 가장 끈적끈적했을 부분은 무엇일까요?"] };
ACT["S2340"] = { s: "Papa, Mama, Brother, and sister decide to clean their house. But they find it tough to get rid of things.",
  q: ["Why is it hard for the Bear family to clean their house?",
      "Do you help clean your house? What do you do?",
      "What is something you find hard to get rid of?"],
  h: ["베어 가족은 왜 집 청소하기가 힘든가요?",
      "너는 집 청소를 돕나요? 무엇을 하나요?",
      "너가 버리기 힘들어하는 물건은 무엇인가요?"] };
ACT["S2341"] = { s: "When the Bear family visits Mrs. Ben's farm, they learn about their life there.",
  q: ["What do the Bear family learn on the farm?",
      "Have you ever visited a farm?",
      "What would you like to see most on a farm?"],
  h: ["베어 가족은 농장에서 무엇을 배우나요?",
      "너는 농장에 가 본 적이 있나요?",
      "농장에서 가장 보고 싶은 것은 무엇인가요?"] };
ACT["S2342"] = { s: "One day, Brother Bear finds a tiny, muddy, helpless kitten. He takes it home and introduces it to his family dog. They decide to keep it as long as the dog doesn't mind!",
  q: ["What does Brother Bear find and bring home?",
      "Have you ever found or wanted to keep an animal?",
      "Do you think the dog will like the new kitten? Why?"],
  h: ["브라더 베어는 무엇을 발견해서 집에 데려오나요?",
      "너는 동물을 발견해서 키우고 싶었던 적이 있나요?",
      "강아지가 새로 온 아기 고양이를 좋아할 것 같나요? 왜 그런가요?"] };
ACT["S2343"] = { s: "Captain Cat, who has whiskers and paws, joins the army! He and his best friend make an army barracks more like home.",
  q: ["What does Captain Cat do in the army?",
      "Do you have a best friend who helps you feel at home?",
      "What do you think Captain Cat is good at in the army?"],
  h: ["캡틴 캣은 군대에서 무엇을 하나요?",
      "너에게는 편안하게 느끼도록 도와주는 단짝 친구가 있나요?",
      "캡틴 캣은 군대에서 무엇을 잘할 것 같나요?"] };
ACT["S2344"] = { s: "Emma accidentally makes bad cookies for her class. Her dog, Dixie, helps to keep the class from eating them.",
  q: ["What does Dixie do to help Emma?",
      "Have you ever baked or cooked something that went wrong?",
      "What do you think Dixie did to stop the class from eating the cookies?"],
  h: ["딕시는 에마를 돕기 위해 무엇을 하나요?",
      "너는 요리나 베이킹을 하다가 실패한 적이 있나요?",
      "딕시는 반 친구들이 쿠키를 먹지 못하게 어떻게 했을까요?"] };
ACT["S2345"] = { s: "Emma's class goes on a trip to the dinosaur museum. Dixie tags along with her and the two best friends end up in a mess.",
  q: ["Where does Emma's class go on their school trip?",
      "Have you ever been to a museum? Which one?",
      "What kind of mess do you think Dixie made at the museum?"],
  h: ["에마의 반은 현장체험학습으로 어디에 가나요?",
      "너는 박물관에 가 본 적이 있나요? 어느 박물관인가요?",
      "딕시는 박물관에서 어떤 소동을 벌였을까요?"] };
ACT["S2346"] = { s: "Dixie goes to school with Emma for Pet Day. She gets very excited and finds it hard to stay calm and sit still.",
  q: ["Why does Dixie find it hard to stay calm at school?",
      "Have you ever had a Pet Day or brought something special to school?",
      "What do you think Dixie does when she gets too excited?"],
  h: ["딕시는 왜 학교에서 얌전히 있기 힘든가요?",
      "너는 학교에 특별한 것을 가져가거나 반려동물의 날을 보낸 적이 있나요?",
      "딕시는 너무 신나면 어떻게 행동할 것 같나요?"] };
ACT["S2347"] = { s: "Grizzwold the lovable bear must find a new home since loggers are cutting down the forest. Will he ever find a home that's just right for him?",
  q: ["Why does Grizzwold need to find a new home?",
      "Have you ever had to move to a new place?",
      "What kind of home do you think would be just right for Grizzwold?"],
  h: ["그리즈월드는 왜 새 집을 찾아야 하나요?",
      "너는 새로운 곳으로 이사해 본 적이 있나요?",
      "그리즈월드에게 꼭 맞는 집은 어떤 집일까요?"] };
ACT["S2348"] = { s: "Oliver is a very special elephant. He has always dreamed of working in the circus. Will his dream ever come true?",
  q: ["What does Oliver the elephant dream of doing?",
      "What do you dream of doing when you grow up?",
      "Do you think Oliver's dream will come true? Why?"],
  h: ["코끼리 올리버는 무엇을 하는 꿈을 꾸나요?",
      "너는 커서 무엇을 하고 싶은 꿈을 꾸나요?",
      "올리버의 꿈이 이루어질 것 같나요? 왜 그런가요?"] };
ACT["S2349"] = { s: "Penny is eager to share her very own song with her family. But she learns to wait until it is right the time to teach her family the song.",
  q: ["What does Penny learn about sharing her song?",
      "Have you ever had to wait for the right time to share something?",
      "Why do you think waiting for the right time can be a good idea?"],
  h: ["페니는 노래를 나누는 것에 대해 무엇을 배웠나요?",
      "너는 무언가를 나누기 위해 적당한 때를 기다려 본 적이 있나요?",
      "적당한 때를 기다리는 것이 왜 좋은 생각일까요?"] };
ACT["S2350"] = { s: "Pinkalicious and Peter attend Teddy Bear Day at the zoo. They have a fantastic time with their teddy bears until a sneaky monkey scoops up Pinkalicious's bear.",
  q: ["What does the sneaky monkey do at the zoo?",
      "Have you ever lost a toy somewhere?",
      "How do you think Pinkalicious got her teddy bear back?"],
  h: ["장난꾸러기 원숭이는 동물원에서 무엇을 하나요?",
      "너는 장난감을 어딘가에서 잃어버린 적이 있나요?",
      "핑카리셔스는 곰인형을 어떻게 되찾았을까요?"] };
ACT["S2351"] = { s: "Pinkalicious prepares a fairy house in her yard. She sleeps outside hoping that she can watch the fairies when they come for a visit.",
  q: ["What does Pinkalicious build in her yard?",
      "Have you ever built something outside, like a fort or house?",
      "Do you think Pinkalicious will see a fairy? Why?"],
  h: ["핑카리셔스는 마당에 무엇을 만드나요?",
      "너는 요새나 집처럼 밖에서 무언가를 만들어 본 적이 있나요?",
      "핑카리셔스가 요정을 보게 될 것 같나요? 왜 그런가요?"] };
ACT["S2352"] = { s: "Young Thomas Edison saves a child from being hit by a train and, as his reward, asks for training as a telegraph operator.",
  q: ["What does young Thomas Edison do to save the child?",
      "Have you ever helped someone in an emergency, big or small?",
      "Why do you think Edison asked for telegraph training as his reward?"],
  h: ["어린 토머스 에디슨은 아이를 구하기 위해 무엇을 하나요?",
      "너는 크든 작든 위급한 상황에서 누군가를 도운 적이 있나요?",
      "에디슨은 왜 보상으로 전신 기술 훈련을 부탁했을까요?"] };
ACT["S2353"] = { s: "This book introduces a collection of 41 folk rhymes, taunts, and insults.",
  q: ["What kind of rhymes are in this book?",
      "Do you know any funny rhymes or songs?",
      "What is your favorite silly rhyme?"],
  h: ["이 책에는 어떤 종류의 동시가 담겨 있나요?",
      "너는 재미있는 동시나 노래를 알고 있나요?",
      "네가 가장 좋아하는 우스꽝스러운 동시는 무엇인가요?"] };
ACT["S2354"] = { s: "A young Indian boy named Red Fox receives a large canoe, and he's off to catch a million fish.",
  q: ["What does Red Fox get, and what does he want to catch?",
      "Have you ever gone fishing, or wanted to try?",
      "Do you think Red Fox will really catch a million fish? Why?"],
  h: ["레드 폭스는 무엇을 받고, 무엇을 잡고 싶어 하나요?",
      "너는 낚시를 해 본 적이 있나요, 아니면 해 보고 싶었나요?",
      "레드 폭스가 정말로 백만 마리 물고기를 잡을 것 같나요? 왜 그런가요?"] };
ACT["S2355"] = { s: "Space Cat and Earl the robot are forced to land their rocket on a strange planet because their spaceship ran out of fuel. Will Space Cat find enough fuel to blast off and get back home?",
  q: ["Why do Space Cat and Earl land on the strange planet?",
      "Have you ever imagined traveling in space?",
      "How do you think Space Cat will find fuel to get home?"],
  h: ["스페이스 캣과 얼은 왜 이상한 행성에 착륙하나요?",
      "너는 우주 여행을 상상해 본 적이 있나요?",
      "스페이스 캣은 집에 가기 위해 연료를 어떻게 찾을까요?"] };
ACT["S2356"] = { s: "On his way to school, Splat falls off his bicycle and lands nose to beak with a duck. When the duck does not make a sound, Splat is worried. He packs it in his backpack and takes it to Mrs. Wimpydimple.",
  q: ["What does Splat do when the duck doesn't make a sound?",
      "Have you ever worried about an animal or a friend?",
      "Why do you think Splat takes the duck to Mrs. Wimpydimple?"],
  h: ["오리가 소리를 내지 않자 스플랫은 무엇을 하나요?",
      "너는 동물이나 친구가 걱정된 적이 있나요?",
      "스플랫은 왜 오리를 윔피딤플 선생님께 데려갈까요?"] };
ACT["S2357"] = { s: "Splat the Cat is upset that he cannot watch his favorite superhero after television breaks. He enters a cake-baking contest to win a new television.",
  q: ["Why does Splat enter the cake-baking contest?",
      "Have you ever tried a contest to win a prize?",
      "Do you think Splat will win the contest? Why?"],
  h: ["스플랫은 왜 케이크 굽기 대회에 나가나요?",
      "너는 상을 타기 위해 대회에 나가 본 적이 있나요?",
      "스플랫이 대회에서 이길 것 같나요? 왜 그런가요?"] };
ACT["S2358"] = { s: "Splat is excited to get a chance to play in Cat Gang, a rock band.",
  q: ["What is Splat excited to do in this book?",
      "Do you play or want to play a musical instrument?",
      "What do you think Splat's rock band sounds like?"],
  h: ["스플랫은 이 책에서 무엇을 하게 되어 신나 있나요?",
      "너는 악기를 연주하나요, 아니면 배워 보고 싶나요?",
      "스플랫의 록 밴드는 어떤 소리가 날 것 같나요?"] };
ACT["S2359"] = { s: "Splat is super excited about camping out. But when his mother tells him that she has invited Spike, his rival, his excitement turns to something else.",
  q: ["What news makes Splat's excitement change?",
      "Have you ever gone camping, or wanted to?",
      "How do you think Splat feels about camping with Spike?"],
  h: ["어떤 소식이 스플랫의 신남을 바꾸어 놓나요?",
      "너는 캠핑을 가 본 적이 있나요, 아니면 가고 싶었나요?",
      "스파이크와 함께 캠핑하는 것에 대해 스플랫은 어떤 기분일까요?"] };
ACT["S2360"] = { s: "Stanley is chased away by the other cavemen because he is not ordinary. But he is not afraid to be himself and just goes on being different. He finds out it isn't such a bad idea after all.",
  q: ["Why do the other cavemen chase Stanley away at first?",
      "Have you ever felt different from other people?",
      "Why do you think it is good that Stanley stays himself?"],
  h: ["다른 원시인들은 처음에 왜 스탠리를 쫓아내나요?",
      "너는 다른 사람들과 다르다고 느낀 적이 있나요?",
      "스탠리가 자기 모습 그대로 사는 것이 왜 좋을까요?"] };
ACT["S2361"] = { s: "This book introduces six funny stories about the silliest family in the whole world.",
  q: ["What kind of family is in this book?",
      "What is the silliest thing your family has ever done?",
      "What do you think happens with a carrot in someone's ear?"],
  h: ["이 책에는 어떤 가족이 나오나요?",
      "너희 가족이 한 일 중 가장 엉뚱했던 일은 무엇인가요?",
      "귀에 당근이 들어가면 어떤 일이 벌어질 것 같나요?"] };
ACT["S2362"] = { s: "Enjoy six spooky stories, told by a 'not too scary' ghost host.",
  q: ["Who tells the spooky stories in this book?",
      "Do you like spooky stories? Why or why not?",
      "What do you think makes a ghost only a little bit scary?"],
  h: ["이 책에서 으스스한 이야기를 들려주는 것은 누구인가요?",
      "너는 으스스한 이야기를 좋아하나요? 왜 그런가요?",
      "유령이 많이 무섭지 않게 되는 이유는 무엇일까요?"] };
ACT["S2363"] = { s: "In this story, the literal-minded Amelia Bedelia runs for mayor! It all started from a little misunderstanding.",
  q: ["What does Amelia Bedelia decide to do in this story?",
      "Have you ever misunderstood someone and it caused a funny problem?",
      "Do you think Amelia Bedelia will be a good mayor? Why?"],
  h: ["이 이야기에서 아멜리아 베델리아는 무엇을 하기로 결심하나요?",
      "너는 누군가의 말을 잘못 알아들어서 재미있는 일이 생긴 적이 있나요?",
      "아멜리아 베델리아가 좋은 시장이 될 것 같나요? 왜 그런가요?"] };
ACT["S2364"] = { s: "Two children are sitting at home on a rainy day. Cat in the Hat visits and invites them to the world of some tricks and games.",
  q: ["What does the Cat in the Hat invite the children to do?",
      "What do you do on a rainy day at home?",
      "Would you let the Cat in the Hat into your house? Why or why not?"],
  h: ["모자 쓴 고양이는 아이들에게 무엇을 하자고 하나요?",
      "너는 비 오는 날 집에서 무엇을 하나요?",
      "모자 쓴 고양이를 너희 집에 들어오게 할 것 같나요? 왜 그런가요?"] };
ACT["S2365"] = { s: "This book invites readers to the fun world of the alphabet.",
  q: ["What does this book introduce to readers?",
      "What is your favorite letter of the alphabet? Why?",
      "What silly word can you think of for one letter?"],
  h: ["이 책은 독자에게 무엇을 소개하나요?",
      "네가 가장 좋아하는 알파벳 글자는 무엇인가요? 왜 그런가요?",
      "한 글자로 시작하는 재미있는 단어를 하나 생각해 볼 수 있나요?"] };
ACT["S2366"] = { s: "This book introduces common \"household\" words to beginning readers.",
  q: ["What kind of words does this book introduce?",
      "What silly creature could be hiding in your room?",
      "What household word do you think is the funniest?"],
  h: ["이 책은 어떤 종류의 단어들을 소개하나요?",
      "네 방에 숨어 있을 만한 엉뚱한 동물은 무엇일까요?",
      "집 안 물건 중 가장 웃기게 들리는 단어는 무엇인가요?"] };
ACT["S2367"] = { s: "This book introduces the world of bugs - including what they eat, how they see, and more.",
  q: ["What did you learn about how bugs eat or see?",
      "Do you like bugs, or are you scared of them?",
      "What is one bug fact that surprised you?"],
  h: ["벌레가 먹고 보는 방법에 대해 무엇을 알게 되었나요?",
      "너는 벌레를 좋아하나요, 아니면 무섭나요?",
      "벌레에 대해 놀라웠던 사실 한 가지는 무엇인가요?"] };
ACT["S2368"] = { s: "This book describes the world of frogs - including what they feed on, how they swim, and more.",
  q: ["What did you learn about how frogs swim or eat?",
      "Have you ever seen a real frog?",
      "What is one thing you find interesting about frogs?"],
  h: ["개구리가 헤엄치고 먹는 방법에 대해 무엇을 알게 되었나요?",
      "너는 진짜 개구리를 본 적이 있나요?",
      "개구리에 대해 흥미로운 점 한 가지는 무엇인가요?"] };
ACT["S2369"] = { s: "This book introduces the dinosaurs from massive Apatosaurus to terrifying T-rex.",
  q: ["Which dinosaurs are introduced in this book?",
      "What is your favorite dinosaur?",
      "Which dinosaur do you think was the scariest?"],
  h: ["이 책에는 어떤 공룡들이 소개되나요?",
      "네가 가장 좋아하는 공룡은 무엇인가요?",
      "가장 무서웠을 것 같은 공룡은 무엇인가요?"] };
ACT["S2370"] = { s: "When greedy Shen refuses to share his yummy pears, a hungry beggar teaches him a little kindness.",
  q: ["What does the beggar teach Shen?",
      "Have you ever had to share something you didn't want to share?",
      "Why do you think kindness is important?"],
  h: ["거지는 셴에게 무엇을 가르쳐 주나요?",
      "너는 나누고 싶지 않은 것을 나누어야 했던 적이 있나요?",
      "친절함이 왜 중요할까요?"] };
ACT["S2371"] = { s: "This African folktale describes how the tortoise outsmarts the leopard and tricks him into sharing his drum with the Sky God.",
  q: ["How does the tortoise outsmart the leopard?",
      "Have you ever used a clever idea to solve a problem?",
      "Why do you think the tortoise's plan worked?"],
  h: ["거북이는 어떻게 표범보다 꾀를 부리나요?",
      "너는 영리한 생각으로 문제를 해결한 적이 있나요?",
      "거북이의 계획은 왜 성공했을까요?"] };
ACT["S2372"] = { s: "When the hungry tiger is on the prowl, Little Deer’s quick thinking outwits him.",
  q: ["How does Little Deer outwit the hungry tiger?",
      "Have you ever used quick thinking to get out of trouble?",
      "What do you think Little Deer felt after outwitting the tiger?"],
  h: ["아기 사슴은 배고픈 호랑이를 어떻게 이겨 내나요?",
      "너는 재빠른 생각으로 곤란한 상황에서 벗어난 적이 있나요?",
      "호랑이를 이긴 뒤 아기 사슴은 어떤 기분이었을까요?"] };
ACT["S2373"] = { s: "Billy receives a goose from someone for his kindness, and it becomes the best present of his life.",
  q: ["Why does Billy receive the golden goose?",
      "Have you ever received a gift for being kind?",
      "Why do you think kindness was rewarded in this story?"],
  h: ["빌리는 왜 황금 거위를 받게 되나요?",
      "너는 친절해서 선물을 받은 적이 있나요?",
      "이 이야기에서 친절함이 왜 보상을 받았을까요?"] };
ACT["S2374"] = { s: "Manu rescues a tiny fish from the stream, and soon he discovers that only the fish can save the world in danger.",
  q: ["What does Manu do for the tiny fish?",
      "Have you ever rescued or helped an animal?",
      "How do you think the fish can save the world?"],
  h: ["마누는 작은 물고기를 위해 무엇을 하나요?",
      "너는 동물을 구해 주거나 도와준 적이 있나요?",
      "그 물고기는 세상을 어떻게 구할 수 있을까요?"] };
ACT["S2375"] = { s: "After a peddler comes to town selling magic fire sticks, Danny, who used to help the villagers by starting fires, feels useless.",
  q: ["Why does Danny the dragon feel useless?",
      "Have you ever felt like no one needed your help anymore?",
      "What do you think Danny can do to feel useful again?"],
  h: ["용 대니는 왜 쓸모없다고 느끼나요?",
      "너는 더 이상 아무도 네 도움이 필요 없다고 느낀 적이 있나요?",
      "대니가 다시 쓸모 있다고 느끼려면 무엇을 할 수 있을까요?"] };
ACT["S2376"] = { s: "When Sam gets too bored, he devises a plan to make life a little more exciting.",
  q: ["What does Sam do because he is bored?",
      "Have you ever done something because you were bored?",
      "Do you think Sam's plan was a good idea? Why or why not?"],
  h: ["샘은 심심해서 무엇을 하나요?",
      "너는 심심해서 무언가를 해 본 적이 있나요?",
      "샘의 계획이 좋은 생각이었다고 생각하나요? 왜 그런가요?"] };
ACT["S2377"] = { s: "When the three little pigs are going out into the big wide world to look for homes of their own, their mother warns of Big Bad Wolf.",
  q: ["What does the mother pig warn her three pigs about?",
      "Have you ever been warned about something before going somewhere?",
      "Which pig's home do you think is the strongest?"],
  h: ["엄마 돼지는 세 아기 돼지에게 무엇을 조심하라고 하나요?",
      "너는 어딘가에 가기 전에 조심하라는 말을 들은 적이 있나요?",
      "어느 돼지의 집이 가장 튼튼할 것 같나요?"] };
ACT["S2378"] = { s: "When life on the farm is getting too dangerous, the animals leave to join a band.",
  q: ["Why do the animals leave the farm?",
      "Have you ever wanted to try being part of a band?",
      "What instrument do you think each animal could play?"],
  h: ["동물들은 왜 농장을 떠나나요?",
      "너는 밴드의 일원이 되어 보고 싶었던 적이 있나요?",
      "각 동물은 어떤 악기를 연주할 수 있을 것 같나요?"] };
ACT["S2379"] = { s: "The Little Red Hen finds some grains and asks her best friends to help her plant them. Will they help her?",
  q: ["What does the Little Red Hen ask her friends to do?",
      "Have you ever asked friends to help you with something?",
      "Do you think her friends will help her? Why or why not?"],
  h: ["빨간 암탉은 친구들에게 무엇을 도와 달라고 하나요?",
      "너는 친구들에게 도움을 요청한 적이 있나요?",
      "친구들이 암탉을 도와줄 것 같나요? 왜 그런가요?"] };
ACT["S2380"] = { s: "Tom is delighted to discover that their little white goose lays a golden egg. But soon, he starts feeling one golden egg a day isn't just enough.",
  q: ["What does Tom want, even though the goose already gives him a golden egg?",
      "Have you ever wanted more than what you already had?",
      "What do you think will happen because Tom wants too much?"],
  h: ["거위가 이미 황금 알을 주는데도 톰은 무엇을 더 바라나요?",
      "너는 이미 가진 것보다 더 많이 갖고 싶었던 적이 있나요?",
      "톰이 너무 많이 욕심을 부려서 어떤 일이 생길까요?"] };
ACT["S2381"] = { s: "A gingerbread man runs away when the oven door is open. Soon, everyone is chasing after him to catch.",
  q: ["Why does everyone chase the gingerbread man?",
      "Have you ever played a chasing game?",
      "Do you think anyone will catch the gingerbread man? Why?"],
  h: ["사람들은 왜 진저브레드맨을 쫓아가나요?",
      "너는 잡기 놀이를 해 본 적이 있나요?",
      "누군가 진저브레드맨을 잡을 수 있을 것 같나요? 왜 그런가요?"] };
ACT["S2382"] = { s: "When the turnip is ready, the farmer tries to pull it out of the ground, but it won't budge. Soon he has a string of helpers.",
  q: ["Why does the farmer need so many helpers?",
      "Have you ever needed help to finish something big?",
      "Why do you think working together helped pull the turnip out?"],
  h: ["농부는 왜 그렇게 많은 도움이 필요한가요?",
      "너는 큰 일을 끝내기 위해 도움이 필요했던 적이 있나요?",
      "함께 힘을 모으는 것이 왜 순무를 뽑는 데 도움이 되었을까요?"] };
ACT["S2383"] = { s: "Chicken Licken warns everyone that the sky is falling. Soon everyone is rushing to warn the King.",
  q: ["What does Chicken Licken think is happening?",
      "Have you ever believed something that turned out to be a mistake?",
      "Do you think the sky is really falling? Why or why not?"],
  h: ["치킨 리큰은 무슨 일이 일어나고 있다고 생각하나요?",
      "너는 잘못된 것을 사실이라고 믿었던 적이 있나요?",
      "하늘이 정말로 무너지고 있는 것 같나요? 왜 그런가요?"] };
ACT["S2384"] = { s: "The greedy dragon wants to hide the gold in Jack's castle. Look who comes along.",
  q: ["What does the greedy dragon want to do with the gold?",
      "Have you ever had to protect something important?",
      "Who do you think will stop the dragon?"],
  h: ["욕심 많은 용은 금으로 무엇을 하려고 하나요?",
      "너는 소중한 것을 지켜야 했던 적이 있나요?",
      "누가 그 용을 막을 수 있을 것 같나요?"] };
ACT["S2385"] = { s: "The Emperor asks Chang, the best painter in China, to paint dragons in his new temple.",
  q: ["What does the Emperor ask Chang to paint?",
      "Have you ever drawn or painted something for someone?",
      "What do you think Chang's dragon paintings look like?"],
  h: ["황제는 장에게 무엇을 그려 달라고 부탁하나요?",
      "너는 누군가를 위해 그림을 그려 본 적이 있나요?",
      "장이 그린 용 그림은 어떤 모습일 것 같나요?"] };
ACT["S2386"] = { s: "The Emperor of China loves to hear the nightingale's sweet songs. But he gets fascinated with a new dazzling mechanical songbird.",
  q: ["What two kinds of birds does the Emperor listen to?",
      "Do you like real music better, or something made by a machine?",
      "Which bird's song do you think the Emperor will choose in the end?"],
  h: ["황제는 어떤 두 종류의 새 소리를 듣나요?",
      "너는 진짜 음악이 더 좋나요, 아니면 기계가 만든 소리가 더 좋나요?",
      "결국 황제는 어느 새의 노래를 선택할 것 같나요?"] };
ACT["S2387"] = { s: "Goldilocks likes to do something naughty every day, and she goes a step too far one day.",
  q: ["What does Goldilocks like to do every day?",
      "Have you ever done something you weren't supposed to do?",
      "What do you think happens when Goldilocks goes too far?"],
  h: ["골디락스는 매일 무엇을 하기를 좋아하나요?",
      "너는 하면 안 되는 일을 해 본 적이 있나요?",
      "골디락스가 너무 심하게 굴면 어떤 일이 생길까요?"] };
ACT["S2388"] = { s: "When Harry Hare suggests a race, Tom Tortoise takes up the challenge. Everyone wonders if Tom really thinks he can beat the fastest hare in history.",
  q: ["What does Harry Hare suggest to Tom Tortoise?",
      "Have you ever raced against someone faster than you?",
      "Do you think Tom Tortoise can win the race? Why?"],
  h: ["해리 토끼는 톰 거북이에게 무엇을 제안하나요?",
      "너는 너보다 빠른 사람과 달리기 시합을 해 본 적이 있나요?",
      "톰 거북이가 경주에서 이길 수 있을 것 같나요? 왜 그런가요?"] };
ACT["S2389"] = { s: "Little Red Riding Hood sets on a journey to Gran's house on her own. Can she outwit a wolf and complete her task successfully?",
  q: ["Where does Little Red Riding Hood travel by herself?",
      "Have you ever gone somewhere on your own for the first time?",
      "Do you think she can outwit the wolf? Why?"],
  h: ["빨간 모자는 혼자서 어디로 가나요?",
      "너는 처음으로 혼자 어딘가에 가 본 적이 있나요?",
      "빨간 모자가 늑대를 이길 수 있을 것 같나요? 왜 그런가요?"] };
ACT["S2390"] = { s: "When hungry children are having pancakes for breakfast, one pancake escapes out of the pan.",
  q: ["What does the pancake do when it escapes?",
      "Have you ever eaten pancakes for breakfast?",
      "Do you think anyone will catch the runaway pancake? Why?"],
  h: ["팬케이크는 도망칠 때 무엇을 하나요?",
      "너는 아침으로 팬케이크를 먹어 본 적이 있나요?",
      "누군가 도망친 팬케이크를 잡을 수 있을 것 같나요? 왜 그런가요?"] };
ACT["S2391"] = { s: "Toby Town Mouse gets surprised when he visits his country cousin - who lives in a hedge.",
  q: ["Where does Toby Town Mouse's cousin live?",
      "Would you rather live in a busy town or a quiet country place?",
      "What do you think surprises Toby the most about the hedge?"],
  h: ["토비 타운 마우스의 사촌은 어디에 사나요?",
      "너는 북적이는 도시와 조용한 시골 중 어디에 살고 싶나요?",
      "산울타리에 대해 토비가 가장 놀랄 만한 것은 무엇일까요?"] };
ACT["S2392"] = { s: "The lonely Ugly Duckling leaves his home and goes out alone into the world to find anyone to love him.",
  q: ["Why does the Ugly Duckling leave home?",
      "Have you ever felt lonely and wished for a friend?",
      "Do you think the duckling will find someone to love him? Why?"],
  h: ["미운 오리 새끼는 왜 집을 떠나나요?",
      "너는 외롭다고 느끼며 친구를 바란 적이 있나요?",
      "그 오리가 자신을 사랑해 줄 누군가를 찾을 것 같나요? 왜 그런가요?"] };
ACT["S2393"] = { s: "Androcles, a slave in Ancient Rome, escapes to the forest. Unfortunately, he runs into a lion. Can he survive?",
  q: ["What does Androcles run into after escaping?",
      "Have you ever been surprised by something unexpected outdoors?",
      "Do you think Androcles can survive meeting the lion? Why?"],
  h: ["안드로클레스는 탈출한 뒤 무엇과 마주치나요?",
      "너는 밖에서 예상치 못한 것에 놀란 적이 있나요?",
      "안드로클레스가 사자를 만나고도 살아남을 수 있을 것 같나요? 왜 그런가요?"] };
ACT["S2394"] = { s: "Tasha goes to visit a witch named Baba Yaga when her stepmother tells her to get a needle and thread. But soon she finds herself in a trap.",
  q: ["Why does Tasha visit Baba Yaga?",
      "Have you ever been sent somewhere and something unexpected happened?",
      "How do you think Tasha can escape the trap?"],
  h: ["타샤는 왜 바바 야가를 찾아가나요?",
      "너는 어딘가에 심부름을 갔다가 예상치 못한 일을 겪은 적이 있나요?",
      "타샤는 함정에서 어떻게 벗어날 수 있을까요?"] };
ACT["S2395"] = { s: "Dick Whittington sets off to London to seek his fortune as he hears that the streets of London are paved with gold.",
  q: ["Why does Dick Whittington go to London?",
      "Have you ever gone somewhere because you heard exciting stories about it?",
      "Do you think the streets of London are really paved with gold? Why?"],
  h: ["딕 휘팅턴은 왜 런던으로 가나요?",
      "너는 흥미진진한 이야기를 듣고 어딘가에 가 본 적이 있나요?",
      "런던 거리가 정말로 금으로 덮여 있을 것 같나요? 왜 그런가요?"] };
ACT["S2396"] = { s: "Thumbelina is as tiny as a thumb and fragile. She gets abandoned in the outside world and faces some big adventures.",
  q: ["How big is Thumbelina, and what does she face?",
      "Have you ever felt small in a big, new place?",
      "What kind of adventure do you think Thumbelina has?"],
  h: ["엄지공주는 얼마나 작고, 무엇과 마주하게 되나요?",
      "너는 크고 낯선 곳에서 작다고 느낀 적이 있나요?",
      "엄지공주는 어떤 모험을 하게 될 것 같나요?"] };
ACT["S2397"] = { s: "A thief steals the King's treasure, but does he know how to handle it?",
  q: ["What does the thief steal, and what problem does he have?",
      "Have you ever gotten something and not known what to do with it?",
      "Why do you think the sea ends up salty?"],
  h: ["도둑은 무엇을 훔치고, 어떤 문제를 겪나요?",
      "너는 무언가를 얻었지만 어떻게 해야 할지 몰랐던 적이 있나요?",
      "바다는 왜 결국 짜게 되었을까요?"] };
ACT["S2398"] = { s: "This book introduces everything about elephants which are the largest land animals in the world.",
  q: ["What is special about elephants, based on this book?",
      "Have you ever seen an elephant in real life or in a picture?",
      "What is the most surprising elephant fact to you?"],
  h: ["이 책에 따르면 코끼리의 특별한 점은 무엇인가요?",
      "너는 실제로나 그림으로 코끼리를 본 적이 있나요?",
      "코끼리에 대해 가장 놀라운 사실은 무엇인가요?"] };
ACT["S2399"] = { s: "This story takes readers back to medieval times and introduces what it was like to be a knight and live in a castle.",
  q: ["What does this book teach about knights and castles?",
      "Would you like to live in a castle like a knight? Why or why not?",
      "What do you think was the hardest part of being a knight?"],
  h: ["이 책은 기사와 성에 대해 무엇을 알려 주나요?",
      "너는 기사처럼 성에 살고 싶나요? 왜 그런가요?",
      "기사로 사는 것 중 가장 힘들었을 부분은 무엇일까요?"] };
