// 간이 학습 질문 — Book No. S24 묶음. 사람이 아니라 AI 가 한 번 쓰고 굳힌 파일이다.
window.ACT = window.ACT || {};
var ACT = window.ACT;
ACT["S2400"] = { s: "Even though he always sails into disaster, Sinbad thirst for adventure. He faces wild storms, gigantic whales, and trolls and survives.",
  q: ["What dangers does Sinbad face on his voyages?",
      "Have you ever felt afraid but still wanted to try something exciting?",
      "Which danger in the story do you think is the scariest, and why?"],
  h: ["신드바드는 항해 중에 어떤 위험들을 만나나요?",
      "무섭지만 그래도 해 보고 싶었던 일이 있었나요?",
      "이야기 속 위험 중에서 가장 무서운 것은 무엇인 것 같나요? 이유도 적어 보세요."] };
ACT["S2401"] = { s: "Aladdin meets his long-lost uncle and finds a magic lamp with a genie, who has the power to grant wishes inside. Can the genie help Aladdin win the Sultan's daughter?",
  q: ["What does Aladdin find inside the magic lamp?",
      "If a genie could grant you one wish, what would you wish for?",
      "Do you think Aladdin's uncle is telling the truth about the lamp? Why or why not?"],
  h: ["알라딘은 마법 램프 안에서 무엇을 발견하나요?",
      "지니가 소원 하나를 들어준다면 너는 무엇을 빌고 싶나요?",
      "알라딘의 삼촌이 램프에 대해 진실을 말하고 있다고 생각하나요? 이유도 적어 보세요."] };
ACT["S2402"] = { s: "Ali Baba is delighted to discover a cave full of treasure. But soon, he has to deal with his nosy brother and forty thieves to keep his treasure safe.",
  q: ["What does Ali Baba find in the cave?",
      "If you found a hidden treasure, who would you tell about it?",
      "Why do you think Ali Baba has trouble keeping his treasure safe?"],
  h: ["알리바바는 동굴에서 무엇을 발견하나요?",
      "숨겨진 보물을 찾는다면 누구에게 알리고 싶나요?",
      "알리바바가 보물을 지키기 어려운 이유는 무엇일까요?"] };
ACT["S2403"] = { s: "This book introduces stories about why animals look and act the way they do.",
  q: ["Which animal legend in this book do you find most interesting?",
      "Do you know a story about why an animal looks or acts a certain way?",
      "If you could make up a legend about an animal, which animal would you choose?"],
  h: ["이 책에 나온 동물 전설 중에 가장 흥미로웠던 것은 무엇인가요?",
      "동물이 왜 그런 모습이나 행동을 하는지 알려 주는 이야기를 알고 있나요?",
      "동물에 대한 전설을 만든다면 어떤 동물을 고르고 싶나요?"] };
ACT["S2404"] = { s: "When the three Billy Goats are leaving their farm to look for food, their friends worry about the terrible troll.",
  q: ["Why are the Billy Goats' friends worried?",
      "Have you ever worried about a friend going somewhere that seemed risky?",
      "What do you think the goats should do about the troll?"],
  h: ["염소들의 친구들은 왜 걱정하나요?",
      "친구가 위험해 보이는 곳에 가서 걱정한 적이 있나요?",
      "염소들이 트롤을 어떻게 하면 좋을까요?"] };
ACT["S2405"] = { s: "Alfie is a burglar who likes to go home to a tasty meal after a hard night’s thieving. But one day, he finds that someone has stolen his breakfast!",
  q: ["What happens to Alfie's breakfast one day?",
      "How would you feel if someone took your food without asking?",
      "Who do you think stole Alfie's breakfast, and why do you think so?"],
  h: ["어느 날 앨피의 아침밥은 어떻게 되나요?",
      "누군가 허락 없이 네 음식을 가져간다면 기분이 어떨까요?",
      "누가 앨피의 아침밥을 훔쳤을 것 같나요? 그렇게 생각하는 이유는요?"] };
ACT["S2406"] = { s: "Cinderella lives with a wicked stepmother and two cruel stepsisters. But her life changes when a magical fairy godmother sets to make her dreams come true.",
  q: ["Who helps Cinderella when her life changes?",
      "Has anyone ever helped you when you needed it most?",
      "What would you ask a fairy godmother to do for you?"],
  h: ["신데렐라의 삶이 바뀔 때 누가 도와주나요?",
      "가장 필요할 때 누군가 나를 도와준 적이 있나요?",
      "요정 대모에게 부탁한다면 무엇을 해 달라고 하고 싶나요?"] };
ACT["S2407"] = { s: "Mr. Puff, who lives next door to Sam, has many interesting things - even a basket of dinosaur eggs!",
  q: ["What surprising thing does Mr. Puff have in a basket?",
      "Do you have a neighbor who has something interesting or surprising?",
      "What would you do if you found dinosaur eggs?"],
  h: ["퍼프 아저씨의 바구니 안에는 어떤 놀라운 것이 있나요?",
      "신기한 것을 가진 이웃이 있나요?",
      "공룡알을 발견한다면 너는 어떻게 할 것 같나요?"] };
ACT["S2408"] = { s: "When a rival seller steals the shoemaker's customers, his business goes down. But then, two elves arrive at his shop on their secret mission.",
  q: ["Why does the shoemaker's business go down?",
      "Have you ever had trouble with something and needed unexpected help?",
      "What do you think the two elves' secret mission is?"],
  h: ["구두장이의 가게 장사는 왜 어려워지나요?",
      "무언가 힘들 때 예상치 못한 도움을 받은 적이 있나요?",
      "두 요정의 비밀 임무는 무엇일 것 같나요?"] };
ACT["S2409"] = { s: "Princess hopes that a handsome prince comes to rescue her from marrying Prince Humper Dunk. But she ends up with a creepy frog instead.",
  q: ["Who does the princess end up with instead of a handsome prince?",
      "Have you ever hoped for one thing but gotten something different?",
      "How do you think the princess feels about getting a frog instead?"],
  h: ["공주는 멋진 왕자 대신 누구와 함께하게 되나요?",
      "무언가를 바랐지만 다른 것을 얻었던 적이 있나요?",
      "공주는 개구리를 받게 되어 기분이 어떨 것 같나요?"] };
ACT["S2410"] = { s: "This book contains stories of magical creatures from faraway lands - including unicorns, flying horses, and more.",
  q: ["Which magical creature in this book do you like the most?",
      "If you could have a magical animal as a pet, which one would you choose?",
      "What magical power would you want your animal to have?"],
  h: ["이 책에 나온 마법 동물 중 가장 좋아하는 것은 무엇인가요?",
      "마법 동물을 애완동물로 키울 수 있다면 어떤 동물을 고르고 싶나요?",
      "네 동물이 어떤 마법 능력을 가졌으면 좋겠나요?"] };
ACT["S2411"] = { s: "One Saturday morning, six monsters meet in a treehouse to start a gang. But one monster has a secret. Read and find out what his secret is.",
  q: ["Where do the six monsters meet to start their gang?",
      "Have you ever had a secret that was hard to keep?",
      "What do you think the monster's secret might be?"],
  h: ["여섯 괴물은 모임을 만들려고 어디에서 만나나요?",
      "지키기 어려운 비밀을 가진 적이 있나요?",
      "그 괴물의 비밀은 무엇일 것 같나요?"] };
ACT["S2412"] = { s: "For Christmas, Clara gets an amazing present - a magic doll. Soon she is magically flying in a sleigh to the Land of Sweets.",
  q: ["What present does Clara get for Christmas?",
      "What is the best present you have ever received?",
      "If you could fly to the Land of Sweets, what would you want to eat there?"],
  h: ["클라라는 크리스마스에 어떤 선물을 받나요?",
      "지금까지 받은 선물 중 가장 좋았던 것은 무엇인가요?",
      "사탕나라로 날아갈 수 있다면 거기서 무엇을 먹고 싶나요?"] };
ACT["S2413"] = { s: "Prince Patrick is eager to find a real princess to marry, but it isn't easy. Can a pea help the prince identify a real princess?",
  q: ["What does the prince use to test if someone is a real princess?",
      "Do you think a pea under many mattresses is a fair way to test someone? Why or why not?",
      "How would you prove you are telling the truth about who you are?"],
  h: ["왕자는 진짜 공주인지 알아보려고 무엇을 사용하나요?",
      "매트리스 아래에 완두콩을 놓는 것이 공정한 방법이라고 생각하나요? 이유도 적어 보세요.",
      "너라면 네가 누구인지 어떻게 증명하고 싶나요?"] };
ACT["S2414"] = { s: "Tom is disappointed to find out that his father only left him a cat. But it is no ordinary cat. Tom and his cat experience adventures with an ogre, a king, and a princess.",
  q: ["Who does Tom have adventures with in this story?",
      "Have you ever been disappointed about a gift that turned out better than you expected?",
      "What do you think makes Tom's cat not an ordinary cat?"],
  h: ["톰은 이야기 속에서 누구와 모험을 하나요?",
      "실망했던 선물이 나중에 생각보다 더 좋았던 적이 있나요?",
      "톰의 고양이가 평범한 고양이가 아니라고 생각하게 만드는 것은 무엇일까요?"] };
ACT["S2415"] = { s: "Rapunzel gets kidnapped at birth and is locked up in a tower. But when a handsome prince comes to save her, she attempts a daring escape.",
  q: ["Where is Rapunzel locked up?",
      "If you were locked in a tower, how would you try to escape?",
      "Why do you think the prince wants to save Rapunzel?"],
  h: ["라푼젤은 어디에 갇혀 있나요?",
      "탑에 갇혔다면 어떻게 탈출하려고 할 것 같나요?",
      "왕자는 왜 라푼젤을 구하고 싶어 하는 것 같나요?"] };
ACT["S2416"] = { s: "This book contains tales of some not-so-scary mythical fire-breathing beasts.",
  q: ["Are the dragons in this book scary or not so scary?",
      "If you met a friendly dragon, what would you want to do together?",
      "Why do you think dragons in stories breathe fire?"],
  h: ["이 책 속 용들은 무섭나요, 아니면 그다지 무섭지 않나요?",
      "친절한 용을 만난다면 함께 무엇을 하고 싶나요?",
      "이야기 속 용들은 왜 불을 뿜는다고 생각하나요?"] };
ACT["S2417"] = { s: "This book presents a collection of ghostly stories.",
  q: ["Which ghost story in this book do you remember most?",
      "Have you ever told or heard a scary story with friends?",
      "Do you think ghosts in stories are always scary? Why or why not?"],
  h: ["이 책 속 유령 이야기 중 가장 기억에 남는 것은 무엇인가요?",
      "친구들과 무서운 이야기를 하거나 들은 적이 있나요?",
      "이야기 속 유령이 항상 무섭다고 생각하나요? 이유도 적어 보세요."] };
ACT["S2418"] = { s: "Read and find out how a kind giant helps a poor fisherman.",
  q: ["Who does the kind giant help in this story?",
      "Have you ever helped someone who needed it?",
      "Why do you think the giant decides to help the fisherman?"],
  h: ["이 이야기에서 친절한 거인은 누구를 돕나요?",
      "도움이 필요한 누군가를 도와준 적이 있나요?",
      "거인은 왜 어부를 돕기로 했을까요?"] };
ACT["S2419"] = { s: "This book has stories about the magical world of gnomes and goblins whose mischievous pixies get people into trouble.",
  q: ["What do the mischievous pixies do to people in this book?",
      "Have you ever played a harmless trick on someone, or had one played on you?",
      "Why do you think gnomes and goblins like to cause trouble?"],
  h: ["이 책 속 장난꾸러기 픽시들은 사람들에게 무슨 일을 벌이나요?",
      "누군가에게 장난을 치거나 장난을 받은 적이 있나요?",
      "노움과 고블린은 왜 말썽을 부리는 것을 좋아할까요?"] };
ACT["S2420"] = { s: "This book contains stories of the exciting adventures of knights.",
  q: ["What kind of adventures do the knights have in this book?",
      "If you were a knight, what adventure would you want to go on?",
      "What do you think makes someone brave like a knight?"],
  h: ["이 책 속 기사들은 어떤 모험을 하나요?",
      "네가 기사라면 어떤 모험을 떠나고 싶나요?",
      "기사처럼 용감해지려면 무엇이 필요할까요?"] };
ACT["S2421"] = { s: "This book introduces stories about scary monsters living under the bed.",
  q: ["Where do the monsters in this book live?",
      "Have you ever imagined something scary hiding in your room?",
      "What would you say to a monster under your bed if you met one?"],
  h: ["이 책 속 괴물들은 어디에 살고 있나요?",
      "방 안에 무서운 무언가가 숨어 있다고 상상한 적이 있나요?",
      "침대 밑 괴물을 만난다면 뭐라고 말하고 싶나요?"] };
ACT["S2422"] = { s: "Meet the craziest crew of pirates on the Seven Seas. Come aboard and set sails with them.",
  q: ["Where do the pirates in this book sail?",
      "If you joined this pirate crew, what job on the ship would you want?",
      "Why do you think people find pirate stories exciting?"],
  h: ["이 책 속 해적들은 어디를 항해하나요?",
      "이 해적단에 들어간다면 배에서 어떤 일을 맡고 싶나요?",
      "사람들은 왜 해적 이야기를 재미있어할까요?"] };
ACT["S2423"] = { s: "This story is about the princes and princesses who are somewhat unique.",
  q: ["How are the princes and princesses in this book different from ordinary ones?",
      "What makes you unique compared to your friends?",
      "Do you think a prince or princess has to act a certain way? Why or why not?"],
  h: ["이 책 속 왕자와 공주들은 보통과 어떻게 다른가요?",
      "친구들과 비교해서 너만의 특별한 점은 무엇인가요?",
      "왕자나 공주가 꼭 특별한 방식으로 행동해야 한다고 생각하나요? 이유도 적어 보세요."] };
ACT["S2424"] = { s: "This book features robots that cause mayhem in tales.",
  q: ["What kind of mayhem do the robots in this book cause?",
      "Have you ever seen a robot or machine cause a problem or a mess?",
      "If your robot caused mayhem, how would you calm it down?"],
  h: ["이 책 속 로봇들은 어떤 큰 소동을 일으키나요?",
      "로봇이나 기계가 문제나 엉망인 상황을 만드는 것을 본 적이 있나요?",
      "네 로봇이 소동을 일으킨다면 어떻게 진정시키고 싶나요?"] };
ACT["S2425"] = { s: "This book contains stories about witches - including wicked, wily witches, and more.",
  q: ["What kind of witches are in this book?",
      "Have you ever read or watched a story about a witch before?",
      "Do you think all witches in stories are bad? Why or why not?"],
  h: ["이 책에는 어떤 마녀들이 나오나요?",
      "전에 마녀에 대한 이야기를 읽거나 본 적이 있나요?",
      "이야기 속 마녀들이 모두 나쁘다고 생각하나요? 이유도 적어 보세요."] };
ACT["S2426"] = { s: "Read and find out everything about chocolate - including where it is from, how it is made, and more.",
  q: ["Where does chocolate come from, according to this book?",
      "What is your favorite way to eat chocolate?",
      "What else would you like to learn about how chocolate is made?"],
  h: ["이 책에 따르면 초콜릿은 어디에서 오나요?",
      "초콜릿을 먹는 방법 중 네가 가장 좋아하는 방식은 무엇인가요?",
      "초콜릿이 만들어지는 과정에 대해 더 알고 싶은 것이 있나요?"] };
ACT["S2427"] = { s: "This text informs the history of the toilet, from cavemen's holes in the ground to Thomas Crapper's flushing toilet.",
  q: ["This book explains how toilets changed from cavemen's holes in the ground to Thomas Crapper's flushing toilet. Pick one part of this history that surprised you, and explain what people used before and what changed.",
      "Think about the bathroom you use every day. How do you think your life would be different if you had to use a hole in the ground instead of a flushing toilet? Write a few sentences about it.",
      "Thomas Crapper's invention changed how people live every day. Think of another everyday invention that changed people's lives, and explain why you think it is important."],
  h: ["이 책은 화장실이 원시인이 땅에 판 구덩이에서 토머스 크래퍼의 물 내리는 변기까지 어떻게 바뀌었는지 알려줘요. 이 역사에서 가장 놀라웠던 부분을 하나 골라, 사람들이 예전에는 무엇을 썼고 무엇이 바뀌었는지 설명해 보세요.",
      "네가 매일 쓰는 화장실을 떠올려 보세요. 물 내리는 변기 대신 땅에 판 구덩이를 써야 한다면 삶이 어떻게 달라질까요? 몇 문장으로 적어 보세요.",
      "토머스 크래퍼의 발명품은 사람들이 사는 방식을 바꾸었어요. 사람들의 삶을 바꾼 다른 일상 속 발명품을 하나 떠올려 보고, 왜 중요하다고 생각하는지 설명해 보세요."] };
ACT["S2428"] = { s: "When the king finds out that his twelve princesses sneak off to go dancing every night, he gets furious. Will his idea stop them from going on outings?",
  q: ["What do the twelve princesses do every night?",
      "Have you ever tried to keep something secret from your family?",
      "Do you think the king's idea will stop the princesses? Why or why not?"],
  h: ["열두 공주는 매일 밤 무엇을 하나요?",
      "가족에게 무언가를 비밀로 하려고 한 적이 있나요?",
      "왕의 생각이 공주들을 멈출 수 있을까요? 이유도 적어 보세요."] };
ACT["S2429"] = { s: "This book introduces magical stories of wizards, including broomstick rides and bubbling cauldrons.",
  q: ["What do the wizards in this book do with broomsticks and cauldrons?",
      "If you were a wizard, what magic would you want to make in a cauldron?",
      "Why do you think wizards in stories often fly on broomsticks?"],
  h: ["이 책 속 마법사들은 빗자루와 가마솥으로 무엇을 하나요?",
      "네가 마법사라면 가마솥으로 어떤 마법을 만들고 싶나요?",
      "이야기 속 마법사들은 왜 빗자루를 타고 나는 것 같나요?"] };
ACT["S2430"] = { s: "This story is about a vain emperor who buys an invisible suit of clothes from rascals.",
  q: ["What kind of clothes does the vain emperor buy?",
      "Have you ever pretended to understand something so you wouldn't feel embarrassed?",
      "Why do you think the rascals are able to trick the emperor?"],
  h: ["허영심 많은 황제는 어떤 옷을 사나요?",
      "창피할까 봐 이해하는 척한 적이 있나요?",
      "사기꾼들은 왜 황제를 속일 수 있었을까요?"] };
ACT["S2431"] = { s: "This story is about Hansel and Gretel who pit their wits against their evil stepmother and a wicked witch.",
  q: ["Who do Hansel and Gretel have to outsmart?",
      "Have you ever had to think of a clever plan to solve a problem?",
      "What do you think Hansel and Gretel do to outsmart the witch?"],
  h: ["헨젤과 그레텔은 누구보다 더 지혜로워야 하나요?",
      "문제를 풀려고 똑똑한 계획을 생각해 낸 적이 있나요?",
      "헨젤과 그레텔은 마녀를 어떻게 이겨낼 것 같나요?"] };
ACT["S2432"] = { s: "A young boy named Jack swaps his mother's cow for some 'magic' beans, and they grow into a huge beanstalk.",
  q: ["What does Jack trade for the magic beans?",
      "Have you ever traded something and later felt surprised by what happened?",
      "What do you think Jack finds when he climbs the huge beanstalk?"],
  h: ["잭은 마법 콩과 무엇을 바꾸나요?",
      "무언가를 바꾸고 나중에 놀랐던 적이 있나요?",
      "잭이 거대한 콩나무를 타고 올라가면 무엇을 발견할 것 같나요?"] };
ACT["S2433"] = { s: "In this story, Theseus takes on the challenge of defeating the fearsome Minotaur who is deep in a maze of tunnels below Crete. Will he survive?",
  q: ["What creature does Theseus have to defeat?",
      "Have you ever felt nervous before facing a big challenge?",
      "How do you think Theseus finds his way through the maze of tunnels?"],
  h: ["테세우스는 어떤 괴물을 물리쳐야 하나요?",
      "큰 도전을 앞두고 긴장한 적이 있나요?",
      "테세우스는 미로 같은 통로 속에서 길을 어떻게 찾을 것 같나요?"] };
ACT["S2434"] = { s: "The miller's daughter Anna dreams of becoming Queen. But she must spin straw into pure gold first. A mysterious little man offers to help, but what will he ask in return?",
  q: ["What must Anna spin straw into before she can become Queen?",
      "Have you ever needed someone's help to finish something difficult?",
      "What do you think the little man will ask for in return for his help?"],
  h: ["안나가 여왕이 되기 전에 지푸라기를 무엇으로 바꾸어야 하나요?",
      "어려운 일을 끝내려고 누군가의 도움이 필요했던 적이 있나요?",
      "그 작은 남자는 도와준 대가로 무엇을 달라고 할 것 같나요?"] };
ACT["S2435"] = { s: "It's Junie B.'s first day of kindergarten. Junie gets scared of the school bus and the meanies on it. What will she do when it's time to go back home?",
  q: ["What is Junie B. scared of on her first day of kindergarten?",
      "Do you remember your first day at a new school? How did you feel?",
      "What do you think Junie B. should do about the school bus?"],
  h: ["주니 비는 유치원 첫날 무엇을 무서워하나요?",
      "새 학교에 가던 첫날이 기억나나요? 그때 기분이 어땠나요?",
      "주니 비는 스쿨버스 문제를 어떻게 하면 좋을까요?"] };
ACT["S2436"] = { s: "Junie B. is not pleased with her new baby brother. But when she finally sees him, she goes ape.",
  q: ["How does Junie B. feel about her new baby brother at first?",
      "Have you ever felt differently about something after you actually saw or tried it?",
      "Why do you think Junie B.'s feelings change when she sees her brother?"],
  h: ["주니 비는 처음에 새 남동생에 대해 어떻게 느끼나요?",
      "직접 보거나 해 보고 나서 생각이 달라진 적이 있나요?",
      "주니 비는 동생을 보고 나서 왜 마음이 바뀌었을까요?"] };
ACT["S2437"] = { s: "Junie B. spies on her teacher Mrs., and she gets into real trouble.",
  q: ["Who does Junie B. spy on in this book?",
      "Have you ever gotten into trouble because you were too curious?",
      "Why do you think Junie B. decides to spy on her teacher?"],
  h: ["주니 비는 이 책에서 누구를 몰래 훔쳐보나요?",
      "너무 궁금해서 곤란해진 적이 있나요?",
      "주니 비는 왜 선생님을 몰래 훔쳐보기로 했을까요?"] };
ACT["S2438"] = { s: "It's Carnival Night, and Junie B. looks forward to winning lots of prizes. But is a fruitcake what she has in mind?",
  q: ["What is Junie B. hoping to win at the Carnival?",
      "Have you ever won a prize you did not really want?",
      "How do you think Junie B. feels about winning a fruitcake?"],
  h: ["주니 비는 카니발에서 무엇을 따고 싶어 하나요?",
      "별로 원하지 않던 상을 받은 적이 있나요?",
      "주니 비는 과일 케이크를 받고 기분이 어떨 것 같나요?"] };
ACT["S2439"] = { s: "When meanie Jim invites everyone except Junie B. to his birthday party, she is very upset. How will she deal with the situation? Book #6",
  q: ["Why is Junie B. upset about Jim's birthday party?",
      "Have you ever felt left out of something? How did that feel?",
      "What do you think Junie B. should do about being left out?"],
  h: ["주니 비는 짐의 생일 파티 때문에 왜 속상해하나요?",
      "어딘가에서 나만 빠진 것 같아 속상했던 적이 있나요?",
      "주니 비는 혼자 빠진 것에 대해 어떻게 하면 좋을까요?"] };
ACT["S2440"] = { s: "There's a new boy in kindergarten, a handsome boy. Junie B. wants him for her boyfriend as well as her friends. Will Junie B. find a way to make him like her?",
  q: ["What does Junie B. want the new boy Warren to be?",
      "Have you ever wanted to become friends with someone new?",
      "What do you think Junie B. could do to make Warren like her?"],
  h: ["주니 비는 새로 온 남자아이 워렌이 무엇이 되었으면 하나요?",
      "새로운 친구와 사귀고 싶었던 적이 있나요?",
      "주니 비는 워렌이 자신을 좋아하게 하려고 무엇을 할 수 있을까요?"] };
ACT["S2441"] = { s: "Junie B. is terrified after hearing that people have monsters under their beds.",
  q: ["What is Junie B. afraid might be under her bed?",
      "Have you ever been afraid of something at nighttime?",
      "What would you say to Junie B. to help her feel less scared?"],
  h: ["주니 비는 침대 밑에 무엇이 있을까 봐 무서워하나요?",
      "밤에 무언가가 무서웠던 적이 있나요?",
      "주니 비가 덜 무섭게 느끼도록 뭐라고 말해 주고 싶나요?"] };
ACT["S2442"] = { s: "Junie B. and Grace are invited for a sleepover party at Lucille's rich nanna's house. It's the house of Junie's dream where things are beautiful and breakable.",
  q: ["What kind of house do Junie B. and Grace get invited to?",
      "Have you ever been somewhere fancy and had to be extra careful?",
      "What do you think could go wrong in a house full of breakable things?"],
  h: ["주니 비와 그레이스는 어떤 집에 초대받나요?",
      "고급스러운 곳에 가서 특별히 조심해야 했던 적이 있나요?",
      "깨지기 쉬운 물건이 가득한 집에서 어떤 일이 생길 수 있을까요?"] };
ACT["S2443"] = { s: "After her first trip to a beauty parlor, Junie B. decides to be a beauty shop guy. But doesn't she need a little practice first?",
  q: ["What job does Junie B. decide she wants after visiting the beauty parlor?",
      "Have you ever wanted to try a new job just because you saw someone doing it?",
      "Why do you think Junie B. might need practice first?"],
  h: ["주니 비는 미용실에 다녀온 뒤 어떤 일을 하고 싶어 하나요?",
      "누군가 하는 것을 보고 그 일을 해 보고 싶었던 적이 있나요?",
      "주니 비는 왜 먼저 연습이 필요할 것 같나요?"] };
ACT["S2444"] = { s: "When Junie B. notices it is against the rule to bring her dog to school on Pet Day, she is frustrated. And she considers taking a raccoon, a worm, or a dead fish, instead.",
  q: ["What pets does Junie B. think about bringing instead of her dog?",
      "Have you ever had to follow a rule you didn't like?",
      "Which of Junie B.'s pet ideas do you think is the strangest? Why?"],
  h: ["주니 비는 강아지 대신 무엇을 데려갈까 생각하나요?",
      "마음에 안 드는 규칙을 따라야 했던 적이 있나요?",
      "주니 비가 생각한 것 중 가장 이상한 것은 무엇인가요? 이유도 적어 보세요."] };
ACT["S2445"] = { s: "When Junie B. finds out that her aunt has asked someone else to be the flower girl at her wedding, she is more than disappointed.",
  q: ["What job does Junie B. not get to do at her aunt's wedding?",
      "Have you ever been disappointed that someone else got to do something you wanted to do?",
      "What do you think Junie B. could do about feeling left out of the wedding?"],
  h: ["주니 비는 이모의 결혼식에서 어떤 역할을 맡지 못하나요?",
      "내가 하고 싶던 일을 다른 사람이 하게 되어 속상했던 적이 있나요?",
      "주니 비는 결혼식에서 빠진 것 같은 기분을 어떻게 풀 수 있을까요?"] };
ACT["S2446"] = { s: "On Valentine's Day, Junie B. receives an unexpected mushy gushy \"valentine\" and is determined to find out who her secret admirer is.",
  q: ["What does Junie B. receive on Valentine's Day?",
      "Have you ever received a surprise gift or note from someone?",
      "How do you think Junie B. will try to find out who sent the valentine?"],
  h: ["주니 비는 밸런타인데이에 무엇을 받나요?",
      "누군가에게서 깜짝 선물이나 쪽지를 받은 적이 있나요?",
      "주니 비는 누가 보냈는지 어떻게 알아내려고 할 것 같나요?"] };
ACT["S2447"] = { s: "Junie B. is worried when she hears that her kindergarten class is going on a field trip to a farm. Maybe she'll get attacked by a rooster.",
  q: ["What is Junie B. worried might happen on the farm field trip?",
      "Have you ever been nervous before a school trip?",
      "What do you think Junie B. should do about her worry?"],
  h: ["주니 비는 농장 체험학습에서 무슨 일이 일어날까 봐 걱정하나요?",
      "학교 견학을 앞두고 긴장한 적이 있나요?",
      "주니 비는 그 걱정을 어떻게 풀면 좋을까요?"] };
ACT["S2448"] = { s: "Junie B. is the captain of Room Nine's Field Day team. Will she find a way to lead her team to victory?",
  q: ["What job does Junie B. have for Field Day?",
      "Have you ever been chosen to lead a team? How did it feel?",
      "What do you think a good team captain should do?"],
  h: ["주니 비는 체육대회에서 어떤 역할을 맡나요?",
      "팀을 이끄는 역할을 맡은 적이 있나요? 그때 기분이 어땠나요?",
      "좋은 팀 대장이 되려면 무엇을 해야 할까요?"] };
ACT["S2449"] = { s: "It is a new school year, and everything is new and different. Junie B. also has a new problem?she might need glasses!",
  q: ["What new problem does Junie B. have in first grade?",
      "Have you ever needed to try something new, like glasses, to help you?",
      "How do you think Junie B. feels about maybe needing glasses?"],
  h: ["주니 비는 1학년이 되어 어떤 새로운 문제가 생기나요?",
      "안경처럼 너를 도와줄 새로운 것을 써 본 적이 있나요?",
      "안경이 필요할지도 모른다는 것에 대해 주니 비는 기분이 어떨 것 같나요?"] };
ACT["S2450"] = { s: "When Junie B. is told that she can help out in the school cafeteria, she is thrilled.",
  q: ["What job is Junie B. excited to do in the cafeteria?",
      "Have you ever been excited to help out with a job at school?",
      "What do you think Junie B. will do as boss of lunch?"],
  h: ["주니 비는 급식실에서 어떤 일을 하게 되어 신났나요?",
      "학교에서 어떤 일을 맡아 신났던 적이 있나요?",
      "주니 비는 급식 대장으로서 무엇을 할 것 같나요?"] };
ACT["S2451"] = { s: "Junie B. is the first student in Room One to lose a tooth, and she learns some interesting things about the Tooth Fairy.",
  q: ["What does Junie B. learn about after losing her tooth?",
      "Do you remember losing your first tooth? What happened?",
      "What do you think Junie B. learns about the Tooth Fairy?"],
  h: ["주니 비는 이가 빠진 뒤 무엇에 대해 알게 되나요?",
      "처음으로 이가 빠졌을 때가 기억나나요? 그때 어떤 일이 있었나요?",
      "주니 비는 이빨 요정에 대해 무엇을 알게 될 것 같나요?"] };
ACT["S2452"] = { s: "It's almost Halloween. Junie B. wants to find a perfect costume that will scare off the real witches and ghosts that she believes will be out for the day.",
  q: ["What kind of costume is Junie B. looking for?",
      "What costume would you choose if you wanted to scare away witches and ghosts?",
      "Do you think a costume can really scare away real witches and ghosts? Why or why not?"],
  h: ["주니 비는 어떤 옷을 찾고 있나요?",
      "마녀와 유령을 쫓아내고 싶다면 너는 어떤 옷을 고르고 싶나요?",
      "옷 하나로 진짜 마녀와 유령을 쫓아낼 수 있다고 생각하나요? 이유도 적어 보세요."] };
ACT["S2453"] = { s: "Room One is doing fun activities to celebrate Christmas. But May keeps telling tales and ruins Junie's holiday glee. The worst part is that Junie B. is stuck as May's Secret Santa.",
  q: ["Who does Junie B. get stuck being Secret Santa for?",
      "Have you ever had to be nice to someone you were annoyed with?",
      "What do you think Junie B. should get May as a Secret Santa gift?"],
  h: ["주니 비는 어쩔 수 없이 누구의 시크릿 산타가 되나요?",
      "짜증 나는 사람에게도 친절하게 대해야 했던 적이 있나요?",
      "주니 비는 메이에게 시크릿 산타 선물로 무엇을 주면 좋을까요?"] };
ACT["S2454"] = { s: "When Junie B. and her family go on a vacation to Hawaii, she manages to find trouble before and during a trip. She records each incident in a photo journal.",
  q: ["How does Junie B. keep track of the trouble she finds on her trip?",
      "Have you ever kept a journal or taken pictures on a trip?",
      "What kind of trouble do you think Junie B. finds in Hawaii?"],
  h: ["주니 비는 여행에서 생긴 일들을 어떻게 기록하나요?",
      "여행 중에 일기를 쓰거나 사진을 찍은 적이 있나요?",
      "주니 비는 하와이에서 어떤 소동을 일으킬 것 같나요?"] };
ACT["S2455"] = { s: "Lucille is having an Easter Egg Hunt at her luxurious mansion, and Junie B. is determined to win the grand prize.",
  q: ["What does Junie B. want to win at Lucille's Easter Egg Hunt?",
      "Have you ever tried hard to win a game or contest?",
      "What do you think Junie B. will do to try to win the grand prize?"],
  h: ["주니 비는 루실의 부활절 달걀 찾기에서 무엇을 따고 싶어 하나요?",
      "게임이나 대회에서 열심히 이기려고 노력한 적이 있나요?",
      "주니 비는 큰 상을 타려고 무엇을 할 것 같나요?"] };
ACT["S2456"] = { s: "Mrs. Scary's class is getting ready for their very own Thanksgiving feast! When they are writing a Thankful List for the school contest, Junie B. finds it challenging to be grateful for Tattletale May.",
  q: ["What is hard for Junie B. to write on her Thankful List?",
      "Is there someone you find it hard to feel thankful for? Why?",
      "What do you think Junie B. could write about May on her list?"],
  h: ["주니 비는 감사 목록에 무엇을 쓰기 어려워하나요?",
      "고마워하기 어려운 사람이 있나요? 그 이유는 무엇인가요?",
      "주니 비는 메이에 대해 목록에 뭐라고 쓸 수 있을까요?"] };
ACT["S2457"] = { s: "A strange noise wakes Wilbur up, and he finds a baby dragon at the door.",
  q: ["What does Wilbur find at the door?",
      "Have you ever woken up because of a strange noise?",
      "What do you think Wilbur and Winnie will do with the baby dragon?"],
  h: ["윌버는 문 앞에서 무엇을 발견하나요?",
      "이상한 소리 때문에 잠에서 깬 적이 있나요?",
      "윌버와 위니는 아기 용을 어떻게 할 것 같나요?"] };
ACT["S2458"] = { s: "It's Winnie the witch's birthday, and she is having a party! But where have all the guests gone?",
  q: ["What happens to the guests at Winnie's party?",
      "Have you ever planned a party and had something go wrong?",
      "Where do you think Winnie's guests have gone?"],
  h: ["위니의 파티에서 손님들에게 무슨 일이 생기나요?",
      "파티를 준비했는데 뭔가 잘못된 적이 있나요?",
      "위니의 손님들은 어디로 갔을 것 같나요?"] };
ACT["S2459"] = { s: "Winnie gets a flying carpet from her sister, but the carpet is out of control.",
  q: ["What gift does Winnie get from her sister?",
      "Have you ever gotten a gift that was harder to use than you expected?",
      "What do you think Winnie should do to control the flying carpet?"],
  h: ["위니는 언니에게서 어떤 선물을 받나요?",
      "생각보다 다루기 어려운 선물을 받은 적이 있나요?",
      "위니는 날아다니는 양탄자를 어떻게 다스려야 할까요?"] };
ACT["S2460"] = { s: "Winnie and Wilbur decide to grow their own vegetables in their garden. But she can't wait until they grow up and uses a little magic to speed up the growing process.",
  q: ["What does Winnie use magic for in this story?",
      "Have you ever wanted something to happen faster than it normally would?",
      "What do you think happens when Winnie speeds up the growing with magic?"],
  h: ["위니는 이 이야기에서 마법을 무엇에 사용하나요?",
      "무언가가 평소보다 빨리 이루어지길 바란 적이 있나요?",
      "위니가 마법으로 빨리 자라게 하면 어떤 일이 생길 것 같나요?"] };
ACT["S2461"] = { s: "Winnie changes herself and Wilbur into creatures of the deep sea. But her magic wand sinks out of sight.",
  q: ["What happens to Winnie's magic wand?",
      "Have you ever lost something important? What did you do?",
      "How do you think Winnie and Wilbur can turn back to normal without the wand?"],
  h: ["위니의 마법 지팡이는 어떻게 되나요?",
      "소중한 것을 잃어버린 적이 있나요? 그때 어떻게 했나요?",
      "위니와 윌버는 지팡이 없이 어떻게 원래대로 돌아갈 수 있을까요?"] };
ACT["S2462"] = { s: "The Incredibles are a family which appears normal, but they are the members who have superpowers. They are the family that confronts the evil Syndrome.",
  q: ["What is special about the Incredibles family?",
      "If you had a superpower, what would you want it to be?",
      "Why do you think the Incredibles keep their powers a secret?"],
  h: ["인크레더블 가족의 특별한 점은 무엇인가요?",
      "초능력을 하나 가질 수 있다면 어떤 능력을 갖고 싶나요?",
      "인크레더블 가족은 왜 자신들의 능력을 비밀로 할까요?"] };
ACT["S2463"] = { s: "The emperor orders every family to send a man to join his army to fight the war. Mulan disguises herself as a man and becomes a soldier.",
  q: ["What does Mulan do to join the army?",
      "Have you ever done something brave to help your family?",
      "Why do you think Mulan decides to disguise herself instead of telling the truth?"],
  h: ["뮬란은 군대에 들어가려고 무엇을 하나요?",
      "가족을 돕기 위해 용감한 일을 해 본 적이 있나요?",
      "뮬란은 왜 사실대로 말하지 않고 변장을 했을까요?"] };
ACT["S2464"] = { s: "When Tinker Bell gets kidnapped by a human, Vidia takes charge to lead the fairies in a daring rescue.",
  q: ["Who leads the fairies in the rescue?",
      "Have you ever had to take charge to help someone in trouble?",
      "What do you think Vidia and the fairies need to do to rescue Tinker Bell?"],
  h: ["요정들의 구출 작전을 이끄는 것은 누구인가요?",
      "곤경에 처한 누군가를 돕기 위해 앞장선 적이 있나요?",
      "비디아와 요정들은 팅커벨을 구하기 위해 무엇을 해야 할까요?"] };
ACT["S2465"] = { s: "Nemo gets caught and taken to the city of Sydney. His father, Marlin, sets on a journey to find his son.",
  q: ["Where is Nemo taken?",
      "Have you ever been separated from your family, even for a short time? How did it feel?",
      "What do you think Marlin needs to do to find Nemo?"],
  h: ["니모는 어디로 잡혀가나요?",
      "잠깐이라도 가족과 떨어진 적이 있나요? 그때 기분이 어땠나요?",
      "말린은 니모를 찾기 위해 무엇을 해야 할까요?"] };
ACT["S2466"] = { s: "Prince Simba, the son of King Mufasa, is born in the Pride Lands. His uncle, Scar, devises a scheme to take the throne.",
  q: ["What does Scar want to take from Simba's family?",
      "Have you ever seen someone try to take something that wasn't theirs?",
      "What do you think Scar's scheme might be?"],
  h: ["스카는 심바의 가족에게서 무엇을 빼앗고 싶어 하나요?",
      "자기 것이 아닌 것을 가지려는 사람을 본 적이 있나요?",
      "스카의 계략은 무엇일 것 같나요?"] };
ACT["S2467"] = { s: "Evil magic turns Prince Naveen into a frog. He needs a kiss from a princess to turn back into a human.",
  q: ["What does Prince Naveen need to turn back into a human?",
      "Have you ever needed someone else's help to fix a problem?",
      "How do you think Prince Naveen feels about being a frog?"],
  h: ["나빈 왕자는 다시 사람이 되려면 무엇이 필요한가요?",
      "문제를 해결하려고 다른 사람의 도움이 필요했던 적이 있나요?",
      "나빈 왕자는 개구리가 된 것에 대해 기분이 어떨 것 같나요?"] };
ACT["S2468"] = { s: "Al, the man from the toy store, steals Woody for the exhibition. Buzz and the gang set off to rescue him.",
  q: ["Who takes Woody, and why?",
      "Have you ever had to help rescue a friend from trouble?",
      "What do you think Buzz and the gang will do to rescue Woody?"],
  h: ["누가, 왜 우디를 데려가나요?",
      "곤경에 처한 친구를 구하는 것을 도운 적이 있나요?",
      "버즈와 친구들은 우디를 구하기 위해 무엇을 할 것 같나요?"] };
ACT["S2469"] = { s: "WALL-E is a robot whose job is to clean up the Earth. This book follows his adventure to save the Earth.",
  q: ["What is WALL-E's job?",
      "What is one thing you could do to help take care of the Earth?",
      "Why do you think WALL-E's job of cleaning up is important?"],
  h: ["월-E의 일은 무엇인가요?",
      "지구를 돌보기 위해 네가 할 수 있는 일 한 가지는 무엇인가요?",
      "월-E가 하는 청소 일은 왜 중요할까요?"] };
ACT["S2470"] = { s: "At Monsters, Inc., the monsters are learning to be Scarers. Scare master Sulley and his assistant Mike are on their mission of scaring the human children of the world. But when a little girl gives them a big scare back, it becomes their job to return her to her bedroom.",
  q: ["What is Sulley and Mike's job at Monsters, Inc.?",
      "Have you ever been surprised when something didn't go the way you expected?",
      "What do you think Sulley and Mike need to do to return the girl safely?"],
  h: ["몬스터 주식회사에서 설리와 마이크의 일은 무엇인가요?",
      "생각했던 것과 다르게 흘러가서 놀랐던 적이 있나요?",
      "설리와 마이크는 여자아이를 안전하게 돌려보내려면 무엇을 해야 할까요?"] };
ACT["S2471"] = { s: "Tinker Bell is not so sure that she wants to be a tinker fairy. She asks her friends to help her find new talent.",
  q: ["What does Tinker Bell ask her friends to help her do?",
      "Have you ever tried to find out what you are good at?",
      "What talent do you think Tinker Bell might discover?"],
  h: ["팅커벨은 친구들에게 무엇을 도와달라고 부탁하나요?",
      "네가 무엇을 잘하는지 찾아보려 한 적이 있나요?",
      "팅커벨은 어떤 재능을 발견하게 될 것 같나요?"] };
ACT["S2472"] = { s: "Hiro is a robotics genius. Alistair Krei steals Hiro Hamada's invention, microbots. He and his friends go on an adventure to get it back.",
  q: ["What does Alistair Krei steal from Hiro?",
      "Have you ever worked with friends to get something back or fix a problem?",
      "What do you think Hiro and his friends will do to get the microbots back?"],
  h: ["알리스테어 크레이는 히로에게서 무엇을 훔치나요?",
      "친구들과 힘을 모아 무언가를 되찾거나 문제를 해결한 적이 있나요?",
      "히로와 친구들은 마이크로봇을 되찾기 위해 무엇을 할 것 같나요?"] };
ACT["S2473"] = { s: "It's the first day back at school. While the kids are hurrying to get on the bus, Arthur and Norman switch their lunch boxes by accident.",
  q: ["What mistake happens with Arthur and Norman's lunch boxes?",
      "Have you ever mixed up your things with someone else's by accident?",
      "What do you think Arthur and Norman find when they open the wrong lunch boxes?"],
  h: ["아서와 노먼의 도시락에는 어떤 실수가 생기나요?",
      "실수로 다른 사람의 물건과 네 물건이 바뀐 적이 있나요?",
      "아서와 노먼은 서로 바뀐 도시락을 열었을 때 무엇을 발견할 것 같나요?"] };
ACT["S2474"] = { s: "Arthur is afraid of pulling his loose tooth. Later, he learns to be brave from his little sister, Violet.",
  q: ["Who helps Arthur learn to be brave about his tooth?",
      "Has a younger brother, sister, or friend ever taught you something?",
      "What do you think Violet does to help Arthur be brave?"],
  h: ["아서는 이빨에 대해 누구를 보고 용기를 배우나요?",
      "동생이나 친구에게 무언가를 배운 적이 있나요?",
      "바이올렛은 아서가 용기를 내도록 어떻게 도와줄 것 같나요?"] };
ACT["S2475"] = { s: "Mildred, Snitch's cat, has disappeared. The members of the Private Eyes Club get on the baffling case right away.",
  q: ["What mystery does the Private Eyes Club investigate?",
      "Have you ever lost a pet, or helped look for someone else's?",
      "What clues do you think the Private Eyes Club will look for?"],
  h: ["탐정클럽은 어떤 사건을 조사하나요?",
      "애완동물을 잃어버렸거나, 다른 사람의 애완동물을 찾아준 적이 있나요?",
      "탐정클럽은 어떤 단서를 찾을 것 같나요?"] };
ACT["S2476"] = { s: "The members of the Private Eyes Club don't want any girls in their club. But when a funny little man double-crosses the private eyes with a message in code, Marigold and the girls get their chance to prove themselves.",
  q: ["What chance do Marigold and the girls get in this story?",
      "Have you ever been told you couldn't join something because of who you are?",
      "How do you think the girls prove themselves in this story?"],
  h: ["매리골드와 여자아이들은 이 이야기에서 어떤 기회를 얻나요?",
      "네가 누구인지 때문에 무언가에 끼지 못한다는 말을 들은 적이 있나요?",
      "여자아이들은 이 이야기에서 자신을 어떻게 증명할 것 같나요?"] };
ACT["S2477"] = { s: "Two detectives, Bunny and Jack, solve the mystery of the missing glass monkey of Mac.",
  q: ["What object do Bunny and Jack search for in this story?",
      "Have you ever helped search for something that was missing?",
      "What do you think happened to the missing glass monkey?"],
  h: ["버니와 잭은 이 이야기에서 무엇을 찾나요?",
      "잃어버린 물건을 찾는 것을 도운 적이 있나요?",
      "사라진 유리 원숭이에게 무슨 일이 생겼을 것 같나요?"] };
ACT["S2478"] = { s: "Bunny and Jack, animal detectives, try to find the cat who has run off with their neighbor's binoculars.",
  q: ["What did the climbing cat run off with?",
      "Have you ever chased after a pet who ran away with something?",
      "Why do you think the cat took the binoculars?"],
  h: ["그 고양이는 무엇을 가지고 도망갔나요?",
      "무언가를 가지고 도망간 애완동물을 쫓아간 적이 있나요?",
      "고양이는 왜 쌍안경을 가져갔을까요?"] };
ACT["S2479"] = { s: "Bunny and Jack, the animal detectives, investigate the case of missing trombone from Mr. Riley's music store.",
  q: ["What instrument goes missing from Mr. Riley's store?",
      "Have you ever played or wanted to play a musical instrument?",
      "Who do you think took the trombone, and why?"],
  h: ["라일리 아저씨의 가게에서 어떤 악기가 사라지나요?",
      "악기를 연주해 본 적이 있거나 연주해 보고 싶었던 적이 있나요?",
      "누가 왜 트롬본을 가져갔을 것 같나요?"] };
ACT["S2480"] = { s: "Bunny and Jack, the animal detectives, investigate the case of the missing balloons from the neighborhood toy store.",
  q: ["What goes missing from the toy store?",
      "Have you ever wondered where something disappeared to?",
      "What do you think happened to the missing balloons?"],
  h: ["장난감 가게에서 무엇이 사라지나요?",
      "무언가 어디로 사라졌는지 궁금했던 적이 있나요?",
      "사라진 풍선들에게 무슨 일이 생겼을 것 같나요?"] };
ACT["S2481"] = { s: "Lulu is a witch girl who is a little nervous about her first day of school. But she immediately loves everything about school except Sandy who seems to do everything better than her.",
  q: ["Who makes Lulu feel less happy about witch school?",
      "Have you ever compared yourself to someone who seemed better at something?",
      "What do you think Lulu could do about feeling that Sandy is better than her?"],
  h: ["루루가 마녀 학교에서 마음이 불편해지는 이유는 누구 때문인가요?",
      "나보다 더 잘하는 것 같은 사람과 나를 비교한 적이 있나요?",
      "루루는 샌디가 더 낫다는 생각에 대해 어떻게 하면 좋을까요?"] };
ACT["S2482"] = { s: "Little Elephant's parents go on a trip, and he stays with his uncle until they come back. He spends a wonderful time with his uncle who makes wishes come true and tells amazing stories.",
  q: ["What does Little Elephant's uncle do that makes their time special?",
      "Do you have a relative who tells you great stories or makes you feel special?",
      "What wish would you want Uncle Elephant to make come true for you?"],
  h: ["아기 코끼리의 삼촌은 무엇을 해서 둘의 시간을 특별하게 만드나요?",
      "멋진 이야기를 해 주거나 너를 특별하게 느끼게 해 주는 친척이 있나요?",
      "코끼리 삼촌에게 소원 하나를 이루어 달라고 한다면 무엇을 부탁하고 싶나요?"] };
ACT["S2483"] = { s: "Zack's Uncle in Florida sends him a big box. In the mail is Bridget, the alligator who is only the size of a key chain. But she grows into a real live alligator when she gets wet.",
  q: ["What happens to Bridget the alligator when she gets wet?",
      "Have you ever received a surprising gift in the mail?",
      "What do you think Zack should do now that Bridget is a real alligator?"],
  h: ["브리짓이라는 악어는 물에 젖으면 어떻게 되나요?",
      "우편으로 놀라운 선물을 받은 적이 있나요?",
      "브리짓이 진짜 악어가 된 지금, 잭은 어떻게 하면 좋을까요?"] };
ACT["S2484"] = { s: "Bridget, the alligator, goes to school with Zack for show-and-tell. There, she sings, skateboards, and turns the classroom upside down.",
  q: ["What does Bridget do at school that causes a big mess?",
      "Have you ever brought something to show-and-tell that caused excitement or trouble?",
      "What do you think Zack's classmates think about Bridget?"],
  h: ["브리짓은 학교에서 무엇을 해서 큰 소동을 일으키나요?",
      "발표 시간에 무언가를 가져가서 신나거나 곤란했던 적이 있나요?",
      "반 친구들은 브리짓에 대해 어떻게 생각할 것 같나요?"] };
ACT["S2485"] = { s: "Snail goes on three errands for his teacher. But every time he tries to do them, something strange happens. He has amazing adventures.",
  q: ["What is Snail supposed to do for his teacher?",
      "Have you ever been asked to do a simple errand that turned into something bigger?",
      "What kind of strange things do you think happen to Snail?"],
  h: ["달팽이는 선생님을 위해 무엇을 해야 하나요?",
      "간단한 심부름이 큰일이 되어 버린 적이 있나요?",
      "달팽이에게는 어떤 이상한 일들이 일어날 것 같나요?"] };
ACT["S2486"] = { s: "Everyone in Mr. Hopper's second-grade class is excited about bringing in their family's favorite dish on the day of the famous chef's visit. But Ollie, who loves to cook, cannot find a dish his whole family likes.",
  q: ["What problem does Ollie have before the chef's visit?",
      "What is a dish that your whole family likes to eat together?",
      "What do you think Ollie should cook to solve his problem?"],
  h: ["올리는 요리사가 방문하기 전 어떤 문제를 겪나요?",
      "가족 모두가 함께 좋아하는 음식은 무엇인가요?",
      "올리는 문제를 풀기 위해 무엇을 요리하면 좋을까요?"] };
ACT["S2487"] = { s: "Sam is delighted to get the best seat in second grade--right next to the class pet named George Washington. On the day of the class field trip to the science museum, he brings the hamster buddy along.",
  q: ["Who is Sam's class pet, and where does Sam bring him?",
      "Would you want to bring a class pet on a field trip? Why or why not?",
      "What do you think could happen when Sam brings the hamster to the museum?"],
  h: ["샘의 반려동물 이름은 무엇이고, 샘은 그를 어디에 데려가나요?",
      "학급 반려동물을 체험학습에 데려가고 싶나요? 이유도 적어 보세요.",
      "샘이 햄스터를 박물관에 데려가면 무슨 일이 생길 수 있을까요?"] };
ACT["S2488"] = { s: "Big Max travels to the land of Ah-Ah Achoo to find the king's missing pet giraffe named Jake.",
  q: ["What animal does Big Max need to find?",
      "Have you ever gone looking for something that was lost?",
      "What clues do you think Big Max will need to find Jake?"],
  h: ["빅 맥스는 어떤 동물을 찾아야 하나요?",
      "잃어버린 것을 찾으러 나선 적이 있나요?",
      "빅 맥스는 제이크를 찾으려면 어떤 단서가 필요할까요?"] };
ACT["S2489"] = { s: "It's Scrappy's birthday but it seems nobody remembers his birthday. But Flappy has some surprises in store for his friend.",
  q: ["What does Flappy have planned for Scrappy?",
      "Have you ever felt like people forgot something important about you?",
      "What kind of surprise do you think Flappy is planning?"],
  h: ["플래피는 스크래피를 위해 무엇을 준비했나요?",
      "사람들이 나에게 중요한 것을 잊은 것처럼 느낀 적이 있나요?",
      "플래피는 어떤 깜짝 이벤트를 준비하고 있을 것 같나요?"] };
ACT["S2490"] = { s: "Stanley wins a trip to the firehouse for his Stop, Drop, and Roll poster, but the visit takes an unexpected, exciting turn.",
  q: ["How does Stanley win his trip to the firehouse?",
      "Have you ever won a prize for something you made or drew?",
      "What unexpected thing do you think happens at the firehouse?"],
  h: ["스탠리는 어떻게 소방서 견학 상을 받게 되나요?",
      "네가 만들거나 그린 것으로 상을 받은 적이 있나요?",
      "소방서에서 어떤 뜻밖의 일이 일어날 것 같나요?"] };
ACT["S2491"] = { s: "It is Halloween. Stanley and Arthur are excited about the party at school. At the party, they get to notice a bully picking on one of their friends. They come up with a plan to help.",
  q: ["What do Stanley and Arthur notice happening at the party?",
      "Have you ever seen someone being bullied? What did you do?",
      "What plan do you think Stanley and Arthur come up with to help their friend?"],
  h: ["스탠리와 아서는 파티에서 무슨 일을 알아차리나요?",
      "누군가 괴롭힘당하는 것을 본 적이 있나요? 그때 어떻게 했나요?",
      "스탠리와 아서는 친구를 돕기 위해 어떤 계획을 세울 것 같나요?"] };
ACT["S2492"] = { s: "When Gilbert the opossum loses his tooth, he's so excited for the tooth fairy to come and leave him a surprise. But Lewis gets jealous and comes up with a sneaky plan.",
  q: ["Why is Lewis jealous of Gilbert?",
      "Have you ever felt jealous of a friend? What happened?",
      "What sneaky plan do you think Lewis comes up with?"],
  h: ["루이스는 왜 길버트를 질투하나요?",
      "친구를 질투한 적이 있나요? 그때 무슨 일이 있었나요?",
      "루이스는 어떤 꾀를 부릴 것 같나요?"] };
ACT["S2493"] = { s: "Gilbert the opossum is excited to go to the beach. He imagines himself as Surfer Dude, but he soon discovers that surfing is harder than it looks.",
  q: ["What does Gilbert imagine himself as at the beach?",
      "Have you ever tried something that was harder than you expected?",
      "What do you think Gilbert learns about surfing?"],
  h: ["길버트는 바닷가에서 자신을 무엇이라고 상상하나요?",
      "생각보다 훨씬 어려웠던 일을 해 본 적이 있나요?",
      "길버트는 서핑에 대해 무엇을 깨닫게 될 것 같나요?"] };
ACT["S2494"] = { s: "A younger brother gives specific, detailed advice on how to get older sisters annoyed.",
  q: ["What kind of advice does the younger brother give in this book?",
      "Do you have a brother or sister you like to tease sometimes?",
      "Do you think the brother's advice is a good idea? Why or why not?"],
  h: ["동생은 이 책에서 어떤 조언을 해 주나요?",
      "가끔 놀리고 싶은 형제나 자매가 있나요?",
      "동생의 조언이 좋은 생각이라고 생각하나요? 이유도 적어 보세요."] };
ACT["S2495"] = { s: "Mark gets to play the turkey in the second grade Thanksgiving play and he doesn't feel good about it. But he ends up saving the day.",
  q: ["What role does Mark play in the Thanksgiving play?",
      "Have you ever had a role or job you didn't want at first?",
      "How do you think Mark ends up saving the day?"],
  h: ["마크는 추수감사절 연극에서 어떤 역할을 맡나요?",
      "처음에는 원하지 않았던 역할이나 일을 맡은 적이 있나요?",
      "마크는 어떻게 상황을 구해 낼 것 같나요?"] };
ACT["S2496"] = { s: "Marley visits Uncle Bob's farm with Cassie. Cassie finds herself an excellent farmhand, but Marley is not sure what he can do to help.",
  q: ["What is Marley unsure about on the farm?",
      "Have you ever felt unsure how you could help with something?",
      "What do you think Marley could do to help on the farm?"],
  h: ["말리는 농장에서 무엇을 잘 모르겠다고 느끼나요?",
      "무언가를 어떻게 도와야 할지 몰라 망설인 적이 있나요?",
      "말리는 농장에서 어떻게 도움이 될 수 있을까요?"] };
ACT["S2497"] = { s: "Marley wonders how to make it up to Cassie after he eats her homework up.",
  q: ["What does Marley do that he needs to make up for?",
      "Have you ever had to make up for a mistake you made?",
      "What do you think Marley could do to make it up to Cassie?"],
  h: ["말리는 무엇을 했기 때문에 그것을 만회해야 하나요?",
      "저지른 실수를 만회해야 했던 적이 있나요?",
      "말리는 캐시에게 어떻게 사과하면 좋을까요?"] };
ACT["S2498"] = { s: "This book features a collection of spooky stories and rhymes based on folklore.",
  q: ["What kind of stories are collected in this book?",
      "Do you know a spooky story or rhyme passed down in your family?",
      "Which spooky story or rhyme in this book did you like best?"],
  h: ["이 책에는 어떤 이야기들이 모여 있나요?",
      "가족에게서 전해 들은 무서운 이야기나 노래를 알고 있나요?",
      "이 책 속 무서운 이야기나 노래 중 가장 좋았던 것은 무엇인가요?"] };
ACT["S2499"] = { s: "Joan can't read her book when Willy and Rosa pinch and fight. So she tells stories of two little alligators who are always fighting and biting.",
  q: ["What do Willy and Rosa do that stops Joan from reading?",
      "Have you ever had trouble concentrating because people nearby were fighting or arguing?",
      "Why do you think Joan tells a story about fighting alligators?"],
  h: ["윌리와 로사는 무엇을 해서 조안이 책을 못 읽게 만드나요?",
      "주변 사람들이 다투어서 집중하기 힘들었던 적이 있나요?",
      "조안은 왜 싸우는 악어 이야기를 들려줄까요?"] };
