// 간이 학습 질문 — Book No. S25 묶음. 사람이 아니라 AI 가 한 번 쓰고 굳힌 파일이다.
window.ACT = window.ACT || {};
var ACT = window.ACT;
ACT["S2500"] = { s: "Pish and Posh Best, beginner fairies, receive encouragement from the Monster Under the Bed as they each try to make four wise wishes to earn their wings.",
  q: ["What wish did Pish and Posh try to make in the story?",
      "If you were a fairy, what wish would you make first?",
      "What wise wish would you give to a beginner fairy?"],
  h: ["이야기에서 피시와 포시는 어떤 소원을 빌려고 했나요?",
      "네가 요정이라면 가장 먼저 어떤 소원을 빌고 싶나요?",
      "초보 요정에게 어떤 지혜로운 소원을 알려주고 싶나요?"] };
ACT["S2501"] = { s: "Jill and Apples are set to compete at the horse show. Jill wakes up extra early to get Apples ready. But Jill starts to get nervous when she gets a glimpse of the competition.",
  q: ["How did Jill feel when she saw the other horses at the show?",
      "Have you ever felt nervous before a contest or a game?",
      "What would you say to Jill to help her feel better?"],
  h: ["질은 쇼에서 다른 말들을 보았을 때 기분이 어땠나요?",
      "너는 시합이나 경기 전에 긴장한 적이 있나요?",
      "질에게 힘을 주기 위해 어떤 말을 해 주고 싶나요?"] };
ACT["S2502"] = { s: "Annie falls off her pony named Splash at a riding lesson. Now, she must decide whether to get back in the saddle.",
  q: ["Why did Annie fall off her pony, Splash?",
      "Have you ever fallen down and had to decide to try again?",
      "What would you say to Annie to help her get back in the saddle?"],
  h: ["애니는 왜 조랑말 스플래시에서 떨어졌나요?",
      "너는 넘어진 뒤에 다시 도전해야 했던 적이 있나요?",
      "애니가 다시 말에 오를 수 있도록 어떤 말을 해 주고 싶나요?"] };
ACT["S2503"] = { s: "This book features a collection of poems about school.",
  q: ["Which poem about school did you like the best in this book?",
      "What is something funny that happened at your school?",
      "What would you write a poem about your school?"],
  h: ["이 책에서 학교에 관한 시 중 어떤 것이 가장 좋았나요?",
      "너희 학교에서 있었던 재미있는 일은 무엇인가요?",
      "너라면 학교에 대해 어떤 시를 쓰고 싶나요?"] };
ACT["S2504"] = { s: "This book introduces Meriwether Lewis and William Clark, who captured a prairie dog and sent it to the president as a gift.",
  q: ["Why did Lewis and Clark send a prairie dog to the president?",
      "Have you ever sent a special gift to someone?",
      "What other animal do you think would make a good gift for a president?"],
  h: ["루이스와 클라크는 왜 대통령에게 프레리도그를 보냈나요?",
      "너는 누군가에게 특별한 선물을 보낸 적이 있나요?",
      "대통령에게 어울리는 선물로 또 어떤 동물이 좋을 것 같나요?"] };
ACT["S2505"] = { s: "Tramp is a scruffy dog, and Lady is a spoiled dog. Will Tramp and Lady fall in love?",
  q: ["How are Lady and Tramp different from each other?",
      "Have you ever become friends with someone very different from you?",
      "Do you think Lady and Tramp will become friends? Why?"],
  h: ["레이디와 트램프는 서로 어떻게 다른가요?",
      "너는 너와 많이 다른 친구와 사귄 적이 있나요?",
      "레이디와 트램프가 친구가 될 것 같나요? 그 이유는 무엇인가요?"] };
ACT["S2506"] = { s: "This book tells the tale of Princess Aurora, who falls into an enchanted sleep after pricking her finger on a spindle.",
  q: ["What happened to Princess Aurora when she pricked her finger?",
      "Have you ever gotten hurt by something small, like a pin or a needle?",
      "What do you think will happen to Princess Aurora next?"],
  h: ["오로라 공주는 손가락을 찔렸을 때 어떤 일이 일어났나요?",
      "너는 바늘처럼 작은 것에 다쳐 본 적이 있나요?",
      "오로라 공주에게 다음에 어떤 일이 일어날 것 같나요?"] };
ACT["S2507"] = { s: "Cinderella wants to go to the royal ball, but she is too busy with chores. Will she make it to the ball in time?",
  q: ["Why couldn't Cinderella go to the ball right away?",
      "What chores do you have to do at home?",
      "Do you think Cinderella will make it to the ball? Why?"],
  h: ["신데렐라는 왜 바로 무도회에 갈 수 없었나요?",
      "너는 집에서 어떤 집안일을 하나요?",
      "신데렐라가 무도회에 갈 수 있을 것 같나요? 그 이유는 무엇인가요?"] };
ACT["S2508"] = { s: "This book contains a Valentine-themed story starring a Disney Princess, Cinderella.",
  q: ["What special day does this Cinderella story happen on?",
      "How do you celebrate Valentine's Day?",
      "What would you give to someone you love on Valentine's Day?"],
  h: ["이 신데렐라 이야기는 어떤 특별한 날에 일어나나요?",
      "너는 밸런타인데이를 어떻게 보내나요?",
      "밸런타인데이에 사랑하는 사람에게 무엇을 주고 싶나요?"] };
ACT["S2509"] = { s: "Princess Merida, a skilled archer, defies a sacred custom and accidentally unleashes a beastly curse upon the kingdom.",
  q: ["What custom did Merida defy in this story?",
      "Have you ever broken a rule and something unexpected happened?",
      "What would you do if you were Merida after the curse happened?"],
  h: ["메리다는 이 이야기에서 어떤 관습을 따르지 않았나요?",
      "너는 규칙을 어겨서 예상하지 못한 일이 생긴 적이 있나요?",
      "저주가 일어난 뒤에 네가 메리다라면 어떻게 하겠나요?"] };
ACT["S2510"] = { s: "After years of living in a tower, Rapunzel escapes and sets off on an adventure.",
  q: ["How did Rapunzel escape from the tower?",
      "Have you ever wanted to go on an adventure outside your home?",
      "What place would you like to explore if you left home for a day?"],
  h: ["라푼젤은 탑에서 어떻게 빠져나왔나요?",
      "너는 집 밖으로 모험을 떠나고 싶었던 적이 있나요?",
      "하루 동안 집을 떠난다면 어디를 탐험하고 싶나요?"] };
ACT["S2511"] = { s: "Rapunzel acquaints herself with her parents and her kingdom, and she realizes there is much more to learn before she accepts her royal destiny.",
  q: ["What did Rapunzel need to learn before becoming a princess?",
      "What is something new you had to learn before doing something important?",
      "What do you think Rapunzel learned about her kingdom?"],
  h: ["라푼젤은 공주가 되기 전에 무엇을 배워야 했나요?",
      "너는 중요한 일을 하기 전에 새로 배워야 했던 것이 있나요?",
      "라푼젤이 왕국에 대해 무엇을 배웠을 것 같나요?"] };
ACT["S2512"] = { s: "Elsa's icy powers trap the kingdom of Arendelle in eternal winter. Anna teams up with a mountain man Kristoff and sets off to find her sister and save the kingdom.",
  q: ["Why did Anna team up with Kristoff?",
      "Have you ever worked with a friend to solve a big problem?",
      "What would you do to help Anna save the kingdom?"],
  h: ["안나는 왜 크리스토프와 함께 팀을 이루었나요?",
      "너는 친구와 함께 큰 문제를 해결해 본 적이 있나요?",
      "안나가 왕국을 구하도록 너라면 어떻게 도와주고 싶나요?"] };
ACT["S2513"] = { s: "Wendy and her brothers fly to Never Land with Peter. There they meet the Lost Boys, experience fairy magic, and battle the evil pirate Captain Hook.",
  q: ["Who did Wendy and her brothers meet in Never Land?",
      "Have you ever imagined flying to a magical place?",
      "What would you like to do if you visited Never Land?"],
  h: ["웬디와 오빠들은 네버랜드에서 누구를 만났나요?",
      "너는 마법 같은 곳으로 날아가는 상상을 해 본 적이 있나요?",
      "네버랜드에 간다면 무엇을 하고 싶나요?"] };
ACT["S2514"] = { s: "Pirate Code says Jake and his crew must race Captain Hook in a 'Winner Take All Competition.' The prize is Jake's ship, Bucky.",
  q: ["What did Jake and his crew have to do to win Bucky back?",
      "Have you ever raced someone to win something important?",
      "What would you do to help Jake win the race?"],
  h: ["제이크와 그의 친구들은 버키를 되찾기 위해 무엇을 해야 했나요?",
      "너는 소중한 것을 얻기 위해 경주해 본 적이 있나요?",
      "제이크가 경주에서 이기도록 어떻게 도와주고 싶나요?"] };
ACT["S2515"] = { s: "A fairy steals powerful blue pixie dust and flies away to join the pirates. Tinker Bell and her fairy friends start in pursuit.",
  q: ["Why did Tinker Bell and her friends chase after the fairy?",
      "Have you ever had to get something back that was taken from you?",
      "What would you say to the fairy who stole the pixie dust?"],
  h: ["팅커벨과 친구들은 왜 그 요정을 쫓아갔나요?",
      "너는 빼앗긴 물건을 되찾아야 했던 적이 있나요?",
      "요정 가루를 훔친 요정에게 어떤 말을 해 주고 싶나요?"] };
ACT["S2516"] = { s: "Tinker Bell helps her fairy friends prepare for the annual Autumn Revelry to restore the Pixie Dust Tree. But she accidentally put Pixie Hollow in jeopardy. She goes on a secret quest across the sea.",
  q: ["What did Tinker Bell need to fix after her mistake?",
      "Have you ever made a mistake and had to fix it?",
      "What do you think Tinker Bell found on her quest across the sea?"],
  h: ["팅커벨은 실수한 뒤에 무엇을 고쳐야 했나요?",
      "너는 실수를 하고 그것을 고쳐야 했던 적이 있나요?",
      "팅커벨이 바다 건너 모험에서 무엇을 찾았을 것 같나요?"] };
ACT["S2517"] = { s: "Tinker Bell, a warm-weather fairy, wonders what the mysterious Winter Woods is like. When she crosses the border, she meets a winter fairy with the very same sparkling wings as hers.",
  q: ["Who did Tinker Bell meet in the Winter Woods?",
      "Have you ever met someone who was surprisingly similar to you?",
      "What do you think Tinker Bell and the winter fairy will do together?"],
  h: ["팅커벨은 윈터 우즈에서 누구를 만났나요?",
      "너는 너와 놀랍도록 닮은 사람을 만난 적이 있나요?",
      "팅커벨과 겨울 요정이 함께 무엇을 할 것 같나요?"] };
ACT["S2518"] = { s: "Ariel, the daring mermaid princess, rescues the human Prince Eric from drowning and falls in love with him. For the chance to become human, Ariel trades her voice to the scheming sea witch, Ursula. The little mermaid will become Ursula's captive forever unless the human prince falls in love with her in three days.",
  q: ["What did Ariel trade to become human?",
      "Have you ever given up something important to get what you wanted?",
      "Do you think Ariel will win Prince Eric's love in three days? Why?"],
  h: ["에리얼은 인간이 되기 위해 무엇을 내주었나요?",
      "너는 원하는 것을 얻기 위해 소중한 것을 포기한 적이 있나요?",
      "에리얼이 3일 안에 에릭 왕자의 사랑을 얻을 것 같나요? 그 이유는 무엇인가요?"] };
ACT["S2519"] = { s: "When her mother marries a king, Sofia is no longer an average girl. She moves into the castle and trains as a princess.",
  q: ["What did Sofia have to do after moving into the castle?",
      "Have you ever had to learn new rules in a new place?",
      "What do you think is the hardest part of training to be a princess?"],
  h: ["소피아는 성으로 이사한 뒤 무엇을 해야 했나요?",
      "너는 새로운 곳에서 새로운 규칙을 배워야 했던 적이 있나요?",
      "공주가 되는 훈련에서 가장 어려운 부분은 무엇일 것 같나요?"] };
ACT["S2520"] = { s: "Prince Simba, the son of King Mufasa, is born in the Pride Lands. His uncle, Scar, devises a scheme to take the throne.",
  q: ["What did Scar want to do to Simba's family?",
      "Have you ever had someone treat you unfairly like Scar treats Simba's family?",
      "What would you warn Simba about his uncle Scar?"],
  h: ["스카는 심바의 가족에게 무엇을 하려고 했나요?",
      "너는 스카가 심바의 가족을 대하듯 불공평한 대우를 받은 적이 있나요?",
      "삼촌 스카에 대해 심바에게 어떤 경고를 해 주고 싶나요?"] };
ACT["S2521"] = { s: "Nemo gets caught and taken to the city of Sydney. His father, Marlin, sets on a journey to find his son.",
  q: ["Why did Marlin set off on his journey?",
      "Have you ever looked hard for someone or something you lost?",
      "What do you think Marlin needs to do to find Nemo?"],
  h: ["말린은 왜 여행을 떠났나요?",
      "너는 잃어버린 사람이나 물건을 열심히 찾아본 적이 있나요?",
      "말린이 니모를 찾으려면 무엇을 해야 할 것 같나요?"] };
ACT["S2522"] = { s: "Pooh and his friends set off to rescue Christopher Robin from a terrifying creature called a Backson.",
  q: ["Who did Pooh and his friends try to rescue?",
      "Have you ever helped rescue or find a friend?",
      "What would you do to help Pooh find Christopher Robin?"],
  h: ["푸와 친구들은 누구를 구하려고 했나요?",
      "너는 친구를 구하거나 찾는 것을 도운 적이 있나요?",
      "푸가 크리스토퍼 로빈을 찾도록 어떻게 도와주고 싶나요?"] };
ACT["S2523"] = { s: "It's spring in the wood. Winnie the Pooh is going on an Easter egg hunt, but he has a hole in his basket. Will he ever win the Easter egg hunt?",
  q: ["What problem did Pooh have with his basket during the Easter egg hunt?",
      "Have you ever had a problem while playing a game?",
      "What would you tell Pooh to help him win the egg hunt?"],
  h: ["푸는 부활절 달걀 찾기에서 바구니에 어떤 문제가 있었나요?",
      "너는 게임을 하다가 문제가 생긴 적이 있나요?",
      "푸가 달걀 찾기에서 이기도록 어떤 말을 해 주고 싶나요?"] };
ACT["S2524"] = { s: "Dusty Crophopper is a speed-loving crop duster. He dreams of competing in the tough air race.",
  q: ["What does Dusty Crophopper dream of doing?",
      "What is something you dream of doing one day?",
      "What do you think Dusty needs to do to be ready for the race?"],
  h: ["더스티 크롭하퍼는 무엇을 하는 것을 꿈꾸나요?",
      "너는 언젠가 이루고 싶은 꿈이 무엇인가요?",
      "더스티가 경주를 준비하려면 무엇을 해야 할 것 같나요?"] };
ACT["S2525"] = { s: "Lightning McQueen is a hotshot young race car. He gets lost on the way to a big race and learns about friendship and all.",
  q: ["What did Lightning McQueen learn while he was lost?",
      "Have you ever learned something important about friendship?",
      "What would you say to Lightning McQueen about being a good friend?"],
  h: ["라이트닝 맥퀸은 길을 잃었을 때 무엇을 배웠나요?",
      "너는 우정에 대해 중요한 것을 배운 적이 있나요?",
      "라이트닝 맥퀸에게 좋은 친구가 되는 법에 대해 어떤 말을 해 주고 싶나요?"] };
ACT["S2526"] = { s: "Lightning McQueen is ready to prove that he is the fastest car in the world. Along with his best friend, Mater, Lightning sets off on a global adventure of a lifetime.",
  q: ["Who went with Lightning McQueen on his global adventure?",
      "Have you ever traveled somewhere new with a friend?",
      "What place would you like to visit with your best friend?"],
  h: ["라이트닝 맥퀸은 세계 모험을 누구와 함께 떠났나요?",
      "너는 친구와 함께 새로운 곳으로 여행 간 적이 있나요?",
      "가장 친한 친구와 함께 가고 싶은 곳은 어디인가요?"] };
ACT["S2527"] = { s: "Mater is inspired by a visit to a town full of airplanes, and he decides to become the first flying tow truck in the world.",
  q: ["What did Mater decide to become after his visit?",
      "Has visiting a new place ever given you a new idea?",
      "What new thing would you like to try after visiting a new place?"],
  h: ["메이터는 방문한 뒤에 무엇이 되기로 결심했나요?",
      "새로운 곳을 방문하고 새로운 아이디어가 떠오른 적이 있나요?",
      "새로운 곳을 방문한 뒤에 도전해 보고 싶은 새로운 것은 무엇인가요?"] };
ACT["S2528"] = { s: "A moon buggy gets stuck in a space crater, and NASCA needs a tow truck to bring him back to Earth. Now, it is all up to Mater to rescue the stranded buggy!",
  q: ["What was Mater's job in this story?",
      "Have you ever helped rescue something that was stuck?",
      "How do you think Mater felt after rescuing the moon buggy?"],
  h: ["이 이야기에서 메이터가 한 일은 무엇인가요?",
      "너는 갇혀 있는 것을 구해 준 적이 있나요?",
      "달 버기를 구한 뒤 메이터는 기분이 어땠을 것 같나요?"] };
ACT["S2529"] = { s: "Scare master Sulley and his assistant Mike struggle to find a way to return a little girl to her home in the human world.",
  q: ["What did Sulley and Mike try to do for the little girl?",
      "Have you ever helped someone find their way home?",
      "What would you do to help Sulley and Mike?"],
  h: ["설리와 마이크는 어린 소녀를 위해 무엇을 하려고 했나요?",
      "너는 누군가 집으로 돌아가도록 도운 적이 있나요?",
      "설리와 마이크를 도와주기 위해 너라면 무엇을 하겠나요?"] };
ACT["S2530"] = { s: "During his first semester at Monsters University, Mike Wazowski dreams of becoming a scarer. But his dream gets derailed when he happens to meet hotshot Sulley.",
  q: ["What did Mike dream of becoming at Monsters University?",
      "What do you dream of becoming when you grow up?",
      "What do you think happened when Mike met Sulley?"],
  h: ["마이크는 몬스터 대학교에서 무엇이 되기를 꿈꿨나요?",
      "너는 커서 무엇이 되고 싶나요?",
      "마이크가 설리를 만났을 때 무슨 일이 있었을 것 같나요?"] };
ACT["S2531"] = { s: "In this book, Perry the Platypus sneaks away and fights his 100th battle with the evil Doctor Doofenshmirt.",
  q: ["Who does Perry the Platypus fight in this story?",
      "Have you ever had a secret job or mission, like Perry?",
      "What do you think happens in Perry's 100th battle?"],
  h: ["이 이야기에서 페리는 누구와 싸우나요?",
      "너는 페리처럼 비밀 임무나 일을 해 본 적이 있나요?",
      "페리의 100번째 전투에서 무슨 일이 일어날 것 같나요?"] };
ACT["S2532"] = { s: "Doc comes down with a case of 'achoo-achoo-sneezy-wheezy disease.' The toys become the doctors for a change! Through the experience, they all learn the importance of getting lots of sleep when you're sick.",
  q: ["What did the toys become when Doc got sick?",
      "Have you ever taken care of someone who was sick?",
      "What did the toys learn about being sick?"],
  h: ["닥이 아팠을 때 장난감들은 무엇이 되었나요?",
      "너는 아픈 사람을 돌본 적이 있나요?",
      "장난감들은 아플 때에 대해 무엇을 배웠나요?"] };
ACT["S2533"] = { s: "Woody is Andy's favorite toy cowboy. One day, a new toy named Buzz, who doesn't know that he is a toy, arrives.",
  q: ["What did Buzz not know about himself?",
      "Have you ever had a new friend join your group?",
      "What would you say to Buzz to help him understand he is a toy?"],
  h: ["버즈는 자기 자신에 대해 무엇을 몰랐나요?",
      "너희 모임에 새 친구가 들어온 적이 있나요?",
      "버즈가 자신이 장난감이라는 것을 알도록 어떤 말을 해 주고 싶나요?"] };
ACT["S2534"] = { s: "A visit to a fast-food restaurant causes a mix-up involving a mini Buzz Lightyear figure. Then the real Buzz goes on an adventurous journey home marked by kids' meal toys.",
  q: ["How did Buzz end up far from home?",
      "Have you ever gotten lost or separated from your family?",
      "What do you think helped Buzz find his way home?"],
  h: ["버즈는 어떻게 집에서 멀리 떨어지게 되었나요?",
      "너는 가족과 떨어지거나 길을 잃은 적이 있나요?",
      "버즈가 집을 찾도록 무엇이 도왔을 것 같나요?"] };
ACT["S2535"] = { s: "Mercy the pig, who adores buttered toast, captures a thief who sneaks into Mr. Watson's kitchen to rob. Book #3",
  q: ["What did Mercy do when a thief came into the kitchen?",
      "Have you ever caught someone doing something wrong?",
      "What would you say to thank Mercy for catching the thief?"],
  h: ["도둑이 부엌에 들어왔을 때 머시는 무엇을 했나요?",
      "너는 누군가 잘못하는 것을 알아챈 적이 있나요?",
      "도둑을 잡은 머시에게 어떤 말로 고마움을 전하고 싶나요?"] };
ACT["S2536"] = { s: "To Mr. and Mrs. Watson, Mercy the pig is a porcine wonder. The Watsons even welcome Mercy snuggling into their bed. But the bed and its occupants slowly sink through the floor. Book #1",
  q: ["What happened to the bed when Mercy snuggled into it?",
      "Have you ever had something break or fall apart unexpectedly?",
      "What do you think the Watsons should do about their sinking bed?"],
  h: ["머시가 침대에 파고들었을 때 침대에 무슨 일이 일어났나요?",
      "너는 갑자기 무언가 부서지거나 무너진 적이 있나요?",
      "가라앉는 침대에 대해 왓슨 가족은 어떻게 해야 할 것 같나요?"] };
ACT["S2537"] = { s: "Mr. Watson goes on a Saturday drive with his favorite pig, Mercy. But when an unexpected passenger shows up in the back seat, it turns into an adventure. Book #2",
  q: ["Who showed up as an unexpected passenger in the car?",
      "Have you ever had a surprise happen during a car ride?",
      "What do you think Mr. Watson said when he saw the passenger?"],
  h: ["차 뒷좌석에 뜻밖의 승객으로 누가 나타났나요?",
      "너는 차를 타고 가다가 놀라운 일을 겪은 적이 있나요?",
      "왓슨 씨는 그 승객을 보고 무슨 말을 했을 것 같나요?"] };
ACT["S2538"] = { s: "The Watsons persuade Mercy the pig to dress up as a princess for Halloween by using the magic word \"treating.\" But her trick-or-treat outing has some very unexpected results. Book #4",
  q: ["What did the Watsons dress Mercy up as for Halloween?",
      "What have you dressed up as for Halloween?",
      "What unexpected thing do you think happened during Mercy's outing?"],
  h: ["왓슨 가족은 핼러윈에 머시에게 무엇을 입혔나요?",
      "너는 핼러윈에 무엇으로 변장해 보았나요?",
      "머시의 외출에서 어떤 뜻밖의 일이 일어났을 것 같나요?"] };
ACT["S2539"] = { s: "Mercy Watson senses and follows the delightful scent of the pansies in her thoughtful neighbors' yard. Animal Control Officer is called out to handle the case of missing pansies. Book #5",
  q: ["What flowers did Mercy Watson follow the scent of?",
      "Have you ever followed a smell to find something?",
      "What do you think happened when Animal Control arrived?"],
  h: ["머시 왓슨은 어떤 꽃의 냄새를 따라갔나요?",
      "너는 냄새를 따라가서 무언가를 찾은 적이 있나요?",
      "동물 관리관이 도착했을 때 무슨 일이 일어났을 것 같나요?"] };
ACT["S2540"] = { s: "On a snowy day, Curious George plays in the snow, learns how to ski and wear snowshoes. He also helps a lost pig find its way home.",
  q: ["What did George do to help the lost pig?",
      "Have you ever helped someone or something find their way?",
      "What is your favorite thing to do on a snowy day?"],
  h: ["조지는 길을 잃은 돼지를 돕기 위해 무엇을 했나요?",
      "너는 누군가 길을 찾도록 도와준 적이 있나요?",
      "눈 오는 날 네가 가장 좋아하는 놀이는 무엇인가요?"] };
ACT["S2541"] = { s: "Curious George gets in trouble when he loses his tadpoles. Through his experience, he learns about the amazing life cycle of frogs.",
  q: ["What did George learn about after losing his tadpoles?",
      "Have you ever lost something and learned something from it?",
      "What do you know about how a tadpole becomes a frog?"],
  h: ["조지는 올챙이를 잃어버린 뒤 무엇에 대해 배웠나요?",
      "너는 무언가를 잃어버리고 그것에서 무언가를 배운 적이 있나요?",
      "올챙이가 개구리가 되는 과정에 대해 아는 것은 무엇인가요?"] };
ACT["S2542"] = { s: "Curious George gets lost when he sets out to feed the ducks on a small raft. He must find his way back home using landmarks.",
  q: ["How did George find his way back home?",
      "Have you ever used landmarks to find your way somewhere?",
      "What landmark near your house would help you find your way home?"],
  h: ["조지는 어떻게 집으로 돌아가는 길을 찾았나요?",
      "너는 길을 찾기 위해 표지물을 이용해 본 적이 있나요?",
      "집 근처에서 길을 찾는 데 도움이 되는 표지물은 무엇인가요?"] };
ACT["S2543"] = { s: "Curious George spends a wonderful day on the first day of school.",
  q: ["How did George spend his first day of school?",
      "What do you remember about your first day of school?",
      "What would you tell George to help him enjoy school?"],
  h: ["조지는 학교 첫날을 어떻게 보냈나요?",
      "너는 학교 첫날에 대해 기억나는 것이 있나요?",
      "조지가 학교를 즐기도록 어떤 말을 해 주고 싶나요?"] };
ACT["S2544"] = { s: "Even though Curious George can only roll gutter balls, he loves bowling. Will his gutter ball talent help save the day?",
  q: ["What kind of balls did George roll while bowling?",
      "Have you ever kept trying at something even though you weren't good at it?",
      "How do you think George's gutter balls saved the day?"],
  h: ["조지는 볼링을 할 때 어떤 공을 굴렸나요?",
      "너는 잘하지 못해도 계속 도전해 본 적이 있나요?",
      "조지의 거터볼이 어떻게 상황을 구했을 것 같나요?"] };
ACT["S2545"] = { s: "On Friendship Day, Dora travels around the world and return friendship bracelets.",
  q: ["What did Dora do on Friendship Day?",
      "Have you ever given a friend a special gift or bracelet?",
      "What would you give to a friend to show your friendship?"],
  h: ["도라는 우정의 날에 무엇을 했나요?",
      "너는 친구에게 특별한 선물이나 팔찌를 준 적이 있나요?",
      "우정을 보여주기 위해 친구에게 무엇을 주고 싶나요?"] };
ACT["S2546"] = { s: "Horrid Henry cannot understand why people waste their precious time writing thank-you letters for terrible presents. When he has to write one, he comes up with a spectacular idea that guarantees to make him rich.",
  q: ["What idea did Henry come up with about his thank-you letter?",
      "Have you ever had to write a thank-you letter or note?",
      "Do you think Henry's idea to get rich will work? Why?"],
  h: ["헨리는 감사 편지에 대해 어떤 아이디어를 생각해 냈나요?",
      "너는 감사 편지나 쪽지를 써 본 적이 있나요?",
      "헨리의 부자가 되는 아이디어가 성공할 것 같나요? 그 이유는 무엇인가요?"] };
ACT["S2547"] = { s: "Horrid Henry hates that he has to heave his weary bone to enter a cross-country run on Sports Day. He comes up with a wonderful idea of how to win the race.",
  q: ["What idea did Henry come up with to win the race?",
      "Have you ever tried a clever trick to win a game?",
      "Do you think Henry's idea to win the race was fair? Why?"],
  h: ["헨리는 경주에서 이기기 위해 어떤 아이디어를 생각해 냈나요?",
      "너는 게임에서 이기기 위해 영리한 방법을 써 본 적이 있나요?",
      "경주에서 이기려는 헨리의 방법이 공정했다고 생각하나요? 그 이유는 무엇인가요?"] };
ACT["S2548"] = { s: "When Herny hears the prize for the reading competition is a family trip to a theme park, he is determined to win. But how is Henry going to read all those books?",
  q: ["Why did Henry want to win the reading competition?",
      "Have you ever tried hard to win a prize?",
      "How do you think Henry managed to read all those books?"],
  h: ["헨리는 왜 독서 대회에서 이기고 싶어 했나요?",
      "너는 상을 타기 위해 열심히 노력한 적이 있나요?",
      "헨리는 그 많은 책을 어떻게 다 읽었을 것 같나요?"] };
ACT["S2549"] = { s: "When Henry sees Margaret giving her friends makeovers, Henry decides to 'borrow' her idea. Henry is sure that he can do it much, much better than Margaret.",
  q: ["What idea did Henry borrow from Margaret?",
      "Have you ever copied a friend's idea and tried to do it better?",
      "Do you think Henry did the makeovers better than Margaret? Why?"],
  h: ["헨리는 마거릿에게서 어떤 아이디어를 빌렸나요?",
      "너는 친구의 아이디어를 따라 하며 더 잘하려고 해 본 적이 있나요?",
      "헨리가 마거릿보다 메이크업을 더 잘했을 것 같나요? 그 이유는 무엇인가요?"] };
ACT["S2550"] = { s: "Henry's parents are dreading his upcoming birthday since his parties end in mischief and disaster every year. This year, Mum and Dad devise a cunning plan.",
  q: ["Why were Henry's parents worried about his birthday party?",
      "Have you ever planned a birthday party?",
      "What plan do you think Henry's parents made this year?"],
  h: ["헨리의 부모님은 왜 생일 파티를 걱정했나요?",
      "너는 생일 파티를 계획해 본 적이 있나요?",
      "올해 헨리의 부모님이 세운 계획은 무엇일 것 같나요?"] };
ACT["S2551"] = { s: "Horrid Henry cooperates with Moody Margaret to cook up Glop!",
  q: ["What did Henry and Margaret work together to make?",
      "Have you ever cooperated with someone you don't usually get along with?",
      "What do you think Glop looks or tastes like?"],
  h: ["헨리와 마거릿은 함께 무엇을 만들었나요?",
      "너는 평소 잘 지내지 않는 사람과 협력해 본 적이 있나요?",
      "글롭은 어떤 모습이나 맛일 것 같나요?"] };
ACT["S2552"] = { s: "When the Queen comes to visit his school, Horrid Henry gets up to some horrid tricks.",
  q: ["What did Henry do when the Queen visited his school?",
      "What would you do if a very important person visited your school?",
      "Do you think Henry's tricks were a good idea? Why?"],
  h: ["여왕이 학교를 방문했을 때 헨리는 무엇을 했나요?",
      "아주 중요한 사람이 너희 학교를 방문한다면 너는 무엇을 하겠나요?",
      "헨리의 장난이 좋은 생각이었다고 생각하나요? 그 이유는 무엇인가요?"] };
ACT["S2553"] = { s: "Horrid Henry has to make money fast! But how can he get rich in a short time?",
  q: ["What did Henry need to do quickly in this story?",
      "Have you ever tried to earn money quickly?",
      "What idea would you give Henry to get rich?"],
  h: ["이 이야기에서 헨리는 빠르게 무엇을 해야 했나요?",
      "너는 빨리 돈을 벌려고 해 본 적이 있나요?",
      "헨리가 부자가 되도록 어떤 아이디어를 주고 싶나요?"] };
ACT["S2554"] = { s: "When Henry is forced to play school at Moody Margaret's house, he devises a plan to find a way to get sent home.",
  q: ["What plan did Henry make while playing school at Margaret's house?",
      "Have you ever wanted to leave somewhere and made a plan to do it?",
      "Do you think Henry's plan worked? Why?"],
  h: ["헨리는 마거릿의 집에서 학교 놀이를 하며 어떤 계획을 세웠나요?",
      "너는 어딘가에서 나가고 싶어서 계획을 세운 적이 있나요?",
      "헨리의 계획이 성공했을 것 같나요? 그 이유는 무엇인가요?"] };
ACT["S2555"] = { s: "Horrid Henry's family goes on a journey to visit Prissy Polly and Pimply Paul. Henry is prepared to do whatever it takes to get out of the trip and go to Rude Ralph's birthday party instead.",
  q: ["Why didn't Henry want to go on the family trip?",
      "Have you ever wanted to go somewhere else instead of a family trip?",
      "What would you do if you were Henry to get out of the trip?"],
  h: ["헨리는 왜 가족 여행을 가고 싶지 않았나요?",
      "너는 가족 여행 대신 다른 곳에 가고 싶었던 적이 있나요?",
      "네가 헨리라면 여행을 피하기 위해 무엇을 하겠나요?"] };
ACT["S2556"] = { s: "Horrid Henry accidentally wears a big, pink girl's underwear to school.",
  q: ["What did Henry accidentally wear to school?",
      "Have you ever worn or brought the wrong thing to school by accident?",
      "What would you say to Henry to make him feel better?"],
  h: ["헨리는 학교에 실수로 무엇을 입고 갔나요?",
      "너는 실수로 학교에 잘못된 것을 가져가거나 입은 적이 있나요?",
      "헨리의 기분이 나아지도록 어떤 말을 해 주고 싶나요?"] };
ACT["S2557"] = { s: "When Miss Battle-Axe makes him the inn-keeper in the school Christmas Nativity play instead of Joseph, Henry makes his part bigger!",
  q: ["What role did Henry get in the Christmas play?",
      "Have you ever been in a school play or performance?",
      "What do you think Henry did to make his part bigger?"],
  h: ["헨리는 크리스마스 연극에서 어떤 역할을 맡았나요?",
      "너는 학교 연극이나 공연에 참여한 적이 있나요?",
      "헨리가 자기 역할을 더 크게 만들려고 무엇을 했을 것 같나요?"] };
ACT["S2558"] = { s: "Buzz and his dog, Raggs, go on a trip to outer space.",
  q: ["Who went with Buzz on the trip to outer space?",
      "If you could travel to outer space, who would you bring with you?",
      "What would you like to see if you went to outer space?"],
  h: ["버즈는 우주 여행을 누구와 함께 갔나요?",
      "네가 우주로 여행 간다면 누구를 데려가고 싶나요?",
      "우주에 간다면 무엇을 보고 싶나요?"] };
ACT["S2559"] = { s: "Buzz digs a mini-golf hole for a contest.",
  q: ["What did Buzz dig for the contest?",
      "Have you ever built or made something for a contest?",
      "What kind of mini-golf hole would you like to build?"],
  h: ["버즈는 대회를 위해 무엇을 팠나요?",
      "너는 대회를 위해 무언가를 만들거나 지어 본 적이 있나요?",
      "너는 어떤 미니 골프 구멍을 만들고 싶나요?"] };
ACT["S2560"] = { s: "After Buzz misses the school bus twice, he decides to invent a new way to go to school.",
  q: ["Why did Buzz decide to invent a new way to go to school?",
      "Have you ever missed the bus or been late for school?",
      "What new way would you invent to get to school?"],
  h: ["버즈는 왜 학교에 가는 새로운 방법을 발명하기로 했나요?",
      "너는 버스를 놓치거나 학교에 늦은 적이 있나요?",
      "너라면 학교에 가는 어떤 새로운 방법을 발명하고 싶나요?"] };
ACT["S2561"] = { s: "Buzz and his dad explore a cave.",
  q: ["Who did Buzz explore the cave with?",
      "Have you ever explored a cave or a dark place?",
      "What creature would you like to find in a cave?"],
  h: ["버즈는 누구와 함께 동굴을 탐험했나요?",
      "너는 동굴이나 어두운 곳을 탐험해 본 적이 있나요?",
      "동굴에서 어떤 생물을 발견하고 싶나요?"] };
ACT["S2562"] = { s: "Buzz gets a job at a toy shop.",
  q: ["Where did Buzz get a job in this story?",
      "Have you ever helped out at a store or shop?",
      "What job at a toy shop would you like to do?"],
  h: ["이 이야기에서 버즈는 어디에서 일을 했나요?",
      "너는 가게에서 일을 도와본 적이 있나요?",
      "장난감 가게에서 너는 어떤 일을 해 보고 싶나요?"] };
ACT["S2563"] = { s: "Margo the octopus is worried about being a model in an upcoming fashion show because when she gets nervous, she squirts ink.",
  q: ["What happens to Margo when she gets nervous?",
      "Have you ever felt nervous before doing something in front of others?",
      "What would you say to help Margo feel less nervous?"],
  h: ["마고는 긴장하면 어떤 일이 일어나나요?",
      "너는 다른 사람들 앞에서 무언가를 하기 전에 긴장한 적이 있나요?",
      "마고가 덜 긴장하도록 어떤 말을 해 주고 싶나요?"] };
ACT["S2564"] = { s: "Hardy the scaredy cat, but when he is attacked by a shark, he finds a way to be brave.",
  q: ["What happened to Hardy that made him find his courage?",
      "Have you ever had to be brave in a scary moment?",
      "What would you do if a shark attacked you like Hardy?"],
  h: ["하디는 어떤 일을 겪고 용기를 찾았나요?",
      "너는 무서운 순간에 용감해져야 했던 적이 있나요?",
      "하디처럼 상어에게 공격받는다면 너는 무엇을 하겠나요?"] };
ACT["S2565"] = { s: "Buzz invents a special paint that makes his skis go very fast.",
  q: ["What did Buzz invent to make his skis go fast?",
      "Have you ever invented or made something to help you go faster?",
      "What would you invent to make something faster?"],
  h: ["버즈는 스키를 빠르게 만들기 위해 무엇을 발명했나요?",
      "너는 더 빠르게 움직이도록 무언가를 만들거나 발명해 본 적이 있나요?",
      "너라면 무엇을 더 빠르게 만들 발명품을 만들고 싶나요?"] };
ACT["S2566"] = { s: "Marco the shark is afraid of going to the dentist, but his tooth will not stop hurting.",
  q: ["Why did Marco have to go to the dentist even though he was afraid?",
      "Have you ever been afraid to go to the dentist?",
      "What would you say to Marco to help him feel brave at the dentist?"],
  h: ["마르코는 무서워하면서도 왜 치과에 가야 했나요?",
      "너는 치과에 가는 것이 무서웠던 적이 있나요?",
      "마르코가 치과에서 용감해지도록 어떤 말을 해 주고 싶나요?"] };
ACT["S2567"] = { s: "Snorp hates his extra-long tongue, which is always in the way. Maybe his cousin Barker will have a solution for Snorp's problem.",
  q: ["What did Snorp not like about himself?",
      "Have you ever not liked something about yourself?",
      "What solution do you think Barker gave Snorp?"],
  h: ["스노프는 자신의 어떤 점이 마음에 들지 않았나요?",
      "너는 네 자신에 대해 마음에 들지 않은 점이 있었나요?",
      "바커가 스노프에게 준 해결책은 무엇이었을 것 같나요?"] };
ACT["S2568"] = { s: "This book presents the childhood of Jackie Robinson, the man who would grow up to be the first African American player in major league baseball.",
  q: ["What did Jackie Robinson become famous for as an adult?",
      "Have you ever admired someone who was the first to do something?",
      "What do you think Jackie Robinson was like as a child?"],
  h: ["잭키 로빈슨은 어른이 되어 무엇으로 유명해졌나요?",
      "너는 처음으로 어떤 일을 해낸 사람을 존경한 적이 있나요?",
      "어린 시절 잭키 로빈슨은 어떤 아이였을 것 같나요?"] };
ACT["S2569"] = { s: "The chef wants to get rid of the birds in his vegetable garden. Who will come up with a good idea?",
  q: ["What problem did the chef have in his vegetable garden?",
      "Have you ever had to find a way to solve a tricky problem?",
      "What idea would you give the chef to get rid of the birds?"],
  h: ["요리사는 채소밭에서 어떤 문제가 있었나요?",
      "너는 까다로운 문제를 풀 방법을 찾아본 적이 있나요?",
      "요리사가 새를 쫓아내도록 어떤 아이디어를 주고 싶나요?"] };
ACT["S2570"] = { s: "Ed drops a piece of gum on the street. But the gum keeps growing when lightning hits it.",
  q: ["What happened to Ed's gum after the lightning hit it?",
      "Have you ever seen something grow or change in a surprising way?",
      "What do you think Ed should do about the growing gum?"],
  h: ["번개가 껌을 쳤을 때 에드의 껌에 무슨 일이 일어났나요?",
      "너는 무언가 놀랍게 자라거나 변하는 것을 본 적이 있나요?",
      "에드는 자라나는 껌에 대해 어떻게 해야 할 것 같나요?"] };
ACT["S2571"] = { s: "Miss Drew put effort into teaching her class about recycling, and it seems to be very successful.",
  q: ["What did Miss Drew teach her class about?",
      "What do you do at home to recycle?",
      "What would you teach your class about recycling?"],
  h: ["드류 선생님은 학급 학생들에게 무엇을 가르쳤나요?",
      "너는 집에서 재활용을 위해 무엇을 하나요?",
      "너라면 반 친구들에게 재활용에 대해 무엇을 가르쳐 주고 싶나요?"] };
ACT["S2572"] = { s: "This tale from Africa tells about a turtle that gets into trouble when some hunters capture him for their hungry chief.",
  q: ["Why did the hunters capture the turtle?",
      "Have you ever been in trouble because someone else wanted something?",
      "How do you think the turtle got out of trouble?"],
  h: ["사냥꾼들은 왜 거북이를 잡았나요?",
      "너는 누군가 원하는 것 때문에 곤란해진 적이 있나요?",
      "거북이는 곤경에서 어떻게 벗어났을 것 같나요?"] };
ACT["S2573"] = { s: "Anansi the hungry trickster comes up with a cunning plan when all the animals are cooking.",
  q: ["What was Anansi trying to do while the animals were cooking?",
      "Have you ever tried a clever plan to get something you wanted?",
      "Do you think Anansi's plan worked? Why?"],
  h: ["동물들이 요리하는 동안 아난시는 무엇을 하려고 했나요?",
      "너는 원하는 것을 얻으려고 영리한 계획을 세워 본 적이 있나요?",
      "아난시의 계획이 성공했을 것 같나요? 그 이유는 무엇인가요?"] };
ACT["S2574"] = { s: "Anansi the trickster runs off with Monkey's bananas! Will Monkey give chase?",
  q: ["What did Anansi steal from Monkey?",
      "Have you ever had something of yours taken by someone?",
      "Do you think Monkey will catch Anansi? Why?"],
  h: ["아난시는 몽키에게서 무엇을 훔쳤나요?",
      "너는 네 물건을 누군가에게 빼앗긴 적이 있나요?",
      "몽키가 아난시를 잡을 것 같나요? 그 이유는 무엇인가요?"] };
ACT["S2575"] = { s: "Two sisters hear that the chief in the next village wants a wife, and they would like to marry him. But he seems somewhat strange.",
  q: ["Why did the two sisters want to marry the chief?",
      "Have you ever thought someone seemed strange when you first met them?",
      "What do you think is strange about the chief?"],
  h: ["두 자매는 왜 그 족장과 결혼하고 싶어 했나요?",
      "너는 처음 만난 사람이 이상하다고 느낀 적이 있나요?",
      "그 족장의 어떤 점이 이상할 것 같나요?"] };
ACT["S2576"] = { s: "Bluebird, who is just plain white, wants to look colorful and bright. Her feathers turn blue when she dives into a bright blue lake. Coyote wants to try as well.",
  q: ["How did Bluebird's feathers turn blue?",
      "Have you ever wanted to try something after seeing a friend do it?",
      "Do you think Coyote's plan to become blue will work? Why?"],
  h: ["블루버드의 깃털은 어떻게 파란색이 되었나요?",
      "너는 친구가 하는 것을 보고 따라 해 보고 싶었던 적이 있나요?",
      "코요테가 파란색이 되려는 계획이 성공할 것 같나요? 그 이유는 무엇인가요?"] };
ACT["S2577"] = { s: "While Bear and Fox are busy working, Brer Rabbit sneaks off for a nap. But when he wakes up, he finds himself down in a well! How will Brer Rabbit get out?",
  q: ["How did Brer Rabbit end up down in the well?",
      "Have you ever gotten into trouble while trying to avoid work?",
      "How do you think Brer Rabbit gets out of the well?"],
  h: ["브레어 래빗은 어떻게 우물에 빠지게 되었나요?",
      "너는 일을 피하려다가 곤란해진 적이 있나요?",
      "브레어 래빗은 우물에서 어떻게 빠져나올 것 같나요?"] };
ACT["S2578"] = { s: "Eagle the brave, who loves animals and birds, sails to an island with a stranger to go bird-watching, and he gets a nasty surprise.",
  q: ["Why did Eagle sail to the island with a stranger?",
      "Have you ever gone somewhere with someone you didn't know well?",
      "What surprise do you think Eagle found on the island?"],
  h: ["이글은 왜 낯선 사람과 함께 섬으로 항해했나요?",
      "너는 잘 모르는 사람과 함께 어딘가에 가 본 적이 있나요?",
      "이글이 섬에서 발견한 뜻밖의 일은 무엇이었을 것 같나요?"] };
ACT["S2579"] = { s: "When Uncle Tiger runs out of wood for his cooking fire, he sends Little Tiger to fetch some more wood from the village. But Little Tiger forgets about his task very soon.",
  q: ["What task did Little Tiger forget to do?",
      "Have you ever forgotten a task you were supposed to do?",
      "What do you think happened because Little Tiger forgot the wood?"],
  h: ["리틀 타이거는 어떤 할 일을 잊어버렸나요?",
      "너는 해야 할 일을 잊어버린 적이 있나요?",
      "리틀 타이거가 나무를 잊어버려서 무슨 일이 일어났을 것 같나요?"] };
ACT["S2580"] = { s: "Haridatta, a poor but diligent farmer, happens to meets a snake who gives him gold every day.",
  q: ["What does the snake give Haridatta every day?",
      "Have you ever received a kind gift from someone unexpectedly?",
      "What would you do if a snake gave you gold every day?"],
  h: ["뱀은 하리다타에게 매일 무엇을 주나요?",
      "너는 뜻밖에 누군가에게서 친절한 선물을 받은 적이 있나요?",
      "뱀이 매일 금을 준다면 너는 무엇을 하겠나요?"] };
ACT["S2581"] = { s: "Issun Boshi, a tiny but brave boy, sets out to serve the emperor. He is on the quest to save the emperor's daughter from the evil ogre.",
  q: ["Who does Issun Boshi try to save from the evil ogre?",
      "Have you ever helped someone even though you were small or young?",
      "What do you think Issun Boshi does to defeat the ogre?"],
  h: ["잇슨보시는 사악한 도깨비로부터 누구를 구하려고 하나요?",
      "너는 작거나 어려도 누군가를 도운 적이 있나요?",
      "잇슨보시는 도깨비를 물리치기 위해 무엇을 했을 것 같나요?"] };
ACT["S2582"] = { s: "A poor couple prays for a child, and their prayers are answered. But Ju-Long, their baby, is a frog. The frog believes that he can help his emperor win the war. Will he ever beat an army?",
  q: ["What does Ju-Long the frog believe he can do for the emperor?",
      "Have you ever believed you could help with something even if people doubted you?",
      "Do you think Ju-Long can help win the war? Why?"],
  h: ["개구리 주롱은 황제를 위해 무엇을 할 수 있다고 믿나요?",
      "너는 사람들이 의심해도 네가 도울 수 있다고 믿은 적이 있나요?",
      "주롱이 전쟁에서 이기도록 도울 수 있을 것 같나요? 그 이유는 무엇인가요?"] };
ACT["S2583"] = { s: "A girl called Anya comes to meet Baba Yaga, a mean witch who likes eating children. Can Anya escape being the witch's dinner?",
  q: ["Why is it dangerous for Anya to meet Baba Yaga?",
      "Have you ever had to be careful around someone or something scary?",
      "How do you think Anya can escape being the witch's dinner?"],
  h: ["아냐가 바바야가를 만나는 것이 왜 위험한가요?",
      "너는 무섭거나 조심해야 할 대상을 만난 적이 있나요?",
      "아냐는 마녀의 저녁밥이 되지 않으려면 어떻게 해야 할 것 같나요?"] };
ACT["S2584"] = { s: "Granny Wendy is taking a Witch Course to be a witch. But she finds it challenging to perform spells correctly.",
  q: ["What was hard for Granny Wendy to do correctly?",
      "Have you ever found it hard to learn a new skill?",
      "What advice would you give Wendy to help her cast spells?"],
  h: ["웬디 할머니는 무엇을 제대로 하기 어려워했나요?",
      "너는 새로운 것을 배우는 게 어려웠던 적이 있나요?",
      "웬디가 주문을 잘 외우도록 어떤 조언을 해 주고 싶나요?"] };
ACT["S2585"] = { s: "Mary and her friend Zach are helping her pirate Uncle Pete rescue his crewmates from a desert island.",
  q: ["What are Mary and Zach helping Uncle Pete do?",
      "Have you ever helped rescue or find someone?",
      "What would you bring if you went to rescue people on a desert island?"],
  h: ["메리와 잭은 피트 삼촌이 무엇을 하도록 돕고 있나요?",
      "너는 누군가를 구하거나 찾는 것을 도운 적이 있나요?",
      "무인도에서 사람들을 구하러 간다면 무엇을 가져가고 싶나요?"] };
ACT["S2586"] = { s: "George and Lottie find a lost dragon in their kitchen. They must solve a series of puzzles to get the dragon back home again.",
  q: ["What do George and Lottie need to solve to help the dragon?",
      "Have you ever solved a puzzle to help someone?",
      "What kind of puzzle do you think they had to solve?"],
  h: ["조지와 로티는 용을 돕기 위해 무엇을 풀어야 하나요?",
      "너는 누군가를 돕기 위해 퍼즐을 풀어 본 적이 있나요?",
      "그들이 풀어야 했던 퍼즐은 어떤 것이었을 것 같나요?"] };
ACT["S2587"] = { s: "Grandpa Spook is feeling sad that he isn't spooky anymore. Sam plans to invite all his friends to the best ever Spooks party to cheer him up.",
  q: ["Why is Grandpa Spook feeling sad?",
      "Have you ever planned something to cheer up someone who was sad?",
      "What would you do at the party to cheer up Grandpa Spook?"],
  h: ["스푸크 할아버지는 왜 슬퍼하고 있나요?",
      "너는 슬퍼하는 사람을 기쁘게 하려고 무언가를 계획한 적이 있나요?",
      "스푸크 할아버지를 기쁘게 하기 위해 파티에서 무엇을 하고 싶나요?"] };
ACT["S2588"] = { s: "Tom and Grace are determined to win the Chunkies Chocolate Competition. They set off to the amazing Chocolate Island in search of the best chocolate in the world.",
  q: ["What are Tom and Grace trying to win?",
      "Have you ever entered a contest for something you love?",
      "What do you think the best chocolate in the world tastes like?"],
  h: ["톰과 그레이스는 무엇을 얻으려고 하나요?",
      "너는 좋아하는 것을 얻으려고 대회에 나가 본 적이 있나요?",
      "세상에서 가장 맛있는 초콜릿은 어떤 맛일 것 같나요?"] };
ACT["S2589"] = { s: "Lucy and Horace, the sea monster, set out on an adventure to rescue Lucy's cat, Tom.",
  q: ["Who are Lucy and Horace trying to rescue?",
      "Have you ever gone on an adventure to save a pet?",
      "What do you think Lucy and Horace need to do to save Tom?"],
  h: ["루시와 호레이스는 누구를 구하려고 하나요?",
      "너는 반려동물을 구하기 위해 모험을 떠난 적이 있나요?",
      "루시와 호레이스는 톰을 구하기 위해 무엇을 해야 할 것 같나요?"] };
ACT["S2590"] = { s: "When Uncle Pete the Pirate comes to visit Molly, she wonders if he isn't bored without anything happening around.",
  q: ["What does Molly wonder about Uncle Pete?",
      "Have you ever worried that a visitor might be bored at your house?",
      "What would you do to make sure Uncle Pete isn't bored?"],
  h: ["몰리는 피트 삼촌에 대해 무엇을 궁금해하나요?",
      "너는 손님이 너희 집에서 심심해할까 봐 걱정한 적이 있나요?",
      "피트 삼촌이 심심하지 않도록 너는 무엇을 하겠나요?"] };
ACT["S2591"] = { s: "Wilfie discovers that his teddy is missing and sets off on an extraordinary journey to a magical land inhabited by lost teddies.",
  q: ["What does Wilfie discover is missing?",
      "Have you ever lost a favorite toy?",
      "What do you think the land of lost teddies looks like?"],
  h: ["윌피는 무엇이 사라진 것을 발견하나요?",
      "너는 가장 좋아하는 장난감을 잃어버린 적이 있나요?",
      "잃어버린 곰인형들의 나라는 어떤 모습일 것 같나요?"] };
ACT["S2592"] = { s: "After finding a message in a bottle, Lucy and Horace, the sea monster, set off to rescue two castaways on Treasure Island.",
  q: ["How did Lucy and Horace learn about the castaways?",
      "Have you ever found a message or clue that led to an adventure?",
      "What do you think Lucy and Horace need to bring to rescue the castaways?"],
  h: ["루시와 호레이스는 조난자들에 대해 어떻게 알게 되었나요?",
      "너는 모험으로 이어지는 메시지나 단서를 찾은 적이 있나요?",
      "루시와 호레이스는 조난자들을 구하기 위해 무엇을 가져가야 할 것 같나요?"] };
ACT["S2593"] = { s: "Molly can hardly believe it when she spots a magic carpet in her garden. Soon she soars through the sky on the trail of a troublesome magician.",
  q: ["What does Molly find in her garden?",
      "Have you ever imagined flying on something magical?",
      "Where would you fly if you had a magic carpet?"],
  h: ["몰리는 정원에서 무엇을 발견하나요?",
      "너는 마법 같은 것을 타고 날아가는 상상을 해 본 적이 있나요?",
      "마법 양탄자가 있다면 너는 어디로 날아가고 싶나요?"] };
ACT["S2594"] = { s: "Humphrey is a bully. But when he meets kind Beefy, his life is never the same again! This story deals with the problem of bullies and how kindness can turn Humphrey around.",
  q: ["What changed Humphrey's life in this story?",
      "Have you ever met someone kind who changed how you acted?",
      "What would you say to Humphrey about being kind to others?"],
  h: ["이 이야기에서 험프리의 삶을 바꾼 것은 무엇인가요?",
      "너는 친절한 사람을 만나 행동이 바뀐 적이 있나요?",
      "다른 사람에게 친절해지는 것에 대해 험프리에게 어떤 말을 해 주고 싶나요?"] };
ACT["S2595"] = { s: "This is a story of BushBob and his love of nature. This story deals with the appreciation of nature.",
  q: ["What does BushBob love in this story?",
      "What do you love about nature?",
      "What would you like to explore in nature with BushBob?"],
  h: ["이 이야기에서 부시밥은 무엇을 사랑하나요?",
      "너는 자연의 어떤 점을 좋아하나요?",
      "부시밥과 함께 자연에서 무엇을 탐험하고 싶나요?"] };
ACT["S2596"] = { s: "Read and find out if Grandpa's dying wish can save his oak tree.",
  q: ["What is Grandpa's wish about the oak tree?",
      "Have you ever tried to save something important to your family?",
      "Do you think the oak tree can be saved? Why?"],
  h: ["할아버지의 참나무에 대한 소원은 무엇인가요?",
      "너는 가족에게 소중한 것을 지키려고 해 본 적이 있나요?",
      "참나무를 구할 수 있을 것 같나요? 그 이유는 무엇인가요?"] };
ACT["S2597"] = { s: "When Milly and Molly experience the death of a school friend, a surprise helps them cope with the tragedy. This story deals with the value: Concern for Others and Coping with Grief.",
  q: ["What helps Milly and Molly cope with their sad feelings?",
      "Have you ever felt sad and had something help you feel better?",
      "What would you do to comfort a friend who is sad?"],
  h: ["밀리와 몰리가 슬픈 마음을 이겨내도록 도와준 것은 무엇인가요?",
      "너는 슬펐을 때 무언가가 너를 도와준 적이 있나요?",
      "슬퍼하는 친구를 위로하기 위해 너는 무엇을 하겠나요?"] };
ACT["S2598"] = { s: "It is the girls' first day at school. How will their pets fill their day? This story deals with the value: Responsibility and Acceptance of Difference.",
  q: ["What do the girls' pets do while they are at school?",
      "What does your pet or a pet you know do during the day?",
      "What responsibility do you have at home like Milly and Molly?"],
  h: ["여자아이들이 학교에 있는 동안 반려동물들은 무엇을 하나요?",
      "네 반려동물이나 아는 반려동물은 낮 동안 무엇을 하나요?",
      "밀리와 몰리처럼 너는 집에서 어떤 책임을 맡고 있나요?"] };
ACT["S2599"] = { s: "Oink is taken by a bad stranger. Milly and Molly think they will never see him again. This story teaches readers to beware of strangers.",
  q: ["What happened to Oink in this story?",
      "What should you do if a stranger tries to talk to you?",
      "What would you tell Milly and Molly to help them feel better?"],
  h: ["이 이야기에서 오잉크에게 무슨 일이 일어났나요?",
      "낯선 사람이 너에게 말을 걸려고 하면 너는 어떻게 해야 하나요?",
      "밀리와 몰리의 기분이 나아지도록 어떤 말을 해 주고 싶나요?"] };
