// 간이 학습 질문 — Book No. S26 묶음. 사람이 아니라 AI 가 한 번 쓰고 굳힌 파일이다.
window.ACT = window.ACT || {};
var ACT = window.ACT;
ACT["S2600"] = { s: "When Milly and Molly go for a quiet walk with Taffy Bogle, it turns into an adventure they will never forget. This story deals with the value: Responsibility.",
  q: ["What happens when Milly and Molly go for a walk with Taffy Bogle?",
      "Have you ever taken a pet for a walk?",
      "Write one thing you can do to be responsible for a pet."],
  h: ["밀리와 몰리가 태피 보글과 산책을 나가면 무슨 일이 생기나요?",
      "당신은 반려동물을 데리고 산책한 적이 있나요?",
      "반려동물을 책임감 있게 돌보기 위해 내가 할 수 있는 일 한 가지를 써 보세요."] };
ACT["S2601"] = { s: "Milly and Molly get to spend a night in the barn with Bunty, but they have no idea what is in store for them! This story deals with the value: Care and Consideration.",
  q: ["Where do Milly and Molly spend the night in this story?",
      "Have you ever slept somewhere new, like a barn or a tent?",
      "Write one way you can show care and consideration for a friend."],
  h: ["이 이야기에서 밀리와 몰리는 밤을 어디에서 보내나요?",
      "당신은 헛간이나 텐트처럼 새로운 곳에서 자 본 적이 있나요?",
      "친구를 배려하고 신경 써 주기 위해 내가 할 수 있는 일을 써 보세요."] };
ACT["S2602"] = { s: "Milly and Molly find something special about Alf. This story deals with the value: Celebration of Difference.",
  q: ["What do Milly and Molly find special about Alf?",
      "Do you have a friend who is different from you in a good way?",
      "Write one thing that makes you special and different."],
  h: ["밀리와 몰리는 알프에게서 무엇이 특별하다고 느끼나요?",
      "당신에게 좋은 의미로 나와 다른 친구가 있나요?",
      "나를 특별하고 다르게 만드는 것 한 가지를 써 보세요."] };
ACT["S2603"] = { s: "Milly and Molly find it challenging to help Aunt Maude. This story deals with the value of Tenacity.",
  q: ["Why is it challenging for Milly and Molly to help Aunt Maude?",
      "Have you ever kept trying at something hard until you finished it?",
      "Write one hard thing you want to keep trying at."],
  h: ["밀리와 몰리가 오드 이모를 돕는 일이 왜 힘든가요?",
      "당신은 힘든 일을 끝까지 포기하지 않고 해 본 적이 있나요?",
      "내가 포기하지 않고 계속 해 보고 싶은 힘든 일을 써 보세요."] };
ACT["S2604"] = { s: "Milly and Molly learn dads can be different. This story deals with the value of Acceptance of family diversity.",
  q: ["What do Milly and Molly learn about dads in this story?",
      "Do you know a family that looks different from yours?",
      "Write one thing you like about your own family."],
  h: ["이 이야기에서 밀리와 몰리는 아빠에 대해 무엇을 배우나요?",
      "당신은 우리 가족과 다르게 생긴 가족을 알고 있나요?",
      "우리 가족에 대해 내가 좋아하는 점 한 가지를 써 보세요."] };
ACT["S2605"] = { s: "Milly and Molly prepare for the worst when a 'bear' enters their tent. This story deals with the value of Courage and Determination.",
  q: ["What do Milly and Molly prepare for when a 'bear' enters their tent?",
      "Have you ever gone camping or slept in a tent?",
      "Write one scary thing you were brave about."],
  h: ["'곰'이 텐트에 들어왔을 때 밀리와 몰리는 무엇을 준비하나요?",
      "당신은 캠핑을 가거나 텐트에서 자 본 적이 있나요?",
      "내가 무서웠지만 용기를 냈던 일을 한 가지 써 보세요."] };
ACT["S2606"] = { s: "Follow Milly and Molly's exploit to the other side of the mountain. This story deals with the value of Thankfulness.",
  q: ["Where do Milly and Molly go in this story?",
      "Have you ever climbed a mountain or a big hill?",
      "Write one thing you are thankful for."],
  h: ["이 이야기에서 밀리와 몰리는 어디로 가나요?",
      "당신은 산이나 큰 언덕에 올라 본 적이 있나요?",
      "내가 감사하게 생각하는 것 한 가지를 써 보세요."] };
ACT["S2607"] = { s: "What does the message hiding in Milly's and Molly's Christmas parcels say? This story deals with the value of Love.",
  q: ["What is hiding in Milly's and Molly's Christmas parcels?",
      "Have you ever given or received a Christmas present?",
      "Write one person you love and why."],
  h: ["밀리와 몰리의 크리스마스 꾸러미 속에는 무엇이 숨겨져 있나요?",
      "당신은 크리스마스 선물을 주거나 받아 본 적이 있나요?",
      "내가 사랑하는 사람 한 명과 그 이유를 써 보세요."] };
ACT["S2608"] = { s: "Dad's sock is missing. Who will be rewarded for finding it? This story deals with the value of Helpfulness.",
  q: ["What is missing in this story, and who tries to find it?",
      "Have you ever helped someone find something they lost?",
      "Write one way you can be helpful at home."],
  h: ["이 이야기에서 무엇이 사라졌고, 누가 그것을 찾으려 하나요?",
      "당신은 누군가 잃어버린 물건을 찾도록 도와준 적이 있나요?",
      "집에서 내가 도움이 될 수 있는 일 한 가지를 써 보세요."] };
ACT["S2609"] = { s: "In this story, Milly and Molly learn that being honest does have its rewards. This story deals with the value: Honesty.",
  q: ["What do Milly and Molly learn about being honest?",
      "Have you ever told the truth even though it was hard?",
      "Write why you think honesty is important."],
  h: ["밀리와 몰리는 정직한 것에 대해 무엇을 배우나요?",
      "당신은 어려워도 사실대로 말한 적이 있나요?",
      "정직함이 왜 중요한지 내 생각을 써 보세요."] };
ACT["S2610"] = { s: "BiddyBid gives the wrong diagnosis for Milly and Molly's spots. Can they forgive her? This story deals with the value: Forgiveness.",
  q: ["What mistake does BiddyBid make?",
      "Have you ever forgiven someone who made a mistake?",
      "Write one time you forgave a friend."],
  h: ["비디비드는 어떤 실수를 하나요?",
      "당신은 실수한 누군가를 용서해 본 적이 있나요?",
      "친구를 용서했던 순간을 한 가지 써 보세요."] };
ACT["S2611"] = { s: "Milly and Molly have something to ask the elephant! This book teaches the value: Courtesy.",
  q: ["What do Milly and Molly want to ask the elephant?",
      "Have you ever asked someone politely for something?",
      "Write one polite word or phrase you like to use."],
  h: ["밀리와 몰리는 코끼리에게 무엇을 물어보고 싶어 하나요?",
      "당신은 누군가에게 공손하게 무언가를 부탁해 본 적이 있나요?",
      "내가 즐겨 쓰는 공손한 말 한 가지를 써 보세요."] };
ACT["S2612"] = { s: "Milly and Molly try to cheer Grandpa up, but something seems to be missing. This story deals with the value: Compassion.",
  q: ["What do Milly and Molly try to do for Grandpa?",
      "Have you ever tried to cheer up someone who felt sad?",
      "Write one thing you could do to cheer up a grandparent."],
  h: ["밀리와 몰리는 할아버지를 위해 무엇을 하려고 하나요?",
      "당신은 슬퍼하는 사람을 기쁘게 해 주려 한 적이 있나요?",
      "할머니나 할아버지를 기쁘게 해 드릴 수 있는 일 한 가지를 써 보세요."] };
ACT["S2613"] = { s: "This story is about Henry who knows how he feels and owns his feelings. This story deals with the value: Self-acceptance.",
  q: ["What does Henry know about himself?",
      "Do you know how you feel when you are happy or sad?",
      "Write one feeling you had today."],
  h: ["헨리는 자기 자신에 대해 무엇을 알고 있나요?",
      "당신은 기쁘거나 슬플 때 자신의 기분을 아나요?",
      "오늘 내가 느낀 감정 한 가지를 써 보세요."] };
ACT["S2614"] = { s: "On Pet Day, Milly and Molly's school playground quickly resembles a Zoo. This story deals with the value: Loyalty.",
  q: ["What does the school playground look like on Pet Day?",
      "Have you ever brought a pet somewhere special?",
      "Write one pet you would like to have."],
  h: ["애완동물의 날에 학교 운동장은 어떻게 보이나요?",
      "당신은 반려동물을 특별한 곳에 데려가 본 적이 있나요?",
      "내가 키우고 싶은 반려동물 한 가지를 써 보세요."] };
ACT["S2615"] = { s: "When the Queen is impressed by Milly and Molly's town, she makes a wonderful offer. This story teaches the value: Diligence.",
  q: ["Why is the Queen impressed by Milly and Molly's town?",
      "Have you ever worked hard on something and felt proud?",
      "Write one thing you work hard at."],
  h: ["여왕님은 왜 밀리와 몰리의 마을에 감동하나요?",
      "당신은 무언가를 열심히 해서 뿌듯했던 적이 있나요?",
      "내가 열심히 하는 일 한 가지를 써 보세요."] };
ACT["S2616"] = { s: "In this story, Milly and Molly learn something valuable from a wise, friendly spider. This book deals with the value: Wisdom.",
  q: ["What do Milly and Molly learn from the spider?",
      "Have you ever learned something wise from an animal or a friend?",
      "Write one wise thing someone has told you."],
  h: ["밀리와 몰리는 거미에게서 무엇을 배우나요?",
      "당신은 동물이나 친구에게서 지혜로운 것을 배운 적이 있나요?",
      "누군가 나에게 해 준 지혜로운 말 한 가지를 써 보세요."] };
ACT["S2617"] = { s: "Tom and Jack are no match for the wind, even with the help of Milly and Molly. This story teaches the value: Respect for Nature.",
  q: ["Who tries to help Tom and Jack against the wind?",
      "Have you ever felt a very strong wind?",
      "Write one way you can respect nature."],
  h: ["바람에 맞서는 톰과 잭을 누가 도와주려 하나요?",
      "당신은 아주 강한 바람을 느껴 본 적이 있나요?",
      "자연을 존중하기 위해 내가 할 수 있는 일 한 가지를 써 보세요."] };
ACT["S2618"] = { s: "This story teaches that behind every name is a 'special star.' This story teaches the value: Building self-esteem in others.",
  q: ["What does this story say is behind every name?",
      "Do you know what your name means, or why you were named that?",
      "Write one nice thing you could say to a friend about their name."],
  h: ["이 이야기는 모든 이름 뒤에 무엇이 있다고 말하나요?",
      "당신은 자신의 이름이 무슨 뜻인지, 왜 그렇게 지어졌는지 아나요?",
      "친구의 이름에 대해 해 줄 수 있는 좋은 말 한 가지를 써 보세요."] };
ACT["S2619"] = { s: "To have lunch at noon with Grandma, Milly and Molly set off on their bikes. This story teaches the value: Punctuality.",
  q: ["Why do Milly and Molly set off on their bikes?",
      "Have you ever ridden a bike to get somewhere on time?",
      "Write one time you arrived somewhere on time."],
  h: ["밀리와 몰리는 왜 자전거를 타고 출발하나요?",
      "당신은 제시간에 도착하려고 자전거를 타 본 적이 있나요?",
      "내가 제시간에 도착했던 일을 한 가지 써 보세요."] };
ACT["S2620"] = { s: "In this story, Milly and Molly turn their school into a cookie factory. This story teaches the value: Cooperation.",
  q: ["What do Milly and Molly turn their school into?",
      "Have you ever worked together with friends to make something?",
      "Write one thing you could make together with friends."],
  h: ["밀리와 몰리는 학교를 무엇으로 바꾸나요?",
      "당신은 친구들과 함께 무언가를 만들어 본 적이 있나요?",
      "친구들과 함께 만들고 싶은 것 한 가지를 써 보세요."] };
ACT["S2621"] = { s: "Milly and Molly learn a trusty steed is a friend indeed. This story teaches the value of Trustworthiness.",
  q: ["What does this story say a trusty steed can be?",
      "Do you have a friend or pet you really trust?",
      "Write one way you can be a trustworthy friend."],
  h: ["이 이야기는 믿음직한 말이 무엇이 될 수 있다고 말하나요?",
      "당신에게는 정말 믿는 친구나 반려동물이 있나요?",
      "믿음직한 친구가 되기 위해 내가 할 수 있는 일을 써 보세요."] };
ACT["S2622"] = { s: "Did you know that sharing feelings make for special friends? This story teaches the value of Sharing Feelings.",
  q: ["What does this story say makes friends special?",
      "Have you ever shared your feelings with a friend?",
      "Write one feeling you want to share with a friend."],
  h: ["이 이야기는 무엇이 친구를 특별하게 만든다고 말하나요?",
      "당신은 친구에게 내 감정을 이야기해 본 적이 있나요?",
      "친구에게 나누고 싶은 감정 한 가지를 써 보세요."] };
ACT["S2623"] = { s: "In this story, Milly and Molly learn that there is talent in everyone. This story teaches the value of a sense of worth.",
  q: ["What do Milly and Molly learn about talent in this story?",
      "Do you have a talent that makes you feel proud?",
      "Write one thing you are good at."],
  h: ["밀리와 몰리는 재능에 대해 무엇을 배우나요?",
      "당신에게는 스스로 자랑스러운 재능이 있나요?",
      "내가 잘하는 것 한 가지를 써 보세요."] };
ACT["S2624"] = { s: "Milly and Molly have a message that they want all the world to see. This story teaches the value: Care of for the environment.",
  q: ["What message do Milly and Molly want the world to see?",
      "Have you ever done something to help the environment?",
      "Write one thing you can do to help the environment."],
  h: ["밀리와 몰리는 세상 사람들이 무슨 메시지를 보기를 원하나요?",
      "당신은 환경을 지키기 위해 무언가를 해 본 적이 있나요?",
      "환경을 지키기 위해 내가 할 수 있는 일 한 가지를 써 보세요."] };
ACT["S2625"] = { s: "Maxter is a TV junkie. But building a tree hut changes Maxter for life. This story deals with the value: Exercise.",
  q: ["How does building a tree hut change Maxter?",
      "Do you like to watch TV, or do you like to play outside more?",
      "Write one outdoor activity you like to do."],
  h: ["나무 오두막을 짓는 것은 맥스터를 어떻게 바꾸나요?",
      "당신은 TV 보는 것을 좋아하나요, 아니면 밖에서 노는 것을 더 좋아하나요?",
      "내가 좋아하는 바깥 활동 한 가지를 써 보세요."] };
ACT["S2626"] = { s: "In this story, Milly and Molly go to jail! This story teaches the value: Self-improvement.",
  q: ["What surprising place do Milly and Molly go to in this story?",
      "Have you ever tried to improve something about yourself?",
      "Write one thing you want to get better at."],
  h: ["이 이야기에서 밀리와 몰리는 어디로 가서 놀랐나요?",
      "당신은 자신의 어떤 점을 더 낫게 만들려고 해 본 적이 있나요?",
      "내가 더 잘하고 싶은 것 한 가지를 써 보세요."] };
ACT["S2627"] = { s: "Milly and Molly want to help Billy Buttons achieve his dream. This story teaches the value: Self-empowerment.",
  q: ["What do Milly and Molly want to help Billy Buttons do?",
      "Has a friend ever helped you reach a dream?",
      "Write one dream you have."],
  h: ["밀리와 몰리는 빌리 버튼스가 무엇을 하도록 돕고 싶어 하나요?",
      "당신의 꿈을 친구가 도와준 적이 있나요?",
      "내가 가진 꿈 한 가지를 써 보세요."] };
ACT["S2628"] = { s: "When a black man and white man refuse to travel together, a ferryman comes up with a perfect solution. This story teaches the value: Accepting Differences.",
  q: ["What problem does the ferryman solve in this story?",
      "Have you ever helped two people who did not get along?",
      "Write why it is good to accept people who are different."],
  h: ["뱃사공은 이 이야기에서 어떤 문제를 해결하나요?",
      "당신은 사이가 안 좋은 두 사람을 도와준 적이 있나요?",
      "나와 다른 사람을 받아들이는 것이 왜 좋은지 써 보세요."] };
ACT["S2629"] = { s: "Milly and Molly learn to speak from their hearts, and the perfect response follows! This story teaches the value: Love.",
  q: ["What do Milly and Molly learn to do with their hearts?",
      "Have you told someone 'I love you' recently?",
      "Write one person you want to say 'I love you' to."],
  h: ["밀리와 몰리는 마음으로 무엇을 하는 법을 배우나요?",
      "당신은 최근에 누군가에게 '사랑해'라고 말해 보았나요?",
      "'사랑해'라고 말하고 싶은 사람 한 명을 써 보세요."] };
ACT["S2630"] = { s: "Milly and Molly help a friend turn his life around, and the result is outstanding. This story teaches the value of Determination.",
  q: ["How do Milly and Molly help their friend?",
      "Have you ever helped a friend who was having a hard time?",
      "Write one way you never give up."],
  h: ["밀리와 몰리는 친구를 어떻게 도와주나요?",
      "당신은 힘든 시간을 보내는 친구를 도와준 적이 있나요?",
      "내가 절대 포기하지 않는 것 한 가지를 써 보세요."] };
ACT["S2631"] = { s: "Milly and Molly learn to take care of the air. This story teaches the value: Care for the air.",
  q: ["What do Milly and Molly learn to take care of?",
      "Have you ever noticed the air was dirty or smoky?",
      "Write one way you can help keep the air clean."],
  h: ["밀리와 몰리는 무엇을 돌보는 법을 배우나요?",
      "당신은 공기가 더럽거나 매캐했던 적을 느낀 적이 있나요?",
      "공기를 깨끗하게 하기 위해 내가 할 수 있는 일을 써 보세요."] };
ACT["S2632"] = { s: "Milly and Molly give an invaluable gift to an old friend. This story teaches the value of Literacy.",
  q: ["What invaluable gift do Milly and Molly give to an old friend?",
      "Do you enjoy reading books?",
      "Write one book you would like to give a friend."],
  h: ["밀리와 몰리는 오랜 친구에게 어떤 소중한 선물을 주나요?",
      "당신은 책 읽는 것을 좋아하나요?",
      "친구에게 선물하고 싶은 책 한 권을 써 보세요."] };
ACT["S2633"] = { s: "With help from nature, Milly and Molly hatch a life-saving plan. This story teaches the value of Social responsibility.",
  q: ["How do Milly and Molly get help from nature?",
      "Have you ever grown a plant or a seed?",
      "Write one seed or plant you would like to grow."],
  h: ["밀리와 몰리는 자연에게서 어떻게 도움을 받나요?",
      "당신은 식물이나 씨앗을 키워 본 적이 있나요?",
      "내가 키워 보고 싶은 씨앗이나 식물 한 가지를 써 보세요."] };
ACT["S2634"] = { s: "Fly Guy unintentionally joins Buzz's class field trip to a flyswatter factory.",
  q: ["Where does Fly Guy go on the class field trip?",
      "Have you ever gone on a field trip with your class?",
      "Write one place you would like to visit on a field trip."],
  h: ["플라이 가이는 현장학습에서 어디로 가나요?",
      "당신은 반 친구들과 현장학습을 가 본 적이 있나요?",
      "현장학습으로 가 보고 싶은 곳 한 가지를 써 보세요."] };
ACT["S2635"] = { s: "Some of the people from his village want to teach Mr. Noisy how to be quiet.",
  q: ["What do the people in the village want to teach Mr. Noisy?",
      "Do you know someone who is very loud?",
      "Write one time you had to be quiet."],
  h: ["마을 사람들은 미스터 노이지에게 무엇을 가르쳐 주고 싶어 하나요?",
      "당신은 아주 시끄러운 사람을 알고 있나요?",
      "내가 조용히 해야 했던 순간을 한 가지 써 보세요."] };
ACT["S2636"] = { s: "When Mr. Impossible is walking in the woods, a boy shows up and takes him to school.",
  q: ["What happens to Mr. Impossible when he is walking in the woods?",
      "Have you ever met someone new who changed your day?",
      "Write one impossible thing you wish you could do."],
  h: ["미스터 임파서블이 숲을 걷다가 무슨 일이 생기나요?",
      "당신은 새로운 사람을 만나서 하루가 달라진 적이 있나요?",
      "할 수 있으면 좋겠다고 생각하는, 불가능해 보이는 일 한 가지를 써 보세요."] };
ACT["S2637"] = { s: "Mr. Quiet is cross with all the noise in Loudland and visits Mr. Happy in Happyland. Will he decide to relocate?",
  q: ["Why is Mr. Quiet cross in Loudland?",
      "Do you like quiet places or noisy places more?",
      "Write one quiet place you like."],
  h: ["미스터 콰이엇은 왜 라우드랜드에서 화가 나나요?",
      "당신은 조용한 곳과 시끄러운 곳 중 어느 곳을 더 좋아하나요?",
      "내가 좋아하는 조용한 곳 한 가지를 써 보세요."] };
ACT["S2638"] = { s: "This story is about Mr. Tall, who is very tall, quite the tallest person anyone has ever met.",
  q: ["What makes Mr. Tall different from everyone else?",
      "Do you know someone who is very tall or very short?",
      "Write one thing that is fun about being tall or short."],
  h: ["미스터 톨은 다른 사람들과 어떻게 다른가요?",
      "당신은 아주 키가 크거나 작은 사람을 알고 있나요?",
      "키가 크거나 작아서 좋은 점 한 가지를 써 보세요."] };
ACT["S2639"] = { s: "Mr. Worry worries about everything, and a wizard tries to relieve him of his worries.",
  q: ["Who tries to help Mr. Worry with his worries?",
      "What is something you sometimes worry about?",
      "Write one way you can feel better when you worry."],
  h: ["마법사는 미스터 워리의 걱정을 어떻게 도와주려 하나요?",
      "당신이 가끔 걱정하는 것은 무엇인가요?",
      "걱정될 때 기분이 나아지는 방법 한 가지를 써 보세요."] };
ACT["S2640"] = { s: "This is a story about Mr. Nonsense looking for a good friend.",
  q: ["What is Mr. Nonsense looking for in this story?",
      "How did you make a new friend?",
      "Write one thing you look for in a good friend."],
  h: ["미스터 넌센스는 이 이야기에서 무엇을 찾고 있나요?",
      "당신은 어떻게 새로운 친구를 사귀었나요?",
      "좋은 친구에게서 내가 바라는 점 한 가지를 써 보세요."] };
ACT["S2641"] = { s: "Mr. Clever comes to realize that there are many things he does not know.",
  q: ["What does Mr. Clever come to realize?",
      "Have you ever learned something you did not know before?",
      "Write one thing you want to learn more about."],
  h: ["미스터 클레버는 무엇을 깨닫게 되나요?",
      "당신은 몰랐던 것을 새로 배워 본 적이 있나요?",
      "내가 더 배우고 싶은 것 한 가지를 써 보세요."] };
ACT["S2642"] = { s: "This story is about Mr. Busy whipping up a picnic for Mr. Slow and himself.",
  q: ["What does Mr. Busy whip up for Mr. Slow and himself?",
      "Have you ever made food for a friend?",
      "Write one food you would like to make for a picnic."],
  h: ["미스터 비지는 미스터 슬로우와 자신을 위해 무엇을 뚝딱 만드나요?",
      "당신은 친구를 위해 음식을 만들어 본 적이 있나요?",
      "소풍을 위해 만들고 싶은 음식 한 가지를 써 보세요."] };
ACT["S2643"] = { s: "Because of his slow and leisurely way of doing things, Mr. Slow has a difficult time finding a suitable job.",
  q: ["Why does Mr. Slow have a hard time finding a job?",
      "Do you like to do things slowly or quickly?",
      "Write one job you think would fit someone who is slow and careful."],
  h: ["미스터 슬로우는 왜 일자리를 구하기 힘든가요?",
      "당신은 무엇을 천천히 하는 것과 빠르게 하는 것 중 어느 쪽을 좋아하나요?",
      "천천히 신중한 사람에게 어울릴 만한 직업 한 가지를 써 보세요."] };
ACT["S2644"] = { s: "This is a story about the wizard trying to stop Mr. Grumble from grumbling.",
  q: ["What does the wizard try to stop Mr. Grumble from doing?",
      "Do you ever grumble or complain about small things?",
      "Write one thing you could say instead of grumbling."],
  h: ["마법사는 미스터 그럼블이 무엇을 못 하게 막으려 하나요?",
      "당신은 작은 일에도 투덜거릴 때가 있나요?",
      "투덜거리는 대신 할 수 있는 말 한 가지를 써 보세요."] };
ACT["S2645"] = { s: "Mr. Cool takes a sick boy on an amazing adventure to help him feel better.",
  q: ["Where does Mr. Cool take the sick boy?",
      "Have you ever visited someone who was sick?",
      "Write one way you can help someone who is sick feel better."],
  h: ["미스터 쿨은 아픈 소년을 어디로 데려가나요?",
      "당신은 아픈 사람을 찾아가 본 적이 있나요?",
      "아픈 사람의 기분이 나아지게 도와줄 방법 한 가지를 써 보세요."] };
ACT["S2646"] = { s: "Mr. Good, who resides in Badland, feels very miserable. Will he find somewhere he belongs?",
  q: ["Where does Mr. Good live, and how does he feel?",
      "Have you ever felt like you did not belong somewhere?",
      "Write one place where you feel like you belong."],
  h: ["미스터 굿은 어디에 살고, 기분이 어떤가요?",
      "당신은 어딘가에 어울리지 않는다고 느낀 적이 있나요?",
      "내가 잘 어울린다고 느끼는 곳 한 가지를 써 보세요."] };
ACT["S2647"] = { s: "Mr. Nobody is taken to the wizard in the hope to become somebody.",
  q: ["Why is Mr. Nobody taken to the wizard?",
      "Have you ever felt like nobody noticed you?",
      "Write one thing that makes you feel like somebody special."],
  h: ["미스터 노바디는 왜 마법사에게 가게 되나요?",
      "당신은 아무도 나를 알아채지 못한다고 느낀 적이 있나요?",
      "내가 특별한 사람이라고 느끼게 해 주는 것 한 가지를 써 보세요."] };
ACT["S2648"] = { s: "This is a story about Mr. Muddle developing a plan to remember Christmas.",
  q: ["What plan does Mr. Muddle make in this story?",
      "How does your family remember or celebrate Christmas?",
      "Write one thing you want to remember this Christmas."],
  h: ["미스터 머들은 이 이야기에서 어떤 계획을 세우나요?",
      "당신의 가족은 크리스마스를 어떻게 기억하거나 기념하나요?",
      "이번 크리스마스에 기억하고 싶은 것 한 가지를 써 보세요."] };
ACT["S2649"] = { s: "This story is about Mr. Wrong who just cannot do anything right.",
  q: ["What kind of trouble does Mr. Wrong have?",
      "Have you ever made a mistake and felt bad about it?",
      "Write one thing that helps you feel better after a mistake."],
  h: ["미스터 롱은 어떤 어려움을 겪고 있나요?",
      "당신은 실수를 하고 속상했던 적이 있나요?",
      "실수한 뒤 기분이 나아지게 해 주는 것 한 가지를 써 보세요."] };
ACT["S2650"] = { s: "The Wizard cures Little Miss Bossy's problem with his magic.",
  q: ["What does the Wizard cure for Little Miss Bossy?",
      "Have you ever told a friend what to do too much?",
      "Write one way you can ask nicely instead of bossing."],
  h: ["마법사는 리틀 미스 보시의 어떤 문제를 고쳐 주나요?",
      "당신은 친구에게 이래라저래라 너무 많이 말한 적이 있나요?",
      "명령하는 대신 부드럽게 부탁할 수 있는 말 한 가지를 써 보세요."] };
ACT["S2651"] = { s: "Guess who cures Miss Naughty of her troublesome pranks.",
  q: ["Who cures Little Miss Naughty of her pranks?",
      "Have you ever played a prank on someone?",
      "Write one prank you think is funny but not mean."],
  h: ["리틀 미스 노티의 장난을 누가 고쳐 주나요?",
      "당신은 누군가에게 장난을 쳐 본 적이 있나요?",
      "짓궂지 않고 재미있다고 생각하는 장난 한 가지를 써 보세요."] };
ACT["S2652"] = { s: "When Little Miss Neat returns to her cottage from her holiday, she sees that someone has been there for tea.",
  q: ["What does Little Miss Neat find when she returns from her holiday?",
      "Have you ever come home and found something surprising?",
      "Write one way you keep your room neat."],
  h: ["리틀 미스 니트는 휴가에서 돌아와 무엇을 발견하나요?",
      "당신은 집에 왔을 때 놀라운 것을 발견한 적이 있나요?",
      "내 방을 깔끔하게 정리하는 방법 한 가지를 써 보세요."] };
ACT["S2653"] = { s: "Little Miss Sunshine visits Miseryland and makes a great change.",
  q: ["Where does Little Miss Sunshine visit, and what does she do there?",
      "Have you ever tried to make a sad place feel happier?",
      "Write one way you can bring sunshine to someone's day."],
  h: ["리틀 미스 선샤인은 어디를 방문하고, 그곳에서 무엇을 하나요?",
      "당신은 슬픈 곳을 더 행복하게 만들려고 해 본 적이 있나요?",
      "누군가의 하루를 밝게 해 줄 방법 한 가지를 써 보세요."] };
ACT["S2654"] = { s: "Despite the fact Little Miss Tiny is much smaller than others, Miss Tiny makes many new friends.",
  q: ["How does Little Miss Tiny make new friends?",
      "Have you ever made a friend even though you were different in size or age?",
      "Write one small thing that is special about you."],
  h: ["리틀 미스 타이니는 어떻게 새 친구를 사귀나요?",
      "당신은 크기나 나이가 달라도 친구를 사귄 적이 있나요?",
      "나에게 특별한, 작은 점 한 가지를 써 보세요."] };
ACT["S2655"] = { s: "Little Miss Trouble causes trouble until she takes her medicine.",
  q: ["What finally stops Little Miss Trouble from causing trouble?",
      "Have you ever gotten into trouble and had to fix it?",
      "Write one way you can stay out of trouble."],
  h: ["리틀 미스 트러블이 문제를 일으키는 것을 결국 무엇이 멈추게 하나요?",
      "당신은 문제를 일으키고 그것을 고쳐야 했던 적이 있나요?",
      "문제를 일으키지 않기 위해 내가 할 수 있는 일을 써 보세요."] };
ACT["S2656"] = { s: "Little Miss Giggles feels miserable when she loses her giggle.",
  q: ["How does Little Miss Giggles feel when she loses her giggle?",
      "What makes you giggle or laugh the most?",
      "Write one thing that always makes you smile."],
  h: ["리틀 미스 기글즈는 웃음을 잃었을 때 기분이 어떤가요?",
      "당신을 가장 많이 웃게 만드는 것은 무엇인가요?",
      "항상 나를 웃게 만드는 것 한 가지를 써 보세요."] };
ACT["S2657"] = { s: "Little Miss Helpful loves to help people, but she ends up helping nobody.",
  q: ["What happens when Little Miss Helpful tries to help people?",
      "Have you ever tried to help but it did not work out?",
      "Write one way you can help that really works."],
  h: ["리틀 미스 헬프풀이 사람들을 도우려 할 때 무슨 일이 생기나요?",
      "당신은 도와주려 했지만 잘 안 된 적이 있나요?",
      "정말로 도움이 되는 방법 한 가지를 써 보세요."] };
ACT["S2658"] = { s: "Mr. Tickle likes to tickle everyone he meets. But when a taste of Little Miss Magic’s powers persuades him, he curbs his behavior.",
  q: ["What does Mr. Tickle stop doing after he sees Little Miss Magic's powers?",
      "Have you ever changed your behavior after learning a lesson?",
      "Write one habit you would like to change."],
  h: ["미스터 티클은 리틀 미스 매직의 힘을 본 뒤 무엇을 그만두나요?",
      "당신은 교훈을 얻은 뒤 행동을 바꾼 적이 있나요?",
      "내가 바꾸고 싶은 습관 한 가지를 써 보세요."] };
ACT["S2659"] = { s: "Little Miss Splendid gets all washed up when it rains on her new hat.",
  q: ["What happens to Little Miss Splendid's new hat?",
      "Have you ever gotten wet in the rain by accident?",
      "Write one thing you like to wear on a rainy day."],
  h: ["리틀 미스 스플렌디드의 새 모자에 무슨 일이 생기나요?",
      "당신은 비를 맞아 실수로 젖은 적이 있나요?",
      "비 오는 날 입고 싶은 것 한 가지를 써 보세요."] };
ACT["S2660"] = { s: "The Little Miss Twins wants to show a visitor how everything occurs in pairs in Twoland.",
  q: ["What does Little Miss Twins want to show a visitor?",
      "Do you know any twins, or have you seen two things that match?",
      "Write one pair of things you like."],
  h: ["리틀 미스 트윈스는 방문객에게 무엇을 보여 주고 싶어 하나요?",
      "당신은 쌍둥이를 알거나, 똑같이 짝을 이루는 두 가지를 본 적이 있나요?",
      "내가 좋아하는 한 쌍의 물건을 써 보세요."] };
ACT["S2661"] = { s: "Little Miss Late always arrives for everything after it is over. What will happen when she meets Mr. Lazy?",
  q: ["What happens when Little Miss Late meets Mr. Lazy?",
      "Have you ever been late for something important?",
      "Write one way you can arrive somewhere on time."],
  h: ["리틀 미스 레이트가 미스터 레이지를 만나면 무슨 일이 생기나요?",
      "당신은 중요한 일에 늦은 적이 있나요?",
      "제시간에 도착하기 위한 방법 한 가지를 써 보세요."] };
ACT["S2662"] = { s: "When Little Miss Lucky leaves her cottage one winter night, she experiences a terrible adventure.",
  q: ["What happens when Little Miss Lucky leaves her cottage one winter night?",
      "Have you ever had an adventure at night?",
      "Write one lucky thing that has happened to you."],
  h: ["리틀 미스 럭키가 어느 겨울밤 오두막을 나서면 무슨 일이 생기나요?",
      "당신은 밤에 모험을 해 본 적이 있나요?",
      "나에게 있었던 운 좋은 일 한 가지를 써 보세요."] };
ACT["S2663"] = { s: "Forgetful Little Miss Scatterbrain has difficulty remembering names or where she puts her things.",
  q: ["What does Little Miss Scatterbrain have trouble remembering?",
      "Have you ever forgotten where you put something?",
      "Write one way you remember important things."],
  h: ["리틀 미스 스캐터브레인은 무엇을 기억하는 데 어려움을 겪나요?",
      "당신은 물건을 어디에 두었는지 잊은 적이 있나요?",
      "중요한 것을 기억하는 나만의 방법 한 가지를 써 보세요."] };
ACT["S2664"] = { s: "Little Miss Star dreams of being famous and finds a way to fulfill her dream.",
  q: ["What does Little Miss Star dream of?",
      "Do you dream of being famous for something?",
      "Write one dream you have for the future."],
  h: ["리틀 미스 스타는 무엇을 꿈꾸나요?",
      "당신은 무언가로 유명해지는 것을 꿈꾸나요?",
      "내가 미래에 이루고 싶은 꿈 한 가지를 써 보세요."] };
ACT["S2665"] = { s: "Little Miss Busy is a workaholic who doesn't know how to relax. When she is ill, all of her friends give her advice on how to rest.",
  q: ["Why do Little Miss Busy's friends give her advice?",
      "Do you ever forget to rest because you are so busy?",
      "Write one way you like to rest and relax."],
  h: ["리틀 미스 비지의 친구들은 왜 그녀에게 조언을 해 주나요?",
      "당신은 너무 바빠서 쉬는 것을 잊을 때가 있나요?",
      "내가 좋아하는 휴식 방법 한 가지를 써 보세요."] };
ACT["S2666"] = { s: "Little Miss Quick finishes everything as quickly as possible! But 'quickly' can also mean 'carelessly.'",
  q: ["What can happen when Little Miss Quick finishes things too quickly?",
      "Have you ever rushed and made a mistake?",
      "Write one time it is better to be slow and careful."],
  h: ["리틀 미스 퀵이 무언가를 너무 빨리 끝내면 무슨 일이 생길 수 있나요?",
      "당신은 서두르다가 실수를 한 적이 있나요?",
      "천천히 신중해야 좋은 순간을 한 가지 써 보세요."] };
ACT["S2667"] = { s: "When Little Miss Brainy gets tired of answering easy questions, she sets out in search of someone who can stump her.",
  q: ["What is Little Miss Brainy searching for?",
      "What is a hard question that once stumped you?",
      "Write one question you find hard to answer."],
  h: ["리틀 미스 브레이니는 무엇을 찾고 있나요?",
      "당신을 곤란하게 만들었던 어려운 질문은 무엇이었나요?",
      "내가 답하기 어려운 질문 한 가지를 써 보세요."] };
ACT["S2668"] = { s: "When everyone in her town gets sick of too curious Little Miss Curious, she runs away.",
  q: ["Why does Little Miss Curious run away?",
      "What is something you are curious about?",
      "Write one question you are curious about."],
  h: ["리틀 미스 큐리어스는 왜 도망치나요?",
      "당신이 궁금해하는 것은 무엇인가요?",
      "내가 궁금한 질문 한 가지를 써 보세요."] };
ACT["S2669"] = { s: "Little Miss Fun throws a fun party and entertains her guests until they are exhausted.",
  q: ["What does Little Miss Fun do at her party?",
      "Have you ever been to a party that was very fun?",
      "Write one fun thing you would do at your own party."],
  h: ["리틀 미스 펀은 파티에서 무엇을 하나요?",
      "당신은 아주 재미있었던 파티에 가 본 적이 있나요?",
      "내 파티에서 하고 싶은 재미있는 일 한 가지를 써 보세요."] };
ACT["S2670"] = { s: "This is a story about Little Miss Scary who loves to scare everyone.",
  q: ["What does Little Miss Scary love to do?",
      "Have you ever tried to scare a friend?",
      "Write one thing that scares you a little."],
  h: ["리틀 미스 스캐리는 무엇을 하기를 좋아하나요?",
      "당신은 친구를 놀래켜 본 적이 있나요?",
      "나를 조금 무섭게 만드는 것 한 가지를 써 보세요."] };
ACT["S2671"] = { s: "This is a story about Little Miss Hug who loves to hug more than anything.",
  q: ["What does Little Miss Hug love more than anything?",
      "Who do you like to hug?",
      "Write one person you would like to give a hug to."],
  h: ["리틀 미스 허그는 무엇보다 무엇을 좋아하나요?",
      "당신은 누구를 안아 주기를 좋아하나요?",
      "안아 주고 싶은 사람 한 명을 써 보세요."] };
ACT["S2672"] = { s: "Rabbit goes grocery shopping with his mom, and he compares amounts to decide what to buy. This book introduces the concepts of fewer, more, and the same.",
  q: ["What does Rabbit do while shopping with his mom?",
      "Have you ever gone grocery shopping with a family member?",
      "Write one food you would put in your shopping cart."],
  h: ["토끼는 엄마와 장을 보며 무엇을 하나요?",
      "당신은 가족과 함께 장을 보러 간 적이 있나요?",
      "내 장바구니에 담고 싶은 음식 한 가지를 써 보세요."] };
ACT["S2673"] = { s: "This simple rhyming story, perfect for teaching the concept of halves, introduces a brother and sister who do not want to share their food.",
  q: ["Why don't the brother and sister want to share their food?",
      "Have you ever had to share food with a brother or sister?",
      "Write one thing you don't mind sharing."],
  h: ["오빠와 여동생은 왜 음식을 나누고 싶어 하지 않나요?",
      "당신은 형제자매와 음식을 나눠 먹어야 했던 적이 있나요?",
      "내가 기꺼이 나눠 줄 수 있는 것 한 가지를 써 보세요."] };
ACT["S2674"] = { s: "One Saturday at the beach, three friends compete in a sandcastle building contest. They measure their sandcastles with spoons, shovels, and bare feet. This book introduces the concept of nonstandard measurement.",
  q: ["What do the three friends use to measure their sandcastles?",
      "Have you ever built a sandcastle at the beach?",
      "Write one thing you would build at the beach."],
  h: ["세 친구는 모래성을 재기 위해 무엇을 쓰나요?",
      "당신은 해변에서 모래성을 쌓아 본 적이 있나요?",
      "해변에서 만들고 싶은 것 한 가지를 써 보세요."] };
ACT["S2675"] = { s: "A girl is getting ready for school with the help of her clever dog that builds timelines to keep track of the time. This book explains the concepts of timelines.",
  q: ["How does the girl's dog help her get ready for school?",
      "How do you get ready for school in the morning?",
      "Write one thing you do every morning."],
  h: ["소녀의 강아지는 학교 갈 준비를 어떻게 도와주나요?",
      "당신은 아침에 학교 갈 준비를 어떻게 하나요?",
      "내가 매일 아침 하는 일 한 가지를 써 보세요."] };
ACT["S2676"] = { s: "Two frogs, Matty and Moe, count their hops to a rock, a log, and a pond. This book explains the concept of the equation.",
  q: ["Where do the two frogs count their hops to?",
      "Have you ever hopped or jumped to count something?",
      "Write one game you like to play by counting."],
  h: ["두 마리 개구리는 어디까지 깡충 뛰며 수를 세나요?",
      "당신은 무언가를 세려고 깡충 뛰어 본 적이 있나요?",
      "수를 세면서 하는, 내가 좋아하는 놀이 한 가지를 써 보세요."] };
ACT["S2677"] = { s: "The face-painting booth at the school fair offers opportunities to count combinations of coins, adding up to fifty.",
  q: ["What do children do at the face-painting booth?",
      "Have you ever counted coins to pay for something?",
      "Write one thing you would like to buy with fifty cents."],
  h: ["아이들은 페이스페인팅 부스에서 무엇을 하나요?",
      "당신은 무언가를 사려고 동전을 세어 본 적이 있나요?",
      "50센트로 사고 싶은 것 한 가지를 써 보세요."] };
ACT["S2678"] = { s: "A surprise birthday party is planned for a kangaroo by his friends, and they use multiplication to figure out how many things they have to do. This story provides opportunities to add and multiply.",
  q: ["What do the kangaroo's friends plan for him?",
      "Have you ever helped plan a surprise party?",
      "Write one thing you would do for a friend's surprise party."],
  h: ["캥거루의 친구들은 캥거루를 위해 무엇을 준비하나요?",
      "당신은 깜짝 파티를 준비해 본 적이 있나요?",
      "친구의 깜짝 파티를 위해 하고 싶은 일 한 가지를 써 보세요."] };
ACT["S2679"] = { s: "A group of friends goes on different rides at a carnival. This book introduces the concept of division.",
  q: ["Where do the friends go on different rides?",
      "Have you ever been to a carnival or an amusement park?",
      "Write one ride you would like to go on."],
  h: ["친구들은 어디에서 여러 놀이기구를 타나요?",
      "당신은 카니발이나 놀이공원에 가 본 적이 있나요?",
      "타 보고 싶은 놀이기구 한 가지를 써 보세요."] };
ACT["S2680"] = { s: "When the Elm Street Kids' Club needs money to fix their clubhouse, they decided to sell lemonade to earn money. To keep track of their sales, they use graphs. This book introduces bar graphs to readers.",
  q: ["Why does the Elm Street Kids' Club sell lemonade?",
      "Have you ever sold something to earn money?",
      "Write one thing you would sell to earn money."],
  h: ["엘름 스트리트 키즈 클럽은 왜 레모네이드를 파나요?",
      "당신은 돈을 벌기 위해 무언가를 팔아 본 적이 있나요?",
      "돈을 벌기 위해 팔고 싶은 것 한 가지를 써 보세요."] };
ACT["S2681"] = { s: "Farmer Skint and his family have fallen on hard times, but their luck changes with the arrival of a special golden goose.",
  q: ["How does the golden goose change Farmer Skint's family?",
      "Have you ever had good luck change your day?",
      "Write one thing you wish could bring you good luck."],
  h: ["황금 거위는 스킨트 농부 가족을 어떻게 바꾸나요?",
      "당신은 행운으로 하루가 달라진 적이 있나요?",
      "나에게 행운을 가져다주면 좋겠다고 생각하는 것 한 가지를 써 보세요."] };
ACT["S2682"] = { s: "Po loves kung fu, but he is not very good at it. Master Shifu is a great kung fu teacher, but he is afraid of Tai Lung. Can Po be a new Dragon Warrior?",
  q: ["What is Po not very good at, even though he loves it?",
      "Is there something you love to do even though you are not good at it yet?",
      "Write one thing you want to get better at, like Po."],
  h: ["포는 좋아하지만 잘하지 못하는 것이 무엇인가요?",
      "당신에게도 아직 잘하지 못하지만 좋아하는 일이 있나요?",
      "포처럼 내가 더 잘하고 싶은 것 한 가지를 써 보세요."] };
ACT["S2683"] = { s: "Alex the lion and his friends want to go back to New York Zoo but now they're in Africa! Can they live happily with the other animals on the reserve?",
  q: ["Where do Alex and his friends want to go back to?",
      "Have you ever been somewhere far from home?",
      "Write one place you miss."],
  h: ["알렉스와 친구들은 어디로 돌아가고 싶어 하나요?",
      "당신은 집에서 먼 곳에 가 본 적이 있나요?",
      "내가 그리워하는 곳 한 가지를 써 보세요."] };
ACT["S2684"] = { s: "Everyone thinks Manny is the last mammoth. Then he finds Ellie. But when the ice melts in the valley, can Manny, Ellie and his friends stay safe?",
  q: ["Who does Manny find in this story?",
      "Have you ever helped a new friend feel less alone?",
      "Write one way animals and people can stay safe from danger."],
  h: ["매니는 이 이야기에서 누구를 찾나요?",
      "당신은 새 친구가 외롭지 않게 도와준 적이 있나요?",
      "동물과 사람이 위험에서 안전하게 지낼 수 있는 방법을 써 보세요."] };
ACT["S2685"] = { s: "Mr. Bean eats some popcorn and hurts his tooth, so he goes to the dentist.",
  q: ["Why does Mr. Bean go to the dentist?",
      "Have you ever had a toothache?",
      "Write one way you take care of your teeth."],
  h: ["미스터 빈은 왜 치과에 가나요?",
      "당신은 이가 아팠던 적이 있나요?",
      "이를 관리하기 위해 내가 하는 일 한 가지를 써 보세요."] };
ACT["S2686"] = { s: "When the King and Queen of Far Far Away see that Fiona and her husband are ogres, they speak to the Fairy Godmother.",
  q: ["Who do the King and Queen speak to when they see Fiona and Shrek?",
      "Have you ever met someone's family for the first time?",
      "Write one thing that makes a family a family, no matter how they look."],
  h: ["왕과 왕비는 피오나와 슈렉을 보고 누구에게 이야기하나요?",
      "당신은 누군가의 가족을 처음 만나 본 적이 있나요?",
      "겉모습과 상관없이 가족을 가족답게 만드는 것 한 가지를 써 보세요."] };
ACT["S2687"] = { s: "Shrek and Fiona have three children now and live a peaceful life. Then, Rumpelstiltskin comes to them.",
  q: ["Who comes to visit Shrek and Fiona's family?",
      "Do you have brothers or sisters, or would you like to?",
      "Write one thing you like about your own peaceful life."],
  h: ["슈렉과 피오나의 가족에게 누가 찾아오나요?",
      "당신은 형제자매가 있나요, 아니면 있으면 좋겠다고 생각하나요?",
      "내 평화로운 일상에서 좋아하는 것 한 가지를 써 보세요."] };
ACT["S2688"] = { s: "The King is dying but Shrek doesn't want to be the new King. With Donkey and Puss In Boots, he goes to find Arthur, the King's heir.",
  q: ["Who does Shrek go to find with Donkey and Puss In Boots?",
      "Have you ever gone on a trip with friends to find someone or something?",
      "Write why you think Shrek doesn't want to be King."],
  h: ["슈렉은 동키, 장화 신은 고양이와 함께 누구를 찾으러 가나요?",
      "당신은 친구들과 함께 누군가나 무언가를 찾으러 떠나 본 적이 있나요?",
      "슈렉이 왕이 되고 싶어 하지 않는 이유를 내 생각대로 써 보세요."] };
ACT["S2689"] = { s: "Mr. Bean loves Buckingham Palace, so he paints his home and it looks the same.",
  q: ["Why does Mr. Bean paint his home?",
      "Is there a famous place you love and wish your home looked like?",
      "Write one thing you would change about your room if you could."],
  h: ["미스터 빈은 왜 자기 집을 페인트칠하나요?",
      "당신이 좋아해서 우리 집도 닮았으면 하는 유명한 장소가 있나요?",
      "할 수 있다면 내 방에서 바꾸고 싶은 것 한 가지를 써 보세요."] };
ACT["S2690"] = { s: "With new friend Buck, Diego and Manny help their friend Sid escape from the dangerous valley of the dinosaur.",
  q: ["Who helps Diego and Manny save Sid?",
      "Have you ever helped save a friend from a scary situation?",
      "Write one dangerous place you would be brave to explore."],
  h: ["디에고와 매니가 시드를 구하도록 누가 도와주나요?",
      "당신은 무서운 상황에서 친구를 구해 준 적이 있나요?",
      "용기를 내어 탐험해 보고 싶은 위험한 곳 한 가지를 써 보세요."] };
ACT["S2691"] = { s: "There is a new ruler in Gongmen City. Shen the peacock rules with the help of his new cannons. And Shen knows about Po's past.",
  q: ["How does Shen rule Gongmen City?",
      "Have you ever learned something surprising about your own past?",
      "Write one question you have about your own past."],
  h: ["셴은 공먼 시티를 어떻게 다스리나요?",
      "당신은 자신의 과거에 대해 놀라운 것을 알게 된 적이 있나요?",
      "내 과거에 대해 궁금한 질문 한 가지를 써 보세요."] };
ACT["S2692"] = { s: "Nanny McPhee goes to Mrs. Green's farm. There she finds a lot of mud, fighting children… and a very big bang!",
  q: ["What does Nanny McPhee find at Mrs. Green's farm?",
      "Have you ever visited a farm?",
      "Write one thing you would like to do on a farm."],
  h: ["내니 맥피는 그린 부인의 농장에서 무엇을 발견하나요?",
      "당신은 농장에 가 본 적이 있나요?",
      "농장에서 해 보고 싶은 것 한 가지를 써 보세요."] };
ACT["S2693"] = { s: "Aladdin is a poor, lazy boy who only likes to play, but when a magician comes to town and pretends to be his uncle, Aladdin's life changes forever.",
  q: ["How does the magician change Aladdin's life?",
      "Have you ever met someone who was not who they said they were?",
      "Write one wish you would make if you found a magic lamp."],
  h: ["마법사는 알라딘의 삶을 어떻게 바꾸나요?",
      "당신은 말과 다른 사람을 만나 본 적이 있나요?",
      "마법 램프를 찾으면 빌고 싶은 소원 한 가지를 써 보세요."] };
ACT["S2694"] = { s: "An ugly duckling spends an unhappy year unwelcomed by the other ducks before he grows into a beautiful swan.",
  q: ["How do the other ducks treat the ugly duckling?",
      "Have you ever felt left out because you looked different?",
      "Write one thing that makes you feel proud of how you look or who you are."],
  h: ["다른 오리들은 미운 오리 새끼를 어떻게 대하나요?",
      "당신은 다르게 생겨서 소외감을 느낀 적이 있나요?",
      "내 모습이나 나 자신에 대해 자랑스럽게 느끼는 것 한 가지를 써 보세요."] };
ACT["S2695"] = { s: "Two young, married Dalmatians must save their missing puppies and enlist the aid of their owners, Mr. and Mrs. Dearly, and all the country's dogs in their search.",
  q: ["Who helps the Dalmatians save their missing puppies?",
      "Have you ever lost something and needed help to find it?",
      "Write one way you would help find missing puppies."],
  h: ["달마시안 부부가 잃어버린 강아지들을 구하도록 누가 도와주나요?",
      "당신은 무언가를 잃어버려서 도움이 필요했던 적이 있나요?",
      "잃어버린 강아지들을 찾도록 도와줄 방법 한 가지를 써 보세요."] };
ACT["S2696"] = { s: "One day a princess loses her golden ball in a pond. A frog finds it for her and she promises to give him anything he wants. The frog wants to come into the palace with her.",
  q: ["What does the princess lose, and who finds it?",
      "Have you ever made a promise to someone?",
      "Write why you think it is important to keep a promise."],
  h: ["공주는 무엇을 잃어버리고, 누가 그것을 찾아 주나요?",
      "당신은 누군가에게 약속을 해 본 적이 있나요?",
      "약속을 지키는 것이 왜 중요한지 내 생각을 써 보세요."] };
ACT["S2697"] = { s: "Ali Baba, a young Persian boy who discovers a cave filled with treasures of forty deadly thieves. Unfortunately, his greedy brother cannot wait to get his hands on the riches.",
  q: ["What does Ali Baba discover in the cave?",
      "Have you ever found something valuable or exciting?",
      "Write why you think Ali Baba's brother's greed causes trouble."],
  h: ["알리바바는 동굴에서 무엇을 발견하나요?",
      "당신은 소중하거나 신나는 것을 발견해 본 적이 있나요?",
      "알리바바 형의 욕심이 왜 문제를 일으키는지 내 생각을 써 보세요."] };
ACT["S2698"] = { s: "This book is the story of Bella, who is unwittingly promised to a beast by her father. She has to live with him in his palace, and overcome her fear of his appearance to break the magic spell that binds him.",
  q: ["What does Bella have to overcome to break the magic spell?",
      "Have you ever gotten to know someone better after being scared of them at first?",
      "Write one time you looked past someone's appearance to know their heart."],
  h: ["벨라는 마법을 풀기 위해 무엇을 이겨 내야 하나요?",
      "당신은 처음엔 무서워했지만 나중에 잘 알게 된 사람이 있나요?",
      "겉모습보다 마음을 보려고 했던 순간을 한 가지 써 보세요."] };
ACT["S2699"] = { s: "This story is about a princess who escapes her wicked stepmother by hiding out in the home of seven hospitable dwarfs.",
  q: ["Who does the princess hide with to escape her stepmother?",
      "Have you ever needed help from new friends?",
      "Write one way you would welcome someone who needed help."],
  h: ["공주는 계모를 피해 누구와 함께 숨나요?",
      "당신은 새로운 친구들의 도움이 필요했던 적이 있나요?",
      "도움이 필요한 사람을 반갑게 맞이할 방법 한 가지를 써 보세요."] };
