// 간이 학습 질문 — Book No. S27 묶음. 사람이 아니라 AI 가 한 번 쓰고 굳힌 파일이다.
window.ACT = window.ACT || {};
var ACT = window.ACT;
ACT["S2700"] = { s: "Some lively clothes transform an ordinary school bus ride into a crazy journey.",
  q: ["What do the lively clothes turn the school bus ride into?",
      "Have you ever had a really fun bus ride?",
      "Write about what you would want to happen on a crazy bus ride."],
  h: ["활기찬 옷들이 스쿨버스 통학을 무엇으로 바꾸나요?",
      "정말 재미있었던 버스 여행을 해 본 적이 있나요?",
      "신나는 버스 여행에서 무슨 일이 일어나면 좋을지 써 보세요."] };
ACT["S2701"] = { s: "Two children find their way home despite an encounter with an old woman with wicked plans.",
  q: ["Who do the two children meet on their way home?",
      "Have you ever felt scared when you were lost?",
      "Write about what you would do if you met someone with wicked plans."],
  h: ["두 아이는 집으로 돌아가는 길에 누구를 만나나요?",
      "길을 잃어서 무서웠던 적이 있나요?",
      "나쁜 계획을 가진 사람을 만난다면 어떻게 할지 써 보세요."] };
ACT["S2702"] = { s: "Jack climbs to the top of a giant beanstalk, where he uses his quick wits to outsmart an ogre and make his and his mother's fortune.",
  q: ["What does Jack climb to the top of?",
      "Have you ever used a clever idea to solve a problem?",
      "Write about a clever plan you would use to outsmart a giant."],
  h: ["잭은 무엇의 꼭대기까지 올라가나요?",
      "영리한 생각으로 문제를 해결해 본 적이 있나요?",
      "거인을 이길 영리한 계획을 하나 써 보세요."] };
ACT["S2703"] = { s: "The story features the adventures of young Charlie Bucket inside the chocolate factory of eccentric chocolatier Willy Wonka.",
  q: ["Whose chocolate factory does Charlie Bucket explore?",
      "Have you ever visited a place that felt magical?",
      "Write about what you would want to see inside a chocolate factory."],
  h: ["찰리 버켓이 탐험하는 곳은 누구의 초콜릿 공장인가요?",
      "마법 같다고 느껴진 곳에 가 본 적이 있나요?",
      "초콜릿 공장 안에서 무엇을 보고 싶은지 써 보세요."] };
ACT["S2704"] = { s: "In Gepetto's hand, a piece of wood that talks becomes a living mischievous marionette and eventually becomes a real boy.",
  q: ["What does the piece of wood become at the end of the story?",
      "Have you ever wished a toy could come alive?",
      "Write about what you would do if your toy became alive for one day."],
  h: ["이야기 끝에 나무 조각은 무엇이 되나요?",
      "장난감이 살아 움직이면 좋겠다고 생각해 본 적이 있나요?",
      "내 장난감이 하루 동안 살아난다면 무엇을 할지 써 보세요."] };
ACT["S2705"] = { s: "The Toy Soldier?is very brave. He loves a ballet dancer, but can they ever be together?",
  q: ["Who does the Toy Soldier love?",
      "Have you ever liked someone but found it hard to be with them?",
      "Write about what you think will happen to the Toy Soldier and the ballet dancer."],
  h: ["장난감 병정은 누구를 좋아하나요?",
      "누군가를 좋아했지만 함께하기 어려웠던 적이 있나요?",
      "장난감 병정과 발레리나에게 무슨 일이 일어날지 내 생각을 써 보세요."] };
ACT["S2706"] = { s: "A strange little man helps the miller's daughter spin straw into gold for the king on the condition that she will give him her first-born child.",
  q: ["What does the strange little man help the miller's daughter spin straw into?",
      "Have you ever made a promise that was hard to keep?",
      "Write about what you would do if you had to keep a difficult promise."],
  h: ["이상한 작은 남자는 방앗간 딸이 짚을 무엇으로 잣도록 도와주나요?",
      "지키기 어려운 약속을 해 본 적이 있나요?",
      "어려운 약속을 지켜야 한다면 어떻게 할지 써 보세요."] };
ACT["S2707"] = { s: "When a beautiful girl named Rapunzel imprisoned by an enchantress meets a handsome prince, her long hair is the only means of escape.",
  q: ["What does Rapunzel use as the only means of escape?",
      "Have you ever wanted to help someone who was locked away?",
      "Write about another way Rapunzel could escape from the tower."],
  h: ["라푼젤이 탈출할 유일한 방법은 무엇인가요?",
      "갇혀 있는 누군가를 도와주고 싶었던 적이 있나요?",
      "라푼젤이 탑에서 탈출할 다른 방법을 생각해서 써 보세요."] };
ACT["S2708"] = { s: "George takes pictures and learns new things when he is curious about animal tracks.",
  q: ["What is George curious about in this book?",
      "Have you ever taken a picture of something interesting outside?",
      "Write about an animal track you would like to find."],
  h: ["조지는 이 책에서 무엇을 궁금해하나요?",
      "밖에서 신기한 것을 사진으로 찍어 본 적이 있나요?",
      "내가 찾아보고 싶은 동물 발자국을 써 보세요."] };
ACT["S2709"] = { s: "Curious George meets some amazing performing acrobats in a circus, and he somehow saves the circus show.",
  q: ["Who does George meet at the circus?",
      "Have you ever been to a circus or watched one on video?",
      "Write about how you think George saves the circus show."],
  h: ["조지는 서커스에서 누구를 만나나요?",
      "서커스에 가 보거나 영상으로 본 적이 있나요?",
      "조지가 서커스 공연을 어떻게 구했을지 상상해서 써 보세요."] };
ACT["S2710"] = { s: "It is Lola's first school picture day. She finds it challenging to stay clean all day when there are games to play, finger painting to do, and pink milk to enjoy.",
  q: ["What kind of day is it for Lola in this book?",
      "Have you ever tried hard to stay clean for something important?",
      "Write about what you would do to stay clean on picture day."],
  h: ["이 책에서 롤라에게 어떤 날인가요?",
      "중요한 일을 앞두고 깨끗하게 있으려고 애써 본 적이 있나요?",
      "사진 찍는 날 깨끗하게 지내려면 어떻게 할지 써 보세요."] };
ACT["S2711"] = { s: "Charlie plans to have a monster-themed party for his birthday. Lola is determined to help, but her idea of birthday fun and decorations is somewhat different from his idea.",
  q: ["What theme does Charlie choose for his birthday party?",
      "Have you ever planned a party with someone whose ideas were different from yours?",
      "Write about what theme you would choose for your own birthday party."],
  h: ["찰리는 생일 파티 주제로 무엇을 고르나요?",
      "나와 생각이 다른 사람과 함께 파티를 준비해 본 적이 있나요?",
      "내 생일 파티라면 어떤 주제를 고를지 써 보세요."] };
ACT["S2712"] = { s: "Lotta's new coat is the fluffiest, softest, loveliest one Lola has ever seen. She wants to borrow it for sure.",
  q: ["What does Lola want to borrow from Lotta?",
      "Have you ever wanted to borrow something special from a friend?",
      "Write about how you would take care of a borrowed coat."],
  h: ["롤라는 롯타에게서 무엇을 빌리고 싶어 하나요?",
      "친구의 특별한 물건을 빌리고 싶었던 적이 있나요?",
      "빌린 코트를 어떻게 소중히 다룰지 써 보세요."] };
ACT["S2713"] = { s: "Lola wants to win every game against her older brother Charlie. She even tries making up creative shortcuts to win a game.",
  q: ["What does Lola make up to try to win a game?",
      "Have you ever really wanted to win a game against someone?",
      "Write about a game you would like to win someday."],
  h: ["롤라는 게임에서 이기려고 무엇을 만들어 내나요?",
      "누군가와 게임을 하며 정말 이기고 싶었던 적이 있나요?",
      "언젠가 이겨 보고 싶은 게임을 써 보세요."] };
ACT["S2714"] = { s: "Charlie has a big soccer game, and he's promised Marv to go. But Lola has a cold, and Charlie meets her every demand.",
  q: ["What does Charlie promise Marv he will do?",
      "Have you ever taken care of someone who was sick?",
      "Write about what you would do if you were Charlie in this situation."],
  h: ["찰리는 마브에게 무엇을 하겠다고 약속했나요?",
      "아픈 사람을 돌봐 준 적이 있나요?",
      "내가 찰리라면 이 상황에서 어떻게 할지 써 보세요."] };
ACT["S2715"] = { s: "This book provides rhyming text that shows various animals as they dance their way in and around the jungle.",
  q: ["Where do the animals dance in this book?",
      "Have you ever danced with your family or friends?",
      "Write about which animal's dance you would like to try."],
  h: ["이 책에서 동물들은 어디에서 춤을 추나요?",
      "가족이나 친구와 함께 춤을 춰 본 적이 있나요?",
      "어떤 동물의 춤을 따라 해 보고 싶은지 써 보세요."] };
ACT["S2716"] = { s: "A homeless man changes his life thanks to a child's father. What happens to the man?",
  q: ["Who helps the homeless man change his life?",
      "Have you ever helped someone who needed it?",
      "Write about what you think happens to the man."],
  h: ["노숙자 남자가 삶을 바꾸도록 도와주는 사람은 누구인가요?",
      "도움이 필요한 누군가를 도와준 적이 있나요?",
      "그 남자에게 무슨 일이 일어났을지 내 생각을 써 보세요."] };
ACT["S2717"] = { s: "Illustrations and rhyming text present ten kinds of endangered animals.",
  q: ["How many kinds of endangered animals does this book present?",
      "Have you ever seen a picture of an endangered animal?",
      "Write about one endangered animal you would like to protect."],
  h: ["이 책에는 멸종 위기 동물이 몇 종류 나오나요?",
      "멸종 위기 동물 사진을 본 적이 있나요?",
      "내가 지켜 주고 싶은 멸종 위기 동물 하나를 써 보세요."] };
ACT["S2718"] = { s: "Woody gets kidnapped when Andy goes to Cowboy Camp. Buzz and the other toys set out on a journey to rescue Woody.",
  q: ["Who gets kidnapped while Andy is at Cowboy Camp?",
      "Have you ever helped rescue or find something that was lost?",
      "Write about what you would do to help rescue Woody."],
  h: ["앤디가 카우보이 캠프에 간 사이 누가 납치되나요?",
      "잃어버린 것을 찾거나 구하는 것을 도와준 적이 있나요?",
      "우디를 구하려면 어떻게 도울지 써 보세요."] };
ACT["S2719"] = { s: "Lola, who loves snow, gets very excited when the weatherman predicts a snowy day. But on an adventure to the Arctic, Lola learns why never-ending snow might not be so perfect.",
  q: ["What does Lola learn on her adventure to the Arctic?",
      "Do you like snowy days?",
      "Write about whether you think endless snow would be fun or not, and why."],
  h: ["롤라는 북극 모험에서 무엇을 배우나요?",
      "눈 오는 날을 좋아하나요?",
      "끝없이 눈이 온다면 재미있을지 아닐지 이유와 함께 써 보세요."] };
ACT["S2720"] = { s: "From the day that Peter is born, Henry is cross that he has a brother. But when Henry unintentionally saves Peter from a fierce dog, he discovers that it's rather nice to be a hero.",
  q: ["How does Henry accidentally save Peter?",
      "Have you ever felt cross about having a younger brother or sister?",
      "Write about a time you felt like a hero, even by accident."],
  h: ["헨리는 실수로 피터를 어떻게 구해 주나요?",
      "동생이 생겨서 짜증이 났던 적이 있나요?",
      "실수로라도 영웅처럼 느껴졌던 순간을 써 보세요."] };
ACT["S2721"] = { s: "In this book, Horrid Henry does horrible acts and causes chaos on his family holiday.",
  q: ["What does Henry cause on his family holiday?",
      "Have you ever caused a little chaos on a family trip?",
      "Write about what you would do differently if you were Henry on holiday."],
  h: ["헨리는 가족 휴가에서 무엇을 일으키나요?",
      "가족 여행에서 작은 소동을 일으킨 적이 있나요?",
      "내가 헨리라면 휴가에서 무엇을 다르게 할지 써 보세요."] };
ACT["S2722"] = { s: "In this story, Horrid Henry is a master hypnotist and puts Moody Margaret under his spell. But will Margaret do whatever Henry asks?",
  q: ["What does Henry do to Moody Margaret in this story?",
      "Have you ever pretended to hypnotize a friend for fun?",
      "Write about what you think Margaret will do after being hypnotized."],
  h: ["헨리는 이 이야기에서 무디 마가렛에게 무엇을 하나요?",
      "재미로 친구를 최면에 거는 척해 본 적이 있나요?",
      "최면에 걸린 마가렛이 어떻게 행동할지 내 생각을 써 보세요."] };
ACT["S2723"] = { s: "Horrid Henry is miserable when Peter loses a tooth before him. He comes up with a brilliant idea to trick the Tooth Fairy.",
  q: ["Why is Henry miserable at the start of this book?",
      "Have you ever lost a tooth?",
      "Write about a clever idea you would use to trick the Tooth Fairy."],
  h: ["이 책 처음에 헨리는 왜 속상해하나요?",
      "이가 빠져 본 적이 있나요?",
      "이빨 요정을 속일 영리한 방법을 써 보세요."] };
ACT["S2724"] = { s: "What will happen to an old lady who swallows many other things, one after another, starting with a chick?",
  q: ["What is the first thing the old lady swallows?",
      "Have you ever pretended to eat something silly or strange as a joke?",
      "Write about what you think the old lady will swallow next."],
  h: ["할머니가 가장 먼저 삼킨 것은 무엇인가요?",
      "장난으로라도 이상한 것을 먹는 척해 본 적이 있나요?",
      "할머니가 다음에 무엇을 삼킬지 내 생각을 써 보세요."] };
ACT["S2725"] = { s: "This book introduces a variation on a timeless rhyme featuring an old lady who swallows a bell, gifts, bows, and more.",
  q: ["What does the old lady swallow first in this book?",
      "Have you ever heard a fun rhyme like this one before?",
      "Write about another silly thing the old lady could swallow."],
  h: ["이 책에서 할머니가 가장 먼저 삼키는 것은 무엇인가요?",
      "이런 재미있는 운율의 노래를 들어 본 적이 있나요?",
      "할머니가 삼킬 만한 또 다른 엉뚱한 것을 생각해서 써 보세요."] };
ACT["S2726"] = { s: "This story describes an old lady who swallows various fall-themed items, starting with some leaves.",
  q: ["What is the first fall-themed item the old lady swallows?",
      "Do you like the fall season?",
      "Write about another fall item the old lady could swallow."],
  h: ["할머니가 가장 먼저 삼키는 가을 물건은 무엇인가요?",
      "가을을 좋아하나요?",
      "할머니가 삼킬 만한 또 다른 가을 물건을 써 보세요."] };
ACT["S2727"] = { s: "Five fiends steal pieces of the beautiful world to admire. But when they realize the beauty comes from being connected, they give them back.",
  q: ["Why do the five fiends give the pieces back?",
      "Have you ever realized that something is more beautiful when it's together with other things?",
      "Write about a piece of the world you would want to admire without taking it."],
  h: ["다섯 도깨비는 왜 조각들을 다시 돌려주나요?",
      "무언가가 다른 것과 함께 있을 때 더 아름답다고 느낀 적이 있나요?",
      "가져가지 않고 그냥 감상하고 싶은 세상의 한 조각을 써 보세요."] };
ACT["S2728"] = { s: "Trixie is unhappy to discover that Sonja and she both have the very same \"one-of-a-kind\" Knuffle Bunnies.",
  q: ["What do Trixie and Sonja both have?",
      "Have you ever found out someone else had the exact same special toy as you?",
      "Write about how you would feel if a friend had the exact same toy as you."],
  h: ["트릭시와 소냐는 둘 다 무엇을 가지고 있나요?",
      "다른 사람이 나와 똑같은 특별한 장난감을 가진 것을 알게 된 적이 있나요?",
      "친구가 나와 똑같은 장난감을 가지고 있다면 기분이 어떨지 써 보세요."] };
ACT["S2729"] = { s: "When Lucy searches for the beautiful butterfly she played in the garden the previous day, she discovers a world full of colorful creatures.",
  q: ["What does Lucy discover while searching for the butterfly?",
      "Have you ever looked for a small creature in a garden?",
      "Write about a colorful creature you would like to find in a garden."],
  h: ["루시는 나비를 찾다가 무엇을 발견하나요?",
      "정원에서 작은 생물을 찾아본 적이 있나요?",
      "정원에서 발견하고 싶은 화려한 생물을 써 보세요."] };
ACT["S2730"] = { s: "A little owl wonders how the things she sees at night look during the daytime and decides to stay awake.",
  q: ["What does the little owl decide to do?",
      "Have you ever wondered what something looks like at a different time of day?",
      "Write about what you think the owl sees during the daytime."],
  h: ["아기 올빼미는 무엇을 하기로 결심하나요?",
      "어떤 것이 다른 시간에는 어떻게 보일지 궁금했던 적이 있나요?",
      "올빼미가 낮 동안 무엇을 보았을지 내 생각을 써 보세요."] };
ACT["S2731"] = { s: "Harry discovers a bucketful of toy dinosaurs in the attic. When he names each one, the dinosaurs come to life.",
  q: ["What happens when Harry names each dinosaur?",
      "Have you ever given a name to one of your toys?",
      "Write about the name you would give to your own toy dinosaur."],
  h: ["해리가 공룡 이름을 지어 주자 무슨 일이 일어나나요?",
      "내 장난감에게 이름을 지어 준 적이 있나요?",
      "내 장난감 공룡에게 지어 줄 이름을 써 보세요."] };
ACT["S2732"] = { s: "Daisy has no idea what her father does for a living. She only knows that his boss is a real dragon. Guess what her daddy is.",
  q: ["What does Daisy know about her father's boss?",
      "Do you know what your parents do for work?",
      "Write your guess about what Daisy's daddy's job is."],
  h: ["데이지는 아빠의 상사에 대해 무엇을 알고 있나요?",
      "부모님이 무슨 일을 하시는지 알고 있나요?",
      "데이지 아빠의 직업이 무엇일지 내 생각을 써 보세요."] };
ACT["S2733"] = { s: "It is the day of the big balloon race. Her mother, Carlotta the Great, is the best lady balloonist in America. Without knowing it, Ariel almost causes her mother to lose a balloon race.",
  q: ["What is Ariel's mother's job?",
      "Have you ever accidentally caused a problem without knowing it?",
      "Write about what you would do to help your mother win a race."],
  h: ["아리엘의 엄마의 직업은 무엇인가요?",
      "나도 모르게 문제를 일으킨 적이 있나요?",
      "엄마가 경주에서 이기도록 어떻게 도울지 써 보세요."] };
ACT["S2734"] = { s: "May-May and Rose have several adventures when they travel to the west by wagon. They don't lose a chance to entertain people along the way.",
  q: ["How do May-May and Rose travel to the west?",
      "Have you ever taken a long trip?",
      "Write about how you would entertain people on a long trip."],
  h: ["메이메이와 로즈는 무엇을 타고 서부로 여행하나요?",
      "긴 여행을 떠나 본 적이 있나요?",
      "긴 여행 중에 사람들을 어떻게 즐겁게 해 줄지 써 보세요."] };
ACT["S2735"] = { s: "This book introduces the birth of the Paricutin volcano in the middle of the cornfield of a poor Mexican farmer.",
  q: ["Where does the Paricutin volcano appear?",
      "Have you ever seen a picture or video of a volcano?",
      "Write about how you think the farmer felt when the volcano appeared."],
  h: ["파리쿠틴 화산은 어디에서 생겨나나요?",
      "화산 사진이나 영상을 본 적이 있나요?",
      "화산이 생겼을 때 농부의 기분이 어땠을지 써 보세요."] };
ACT["S2736"] = { s: "Faith's family is traveling west to California. Faith's Pa is reluctant to take a chicken named Josefina on a wagon train. But Faith loves her pet and can't leave her behind. Will old Josefina show Pa that she still has a few surprises left in her?",
  q: ["What is the name of Faith's pet chicken?",
      "Have you ever refused to leave a pet behind?",
      "Write about what surprise you think Josefina shows Pa."],
  h: ["페이스가 기르는 닭의 이름은 무엇인가요?",
      "반려동물을 두고 갈 수 없다고 생각한 적이 있나요?",
      "조세피나가 아빠에게 보여 줄 놀라운 일이 무엇일지 써 보세요."] };
ACT["S2737"] = { s: "A little girl Marisol, who has a longing for a pet, makes friends with a stray dog. She convinces her grandfather, who never lets her, even pet stray dogs, to keep it outside their house at last.",
  q: ["Who does Marisol make friends with?",
      "Have you ever wanted a pet very much?",
      "Write about how you would convince someone to let you keep a pet."],
  h: ["마리솔은 누구와 친구가 되나요?",
      "반려동물을 정말 갖고 싶었던 적이 있나요?",
      "반려동물을 키우게 해 달라고 누군가를 어떻게 설득할지 써 보세요."] };
ACT["S2738"] = { s: "This historical fiction depicts a young boy fighting in the Battle of Lexington, the famous battle that marked the beginning of the American Revolution.",
  q: ["What battle does Sam fight in?",
      "Have you ever learned about a famous battle in history?",
      "Write about how you think Sam felt on the day of the battle."],
  h: ["샘은 어떤 전투에서 싸우나요?",
      "역사 속 유명한 전투에 대해 배워 본 적이 있나요?",
      "전투가 있던 날 샘의 기분이 어땠을지 써 보세요."] };
ACT["S2739"] = { s: "Rosie, Marvin's best friend, is the meanest cow in the world. When Rosie is sold and his family moves to a new farm, Marvin is inconsolable. Will Marvin ever adjust to a new life in a new place?",
  q: ["Who is Marvin's best friend in this book?",
      "Have you ever had to say goodbye to a friend when you moved?",
      "Write about what would help Marvin adjust to his new life."],
  h: ["이 책에서 마빈의 가장 친한 친구는 누구인가요?",
      "이사를 가면서 친구와 헤어져야 했던 적이 있나요?",
      "마빈이 새로운 삶에 적응하도록 무엇이 도움이 될지 써 보세요."] };
ACT["S2740"] = { s: "A Black family travels a long way to Kansas to take advantage of the free land offered through the Homestead Act after the Civil War. But the three boys must begin a journey of their own when Daddy moves on. They face the dangers of the wilderness alone and learn to care for one another.",
  q: ["Where does the family travel to get free land?",
      "Have you ever had to take care of your brother or sister on your own?",
      "Write about how the three boys learn to care for one another."],
  h: ["가족은 무료 땅을 얻으려고 어디로 이동하나요?",
      "혼자서 동생이나 형제를 돌봐야 했던 적이 있나요?",
      "세 소년이 서로를 돌보는 법을 어떻게 배우는지 상상해서 써 보세요."] };
ACT["S2741"] = { s: "This is a story about the struggle of a Swedish family traveling to America in the 19th century. In 1868, Carl Erik and his family receive a letter from an uncle in America. They decide to move abroad to make a new life. The family begins a long trek across land and sea to America.",
  q: ["What does the family receive that makes them decide to move to America?",
      "Have you ever moved to a new place, or thought about what that would be like?",
      "Write about what you think was the hardest part of the family's journey."],
  h: ["가족이 미국으로 이사하기로 결심하게 만드는 것은 무엇인가요?",
      "새로운 곳으로 이사해 본 적이 있거나 그것이 어떨지 생각해 본 적이 있나요?",
      "가족의 여행에서 가장 힘들었을 부분이 무엇일지 써 보세요."] };
ACT["S2742"] = { s: "This book is about the birth and the first six months of the life of a baby dolphin.",
  q: ["How many months of the baby dolphin's life does this book cover?",
      "Have you ever seen a dolphin, in real life or on a screen?",
      "Write about what you would like to know about a baby dolphin's life."],
  h: ["이 책은 아기 돌고래의 삶에서 몇 달 동안을 다루나요?",
      "실제로든 화면으로든 돌고래를 본 적이 있나요?",
      "아기 돌고래의 삶에 대해 알고 싶은 것을 써 보세요."] };
ACT["S2743"] = { s: "The American Revolution is being fought around Letty's family farm. The family must flee to safety before the British soldiers arrive. Letty tries to save her pet goose Solomon from marauding British soldiers.",
  q: ["What is the name of Letty's pet goose?",
      "Have you ever tried to protect something important to you?",
      "Write about how you think Letty saves her goose."],
  h: ["레티가 기르는 거위의 이름은 무엇인가요?",
      "나에게 소중한 것을 지키려고 애써 본 적이 있나요?",
      "레티가 거위를 어떻게 구했을지 상상해서 써 보세요."] };
ACT["S2744"] = { s: "A young Native American boy named Small Wolf sets out to hunt on Manhattan Island. There, he discovers some strange people with very different ideas about land.",
  q: ["Where does Small Wolf go to hunt?",
      "Have you ever met someone with very different ideas from yours?",
      "Write about what you think Small Wolf felt when he met the strange people."],
  h: ["스몰 울프는 사냥을 하러 어디로 가나요?",
      "나와 생각이 아주 다른 사람을 만나 본 적이 있나요?",
      "스몰 울프가 낯선 사람들을 만났을 때 어떤 기분이었을지 써 보세요."] };
ACT["S2745"] = { s: "Sixteen-year-old Bill becomes a rider for the Pony Express. While he works, he encounters many dangers but his letters home never hint at them.",
  q: ["How old is Bill when he becomes a Pony Express rider?",
      "Have you ever kept something worrying from your family to protect them?",
      "Write about why you think Bill never mentions the dangers in his letters."],
  h: ["빌은 몇 살에 포니 익스프레스 기수가 되나요?",
      "가족을 걱정시키지 않으려고 힘든 일을 숨겨 본 적이 있나요?",
      "빌이 편지에 위험한 일을 쓰지 않는 이유가 무엇일지 써 보세요."] };
ACT["S2746"] = { s: "Emma and her adopted brother want a pet. But Emma is allergic to furry animals. They try a lizard that has no fur.",
  q: ["Why can't Emma have a furry pet?",
      "Have you ever wanted a pet but couldn't have one for some reason?",
      "Write about what other pet without fur you would choose."],
  h: ["엠마는 왜 털 있는 반려동물을 키울 수 없나요?",
      "반려동물을 원했지만 어떤 이유로 키울 수 없었던 적이 있나요?",
      "털이 없는 반려동물 중 내가 고를 만한 것을 써 보세요."] };
ACT["S2747"] = { s: "This book presents easy magic tricks for the future magicians.",
  q: ["Who is this book written for?",
      "Have you ever tried a magic trick?",
      "Write about a magic trick you would like to learn."],
  h: ["이 책은 누구를 위해 쓰였나요?",
      "마술을 해 본 적이 있나요?",
      "배우고 싶은 마술을 써 보세요."] };
ACT["S2748"] = { s: "Minnie's jelly donut is missing! Moo is sure that it's been stolen. Minnie and Moo look for the thief who may have left behind a blue feather.",
  q: ["What clue might the thief have left behind?",
      "Have you ever looked for something that went missing?",
      "Write about who you think stole the jelly donut."],
  h: ["도둑이 남겼을 수도 있는 단서는 무엇인가요?",
      "잃어버린 물건을 찾아본 적이 있나요?",
      "누가 젤리 도넛을 훔쳤을지 내 생각을 써 보세요."] };
ACT["S2749"] = { s: "A bad dream upsets Minnie. Her barnyard friends find a way to make her feel better. They send her bed rolling into town on Halloween night to join the Halloween festivities.",
  q: ["What do Minnie's friends do to make her feel better?",
      "Have you ever had a bad dream that upset you?",
      "Write about what would make you feel better after a bad dream."],
  h: ["미니의 친구들은 미니의 기분을 풀어 주려고 무엇을 하나요?",
      "속상한 나쁜 꿈을 꾼 적이 있나요?",
      "나쁜 꿈을 꾼 뒤 기분이 나아지려면 무엇이 도움이 될지 써 보세요."] };
ACT["S2750"] = { s: "Clara wishes to learn to read but her papa doesn't allow her. Her dream comes true when a horse-drawn book wagon visits their farm with the country's first traveling library.",
  q: ["What does Clara wish to learn?",
      "Have you ever wanted to learn something that was hard to start?",
      "Write about what you think Clara feels when the book wagon arrives."],
  h: ["클라라는 무엇을 배우고 싶어 하나요?",
      "시작하기 어려웠지만 배우고 싶었던 것이 있나요?",
      "책 마차가 도착했을 때 클라라의 기분이 어땠을지 써 보세요."] };
ACT["S2751"] = { s: "Emma has wished for a little brother for so long. Now her family is adopting Max. But it seems to be more to having a little brother than she had ever guessed. Emma finally learns to be the sister he needs.",
  q: ["What is the name of the brother Emma's family adopts?",
      "Have you ever wished for a sibling, or wished yours was different?",
      "Write about what kind of sister or brother you try to be."],
  h: ["엠마의 가족이 입양하는 남동생의 이름은 무엇인가요?",
      "형제나 자매를 원했거나 다르길 바랐던 적이 있나요?",
      "나는 어떤 언니, 오빠, 누나, 형, 동생이 되려고 하는지 써 보세요."] };
ACT["S2752"] = { s: "This story describes the long trek of Swedish immigrants, from their arrival in New York to their journey home in Minnesota.",
  q: ["Where do the Swedish immigrants arrive first?",
      "Have you ever taken a very long journey?",
      "Write about what you think was hardest about their trek to Minnesota."],
  h: ["스웨덴 이민자들은 처음 어디에 도착하나요?",
      "아주 긴 여행을 해 본 적이 있나요?",
      "미네소타까지 가는 여정에서 무엇이 가장 힘들었을지 써 보세요."] };
ACT["S2753"] = { s: "Minnie and Moo go to the bank to ask for money to help Mr. Farmer with his finances. Then they are mistaken for the dangerous outlaws, the Bazooka sisters.",
  q: ["Why do Minnie and Moo go to the bank?",
      "Have you ever been mistaken for someone else?",
      "Write about how you think Minnie and Moo prove they are not outlaws."],
  h: ["미니와 무는 왜 은행에 가나요?",
      "다른 사람으로 오해받은 적이 있나요?",
      "미니와 무가 무법자가 아니라는 것을 어떻게 증명했을지 써 보세요."] };
ACT["S2754"] = { s: "May-May and Rose, singing and dancing Golly Sisters, hit on the road to give chances to more audiences to enjoy their show.",
  q: ["What do May-May and Rose do for their audience?",
      "Have you ever performed a song or dance for other people?",
      "Write about what show you would like to put on for an audience."],
  h: ["메이메이와 로즈는 관객을 위해 무엇을 하나요?",
      "다른 사람들 앞에서 노래나 춤을 보여 준 적이 있나요?",
      "관객을 위해 보여 주고 싶은 공연을 써 보세요."] };
ACT["S2755"] = { s: "May-May and Rose, the hilarious singing and dancing Golly sisters, take their traveling show through the West.",
  q: ["What kind of show do May-May and Rose put on?",
      "Have you ever traveled somewhere to share something you enjoy doing?",
      "Write about where you would like to travel to perform your own show."],
  h: ["메이메이와 로즈는 어떤 공연을 하나요?",
      "좋아하는 일을 나누러 어딘가로 여행 가 본 적이 있나요?",
      "내 공연을 보여 주러 가고 싶은 곳을 써 보세요."] };
ACT["S2756"] = { s: "Elvis is a proud rooster. He struts. He uses rude words. But after a handsome peacock visits his farm, he learns a lesson in manners.",
  q: ["Who visits the farm and teaches Elvis a lesson in manners?",
      "Have you ever learned a lesson about manners from someone?",
      "Write about a polite word you like to use."],
  h: ["농장에 찾아와 엘비스에게 예절을 가르쳐 주는 것은 누구인가요?",
      "누군가에게서 예절에 관한 교훈을 배운 적이 있나요?",
      "내가 자주 쓰는 예의 바른 말을 써 보세요."] };
ACT["S2757"] = { s: "Young Daniel carves a wooden duck and exhibits it at the town fair. He is hurt when people laugh at his wood carving duck.",
  q: ["What does Daniel carve and show at the fair?",
      "Have you ever felt hurt when someone laughed at something you made?",
      "Write about how you would comfort Daniel after people laughed at his duck."],
  h: ["다니엘은 무엇을 조각해서 장터에 전시하나요?",
      "내가 만든 것을 누군가 비웃어서 속상했던 적이 있나요?",
      "사람들이 오리를 비웃은 뒤 다니엘을 어떻게 위로해 줄지 써 보세요."] };
ACT["S2758"] = { s: "Abigail and Tom travel to school every day aboard their father's freight boat named the 'Neptune.' One day, an accident pushes Abigail to take its wheel and, steer the ship up the Hudson River from New Jersey to New York City.",
  q: ["What is the name of the family's freight boat?",
      "Have you ever had to do something difficult because of a sudden accident?",
      "Write about how you think Abigail felt while steering the boat."],
  h: ["가족의 화물선 이름은 무엇인가요?",
      "갑작스러운 사고 때문에 어려운 일을 해야 했던 적이 있나요?",
      "배를 조종하는 동안 애비게일의 기분이 어땠을지 써 보세요."] };
ACT["S2759"] = { s: "It is quiet in Cactus Junction. When Sarah is practicing her lasso, she hears a shout that the bank has been robbed! Then she sees two strange women with big muscles and hairy arms.",
  q: ["What is Sarah practicing when she hears the shout?",
      "Have you ever been surprised by strange news while doing something normal?",
      "Write about what you think Sarah does next."],
  h: ["사라는 소리를 들을 때 무엇을 연습하고 있나요?",
      "평범한 일을 하다가 이상한 소식에 놀란 적이 있나요?",
      "사라가 다음에 무엇을 할지 내 생각을 써 보세요."] };
ACT["S2760"] = { s: "Mike, Jeffrey, Beaner, and Raymond are all members of the Animal Rescue Club. They spring into action whenever wild animals are in trouble. They save them, nurse them, and return them to the wild.",
  q: ["What do the members of the Animal Rescue Club do for wild animals in trouble?",
      "Have you ever helped take care of an animal?",
      "Write about what animal you would like to help rescue."],
  h: ["동물 구조 클럽 회원들은 위험에 처한 야생 동물을 위해 무엇을 하나요?",
      "동물을 돌보는 것을 도와준 적이 있나요?",
      "구조해 주고 싶은 동물을 써 보세요."] };
ACT["S2761"] = { s: "A boy called Tom Tate meets the Wright Brothers and witnesses the invention of the airplane in Kitty Hawk.",
  q: ["Who does Tom Tate meet in this book?",
      "Have you ever watched something amazing being invented or built?",
      "Write about how you think Tom Tate felt watching the first flight."],
  h: ["톰 테이트는 이 책에서 누구를 만나나요?",
      "놀라운 것이 발명되거나 만들어지는 것을 본 적이 있나요?",
      "첫 비행을 지켜보는 동안 톰 테이트의 기분이 어땠을지 써 보세요."] };
ACT["S2762"] = { s: "Wendy, a little witch, is afraid of her mean, bossy witch sisters. But she finds a way to out-witch them one special Halloween night.",
  q: ["Who is Wendy afraid of in this story?",
      "Have you ever felt afraid of someone who was mean or bossy?",
      "Write about how you think Wendy out-witches her sisters."],
  h: ["웬디는 이 이야기에서 누구를 무서워하나요?",
      "못되거나 잘난 척하는 사람이 무서웠던 적이 있나요?",
      "웬디가 언니들을 어떻게 이겼을지 상상해서 써 보세요."] };
ACT["S2763"] = { s: "Preston the pig has the strange feeling that he is being followed by someone.",
  q: ["What strange feeling does Preston the pig have?",
      "Have you ever felt like someone was following you?",
      "Write about who or what you think is following Preston."],
  h: ["프레스턴 돼지는 어떤 이상한 느낌을 받나요?",
      "누군가 나를 따라오는 것 같다고 느낀 적이 있나요?",
      "프레스턴을 따라오는 것이 누구, 혹은 무엇일지 써 보세요."] };
ACT["S2764"] = { s: "This book introduces an old lady who swallows a series of strange items, such as some books. Find out a big surprise she encounters at last.",
  q: ["What strange item does the old lady swallow?",
      "Have you ever been surprised by the ending of a story?",
      "Write about what big surprise you think the old lady finds at the end."],
  h: ["할머니가 삼키는 이상한 물건은 무엇인가요?",
      "이야기의 결말에 놀라 본 적이 있나요?",
      "할머니가 마지막에 만나는 큰 놀라움이 무엇일지 써 보세요."] };
ACT["S2765"] = { s: "When Dad calls Jack to come and have his bath, he runs off the garden to hide.",
  q: ["Where does Jack run to hide?",
      "Have you ever run off or hidden from bath time?",
      "Write about where you would hide if you didn't want to take a bath."],
  h: ["잭은 숨으러 어디로 도망가나요?",
      "목욕 시간에 도망치거나 숨어 본 적이 있나요?",
      "목욕하기 싫을 때 나라면 어디에 숨을지 써 보세요."] };
ACT["S2766"] = { s: "Bambi, the little fawn, sets out to explore the forest with Thumper and Flower. In a brief moment, Bambi's life changes forever.",
  q: ["Who does Bambi explore the forest with?",
      "Have you ever explored a forest, park, or big outdoor place?",
      "Write about what you think happens to change Bambi's life."],
  h: ["밤비는 누구와 함께 숲을 탐험하나요?",
      "숲이나 공원 같은 넓은 야외 장소를 탐험해 본 적이 있나요?",
      "밤비의 삶을 바꾸는 일이 무엇일지 상상해서 써 보세요."] };
ACT["S2767"] = { s: "This storybook tells how Tinker Bell arrives at Pixie Hollow and discovers her tinkering talent!",
  q: ["What talent does Tinker Bell discover?",
      "Have you ever discovered a talent you didn't know you had?",
      "Write about a talent you would like to discover in yourself."],
  h: ["팅커벨은 어떤 재능을 발견하나요?",
      "내가 몰랐던 재능을 발견한 적이 있나요?",
      "내 안에서 발견하고 싶은 재능을 써 보세요."] };
ACT["S2768"] = { s: "When Andy grows up, Woody and his gang find a new home in a daycare center. But life there is no fun at all. Will the toys find a decent home in the end?",
  q: ["Where do the toys find a new home when Andy grows up?",
      "Have you ever had to leave a place you were attached to?",
      "Write about what home you would wish for the toys in the end."],
  h: ["앤디가 자란 뒤 장난감들은 어디에서 새 보금자리를 찾나요?",
      "애착이 있던 곳을 떠나야 했던 적이 있나요?",
      "장난감들이 결국 어떤 집을 찾으면 좋겠는지 써 보세요."] };
ACT["S2769"] = { s: "To look for her dad, Belle sets off to a castle that is under a terrible curse. Can she break the spell and save everyone?",
  q: ["Why does Belle set off to the castle?",
      "Have you ever gone somewhere scary to help someone you love?",
      "Write about how you think Belle breaks the spell."],
  h: ["벨은 왜 성으로 떠나나요?",
      "사랑하는 사람을 돕기 위해 무서운 곳에 가 본 적이 있나요?",
      "벨이 저주를 어떻게 풀었을지 상상해서 써 보세요."] };
ACT["S2770"] = { s: "Mickey Mouse decorates his house for a Halloween party. But when his friends show up, they can't find Mickey. Instead, they only see one scary thing after the next.",
  q: ["What does Mickey decorate his house for?",
      "Have you ever decorated for a holiday or party?",
      "Write about a scary thing you think Mickey's friends see."],
  h: ["미키는 무엇을 위해 집을 꾸미나요?",
      "명절이나 파티를 위해 무언가를 꾸며 본 적이 있나요?",
      "미키의 친구들이 보았을 무서운 것을 상상해서 써 보세요."] };
ACT["S2771"] = { s: "Tiana, whose dream is opening the finest restaurant in New Orleans, meets a frog prince. The prince needs a kiss from a princess to turn human again.",
  q: ["What is Tiana's dream?",
      "Have you ever had a big dream you worked hard toward?",
      "Write about what you think happens after Tiana meets the frog prince."],
  h: ["티아나의 꿈은 무엇인가요?",
      "열심히 노력하는 큰 꿈이 있었던 적이 있나요?",
      "티아나가 개구리 왕자를 만난 뒤 무슨 일이 일어날지 써 보세요."] };
ACT["S2772"] = { s: "Flint Lockwood loves inventing but now his old invention the Food Machine is working again and making dangerous Food Animals.",
  q: ["What does Flint Lockwood's Food Machine make in this book?",
      "Have you ever built or invented something that didn't work as planned?",
      "Write about what kind of Food Animal you would want to see."],
  h: ["플린트 록우드의 음식 기계는 이 책에서 무엇을 만들어 내나요?",
      "계획대로 되지 않은 무언가를 만들거나 발명해 본 적이 있나요?",
      "어떤 음식 동물을 보고 싶은지 써 보세요."] };
ACT["S2773"] = { s: "What is Snoopy thinking? Charlie Brown and his friends never know. What happens when he finds a new school for Peppermint Patty?",
  q: ["What does Snoopy find for Peppermint Patty?",
      "Have you ever wondered what your pet was thinking?",
      "Write about what you think Snoopy is thinking."],
  h: ["스누피는 페퍼민트 패티를 위해 무엇을 찾아 주나요?",
      "내 반려동물이 무슨 생각을 하는지 궁금했던 적이 있나요?",
      "스누피가 무슨 생각을 하고 있을지 상상해서 써 보세요."] };
ACT["S2774"] = { s: "A friend of Puss in Boots, Humpty Dumpty, wants to be rich. What is Humpty Dumpty's plan to be rich?",
  q: ["What does Humpty Dumpty want to become?",
      "Have you ever made a plan to get something you really wanted?",
      "Write about what you think Humpty Dumpty's plan is."],
  h: ["험프티 덤프티는 무엇이 되고 싶어 하나요?",
      "정말 원하는 것을 얻기 위해 계획을 세워 본 적이 있나요?",
      "험프티 덤프티의 계획이 무엇일지 내 생각을 써 보세요."] };
ACT["S2775"] = { s: "The people of the desert town of Dirt don’t have any water. Why doesn't the Mayor help his people?",
  q: ["What do the people of Dirt not have?",
      "Have you ever wondered why a leader didn't help the people who needed it?",
      "Write about what you think the Mayor's reason is."],
  h: ["더트 마을 사람들에게 없는 것은 무엇인가요?",
      "지도자가 도움이 필요한 사람들을 왜 돕지 않는지 궁금했던 적이 있나요?",
      "시장의 이유가 무엇일지 내 생각을 써 보세요."] };
ACT["S2776"] = { s: "Blu is a beautiful blue Spix's Macaw. But there's one big problem. Blu can't fly.",
  q: ["What is Blu's big problem?",
      "Have you ever struggled to learn something that seemed easy for others?",
      "Write about how you think Blu learns to fly."],
  h: ["블루의 큰 문제는 무엇인가요?",
      "다른 사람에게는 쉬워 보이는 것을 배우느라 힘들었던 적이 있나요?",
      "블루가 나는 법을 어떻게 배울지 상상해서 써 보세요."] };
ACT["S2777"] = { s: "Gargamel is in Paris and he wants Smurfette. When he takes her from Smurf Village, the Smurfs are not happy! Can the Smurfs save Smurfette?",
  q: ["Who does Gargamel take from Smurf Village?",
      "Have you ever helped rescue a friend from trouble?",
      "Write about how you think the Smurfs save Smurfette."],
  h: ["가가멜은 스머프 마을에서 누구를 데려가나요?",
      "곤경에 처한 친구를 구하는 것을 도와준 적이 있나요?",
      "스머프들이 스머페트를 어떻게 구했을지 상상해서 써 보세요."] };
ACT["S2778"] = { s: "SpongeBob and Patrick are taking care of Wormy, Sandy's pet caterpillar. One morning, Wormy disappears and they get panicked.",
  q: ["What kind of pet is Wormy?",
      "Have you ever panicked when you couldn't find something you were taking care of?",
      "Write about where you think Wormy went."],
  h: ["워미는 어떤 종류의 반려동물인가요?",
      "돌보던 것을 찾지 못해서 당황했던 적이 있나요?",
      "워미가 어디로 갔을지 내 생각을 써 보세요."] };
ACT["S2779"] = { s: "The Kraang has April and her dad in their lair, but Leo has a plan! Who is Snake and are the Turtles ready to attack?",
  q: ["Who does the Kraang have in their lair?",
      "Have you ever made a plan to help rescue someone?",
      "Write about what plan you think Leo has."],
  h: ["크랭은 소굴에 누구를 붙잡고 있나요?",
      "누군가를 구하기 위해 계획을 세워 본 적이 있나요?",
      "리오의 계획이 무엇일지 내 생각을 써 보세요."] };
ACT["S2780"] = { s: "Tintin, Snowy and Captain Haddock are looking for treasure! But the treasure is far away and they are in a very small boat.",
  q: ["What are Tintin and his friends looking for?",
      "Have you ever gone looking for something exciting, even if it was hard to find?",
      "Write about what you think happens to them on their small boat."],
  h: ["틴틴과 친구들은 무엇을 찾고 있나요?",
      "찾기 어려워도 신나는 것을 찾아 나선 적이 있나요?",
      "작은 배를 탄 그들에게 무슨 일이 일어날지 써 보세요."] };
ACT["S2781"] = { s: "Alex, Melman, Gloria and Marty are in Africa and they want to go back to New York Zoo. In Europe, they meet the animals on the circus train.",
  q: ["Where do the four friends want to go back to?",
      "Have you ever really missed home while traveling?",
      "Write about what you think happens when they meet the circus train animals."],
  h: ["네 친구는 어디로 돌아가고 싶어 하나요?",
      "여행 중에 집이 정말 그리웠던 적이 있나요?",
      "서커스 기차 동물들을 만났을 때 무슨 일이 일어날지 써 보세요."] };
ACT["S2782"] = { s: "Peppermint Patty is going to an ice-skating competition and Snoopy is giving her lessons.",
  q: ["Who is giving Peppermint Patty ice-skating lessons?",
      "Have you ever practiced hard for a competition?",
      "Write about how you think the competition goes for Peppermint Patty."],
  h: ["페퍼민트 패티에게 스케이트를 가르쳐 주는 것은 누구인가요?",
      "대회를 위해 열심히 연습해 본 적이 있나요?",
      "페퍼민트 패티의 대회가 어떻게 될지 내 생각을 써 보세요."] };
ACT["S2783"] = { s: "Many years ago, Humpty Dumpty stole gold from the bank and he went to prison. When he meets his old friend Puss in Boots again, Puss is very angry.",
  q: ["Why does Puss get angry when he meets Humpty Dumpty again?",
      "Have you ever been angry at an old friend for something they did?",
      "Write about what you think Puss says to Humpty Dumpty."],
  h: ["퍼스는 험프티 덤프티를 다시 만났을 때 왜 화가 나나요?",
      "오랜 친구가 한 일 때문에 화가 났던 적이 있나요?",
      "퍼스가 험프티 덤프티에게 무슨 말을 했을지 써 보세요."] };
ACT["S2784"] = { s: "Linda and her Spix's Macaw Blu are best friends. They go to Rio in Brazil to meet the beautiful jewel. It's Carnival time but there are some bad people around.",
  q: ["Where do Linda and Blu travel to?",
      "Have you ever traveled somewhere exciting with a friend?",
      "Write about how Linda and Blu might stay safe from the bad people."],
  h: ["린다와 블루는 어디로 여행을 떠나나요?",
      "친구와 함께 신나는 곳으로 여행 가 본 적이 있나요?",
      "린다와 블루가 나쁜 사람들로부터 어떻게 안전하게 지낼지 써 보세요."] };
ACT["S2785"] = { s: "SpongeBob finds a magic pencil and draws DoodleBob with it. What happens in Bikini Bottom?",
  q: ["What does SpongeBob draw with the magic pencil?",
      "Have you ever wished a drawing of yours could come to life?",
      "Write about what you would draw with a magic pencil."],
  h: ["스폰지밥은 마법 연필로 무엇을 그리나요?",
      "내가 그린 그림이 살아나면 좋겠다고 생각해 본 적이 있나요?",
      "마법 연필로 무엇을 그리고 싶은지 써 보세요."] };
ACT["S2786"] = { s: "Donnie doesn't like fighting with his bo staff so he makes a robot.",
  q: ["What does Donnie make instead of fighting with his bo staff?",
      "Have you ever built something to help you do a hard task?",
      "Write about what kind of robot you would like to build."],
  h: ["도니는 봉으로 싸우는 대신 무엇을 만드나요?",
      "어려운 일을 도와줄 무언가를 만들어 본 적이 있나요?",
      "만들어 보고 싶은 로봇을 써 보세요."] };
ACT["S2787"] = { s: "When Tintin finds a scroll inside his model ship, he starts looking for more clues. Who is Sir Francis Haddock and where is the lost treasure?",
  q: ["What does Tintin find inside his model ship?",
      "Have you ever found a clue that led you to search for something?",
      "Write about where you think the lost treasure is."],
  h: ["틴틴은 모형 배 안에서 무엇을 발견하나요?",
      "무언가를 찾아 나서게 만든 단서를 발견한 적이 있나요?",
      "잃어버린 보물이 어디에 있을지 내 생각을 써 보세요."] };
ACT["S2788"] = { s: "This story is about two monkeys who are as different as night and day but learn to be friends.",
  q: ["How are the two monkeys different from each other?",
      "Have you ever become friends with someone who was very different from you?",
      "Write about a friend of yours who is different from you."],
  h: ["두 원숭이는 서로 어떻게 다른가요?",
      "나와 아주 다른 사람과 친구가 된 적이 있나요?",
      "나와 다른 나의 친구에 대해 써 보세요."] };
ACT["S2789"] = { s: "This book contains bright ideas for young children to help save the environment.",
  q: ["Who are the ideas in this book for?",
      "Have you ever done something to help the environment?",
      "Write about one thing you can do to help your world."],
  h: ["이 책의 아이디어들은 누구를 위한 것인가요?",
      "환경을 돕기 위해 무언가를 해 본 적이 있나요?",
      "세상을 돕기 위해 내가 할 수 있는 한 가지를 써 보세요."] };
ACT["S2790"] = { s: "Raccoon is nervous that unexpected events might spoil a picnic. But Duck convinces Raccoon that surprises can be fun.",
  q: ["What is Raccoon nervous about?",
      "Have you ever been nervous that something unexpected would ruin your plans?",
      "Write about a surprise that turned out to be fun for you."],
  h: ["라쿤은 무엇을 걱정하나요?",
      "예상치 못한 일이 계획을 망칠까 봐 걱정한 적이 있나요?",
      "나에게 재미있었던 뜻밖의 놀라움을 써 보세요."] };
ACT["S2791"] = { s: "To help with his anxiety, his grandmother recommends Billy use the worry dolls. Will they solve his problem?",
  q: ["What does Billy's grandmother recommend he use?",
      "Have you ever felt worried about something?",
      "Write about something you do to feel less worried."],
  h: ["빌리의 할머니는 무엇을 사용하라고 추천하나요?",
      "무언가가 걱정되었던 적이 있나요?",
      "걱정을 덜기 위해 내가 하는 것을 써 보세요."] };
ACT["S2792"] = { s: "This book shows how Mommies and Daddies participate in everyday activities and show their love for their children.",
  q: ["What does this book show about Mommies and Daddies?",
      "How does your family show love for each other?",
      "Write about something your mom or dad does best."],
  h: ["이 책은 엄마와 아빠에 대해 무엇을 보여 주나요?",
      "우리 가족은 서로에게 사랑을 어떻게 표현하나요?",
      "엄마나 아빠가 가장 잘하는 것을 써 보세요."] };
ACT["S2793"] = { s: "A lonely young girl receives a toy gorilla for her birthday from her neglectful busy father. The gorilla comforts her by taking the girl on a miraculous trip to the zoo.",
  q: ["What gift does the girl receive for her birthday?",
      "Have you ever felt lonely and wished someone would spend time with you?",
      "Write about where you would want a magical trip to take you."],
  h: ["소녀는 생일에 어떤 선물을 받나요?",
      "외로워서 누군가 함께 시간을 보내 주기를 바란 적이 있나요?",
      "마법 같은 여행이 나를 어디로 데려가면 좋을지 써 보세요."] };
ACT["S2794"] = { s: "Peter takes Wendy to Never Land where she will never grow up.",
  q: ["Where does Peter take Wendy?",
      "Have you ever imagined a place where you would never grow up?",
      "Write about what you would want to do in Never Land."],
  h: ["피터는 웬디를 어디로 데려가나요?",
      "절대 자라지 않는 곳을 상상해 본 적이 있나요?",
      "네버랜드에서 하고 싶은 일을 써 보세요."] };
ACT["S2795"] = { s: "Snow White gets kicked out of the castle as the Queen gets jealous of her beauty. She meets dwarves in the forest and stays in their cottage.",
  q: ["Who does Snow White meet in the forest?",
      "Have you ever made new friends in an unexpected place?",
      "Write about how you think Snow White feels living with the dwarves."],
  h: ["백설공주는 숲에서 누구를 만나나요?",
      "예상치 못한 곳에서 새로운 친구를 사귄 적이 있나요?",
      "난쟁이들과 함께 사는 백설공주의 기분이 어떨지 써 보세요."] };
ACT["S2796"] = { s: "Cinderella wants to go to the royal ball, but she is too busy helping her stepmother and stepsisters get ready.",
  q: ["신데렐라는 무도회에 가고 싶어 하지만 무엇을 하느라 바쁜가요?",
      "나는 누군가를 도와주느라 내가 하고 싶은 일을 못한 적이 있나요?",
      "내가 신데렐라라면 무도회에 가기 위해 어떻게 할지 써 보세요."],
  h: ["", "", ""] };
ACT["S2797"] = { s: "This book presents the tale of Princess Aurora, who pricks her finger on a spindle and falls into an enchanted sleep.",
  q: ["What does Princess Aurora prick her finger on?",
      "Have you ever gotten a small cut or prick that hurt more than you expected?",
      "Write about what you think wakes Princess Aurora up."],
  h: ["오로라 공주는 손가락을 무엇에 찔리나요?",
      "생각보다 아팠던 작은 상처를 입어 본 적이 있나요?",
      "오로라 공주를 무엇이 깨울지 내 생각을 써 보세요."] };
ACT["S2798"] = { s: "Ariel, the little mermaid, wishes to be part of the human world. When she goes to the surface one day, she happens to save a prince and falls in love with him.",
  q: ["Who does Ariel save when she goes to the surface?",
      "Have you ever wished to be part of a world very different from your own?",
      "Write about what part of the human world you think Ariel likes most."],
  h: ["아리엘은 수면으로 올라갔을 때 누구를 구해 주나요?",
      "나와 아주 다른 세상의 일부가 되고 싶었던 적이 있나요?",
      "아리엘이 인간 세상에서 가장 좋아할 것 같은 부분을 써 보세요."] };
ACT["S2799"] = { s: "This book describes how Belle meets the Beast and makes friends with the enchanted objects.",
  q: ["Who does Belle make friends with besides the Beast?",
      "Have you ever made friends with someone unexpected?",
      "Write about which enchanted object you would want to meet."],
  h: ["벨은 야수 말고 또 누구와 친구가 되나요?",
      "예상치 못한 존재와 친구가 되어 본 적이 있나요?",
      "만나고 싶은 마법에 걸린 물건을 써 보세요."] };
