// 간이 학습 질문 — Book No. S28 묶음. 사람이 아니라 AI 가 한 번 쓰고 굳힌 파일이다.
window.ACT = window.ACT || {};
var ACT = window.ACT;
ACT["S2800"] = { s: "After Rapunzel escapes the tower, she experiences a whole different world outside.",
  q: ["What is one new thing Rapunzel sees in the world outside the tower?",
      "Have you ever gone somewhere completely new to you?",
      "If you left a place you knew well, what would you want to see first?"],
  h: ["라푼젤이 탑 밖 세상에서 본 새로운 것 한 가지는 무엇인가요?",
      "너는 완전히 새로운 곳에 가 본 적이 있나요?",
      "네가 잘 알던 곳을 떠난다면, 가장 먼저 무엇을 보고 싶나요?"] };
ACT["S2801"] = { s: "Elsa's icy powers trap the kingdom of Arendelle in eternal winter. Anna teams up with a mountain man Kristoff and sets off to find her sister and save the kingdom.",
  q: ["Who does Anna team up with to find her sister?",
      "Have you ever teamed up with someone to solve a problem?",
      "What would you do first if your kingdom was trapped in winter?"],
  h: ["안나는 언니를 찾기 위해 누구와 함께 떠나나요?",
      "너는 문제를 해결하려고 누군가와 힘을 합쳐 본 적이 있나요?",
      "네 왕국이 겨울에 갇힌다면 너는 가장 먼저 무엇을 하겠니?"] };
ACT["S2802"] = { s: "Carl sets off to Paradise Falls in his old house. He makes the house float by tying hundreds of balloons to it.",
  q: ["How does Carl make his house float?",
      "Have you ever played with balloons?",
      "Where would you want to fly your house to?"],
  h: ["칼은 어떻게 집을 하늘에 띄우나요?",
      "너는 풍선을 가지고 놀아 본 적이 있나요?",
      "네 집을 날린다면 어디로 가고 싶나요?"] };
ACT["S2803"] = { s: "Moana sets sail in search of a fabled island. During her journey, she teams up with the demi-god Maui and traverses the open ocean.",
  q: ["Who does Moana team up with on her journey?",
      "Have you ever sailed on a boat or been near the ocean?",
      "If you searched for a fabled island, what would you hope to find there?"],
  h: ["모아나는 여행 중에 누구와 함께하나요?",
      "너는 배를 타 보거나 바다 가까이 가 본 적이 있나요?",
      "네가 전설의 섬을 찾는다면 그곳에서 무엇을 발견하고 싶나요?"] };
ACT["S2804"] = { s: "In a city of animals called Zootopia, a fugitive fox and a rookie rabbit cop work together and uncover a conspiracy.",
  q: ["Who works together to uncover the conspiracy in Zootopia?",
      "Have you ever worked with someone very different from you?",
      "What animal would you want to be a police officer in Zootopia?"],
  h: ["주토피아에서 누가 함께 힘을 합쳐 음모를 밝혀내나요?",
      "너와 아주 다른 누군가와 함께 일해 본 적이 있나요?",
      "네가 주토피아의 경찰이라면 어떤 동물이고 싶나요?"] };
ACT["S2805"] = { s: "Eleven-year-old Riley gets to move into a new town, and her world turns upside-down. Can all the Emotions succeed in helping Riley?",
  q: ["Why does Riley's world turn upside-down?",
      "Have you ever moved to a new town or school?",
      "What emotion do you feel most when something changes in your life?"],
  h: ["라일리의 세상은 왜 뒤죽박죽이 되나요?",
      "너는 새로운 동네나 학교로 옮겨 본 적이 있나요?",
      "네 삶에서 무언가 바뀔 때 너는 어떤 감정을 가장 많이 느끼니?"] };
ACT["S2806"] = { s: "Dory, who does not have a good memory, gets lost. Can she find her way back home?",
  q: ["Why does Dory get lost?",
      "Have you ever gotten lost somewhere?",
      "What would you do if you forgot the way home?"],
  h: ["도리는 왜 길을 잃나요?",
      "너는 어딘가에서 길을 잃은 적이 있나요?",
      "집으로 가는 길을 잊어버린다면 너는 어떻게 하겠니?"] };
ACT["S2807"] = { s: "Kipper goes to the village where the tiny humans live. He becomes a giant in the village.",
  q: ["What does Kipper become in the village?",
      "Have you ever felt very big or very small compared to others?",
      "If you were a giant for a day, what would you do?"],
  h: ["키퍼는 마을에서 무엇이 되나요?",
      "너는 다른 사람들에 비해 아주 크거나 작다고 느낀 적이 있나요?",
      "네가 하루 동안 거인이 된다면 무엇을 하고 싶니?"] };
ACT["S2808"] = { s: "The school trip is nearly spoiled by the rain, but Nadim has an idea.",
  q: ["What nearly spoils the school trip?",
      "Have you ever had an outdoor plan spoiled by rain?",
      "What idea would you give if rain spoiled your trip?"],
  h: ["학교 소풍을 망칠 뻔한 것은 무엇인가요?",
      "너는 비 때문에 바깥 계획이 망가진 적이 있나요?",
      "비가 네 소풍을 망친다면 너는 어떤 아이디어를 내겠니?"] };
ACT["S2809"] = { s: "The children go on an underwater adventure.",
  q: ["Where do the children go on their adventure?",
      "Have you ever gone under water, like in a pool or the sea?",
      "What would you like to find on an underwater adventure?"],
  h: ["아이들은 어디로 모험을 떠나나요?",
      "너는 수영장이나 바다에서 물속에 들어가 본 적이 있나요?",
      "물속 모험에서 너는 무엇을 찾고 싶니?"] };
ACT["S2810"] = { s: "A visit to the pantomime leads to an adventure with Robin Hood.",
  q: ["What leads to the adventure with Robin Hood?",
      "Have you ever watched a play or a pantomime?",
      "What would you want to do on an adventure with Robin Hood?"],
  h: ["로빈 후드와의 모험은 무엇으로 시작되나요?",
      "너는 연극이나 팬터마임을 본 적이 있나요?",
      "로빈 후드와 모험을 한다면 너는 무엇을 하고 싶니?"] };
ACT["S2811"] = { s: "The magic takes the children to dinosaurs.",
  q: ["What takes the children to the dinosaurs?",
      "Have you ever seen a dinosaur, in a museum or a picture?",
      "Which dinosaur would you like to meet the most?"],
  h: ["무엇이 아이들을 공룡에게 데려가나요?",
      "너는 박물관이나 그림에서 공룡을 본 적이 있나요?",
      "너는 어떤 공룡을 가장 만나 보고 싶니?"] };
ACT["S2812"] = { s: "There is a princess who can't laugh. Who can make the princess laugh?",
  q: ["What can't the princess do?",
      "What makes you laugh the most?",
      "What would you do to make the princess laugh?"],
  h: ["공주는 무엇을 할 수 없나요?",
      "너를 가장 많이 웃게 만드는 것은 무엇이니?",
      "공주를 웃게 하려면 너는 무엇을 하겠니?"] };
ACT["S2813"] = { s: "The children get the blame when some jewellery is stolen.",
  q: ["What happens to the children when the jewellery is stolen?",
      "Have you ever been blamed for something you didn't do?",
      "What would you do if people blamed you by mistake?"],
  h: ["보석을 도둑맞았을 때 아이들에게 무슨 일이 생기나요?",
      "너는 하지 않은 일로 오해를 받은 적이 있나요?",
      "사람들이 너를 잘못 오해한다면 어떻게 하겠니?"] };
ACT["S2814"] = { s: "The magic key takes the children to the land of Father Christmas. What is the land for?",
  q: ["Where does the magic key take the children?",
      "What do you like most about Christmas?",
      "What do you think the land of Father Christmas is for?"],
  h: ["마법 열쇠는 아이들을 어디로 데려가나요?",
      "너는 크리스마스에서 무엇이 가장 좋으니?",
      "산타 할아버지의 나라는 무엇을 위한 곳일 것 같니?"] };
ACT["S2815"] = { s: "The children help rescue the crew of a ship in trouble.",
  q: ["Who do the children help rescue?",
      "Have you ever helped someone who was in trouble?",
      "How would you help rescue a ship's crew?"],
  h: ["아이들은 누구를 구하는 것을 돕나요?",
      "너는 어려움에 처한 누군가를 도와준 적이 있나요?",
      "배의 선원들을 구하려면 너는 어떻게 돕겠니?"] };
ACT["S2816"] = { s: "The children go to Paris. But they can't find the Eiffel Tower. Where is it?",
  q: ["What can't the children find in Paris?",
      "Have you ever looked for something and couldn't find it?",
      "Where do you think the Eiffel Tower could be hiding?"],
  h: ["아이들은 파리에서 무엇을 찾지 못하나요?",
      "너는 무언가를 찾다가 찾지 못한 적이 있나요?",
      "에펠탑이 어디에 숨어 있을 것 같니?"] };
ACT["S2817"] = { s: "Biff and Chip get the blame when the prince's crown is stolen.",
  q: ["Who gets the blame when the crown is stolen?",
      "Have you ever lost something important that belonged to someone else?",
      "Who do you think really stole the crown?"],
  h: ["왕관을 도둑맞았을 때 누가 누명을 쓰나요?",
      "너는 다른 사람의 소중한 물건을 잃어버린 적이 있나요?",
      "왕관을 진짜로 훔친 사람은 누구일 것 같니?"] };
ACT["S2818"] = { s: "Can Biff and Chip catch the thieves and get the crown back?",
  q: ["What do Biff and Chip try to get back?",
      "Have you ever tried to get something back that was taken from you?",
      "How do you think they catch the thieves?"],
  h: ["비프와 칩은 무엇을 되찾으려 하나요?",
      "너는 빼앗긴 것을 되찾으려 해 본 적이 있나요?",
      "그들은 도둑을 어떻게 잡을 것 같니?"] };
ACT["S2819"] = { s: "The children do the assignment about nature with Gran.",
  q: ["Who helps the children with their assignment?",
      "Does anyone in your family help you with homework?",
      "What nature topic would you like to do homework about?"],
  h: ["아이들의 숙제를 누가 도와주나요?",
      "너희 가족 중 누군가 숙제를 도와주니?",
      "너는 자연에 대해 어떤 주제로 숙제를 하고 싶니?"] };
ACT["S2820"] = { s: "The magic takes the children to the ancient Greek village and they see the origin of the Olympic games.",
  q: ["Where does the magic take the children?",
      "Have you ever watched or played in the Olympic games?",
      "What Olympic event would you like to try?"],
  h: ["마법은 아이들을 어디로 데려가나요?",
      "너는 올림픽 경기를 보거나 해 본 적이 있나요?",
      "너는 어떤 올림픽 종목을 해 보고 싶니?"] };
ACT["S2821"] = { s: "The magic key takes Chip, Wilf, Nadim and Floppy into the computer game.",
  q: ["Where does the magic key take Chip, Wilf, Nadim and Floppy?",
      "Have you ever wished to go inside a computer game?",
      "If you went into a computer game, what game would you choose?"],
  h: ["마법 열쇠는 칩, 윌프, 나딤, 플로피를 어디로 데려가나요?",
      "너는 컴퓨터 게임 안으로 들어가고 싶었던 적이 있나요?",
      "컴퓨터 게임 속으로 들어간다면 어떤 게임을 고르겠니?"] };
ACT["S2822"] = { s: "The children has lost in the jungle, and fall into danger.",
  q: ["Where do the children get lost?",
      "Have you ever been in a place that felt a little scary?",
      "What would you do if you were lost in a jungle?"],
  h: ["아이들은 어디에서 길을 잃나요?",
      "너는 조금 무섭게 느껴지는 곳에 있어 본 적이 있나요?",
      "정글에서 길을 잃는다면 너는 어떻게 하겠니?"] };
ACT["S2823"] = { s: "The little house gets broken at school. How does it get repaired?",
  q: ["What gets broken at school?",
      "Have you ever fixed something that was broken?",
      "How do you think the little house gets repaired?"],
  h: ["학교에서 무엇이 부서지나요?",
      "너는 부서진 것을 고쳐 본 적이 있나요?",
      "작은 집은 어떻게 고쳐질 것 같니?"] };
ACT["S2824"] = { s: "The magic key has not glowed for a long time. What happens to it?",
  q: ["What has the magic key not done for a long time?",
      "Have you ever had a favorite thing stop working?",
      "What do you think happens to the magic key?"],
  h: ["마법 열쇠는 오랫동안 무엇을 하지 않았나요?",
      "네가 아끼던 것이 작동을 멈춘 적이 있나요?",
      "마법 열쇠에게 무슨 일이 생긴 것 같니?"] };
ACT["S2825"] = { s: "The children go to the land of the willow pattern. They help a couple chased by her father.",
  q: ["Who do the children help?",
      "Have you ever helped two people who needed each other's help?",
      "How would you help a couple being chased?"],
  h: ["아이들은 누구를 돕나요?",
      "너는 서로 도움이 필요한 두 사람을 도와준 적이 있나요?",
      "쫓기고 있는 커플을 너는 어떻게 돕겠니?"] };
ACT["S2826"] = { s: "Wilf's birthday present is the beginning of an exciting undersea adventure.",
  q: ["What starts the exciting undersea adventure?",
      "What is the best birthday present you have ever gotten?",
      "What would you want your birthday present to start an adventure to?"],
  h: ["신나는 바닷속 모험은 무엇으로 시작되나요?",
      "네가 받아 본 가장 좋은 생일 선물은 무엇이었니?",
      "네 생일 선물이 모험의 시작이 된다면 어떤 모험이면 좋겠니?"] };
ACT["S2827"] = { s: "A new girl comes to the school. The girl is very nasty and acts like a bully.",
  q: ["How does the new girl act?",
      "Have you ever met someone who was not kind to you?",
      "What would you do if someone acted like a bully to you?"],
  h: ["새로 온 여자아이는 어떻게 행동하나요?",
      "너에게 친절하지 않은 사람을 만난 적이 있나요?",
      "누군가 너에게 못되게 군다면 너는 어떻게 하겠니?"] };
ACT["S2828"] = { s: "Floppy breaks Gran's Chinese vase. Can the magic help to mend it?",
  q: ["What does Floppy break?",
      "Have you ever accidentally broken something?",
      "How do you think the magic mends the vase?"],
  h: ["플로피는 무엇을 깨뜨리나요?",
      "너는 실수로 무언가를 깨뜨린 적이 있나요?",
      "마법은 꽃병을 어떻게 고칠 것 같니?"] };
ACT["S2829"] = { s: "The children go back in time and help look for gold.",
  q: ["What do the children help look for?",
      "Have you ever gone looking for something hidden, like a treasure hunt?",
      "If you traveled back in time, what year would you want to visit?"],
  h: ["아이들은 무엇을 찾는 것을 돕나요?",
      "너는 보물찾기처럼 숨겨진 것을 찾아본 적이 있나요?",
      "시간을 거슬러 간다면 너는 몇 년으로 가고 싶니?"] };
ACT["S2830"] = { s: "The children are sucked into the jigsaw puzzle.",
  q: ["What are the children sucked into?",
      "Have you ever finished a jigsaw puzzle?",
      "What would you see if you were sucked into a puzzle picture?"],
  h: ["아이들은 무엇 속으로 빨려 들어가나요?",
      "너는 직소 퍼즐을 완성해 본 적이 있나요?",
      "네가 퍼즐 그림 속으로 빨려 들어간다면 무엇이 보일 것 같니?"] };
ACT["S2831"] = { s: "Can Gran stop the motorway from being built for the nature?",
  q: ["What does Gran try to stop from being built?",
      "Have you ever tried to protect nature or an animal?",
      "How could Gran stop the motorway from being built?"],
  h: ["할머니는 무엇이 지어지지 못하도록 막으려 하나요?",
      "너는 자연이나 동물을 지키려 해 본 적이 있나요?",
      "할머니는 고속도로 건설을 어떻게 막을 수 있을까?"] };
ACT["S2832"] = { s: "Chip and Biff go to Roman times and they sell pizza in Rome.",
  q: ["What do Chip and Biff sell in Rome?",
      "Have you ever sold or given something you made to other people?",
      "What food would you like to sell in ancient Rome?"],
  h: ["칩과 비프는 로마에서 무엇을 파나요?",
      "너는 네가 만든 것을 다른 사람에게 팔거나 준 적이 있나요?",
      "고대 로마에서 너는 어떤 음식을 팔고 싶니?"] };
ACT["S2833"] = { s: "To enjoy the holiday, Dad takes down fuse box on purpose.",
  q: ["What does Dad do on purpose?",
      "Have you ever spent time without electricity?",
      "What would you do for fun if the power went out?"],
  h: ["아빠는 일부러 무엇을 하나요?",
      "너는 전기 없이 시간을 보내 본 적이 있나요?",
      "전기가 나가면 너는 무엇을 하며 재미있게 놀겠니?"] };
ACT["S2834"] = { s: "Floppy has an adventure that takes him to Australia. Can he help the dingos solve a problem?",
  q: ["Who does Floppy try to help in Australia?",
      "Have you ever helped an animal with a problem?",
      "What problem do you think the dingos have?"],
  h: ["플로피는 호주에서 누구를 도우려 하나요?",
      "너는 어려움에 처한 동물을 도와준 적이 있나요?",
      "딩고들에게 어떤 문제가 있을 것 같니?"] };
ACT["S2835"] = { s: "Getting to Riddle Mountain is hard when the only way is to solve riddles.",
  q: ["What is the only way to get to Riddle Mountain?",
      "Have you ever solved a riddle or a puzzle?",
      "Do you think you could solve riddles to get up a mountain?"],
  h: ["리들 마운틴에 가는 유일한 방법은 무엇인가요?",
      "너는 수수께끼나 퍼즐을 풀어 본 적이 있나요?",
      "너는 수수께끼를 풀어 산을 오를 수 있을 것 같니?"] };
ACT["S2836"] = { s: "Can the children get to Riddle Mountain and solve the hardest riddle of all?",
  q: ["What do the children try to solve?",
      "What is the hardest puzzle or question you have ever solved?",
      "What do you think the hardest riddle could be?"],
  h: ["아이들은 무엇을 풀려고 하나요?",
      "네가 풀어 본 것 중 가장 어려웠던 문제는 무엇이었니?",
      "가장 어려운 수수께끼는 무엇일 것 같니?"] };
ACT["S2837"] = { s: "The children are on the ship by magic. Sooner or later they find out why the magic has taken them on board.",
  q: ["How do the children get on the ship?",
      "Have you ever been somewhere without knowing exactly why?",
      "Why do you think the magic brought them on board?"],
  h: ["아이들은 어떻게 배에 타게 되나요?",
      "너는 이유를 모른 채 어딘가에 있게 된 적이 있나요?",
      "마법은 왜 그들을 배에 태웠을 것 같니?"] };
ACT["S2838"] = { s: "The magic key takes the children back to a time when making breakfast is very different.",
  q: ["What is different about making breakfast in the past?",
      "What do you usually eat for breakfast?",
      "What do you think breakfast was like a long time ago?"],
  h: ["옛날에 아침을 만드는 것은 무엇이 달랐나요?",
      "너는 보통 아침으로 무엇을 먹니?",
      "아주 오래전 아침 식사는 어땠을 것 같니?"] };
ACT["S2839"] = { s: "With the flying carpet, Biff and Chip save the king and capture the bad man.",
  q: ["What do Biff and Chip use to save the king?",
      "If you had a flying carpet, where would you fly?",
      "How do you think they capture the bad man?"],
  h: ["비프와 칩은 왕을 구하기 위해 무엇을 사용하나요?",
      "네게 날아다니는 양탄자가 있다면 어디로 날아가고 싶니?",
      "그들은 나쁜 남자를 어떻게 붙잡을 것 같니?"] };
ACT["S2840"] = { s: "The magic key turns Kipper into a teddy bear. How does Kipper rescue them from kidnappers?",
  q: ["What does the magic key turn Kipper into?",
      "Do you have a favorite stuffed animal, like a teddy bear?",
      "How do you think a teddy bear could rescue someone?"],
  h: ["마법 열쇠는 키퍼를 무엇으로 바꾸나요?",
      "너에게 곰 인형처럼 아끼는 인형이 있니?",
      "곰 인형이 어떻게 누군가를 구할 수 있을 것 같니?"] };
ACT["S2841"] = { s: "When Gran takes the children on a visit to London, things don't go quite as Gran planned!",
  q: ["Who takes the children to London?",
      "Has a trip you planned ever gone differently than you expected?",
      "What do you think goes wrong in London?"],
  h: ["누가 아이들을 런던에 데려가나요?",
      "네가 계획한 여행이 생각과 다르게 흘러간 적이 있니?",
      "런던에서 무엇이 계획대로 안 되었을 것 같니?"] };
ACT["S2842"] = { s: "The children find a machine that makes the rainbow. But things go badly wrong when Nadim tries to make it work.",
  q: ["What does the machine the children find make?",
      "Have you ever tried to use a machine and had trouble?",
      "What do you think goes wrong when Nadim uses the machine?"],
  h: ["아이들이 발견한 기계는 무엇을 만드나요?",
      "너는 기계를 쓰다가 어려움을 겪은 적이 있니?",
      "나딤이 기계를 쓸 때 무엇이 잘못되었을 것 같니?"] };
ACT["S2843"] = { s: "The magic key takes the children to London in the past. When they visit Buckingham Palace, they get quite a surprise.",
  q: ["Where do the children visit in the past?",
      "Have you ever visited a famous building or palace?",
      "What surprise do you think they get at the palace?"],
  h: ["아이들은 과거의 어디를 방문하나요?",
      "너는 유명한 건물이나 궁전을 방문해 본 적이 있니?",
      "궁전에서 아이들은 어떤 놀라운 일을 겪었을 것 같니?"] };
ACT["S2844"] = { s: "The children find themselves on a Viking ship. Can they save the Viking village when raiders attack?",
  q: ["What do the children try to save?",
      "Have you ever helped protect something important to your family or friends?",
      "How would you help save the village from the raiders?"],
  h: ["아이들은 무엇을 구하려고 하나요?",
      "너는 가족이나 친구에게 소중한 것을 지키는 것을 도와준 적이 있니?",
      "너는 습격자들로부터 마을을 어떻게 구하겠니?"] };
ACT["S2845"] = { s: "The children have an adventure in Ancient Egypt. Floppy is mistaken for an important dog, and the children have to help make a pyramid.",
  q: ["What is Floppy mistaken for?",
      "Have you ever been mistaken for someone or something else?",
      "How do you think the children help make a pyramid?"],
  h: ["플로피는 무엇으로 오해받나요?",
      "너는 다른 사람이나 다른 것으로 오해받은 적이 있니?",
      "아이들은 피라미드를 만드는 것을 어떻게 도울 것 같니?"] };
ACT["S2846"] = { s: "Floppy is left behind on a magic adventure. Can Biff and Chip save Floppy from the Evil Genie?",
  q: ["Who is left behind on the magic adventure?",
      "Have you ever been left behind or lost from a group?",
      "How would you save Floppy from the Evil Genie?"],
  h: ["마법 모험에서 누가 남겨지나요?",
      "너는 무리에서 남겨지거나 떨어져 본 적이 있니?",
      "너는 사악한 지니로부터 플로피를 어떻게 구하겠니?"] };
ACT["S2847"] = { s: "Biff, Chip and Kipper should do the job to get their pocket money. Will they get it from Dad?",
  q: ["What should Biff, Chip and Kipper do to get pocket money?",
      "Do you do any jobs at home to earn money or rewards?",
      "What job would you want to do to earn pocket money?"],
  h: ["비프, 칩, 키퍼는 용돈을 받으려면 무엇을 해야 하나요?",
      "너는 용돈이나 보상을 받으려고 집안일을 하니?",
      "너는 용돈을 벌기 위해 어떤 일을 하고 싶니?"] };
ACT["S2848"] = { s: "Biff grows an apple in a bottle. But what is in the bottle she finds on a magic adventure. What happens when she pulls out the cork?",
  q: ["What does Biff grow in a bottle?",
      "Have you ever been curious about what was inside something closed?",
      "What do you think happens when Biff pulls out the cork?"],
  h: ["비프는 병 속에서 무엇을 기르나요?",
      "너는 닫힌 것 안에 무엇이 있는지 궁금했던 적이 있니?",
      "비프가 코르크 마개를 뽑으면 무슨 일이 일어날 것 같니?"] };
ACT["S2849"] = { s: "The children are sent to London in the era of World War II.",
  q: ["When are the children sent to London?",
      "Have you ever learned about a time long before you were born?",
      "What do you think London was like during that time?"],
  h: ["아이들은 언제의 런던으로 보내지나요?",
      "너는 네가 태어나기 훨씬 전의 시대에 대해 배운 적이 있니?",
      "그 시대의 런던은 어땠을 것 같니?"] };
ACT["S2850"] = { s: "A great flood hits the town. What happens to Kipper's family?",
  q: ["What hits the town?",
      "Have you ever experienced strong rain or a storm?",
      "What do you think happens to Kipper's family in the flood?"],
  h: ["마을에 무엇이 닥치나요?",
      "너는 강한 비나 폭풍을 겪어 본 적이 있니?",
      "홍수 속에서 키퍼의 가족에게 무슨 일이 일어났을 것 같니?"] };
ACT["S2851"] = { s: "Mrs. May and the children go to the sea to save the otters and the sea life.",
  q: ["What do Mrs. May and the children go to the sea to save?",
      "Have you ever done something to help protect nature?",
      "How would you help save the otters and sea life?"],
  h: ["메이 선생님과 아이들은 무엇을 구하러 바다에 가나요?",
      "너는 자연을 지키기 위해 무언가를 해 본 적이 있니?",
      "너는 수달과 바다 생물을 어떻게 구하겠니?"] };
ACT["S2852"] = { s: "Chip drops litter carelessly. After meeting the Litter Queen, he totally changes.",
  q: ["What does Chip do carelessly at first?",
      "Have you ever picked up litter or kept a place clean?",
      "What do you think the Litter Queen tells Chip?"],
  h: ["칩은 처음에 무엇을 부주의하게 하나요?",
      "너는 쓰레기를 줍거나 장소를 깨끗하게 지켜 본 적이 있니?",
      "쓰레기 여왕은 칩에게 무슨 말을 했을 것 같니?"] };
ACT["S2853"] = { s: "Can Wilma save the land from snow and ice? She has to take the crystal bell frm the evil Grimlock.",
  q: ["What does Wilma have to take from Grimlock?",
      "Have you ever tried to complete a hard task to help others?",
      "How do you think Wilma gets the crystal bell?"],
  h: ["윌마는 그림록에게서 무엇을 가져와야 하나요?",
      "너는 다른 사람을 돕기 위해 어려운 일을 해낸 적이 있니?",
      "윌마는 수정 종을 어떻게 얻을 것 같니?"] };
ACT["S2854"] = { s: "Nadim likes computer games very much. The magic takes the children into a game called Storm Castle.",
  q: ["What is the name of the game the children are taken into?",
      "What is your favorite computer or video game?",
      "If you went inside a game, what would you want it to be like?"],
  h: ["아이들이 들어가게 되는 게임의 이름은 무엇인가요?",
      "네가 가장 좋아하는 컴퓨터 게임이나 비디오 게임은 무엇이니?",
      "게임 속으로 들어간다면 그 게임은 어떤 모습이면 좋겠니?"] };
ACT["S2855"] = { s: "Floppy becomes a big hero in a magic.",
  q: ["What does Floppy become?",
      "If your pet became a hero, what would it do?",
      "What kind of hero would you like to be?"],
  h: ["플로피는 무엇이 되나요?",
      "네 반려동물이 영웅이 된다면 무엇을 할 것 같니?",
      "너는 어떤 영웅이 되고 싶니?"] };
ACT["S2856"] = { s: "Camping in the nature is fun. But can the children survive the dangers of camping in the wild?",
  q: ["What do the children have to survive while camping?",
      "Have you ever been camping in nature?",
      "What danger do you think they face while camping?"],
  h: ["아이들은 캠핑하면서 무엇을 이겨 내야 하나요?",
      "너는 자연에서 캠핑을 해 본 적이 있니?",
      "아이들은 캠핑 중 어떤 위험을 마주했을 것 같니?"] };
ACT["S2857"] = { s: "Princess Aisha needs the Blue Eye to become Queen. How can Biff and Wilf help Princess Aisha?",
  q: ["What does Princess Aisha need to become Queen?",
      "Have you ever helped a friend reach an important goal?",
      "How would you help Princess Aisha find the Blue Eye?"],
  h: ["아이샤 공주는 여왕이 되려면 무엇이 필요하나요?",
      "너는 친구가 중요한 목표를 이루도록 도운 적이 있니?",
      "너는 아이샤 공주가 블루 아이를 찾도록 어떻게 돕겠니?"] };
ACT["S2858"] = { s: "Biff and Wilf meet Princess Aisha again in another adventure. What happens to Princess Aisha?",
  q: ["Who do Biff and Wilf meet again?",
      "Have you ever met a friend again after a long time?",
      "What do you think happens to Princess Aisha this time?"],
  h: ["비프와 윌프는 누구를 다시 만나나요?",
      "너는 오랜만에 친구를 다시 만난 적이 있니?",
      "이번에는 아이샤 공주에게 무슨 일이 일어났을 것 같니?"] };
ACT["S2859"] = { s: "The magic key takes Biff and Chip to the Netherlands. They help stop a dam bursting and catch a thief thanks to some Dutch cheese.",
  q: ["What do Biff and Chip help stop from bursting?",
      "Have you ever used something unusual, like food, to solve a problem?",
      "How do you think the Dutch cheese helps catch the thief?"],
  h: ["비프와 칩은 무엇이 터지는 것을 막는 것을 돕나요?",
      "너는 음식처럼 특이한 것으로 문제를 해결해 본 적이 있니?",
      "네덜란드 치즈는 도둑을 잡는 데 어떻게 도움이 되었을 것 같니?"] };
ACT["S2860"] = { s: "The children are sent to Middle Ages and invited to a feast as entertainers.",
  q: ["What are the children invited to as entertainers?",
      "Have you ever performed for other people, like singing or dancing?",
      "What would you perform if you were invited to a feast?"],
  h: ["아이들은 엔터테이너로서 무엇에 초대받나요?",
      "너는 노래나 춤처럼 다른 사람 앞에서 공연해 본 적이 있니?",
      "잔치에 초대받는다면 너는 무엇을 공연하고 싶니?"] };
ACT["S2861"] = { s: "Nadim and Anneena go back in time and meet two crazy inventors. The two men want to invent the first flying machine. Can you guess who they are?",
  q: ["What do the two inventors want to invent?",
      "Have you ever wanted to invent something?",
      "Who do you guess the two inventors are?"],
  h: ["두 발명가는 무엇을 발명하고 싶어 하나요?",
      "너는 무언가를 발명하고 싶었던 적이 있니?",
      "너는 그 두 발명가가 누구일 것 같니?"] };
ACT["S2862"] = { s: "Kipper has a magic key adventure that he doesn't like, and he learns that it is not a good idea to get angry with it.",
  q: ["What does Kipper learn is not a good idea?",
      "Have you ever felt angry and later realized it wasn't a good idea?",
      "What would you do instead of getting angry?"],
  h: ["키퍼는 무엇이 좋지 않은 생각이라는 것을 배우나요?",
      "너는 화가 났다가 나중에 그게 좋은 생각이 아니었다고 느낀 적이 있니?",
      "화를 내는 대신 너는 무엇을 하겠니?"] };
ACT["S2863"] = { s: "A traditional story about a prince who is turned into a frog.",
  q: ["What is the prince turned into?",
      "Have you ever read or heard another story about a prince or princess?",
      "If you were turned into an animal, which one would you want to be?"],
  h: ["왕자는 무엇으로 변하나요?",
      "너는 왕자나 공주에 관한 다른 이야기를 읽거나 들어 본 적이 있니?",
      "네가 동물로 변한다면 어떤 동물이 되고 싶니?"] };
ACT["S2864"] = { s: "In this traditional South American tale, clever monkey tricks the monster into releasing her friends, and he goes back to his cave empty-handed.",
  q: ["What does the clever monkey trick the monster into doing?",
      "Have you ever used a clever idea to solve a problem?",
      "How do you think the monkey tricks the monster?"],
  h: ["영리한 원숭이는 괴물을 속여 무엇을 하게 하나요?",
      "너는 영리한 생각으로 문제를 해결해 본 적이 있니?",
      "원숭이는 괴물을 어떻게 속였을 것 같니?"] };
ACT["S2865"] = { s: "Based on a Native American folk legend, this book tells the story of how Bear lost his tail.",
  q: ["What does this book explain about Bear?",
      "Do you know why any animal looks the way it does, from a story or a fact?",
      "How do you think Bear lost his tail?"],
  h: ["이 책은 곰에 대해 무엇을 설명해 주나요?",
      "너는 어떤 동물이 왜 그런 모습인지 이야기나 사실로 알고 있는 것이 있니?",
      "곰은 꼬리를 어떻게 잃어버렸을 것 같니?"] };
ACT["S2866"] = { s: "A traditional Japanese tale about a stonecutter who wishes for more in life.",
  q: ["What does the stonecutter wish for?",
      "Have you ever wished you had more of something?",
      "What do you think Yoshi wishes for first?"],
  h: ["돌 깎는 사람은 무엇을 바라나요?",
      "너는 무언가를 더 많이 갖고 싶었던 적이 있니?",
      "요시가 가장 먼저 바라는 것은 무엇일 것 같니?"] };
ACT["S2867"] = { s: "Rumpelstiltskin is based on the traditional tale from German folklore about a goblin who helps a miller's daughter spin straw into gold.",
  q: ["What does the goblin help the miller's daughter do?",
      "Have you ever gotten help from someone to finish a hard task?",
      "If you could spin straw into gold, what would you make?"],
  h: ["고블린은 방앗간 집 딸이 무엇을 하도록 돕나요?",
      "너는 어려운 일을 끝내려고 누군가에게 도움을 받은 적이 있니?",
      "짚을 금으로 만들 수 있다면 너는 무엇을 만들고 싶니?"] };
ACT["S2868"] = { s: "Baba Yaga is a witch who appears in many Russia and Middle Eastern folk tales. Can the brave girl Natasha escape the clutches of the wicked witch?",
  q: ["Who tries to escape the wicked witch?",
      "Have you ever needed to be brave to get out of a tricky situation?",
      "How do you think Natasha escapes Baba Yaga?"],
  h: ["누가 사악한 마녀에게서 도망치려 하나요?",
      "너는 어려운 상황에서 벗어나려고 용기를 낸 적이 있니?",
      "나타샤는 바바야가에게서 어떻게 도망칠 것 같니?"] };
ACT["S2869"] = { s: "It is one of the oldest and most well known of fairy tales, with versions told across the world. Cinderella’s goodness overcomes the greed of her stepfamily.",
  q: ["What overcomes the greed of Cinderella's stepfamily?",
      "Have you ever heard another version of the Cinderella story?",
      "What kind of goodness do you have that helps you?"],
  h: ["신데렐라의 계모 가족의 욕심을 이기는 것은 무엇인가요?",
      "너는 신데렐라 이야기의 다른 버전을 들어 본 적이 있니?",
      "너에게 도움이 되는 어떤 착한 마음이 있니?"] };
ACT["S2870"] = { s: "Aladdin is based on the traditional tale from the Middle East of a boy who finds a magic lamp containing a genie who grants him three wishes.",
  q: ["How many wishes does the genie grant?",
      "If you had three wishes, what would you wish for?",
      "What do you think Aladdin's first wish is?"],
  h: ["지니는 소원을 몇 개 들어주나요?",
      "너에게 소원 세 가지가 있다면 무엇을 빌고 싶니?",
      "알라딘의 첫 번째 소원은 무엇일 것 같니?"] };
ACT["S2871"] = { s: "This story is a German rags-to-riches folk tale. There is something strange happening at the palace, where the King's twelve daughters are wearing through their slippers every night.",
  q: ["What strange thing happens to the King's twelve daughters every night?",
      "Have you ever worn out your shoes from doing something a lot?",
      "Why do you think their slippers wear out every night?"],
  h: ["왕의 열두 딸들에게 매일 밤 어떤 이상한 일이 일어나나요?",
      "너는 무언가를 많이 해서 신발이 닳아 본 적이 있니?",
      "슬리퍼가 매일 밤 닳는 이유는 무엇일 것 같니?"] };
ACT["S2872"] = { s: "Anansi the trickster wants everyone to listen to his stories, but he will have to complete three challenges before he is proved worthy of the title King of stories.",
  q: ["How many challenges does Anansi have to complete?",
      "Do you like telling stories to other people?",
      "What challenge do you think would be hardest for Anansi?"],
  h: ["아난시는 도전 과제를 몇 개 완수해야 하나요?",
      "너는 다른 사람들에게 이야기하는 것을 좋아하니?",
      "아난시에게 가장 어려운 도전은 무엇일 것 같니?"] };
ACT["S2873"] = { s: "This story is a European fairy tale about a young girl and a big bad wolf.",
  q: ["Who are the two main characters in this story?",
      "Have you heard this story told a different way before?",
      "What would you warn Little Red Riding Hood about?"],
  h: ["이 이야기의 주요 등장인물 둘은 누구인가요?",
      "너는 이 이야기를 다른 방식으로 들어 본 적이 있니?",
      "너라면 빨간 모자에게 무엇을 조심하라고 하겠니?"] };
ACT["S2874"] = { s: "This story is based on one of the Irish legends of Fionn mac Cumhail. He was said to have been a great Irish warrior who had many adventures.",
  q: ["What was Fionn mac Cumhail said to be?",
      "Do you know a legend or story about a great warrior?",
      "What adventure would you like a great warrior to have?"],
  h: ["피온 막 쿠얼은 어떤 사람이었다고 전해지나요?",
      "너는 위대한 전사에 관한 전설이나 이야기를 알고 있니?",
      "위대한 전사가 어떤 모험을 하면 좋겠니?"] };
ACT["S2875"] = { s: "This book is the story of Bella, who is unwittingly promised to a beast by her father. She has to live with him in his palace, and overcome her fear of his appearance to break the magic spell that binds him.",
  q: ["What does Bella have to overcome to break the magic spell?",
      "Have you ever been scared of how something looked at first?",
      "How do you think Bella breaks the spell?"],
  h: ["벨라는 마법을 풀기 위해 무엇을 이겨 내야 하나요?",
      "너는 처음 보았을 때 겉모습 때문에 무서웠던 적이 있니?",
      "벨라는 마법을 어떻게 풀 것 같니?"] };
ACT["S2876"] = { s: "This book is an Irish legend of a wicked queen who wants the King to love her more than his four children.",
  q: ["What does the wicked queen want?",
      "Have you ever felt jealous of the attention someone else got?",
      "What do you think the wicked queen does to the four children?"],
  h: ["사악한 왕비는 무엇을 원하나요?",
      "너는 다른 사람이 받는 관심이 부러웠던 적이 있니?",
      "사악한 왕비는 네 아이에게 무슨 짓을 했을 것 같니?"] };
ACT["S2877"] = { s: "Mulan is a brave girl who decides to protect her family and country. To become a soldier, she must pretend to be a boy and learn to fight and outsmart her enemies.",
  q: ["What must Mulan pretend to be to become a soldier?",
      "Have you ever done something brave to protect your family?",
      "How do you think Mulan learns to outsmart her enemies?"],
  h: ["뮬란은 군인이 되려면 무엇인 척해야 하나요?",
      "너는 가족을 지키기 위해 용감한 일을 해 본 적이 있니?",
      "뮬란은 적을 이기는 방법을 어떻게 배웠을 것 같니?"] };
ACT["S2878"] = { s: "Astrid has to rescue her prince from the clutches of the troll Long Nose. Her intelligence outwits the troll and save the prince from the enchanted castle.",
  q: ["What does Astrid use to outwit the troll?",
      "Have you ever used a clever idea instead of strength to solve a problem?",
      "How do you think Astrid saves the prince?"],
  h: ["아스트리드는 트롤을 이기기 위해 무엇을 사용하나요?",
      "너는 힘 대신 영리한 생각으로 문제를 해결해 본 적이 있니?",
      "아스트리드는 왕자를 어떻게 구했을 것 같니?"] };
ACT["S2879"] = { s: "Ella is a mucky, messy kind of hippo. Her sisters, Primrose and Daisy, are always neat and tidy. What will happen when the Prince asks them all to his party?",
  q: ["How are Ella's sisters different from her?",
      "Are you more messy or more neat and tidy?",
      "What do you think happens when Ella goes to the Prince's party?"],
  h: ["엘라의 언니들은 엘라와 어떻게 다른가요?",
      "너는 지저분한 편이니, 깔끔한 편이니?",
      "엘라가 왕자님의 파티에 가면 무슨 일이 일어날 것 같니?"] };
ACT["S2880"] = { s: "When Spanner and Captain Comet investigate a new purple planet, they discover it is a space monster.",
  q: ["What do Spanner and Captain Comet discover the purple planet really is?",
      "Have you ever thought something ordinary was actually something surprising?",
      "What would you do if you discovered a planet was really a monster?"],
  h: ["스패너와 코멧 선장은 보라색 행성이 사실은 무엇이라는 것을 발견하나요?",
      "너는 평범해 보이던 것이 사실 놀라운 것이었다고 생각한 적이 있니?",
      "행성이 사실 괴물이라는 것을 알게 된다면 너는 어떻게 하겠니?"] };
ACT["S2881"] = { s: "Robo-Vac can tidy up anything, but it also tries to run the life of Connor. He wants to stop it, but without hurting its feelings.",
  q: ["What does Connor want to do without hurting Robo-Vac's feelings?",
      "Have you ever had to say no to someone kindly?",
      "How would you stop a robot without hurting its feelings?"],
  h: ["코너는 로보백의 마음을 다치게 하지 않으면서 무엇을 하고 싶어 하나요?",
      "너는 누군가에게 친절하게 거절해 본 적이 있니?",
      "로봇의 마음을 다치지 않게 하면서 너는 어떻게 멈추게 하겠니?"] };
ACT["S2882"] = { s: "Best friends Emma and Sam dig up something strange on the beach. They take it to school, but when it hatches into a baby dinosaur nobody knows what to do.",
  q: ["What does the strange thing hatch into?",
      "Have you ever found something strange or surprising outside?",
      "What would you do if a baby dinosaur hatched at your school?"],
  h: ["이상한 것은 부화해서 무엇이 되나요?",
      "너는 밖에서 이상하거나 놀라운 것을 발견해 본 적이 있니?",
      "학교에서 아기 공룡이 부화한다면 너는 어떻게 하겠니?"] };
ACT["S2883"] = { s: "When the family move into a haunted house, they fall out with the Spook family who live there. When they try to move away, the house begins to fall down, so they learn to get along and both families end up sharing the house peacefully.",
  q: ["What do the two families learn to do in the end?",
      "Have you ever had to learn to get along with someone you disagreed with?",
      "How would you share a house peacefully with a ghost family?"],
  h: ["두 가족은 결국 무엇을 하는 법을 배우나요?",
      "너는 의견이 달랐던 사람과 사이좋게 지내는 법을 배운 적이 있니?",
      "유령 가족과 집을 평화롭게 나눠 쓴다면 너는 어떻게 하겠니?"] };
ACT["S2884"] = { s: "Mr. Flinch hates noise. His neighbours are just the opposite ― they like having fun and making lots of noise. Flinch wants to get rid of them, but will he regret his actions?",
  q: ["What does Mr. Flinch want to do to his noisy neighbours?",
      "Have you ever been bothered by a loud noise?",
      "Do you think Mr. Flinch will regret his actions? Why?"],
  h: ["플린치 씨는 시끄러운 이웃에게 무엇을 하고 싶어 하나요?",
      "너는 시끄러운 소리 때문에 불편했던 적이 있니?",
      "플린치 씨는 자신의 행동을 후회할 것 같니? 왜 그렇게 생각하니?"] };
ACT["S2885"] = { s: "Spanner and two captains go off to investigate a spaceship that seems to be empty. It turns out to be a trap set by space pirates. The pirates tries to steal everything from them, but Spanner saves the day.",
  q: ["Who sets the trap on the empty spaceship?",
      "Have you ever felt like something was a trick or a trap?",
      "How do you think Spanner saves the day?"],
  h: ["텅 빈 우주선에 함정을 놓은 것은 누구인가요?",
      "너는 무언가 속임수나 함정처럼 느껴진 적이 있니?",
      "스패너는 어떻게 상황을 구해 낼 것 같니?"] };
ACT["S2886"] = { s: "Class Four has a new boy. He is called Otto, he comes from outer space and he is green! Otto speaks English, but takes every word literally, which causes some misunderstandings.",
  q: ["Why does Otto cause misunderstandings?",
      "Have you ever misunderstood what someone meant?",
      "What word do you think would confuse Otto the most?"],
  h: ["오토는 왜 오해를 일으키나요?",
      "너는 누군가의 말을 오해해 본 적이 있니?",
      "오토가 가장 헷갈려 할 말은 무엇일 것 같니?"] };
ACT["S2887"] = { s: "Spider says that nothing scares him, but there are monsters on the other side of the thorn bush. He goes to the monsters’ house for an adventure.",
  q: ["What does Spider say about himself?",
      "Have you ever said you weren't scared, even if you were a little?",
      "What do you think Spider finds at the monsters' house?"],
  h: ["거미는 자기 자신에 대해 뭐라고 말하나요?",
      "너는 조금 무서워도 무섭지 않다고 말해 본 적이 있니?",
      "거미는 괴물들의 집에서 무엇을 발견할 것 같니?"] };
ACT["S2888"] = { s: "Jenny and Lucas live next door to Mr. Perkins. He is mad about TV and pretends to be a film character. Luckily Lucas and Jenny like having a cowboy next door!",
  q: ["What does Mr. Perkins pretend to be?",
      "Have you ever pretended to be a character from a movie or show?",
      "What character would you like to pretend to be?"],
  h: ["퍼킨스 씨는 무엇인 척하나요?",
      "너는 영화나 방송 속 인물인 척해 본 적이 있니?",
      "너는 어떤 인물인 척하고 싶니?"] };
ACT["S2889"] = { s: "Princess Pip goes on holiday with her parents, the King and Queen, and finds it all very boring. Then Daisy, the servant girl, helps Pip to discover that the seaside is far from dull.",
  q: ["Who helps Princess Pip discover the seaside is fun?",
      "Have you ever thought something was boring until someone showed you it wasn't?",
      "What would you show Princess Pip to do at the seaside?"],
  h: ["누가 핍 공주에게 바닷가가 재미있다는 것을 알게 해 주나요?",
      "너는 지루하다고 생각했다가 누군가 덕분에 아니라는 것을 알게 된 적이 있니?",
      "너라면 핍 공주에게 바닷가에서 무엇을 하라고 보여 주고 싶니?"] };
ACT["S2890"] = { s: "The animals of the Arctic are all very talented, but Walrus does not have any special skill. He tries to join in with the others, but ends up annoying them.",
  q: ["What does Walrus try to do with the other animals?",
      "Have you ever wanted to join in but felt you weren't good enough?",
      "What special skill would you give Walrus?"],
  h: ["바다코끼리는 다른 동물들과 무엇을 하려 하나요?",
      "너는 함께하고 싶었지만 잘 못한다고 느낀 적이 있니?",
      "바다코끼리에게 어떤 특별한 재주를 주고 싶니?"] };
ACT["S2891"] = { s: "Lenny loves playing soccer very much. He wants a new pair of shorts so he can play at school.",
  q: ["Why does Lenny want a new pair of shorts?",
      "Do you have a favorite sport you love to play?",
      "What would you want to wear to play your favorite sport?"],
  h: ["레니는 왜 새 반바지를 원하나요?",
      "너에게 즐겨 하는 좋아하는 운동이 있니?",
      "네가 좋아하는 운동을 할 때 무엇을 입고 싶니?"] };
ACT["S2892"] = { s: "Everyone is making things for the craft fair, and Shahnaz wants to make something extra special.",
  q: ["What does Shahnaz want to make?",
      "Have you ever made something special for a fair or a gift?",
      "What would you make that is extra special?"],
  h: ["샤나즈는 무엇을 만들고 싶어 하나요?",
      "너는 축제나 선물을 위해 특별한 것을 만들어 본 적이 있니?",
      "너는 어떤 특별한 것을 만들고 싶니?"] };
ACT["S2893"] = { s: "Snap, the boss dog of Blossom Street, comes up with a clever way to watch over his old neighborhood after moving away.",
  q: ["What does Snap come up with to watch over his old neighborhood?",
      "Have you ever missed a place you used to live?",
      "How would you watch over a place you moved away from?"],
  h: ["스냅은 예전 동네를 지켜보기 위해 어떤 영리한 방법을 생각해 내나요?",
      "너는 예전에 살던 곳이 그리웠던 적이 있니?",
      "네가 떠나온 곳을 너는 어떻게 지켜보겠니?"] };
ACT["S2894"] = { s: "Nothing ever happens at Riverside Apartments, until the day Mr. Stofflees moves in.",
  q: ["What changes when Mr. Stofflees moves in?",
      "Have you ever had a new, interesting neighbor move in?",
      "What do you think happens after Mr. Stofflees moves in?"],
  h: ["스토플리스 씨가 이사 오면서 무엇이 달라지나요?",
      "너는 흥미로운 새 이웃이 이사 온 적이 있니?",
      "스토플리스 씨가 이사 온 뒤 무슨 일이 생길 것 같니?"] };
ACT["S2895"] = { s: "The castle is in a terrible mess. Princess Jane and King Harry try to solve this problem with the help of the amazing Cleaning Ladies of Om.",
  q: ["Who helps Princess Jane and King Harry solve the problem?",
      "Have you ever needed help to clean up a big mess?",
      "What do you think the Cleaning Ladies of Om can do?"],
  h: ["제인 공주와 해리 왕을 도와 문제를 해결하는 이들은 누구인가요?",
      "너는 큰 어질러진 곳을 치우는 데 도움이 필요했던 적이 있니?",
      "옴의 청소부 아주머니들은 무엇을 할 수 있을 것 같니?"] };
ACT["S2896"] = { s: "When the Castle Carrot King plays a dirty trick to win a soccer match, the Masked Cleaning Ladies are there to deal with it.",
  q: ["What does the Castle Carrot King do to win the match?",
      "Have you ever seen someone play unfairly in a game?",
      "How do you think the Cleaning Ladies deal with the trick?"],
  h: ["캐슬 캐럿 왕은 경기에서 이기려고 무엇을 하나요?",
      "너는 게임에서 누군가 반칙하는 것을 본 적이 있니?",
      "청소부 아주머니들은 그 속임수를 어떻게 처리할 것 같니?"] };
ACT["S2897"] = { s: "Rachel likes all of Grandma's buttons, until she sees the purple buttons at the bottom of the tin. Are they as unlucky as she thinks?",
  q: ["What does Rachel think about the purple buttons?",
      "Have you ever thought something was unlucky?",
      "Do you think the purple buttons are really unlucky? Why?"],
  h: ["레이첼은 보라색 단추에 대해 어떻게 생각하나요?",
      "너는 무언가가 불운하다고 생각해 본 적이 있니?",
      "보라색 단추가 정말 불운할 것 같니? 왜 그렇게 생각하니?"] };
ACT["S2898"] = { s: "Scott's little sister Laura is very proud of her new jelly shoes. Scott, tells her they are made of jellyfish, she changes her mind about the shoes.",
  q: ["What does Scott tell Laura the shoes are made of?",
      "Have you ever changed your mind about something you liked?",
      "Do you think the shoes are really made of jellyfish?"],
  h: ["스콧은 신발이 무엇으로 만들어졌다고 로라에게 말하나요?",
      "너는 좋아하던 것에 대해 마음이 바뀐 적이 있니?",
      "그 신발이 정말 해파리로 만들어졌을 것 같니?"] };
ACT["S2899"] = { s: "Dexter is mad about dinosaurs. He wants a dinosaur for his birthday. Can his friend the magician help him?",
  q: ["What does Dexter want for his birthday?",
      "What is something you really wanted for your birthday?",
      "How do you think the magician could get Dexter a dinosaur?"],
  h: ["덱스터는 생일 선물로 무엇을 원하나요?",
      "네가 생일에 정말 갖고 싶었던 것은 무엇이었니?",
      "마법사는 덱스터에게 공룡을 어떻게 구해 줄 것 같니?"] };
