// 간이 학습 질문 — Book No. S29 묶음. 사람이 아니라 AI 가 한 번 쓰고 굳힌 파일이다.
window.ACT = window.ACT || {};
var ACT = window.ACT;
ACT["S2900"] = { s: "Queen Norah thinks she knows everything that goes on in the castle. But she is wrong. Princess Jane and the Masked Cleaning Ladies know what to do with pirates.",
  q: ["What do you think Princess Jane and the Masked Cleaning Ladies did when the pirates came?",
      "Have you ever pretended to be someone else, like a hero in disguise?",
      "If you were a masked cleaning lady fighting pirates, what would you use as your weapon?"],
  h: ["프린세스 제인과 가면 쓴 청소부들은 해적이 나타났을 때 무엇을 했을 것 같나요?",
      "변장한 영웅처럼 누군가인 척 해 본 적이 있나요?",
      "네가 해적과 싸우는 가면 쓴 청소부라면 무엇을 무기로 쓰고 싶나요?"] };
ACT["S2901"] = { s: "Ross should wear red velvet pants on his sister's wedding day and tries to find a way to get out of doing it.",
  q: ["What do you think Ross tried to do to get out of wearing the red velvet trousers?",
      "Have you ever had to wear clothes you didn't like for a special event?",
      "If you had to wear something embarrassing to a wedding, what would you do?"],
  h: ["로스는 빨간 벨벳 바지를 안 입으려고 무엇을 했을 것 같나요?",
      "특별한 날에 입기 싫은 옷을 입어야 했던 적이 있나요?",
      "결혼식에서 창피한 옷을 입어야 한다면 너는 어떻게 하겠나요?"] };
ACT["S2902"] = { s: "Sue makes suits, but in The Great Spaghetti Suit she meets her toughest customer. Then Sue's son has an idea for a very special suit.",
  q: ["What kind of special suit do you think Sue's son came up with?",
      "Have you ever had a really difficult customer or hard-to-please person to deal with?",
      "If you could design a suit made of food, what food would you choose?"],
  h: ["수의 아들은 어떤 특별한 옷을 생각해 냈을 것 같나요?",
      "다루기 정말 힘든 손님이나 사람을 만나 본 적이 있나요?",
      "음식으로 옷을 만든다면 너는 어떤 음식을 고르고 싶나요?"] };
ACT["S2903"] = { s: "Rodney tries to create an amazing paint machine in order to sell his dad's buns to the Charming Tea Shop.",
  q: ["What do you think Rodney's paint machine was supposed to do to help sell the buns?",
      "Have you ever tried to invent something to solve a problem?",
      "If you invented a machine to help your family's business, what would it do?"],
  h: ["로드니의 페인트 기계는 빵을 파는 데 어떻게 도움을 주려 했을 것 같나요?",
      "문제를 해결하려고 무언가를 발명해 본 적이 있나요?",
      "네가 가족의 가게를 도울 기계를 발명한다면 어떤 일을 하는 기계일까요?"] };
ACT["S2904"] = { s: "Twins Bertha and Flo come up with a clever way to be loved as twin wrestlers.",
  q: ["What clever plan do you think the twins used to become loved wrestlers?",
      "Do you have a twin, or do you know any twins? What are they like?",
      "If you were a wrestler, what would your wrestling name be?"],
  h: ["쌍둥이 자매는 사랑받는 레슬러가 되려고 어떤 영리한 계획을 세웠을 것 같나요?",
      "너는 쌍둥이거나, 쌍둥이를 알고 있나요? 그들은 어떤가요?",
      "네가 레슬러라면 레슬링 이름을 무엇으로 짓고 싶나요?"] };
ACT["S2905"] = { s: "Derek and Janey try to hide the disaster that happened to Mr. Such's trousers in art class.",
  q: ["What do you think happened to Mr. Such's trousers in art class?",
      "Have you ever tried to hide a mistake or accident from someone?",
      "If you ruined someone's clothes by accident, what would you do?"],
  h: ["미술 시간에 서치 선생님의 바지에 무슨 일이 일어났을 것 같나요?",
      "실수나 사고를 누군가에게 숨기려 한 적이 있나요?",
      "실수로 누군가의 옷을 망가뜨렸다면 너는 어떻게 하겠나요?"] };
ACT["S2906"] = { s: "Amy gets an ability to communicate with hedgehogs. And Mr. Peck from next door plans to earn money using Amy's ability.",
  q: ["How do you think Mr. Peck planned to use Amy's ability to earn money?",
      "If you could talk to one kind of animal, which animal would you choose?",
      "Do you think it's right for Mr. Peck to use Amy's special ability for money? Why or why not?"],
  h: ["펙 아저씨는 에이미의 능력을 이용해서 돈을 어떻게 벌려고 했을 것 같나요?",
      "한 가지 동물과 이야기할 수 있다면 어떤 동물을 고르고 싶나요?",
      "펙 아저씨가 에이미의 특별한 능력을 돈벌이에 쓰는 것이 옳다고 생각하나요, 아닌가요? 이유는 무엇인가요?"] };
ACT["S2907"] = { s: "Rodney has to take flans to a shop on the other side of the river. The bridge is broken. How can Rodney deliver the flans across the river?",
  q: ["How do you think Rodney managed to get the flans across the broken bridge?",
      "Have you ever had a problem where you had to find a creative way to get somewhere?",
      "If the bridge was broken, how would you get the flans across the river?"],
  h: ["로드니는 부서진 다리를 건너 플랑을 어떻게 옮겼을 것 같나요?",
      "어딘가에 가려고 창의적인 방법을 찾아야 했던 적이 있나요?",
      "다리가 부서졌다면 너는 플랑을 강 건너로 어떻게 옮기겠나요?"] };
ACT["S2908"] = { s: "Bertie Wiggins takes the place of Prince Cecil on the royal television show and amazing secrets about the royal family are revealed in the show.",
  q: ["What kind of secrets about the royal family do you think were revealed on the show?",
      "Have you ever pretended to be someone else, even just for fun?",
      "If you took someone else's place for a day, whose place would you want to take?"],
  h: ["그 쇼에서 왕실 가족에 대해 어떤 놀라운 비밀이 밝혀졌을 것 같나요?",
      "재미로라도 다른 사람인 척해 본 적이 있나요?",
      "하루 동안 다른 사람의 자리를 대신한다면 누구의 자리를 대신하고 싶나요?"] };
ACT["S2909"] = { s: "Ray Martin, the new boss of Football Club, sees his players all pouring tea in the shower. So he goes to see the tea lady to know the reason they don't drink tea.",
  q: ["Why do you think the players were pouring their tea in the shower instead of drinking it?",
      "Have you ever pretended to do something you didn't actually want to do?",
      "If you were the tea lady, what would you say to Ray Martin about the tea?"],
  h: ["선수들은 왜 차를 마시지 않고 샤워실에 부어 버렸을 것 같나요?",
      "사실은 하기 싫은 일을 하는 척해 본 적이 있나요?",
      "네가 그 차 담당 아주머니라면 레이 마틴에게 차에 대해 무슨 말을 하고 싶나요?"] };
ACT["S2910"] = { s: "Bob and Benny are eager to do odd jobs around the neighborhood. What odd jobs will they get?",
  q: ["What kind of odd jobs do you think Bob and Benny got in the neighborhood?",
      "Have you ever done a small job or chore to earn money or help someone?",
      "If you could do an odd job around your neighborhood, what job would you like to do?"],
  h: ["밥과 베니는 동네에서 어떤 잡다한 일들을 맡았을 것 같나요?",
      "돈을 벌거나 누군가를 돕기 위해 작은 일을 해 본 적이 있나요?",
      "네가 동네에서 잡다한 일을 한다면 어떤 일을 해 보고 싶나요?"] };
ACT["S2911"] = { s: "Janey makes a cricket team, Janey Giants, to defeat Fast Freddie. Her team consists of ten small players and a dog. Can she defeat arrogant Fast Freddie?",
  q: ["How do you think Janey's team of small players and a dog managed to play against Fast Freddie?",
      "Have you ever been on a team that other people didn't think could win?",
      "If your team had a dog as a player, what job would you give the dog?"],
  h: ["작은 선수들과 개로 이루어진 제이니의 팀은 패스트 프레디와 어떻게 경기했을 것 같나요?",
      "다른 사람들이 이길 거라 생각하지 않았던 팀에 있었던 적이 있나요?",
      "네 팀에 개가 선수로 있다면 그 개에게 어떤 역할을 맡기고 싶나요?"] };
ACT["S2912"] = { s: "Blackbones, the pirate teacher, hopes his idea to raise money at the school fair will make the principal withdraw her decision.",
  q: ["What kind of idea do you think Blackbones came up with to raise money at the school fair?",
      "Have you ever helped raise money for your school or a cause?",
      "If you had to raise money to save something at your school, what would you do?"],
  h: ["블랙본스는 학교 축제에서 돈을 모으려고 어떤 아이디어를 냈을 것 같나요?",
      "학교나 어떤 일을 위해 돈을 모으는 것을 도와 본 적이 있나요?",
      "학교의 무언가를 지키기 위해 돈을 모아야 한다면 너는 무엇을 하겠나요?"] };
ACT["S2913"] = { s: "My big brother's new purple trainers are not safe. At night, they move by themselves. I think they are alive!",
  q: ["What do you think the purple trainers did at night when they moved by themselves?",
      "Have you ever thought that one of your toys or things might be alive?",
      "If your shoes came alive at night, what do you think they would do?"],
  h: ["밤에 스스로 움직이는 보라색 운동화는 무엇을 했을 것 같나요?",
      "네 장난감이나 물건이 살아 있을지도 모른다고 생각해 본 적이 있나요?",
      "네 신발이 밤에 살아 움직인다면 무엇을 할 것 같나요?"] };
ACT["S2914"] = { s: "The mix-up between Pippa and Flo begins from a postman's mistake. But by the mistake, two girls becomes best friends.",
  q: ["What kind of mistake do you think the postman made between Pippa and Flo?",
      "Have you ever made a new friend because of a mistake or a surprise?",
      "If a mail mix-up brought you a new friend, what would you say to them first?"],
  h: ["우체부는 피파와 플로 사이에 어떤 실수를 했을 것 같나요?",
      "실수나 뜻밖의 일 때문에 새로운 친구를 사귀어 본 적이 있나요?",
      "우편물 실수로 새로운 친구가 생긴다면 그 친구에게 처음 무슨 말을 하고 싶나요?"] };
ACT["S2915"] = { s: "Poppleton decides he doesn't want to be a city pig anymore so he moves to a small town and meets new friends.",
  q: ["What do you think Poppleton found different about living in a small town compared to the city?",
      "Have you ever moved to a new place or started somewhere new?",
      "If you moved to a small town, what new friends would you want to meet?"],
  h: ["파플턴은 도시와 달리 작은 마을에서 사는 것이 어떻게 달랐을 것 같나요?",
      "새로운 곳으로 이사하거나 새로 시작해 본 적이 있나요?",
      "네가 작은 마을로 이사한다면 어떤 새 친구를 만나고 싶나요?"] };
ACT["S2916"] = { s: "Poppleton goes to the shore, struggles with dry skin, and tries a grapefruit for the first time.",
  q: ["What do you think happened when Poppleton tried a grapefruit for the first time?",
      "Have you ever tried a new food for the first time? What did you think of it?",
      "What new food would you like to try, like Poppleton did with the grapefruit?"],
  h: ["파플턴이 처음으로 자몽을 먹어 보았을 때 무슨 일이 있었을 것 같나요?",
      "새로운 음식을 처음 먹어 본 적이 있나요? 어땠나요?",
      "파플턴이 자몽을 먹어 본 것처럼 너는 어떤 새로운 음식을 먹어 보고 싶나요?"] };
ACT["S2917"] = { s: "Poppleton and his friends go look at the stars, go shopping and go sailing.",
  q: ["Which of the three things—looking at stars, shopping, or sailing—do you think Poppleton enjoyed the most?",
      "Have you ever looked at the stars, gone shopping, or gone sailing with friends?",
      "If you could do one of these three things with a friend, which would you choose?"],
  h: ["별 보기, 쇼핑, 배 타기 중에 파플턴은 어떤 것을 가장 즐겼을 것 같나요?",
      "친구와 함께 별을 보거나 쇼핑을 하거나 배를 타 본 적이 있나요?",
      "이 세 가지 중 하나를 친구와 함께한다면 무엇을 고르고 싶나요?"] };
ACT["S2918"] = { s: "Poppleton plants a tree, gets a cold, and hangs some wallpaper with the help of his friends.",
  q: ["How do you think Poppleton's friends helped him while he had a cold?",
      "Have your friends or family ever helped you when you were sick?",
      "If your friend was sick, what would you do to help them?"],
  h: ["파플턴이 감기에 걸렸을 때 친구들은 어떻게 도와주었을 것 같나요?",
      "네가 아팠을 때 친구나 가족이 도와준 적이 있나요?",
      "네 친구가 아프다면 너는 어떻게 도와주고 싶나요?"] };
ACT["S2919"] = { s: "Poppleton goes to a movie, decides to make a quilt, and soaks in a bathtub.",
  q: ["Which of these three things do you think Poppleton enjoyed doing the most: watching a movie, making a quilt, or soaking in a bathtub?",
      "Have you ever watched a movie, made something with your hands, or relaxed in a bath?",
      "If you had a free day like Poppleton, what would you choose to do?"],
  h: ["영화 보기, 퀼트 만들기, 목욕하기 중에 파플턴은 무엇을 가장 즐겼을 것 같나요?",
      "영화를 보거나 손으로 무언가를 만들거나 목욕하며 쉬어 본 적이 있나요?",
      "파플턴처럼 자유로운 하루가 있다면 너는 무엇을 하고 싶나요?"] };
ACT["S2920"] = { s: "In this book, Froggy is helping his father prepare to celebrate his mother's birthday.",
  q: ["What do you think Froggy and his dad did to prepare for the mom's birthday?",
      "Have you ever helped plan a birthday surprise for someone in your family?",
      "If you planned a birthday surprise for your mom, what would you do?"],
  h: ["프로기와 아빠는 엄마의 생일을 준비하려고 무엇을 했을 것 같나요?",
      "가족을 위한 생일 깜짝 파티를 준비해 본 적이 있나요?",
      "네가 엄마를 위한 생일 깜짝 파티를 준비한다면 무엇을 하고 싶나요?"] };
ACT["S2921"] = { s: "When Froggy goes to a sleep-away camp, he causes tons of trouble for the camp's director.",
  q: ["What kind of trouble do you think Froggy caused at the sleep-away camp?",
      "Have you ever been to a camp or a sleepover away from home?",
      "If you went to camp like Froggy, what trouble might accidentally happen to you?"],
  h: ["프로기는 캠프에서 캠프 감독에게 어떤 사고를 쳤을 것 같나요?",
      "집을 떠나 캠프나 다른 곳에서 자 본 적이 있나요?",
      "프로기처럼 캠프에 간다면 너에게는 어떤 사고가 생길 것 같나요?"] };
ACT["S2922"] = { s: "Froggy is excited for his first day on the T-ball team. But he finds it hard to remember the rules.",
  q: ["What kind of rules do you think Froggy had trouble remembering in T-ball?",
      "Have you ever joined a new team or game and found the rules hard to remember?",
      "If a friend forgot the rules like Froggy, how would you help them remember?"],
  h: ["프로기는 티볼에서 어떤 규칙을 기억하기 힘들어했을 것 같나요?",
      "새로운 팀이나 게임에 들어가서 규칙을 기억하기 힘들었던 적이 있나요?",
      "친구가 프로기처럼 규칙을 잊어버린다면 너는 어떻게 도와주겠나요?"] };
ACT["S2923"] = { s: "When Froggy's parents go out for the night, Froggy is left with a brand-new babysitter!",
  q: ["What do you think happened between Froggy and his brand-new babysitter?",
      "Have you ever had a babysitter or someone new take care of you?",
      "If you were Froggy's new babysitter, what would you do to become his friend?"],
  h: ["프로기와 새로 온 아기 돌보미 사이에 무슨 일이 있었을 것 같나요?",
      "새로운 사람이 너를 돌봐 준 적이 있나요?",
      "네가 프로기의 새 돌보미라면 친해지려고 무엇을 하고 싶나요?"] };
ACT["S2924"] = { s: "It is Froggy's birthday, but no one, even his parents, seems to realize it is his special day.",
  q: ["What do you think Froggy did when no one remembered his birthday?",
      "Have you ever felt like people forgot about you or something important to you?",
      "If your family forgot your birthday, what would you say or do?"],
  h: ["아무도 생일을 기억하지 못했을 때 프로기는 무엇을 했을 것 같나요?",
      "사람들이 너를, 혹은 너에게 중요한 것을 잊어버렸다고 느낀 적이 있나요?",
      "가족이 네 생일을 잊어버렸다면 너는 무슨 말을 하거나 어떻게 하겠나요?"] };
ACT["S2925"] = { s: "When none of Froggy's friends is home, his dad suggests a movie outing with Frogillina.",
  q: ["What do you think happened on the movie outing with Froggy and Frogillina?",
      "Have you ever spent time with someone new because your usual friends weren't around?",
      "If your dad suggested you hang out with someone you didn't know well, how would you feel?"],
  h: ["프로기와 프로질리나가 영화를 보러 갔을 때 무슨 일이 있었을 것 같나요?",
      "평소 친구들이 없어서 새로운 사람과 시간을 보낸 적이 있나요?",
      "아빠가 잘 모르는 사람과 놀라고 한다면 너는 기분이 어떨 것 같나요?"] };
ACT["S2926"] = { s: "Nate is invited to a birthday party where the birthday girl is bringing her four snakes, one of which goes missing.",
  q: ["What clues do you think Nate used to find the missing snake?",
      "Have you ever lost a pet or something and had to search for it?",
      "If you were Nate the detective, how would you look for the missing snake?"],
  h: ["네이트는 잃어버린 뱀을 찾으려고 어떤 단서를 썼을 것 같나요?",
      "반려동물이나 물건을 잃어버려서 찾아본 적이 있나요?",
      "네가 탐정 네이트라면 잃어버린 뱀을 어떻게 찾겠나요?"] };
ACT["S2927"] = { s: "Nate helps his friend Esmeralda find the word she came up with for the name of the pet concert, before it's too late.",
  q: ["What do you think the missing word for the pet concert's name was?",
      "Have you ever forgotten an important word or idea you wanted to remember?",
      "If you were naming a concert for pets, what name would you come up with?"],
  h: ["애완동물 콘서트의 이름으로 쓸, 잃어버린 그 단어는 무엇이었을 것 같나요?",
      "기억해 두고 싶었던 중요한 말이나 생각을 잊어버린 적이 있나요?",
      "네가 애완동물 콘서트의 이름을 짓는다면 어떤 이름을 짓고 싶나요?"] };
ACT["S2928"] = { s: "Nate the Great and his dog, Sludge, would like to take a break from detective work, but new cases await them.",
  q: ["What kind of new case do you think Nate and Sludge had to solve?",
      "Have you ever wanted a break from something but had to keep doing it?",
      "If you were Nate, what new mystery would you like to solve?"],
  h: ["네이트와 슬러지는 어떤 새로운 사건을 풀어야 했을 것 같나요?",
      "무언가를 쉬고 싶었지만 계속해야 했던 적이 있나요?",
      "네가 네이트라면 어떤 새로운 수수께끼를 풀어보고 싶나요?"] };
ACT["S2929"] = { s: "Lola is obsessed with the book called Beetles, Bugs, and Butterflies. She is disappointed when the book is not on the library's shelf. Charlie tries to find another book that she might enjoy.",
  q: ["What kind of book do you think Charlie tried to find for Lola instead?",
      "Have you ever gone to the library looking for a specific book and not found it?",
      "If you were Charlie, what book would you suggest to Lola instead?"],
  h: ["찰리는 롤라를 위해 대신 어떤 책을 찾아 주려 했을 것 같나요?",
      "도서관에서 원하던 책을 찾지 못한 적이 있나요?",
      "네가 찰리라면 롤라에게 대신 어떤 책을 추천하고 싶나요?"] };
ACT["S2930"] = { s: "Lola wears her alligator costume everywhere, and Charlie feels a bit embarrassed. When Lola plans to wear it for her school talk, Charlie tries to stop her from making a fool of herself.",
  q: ["What do you think happened when Lola wore her alligator costume for her school talk?",
      "Have you ever felt embarrassed by something a family member did or wore?",
      "If your little sibling wanted to wear a silly costume to school, what would you say?"],
  h: ["롤라가 학교 발표에서 악어 옷을 입었을 때 무슨 일이 있었을 것 같나요?",
      "가족이 한 일이나 입은 옷 때문에 창피했던 적이 있나요?",
      "네 동생이 학교에 우스꽝스러운 옷을 입고 가고 싶어 한다면 뭐라고 말하겠나요?"] };
ACT["S2931"] = { s: "Lola devises plans to cheer Charlie up after he breaks his arm.",
  q: ["What kind of plans do you think Lola came up with to cheer Charlie up?",
      "Have you ever gotten hurt, or tried to cheer up someone who was hurt?",
      "If your friend broke their arm, what would you do to make them feel better?"],
  h: ["롤라는 찰리를 기분 좋게 해 주려고 어떤 계획을 세웠을 것 같나요?",
      "다쳐 본 적이 있거나, 다친 사람을 기분 좋게 해 준 적이 있나요?",
      "네 친구가 팔을 다쳤다면 너는 무엇을 해서 기분을 풀어 주겠나요?"] };
ACT["S2932"] = { s: "Charlie and her little sister Lola are trying their best to beat the summer heat. Lola gets boiling mad with Arnold when he accidentally knocks her ice cream to the ground and refuses to apologize.",
  q: ["What do you think Lola did when Arnold wouldn't apologize for the ice cream?",
      "Have you ever gotten really upset when someone wouldn't say sorry?",
      "If someone accidentally knocked your ice cream down and didn't apologize, what would you say?"],
  h: ["아놀드가 사과하지 않았을 때 롤라는 어떻게 했을 것 같나요?",
      "누군가 미안하다고 말하지 않아서 정말 화났던 적이 있나요?",
      "누군가 네 아이스크림을 실수로 떨어뜨리고 사과하지 않는다면 너는 뭐라고 말하겠나요?"] };
ACT["S2933"] = { s: "Lola has 'Save an Animal Day' at her school. She chooses a panda as the animal she wants to save.",
  q: ["What do you think Lola did to help save pandas for her school project?",
      "Which animal would you choose to save if your school had a \"Save an Animal Day\"?",
      "What would you tell your classmates about why your chosen animal needs saving?"],
  h: ["롤라는 학교 과제로 판다를 지키려고 무엇을 했을 것 같나요?",
      "학교에 '동물 지키기의 날'이 있다면 너는 어떤 동물을 고르고 싶나요?",
      "네가 고른 동물이 왜 지켜져야 하는지 친구들에게 뭐라고 말하고 싶나요?"] };
ACT["S2934"] = { s: "Lola is getting ready for Field Day. She finds that she might do well in the egg-and-spoon race if only she practices her concentration.",
  q: ["How do you think Lola practiced her concentration for the egg-and-spoon race?",
      "Have you ever practiced something hard to get better at a game or sport?",
      "If you were in an egg-and-spoon race, how would you stay focused?"],
  h: ["롤라는 달걀 숟가락 경주를 위해 집중력을 어떻게 연습했을 것 같나요?",
      "게임이나 운동을 더 잘하려고 힘든 것을 연습해 본 적이 있나요?",
      "네가 달걀 숟가락 경주를 한다면 집중력을 어떻게 유지하겠나요?"] };
ACT["S2935"] = { s: "Lola wants to do everything on her own. But things turn out to be more challenging than she guessed.",
  q: ["What kind of things do you think Lola tried to do all by herself?",
      "Have you ever tried to do something on your own that turned out harder than you thought?",
      "What is something you'd like to try doing all by yourself?"],
  h: ["롤라는 혼자서 어떤 일들을 해 보려고 했을 것 같나요?",
      "혼자 해 보려 했는데 생각보다 어려웠던 일이 있나요?",
      "네가 혼자 해 보고 싶은 일은 무엇인가요?"] };
ACT["S2936"] = { s: "On the day of the school concert, when Lola is practicing singing, she gets a case of hiccups. Everyone tries to help Lola get rid of hiccups, but nothing works.",
  q: ["What kinds of things do you think people tried to get rid of Lola's hiccups?",
      "Have you ever gotten hiccups at a bad time? What did you do?",
      "What is your own trick for getting rid of hiccups?"],
  h: ["사람들은 롤라의 딸꾹질을 없애려고 어떤 방법들을 써 보았을 것 같나요?",
      "하필 안 좋은 때에 딸꾹질을 해 본 적이 있나요? 그때 어떻게 했나요?",
      "딸꾹질을 없애는 너만의 방법을 적어 보세요."] };
ACT["S2937"] = { s: "Lola brings the class guinea pig, Bert, home for summer vacation. She gets in trouble when Bert escapes.",
  q: ["What do you think happened when Bert the guinea pig escaped from Lola's house?",
      "Have you ever taken care of a class pet or someone else's pet?",
      "If your class pet escaped while you were watching it, what would you do?"],
  h: ["기니피그 버트가 롤라의 집에서 도망쳤을 때 무슨 일이 있었을 것 같나요?",
      "학급 반려동물이나 다른 사람의 반려동물을 돌봐 본 적이 있나요?",
      "네가 돌보던 학급 반려동물이 도망친다면 너는 어떻게 하겠나요?"] };
ACT["S2938"] = { s: "Lola decides that she must have glasses, and she goes to the optician.",
  q: ["What do you think happened when Lola went to the optician to get glasses?",
      "Have you ever wanted something just because a friend or classmate had it?",
      "If you got glasses like Lola, what color frames would you want to pick?"],
  h: ["롤라가 안경을 맞추러 안경점에 갔을 때 무슨 일이 있었을 것 같나요?",
      "친구가 가진 것을 보고 너도 갖고 싶었던 적이 있나요?",
      "롤라처럼 안경을 맞춘다면 어떤 색 안경테를 고르고 싶나요?"] };
ACT["S2939"] = { s: "Lola is excited to have her first sleepover at Lotta's house. But everything is just a bit too different, and Lola misses home.",
  q: ["What do you think felt too different for Lola at Lotta's house?",
      "Have you ever had a sleepover and missed home?",
      "If you were Lotta, what would you do to help Lola feel more comfortable?"],
  h: ["롯다의 집에서 무엇이 롤라에게 낯설게 느껴졌을 것 같나요?",
      "다른 집에서 자면서 집이 그리웠던 적이 있나요?",
      "네가 롯다라면 롤라가 편안하게 느끼도록 무엇을 해 주고 싶나요?"] };
ACT["S2940"] = { s: "Lola is disappointed to find out that she isn't still tall enough to ride the roller coaster at the fair.  Charlie tells her that there are many good things about being small.",
  q: ["What good things about being small do you think Charlie told Lola about?",
      "Have you ever been too small or too young to do something you wanted?",
      "What do you think is a good thing about being smaller or younger?"],
  h: ["찰리는 작다는 것의 좋은 점으로 롤라에게 무엇을 말해 주었을 것 같나요?",
      "너무 작거나 어려서 하고 싶은 것을 못 해 본 적이 있나요?",
      "작거나 어리다는 것의 좋은 점은 무엇이라고 생각하나요?"] };
ACT["S2941"] = { s: "Lola finds a toy rabbit that someone lost. She and Charlie try to look for its owner.",
  q: ["How do you think Lola and Charlie tried to find the owner of the lost toy rabbit?",
      "Have you ever found something that belonged to someone else? What did you do?",
      "If you found a lost toy, how would you try to find its owner?"],
  h: ["롤라와 찰리는 잃어버린 토끼 인형의 주인을 어떻게 찾으려 했을 것 같나요?",
      "다른 사람의 물건을 주운 적이 있나요? 그때 어떻게 했나요?",
      "잃어버린 장난감을 발견하면 너는 주인을 어떻게 찾으려 하겠나요?"] };
ACT["S2942"] = { s: "Marv and his little brother Morten come to play. Lola wants to play \"tea party\" with Morten, but he doesn't seem interested.",
  q: ["What do you think Lola did to try to get Morten interested in playing tea party?",
      "Have you ever tried to get someone interested in a game they didn't want to play?",
      "What game would you suggest instead if a friend wasn't interested in your idea?"],
  h: ["몰텐이 다과회 놀이에 관심 없어 하자 롤라는 관심을 끌려고 무엇을 했을 것 같나요?",
      "누군가 하기 싫어하는 게임에 관심을 갖게 하려 한 적이 있나요?",
      "친구가 네 놀이에 관심이 없다면 대신 어떤 놀이를 제안하고 싶나요?"] };
ACT["S2943"] = { s: "Lola and Lotta are best friends, and they do everything together. But when a new girl comes between them, Lola feels left out.",
  q: ["What do you think happened between Lola, Lotta, and the new girl?",
      "Have you ever felt left out when your friend made a new friend?",
      "If you were Lotta, how would you make sure Lola didn't feel left out?"],
  h: ["롤라, 롯다, 그리고 새로 온 여자아이 사이에 무슨 일이 있었을 것 같나요?",
      "친구가 새 친구를 사귀면서 네가 소외된 기분이 들었던 적이 있나요?",
      "네가 롯다라면 롤라가 소외감을 느끼지 않도록 어떻게 하겠나요?"] };
ACT["S2944"] = { s: "Lola is clearing out some of her old things. Charlie persuades her to recycle instead of throwing them out.",
  q: ["What do you think Charlie said to convince Lola to recycle instead of throw things away?",
      "Have you ever recycled or reused something instead of throwing it away?",
      "What is one thing you could recycle instead of throwing away?"],
  h: ["찰리는 물건을 버리지 말고 재활용하라고 롤라를 어떻게 설득했을 것 같나요?",
      "물건을 버리는 대신 재활용하거나 다시 써 본 적이 있나요?",
      "네가 버리지 않고 재활용할 수 있는 물건을 한 가지 적어 보세요."] };
ACT["S2945"] = { s: "Someone has stolen Papa’s blackberry honey, and it’s up to Brother, Sister, and Cousin Fred to solve the case.",
  q: ["Who do you think stole Papa's blackberry honey?",
      "Have you ever tried to figure out who took something that went missing?",
      "If you were a detective solving the honey mystery, what clues would you look for?"],
  h: ["누가 아빠의 블랙베리 꿀을 훔쳤을 것 같나요?",
      "없어진 물건을 누가 가져갔는지 알아내려 해 본 적이 있나요?",
      "네가 꿀 사건을 푸는 탐정이라면 어떤 단서를 찾아보겠나요?"] };
ACT["S2946"] = { s: "Brother, Sister, and Cousin Fred are ready to set out on a Bear Scout adventure. However, when Papa joins the trio, things end up becoming a bit of a mishap.",
  q: ["What kind of mishap do you think happened when Papa joined the Bear Scout adventure?",
      "Have you ever had a family trip or activity that didn't go as planned?",
      "If your parent joined your scout or club adventure, what do you think might go wrong?"],
  h: ["아빠가 곰 스카우트 모험에 합류했을 때 어떤 사고가 있었을 것 같나요?",
      "계획대로 되지 않았던 가족 여행이나 활동이 있었나요?",
      "네 부모님이 스카우트나 동아리 모험에 함께한다면 어떤 일이 잘못될 것 같나요?"] };
ACT["S2947"] = { s: "The Bears are off to a Bear Scout camping trip. But once they are in the woods, the cubs think they see a ghost.",
  q: ["What do you think the cubs actually saw in the woods that looked like a ghost?",
      "Have you ever thought you saw something scary that turned out to be something else?",
      "If you were camping in the woods and saw something that looked like a ghost, what would you do?"],
  h: ["아기 곰들이 숲에서 유령처럼 본 것은 사실 무엇이었을 것 같나요?",
      "무서운 것을 본 줄 알았는데 알고 보니 다른 것이었던 적이 있나요?",
      "숲에서 캠핑하다가 유령처럼 보이는 것을 본다면 너는 어떻게 하겠나요?"] };
ACT["S2948"] = { s: "In February, the first-graders in Mrs. Connor's class present facts about the presidents.",
  q: ["What kind of facts about presidents do you think the first-graders shared?",
      "Have you ever given a presentation or report in class about a person?",
      "If you researched a president, what fact would you want to share with your class?"],
  h: ["1학년 아이들은 대통령들에 대해 어떤 사실을 발표했을 것 같나요?",
      "어떤 인물에 대해 수업 시간에 발표하거나 보고서를 써 본 적이 있나요?",
      "대통령에 대해 조사한다면 친구들에게 어떤 사실을 알려 주고 싶나요?"] };
ACT["S2949"] = { s: "Mrs. Connor's first-graders watch as caterpillars slowly turn into butterflies in the butterfly garden at Robin Hill School.",
  q: ["What do you think the first-graders noticed as the caterpillars changed into butterflies?",
      "Have you ever watched an animal or insect grow or change over time?",
      "If you had a butterfly garden at your school, what would you want to watch happen?"],
  h: ["애벌레가 나비로 변하는 것을 보며 1학년 아이들은 무엇을 알아챘을 것 같나요?",
      "동물이나 곤충이 자라거나 변하는 모습을 지켜본 적이 있나요?",
      "학교에 나비 정원이 있다면 무엇을 지켜보고 싶나요?"] };
ACT["S2950"] = { s: "When Mrs. Connor's class celebrates Earth Day, Emma decides to start small by recycling, using only what she needs, and picking up trash when she goes for a walk.",
  q: ["Which of Emma's three Earth Day habits do you think helps the planet the most: recycling, using only what she needs, or picking up trash?",
      "Have you ever recycled, saved resources, or picked up trash to help the environment?",
      "What is one small thing you could start doing, like Emma, to help the Earth?"],
  h: ["재활용하기, 필요한 만큼만 쓰기, 쓰레기 줍기 중에 지구에 가장 도움이 되는 건 무엇이라고 생각하나요?",
      "환경을 위해 재활용을 하거나 자원을 아끼거나 쓰레기를 주워 본 적이 있나요?",
      "엠마처럼 네가 시작할 수 있는 작은 일 한 가지는 무엇인가요?"] };
ACT["S2951"] = { s: "Mrs. Connor's students share their dreams for the future after learning about the day that celebrates the life and dream of Dr. Martin Luther King Jr.",
  q: ["What kind of dreams for the future do you think the students shared?",
      "Have you ever thought about a dream you have for the future?",
      "What is one dream you have for the future? Write it down."],
  h: ["학생들은 어떤 미래의 꿈을 나누었을 것 같나요?",
      "미래에 대한 꿈을 생각해 본 적이 있나요?",
      "네가 가진 미래의 꿈 한 가지를 적어 보세요."] };
ACT["S2952"] = { s: "On a hot summer day, Mr. Putter and Tabby join Mrs. Teaberry and Zeke on an adventurous sightseeing boat cruise.",
  q: ["What kind of adventures do you think Mr. Putter and Tabby had on the boat cruise?",
      "Have you ever gone on a boat ride or a sightseeing trip?",
      "If you went on a boat cruise, where would you want to go?"],
  h: ["미스터 퍼터와 태비는 유람선에서 어떤 모험을 했을 것 같나요?",
      "배를 타 보거나 관광 여행을 가 본 적이 있나요?",
      "네가 유람선을 탄다면 어디로 가고 싶나요?"] };
ACT["S2953"] = { s: "Mr. Putter and Tabby take time off from napping and join the Yankee Doodle Dandies to play baseball.",
  q: ["What do you think happened when Mr. Putter played baseball with the Yankee Doodle Dandies?",
      "Have you ever taken a break from something you usually do to try something new?",
      "If you played on a baseball team, what position would you want to play?"],
  h: ["미스터 퍼터가 양키 두들 댄디스와 야구를 했을 때 무슨 일이 있었을 것 같나요?",
      "평소 하던 일을 잠시 쉬고 새로운 것을 해 본 적이 있나요?",
      "네가 야구팀에서 뛴다면 어떤 자리에서 뛰고 싶나요?"] };
ACT["S2954"] = { s: "When Mrs. Teaberry asks Mr. Putter to go ballroom dancing, he reluctantly agrees.",
  q: ["What do you think happened when Mr. Putter went ballroom dancing?",
      "Have you ever agreed to do something you didn't really want to do at first?",
      "If someone asked you to dance even though you didn't want to, what would you say?"],
  h: ["미스터 퍼터가 볼룸 댄스를 추러 갔을 때 무슨 일이 있었을 것 같나요?",
      "처음에는 별로 하고 싶지 않았지만 하겠다고 해 본 적이 있나요?",
      "누군가 하기 싫은 춤을 추자고 한다면 너는 뭐라고 말하겠나요?"] };
ACT["S2955"] = { s: "Mrs. Teaberry asks Mr. Putter to run a senior marathon with her. He agrees when he learns that the second prize is a train set.",
  q: ["Why do you think a train set made Mr. Putter want to run the marathon?",
      "Have you ever done something hard because of a prize or reward waiting for you?",
      "What prize would make you want to run a marathon?"],
  h: ["기차 세트가 왜 미스터 퍼터가 마라톤을 뛰고 싶게 만들었을 것 같나요?",
      "기다리는 상 때문에 힘든 일을 해 본 적이 있나요?",
      "어떤 상을 준다면 너는 마라톤을 뛰고 싶을 것 같나요?"] };
ACT["S2956"] = { s: "Mr. Putter and Tabby like winter but think it's rather boring. But when Mrs. Teaberry and Zeke pull two sleds out of the garage, he changes his mind.",
  q: ["What do you think happened once Mr. Putter tried sledding with Mrs. Teaberry and Zeke?",
      "Have you ever thought something was boring until you actually tried it?",
      "What winter activity would change your mind about winter being boring?"],
  h: ["미스터 퍼터가 썰매를 타 본 뒤에 무슨 일이 있었을 것 같나요?",
      "지루할 거라 생각했는데 직접 해 보니 재미있었던 것이 있나요?",
      "어떤 겨울 놀이가 너에게 겨울이 지루하지 않다고 생각하게 만들까요?"] };
ACT["S2957"] = { s: "A timid boy is eager to frighten the school bully on Halloween. He happens to acquire a magic ring and the power to change himself into a monster.",
  q: ["What do you think the timid boy did with his magic ring on Halloween?",
      "Have you ever wanted to scare someone or surprise them on Halloween?",
      "If you had a magic ring that could turn you into a monster, what would you do with it?"],
  h: ["겁 많은 소년은 핼러윈에 마법 반지로 무엇을 했을 것 같나요?",
      "핼러윈에 누군가를 놀래키거나 깜짝 놀라게 하고 싶었던 적이 있나요?",
      "괴물로 변신시켜 주는 마법 반지가 있다면 너는 무엇을 하겠나요?"] };
ACT["S2958"] = { s: "When Grandma falls asleep, Will finds himself responsible for his little brother and finds out the hard way what not to do when in charge.",
  q: ["What do you think Will did wrong while taking care of his little brother?",
      "Have you ever had to take care of a younger sibling or someone younger than you?",
      "If you were in charge of a little kid, what would you be careful not to do?"],
  h: ["윌은 동생을 돌보며 어떤 실수를 했을 것 같나요?",
      "동생이나 너보다 어린 사람을 돌봐 본 적이 있나요?",
      "네가 어린아이를 돌본다면 무엇을 조심하고 싶나요?"] };
ACT["S2959"] = { s: "When Chelsea proposes a Reading Buddy program that would require Will to hang out with the kindergartners, Will makes a decision to run against her for class president.",
  q: ["Why do you think Will decided to run against Chelsea for class president?",
      "Have you ever disagreed with someone's idea so much that you wanted to do something about it?",
      "If you ran for class president, what one idea would you promise to do?"],
  h: ["윌은 왜 첼시에 맞서 반장 선거에 나가기로 결심했을 것 같나요?",
      "누군가의 생각에 너무 반대해서 무언가 해 보고 싶었던 적이 있나요?",
      "네가 반장 선거에 나간다면 어떤 약속 한 가지를 하고 싶나요?"] };
ACT["S2960"] = { s: "The animals that are known to be bad guys group up to be good. Mr. Wolf, Mr. Piranha, Mr. Snake, and Mr. Shark break into the Maximum Security City Dog Pound and let 200 dogs out of it. And by doing this, they decide to do more good stuff.",
  q: ["Why do you think the Bad Guys chose to free the 200 dogs as their first good deed?",
      "Have you ever helped an animal or done something kind that surprised people?",
      "If you were part of the Bad Guys trying to become good, what good deed would you want to do first?"],
  h: ["배드 가이즈는 왜 첫 착한 일로 200마리의 개를 풀어 주기로 했을 것 같나요?",
      "동물을 도와주거나 사람들을 놀라게 할 만한 착한 일을 해 본 적이 있나요?",
      "네가 배드 가이즈의 일원이라면 처음으로 어떤 착한 일을 하고 싶나요?"] };
ACT["S2961"] = { s: "The bad guys who want to be good try to rescue 10,000 chickens from a high-tech cage farm guarded by lasers.",
  q: ["How do you think the Bad Guys got past the lasers to rescue the chickens?",
      "Have you ever had to be careful and sneaky to get something done?",
      "If you had to rescue 10,000 chickens from a guarded farm, what plan would you make?"],
  h: ["배드 가이즈는 레이저를 피해서 닭들을 어떻게 구했을 것 같나요?",
      "무언가를 해내려고 조심스럽고 은밀하게 움직여야 했던 적이 있나요?",
      "지켜지고 있는 농장에서 닭 만 마리를 구해야 한다면 너는 어떤 계획을 세우겠나요?"] };
ACT["S2962"] = { s: "The Good Guys get an anonymous call about bulldozers getting ready to destroy homes of forest animals. Then, they meet the furious guinea pig who is planning for a revenge.",
  q: ["Why do you think the guinea pig was so furious and planning revenge?",
      "Have you ever felt very angry about something unfair happening to animals or nature?",
      "If you were the Good Guys, how would you stop the bulldozers from destroying the animals' homes?"],
  h: ["기니피그는 왜 그렇게 화가 나서 복수를 계획하고 있었을 것 같나요?",
      "동물이나 자연에 불공평한 일이 생겨서 몹시 화가 났던 적이 있나요?",
      "네가 굿 가이즈라면 불도저가 동물들의 집을 부수는 것을 어떻게 막겠나요?"] };
ACT["S2963"] = { s: "There has been a zombie-kitten apocalypse. The Good Guys and Agent Fox try to find an antidote and meet Granny Gumbo. On the other hand, Mr. Shark and Mr. Piranha go to an island where Dr. Marmalade may be hiding.",
  q: ["What do you think Granny Gumbo told the Good Guys about the antidote?",
      "Have you ever had to search for something important with a team or friends?",
      "If you found zombie kittens, what would you do to help them?"],
  h: ["그래니 검보는 해독제에 대해 굿 가이즈에게 무엇을 알려 주었을 것 같나요?",
      "팀이나 친구들과 함께 중요한 것을 찾아 나선 적이 있나요?",
      "좀비 새끼 고양이를 발견한다면 너는 그들을 도우려고 무엇을 하겠나요?"] };
ACT["S2964"] = { s: "As Dr. Marmalade's Cute-Zilla Ray was turning cute animals into monsters, the Good Guys try to save the world. They borrow a rocket and go to the moon. There, they find Dr. Marmalade and try to stop him.",
  q: ["How do you think the Good Guys tried to stop Dr. Marmalade on the moon?",
      "Have you ever worked with a team to try to fix a big problem?",
      "If you flew a rocket to the moon to stop a villain, what would you bring with you?"],
  h: ["굿 가이즈는 달에서 마멀레이드 박사를 막으려고 어떻게 했을 것 같나요?",
      "큰 문제를 해결하려고 팀과 함께 일해 본 적이 있나요?",
      "악당을 막으러 달까지 로켓을 타고 간다면 무엇을 챙겨 가고 싶나요?"] };
ACT["S2965"] = { s: "Dr. Marmalade revealed his real identity. The Good Guys escape from the alien and find an escape pod. But the alien finds Legs and takes him away. One by one, the alien captures the other members, and they get trapped. Snake comes to save them and they successfully escape from the alien, but they end up at the wrong place.",
  q: ["How do you think Snake managed to save the other members from the alien?",
      "Have you ever had to help rescue a friend from a tricky situation?",
      "If you ended up in the wrong place after an escape like the Good Guys, what would you do next?"],
  h: ["스네이크는 다른 팀원들을 외계인에게서 어떻게 구했을 것 같나요?",
      "곤란한 상황에 처한 친구를 구하려고 애써 본 적이 있나요?",
      "굿 가이즈처럼 탈출 후 엉뚱한 곳에 도착한다면 너는 다음에 무엇을 하겠나요?"] };
ACT["S2966"] = { s: "While aliens invade earth, the Good Guys Club ends up in the distant past where dinosaurs exist. Legs finds a portal and thinks it's a way back to the present. They all come back to the present, but something seems different.",
  q: ["What do you think seemed different when the Good Guys came back to the present?",
      "If you traveled to the time of the dinosaurs, what would you want to see?",
      "What do you think might have changed in the present because they went to the past?"],
  h: ["굿 가이즈가 현재로 돌아왔을 때 무엇이 달라 보였을 것 같나요?",
      "공룡이 살던 시대로 시간여행을 간다면 무엇을 보고 싶나요?",
      "그들이 과거로 갔기 때문에 현재에 무엇이 바뀌었을 것 같나요?"] };
ACT["S2967"] = { s: "The Good Guys Club tries to save the citizens from alien invasion, but their superpowers don't seem to be effective. Agent Fox introduces them to the International League of Heroes and starts their training. On the other hand, Milton comes up with a brilliant plan. But something unexpected happens.",
  q: ["What kind of brilliant plan do you think Milton came up with?",
      "Have you ever trained hard to get better at something, like the Good Guys did?",
      "What unexpected thing do you imagine happened to Milton's plan?"],
  h: ["밀턴은 어떤 기발한 계획을 생각해 냈을 것 같나요?",
      "굿 가이즈처럼 무언가를 더 잘하려고 열심히 훈련해 본 적이 있나요?",
      "밀턴의 계획에 어떤 예상치 못한 일이 일어났을 것 같나요?"] };
ACT["S2968"] = { s: "Wolf turns into a gigantic monster after getting attacked by Marmalade. He is not the good guy he's been trying to be. The Good Guys Club and the International League of Heroes split up to two groups; one for the Operation Trantula and another one to save Wolf.",
  q: ["How do you think the other Good Guys tried to save Wolf and turn him back to normal?",
      "Have you ever tried hard to be good but something made it difficult?",
      "If your friend turned into a monster by accident, what would you do to help them?"],
  h: ["다른 굿 가이즈들은 울프를 구해서 원래대로 되돌리려고 어떻게 했을 것 같나요?",
      "착하게 지내려고 애썼지만 그게 힘들었던 적이 있나요?",
      "네 친구가 실수로 괴물이 되어 버린다면 도와주려고 무엇을 하겠나요?"] };
ACT["S2969"] = { s: "All hail Crown Prince Marmalade, surrender to his evil magnificence, and kneel before his butt-handed glory. The Bad Guys and even Badder Girls might have been knocked down, but that doesn mean they'll stay down.",
  q: ["What do you think the Bad Guys and Badder Girls did to get back up after being knocked down?",
      "Have you ever failed at something but tried again instead of giving up?",
      "What would you say to encourage the Bad Guys to keep trying?"],
  h: ["배드 가이즈와 배더 걸즈는 쓰러진 뒤 다시 일어나려고 무엇을 했을 것 같나요?",
      "무언가에 실패했지만 포기하지 않고 다시 도전해 본 적이 있나요?",
      "배드 가이즈에게 힘내라고 한다면 너는 뭐라고 말해 주고 싶나요?"] };
ACT["S2970"] = { s: "The Bad Guys have saved the world from evil and now it's time to party, but Mr. Snake doesn't feel like partying. He would rather mess with things.",
  q: ["Why do you think Mr. Snake didn't feel like celebrating with the others?",
      "Have you ever felt like not celebrating when everyone else wanted to?",
      "If your friend didn't want to join a party, what would you do to include them?"],
  h: ["스네이크는 왜 다른 친구들과 함께 축하하고 싶지 않았을 것 같나요?",
      "다른 사람들은 축하하고 싶어 했는데 너는 그러고 싶지 않았던 적이 있나요?",
      "네 친구가 파티에 끼고 싶어하지 않는다면 함께하게 하려고 너는 무엇을 하겠나요?"] };
ACT["S2971"] = { s: "Snake's terrible powers are revealed, while Agent Fox suddenly has a whole lot more backstory than expected.",
  q: ["What kind of terrible powers do you think Snake turned out to have?",
      "Have you ever found out a surprising secret about a friend?",
      "What backstory would you imagine for Agent Fox?"],
  h: ["스네이크에게는 어떤 무시무시한 힘이 있었을 것 같나요?",
      "친구에 대해 놀라운 비밀을 알게 된 적이 있나요?",
      "에이전트 폭스에게는 어떤 지난 이야기가 있었을 것 같나요?"] };
ACT["S2972"] = { s: "The Bad Guys have entered a whole new world. Literally, a very nasty new universe awaits.",
  q: ["What do you think the nasty new universe looked like?",
      "Have you ever imagined visiting a completely different world?",
      "If you entered a new, scary universe, what would you bring to protect yourself?"],
  h: ["그 고약한 새로운 우주는 어떤 모습이었을 것 같나요?",
      "완전히 다른 세상에 가 보는 상상을 해 본 적이 있나요?",
      "무섭고 낯선 우주에 들어간다면 자신을 지키려고 무엇을 챙기겠나요?"] };
ACT["S2973"] = { s: "The Bad Guys are in a building that just feels bad, and Underlord Shaard is chasing after the B-Team. The multiverse is becoming worse for these Bad Guys.",
  q: ["What do you think made the building feel so bad to the Bad Guys?",
      "Have you ever been somewhere that just felt scary or wrong?",
      "If Underlord Shaard was chasing you, how would you try to escape?"],
  h: ["그 건물에서 무엇이 배드 가이즈에게 그렇게 불길하게 느껴졌을 것 같나요?",
      "왠지 무섭거나 이상하게 느껴지는 곳에 가 본 적이 있나요?",
      "언더로드 샤드가 너를 쫓아온다면 어떻게 도망치겠나요?"] };
ACT["S2974"] = { s: "Jessica's birthday is coming. Jessica hopes that her present will be a real-live potbellied pig. She can hardly wait for her party with Judy Moody and all their friends.",
  q: ["What do you think happened when Jessica opened her birthday present?",
      "Have you ever really wanted a pet as a gift?",
      "If you could get any animal as a birthday present, what animal would you want?"],
  h: ["제시카가 생일 선물을 열었을 때 무슨 일이 있었을 것 같나요?",
      "선물로 반려동물을 정말로 갖고 싶었던 적이 있나요?",
      "생일 선물로 어떤 동물이든 받을 수 있다면 어떤 동물을 갖고 싶나요?"] };
ACT["S2975"] = { s: "Rocky is perfecting the tricks for his magic show and Judy Moody offers to help. Rocky agrees. But it turns out that Judy is the most UN-spectacular assistant ever. Is Rocky’s magic good enough to mend his and Judy’s friendship?",
  q: ["What do you think Judy did that made her such a bad magic assistant?",
      "Have you ever helped a friend with something and it didn't go very well?",
      "If you were Judy's friend, how would you help fix the friendship after the magic show trouble?"],
  h: ["주디는 무엇을 해서 그렇게 형편없는 마술 조수가 되었을 것 같나요?",
      "친구를 도와주었는데 잘 안 풀렸던 적이 있나요?",
      "네가 주디의 친구라면 마술 쇼 이후 우정을 어떻게 회복시키고 싶나요?"] };
ACT["S2976"] = { s: "Amy Namey is on the hunt for a good news story. But not a lot happens in the town of Frog Neck Lake until she teams up with Judy Moody and goes in search of the Great Virginia Sea Serpent. Are Amy and Judy about to stumble upon the scoop of the century?",
  q: ["What do you think Amy and Judy found while searching for the Great Virginia Sea Serpent?",
      "Have you ever looked for something exciting or mysterious with a friend?",
      "If you were a reporter searching for a sea serpent, what would you do to find it?"],
  h: ["에이미와 주디는 거대 버지니아 바다 괴물을 찾다가 무엇을 발견했을 것 같나요?",
      "친구와 함께 신나거나 신비로운 것을 찾아본 적이 있나요?",
      "네가 바다 괴물을 찾는 기자라면 그것을 찾으려고 무엇을 하겠나요?"] };
ACT["S2977"] = { s: "Stink is camped out in the backyard with his sister, Judy. He can't wait to lay eyes on P/2015 OZ4, also known as the Sherman-Holm Comet.",
  q: ["What do you think Stink and Judy saw when they watched the comet?",
      "Have you ever stayed up late or camped outside to see something in the sky?",
      "If you camped out to watch a comet, what would you want to bring with you?"],
  h: ["스팅크와 주디가 혜성을 지켜보았을 때 무엇을 보았을 것 같나요?",
      "하늘의 무언가를 보려고 늦게까지 있거나 밖에서 캠핑해 본 적이 있나요?",
      "혜성을 보려고 캠핑한다면 무엇을 챙겨 가고 싶나요?"] };
ACT["S2978"] = { s: "When Judy and her friends are on the playground, Jessica overhears a 5th-grader saying there is no Tooth Fairy. Judy wants to prove there is Tooth Fairy.",
  q: ["How do you think Judy tried to prove that the Tooth Fairy is real?",
      "Have you ever wanted to prove something you believed in was true?",
      "What is something you believe in that you would want to prove to others?"],
  h: ["주디는 이빨 요정이 진짜라는 것을 증명하려고 어떻게 했을 것 같나요?",
      "네가 믿는 무언가가 진짜라는 것을 증명하고 싶었던 적이 있나요?",
      "네가 믿고 있는 것 중에서 다른 사람에게 증명하고 싶은 것은 무엇인가요?"] };
ACT["S2979"] = { s: "Fancy Nancy learns a valuable lesson about poison ivy after picking a bouquet of wildflowers.",
  q: ["What do you think happened to Nancy after she picked the poison ivy?",
      "Have you ever touched a plant or something and gotten hurt by it?",
      "What lesson would you want to learn about being careful with plants outside?"],
  h: ["낸시는 독이 있는 담쟁이를 만진 뒤에 무슨 일이 있었을 것 같나요?",
      "식물이나 다른 무언가를 만졌다가 다쳐 본 적이 있나요?",
      "밖에서 식물을 조심하는 것에 대해 어떤 교훈을 배우고 싶나요?"] };
ACT["S2980"] = { s: "Fancy Nancy wants something imaginative for her school project. At last, an unexpected source inspires her.",
  q: ["What kind of unexpected thing do you think gave Nancy the idea for her project?",
      "Have you ever gotten a great idea from something unexpected?",
      "If you needed an imaginative idea for a school project, where would you look for inspiration?"],
  h: ["무엇이 뜻밖에도 낸시에게 과제 아이디어를 주었을 것 같나요?",
      "뜻밖의 것에서 좋은 아이디어를 얻은 적이 있나요?",
      "학교 과제를 위해 참신한 아이디어가 필요하다면 너는 어디서 영감을 얻고 싶나요?"] };
ACT["S2981"] = { s: "Fancy Nancy learns about Earth Day and tries to participate in \"being green.\"",
  q: ["What do you think Nancy did to try to \"be green\" for Earth Day?",
      "Have you ever done something to help take care of the Earth?",
      "What is one green thing you could do for Earth Day?"],
  h: ["낸시는 지구의 날을 맞아 '친환경적으로' 살려고 무엇을 했을 것 같나요?",
      "지구를 돌보기 위해 무언가를 해 본 적이 있나요?",
      "지구의 날을 맞아 네가 할 수 있는 친환경적인 일 한 가지는 무엇인가요?"] };
ACT["S2982"] = { s: "In this story, Nancy's friend Bree gets to wear fancy glasses. Nancy wants to wear glasses and look spectacular, too.",
  q: ["What do you think Nancy did to try to get glasses like Bree's?",
      "Have you ever wanted to have something because your friend had it?",
      "If you could wear fancy glasses like Nancy wanted, what would they look like?"],
  h: ["낸시는 브리처럼 안경을 쓰려고 무엇을 했을 것 같나요?",
      "친구가 가진 것을 보고 너도 갖고 싶었던 적이 있나요?",
      "낸시처럼 멋진 안경을 쓴다면 어떤 모양의 안경일까요?"] };
ACT["S2983"] = { s: "Nancy bakes cupcakes for the bake sale at school. But she fails to pay attention and gets into trouble.",
  q: ["What kind of trouble do you think Nancy got into while baking the cupcakes?",
      "Have you ever gotten into trouble because you weren't paying attention?",
      "If you baked something for a school event, what would you be careful about?"],
  h: ["낸시는 컵케이크를 만들다가 어떤 곤란한 일을 겪었을 것 같나요?",
      "집중하지 않아서 곤란한 일을 겪은 적이 있나요?",
      "학교 행사를 위해 무언가를 굽는다면 너는 무엇을 조심하고 싶나요?"] };
ACT["S2984"] = { s: "Nancy writes a report about her great-grandpa. She decides to make things up so his life seems more exciting.",
  q: ["What do you think happened when Nancy made up exciting things about her great-grandpa?",
      "Have you ever been tempted to exaggerate a story to make it sound more exciting?",
      "Do you think it's okay for Nancy to make things up in her report? Why or why not?"],
  h: ["낸시가 증조할아버지에 대해 이야기를 꾸며냈을 때 무슨 일이 있었을 것 같나요?",
      "이야기를 더 재미있게 만들려고 과장해 본 적이 있나요?",
      "낸시가 보고서에 이야기를 꾸며 넣은 것이 괜찮다고 생각하나요, 아닌가요? 이유는 무엇인가요?"] };
ACT["S2985"] = { s: "Fancy Nancy feels guilty about her lame performance at the previous year's Field Day caused by her slow running in the relay race. Now, she faces another relay race with a mean classmate.",
  q: ["What do you think Nancy did differently in the relay race this time?",
      "Have you ever gotten a second chance to do better at something you felt bad about?",
      "If you had a mean teammate in a race, how would you handle it?"],
  h: ["낸시는 이번 계주에서 무엇을 다르게 했을 것 같나요?",
      "아쉬웠던 일에 대해 다시 잘해 볼 기회를 얻은 적이 있나요?",
      "심술궂은 팀원과 함께 경주해야 한다면 너는 어떻게 하겠나요?"] };
ACT["S2986"] = { s: "Fancy Nancy is thinking about how to make her hair look good for her school pictures. She gets a great idea and quickly grabs a pair of scissors.",
  q: ["What do you think happened after Nancy grabbed the scissors?",
      "Have you ever tried to change your hair or your look before something important?",
      "If you were about to take school pictures, how would you want your hair to look?"],
  h: ["낸시가 가위를 집은 뒤에 무슨 일이 있었을 것 같나요?",
      "중요한 일을 앞두고 머리 모양이나 외모를 바꿔 본 적이 있나요?",
      "학교 사진을 찍기 전이라면 너는 머리를 어떻게 하고 싶나요?"] };
ACT["S2987"] = { s: "Fancy Nancy is on the verge of losing her first tooth. However, she can only earn a special necklace from the school nurse if she manages to prevent her tooth from falling out until she gets to school.",
  q: ["What do you think Nancy did to keep her tooth from falling out before school?",
      "Have you ever had a loose tooth? What happened to it?",
      "If you had a loose tooth, would you want it to fall out quickly or stay in as long as possible? Why?"],
  h: ["낸시는 학교에 도착할 때까지 이가 빠지지 않게 하려고 무엇을 했을 것 같나요?",
      "이가 흔들려 본 적이 있나요? 그때 어떻게 되었나요?",
      "이가 흔들린다면 빨리 빠지길 바라나요, 아니면 오래 붙어 있길 바라나요? 이유는 무엇인가요?"] };
ACT["S2988"] = { s: "Fancy Nancy finds a way to make her classmates happy by organizing a fun party for the whole class.",
  q: ["What kind of fun things do you think Nancy planned for the class party?",
      "Have you ever helped organize a party or fun event for a group?",
      "If you organized a party for your class, what would you plan?"],
  h: ["낸시는 학급 파티를 위해 어떤 재미있는 것들을 계획했을 것 같나요?",
      "여러 사람을 위한 파티나 재미있는 행사를 준비해 본 적이 있나요?",
      "네가 반 친구들을 위한 파티를 연다면 무엇을 계획하고 싶나요?"] };
ACT["S2989"] = { s: "Fancy Nancy's mother tells her that she has too many tutus in her closet, so she thinks about taking some to school for Swap-and-shop Day.",
  q: ["What do you think Nancy chose to take to Swap-and-shop Day?",
      "Have you ever traded or swapped something you had for something new?",
      "If you had a Swap-and-shop Day at your school, what would you bring to trade?"],
  h: ["낸시는 물물교환의 날에 무엇을 가져가기로 골랐을 것 같나요?",
      "네가 가진 물건을 다른 것과 바꿔 본 적이 있나요?",
      "학교에 물물교환의 날이 있다면 너는 무엇을 가져가서 바꾸고 싶나요?"] };
ACT["S2990"] = { s: "Fancy Nancy is going on a field trip with her class to pick apples and wants to find the best Gala apple to give to her dad.",
  q: ["What do you think made Nancy's chosen apple the best one for her dad?",
      "Have you ever picked fruit or vegetables on a field trip or farm visit?",
      "If you picked the best apple for someone you love, how would you choose it?"],
  h: ["낸시가 고른 사과를 아빠에게 주기에 가장 좋은 사과로 만든 건 무엇이었을 것 같나요?",
      "현장 학습이나 농장에서 과일이나 채소를 따 본 적이 있나요?",
      "사랑하는 사람을 위해 가장 좋은 사과를 고른다면 너는 어떻게 고르겠나요?"] };
ACT["S2991"] = { s: "When a friend brings a special clover with four leaves to show, Fancy Nancy becomes very interested in luck, both good and bad.",
  q: ["What kind of lucky or unlucky things do you think happened to Nancy after seeing the four-leaf clover?",
      "Have you ever found something that people say brings good luck?",
      "Do you believe in good luck charms like a four-leaf clover? Why or why not?"],
  h: ["네잎클로버를 본 뒤 낸시에게 어떤 행운이나 불운이 일어났을 것 같나요?",
      "사람들이 행운을 가져다준다고 말하는 것을 찾아본 적이 있나요?",
      "네잎클로버 같은 행운의 부적을 믿나요, 안 믿나요? 이유는 무엇인가요?"] };
ACT["S2992"] = { s: "Fancy Nancy is having a great time looking at all the amazing sea creatures at the aquarium. But when she reaches the exhibit with the jellyfish, she gets scared.",
  q: ["What do you think scared Nancy about the jellyfish exhibit?",
      "Have you ever been scared of a sea creature or an animal at the zoo or aquarium?",
      "What would you say to Nancy to help her feel less scared of the jellyfish?"],
  h: ["낸시는 해파리 전시관에서 무엇 때문에 무서워졌을 것 같나요?",
      "동물원이나 수족관에서 바다 생물이나 동물이 무서웠던 적이 있나요?",
      "낸시가 해파리를 덜 무서워하도록 너는 무슨 말을 해 주고 싶나요?"] };
ACT["S2993"] = { s: "Fancy Nancy and her friends are getting ready for a surprise party. They work together to make yummy treats and decorate their classroom for the party.",
  q: ["What kind of treats and decorations do you think Nancy and her friends made?",
      "Have you ever worked with friends to prepare a surprise for someone?",
      "If you decorated a classroom for a surprise party, what would you want it to look like?"],
  h: ["낸시와 친구들은 어떤 간식과 장식을 만들었을 것 같나요?",
      "친구들과 함께 누군가를 위한 깜짝 파티를 준비해 본 적이 있나요?",
      "네가 깜짝 파티를 위해 교실을 꾸민다면 어떤 모습으로 만들고 싶나요?"] };
ACT["S2994"] = { s: "Nancy really enjoys playing with her puppy, Frenchy, during the summer. However, when Frenchy causes too many problems, the family decides it's time for Frenchy to go to puppy school.",
  q: ["What kind of problems do you think Frenchy caused that made the family send him to puppy school?",
      "Have you ever had a pet that caused trouble at home?",
      "If you had a puppy that misbehaved, what would you teach it first?"],
  h: ["프렌치가 어떤 문제를 일으켜서 가족이 강아지 학교에 보내기로 했을 것 같나요?",
      "집에서 말썽을 부리는 반려동물을 키워 본 적이 있나요?",
      "말썽꾸러기 강아지를 키운다면 가장 먼저 무엇을 가르치고 싶나요?"] };
ACT["S2995"] = { s: "Violet is Nancy's favorite reading buddy at school, and they both enjoy reading together very much. But when they can't meet for a few Mondays in a row, Nancy feels sad.",
  q: ["What do you think Nancy did while she couldn't meet with Violet for reading?",
      "Have you ever missed doing something fun with a friend because you couldn't meet?",
      "If you couldn't see your reading buddy for a while, what would you do to feel less sad?"],
  h: ["바이올렛과 만나지 못하는 동안 낸시는 무엇을 했을 것 같나요?",
      "친구와 만나지 못해서 함께하던 재미있는 일을 그리워한 적이 있나요?",
      "독서 친구를 한동안 못 만난다면 덜 슬프도록 너는 무엇을 하겠나요?"] };
ACT["S2996"] = { s: "When Bree gets sick and can't go with her classmates to see a bubble show, Nancy and her friends decide to perform their own bubble show for Bree.",
  q: ["What kind of bubble show do you think Nancy and her friends put on for Bree?",
      "Have you ever done something special for a friend who was sick?",
      "If your friend was sick and missed something fun, what would you do for them?"],
  h: ["낸시와 친구들은 브리를 위해 어떤 비눗방울 쇼를 보여 주었을 것 같나요?",
      "아픈 친구를 위해 특별한 무언가를 해 준 적이 있나요?",
      "네 친구가 아파서 재미있는 것을 놓쳤다면 너는 무엇을 해 주고 싶나요?"] };
ACT["S2997"] = { s: "It is Backward Day at school. Nancy's class celebrates the day with brilliant ideas.",
  q: ["What kind of brilliant, backward ideas do you think Nancy's class came up with?",
      "Have you ever done something the opposite way, just for fun?",
      "If your school had a Backward Day, what would you do backward?"],
  h: ["낸시네 반은 거꾸로의 날을 맞아 어떤 기발한 아이디어를 냈을 것 같나요?",
      "재미로 무언가를 거꾸로 해 본 적이 있나요?",
      "학교에 거꾸로의 날이 있다면 너는 무엇을 거꾸로 해 보고 싶나요?"] };
ACT["S2998"] = { s: "Inspired by the folk song \"There Was an Old Lady Who Swallowed a Fly\", this story describes what happens to a cold lady who swallowed some snow.",
  q: ["What do you think happened after the cold lady swallowed the snow?",
      "Have you ever played in the snow or gotten very cold outside?",
      "If a story lady swallowed something silly to cure a cold, what would you have her swallow?"],
  h: ["감기에 걸린 아주머니가 눈을 삼킨 뒤에 무슨 일이 있었을 것 같나요?",
      "눈밭에서 놀거나 밖에서 아주 추웠던 적이 있나요?",
      "이야기 속 아주머니가 감기를 고치려고 엉뚱한 것을 삼킨다면 너는 무엇을 삼키게 하고 싶나요?"] };
ACT["S2999"] = { s: "This story describes an old lady who swallows many different things, one after another, starting with a bat.",
  q: ["What do you think the old lady swallowed after the bat?",
      "Have you ever heard a silly story about someone eating strange things one after another?",
      "If you made up your own version of this story, what would the old lady swallow first?"],
  h: ["박쥐를 삼킨 뒤에 할머니는 무엇을 삼켰을 것 같나요?",
      "누군가 이상한 것들을 차례로 먹는 우스운 이야기를 들어 본 적이 있나요?",
      "네가 이 이야기를 새로 만든다면 할머니가 처음에 무엇을 삼키게 하고 싶나요?"] };
