// 간이 학습 질문 — Book No. S30 묶음. 사람이 아니라 AI 가 한 번 쓰고 굳힌 파일이다.
window.ACT = window.ACT || {};
var ACT = window.ACT;
ACT["S3001"] = { s: "Dink and his detective friends hope to receive a big reward by finding the person whose video recorder picked up a picture of the local bank robber.",
  q: ["What did the video recorder capture that gave Dink and his friends a clue about the bank robber?",
      "Have you or your family ever used a video recording to find out what happened somewhere?",
      "If you found the reward money, what would you want to do with it?"],
  h: ["비디오 녹화기에 무엇이 찍혀서 딩크와 친구들에게 은행 강도에 대한 단서가 되었나요?",
      "너는 또는 가족이 어떤 일이 있었는지 알아보려고 비디오 녹화를 본 적이 있나요?",
      "네가 그 보상금을 받는다면 무엇을 하고 싶나요?"] };
ACT["S3002"] = { s: "While visiting Wallis' castle, Dink and his friends hear strange sounds behind the walls. Does the castle have a hidden dungeon? The kids investigate strange noises that lead them to a dangerous secret.",
  q: ["What strange sounds did Dink and his friends hear behind the walls of Wallis' castle?",
      "Have you ever heard a strange sound in an old or unfamiliar building?",
      "What do you think could be hiding in a secret dungeon like the one in the story?"],
  h: ["딩크와 친구들은 월리스의 성벽 뒤에서 어떤 이상한 소리를 들었나요?",
      "너는 낡거나 낯선 건물에서 이상한 소리를 들어본 적이 있나요?",
      "이야기 속 숨겨진 지하 감옥 같은 곳에는 무엇이 숨어 있을 것 같나요?"] };
ACT["S3003"] = { s: "Dink has been getting strange mail all week long. The letters inside are for someone named Doris. Dink and his friends find the mysterious truth behind the envelopes incorrectly delivered to his house.",
  q: ["Who were the strange letters in Dink's mailbox actually meant for?",
      "Have you ever received mail or a package that wasn't meant for you?",
      "What do you think Dink felt like as he tried to figure out the mystery of the envelopes?"],
  h: ["딩크의 우편함에 온 이상한 편지들은 사실 누구에게 온 것이었나요?",
      "너에게 온 것이 아닌 우편물이나 소포를 받아본 적이 있나요?",
      "딩크가 봉투의 수수께끼를 풀려고 할 때 어떤 기분이었을 것 같나요?"] };
ACT["S3004"] = { s: "When Ruth Rose and her friends are vacationing in Florida, they discover that her grandmother is about to invest in a project to recover sunken treasure, They come across evidence that the entire plan may be a fraud.",
  q: ["What was Ruth Rose's grandmother about to invest in while vacationing in Florida?",
      "Have you or your family ever been careful about a plan that seemed too good to be true?",
      "What clues do you think helped the kids realize the treasure plan might be a fraud?"],
  h: ["루스 로즈의 할머니는 플로리다에서 휴가를 보내며 무엇에 투자하려 했나요?",
      "너나 가족이 너무 좋아 보여서 조심했던 계획이 있었나요?",
      "아이들이 그 보물 계획이 사기일지도 모른다고 알아차리는 데 어떤 단서가 도움이 되었을 것 같나요?"] };
ACT["S3005"] = { s: "Strange sounds and even stranger sights are terrifying guests at the Shangri-la Hotel. More and more people are being scared away. Dink and his friends investigate the mystery.",
  q: ["What was happening at the Shangri-la Hotel that scared the guests away?",
      "Have you ever stayed at a hotel or slept somewhere new that felt a little scary at night?",
      "If you were investigating the hotel like Dink, what would you look for first?"],
  h: ["샹그릴라 호텔에서 무슨 일이 있었길래 손님들이 겁먹고 떠났나요?",
      "너는 호텔에 묵거나 낯선 곳에서 자면서 밤에 조금 무서웠던 적이 있나요?",
      "네가 딩크처럼 호텔을 조사한다면 가장 먼저 무엇을 살펴보고 싶나요?"] };
ACT["S3006"] = { s: "While Dink, Josh, and Ruth Rose are picnicking on Squaw Island, they find a hundred-dollar bill. And when they return to explore further, they find an entire cave full of money.",
  q: ["What did Dink, Josh, and Ruth Rose find when they went back to explore Squaw Island further?",
      "Have you ever found money or something valuable outside and wondered where it came from?",
      "What would you do if you found a whole cave full of money like the kids did?"],
  h: ["딩크, 조시, 루스 로즈가 스쿼 섬을 더 탐험하러 돌아갔을 때 무엇을 발견했나요?",
      "너는 밖에서 돈이나 값진 것을 주워서 어디서 왔을지 궁금했던 적이 있나요?",
      "아이들처럼 돈이 가득한 동굴을 발견한다면 너는 어떻게 할 것 같나요?"] };
ACT["S3007"] = { s: "Dink, Josh, and Ruth Rose visit New York City. They use their detective skills to locate a giant emerald missing from a statue delivered to Uncle Warren's museum in New York City.",
  q: ["What was missing from the statue delivered to Uncle Warren's museum?",
      "Have you ever visited a museum in a big city? What did you see there?",
      "What detective skills do you think would be most useful for finding a missing jewel?"],
  h: ["워런 삼촌의 박물관에 배달된 동상에서 무엇이 사라졌나요?",
      "너는 큰 도시의 박물관에 가 본 적이 있나요? 그곳에서 무엇을 보았나요?",
      "사라진 보석을 찾으려면 어떤 탐정 기술이 가장 도움이 될 것 같나요?"] };
ACT["S3008"] = { s: "Someone has kidnapped the king and queen of Socotra. For safety's sake, their son is staying with Dink until they are safe. But then the prince is kidnapped, too. Let's see how Dink and his friends unmask the royals' enemies before it's too late.",
  q: ["Why was the king and queen's son staying with Dink at the beginning of the story?",
      "Have you ever taken care of or looked out for a friend who needed help?",
      "What do you think Dink and his friends need to do to find the royal family's enemies?"],
  h: ["이야기 초반에 왕과 왕비의 아들은 왜 딩크와 함께 지내고 있었나요?",
      "너는 도움이 필요한 친구를 돌보거나 챙겨준 적이 있나요?",
      "딩크와 친구들이 왕실의 적을 찾아내려면 무엇을 해야 할 것 같나요?"] };
ACT["S3009"] = { s: "It's Mummy Monday at the museum, and the kids get to see a child mummy in an actual tomb. But someone robs the tomb and steals the mummy. Can the three friends solve the mystery?",
  q: ["The child mummy's tomb is robbed on Mummy Monday. Imagine you are one of the kids at the museum that day — what would you have noticed first, and how would you and your friends start investigating who took the mummy? Write a few sentences about your plan.",
      "Think about a time you visited a museum or saw something rare and special on display. What was it, and why did it feel important to protect or take care of?",
      "Dink and his friends solve mysteries as a team. Do you think it is easier to solve a mystery alone or with friends? Explain your thinking with your own reasons."],
  h: ["미라의 월요일에 아기 미라가 있는 무덤이 도둑맞아요. 네가 그날 박물관에 있던 아이 중 한 명이라고 상상해 보세요. 무엇을 가장 먼저 알아챘을지, 그리고 친구들과 함께 누가 미라를 가져갔는지 어떻게 조사를 시작할지 몇 문장으로 적어 보세요.",
      "박물관에 가거나 귀하고 특별한 전시물을 본 적을 떠올려 보세요. 그것은 무엇이었고, 왜 소중히 지켜야 한다고 느꼈나요?",
      "딩크와 친구들은 팀을 이루어 수수께끼를 풀어요. 수수께끼를 혼자 푸는 것과 친구들과 함께 푸는 것 중 어느 쪽이 더 쉬울 것 같나요? 그렇게 생각하는 이유와 함께 적어 보세요."] };
ACT["S3010"] = { s: "Dink, Josh, and Ruth Rose are spending a week at a dude ranch. Everything is normal in a cowboy kind of way until Josh finds a huge gold nugget. they find themselves with another mystery to solve.",
  q: ["What did Josh find at the dude ranch that started a new mystery?",
      "Have you ever visited a ranch or farm? What animals or things did you see there?",
      "What do you think Dink and his friends should do first after finding the gold nugget?"],
  h: ["조시가 목장에서 발견한 것이 무엇이었길래 새로운 수수께끼가 시작되었나요?",
      "너는 목장이나 농장에 가 본 적이 있나요? 그곳에서 어떤 동물이나 것들을 보았나요?",
      "금덩이를 발견한 뒤 딩크와 친구들이 가장 먼저 무엇을 해야 한다고 생각하나요?"] };
ACT["S3011"] = { s: "Dink, Josh, and Ruth Rose are visiting Dink's uncle in New York City when several paintings are stolen from his apartment building. They help uncover who is responsible for stealing a very valuable painting.",
  q: ["What happened to the paintings in Dink's uncle's apartment building?",
      "Have you ever seen a painting or artwork that you thought was very valuable?",
      "What clues would you look for if you wanted to find out who stole a valuable painting?"],
  h: ["딩크 삼촌의 아파트 건물에서 그림에 무슨 일이 일어났나요?",
      "너는 아주 값지다고 생각한 그림이나 작품을 본 적이 있나요?",
      "값진 그림을 훔친 사람이 누구인지 알아내려면 어떤 단서를 찾아야 할 것 같나요?"] };
ACT["S3012"] = { s: "When the town raises enough cash to build a special duck bridge so that the ducks cross River Road, the money is stolen. Josh and his friends try to find the culprit.",
  q: ["What was the town's money supposed to be used for before it was stolen?",
      "Have you or your class ever raised money for something important?",
      "Who do you think might want to steal money meant for a duck bridge, and why?"],
  h: ["도둑맞기 전에 그 마을 돈은 무엇을 위해 쓰일 예정이었나요?",
      "너나 너희 반이 중요한 일을 위해 돈을 모아본 적이 있나요?",
      "오리 다리를 위한 돈을 훔치고 싶어 할 사람은 누구이고, 왜 그럴 것 같나요?"] };
ACT["S3013"] = { s: "Dink, Josh, and Ruth Rose are excited to see Uncle Warren's new racehorse. But the night before the big race, the horse disappears. Then he shows up the next day, just in time to lose the race. Dink and his friends investigate the mystery.",
  q: ["What happened to Uncle Warren's racehorse the night before the big race?",
      "Have you ever watched or been to a horse race or another kind of race?",
      "Why do you think someone would want to make a racehorse disappear and then lose the race?"],
  h: ["큰 경주가 열리기 전날 밤 워런 삼촌의 경주마에게 무슨 일이 있었나요?",
      "너는 경마나 다른 종류의 경주를 보거나 가 본 적이 있나요?",
      "누군가 경주마를 사라지게 했다가 경주에서 지게 만들려는 이유는 무엇일 것 같나요?"] };
ACT["S3014"] = { s: "The kids' old friend, Jud Wheat, is in town. He's raising funds for a dinosaur museum by taking a nearly life-size Tyrannosaurus rex model on tour. But after the show in Green Lawn, all Jud's money disappears. Dink and his friends investigate the theft of a great deal of money.",
  q: ["What was Jud Wheat doing with the life-size T. rex model to raise money for the museum?",
      "Have you ever seen a life-size dinosaur model at a museum or a show?",
      "What steps would you take to investigate the theft of Jud's money?"],
  h: ["저드 휘트는 박물관을 위한 기금을 모으려고 실물 크기 티라노사우루스 모형으로 무엇을 했나요?",
      "너는 박물관이나 전시회에서 실물 크기 공룡 모형을 본 적이 있나요?",
      "저드의 돈이 도둑맞은 사건을 조사하려면 너는 어떤 순서로 조사하고 싶나요?"] };
ACT["S3015"] = { s: "While the whole town of Green Lawn is watching the women take on the men in a charity baseball game, Mr. Pocket's prized baseball collection is stolen. The police suspect the umpire at the baseball game fund-raiser. Dink, Josh, and Ruth Rose try to prove his innocence.",
  q: ["What was stolen during the charity baseball game in Green Lawn?",
      "Have you ever watched or played in a charity game or event to help raise money?",
      "Why do you think the police suspected the umpire, and how might Dink and his friends prove him innocent?"],
  h: ["그린 론의 자선 야구 경기 동안 무엇이 도둑맞았나요?",
      "너는 돈을 모으기 위한 자선 경기나 행사를 보거나 참가해 본 적이 있나요?",
      "경찰은 왜 심판을 의심했고, 딩크와 친구들은 그가 무죄임을 어떻게 증명할 수 있을 것 같나요?"] };
ACT["S3016"] = { s: "When Dink, Josh, and Ruth Rose follow a mysterious pale and dark-haired stranger into Ellie's Diner, he suddenly vanishes. Then they see a cut on Ellie's neck. The kids investigate the mysterious man in black who Josh believes is a vampire.",
  q: ["What did Dink, Josh, and Ruth Rose notice about the mysterious stranger and about Ellie?",
      "Have you ever seen someone act mysteriously or noticed something odd about a stranger?",
      "Do you think the mysterious man is really a vampire, or is there another explanation? Why?"],
  h: ["딩크, 조시, 루스 로즈는 수상한 낯선 사람과 엘리에게서 무엇을 알아챘나요?",
      "너는 누군가 수상하게 행동하거나 낯선 사람에게서 이상한 점을 알아챈 적이 있나요?",
      "그 수상한 남자가 정말 뱀파이어라고 생각하나요, 아니면 다른 이유가 있을까요? 이유를 적어 보세요."] };
ACT["S3017"] = { s: "Josh, Dink, and Ruth Rose visit their friend, Wallis and her adopted daughter on Mount Desert Island in Maine. They spot a white mother wolf and her babies on a cliff. But soon the pups are stolen. The kids investigate why three white wolf cubs were stolen, and by whom.",
  q: ["What did Josh, Dink, and Ruth Rose spot on a cliff while visiting Mount Desert Island?",
      "Have you ever seen wild animals and their babies together in nature?",
      "Why do you think someone would steal the white wolf pups, and what would you do to protect them?"],
  h: ["조시, 딩크, 루스 로즈는 마운트 데저트 섬을 방문했을 때 절벽에서 무엇을 발견했나요?",
      "너는 자연에서 야생 동물과 그 새끼들을 함께 본 적이 있나요?",
      "누군가 하얀 늑대 새끼들을 훔친 이유는 무엇일 것 같고, 너라면 그들을 어떻게 지켜주고 싶나요?"] };
ACT["S3018"] = { s: "Dink, Josh, and Ruth Rose are having an excellent time at a concert. But during intermission, Dink injures his arm and the singer's diamond pendant is stolen. The kids are soon on the trail of the thief.",
  q: ["What two things happened to Dink during the intermission of the concert?",
      "Have you ever been to a concert or a big show? What do you remember about it?",
      "How do you think the kids will figure out who stole the singer's diamond pendant?"],
  h: ["콘서트 휴식 시간 동안 딩크에게 두 가지 일이 일어났어요. 그것은 무엇이었나요?",
      "너는 콘서트나 큰 공연에 가 본 적이 있나요? 무엇이 기억에 남나요?",
      "아이들은 가수의 다이아몬드 목걸이를 훔친 사람을 어떻게 찾아낼 것 같나요?"] };
ACT["S3019"] = { s: "The people of a Louisiana swampland village tell stories of voodoo and a giant zombie with silver hair who has been digging up graves in the cemetery. But Dink, Josh, and Ruth Rose begin to suspect that the supernatural may not be the cause of the eerie occurrences.",
  q: ["What stories did the people of the Louisiana swampland village tell about the zombie?",
      "Have you ever heard a scary local story or legend where you live?",
      "Do you think the eerie events have a supernatural cause or a real-world explanation? Why?"],
  h: ["루이지애나 늪지대 마을 사람들은 좀비에 대해 어떤 이야기를 했나요?",
      "너는 네가 사는 곳에서 무서운 이야기나 전설을 들어본 적이 있나요?",
      "그 으스스한 일들이 초자연적인 이유 때문이라고 생각하나요, 아니면 현실적인 이유가 있을까요? 이유를 적어 보세요."] };
ACT["S3020"] = { s: "This book presents the physical characteristics, adaptations, and behavior of various animals that live in the Arctic, including the polar bear, arctic fox, and arctic hare.",
  q: ["Which Arctic animals does this book describe, and how have they adapted to their environment?",
      "Have you ever learned about an animal that lives in a very cold place?",
      "Which Arctic animal from the book would you most like to learn more about, and why?"],
  h: ["이 책은 어떤 북극 동물을 설명하며, 그 동물들은 환경에 어떻게 적응했나요?",
      "너는 아주 추운 곳에 사는 동물에 대해 배워본 적이 있나요?",
      "책 속 북극 동물 중 어떤 동물에 대해 더 알고 싶고, 그 이유는 무엇인가요?"] };
ACT["S3021"] = { s: "This book gives a comprehensive introduction to Egyptian gods and goddesses with simple text and illustrations. There is also tons of neat information about pyramids, mummies, and the afterlife.",
  q: ["What information does this book give about pyramids, mummies, and the afterlife?",
      "Have you ever learned about ancient Egypt in school or from a book?",
      "Which Egyptian god or goddess would you like to learn more about, and why?"],
  h: ["이 책은 피라미드, 미라, 사후 세계에 대해 어떤 정보를 알려주나요?",
      "너는 학교나 책에서 고대 이집트에 대해 배워본 적이 있나요?",
      "이집트 신이나 여신 중 누구에 대해 더 알고 싶고, 그 이유는 무엇인가요?"] };
ACT["S3022"] = { s: "A boring family reunion provides data for charting graphs for Gary Graff's homework assignment. It gives Gary a chance to not only learn about graphs, but about his family as well.",
  q: ["What did Gary Graff use the family reunion to make for his homework?",
      "Have you ever made a graph or chart for school or at home?",
      "If you made a graph about your own family, what would you want to count?"],
  h: ["게리 그래프는 가족 모임을 이용해 숙제로 무엇을 만들었나요?",
      "너는 학교나 집에서 그래프나 표를 만들어본 적이 있나요?",
      "네 가족에 대한 그래프를 만든다면, 무엇을 세어 보고 싶나요?"] };
ACT["S3023"] = { s: "William, a seven-year-old page in England in 1415, dreams of becoming a squire, and he hopes someday to be dubbed a knight as well.",
  q: ["What does William dream of becoming someday, after being a page?",
      "Have you ever dreamed of growing up to do a certain job or role?",
      "What do you think a page has to learn before becoming a squire and then a knight?"],
  h: ["윌리엄은 시동(페이지)을 거친 뒤 언젠가 무엇이 되기를 꿈꾸나요?",
      "너는 커서 어떤 일이나 역할을 하고 싶다고 꿈꿔본 적이 있나요?",
      "시동이 종자를 거쳐 기사가 되기 전에 무엇을 배워야 할 것 같나요?"] };
ACT["S3024"] = { s: "This book describes the Egyptian pharaohs' beliefs about life after death, the technique of mummification, and pyramids as burial places. This book has a lot of amazing mummy facts.",
  q: ["What did the Egyptian pharaohs believe about life after death?",
      "Have you ever learned an amazing fact about mummies or ancient Egypt before?",
      "What is the most surprising mummy fact you learned from this book, and why does it surprise you?"],
  h: ["이집트 파라오들은 죽음 이후의 삶에 대해 무엇을 믿었나요?",
      "너는 전에 미라나 고대 이집트에 대한 놀라운 사실을 배워본 적이 있나요?",
      "이 책에서 배운 미라에 대한 사실 중 가장 놀라운 것은 무엇이고, 왜 놀라운가요?"] };
ACT["S3025"] = { s: "This is a book with illustrated collection of humorous poems. It is about all kinds of pets and their adventures.",
  q: ["What kinds of pets and adventures are described in these funny poems?",
      "Have you or someone you know had a pet that got into a funny adventure?",
      "If you wrote a funny poem about a pet, what pet and adventure would you write about?"],
  h: ["이 재미있는 시들에는 어떤 반려동물과 모험이 나오나요?",
      "너나 네가 아는 사람의 반려동물이 재미있는 모험을 한 적이 있나요?",
      "네가 반려동물에 대한 재미있는 시를 쓴다면, 어떤 반려동물과 어떤 모험을 쓰고 싶나요?"] };
ACT["S3026"] = { s: "This book is a great introduction to the life and behavior of all kinds of cats. Topics discussed include hunting techniques, sleeping habits, color patterns, and the importance of preserving the cats' habitats.",
  q: ["What hunting techniques and habits of cats does this book talk about?",
      "Have you ever watched a cat hunt, sleep, or play?",
      "Why do you think it's important to preserve cats' habitats?"],
  h: ["이 책은 고양이의 어떤 사냥 기술과 습관에 대해 이야기하나요?",
      "너는 고양이가 사냥하거나, 자거나, 노는 모습을 본 적이 있나요?",
      "고양이의 서식지를 보존하는 것이 왜 중요하다고 생각하나요?"] };
ACT["S3027"] = { s: "This book features some of the most disgusting, far-out bugs on the planet. You will learn how a scorpion uses its poison, discover how the jumping spider hunts, and much more.",
  q: ["How does a scorpion use its poison, according to this book?",
      "Have you ever seen a bug that you thought was disgusting or strange?",
      "Which creepy, crawly critter from the book would you least want to meet, and why?"],
  h: ["이 책에 따르면 전갈은 독을 어떻게 사용하나요?",
      "너는 징그럽거나 이상하다고 생각한 벌레를 본 적이 있나요?",
      "책 속 오싹하고 기어다니는 생물 중 가장 만나고 싶지 않은 것은 무엇이고, 그 이유는 무엇인가요?"] };
ACT["S3028"] = { s: "On March 27, 1964, a massive earthquake ripped through Anchorage, Alaska, destroying the community. This book explains all about how and why this terrifying natural phenomenon occurs.",
  q: ["What happened in Anchorage, Alaska on March 27, 1964?",
      "Have you ever felt the ground shake or heard about an earthquake?",
      "Why do you think earthquakes happen, based on what this book explains?"],
  h: ["1964년 3월 27일 알래스카 앵커리지에서 무슨 일이 있었나요?",
      "너는 땅이 흔들리는 것을 느끼거나 지진에 대해 들어본 적이 있나요?",
      "이 책에서 설명하는 내용을 바탕으로, 지진은 왜 일어난다고 생각하나요?"] };
ACT["S3029"] = { s: "Did you know that there is a type of goat that faints whenever it feels threatened? Find out more about these and other creatures with bizarre behaviors in this book.",
  q: ["What does the goat in this book do whenever it feels threatened?",
      "Have you ever seen or heard about an animal with a strange or funny behavior?",
      "Which bizarre animal behavior from this book surprised you the most, and why?"],
  h: ["이 책 속 염소는 위협을 느낄 때마다 어떻게 하나요?",
      "너는 이상하거나 재미있는 행동을 하는 동물을 보거나 들어본 적이 있나요?",
      "이 책에서 가장 놀라웠던 기이한 동물 행동은 무엇이고, 그 이유는 무엇인가요?"] };
ACT["S3030"] = { s: "From creatures that glow in the deep sea to ones that look like they have two heads, this book shows us some of the planet's most far-out and freaky animals.",
  q: ["What kinds of far-out and freaky animals does this book show, from the deep sea to two-headed creatures?",
      "Have you ever seen a picture or video of a strange-looking animal that surprised you?",
      "Which freaky animal from this book would you most like to see in real life, and why?"],
  h: ["이 책은 심해 생물부터 머리가 둘인 생물까지 어떤 기이하고 특이한 동물들을 보여주나요?",
      "너는 놀라운 모습의 이상한 동물 사진이나 영상을 본 적이 있나요?",
      "이 책 속 기이한 동물 중 실제로 보고 싶은 것은 무엇이고, 그 이유는 무엇인가요?"] };
ACT["S3031"] = { s: "It's Judy's first day of a new school year, but she is in a bad mood. But when she gets an assignment to create a collage all about herself, she is delighted that she has the chance to express herself. Book #1",
  q: ["What assignment does Judy get that ends up making her feel delighted?",
      "Have you ever started a new school year in a bad mood that got better later?",
      "If you made a collage all about yourself, what would you put on it?"],
  h: ["주디는 어떤 과제를 받았고, 그것이 왜 그녀를 기쁘게 만들었나요?",
      "너는 새 학년이 시작될 때 기분이 안 좋았다가 나중에 나아진 적이 있나요?",
      "네가 자신에 대한 콜라주를 만든다면, 무엇을 붙이고 싶나요?"] };
ACT["S3032"] = { s: "What do baby gorillas like to do in the jungle? They swing in the trees, and play tag in the bushes. They even get piggyback rides from their mothers. You can find out information on how gorillas act, live, and travel.",
  q: ["What fun things do baby gorillas do in the jungle, according to this book?",
      "Have you ever gotten a piggyback ride, like the baby gorillas do?",
      "What else would you like to find out about how gorillas live and travel?"],
  h: ["이 책에 따르면 아기 고릴라들은 정글에서 어떤 재미있는 일을 하나요?",
      "너는 아기 고릴라들처럼 업혀서 이동해 본 적이 있나요?",
      "고릴라가 어떻게 살고 이동하는지에 대해 더 알고 싶은 것은 무엇인가요?"] };
ACT["S3033"] = { s: "Where does the word 'planet' come from? How long is a year on Mercury? Read this book and find out! This guide to the solar system is an ideal introduction for young readers.",
  q: ["How long is a year on Mercury, based on what you can find in this book?",
      "Have you ever looked up at the night sky and wondered about the planets?",
      "Which planet from this book would you most like to learn more about, and why?"],
  h: ["이 책에서 찾을 수 있는 내용에 따르면, 수성에서의 1년은 얼마나 되나요?",
      "너는 밤하늘을 올려다보며 행성들에 대해 궁금해한 적이 있나요?",
      "이 책 속 행성 중 어떤 행성에 대해 더 알고 싶고, 그 이유는 무엇인가요?"] };
ACT["S3034"] = { s: "More than 200 years ago, explorers went on a journey to the Pacific Ocean. With the help of a young American Indian girl, Sacajawea, the trip was a success.",
  q: ["Who helped the explorers on their journey to the Pacific Ocean more than 200 years ago?",
      "Have you ever helped someone finish a difficult journey or task?",
      "Why do you think Sacajawea was so important to the success of the trip?"],
  h: ["200년도 더 전에 탐험가들이 태평양으로 가는 여정에서 누가 도와주었나요?",
      "너는 누군가 어려운 여정이나 일을 마치도록 도와준 적이 있나요?",
      "사카자위아가 그 여행의 성공에 왜 그렇게 중요했다고 생각하나요?"] };
ACT["S3035"] = { s: "This is a true story of Native American Sitting Bull and how he grew to be one of the greatest Indian chiefs ever. It recounts his adventures from the battle of Little Big Horn to Buffalo Bill's Wild West Show in this easy-to-read book.",
  q: ["What are two events from Sitting Bull's life that this book recounts?",
      "Have you ever read or heard a true story about a famous leader?",
      "What makes Sitting Bull one of the greatest Indian chiefs, based on this book?"],
  h: ["이 책이 들려주는 시팅 불의 삶의 사건 두 가지는 무엇인가요?",
      "너는 유명한 지도자에 대한 실화를 읽거나 들어본 적이 있나요?",
      "이 책을 바탕으로, 시팅 불이 가장 위대한 인디언 추장 중 하나가 된 이유는 무엇이라고 생각하나요?"] };
ACT["S3036"] = { s: "This book describes the formation and activities of volcanoes and identifies some notable eruptions.",
  q: ["What does this book describe about how volcanoes form and erupt?",
      "Have you ever seen a picture or video of a volcano erupting?",
      "Which notable eruption from this book would you like to learn more about, and why?"],
  h: ["이 책은 화산이 어떻게 만들어지고 폭발하는지에 대해 무엇을 설명하나요?",
      "너는 화산이 폭발하는 사진이나 영상을 본 적이 있나요?",
      "이 책 속 유명한 폭발 중 어떤 것에 대해 더 알고 싶고, 그 이유는 무엇인가요?"] };
ACT["S3037"] = { s: "What was it like to head out west in a covered wagon? This book follows a wagon trail to California in 1848 as hundreds of pioneers endure great hardships while traveling 2,000 miles of wilderness.",
  q: ["How far did the pioneers travel on the wagon trail to California in 1848?",
      "Have you ever gone on a very long trip? How did you feel during it?",
      "What hardship do you think would have been hardest for the pioneers to endure, and why?"],
  h: ["1848년 개척자들은 캘리포니아로 가는 마차 길에서 얼마나 먼 거리를 여행했나요?",
      "너는 아주 긴 여행을 해 본 적이 있나요? 그동안 기분이 어땠나요?",
      "개척자들에게 가장 견디기 힘들었을 어려움은 무엇이었을 것 같고, 그 이유는 무엇인가요?"] };
ACT["S3038"] = { s: "This easy-to-read book introduces young readers to the amazing creatures found at the bottom of the ocean.",
  q: ["What kind of creatures does this book introduce that live at the bottom of the ocean?",
      "Have you ever seen a picture of a strange deep-sea creature?",
      "Which ocean creature from this book would you most like to see for yourself, and why?"],
  h: ["이 책은 바다 밑바닥에 사는 어떤 생물들을 소개하나요?",
      "너는 이상하게 생긴 심해 생물의 사진을 본 적이 있나요?",
      "이 책 속 바다 생물 중 직접 보고 싶은 것은 무엇이고, 그 이유는 무엇인가요?"] };
ACT["S3039"] = { s: "This book presents the life and career of Seabiscuit, the racehorse, who set sixteen-track records and won more prize money than any other horse.",
  q: ["What did Seabiscuit the racehorse achieve during his career?",
      "Have you ever watched or heard about a horse race?",
      "What do you think made Seabiscuit such a successful racehorse?"],
  h: ["경주마 시비스킷은 경력 동안 어떤 것을 이루었나요?",
      "너는 경마를 보거나 들어본 적이 있나요?",
      "시비스킷을 그렇게 성공적인 경주마로 만든 것은 무엇이었다고 생각하나요?"] };
ACT["S3040"] = { s: "Anne, a young orphan girl, finally finds a home at Green Gables. But it's not exactly smooth sailing. She always seems to find herself getting into trouble!",
  q: ["What kind of home does Anne finally find at Green Gables?",
      "Have you ever moved somewhere new or met a new family?",
      "Why do you think Anne keeps getting into trouble, even though it's not exactly smooth sailing?"],
  h: ["앤은 그린 게이블스에서 마침내 어떤 집을 찾게 되나요?",
      "너는 새로운 곳으로 이사하거나 새로운 가족을 만난 적이 있나요?",
      "순탄하지만은 않은데도 앤이 계속 말썽에 휘말리는 이유는 무엇일 것 같나요?"] };
ACT["S3041"] = { s: "Danny's twin niece and nephew are helping him prepare to open his diner one morning. But they are soon overwhelmed by the work. Things work out after they put their multiplication skills to work.",
  q: ["What skill do the twins use to help solve the problems at Danny's diner?",
      "Have you ever helped a family member get ready for something important, like opening a business?",
      "What other math skills do you think could help Danny run his diner well?"],
  h: ["쌍둥이는 대니의 식당에서 문제를 해결하는 데 어떤 능력을 쓰나요?",
      "너는 가게를 여는 것처럼 중요한 일을 준비하는 가족을 도와준 적이 있나요?",
      "대니가 식당을 잘 운영하는 데 어떤 다른 수학 능력이 도움이 될 것 같나요?"] };
ACT["S3042"] = { s: "This book presents the life and career of Lance Armstrong, the number one cyclist in the world and cancer survivor. The book follows his athletic career and how he did not let the disease stop him from achieving his dream.",
  q: ["How did Lance Armstrong not let cancer stop him from achieving his dream?",
      "Have you ever kept trying to reach a goal even when it was hard?",
      "What do you admire most about Lance Armstrong's athletic career, based on this book?"],
  h: ["랜스 암스트롱은 암에 걸렸는데도 꿈을 이루는 것을 어떻게 포기하지 않았나요?",
      "너는 힘들어도 목표를 이루기 위해 계속 노력한 적이 있나요?",
      "이 책을 바탕으로, 랜스 암스트롱의 운동선수 경력에서 가장 존경스러운 점은 무엇인가요?"] };
ACT["S3043"] = { s: "This book introduces facts and true stories about sharks and discusses both the good and the bad things sharks can do.",
  q: ["What good and bad things about sharks does this book discuss?",
      "Have you ever seen a shark at an aquarium, in a movie, or in real life?",
      "What true shark story from this book surprised you the most, and why?"],
  h: ["이 책은 상어에 대한 어떤 좋은 점과 나쁜 점을 이야기하나요?",
      "너는 수족관이나 영화, 실제로 상어를 본 적이 있나요?",
      "이 책 속 실제 상어 이야기 중 가장 놀라웠던 것은 무엇이고, 그 이유는 무엇인가요?"] };
ACT["S3044"] = { s: "Arthur wants to buy a T-shirt and cap, but he is penniless. He goes into business assisted by his sister Violet.",
  q: ["Who helps Arthur go into business when he wants to buy a T-shirt and cap?",
      "Have you ever wanted to buy something but didn't have enough money?",
      "What kind of business would you start if you needed to earn money for something you wanted?"],
  h: ["아서가 티셔츠와 모자를 사고 싶을 때 사업을 시작하도록 도와주는 사람은 누구인가요?",
      "너는 무언가를 사고 싶었는데 돈이 충분하지 않았던 적이 있나요?",
      "네가 원하는 것을 사기 위해 돈을 벌어야 한다면 어떤 사업을 시작하고 싶나요?"] };
ACT["S3045"] = { s: "Papa's seven little mice ask for a bedtime story. Papa tells one Mouse tale to each mouse and helps them fall asleep.",
  q: ["What does Papa do for his seven little mice at bedtime?",
      "Have you ever asked for a bedtime story? Who told it to you?",
      "If you were Papa, what kind of story would you tell each little mouse?"],
  h: ["아빠는 잠자리에서 일곱 마리 아기 쥐들을 위해 무엇을 해 주나요?",
      "너는 잠자리 이야기를 해 달라고 한 적이 있나요? 누가 들려주었나요?",
      "네가 아빠 쥐라면, 각 아기 쥐에게 어떤 이야기를 들려주고 싶나요?"] };
ACT["S3046"] = { s: "Harry wins a pony in a contest. His aunt and her friends come up with an idea to keep it.",
  q: ["How does Harry come to have a pony, and who helps him figure out how to keep it?",
      "Have you ever won something in a contest?",
      "If you won a pony like Harry, what idea would you come up with to keep it?"],
  h: ["해리는 어떻게 조랑말을 갖게 되었고, 누가 그것을 키울 방법을 생각해내도록 도와주나요?",
      "너는 대회에서 무언가를 상으로 받은 적이 있나요?",
      "네가 해리처럼 조랑말을 받는다면, 그것을 키울 방법을 어떻게 생각해내고 싶나요?"] };
ACT["S3047"] = { s: "Ten-year-old Andrew invents the shrinking machine and accidentally gets sucked into it along with his cousin Judy. Later they find themselves on the dog next door. There, they encounter everything from colossal fleas to crab-like eyelash mites.",
  q: ["What creatures do Andrew and Judy encounter after they end up on the dog next door?",
      "Have you ever imagined what the world would look like if you were tiny?",
      "If you were shrunk down like Andrew, what tiny creature would you be most afraid of meeting?"],
  h: ["앤드루와 주디가 옆집 개 위에서 마주치게 된 생물들은 무엇인가요?",
      "너는 네가 아주 작아진다면 세상이 어떻게 보일지 상상해본 적이 있나요?",
      "네가 앤드루처럼 작아진다면 어떤 작은 생물을 만나는 것이 가장 무서울 것 같나요?"] };
ACT["S3048"] = { s: "Andrew's neighbor bathes her dog. Andrew and Judy, who became microscopic, find themselves washed off the dog and lost in the bathroom! They'll have to use their wits if they're to survive the fights with an ocean of soapy water, mold, and a predatory spider.",
  q: ["What dangers do Andrew and Judy face after being washed off the dog and lost in the bathroom?",
      "Have you ever felt lost in a place that suddenly seemed much bigger than usual?",
      "What do you think Andrew and Judy need most to survive the soapy water and the spider?"],
  h: ["앤드루와 주디는 개에게서 씻겨 내려가 욕실에서 길을 잃은 뒤 어떤 위험을 마주하나요?",
      "너는 갑자기 훨씬 더 커 보이는 장소에서 길을 잃은 기분을 느껴본 적이 있나요?",
      "비눗물과 거미 사이에서 살아남으려면 앤드루와 주디에게 가장 필요한 것이 무엇일 것 같나요?"] };
ACT["S3049"] = { s: "After escaping the bathroom, Andrew, his cousin Judy, and super-smart robot Thudd have to find their way through a maze of pipes to the kitchen sink. On their way toward safety, they encounter drain flies, a cockroach, and worse.",
  q: ["What creatures do Andrew, Judy, and Thudd meet on their way through the maze of pipes?",
      "Have you ever had to find your way through somewhere tricky, like a maze?",
      "How do you think Thudd the robot helps Andrew and Judy stay safe on their journey?"],
  h: ["앤드루, 주디, 서드는 파이프 미로를 지나가면서 어떤 생물들을 만나나요?",
      "너는 미로처럼 까다로운 곳에서 길을 찾아야 했던 적이 있나요?",
      "로봇 서드는 여행 중 앤드루와 주디가 안전하게 지내도록 어떻게 도와줄 것 같나요?"] };
ACT["S3050"] = { s: "Andrew, his cousin Judy, and the robot Thudd manage to escape the kitchen only to end up in the garden. They are running out of time. They have to reach the Atom Sucker before it explodes and unshrink themselves.",
  q: ["What do Andrew, Judy, and Thudd need to reach before the Atom Sucker explodes?",
      "Have you ever had to race against time to finish something important?",
      "What do you think will happen if they don't reach the Atom Sucker in time?"],
  h: ["앤드루, 주디, 서드는 원자 흡입기가 폭발하기 전에 무엇에 도달해야 하나요?",
      "너는 중요한 일을 끝내기 위해 시간과 다투어야 했던 적이 있나요?",
      "그들이 제시간에 원자 흡입기에 도착하지 못하면 어떤 일이 벌어질 것 같나요?"] };
ACT["S3051"] = { s: "Andrew, Judy, and Thudd succeeded in unshrinking themselves and go on a vacation to Hawaii. They accidentally set off in Uncle Al's latest invention, the submarine-like Water Bug, and end up stranding themselves underwater! They struggle to keep the evil Soggy Bob from taking a rare ocean creature.",
  q: ["What invention do Andrew, Judy, and Thudd accidentally set off during their Hawaii vacation?",
      "Have you ever gone on a vacation that turned into an unexpected adventure?",
      "What do you think the evil Soggy Bob wants with the rare ocean creature?"],
  h: ["앤드루, 주디, 서드는 하와이 휴가 중 실수로 어떤 발명품을 작동시켰나요?",
      "너는 예상치 못한 모험으로 바뀐 휴가를 가 본 적이 있나요?",
      "사악한 소기 밥이 그 희귀한 바다 생물을 원하는 이유는 무엇일 것 같나요?"] };
ACT["S3052"] = { s: "After escaping an underwater volcano, Andrew, his cousin Judy, and Thudd are swallowed by the world's largest creature, a blue whale. Inside of the whale, they struggle to find their way home.",
  q: ["What happens to Andrew, Judy, and Thudd right after they escape the underwater volcano?",
      "Have you ever learned a fact about the biggest animal in the world, the blue whale?",
      "How do you think the three friends will find their way out of the whale?"],
  h: ["앤드루, 주디, 서드는 해저 화산에서 탈출한 직후 무슨 일을 겪나요?",
      "너는 세상에서 가장 큰 동물인 대왕고래에 대한 사실을 배워본 적이 있나요?",
      "세 친구는 고래 몸속에서 밖으로 나가는 길을 어떻게 찾을 것 같나요?"] };
ACT["S3053"] = { s: "Andrew, Judy, and Thudd are finally out of the whale, but the Water Bug gets caught on the Great Barrier Reef!",
  q: ["Where does the Water Bug get caught after Andrew, Judy, and Thudd escape the whale?",
      "Have you ever seen a picture of a coral reef? What did it look like?",
      "What problems do you think they will face while stuck on the Great Barrier Reef?"],
  h: ["앤드루, 주디, 서드가 고래에서 벗어난 뒤 워터버그는 어디에 걸리게 되나요?",
      "너는 산호초 사진을 본 적이 있나요? 어떤 모습이었나요?",
      "그레이트 배리어 리프에 갇혀 있는 동안 그들은 어떤 문제를 겪을 것 같나요?"] };
ACT["S3054"] = { s: "While trying to save the giant squid from Soggy Bob, Andrew, Judy, and the robot Thudd get lost at the Challenger Deep, the deepest place in the ocean.",
  q: ["Who are Andrew, Judy, and Thudd trying to save from Soggy Bob at the Challenger Deep?",
      "Have you ever learned about the deepest place in the ocean?",
      "What dangers do you think the deepest part of the ocean might hold for them?"],
  h: ["챌린저 해연에서 앤드루, 주디, 서드는 소기 밥에게서 누구를 구하려고 하나요?",
      "너는 바다에서 가장 깊은 곳에 대해 배워본 적이 있나요?",
      "바다에서 가장 깊은 곳에는 그들에게 어떤 위험이 있을 것 같나요?"] };
ACT["S3055"] = { s: "Dr. Kron-Tox kidnaps Uncle Al and sends him to prehistoric times. Andrew, his cousin Judy, and the robot Thudd attempt to use Uncle Al's latest invention, the Time-A-Tron, to rescue him. Throughout time travel, they learn about the origins of the universe.",
  q: ["Andrew, Judy, and Thudd use Uncle Al's Time-A-Tron to travel through time and learn about the origins of the universe while trying to rescue him from Dr. Kron-Tox. Imagine you could time-travel with them — which moment in the history of the universe would you most want to see, and what do you think it would look like? Write a few sentences about it.",
      "Think about a time you learned something new and amazing about how the world or the universe began. What did you learn, and how did it make you feel?",
      "Dr. Kron-Tox sends Uncle Al to prehistoric times as part of his plan. Why do you think a villain in a story might use time travel against the people he wants to defeat? Explain your thinking."],
  h: ["앤드루, 주디, 서드는 크론톡스 박사에게서 앨 삼촌을 구하려고 앨 삼촌의 타임어트론으로 시간 여행을 하며 우주의 기원에 대해 배워요. 네가 그들과 함께 시간 여행을 할 수 있다면 우주 역사에서 어느 순간을 가장 보고 싶은지, 그 모습이 어떨 것 같은지 몇 문장으로 적어 보세요.",
      "세상이나 우주가 어떻게 시작되었는지에 대해 새롭고 놀라운 것을 배웠던 때를 떠올려 보세요. 무엇을 배웠고, 그때 기분이 어땠나요?",
      "크론톡스 박사는 계획의 일부로 앨 삼촌을 선사시대로 보내요. 이야기 속 악당이 물리치고 싶은 사람에게 시간 여행을 이용하는 이유는 무엇일 것 같나요? 네 생각을 적어 보세요."] };
ACT["S3056"] = { s: "Andrew, Judy, and Thudd have escaped the Big Bang but end up finding themselves inside the Earth. They must fix their time machine and rescue Uncle Al who is now stranded in the Ice Age.",
  q: ["Where do Andrew, Judy, and Thudd end up after escaping the Big Bang?",
      "Have you ever learned about what it's like inside the Earth?",
      "What do you think Andrew and Judy will need to fix their time machine?"],
  h: ["빅뱅에서 탈출한 뒤 앤드루, 주디, 서드는 어디로 가게 되나요?",
      "너는 지구 내부가 어떤 모습인지 배워본 적이 있나요?",
      "앤드루와 주디가 타임머신을 고치려면 무엇이 필요할 것 같나요?"] };
ACT["S3057"] = { s: "Andrew, Judy, and Thudd find themselves surrounded by enormous and hungry dinosaurs. They must protect themselves from the world's most fearsome creatures.",
  q: ["What kind of creatures surround Andrew, Judy, and Thudd in this book?",
      "Have you ever learned an interesting fact about dinosaurs?",
      "How do you think Andrew, Judy, and Thudd will protect themselves from the dinosaurs?"],
  h: ["이 책에서 앤드루, 주디, 서드를 둘러싼 생물은 어떤 종류인가요?",
      "너는 공룡에 대한 흥미로운 사실을 배워본 적이 있나요?",
      "앤드루, 주디, 서드는 공룡들로부터 자신들을 어떻게 지킬 것 같나요?"] };
ACT["S3058"] = { s: "Andrew, Judy, Thudd, and Beeper succeed in finding Uncle Al in the Ice Age. There, they encounter prehistoric animals, birds, and people.",
  q: ["Who joins Andrew, Judy, and Thudd in finding Uncle Al in the Ice Age?",
      "Have you ever learned about what life was like during the Ice Age?",
      "What prehistoric animal, bird, or person would you most want to meet in the Ice Age, and why?"],
  h: ["앤드루, 주디, 서드가 빙하 시대에서 앨 삼촌을 찾는 데 누가 함께하나요?",
      "너는 빙하 시대의 생활이 어땠는지 배워본 적이 있나요?",
      "빙하 시대의 선사시대 동물, 새, 사람 중 누구를 가장 만나고 싶고, 그 이유는 무엇인가요?"] };
ACT["S3059"] = { s: "Andrew, Judy, and Thudd manage to time-travel out of the Ice Age. But now they are shrunk down and tossed out with the garbage!",
  q: ["What happens to Andrew, Judy, and Thudd right after they time-travel out of the Ice Age?",
      "Have you ever accidentally ended up somewhere you didn't expect, like the garbage?",
      "What do you think it would be like to be shrunk down and tossed out with the garbage?"],
  h: ["빙하 시대에서 시간 여행으로 빠져나온 직후 앤드루, 주디, 서드에게 무슨 일이 일어나나요?",
      "너는 예상치 못한 곳, 예를 들면 쓰레기 같은 곳에 실수로 가게 된 적이 있나요?",
      "몸이 작아져서 쓰레기와 함께 버려진다면 어떤 기분일 것 같나요?"] };
ACT["S3060"] = { s: "Beetle-sized Andrew and his cousin Judy are carried into a cave. They learn about the bats and bugs that live there from Thudd the robot and personal experience.",
  q: ["Who teaches Andrew and Judy about the bats and bugs living in the cave?",
      "Have you ever visited or learned about a cave?",
      "What would you want to learn about bats if you were beetle-sized like Andrew?"],
  h: ["동굴에 사는 박쥐와 벌레에 대해 앤드루와 주디에게 누가 가르쳐 주나요?",
      "너는 동굴을 방문하거나 동굴에 대해 배워본 적이 있나요?",
      "네가 앤드루처럼 딱정벌레만 한 크기가 된다면 박쥐에 대해 무엇을 알고 싶나요?"] };
ACT["S3061"] = { s: "Insect-sized Andrew, Judy, and Thudd get lost in an Australian rainforest. They must evade insects, plants, and other threats and make their way toward the village where Uncle Al will meet them.",
  q: ["What threats do insect-sized Andrew, Judy, and Thudd need to evade in the Australian rainforest?",
      "Have you ever visited or learned about a rainforest?",
      "How do you think being insect-sized would change the way you see a rainforest?"],
  h: ["곤충만 한 크기가 된 앤드루, 주디, 서드는 호주 열대 우림에서 어떤 위험을 피해야 하나요?",
      "너는 열대 우림을 방문하거나 열대 우림에 대해 배워본 적이 있나요?",
      "곤충만 한 크기가 되면 열대 우림을 보는 방식이 어떻게 달라질 것 같나요?"] };
ACT["S3062"] = { s: "An electric fish shrinks Andrew, his cousin Judy, and Thudd the robot to the size of bacteria. Then they are injected by a mosquito into Uncle Al's blood vessel. They battle parasites, germs, and white blood cells in the bloodstream.",
  q: ["An electric fish shrinks Andrew, Judy, and Thudd down to the size of bacteria, and a mosquito injects them into Uncle Al's blood vessel, where they battle parasites, germs, and white blood cells. If you were shrunk down to travel inside someone's bloodstream, what do you think you would see and feel, and how would you try to stay safe? Write a few sentences describing your journey.",
      "Think about what you already know about germs, parasites, or white blood cells in the human body. How does learning that this adventure happens inside a real body change the way you think about staying healthy?",
      "Andrew and his friends keep getting shrunk to incredibly small sizes throughout this series. Why do you think the author keeps sending them into stranger and smaller worlds instead of ending the adventures? Explain your thinking."],
  h: ["전기뱀장어가 앤드루, 주디, 서드를 박테리아 크기로 줄이고, 모기가 그들을 앨 삼촌의 혈관 속으로 주입해서 그들은 기생충, 세균, 백혈구와 싸워요. 네가 작아져서 누군가의 혈관 속을 여행한다면 무엇을 보고 느낄 것 같은지, 안전하게 지내려고 어떻게 할지 몇 문장으로 적어 보세요.",
      "네가 이미 알고 있는 세균, 기생충, 백혈구에 대한 지식을 떠올려 보세요. 이 모험이 실제 사람 몸속에서 일어난다는 것을 알면 건강을 지키는 것에 대한 생각이 어떻게 달라지나요?",
      "앤드루와 친구들은 이 시리즈 내내 계속 점점 더 작은 크기로 줄어들어요. 작가는 왜 모험을 끝내지 않고 그들을 계속 더 이상하고 더 작은 세계로 보내는 것 같나요? 네 생각을 적어 보세요."] };
ACT["S3063"] = { s: "Lizzie refuses to speak to anyone as if she has a zip across her mouth. Nothing can coax her into speaking to her new family until she meets stubborn Great-Gran.",
  q: ["Why does Lizzie refuse to speak to anyone in her new family?",
      "Have you ever felt too shy or upset to talk to people around you?",
      "What do you think Great-Gran does that finally coaxes Lizzie into speaking?"],
  h: ["리지는 새 가족에게 왜 아무 말도 하지 않으려 하나요?",
      "너는 너무 부끄럽거나 속상해서 주변 사람들에게 말하기 힘들었던 적이 있나요?",
      "왕할머니가 마침내 리지가 말을 하게 만든 방법은 무엇이었을 것 같나요?"] };
ACT["S3064"] = { s: "A tiny monster from another planet takes Natalie in his mini flying saucer for some 'Monster Fun.'",
  q: ["What does the tiny monster do to take Natalie on 'Monster Fun'?",
      "Have you ever imagined meeting a friendly monster or alien?",
      "If a tiny monster took you on an adventure in a mini flying saucer, where would you want to go?"],
  h: ["작은 괴물은 나탈리를 '몬스터 펀'으로 데려가려고 무엇을 하나요?",
      "너는 친절한 괴물이나 외계인을 만나는 상상을 해본 적이 있나요?",
      "작은 괴물이 작은 비행접시로 너를 모험에 데려간다면, 어디로 가고 싶나요?"] };
ACT["S3065"] = { s: "Dinah is the only one who doesn't have a packed lunch for the school trip to the Dinosaur Museum. But a friendly iguanodon cooks Dinah an extra special packed lunch.",
  q: ["Who cooks Dinah an extra special packed lunch for her school trip?",
      "Have you ever forgotten to bring something important for a school trip?",
      "What do you think the iguanodon put in Dinah's special packed lunch?"],
  h: ["다이나의 소풍을 위해 특별한 도시락을 만들어준 것은 누구인가요?",
      "너는 학교 소풍에 중요한 것을 깜빡하고 가져가지 못한 적이 있나요?",
      "이구아노돈이 다이나의 특별한 도시락에 무엇을 넣었을 것 같나요?"] };
ACT["S3066"] = { s: "The principal asks Arthur to take home a large envelope marked confidential. It sure looks like trouble.",
  q: ["What does the principal ask Arthur to take home?",
      "Have you ever been asked to carry something important or secret for someone?",
      "Why do you think a large envelope marked confidential would look like trouble to Arthur?"],
  h: ["교장 선생님은 아서에게 무엇을 집으로 가져가라고 부탁하나요?",
      "너는 누군가로부터 중요하거나 비밀스러운 것을 맡아 옮겨본 적이 있나요?",
      "'기밀'이라고 적힌 큰 봉투가 아서에게 왜 말썽처럼 보였을 것 같나요?"] };
ACT["S3067"] = { s: "Arthur and his friends take action when they discover their favorite book series is banned.",
  q: ["What do Arthur and his friends discover has been banned?",
      "Have you ever thought something you liked was treated unfairly?",
      "What action do you think Arthur and his friends take to fight the ban?"],
  h: ["아서와 친구들은 무엇이 금지되었다는 것을 발견하나요?",
      "너는 네가 좋아하는 것이 부당하게 취급받는다고 느낀 적이 있나요?",
      "아서와 친구들은 그 금지에 맞서기 위해 어떤 행동을 취할 것 같나요?"] };
ACT["S3068"] = { s: "Arthur is delighted to make the Little League team, but he worries that he won't be able to play as well as his friends.",
  q: ["What worry does Arthur have after making the Little League team?",
      "Have you ever joined a team or activity and worried you wouldn't do as well as others?",
      "What would you say to Arthur to help him feel better about his worry?"],
  h: ["아서는 리틀 리그 팀에 들어간 뒤 어떤 걱정을 하나요?",
      "너는 팀이나 활동에 참여했을 때 다른 사람들만큼 잘하지 못할까 봐 걱정한 적이 있나요?",
      "아서가 걱정을 덜도록 네가 해 주고 싶은 말은 무엇인가요?"] };
ACT["S3069"] = { s: "Arthur is eager to enter a jingle in the Crunch Cereal Contest, but he finds it challenging to think of a good idea. When he hears D.W. singing a catchy tune, he enters it instead.",
  q: ["Whose jingle does Arthur end up entering in the Crunch Cereal Contest?",
      "Have you ever had trouble thinking of a good idea for a contest or project?",
      "What do you think Arthur felt when he decided to enter D.W.'s jingle instead of his own?"],
  h: ["아서는 크런치 시리얼 대회에 결국 누구의 노래를 출품하나요?",
      "너는 대회나 프로젝트를 위한 좋은 아이디어를 떠올리기 힘들었던 적이 있나요?",
      "아서가 자신의 것 대신 디더블유의 노래를 출품하기로 했을 때 어떤 기분이었을 것 같나요?"] };
ACT["S3070"] = { s: "Arthur gets wrongly accused of stealing quarters from a fund drive. Buster, a brand-new private eye, solves the crime and proves Arthur's innocence.",
  q: ["Who solves the crime and proves Arthur's innocence?",
      "Have you ever been blamed for something you didn't do?",
      "What skills do you think Buster needs to be a good private eye?"],
  h: ["그 범죄를 해결하고 아서의 무죄를 증명하는 사람은 누구인가요?",
      "너는 하지 않은 일로 비난받은 적이 있나요?",
      "버스터가 훌륭한 탐정이 되려면 어떤 능력이 필요할 것 같나요?"] };
ACT["S3071"] = { s: "Arthur and Francine get locked in the library after it is closed. They must set aside their differences and work together to find a way out.",
  q: ["What do Arthur and Francine have to do to find a way out of the library?",
      "Have you ever had to work together with someone you didn't get along with?",
      "How do you think Arthur and Francine's feelings about each other change by the end?"],
  h: ["아서와 프랜신은 도서관에서 빠져나갈 방법을 찾기 위해 무엇을 해야 하나요?",
      "너는 사이가 좋지 않은 사람과 함께 협력해야 했던 적이 있나요?",
      "아서와 프랜신이 서로에 대해 느끼는 감정은 마지막에 어떻게 달라질 것 같나요?"] };
ACT["S3072"] = { s: "Arthur's class goes on a field trip to Rainbow Rock State Park. Arthur and Buster uncover a rare fossil, but they don't want to share their discovery with the park's paleontologists.",
  q: ["What do Arthur and Buster find on their field trip to Rainbow Rock State Park?",
      "Have you ever found something special or rare and wanted to keep it a secret?",
      "Why do you think Arthur and Buster don't want to share their discovery with the paleontologists?"],
  h: ["아서와 버스터는 레인보우 록 주립공원 현장학습에서 무엇을 발견하나요?",
      "너는 특별하거나 귀한 것을 발견해서 비밀로 하고 싶었던 적이 있나요?",
      "아서와 버스터가 발견물을 고생물학자들과 나누고 싶어 하지 않는 이유는 무엇일 것 같나요?"] };
ACT["S3073"] = { s: "Francine is paired up with Arthur for square dancing in gym class. She refuses Muffy's request to trade partners. Binky misunderstands the whole thing and spreads words that Arthur and Francine are in love.",
  q: ["What does Binky misunderstand and spread around school?",
      "Have you ever heard a rumor spread about you that wasn't true?",
      "What could Francine and Arthur do to stop the misunderstanding from Binky?"],
  h: ["빙키는 무엇을 오해해서 학교에 소문을 퍼뜨리나요?",
      "너는 사실이 아닌 소문이 너에 대해 퍼진 적이 있나요?",
      "프랜신과 아서는 빙키가 만든 오해를 멈추기 위해 무엇을 할 수 있을 것 같나요?"] };
ACT["S3074"] = { s: "Arthur is thrilled that his favorite rock group Binky is giving a concert in their town. The thing is, his seat is in row ZZZ! His only hope of seeing the rock star up close is to be chosen as 'the lucky kid.'",
  q: ["What is Arthur's only hope of seeing Binky up close at the concert?",
      "Have you ever really wanted to see your favorite singer or group perform?",
      "What do you think Arthur will do to try to become 'the lucky kid'?"],
  h: ["콘서트에서 빙키를 가까이 볼 수 있는 아서의 유일한 희망은 무엇인가요?",
      "너는 네가 가장 좋아하는 가수나 그룹의 공연을 정말 보고 싶었던 적이 있나요?",
      "아서는 '행운의 아이'가 되기 위해 무엇을 할 것 같나요?"] };
ACT["S3075"] = { s: "Muffy bets that Francine can't be nice for a whole week. Francine struggles to keep her temper while Arthur and his gang push her to the limit.",
  q: ["What bet does Muffy make about Francine's ability to be nice?",
      "Have you ever tried hard to stay calm even when people were bothering you?",
      "What do you think Arthur and his gang do to push Francine to the limit?"],
  h: ["머피는 프랜신이 친절할 수 있는지에 대해 어떤 내기를 거나요?",
      "너는 사람들이 괴롭혀도 침착함을 지키려고 애써본 적이 있나요?",
      "아서와 친구들은 프랜신을 한계까지 몰아붙이기 위해 무엇을 할 것 같나요?"] };
ACT["S3076"] = { s: "At Prunella's half-birthday party, her sister reveals a fortune-telling cootie-catcher that can predict the future.",
  q: ["What does Prunella's sister reveal at the half-birthday party?",
      "Have you ever tried a fortune-telling game with friends, like a cootie-catcher?",
      "Do you think a paper fortune-teller can really predict the future? Why or why not?"],
  h: ["프루넬라의 절반 생일 파티에서 언니는 무엇을 보여주나요?",
      "너는 친구들과 종이 운세 놀이 같은 점치기 게임을 해본 적이 있나요?",
      "종이 운세 놀이가 정말 미래를 예측할 수 있다고 생각하나요? 왜 그렇게 생각하나요?"] };
ACT["S3077"] = { s: "Arthur and his gang help Buster study for an important test so that Buster can move on to the fourth grade with them.",
  q: ["Why do Arthur and his gang help Buster study for the important test?",
      "Have you ever studied together with friends to help each other pass a test?",
      "What study methods do you think would help Buster the most?"],
  h: ["아서와 친구들은 왜 버스터가 중요한 시험을 준비하도록 도와주나요?",
      "너는 친구들과 함께 공부하며 서로 시험을 잘 보도록 도운 적이 있나요?",
      "버스터에게 가장 도움이 될 공부 방법은 무엇일 것 같나요?"] };
ACT["S3078"] = { s: "After Muffy bribes the judges at the science fair, Francine and the Brain write love notes to her to get revenge for her.",
  q: ["What do Francine and the Brain do to get revenge on Muffy?",
      "Have you ever felt like something unfair happened at a contest, like the science fair?",
      "Do you think writing love notes was a fair way to get revenge? Why or why not?"],
  h: ["프랜신과 브레인은 머피에게 복수하기 위해 무엇을 하나요?",
      "너는 과학 박람회 같은 대회에서 불공정한 일이 일어났다고 느낀 적이 있나요?",
      "사랑의 쪽지를 쓴 것이 공정한 복수 방법이었다고 생각하나요? 왜 그렇게 생각하나요?"] };
ACT["S3079"] = { s: "Everyone treats Buster like a hero after he rescues a cat stuck in a tree. Arthur and his friends devise a plan to bring him back to his old self when he begins to enjoy his celebrity a little too much.",
  q: ["What does Buster do that makes everyone treat him like a hero?",
      "Have you ever done something brave that made people admire you?",
      "Why do you think Arthur and his friends want to bring Buster back to his old self?"],
  h: ["버스터가 무엇을 했길래 모두가 그를 영웅처럼 대하게 되나요?",
      "너는 용감한 일을 해서 사람들이 너를 존경하게 만든 적이 있나요?",
      "아서와 친구들이 버스터를 예전 모습으로 되돌리고 싶어 하는 이유는 무엇일 것 같나요?"] };
ACT["S3080"] = { s: "An argument between Francine and the Brain, the team's best players, threatens the future of their soccer team. Arthur tries to reconcile the two.",
  q: ["What is threatening the future of Arthur's soccer team?",
      "Have you ever seen two teammates argue and cause problems for a whole team?",
      "What do you think Arthur could say to help Francine and the Brain make up?"],
  h: ["아서네 축구팀의 미래를 위협하는 것은 무엇인가요?",
      "너는 두 팀원이 다투어서 팀 전체에 문제가 생긴 것을 본 적이 있나요?",
      "프랜신과 브레인이 화해하도록 아서는 어떤 말을 할 수 있을 것 같나요?"] };
ACT["S3081"] = { s: "The graffiti that says \"Binky Rules\" is all over school property. Binky is accused of doing it, but he denies it. Buster and Fern try to solve the mystery.",
  q: ["What message is spray-painted all over the school property?",
      "Have you ever been blamed for something you said you didn't do?",
      "How do you think Buster and Fern go about solving the graffiti mystery?"],
  h: ["학교 곳곳에 스프레이로 적힌 메시지는 무엇인가요?",
      "너는 하지 않았다고 말한 일로 비난받은 적이 있나요?",
      "버스터와 펀은 낙서 수수께끼를 어떻게 풀어갈 것 같나요?"] };
ACT["S3082"] = { s: "Arthur and his friends are unhappy with too much homework they have to do. They dare each other to skip school for a whole day.",
  q: ["What do Arthur and his friends dare each other to do about homework?",
      "Have you ever felt like you had too much homework to handle?",
      "Do you think skipping school for a day was a good idea for Arthur and his friends? Why or why not?"],
  h: ["아서와 친구들은 숙제에 대해 서로에게 무엇을 하라고 부추기나요?",
      "너는 숙제가 너무 많아서 감당하기 힘들다고 느낀 적이 있나요?",
      "아서와 친구들이 하루 동안 학교를 빠진 것이 좋은 생각이었다고 생각하나요? 왜 그렇게 생각하나요?"] };
ACT["S3083"] = { s: "The Brain decides to become a comedian after he's defeated by Buster in a math contest. His friends try to convince him that he is still as smart as ever.",
  q: ["Why does the Brain decide to become a comedian?",
      "Have you ever lost a contest or game and felt like it changed how you saw yourself?",
      "How do you think the Brain's friends try to convince him he is still smart?"],
  h: ["브레인은 왜 코미디언이 되기로 결심하나요?",
      "너는 대회나 게임에서 져서 스스로에 대한 생각이 달라진 적이 있나요?",
      "브레인의 친구들은 그가 여전히 똑똑하다는 것을 어떻게 설득하려 할 것 같나요?"] };
ACT["S3084"] = { s: "Buster tells his friends that he has seen a UFO, but none of them believe him. He tries to prove himself with the pictures he has taken, but the Brain has a simple explanation for every photo.",
  q: ["What does Buster use to try to prove he really saw a UFO?",
      "Have you ever seen something in the sky that you couldn't explain?",
      "Do you believe Buster really saw a UFO, or do you think the Brain's explanations are right? Why?"],
  h: ["버스터는 자신이 정말 UFO를 보았다는 것을 증명하려고 무엇을 이용하나요?",
      "너는 설명할 수 없는 무언가를 하늘에서 본 적이 있나요?",
      "버스터가 정말 UFO를 보았다고 생각하나요, 아니면 브레인의 설명이 맞다고 생각하나요? 이유를 적어 보세요."] };
ACT["S3085"] = { s: "Since his parents' divorce, Buster's father is not around much. Arthur and his gang try to find a substitute to attend the Father's Day picnic with Buster.",
  q: ["What are Arthur and his gang trying to find for Buster before Father's Day?",
      "Have you ever helped a friend who was missing someone important in their life?",
      "Who do you think Arthur and his friends will find to be Buster's substitute?"],
  h: ["아서와 친구들은 아버지의 날 전에 버스터를 위해 무엇을 찾으려 하나요?",
      "너는 삶에서 중요한 사람이 없는 친구를 도와준 적이 있나요?",
      "아서와 친구들이 버스터의 대신으로 찾아낼 사람은 누구일 것 같나요?"] };
ACT["S3086"] = { s: "When Arthur fails to show up for his second piano lesson, his music teacher dismisses him. Now he has to decide how much he wants to take piano lessons.",
  q: ["What happens when Arthur fails to show up for his second piano lesson?",
      "Have you ever had to decide whether to keep doing an activity or lesson?",
      "What do you think Arthur will decide about taking piano lessons, and why?"],
  h: ["아서가 두 번째 피아노 수업에 나타나지 않았을 때 무슨 일이 일어나나요?",
      "너는 어떤 활동이나 수업을 계속할지 그만둘지 결정해야 했던 적이 있나요?",
      "아서가 피아노 수업에 대해 어떤 결정을 내릴 것 같고, 그 이유는 무엇인가요?"] };
ACT["S3087"] = { s: "The Brain usually is not superstitious. But he comes to believe in superstition when he starts finding bad luck everywhere he turns.",
  q: ["What happens after the Brain is defeated by Buster in a math contest?",
      "Have you ever started believing in luck or superstition after something surprising happened?",
      "Why do you think it's easy to believe bad luck is everywhere once you start looking for it?"],
  h: ["브레인이 수학 대결에서 버스터에게 진 뒤 무슨 일이 일어나나요?",
      "너는 놀라운 일이 일어난 뒤 운이나 미신을 믿기 시작한 적이 있나요?",
      "한 번 찾기 시작하면 어디에나 불운이 있다고 믿기 쉬운 이유는 무엇일 것 같나요?"] };
ACT["S3088"] = { s: "This treehouse has 13 stories, a bowling alley, a see-through swimming pool, a secret underground laboratory. This house is full of interesting things!",
  q: ["What special rooms and features does this thirteen-storey treehouse have?",
      "Have you ever imagined building your own amazing treehouse?",
      "If you added one more room to this treehouse, what would it be and why?"],
  h: ["이 13층짜리 나무집에는 어떤 특별한 방과 시설이 있나요?",
      "너는 너만의 멋진 나무집을 짓는 상상을 해본 적이 있나요?",
      "네가 이 나무집에 방을 하나 더 추가한다면, 무엇으로 하고 싶고 그 이유는 무엇인가요?"] };
ACT["S3089"] = { s: "A young woman tells her son, throughout his childhood, how much she loves him, until a time when the son has a daughter of his own and passes on the same message of his affection for her.",
  q: ["What message does the young woman tell her son throughout his childhood?",
      "Have you ever told a family member how much you love them?",
      "Why do you think the son passes the same message on to his own daughter?"],
  h: ["젊은 여성은 아들이 자라는 동안 계속 어떤 메시지를 전하나요?",
      "너는 가족에게 얼마나 사랑하는지 말해본 적이 있나요?",
      "아들이 자신의 딸에게도 같은 메시지를 전하는 이유는 무엇일 것 같나요?"] };
ACT["S3090"] = { s: "A young penguin and his father receive comfort from each other as they wait for the mother penguin from her diving.",
  q: ["What are the young penguin and his father waiting for?",
      "Have you ever waited for a family member to come back from somewhere?",
      "How do you think the young penguin and his father comfort each other while they wait?"],
  h: ["아기 펭귄과 아빠는 무엇을 기다리고 있나요?",
      "너는 가족이 어딘가에서 돌아오기를 기다려본 적이 있나요?",
      "아기 펭귄과 아빠는 기다리는 동안 서로를 어떻게 위로할 것 같나요?"] };
ACT["S3091"] = { s: "Grace, who loves stories, is determined to play Peter Pan in the school play.",
  q: ["What role is Grace determined to play in the school play?",
      "Have you ever really wanted a certain role or part in a school activity?",
      "What do you think Grace does to show she can play the role she wants?"],
  h: ["그레이스는 학교 연극에서 어떤 역할을 맡기로 결심하나요?",
      "너는 학교 활동에서 특정한 역할을 정말 맡고 싶었던 적이 있나요?",
      "그레이스는 자신이 원하는 역할을 할 수 있다는 것을 보여주기 위해 무엇을 할 것 같나요?"] };
ACT["S3092"] = { s: "Chrysanthemum loves her perfect name. But on her first day of school, the other children make fun of her name.",
  q: ["What do the other children do to Chrysanthemum on her first day of school?",
      "Have you ever felt embarrassed about your name or something about yourself?",
      "What do you think helps Chrysanthemum feel proud of her name again?"],
  h: ["크리산써멈이 학교 첫날 다른 아이들에게 어떤 일을 당하나요?",
      "너는 네 이름이나 너 자신에 대해 부끄러움을 느낀 적이 있나요?",
      "크리산써멈이 다시 자기 이름을 자랑스러워하도록 도와주는 것은 무엇일 것 같나요?"] };
ACT["S3093"] = { s: "In this book, a little girl tells how her deaf sister experiences everyday things.",
  q: ["What does the little girl tell about her deaf sister in this book?",
      "Have you ever spent time with someone who experiences the world differently from you?",
      "What do you think is something special about having a sister who is deaf?"],
  h: ["이 책에서 여자아이는 청각 장애가 있는 언니(동생)에 대해 무엇을 이야기하나요?",
      "너는 세상을 너와 다르게 경험하는 사람과 함께 시간을 보낸 적이 있나요?",
      "청각 장애가 있는 언니(동생)가 있다는 것의 특별한 점은 무엇일 것 같나요?"] };
ACT["S3094"] = { s: "It's Valentine's Day. Splat has a special valentine for Kitten. Will Splat's valentine win her heart in the end?",
  q: ["What special thing does Splat have for Kitten on Valentine's Day?",
      "Have you ever made or given a valentine to someone special?",
      "Do you think Splat's valentine wins Kitten's heart? Why or why not?"],
  h: ["밸런타인데이에 스플랫이 키튼을 위해 준비한 특별한 것은 무엇인가요?",
      "너는 특별한 사람에게 밸런타인 카드를 만들거나 준 적이 있나요?",
      "스플랫의 밸런타인이 키튼의 마음을 얻을 것 같나요? 왜 그렇게 생각하나요?"] };
ACT["S3095"] = { s: "Exhausted with endless chores, Mrs. Piggott leaves home one day. Her family realizes how much she has been working for them.",
  q: ["Why is Mrs. Piggott exhausted, and what does she finally do about it?",
      "Have you ever felt tired from doing too many chores?",
      "What do you think Mrs. Piggott's family realizes after she leaves?"],
  h: ["피곳 부인은 왜 지쳐 있었고, 결국 그것 때문에 무엇을 하나요?",
      "너는 집안일을 너무 많이 해서 지친 적이 있나요?",
      "피곳 부인이 떠난 뒤 가족은 무엇을 깨닫게 될 것 같나요?"] };
ACT["S3096"] = { s: "Duck, Squirrel, and Cat live peacefully in an old cabin, and they make pumpkin soup the same way every day. One day, Duck wants to take a different job in making the soup.",
  q: ["What does Duck want to do differently about making the pumpkin soup?",
      "Have you ever wanted to change the way your family does something, like cooking?",
      "How do you think Squirrel and Cat react to Duck wanting a different job?"],
  h: ["오리는 호박 수프를 만드는 방법을 어떻게 다르게 하고 싶어 하나요?",
      "너는 가족이 요리 같은 일을 하는 방식을 바꾸고 싶었던 적이 있나요?",
      "다람쥐와 고양이는 오리가 다른 역할을 원하는 것에 어떻게 반응할 것 같나요?"] };
ACT["S3097"] = { s: "A princess finds out that her evil uncle is taking over the kingdom. She must warn her father, the King.",
  q: ["What does the princess find out that her evil uncle is doing?",
      "Have you ever had to warn someone about something important?",
      "What do you think the princess does to try to save the kingdom?"],
  h: ["공주는 사악한 삼촌이 무엇을 하고 있다는 것을 알게 되나요?",
      "너는 누군가에게 중요한 것을 경고해야 했던 적이 있나요?",
      "공주는 왕국을 구하기 위해 무엇을 할 것 같나요?"] };
ACT["S3098"] = { s: "One day, a mysterious man enters a restaurant and pays with a magical paper crane for his dinner.",
  q: ["What does the mysterious man use to pay for his dinner at the restaurant?",
      "Have you ever met someone who seemed mysterious or magical?",
      "What do you think is special or magical about the paper crane?"],
  h: ["수상한 남자는 식당에서 저녁 식사 값을 무엇으로 치르나요?",
      "너는 신비하거나 마법 같아 보이는 사람을 만난 적이 있나요?",
      "그 종이 학에는 어떤 특별하거나 마법 같은 점이 있을 것 같나요?"] };
ACT["S3099"] = { s: "Andy and Terry will have even more time to jump on the world's highest trampoline, toast marshmallows in an active volcano, and swim in the chocolate waterfall!",
  q: ["What activities will Andy and Terry have more time for in the treehouse now?",
      "Have you ever wished you had more time to do something fun?",
      "Which activity in the treehouse would you most want to try, and why?"],
  h: ["앤디와 테리는 이제 나무집에서 어떤 활동을 할 시간이 더 많아지나요?",
      "너는 재미있는 일을 할 시간이 더 있었으면 좋겠다고 바란 적이 있나요?",
      "나무집 속 활동 중 가장 해보고 싶은 것은 무엇이고, 그 이유는 무엇인가요?"] };
