// 간이 학습 질문 — Book No. S32 묶음. 사람이 아니라 AI 가 한 번 쓰고 굳힌 파일이다.
window.ACT = window.ACT || {};
var ACT = window.ACT;
ACT["S3200"] = { s: "Inspired by his third-grade lesson on the moon, Harry announces that he is going there.",
  q: ["What did Harry announce after his lesson on the moon?",
      "Have you ever learned something in class that made you want to try it yourself?",
      "Write one thing you would want to do if you learned about the moon."],
  h: ["해리는 달에 관한 수업을 듣고 나서 무엇을 하겠다고 선언했나요?",
      "나는 수업에서 배운 것 때문에 직접 해 보고 싶어진 적이 있나요?",
      "내가 달에 대해 배운다면 해 보고 싶은 일을 한 가지 적어 보세요."] };
ACT["S3201"] = { s: "In this book, Harry and Doug are on a secret mission to place cobwebs all over the school to celebrate Charlotte's Web. They also learn how to make green slime and join some other school activities.",
  q: ["What was Harry and Doug's secret mission at school?",
      "Have you ever made a craft or slime with a friend?",
      "Write one activity from the book you would like to try at your school."],
  h: ["해리와 더그는 학교에서 어떤 비밀 임무를 맡았나요?",
      "나는 친구와 함께 만들기나 슬라임을 만들어 본 적이 있나요?",
      "이 책에 나온 학교 활동 중에 내가 해 보고 싶은 것을 한 가지 적어 보세요."] };
ACT["S3202"] = { s: "Harry falls in love with Song Lee, and Doug, Harry's best friend, can't stand all that mushy-gushy stuff.",
  q: ["Who does Harry fall in love with in this book?",
      "How does Doug feel about all the mushy-gushy stuff?",
      "Write your opinion: do you agree with Doug, or not, and why?"],
  h: ["해리는 이 책에서 누구를 좋아하게 되나요?",
      "더그는 그런 오글거리는 일들을 어떻게 생각하나요?",
      "여러분은 더그의 생각에 동의하나요? 이유와 함께 적어 보세요."] };
ACT["S3203"] = { s: "When Harry and his friends move on to third grade, it brings lots of changes. But still, Harry and Sidney are lifelong enemies. When Sidney accidentally kills Harry's pet, Harry decides to get revenge during a class trip.",
  q: ["What happens to Harry's pet because of Sidney?",
      "Have you ever felt angry enough to want to get back at someone?",
      "Write what you think Harry should do instead of getting revenge."],
  h: ["시드니 때문에 해리의 애완동물에게 무슨 일이 일어났나요?",
      "나는 누군가에게 되갚아 주고 싶을 만큼 화가 난 적이 있나요?",
      "복수하는 대신 해리가 어떻게 하면 좋을지 내 생각을 적어 보세요."] };
ACT["S3204"] = { s: "It's almost Valentine's Day, and the students in room 2B are preoccupied with a possible wedding between Song Lee and Horrible Harry.",
  q: ["What are the students in room 2B preoccupied with?",
      "Have you ever teased a friend about liking someone, or been teased yourself?",
      "Write what you think will happen at the kickball wedding."],
  h: ["2B반 학생들은 무엇에 정신이 팔려 있나요?",
      "나는 누가 누구를 좋아한다고 놀리거나, 놀림을 받아 본 적이 있나요?",
      "킥볼 결혼식에서 무슨 일이 일어날지 내 생각을 적어 보세요."] };
ACT["S3205"] = { s: "Harry discovers the biggest mystery ever in Room 3B - a locked closet that's been sealed off for years. Harry and his classmates want to find out what's inside.",
  q: ["What mystery does Harry discover in Room 3B?",
      "Have you ever wondered what was behind a locked door?",
      "Write what you imagine is inside the locked closet."],
  h: ["해리는 3B반에서 어떤 수수께끼를 발견했나요?",
      "나는 잠긴 문 뒤에 무엇이 있을지 궁금했던 적이 있나요?",
      "잠긴 벽장 안에 무엇이 있을지 상상해서 적어 보세요."] };
ACT["S3206"] = { s: "The Goog, Harry's pet cat, sneaks a ride in Grandma's truck and gets into the school building. To catch him before anyone else does, Harry and Doug chase all over school, even searching the places students aren't allowed to enter.",
  q: ["How does the Goog end up inside the school building?",
      "Have you ever had a pet get somewhere it wasn't supposed to be?",
      "Write what you think Harry and Doug find in the places they aren't allowed to enter."],
  h: ["고양이 구그는 어떻게 학교 건물 안까지 들어가게 되었나요?",
      "나는 애완동물이 가면 안 되는 곳에 가 버린 적이 있나요?",
      "해리와 더그가 들어가면 안 되는 곳에서 무엇을 발견했을지 적어 보세요."] };
ACT["S3207"] = { s: "When the kids in room 3B find out Miss Mackle is engaged, Horrible Harry sets out to discover the lucky groom, even taking some risky moves to be the first one to know.",
  q: ["What does Harry try to discover about Miss Mackle?",
      "Have you ever taken a risk because you were very curious about something?",
      "Write who you think the lucky groom might be."],
  h: ["해리는 미스 매클에 대해 무엇을 알아내려고 하나요?",
      "나는 너무 궁금해서 위험한 행동을 해 본 적이 있나요?",
      "행운의 신랑이 누구일지 내 생각을 적어 보세요."] };
ACT["S3208"] = { s: "When Sid, Harry's sworn enemy, ruins Song Lee's origami animal, Harry plots triple revenge!",
  q: ["What does Sid do to Song Lee's origami animal?",
      "Have you ever wanted to get back at someone for ruining something of yours or a friend's?",
      "Write what you think Harry's triple revenge could be."],
  h: ["시드는 송리의 종이접기 동물에게 무슨 짓을 했나요?",
      "나는 내 것이나 친구 것을 망친 사람에게 되갚아 주고 싶었던 적이 있나요?",
      "해리의 삼중 복수가 무엇일지 내 생각을 적어 보세요."] };
ACT["S3209"] = { s: "In this book, Henry tries to run away, attempts to sell his little brother at a yard sale, and commits other horrid acts.",
  q: ["What two things does Henry try to do to get away from home or get money?",
      "Have you ever tried to earn money in a funny or clever way?",
      "Write what you think happens when Henry tries to sell his little brother."],
  h: ["헨리는 집을 떠나거나 돈을 벌려고 어떤 두 가지 일을 하려고 했나요?",
      "나는 재미있거나 기발한 방법으로 돈을 벌어 본 적이 있나요?",
      "헨리가 동생을 팔려고 할 때 무슨 일이 일어날지 적어 보세요."] };
ACT["S3210"] = { s: "In this book, Henry enters a snowman-building contest, and he uses a few last-minute tricks to win this one.",
  q: ["What contest does Henry enter in this book?",
      "Have you ever built a snowman? What did it look like?",
      "Write what trick you think Henry uses to win the contest."],
  h: ["헨리는 이 책에서 어떤 대회에 나가나요?",
      "나는 눈사람을 만들어 본 적이 있나요? 어떤 모습이었나요?",
      "헨리가 대회에서 이기려고 어떤 꾀를 냈을지 적어 보세요."] };
ACT["S3211"] = { s: "This book is a collection of stories about Horrid Henry getting involved in various schemes while collecting gizmos, scaring Perfect Peter with the Mummy's Curse, starting a rumor about a shark in the swimming pool, and having trouble with his homework.",
  q: ["Name one thing Henry does in this collection of stories.",
      "Have you ever played a scary trick on someone, like Henry does to Peter?",
      "Write which of these stories you would most want to read, and why."],
  h: ["이 책에 나오는 이야기 중 헨리가 한 일을 한 가지 적어 보세요.",
      "나는 헨리가 피터에게 그랬던 것처럼 누군가에게 무서운 장난을 쳐 본 적이 있나요?",
      "이 이야기들 중에서 가장 읽고 싶은 이야기와 그 이유를 적어 보세요."] };
ACT["S3212"] = { s: "This book is a collection of stories about Horrid Henry preparing to establish his leadership over his babysitter, traumatizing his parents on a long car trip, going trick-or-treating at Halloween, and emerging victorious from a raid on Moody Margaret's Secret Club.",
  q: ["What does Henry try to do to his babysitter?",
      "Have you ever had a babysitter? What was it like?",
      "Write which story in this book sounds the most fun to you."],
  h: ["헨리는 베이비시터에게 어떤 일을 하려고 하나요?",
      "나는 베이비시터를 만나 본 적이 있나요? 어땠나요?",
      "이 책 이야기 중 가장 재미있을 것 같은 이야기를 적어 보세요."] };
ACT["S3213"] = { s: "This book is a collection of stories about Horrid Henry: reading Peter's diary; tricking his mother into buying him sneakers on a shopping trip; trying to win the class soccer match by any means necessary; trembling when his old sworn enemy Bossy Bill shows up at school.",
  q: ["What does Henry do to try to win the class soccer match?",
      "Have you ever played on a sports team? What position did you play?",
      "Write what you think happens when Bossy Bill shows up at school."],
  h: ["헨리는 반 축구 시합에서 이기려고 무엇을 하나요?",
      "나는 스포츠 팀에서 뛰어 본 적이 있나요? 무슨 자리를 맡았나요?",
      "보시 빌이 학교에 나타나면 무슨 일이 일어날지 적어 보세요."] };
ACT["S3214"] = { s: "This book contains four stories that follow the adventures of Horrid Henry, including tormenting his younger brother Perfect Peter, ruining Moody Margaret's sleepover, irritating his teacher, and trying to trick his family into seeing his favorite band.",
  q: ["Name one thing Henry does to Perfect Peter or Moody Margaret in this book.",
      "Have you ever wanted to see your favorite band or singer perform?",
      "Write which of these four stories you would want to read first."],
  h: ["헨리가 동생 퍼펙트 피터나 무디 마거릿에게 한 일을 한 가지 적어 보세요.",
      "나는 내가 좋아하는 밴드나 가수의 공연을 보고 싶었던 적이 있나요?",
      "이 네 가지 이야기 중 가장 먼저 읽고 싶은 것을 적어 보세요."] };
ACT["S3215"] = { s: "Stories in this book recount the adventures of Horrid Henry trying to trick the Tooth Fairy into giving him more money, causing his teachers to run screaming from school, and doing other horrible acts.",
  q: ["What does Henry try to trick the Tooth Fairy into doing?",
      "Have you ever lost a tooth? What did you do with it?",
      "Write what trick you would try on the Tooth Fairy if you were Henry."],
  h: ["헨리는 이빨 요정을 속여서 무엇을 하려고 하나요?",
      "나는 이가 빠진 적이 있나요? 빠진 이는 어떻게 했나요?",
      "내가 헨리라면 이빨 요정에게 어떤 꾀를 쓸지 적어 보세요."] };
ACT["S3216"] = { s: "This book is a collection of stories about Horrid Henry- finding more trouble to get into while campaigning for student president; performing with a magician; battling with his brother over who gets the green dinosaur; taking control of the remote.",
  q: ["What does Henry campaign for in this book?",
      "Have you ever fought with a sibling or friend over a toy?",
      "Write what you think happens when Henry performs with the magician."],
  h: ["헨리는 이 책에서 무엇이 되려고 선거 운동을 하나요?",
      "나는 형제나 친구와 장난감을 두고 다퉈 본 적이 있나요?",
      "헨리가 마술사와 함께 공연할 때 무슨 일이 일어날지 적어 보세요."] };
ACT["S3217"] = { s: "This book is a collection of stories about a Christmas play livened up by Horrid Henry's antics and other horrid acts.",
  q: ["What event does Henry liven up in this book?",
      "Have you ever been in a school play or performance?",
      "Write one funny thing you imagine Henry does during the Christmas play."],
  h: ["헨리는 이 책에서 어떤 행사를 더 신나게 만드나요?",
      "나는 학교 연극이나 공연에 나가 본 적이 있나요?",
      "헨리가 크리스마스 연극에서 벌였을 만한 재미있는 일을 상상해서 적어 보세요."] };
ACT["S3218"] = { s: "Stories in this book recount the adventures of Horrid Henry- using a stinkbomb as a toxic weapon in his war with Moody Margaret; going on a sleepover; using tricks to win the school reading competition; having the joy of seeing his teacher in hot water with the principal.",
  q: ["What weapon does Henry use in his war with Moody Margaret?",
      "Have you ever gone to a sleepover? What did you do there?",
      "Write what trick you think Henry uses to win the reading competition."],
  h: ["헨리는 무디 마거릿과의 싸움에서 어떤 무기를 쓰나요?",
      "나는 친구 집에서 자 본 적이 있나요? 무엇을 했나요?",
      "헨리가 독서 대회에서 이기려고 어떤 꾀를 냈을지 적어 보세요."] };
ACT["S3219"] = { s: "This book contains four stories in which Horrid Henry accidentally wears girls' underpants to school; tries to prove he is sicker than his brother; writes the meanest thank-you cards ever; does other horrible acts.",
  q: ["What embarrassing mistake does Henry make at school?",
      "Have you ever made an embarrassing mistake in front of your class?",
      "Write what you think Henry writes in his meanest thank-you cards."],
  h: ["헨리는 학교에서 어떤 창피한 실수를 하나요?",
      "나는 반 친구들 앞에서 창피한 실수를 한 적이 있나요?",
      "헨리가 가장 심술궂은 감사 카드에 무엇을 썼을지 적어 보세요."] };
ACT["S3220"] = { s: "Small Bad Wolf is determined to be bad like his father, Big Bad Wolf. But when the lazy older wolf gives lessons, the training does not turn out as planned.",
  q: ["What does Small Bad Wolf want to learn from his father?",
      "Have you ever tried to learn something from a parent or older family member?",
      "Write what you think goes wrong with the training."],
  h: ["아기 나쁜 늑대는 아빠에게서 무엇을 배우고 싶어 하나요?",
      "나는 부모님이나 어른 가족에게서 무언가를 배우려고 한 적이 있나요?",
      "훈련이 왜 계획대로 되지 않았을지 적어 보세요."] };
ACT["S3221"] = { s: "Miss Bruce, the new student teacher in Jake's second-grade class, never smiles. Jake is determined to make Miss Bruce laugh. But things get out of hand, and he finds himself in big trouble.",
  q: ["What is Jake determined to do to Miss Bruce?",
      "Have you ever tried to make someone laugh who seemed very serious?",
      "Write what kind of trouble you think Jake gets into."],
  h: ["제이크는 미스 브루스에게 무엇을 시도하나요?",
      "나는 아주 진지해 보이는 사람을 웃겨 보려고 한 적이 있나요?",
      "제이크가 어떤 곤란한 일에 빠졌을지 적어 보세요."] };
ACT["S3222"] = { s: "When Stink discovers that Pluto has been downgraded from a planet to a dwarf planet, he launches a campaign in his classroom to restore its status.",
  q: ["What does Stink launch a campaign to do?",
      "Have you ever wanted to change something you thought was unfair?",
      "Write your opinion: should Pluto be called a planet again?"],
  h: ["스팅크는 무엇을 되돌리려고 캠페인을 시작하나요?",
      "나는 불공평하다고 생각한 것을 바꾸고 싶었던 적이 있나요?",
      "명왕성을 다시 행성이라고 불러야 한다고 생각하는지 내 의견을 적어 보세요."] };
ACT["S3223"] = { s: "Stink's parents tell Stink that he must play a sport after he gets an unsatisfactory grade in physical education, so he masters thumb wrestling, as seen on a sports channel.",
  q: ["What activity does Stink decide to master to satisfy his parents?",
      "Have you ever practiced a game or sport until you got good at it?",
      "Write what you think happens in the thumb-wrestling smackdown."],
  h: ["스팅크는 부모님을 만족시키려고 무엇을 잘하려고 연습하나요?",
      "나는 게임이나 운동을 잘할 때까지 연습해 본 적이 있나요?",
      "엄지 씨름 대결에서 무슨 일이 일어날지 적어 보세요."] };
ACT["S3224"] = { s: "Stink and his friends try to earn money to buy the latest book in the Nightmare on Zombie Street series and go to the book release party.",
  q: ["What are Stink and his friends trying to earn money for?",
      "Have you ever saved money to buy something you really wanted?",
      "Write what you think happens at the midnight zombie walk."],
  h: ["스팅크와 친구들은 무엇을 사려고 돈을 모으나요?",
      "나는 정말 갖고 싶은 것을 사려고 돈을 모아 본 적이 있나요?",
      "한밤중 좀비 걷기 행사에서 무슨 일이 일어날지 적어 보세요."] };
ACT["S3225"] = { s: "When her classmate Jessica's picture is on the front page of the newspaper, Judy gets jealous. Book #2",
  q: ["Why does Judy get jealous of Jessica?",
      "Have you ever felt jealous of a friend? What happened?",
      "Write what you think Judy does because she feels jealous."],
  h: ["주디는 왜 제시카를 질투하게 되나요?",
      "나는 친구를 질투해 본 적이 있나요? 어떤 일이 있었나요?",
      "질투가 나서 주디가 어떤 행동을 했을지 적어 보세요."] };
ACT["S3226"] = { s: "Her substitute teacher realizes Judy is struggling in math and sends her to a math tutor at the local college. Soon Judy is completely into the spirit of college life. Book #8",
  q: ["Why does Judy get sent to a math tutor?",
      "Have you ever gotten extra help with a subject that was hard for you?",
      "Write what you imagine college life looks like for Judy."],
  h: ["주디는 왜 수학 과외 선생님에게 보내지나요?",
      "나는 어려운 과목에서 도움을 받아 본 적이 있나요?",
      "주디가 겪는 대학 생활이 어떨지 상상해서 적어 보세요."] };
ACT["S3227"] = { s: "After a close encounter with a mutant amphibian makes him freaky for frogs, Stink who is afraid of water becomes a swimming success.",
  q: ["What is Stink afraid of at the start of the book?",
      "Have you ever been afraid of something and then overcome that fear?",
      "Write what you think helps Stink become good at swimming."],
  h: ["스팅크는 이 책 처음에 무엇을 무서워하나요?",
      "나는 무언가를 무서워했다가 극복해 본 적이 있나요?",
      "스팅크가 수영을 잘하게 되는 데 무엇이 도움이 되었을지 적어 보세요."] };
ACT["S3228"] = { s: "When Stink's parents gain tickets for the whole family to sleep over at the aquarium, it sounds like a science freak's dream come true.",
  q: ["Where does Stink's family get to sleep over?",
      "Have you ever slept somewhere unusual, like a museum or a tent?",
      "Write what you would want to see if you slept over at an aquarium."],
  h: ["스팅크 가족은 어디서 자고 오게 되나요?",
      "나는 박물관이나 텐트처럼 특별한 곳에서 자 본 적이 있나요?",
      "수족관에서 잔다면 무엇을 보고 싶은지 적어 보세요."] };
ACT["S3229"] = { s: "Will Stink be able to control his homegrown slime mold, or will it take over his pets, his room, his house, and the world?",
  q: ["What has Stink grown that might take over his house?",
      "Have you ever grown or made something that got bigger than you expected?",
      "Write what you think happens to Stink's slime mold."],
  h: ["스팅크가 기른 것 중 집을 뒤덮을지도 모르는 것은 무엇인가요?",
      "나는 무언가를 기르거나 만들었는데 생각보다 커진 적이 있나요?",
      "스팅크의 점균이 어떻게 될지 적어 보세요."] };
ACT["S3230"] = { s: "Stink is faced with a difficult choice: hang out at home with his sister, Judy, or join a camp about Shakespeare's play.",
  q: ["What two choices does Stink have to choose between?",
      "Have you ever had to choose between two things you both wanted to do?",
      "Write which choice you think Stink should make, and why."],
  h: ["스팅크는 어떤 두 가지 중 하나를 골라야 하나요?",
      "나는 둘 다 하고 싶은 일 중에서 하나를 골라야 했던 적이 있나요?",
      "스팅크가 어떤 선택을 해야 할지 이유와 함께 적어 보세요."] };
ACT["S3231"] = { s: "Andy and Terry upgrade their top-secret and fantastic treehouse by adding thirteen stories.",
  q: ["How many stories do Andy and Terry add to their treehouse?",
      "Have you ever built or imagined your own treehouse?",
      "Write what you would put in your own dream treehouse."],
  h: ["앤디와 테리는 트리하우스에 몇 층을 더 짓나요?",
      "나는 나만의 트리하우스를 만들거나 상상해 본 적이 있나요?",
      "내가 꿈꾸는 트리하우스에는 무엇을 넣고 싶은지 적어 보세요."] };
ACT["S3232"] = { s: "When Katie plans to go to Suzanne's all-girl-sleepover party, Jeremy, who wants her to ride the hot new rollercoaster, gets annoyed. All the boys in her class decide that all girls have cooties. Katie tries to reunite the boys and girls when she finds herself in Jeremy's shoes-literally.  Book #4",
  q: ["What do all the boys in Katie's class decide about girls?",
      "Have you ever seen a disagreement between two groups of friends?",
      "Write what you think Katie does to bring the boys and girls back together."],
  h: ["케이티 반의 남자아이들은 여자아이들에 대해 무엇이라고 결론짓나요?",
      "나는 친구 그룹끼리 다투는 것을 본 적이 있나요?",
      "케이티가 남자아이들과 여자아이들을 다시 화해시키려고 무엇을 했을지 적어 보세요."] };
ACT["S3233"] = { s: "During the Science Camp, Katie magically turns into the strict Head Counselor. While on a hike, she gets to lead her class and ends up getting lost. Book #6",
  q: ["Who does Katie turn into during Science Camp?",
      "Have you ever gotten lost, or been the one leading a group?",
      "Write what you think Katie does to find her way back."],
  h: ["케이티는 과학 캠프에서 누구로 변하나요?",
      "나는 길을 잃어 본 적이 있나요, 아니면 무리를 이끌어 본 적이 있나요?",
      "케이티가 길을 다시 찾으려고 무엇을 했을지 적어 보세요."] };
ACT["S3234"] = { s: "Katie magically turns into Becky, a new girl at school, and realizes Becky is just trying to fit in by being a copycat of Suzanne. Book #7",
  q: ["Why is Becky copying Suzanne?",
      "Have you ever tried to fit in by copying someone else?",
      "Write your advice for Becky on how to fit in without copying."],
  h: ["베키는 왜 수잔을 따라 하나요?",
      "나는 다른 사람을 따라 하면서 어울리려고 했던 적이 있나요?",
      "베키에게 따라 하지 않고도 잘 어울릴 방법을 조언해 적어 보세요."] };
ACT["S3235"] = { s: "Her strict teacher moves next door to Katie. She scares her friends away and insists on keeping her dog on a leash at all times. Katie turns into her dog Pepper when the magical wind blows. Book #8",
  q: ["What animal does Katie turn into in this book?",
      "Have you ever imagined what it would be like to be a pet?",
      "Write what you think it feels like to be Pepper the dog."],
  h: ["케이티는 이 책에서 어떤 동물로 변하나요?",
      "나는 애완동물이 된다면 어떨지 상상해 본 적이 있나요?",
      "강아지 페퍼가 되면 어떤 기분일지 적어 보세요."] };
ACT["S3236"] = { s: "Katie has never cooked a thing alone before. But she switches into the chef Louie at a pizza parlor that sponsors a pizza-eating contest. Book #9",
  q: ["What job does Katie find herself doing in this book?",
      "Have you ever tried cooking or baking something?",
      "Write what you think happens at the pizza-eating contest."],
  h: ["케이티는 이 책에서 어떤 일을 맡게 되나요?",
      "나는 요리나 베이킹을 해 본 적이 있나요?",
      "피자 먹기 대회에서 무슨 일이 일어날지 적어 보세요."] };
ACT["S3237"] = { s: "Katie gets very excited to know that a movie is being filmed in their town. And best of all, the star of the movie is the world's most popular child actress-Rosie Moran. When the magical wind blows, Katie turns into Rosie while she is filming. Book #10",
  q: ["Who does Katie turn into while the movie is being filmed?",
      "Have you ever wanted to be in a movie?",
      "Write what you think happens when Katie tries to act as Rosie."],
  h: ["영화를 찍는 동안 케이티는 누구로 변하나요?",
      "나는 영화에 나오고 싶었던 적이 있나요?",
      "케이티가 로지로서 연기할 때 무슨 일이 일어날지 적어 보세요."] };
ACT["S3238"] = { s: "Katie's teacher hopes to win the 'Teacher of the Year Contest.' But when Katie turns into her and fails to control the class, her chances do not look good. Book #11",
  q: ["What does Katie's teacher hope to win?",
      "Have you ever tried to be in charge of a group and found it hard?",
      "Write what you think happens to the teacher's chances after this."],
  h: ["케이티의 선생님은 무엇을 타고 싶어 하나요?",
      "나는 모둠을 이끌어 보려다가 힘들었던 적이 있나요?",
      "이 일 이후 선생님이 상을 받을 가능성이 어떻게 될지 적어 보세요."] };
ACT["S3239"] = { s: "When Katie's class goes on a field trip to the natural history museum, she finds herself magically transported into the body of their tour guide. Book #12",
  q: ["Where does Katie's class go on a field trip?",
      "Have you ever been on a field trip to a museum?",
      "Write what you would want to show visitors if you were a museum tour guide."],
  h: ["케이티 반은 현장 학습으로 어디에 가나요?",
      "나는 박물관으로 현장 학습을 가 본 적이 있나요?",
      "내가 박물관 안내원이라면 방문객에게 무엇을 보여 주고 싶은지 적어 보세요."] };
ACT["S3240"] = { s: "In this book, Katie turns into her unfair track coach and gives every kid on the team a chance to compete, including the slowest runner in her class. Book #13",
  q: ["What does Katie do differently as the track coach?",
      "Have you ever competed in a race? How did it go?",
      "Write why you think it is fair to give every kid a chance to compete."],
  h: ["케이티는 육상 코치가 되어 원래와 다르게 무엇을 하나요?",
      "나는 달리기 경주에 나가 본 적이 있나요? 어땠나요?",
      "모든 아이에게 경기할 기회를 주는 것이 왜 공평한지 내 생각을 적어 보세요."] };
ACT["S3241"] = { s: "When her best friend Suzanne becomes a total snob, Katie declares that she and Suzanne are friends for never! Then Katie magically turns into Suzanne- the moment when Suzanne is about to make her modeling debut! Book #14",
  q: ["What does Katie declare about her friendship with Suzanne?",
      "Have you ever had a big fight with a best friend?",
      "Write what you think happens when Katie is Suzanne at her modeling debut."],
  h: ["케이티는 수잔과의 우정에 대해 무엇이라고 선언하나요?",
      "나는 가장 친한 친구와 크게 다퉈 본 적이 있나요?",
      "케이티가 수잔이 되어 모델 데뷔를 할 때 무슨 일이 일어날지 적어 보세요."] };
ACT["S3242"] = { s: "Katie is the kind of person who dislikes the \"mushy gushy stuff\" of Valentine's Day. When the magic wind turns Katie into a candy store owner, she mixes up the \"love messages\" on the candy hearts. Book #15",
  q: ["What does Katie mix up while she is the candy store owner?",
      "Have you ever given or received a Valentine's Day card?",
      "Write what funny message you would put on a candy heart."],
  h: ["케이티는 사탕 가게 주인이 되어 무엇을 뒤섞어 버리나요?",
      "나는 밸런타인데이 카드를 주거나 받아 본 적이 있나요?",
      "내가 사탕 하트에 적고 싶은 재미있는 메시지를 적어 보세요."] };
ACT["S3243"] = { s: "Katie and Suzanne are desperate to get the concert tickets for their favorite band, the Bayside Boys, that will perform in Cherrydale. But when the magic wind blows and turns Katie into one of the Boys, she causes the band to break up. Book #16",
  q: ["What happens to the band when Katie turns into one of the Boys?",
      "Have you ever really wanted tickets to see your favorite singer or band?",
      "Write what you think Katie does to try to fix the band before it breaks up."],
  h: ["케이티가 밴드 멤버로 변하자 밴드에 무슨 일이 일어나나요?",
      "나는 내가 좋아하는 가수나 밴드의 콘서트 표를 정말 갖고 싶었던 적이 있나요?",
      "밴드가 깨지기 전에 케이티가 무엇을 했을지 적어 보세요."] };
ACT["S3244"] = { s: "Katie is so excited that her favorite author, Nellie Farrow, is in her class to tell them all about her new book. But when Nellie is about to give her presentation, Katie turns into her. Book #17",
  q: ["Who visits Katie's class, and who does Katie turn into?",
      "Have you ever met an author or someone you admire?",
      "Write what you think Katie says during the presentation as Nellie."],
  h: ["케이티 반에 누가 찾아오고, 케이티는 누구로 변하나요?",
      "나는 존경하는 작가나 사람을 만나 본 적이 있나요?",
      "케이티가 넬리가 되어 발표할 때 무슨 말을 했을지 적어 보세요."] };
ACT["S3245"] = { s: "Kevin, who thinks he's the best yellow belt, can't wait for his big karate match. But the magic wind turns Katie into Kevin just before his big match and threatens his chances of beating the competition. Book #18",
  q: ["What is Kevin looking forward to before Katie turns into him?",
      "Have you ever taken part in a martial arts class or a sports match?",
      "Write what you think happens when Katie fights the match as Kevin."],
  h: ["케이티가 케빈으로 변하기 전 케빈은 무엇을 기대하고 있나요?",
      "나는 무술 수업이나 스포츠 시합에 참가해 본 적이 있나요?",
      "케이티가 케빈이 되어 시합할 때 무슨 일이 일어날지 적어 보세요."] };
ACT["S3246"] = { s: "The magic wind turns Katie into George, who plays practical jokes to liven up their school. Katie has to figure out how to get him out of trouble and soothe everyone's hurt feelings. Book #19",
  q: ["What does George like to do that gets Katie into trouble?",
      "Have you ever played a practical joke, or had one played on you?",
      "Write what you think Katie does to soothe everyone's hurt feelings."],
  h: ["조지가 즐겨 하는 일 때문에 케이티는 어떤 곤란에 빠지나요?",
      "나는 장난을 쳐 본 적이 있나요, 아니면 장난을 당해 본 적이 있나요?",
      "케이티가 사람들의 속상한 마음을 달래려고 무엇을 했을지 적어 보세요."] };
ACT["S3247"] = { s: "Katie is concerned when she hears that Selena is using live mice in a science fair project. When Katie turns into Selena on the day of the fair, she plans to set the mice free. Book #20",
  q: ["What does Katie plan to do with the mice when she becomes Selena?",
      "Have you ever felt worried about how an animal was being treated?",
      "Write what you think happens when Katie tries to set the mice free."],
  h: ["케이티는 셀레나가 되어 쥐들을 어떻게 하려고 하나요?",
      "나는 동물이 대우받는 모습을 보고 걱정한 적이 있나요?",
      "케이티가 쥐들을 풀어 주려고 할 때 무슨 일이 일어날지 적어 보세요."] };
ACT["S3248"] = { s: "Jack and Annie travel back in time to medieval England via a magic tree house. Book #2",
  q: ["Where and when do Jack and Annie travel to in this book?",
      "Have you ever imagined traveling back in time?",
      "Write what you think Jack and Annie see in medieval England."],
  h: ["잭과 애니는 이 책에서 언제, 어디로 여행하나요?",
      "나는 과거로 시간 여행하는 것을 상상해 본 적이 있나요?",
      "잭과 애니가 중세 영국에서 무엇을 보았을지 적어 보세요."] };
ACT["S3249"] = { s: "Jack and Annie set on an adventure in their tree house back to ancient Egypt. There the children help a queen's mummy continue her voyage to the Next Life. Book #3",
  q: ["Who do Jack and Annie help in ancient Egypt?",
      "Have you ever learned about ancient Egypt or mummies?",
      "Write what you think the queen's journey to the Next Life is like."],
  h: ["잭과 애니는 고대 이집트에서 누구를 돕나요?",
      "나는 고대 이집트나 미라에 대해 배워 본 적이 있나요?",
      "여왕의 사후 세계로의 여행이 어떨지 상상해서 적어 보세요."] };
ACT["S3250"] = { s: "The magic tree house takes Jack and Annie back to the days of deserted islands, secret maps, hidden treasure, and ruthless pirates. Will the children find a buried treasure? Book #4",
  q: ["What are Jack and Annie searching for in this book?",
      "Have you ever imagined finding buried treasure?",
      "Write what you think is inside the treasure they find."],
  h: ["잭과 애니는 이 책에서 무엇을 찾고 있나요?",
      "나는 묻힌 보물을 찾는 상상을 해 본 적이 있나요?",
      "그들이 찾은 보물 안에 무엇이 있을지 적어 보세요."] };
ACT["S3251"] = { s: "The magic tree house whisks Jack and Annie back to ancient Japan where they encounter a ninja master. Book #5",
  q: ["Who do Jack and Annie meet in ancient Japan?",
      "Have you ever learned about ninjas before?",
      "Write what you think the ninja master teaches Jack and Annie."],
  h: ["잭과 애니는 고대 일본에서 누구를 만나나요?",
      "나는 닌자에 대해 배워 본 적이 있나요?",
      "닌자 스승이 잭과 애니에게 무엇을 가르쳤을지 적어 보세요."] };
ACT["S3252"] = { s: "Jack, Annie, and Peanut the mouse travels in a magic tree house and find themselves lost in the Amazon rainforest where fierce wild animals reside. Will they find their way back home? Book #6",
  q: ["Who travels with Jack and Annie in this book?",
      "Have you ever been lost, even for a short time?",
      "Write what animal you think they meet in the Amazon rainforest."],
  h: ["이 책에서 잭과 애니와 함께 여행하는 것은 누구인가요?",
      "나는 잠깐이라도 길을 잃어 본 적이 있나요?",
      "아마존 밀림에서 만났을 동물을 상상해서 적어 보세요."] };
ACT["S3253"] = { s: "The magic tree house takes Jack and Annie on an adventure to the Ice Age, the time of Cro-Magnons and woolly mammoths. Book #7",
  q: ["What time period do Jack and Annie travel to in this book?",
      "Have you ever seen a picture of a woolly mammoth?",
      "Write what you think it would be like to meet a Cro-Magnon person."],
  h: ["잭과 애니는 이 책에서 어느 시대로 여행하나요?",
      "나는 털매머드 사진을 본 적이 있나요?",
      "크로마뇽인을 만난다면 어떨지 상상해서 적어 보세요."] };
ACT["S3254"] = { s: "The magic tree house transports Jack and Annie to a moon base in the future. They need to find the fourth thing that they need to free their friend Morgan from the magic spell. Book #8",
  q: ["What are Jack and Annie trying to find to free Morgan?",
      "Have you ever had to find something to help a friend?",
      "Write what you think the fourth thing might be."],
  h: ["잭과 애니는 모건을 구하려고 무엇을 찾고 있나요?",
      "나는 친구를 돕기 위해 무언가를 찾아본 적이 있나요?",
      "그 네 번째 물건이 무엇일지 상상해서 적어 보세요."] };
ACT["S3255"] = { s: "The magic tree house sends Jack and Annie back to the wild west. The children try to solve a riddle while they experience excitement and danger. Book #10",
  q: ["What do Jack and Annie try to solve in the wild west?",
      "Have you ever tried to solve a riddle?",
      "Write your own riddle that Jack and Annie might have to solve."],
  h: ["잭과 애니는 서부 시대에서 무엇을 풀려고 하나요?",
      "나는 수수께끼를 풀어 본 적이 있나요?",
      "잭과 애니가 풀어야 할 것 같은 수수께끼를 내가 만들어서 적어 보세요."] };
ACT["S3256"] = { s: "The magic tree house whisks Jack and Annie off to Africa. On their adventure, they encounter some wonderful animals, and they even solve a mystery. Book #11",
  q: ["What continent do Jack and Annie travel to in this book?",
      "Have you ever seen lions or other African animals at a zoo?",
      "Write what mystery you think Jack and Annie solve in Africa."],
  h: ["잭과 애니는 이 책에서 어느 대륙으로 여행하나요?",
      "나는 동물원에서 사자나 아프리카 동물을 본 적이 있나요?",
      "잭과 애니가 아프리카에서 푼 수수께끼가 무엇일지 적어 보세요."] };
ACT["S3257"] = { s: "In their magic tree house, Jack and Annie travel to the Arctic. In the adventure, a polar bear leads the children onto very thin ice. Book #12",
  q: ["What animal leads Jack and Annie onto thin ice?",
      "Have you ever walked on ice or thick snow?",
      "Write what you think happens next when they are on the thin ice."],
  h: ["어떤 동물이 잭과 애니를 얇은 얼음 위로 이끄나요?",
      "나는 얼음이나 두꺼운 눈 위를 걸어 본 적이 있나요?",
      "얇은 얼음 위에서 무슨 일이 일어날지 적어 보세요."] };
ACT["S3258"] = { s: "In their magic tree house, Jack and Annie travel to the days of the Roman Empire just as Vesuvius is about to erupt. They rush in search of a Roman scroll before everything is buried in ash. Book #13",
  q: ["What are Jack and Annie racing to find before the volcano erupts?",
      "Have you ever had to hurry to finish something before time ran out?",
      "Write what you think happens right before Vesuvius erupts."],
  h: ["잭과 애니는 화산이 터지기 전에 무엇을 찾으려고 서두르나요?",
      "나는 시간이 다 되기 전에 무언가를 서둘러 끝내야 했던 적이 있나요?",
      "베수비오 화산이 터지기 직전에 무슨 일이 일어났을지 적어 보세요."] };
ACT["S3259"] = { s: "Jack and Annie are taken back 2000 years to ancient China by the magic tree house. They are on their mission to find the original copy of an old legend before the Imperial Library gets burned down by the evil king. Book #14",
  q: ["What are Jack and Annie trying to save before the library burns down?",
      "Have you ever tried to save or protect something important?",
      "Write what you think happens if the evil king finds them."],
  h: ["잭과 애니는 도서관이 불타기 전에 무엇을 지키려고 하나요?",
      "나는 소중한 것을 지키려고 애써 본 적이 있나요?",
      "사악한 왕이 그들을 찾아내면 무슨 일이 일어날지 적어 보세요."] };
ACT["S3260"] = { s: "Their magic tree house transports Jack and Annie back to a monastery in medieval Ireland. There they attempt to retrieve a lost book while being menaced by Viking raiders. Book #15",
  q: ["What are Jack and Annie trying to retrieve in medieval Ireland?",
      "Have you ever tried to find something that was lost?",
      "Write what you think happens when the Viking raiders appear."],
  h: ["잭과 애니는 중세 아일랜드에서 무엇을 되찾으려고 하나요?",
      "나는 잃어버린 물건을 찾아본 적이 있나요?",
      "바이킹 약탈자들이 나타나면 무슨 일이 일어날지 적어 보세요."] };
ACT["S3261"] = { s: "The magic tree house takes Jack and Annie to the deck of the \"Titanic\" where they have to find a mysterious gift that will free their puppy from a terrible magic spell. Book #17",
  q: ["What ship do Jack and Annie visit in this book?",
      "Have you ever heard the story of the Titanic before?",
      "Write what you think the mysterious gift turns out to be."],
  h: ["잭과 애니는 이 책에서 어떤 배를 방문하나요?",
      "나는 타이타닉호 이야기를 들어 본 적이 있나요?",
      "그 신비한 선물이 무엇일지 적어 보세요."] };
ACT["S3262"] = { s: "The magic tree house whisks Jack and Annie off to the Great Plains. There they learn about the life of the Lakota Indians. Book #18",
  q: ["Who do Jack and Annie learn about on the Great Plains?",
      "Have you ever learned about a Native American tribe in school?",
      "Write one thing you would want to learn about the Lakota way of life."],
  h: ["잭과 애니는 대평원에서 누구에 대해 배우나요?",
      "나는 학교에서 아메리카 원주민 부족에 대해 배워 본 적이 있나요?",
      "라코타 사람들의 생활에 대해 알고 싶은 것을 한 가지 적어 보세요."] };
ACT["S3263"] = { s: "The magic tree house takes Jack and Annie to India. They are on a mission to get a gift to help free the dog Teddy from a spell. Book #19",
  q: ["What country do Jack and Annie travel to in this book?",
      "Have you ever helped take care of or rescue an animal?",
      "Write what gift you think will free Teddy from the spell."],
  h: ["잭과 애니는 이 책에서 어느 나라로 여행하나요?",
      "나는 동물을 돌보거나 구하는 것을 도와본 적이 있나요?",
      "테디를 마법에서 풀어 줄 선물이 무엇일지 적어 보세요."] };
ACT["S3264"] = { s: "The magic tree house takes Jack and Annie away to Australia. They are on a mission to save some animals from wildfire. Book #20",
  q: ["What are Jack and Annie trying to save in Australia?",
      "Have you ever heard about a wildfire on the news?",
      "Write what you think Jack and Annie do to save the animals."],
  h: ["잭과 애니는 호주에서 무엇을 구하려고 하나요?",
      "나는 뉴스에서 산불 소식을 들어 본 적이 있나요?",
      "잭과 애니가 동물들을 구하려고 무엇을 했을지 적어 보세요."] };
ACT["S3265"] = { s: "The magic tree house transports Jack and Annie to the time of the Civil War. The children encounter the famous nurse, Clara Barton. Book #21",
  q: ["Who do Jack and Annie meet during the Civil War?",
      "Have you ever learned about nurses who help people in wars?",
      "Write what you think Clara Barton teaches Jack and Annie."],
  h: ["잭과 애니는 남북전쟁 때 누구를 만나나요?",
      "나는 전쟁에서 사람들을 돕는 간호사에 대해 배워 본 적이 있나요?",
      "클라라 바턴이 잭과 애니에게 무엇을 가르쳤을지 적어 보세요."] };
ACT["S3266"] = { s: "The magic tree house takes Jack and Annie back to the Kansas prairie where they must find \"something to learn.\" Book #23",
  q: ["What are Jack and Annie searching for on the Kansas prairie?",
      "Have you ever experienced strong wind or a storm?",
      "Write what you think the \"something to learn\" turns out to be."],
  h: ["잭과 애니는 캔자스 초원에서 무엇을 찾아야 하나요?",
      "나는 강한 바람이나 폭풍을 겪어 본 적이 있나요?",
      "그 '배워야 할 것'이 무엇일지 적어 보세요."] };
ACT["S3267"] = { s: "Jack and Annie get transported by the magic tree house to San Francisco in 1906 where they experience one of the biggest earthquakes the United States had ever known. Book #24",
  q: ["What natural disaster do Jack and Annie experience in San Francisco?",
      "Have you ever felt an earthquake, even a small one?",
      "Write what you think Jack and Annie do to stay safe during the earthquake."],
  h: ["잭과 애니는 샌프란시스코에서 어떤 자연재해를 겪나요?",
      "나는 작더라도 지진을 느껴 본 적이 있나요?",
      "지진이 일어나는 동안 잭과 애니가 안전하게 있으려고 무엇을 했을지 적어 보세요."] };
ACT["S3268"] = { s: "The magic tree house sends Jack and Annie to Elizabethan London, and they encounter one of the greatest writers of all time, William Shakespeare. Book #25",
  q: ["Who do Jack and Annie meet in Elizabethan London?",
      "Have you ever been in or watched a play?",
      "Write what you would ask Shakespeare if you met him."],
  h: ["잭과 애니는 엘리자베스 시대 런던에서 누구를 만나나요?",
      "나는 연극에 나가거나 연극을 본 적이 있나요?",
      "셰익스피어를 만난다면 무엇을 물어보고 싶은지 적어 보세요."] };
ACT["S3269"] = { s: "Jack and Annie travel to an African rainforest in their magic tree house. They encounter a group of gorillas and learn to communicate with them. Book #26",
  q: ["What animals do Jack and Annie learn to communicate with?",
      "Have you ever watched gorillas at a zoo?",
      "Write what you think Jack and Annie say to the gorillas."],
  h: ["잭과 애니는 어떤 동물과 소통하는 법을 배우나요?",
      "나는 동물원에서 고릴라를 본 적이 있나요?",
      "잭과 애니가 고릴라에게 무슨 말을 했을지 적어 보세요."] };
ACT["S3270"] = { s: "The magic tree house takes Jack and Annie to the year 1621, where the siblings celebrate the first Thanksgiving with the Pilgrims in the New Plymouth Colony. Book #27",
  q: ["What event do Jack and Annie celebrate with the Pilgrims?",
      "Have you ever celebrated Thanksgiving with your family?",
      "Write what food you think was served at the first Thanksgiving."],
  h: ["잭과 애니는 청교도들과 함께 어떤 행사를 기념하나요?",
      "나는 가족과 추수감사절을 보내 본 적이 있나요?",
      "첫 추수감사절에 어떤 음식이 나왔을지 적어 보세요."] };
ACT["S3271"] = { s: "When Clarence starts a rumor that Marvin Redpost picks his nose, it spreads and makes everyone at school believe it. Will Marvin be doomed to be teased forever?",
  q: ["What rumor does Clarence start about Marvin?",
      "Have you ever had an untrue rumor spread about you or a friend?",
      "Write what you think Marvin does to stop the rumor."],
  h: ["클래런스는 마빈에 대해 어떤 소문을 퍼뜨리나요?",
      "나는 나나 친구에 대해 사실이 아닌 소문이 퍼진 적이 있나요?",
      "마빈이 소문을 멈추려고 무엇을 했을지 적어 보세요."] };
ACT["S3272"] = { s: "Casey tells Marvin that he'll turn into a girl if she kisses his elbow. When he accidentally kisses his elbow, he starts to think and act like a girl.",
  q: ["What does Casey tell Marvin will happen if he kisses his elbow?",
      "Have you ever believed something silly that a friend told you?",
      "Write what you think happens after Marvin starts acting like a girl."],
  h: ["케이시는 마빈이 팔꿈치에 입을 맞추면 무슨 일이 일어난다고 말하나요?",
      "나는 친구가 말한 엉뚱한 이야기를 믿어 본 적이 있나요?",
      "마빈이 여자아이처럼 행동하기 시작한 뒤 무슨 일이 일어날지 적어 보세요."] };
ACT["S3273"] = { s: "In this book, Marvin gets his first job as a 'dog sitter.' He is excited to take care of his teacher's dog while she's away. But when the dog starts to look sick, Marvin has to decide what to do.",
  q: ["What job does Marvin get in this book?",
      "Have you ever taken care of a pet, even for a short time?",
      "Write what you think Marvin should do when the dog looks sick."],
  h: ["마빈은 이 책에서 어떤 일을 맡게 되나요?",
      "나는 잠깐이라도 애완동물을 돌봐 본 적이 있나요?",
      "강아지가 아파 보일 때 마빈이 어떻게 해야 할지 적어 보세요."] };
ACT["S3274"] = { s: "Marvin sees a glowing green thing that looks like a flying birthday cake in the night sky. And after two days, a mysterious new boy with peculiar behavior joins his third-grade class.",
  q: ["What strange thing does Marvin see in the night sky?",
      "Have you ever seen something strange in the sky that you couldn't explain?",
      "Write who or what you think the mysterious new boy really is."],
  h: ["마빈은 밤하늘에서 어떤 이상한 것을 보나요?",
      "나는 설명할 수 없는 이상한 것을 하늘에서 본 적이 있나요?",
      "그 수상한 전학생이 누구일지 내 생각을 적어 보세요."] };
ACT["S3275"] = { s: "Although Marvin can't even climb onto the seat of his new mountain bike without wobbling, he accepts a challenge to ride down Suicide Hill and finds himself in a desperate situation when everyone is coming to see him.",
  q: ["What challenge does Marvin accept even though he can barely ride his bike?",
      "Have you ever accepted a challenge that turned out to be harder than you thought?",
      "Write what you think happens when Marvin rides down Suicide Hill."],
  h: ["마빈은 자전거도 잘 못 타면서 어떤 도전을 받아들이나요?",
      "나는 생각보다 어려웠던 도전을 받아들여 본 적이 있나요?",
      "마빈이 그 언덕을 내려갈 때 무슨 일이 일어날지 적어 보세요."] };
ACT["S3276"] = { s: "When his not-ordinary friend shares her magic crystal with Marvin, things get all mixed up.",
  q: ["What does Marvin's friend share with him?",
      "Have you ever borrowed or been given something unusual from a friend?",
      "Write what you think gets mixed up because of the crystal."],
  h: ["마빈의 친구는 마빈에게 무엇을 나눠 주나요?",
      "나는 친구에게 특별한 것을 빌리거나 받아 본 적이 있나요?",
      "그 수정 때문에 무엇이 뒤죽박죽될지 적어 보세요."] };
ACT["S3277"] = { s: "Nancy and her friends saddle up to find out how Buttons, the Shetland pony, keeps escaping from the new zoo.",
  q: ["What mystery does Nancy try to solve about Buttons the pony?",
      "Have you ever seen a pony or horse at a farm or zoo?",
      "Write how you think Buttons keeps escaping."],
  h: ["낸시는 조랑말 버튼즈에 관한 어떤 수수께끼를 풀려고 하나요?",
      "나는 농장이나 동물원에서 조랑말이나 말을 본 적이 있나요?",
      "버튼즈가 어떻게 계속 탈출하는지 내 생각을 적어 보세요."] };
ACT["S3278"] = { s: "Nancy and her friends are going to be in the Cinderella ballet. When the glass slippers disappear, Nancy is determined to find Cinderella's slippers.",
  q: ["What goes missing before the Cinderella ballet?",
      "Have you ever been in a play or dance recital?",
      "Write who you think took the glass slippers, and why."],
  h: ["신데렐라 발레 공연 전에 무엇이 사라지나요?",
      "나는 연극이나 무용 발표회에 나가 본 적이 있나요?",
      "누가, 왜 유리 구두를 가져갔을지 내 생각을 적어 보세요."] };
ACT["S3279"] = { s: "Nancy Drew set out to solve the mystery of their disappearing snowman, Sherlock, after Nancy's friend Deirdre's fortune-telling predictions start coming true.",
  q: ["What starts happening after Deirdre's fortune-telling predictions come true?",
      "Have you ever built a snowman that later melted or disappeared?",
      "Write what you think really happened to the snowman."],
  h: ["디어드리의 점괘가 맞아떨어지기 시작하면서 무슨 일이 일어나나요?",
      "나는 나중에 녹거나 사라진 눈사람을 만들어 본 적이 있나요?",
      "눈사람에게 정말로 무슨 일이 있었을지 적어 보세요."] };
ACT["S3280"] = { s: "The Clue Crew investigates the disappearance of dog biscuits from a basket belonging to a poodle named Lola.",
  q: ["What food goes missing in this mystery?",
      "Have you ever lost track of a pet's food or toy?",
      "Write who or what you think took Lola's dog biscuits."],
  h: ["이 사건에서 어떤 음식이 사라지나요?",
      "나는 애완동물의 먹이나 장난감을 잃어버린 적이 있나요?",
      "누가 롤라의 강아지 비스킷을 가져갔을지 내 생각을 적어 보세요."] };
ACT["S3281"] = { s: "When the circus performers are forced to go on without the important props, Nancy wonders if someone is clowning around with this circus. What Nancy and the Clue Crew discover proves that the circus really is the greatest show on Earth.",
  q: ["What do the circus performers lose before their show?",
      "Have you ever been to a circus or watched one on video?",
      "Write who you think is behind the missing circus props."],
  h: ["서커스 공연자들은 공연 전에 무엇을 잃어버리나요?",
      "나는 서커스에 가 보거나 영상으로 본 적이 있나요?",
      "사라진 서커스 소품 뒤에 누가 있을지 적어 보세요."] };
ACT["S3282"] = { s: "It's Halloween, and the girls visit the studio of their favorite TV show. With all the scary noises the Clue Crew keeps hearing and the creepy shadows that seem to be lurking, it seems like the studio is haunted.",
  q: ["What makes the girls think the TV studio is haunted?",
      "Have you ever been somewhere that felt spooky or scary?",
      "Write what you think is really causing the scary noises."],
  h: ["아이들은 왜 방송국 스튜디오가 귀신 들린 곳이라고 생각하나요?",
      "나는 으스스하고 무섭게 느껴진 곳에 가 본 적이 있나요?",
      "그 무서운 소리의 진짜 원인이 무엇일지 적어 보세요."] };
ACT["S3283"] = { s: "Nate helps Rosamond discover who has been tearing pages out of her books.",
  q: ["What mystery does Nate help Rosamond solve?",
      "Have you ever had a book of yours get damaged or torn?",
      "Write who you think is tearing the pages out of the books."],
  h: ["네이트는 로자먼드가 어떤 수수께끼를 풀도록 도와주나요?",
      "나는 내 책이 망가지거나 찢어진 적이 있나요?",
      "누가 책장을 찢고 있는지 내 생각을 적어 보세요."] };
ACT["S3284"] = { s: "Freddy rescues a baby bird that has fallen from its nest and has to find a way to get it to school without his mother or teacher noticing for show-and-tell.",
  q: ["What animal does Freddy rescue in this book?",
      "Have you ever tried to hide something from an adult, like Freddy does?",
      "Write how you think Freddy sneaks the bird into show-and-tell."],
  h: ["프레디는 이 책에서 어떤 동물을 구하나요?",
      "나는 프레디처럼 어른에게 무언가를 숨겨 본 적이 있나요?",
      "프레디가 새를 몰래 학교에 가져갈 방법을 적어 보세요."] };
ACT["S3285"] = { s: "Freddy is nervous about the first-grade Grandparents' Day talent show, especially with Max bullying and teasing him. Dad has an idea that might make Freddy a star.",
  q: ["Why is Freddy nervous about the talent show?",
      "Have you ever been nervous before performing in front of people?",
      "Write what idea you think Freddy's dad comes up with."],
  h: ["프레디는 왜 장기 자랑 대회를 앞두고 긴장하나요?",
      "나는 사람들 앞에서 공연하기 전에 긴장한 적이 있나요?",
      "프레디 아빠가 어떤 아이디어를 떠올렸을지 적어 보세요."] };
ACT["S3286"] = { s: "When first-grader Freddy is exhausted because of nightmares, his friends and family give him suggestions on how to deal with them.",
  q: ["Why is Freddy exhausted in this book?",
      "Have you ever had a nightmare? What did you do afterward?",
      "Write one suggestion you would give Freddy for dealing with nightmares."],
  h: ["프레디는 이 책에서 왜 지쳐 있나요?",
      "나는 악몽을 꾼 적이 있나요? 그 뒤에 무엇을 했나요?",
      "악몽을 이겨 내는 방법으로 프레디에게 해 줄 조언을 한 가지 적어 보세요."] };
ACT["S3287"] = { s: "Freddy and his classmates participate in a Bike-A-Thon to help raise money for a local animal shelter.",
  q: ["What event do Freddy and his classmates take part in?",
      "Have you ever ridden a bike for exercise or fun?",
      "Write what you would do to help raise money for an animal shelter."],
  h: ["프레디와 반 친구들은 어떤 행사에 참여하나요?",
      "나는 운동이나 재미로 자전거를 타 본 적이 있나요?",
      "동물 보호소를 도우려면 내가 무엇을 할 수 있을지 적어 보세요."] };
ACT["S3288"] = { s: "Freddy is apprehensive about the haunted house that Chloe plans to have at her Halloween party but tries to hide his fear from his classmates.",
  q: ["What is Freddy afraid of in this book?",
      "Have you ever tried to hide being scared in front of friends?",
      "Write what you think happens when Freddy goes into the haunted house."],
  h: ["프레디는 이 책에서 무엇을 무서워하나요?",
      "나는 친구들 앞에서 무서운 마음을 숨겨 본 적이 있나요?",
      "프레디가 귀신의 집에 들어가면 무슨 일이 일어날지 적어 보세요."] };
ACT["S3289"] = { s: "When Freddy has a chance to hold a fossilized shark's tooth for him for one week, he must think of a way to earn the fifty dollar price.",
  q: ["What does Freddy need fifty dollars for?",
      "Have you ever saved up money to buy or borrow something special?",
      "Write how you think Freddy earns the fifty dollars."],
  h: ["프레디는 50달러가 왜 필요한가요?",
      "나는 특별한 것을 사거나 빌리려고 돈을 모아 본 적이 있나요?",
      "프레디가 50달러를 어떻게 벌었을지 적어 보세요."] };
ACT["S3290"] = { s: "Freddy wants to give his best friend, Jessie, a special, secret valentine, but to do that, he must break some rules at home and avoid the bully at school.",
  q: ["Who does Freddy want to give a secret valentine to?",
      "Have you ever given someone a card or gift in secret?",
      "Write what rule you think Freddy has to break to give the valentine."],
  h: ["프레디는 누구에게 비밀 밸런타인 카드를 주고 싶어 하나요?",
      "나는 누군가에게 몰래 카드나 선물을 준 적이 있나요?",
      "프레디가 카드를 주려고 어떤 규칙을 어겼을지 적어 보세요."] };
ACT["S3291"] = { s: "When Freddy's mother finally allows him to bring Harold the class hamster home for the weekend, Freddy has his hands full making sure that Harold does not escape.",
  q: ["What pet does Freddy bring home for the weekend?",
      "Have you ever taken care of a class pet?",
      "Write what you think happens when Harold tries to escape."],
  h: ["프레디는 주말에 어떤 반려동물을 집에 데려가나요?",
      "나는 학급 동물을 돌봐 본 적이 있나요?",
      "해럴드가 탈출하려고 할 때 무슨 일이 일어날지 적어 보세요."] };
ACT["S3292"] = { s: "Freddy decides to bake 100 cookies for the one hundredth day of school celebration, but his father accidentally eats one.",
  q: ["How many cookies does Freddy bake, and why?",
      "Have you ever baked something for a school celebration?",
      "Write what you think Freddy does after his father eats a cookie."],
  h: ["프레디는 왜, 그리고 몇 개의 쿠키를 굽나요?",
      "나는 학교 행사를 위해 무언가를 구워 본 적이 있나요?",
      "아빠가 쿠키를 먹은 뒤 프레디가 어떻게 했을지 적어 보세요."] };
ACT["S3293"] = { s: "Freddy who is afraid of the dark, is apprehensive about going on a wilderness camping trip.",
  q: ["What is Freddy afraid of before the camping trip?",
      "Have you ever gone camping, or been afraid of the dark?",
      "Write what you would tell Freddy to help him feel braver."],
  h: ["프레디는 캠핑을 가기 전에 무엇을 무서워하나요?",
      "나는 캠핑을 가 본 적이 있거나, 어둠을 무서워한 적이 있나요?",
      "프레디가 더 용감해지도록 내가 해 줄 말을 적어 보세요."] };
ACT["S3294"] = { s: "Freddy's classmates are excited to be studying penguins. When they learn that some penguins are endangered, the class decides to help.",
  q: ["What do Freddy's classmates learn about penguins?",
      "Have you ever learned about an endangered animal?",
      "Write one way you think the class could help the penguins."],
  h: ["프레디 반 친구들은 펭귄에 대해 무엇을 알게 되나요?",
      "나는 멸종 위기 동물에 대해 배워 본 적이 있나요?",
      "반 친구들이 펭귄을 도울 방법을 한 가지 적어 보세요."] };
ACT["S3295"] = { s: "Evil Uncle Unicorn attempts to dominate earth by using a Ladybot to trick Mighty Robot.",
  q: ["This book says Evil Uncle Unicorn uses a Ladybot to trick Mighty Robot. Write a paragraph imagining how the Ladybot might trick the Robot.",
      "Write a paragraph about a time someone tried to trick you, and how you figured it out.",
      "Write a paragraph giving your opinion on whether Mighty Robot should trust new robots he meets, and why."],
  h: ["이 책은 사악한 유니콘 삼촌이 레이디봇을 이용해 마이티 로봇을 속인다고 말해요. 레이디봇이 로봇을 어떻게 속였을지 상상해서 문단으로 써 보세요.",
      "누군가 여러분을 속이려 했던 경험과, 어떻게 알아챘는지 문단으로 써 보세요.",
      "마이티 로봇이 새로 만나는 로봇을 믿어야 한다고 생각하는지, 왜 그런지 여러분의 의견을 문단으로 써 보세요."] };
ACT["S3296"] = { s: "When Mr. Mosquito invades Earth with an army of Mutant Mosquitoes from Mercury, Ricky and his Robot know exactly what to do!",
  q: ["Who invades Earth with an army of mosquitoes?",
      "Have you ever been bothered by real mosquitoes?",
      "Write what you think Ricky and his robot do to stop them."],
  h: ["누가 모기 군대를 이끌고 지구를 침략하나요?",
      "나는 진짜 모기 때문에 귀찮았던 적이 있나요?",
      "리키와 로봇이 모기들을 막으려고 무엇을 했을지 적어 보세요."] };
ACT["S3297"] = { s: "General Jackrabbit and his Robo-Rabbits from Jupiter attempt to take over the world on Ricky Ricotta's birthday.",
  q: ["What day do the Robo-Rabbits choose to attack?",
      "Have you ever had something unexpected happen on your birthday?",
      "Write what you think Ricky does to save his birthday."],
  h: ["로보 래빗들은 어느 날 공격을 하나요?",
      "나는 생일에 예상치 못한 일이 일어난 적이 있나요?",
      "리키가 생일을 지키려고 무엇을 했을지 적어 보세요."] };
ACT["S3298"] = { s: "Ricky and his Mighty Robot meet a mean little Martian named Major Monkey who plans to take over Earth with his monstrous Mecha-Monkeys.",
  q: ["Who is planning to take over Earth in this book?",
      "Have you ever seen a robot toy or a movie about robots?",
      "Write what kind of Mecha-Monkey you would build if you were Major Monkey."],
  h: ["이 책에서 지구를 정복하려는 것은 누구인가요?",
      "나는 로봇 장난감을 가지고 놀거나 로봇 영화를 본 적이 있나요?",
      "내가 메이저 몽키라면 어떤 메카 몽키를 만들고 싶은지 적어 보세요."] };
ACT["S3299"] = { s: "The evil Victor Von Vulture and his army of Voodoo Vultures from Venus are about to take over planet Earth.",
  q: ["Who is about to take over planet Earth in this book?",
      "Have you ever seen a vulture, in real life or in a picture?",
      "Write how you think Ricky and Mighty Robot stop the Voodoo Vultures."],
  h: ["이 책에서 지구를 정복하려는 것은 누구인가요?",
      "나는 실제로나 사진으로 독수리를 본 적이 있나요?",
      "리키와 마이티 로봇이 부두 벌처들을 어떻게 막았을지 적어 보세요."] };
