// 간이 학습 질문 — Book No. S34 묶음. 사람이 아니라 AI 가 한 번 쓰고 굳힌 파일이다.
window.ACT = window.ACT || {};
var ACT = window.ACT;   // catalog.js 와 같은 다리: Node(check-act.js)의 Function 가짜 window 에서는 window.ACT 를 쓰고 그냥 ACT 는 못 쓴다
ACT["S3400"] = { s: "When Zack is bitten by a tick during a class trip to Central Park, he succumbs to Rhyme Disease, which causes him to speak only in rhymes and to float like a helium balloon.",
  q: ["What happens to Zack after he catches Rhyme Disease?",
      "Have you ever gotten sick and felt strange, like Zack did?",
      "Would you like to speak only in rhymes for a day? Why or why not?"],
  h: ["잭이 라임병에 걸린 뒤 무슨 일이 일어나나요?",
      "너도 아파서 이상한 기분이 들었던 적이 있나요?",
      "하루 동안 라임(운율)으로만 말한다면 좋을 것 같나요? 왜 그런가요?"] };
ACT["S3401"] = { s: "Zack gets a chance to meet the old horror film star Count Bugosi, who may or many not be a real vampire.",
  q: ["Who does Zack get a chance to meet in this book?",
      "Have you ever met someone famous or someone who seemed mysterious?",
      "Do you think Count Bugosi is a real vampire? Why or why not?"],
  h: ["잭은 이 책에서 누구를 만날 기회를 얻나요?",
      "너는 유명하거나 신비로워 보이는 사람을 만난 적이 있나요?",
      "버고시 백작이 진짜 뱀파이어라고 생각하나요? 왜 그런가요?"] };
ACT["S3402"] = { s: "When Zack gets a dinosaur egg at the flea market, he was given one warning: do not put it in the microwave.",
  q: ["What warning does Zack get about the dinosaur egg?",
      "Have you ever been given a warning that you were curious about breaking?",
      "What do you think will happen if Zack puts the egg in the microwave?"],
  h: ["잭은 공룡 알에 대해 어떤 경고를 받았나요?",
      "너는 어기고 싶을 만큼 궁금했던 경고를 받아 본 적이 있나요?",
      "잭이 알을 전자레인지에 넣으면 어떤 일이 일어날 것 같나요?"] };
ACT["S3403"] = { s: "When magic enables Zack's eighty-eight-year-old grandmother to become a terrific batter, she ends up playing in a Chicago White Sox baseball game.",
  q: ["What does magic help Zack's grandmother do in this book?",
      "Have you ever seen an older person in your family do something surprising?",
      "What do you think it would be like to watch your grandmother play in a real baseball game?"],
  h: ["이 책에서 마법은 잭의 할머니가 무엇을 하도록 도와주나요?",
      "너희 가족 중 나이 드신 분이 놀라운 일을 하는 것을 본 적이 있나요?",
      "할머니가 진짜 야구 경기에서 뛰는 걸 본다면 어떤 기분일 것 같나요?"] };
ACT["S3404"] = { s: "The natural history museum always seemed kind of spooky. I thought the models looked just a little too real. However, I didn't realize how spooky it was until I got trapped there at night!",
  q: ["What happens to the narrator at the museum at night?",
      "Have you ever visited a museum? What did you think of it?",
      "Would you want to get trapped in a museum at night? Why or why not?"],
  h: ["밤에 박물관에서 화자에게 무슨 일이 일어나나요?",
      "너는 박물관에 가 본 적이 있나요? 어땠나요?",
      "밤에 박물관에 갇히고 싶나요? 왜 그런가요?"] };
ACT["S3405"] = { s: "Mummies are cool, but they’re creepy, too! Something funny happens when Zack meets teenage mummy.",
  q: ["Who does Zack meet in this book?",
      "Have you ever learned about mummies before? What did you think of them?",
      "What funny thing do you imagine happens when Zack meets the teenage mummy?"],
  h: ["잭은 이 책에서 누구를 만나나요?",
      "너는 미라에 대해 배운 적이 있나요? 어떤 생각이 들었나요?",
      "잭이 십대 미라를 만났을 때 어떤 재미있는 일이 일어났을지 상상해서 적어 보세요."] };
ACT["S3406"] = { s: "After she eats his homework, ten-year-old Zack suspects that his substitute teacher Mrs. Wolfowitz is a werewolf, and with Mrs. Coleman-Levin's help, he and Spence uncover her bizarre secret.",
  q: ["Why does Zack suspect his substitute teacher is a werewolf?",
      "Have you ever had a substitute teacher? What was that like?",
      "What do you think Zack and Spence will find out about Mrs. Wolfowitz's secret?"],
  h: ["잭은 왜 대체 선생님이 늑대인간이라고 의심하나요?",
      "너는 대체(보결) 선생님을 만난 적이 있나요? 어땠나요?",
      "잭과 스펜스가 울포비츠 선생님의 비밀에 대해 무엇을 알아낼 것 같나요?"] };
ACT["S3407"] = { s: "Zack and Spencer come across an extra package of freeze-dried something. When opened and wet, the shriveled mass starts growing.",
  q: ["What happens when Zack and Spencer add water to the freeze-dried package?",
      "Have you ever seen something grow after adding water, like a sponge or seeds?",
      "What do you think the shriveled mass will grow into?"],
  h: ["잭과 스펜서가 동결 건조된 것에 물을 넣자 무슨 일이 일어나나요?",
      "너는 물을 넣으면 자라나는 것(스펀지, 씨앗 등)을 본 적이 있나요?",
      "쪼그라든 덩어리가 무엇으로 자랄 것 같나요?"] };
ACT["S3408"] = { s: "A few days before his school's Halloween dance, Zack meets a girl who seems to be already wearing her costume.",
  q: ["Who does Zack meet before the Halloween dance?",
      "Have you ever worn a costume for Halloween or another event?",
      "What do you think the girl's costume really is?"],
  h: ["핼러윈 댄스파티 전에 잭은 누구를 만나나요?",
      "너는 핼러윈이나 다른 행사에서 코스튬(분장)을 입어 본 적이 있나요?",
      "그 소녀의 옷차림이 정말 무엇일 것 같나요?"] };
ACT["S3409"] = { s: "This book demonstrates the challenging relationship between first-grader Jacob and his older sister, Abigail. Third-grader Abigail calls her pesky brother, 'The pain.' Jacob calls her triumphant sister, 'The Great One.'",
  q: ["What do Jacob and Abigail call each other?",
      "Do you have a brother or sister? Do you ever call each other nicknames?",
      "Why do you think Jacob and Abigail call each other these names?"],
  h: ["제이콥과 애비게일은 서로를 뭐라고 부르나요?",
      "너는 형제나 자매가 있나요? 서로 별명을 부르나요?",
      "제이콥과 애비게일이 서로에게 이런 이름을 붙인 이유가 뭘까요?"] };
ACT["S3410"] = { s: "It's Arthur's birthday and he is having a gymnastic party. He's sure to win the prize for the best all-around gymnast.",
  q: ["What kind of party is Arthur having?",
      "Have you ever been to or had a birthday party with a special theme?",
      "Do you think Arthur will win the prize? Why or why not?"],
  h: ["아서는 어떤 파티를 열고 있나요?",
      "너는 특별한 주제가 있는 생일 파티에 가 보거나 열어 본 적이 있나요?",
      "아서가 상을 받을 것 같나요? 왜 그런가요?"] };
ACT["S3411"] = { s: "Frances wants to be friends with Albert, the badger next door. She helps him and learns what it means to be a good friend.",
  q: ["What does Frances learn in this book?",
      "Have you ever helped a friend or neighbor?",
      "What do you think it means to be a good friend?"],
  h: ["프랜시스는 이 책에서 무엇을 배우나요?",
      "너는 친구나 이웃을 도와준 적이 있나요?",
      "좋은 친구가 된다는 것은 무엇을 의미한다고 생각하나요?"] };
ACT["S3412"] = { s: "Luna's classmates think she is the new kid from outer space. When Luna comes up with an idea for the Family Night program, the rest of the class is reluctant. But later, they follow her suggestion and perform for the night.",
  q: ["What idea does Luna come up with for the Family Night program?",
      "Have you ever had an idea that other people didn't like at first?",
      "Why do you think Luna's classmates changed their minds and followed her idea?"],
  h: ["루나는 패밀리 나이트 프로그램을 위해 어떤 아이디어를 냈나요?",
      "너는 다른 사람들이 처음엔 좋아하지 않았던 아이디어를 낸 적이 있나요?",
      "루나의 반 친구들이 마음을 바꿔 그녀의 아이디어를 따른 이유가 뭘까요?"] };
ACT["S3413"] = { s: "This book reviews the mammals that ruled Earth after the dinosaurs.",
  q: ["What kind of animals does this book talk about?",
      "Have you ever seen a picture or model of a mammoth?",
      "Which mammal from after the dinosaurs would you like to learn more about?"],
  h: ["이 책은 어떤 동물들에 대해 이야기하나요?",
      "너는 매머드의 그림이나 모형을 본 적이 있나요?",
      "공룡 이후의 포유동물 중 더 알고 싶은 동물은 무엇인가요?"] };
ACT["S3414"] = { s: "In this version of the classic fairytale, \"Goldilocks and the Three Bears,\" Ghostyshocks confronts her fears and finds friends with her new neighbors, the bears.",
  q: ["What does Ghostyshocks do in this story?",
      "Have you ever made friends with a new neighbor?",
      "What fears do you think Ghostyshocks had to face?"],
  h: ["이 이야기에서 고스티삭스는 무엇을 하나요?",
      "너는 새 이웃과 친구가 되어 본 적이 있나요?",
      "고스티삭스가 맞서야 했던 두려움은 무엇이었을까요?"] };
ACT["S3415"] = { s: "In this book, Abigail and Jacob are on the move as they go to the mall and get separated; ride the Super Slide at the fair; go for a beach outing to ride a boogie board.",
  q: ["What are some of the places Abigail and Jacob go in this book?",
      "Have you ever gotten separated from your family in a crowded place?",
      "Which activity in the book would you most like to try — the mall, the Super Slide, or the boogie board?"],
  h: ["애비게일과 제이콥은 이 책에서 어떤 장소들에 가나요?",
      "너는 붐비는 곳에서 가족과 떨어져 본 적이 있나요?",
      "몰, 슈퍼 슬라이드, 부기보드 중에서 가장 해 보고 싶은 것은 무엇인가요?"] };
ACT["S3416"] = { s: "Nate the Great is about to enter his dog Sludge in the smartest pet contest. But when the prize disappears, it looks as if the contest will fail.",
  q: ["What happens to the prize in this book?",
      "Have you or your pet ever entered a contest?",
      "What do you think happened to the missing prize?"],
  h: ["이 책에서 상품에 무슨 일이 일어나나요?",
      "너나 너의 반려동물이 대회에 나가 본 적이 있나요?",
      "사라진 상품에 무슨 일이 있었을 것 같나요?"] };
ACT["S3417"] = { s: "Nate the Great has his work cut out for him when Rosamond loses his birthday gift.",
  q: ["What does Rosamond lose in this book?",
      "Have you ever lost a gift or an important item?",
      "How do you think Nate the Great will find the missing gift?"],
  h: ["로자몬드는 이 책에서 무엇을 잃어버리나요?",
      "너는 선물이나 소중한 물건을 잃어버린 적이 있나요?",
      "네이트 더 그레이트가 잃어버린 선물을 어떻게 찾을 것 같나요?"] };
ACT["S3418"] = { s: "Nate the Great finds that someone has left his dog a valentine.",
  q: ["What does Nate the Great find for his dog?",
      "Have you ever given or received a valentine?",
      "Who do you think left the valentine for the dog?"],
  h: ["네이트 더 그레이트는 자기 강아지를 위해 무엇을 발견하나요?",
      "너는 발렌타인 카드를 주거나 받아 본 적이 있나요?",
      "누가 강아지에게 발렌타인 카드를 남겼을 것 같나요?"] };
ACT["S3419"] = { s: "When Junie B. hurts her toe and cannot play in the school kickball tournament, she decides to be in the halftime show.",
  q: ["What does Junie B. decide to do instead of playing kickball?",
      "Have you ever gotten hurt and had to sit out of a game or activity?",
      "What do you think Junie B.'s halftime show will be like?"],
  h: ["주니 비는 킥볼 대신 무엇을 하기로 결심하나요?",
      "너는 다쳐서 경기나 활동을 쉬어야 했던 적이 있나요?",
      "주니 비의 하프타임 쇼는 어떤 모습일 것 같나요?"] };
ACT["S3420"] = { s: "It's kindergarten graduation, and Junie B. gets a white graduation gown for the day. But she accidentally spills grape juice on her gown.",
  q: ["What does Junie B. spill on her graduation gown?",
      "Have you ever spilled something on your clothes at an important event?",
      "What do you think Junie B. will do about the stain on her gown?"],
  h: ["주니 비는 졸업 가운에 무엇을 쏟나요?",
      "너는 중요한 행사에서 옷에 무언가를 쏟아 본 적이 있나요?",
      "주니 비가 가운의 얼룩을 어떻게 할 것 같나요?"] };
ACT["S3421"] = { s: "When it's Job Day at school, Junie B. creates the strangest job description.",
  q: ["What kind of job description does Junie B. create?",
      "Have you ever talked about what job you want to have when you grow up?",
      "What job do you think Junie B. talked about?"],
  h: ["주니 비는 어떤 이상한 직업 소개를 만드나요?",
      "너는 커서 하고 싶은 일에 대해 이야기해 본 적이 있나요?",
      "주니 비가 이야기한 직업은 무엇이었을 것 같나요?"] };
ACT["S3422"] = { s: "Junie B. Jones shows off her new, furry mittens in kindergarten. But when her mittens disappear, disaster strikes.",
  q: ["What does Junie B. show off at kindergarten?",
      "Have you ever lost something you were proud of showing to others?",
      "What do you think happened to Junie B.'s mittens?"],
  h: ["주니 비는 유치원에서 무엇을 자랑하나요?",
      "너는 자랑스럽게 보여 주던 물건을 잃어버린 적이 있나요?",
      "주니 비의 장갑에 무슨 일이 있었을 것 같나요?"] };
ACT["S3423"] = { s: "Junie B. copies her classmate's paper when her father won't let her stay up late to do her homework. But is it cheating too?",
  q: ["Why does Junie B. copy her classmate's paper?",
      "Have you ever been in a situation where you had to decide if something was right or wrong?",
      "Do you think copying homework is cheating? Why or why not?"],
  h: ["주니 비는 왜 친구의 숙제를 베끼나요?",
      "너는 옳고 그름을 결정해야 했던 상황을 겪은 적이 있나요?",
      "숙제를 베끼는 것이 부정행위라고 생각하나요? 왜 그런가요?"] };
ACT["S3424"] = { s: "Room One is putting on a Columbus Day play, but problems keep on happening. Can the play be saved?",
  q: ["What is Room One putting on in this book?",
      "Have you ever been part of a school play or performance?",
      "What problems do you think happen during the play?"],
  h: ["교실 원 반은 이 책에서 무엇을 준비하나요?",
      "너는 학교 연극이나 공연에 참여해 본 적이 있나요?",
      "연극을 하며 어떤 문제들이 생겼을 것 같나요?"] };
ACT["S3425"] = { s: "This book describes many different butterflies living all over the world.",
  q: ["What does this book describe?",
      "Have you ever seen a butterfly? What did it look like?",
      "Which butterfly from around the world would you like to learn about?"],
  h: ["이 책은 무엇을 설명하나요?",
      "너는 나비를 본 적이 있나요? 어떤 모습이었나요?",
      "세계 여러 나비 중에서 알고 싶은 나비는 무엇인가요?"] };
ACT["S3426"] = { s: "This story is about the beautiful mermaid who sacrifices her life to be with the handsome prince she loves.",
  q: ["The mermaid in this story gives up her life to be with the prince she loves. Write about what she gives up and why you think she makes this choice.",
      "Have you ever given up something important to be with someone or to get something you wanted? Write about what happened and how you felt.",
      "Do you think the mermaid's choice to sacrifice her life for love is a good idea? Explain your thinking with your own reasons."],
  h: ["이 이야기 속 인어는 사랑하는 왕자와 함께 있기 위해 자기 목숨을 희생해요. 인어가 무엇을 포기했는지, 왜 그런 선택을 했다고 생각하는지 적어 보세요.",
      "너는 누군가와 함께 있기 위해, 또는 원하는 것을 얻기 위해 소중한 것을 포기해 본 적이 있나요? 무슨 일이 있었고 그때 기분이 어땠는지 적어 보세요.",
      "사랑을 위해 목숨을 희생하는 인어의 선택이 좋은 생각이라고 생각하나요? 너의 생각과 이유를 설명해 보세요."] };
ACT["S3427"] = { s: "Princess Rose is cursed at birth by a wicked witch and is destined to prick her finger on a spinning wheel and die. Can the true love’s kiss save her?",
  q: ["Princess Rose is cursed at birth and is destined to prick her finger on a spinning wheel. Write about what you think happens when the curse comes true, and whether you believe a kiss can save her.",
      "Have you ever heard of a wish or a warning that came true in a story or in real life? Write about it and how it made you feel.",
      "Do you think curses like the one in this story are more scary or more magical? Explain your thinking with your own reasons."],
  h: ["로즈 공주는 태어날 때 저주를 받고, 물레에 손가락을 찔려 죽을 운명이에요. 저주가 이루어지면 무슨 일이 일어날지, 그리고 입맞춤이 그녀를 구할 수 있을지 너의 생각을 적어 보세요.",
      "너는 이야기 속에서나 실제로 이루어진 소원이나 경고에 대해 들어 본 적이 있나요? 그 이야기와 그때 느낀 기분을 적어 보세요.",
      "이 이야기 속 저주 같은 것이 더 무섭다고 생각하나요, 더 신비롭다고 생각하나요? 너의 생각과 이유를 설명해 보세요."] };
ACT["S3428"] = { s: "This story is about the beautiful princess, and her wicked stepmother, and her seven rescuers.",
  q: ["Who are the seven rescuers in this story?",
      "Have you ever been helped by a group of people?",
      "Why do you think the stepmother is wicked to the princess?"],
  h: ["이 이야기에서 일곱 구조자는 누구인가요?",
      "너는 여러 사람의 도움을 받은 적이 있나요?",
      "새엄마가 공주에게 못되게 구는 이유가 뭘까요?"] };
ACT["S3429"] = { s: "This story is about a sorcerer's apprentice named Max who dabbles in magic beyond his abilities and finds himself in a world of trouble.",
  q: ["What does Max do that gets him into trouble?",
      "Have you ever tried something that was too hard for you?",
      "What kind of trouble do you think Max finds himself in?"],
  h: ["맥스는 무엇을 해서 곤경에 빠지나요?",
      "너는 너무 어려운 것을 시도해 본 적이 있나요?",
      "맥스가 어떤 곤경에 빠졌을 것 같나요?"] };
ACT["S3430"] = { s: "This book contains three original Western adventures including the stories of rotten rustlers, rigged rodeos, and runaway wagons.",
  q: ["What three kinds of Western adventures are in this book?",
      "Have you ever seen a movie or show about cowboys?",
      "Which of the three stories — rustlers, rodeos, or runaway wagons — sounds most exciting to you?"],
  h: ["이 책에는 어떤 세 가지 서부 모험 이야기가 담겨 있나요?",
      "너는 카우보이가 나오는 영화나 프로그램을 본 적이 있나요?",
      "도둑, 로데오, 도망친 마차 이야기 중에 어떤 것이 가장 흥미로운가요?"] };
ACT["S3431"] = { s: "This book is about magical fairytale castles and their inhabitants.",
  q: ["What is this book about?",
      "Have you ever imagined living in a castle?",
      "What kind of inhabitants do you think live in these magical castles?"],
  h: ["이 책은 무엇에 관한 것인가요?",
      "너는 성에서 사는 상상을 해 본 적이 있나요?",
      "이 마법의 성에는 어떤 존재들이 살고 있을 것 같나요?"] };
ACT["S3432"] = { s: "This book presents spooky stories - including the dangerous dungeons of Chillmore Castle, the \"Spook-Spotters\" of Grimly Grange, and more.",
  q: ["What are some of the spooky stories in this book about?",
      "Have you ever been scared by a spooky story?",
      "Which spooky place — Chillmore Castle or Grimly Grange — would you rather explore?"],
  h: ["이 책 속 무서운 이야기들은 무엇에 관한 것인가요?",
      "너는 무서운 이야기 때문에 겁을 먹은 적이 있나요?",
      "칠모어 성과 그림리 그레인지 중 어디를 탐험해 보고 싶나요?"] };
ACT["S3433"] = { s: "This book introduces a mermaid who just loves to dance, a mermaid who is lurking to sabotage the Great Seahorse Race, and a mermaid who is on a journey to the spooky Pirates Graveyard.",
  q: ["What are the three mermaids in this book like?",
      "Have you ever wished you could live under the sea?",
      "Which mermaid's story sounds most interesting to you — the dancer, the saboteur, or the traveler?"],
  h: ["이 책 속 세 인어는 각각 어떤가요?",
      "너는 바닷속에서 살아 보고 싶다고 생각한 적이 있나요?",
      "춤추는 인어, 방해하는 인어, 여행하는 인어 중 누구의 이야기가 가장 흥미로운가요?"] };
ACT["S3434"] = { s: "This book contains stories of Santa and introduces how he makes his toys, what he does on his days off, and more.",
  q: ["What does this book tell you about Santa?",
      "Have you ever wondered what Santa does on his days off?",
      "What do you imagine Santa does when he is not delivering toys?"],
  h: ["이 책은 산타에 대해 무엇을 알려 주나요?",
      "너는 산타가 쉬는 날에 무엇을 하는지 궁금했던 적이 있나요?",
      "산타가 장난감을 배달하지 않을 때 무엇을 할 것 같나요?"] };
ACT["S3435"] = { s: "This book introduces snowmen who love to have amazing adventures.",
  q: ["What do the snowmen in this book love to do?",
      "Have you ever built a snowman?",
      "What kind of adventure would you like a snowman to have?"],
  h: ["이 책 속 눈사람들은 무엇을 좋아하나요?",
      "너는 눈사람을 만들어 본 적이 있나요?",
      "눈사람이 어떤 모험을 하면 좋을 것 같나요?"] };
ACT["S3436"] = { s: "This is a story about Pegasus the flying horse helping Bellerophon defeat a fire-breathing monster.",
  q: ["Who does Pegasus help in this story?",
      "Have you ever helped a friend face something scary?",
      "What do you think it would be like to fly on Pegasus?"],
  h: ["페가수스는 이 이야기에서 누구를 도와주나요?",
      "너는 친구가 무서운 것에 맞서도록 도와준 적이 있나요?",
      "페가수스를 타고 나는 건 어떤 기분일 것 같나요?"] };
ACT["S3437"] = { s: "The Greek army arrives at Troy to recapture Helen, the most beautiful woman in the world. The Greek commander, Odysseus, comes up with an extraordinary solution to get inside the heavily defended city.",
  q: ["What solution does Odysseus come up with?",
      "Have you ever come up with a clever solution to a hard problem?",
      "What do you think Odysseus' solution is?"],
  h: ["오디세우스는 어떤 해결책을 생각해 내나요?",
      "너는 어려운 문제에 대해 기발한 해결책을 생각해 낸 적이 있나요?",
      "오디세우스의 해결책이 무엇일 것 같나요?"] };
ACT["S3438"] = { s: "This book contains shaggy dog tales - including stories about a dog show, a sheepdog in danger, and more.",
  q: ["What are some of the dog stories in this book about?",
      "Have you ever seen a dog show or owned a dog?",
      "What do you think happens to the sheepdog in danger?"],
  h: ["이 책 속 강아지 이야기들은 무엇에 관한 것인가요?",
      "너는 개 쇼를 본 적이 있거나 강아지를 키워 본 적이 있나요?",
      "위험에 처한 양치기 개에게 무슨 일이 일어날 것 같나요?"] };
ACT["S3439"] = { s: "This book contains dinosaur tales - including stories about wrestling raptors, vegetarian dinosaurs, and more.",
  q: ["What kinds of dinosaur stories are in this book?",
      "Have you ever learned about dinosaurs before?",
      "Which dinosaur — a wrestling raptor or a vegetarian dinosaur — would you like to read about first?"],
  h: ["이 책 속 공룡 이야기는 무엇에 관한 것인가요?",
      "너는 전에 공룡에 대해 배운 적이 있나요?",
      "씨름하는 랩터와 채식 공룡 중 어느 이야기를 먼저 읽고 싶나요?"] };
ACT["S3440"] = { s: "When the naughty Monkey steals a magic peach, it angers the Emperor of Heaven and he is given a task by Buddha.",
  q: ["What does the Monkey steal, and who does it make angry?",
      "Have you ever done something naughty and gotten in trouble?",
      "What task do you think Buddha gives to the Monkey?"],
  h: ["원숭이는 무엇을 훔치고, 그것 때문에 누가 화가 나나요?",
      "너는 장난을 쳐서 혼난 적이 있나요?",
      "부처가 원숭이에게 어떤 임무를 줄 것 같나요?"] };
ACT["S3441"] = { s: "After he pulls a sword out of a stone, suddenly Arthur becomes the King of Britain in charge of a band of brave knights.",
  q: ["How does Arthur become the King of Britain?",
      "Have you ever done something that suddenly changed your life?",
      "What do you think it would be like to lead a band of brave knights?"],
  h: ["아서는 어떻게 브리튼의 왕이 되나요?",
      "너의 삶을 갑자기 바꾼 일을 해 본 적이 있나요?",
      "용감한 기사들을 이끄는 건 어떤 기분일 것 같나요?"] };
ACT["S3442"] = { s: "This book introduces some retold Aesop's fables about sly foxes, thirsty storks, and greedy dogs.",
  q: ["What kinds of animals are in the fables in this book?",
      "Have you ever heard an Aesop's fable before?",
      "Which animal — the sly fox, the thirsty stork, or the greedy dog — sounds most interesting to you?"],
  h: ["이 책 속 우화에는 어떤 동물들이 나오나요?",
      "너는 전에 이솝 우화를 들어 본 적이 있나요?",
      "교활한 여우, 목마른 황새, 욕심 많은 개 중에 누가 가장 흥미로운가요?"] };
ACT["S3443"] = { s: "This book introduces a Greek myth about Hercules who completes 12 impossible tasks to earn the forgiveness of the gods.",
  q: ["How many tasks does Hercules complete, and why?",
      "Have you ever had to complete a hard task to earn forgiveness or trust?",
      "Which of Hercules' 12 tasks do you imagine would be the hardest?"],
  h: ["헤라클레스는 몇 개의 임무를 완수하고, 그 이유는 무엇인가요?",
      "너는 용서나 신뢰를 얻기 위해 힘든 과제를 해낸 적이 있나요?",
      "헤라클레스의 12가지 임무 중에 가장 어려울 것 같은 것은 무엇인가요?"] };
ACT["S3444"] = { s: "This book introduces the ancient Greek adventure story of Ulysses who faces many challenges on his way home from the Trojan War.",
  q: ["What is Ulysses trying to do in this story?",
      "Have you ever had a long or difficult journey home?",
      "What kind of challenges do you think Ulysses faces?"],
  h: ["율리시스는 이 이야기에서 무엇을 하려고 하나요?",
      "너는 집으로 가는 길이 길거나 힘들었던 적이 있나요?",
      "율리시스가 어떤 어려움들을 겪을 것 같나요?"] };
ACT["S3445"] = { s: "This is a retelling story of Phileas Fogg who travels around the world in just eighty days.",
  q: ["Phileas Fogg travels around the world in only eighty days. Write about what you think would be the hardest part of traveling around the world that fast, and why.",
      "Have you ever set a goal with a tight time limit, like finishing something by a certain day? Write about what happened and how you felt while doing it.",
      "If you could travel around the world, which places would you visit and why? Explain your thinking."],
  h: ["필리어스 포그는 겨우 80일 만에 세계를 여행해요. 그렇게 빠르게 세계를 여행할 때 가장 힘든 점이 무엇일지, 그리고 왜 그런지 적어 보세요.",
      "너는 정해진 시간 안에 무언가를 끝내야 하는 목표를 세운 적이 있나요? 무슨 일이 있었고 그동안 기분이 어땠는지 적어 보세요.",
      "네가 세계를 여행할 수 있다면 어느 곳들을 가고 싶은지, 그 이유와 함께 적어 보세요."] };
ACT["S3446"] = { s: "This story is about the Canterville Ghost which is determined to scare away the Otis family, the new residents in his castle.",
  q: ["What is the Canterville Ghost determined to do?",
      "Have you ever tried hard to scare someone, or been scared by someone?",
      "Do you think the ghost will succeed in scaring away the Otis family? Why or why not?"],
  h: ["캔터빌 유령은 무엇을 하기로 결심하나요?",
      "너는 누군가를 놀라게 하려고 애써 본 적이 있거나, 누군가에게 놀란 적이 있나요?",
      "유령이 오티스 가족을 놀라게 해서 쫓아낼 수 있을 것 같나요? 왜 그런가요?"] };
ACT["S3447"] = { s: "Scrooge is taken on a ghostly journey through life by three Christmas spirits, and he faces his past and present, and future.",
  q: ["Who takes Scrooge on the ghostly journey in this story?",
      "Have you ever thought about your own past, present, and future?",
      "What do you think Scrooge learns from seeing his past, present, and future?"],
  h: ["스크루지를 유령의 여정으로 데려가는 것은 누구인가요?",
      "너는 너의 과거, 현재, 미래에 대해 생각해 본 적이 있나요?",
      "스크루지가 자신의 과거, 현재, 미래를 보며 무엇을 배웠을 것 같나요?"] };
ACT["S3448"] = { s: "The clumsy crocodile named Cassy gets a job at Everglades Department Store but ends up messing everything.",
  q: ["What happens after Cassy gets a job at the store?",
      "Have you ever made a mistake while trying to do a job or a task?",
      "What do you think Cassy will do to fix the mess she made?"],
  h: ["캐시가 가게에서 일을 시작한 뒤 무슨 일이 일어나나요?",
      "너는 어떤 일이나 과제를 하다가 실수를 한 적이 있나요?",
      "캐시가 자기가 만든 엉망을 어떻게 해결할 것 같나요?"] };
ACT["S3449"] = { s: "Read and find out why the ghost named Jake Hubbard is not like any other ghost you are likely to find on a ghost train.",
  q: ["What is unusual about the ghost named Jake Hubbard?",
      "Have you ever ridden a scary ride like a ghost train?",
      "What do you imagine makes Jake Hubbard different from other ghosts?"],
  h: ["제이크 허바드라는 유령은 무엇이 특별한가요?",
      "너는 유령 열차 같은 무서운 놀이기구를 타 본 적이 있나요?",
      "제이크 허바드가 다른 유령들과 다른 점이 무엇일 것 같나요?"] };
ACT["S3450"] = { s: "After his ship gets wrecked, Lemuel Gulliver is kidnapped by the residents of a strange land called Lilliput.",
  q: ["What happens to Gulliver after his ship gets wrecked?",
      "Have you ever been somewhere strange or unfamiliar?",
      "What do you imagine the residents of Lilliput look like?"],
  h: ["배가 난파된 뒤 걸리버에게 무슨 일이 일어나나요?",
      "너는 낯설고 이상한 곳에 가 본 적이 있나요?",
      "릴리퍼트의 주민들은 어떤 모습일 것 같나요?"] };
ACT["S3451"] = { s: "The home of Kit and Ned looks perfectly normal from the outside. But is it perfect inside as well?",
  q: ["The book asks whether Kit and Ned's house is as perfect inside as it looks outside. Write about what you imagine might be different or strange inside the house.",
      "Have you ever visited a place that looked normal on the outside but felt different once you went inside? Write about what happened and how you felt.",
      "Do you think things always look the same on the inside as they do on the outside? Explain your thinking with your own examples."],
  h: ["이 책은 키트와 네드의 집이 겉모습처럼 안도 완벽한지 물어요. 집 안이 무엇이 다르거나 이상할지 너의 생각을 적어 보세요.",
      "너는 겉으로는 평범해 보였지만 들어가 보니 느낌이 달랐던 곳에 가 본 적이 있나요? 무슨 일이 있었고 그때 기분이 어땠는지 적어 보세요.",
      "겉모습과 속모습이 항상 같다고 생각하나요? 너만의 예를 들어 생각을 설명해 보세요."] };
ACT["S3452"] = { s: "When Lily receives an incredible present that grants her six wishes, she is delighted. But will her wishes turn out as planned?",
  q: ["What does Lily's incredible present grant her?",
      "Have you ever gotten something you were very excited about?",
      "If you could have six wishes granted, what would you wish for?"],
  h: ["릴리의 놀라운 선물은 그녀에게 무엇을 준다고 하나요?",
      "너는 아주 신나는 물건을 받아 본 적이 있나요?",
      "네게 여섯 가지 소원이 이루어진다면 무엇을 빌고 싶나요?"] };
ACT["S3453"] = { s: "This book introduces the Greek myth of Jason who gets sent on a quest for the Golden Fleece.",
  q: ["What is Jason sent on a quest to find?",
      "Have you ever gone on a quest or search for something important?",
      "What challenges do you think Jason faces on his quest?"],
  h: ["제이슨은 무엇을 찾기 위한 모험을 떠나나요?",
      "너는 중요한 것을 찾기 위한 모험을 해 본 적이 있나요?",
      "제이슨이 모험 중에 어떤 어려움을 겪을 것 같나요?"] };
ACT["S3454"] = { s: "Adam and Sally arrive at Twelve Bells End and learn the truth about the curse of the Midnight family.",
  q: ["What do Adam and Sally learn about at Twelve Bells End?",
      "Have you ever learned a surprising truth about a place or a family?",
      "What do you imagine the curse of the Midnight family is?"],
  h: ["애덤과 샐리는 트웰브 벨스 엔드에서 무엇을 알게 되나요?",
      "너는 어떤 장소나 가족에 대한 놀라운 진실을 알게 된 적이 있나요?",
      "미드나잇 가문의 저주가 무엇일 것 같나요?"] };
ACT["S3455"] = { s: "When the worst nightmares of the villagers of Nether Bogey seem to be coming true, Harry suspects Mystery Mansion and the shadowy characters that live there have something to do with it.",
  q: ["What does Harry suspect is causing the villagers' nightmares to come true?",
      "Have you ever suspected someone or something was causing a strange problem?",
      "What do you think the shadowy characters in Mystery Mansion are doing?"],
  h: ["해리는 마을 사람들의 악몽이 이루어지는 원인이 무엇이라고 의심하나요?",
      "너는 이상한 문제의 원인을 누군가나 무언가로 의심해 본 적이 있나요?",
      "미스터리 맨션의 수상한 인물들이 무엇을 하고 있을 것 같나요?"] };
ACT["S3456"] = { s: "Pinocchio wants to be good and become a real boy. But whatever he tries, he just can't stay out of trouble.",
  q: ["What does Pinocchio want to become?",
      "Have you ever tried hard to be good but still got into trouble?",
      "What kind of trouble do you think Pinocchio gets into?"],
  h: ["피노키오는 무엇이 되고 싶어 하나요?",
      "너는 착하게 행동하려고 애썼지만 그래도 곤란에 빠진 적이 있나요?",
      "피노키오가 어떤 곤란에 빠질 것 같나요?"] };
ACT["S3457"] = { s: "Unfortunately, Robinson Crusoe gets shipwrecked on a desert island and is stuck there for thirty-five years.",
  q: ["How long is Robinson Crusoe stuck on the island?",
      "Have you ever been somewhere alone for a long time?",
      "What do you think would be the hardest part of living alone on a desert island?"],
  h: ["로빈슨 크루소는 섬에 얼마나 오래 갇혀 있나요?",
      "너는 오랫동안 혼자 있어 본 적이 있나요?",
      "무인도에서 혼자 사는 것 중 가장 힘든 점은 무엇일 것 같나요?"] };
ACT["S3458"] = { s: "This fairy tale is about the wicked Snow Queen who attempts to kidnap a boy in the frozen north.",
  q: ["What does the wicked Snow Queen try to do?",
      "Have you ever been somewhere very cold?",
      "What do you think happens when the Snow Queen tries to kidnap the boy?"],
  h: ["못된 눈의 여왕은 무엇을 하려고 하나요?",
      "너는 아주 추운 곳에 가 본 적이 있나요?",
      "눈의 여왕이 소년을 납치하려 할 때 무슨 일이 일어날 것 같나요?"] };
ACT["S3459"] = { s: "Abi and Dom set out on a quest to discover the secrets of the magician Mesmo.",
  q: ["Abi and Dom go on a quest to discover the secrets of the magician Mesmo. Write about what secrets you imagine they might discover, and why those secrets could be important.",
      "Have you ever wanted to find out the truth about a mystery or a secret? Write about what you did to find out and how it turned out.",
      "Do you think it is always a good idea to uncover someone's secrets? Explain your thinking with your own reasons."],
  h: ["애비와 돔은 마법사 메스모의 비밀을 밝혀내는 모험을 떠나요. 그들이 어떤 비밀을 발견할 것 같은지, 그 비밀이 왜 중요할지 적어 보세요.",
      "너는 어떤 미스터리나 비밀의 진실을 알아내고 싶었던 적이 있나요? 그것을 알아내기 위해 무엇을 했고 결과가 어땠는지 적어 보세요.",
      "누군가의 비밀을 밝혀내는 것이 항상 좋은 일이라고 생각하나요? 너의 생각과 이유를 설명해 보세요."] };
ACT["S3460"] = { s: "This book recounts the history of cars from the early designs of Leonardo da Vinci to the streamlined models of today.",
  q: ["This book tells the history of cars from Leonardo da Vinci's early designs to today's streamlined models. Write about what you think changed the most about cars over that long history.",
      "Have you ever seen an old car or a picture of one? Write about how it was different from cars you see today.",
      "If you could design a car of the future, what would it look like and what would it do? Explain your ideas."],
  h: ["이 책은 레오나르도 다빈치의 초기 설계부터 오늘날의 매끈한 모델까지 자동차의 역사를 이야기해요. 그 긴 역사 동안 자동차에서 가장 많이 바뀐 것이 무엇이라고 생각하는지 적어 보세요.",
      "너는 오래된 자동차나 그 사진을 본 적이 있나요? 오늘날의 자동차와 무엇이 달랐는지 적어 보세요.",
      "네가 미래의 자동차를 디자인한다면 어떤 모습이고 무엇을 할 수 있을지, 너의 생각을 적어 보세요."] };
ACT["S3461"] = { s: "This book explains everything about castles - including why castles were first built, what it was like to live in one, and more.",
  q: ["This book explains why castles were first built and what it was like to live in one. Write about what you learned or imagine about why people needed castles.",
      "Have you ever visited or seen a picture of a real castle? Write about what it looked like and how you felt.",
      "If you could build your own castle, what special rooms or features would it have, and why? Explain your thinking."],
  h: ["이 책은 성이 처음 왜 지어졌는지, 성 안에서 사는 것이 어땠는지 설명해요. 사람들이 왜 성이 필요했는지 배운 것이나 너의 생각을 적어 보세요.",
      "너는 실제 성에 가 보거나 사진을 본 적이 있나요? 어떤 모습이었고 그때 기분이 어땠는지 적어 보세요.",
      "네가 직접 성을 짓는다면 어떤 특별한 방이나 시설을 만들고 싶은지, 그 이유와 함께 적어 보세요."] };
ACT["S3462"] = { s: "This book introduces the history of flying machines from Leonardo da Vinci to the Wright brothers, and more.",
  q: ["This book tells the history of flying machines from Leonardo da Vinci to the Wright brothers. Write about what you think was the biggest challenge for people trying to build the first flying machines.",
      "Have you ever flown in an airplane or watched something fly through the sky? Write about the experience and how it felt.",
      "If you could invent your own flying machine, what would it look like and how would it work? Explain your ideas."],
  h: ["이 책은 레오나르도 다빈치부터 라이트 형제까지 비행기의 역사를 소개해요. 처음 비행 기계를 만들려던 사람들에게 가장 큰 어려움이 무엇이었을지 생각을 적어 보세요.",
      "너는 비행기를 타 보거나 하늘을 나는 것을 본 적이 있나요? 그 경험과 그때 느낀 기분을 적어 보세요.",
      "네가 직접 비행 기계를 발명한다면 어떤 모습이고 어떻게 작동할지, 너의 생각을 적어 보세요."] };
ACT["S3463"] = { s: "This book follows the history of ships and daring explorers who sail in them.",
  q: ["This book follows the history of ships and the daring explorers who sailed them. Write about what you think made those explorers brave enough to sail into the unknown.",
      "Have you ever ridden on a boat or a ship? Write about the experience and how it felt.",
      "If you were an explorer sailing to an unknown place, where would you want to go and why? Explain your thinking."],
  h: ["이 책은 배의 역사와 배를 타고 항해한 용감한 탐험가들을 따라가요. 그 탐험가들이 미지의 세계로 항해할 만큼 용감했던 이유가 무엇일지 적어 보세요.",
      "너는 배를 타 본 적이 있나요? 그 경험과 그때 느낀 기분을 적어 보세요.",
      "네가 미지의 곳으로 항해하는 탐험가라면 어디로 가고 싶은지, 그 이유와 함께 적어 보세요."] };
ACT["S3464"] = { s: "This book chronicles the history of trains from the first engines of the eighteenth century to the high-speed trains of today.",
  q: ["This book chronicles the history of trains from the first engines of the eighteenth century to today's high-speed trains. Write about what you think changed the most about trains over time.",
      "Have you ever ridden on a train? Write about the experience and how it felt.",
      "If you could design a train of the future, what would it look like and how fast would it go? Explain your ideas."],
  h: ["이 책은 18세기 최초의 기관차부터 오늘날의 고속 열차까지 기차의 역사를 기록해요. 시간이 지나며 기차에서 가장 많이 바뀐 것이 무엇이라고 생각하는지 적어 보세요.",
      "너는 기차를 타 본 적이 있나요? 그 경험과 그때 느낀 기분을 적어 보세요.",
      "네가 미래의 기차를 디자인한다면 어떤 모습이고 얼마나 빠를지, 너의 생각을 적어 보세요."] };
ACT["S3465"] = { s: "Cabin boy Jim sets off in search of treasure. But to win the treasure, he must outwit the cunning pirate Long John Silver.",
  q: ["Who must Jim outwit to win the treasure?",
      "Have you ever had to outsmart someone in a game or competition?",
      "What do you think Jim does to outwit Long John Silver?"],
  h: ["짐이 보물을 얻기 위해 누구를 이겨야 하나요?",
      "너는 게임이나 경쟁에서 누군가를 이겨야 했던 적이 있나요?",
      "짐이 롱 존 실버를 어떻게 이길 것 같나요?"] };
ACT["S3466"] = { s: "Alice follows the White Rabbit down a rabbit hole and finds herself in Wonderland. There she meets extraordinary characters one after another.",
  q: ["How does Alice end up in Wonderland?",
      "Have you ever followed your curiosity somewhere new?",
      "What kind of extraordinary character would you like to meet in Wonderland?"],
  h: ["앨리스는 어떻게 원더랜드에 가게 되나요?",
      "너는 호기심을 따라 새로운 곳에 가 본 적이 있나요?",
      "원더랜드에서 어떤 특별한 인물을 만나고 싶나요?"] };
ACT["S3467"] = { s: "When Alice steps through a looking glass, her adventures in the topsy-turvy world continue.",
  q: ["What does Alice step through to continue her adventures?",
      "Have you ever imagined a world where everything is upside down or backward?",
      "What do you think the topsy-turvy world looks like?"],
  h: ["앨리스는 모험을 계속하기 위해 무엇을 통과하나요?",
      "너는 모든 것이 거꾸로 되어 있는 세상을 상상해 본 적이 있나요?",
      "뒤죽박죽인 세상은 어떤 모습일 것 같나요?"] };
ACT["S3468"] = { s: "After a prince is enchanted by a wicked fairy, he turns into the Beast and lives alone in his castle, waiting for true love to break the spell. Who can be the one to see through his ugly exterior?",
  q: ["What does the prince turn into after the fairy's spell?",
      "Have you ever judged someone by how they looked and later changed your mind?",
      "Who do you think will be able to see through the Beast's ugly exterior?"],
  h: ["왕자는 요정의 마법으로 무엇이 되나요?",
      "너는 누군가를 겉모습으로 판단했다가 나중에 생각이 바뀐 적이 있나요?",
      "누가 야수의 못생긴 겉모습 너머를 볼 수 있을 것 같나요?"] };
ACT["S3469"] = { s: "A young girl sets out with a great white bear on a journey. For the sake of true love, she battles with a troll queen.",
  q: ["The girl in this story battles a troll queen for the sake of true love. Write about what you imagine happens during this battle and why the girl is willing to fight for love.",
      "Have you ever done something difficult or scary for someone you cared about? Write about what happened and how you felt.",
      "Do you think fighting for love is worth taking a big risk? Explain your thinking with your own reasons."],
  h: ["이 이야기 속 소녀는 진정한 사랑을 위해 트롤 여왕과 싸워요. 그 싸움에서 무슨 일이 일어날지, 소녀가 왜 사랑을 위해 싸우려 하는지 너의 생각을 적어 보세요.",
      "너는 소중한 사람을 위해 힘들거나 무서운 일을 해 본 적이 있나요? 무슨 일이 있었고 그때 기분이 어땠는지 적어 보세요.",
      "사랑을 위해 큰 위험을 감수하고 싸우는 것이 가치 있다고 생각하나요? 너의 생각과 이유를 설명해 보세요."] };
ACT["S3470"] = { s: "Three siblings discover a castle and enter a world full of magic and meet a princess who says she has a ring of invisibility.",
  q: ["What does the princess say she has?",
      "Have you ever discovered a place that felt magical?",
      "If you had a ring of invisibility, what would you do with it?"],
  h: ["공주는 자신이 무엇을 가지고 있다고 말하나요?",
      "너는 마법 같은 느낌이 드는 장소를 발견한 적이 있나요?",
      "네게 투명 반지가 있다면 무엇을 하고 싶나요?"] };
ACT["S3471"] = { s: "This book examines fashion trends throughout history, from Roman togas to crippling corsets.",
  q: ["This book looks at fashion trends from Roman togas to corsets. Write about what you think this shows about how people's ideas of fashion have changed over time.",
      "Have you ever worn something that was uncomfortable just because it looked good? Write about what happened and how you felt.",
      "Do you think fashion should be more about comfort or about looking good? Explain your thinking with your own reasons."],
  h: ["이 책은 로마의 토가부터 코르셋까지 역사 속 패션 유행을 살펴봐요. 이것이 사람들의 패션에 대한 생각이 시간에 따라 어떻게 변했는지 보여 준다고 생각하는지 적어 보세요.",
      "너는 보기에만 좋아서 불편한 옷을 입어 본 적이 있나요? 무슨 일이 있었고 그때 기분이 어땠는지 적어 보세요.",
      "패션은 편안함이 더 중요할까요, 보기 좋은 것이 더 중요할까요? 너의 생각과 이유를 설명해 보세요."] };
ACT["S3472"] = { s: "When a ghostly figure appears to Prince Hamlet and reveals the dreadful truth about his father's death, he plots for revenge.",
  q: ["What does the ghostly figure reveal to Prince Hamlet?",
      "Have you ever learned a hard truth that changed how you felt about something?",
      "Do you think Hamlet's plan for revenge is a good idea? Why or why not?"],
  h: ["유령 같은 인물이 햄릿 왕자에게 무엇을 밝히나요?",
      "너는 어떤 것에 대한 네 감정을 바꿔 놓은 힘든 진실을 알게 된 적이 있나요?",
      "햄릿의 복수 계획이 좋은 생각이라고 생각하나요? 왜 그런가요?"] };
ACT["S3473"] = { s: "After the death of her beloved father, Sara Crewe struggles at boarding school.",
  q: ["What happens to Sara Crewe's father?",
      "Have you ever struggled with something difficult after losing someone or something important?",
      "What do you think Sara Crewe's struggles at boarding school are like?"],
  h: ["사라 크루의 아버지에게 무슨 일이 일어나나요?",
      "너는 소중한 것을 잃은 뒤 힘든 일을 겪어 본 적이 있나요?",
      "사라 크루가 기숙학교에서 겪는 어려움은 어떤 것일 것 같나요?"] };
ACT["S3474"] = { s: "Macbeth is the bravest general in Scotland and the loyal servant to King Duncan. But after he hears that he could be king himself, he becomes mad with ambition and sets out on a bloody path to power.",
  q: ["What does Macbeth do after he hears he could be king?",
      "Have you ever wanted something so much that it changed how you acted?",
      "Do you think Macbeth's ambition is a good or bad thing? Why?"],
  h: ["맥베스는 자신이 왕이 될 수 있다는 말을 듣고 무엇을 하나요?",
      "너는 무언가를 너무 원해서 네 행동이 달라진 적이 있나요?",
      "맥베스의 야망이 좋은 것이라고 생각하나요, 나쁜 것이라고 생각하나요? 왜 그런가요?"] };
ACT["S3475"] = { s: "Disobeying his advisors, Young King Leo opens the magical book and accidentally releases the greedy dragon. He must find a solution before his kingdom gets destroyed by it.",
  q: ["King Leo disobeys his advisors and accidentally releases a greedy dragon. Write about what you think King Leo should do to solve this problem, and why.",
      "Have you ever disobeyed advice from someone and then had to deal with the result? Write about what happened and how you felt.",
      "Do you think it is ever okay to disobey rules or advice? Explain your thinking with your own reasons."],
  h: ["레오 왕은 조언자들의 말을 어기고 실수로 욕심 많은 용을 풀어놓아요. 레오 왕이 이 문제를 어떻게 해결해야 할지, 그 이유와 함께 너의 생각을 적어 보세요.",
      "너는 누군가의 조언을 어기고 그 결과를 감당해야 했던 적이 있나요? 무슨 일이 있었고 그때 기분이 어땠는지 적어 보세요.",
      "규칙이나 조언을 어기는 것이 때로는 괜찮다고 생각하나요? 너의 생각과 이유를 설명해 보세요."] };
ACT["S3476"] = { s: "This book tells the enchanting story of magic and mix-ups and fairies and fools.",
  q: ["What kinds of things does this story tell about?",
      "Have you ever been part of a funny mix-up?",
      "What do you imagine the fairies in this story do?"],
  h: ["이 이야기는 어떤 것들에 대해 이야기하나요?",
      "너는 재미있는 착각이나 혼란을 겪어 본 적이 있나요?",
      "이 이야기 속 요정들은 무엇을 할 것 같나요?"] };
ACT["S3477"] = { s: "A mysterious phantom who lurks in deep below the Paris Opera House haunts the stars of the stage.",
  q: ["Where does the mysterious phantom lurk?",
      "Have you ever felt like someone or something mysterious was watching you?",
      "Why do you think the phantom haunts the stars of the stage?"],
  h: ["신비한 유령은 어디에 숨어 있나요?",
      "너는 신비한 누군가나 무언가가 너를 지켜보는 것 같은 기분을 느껴 본 적이 있나요?",
      "유령이 왜 무대의 스타들을 괴롭히는 것 같나요?"] };
ACT["S3478"] = { s: "When a young beggar boy accidentally meets the Prince of England, their lives change forever.",
  q: ["Who does the beggar boy accidentally meet?",
      "Have you ever met someone by accident who changed your life?",
      "How do you think the beggar boy's and the prince's lives change?"],
  h: ["거지 소년은 우연히 누구를 만나나요?",
      "너는 우연히 만나서 네 삶을 바꿔 놓은 사람이 있나요?",
      "거지 소년과 왕자의 삶이 어떻게 바뀔 것 같나요?"] };
ACT["S3479"] = { s: "When their father is wrongly accused of spying, Bobbie, Peter, and Phyllis move from London to the countryside.",
  q: ["Why do Bobbie, Peter, and Phyllis move to the countryside?",
      "Have you ever had to move somewhere because of something that happened in your family?",
      "What do you think will happen to the children's father?"],
  h: ["바비, 피터, 필리스는 왜 시골로 이사하나요?",
      "너는 가족에게 일어난 일 때문에 이사를 해야 했던 적이 있나요?",
      "아이들의 아버지에게 무슨 일이 일어날 것 같나요?"] };
ACT["S3480"] = { s: "Much Millington's father gets arrested by the evil Sheriff of Nottingham. Muc plans a daring raid on the Sheriff's castle with the help of the mysterious outlaw Robin Hood.",
  q: ["Who helps Much plan a raid on the Sheriff's castle?",
      "Have you ever planned something daring to help someone you love?",
      "What do you think happens during the raid on the Sheriff's castle?"],
  h: ["머치가 보안관의 성을 습격할 계획을 세울 때 누가 도와주나요?",
      "너는 사랑하는 사람을 돕기 위해 대담한 일을 계획해 본 적이 있나요?",
      "보안관의 성을 습격하는 동안 무슨 일이 일어날 것 같나요?"] };
ACT["S3481"] = { s: "This book introduces Shakespeare's love story of Romeo and Juliet, whose families are life-long enemies.",
  q: ["What is the relationship between Romeo and Juliet's families?",
      "Have you ever liked someone even though other people didn't approve?",
      "What do you think happens when two people from enemy families fall in love?"],
  h: ["로미오와 줄리엣 가족의 관계는 어떤가요?",
      "너는 다른 사람들이 반대해도 누군가를 좋아한 적이 있나요?",
      "원수 가문의 두 사람이 사랑에 빠지면 무슨 일이 일어날 것 같나요?"] };
ACT["S3482"] = { s: "After her parents' death, Mary Lennox moves into her uncle's gloomy mansion and feels lonely. But behind an old ivy-covered wall is exciting secrets, waiting to be discovered.",
  q: ["What is hidden behind the old ivy-covered wall?",
      "Have you ever felt lonely in a new place?",
      "What kind of secrets do you imagine Mary discovers behind the wall?"],
  h: ["담쟁이덩굴로 덮인 오래된 벽 뒤에는 무엇이 숨겨져 있나요?",
      "너는 새로운 곳에서 외로움을 느껴 본 적이 있나요?",
      "메리가 벽 뒤에서 어떤 비밀을 발견할 것 같나요?"] };
ACT["S3483"] = { s: "This book introduces the story of football, including its beginnings in the Roman Army, how both American football and rugby were born, and more.",
  q: ["Where does this book say football began?",
      "Have you ever played or watched football?",
      "What do you think is the most interesting thing about football's history?"],
  h: ["이 책은 축구가 어디에서 시작되었다고 하나요?",
      "너는 축구를 해 보거나 본 적이 있나요?",
      "축구의 역사에서 가장 흥미로운 점은 무엇이라고 생각하나요?"] };
ACT["S3484"] = { s: "This book follows the history of the Olympics from the traditional games of Ancient Greece to the modern Games.",
  q: ["This book follows the history of the Olympics from Ancient Greece to today. Write about what you think has changed the most about the Olympics over that long history, and why those changes might have happened.",
      "Have you ever watched the Olympics or another big sports event? Write about what you saw and how it made you feel.",
      "Do you think the Olympics are important for bringing countries together? Explain your thinking with your own reasons."],
  h: ["이 책은 고대 그리스부터 오늘날까지 올림픽의 역사를 따라가요. 그 긴 역사 동안 올림픽에서 가장 많이 바뀐 것이 무엇이라고 생각하는지, 왜 그런 변화가 있었을지 적어 보세요.",
      "너는 올림픽이나 다른 큰 스포츠 행사를 본 적이 있나요? 무엇을 보았고 그때 기분이 어땠는지 적어 보세요.",
      "올림픽이 여러 나라를 하나로 모으는 데 중요하다고 생각하나요? 너의 생각과 이유를 설명해 보세요."] };
ACT["S3485"] = { s: "When her brothers are turned into swans by their wicked stepmother, a young princess tries to reverse a spell.",
  q: ["What does the wicked stepmother turn the princess's brothers into?",
      "Have you ever tried hard to fix a problem for your family?",
      "What do you think the princess does to reverse the spell?"],
  h: ["못된 새엄마는 공주의 오빠들을 무엇으로 바꾸나요?",
      "너는 가족을 위해 문제를 해결하려고 애써 본 적이 있나요?",
      "공주가 마법을 되돌리기 위해 무엇을 할 것 같나요?"] };
ACT["S3486"] = { s: "When a magical storm washes a royal ship ashore, Prospero and his daughter, Miranda, are stranded on a lonely desert island. And he finally has the chance to right old wrongs.",
  q: ["What chance does Prospero finally get on the island?",
      "Have you ever gotten a chance to make something right that had gone wrong before?",
      "What do you think Prospero does to right his old wrongs?"],
  h: ["프로스페로는 섬에서 마침내 어떤 기회를 얻나요?",
      "너는 예전에 잘못되었던 일을 바로잡을 기회를 얻어 본 적이 있나요?",
      "프로스페로가 옛 잘못을 바로잡기 위해 무엇을 할 것 같나요?"] };
ACT["S3487"] = { s: "Viola is left shipwrecked on the coast of Illyria and she disguises herself as a boy for protection. Things start to get mixed up when she is hired as a servant by Duke Orsino.",
  q: ["Why does Viola disguise herself as a boy?",
      "Have you ever pretended to be someone else for a reason?",
      "What kind of mix-ups do you think happen because of Viola's disguise?"],
  h: ["비올라는 왜 소년으로 변장하나요?",
      "너는 어떤 이유로 다른 사람인 척해 본 적이 있나요?",
      "비올라의 변장 때문에 어떤 혼란이 생길 것 같나요?"] };
ACT["S3488"] = { s: "This book describes the life of Mole, Ratty, Badger, and Toad on the riverbank.",
  q: ["Who are the four characters in this book?",
      "Have you ever spent time by a river or in nature with friends?",
      "Which of the four characters — Mole, Ratty, Badger, or Toad — sounds the most interesting to you?"],
  h: ["이 책 속 네 인물은 누구인가요?",
      "너는 친구들과 강가나 자연에서 시간을 보낸 적이 있나요?",
      "두더지, 래티, 오소리, 두꺼비 중 누가 가장 흥미로운가요?"] };
ACT["S3489"] = { s: "Dorothy gets whizzed to Oz in a tornado and lands in an unfamiliar place. Can she return to Kansas safely?",
  q: ["How does Dorothy end up in Oz?",
      "Have you ever been somewhere unfamiliar and wanted to get back home?",
      "What do you think Dorothy needs to do to get back to Kansas safely?"],
  h: ["도로시는 어떻게 오즈에 가게 되나요?",
      "너는 낯선 곳에 가서 집으로 돌아가고 싶었던 적이 있나요?",
      "도로시가 안전하게 캔자스로 돌아가려면 무엇을 해야 할 것 같나요?"] };
ACT["S3490"] = { s: "This book introduces everything about underwear from the first medieval pants to rib-cracking corsets and petticoats.",
  q: ["This book covers the history of underwear from medieval pants to rib-cracking corsets. Write about what you think this history shows about how people's ideas of comfort and beauty have changed.",
      "Have you ever worn clothing that was uncomfortable but that people thought looked nice? Write about what happened and how you felt.",
      "Do you think clothing today is more comfortable than clothing from history? Explain your thinking with your own reasons."],
  h: ["이 책은 중세의 바지부터 갈비뼈를 조이는 코르셋까지 속옷의 역사를 다뤄요. 이 역사가 사람들의 편안함과 아름다움에 대한 생각이 어떻게 변했는지 보여 준다고 생각하는지 적어 보세요.",
      "너는 사람들이 보기에는 좋다고 생각했지만 불편했던 옷을 입어 본 적이 있나요? 무슨 일이 있었고 그때 기분이 어땠는지 적어 보세요.",
      "오늘날의 옷이 옛날 옷보다 더 편하다고 생각하나요? 너의 생각과 이유를 설명해 보세요."] };
ACT["S3491"] = { s: "Jacob and Abigail find it challenging to agree on anything. But deep down, they know they can count on each other, especially at school.",
  q: ["What do Jacob and Abigail know deep down, even though they don't agree?",
      "Do you have a sibling or friend you can count on, even when you disagree?",
      "Why do you think Jacob and Abigail can count on each other at school?"],
  h: ["제이콥과 애비게일은 서로 의견이 다르지만 마음속으로 무엇을 알고 있나요?",
      "너는 의견이 달라도 믿고 의지할 수 있는 형제자매나 친구가 있나요?",
      "제이콥과 애비게일이 학교에서 서로를 믿을 수 있는 이유가 뭘까요?"] };
ACT["S3492"] = { s: "How different is a friend from a fiend? Jake vows never to speak in class again when he is embarrassed by a reading circle blunder. Abigail finds it hard to trust one of her best friends.",
  q: ["Why does Jake vow never to speak in class again?",
      "Have you ever felt embarrassed in front of your class?",
      "Why do you think Abigail finds it hard to trust her best friend?"],
  h: ["제이크는 왜 다시는 수업 시간에 말하지 않겠다고 다짐하나요?",
      "너는 반 친구들 앞에서 창피했던 적이 있나요?",
      "애비게일이 가장 친한 친구를 믿기 힘들어하는 이유가 뭘까요?"] };
ACT["S3493"] = { s: "Mr. and Mrs. Watson bring their pet pig to the drive-in. When the pig arrives, she is off to find her bucket of buttery popcorn. Book #6",
  q: ["What does Mercy the pig go to find at the drive-in?",
      "Have you ever gone to a movie or a drive-in?",
      "What do you think Mercy does to get her popcorn?"],
  h: ["돼지 머시는 드라이브인에서 무엇을 찾으러 가나요?",
      "너는 영화관이나 드라이브인에 가 본 적이 있나요?",
      "머시가 팝콘을 얻기 위해 무엇을 할 것 같나요?"] };
ACT["S3494"] = { s: "Second-grader Ivy and Bean decide to become the youngest people ever to discover a dinosaur skeleton. Book #3",
  q: ["What do Ivy and Bean decide to become?",
      "Have you ever tried to be the first or the best at something?",
      "What do you think Ivy and Bean do to look for a dinosaur skeleton?"],
  h: ["아이비와 빈은 무엇이 되기로 결심하나요?",
      "너는 무언가에서 처음이나 최고가 되려고 해 본 적이 있나요?",
      "아이비와 빈이 공룡 뼈를 찾기 위해 무엇을 할 것 같나요?"] };
ACT["S3495"] = { s: "Bean's parents leave her in the care of Nancy for the afternoon. She enlists Ivy to come over and teach Nancy how to be a really good babysitter. Book #4",
  q: ["What does Bean want to teach Nancy?",
      "Have you ever had a babysitter, or been one yourself?",
      "What do you think Ivy and Bean do to teach Nancy?"],
  h: ["빈은 낸시에게 무엇을 가르치고 싶어 하나요?",
      "너는 베이비시터가 돌봐준 적이 있거나, 네가 누군가를 돌봐준 적이 있나요?",
      "아이비와 빈이 낸시를 가르치기 위해 무엇을 할 것 같나요?"] };
ACT["S3496"] = { s: "Seven-year-old Bean plays a mean trick on her sister, and she finds unexpected support for her antics from the new neighbor girl, Ivy.  Book #1",
  q: ["Who supports Bean's trick on her sister?",
      "Have you ever played a trick on someone in your family?",
      "What do you think Bean's trick on her sister is?"],
  h: ["빈이 언니에게 친 장난을 누가 도와주나요?",
      "너는 가족에게 장난을 쳐 본 적이 있나요?",
      "빈이 언니에게 친 장난이 무엇이었을 것 같나요?"] };
ACT["S3497"] = { s: "In this book, the two girls decide to be very good and nice. But things don't turn out as they planned. Book #5",
  q: ["What do Ivy and Bean decide to be in this book?",
      "Have you ever tried very hard to be good, but things didn't turn out as planned?",
      "What do you think happens when Ivy and Bean try to be good and nice?"],
  h: ["아이비와 빈은 이 책에서 무엇이 되기로 결심하나요?",
      "너는 착해지려고 정말 애썼지만 계획대로 되지 않았던 적이 있나요?",
      "아이비와 빈이 착하고 다정하게 굴려고 할 때 무슨 일이 일어날 것 같나요?"] };
ACT["S3498"] = { s: "When best friends Ivy and Bean try to make money by writing a newspaper about Pancake Court, their neighbors are not pleased to read about themselves. Book #8",
  q: ["How do Ivy and Bean try to make money?",
      "Have you ever tried to earn money by doing something creative?",
      "Why do you think the neighbors are not pleased with the newspaper?"],
  h: ["아이비와 빈은 어떻게 돈을 벌려고 하나요?",
      "너는 창의적인 방법으로 돈을 벌어 보려고 한 적이 있나요?",
      "이웃들이 신문 기사를 좋아하지 않는 이유가 뭘까요?"] };
ACT["S3499"] = { s: "Bean watches a movie about a detective on television, and she decides to set up a shop as a private investigator. Book #10",
  q: ["What does Bean decide to set up after watching a detective movie?",
      "Have you ever wanted to try a job you saw in a movie or TV show?",
      "What kind of cases do you think Bean will try to solve?"],
  h: ["빈은 탐정 영화를 본 뒤 무엇을 차리기로 결심하나요?",
      "너는 영화나 TV에서 본 직업을 해 보고 싶었던 적이 있나요?",
      "빈이 어떤 사건들을 해결하려고 할 것 같나요?"] };
