// 간이 학습 질문 — Book No. S37 묶음. 사람이 아니라 AI 가 한 번 쓰고 굳힌 파일이다.
window.ACT = window.ACT || {};
var ACT = window.ACT;
ACT["S3700"] = { s: "The children offer to help Mrs. Gale clear out a pond. When Wesley discovers a pound coin in the pond, a man tries to take it.",
  q: ["What did Wesley find in the pond?",
      "Have you ever found money somewhere?",
      "Write what you would do if you found money like Wesley."],
  h: ["웨슬리는 연못에서 무엇을 발견했나요?",
      "나는 어딘가에서 돈을 주운 적이 있나요?",
      "내가 웨슬리처럼 돈을 주우면 어떻게 할지 적어 보세요."] };
ACT["S3701"] = { s: "Phil is a goalkeeper, but he is so bad that his team claim he couldn't even catch a cold. When he accidentally kicks a ball through Mrs. Frost's window, she offers him a choice.",
  q: ["What happened when Phil accidentally kicked a ball?",
      "Have you ever broken something by accident?",
      "Write what you would do if you broke someone's window."],
  h: ["필이 실수로 공을 찼을 때 무슨 일이 일어났나요?",
      "나는 실수로 무언가를 망가뜨린 적이 있나요?",
      "내가 누군가의 창문을 깼다면 어떻게 할지 적어 보세요."] };
ACT["S3702"] = { s: "Jake finds a nice pair of trainers and when he wears them he runs at an amazing pace and it becomes clear that the trainers are very special indeed. But the trainers go missing before the big race.",
  q: ["What happens when Jake wears the trainers he found?",
      "Have you ever lost something important before a big event?",
      "Write what you would do if your special shoes went missing."],
  h: ["제이크가 주운 운동화를 신으면 무슨 일이 일어나나요?",
      "나는 중요한 일을 앞두고 무언가를 잃어버린 적이 있나요?",
      "내 특별한 신발이 사라진다면 어떻게 할지 적어 보세요."] };
ACT["S3703"] = { s: "Do you ever wonder why we have seasons? Captivating versions of some of the best myths and legends from around the world.",
  q: ["What does this book try to explain about the seasons?",
      "Have you ever wondered why winter comes every year?",
      "Write your own idea about why winter might come into the world."],
  h: ["이 책은 계절에 대해 무엇을 설명하려고 하나요?",
      "나는 왜 해마다 겨울이 오는지 궁금했던 적이 있나요?",
      "겨울이 세상에 오게 된 이유를 나만의 생각으로 적어 보세요."] };
ACT["S3704"] = { s: "This book tells three water-themed myths. They all explain something about the sea ? why it is salty, why droughts and floods happen, how sea creatures came to be.",
  q: ["What three things about water do the myths in this book explain?",
      "Have you ever tasted salty sea water?",
      "Write your own guess about why the sea is salty."],
  h: ["이 책 속 신화들은 물에 대해 어떤 세 가지를 설명하나요?",
      "나는 짠 바닷물을 맛본 적이 있나요?",
      "바다가 왜 짠지 나만의 짐작을 적어 보세요."] };
ACT["S3705"] = { s: "Troy is surrounded by the Greek army and Karis sees many heroic deeds and battles. Will Troy ever be free?",
  q: ["What does Karis see happening around Troy?",
      "Have you ever read or watched a story about a battle?",
      "Write whether you think Troy will be free, and why."],
  h: ["카리스는 트로이 주변에서 무슨 일이 일어나는 것을 보았나요?",
      "나는 전투 이야기를 읽거나 본 적이 있나요?",
      "트로이가 자유로워질 것 같은지, 그 이유와 함께 적어 보세요."] };
ACT["S3706"] = { s: "When an earthquake destroyed a town in Turkey, many people were trapped in their homes. Kelly and Simon helped save lives in that rescue.",
  q: ["What did Kelly and Simon do after the earthquake?",
      "Have you ever heard of a dog helping people?",
      "Write what you think makes rescue dogs like Kelly special."],
  h: ["켈리와 사이먼은 지진이 난 뒤 무엇을 했나요?",
      "나는 개가 사람을 도왔다는 이야기를 들어 본 적이 있나요?",
      "켈리 같은 구조견이 특별한 이유를 내 생각으로 적어 보세요."] };
ACT["S3707"] = { s: "No one dares to fight Blackbeard. So how can Robert Maynard capture the most terrifying pirate that ever lived?",
  q: ["Why does no one dare to fight Blackbeard?",
      "Have you ever read another story about pirates?",
      "Write your own idea about how Robert Maynard might capture Blackbeard."],
  h: ["왜 아무도 블랙비어드와 싸우려 하지 않나요?",
      "나는 해적에 관한 다른 이야기를 읽어 본 적이 있나요?",
      "로버트 메이나드가 블랙비어드를 어떻게 잡을지 내 생각을 적어 보세요."] };
ACT["S3708"] = { s: "Nothing will stop her! This is the story of Melanie Brown, one of the five singer-dancers who became the world-famous Spice Girls.",
  q: ["What group did Melanie Brown become famous as a member of?",
      "Have you ever heard a song by the Spice Girls?",
      "Write about a singer or dancer you admire."],
  h: ["멜라니 브라운은 어떤 그룹의 멤버로 유명해졌나요?",
      "나는 스파이스 걸스의 노래를 들어 본 적이 있나요?",
      "내가 존경하는 가수나 댄서에 대해 적어 보세요."] };
ACT["S3709"] = { s: "Years in the future, Sophie and her little brother Sam have Petey, a house robot, to take care of them. Then one day, Petey changes ? he develops a mind and feelings of his own.",
  q: ["What changes about Petey one day?",
      "Have you ever imagined having a robot at home?",
      "Write what you would want a house robot to help you with."],
  h: ["어느 날 페티에게 어떤 변화가 생기나요?",
      "나는 집에 로봇이 있으면 좋겠다고 상상해 본 적이 있나요?",
      "집에 있는 로봇이 나를 도와주었으면 하는 일을 한 가지 적어 보세요."] };
ACT["S3710"] = { s: "One night Danny finds a fox at the factory and takes care of the fox until the factory closes. Everyone forgets about the fox, except Danny.",
  q: ["Where does Danny find the fox?",
      "Have you ever taken care of an animal?",
      "Write what you would do to take care of a fox like Danny."],
  h: ["대니는 여우를 어디에서 발견했나요?",
      "나는 동물을 돌본 적이 있나요?",
      "대니처럼 여우를 돌본다면 나는 무엇을 할지 적어 보세요."] };
ACT["S3711"] = { s: "Grace, a teenage girl, is on board the pirate ship Sea Devil, but Captain Cutthroat leaves her to die out on a desert island anyway.",
  q: ["What does Captain Cutthroat do to Grace?",
      "Have you ever read a story about being left alone on an island?",
      "Write what you think Grace should do to survive on the island."],
  h: ["컷스로트 선장은 그레이스에게 무엇을 하나요?",
      "나는 무인도에 혼자 남겨지는 이야기를 읽어 본 적이 있나요?",
      "그레이스가 섬에서 살아남으려면 어떻게 해야 할지 내 생각을 적어 보세요."] };
ACT["S3712"] = { s: "Mike and Katy are riding home on their bicycles when something goes whizzing over their heads in the dark. When they check out where this thing landed, they meet up with seemingly cute aliens.",
  q: ["What do Mike and Katy find after something whizzes over their heads?",
      "Have you ever seen something strange in the night sky?",
      "Write what you would say if you met an alien like Mike and Katy did."],
  h: ["무언가 머리 위로 휙 지나간 뒤, 마이크와 케이티는 무엇을 발견했나요?",
      "나는 밤하늘에서 이상한 것을 본 적이 있나요?",
      "마이크와 케이티처럼 외계인을 만난다면 무슨 말을 할지 적어 보세요."] };
ACT["S3713"] = { s: "Del has a good talent for soccer and the best player in his team. But he makes a mistake in the final. What happens to Del?",
  q: ["What mistake does Del make in the final?",
      "Have you ever made a mistake during a game or contest?",
      "Write what you would say to Del after his mistake."],
  h: ["델은 결승전에서 어떤 실수를 하나요?",
      "나는 경기나 대회에서 실수를 한 적이 있나요?",
      "실수한 델에게 내가 해 주고 싶은 말을 적어 보세요."] };
ACT["S3714"] = { s: "A young girl, Tess, starts her first job as a housemaid. Then she meets Will, a young boy sold to Mr. Fry to go up chimneys. Can Tess find a way to save Will?",
  q: ["What job does Will do for Mr. Fry?",
      "Have you ever tried to help a friend who was in trouble?",
      "Write your own idea about how Tess could save Will."],
  h: ["윌은 프라이 아저씨를 위해 무슨 일을 하나요?",
      "나는 어려움에 처한 친구를 도우려 한 적이 있나요?",
      "테스가 윌을 구할 방법을 내 생각으로 적어 보세요."] };
ACT["S3715"] = { s: "An eight-year-old boy Drake is taken to the castle. The wizard Griffith tells him that he is chosen to be a Dragon Master like Ana, Rori, and Bo. His first task is to discover any special powers his Earth Dragon, Worm, has.",
  q: ["What is Drake's first task as a Dragon Master?",
      "Have you ever had a first day at something new, like Drake?",
      "Write what special power you would want your own dragon to have."],
  h: ["드레이크가 드래곤 마스터로서 처음 받은 임무는 무엇인가요?",
      "나는 드레이크처럼 새로운 일을 처음 시작해 본 적이 있나요?",
      "내 드래곤이 가졌으면 하는 특별한 힘을 적어 보세요."] };
ACT["S3716"] = { s: "Ana's Dragon, Kepri, gets sick, and the wizard's potion doesn't work. Drake's Dragon, Worm, uses his special power and teleports himself, Kepri, and the four young Dragon Masters across the world in search of a cure. Will the Dragon Masters be able to save Kepri?",
  q: ["What special power does Worm use to help find a cure?",
      "Have you ever taken care of someone who was sick?",
      "Write what you think the Dragon Masters will need to save Kepri."],
  h: ["웜은 치료법을 찾기 위해 어떤 특별한 힘을 쓰나요?",
      "나는 아픈 사람을 돌본 적이 있나요?",
      "드래곤 마스터들이 케프리를 구하려면 무엇이 필요할지 적어 보세요."] };
ACT["S3717"] = { s: "Drake is shocked to discover that Bo, his fellow Dragon Master, is trying to steal the Dragon Stone. In this book, Drake and the Dragon Masters work together to find a way to protect Bo and his dragon, Shu, from the dark wizard.",
  q: ["What is Drake shocked to discover about Bo?",
      "Have you ever been surprised by something a friend did?",
      "Write what you would do if you found out a friend was in trouble like Bo."],
  h: ["드레이크는 보에 대해 어떤 사실을 알고 충격을 받았나요?",
      "나는 친구가 한 일에 놀란 적이 있나요?",
      "보처럼 친구가 곤경에 처한 것을 알게 되면 나는 어떻게 할지 적어 보세요."] };
ACT["S3718"] = { s: "In this book, Dragon Masters battle the dark wizard Maldred who rides a giant four-headed dragon that spits poison. The evil wizard attacks the castle when the other Dragon Masters are away. Rori and Drake are the only ones to defend the castle.",
  q: ["Who defends the castle when the other Dragon Masters are away?",
      "Have you ever had to handle something important with just one other person?",
      "Write what you would do to defend the castle if you were Rori or Drake."],
  h: ["다른 드래곤 마스터들이 없을 때 누가 성을 지키나요?",
      "나는 단 한 사람과 함께 중요한 일을 처리해 본 적이 있나요?",
      "내가 로리나 드레이크라면 성을 어떻게 지킬지 적어 보세요."] };
ACT["S3719"] = { s: "In this book, a new Dragon Master, Petra, comes to the castle. She gets to train the giant four-headed dragon, but she doesn't try to connect with it! When something terrible happens to the king, Petra will have to work with the other Dragon Masters to save him.",
  q: ["What does Petra fail to do when she trains the giant dragon?",
      "Have you ever had to work with others to solve a problem?",
      "Write what you think Petra should do differently with her dragon."],
  h: ["페트라는 거대한 드래곤을 훈련시킬 때 무엇을 하지 않았나요?",
      "나는 문제를 풀기 위해 다른 사람들과 함께 일한 적이 있나요?",
      "페트라가 드래곤을 대하는 방법을 어떻게 바꾸면 좋을지 적어 보세요."] };
ACT["S3720"] = { s: "In this book, the prime Dragon Stone is dying, and the Dragon Masters have to locate the hidden stone before their telepathic connection is completely gone. Will the Dragon Masters find the stone in time and save it?",
  q: ["What are the Dragon Masters racing to find before time runs out?",
      "Have you ever had to find something important quickly?",
      "Write what you think might happen if they don't find the stone in time."],
  h: ["드래곤 마스터들은 시간이 다하기 전에 무엇을 찾으려고 서두르나요?",
      "나는 중요한 것을 빨리 찾아야 했던 적이 있나요?",
      "제때 돌을 찾지 못하면 어떻게 될지 내 생각을 적어 보세요."] };
ACT["S3721"] = { s: "In this book, the Dragon Masters have to find Carlos, the newest Dragon Master, and track down his wild Lightning Dragon that shoots dangerous sparks of energy.",
  q: ["What does Carlos's wild Lightning Dragon shoot out?",
      "Have you ever tried to find someone who was lost?",
      "Write what you would do to calm a wild dragon like Carlos's."],
  h: ["카를로스의 거친 번개 드래곤은 무엇을 쏘아 내나요?",
      "나는 길을 잃은 사람을 찾으려 한 적이 있나요?",
      "카를로스의 드래곤 같은 거친 드래곤을 진정시키려면 나는 어떻게 할지 적어 보세요."] };
ACT["S3722"] = { s: "Eko, Griffith's first Dragon Master, returns and attempts to kidnap and gain control of every dragon in the kingdom. Can Drake and the other Dragon Masters stop Eko?",
  q: ["What does Eko try to do to every dragon in the kingdom?",
      "Have you ever had to stop someone from doing something wrong?",
      "Write what you would do to help stop Eko."],
  h: ["에코는 왕국의 모든 드래곤에게 무엇을 하려 하나요?",
      "나는 누군가 잘못된 일을 하는 것을 막으려 한 적이 있나요?",
      "에코를 막는 것을 돕기 위해 나는 무엇을 할지 적어 보세요."] };
ACT["S3723"] = { s: "Mina, a Dragon Master from the Far North Lands, arrives at the castle. She needs help to stop a magical Ice Giant from attacking her kingdom. Only a fire dragon can defeat the Ice Giant.",
  q: ["What kind of dragon can defeat the Ice Giant?",
      "Have you ever asked friends for help with a big problem?",
      "Write what you think will happen when the fire dragon meets the Ice Giant."],
  h: ["어떤 드래곤이 얼음 거인을 이길 수 있나요?",
      "나는 큰 문제를 두고 친구들에게 도움을 청한 적이 있나요?",
      "불의 드래곤이 얼음 거인을 만나면 어떻게 될지 내 생각을 적어 보세요."] };
ACT["S3724"] = { s: "After Drake has a mysterious dream about a new dragon trapped in a cave, he and Ana set off to find the Rainbow Dragon. Will they find the secret cave from Drake's dream?",
  q: ["What does Drake dream about that sends him and Ana on a journey?",
      "Have you ever had a dream that felt important?",
      "Write what you think the secret cave from Drake's dream looks like."],
  h: ["드레이크는 어떤 꿈을 꾸고 아나와 함께 여행을 떠나나요?",
      "나는 중요하게 느껴지는 꿈을 꾼 적이 있나요?",
      "드레이크의 꿈에 나온 비밀 동굴이 어떤 모습일지 상상해서 적어 보세요."] };
ACT["S3725"] = { s: "In this book, the wizard Maldred comes back and casts his dark spell on Diego to steal two keys necessary for a dastardly plot. Drake learns that Maldred needs the keys to control the Naga, an enormous dragon that lives deep within the Earth.",
  q: ["Why does Maldred need the two keys?",
      "Have you ever lost something because someone tricked you?",
      "Write what you think Drake should do to stop Maldred's plot."],
  h: ["몰드레드는 왜 두 개의 열쇠가 필요한가요?",
      "나는 누군가의 속임수 때문에 무언가를 잃은 적이 있나요?",
      "드레이크가 몰드레드의 계획을 막으려면 어떻게 해야 할지 적어 보세요."] };
ACT["S3726"] = { s: "In this book, the wizard Maldred is after the powerful Gold Key, protected by the Gold Dragon and her Dragon Master, Darma. Drake and Rori travel to help them keep the key safe. They have to stop the evil wizard from getting the Gold Key and gaining the power to control the Earthquake Dragon.",
  q: ["What do Drake and Rori travel to help protect?",
      "Have you ever helped someone protect something important?",
      "Write what you would do to keep the Gold Key safe from Maldred."],
  h: ["드레이크와 로리는 무엇을 지키기 위해 여행을 떠나나요?",
      "나는 누군가 소중한 것을 지키는 것을 도운 적이 있나요?",
      "황금 열쇠를 몰드레드에게서 지키려면 나는 어떻게 할지 적어 보세요."] };
ACT["S3727"] = { s: "Having stolen the Gold and Silver keys, the evil wizard Maldred can control the Naga, a powerful dragon who can cause terrible earthquakes. Maldred is on his way to a secret temple in the center of the earth where Naga lives. Drake and his friends must stop his attempt to release the dragon.",
  q: ["What can Maldred control now that he has the Gold and Silver keys?",
      "Have you ever had to stop a big problem together with friends?",
      "Write what you think Drake and his friends should do to stop Maldred."],
  h: ["몰드레드는 황금과 은 열쇠를 가지고 무엇을 다스릴 수 있게 되었나요?",
      "나는 친구들과 함께 큰 문제를 막으려 한 적이 있나요?",
      "드레이크와 친구들이 몰드레드를 막으려면 어떻게 해야 할지 적어 보세요."] };
ACT["S3728"] = { s: "Drake must save his kingdom from a terrible earthquake destroying Bracken's crops. He sets off to a secret fairyland to reach a magical Spring Dragon that has the power to regrow the crops.",
  q: ["What power does the magical Spring Dragon have?",
      "Have you ever grown a plant or crop?",
      "Write what you would do to help Bracken's crops grow again."],
  h: ["마법의 봄 드래곤은 어떤 힘을 가지고 있나요?",
      "나는 식물이나 작물을 길러 본 적이 있나요?",
      "브래큰의 작물이 다시 자라도록 돕는다면 나는 무엇을 할지 적어 보세요."] };
ACT["S3729"] = { s: "When the dark wizard Maldred traps Dragon Master Eko with a powerful spell, Drake travels back in time to find the Time Dragon and free her.",
  q: ["Where does Drake travel to find the Time Dragon?",
      "Have you ever wished you could travel back in time?",
      "Write what time you would like to travel back to and why."],
  h: ["드레이크는 시간의 드래곤을 찾기 위해 어디로 여행하나요?",
      "나는 시간을 거슬러 여행하고 싶었던 적이 있나요?",
      "내가 돌아가고 싶은 시간과 그 이유를 적어 보세요."] };
ACT["S3730"] = { s: "When magic from a wizards' battle destroys the city of Remus, Drake and Petra team up with a Dragon Master named Tessa, who has a very close connection with her Sound Dragon, Sono. They cooperate to stop this dangerous duel and find a Power Crystal to save the city.",
  q: ["What do Drake, Petra, and Tessa look for to save the city?",
      "Have you ever worked as a team to solve a problem?",
      "Write what you think makes Tessa's connection with Sono special."],
  h: ["드레이크, 페트라, 테사는 도시를 구하기 위해 무엇을 찾나요?",
      "나는 팀을 이루어 문제를 해결해 본 적이 있나요?",
      "테사와 소노의 연결이 특별한 이유를 내 생각으로 적어 보세요."] };
ACT["S3731"] = { s: "Froggy sets out for the library with Mom and his baby sister. But when Froggy gets too excited, he forgets to use his manners.",
  q: ["What does Froggy forget to use when he gets too excited?",
      "Have you ever gotten so excited that you forgot your manners?",
      "Write one manner you try to remember when you visit the library."],
  h: ["프로기는 너무 신이 나서 무엇을 잊어버리나요?",
      "나는 너무 신이 나서 예의를 잊어버린 적이 있나요?",
      "도서관에 갈 때 내가 지키려고 하는 예절을 한 가지 적어 보세요."] };
ACT["S3732"] = { s: "This book recounts four fact-based tales of hauntings, including a ghost horse, a haunted painting, a skeleton in Colorado, and a ghostly sea captain.",
  q: ["What are the four hauntings this book tells about?",
      "Have you ever heard a ghost story before?",
      "Write which of the four ghost stories sounds the most interesting to you."],
  h: ["이 책이 들려주는 네 가지 유령 이야기는 무엇인가요?",
      "나는 예전에 유령 이야기를 들어 본 적이 있나요?",
      "네 가지 이야기 중에 내가 가장 흥미롭게 느끼는 것을 적어 보세요."] };
ACT["S3733"] = { s: "This story describes the burial of the pharaoh Tutankhamen and the discovery of his long-lost grave by archaeologists more than 3,000 years later.",
  q: ["How long after his burial was Tutankhamen's grave discovered?",
      "Have you ever seen a picture of a mummy or a pharaoh?",
      "Write one question you would ask an archaeologist about Tutankhamen."],
  h: ["투탕카멘의 무덤은 매장된 지 얼마 뒤에 발견되었나요?",
      "나는 미라나 파라오의 사진을 본 적이 있나요?",
      "투탕카멘에 대해 고고학자에게 묻고 싶은 질문을 한 가지 적어 보세요."] };
ACT["S3744"] = { s: "Jack and Annie are on their mission to help a teenaged Louis Armstrong to become the \"King of Jazz.\" The siblings travel back in time to New Orleans in 1915.",
  q: ["Where and when do Jack and Annie travel to on this mission?",
      "Have you ever listened to jazz music?",
      "Write how you think Jack and Annie could help Louis Armstrong."],
  h: ["잭과 애니는 이번 임무에서 언제, 어디로 여행하나요?",
      "나는 재즈 음악을 들어 본 적이 있나요?",
      "잭과 애니가 루이 암스트롱을 어떻게 도울 수 있을지 적어 보세요."] };
ACT["S3745"] = { s: "The magic tree house takes Jack and Annie back to nineteenth-century Ireland, where they encounter a young Augusta Gregory and inspire her to share her love of Irish legends and folktales with the world.",
  q: ["Who do Jack and Annie inspire in nineteenth-century Ireland?",
      "Have you ever heard an Irish legend or folktale?",
      "Write one old story or legend you would like to share with the world."],
  h: ["잭과 애니는 19세기 아일랜드에서 누구에게 영감을 주나요?",
      "나는 아일랜드의 전설이나 옛이야기를 들어 본 적이 있나요?",
      "세상에 들려주고 싶은 옛이야기나 전설을 한 가지 적어 보세요."] };
ACT["S3746"] = { s: "The magic tree house takes Jack and Annie back to Victorian London, on a mission to help the famous writer Charles Dickens.",
  q: ["Which famous writer do Jack and Annie go to help?",
      "Have you ever read a story by Charles Dickens or heard about him?",
      "Write what you would ask Charles Dickens if you met him."],
  h: ["잭과 애니는 어떤 유명한 작가를 도우러 가나요?",
      "나는 찰스 디킨스의 이야기를 읽어 보거나 그에 대해 들어 본 적이 있나요?",
      "찰스 디킨스를 만난다면 무엇을 물어보고 싶은지 적어 보세요."] };
ACT["S3747"] = { s: "The magic tree house whisks Jack and Annie off to a monastery in the Swiss Alps. They are on their mission to find the second of four special objects necessary to break the spell on Penny, the wizard Merlin's beloved penguin.",
  q: ["What are Jack and Annie searching for at the monastery?",
      "Have you ever gone on a search for something special?",
      "Write what you think the second special object could look like."],
  h: ["잭과 애니는 수도원에서 무엇을 찾고 있나요?",
      "나는 특별한 것을 찾아 나선 적이 있나요?",
      "두 번째 특별한 물건이 어떤 모습일지 상상해서 적어 보세요."] };
ACT["S3748"] = { s: "Jack and Annie travel to Washington, D.C., in the 1860s. The siblings encounter Abraham Lincoln, who is desperately trying to save a nation in crisis.",
  q: ["Who do Jack and Annie meet in Washington, D.C.?",
      "Have you ever learned about Abraham Lincoln at school?",
      "Write one question you would like to ask Abraham Lincoln."],
  h: ["잭과 애니는 워싱턴 D.C.에서 누구를 만나나요?",
      "나는 학교에서 에이브러햄 링컨에 대해 배운 적이 있나요?",
      "에이브러햄 링컨에게 묻고 싶은 질문을 한 가지 적어 보세요."] };
ACT["S3749"] = { s: "Jack and Annie get transported by the magic tree house to southwest China. They have to find the final object needed to break the spell on the wizard Merlin's beloved penguin.",
  q: ["Where does the magic tree house take Jack and Annie this time?",
      "Have you ever seen a panda, in real life or in a picture?",
      "Write what you think the final magic object might be."],
  h: ["이번에 마법의 나무집은 잭과 애니를 어디로 데려가나요?",
      "나는 실제로나 사진으로 판다를 본 적이 있나요?",
      "마지막 마법 물건이 무엇일지 내 생각을 적어 보세요."] };
ACT["S3750"] = { s: "Jack and Annie travel back to ancient Greece, where they adventure with twelve-year-old Alexander the Great.",
  q: ["Who do Jack and Annie adventure with in ancient Greece?",
      "Have you ever heard of Alexander the Great before?",
      "Write what you would like to do if you traveled to ancient Greece."],
  h: ["잭과 애니는 고대 그리스에서 누구와 함께 모험하나요?",
      "나는 예전에 알렉산더 대왕에 대해 들어 본 적이 있나요?",
      "고대 그리스로 여행한다면 무엇을 하고 싶은지 적어 보세요."] };
ACT["S3751"] = { s: "Jack and Annie travel to Coney Island on a mission to find the elusive magician Harry Houdini.",
  q: ["Who are Jack and Annie trying to find at Coney Island?",
      "Have you ever watched a magic trick?",
      "Write what magic trick you would like to learn."],
  h: ["잭과 애니는 코니 아일랜드에서 누구를 찾으려 하나요?",
      "나는 마술을 본 적이 있나요?",
      "내가 배우고 싶은 마술을 한 가지 적어 보세요."] };
ACT["S3752"] = { s: "The magic tree house takes Jack and Annie back in time to 1925 Nome, Alaska. The siblings meet Balto, the famous sled dog, and help save the town from illness.",
  q: ["How do Jack and Annie help the town of Nome?",
      "Have you ever heard of a sled dog like Balto?",
      "Write what you think made Balto such a brave dog."],
  h: ["잭과 애니는 놈 마을을 어떻게 돕나요?",
      "나는 발토 같은 썰매개에 대해 들어 본 적이 있나요?",
      "발토가 그렇게 용감한 개가 될 수 있었던 이유를 내 생각으로 적어 보세요."] };
ACT["S3753"] = { s: "When A.J.'s class goes to the gym for \"Fizz Ed,\" they do everything except play sports.",
  q: ["What do A.J.'s class do instead of playing sports in gym class?",
      "Have you ever had a class that was different from what you expected?",
      "Write what you would want to do in gym class instead of sports."],
  h: ["A.J.네 반은 체육 시간에 운동 대신 무엇을 하나요?",
      "나는 예상과 다른 수업을 들어 본 적이 있나요?",
      "체육 시간에 운동 대신 하고 싶은 것을 적어 보세요."] };
ACT["S3754"] = { s: "After boring Mr. Loring retires, A.J.'s class gets a new music teacher, Mr. Hynde. He raps, break-dances, and makes the music class awesome.",
  q: ["What does Mr. Hynde do that makes music class awesome?",
      "Have you ever had a teacher who surprised you?",
      "Write what you would want a music teacher to do in class."],
  h: ["하인드 선생님은 음악 시간을 어떻게 멋지게 만드나요?",
      "나는 나를 놀라게 한 선생님이 있었나요?",
      "음악 선생님이 수업 시간에 해 주었으면 하는 것을 적어 보세요."] };
ACT["S3755"] = { s: "A.J. has a crush on the school nurse, Mrs. Cooney. But he starts to doubt that her charms are just a cover for her secret identity as an international spy.",
  q: ["What does A.J. start to suspect about Mrs. Cooney?",
      "Have you ever imagined a person you know having a secret identity?",
      "Write what secret identity you would like to have."],
  h: ["A.J.는 쿠니 선생님에 대해 무엇을 의심하기 시작하나요?",
      "나는 내가 아는 사람이 비밀스러운 정체를 가지고 있다고 상상해 본 적이 있나요?",
      "내가 가지고 싶은 비밀 정체를 적어 보세요."] };
ACT["S3756"] = { s: "Ms. LaGrange is the new lunch lady at Ella Mentry School. Although she acts weird sometimes, she tries her best to get the kids to eat healthy food.",
  q: ["What does Ms. LaGrange try her best to do for the kids?",
      "Have you ever tried a healthy food someone made for you?",
      "Write one healthy food you like to eat."],
  h: ["라그란지 선생님은 아이들을 위해 무엇을 최선을 다해 하려고 하나요?",
      "나는 누군가 만들어 준 건강한 음식을 먹어 본 적이 있나요?",
      "내가 좋아하는 건강한 음식을 한 가지 적어 보세요."] };
ACT["S3757"] = { s: "Miss Lazar is the Super Custodian at A.J's school. She dances with a mop. She says it is fun to clean throw-up.",
  q: ["What does Miss Lazar do while she cleans?",
      "Have you ever helped clean up something messy?",
      "Write one chore you could try to make more fun, like Miss Lazar does."],
  h: ["레이자 선생님은 청소하면서 무엇을 하나요?",
      "나는 지저분한 것을 치우는 것을 도운 적이 있나요?",
      "레이자 선생님처럼 더 재미있게 해 볼 수 있는 집안일을 한 가지 적어 보세요."] };
ACT["S3758"] = { s: "Mr. Docker is a new science teacher at A.J's school. He is a crazy inventor who blows things up and uses potatoes for power.",
  q: ["What does Mr. Docker use to make power?",
      "Have you ever done a science experiment at school?",
      "Write one invention you would like to make like Mr. Docker."],
  h: ["도커 선생님은 무엇으로 전기를 만드나요?",
      "나는 학교에서 과학 실험을 해 본 적이 있나요?",
      "도커 선생님처럼 내가 만들어 보고 싶은 발명품을 적어 보세요."] };
ACT["S3759"] = { s: "Mrs. Kormel, the weird school bus driver, gets lost on the way to school. Will she get the kids to school on time?",
  q: ["What problem does Mrs. Kormel have on the way to school?",
      "Have you ever gotten lost or been late somewhere?",
      "Write what you would do to help Mrs. Kormel find the way."],
  h: ["코멜 선생님은 학교로 가는 길에 어떤 문제를 겪나요?",
      "나는 길을 잃거나 어딘가에 늦은 적이 있나요?",
      "코멜 선생님이 길을 찾도록 나는 어떻게 도울지 적어 보세요."] };
ACT["S3760"] = { s: "When Ms. Todd, the new substitute teacher, comes to class, the kids doubt Miss Daisy has been kidnapped. They decide to do the detective work and get the goods on Ms. Todd.",
  q: ["What do the kids decide to do about Ms. Todd?",
      "Have you ever played detective to solve a mystery?",
      "Write what clues you would look for if you were investigating Ms. Todd."],
  h: ["아이들은 토드 선생님에 대해 무엇을 하기로 결심하나요?",
      "나는 탐정 놀이를 하며 수수께끼를 풀어 본 적이 있나요?",
      "내가 토드 선생님을 조사한다면 어떤 단서를 찾을지 적어 보세요."] };
ACT["S3761"] = { s: "Mrs. Patty, the school's secretary, always gives out the best Halloween candy ever! But rumor has it that she is a witch.",
  q: ["What rumor do the kids hear about Mrs. Patty?",
      "Have you ever heard a rumor about someone that turned out to be untrue?",
      "Write what kind of Halloween candy you would like to give out."],
  h: ["아이들은 패티 선생님에 대해 어떤 소문을 듣나요?",
      "나는 사실이 아니었던 소문을 들어 본 적이 있나요?",
      "내가 나눠 주고 싶은 할로윈 사탕을 적어 보세요."] };
ACT["S3762"] = { s: "Mr. Macky is the wacky reading specialist who believes he's Abe Lincoln. When it's President's Day, he wants the kids to read stuff about the presidents.",
  q: ["What does Mr. Macky want the kids to read for President's Day?",
      "Have you ever celebrated a holiday about a famous person at school?",
      "Write one fact you know about a president or famous leader."],
  h: ["매키 선생님은 대통령의 날에 아이들이 무엇을 읽기를 바라나요?",
      "나는 학교에서 유명한 인물을 기리는 날을 보낸 적이 있나요?",
      "대통령이나 유명한 지도자에 대해 내가 아는 사실을 한 가지 적어 보세요."] };
ACT["S3763"] = { s: "Ms. Coco runs the gifted and talented program at school. She motivates the kids to write poetry by discovering interesting ways.",
  q: ["What subject does Ms. Coco motivate the kids to write?",
      "Have you ever written a poem?",
      "Write one line of a poem about something you like."],
  h: ["코코 선생님은 아이들이 무엇을 쓰도록 이끌어 주나요?",
      "나는 시를 써 본 적이 있나요?",
      "내가 좋아하는 것에 대한 시 한 줄을 적어 보세요."] };
ACT["S3764"] = { s: "Miss Suki, a famous children's book author, comes to A.J.'s school for a visit with her pet raptor. But will the kids be safe with the raptor on the loose?",
  q: ["What pet does Miss Suki bring to A.J.'s school?",
      "Have you ever met an author who wrote a book you read?",
      "Write what you would ask Miss Suki if you met her."],
  h: ["수키 선생님은 A.J.네 학교에 어떤 애완동물을 데려오나요?",
      "나는 내가 읽은 책을 쓴 작가를 만난 적이 있나요?",
      "수키 선생님을 만난다면 무엇을 물어보고 싶은지 적어 보세요."] };
ACT["S3765"] = { s: "Mrs. Yonkers is a new computer lab teacher, and she tries to bring the second-grader into the twenty-first century.",
  q: ["What subject does Mrs. Yonkers teach?",
      "Have you ever used a computer at school?",
      "Write one thing you like to do on a computer."],
  h: ["용커스 선생님은 무슨 과목을 가르치나요?",
      "나는 학교에서 컴퓨터를 사용해 본 적이 있나요?",
      "컴퓨터로 하기 좋아하는 것을 한 가지 적어 보세요."] };
ACT["S3766"] = { s: "Dr. Carble gets grumpier than ever and tries to fire Mr. Klutz. The kids are on to save their principal's job.",
  q: ["What do the kids try to do to help Mr. Klutz?",
      "Have you ever tried to help someone keep their job or place in a team?",
      "Write what you would do to help save Mr. Klutz's job."],
  h: ["아이들은 클러츠 교장 선생님을 돕기 위해 무엇을 하려 하나요?",
      "나는 누군가 일자리나 자리를 지키도록 도운 적이 있나요?",
      "클러츠 교장 선생님의 자리를 지키기 위해 나는 무엇을 할지 적어 보세요."] };
ACT["S3767"] = { s: "Mr. Louie is a hippie crossing guard. For Valentine's Day, he puts a love potion in the water fountain.",
  q: ["What does Mr. Louie put in the water fountain for Valentine's Day?",
      "Have you ever celebrated Valentine's Day at school?",
      "Write what you would give a friend for Valentine's Day."],
  h: ["루이 아저씨는 밸런타인데이에 분수대에 무엇을 넣나요?",
      "나는 학교에서 밸런타인데이를 보낸 적이 있나요?",
      "밸런타인데이에 친구에게 주고 싶은 것을 적어 보세요."] };
ACT["S3768"] = { s: "Ms. Krup is a tour guide in the natural history museum. When she tells the kids that dinosaur skeletons come to life in the middle of the night, the place seems to be the coolest ever.",
  q: ["What does Ms. Krup tell the kids happens to the dinosaur skeletons at night?",
      "Have you ever visited a natural history museum?",
      "Write what dinosaur you would like to see come to life."],
  h: ["크럽 선생님은 밤에 공룡 뼈들에게 무슨 일이 일어난다고 말하나요?",
      "나는 자연사 박물관에 가 본 적이 있나요?",
      "살아 움직이는 모습을 보고 싶은 공룡을 적어 보세요."] };
ACT["S3769"] = { s: "It’s up to Mama and Papa to help the cubs understand that even though bad dreams can be scary, they aren’t real.",
  q: ["What do Mama and Papa help the cubs understand about bad dreams?",
      "Have you ever had a bad dream?",
      "Write what helps you feel better after a bad dream."],
  h: ["엄마와 아빠는 나쁜 꿈에 대해 새끼 곰들에게 무엇을 이해시켜 주나요?",
      "나는 나쁜 꿈을 꾼 적이 있나요?",
      "나쁜 꿈을 꾼 뒤 기분이 나아지게 해 주는 것을 적어 보세요."] };
ACT["S3770"] = { s: "When a big storm rolls through Bear Country, Papa and Mama help the cubs realize that they are all safe.",
  q: ["What do Papa and Mama help the cubs realize during the storm?",
      "Have you ever been in a big storm?",
      "Write one thing you are thankful for, like the cubs counting their blessings."],
  h: ["아빠와 엄마는 폭풍이 치는 동안 새끼 곰들에게 무엇을 깨닫게 해 주나요?",
      "나는 큰 폭풍을 겪은 적이 있나요?",
      "새끼 곰들처럼 내가 감사하게 여기는 것을 한 가지 적어 보세요."] };
ACT["S3771"] = { s: "Join Papa, Mama, and Brother, as they help Sister celebrate her birthday. The special day is not all fun and games when Sister becomes overwhelmed by all of the festivities.",
  q: ["Why does Sister become overwhelmed on her birthday?",
      "Have you ever felt overwhelmed on a special day like your birthday?",
      "Write what would make your birthday feel just right, not too much."],
  h: ["시스터는 생일에 왜 정신없이 벅차했나요?",
      "나는 생일처럼 특별한 날에 벅차다고 느낀 적이 있나요?",
      "너무 넘치지 않고 딱 알맞은 생일을 보내려면 무엇이 필요할지 적어 보세요."] };
ACT["S3772"] = { s: "Mama always makes the cubs' schedules tight, but sometimes it can cause too much pressure.",
  q: ["What does Mama always make tight for the cubs?",
      "Have you ever felt pressure from a busy schedule?",
      "Write what you would do to feel less pressure when you are busy."],
  h: ["엄마는 새끼 곰들의 무엇을 늘 빡빡하게 짜나요?",
      "나는 바쁜 일정 때문에 부담을 느낀 적이 있나요?",
      "바쁠 때 부담을 덜 느끼려면 나는 어떻게 할지 적어 보세요."] };
ACT["S3773"] = { s: "Brother has begun to tease Sister because he thinks it’s funny, but soon he learned a very valuable lesson.",
  q: ["Why does Brother start to tease Sister?",
      "Have you ever teased someone or been teased?",
      "Write what lesson you think Brother learned about teasing."],
  h: ["브라더는 왜 시스터를 놀리기 시작했나요?",
      "나는 누군가를 놀리거나 놀림을 받은 적이 있나요?",
      "브라더가 놀림에 대해 어떤 교훈을 배웠을지 적어 보세요."] };
ACT["S3774"] = { s: "Papa, Brother, and Sister have a new favorite hobby… watching TV. But when Mama feels like they are missing out on all the wonderful things around them.",
  q: ["What does the Bear family's new favorite hobby become?",
      "Have you ever watched too much TV and missed doing something else?",
      "Write one fun thing you could do instead of watching TV."],
  h: ["베어 가족이 새로 가장 좋아하게 된 취미는 무엇인가요?",
      "나는 TV를 너무 많이 보다가 다른 것을 놓친 적이 있나요?",
      "TV 대신 할 수 있는 재미있는 일을 한 가지 적어 보세요."] };
ACT["S3775"] = { s: "Papa, Mama, Brother, and Sister are heading to the Great Grizzly Mountains for a relaxing vacation.",
  q: ["Where is the Bear family heading for their vacation?",
      "Have you ever gone on a vacation with your family?",
      "Write where you would like to go for a relaxing vacation."],
  h: ["베어 가족은 휴가로 어디에 가나요?",
      "나는 가족과 함께 휴가를 가 본 적이 있나요?",
      "편안한 휴가를 보내고 싶은 곳을 적어 보세요."] };
ACT["S3776"] = { s: "It’s Valentine’s Day and Sister has a special card for a cub named Billy.",
  q: ["Who does Sister make a special Valentine's card for?",
      "Have you ever made a Valentine's card for someone?",
      "Write who you would like to give a Valentine's card to."],
  h: ["시스터는 누구를 위해 특별한 밸런타인 카드를 만드나요?",
      "나는 누군가를 위해 밸런타인 카드를 만들어 본 적이 있나요?",
      "내가 밸런타인 카드를 주고 싶은 사람을 적어 보세요."] };
ACT["S3777"] = { s: "The cubs are trying to collect the most Easter eggs, but when they discover a mama bird's nest about to hatch, it’s the true meaning of the holiday that they find.",
  q: ["What do the cubs discover while collecting Easter eggs?",
      "Have you ever gone on an Easter egg hunt?",
      "Write what you think the true meaning of Easter is, in your own words."],
  h: ["새끼 곰들은 부활절 달걀을 모으다가 무엇을 발견하나요?",
      "나는 부활절 달걀 찾기를 해 본 적이 있나요?",
      "부활절의 진짜 의미가 무엇인지 내 말로 적어 보세요."] };
ACT["S3778"] = { s: "From closets and drawers to the attic and the basement, the Bear family realize that they have too much stuff.",
  q: ["Where does the Bear family look and realize they have too much stuff?",
      "Have you ever cleaned out your closet or room to give things away?",
      "Write one thing you could give to someone in need."],
  h: ["베어 가족은 어디를 살펴보고 물건이 너무 많다는 것을 깨닫나요?",
      "나는 물건을 나눠 주려고 옷장이나 방을 정리해 본 적이 있나요?",
      "어려운 사람에게 나눠 줄 수 있는 물건을 한 가지 적어 보세요."] };
ACT["S3779"] = { s: "Sister has gotten into a bad habit of talking to strangers. So her parents show her the important rules of safety.",
  q: ["What bad habit has Sister gotten into?",
      "Have you ever learned safety rules about strangers?",
      "Write one safety rule you remember about strangers."],
  h: ["시스터는 어떤 나쁜 습관이 생겼나요?",
      "나는 낯선 사람에 대한 안전 규칙을 배운 적이 있나요?",
      "낯선 사람에 대해 기억하는 안전 규칙을 한 가지 적어 보세요."] };
ACT["S3780"] = { s: "Brother and Sister have agreed to help their elderly neighbor, Miz McGrizz, clean her attic.",
  q: ["What do Brother and Sister agree to help Miz McGrizz do?",
      "Have you ever helped an elderly neighbor with a task?",
      "Write one way you could help a neighbor."],
  h: ["브라더와 시스터는 미즈 맥그리즈를 무엇을 도와주기로 하나요?",
      "나는 나이 드신 이웃의 일을 도운 적이 있나요?",
      "이웃을 도울 수 있는 방법을 한 가지 적어 보세요."] };
ACT["S3781"] = { s: "A panda family moves next door and teaches the bears a lesson about acceptance of differences.",
  q: ["What lesson does the panda family teach the bears?",
      "Have you ever had new neighbors move in?",
      "Write what you would say to welcome a new neighbor."],
  h: ["판다 가족은 곰 가족에게 어떤 교훈을 가르쳐 주나요?",
      "나는 새 이웃이 이사 오는 것을 본 적이 있나요?",
      "새 이웃을 환영하며 하고 싶은 말을 적어 보세요."] };
ACT["S3782"] = { s: "Mama and Papa are going out, so Mrs.Grizzle is coming to babysit Brother and Sister.",
  q: ["Who comes to babysit Brother and Sister?",
      "Have you ever had a babysitter stay with you?",
      "Write what you like to do when a babysitter is with you."],
  h: ["누가 브라더와 시스터를 돌봐 주러 오나요?",
      "나는 베이비시터와 함께 있어 본 적이 있나요?",
      "베이비시터와 함께 있을 때 내가 하고 싶은 것을 적어 보세요."] };
ACT["S3783"] = { s: "The Bear family says goodbyes to friends, and move from the mountains and into their tree house down the sunny dirt road.",
  q: ["Where does the Bear family move to?",
      "Have you ever moved to a new home, or known someone who did?",
      "Write what you would miss most if you moved to a new home."],
  h: ["베어 가족은 어디로 이사하나요?",
      "나는 새집으로 이사해 본 적이 있거나, 이사한 사람을 알고 있나요?",
      "새집으로 이사한다면 가장 그리울 것을 적어 보세요."] };
ACT["S3784"] = { s: "Bear family has a baby girl named Honey! However, Sister isn’t sure she likes having the new baby in the tree house.",
  q: ["How does Sister feel about the new baby, Honey?",
      "Have you ever had a new baby join your family?",
      "Write how you would feel about having a new baby sister or brother."],
  h: ["시스터는 새로 태어난 허니에 대해 어떻게 느끼나요?",
      "나는 우리 가족에 새 아기가 생긴 적이 있나요?",
      "새 동생이 생긴다면 어떤 기분일지 적어 보세요."] };
ACT["S3785"] = { s: "When Mama opens her own quilt shop, Papa, Brother, and Sister have to adjust to a new routine.",
  q: ["What new shop does Mama open?",
      "Have you ever had to adjust to a new routine?",
      "Write what new routine you would need if your mom started a new job."],
  h: ["엄마는 어떤 새 가게를 여나요?",
      "나는 새로운 일과에 적응해야 했던 적이 있나요?",
      "엄마가 새 일을 시작한다면 나는 어떤 새 일과가 필요할지 적어 보세요."] };
ACT["S3786"] = { s: "It’s Father’s Day, and Papa thinks that Mama and the cubs have forgotten all about it. But they are actually planning something very special for him.",
  q: ["What does Papa think Mama and the cubs have forgotten?",
      "Have you ever planned a surprise for someone?",
      "Write what surprise you would like to plan for your dad."],
  h: ["아빠는 엄마와 새끼 곰들이 무엇을 잊었다고 생각하나요?",
      "나는 누군가를 위해 깜짝 선물을 계획해 본 적이 있나요?",
      "우리 아빠를 위해 계획하고 싶은 깜짝 선물을 적어 보세요."] };
ACT["S3787"] = { s: "Brother and Sister Bear don't want to spend a week with their grandparents, but they learn much from them.",
  q: ["What do Brother and Sister learn from their grandparents?",
      "Have you ever spent time with your grandparents?",
      "Write one thing you have learned from a grandparent."],
  h: ["브라더와 시스터는 할아버지, 할머니에게서 무엇을 배우나요?",
      "나는 할아버지, 할머니와 시간을 보낸 적이 있나요?",
      "할아버지나 할머니에게서 배운 것을 한 가지 적어 보세요."] };
ACT["S3788"] = { s: "After reading a scary book, Sister becomes afraid of the dark. Thankfully, Papa has some good ideas to help Sister conquer her fear.",
  q: ["What does Sister become afraid of after reading a scary book?",
      "Have you ever been afraid of the dark?",
      "Write one idea that could help someone conquer their fear of the dark."],
  h: ["시스터는 무서운 책을 읽은 뒤 무엇을 무서워하게 되나요?",
      "나는 어둠을 무서워한 적이 있나요?",
      "어둠에 대한 두려움을 이겨 내는 데 도움이 될 방법을 한 가지 적어 보세요."] };
ACT["S3789"] = { s: "When Brother and Sister start fighting, Mama and Papa help them remember that being kind to one another is the most important thing.",
  q: ["What do Mama and Papa help Brother and Sister remember?",
      "Have you ever had a fight with a brother, sister, or friend?",
      "Write one kind thing you could do for someone after a fight."],
  h: ["엄마와 아빠는 브라더와 시스터에게 무엇을 기억하게 해 주나요?",
      "나는 형제자매나 친구와 다툰 적이 있나요?",
      "다툰 뒤에 상대에게 해 줄 수 있는 친절한 행동을 한 가지 적어 보세요."] };
ACT["S3790"] = { s: "Brother and Sister break a lamp. When Mama asks them what happened, they tell her a series of whoppers that just get bigger and bigger.",
  q: ["What do Brother and Sister do when Mama asks about the lamp?",
      "Have you ever told a small lie that got bigger?",
      "Write why you think telling the truth is important."],
  h: ["엄마가 램프에 대해 묻자 브라더와 시스터는 무엇을 하나요?",
      "나는 작은 거짓말이 점점 커진 적이 있나요?",
      "진실을 말하는 것이 왜 중요한지 내 생각을 적어 보세요."] };
ACT["S3791"] = { s: "Brother just got a new bike for his birthday, and now Sister is green with envy.",
  q: ["Why is Sister green with envy?",
      "Have you ever felt jealous of something a sibling or friend got?",
      "Write what you do when you feel jealous of someone."],
  h: ["시스터는 왜 질투로 속이 상했나요?",
      "나는 형제자매나 친구가 가진 것을 부러워한 적이 있나요?",
      "누군가를 질투하는 마음이 들 때 나는 어떻게 하는지 적어 보세요."] };
ACT["S3792"] = { s: "Members of the bear family try to solve their problems without playing the blame game.",
  q: ["What game do the bear family try not to play when they have problems?",
      "Have you ever blamed someone else for a problem?",
      "Write one better way to solve a problem instead of blaming."],
  h: ["곰 가족은 문제가 생겼을 때 어떤 게임을 하지 않으려 하나요?",
      "나는 문제를 다른 사람 탓으로 돌린 적이 있나요?",
      "탓하는 대신 문제를 푸는 더 좋은 방법을 한 가지 적어 보세요."] };
ACT["S3793"] = { s: "Brother and Sister think Mama and Papa are too bossy, so the Bear family decides to switch places so they can see what life is like through each other’s eyes.",
  q: ["What does the Bear family decide to do to understand each other?",
      "Have you ever wished you could switch places with a parent for a day?",
      "Write what you think would be hard about being a grownup for a day."],
  h: ["베어 가족은 서로를 이해하기 위해 무엇을 하기로 하나요?",
      "나는 하루 동안 부모님과 자리를 바꾸고 싶었던 적이 있나요?",
      "하루 동안 어른이 된다면 무엇이 힘들지 적어 보세요."] };
ACT["S3794"] = { s: "The Bear family head to Doctor Grizzly’s office for their important check-ups.",
  q: ["Why does the Bear family go to Doctor Grizzly's office?",
      "Have you ever gone to the doctor for a check-up?",
      "Write how you feel when you go to the doctor."],
  h: ["베어 가족은 왜 그리즐리 의사 선생님의 병원에 가나요?",
      "나는 검진을 받으러 병원에 가 본 적이 있나요?",
      "병원에 갈 때 내 기분이 어떤지 적어 보세요."] };
ACT["S3795"] = { s: "The Bear family visit the dentist where they’ll get checked for cavities, have their teeth cleaned, and learn all about the tools a dentist uses to help keep teeth healthy.",
  q: ["What do the Bear family learn about at the dentist?",
      "Have you ever visited the dentist?",
      "Write one thing you do to keep your teeth healthy."],
  h: ["베어 가족은 치과에서 무엇에 대해 배우나요?",
      "나는 치과에 가 본 적이 있나요?",
      "이를 건강하게 지키기 위해 내가 하는 일을 한 가지 적어 보세요."] };
ACT["S3796"] = { s: "It’s time for the school play,?Grizzlystiltskin,?and Sister is playing the Princess! But she has stage fright.",
  q: ["What role does Sister play in the school play?",
      "Have you ever felt nervous before performing in front of others?",
      "Write what would help you feel less nervous before a performance."],
  h: ["시스터는 학예회에서 무슨 역할을 맡나요?",
      "나는 사람들 앞에서 공연하기 전에 긴장한 적이 있나요?",
      "공연 전에 긴장을 덜 느끼는 데 도움이 되는 것을 적어 보세요."] };
ACT["S3797"] = { s: "Brother and Sister are having a bad case of the 'gimmies.' Whenever they don’t get what they want, they throw a tantrum.",
  q: ["What do Brother and Sister do when they don't get what they want?",
      "Have you ever wanted something so badly that you got upset?",
      "Write what you could do instead of throwing a tantrum."],
  h: ["브라더와 시스터는 원하는 것을 얻지 못하면 무엇을 하나요?",
      "나는 무언가를 너무 갖고 싶어서 속상했던 적이 있나요?",
      "떼를 쓰는 대신 할 수 있는 것을 적어 보세요."] };
ACT["S3798"] = { s: "A new cub, Lizzie, has moved to town. But when bossiness enters the mix, Sister and Lizzie’s new friendship might be in trouble.",
  q: ["What causes trouble between Sister and Lizzie's new friendship?",
      "Have you ever had trouble with a friend because of bossiness?",
      "Write what you would say to a friend who was being too bossy."],
  h: ["시스터와 리지의 새 우정에 무엇이 문제를 일으키나요?",
      "나는 친구가 지나치게 이래라저래라 해서 힘들었던 적이 있나요?",
      "너무 이래라저래라 하는 친구에게 하고 싶은 말을 적어 보세요."] };
ACT["S3799"] = { s: "Brother and his friends are tired of Sister tagging along with them, so they create their own club where girls are not allowed.",
  q: ["What kind of club do Brother and his friends create?",
      "Have you ever been left out of a game or club?",
      "Write how you think Sister feels about being left out."],
  h: ["브라더와 친구들은 어떤 클럽을 만드나요?",
      "나는 놀이나 클럽에서 소외된 적이 있나요?",
      "소외된 시스터의 기분이 어떨지 적어 보세요."] };
