// 간이 학습 질문 — Book No. S38 묶음. 사람이 아니라 AI 가 한 번 쓰고 굳힌 파일이다.
window.ACT = window.ACT || {};
var ACT = window.ACT;
ACT["S3800"] = { s: "Brother Bear is feeling peer pressure from Too-Tall-Grizzly and his crew, and before you know it, Brother is accepting dangerous dares that they tell him to do.",
  q: ["What dangerous dares did Too-Tall-Grizzly's crew give to Brother Bear?",
      "Has a friend ever dared you to do something?",
      "Do you think Brother Bear should say no to the dares?"],
  h: ["투톨 그리즐리 무리는 브라더 베어에게 어떤 위험한 내기를 시켰나요?",
      "친구가 너에게 무언가를 해 보라고 부추긴 적이 있나요?",
      "브라더 베어가 그 내기를 거절해야 한다고 생각하나요?"] };
ACT["S3801"] = { s: "There is a bully at school, and the bully is picking on Sister! Will she ever be able to stand up for herself?",
  q: ["Who is the bully picking on at school?",
      "Have you ever seen someone being bullied?",
      "What do you think Sister should do to stand up for herself?"],
  h: ["학교에서 불량배가 누구를 괴롭히나요?",
      "누군가 괴롭힘을 당하는 것을 본 적이 있나요?",
      "시스터가 스스로를 지키려면 어떻게 해야 한다고 생각하나요?"] };
ACT["S3802"] = { s: "All the cubs in Bear Country are ready for the new school year except for Sister Bear. She is about to start kindergarten, but can't stop worrying about what it will be like.",
  q: ["Why is Sister Bear worried about starting kindergarten?",
      "Were you nervous on your first day of school?",
      "What would you say to Sister Bear to make her feel better?"],
  h: ["시스터 베어는 왜 유치원 시작을 걱정하나요?",
      "학교 첫날에 긴장한 적이 있나요?",
      "시스터 베어를 안심시키려면 어떤 말을 해 주고 싶나요?"] };
ACT["S3803"] = { s: "Brother gets in trouble when he allows television, his boom box, the telephone, and other distractions to get in the way of his homework.",
  q: ["What things distract Brother from doing his homework?",
      "What distracts you when you try to do your homework?",
      "What could Brother do to finish his homework without distractions?"],
  h: ["브라더가 숙제를 못 하게 방해한 것들은 무엇인가요?",
      "너는 숙제할 때 무엇 때문에 방해받나요?",
      "브라더가 방해받지 않고 숙제를 끝내려면 어떻게 해야 할까요?"] };
ACT["S3804"] = { s: "Sister Bear dislikes gym class so much that she takes advantage of a minor injury and sits on the sidelines instead.",
  q: ["Why does Sister Bear sit on the sidelines during gym class?",
      "Is there a class or activity you don't like?",
      "Do you think Sister Bear's excuse was fair?"],
  h: ["시스터 베어는 왜 체육 시간에 구경만 했나요?",
      "너는 싫어하는 수업이나 활동이 있나요?",
      "시스터 베어의 핑계가 정당하다고 생각하나요?"] };
ACT["S3805"] = { s: "When Brother Bear spends too much time on sports and brings home a terrible report card.",
  q: ["Why does Brother Bear bring home a terrible report card?",
      "Do you spend more time on sports or on homework?",
      "How can Brother Bear balance sports and school work?"],
  h: ["브라더 베어는 왜 나쁜 성적표를 받아 왔나요?",
      "너는 운동과 공부 중 어느 쪽에 시간을 더 많이 쓰나요?",
      "브라더 베어가 운동과 공부의 균형을 잡으려면 어떻게 해야 할까요?"] };
ACT["S3806"] = { s: "With the help of her family, Sister Bear breaks her habit of biting her nails.",
  q: ["What bad habit does Sister Bear break with her family's help?",
      "Do you have a habit you want to change?",
      "How did Sister Bear's family help her stop biting her nails?"],
  h: ["시스터 베어는 가족의 도움으로 어떤 나쁜 습관을 고쳤나요?",
      "너는 고치고 싶은 습관이 있나요?",
      "가족은 시스터 베어가 손톱 물어뜯기를 그만두도록 어떻게 도왔을까요?"] };
ACT["S3807"] = { s: "Sister has learned a new word and it’s a big blooper. How will Papa, Mama, and Brother react when they hear her say it?",
  q: ["What did Sister say that was a big blooper?",
      "Have you ever said a word you shouldn't have?",
      "How do you think Papa, Mama, and Brother reacted?"],
  h: ["시스터가 말한 큰 실수는 무엇이었을까요?",
      "너는 하면 안 되는 말을 한 적이 있나요?",
      "파파, 마마, 브라더는 어떻게 반응했을 것 같나요?"] };
ACT["S3808"] = { s: "Mama and Papa Bear try to teach Brother and Sister the value of money and how to manage their allowance.",
  q: ["What do Mama and Papa try to teach Brother and Sister?",
      "Do you get an allowance? How do you use it?",
      "What is a smart way to manage money?"],
  h: ["마마와 파파는 브라더와 시스터에게 무엇을 가르치려 했나요?",
      "너는 용돈을 받나요? 용돈을 어떻게 쓰나요?",
      "돈을 현명하게 관리하는 방법은 무엇일까요?"] };
ACT["S3809"] = { s: "Brother and Sister’s friends have started collecting a new toy called Beary Bubbies and the cubs just have to have them.",
  q: ["What new toy did the cubs' friends start collecting?",
      "Have you ever wanted a toy just because your friends had it?",
      "Do you think the cubs really need Beary Bubbies?"],
  h: ["친구들이 모으기 시작한 새 장난감은 무엇이었나요?",
      "친구들이 가지고 있어서 너도 갖고 싶었던 장난감이 있나요?",
      "새끼 곰들에게 정말 베어리 버비가 필요하다고 생각하나요?"] };
ACT["S3810"] = { s: "Mr. Putter and Mrs. Teaberry bring their pets to the library for a special storytime. Who knows what will happen?",
  q: ["Where do Mr. Putter and Mrs. Teaberry bring their pets?",
      "Have you ever gone to a special storytime at a library?",
      "What do you think happened when the pets came to storytime?"],
  h: ["미스터 퍼터와 미시즈 티베리는 반려동물을 어디로 데려갔나요?",
      "도서관에서 특별한 스토리타임에 가 본 적이 있나요?",
      "반려동물들이 스토리타임에 오면 무슨 일이 생길 것 같나요?"] };
ACT["S3811"] = { s: "Mr. Putter and his cat, Tabby, attend a cooking class with Mrs. Teaberry and her dog, Zeke. They learn 100 ways to cook beans. But when Zeke bites into something surprising, beans go flying!",
  q: ["What surprising thing does Zeke bite into?",
      "Have you ever taken a cooking class?",
      "What do you think happens after the beans go flying?"],
  h: ["제크가 깨문 놀라운 것은 무엇이었을까요?",
      "요리 수업을 들어 본 적이 있나요?",
      "콩들이 날아간 뒤에 무슨 일이 벌어졌을 것 같나요?"] };
ACT["S3812"] = { s: "Mr. Putter and Tabby take Mrs. Teaberry to the Conservatory for her birthday. Zeke tries his best to stay out of trouble until he sees the banana tree.",
  q: ["Where do Mr. Putter and Tabby take Mrs. Teaberry for her birthday?",
      "Have you ever visited a place full of plants or flowers?",
      "What trouble do you think Zeke gets into with the banana tree?"],
  h: ["미스터 퍼터와 태비는 생일을 맞은 미시즈 티베리를 어디로 데려갔나요?",
      "식물이나 꽃이 가득한 곳에 가 본 적이 있나요?",
      "제크가 바나나 나무 때문에 어떤 말썽을 부렸을 것 같나요?"] };
ACT["S3813"] = { s: "This book tells how the young Hungarian immigrant Ehrich Weiss worked to become the world famous magician Harry Houdini.",
  q: ["What did Ehrich Weiss become famous as?",
      "Have you ever seen a magic trick that amazed you?",
      "What do you think it took for him to become world famous?"],
  h: ["에리히 바이스는 무엇으로 유명해졌나요?",
      "너를 놀라게 한 마술을 본 적이 있나요?",
      "그가 세계적으로 유명해지기 위해 무엇이 필요했을 것 같나요?"] };
ACT["S3814"] = { s: "This book reviews the history of helicopters, explains how they work, and how they are used.",
  q: ["What does this book tell you about helicopters?",
      "Have you ever seen a real helicopter?",
      "Why do you think helicopters are useful?"],
  h: ["이 책은 헬리콥터에 대해 무엇을 알려 주나요?",
      "실제 헬리콥터를 본 적이 있나요?",
      "헬리콥터가 왜 쓸모 있다고 생각하나요?"] };
ACT["S3815"] = { s: "In 1940, four boys discovered drawings of prehistoric animals in Lascaux Cave in southwestern France. The walls of the cave were covered with life-size paintings of animals.",
  q: ["What did the four boys discover in Lascaux Cave?",
      "Have you ever discovered something surprising?",
      "Why do you think the cave paintings were important?"],
  h: ["네 소년은 라스코 동굴에서 무엇을 발견했나요?",
      "너는 놀라운 것을 발견한 적이 있나요?",
      "동굴 벽화가 왜 중요했다고 생각하나요?"] };
ACT["S3816"] = { s: "Near the Austrian-Italian border, a frozen body of a man that was later found to be more than 5000 years old was discovered.",
  q: ["Where was the frozen body of the ancient man discovered?",
      "Have you ever seen something very old in a museum?",
      "What do you want to know about the 5,000-year-old man?"],
  h: ["얼어붙은 고대인의 시신은 어디에서 발견되었나요?",
      "박물관에서 아주 오래된 것을 본 적이 있나요?",
      "5천 년 된 그 사람에 대해 무엇이 궁금한가요?"] };
ACT["S3817"] = { s: "When a dragon named Fred left his home, his parents gave him a list of how to be a good dragon. He went to a castle and ate people to prove that he is a good dragon. But, he started to feel sick and tries to find a way to feel better.",
  q: ["What list did Fred's parents give him about being a good dragon?",
      "Have you ever tried to follow rules someone gave you?",
      "Why do you think Fred started to feel sick after eating people?"],
  h: ["프레드의 부모님은 좋은 용이 되는 방법으로 어떤 목록을 주었나요?",
      "누군가 알려 준 규칙을 따라 본 적이 있나요?",
      "프레드가 사람들을 먹고 나서 왜 아팠을 것 같나요?"] };
ACT["S3818"] = { s: "This book tells the life of Harriet Tubman, including her childhood in slavery and her later work in helping other slaves escape north to freedom through the Underground Railroad.",
  q: ["What did Harriet Tubman do to help other slaves?",
      "Have you ever helped someone who needed you?",
      "Why do you think Harriet Tubman was brave?"],
  h: ["해리엇 터브먼은 다른 노예들을 돕기 위해 무엇을 했나요?",
      "너를 필요로 하는 사람을 도와준 적이 있나요?",
      "해리엇 터브먼이 왜 용감했다고 생각하나요?"] };
ACT["S3819"] = { s: "Astrid is freed from Maldred's time trap. Now, she is plotting to work on a spell to bring the bones scattered in the Fortress to life.",
  q: ["What is Astrid plotting to do with the bones in the Fortress?",
      "Have you ever read a story about magic spells?",
      "What do you think will happen if Astrid brings the bones to life?"],
  h: ["아스트리드는 요새의 뼈들로 무엇을 하려고 계획하나요?",
      "마법 주문이 나오는 이야기를 읽어 본 적이 있나요?",
      "아스트리드가 뼈들을 살아나게 하면 무슨 일이 벌어질 것 같나요?"] };
ACT["S3820"] = { s: "Dragon Masters must stop Astrid from casting an evil spell. Ana and Drake travel to an island to bring a Lava Dragon.",
  q: ["Where do Ana and Drake travel to find the Lava Dragon?",
      "Which dragon in this series do you like best?",
      "Why do you think they need the Lava Dragon to stop Astrid?"],
  h: ["아나와 드레이크는 라바 드래곤을 찾으러 어디로 갔나요?",
      "이 시리즈에 나온 용 중에 어떤 용이 가장 마음에 드나요?",
      "아스트리드를 막으려면 왜 라바 드래곤이 필요할까요?"] };
ACT["S3821"] = { s: "Drake, Bo, and Opeli travel to another island to find the help of the enormous Sea Dragon. They need the dragon to stop Astrid from casting her dangerous False Life spell.",
  q: ["Who do Drake, Bo, and Opeli travel to find on the island?",
      "Have you ever seen the ocean or a big sea creature?",
      "Why do they need the Sea Dragon's help?"],
  h: ["드레이크, 보, 오펠리는 섬에서 누구를 찾으러 갔나요?",
      "바다나 큰 바다 생물을 본 적이 있나요?",
      "그들에게 왜 바다 용의 도움이 필요할까요?"] };
ACT["S3822"] = { s: "Dragon Masters must go into battle when Evil wizard Astrid brings the Garden of Beasts to life.",
  q: ["What does Astrid bring to life to fight the Dragon Masters?",
      "Have you ever had to be brave before a big challenge?",
      "What do you think happens in the Garden of Beasts battle?"],
  h: ["아스트리드는 드래곤 마스터들과 싸우기 위해 무엇을 살아나게 했나요?",
      "큰 어려움 앞에서 용기를 내야 했던 적이 있나요?",
      "짐승의 정원에서의 싸움은 어떻게 되었을 것 같나요?"] };
ACT["S3823"] = { s: "Flower Dragon named Wildroot needs help because his home is in danger. This tiny dragon needs to find his own Dragon Master, too.",
  q: ["What kind of help does the Flower Dragon Wildroot need?",
      "Have you ever helped a small creature or friend in trouble?",
      "Who do you think will become Wildroot's Dragon Master?"],
  h: ["꽃 용 와일드루트에게는 어떤 도움이 필요한가요?",
      "위험에 처한 작은 동물이나 친구를 도와준 적이 있나요?",
      "누가 와일드루트의 드래곤 마스터가 될 것 같나요?"] };
ACT["S3824"] = { s: "Dr. Dolittle sets off with his animal friends on an adventure to the Land of the Monkeys in Africa.",
  q: ["Where do Dr. Dolittle and his animal friends go on their adventure?",
      "If you could talk to animals, what would you ask them?",
      "What do you think they find in the Land of the Monkeys?"],
  h: ["두리틀 박사와 동물 친구들은 어디로 모험을 떠났나요?",
      "동물과 말할 수 있다면 무엇을 물어보고 싶나요?",
      "원숭이의 나라에서 그들은 무엇을 발견했을 것 같나요?"] };
ACT["S3825"] = { s: "Just once, Frank Pearl would like to win at something. At the Great Third-Grade Breakfast Bash, with Judy Moody cheering him on, there's no way that Frank can miss out on a trophy this time.",
  q: ["What does Frank Pearl want to do at the Breakfast Bash?",
      "Have you ever really wanted to win something?",
      "How do you think Judy cheering him on made Frank feel?"],
  h: ["프랭크 펄은 브렉퍼스트 배시에서 무엇을 하고 싶어 하나요?",
      "무언가에서 꼭 이기고 싶었던 적이 있나요?",
      "주디가 응원해 준 것이 프랭크에게 어떤 기분을 주었을 것 같나요?"] };
ACT["S3826"] = { s: "Judy knows that Jaws the Venus flytrap is sick for sure when she sees it. In her quest for a medical miracle, Judy finds herself wrangling an unruly toad and seeking help from Mouse, the mind-reading cat.",
  q: ["What animals does Judy deal with to help her sick plant?",
      "Have you ever taken care of a sick pet or plant?",
      "How do you think Mouse the cat helps Judy?"],
  h: ["주디는 아픈 식물을 도우려고 어떤 동물들을 상대했나요?",
      "아픈 반려동물이나 식물을 돌본 적이 있나요?",
      "고양이 마우스가 주디를 어떻게 도왔을 것 같나요?"] };
ACT["S3827"] = { s: "Judy Moody tries to break the birthday jinx that happens every year on her mom's birthday by making sure everything goes right. She asks her brother to make a handmade present, her dad to make a carrot cake from scratch, and she makes a phone-number bracelet. Unfortunately, none of the presents turn out as expected, and the birthday jinx continues until they all give their mom thoughtful presents that show they care.",
  q: ["What does Judy do to try to break her mom's birthday jinx?",
      "What kind of present would you make for someone you love?",
      "Why do you think thoughtful presents finally broke the jinx?"],
  h: ["주디는 엄마의 생일 징크스를 깨려고 무엇을 했나요?",
      "사랑하는 사람에게 어떤 선물을 만들어 주고 싶나요?",
      "정성 어린 선물이 왜 결국 징크스를 깨뜨렸을까요?"] };
ACT["S3828"] = { s: "Mr. Todd tells the class about the origins of April Fools' Day and some different ways it is celebrated around the world. Judy Moody, one of the students, gets an idea to play an April Fools' joke on Mr. Todd.",
  q: ["What idea does Judy Moody get after learning about April Fools' Day?",
      "Have you ever played an April Fools' joke on someone?",
      "What joke do you think Judy plays on Mr. Todd?"],
  h: ["만우절에 대해 배운 뒤 주디 무디는 어떤 생각을 떠올렸나요?",
      "만우절에 누군가에게 장난을 쳐 본 적이 있나요?",
      "주디가 토드 선생님께 어떤 장난을 쳤을 것 같나요?"] };
ACT["S3829"] = { s: "Judy is a righty. She is feeling left out when Stink and Dad are celebrating Left Handers Day. What is she going to do?",
  q: ["Why does Judy feel left out on Left Handers Day?",
      "Have you ever felt left out when others celebrated something?",
      "What do you think Judy does to join in the celebration?"],
  h: ["주디는 왜 왼손잡이의 날에 소외감을 느꼈나요?",
      "다른 사람들이 무언가를 기념할 때 소외감을 느낀 적이 있나요?",
      "주디는 축하 자리에 함께하려고 어떻게 했을 것 같나요?"] };
ACT["S3830"] = { s: "Stink is on a dig, dig, digging quest in his backyard to find a tooth from a saber-toothed cat. Will Stink make a discovery before their whole backyard caves in?",
  q: ["What is Stink searching for in his backyard?",
      "Have you ever dug in the dirt looking for something?",
      "Do you think Stink will find the tooth before the backyard caves in?"],
  h: ["스팅크는 뒷마당에서 무엇을 찾고 있나요?",
      "무언가를 찾으려고 땅을 파 본 적이 있나요?",
      "뒷마당이 무너지기 전에 스팅크가 이빨을 찾을 수 있을 것 같나요?"] };
ACT["S3831"] = { s: "Judy can’t wait to play a prank on Stink when Stink discovers that his backyard science project is an overnight success.",
  q: ["What is Stink's overnight success that Judy wants to prank him about?",
      "Have you ever played a harmless prank on a family member?",
      "What kind of prank do you think Judy plans?"],
  h: ["스팅크가 하룻밤 사이 성공시킨 과학 프로젝트는 무엇이었나요?",
      "가족에게 장난을 쳐 본 적이 있나요?",
      "주디는 어떤 장난을 계획했을 것 같나요?"] };
ACT["S3832"] = { s: "Judy and her newfound friend, Mighty Fantaskey, draw inspiration from their beloved detective as they embark on a quest to locate a missing mood ring in a eerie attic.",
  q: ["What do Judy and Mighty Fantaskey search for in the attic?",
      "Have you ever lost something important and searched for it?",
      "What clues do you think help them find the mood ring?"],
  h: ["주디와 마이티 판타스키는 다락방에서 무엇을 찾고 있나요?",
      "소중한 물건을 잃어버려서 찾아본 적이 있나요?",
      "무드 링을 찾는 데 어떤 단서가 도움이 되었을 것 같나요?"] };
ACT["S3834"] = { s: "Jared, Mallory and Simon, having escaped goblins and trolls, are now being harassed by a house boggart. Mallory thinks the only way to stop the madness is to get rid of the Guide. And the only person who can help them is their strange old Aunt Lucinda.",
  q: ["Who does Mallory think can help them get rid of the house boggart?",
      "Have you ever asked an older relative for help with a problem?",
      "What secret do you think Aunt Lucinda knows?"],
  h: ["맬러리는 누가 집 보가트를 없애는 데 도움이 될 거라 생각하나요?",
      "어려운 일을 나이 많은 친척에게 도움을 청해 본 적이 있나요?",
      "루신다 이모는 어떤 비밀을 알고 있을 것 같나요?"] };
ACT["S3835"] = { s: "he monster alarm rings while Princess Magnolia is having tea with Duchess Wigtower. A monster is trying to attack the goats. Magnolia sneaks away to become the Princess in Black and stop the monster.",
  q: ["What is the monster trying to attack in this book?",
      "Do you have a secret talent or a secret you keep?",
      "Why do you think Magnolia keeps her superhero identity a secret?"],
  h: ["이 책에서 괴물은 무엇을 공격하려고 하나요?",
      "너에게는 남모르는 재주나 비밀이 있나요?",
      "매그놀리아가 왜 슈퍼히어로라는 사실을 비밀로 했을 것 같나요?"] };
ACT["S3836"] = { s: "Defeating a monster just in time to attend her own birthday party, Princess Magnolia, the secret superhero Princess in Black, is repeatedly interrupted by the Monster Alarm in ways that threaten to expose her secret.",
  q: ["What keeps interrupting Princess Magnolia's birthday party?",
      "Has something ever interrupted your birthday plans?",
      "How do you think she keeps her secret safe at her own party?"],
  h: ["매그놀리아 공주의 생일 파티를 계속 방해한 것은 무엇인가요?",
      "너의 생일 계획이 방해받은 적이 있나요?",
      "자기 생일 파티에서 그녀는 비밀을 어떻게 지켰을 것 같나요?"] };
ACT["S3837"] = { s: "Princess Magnolia and her unicorn are on their way to brunch when the monster alarm rings. They change into their superhero alter egos and rush to the scene. They find a field of bunnies that aren't as innocent as they seem.",
  q: ["What do Princess Magnolia and her unicorn find in the field?",
      "Have you ever thought something looked harmless but wasn't?",
      "Why do you think the bunnies aren't as innocent as they seem?"],
  h: ["매그놀리아 공주와 유니콘은 들판에서 무엇을 발견했나요?",
      "겉보기에는 순해 보였지만 아니었던 것을 본 적이 있나요?",
      "토끼들이 왜 보이는 것처럼 순하지 않았을 것 같나요?"] };
ACT["S3838"] = { s: "After battling monsters all night, a sleepy Princess in Black decides that she needs a vacation. After all, the Goat Avenger has offered to protect the goats while she's away. The very next day Princess Magnolia rides her bicycle to the seaside, where the air is salty, the sun is shiny, and the sea is as blue as monster fur. But just as Princess Magnolia is about to take a nap on her hammock, she hears a \"ROAR!\" Could a sea monster ruin this vacation for the Princess in Black?",
  q: ["Why does the Princess in Black decide she needs a vacation?",
      "Where would you like to go on a vacation?",
      "Do you think a sea monster will really ruin her vacation?"],
  h: ["프린세스 인 블랙은 왜 휴가가 필요하다고 생각했나요?",
      "너는 어디로 휴가를 가고 싶나요?",
      "바다 괴물이 정말 그녀의 휴가를 망칠 것 같나요?"] };
ACT["S3839"] = { s: "A pet-eating monster interrupts Princess Magnolia's perfect playdate with Princess Sneezewort. When Princess in Black goes to investigate, she finds a new masked avenger.",
  q: ["What kind of monster interrupts the playdate?",
      "Have you ever had a playdate interrupted by something?",
      "Who do you think the new masked avenger is?"],
  h: ["놀이 약속을 방해한 괴물은 어떤 괴물이었나요?",
      "놀이 약속이 무언가 때문에 방해받은 적이 있나요?",
      "새로 나타난 가면 쓴 영웅은 누구일 것 같나요?"] };
ACT["S3840"] = { s: "At the science fair, a squishy goo monster is a challenge for the Princess in Black. Luckily some science-fair loving princesses are on hand to help.",
  q: ["What kind of monster shows up at the science fair?",
      "Have you ever been part of a science fair?",
      "How do you think the science-fair princesses help her?"],
  h: ["과학 박람회에 나타난 괴물은 어떤 괴물이었나요?",
      "과학 박람회에 참여해 본 적이 있나요?",
      "과학 박람회 공주들이 그녀를 어떻게 도왔을 것 같나요?"] };
ACT["S3841"] = { s: "When the goat pasture is plagued with a foul stench, the Princess in Black and her friends must take on a stinky beast.",
  q: ["What problem plagues the goat pasture in this book?",
      "Have you ever had to deal with a bad smell?",
      "How do you think the Princess in Black deals with the stinky beast?"],
  h: ["이 책에서 염소 목장에 어떤 문제가 생겼나요?",
      "나쁜 냄새 때문에 곤란했던 적이 있나요?",
      "프린세스 인 블랙은 냄새나는 괴물을 어떻게 처리했을 것 같나요?"] };
ACT["S3842"] = { s: "Mo LoBeau is an eleven-year-old girl who was abandoned as a baby in Tupelo Landing, North Carolina. She teams up with her friend Dale to become detectives when a crime appears to involve her caretaker - Colonel and Miss Lana.",
  q: ["Who does Mo LoBeau team up with to become a detective?",
      "Have you ever solved a mystery with a friend?",
      "Why do you think Mo wants to protect Colonel and Miss Lana?"],
  h: ["모 로보는 탐정이 되기 위해 누구와 팀을 이루었나요?",
      "친구와 함께 수수께끼를 풀어 본 적이 있나요?",
      "모는 왜 콜로넬과 미스 라나를 지키고 싶어 했을 것 같나요?"] };
ACT["S3843"] = { s: "Jack's class has a new teacher and Jack is worried. She seems so different from Ms. Walton - will the class learn anything?",
  q: ["Why is Jack worried about the new teacher?",
      "Have you ever had a new teacher you weren't sure about?",
      "What do you think helps Jack's class learn from her?"],
  h: ["잭은 왜 새 선생님을 걱정하나요?",
      "낯설게 느껴진 새 선생님을 만나 본 적이 있나요?",
      "잭의 반이 새 선생님께 배우는 데 무엇이 도움이 되었을 것 같나요?"] };
ACT["S3844"] = { s: "Billie goes to the beach! She digs up the sand to make the most beautiful sandcastle. But then she finds a tiny bottle.",
  q: ["What does Billie find in the sand at the beach?",
      "Have you ever built a sandcastle at the beach?",
      "What do you think is inside the tiny bottle?"],
  h: ["빌리는 해변 모래 속에서 무엇을 발견했나요?",
      "해변에서 모래성을 쌓아 본 적이 있나요?",
      "작은 병 안에는 무엇이 들어 있을 것 같나요?"] };
ACT["S3845"] = { s: "The Princess in Black is ready for her snowy playdate with the Goat Avenger and the Princess in Blankets. It's a perfect day to build snow monsters and battle them for practice. But just when they're about to wage battle, a huge foot smashes their snow monster. With a noisy giant crashing around the kingdom, the Princess in Black uses the Sparkle Signal to call ALL her heroic friends together - for the biggest adventure yet.",
  q: ["What smashes the snow monster during the playdate?",
      "Have you ever built something out of snow?",
      "Why do you think the Princess in Black calls all her friends together?"],
  h: ["놀이 약속 중에 눈 괴물을 부순 것은 무엇이었나요?",
      "눈으로 무언가를 만들어 본 적이 있나요?",
      "프린세스 인 블랙은 왜 모든 친구를 불러 모았을까요?"] };
ACT["S3846"] = { s: "When a mermaid princess needs help protecting her adorable sea goats from being eaten by a greedy kraken, the Princess in Black and her friends come to her rescue.",
  q: ["What is the kraken trying to eat in this book?",
      "Have you ever helped a new friend who needed protection?",
      "Why do you think the mermaid princess asks the Princess in Black for help?"],
  h: ["이 책에서 크라켄은 무엇을 잡아먹으려 했나요?",
      "보호가 필요한 새 친구를 도와준 적이 있나요?",
      "인어 공주는 왜 프린세스 인 블랙에게 도움을 청했을까요?"] };
ACT["S3847"] = { s: "When her plans for the Flower Festival are ruined, Princess Magnolia accepts the help of a valiant new hero to save the evening.",
  q: ["What happens to Princess Magnolia's plans for the Flower Festival?",
      "Has your plan for an event ever been ruined?",
      "Who do you think the valiant new hero, the Prince in Pink, is?"],
  h: ["매그놀리아 공주의 플라워 페스티벌 계획에 무슨 일이 생겼나요?",
      "계획했던 행사가 망가진 적이 있나요?",
      "용감한 새 영웅 핑크 왕자는 누구일 것 같나요?"] };
ACT["S3848"] = { s: "Eva is busy preparing for the spring festival with her friend Lucy. Overwhelmed by the long to-do list, Eva insists on managing everything alone?until she learns the value of teamwork.",
  q: ["What does Eva learn while preparing for the spring festival?",
      "Have you ever tried to do too much by yourself?",
      "Why is teamwork important when preparing for an event?"],
  h: ["에바는 봄 축제를 준비하며 무엇을 배웠나요?",
      "혼자 너무 많은 일을 하려고 한 적이 있나요?",
      "행사를 준비할 때 왜 팀워크가 중요할까요?"] };
ACT["S3849"] = { s: "Eva feels jealous when the new owl, Hailey, becomes friends with Lucy instead of her, but she wonders if they can all be friends together.",
  q: ["Why does Eva feel jealous of the new owl, Hailey?",
      "Have you ever felt jealous when a friend made a new friend?",
      "Do you think Eva, Lucy, and Hailey can all be friends together?"],
  h: ["에바는 왜 새로 온 올빼미 헤일리를 질투했나요?",
      "친구가 새 친구를 사귀어서 질투를 느낀 적이 있나요?",
      "에바, 루시, 헤일리가 모두 함께 친구가 될 수 있을 것 같나요?"] };
ACT["S3850"] = { s: "Eva enjoys crafting gifts for her friends for the party at the Old Oak Tree, but this time she didn't have enough time to make gifts!",
  q: ["What problem does Eva have before the Warm Hearts Day party?",
      "Have you ever run out of time to make something?",
      "What could Eva do since she didn't have time to make gifts?"],
  h: ["웜 하츠 데이 파티 전에 에바에게 어떤 문제가 생겼나요?",
      "무언가를 만들 시간이 부족했던 적이 있나요?",
      "선물을 만들 시간이 없었던 에바는 어떻게 했을까요?"] };
ACT["S3851"] = { s: "Eva and her classmates are preparing for their Owl Oath ceremony, where Eva must show bravery, wisdom, and kindness to save the day.",
  q: ["What three things must Eva show at the Owl Oath ceremony?",
      "Have you ever had to show courage to help someone?",
      "How do you think Eva saves the day?"],
  h: ["에바는 아울 오스 의식에서 무엇 세 가지를 보여야 하나요?",
      "누군가를 돕기 위해 용기를 내야 했던 적이 있나요?",
      "에바는 어떻게 상황을 해결했을 것 같나요?"] };
ACT["S3852"] = { s: "Eva's class was excited about their field trip to the pumpkin farm. But their excitement turns to mystery-solving when an award-winning pumpkin disappears.",
  q: ["What mystery happens on Eva's class trip to the pumpkin farm?",
      "Have you ever gone on a field trip to a farm?",
      "Who do you think took the award-winning pumpkin?"],
  h: ["에바의 반이 호박 농장으로 간 현장학습에서 어떤 수수께끼가 일어났나요?",
      "농장으로 현장학습을 가 본 적이 있나요?",
      "상을 받은 호박을 누가 가져갔을 것 같나요?"] };
ACT["S3853"] = { s: "Eva is going on a camping trip with her classmates. She can't wait for tent-pitching, campfire treats, and forest treasure hunts.",
  q: ["What is Eva most excited about on the camping trip?",
      "Have you ever gone camping with your class or family?",
      "What would you look forward to most on a camping trip?"],
  h: ["에바는 캠핑 여행에서 무엇을 가장 기대하나요?",
      "반 친구들이나 가족과 캠핑을 가 본 적이 있나요?",
      "캠핑 여행에서 네가 가장 기대하는 것은 무엇인가요?"] };
ACT["S3854"] = { s: "Eva and her friends eagerly prepare for the school play. But when Sue takes the lead role, Eva worries she won't get her chance to shine.",
  q: ["Why does Eva worry about the school play?",
      "Have you ever wanted a bigger role in something you were part of?",
      "What do you think Eva does even without the lead role?"],
  h: ["에바는 학교 연극에 대해 왜 걱정하나요?",
      "네가 참여한 일에서 더 큰 역할을 맡고 싶었던 적이 있나요?",
      "주연을 맡지 못해도 에바는 어떻게 했을 것 같나요?"] };
ACT["S3855"] = { s: "Eva eagerly wants a new pet, but she cannot decide. With Lucy's idea, they start pet-sitting various animals!",
  q: ["What idea does Lucy give Eva about choosing a pet?",
      "If you could pet-sit any animal, which would you choose?",
      "Why do you think pet-sitting helps Eva decide?"],
  h: ["루시는 애완동물을 고르는 것에 대해 에바에게 어떤 생각을 주었나요?",
      "어떤 동물이든 돌봐 줄 수 있다면 무엇을 고르고 싶나요?",
      "동물을 돌보는 경험이 에바가 결정하는 데 왜 도움이 되었을까요?"] };
ACT["S3856"] = { s: "Eva must wear a sling for a week! She couldn’t even write in her diary with her injured wing, so her friends and family help her.",
  q: ["Why can't Eva write in her diary for a week?",
      "Has anyone ever helped you when you were hurt?",
      "How do you think Eva's friends and family help her?"],
  h: ["에바는 왜 일주일 동안 일기를 쓸 수 없었나요?",
      "네가 다쳤을 때 누군가 도와준 적이 있나요?",
      "에바의 친구와 가족은 그녀를 어떻게 도왔을 것 같나요?"] };
ACT["S3857"] = { s: "Bo and the unicorns of Sparklegrove Forest embark on a quest to recover missing items, leading them to the dragon caves. Will they encounter a fearsome creature or make a new friend instead?",
  q: ["Where does the quest for missing items lead Bo and the unicorns?",
      "Have you ever been afraid of meeting something new?",
      "Do you think they find a fearsome creature or a new friend?"],
  h: ["사라진 물건을 찾는 모험은 보와 유니콘들을 어디로 이끌었나요?",
      "새로운 존재를 만나는 것이 두려웠던 적이 있나요?",
      "그들은 무서운 존재를 만났을까요, 아니면 새 친구를 사귀었을까요?"] };
ACT["S3858"] = { s: "Bo and the Sparklegrove unicorns aim to earn their Bravery Patch, unsure if they'll face a monster, but learn bravery comes in various forms, including standing up for others.",
  q: ["What do Bo and the unicorns learn about bravery?",
      "Have you ever been brave for someone else, not just yourself?",
      "What does it mean to be brave by standing up for others?"],
  h: ["보와 유니콘들은 용기에 대해 무엇을 배웠나요?",
      "다른 사람을 위해 용기를 낸 적이 있나요?",
      "다른 이를 위해 나서는 것이 용감하다는 것은 무슨 뜻일까요?"] };
ACT["S3859"] = { s: "Bo and Sunny help bored goblin princess Greta by granting her wish for flying powers, but when things spiral out of control, they must find a way to fix the mess and teach Greta about the power of imagination.",
  q: ["What wish do Bo and Sunny grant to goblin princess Greta?",
      "Have you ever helped a bored friend find something fun to do?",
      "What do you think they teach Greta about imagination?"],
  h: ["보와 서니는 고블린 공주 그레타의 어떤 소원을 들어주었나요?",
      "심심해하는 친구가 재미있는 일을 찾도록 도와준 적이 있나요?",
      "그들은 그레타에게 상상력에 대해 무엇을 가르쳐 주었을 것 같나요?"] };
ACT["S3860"] = { s: "Bo and friends embark on a quest to aid a merbaby who can't swim, meeting a werewolf and learning water tricks along the way, ultimately realizing that Flo is perfect as she is.",
  q: ["What problem does the merbaby have that Bo and friends help with?",
      "Have you ever learned that you didn't need to change to be perfect?",
      "Why is it good that Flo learns she is perfect as she is?"],
  h: ["인어 아기에게는 어떤 문제가 있었고 보와 친구들은 그것을 어떻게 도왔나요?",
      "바뀌지 않아도 그 자체로 완벽하다는 것을 깨달은 적이 있나요?",
      "플로가 지금 모습 그대로 완벽하다는 것을 깨달은 것이 왜 좋은 일일까요?"] };
ACT["S3861"] = { s: "Cookie wanted to be perfect and know every answer to the questions, but that wasn’t possible. Then, Ms. Biscotti, the teacher, assigned a special homework task?to create something original.",
  q: ["What homework task does Ms. Biscotti give the class?",
      "Have you ever tried to be perfect at everything?",
      "Why is it hard to know every answer all the time?"],
  h: ["비스코티 선생님은 반에 어떤 숙제를 내 주었나요?",
      "모든 것을 완벽하게 하려고 애써 본 적이 있나요?",
      "항상 모든 답을 아는 것이 왜 어려울까요?"] };
ACT["S3862"] = { s: "The Sour Grape holds grudges?lots of them. Whether it's a small slight or a big offense, this grape remembers it all.",
  q: ["What does the Sour Grape do when something upsets it?",
      "Have you ever held onto a grudge?",
      "Why might it be hard to let go of a grudge?"],
  h: ["사워 그레이프는 화나는 일이 생기면 어떻게 하나요?",
      "너는 누군가에게 서운했던 마음을 오래 품어 본 적이 있나요?",
      "서운한 마음을 내려놓기가 왜 어려울까요?"] };
ACT["S3867"] = { s: "Gordon Blue becomes Kung Pow Chicken to solve the mystery of disappearing feathers in Fowladelphia. As shivering chickens are forced to wear wooly sweaters, Kung Pow Chicken races in his Beakmobile to save the day!",
  q: ["What mystery does Kung Pow Chicken solve in Fowladelphia?",
      "Have you ever felt cold and needed to wear a sweater?",
      "What do you think happens to the missing feathers?"],
  h: ["쿵파우 치킨은 파울라델피아에서 어떤 수수께끼를 풀었나요?",
      "추워서 스웨터가 필요했던 적이 있나요?",
      "사라진 깃털들은 어떻게 되었을 것 같나요?"] };
ACT["S3868"] = { s: "When the opera singer Honey Comb is chicknapped, Kung Pow Chicken must stop Dr. Screech from turning her voice into a supersonic weapon and rescue her!",
  q: ["Who does Kung Pow Chicken need to stop from using Honey Comb's voice?",
      "Have you ever heard someone with a really beautiful singing voice?",
      "How do you think Kung Pow Chicken rescues Honey Comb?"],
  h: ["쿵파우 치킨은 허니 콤의 목소리를 이용하려는 누구를 막아야 했나요?",
      "정말 아름다운 노래 목소리를 가진 사람을 만나 본 적이 있나요?",
      "쿵파우 치킨은 허니 콤을 어떻게 구했을 것 같나요?"] };
ACT["S3869"] = { s: "Chickens are acting like zombies, and Kung Pow Chicken suspects the evil Birdbrain is behind it. But when he's captured by the zombie army, he must find a way to stop the brain-stealing villain and save the day!",
  q: ["Who does Kung Pow Chicken suspect is turning chickens into zombies?",
      "Have you ever watched a movie about zombies?",
      "How do you think Kung Pow Chicken escapes the zombie army?"],
  h: ["쿵파우 치킨은 닭들을 좀비로 만든 것이 누구라고 의심했나요?",
      "좀비가 나오는 영화를 본 적이 있나요?",
      "쿵파우 치킨은 좀비 군대에서 어떻게 탈출했을 것 같나요?"] };
ACT["S3870"] = { s: "Dr. Seuss is the Cat in the Hat, and today He'll tell you all about the great dinosaur!",
  q: ["What does the Cat in the Hat teach you about in this book?",
      "Which dinosaur is your favorite?",
      "What is one fact about dinosaurs you already know?"],
  h: ["이 책에서 캣 인 더 햇은 무엇에 대해 가르쳐 주나요?",
      "네가 가장 좋아하는 공룡은 무엇인가요?",
      "공룡에 대해 네가 이미 알고 있는 사실을 하나 적어 보세요."] };
ACT["S3871"] = { s: "No matter how far you travel, a map on your lap will always help you know where you are.",
  q: ["How does a map help you when you travel?",
      "Have you ever used a map to find your way?",
      "Where would you like to use a map to travel to?"],
  h: ["지도는 여행할 때 어떻게 도움을 주나요?",
      "길을 찾으려고 지도를 사용해 본 적이 있나요?",
      "지도를 가지고 어디로 가 보고 싶나요?"] };
ACT["S3872"] = { s: "The Cat in the Hat takes Sally and Dick for an “umbrella-vator” ride through the understory, canopy, and emergent layers of a tropical rain forest, encountering a host of plants, animals, and native peoples along the way.",
  q: ["What are the three layers of the rain forest in this book?",
      "Have you ever learned about a rain forest before?",
      "What animal or plant would you like to see in the rain forest?"],
  h: ["이 책에 나온 열대 우림의 세 층은 무엇인가요?",
      "열대 우림에 대해 배워 본 적이 있나요?",
      "열대 우림에서 보고 싶은 동물이나 식물은 무엇인가요?"] };
ACT["S3873"] = { s: "Dr. Seuss is the Cat in the Hat, and today we will go to the Short-Shaggy-Tail-Waggy Super Dog Show!",
  q: ["What is the name of the dog show in this book?",
      "Have you ever been to a dog show or seen one on TV?",
      "What kind of dog would you like to show?"],
  h: ["이 책에 나오는 개 쇼의 이름은 무엇인가요?",
      "개 쇼에 가 보거나 텔레비전에서 본 적이 있나요?",
      "너는 어떤 개를 쇼에 데리고 나가고 싶나요?"] };
ACT["S3874"] = { s: "Dr. Seuss is the Cat in the Hat. Pack your bag. Come with him. We’re going to Africa on safari!",
  q: ["Where does the Cat in the Hat take you in this book?",
      "Have you ever seen African animals at a zoo?",
      "Which African animal would you most like to see on safari?"],
  h: ["이 책에서 캣 인 더 햇은 너를 어디로 데려가나요?",
      "동물원에서 아프리카 동물을 본 적이 있나요?",
      "사파리에서 가장 보고 싶은 아프리카 동물은 무엇인가요?"] };
ACT["S3875"] = { s: "Butterflies are surprising and beautiful things as they soar through the air on their bright-colored wings.",
  q: ["What does this book say butterflies do on their wings?",
      "Have you ever seen a butterfly up close?",
      "What color wings would you give your own butterfly?"],
  h: ["이 책은 나비가 날개로 무엇을 한다고 말하나요?",
      "나비를 가까이에서 본 적이 있나요?",
      "네가 나비를 그린다면 날개를 무슨 색으로 하고 싶나요?"] };
ACT["S3876"] = { s: "Fun facts about mammals, from the land to the sea, the smallest (pygmy shrew) to the largest (blue whale), and more.",
  q: ["What is the smallest mammal mentioned in this book?",
      "What is your favorite mammal?",
      "Why do you think it's fun to compare the smallest and largest mammals?"],
  h: ["이 책에 나온 가장 작은 포유류는 무엇인가요?",
      "네가 가장 좋아하는 포유류는 무엇인가요?",
      "가장 작은 포유류와 가장 큰 포유류를 비교하는 것이 왜 재미있을까요?"] };
ACT["S3877"] = { s: "Dr. Seuss is the Cat in the Hat. We must leave right away. Can you guess what he's cooking for breakfast today?",
  q: ["What is the Cat in the Hat cooking for breakfast in this book?",
      "Have you ever eaten an egg for breakfast?",
      "What animal do you think hatches from an egg?"],
  h: ["이 책에서 캣 인 더 햇은 아침으로 무엇을 요리하고 있나요?",
      "아침에 달걀을 먹어 본 적이 있나요?",
      "알에서 부화하는 동물로 어떤 것이 떠오르나요?"] };
ACT["S3878"] = { s: "Fun facts about butterflies, ants, bees, and more.",
  q: ["What insects does this book give fun facts about?",
      "What insect have you seen recently?",
      "Which insect fact would you like to learn more about?"],
  h: ["이 책은 어떤 곤충들에 대한 재미있는 사실을 알려 주나요?",
      "최근에 본 곤충이 있나요?",
      "어떤 곤충에 대해 더 알아보고 싶나요?"] };
ACT["S3879"] = { s: "Fun facts about cats, from domestic to wild, kittens to cubs, and more.",
  q: ["What kinds of cats does this book tell fun facts about?",
      "Do you have a cat, or do you know someone who does?",
      "Would you rather learn about a wild cat or a kitten?"],
  h: ["이 책은 어떤 종류의 고양이들에 대한 재미있는 사실을 알려 주나요?",
      "너는 고양이를 키우거나 고양이를 키우는 사람을 아나요?",
      "야생 고양이와 아기 고양이 중 어느 쪽에 대해 더 배우고 싶나요?"] };
ACT["S3880"] = { s: "You see, weather keeps changing, but one thing we know. It makes life exciting wherever you go. Fun facts about the sun, thunderstorms, snowflakes, and more",
  q: ["What kinds of weather does this book give fun facts about?",
      "What was the weather like today?",
      "What is your favorite kind of weather and why?"],
  h: ["이 책은 어떤 날씨에 대한 재미있는 사실을 알려 주나요?",
      "오늘 날씨는 어땠나요?",
      "네가 가장 좋아하는 날씨는 무엇이고 그 이유는 무엇인가요?"] };
ACT["S3881"] = { s: "What’s the story today? Funny that you should ask. We’re going to take on a whale of a task! Fun facts about whales, porpoises, dolphins, and more.",
  q: ["What sea animals does this book give fun facts about?",
      "Have you ever seen a whale or a dolphin?",
      "What would you like to know about whales?"],
  h: ["이 책은 어떤 바다 동물들에 대한 재미있는 사실을 알려 주나요?",
      "고래나 돌고래를 본 적이 있나요?",
      "고래에 대해 무엇이 궁금한가요?"] };
ACT["S3882"] = { s: "Dr. Seuss is the Cat in the Hat and tonight we’ll take flight and meet some of the critters that come out at night. Fun facts about raccoons, wolves, fireflies, and more",
  q: ["What nocturnal animals does this book mention?",
      "Have you ever seen an animal that only comes out at night?",
      "Why do you think some animals come out only at night?"],
  h: ["이 책에는 어떤 야행성 동물들이 나오나요?",
      "밤에만 나오는 동물을 본 적이 있나요?",
      "어떤 동물들은 왜 밤에만 나올까요?"] };
ACT["S3883"] = { s: "Fun facts about narwals, dolphins, sharks, giant squid, manatees, and more.",
  q: ["What sea creatures does this book give fun facts about?",
      "Which sea creature in this book would you like to see for real?",
      "What is the biggest sea creature you can think of?"],
  h: ["이 책은 어떤 바다 생물들에 대한 재미있는 사실을 알려 주나요?",
      "이 책에 나온 바다 생물 중 실제로 보고 싶은 것은 무엇인가요?",
      "네가 생각할 수 있는 가장 큰 바다 생물은 무엇인가요?"] };
ACT["S3884"] = { s: "You may think that deserts are empty and bare, but you’ll be surprised by the things we’ll find there…",
  q: ["What surprising things does this book say you can find in a desert?",
      "Have you ever thought a place was empty but it wasn't?",
      "Why do you think deserts are dry?"],
  h: ["이 책은 사막에서 어떤 놀라운 것들을 찾을 수 있다고 말하나요?",
      "비어 있을 거라 생각했지만 아니었던 곳이 있나요?",
      "사막은 왜 건조하다고 생각하나요?"] };
ACT["S3885"] = { s: "Dr. Seuss is the Cat in the Hat. Come and travel with him to find animals that are not easy to see.",
  q: ["What kind of animals does this book help you find?",
      "Have you ever had trouble spotting an animal that blends in?",
      "Why do some animals hide so well in their surroundings?"],
  h: ["이 책은 어떤 동물들을 찾도록 도와주나요?",
      "주변과 비슷해서 찾기 힘든 동물을 본 적이 있나요?",
      "어떤 동물들은 왜 주변에 잘 숨을 수 있을까요?"] };
ACT["S3886"] = { s: "In a super shark tank that is like a small sea, we will visit with sharks. Dr. Seuss dare you to come with him.",
  q: ["Where does this book take you to visit sharks?",
      "Have you ever seen a shark at an aquarium or on TV?",
      "Are you excited or scared to visit the shark tank? Why?"],
  h: ["이 책은 상어를 보러 너를 어디로 데려가나요?",
      "수족관이나 텔레비전에서 상어를 본 적이 있나요?",
      "상어 탱크를 방문하는 것이 설레나요, 무섭나요? 왜 그런가요?"] };
ACT["S3887"] = { s: "Fun facts about money, including pennies, dollars, gold, and more.",
  q: ["What does this book give fun facts about?",
      "Have you ever saved coins or dollars?",
      "What would you buy if you saved up your money?"],
  h: ["이 책은 무엇에 대한 재미있는 사실을 알려 주나요?",
      "동전이나 지폐를 모아 본 적이 있나요?",
      "돈을 모으면 무엇을 사고 싶나요?"] };
ACT["S3892"] = { s: "While stopping to admire some of the world’s most amazing trees, the Cat in the Hat teaches beginning readers how to identify different species from the shape of their crowns, leaves, lobes, seeds, bark, and fruit.",
  q: ["How does the Cat in the Hat teach you to identify trees?",
      "Have you ever looked closely at a tree's leaves or bark?",
      "What is your favorite kind of tree?"],
  h: ["캣 인 더 햇은 나무를 구별하는 법을 어떻게 가르쳐 주나요?",
      "나무의 잎이나 나무껍질을 자세히 살펴본 적이 있나요?",
      "네가 가장 좋아하는 나무는 무엇인가요?"] };
ACT["S3893"] = { s: "Cat introduces Sally and Nick to all things horsey.",
  q: ["What does the Cat introduce Sally and Nick to in this book?",
      "Have you ever ridden or petted a horse?",
      "What would you like to learn about horses?"],
  h: ["이 책에서 캣은 샐리와 닉에게 무엇을 소개하나요?",
      "말을 타거나 쓰다듬어 본 적이 있나요?",
      "말에 대해 무엇을 배우고 싶나요?"] };
ACT["S3894"] = { s: "The Cat in the Hat takes Sally and Dick on a trip in his Inside Your Outside Machine to learn about the human body.",
  q: ["Where does the Cat take Sally and Dick to learn about the body?",
      "What part of your body do you think is the most interesting?",
      "What would you like to know about how your body works?"],
  h: ["캣은 몸에 대해 배우려고 샐리와 딕을 어디로 데려가나요?",
      "네 몸에서 가장 흥미로운 부분은 무엇이라고 생각하나요?",
      "네 몸이 어떻게 작동하는지 무엇이 궁금한가요?"] };
ACT["S3895"] = { s: "Dr. Seuss's Cat in the Hat introduces Sally and Dick to the planets, stars, and moons in our universe.",
  q: ["What does the Cat introduce Sally and Dick to in this book?",
      "Have you ever looked up at the stars at night?",
      "Which planet would you most like to visit?"],
  h: ["캣은 샐리와 딕에게 무엇을 소개하나요?",
      "밤에 하늘의 별을 올려다본 적이 있나요?",
      "가장 가 보고 싶은 행성은 무엇인가요?"] };
ACT["S3896"] = { s: "Dr. Seuss's Cat in the Hat introduces Sally and Dick to a variety of birds, from the ten-foot ostrich to the two-inch hummingbird.",
  q: ["What is the biggest bird and the smallest bird in this book?",
      "What bird have you seen near your home?",
      "Which bird in this book would you like to see in real life?"],
  h: ["이 책에서 가장 큰 새와 가장 작은 새는 무엇인가요?",
      "집 근처에서 본 새가 있나요?",
      "이 책에 나온 새 중에 실제로 보고 싶은 새는 무엇인가요?"] };
ACT["S3897"] = { s: "Fish is hosting a seaside talk show for the Fish Channel, and some of the guests include a clam, a horseshoe crab, and a sea star.",
  q: ["Who are the guests on Fish's seaside talk show?",
      "Have you ever collected shells or seen sea creatures at the beach?",
      "Which beach creature in this book would you like to meet?"],
  h: ["피시의 해변 토크쇼에 나온 손님들은 누구인가요?",
      "해변에서 조개껍데기를 모으거나 바다 생물을 본 적이 있나요?",
      "이 책에 나온 해변 생물 중 만나 보고 싶은 것은 무엇인가요?"] };
ACT["S3898"] = { s: "In rhyming format, the Cat in the Hat talks about all the animals that make good pets. how to pick the pet that is best for you, and how to care for them.",
  q: ["What does the Cat in the Hat talk about in this book?",
      "If you could pick a new pet, which animal would you choose?",
      "How would you take care of your pet?"],
  h: ["이 책에서 캣 인 더 햇은 무엇에 대해 이야기하나요?",
      "새 반려동물을 고를 수 있다면 어떤 동물을 고르고 싶나요?",
      "네 반려동물을 어떻게 돌봐 줄 건가요?"] };
ACT["S3899"] = { s: "The Cat in the Hat examines the various parts of plants, seeds, flowers, basic photosynthesis, pollination, and seed dispersal.",
  q: ["What parts of a plant does the Cat in the Hat examine?",
      "Have you ever planted a seed and watched it grow?",
      "What would you like to grow from a seed?"],
  h: ["캣 인 더 햇은 식물의 어떤 부분들을 살펴보나요?",
      "씨앗을 심고 자라는 모습을 지켜본 적이 있나요?",
      "씨앗에서 무엇을 키워 보고 싶나요?"] };
