// 간이 학습 질문 — Book No. S39 묶음. 사람이 아니라 AI 가 한 번 쓰고 굳힌 파일이다.
window.ACT = window.ACT || {};
var ACT = window.ACT;
ACT["S3900"] = { s: "The Cat in the Hat introduces Dick and Sally to various animal babies in the wild.",
  q: ["What animal babies did the Cat in the Hat show Dick and Sally?",
      "Have you ever seen a baby animal in the wild?",
      "What wild animal baby would you like to see?"],
  h: ["모자 쓴 고양이는 딕과 샐리에게 어떤 아기 동물들을 보여 주었나요?",
      "너는 야생에서 아기 동물을 본 적이 있나요?",
      "너는 어떤 아기 야생 동물을 보고 싶나요?"] };
ACT["S3901"] = { s: "The Cat in the Hat travels the world in his crocodile car to investigate the habitats and characteristics of lizards, snakes, turtles, and unique species of reptiles.",
  q: ["What reptiles did the Cat in the Hat investigate in his crocodile car?",
      "Have you ever seen a lizard, snake, or turtle?",
      "What reptile would you like to learn more about?"],
  h: ["모자 쓴 고양이는 악어 자동차를 타고 어떤 파충류를 조사했나요?",
      "너는 도마뱀이나 뱀, 거북을 본 적이 있나요?",
      "너는 어떤 파충류에 대해 더 알고 싶나요?"] };
ACT["S3902"] = { s: "The Cat in the Hat takes Sally and Dick to a pond to explore all the plants and animals in and around the water. On their adventure, they study how frogs develop and examples of metamorphosis.",
  q: ["What did Sally and Dick learn about how frogs develop?",
      "Have you ever visited a pond and seen plants or animals there?",
      "What would you like to know about how frogs change as they grow?"],
  h: ["샐리와 딕은 개구리가 어떻게 자라는지에 대해 무엇을 배웠나요?",
      "너는 연못에 가서 식물이나 동물을 본 적이 있나요?",
      "개구리가 자라며 변하는 모습에 대해 너는 무엇이 궁금한가요?"] };
ACT["S3903"] = { s: "Ten-year-old George Calder feels like the luckiest boy in the world. He's traveling across the Atlantic on the legendary Titanic, accompanied by his sister and Aunt Daisy.",
  q: ["Why does George Calder feel like the luckiest boy in the world at the start of this book?",
      "Have you ever traveled somewhere with your family that made you excited?",
      "What do you think will happen to George on the Titanic?"],
  h: ["이야기 처음에 조지 캘더는 왜 자기가 세상에서 가장 운 좋은 소년이라고 느꼈나요?",
      "너는 가족과 함께 여행을 가서 신났던 적이 있나요?",
      "타이타닉호에서 조지에게 무슨 일이 일어날 것 같나요?"] };
ACT["S3904"] = { s: "Chet Roscow is just starting to feel like he belongs in Elm Hills, New Jersey? but his peaceful summer is suddenly disrupted by terrifying news: a massive shark has been attacking people in the water nearby.",
  q: ["What terrifying news disrupted Chet's peaceful summer?",
      "Have you ever had a peaceful day suddenly interrupted by scary news?",
      "What would you do if you heard a shark was near the water?"],
  h: ["무슨 무서운 소식이 쳇의 평화로운 여름을 방해했나요?",
      "너는 평화롭던 날에 갑자기 무서운 소식을 들은 적이 있나요?",
      "근처에 상어가 있다는 소식을 들으면 너는 어떻게 하겠나요?"] };
ACT["S3905"] = { s: "Ten-year-old Leo enjoys being a newsboy in San Francisco. As the new century begins the city feels full of hope. But one spring morning, everything changes.",
  q: ["What was Leo's job in San Francisco before everything changed?",
      "Have you ever had a morning where everything suddenly changed?",
      "What do you think happened on that spring morning?"],
  h: ["모든 것이 바뀌기 전, 샌프란시스코에서 레오가 하던 일은 무엇이었나요?",
      "너는 어느 날 아침 갑자기 모든 것이 바뀌었던 적이 있나요?",
      "그 봄날 아침에 무슨 일이 일어났을 것 같나요?"] };
ACT["S3906"] = { s: "Astrid can’t wait to attend roller derby camp, but her best friend Nicole opts for dance instead. As Astrid navigates the challenges of a brand-new sport, she befriends someone unexpected?and fears she’s drifting away from Nicole.",
  q: ["Why did Astrid go to roller derby camp without Nicole?",
      "Have you ever tried a new activity that a friend did not want to try with you?",
      "What would you say to Astrid about making a new friend?"],
  h: ["애스트리드는 왜 니콜 없이 롤러더비 캠프에 갔나요?",
      "너는 친구가 함께 하고 싶어 하지 않은 새로운 활동을 해 본 적이 있나요?",
      "새 친구를 사귄 애스트리드에게 너는 무슨 말을 해 주고 싶나요?"] };
ACT["S3907"] = { s: "Birthday shopping isn't easy for six-year-old triplets.",
  q: ["Why isn't birthday shopping easy for the six-year-old triplets?",
      "Have you ever gone shopping for a birthday gift?",
      "What gift would you choose for a triplet's birthday?"],
  h: ["여섯 살 세쌍둥이에게 생일 선물 사기가 왜 쉽지 않았나요?",
      "너는 생일 선물을 사러 가 본 적이 있나요?",
      "세쌍둥이의 생일에 너라면 어떤 선물을 고르겠나요?"] };
ACT["S3908"] = { s: "Nick Mack finds that good luck comes to him in many different ways. But on his birthday, will his biggest wish come true? Three short stories",
  q: ["In what different ways does good luck come to Nick Mack?",
      "Have you ever had good luck happen to you in a surprising way?",
      "What do you think Nick Mack's biggest wish is?"],
  h: ["좋은 행운은 닉 맥에게 어떤 여러 가지 방식으로 찾아왔나요?",
      "너는 뜻밖의 방식으로 행운이 찾아온 적이 있나요?",
      "닉 맥의 가장 큰 소원은 무엇일 것 같나요?"] };
ACT["S3909"] = { s: "Three short stories about the Murphy family: the Murphy's cut the grass, get a dose of head lice, and see a UFO flying above the woods.",
  q: ["What three things happen to the Murphy family in this book?",
      "Have you ever helped cut the grass at home?",
      "What would you do if you saw a UFO flying above the woods?"],
  h: ["이 책에서 머피 가족에게 일어난 세 가지 일은 무엇인가요?",
      "너는 집에서 잔디 깎는 것을 도와본 적이 있나요?",
      "숲 위로 UFO가 날아가는 것을 본다면 너는 어떻게 하겠나요?"] };
ACT["S3910"] = { s: "Angelina, the dancing mouse, discovers what a special day a birthday can be.",
  q: ["What does Angelina the dancing mouse discover about her birthday?",
      "Have you ever had a birthday that felt special?",
      "What would make your birthday feel special?"],
  h: ["춤추는 생쥐 안젤리나는 생일이 얼마나 특별한 날인지 깨달았나요?",
      "너는 특별하게 느껴졌던 생일이 있었나요?",
      "무엇이 있으면 네 생일이 특별하게 느껴질까요?"] };
ACT["S3911"] = { s: "Hubie dreads the upcoming class election, imagining all sorts of horrible consequences and gruesome scenarios involving his teacher, Mrs. Green, if he is forced to run for class president.",
  q: ["What horrible scenarios does Hubie imagine about the class election?",
      "Have you ever dreaded doing something at school?",
      "What would you say to Hubie to help him feel less worried?"],
  h: ["휴비는 학급 회장 선거에 대해 어떤 끔찍한 상황들을 상상했나요?",
      "너는 학교에서 하기 싫었던 일이 있었나요?",
      "걱정하는 휴비에게 너는 무슨 말을 해 주고 싶나요?"] };
ACT["S3912"] = { s: "Under the strict supervision of Mrs. Green, Hubie must create an invention for the annual Science Fair. He wrestles with his fears and his imagination while deciding whether to build a clone or a laughter machine.",
  q: ["What two inventions does Hubie consider building for the Science Fair?",
      "Have you ever had to make something for a school project?",
      "Which invention would you choose to build, a clone or a laughter machine?"],
  h: ["휴비는 과학 박람회를 위해 어떤 두 가지 발명품을 만들지 고민했나요?",
      "너는 학교 과제로 무언가를 만들어 본 적이 있나요?",
      "너라면 복제품과 웃음 기계 중 무엇을 만들겠나요?"] };
ACT["S3913"] = { s: "When Mrs. Green mandates that all students must participate in the school's talent show, Hubie faces severe stage fright as he prepares his piano lessons and magic act.",
  q: ["What two acts does Hubie prepare for the talent show?",
      "Have you ever felt nervous before performing in front of others?",
      "What talent would you like to show in a talent show?"],
  h: ["휴비는 장기 자랑을 위해 어떤 두 가지를 준비했나요?",
      "너는 사람들 앞에서 무언가를 보여 주기 전에 긴장한 적이 있나요?",
      "너는 장기 자랑에서 어떤 재주를 보여 주고 싶나요?"] };
ACT["S3914"] = { s: "A trip to the sweet factory is full of surprises for Albert and his new pet Rocky the raccoon.",
  q: ["What surprises happen to Albert and Rocky at the sweet factory?",
      "Have you ever visited a factory or a special place with a pet?",
      "What pet would you like to bring on a surprising trip?"],
  h: ["앨버트와 로키는 사탕 공장에서 어떤 뜻밖의 일들을 겪었나요?",
      "너는 공장이나 특별한 곳에 반려동물과 함께 가 본 적이 있나요?",
      "너는 어떤 반려동물과 함께 뜻밖의 여행을 떠나고 싶나요?"] };
ACT["S3915"] = { s: "Teresa \"Tree\" is a teenager who has spent her life taking care of her disabled younger brother, Dab, while their mother, Vy, works. Tree meets a mysterious, handsome ghost named Brother Rush who allows her to travel back in time to witness the tragic history of her family, forcing her to confront the truth about Dab and Vy.",
  q: ["Who is the mysterious ghost that Tree meets in this book?",
      "Have you ever taken care of a younger brother or sister?",
      "What do you think Tree learns about her family's history?"],
  h: ["트리가 이 책에서 만난 신비로운 유령은 누구인가요?",
      "너는 동생을 돌본 적이 있나요?",
      "트리는 가족의 역사에 대해 무엇을 알게 될 것 같나요?"] };
ACT["S3916"] = { s: "When their mother starts dropping them off at the library several afternoons a week, nine-year-old William and his brother dread boredom and the overbearing librarian, but they are surprised at how things turn out.",
  q: ["What did William and his brother dread about going to the library?",
      "Have you ever gone somewhere expecting to be bored?",
      "What do you think surprised William and his brother at the library?"],
  h: ["윌리엄과 남동생은 도서관에 가는 것에 대해 무엇을 걱정했나요?",
      "너는 지루할 것이라 생각하고 어딘가에 갔던 적이 있나요?",
      "도서관에서 윌리엄과 남동생을 놀라게 한 것은 무엇이었을 것 같나요?"] };
ACT["S3917"] = { s: "This biography discusses the life and work of Abigail Adams, devoted wife, mother, and patriot. As the second First Lady of a new republic, she helped her husband, John Adams, make important decisions that influenced the history of the United States.",
  q: ["What role did Abigail Adams have as the second First Lady?",
      "Have you ever helped someone in your family make an important decision?",
      "What do you think made Abigail Adams a good helper to her husband?"],
  h: ["애비게일 애덤스는 두 번째 영부인으로서 어떤 역할을 했나요?",
      "너는 가족이 중요한 결정을 내릴 때 도와준 적이 있나요?",
      "애비게일 애덤스가 남편을 잘 도울 수 있었던 이유는 무엇이었을 것 같나요?"] };
ACT["S3918"] = { s: "George Washington helped form the United States into what it is today by making wise decisions. After becoming a war hero in the French and Indian War, he went on to lead a fight against the British in the American Revolution. He continued his legacy by becoming the first president of the United States.",
  q: ["What war made George Washington a war hero before the American Revolution?",
      "Have you ever made a wise decision that helped you or others?",
      "What do you think it was like to be the first president of the United States?"],
  h: ["조지 워싱턴은 미국 독립 전쟁 전에 어떤 전쟁에서 전쟁 영웅이 되었나요?",
      "너는 너 자신이나 다른 사람에게 도움이 되는 현명한 결정을 내린 적이 있나요?",
      "미국의 첫 번째 대통령이 되는 것은 어떤 기분이었을 것 같나요?"] };
ACT["S3919"] = { s: "The school carnival is coming up, but Hubie is certain that instead of fun and games, the event will be a terrifying nightmare filled with grotesque attractions and scary rides.",
  q: ["What kind of nightmare does Hubie imagine the school carnival will be?",
      "Have you ever worried that an event would not be fun?",
      "What ride or game would you like to have at a school carnival?"],
  h: ["휴비는 학교 축제가 어떤 끔찍한 악몽이 될 것이라고 상상했나요?",
      "너는 어떤 행사가 재미없을까 봐 걱정한 적이 있나요?",
      "학교 축제에 어떤 놀이 기구나 게임이 있으면 좋겠나요?"] };
ACT["S3920"] = { s: "\"Name one good thing about winter,\" demands Princess Rosa. Then in from the cold comes the best thing of all.",
  q: ["What does Princess Rosa demand at the beginning of this book?",
      "Have you ever thought something good could come from the cold winter?",
      "What good thing about winter would you tell Princess Rosa?"],
  h: ["이 책 처음에 로사 공주는 무엇을 말해 보라고 요구했나요?",
      "너는 추운 겨울에서 좋은 것이 올 수 있다고 생각한 적이 있나요?",
      "로사 공주에게 너라면 겨울의 어떤 좋은 점을 말해 주고 싶나요?"] };
ACT["S3921"] = { s: "When Miss Perry is sick, Iris and Walter get a substitute teacher named Mrs. Miller. The new teacher seems very strict and makes Iris feel shy and uncomfortable, leading her to have a terrible day at school. Walter suggests a creative way for Iris to cope with the change, and they both learn that first impressions can sometimes be wrong, and change isn't always scary.",
  q: ["How did the substitute teacher, Mrs. Miller, make Iris feel at first?",
      "Have you ever had a substitute teacher at your school?",
      "What creative idea do you think Walter suggests to help Iris?"],
  h: ["대리 선생님 밀러 선생님은 처음에 아이리스를 어떤 기분이 들게 했나요?",
      "너는 학교에서 대리 선생님을 만나 본 적이 있나요?",
      "월터는 아이리스를 돕기 위해 어떤 창의적인 방법을 생각해 냈을 것 같나요?"] };
ACT["S3922"] = { s: "Children watch in amazement as the bicycle food deliverers of Tokyo stack their noodle bowls like architects, zip through the city like acrobats, and deliver delicious noodles to students, office workers, and families.",
  q: ["How do the bicycle food deliverers of Tokyo stack their noodle bowls?",
      "Have you ever watched someone deliver food on a bicycle?",
      "What food would you like a bicycle deliverer to bring you?"],
  h: ["도쿄의 자전거 음식 배달부들은 국수 그릇을 어떻게 쌓나요?",
      "너는 자전거로 음식을 배달하는 사람을 본 적이 있나요?",
      "자전거 배달부가 너에게 어떤 음식을 가져다주면 좋겠나요?"] };
ACT["S3923"] = { s: "While a young girl and her father share an early morning horseback ride around their town, he tells her cowboy stories and she realizes she is a cowboy too.",
  q: ["What does the girl realize while riding horseback with her father?",
      "Have you ever gone somewhere early in the morning with a parent?",
      "What cowboy story would you like your father to tell you?"],
  h: ["여자아이는 아빠와 말을 타며 무엇을 깨달았나요?",
      "너는 이른 아침에 부모님과 함께 어딘가에 가 본 적이 있나요?",
      "아빠에게 어떤 카우보이 이야기를 듣고 싶나요?"] };
ACT["S3924"] = { s: "During a family road trip to Mexico, young Pedro Martin?connects with his grandfather and learns more about his own Mexican identity. Text contains mild violence, disturbing imagery, and references to racism and religious bias.",
  q: ["What does Pedro learn about during his family's road trip to Mexico?",
      "Have you ever gone on a road trip with your family?",
      "What would you like to learn about your own family's roots?"],
  h: ["페드로는 가족과 함께 멕시코로 떠난 여행에서 무엇을 배웠나요?",
      "너는 가족과 함께 자동차 여행을 떠나 본 적이 있나요?",
      "너는 우리 가족의 뿌리에 대해 무엇을 알고 싶나요?"] };
ACT["S3925"] = { s: "A nest of baby Invisible Dragons has been discovered in Aragon, and the babies' parents are nowhere to be found. The baby dragons need to eat the fruit from the magical Dragon Tree to keep their invisible powers",
  q: ["What do the baby Invisible Dragons need to eat to keep their powers?",
      "Have you ever had to take care of a baby animal?",
      "What do you think happened to the baby dragons' parents?"],
  h: ["아기 투명 드래곤들은 힘을 유지하기 위해 무엇을 먹어야 하나요?",
      "너는 아기 동물을 돌봐 본 적이 있나요?",
      "아기 드래곤들의 부모님에게 무슨 일이 일어났을 것 같나요?"] };
ACT["S3926"] = { s: "Chaya and his Dragon Master Aruna are responsible for a huge shadow stretching across the sky. The Dragon Masters must learn how Chaya and Aruna?have so much power and why other wizards around the world are losing theirs.",
  q: ["What are Chaya and Aruna responsible for in this book?",
      "Have you ever wondered why something powerful was happening?",
      "Why do you think other wizards are losing their power?"],
  h: ["이 책에서 차야와 아루나는 무엇에 책임이 있나요?",
      "너는 어떤 강력한 일이 왜 일어나는지 궁금했던 적이 있나요?",
      "다른 마법사들이 힘을 잃는 이유는 무엇일 것 같나요?"] };
ACT["S3927"] = { s: "One step closer to stopping the Shadow Dragon from blanketing the world with its sky-shadow, Drake and the rest of the Dragon Masters must learn how to play the Star Flute in order to summon the Star Dragon.",
  q: ["What must Drake and the Dragon Masters learn to play to summon the Star Dragon?",
      "Have you ever learned to play a musical instrument?",
      "What do you think will happen when they summon the Star Dragon?"],
  h: ["드레이크와 드래곤 마스터들은 스타 드래곤을 부르기 위해 무엇을 연주하는 법을 배워야 하나요?",
      "너는 악기 연주하는 법을 배운 적이 있나요?",
      "스타 드래곤을 불러내면 어떤 일이 일어날 것 같나요?"] };
ACT["S3928"] = { s: "While Drake and Rori travel to rescue their friend Griffith, they team up with a boy named Llew and try to gain the trust of a Crystal Dragon.",
  q: ["Who do Drake and Rori team up with to rescue Griffith?",
      "Have you ever teamed up with someone new to help a friend?",
      "What would you do to gain the trust of a dragon?"],
  h: ["드레이크와 로리는 그리피스를 구하기 위해 누구와 힘을 합쳤나요?",
      "너는 친구를 돕기 위해 새로운 사람과 힘을 합친 적이 있나요?",
      "드래곤의 신뢰를 얻기 위해 너라면 무엇을 하겠나요?"] };
ACT["S3929"] = { s: "On a mission to retrieve a powerful object from the wizard Zoltan, Drake and Bo befriend another dragon master and his ghost dragon.",
  q: ["What powerful object do Drake and Bo try to retrieve from the wizard Zoltan?",
      "Have you ever made a new friend while working on a mission or task?",
      "What do you think a ghost dragon looks like?"],
  h: ["드레이크와 보는 마법사 졸탄에게서 어떤 강력한 물건을 되찾으려 했나요?",
      "너는 어떤 일을 하다가 새로운 친구를 사귄 적이 있나요?",
      "유령 드래곤은 어떤 모습일 것 같나요?"] };
ACT["S3930"] = { s: "This is a rip-roaringly funny collection of over 500 jokes and 'gigglesome gags' inspired by the wonderful world of Roald Dahl. Featuring beloved characters like Willy Wonka and the BFG, it is designed to make even the grumpiest person laugh.",
  q: ["Which characters from Roald Dahl's books are featured in this joke book?",
      "Have you ever told a joke that made someone laugh?",
      "What is your favorite joke or funny thing to say?"],
  h: ["이 유머책에는 로알드 달의 책 속 어떤 인물들이 나오나요?",
      "너는 누군가를 웃게 만든 농담을 해 본 적이 있나요?",
      "네가 가장 좋아하는 농담이나 재미있는 말은 무엇인가요?"] };
ACT["S3931"] = { s: "This is a brilliant collection of jokes, riddles, and puns inspired by Roald Dahl's beloved character, Matilda Wormwood. It features hundreds of hilarious gags about school, teachers, and clever kids, perfect for sharing with friends and family.",
  q: ["What are the jokes in this book about, besides Matilda herself?",
      "Have you ever shared a joke with your friends or family?",
      "What joke about school would you like to make up?"],
  h: ["이 책 속 농담들은 마틸다 말고 또 무엇에 관한 것인가요?",
      "너는 친구나 가족과 농담을 나눠 본 적이 있나요?",
      "너는 학교에 관한 어떤 농담을 만들어 보고 싶나요?"] };
ACT["S3932"] = { s: "A wonderfully wacky collection of jokes and puns inspired by Roald Dahl's 'George's Marvellous Medicine'. It is packed with hundreds of 'splendiferous' jokes about doctors, inventions, and crazy concoctions that will leave readers in stitches.",
  q: ["What are the jokes in this book about?",
      "Have you ever made up a silly invention or recipe?",
      "What funny medicine or invention would you like to create?"],
  h: ["이 책 속 농담들은 무엇에 관한 것인가요?",
      "너는 엉뚱한 발명품이나 레시피를 만들어 본 적이 있나요?",
      "너는 어떤 재미있는 약이나 발명품을 만들어 보고 싶나요?"] };
ACT["S3933"] = { s: "Jack and Annie use the magic treehouse to travel back in time to 1947 Brooklyn, New York, where they pretend to be batboys at Jackie Robinson's first game with the Brooklyn Dodgers, against the Boston Braves.",
  q: ["What job do Jack and Annie pretend to have at the baseball game?",
      "Have you ever pretended to have a job you thought was exciting?",
      "What would you like to see at Jackie Robinson's first game?"],
  h: ["잭과 애니는 야구 경기에서 어떤 일을 맡은 척했나요?",
      "너는 멋져 보이는 일을 하는 척해 본 적이 있나요?",
      "재키 로빈슨의 첫 경기에서 너는 무엇을 보고 싶나요?"] };
ACT["S3934"] = { s: "Jack and Annie travel in the magic treehouse to Galveston, Texas, on September 8, 1900, the day of the worst natural disaster in U.S. history.",
  q: ["Where and when do Jack and Annie travel to in this book?",
      "Have you ever experienced strong wind or a storm?",
      "What do you think Jack and Annie will see on that day?"],
  h: ["이 책에서 잭과 애니는 언제, 어디로 여행을 떠나나요?",
      "너는 강한 바람이나 폭풍을 겪어 본 적이 있나요?",
      "그날 잭과 애니는 무엇을 보게 될 것 같나요?"] };
ACT["S3935"] = { s: "The magic treehouse whisks Jack and Annie back in time to meet famed Roman emperor Marcus Aurelius.",
  q: ["Which famous Roman emperor do Jack and Annie meet?",
      "Have you ever read or heard about someone famous from long ago?",
      "What would you like to ask Marcus Aurelius if you met him?"],
  h: ["잭과 애니는 어떤 유명한 로마 황제를 만나나요?",
      "너는 아주 오래전에 살았던 유명한 사람에 대해 읽거나 들어 본 적이 있나요?",
      "마르쿠스 아우렐리우스를 만난다면 너는 무엇을 물어보고 싶나요?"] };
ACT["S3936"] = { s: "Jack and Annie are whisked back in time by the magic treehouse to meet Benjamin Franklin in Old Philadelphia.",
  q: ["Who do Jack and Annie meet in Old Philadelphia?",
      "Have you ever wanted to meet someone from history?",
      "What would you like to ask Benjamin Franklin?"],
  h: ["잭과 애니는 옛 필라델피아에서 누구를 만나나요?",
      "너는 역사 속 인물을 만나 보고 싶었던 적이 있나요?",
      "벤저민 프랭클린을 만난다면 너는 무엇을 물어보고 싶나요?"] };
ACT["S3937"] = { s: "The magic tree house whisks Jack and Annie to Greenland, where their mission is to save a narwhal.",
  q: ["What is Jack and Annie's mission in Greenland?",
      "Have you ever tried to help an animal in trouble?",
      "What do you think a narwhal looks like?"],
  h: ["그린란드에서 잭과 애니의 임무는 무엇인가요?",
      "너는 어려움에 처한 동물을 도와준 적이 있나요?",
      "일각고래는 어떤 모습일 것 같나요?"] };
ACT["S3938"] = { s: "The magic tree house whisks Jack and Annie away to South America, where they must climb Machu Picchu to save a baby llama.",
  q: ["What must Jack and Annie climb to save a baby llama?",
      "Have you ever climbed somewhere high?",
      "What would you do to help a baby llama?"],
  h: ["잭과 애니는 아기 라마를 구하기 위해 어디를 올라야 하나요?",
      "너는 높은 곳을 올라 본 적이 있나요?",
      "아기 라마를 돕기 위해 너라면 무엇을 하겠나요?"] };
ACT["S3939"] = { s: "When the magic tree house whisks Jack and Annie back in time, they land in the tallest tree in Yosemite, California where they join nature conservationist, John Muir, and US President Teddy Roosevelt on a historic trip through the woods.",
  q: ["Which two famous people do Jack and Annie join in Yosemite?",
      "Have you ever taken a trip through the woods?",
      "What would you like to see on a trip through Yosemite?"],
  h: ["잭과 애니는 요세미티에서 어떤 두 유명한 사람과 함께하나요?",
      "너는 숲속으로 여행을 떠나 본 적이 있나요?",
      "요세미티 여행에서 너는 무엇을 보고 싶나요?"] };
ACT["S3940"] = { s: "Morgan le Fay tells Jack and Annie to seek out \"The Gray Ghost\" and listen to her story. They are whisked away to Nepal where they meet Tenzin, a climber, who takes them up the mountain to meet a snow leopard.",
  q: ["Who takes Jack and Annie up the mountain to meet the snow leopard?",
      "Have you ever climbed a mountain or a high hill?",
      "What would you like to say to the snow leopard if you met her?"],
  h: ["산 위로 잭과 애니를 데려가 눈표범을 만나게 해 준 사람은 누구인가요?",
      "너는 산이나 높은 언덕을 올라 본 적이 있나요?",
      "눈표범을 만난다면 너는 무슨 말을 해 주고 싶나요?"] };
ACT["S3941"] = { s: "The magic tree house transports Jack and Annie to South Africa where they must protect a majestic rhino from poachers.",
  q: ["What must Jack and Annie protect the rhino from?",
      "Have you ever wanted to protect an animal?",
      "What would you do to keep a rhino safe from poachers?"],
  h: ["잭과 애니는 코뿔소를 무엇으로부터 지켜야 하나요?",
      "너는 동물을 지켜 주고 싶었던 적이 있나요?",
      "코뿔소를 밀렵꾼으로부터 지키기 위해 너라면 무엇을 하겠나요?"] };
ACT["S3942"] = { s: "When the magic tree house returns, it whisks Jack and Annie away to the Galapagos Islands. They become World Turtle Experts and must save a tortoise in danger of an erupting volcano.",
  q: ["What must Jack and Annie save the tortoise from?",
      "Have you ever learned about a place that had a volcano?",
      "What would you do to help a tortoise escape a volcano?"],
  h: ["잭과 애니는 거북을 무엇으로부터 구해야 하나요?",
      "너는 화산이 있는 곳에 대해 배운 적이 있나요?",
      "거북이 화산에서 도망치도록 너라면 어떻게 돕겠나요?"] };
ACT["S3943"] = { s: "Jack and Annie are whisked away to Mongolia to rescue little horses.",
  q: ["Where do Jack and Annie go to rescue the little horses?",
      "Have you ever seen a horse up close?",
      "What would you do to help rescue a little horse?"],
  h: ["잭과 애니는 어린 말들을 구하기 위해 어디로 가나요?",
      "너는 말을 가까이에서 본 적이 있나요?",
      "어린 말을 구하기 위해 너라면 무엇을 하겠나요?"] };
ACT["S3944"] = { s: "Horrid Henry hates babysitters - and he knows exactly how to make sure they never come back. That is, until he meets Rabid Rebecca, the toughest teen in town.",
  q: ["Who is Rabid Rebecca in this book?",
      "Have you ever had a babysitter take care of you?",
      "What do you think Henry will do when he meets Rabid Rebecca?"],
  h: ["이 책에서 래비드 레베카는 누구인가요?",
      "너는 베이비시터가 너를 돌봐 준 적이 있나요?",
      "래비드 레베카를 만나면 헨리는 어떻게 할 것 같나요?"] };
ACT["S3945"] = { s: "Horrid Henry is off to New Nick's house for a sleepover. New beds to bounce on! New biscuit tins to raid. Henry can't wait. Book #8.",
  q: ["What two things does Henry look forward to at New Nick's sleepover?",
      "Have you ever gone to a friend's house for a sleepover?",
      "What would you look forward to most at a sleepover?"],
  h: ["헨리는 뉴 닉의 파자마 파티에서 어떤 두 가지를 기대했나요?",
      "너는 친구 집에서 자고 온 적이 있나요?",
      "파자마 파티에서 너는 무엇을 가장 기대하고 싶나요?"] };
ACT["S3946"] = { s: "Horrid Henry hates weddings. So when he's forced to be a pageboy for Prissy Polly, Henry decides to have some fun.",
  q: ["What role is Henry forced to play at Prissy Polly's wedding?",
      "Have you ever gone to a wedding?",
      "What fun would you have if you had to be a pageboy at a wedding?"],
  h: ["헨리는 프리시 폴리의 결혼식에서 어떤 역할을 맡게 되었나요?",
      "너는 결혼식에 가 본 적이 있나요?",
      "결혼식에서 시동 역할을 맡는다면 너는 어떤 재미있는 일을 하고 싶나요?"] };
ACT["S3947"] = { s: "Horrid Henry can't believe his parents are forcing him to stay overnight at Stuck-Up Steve's house. And to make things worse, Steve's house is haunted. Or is it?",
  q: ["Why does Henry think Steve's house might be scary?",
      "Have you ever stayed overnight at someone else's house?",
      "What do you think is really happening in Steve's house?"],
  h: ["헨리는 스티브의 집이 왜 무서울 것 같다고 생각했나요?",
      "너는 다른 사람 집에서 하룻밤을 자 본 적이 있나요?",
      "스티브의 집에서 실제로 무슨 일이 벌어지고 있을 것 같나요?"] };
ACT["S3948"] = { s: "Horrid Henry would much rather have pizza and chips for his Christmas lunch, and this year, he might just get his way...",
  q: ["What food does Henry want for his Christmas lunch instead?",
      "Have you ever wanted a different food for a special meal?",
      "What would you want to eat for your own Christmas lunch?"],
  h: ["헨리는 크리스마스 점심으로 대신 어떤 음식을 먹고 싶어 했나요?",
      "너는 특별한 식사에서 다른 음식을 먹고 싶었던 적이 있나요?",
      "너라면 크리스마스 점심으로 무엇을 먹고 싶나요?"] };
ACT["S3953"] = { s: "Geronimo admits that he's a scaredy-mouse, which is why he hates Halloween. His sister and nephew persuade him to write a Halloween book in one day. As research, Cousin Trap demonstrates the frightening gags in the trick store he's working for.",
  q: ["What does Geronimo have to write in one day?",
      "Have you ever been afraid of something like Halloween tricks?",
      "What scary gag would you like to see at a trick store?"],
  h: ["제로니모는 하루 만에 무엇을 써야 했나요?",
      "너는 할로윈 장난 같은 것을 무서워한 적이 있나요?",
      "너는 장난감 가게에서 어떤 무서운 장난을 보고 싶나요?"] };
ACT["S3954"] = { s: "It's Christmas Eve and Geronimo is getting ready for his enormous party, when one disaster after another happens to the poor mouse. With his paw in a cast, a broken tail, and a bruised snout, Geronimo is losing his holiday spirit.",
  q: ["What injuries does Geronimo get before his Christmas party?",
      "Have you ever had bad luck before a special event?",
      "What would you do to cheer Geronimo up?"],
  h: ["크리스마스 파티 전에 제로니모는 어떤 부상을 입었나요?",
      "너는 특별한 행사 전에 안 좋은 일이 생긴 적이 있나요?",
      "제로니모의 기운을 북돋아 주려면 너는 무엇을 하겠나요?"] };
ACT["S3955"] = { s: "A subway tunnel may be haunted by ghosts. Ace reporter Geronimo Stilton is on the case! When his sister, Thea, told him a ghost was haunting New Mouse City's subway tunnels, he knew he had to get the scoop!",
  q: ["What is Geronimo trying to find out as a reporter in this book?",
      "Have you ever ridden on a subway train?",
      "What do you think is really haunting the subway tunnel?"],
  h: ["이 책에서 기자 제로니모는 무엇을 알아내려고 하나요?",
      "너는 지하철을 타 본 적이 있나요?",
      "지하철 터널에 정말로 나타난 것은 무엇일 것 같나요?"] };
ACT["S3956"] = { s: "Professor von Volt has discovered the location of the famous Ruby of Fire. Thea drags Geronimo into a race to be the first to find the legendary gem.",
  q: ["What legendary gem are Thea and Geronimo racing to find?",
      "Have you ever raced to find something first?",
      "What would you do if you found the Ruby of Fire first?"],
  h: ["테아와 제로니모는 어떤 전설의 보석을 먼저 찾으려고 경주하나요?",
      "너는 무언가를 먼저 찾으려고 경주해 본 적이 있나요?",
      "불의 루비를 먼저 찾는다면 너는 어떻게 하겠나요?"] };
ACT["S3957"] = { s: "Geronimo investigates to see if the famous painting MONA MOUSA holds a secret code.",
  q: ["What does Geronimo investigate about the painting MONA MOUSA?",
      "Have you ever tried to solve a puzzle or a secret code?",
      "What do you think the secret code in the painting means?"],
  h: ["제로니모는 모나 마우사 그림에 대해 무엇을 조사하나요?",
      "너는 퍼즐이나 비밀 암호를 풀어 본 적이 있나요?",
      "그림 속 비밀 암호는 무슨 뜻일 것 같나요?"] };
ACT["S3958"] = { s: "Geronimo travels to Ratzikistan to help his grandfather write a travel guide about this remote area.",
  q: ["What is Geronimo helping his grandfather write?",
      "Have you ever helped a family member with a project?",
      "What would you like to see in Ratzikistan?"],
  h: ["제로니모는 할아버지가 무엇을 쓰는 것을 돕고 있나요?",
      "너는 가족을 도와 어떤 일을 해 본 적이 있나요?",
      "라치키스탄에서 너는 무엇을 보고 싶나요?"] };
ACT["S3959"] = { s: "A mysterious one-eyed rat is trying to steal THE RODENT'S GAZETTE from Stilton and the only way to save it is to be a winner on the TV game show THE MOUSETRAP.",
  q: ["What must Geronimo do to save his newspaper?",
      "Have you ever watched or played a game show?",
      "What would you do to win a game show like THE MOUSETRAP?"],
  h: ["제로니모는 신문을 지키기 위해 무엇을 해야 하나요?",
      "너는 게임 쇼를 보거나 해 본 적이 있나요?",
      "마우스트랩 같은 게임 쇼에서 이기려면 너는 무엇을 하겠나요?"] };
ACT["S3960"] = { s: "Geronimo Stilton embarks on an adventure to investigate rumors of a haunted pirate treasure buried on a desert island.",
  q: ["What rumor does Geronimo investigate in this book?",
      "Have you ever heard a rumor about hidden treasure?",
      "What would you do if you found pirate treasure on a desert island?"],
  h: ["이 책에서 제로니모는 어떤 소문을 조사하나요?",
      "너는 숨겨진 보물에 대한 소문을 들어 본 적이 있나요?",
      "무인도에서 해적 보물을 찾는다면 너는 어떻게 하겠나요?"] };
ACT["S3961"] = { s: "Newspaper editor Geronimo Stilton unknowingly hires a fourteen-year-old mouse named Pinky Pick as his assistant editor, but when he sees her for the first time, he can't believe his eyes.",
  q: ["Who does Geronimo hire without knowing her age?",
      "Have you ever been surprised by someone you just met?",
      "What do you think surprised Geronimo about Pinky Pick?"],
  h: ["제로니모는 나이를 모른 채 누구를 고용했나요?",
      "너는 처음 만난 사람에게 놀랐던 적이 있나요?",
      "핑키 픽에 대해 무엇이 제로니모를 놀라게 했을 것 같나요?"] };
ACT["S3962"] = { s: "Somehow, Geronimo's vacations never seem to go according to plan. Instead of a beautiful seaside resort, he finds himself in a fleabag hotel that is falling down around his ears.",
  q: ["What kind of hotel does Geronimo end up in instead of a nice resort?",
      "Have you ever had a vacation that didn't go as planned?",
      "What would you do if your hotel started falling apart?"],
  h: ["제로니모는 좋은 리조트 대신 어떤 허름한 호텔에 묵게 되었나요?",
      "너는 계획대로 되지 않은 휴가를 보낸 적이 있나요?",
      "묵고 있는 호텔이 무너지기 시작한다면 너는 어떻게 하겠나요?"] };
ACT["S3963"] = { s: "Geronimo Stilton is on a wagon train headed west when he finds himself face-to-face in a showdown with the wickedest rat in all of Cactus City.",
  q: ["Who does Geronimo face in a showdown in Cactus City?",
      "Have you ever had to face someone you were nervous about?",
      "What would you say to the wickedest rat in Cactus City?"],
  h: ["제로니모는 캑터스 시티에서 누구와 결투를 벌이게 되나요?",
      "너는 긴장되는 상대를 마주해야 했던 적이 있나요?",
      "캑터스 시티의 가장 못된 쥐에게 너는 무슨 말을 하고 싶나요?"] };
ACT["S3964"] = { s: "Geronimo Stilton has no ideas for his new book until Creepella von Cracklefur mouse-naps him for a weekend at her family's spooky castle.",
  q: ["Who takes Geronimo to a spooky castle for the weekend?",
      "Have you ever visited an old or spooky place?",
      "What do you think Geronimo finds inside the spooky castle?"],
  h: ["누가 제로니모를 주말 동안 으스스한 성으로 데려가나요?",
      "너는 오래되거나 으스스한 곳을 가 본 적이 있나요?",
      "으스스한 성 안에서 제로니모는 무엇을 발견할 것 같나요?"] };
ACT["S3965"] = { s: "It was Valentine's Day in New Mouse City, and Geronimo had sent valentine cards to all his friends and family members. But when he opened his mailbox on the morning of Feb. 14th, it was empty! Had everyone forgotten about Geronimo?",
  q: ["What did Geronimo find when he opened his mailbox on Valentine's Day?",
      "Have you ever sent or received a Valentine's card?",
      "What do you think really happened to Geronimo's valentine cards?"],
  h: ["밸런타인데이 아침에 제로니모가 우편함을 열었을 때 무엇을 발견했나요?",
      "너는 밸런타인 카드를 보내거나 받아 본 적이 있나요?",
      "제로니모에게 온 밸런타인 카드들에는 실제로 무슨 일이 있었을 것 같나요?"] };
ACT["S3966"] = { s: "Geronimo Stilton recounts his trip to Niagara Falls when he accompanies some young mice there as part of a school field trip.",
  q: ["Why does Geronimo travel to Niagara Falls?",
      "Have you ever gone on a school field trip?",
      "What would you like to see if you visited Niagara Falls?"],
  h: ["제로니모는 왜 나이아가라 폭포로 여행을 가나요?",
      "너는 학교 현장 학습을 가 본 적이 있나요?",
      "나이아가라 폭포에 간다면 너는 무엇을 보고 싶나요?"] };
ACT["S3967"] = { s: "Geronimo is on the trail of treasure, but the rolling and rollicking of the sea is more than he bargained for. And that's not all, someone else seems to be after the same end goal.",
  q: ["What problem does Geronimo have with the sea while searching for treasure?",
      "Have you ever felt seasick or dizzy from moving around?",
      "Who do you think is also after the same treasure?"],
  h: ["보물을 찾는 동안 제로니모는 바다 때문에 어떤 어려움을 겪나요?",
      "너는 움직임 때문에 멀미가 나거나 어지러웠던 적이 있나요?",
      "같은 보물을 노리는 다른 사람은 누구일 것 같나요?"] };
ACT["S3968"] = { s: "Geronimo receives an urgent message from his friend Professor Sandsnout just before Halloween. He needs Geronimo's help, so Geronimo rushes to his aid at the Egyptian Mouseum, only to find real, live mummies.",
  q: ["What does Geronimo find at the Egyptian Mouseum?",
      "Have you ever rushed to help a friend?",
      "What would you do if you met a real, live mummy?"],
  h: ["제로니모는 이집트 박물관에서 무엇을 발견하나요?",
      "너는 친구를 돕기 위해 서둘러 달려간 적이 있나요?",
      "진짜 살아 있는 미라를 만난다면 너는 어떻게 하겠나요?"] };
ACT["S3969"] = { s: "Geronimo loves Christmas in New Mouse City, but this year there's just too much to do at his newspaper. His family and friends are upset because he doesn't have time to celebrate. If only he had his own reindeer to fly to Santa's Toy Factory.",
  q: ["Why are Geronimo's family and friends upset with him this Christmas?",
      "Have you ever been too busy to spend time with your family?",
      "What would you do if you had your own reindeer for Christmas?"],
  h: ["이번 크리스마스에 제로니모의 가족과 친구들은 왜 그에게 서운해했나요?",
      "너는 너무 바빠서 가족과 시간을 보내지 못한 적이 있나요?",
      "크리스마스에 너만의 순록이 있다면 너는 무엇을 하겠나요?"] };
ACT["S3970"] = { s: "Geronimo hates traveling, so when he gets invited to visit a long-lost relative who lives far away, he isn't filled with joy. But Thea, Trap, and Benjamin think it sounds fabumouse and they drag him to the crazy castle on Penny-Pincher Peak.",
  q: ["Why isn't Geronimo happy about the invitation from his relative?",
      "Have you ever had to visit a relative you didn't know well?",
      "What do you think Geronimo finds at the castle on Penny-Pincher Peak?"],
  h: ["친척의 초대를 받고도 제로니모는 왜 기뻐하지 않았나요?",
      "너는 잘 모르는 친척을 방문해야 했던 적이 있나요?",
      "페니핀처 봉우리의 성에서 제로니모는 무엇을 발견할 것 같나요?"] };
ACT["S3971"] = { s: "Rodent journalist Geronimo Stilton visits Australia where he has an adventurous time dodging sharks and snakes and getting lost in the outback.",
  q: ["What dangers does Geronimo face in Australia?",
      "Have you ever gotten lost somewhere?",
      "What would you do if you got lost in the outback?"],
  h: ["제로니모는 호주에서 어떤 위험을 겪나요?",
      "너는 어딘가에서 길을 잃은 적이 있나요?",
      "오지에서 길을 잃는다면 너는 어떻게 하겠나요?"] };
ACT["S3972"] = { s: "Geronimo accidentally gets signed up for the Mouse Island Marathon, and his friends and family are determined to help him cross the finish line.",
  q: ["How does Geronimo end up in the Mouse Island Marathon?",
      "Have you ever run in a race or competed in a sport?",
      "What would you say to encourage Geronimo to finish the marathon?"],
  h: ["제로니모는 어떻게 마우스 아일랜드 마라톤에 참가하게 되었나요?",
      "너는 달리기 경주나 운동 경기에 나가 본 적이 있나요?",
      "마라톤을 완주하도록 제로니모를 응원하려면 너는 무슨 말을 하겠나요?"] };
