// 간이 학습 질문 — Book No. S40 묶음. 사람이 아니라 AI 가 한 번 쓰고 굳힌 파일이다.
window.ACT = window.ACT || {};
var ACT = window.ACT;
ACT["S4001"] = { s: "A timid boy is eager to frighten the school bully on Halloween. He happens to acquire a magic ring and the power to change himself into a monster.",
  q: ["What does the timid boy want to do to the school bully on Halloween?",
      "Have you ever wanted to scare or surprise someone?",
      "If you had a magic ring that could turn you into a monster, what would you do?"],
  h: ["겁 많은 소년은 할로윈에 학교 불량배에게 무엇을 하고 싶어 하나요?",
      "누군가를 놀래키거나 깜짝 놀라게 하고 싶었던 적이 있나요?",
      "나를 괴물로 바꿔 주는 마법 반지가 있다면 무엇을 하고 싶나요?"] };
ACT["S4002"] = { s: "This book introduces five poems to readers. They celebrate the making of a special pie, an upside-down boy, a sneezing elephant, an encounter with a monster, and an alien who lands in a bowl of soup.",
  q: ["Which of the five poems in this book sounds the most interesting to you? Explain why.",
      "Have you ever read or heard a funny poem before? Write about it.",
      "If you could write your own funny poem, what silly topic would you choose? Write your idea in a paragraph."],
  h: ["이 책에 나온 다섯 편의 시 중에 어떤 시가 가장 재미있어 보이나요? 이유도 함께 써 보세요.",
      "재미있는 시를 읽거나 들어 본 적이 있나요? 그 이야기를 적어 보세요.",
      "내가 웃긴 시를 쓴다면 어떤 엉뚱한 주제로 쓰고 싶나요? 내 생각을 한 문단으로 적어 보세요."] };
ACT["S4003"] = { s: "Did you know that the horned lizard squirts blood out of its eyes to scare off predators? Learn more about this creature as well as the leech, the naked mole rat, the hagfish, and many more creepy critters and their interesting and strange behaviors.",
  q: ["Which disgusting animal behavior from this book surprised you the most? Explain why animals might do things like that.",
      "Have you ever learned a strange fact about an animal that surprised you? Write about it.",
      "If you could ask the author about one more disgusting animal fact, what would you want to know? Explain your idea in a paragraph."],
  h: ["이 책에 나온 역겨운 동물 행동 중에 가장 놀라웠던 것은 무엇인가요? 동물이 왜 그런 행동을 할지 생각해서 써 보세요.",
      "동물에 대해 놀라운 사실을 알게 된 적이 있나요? 그 이야기를 적어 보세요.",
      "작가에게 역겨운 동물 사실을 하나 더 묻는다면 무엇이 궁금한가요? 내 생각을 한 문단으로 적어 보세요."] };
ACT["S4004"] = { s: "During the Civil war, the Confederate submarine called the H.L. Hunley mysteriously vanished. After over a century it recovered from deep in the waters off the coast of South Carolina. This book recounts the mysterious events.",
  q: ["What happened to the submarine H.L. Hunley during the Civil War, and what happened to it many years later?",
      "Have you ever heard of something lost being found again after a long time? Write about it.",
      "Why do you think people wanted to find the missing submarine so badly? Write your own idea in a paragraph."],
  h: ["남북전쟁 때 잠수함 헌리호는 어떻게 되었고, 그로부터 오랜 시간이 지난 뒤에는 어떻게 되었나요?",
      "오랜 시간이 지나서야 잃어버렸던 것을 다시 찾은 이야기를 들어 본 적이 있나요? 적어 보세요.",
      "사람들이 사라진 잠수함을 그토록 찾고 싶어 한 이유가 무엇일지 내 생각을 한 문단으로 적어 보세요."] };
ACT["S4005"] = { s: "Amber Brown faces complications because she has to decide where to spend Thanksgiving--with her dad in New York City, or with her mom and Max in Walla Walla, Washington. She feels like she's in the middle of a bad dream.",
  q: ["Why does Amber Brown feel like she is in the middle of a bad dream in this book?",
      "Have you ever had to choose between two people or two places you both love? Write about how it felt.",
      "If you were Amber, how would you decide where to spend Thanksgiving? Explain your reasons in a paragraph."],
  h: ["엠버 브라운은 이 책에서 왜 나쁜 꿈 한가운데 있는 것처럼 느끼나요?",
      "둘 다 좋아하는 사람이나 장소 중에서 하나를 골라야 했던 적이 있나요? 그때 기분이 어땠는지 적어 보세요.",
      "내가 엠버라면 추수감사절을 어디서 보낼지 어떻게 정할까요? 이유와 함께 한 문단으로 적어 보세요."] };
ACT["S4006"] = { s: "It is the end of third grade. Amber is excited about her trip to London and Paris, where she will meet her father again. But she comes down with chickenpox and her plans change.",
  q: ["What sickness does Amber get before her trip?",
      "Have you ever gotten sick before something exciting?",
      "What would you do if your trip plans suddenly changed?"],
  h: ["여행을 떠나기 전에 엠버는 어떤 병에 걸리나요?",
      "신나는 일을 앞두고 아팠던 적이 있나요?",
      "여행 계획이 갑자기 바뀐다면 나는 어떻게 할까요?"] };
ACT["S4007"] = { s: "Amber's mom is thinking of getting married. Amber is learning that even when things change, the most important thing stays the same. No matter what her mom decides, Amber knows she will be forever Amber Brown.",
  q: ["What is Amber's mom thinking about doing in this book?",
      "Has something in your family ever changed?",
      "What is one thing about yourself that will always stay the same?"],
  h: ["이 책에서 엠버의 엄마는 무엇을 하려고 생각하고 있나요?",
      "우리 가족에게 무언가 변한 일이 있었나요?",
      "무슨 일이 있어도 변하지 않을, 나만의 모습 한 가지는 무엇인가요?"] };
ACT["S4008"] = { s: "Amber's divorced parents share joint custody of her, and she feels as if half of her belongs to her mom and the other half belongs to her dad. She suffers from a lack of self-esteem.",
  q: ["How does Amber feel about being shared between her two parents?",
      "Do you ever feel like you belong to two different places?",
      "What would you say to Amber to help her feel better about herself?"],
  h: ["엠버는 두 부모님 사이에서 나뉘어 지내는 것에 대해 어떤 기분을 느끼나요?",
      "나는 두 곳에 반씩 속해 있는 것 같다고 느낀 적이 있나요?",
      "엠버가 자신에 대해 더 좋게 느끼도록 내가 해 줄 수 있는 말은 무엇일까요?"] };
ACT["S4009"] = { s: "Amber learns her best friend, Justin Daniels, is moving to Alabama. They've always stuck up for one another. But everything begins to change.",
  q: ["Where is Amber's best friend Justin moving to?",
      "Have you ever had a friend move away?",
      "What would you want to say to a friend before they move away?"],
  h: ["엠버의 가장 친한 친구 저스틴은 어디로 이사를 가나요?",
      "친구가 멀리 이사를 간 적이 있나요?",
      "친구가 멀리 이사 가기 전에 나는 어떤 말을 해 주고 싶나요?"] };
ACT["S4010"] = { s: "Amber feels she is caught in the middle. Her divorced parents fight over to take joint custody of her.",
  q: ["Why does Amber feel caught in the middle in this book?",
      "Have you ever felt stuck between two people who disagreed?",
      "What advice would you give Amber's parents?"],
  h: ["이 책에서 엠버는 왜 가운데 끼어 있다고 느끼나요?",
      "서로 다른 의견을 가진 두 사람 사이에 끼어 있다고 느낀 적이 있나요?",
      "엠버의 부모님에게 내가 해 주고 싶은 조언은 무엇인가요?"] };
ACT["S4011"] = { s: "Araminta and Wanda want to find Sir Horace the perfect gift for his five-hundredth birthday. They attempt to get an ancient sword in a grotto hidden under her haunted house. With the help of the ghost Edmund, they set off on a trip through a secret tunnel.",
  q: ["What do Araminta and Wanda go looking for, and who helps them on their trip?",
      "Have you ever tried to find or make a special gift for someone? Write about it.",
      "Would you be brave enough to go through a secret tunnel with a ghost's help? Explain why or why not."],
  h: ["아라민타와 완다는 무엇을 찾으러 떠나고, 누가 그 길을 도와주나요?",
      "누군가를 위해 특별한 선물을 찾거나 만들어 본 적이 있나요? 적어 보세요.",
      "유령의 도움을 받아 비밀 통로를 지나갈 용기가 나에게 있을까요? 이유를 들어 설명해 보세요."] };
ACT["S4012"] = { s: "Doctor Dog is a favorite pet of the Gumboyle family. He is also their trusty personal physician. Will the family survive when Doctor Dog jets off to a medical conference in Brazil?",
  q: ["What two jobs does Doctor Dog have for the Gumboyle family?",
      "Have you ever depended on someone who then had to go away for a while? Write about how you felt.",
      "What do you think might happen to the Gumboyle family while Doctor Dog is away? Write your own idea in a paragraph."],
  h: ["닥터 도그는 검보일 가족에게 어떤 두 가지 역할을 하나요?",
      "의지하던 사람이 한동안 자리를 비운 적이 있나요? 그때 기분을 적어 보세요.",
      "닥터 도그가 없는 동안 검보일 가족에게 무슨 일이 일어날까요? 내 생각을 한 문단으로 적어 보세요."] };
ACT["S4013"] = { s: "Abigail and her friends jump back to the past to meet Martin Luther King Jr. They need to convince him not to get discouraged and lead one of his famous voting rights marches.",
  q: ["Who do Abigail and her friends travel back in time to meet, and what do they try to convince him to do?",
      "Have you ever needed encouragement to keep going with something hard? Write about it.",
      "Why do you think it was important for Martin Luther King Jr. not to give up? Write your thoughts in a paragraph."],
  h: ["애비게일과 친구들은 과거로 가서 누구를 만나고, 그에게 무엇을 하라고 설득하려 하나요?",
      "힘든 일을 계속하기 위해 누군가의 격려가 필요했던 적이 있나요? 적어 보세요.",
      "마틴 루터 킹이 포기하지 않는 것이 왜 중요했을지 내 생각을 한 문단으로 적어 보세요."] };
ACT["S4014"] = { s: "Chester, the Monroe family's cat, tries to alert his owners and Harold, their dog, that the newly adopted bunny may be a vampire.",
  q: ["What does Chester the cat try to warn the family about?",
      "Have you ever tried to warn someone about something but they didn't believe you? Write about it.",
      "Do you think the bunny really is a vampire? Explain your guess in a paragraph."],
  h: ["고양이 체스터는 가족에게 무엇을 경고하려 하나요?",
      "누군가에게 무언가를 경고했지만 믿어 주지 않았던 적이 있나요? 적어 보세요.",
      "그 토끼가 진짜 뱀파이어라고 생각하나요? 내 생각을 한 문단으로 적어 보세요."] };
ACT["S4015"] = { s: "The wire-haired dachshund named Howie writes a story in which he saves the world from a science experiment that goes awry.",
  q: ["What kind of story does Howie the dog write in this book?",
      "Have you ever written or imagined a story where you were the hero? Write about it.",
      "If you had to save the world from an experiment gone wrong, what would you do? Write your plan in a paragraph."],
  h: ["강아지 하위는 이 책에서 어떤 이야기를 쓰나요?",
      "내가 주인공이 되는 이야기를 써 보거나 상상해 본 적이 있나요? 적어 보세요.",
      "잘못된 실험에서 세상을 구해야 한다면 나는 어떻게 할까요? 내 계획을 한 문단으로 적어 보세요."] };
ACT["S4016"] = { s: "This book is an abridged sequel to Anne Of Green Gables. The story shares sixteen-year-old Anne's life in a small village on Prince Edward Island as a schoolteacher.",
  q: ["What job does sixteen-year-old Anne have in this book?",
      "Have you ever thought about what job you want when you grow up?",
      "What job would you like to try someday? Write it down."],
  h: ["열여섯 살 앤은 이 책에서 어떤 일을 하나요?",
      "내가 어른이 되면 어떤 일을 하고 싶은지 생각해 본 적이 있나요?",
      "언젠가 해 보고 싶은 일을 적어 보세요."] };
ACT["S4017"] = { s: "Eight-year-old Clementine is convinced that she has no talents at all. She devises a plan to avoid participating in the class talent show.",
  q: ["Why does Clementine want to avoid the class talent show?",
      "Have you ever felt like you weren't good at anything special? Write about that feeling.",
      "What is one talent you have, even a small one? Write about it in a paragraph."],
  h: ["클레멘타인은 왜 학예회에 나가지 않으려 하나요?",
      "특별히 잘하는 것이 없다고 느낀 적이 있나요? 그때 기분을 적어 보세요.",
      "작더라도 내가 가진 재능 한 가지는 무엇인가요? 한 문단으로 적어 보세요."] };
ACT["S4018"] = { s: "The ten-year-old boy detective of Idaville solves ten baffling new crimes, including The Case of the Missing Penknife Named Excalibur.",
  q: ["What is the name of the missing item in one of Encyclopedia Brown's cases?",
      "Have you ever lost something important and had to figure out where it went? Write about it.",
      "What makes a good detective, in your opinion? Write your thoughts in a paragraph."],
  h: ["엔사이클로피디아 브라운이 맡은 사건 중 하나에서 사라진 물건의 이름은 무엇인가요?",
      "중요한 물건을 잃어버리고 어디 있는지 찾아야 했던 적이 있나요? 적어 보세요.",
      "좋은 탐정이 되려면 무엇이 필요하다고 생각하나요? 내 생각을 한 문단으로 적어 보세요."] };
ACT["S4019"] = { s: "Encyclopedia Brown, Sherlock Holmes of Idaville, solves ten new crimes, including The Case of the Stolen Diamond Necklace.",
  q: ["What was stolen in one of the cases Encyclopedia Brown solves?",
      "Have you ever helped find something that was lost or missing? Write about it.",
      "If you were a detective, what kind of mystery would you like to solve? Explain your idea in a paragraph."],
  h: ["엔사이클로피디아 브라운이 해결한 사건 중 하나에서 도둑맞은 것은 무엇인가요?",
      "잃어버린 것을 찾도록 도와준 적이 있나요? 적어 보세요.",
      "내가 탐정이라면 어떤 미스터리를 풀어 보고 싶나요? 내 생각을 한 문단으로 적어 보세요."] };
ACT["S4020"] = { s: "The ten-year-old boy detective of Idaville solves ten more mysteries, including The Case of the Ghost Who Whistles.",
  q: ["What strange thing does the \"ghost\" in one case do?",
      "Have you ever heard a strange sound you couldn't explain? Write about it.",
      "Do you think the whistling ghost is really a ghost? Explain your guess in a paragraph."],
  h: ["한 사건 속 '유령'은 어떤 이상한 행동을 하나요?",
      "설명할 수 없는 이상한 소리를 들어 본 적이 있나요? 적어 보세요.",
      "휘파람을 부는 유령이 진짜 유령이라고 생각하나요? 내 생각을 한 문단으로 적어 보세요."] };
ACT["S4021"] = { s: "Leroy Brown, aka Encyclopedia Brown, uses his computer-like brain to help solve ten puzzling crimes. In this book, he solves ten new baffling mysteries, including The Case of the Missing Clues.",
  q: ["What nickname does Leroy Brown have because of his smart brain?",
      "Have you ever used clues to figure something out? Write about it.",
      "What clue-finding skill do you think is most useful for a detective? Explain in a paragraph."],
  h: ["리로이 브라운은 똑똑한 두뇌 덕분에 어떤 별명을 얻었나요?",
      "단서를 이용해서 무언가를 알아낸 적이 있나요? 적어 보세요.",
      "탐정에게 가장 쓸모 있는 단서 찾기 능력은 무엇이라고 생각하나요? 한 문단으로 설명해 보세요."] };
ACT["S4022"] = { s: "The ten-year-old boy detective of Idaville solves ten more mysteries, including The Case of the Silver Fruit Bowl.",
  q: ["What object goes missing in one of Encyclopedia Brown's cases?",
      "Have you ever helped keep peace between two people who were arguing? Write about it.",
      "How do you think Encyclopedia Brown \"keeps the peace\" while solving crimes? Write your idea in a paragraph."],
  h: ["엔사이클로피디아 브라운의 사건 중 하나에서 사라진 물건은 무엇인가요?",
      "다투는 두 사람 사이에서 평화를 지키도록 도운 적이 있나요? 적어 보세요.",
      "엔사이클로피디아 브라운은 사건을 풀며 어떻게 '평화를 지킬지' 내 생각을 한 문단으로 적어 보세요."] };
ACT["S4023"] = { s: "Encyclopedia Brown, Sherlock Holmes of Idaville, solves ten new cases, including The Case of the Electric Clock.",
  q: ["What object is part of one of the mysteries in this book?",
      "Have you ever solved a small mystery at home or school?",
      "What mystery would you like to solve?"],
  h: ["이 책의 사건 중 하나에 등장하는 물건은 무엇인가요?",
      "집이나 학교에서 작은 미스터리를 풀어 본 적이 있나요?",
      "내가 풀어 보고 싶은 미스터리는 무엇인가요?"] };
ACT["S4024"] = { s: "Leroy Brown, aka Encyclopedia Brown, uses his computer-like brain to help solve ten more puzzling crimes, including The Case of the Champion Skier.",
  q: ["Who is at the center of the case involving a champion skier?",
      "Have you ever watched or tried a sport like skiing? Write about it.",
      "What do you think happened in the Case of the Champion Skier? Write your own guess in a paragraph."],
  h: ["챔피언 스키 선수 사건의 중심에는 누가 있을까요?",
      "스키 같은 스포츠를 보거나 해 본 적이 있나요? 적어 보세요.",
      "챔피언 스키 선수 사건에서 무슨 일이 일어났을지 내 생각을 한 문단으로 적어 보세요."] };
ACT["S4025"] = { s: "Encyclopedia Brown, brilliant fifth-grade amateur detective, solves ten more mysteries, including The Case of the Growling Dog.",
  q: ["What animal makes a strange sound in one of the cases?",
      "Have you ever heard a dog growl? What happened?",
      "What do you think caused the dog to growl?"],
  h: ["사건 중 하나에서 이상한 소리를 내는 동물은 무엇인가요?",
      "개가 으르렁거리는 소리를 들어 본 적이 있나요? 그때 무슨 일이 있었나요?",
      "그 개가 왜 으르렁거렸을 것 같나요?"] };
ACT["S4026"] = { s: "Encyclopedia Brown, the ten-year-old mastermind of Idaville's war on crime, solves ten more baffling cases including, The Case of a Missing Silver Dollar.",
  q: ["What is missing in one of the cases Encyclopedia Brown solves in this book?",
      "Have you ever misplaced money or a coin that was special to you? Write about it.",
      "How would you go about looking for something small that went missing? Explain your steps in a paragraph."],
  h: ["이 책에서 엔사이클로피디아 브라운이 푸는 사건 중 하나에서 사라진 것은 무엇인가요?",
      "소중한 돈이나 동전을 잃어버린 적이 있나요? 적어 보세요.",
      "작은 물건이 사라졌을 때 나는 어떻게 찾아볼까요? 그 방법을 한 문단으로 적어 보세요."] };
ACT["S4027"] = { s: "Encyclopedia Brown, Idaville's favorite sleuth, traces the clues in ten mysteries, including The Case of the Dead Eagles.",
  q: ["What animals does Encyclopedia Brown investigate in one of his cases?",
      "Have you ever noticed something wrong with an animal or nature around you? Write about it.",
      "Why do you think someone might want to harm eagles? Write your own idea in a paragraph."],
  h: ["엔사이클로피디아 브라운이 조사하는 사건 중 하나에 등장하는 동물은 무엇인가요?",
      "주변 동물이나 자연에서 무언가 잘못된 것을 알아챈 적이 있나요? 적어 보세요.",
      "누군가 독수리를 해치려 한 이유는 무엇일까요? 내 생각을 한 문단으로 적어 보세요."] };
ACT["S4028"] = { s: "In this book, Encyclopedia Brown, the boy detective, solves ten new crimes, including The Case of the Midnight Visitor.",
  q: ["When does the mysterious visitor in one case appear?",
      "Have you ever heard a strange noise at night? Write about what happened.",
      "Who do you imagine the midnight visitor might be? Explain your guess in a paragraph."],
  h: ["한 사건 속 수상한 방문자는 언제 나타나나요?",
      "밤에 이상한 소리를 들어 본 적이 있나요? 그때 있었던 일을 적어 보세요.",
      "한밤중의 방문자가 누구일 것 같나요? 내 생각을 한 문단으로 적어 보세요."] };
ACT["S4029"] = { s: "When Jon takes Garfield's TV away and takes Garfield and Odie to the vet, they decide to leave their unhappy home and try their luck somewhere else.",
  q: ["Why do Garfield and Odie decide to leave home in this book?",
      "Have you ever been upset about losing a privilege, like TV time? Write about it.",
      "What do you think Garfield and Odie will find when they try their luck somewhere else? Write your prediction."],
  h: ["가필드와 오디는 이 책에서 왜 집을 떠나기로 하나요?",
      "텔레비전 보는 시간처럼 무언가를 빼앗겨 속상했던 적이 있나요? 적어 보세요.",
      "가필드와 오디가 다른 곳에서 운을 시험하면 무엇을 발견하게 될까요? 내 예상을 적어 보세요."] };
ACT["S4030"] = { s: "Two frightened mice give Garfield terrifying news that a beast is living in the house. Garfield warily sets out to investigate.",
  q: ["What do the two frightened mice tell Garfield about?",
      "Have you ever been scared to check something out, but did it anyway? Write about it.",
      "What do you think the \"beast in the basement\" really is? Explain your guess in a paragraph."],
  h: ["겁에 질린 두 마리 쥐는 가필드에게 무슨 소식을 전하나요?",
      "무서웠지만 그래도 확인하러 가 본 적이 있나요? 적어 보세요.",
      "'지하실의 괴물'이 정말 무엇일 것 같나요? 내 생각을 한 문단으로 적어 보세요."] };
ACT["S4031"] = { s: "When Garfield and Odie are taken away to the North Pole, they notice that Santa is kidnapped. Will they rescue Santa in time before Christmas?",
  q: ["What happens to Santa in this book, and who might rescue him?",
      "Have you ever helped save the day for someone during a holiday? Write about it.",
      "How do you think Garfield and Odie will try to rescue Santa? Write your own plan in a paragraph."],
  h: ["이 책에서 산타에게 무슨 일이 생기고, 누가 그를 구할 수 있을까요?",
      "명절에 누군가를 위해 상황을 구해 준 적이 있나요? 적어 보세요.",
      "가필드와 오디는 산타를 어떻게 구하려 할까요? 내 계획을 한 문단으로 적어 보세요."] };
ACT["S4032"] = { s: "When Geronimo Stilton goes to Egypt to interview a famous archaeologist, he learns the secret of the Seven Wonders of the Ancient Mouse World. Book #2",
  q: ["Where does Geronimo Stilton travel to in this book?",
      "Have you ever learned a secret or surprising fact from an interview or a book?",
      "Which of the Seven Wonders would you like to learn about?"],
  h: ["제로니모 스틸턴은 이 책에서 어디로 여행을 떠나나요?",
      "인터뷰나 책에서 놀라운 비밀을 알게 된 적이 있나요?",
      "일곱 가지 불가사의 중 어떤 것에 대해 알고 싶나요?"] };
ACT["S4033"] = { s: "Geronimo gets lost in a spooky forest and seeks shelter in an old mansion. He ends up realizing the mansion is haunted. Book #3",
  q: ["Where does Geronimo take shelter in this book?",
      "Have you ever gotten lost somewhere?",
      "What would you do if you thought a house you were in was haunted?"],
  h: ["제로니모는 이 책에서 어디로 피신하나요?",
      "어딘가에서 길을 잃은 적이 있나요?",
      "내가 있는 집이 귀신 들린 집이라고 생각되면 나는 어떻게 할까요?"] };
ACT["S4034"] = { s: "In this book, Geronimo goes trekking to Mouse Everest to help his old friend Professor von Volt. Book #4",
  q: ["Where does Geronimo go trekking in this book?",
      "Have you ever helped a friend who needed you?",
      "What is the tallest place you have ever climbed or visited?"],
  h: ["제로니모는 이 책에서 어디로 트레킹을 떠나나요?",
      "나를 필요로 하는 친구를 도와준 적이 있나요?",
      "내가 올라가 보거나 가 본 곳 중 가장 높은 곳은 어디인가요?"] };
ACT["S4035"] = { s: "In this book, someone goes around pretending to be Geronimo Stilton. To make matters worse, the greedy imposter attempts to take over the newspaper. Book #6",
  q: ["What does the imposter in this book pretend to be?",
      "Has anyone ever pretended to be someone else to trick you or a friend?",
      "What would you do if someone pretended to be you?"],
  h: ["이 책에서 가짜는 누구인 척 행동하나요?",
      "누군가 다른 사람인 척하며 나나 친구를 속인 적이 있나요?",
      "누군가 나인 척한다면 나는 어떻게 할까요?"] };
ACT["S4036"] = { s: "Trap, Geronimo's troublemaker cousin, is in trouble indeed, and Thea wants to drag Geronimo to Transratania for a rescue mission. Book #7",
  q: ["Who is in trouble in this book?",
      "Have you ever gone to help a family member who was in trouble?",
      "Would you go on a rescue mission for your cousin? Why or why not?"],
  h: ["이 책에서 곤경에 처한 사람은 누구인가요?",
      "곤경에 처한 가족을 도우러 간 적이 있나요?",
      "사촌을 구하러 떠나는 모험에 나설 것 같나요? 이유를 들어 보세요."] };
ACT["S4037"] = { s: "Everyone in New Mouse City is furious with Geronimo because the phone book he publishes is full of wrong numbers. When Trap invites him to the Claw Islands, he agrees to go on the quest only to get away from the blame. Book #8",
  q: ["Why is everyone in New Mouse City angry with Geronimo?",
      "Have you ever made a mistake that upset other people?",
      "Where would you want to escape to if everyone was upset with you?"],
  h: ["뉴마우스 시티의 모든 사람들은 왜 제로니모에게 화가 나 있나요?",
      "실수를 해서 다른 사람들을 속상하게 만든 적이 있나요?",
      "모두가 나에게 화가 났다면 나는 어디로 도망치고 싶나요?"] };
ACT["S4038"] = { s: "Geronimo happens to spot the most beautiful rodent in the world, and he finds himself trying to win her heart. Book #10",
  q: ["What does Geronimo try to do in this book?",
      "Have you ever tried hard to make a new friend?",
      "What would you do to make a new friend like you?"],
  h: ["제로니모는 이 책에서 무엇을 하려고 하나요?",
      "새로운 친구를 사귀려고 열심히 노력해 본 적이 있나요?",
      "새로운 친구가 나를 좋아하게 하려면 나는 무엇을 할까요?"] };
ACT["S4039"] = { s: "The most unusual second-grader Gooney Bird Greene finds a surprise Room Mother to bring cupcakes to her class for the Thanksgiving pageant. Book #2",
  q: ["What does Gooney Bird find for her class's Thanksgiving pageant?",
      "Have you ever helped plan a class party or event?",
      "What treat would you like to bring to a class party?"],
  h: ["구니 버드는 반 추수감사절 공연을 위해 무엇을 찾아내나요?",
      "학급 파티나 행사를 계획하도록 도와준 적이 있나요?",
      "학급 파티에 내가 가져가고 싶은 간식은 무엇인가요?"] };
ACT["S4040"] = { s: "When students in Mrs. Pidgeon's second-grade class learn about fables, Gooney Bird comes up with an idea. She suggests each child create a fable and tell it to the class. Book #3",
  q: ["What does Gooney Bird suggest each student make in this book?",
      "Have you ever made up your own story to tell others?",
      "What animal would you use as the main character in your own fable?"],
  h: ["구니 버드는 학생들에게 각자 무엇을 만들자고 제안하나요?",
      "다른 사람에게 들려줄 이야기를 스스로 만들어 본 적이 있나요?",
      "내가 우화를 만든다면 어떤 동물을 주인공으로 삼고 싶나요?"] };
ACT["S4041"] = { s: "Students in Mrs. Pidgeon's class study poetry and learn many different ways to write a poem. Irrepressible Gooney Bird uses all the inspiration to organize the most important poem the class has ever written. Book #4",
  q: ["What do the students in this book learn to write?",
      "Have you ever written a poem?",
      "What would you want to write a poem about?"],
  h: ["이 책에서 학생들은 무엇을 쓰는 법을 배우나요?",
      "시를 써 본 적이 있나요?",
      "내가 시를 쓴다면 어떤 주제로 쓰고 싶나요?"] };
ACT["S4042"] = { s: "This book describes the power of blizzards, including descriptions of famous storms and information on how scientists predict and forecast them.",
  q: ["How do scientists predict and forecast blizzards, according to this book?",
      "Have you ever experienced a big storm or snowy weather? Write about it.",
      "Why do you think it is important for scientists to predict blizzards before they happen? Write your idea in a paragraph."],
  h: ["이 책에 따르면 과학자들은 눈보라를 어떻게 예측하고 예보하나요?",
      "큰 폭풍이나 눈 오는 날씨를 겪어 본 적이 있나요? 적어 보세요.",
      "과학자들이 눈보라를 미리 예측하는 것이 왜 중요할지 한 문단으로 적어 보세요."] };
ACT["S4043"] = { s: "This book describes the incredible power of lightning, including its positive and negative effects on living things.",
  q: ["What are some positive and negative effects of lightning on living things, according to this book?",
      "Have you ever seen lightning during a storm? Write about how it looked or felt.",
      "Why do you think lightning can be both helpful and dangerous? Explain your idea in a paragraph."],
  h: ["이 책에 따르면 번개가 생물에게 주는 좋은 영향과 나쁜 영향은 각각 무엇인가요?",
      "폭풍우 속에서 번개를 본 적이 있나요? 그때 모습이나 느낌을 적어 보세요.",
      "번개가 도움이 되기도 하고 위험하기도 한 이유는 무엇일까요? 내 생각을 한 문단으로 적어 보세요."] };
ACT["S4044"] = { s: "This book describes two researchers who follow tornadoes to study them.",
  q: ["What do the two researchers in this book do to study tornadoes?",
      "Have you ever been curious enough about something to study it closely? Write about it.",
      "Why do you think people are willing to follow dangerous tornadoes to study them? Explain your idea in a paragraph."],
  h: ["이 책에 나오는 두 연구자는 토네이도를 연구하기 위해 무엇을 하나요?",
      "무언가가 궁금해서 자세히 살펴본 적이 있나요? 적어 보세요.",
      "사람들이 위험한 토네이도를 쫓으면서까지 연구하는 이유는 무엇일까요? 한 문단으로 적어 보세요."] };
ACT["S4045"] = { s: "This book is a sequel to CLIFFHANGER. The story follows the struggles of two boys who encounter bullies on holiday.",
  q: ["What problem do the two boys face on their holiday in this book?",
      "Have you ever dealt with a bully, or seen someone else deal with one? Write about it.",
      "What advice would you give the boys for dealing with the bullies? Write your ideas in a paragraph."],
  h: ["두 소년은 휴가 중 이 책에서 어떤 문제를 겪나요?",
      "괴롭히는 사람을 겪었거나, 다른 사람이 겪는 것을 본 적이 있나요? 적어 보세요.",
      "괴롭히는 아이들을 상대할 방법으로 두 소년에게 내가 해 줄 조언은 무엇인가요? 한 문단으로 적어 보세요."] };
ACT["S4046"] = { s: "Ten-year-old Dolphin is determined to stay with her mom, even if her mom stays out quite so late or has mood spells now and again. But when her older sister Star goes to live with her newly discovered dad, their mom falls into further manic-depression.",
  q: ["Why does Dolphin want to stay with her mom, even when things are hard?",
      "Have you ever chosen to stay loyal to someone even when it was difficult? Write about it.",
      "How do you think Dolphin feels when her sister Star leaves to live with their dad? Explain your thoughts in a paragraph."],
  h: ["돌핀은 힘든 상황에서도 왜 엄마와 함께 있으려 하나요?",
      "힘들어도 누군가의 곁을 지키기로 한 적이 있나요? 적어 보세요.",
      "언니 스타가 아빠와 살러 떠날 때 돌핀은 어떤 기분일까요? 내 생각을 한 문단으로 적어 보세요."] };
ACT["S4047"] = { s: "When her lifelong friend Vicky dies, Jade struggles with grief and guilt.",
  q: ["What does Jade struggle with after her friend Vicky dies?",
      "Have you ever felt sad about losing someone or something important? Write about it, if you feel comfortable.",
      "What do you think could help Jade feel better over time? Write your idea in a paragraph."],
  h: ["친구 비키가 죽은 뒤 제이드는 무엇 때문에 힘들어하나요?",
      "소중한 사람이나 것을 잃어서 슬펐던 적이 있나요? 괜찮다면 적어 보세요.",
      "시간이 지나면서 제이드의 마음이 나아지려면 무엇이 도움이 될까요? 내 생각을 한 문단으로 적어 보세요."] };
ACT["S4048"] = { s: "When ring-leader Wendy decides Blubber is a good name for Linda, everyone in her fifth-grade class starts abusing her. This story is of mob cruelty.",
  q: ["What unkind nickname does Wendy give to Linda in this book?",
      "Have you ever seen someone be unkind to a classmate?",
      "What would you do if you saw your class being unkind to one student?"],
  h: ["웬디는 린다에게 어떤 못된 별명을 붙이나요?",
      "누군가 같은 반 친구에게 못되게 구는 것을 본 적이 있나요?",
      "우리 반이 한 친구에게 못되게 군다면 나는 어떻게 할까요?"] };
ACT["S4049"] = { s: "His younger brother's obsession with money gives Peter many embarrassing moments. And the stage for the wacky new school year is completed with the discovery of long-lost cousins, Flora and Fauna.",
  q: ["What is Peter's younger brother obsessed with in this book?",
      "Have you ever been embarrassed by something a family member did?",
      "What would you name a long-lost cousin if you discovered one, and why?"],
  h: ["피터의 남동생은 이 책에서 무엇에 푹 빠져 있나요?",
      "가족이 한 일 때문에 창피했던 적이 있나요?",
      "오랫동안 몰랐던 사촌을 알게 된다면 어떤 별명을 붙이고 싶나요? 이유도 적어 보세요."] };
ACT["S4050"] = { s: "In this book, Peter describes the disastrous family vacation in Maine with the Tubmans and his pesky little brother, Fudge. Will Peter be able to survive the summer?",
  q: ["Where does Peter's family go on vacation in this book?",
      "Have you ever been on a vacation that didn't go as planned?",
      "What would make your perfect family vacation?"],
  h: ["이 책에서 피터의 가족은 어디로 휴가를 가나요?",
      "계획대로 되지 않은 여행을 해 본 적이 있나요?",
      "내가 생각하는 완벽한 가족 여행은 어떤 모습인가요?"] };
ACT["S4051"] = { s: "When her family spends the summer in Tarrytown, Sheila faces some of her worst fears-swimming lessons! Even though she does her best to pretend that she's an expert at everything, she can't fool her best friend. Will Sheila learn that she has to admit her fears before she can overcome them?",
  q: ["What is Sheila afraid of in this book?",
      "Have you ever been afraid to learn something new, like swimming?",
      "What is something you were scared to try but did anyway?"],
  h: ["실라는 이 책에서 무엇을 두려워하나요?",
      "수영처럼 새로운 것을 배우기가 두려웠던 적이 있나요?",
      "무서웠지만 그래도 도전해 본 것은 무엇인가요?"] };
ACT["S4052"] = { s: "This book, sequel to Tales of a Fourth Grade Nothing, is about twelve-year-old Peter who relates his life with his troublesome little brother, Fudge.",
  q: ["Who is the troublesome character in Peter's life in this book?",
      "Do you have a younger brother or sister who does funny or troublesome things?",
      "What is one funny thing a sibling or family member has done?"],
  h: ["피터의 삶에서 말썽을 부리는 인물은 누구인가요?",
      "웃기거나 말썽을 부리는 동생이 있나요?",
      "가족이 저지른 재미있는 일 한 가지를 적어 보세요."] };
ACT["S4053"] = { s: "While the Clue Crew is at the River Heights Fall Festival, the girls test out all the games and win some tickets for the rides, but when their friends' tickets go missing, the Crew springs into action.",
  q: ["What goes missing at the fall festival in this book?",
      "Have you ever lost a ticket or something important at an event? Write about it.",
      "How do you think the Clue Crew will figure out what happened to the tickets? Write your idea in a paragraph."],
  h: ["가을 축제에서 이 책 속 사람들이 잃어버린 것은 무엇인가요?",
      "행사에서 티켓이나 중요한 것을 잃어버린 적이 있나요? 적어 보세요.",
      "클루 크루가 사라진 티켓의 진실을 어떻게 알아낼지 내 생각을 한 문단으로 적어 보세요."] };
ACT["S4054"] = { s: "Pete is a boy who needs to know where he stands with God, his parents, and his best friend, a confirmed atheist.",
  q: ["What three relationships does Pete want to understand better in this book?",
      "Have you ever had a big question about life or beliefs that you wanted to understand better? Write about it.",
      "Why do you think it might be hard for Pete and his atheist friend to talk about these big questions? Explain your idea in a paragraph."],
  h: ["피트가 이 책에서 더 잘 이해하고 싶어 하는 세 가지 관계는 무엇인가요?",
      "삶이나 믿음에 대해 더 잘 이해하고 싶었던 큰 질문이 있었나요? 적어 보세요.",
      "피트와 무신론자 친구가 이런 큰 질문을 이야기하기 어려운 이유는 무엇일까요? 한 문단으로 설명해 보세요."] };
ACT["S4055"] = { s: "Billy accepts the challenge to eat 15 worms in 15 days when his friend bets 50 dollars that he cannot do it.",
  q: ["What challenge does Billy accept in this book?",
      "Have you ever accepted a dare or a challenge from a friend?",
      "Would you eat a worm for 50 dollars? Why or why not?"],
  h: ["빌리는 이 책에서 어떤 도전을 받아들이나요?",
      "친구의 내기나 도전을 받아들인 적이 있나요?",
      "50달러를 준다면 지렁이를 먹을 것 같나요? 이유를 들어 보세요."] };
ACT["S4056"] = { s: "Verity is buried in sorrow when her beloved cat Mabel dies. Verity decides to mummify Mabel and keep her hidden when she remembers her recent school lessons about the Ancient Egyptians. What will happen if anyone finds out?",
  q: ["What does Verity decide to do with her cat Mabel after she dies?",
      "Have you ever lost a pet, or known someone who did? Write about how that felt.",
      "What do you think will happen if someone finds out what Verity did? Write your own idea in a paragraph."],
  h: ["베리티는 고양이 메이블이 죽은 뒤 무엇을 하기로 하나요?",
      "반려동물을 잃었거나, 그런 친구를 본 적이 있나요? 그때 느낌을 적어 보세요.",
      "베리티가 한 일이 들통나면 무슨 일이 일어날까요? 내 생각을 한 문단으로 적어 보세요."] };
ACT["S4057"] = { s: "When the unconventional English teacher who helped her conquer many of her feelings of insecurity is fired, thirteen-year-old Marcy Lewis uses her courage to campaign for the teacher's restoration.",
  q: ["What does Marcy do to try to help her teacher in this book?",
      "Have you ever stood up for a teacher or friend you cared about?",
      "What would you do if your favorite teacher was fired?"],
  h: ["마시는 선생님을 돕기 위해 이 책에서 무엇을 하나요?",
      "아끼는 선생님이나 친구를 위해 나선 적이 있나요?",
      "내가 좋아하는 선생님이 학교를 그만두게 된다면 나는 어떻게 할까요?"] };
ACT["S4058"] = { s: "Peter is thrilled to hear that Grandpa is coming to live with him, until he finds out that he will have to give up his room. Peter decides that it will take a war to regain his room.",
  q: ["What does Peter have to give up when Grandpa comes to live with him?",
      "Have you ever had to share or give up your room for someone?",
      "How would you try to solve a problem like Peter's, without a \"war\"?"],
  h: ["할아버지가 함께 살게 되면서 피터는 무엇을 포기해야 하나요?",
      "누군가를 위해 내 방을 나누거나 포기해야 했던 적이 있나요?",
      "'전쟁'을 벌이지 않고 피터의 문제를 해결하려면 나는 어떻게 할까요?"] };
ACT["S4059"] = { s: "The enormous crocodile devises secret plans and a few clever tricks to secure his lunch only to have them foiled by his neighbors.",
  q: ["What tricks does the enormous crocodile try to use to get his lunch?",
      "Have you ever made a clever plan that didn't work out the way you hoped? Write about it.",
      "Why do you think the crocodile's neighbors want to stop him? Explain your idea in a paragraph."],
  h: ["거대한 악어는 점심을 얻기 위해 어떤 꾀를 쓰나요?",
      "머리를 써서 계획을 세웠지만 생각대로 되지 않았던 적이 있나요? 적어 보세요.",
      "악어의 이웃들이 그를 막으려는 이유는 무엇일까요? 내 생각을 한 문단으로 적어 보세요."] };
ACT["S4060"] = { s: "This book highlights the life of Harriet Tubman as an American abolitionist and political activist.",
  q: ["What was Harriet Tubman's role in American history, according to this book?",
      "Have you learned about a brave person in history before? Who was it?",
      "What is one word you would use to describe Harriet Tubman?"],
  h: ["이 책에 따르면 해리엇 터브먼은 미국 역사에서 어떤 역할을 했나요?",
      "역사 속 용감한 사람에 대해 배운 적이 있나요? 누구였나요?",
      "해리엇 터브먼을 한 단어로 표현한다면 무엇이라고 하고 싶나요?"] };
ACT["S4061"] = { s: "Cinderboy is football-mad, so he is heartbroken when his mean stepdad takes his two lazy stepbrothers to watch the Cup Final, but then TV godmother appears and promises he will go to the match after all.",
  q: ["Why is Cinderboy heartbroken at the start of this book?",
      "Have you ever been left out of something you really wanted to do? Write about how it felt.",
      "How do you think the TV godmother will help Cinderboy get to the match? Write your idea in a paragraph."],
  h: ["신더보이는 이 책 초반에 왜 마음이 아픈가요?",
      "정말 하고 싶었던 일에서 나만 빠졌던 적이 있나요? 그 기분을 적어 보세요.",
      "TV 요정 대모는 신더보이가 경기를 보러 가도록 어떻게 도와줄까요? 내 생각을 한 문단으로 적어 보세요."] };
ACT["S4062"] = { s: "In this modern twist on the classic story of \"The Three Little Pigs,\" Eco-Wolf and his woodland warriors save the forest and valley from three polluting pigs.",
  q: ["What do the three pigs do that is bad for the forest in this book?",
      "Have you ever helped clean up or protect nature?",
      "What is one thing you could do to help protect the environment?"],
  h: ["세 마리 돼지는 이 책에서 숲에 어떤 나쁜 짓을 하나요?",
      "자연을 청소하거나 지키는 것을 도운 적이 있나요?",
      "환경을 지키기 위해 내가 할 수 있는 일 한 가지는 무엇인가요?"] };
ACT["S4063"] = { s: "When he sells their cow for a tin of baked beans, daft Jack's mother is not very pleased ? until they realize that this is a lucky bean tin and they have won a brilliant prize.",
  q: ["What does daft Jack trade the family cow for in this book?",
      "Have you ever traded something and later found out it was worth more than you thought? Write about it.",
      "What do you think the \"brilliant prize\" might be? Write your own guess in a paragraph."],
  h: ["잭은 이 책에서 소를 무엇과 바꾸나요?",
      "무언가를 바꾸고 나중에 생각보다 값진 것이었음을 알게 된 적이 있나요? 적어 보세요.",
      "그 '멋진 상품'이 무엇일 것 같나요? 내 생각을 한 문단으로 적어 보세요."] };
ACT["S4064"] = { s: "In this version of \"Little Red Riding Hood,\" a big, bad girl scares a wolf cub who is going to visit his granny wolf.",
  q: ["Who is scared in this twisted version of the story, and who scares them?",
      "Have you ever heard a story told in a surprising, twisted way before? Write about it.",
      "How do you think the wolf cub feels after being scared by the girl? Write your idea in a paragraph."],
  h: ["이 뒤집힌 이야기에서 겁을 먹는 것은 누구이고, 누가 겁을 주나요?",
      "익숙한 이야기가 뜻밖의 방식으로 뒤집힌 것을 들어 본 적이 있나요? 적어 보세요.",
      "여자아이에게 겁을 먹은 뒤 늑대 새끼는 어떤 기분일까요? 내 생각을 한 문단으로 적어 보세요."] };
ACT["S4065"] = { s: "Snow White wants to be a pop star. Her mum is not in favour. Luckily the seven aliens arrive in time to rescue her dream.",
  q: ["What dream does Snow White have in this book?",
      "Have you ever had a dream that someone else didn't support at first? Write about it.",
      "How do you imagine the seven aliens help Snow White become a pop star? Write your idea in a paragraph."],
  h: ["백설공주는 이 책에서 어떤 꿈을 가지고 있나요?",
      "다른 사람이 처음에는 응원해 주지 않았던 꿈이 있었나요? 적어 보세요.",
      "일곱 외계인은 백설공주가 팝스타가 되도록 어떻게 도와줄까요? 내 생각을 한 문단으로 적어 보세요."] };
ACT["S4066"] = { s: "A fictional girl writes a report after a visit to the National Baseball Hall of Fame and presents a history of the Negro leagues.",
  q: ["What does the girl in this book do after visiting the National Baseball Hall of Fame?",
      "Have you ever visited a museum and learned something new? Write about it.",
      "Why do you think it is important to learn about the history of the Negro leagues? Write your thoughts in a paragraph."],
  h: ["이 책 속 여자아이는 명예의 전당을 방문한 뒤 무엇을 하나요?",
      "박물관에 가서 새로운 것을 배운 적이 있나요? 적어 보세요.",
      "니그로 리그의 역사를 배우는 것이 왜 중요할까요? 내 생각을 한 문단으로 적어 보세요."] };
ACT["S4067"] = { s: "The kids in Ms. Brandt's class create a special report on the United States of America.",
  q: ["What do the kids in Ms. Brandt's class make a report about?",
      "Have you ever made a report or project about a place?",
      "If you made a report about a state, which one would you choose?"],
  h: ["브랜트 선생님 반 아이들은 무엇에 대한 보고서를 만드나요?",
      "어떤 장소에 대한 보고서나 프로젝트를 만들어 본 적이 있나요?",
      "미국의 한 주에 대해 보고서를 쓴다면 어떤 주를 고르고 싶나요?"] };
ACT["S4068"] = { s: "This book describes the structure and behavior of various carnivorous plants.",
  q: ["What kind of plants does this book describe, and how do they behave?",
      "Have you ever seen or heard about a plant that eats insects? Write about what you know or imagine.",
      "Why do you think some plants need to eat insects to survive? Explain your idea in a paragraph."],
  h: ["이 책은 어떤 식물을 설명하고, 그 식물은 어떻게 행동하나요?",
      "곤충을 먹는 식물을 보거나 들어 본 적이 있나요? 아는 것이나 상상한 것을 적어 보세요.",
      "어떤 식물은 왜 곤충을 먹어야 살아남을까요? 내 생각을 한 문단으로 적어 보세요."] };
ACT["S4069"] = { s: "This book describes the eruption of Mount St. Helens in Washington State in 1980.",
  q: ["What volcano and event does this book describe?",
      "Have you ever seen a picture or video of a volcano erupting? Write about what you saw or imagine.",
      "Why do you think volcanic eruptions can be so dangerous? Explain your idea in a paragraph."],
  h: ["이 책은 어떤 화산과 사건을 설명하나요?",
      "화산이 폭발하는 사진이나 영상을 본 적이 있나요? 보았거나 상상한 것을 적어 보세요.",
      "화산 폭발이 왜 그렇게 위험할까요? 내 생각을 한 문단으로 적어 보세요."] };
ACT["S4070"] = { s: "This book introduces the careers of six of baseball's greatest hitters, including Babe Ruth, Hank Aaron, and Mark McGwire.",
  q: ["Name one of the baseball hitters described in this book.",
      "Have you ever played or watched baseball? Write about your experience.",
      "What do you think makes someone a great hitter in baseball? Explain your idea in a paragraph."],
  h: ["이 책에 나오는 야구 타자 중 한 명의 이름을 적어 보세요.",
      "야구를 해 보거나 본 적이 있나요? 그 경험을 적어 보세요.",
      "훌륭한 타자가 되려면 무엇이 필요할까요? 내 생각을 한 문단으로 적어 보세요."] };
ACT["S4071"] = { s: "This book examines the accomplishments of Babe Ruth, Joe DiMaggio, Jackie Robinson, Roberto Clemente, and Hank Aaron, all of whom were elected to the Baseball Hall of Fame.",
  q: ["Name one player from this book who was elected to the Baseball Hall of Fame.",
      "Have you ever admired someone for their accomplishments in a sport? Write about it.",
      "Why do you think these five players are remembered as some of baseball's best? Explain your idea in a paragraph."],
  h: ["이 책에서 명예의 전당에 오른 선수 한 명의 이름을 적어 보세요.",
      "스포츠에서 누군가의 업적을 존경한 적이 있나요? 적어 보세요.",
      "이 다섯 선수가 야구 역사상 최고로 기억되는 이유는 무엇일까요? 내 생각을 한 문단으로 적어 보세요."] };
ACT["S4072"] = { s: "In the year 1195, young Roger and his sister Alice travel the French countryside in search of their ailing mother's estranged brother, a wealthy baron.",
  q: ["Who are Roger and Alice searching for in this book, and why?",
      "Have you ever gone looking for a relative you didn't know well? Write about it, or imagine what that might be like.",
      "What difficulties do you think Roger and Alice might face traveling through the French countryside? Write your ideas in a paragraph."],
  h: ["로저와 앨리스는 이 책에서 누구를 찾고 있고, 그 이유는 무엇인가요?",
      "잘 몰랐던 친척을 찾으러 나선 적이 있나요? 적거나, 그것이 어떤 느낌일지 상상해서 적어 보세요.",
      "프랑스 시골을 여행하는 로저와 앨리스는 어떤 어려움을 겪을까요? 내 생각을 한 문단으로 적어 보세요."] };
ACT["S4073"] = { s: "This book tells the story of an eleven-year-old detective and his adventures after finding a duck in the elevator of his apartment building.",
  q: ["What strange thing does the eleven-year-old detective find in the elevator?",
      "Have you ever found something surprising in an unexpected place? Write about it.",
      "How do you think the duck ended up in the elevator? Write your own guess in a paragraph."],
  h: ["열한 살 탐정은 엘리베이터에서 어떤 이상한 것을 발견하나요?",
      "예상치 못한 곳에서 놀라운 것을 발견한 적이 있나요? 적어 보세요.",
      "그 오리는 어쩌다 엘리베이터에 있게 됐을까요? 내 짐작을 한 문단으로 적어 보세요."] };
ACT["S4074"] = { s: "This book tells what happens beneath the Earth to cause a volcanic eruption and the different structures beneath the Earth that cause new land to form.",
  q: ["What happens beneath the Earth to cause a volcanic eruption, according to this book?",
      "Have you ever wondered how mountains or land are formed? Write about your thoughts.",
      "Why do you think it's important for scientists to understand what happens beneath the Earth? Explain in a paragraph."],
  h: ["이 책에 따르면 땅속에서 어떤 일이 일어나 화산 폭발이 일어나나요?",
      "산이나 땅이 어떻게 생겨났는지 궁금했던 적이 있나요? 내 생각을 적어 보세요.",
      "과학자들이 땅속에서 일어나는 일을 이해하는 것이 왜 중요할까요? 한 문단으로 설명해 보세요."] };
ACT["S4075"] = { s: "This book explains what distinguishes a pond from other bodies of water, the plant and animal life within it, and how their life cycles contribute to the pond itself.",
  q: ["What makes a pond different from other bodies of water, according to this book?",
      "Have you ever visited a pond? Write about what you saw there, or imagine what you might see.",
      "Why do you think plants and animals in a pond depend on each other? Explain your idea in a paragraph."],
  h: ["이 책에 따르면 연못은 다른 물과 무엇이 다른가요?",
      "연못에 가 본 적이 있나요? 거기서 본 것을 적거나, 무엇을 보게 될지 상상해서 적어 보세요.",
      "연못 속 식물과 동물이 서로 의지하며 사는 이유는 무엇일까요? 내 생각을 한 문단으로 적어 보세요."] };
ACT["S4076"] = { s: "This book shows how and where these storms form and the dangers they pose to the land and people who live in Gulf and Atlantic coast regions.",
  q: ["Where do hurricanes often cause danger, according to this book?",
      "Have you ever experienced or heard about a big storm? Write about it.",
      "Why do you think people who live near the coast need to prepare for hurricanes? Explain your idea in a paragraph."],
  h: ["이 책에 따르면 허리케인은 주로 어디에서 위험을 일으키나요?",
      "큰 폭풍을 겪거나 들어 본 적이 있나요? 적어 보세요.",
      "해안 근처에 사는 사람들이 허리케인을 대비해야 하는 이유는 무엇일까요? 내 생각을 한 문단으로 적어 보세요."] };
ACT["S4077"] = { s: "This book provides an exploration of diving and climbing sports and discusses scientific concepts related to them as well as describing the actions of people who participate in them.",
  q: ["What two sports does this book explore, and what science is connected to them?",
      "Have you ever tried climbing or diving, even a small amount? Write about your experience.",
      "Why do you think understanding science can help someone become better at climbing or diving? Explain your idea in a paragraph."],
  h: ["이 책은 어떤 두 가지 스포츠를 다루고, 그것과 관련된 과학은 무엇인가요?",
      "작게라도 클라이밍이나 다이빙을 해 본 적이 있나요? 그 경험을 적어 보세요.",
      "과학을 이해하면 클라이밍이나 다이빙을 더 잘하는 데 왜 도움이 될까요? 내 생각을 한 문단으로 적어 보세요."] };
ACT["S4078"] = { s: "Grave robbers devise a plan to steal King Tutankhamen’s riches after his funeral.",
  q: ["What do the grave robbers plan to do in this book?",
      "Have you ever heard of ancient Egyptian kings and their treasures before?",
      "What do you think should happen to people who try to steal from a tomb?"],
  h: ["도굴꾼들은 이 책에서 무엇을 계획하나요?",
      "고대 이집트 왕들과 그들의 보물에 대해 들어 본 적이 있나요?",
      "무덤에서 물건을 훔치려는 사람들은 어떻게 되어야 한다고 생각하나요?"] };
ACT["S4079"] = { s: "To earn money, a poor student in ancient Egypt agrees to help an old woman remove a ghost. But instead, he discovers the true identity of the phantom and receives a rich reward.",
  q: ["What does the poor student agree to do to earn money in this book?",
      "Have you ever done a job or favor to earn money or a reward?",
      "Who or what do you think the \"phantom\" really turns out to be?"],
  h: ["가난한 학생은 돈을 벌기 위해 이 책에서 무엇을 하기로 하나요?",
      "돈이나 보상을 얻기 위해 일이나 부탁을 해 본 적이 있나요?",
      "그 '유령'의 진짜 정체는 무엇일 것 같나요?"] };
ACT["S4080"] = { s: "A clever trick saves the workers who are building the Great Pyramid, and their working conditions are improved as well.",
  q: ["What happens to the workers building the Great Pyramid in this book?",
      "Have you ever used a clever trick to solve a problem?",
      "What trick would you use to help workers who are having a hard time?"],
  h: ["대피라미드를 짓는 일꾼들에게 이 책에서 무슨 일이 일어나나요?",
      "문제를 해결하기 위해 꾀를 써 본 적이 있나요?",
      "힘든 상황의 일꾼들을 도울 꾀는 무엇이 있을까요?"] };
ACT["S4081"] = { s: "In 1180 B.C., Acheron the storyteller is so well-known as a liar that no one believes him when he is suspicious of a wooden horse left by the Greek army.",
  q: ["Why does no one believe Acheron in this book?",
      "Have you ever told the truth but no one believed you?",
      "What would you do if you knew something dangerous was hidden inside the wooden horse?"],
  h: ["이 책에서 아케론의 말을 아무도 믿지 않는 이유는 무엇인가요?",
      "진실을 말했는데 아무도 믿어 주지 않았던 적이 있나요?",
      "목마 안에 위험한 것이 숨어 있다는 것을 안다면 나는 어떻게 할까요?"] };
ACT["S4082"] = { s: "Cypselis has made a bet with Big Bacchiad. If Cypselis can beat him in an Olympic foot race, Cypselis' family will receive a goat. But if Cypselis loses, his twin sister will become Big Bacchiad's slave!",
  q: ["What does Cypselis risk if he loses the foot race?",
      "Have you ever competed in a race or contest that felt really important?",
      "Do you think it is fair to make such a big bet on a race? Explain why or why not."],
  h: ["키프셀리스는 경주에서 지면 무엇을 잃게 되나요?",
      "정말 중요하게 느껴졌던 경주나 시합에 나가 본 적이 있나요?",
      "경주 하나에 이렇게 큰 것을 거는 것이 공평하다고 생각하나요? 이유를 들어 보세요."] };
ACT["S4083"] = { s: "Young Darius is forced to leave and join his uncle, a Spartan general, and prove to the Spartans that he is worth more than what meets the eye.",
  q: ["What does Darius have to prove to the Spartans in this book?",
      "Have you ever had to prove yourself to someone who doubted you?",
      "What would you do to prove yourself worth more than people expect?"],
  h: ["다리우스는 스파르타인들에게 무엇을 증명해야 하나요?",
      "나를 의심하는 사람에게 내 능력을 증명해야 했던 적이 있나요?",
      "사람들의 기대보다 더 뛰어난 나를 보여 주려면 나는 무엇을 할까요?"] };
ACT["S4084"] = { s: "A young actor at the Globe Theatre must defend his master when Queen Elizabeth suspects that Shakespeare tried to help the Earl of Essex overthrow her.",
  q: ["What does the young actor have to do for his master in this book?",
      "Have you ever had to defend or stand up for someone you cared about? Write about it.",
      "Why do you think Queen Elizabeth suspected Shakespeare of helping overthrow her? Write your idea in a paragraph."],
  h: ["젊은 배우는 이 책에서 자신의 스승을 위해 무엇을 해야 하나요?",
      "아끼는 사람을 변호하거나 나서서 지켜 준 적이 있나요? 적어 보세요.",
      "엘리자베스 여왕은 왜 셰익스피어를 의심했을까요? 내 생각을 한 문단으로 적어 보세요."] };
ACT["S4085"] = { s: "A poor serving girl conspires to save an innocent woman that Lord Scuggate is planning to burn as a witch in order to impress the queen.",
  q: ["What is the serving girl trying to save the innocent woman from in this book?",
      "Have you ever tried to help someone who was being treated unfairly? Write about it.",
      "Why do you think Lord Scuggate wanted to accuse an innocent woman of witchcraft? Write your idea in a paragraph."],
  h: ["하녀는 이 책에서 죄 없는 여인을 무엇으로부터 구하려 하나요?",
      "부당한 대우를 받는 사람을 도우려 한 적이 있나요? 적어 보세요.",
      "스카게이트 경은 왜 죄 없는 여인을 마녀로 몰려 했을까요? 내 생각을 한 문단으로 적어 보세요."] };
ACT["S4086"] = { s: "The niece of King Henry VII of England infiltrates the servants' quarters to find out if one of the kitchen helpers is trying to become king.",
  q: ["What does the king's niece do to investigate in this book?",
      "Have you ever pretended to be someone else to find out information?",
      "How do you think the niece will find out the truth?"],
  h: ["왕의 조카는 이 책에서 조사를 위해 무엇을 하나요?",
      "정보를 알아내려고 다른 사람인 척한 적이 있나요?",
      "그 조카는 진실을 어떻게 알아낼까요?"] };
ACT["S4087"] = { s: "A family of street performers wins a pile of gold when they are called to perform for King Henry VIII, but they have to lose it again to save themselves from being hanged.",
  q: ["What does the family of street performers win, and what do they later have to do with it?",
      "Have you ever had to give up something you won or earned?",
      "What would you do if you had to choose between keeping treasure and staying safe?"],
  h: ["거리 공연자 가족은 무엇을 얻고, 나중에 그것을 어떻게 해야 하나요?",
      "얻거나 번 것을 다시 포기해야 했던 적이 있나요?",
      "보물을 지키는 것과 안전을 지키는 것 중 하나를 골라야 한다면 나는 어떻게 할까요?"] };
ACT["S4088"] = { s: "Brother and Sister Bear are not greedy, but all the toys on TV look so great! Mama Bear teaches her cubs that they can't believe everything they see.",
  q: ["What lesson does Mama Bear teach Brother and Sister Bear in this book?",
      "Have you ever seen a toy or product advertised on TV that looked better than it really was? Write about it.",
      "Why do you think it's important not to believe everything you see in commercials? Explain your idea in a paragraph."],
  h: ["엄마 곰은 이 책에서 남매 곰에게 어떤 교훈을 가르쳐 주나요?",
      "TV 광고에서 실제보다 더 좋아 보였던 장난감이나 물건을 본 적이 있나요? 적어 보세요.",
      "광고에서 보는 것을 다 믿으면 안 되는 이유는 무엇일까요? 내 생각을 한 문단으로 적어 보세요."] };
ACT["S4089"] = { s: "The members of the Freaky Joe Club are back in school, but something strange is going on at the Edith R. Hammerrocker Elementary School. Why does the new principal hate the school's nickname and what is a Hammerrocker Hamster anyway?",
  q: ["What does the new principal seem to dislike in this book?",
      "Have you ever wondered about a strange nickname at your school?",
      "What do you think a \"Hammerrocker Hamster\" might be?"],
  h: ["새 교장 선생님은 이 책에서 무엇을 싫어하는 것 같나요?",
      "우리 학교의 이상한 별명에 대해 궁금했던 적이 있나요?",
      "'해머로커 햄스터'는 무엇일 것 같나요?"] };
ACT["S4090"] = { s: "Ms. Frizzle takes the class on a field trip to a costume company to look for the missing bones on a skeleton costume.",
  q: ["What are Ms. Frizzle's class looking for at the costume company?",
      "Have you ever gone on a field trip that taught you something surprising? Write about it.",
      "What do you think happened to the missing bones? Write your own guess in a paragraph."],
  h: ["프리즐 선생님 반은 의상 회사에서 무엇을 찾고 있나요?",
      "놀라운 것을 배운 현장 학습을 가 본 적이 있나요? 적어 보세요.",
      "사라진 뼈들에게 무슨 일이 일어났을까요? 내 짐작을 한 문단으로 적어 보세요."] };
ACT["S4091"] = { s: "Ms. Frizzle and the class go to see whales.",
  q: ["What animal does Ms. Frizzle's class go to see in this book?",
      "Have you ever seen a whale, in real life or in a video? Write about it.",
      "What do you think it would be like to see a whale up close? Write your idea in a paragraph."],
  h: ["프리즐 선생님 반은 이 책에서 어떤 동물을 보러 가나요?",
      "실제로나 영상으로 고래를 본 적이 있나요? 적어 보세요.",
      "고래를 가까이에서 본다면 어떤 느낌일까요? 내 생각을 한 문단으로 적어 보세요."] };
ACT["S4092"] = { s: "Ms. Frizzle takes the class on a field trip to outer space and they learn all about the awesome solar system.",
  q: ["What do Ms. Frizzle's class learn about on their trip to outer space?",
      "Have you ever looked at the stars or planets in the sky? Write about it.",
      "Which planet would you most want to visit, and why? Explain your idea in a paragraph."],
  h: ["프리즐 선생님 반은 우주 여행에서 무엇을 배우나요?",
      "밤하늘의 별이나 행성을 바라본 적이 있나요? 적어 보세요.",
      "어느 행성에 가장 가 보고 싶나요? 이유와 함께 한 문단으로 적어 보세요."] };
ACT["S4093"] = { s: "Ms. Frizzle takes the class on a field trip to Weatherama Theme Park and they learn the hair-raising facts about tornadoes.",
  q: ["Where does Ms. Frizzle's class go on their field trip in this book?",
      "Have you ever learned a surprising fact about weather?",
      "What is one fact about tornadoes you already know or want to learn?"],
  h: ["프리즐 선생님 반은 이 책에서 어디로 현장 학습을 가나요?",
      "날씨에 대해 놀라운 사실을 배운 적이 있나요?",
      "토네이도에 대해 이미 알거나 알고 싶은 사실 한 가지는 무엇인가요?"] };
ACT["S4094"] = { s: "Ms. Frizzle takes the class on a field trip and they meet all kinds of sharks.",
  q: ["What kind of animals does Ms. Frizzle's class meet in this book?",
      "Have you ever seen a shark, in real life, at an aquarium, or on video? Write about it.",
      "What do you think it would feel like to meet a shark up close? Write your idea in a paragraph."],
  h: ["프리즐 선생님 반은 이 책에서 어떤 동물들을 만나나요?",
      "실제로, 수족관에서, 또는 영상으로 상어를 본 적이 있나요? 적어 보세요.",
      "상어를 가까이에서 만난다면 어떤 느낌일까요? 내 생각을 한 문단으로 적어 보세요."] };
ACT["S4095"] = { s: "Ms Frizzle and the gang find out they must become Dinosaur Detectives at the Museum of Natural History.",
  q: ["Where does Ms. Frizzle's class go to become Dinosaur Detectives?",
      "Have you ever visited a museum of natural history or seen dinosaur bones?",
      "What dinosaur would you most want to learn about?"],
  h: ["프리즐 선생님 반은 공룡 탐정이 되기 위해 어디로 가나요?",
      "자연사 박물관에 가 보거나 공룡 뼈를 본 적이 있나요?",
      "가장 알고 싶은 공룡은 무엇인가요?"] };
ACT["S4096"] = { s: "Ms. Frizzle's class travels on the Magic School Bus to Australia where they study the continent's animals.",
  q: ["Which country does Ms. Frizzle's class travel to, and what do they study there?",
      "Have you ever learned about animals from another country? Write about it.",
      "What Australian animal would you most want to study up close, and why? Explain your idea in a paragraph."],
  h: ["프리즐 선생님 반은 어느 나라로 여행을 떠나고, 그곳에서 무엇을 공부하나요?",
      "다른 나라의 동물에 대해 배운 적이 있나요? 적어 보세요.",
      "가까이에서 연구해 보고 싶은 호주 동물은 무엇인가요? 이유와 함께 한 문단으로 적어 보세요."] };
ACT["S4097"] = { s: "Lucy and Bill travel on a seemingly ordinary train. But suddenly they find themselves in ancient Rome.",
  q: ["Where do Lucy and Bill suddenly find themselves in this book?",
      "Have you ever imagined traveling back in time to an ancient civilization? Write about where you would go.",
      "What do you think Lucy and Bill will see and do in ancient Rome? Write your ideas in a paragraph."],
  h: ["루시와 빌은 이 책에서 갑자기 어디에 있게 되나요?",
      "고대 문명으로 시간 여행을 떠나는 상상을 해 본 적이 있나요? 어디로 가고 싶은지 적어 보세요.",
      "루시와 빌은 고대 로마에서 무엇을 보고 하게 될까요? 내 생각을 한 문단으로 적어 보세요."] };
ACT["S4098"] = { s: "Ms. Frizzle's class challenges Mr. O'Neatly's class to a science contest with the topic of magnetism.",
  q: ["What topic is the science contest about in this book?",
      "Have you ever competed with another class or team in a contest? Write about it.",
      "What do you already know about magnets, or what would you like to learn? Explain in a paragraph."],
  h: ["이 책에서 과학 대회의 주제는 무엇인가요?",
      "다른 반이나 팀과 대회에서 겨뤄 본 적이 있나요? 적어 보세요.",
      "자석에 대해 이미 알고 있는 것이나 알고 싶은 것을 한 문단으로 설명해 보세요."] };
ACT["S4099"] = { s: "Ms. Frizzle's class goes to the North Pole to study the animals of the Arctic.",
  q: ["Where does Ms. Frizzle's class travel to in this book?",
      "Have you ever learned about animals that live in cold places?",
      "What Arctic animal would you most like to learn about?"],
  h: ["프리즐 선생님 반은 이 책에서 어디로 여행을 떠나나요?",
      "추운 곳에 사는 동물에 대해 배운 적이 있나요?",
      "가장 알고 싶은 북극 동물은 무엇인가요?"] };
