// 간이 학습 질문 — Book No. S41 묶음. 사람이 아니라 AI 가 한 번 쓰고 굳힌 파일이다.
window.ACT = window.ACT || {};
var ACT = window.ACT;
ACT["S4100"] = { s: "The Magic School Bus takes Ms. Frizzle's class into a thunderstorm so that her students can study it.",
  q: ["What did Ms. Frizzle's class get to study by going right into a thunderstorm?",
      "Have you ever watched a thunderstorm from somewhere safe? Describe what you saw and heard.",
      "If your class could ride the Magic School Bus into any kind of weather, what would you choose and why?"],
  h: ["프리즐 선생님 반은 폭풍 속으로 직접 들어가서 무엇을 공부했나요?",
      "안전한 곳에서 천둥번개 치는 날을 본 적이 있나요? 그때 보고 들은 것을 설명해 보세요.",
      "우리 반이 매직 스쿨버스를 타고 어떤 날씨 속으로도 갈 수 있다면, 나는 어떤 날씨를 고르고 싶고 왜 그런가요?"] };
ACT["S4101"] = { s: "Arnold is not happy when his class goes on a food chain field trip the day his cousin Janet comes to school with him.",
  q: ["Why do you think Arnold was not happy about the food chain field trip that day?",
      "Has someone in your family ever visited your school or class with you? What was that day like?",
      "What do you think Arnold might have learned about food chains, even though the timing was bad for him?"],
  h: ["그날 아놀드는 왜 먹이사슬 체험학습을 좋아하지 않았을까요?",
      "우리 가족 중 누군가 나와 함께 학교나 교실에 온 적이 있나요? 그날은 어땠나요?",
      "타이밍이 나빴어도 아놀드가 먹이사슬에 대해 무엇을 배웠을 것 같나요?"] };
ACT["S4102"] = { s: "The kids in Ms. Frizzle's class learn firsthand lessons about the underwater world.",
  q: ["What kind of lessons do you think the kids learned about the underwater world firsthand?",
      "Have you ever seen the underwater world, at an aquarium, the ocean, or on TV? What did you notice?",
      "If you could learn about the underwater world firsthand like Ms. Frizzle's class, what would you most want to see?"],
  h: ["아이들은 바닷속 세계에 대해 직접 어떤 것들을 배웠을 것 같나요?",
      "수족관이나 바다, 또는 텔레비전에서 바닷속 세계를 본 적이 있나요? 무엇을 알게 되었나요?",
      "프리즐 선생님 반처럼 바닷속을 직접 배울 수 있다면, 가장 보고 싶은 것은 무엇인가요?"] };
ACT["S4103"] = { s: "Ms. Frizzle's class learns about light and color while racing in the Color Day relays.",
  q: ["What did Ms. Frizzle's class learn while racing in the Color Day relays?",
      "Have you ever taken part in a relay race? What was it like?",
      "What is your favorite color and why?"],
  h: ["프리즐 선생님 반은 색깔의 날 계주를 하며 무엇을 배웠나요?",
      "계주 경기를 해 본 적이 있나요? 어땠나요?",
      "내가 가장 좋아하는 색은 무엇이고 이유는 무엇인가요?"] };
ACT["S4104"] = { s: "Ms. Frizzle's class goes on a field trip to the western U.S. in order to study rocks and minerals.",
  q: ["What do you think Ms. Frizzle's class discovered about rocks and minerals on their trip out west?",
      "Have you ever collected rocks or looked closely at one? Describe what you found interesting about it.",
      "If you went on a field trip to study rocks and minerals, what would you hope to bring home?"],
  h: ["프리즐 선생님 반은 서부로 간 체험학습에서 암석과 광물에 대해 무엇을 알아냈을까요?",
      "돌을 모으거나 자세히 살펴본 적이 있나요? 그 돌의 어떤 점이 흥미로웠나요?",
      "암석과 광물을 공부하러 체험학습을 간다면, 무엇을 가져오고 싶나요?"] };
ACT["S4105"] = { s: "When Joe, Fred, and Sam are sent back in time by a magic book, they find themselves face to face with giants, dragons, wizards, King Arthur, and the Knights of the Round Table.",
  q: ["Who do Joe, Fred, and Sam meet after the magic book sends them back in time?",
      "If a magic book could send you back in time, where would you want to go?",
      "Which person or creature from the story would you most want to meet?"],
  h: ["마법의 책이 조, 프레드, 샘을 과거로 보낸 뒤 그들은 누구를 만나나요?",
      "마법의 책이 나를 과거로 보내 준다면 나는 어디로 가고 싶나요?",
      "이야기에 나온 인물이나 존재 중에 가장 만나고 싶은 것은 누구인가요?"] };
ACT["S4106"] = { s: "Joe receives a mysterious book from his uncle, and soon Joe and his friends travel back in time to a pirate adventure on the ocean.",
  q: ["Who gives Joe the mysterious book that starts the adventure?",
      "Have you ever received a mysterious or surprising gift? What was it?",
      "Would you like to travel back in time to a pirate adventure? Why or why not?"],
  h: ["이 모험을 시작하게 한 신비한 책을 조에게 준 사람은 누구인가요?",
      "신비하거나 뜻밖의 선물을 받은 적이 있나요? 무엇이었나요?",
      "과거로 가서 해적 모험을 하고 싶나요? 이유는 무엇인가요?"] };
ACT["S4107"] = { s: "Joe, Sam, and Fred are cowboys who find the Wild West just a bit too wild.",
  q: ["What do Joe, Sam, and Fred become in this story?",
      "Have you ever seen a movie or story about cowboys and the Wild West? What was it like?",
      "Do you think you would enjoy living in the Wild West? Why or why not?"],
  h: ["이 이야기에서 조, 샘, 프레드는 무엇이 되나요?",
      "카우보이나 서부 개척 시대에 관한 영화나 이야기를 본 적이 있나요? 어땠나요?",
      "서부 개척 시대에 산다면 즐거울 것 같나요? 이유는 무엇인가요?"] };
ACT["S4108"] = { s: "The Time Warp Trio find themselves in the middle of an adventure in prehistoric times.",
  q: ["What time period does the Time Warp Trio travel to in this book?",
      "Have you ever learned about prehistoric times at school? What did you learn?",
      "What is one thing you would want to see if you visited prehistoric times?"],
  h: ["이 책에서 타임 워프 트리오는 어느 시대로 여행을 가나요?",
      "학교에서 선사 시대에 대해 배운 적이 있나요? 무엇을 배웠나요?",
      "선사 시대를 방문한다면 가장 보고 싶은 것은 무엇인가요?"] };
ACT["S4109"] = { s: "While on a field trip to New York's Museum of Natural History, Joe, Sam, and Fred travel 100 years into the future, where they encounter futuristic things.",
  q: ["Where are Joe, Sam, and Fred when they travel 100 years into the future?",
      "Have you ever visited a museum? What did you see there?",
      "What is one futuristic thing you would like to see 100 years from now?"],
  h: ["조, 샘, 프레드가 100년 뒤 미래로 가게 될 때 그들은 어디에 있었나요?",
      "박물관에 가 본 적이 있나요? 그곳에서 무엇을 보았나요?",
      "100년 후 미래에서 보고 싶은 것을 한 가지 적어 보세요."] };
ACT["S4110"] = { s: "Because of a magical time travel book, the kids are dodging crocodiles and trying to outwit the evil high priest.",
  q: ["What two dangers do the kids have to deal with in this book?",
      "Have you ever had to think quickly to get out of a tricky situation? What happened?",
      "If you had to outwit an evil high priest like the kids in this story, what kind of plan would you try?"],
  h: ["이 책에서 아이들이 맞닥뜨리는 두 가지 위험은 무엇인가요?",
      "곤란한 상황에서 빠르게 생각해서 빠져나온 적이 있나요? 무슨 일이 있었나요?",
      "이 이야기 속 아이들처럼 사악한 대제사장을 이겨내야 한다면, 나는 어떤 계획을 세워 볼 것 같나요?"] };
ACT["S4111"] = { s: "When their reading list is accidently placed in The Book at the beginning of summer vacation, Joe, Sam, and Fred find themselves trapped inside a strange bookish universe.",
  q: ["What gets accidentally placed in The Book at the start of summer vacation?",
      "Do you have a summer reading list? What is on it?",
      "Would you like to be trapped inside a bookish universe like Joe, Sam, and Fred? Why or why not?"],
  h: ["여름방학이 시작될 때 실수로 그 책 속에 들어가게 되는 것은 무엇인가요?",
      "여름방학 독서 목록이 있나요? 그 목록에는 무엇이 있나요?",
      "조, 샘, 프레드처럼 책 속 세상에 갇히고 싶나요? 이유는 무엇인가요?"] };
ACT["S4112"] = { s: "Joe, Fred, and Sam are transported to ancient Rome and forced to fight as gladiators in the Colosseum.",
  q: ["What are Joe, Fred, and Sam forced to do once they arrive in ancient Rome?",
      "Have you ever learned about ancient Rome or the Colosseum? What do you remember about it?",
      "How do you think you would feel if you were suddenly forced to fight as a gladiator like the boys in this story?"],
  h: ["조, 프레드, 샘이 고대 로마에 도착한 뒤 억지로 하게 되는 일은 무엇인가요?",
      "고대 로마나 콜로세움에 대해 배운 적이 있나요? 기억나는 것이 있나요?",
      "이 이야기 속 아이들처럼 갑자기 검투사로 싸워야 한다면 나는 어떤 기분일 것 같나요?"] };
ACT["S4113"] = { s: "Joe, Fred, and Sam are transported to 17th century Japan where they infuriate a Samurai warrior, encounter their great-granddaughters, and save their lives by reciting an ancient form of poetry.",
  q: ["What do Joe, Fred, and Sam use to save their lives in 17th century Japan?",
      "Have you ever written or read a poem? What was it about?",
      "Would you like to meet your own great-granddaughters someday like the boys in this story? Why or why not?"],
  h: ["17세기 일본에서 조, 프레드, 샘이 목숨을 구하기 위해 사용한 것은 무엇인가요?",
      "시를 써 보거나 읽어 본 적이 있나요? 어떤 내용이었나요?",
      "이 이야기 속 소년들처럼 언젠가 나의 증손녀를 만나고 싶나요? 이유는 무엇인가요?"] };
ACT["S4114"] = { s: "Fred, Sam, and Joe travel through time to 1877 New York City, where they and their great granddaughters, who have also come from the future, help them find a way back to their own time.",
  q: ["Who helps Fred, Sam, and Joe find a way back to their own time?",
      "Have you ever gotten lost or needed help finding your way somewhere? Who helped you?",
      "If you traveled to New York City in 1877, what do you think would surprise you the most?"],
  h: ["프레드, 샘, 조가 자기 시대로 돌아갈 길을 찾도록 도와주는 사람은 누구인가요?",
      "길을 잃거나 길을 찾는 데 도움이 필요했던 적이 있나요? 누가 도와주었나요?",
      "1877년 뉴욕시로 간다면 무엇이 가장 놀라울 것 같나요?"] };
ACT["S4115"] = { s: "Did you know that our word Thursday comes from the Viking god Thor ... as in Thor's Day? This book lets you know what happened two thousand years ago.",
  q: ["Which day of the week does this book say comes from the Viking god Thor?",
      "Do you know why any of the other days of the week are named the way they are?",
      "What is one thing you would like to learn about what happened two thousand years ago?"],
  h: ["이 책에서 바이킹 신 토르의 이름에서 나왔다고 하는 요일은 무엇인가요?",
      "다른 요일 이름이 왜 그렇게 지어졌는지 알고 있나요?",
      "이천 년 전에 있었던 일 중에 알고 싶은 것을 한 가지 적어 보세요."] };
ACT["S4116"] = { s: "Joe, Fred, and Sam find themselves whisked by The Book to the main ring-ball court in Chichen Itza, Mexico in 1000 A.D., where they must play for their lives against a Mayan High Priest who cheats.",
  q: ["Who do Joe, Fred, and Sam have to play a ring-ball game against?",
      "Have you ever played a game against someone who did not play fair? What happened?",
      "Would you want to play a game where the other side cheats, like in this story? Why or why not?"],
  h: ["조, 프레드, 샘이 고리공 경기를 벌여야 하는 상대는 누구인가요?",
      "공정하게 하지 않는 사람과 게임을 해 본 적이 있나요? 어떤 일이 있었나요?",
      "이 이야기처럼 상대가 반칙을 하는 게임을 하고 싶나요? 이유는 무엇인가요?"] };
ACT["S4117"] = { s: "A flock of sheep at Nicky's family's Australian ranch is losing all its wool, and no one knows why. Nicky and her friends the Thea Sisters head to Australia and set off on a tour of the whole country in search of clues.",
  q: ["What mysterious problem is happening to the sheep on Nicky's family's ranch?",
      "Have you ever tried to solve a mystery or figure out why something strange was happening? Tell about it.",
      "If you were one of the Thea Sisters searching for clues across Australia, what kind of clue would you hope to find first?"],
  h: ["니키네 가족 목장의 양들에게 일어나는 이상한 일은 무엇인가요?",
      "이상한 일이 왜 일어났는지 알아내려고 한 적이 있나요? 그 이야기를 해 보세요.",
      "테아 자매의 한 명으로 호주 곳곳에서 단서를 찾는다면, 가장 먼저 어떤 단서를 찾고 싶나요?"] };
ACT["S4118"] = { s: "This book presents more humorous episodes from the classroom on the 13th floor of Wayside School, including students learning to tango, facing the cafeteria's dreaded Mushroom Surprise, and more. Book #3",
  q: ["What food do the students dread in the cafeteria?",
      "What is your least favorite food at school or at home?",
      "Would you like to learn to tango like the students in this book? Why or why not?"],
  h: ["학생들이 급식실에서 무서워하는 음식은 무엇인가요?",
      "학교나 집에서 내가 가장 싫어하는 음식은 무엇인가요?",
      "이 책의 학생들처럼 탱고를 배우고 싶나요? 이유는 무엇인가요?"] };
ACT["S4119"] = { s: "In this book, the students in the classroom on the thirteenth-floor experience a series of unusual substitute teachers. Book #2",
  q: ["What kind of teachers do the students experience in this book?",
      "Have you ever had a substitute teacher? What was that day like?",
      "What would your dream substitute teacher be like?"],
  h: ["이 책에서 학생들이 만나는 선생님들은 어떤 선생님인가요?",
      "보결(대리) 선생님을 만난 적이 있나요? 그날은 어땠나요?",
      "내가 꿈꾸는 대리 선생님은 어떤 모습일까요?"] };
ACT["S4120"] = { s: "When an investigation into a series of mysterious deaths leads agents to an elite prep school for rebellious kids, MI6 assigns fourteen-year-old Alex who continues his work as a spy for the British to the case. Book #2",
  q: ["Why does MI6 assign fourteen-year-old Alex to investigate the prep school?",
      "Have you ever had to solve a problem or take on a big responsibility that felt too old for you? Describe what happened.",
      "Do you think a fourteen-year-old like Alex could really work as a spy? Explain your thinking."],
  h: ["MI6는 왜 열네 살인 알렉스에게 그 예비학교를 조사하도록 맡길까요?",
      "나이에 비해 너무 큰 책임이나 문제를 맡아 본 적이 있나요? 무슨 일이 있었는지 설명해 보세요.",
      "알렉스처럼 열네 살인 아이가 정말로 스파이로 일할 수 있을 것 같나요? 내 생각을 설명해 보세요."] };
ACT["S4121"] = { s: "You don't bring your rat to show-and-tell.  This book contains a humorous collection of poems about school. Guaranteed to tickle any kid's funny bone!",
  q: ["What does the title say you should not bring to show-and-tell?",
      "Have you ever had a show-and-tell at school? What did you bring or wish you could bring?",
      "This book is a collection of funny poems about school. What would you write a funny poem about?"],
  h: ["제목에서는 발표 시간에 무엇을 가져오면 안 된다고 하나요?",
      "학교에서 발표(쇼앤텔) 시간을 가져 본 적이 있나요? 무엇을 가져갔거나 가져가고 싶었나요?",
      "이 책은 학교에 대한 재미있는 시 모음이에요. 나라면 무엇에 대해 재미있는 시를 써 보고 싶나요?"] };
ACT["S4122"] = { s: "This book presents different kinds of magnets, how they work, and how they are used.",
  q: ["What three things does this book explain about magnets?",
      "Have you ever played with a magnet or seen one used somewhere? What did it do?",
      "What would you like to use a magnet for if you could invent your own magnetic tool?"],
  h: ["이 책은 자석에 대해 세 가지를 설명해요. 무엇인가요?",
      "자석을 가지고 놀아 보거나 어디에 쓰이는지 본 적이 있나요? 무엇을 했나요?",
      "내가 나만의 자석 도구를 만든다면 어디에 쓰고 싶나요?"] };
ACT["S4123"] = { s: "Nora Rowley is a fifth-grader who only wants to be considered normal. She always tries her best to hide the fact that she is a genius. Nora tries to prove that tests alone are a stupid way to measure intelligence. She also believes grades are not important.",
  q: ["Why does Nora try to hide the fact that she is a genius?",
      "Have you ever tried to hide a talent or something special about yourself so you could fit in? Explain.",
      "Do you agree with Nora that tests alone are not a good way to measure intelligence? Explain your opinion."],
  h: ["노라는 왜 자신이 천재라는 사실을 숨기려고 하나요?",
      "튀지 않으려고 나의 재능이나 특별한 점을 숨겨 본 적이 있나요? 설명해 보세요.",
      "시험만으로 똑똑함을 재는 것이 좋은 방법이 아니라는 노라의 생각에 동의하나요? 내 생각을 설명해 보세요."] };
ACT["S4124"] = { s: "In his letters to his favorite author, young Leigh reveals his problems in dealing with his parents' divorce, being the new boy in school, and generally finding his own place in the world.",
  q: ["What three problems does Leigh write about in his letters to his favorite author?",
      "Have you ever written a letter to someone about something that was bothering you? What did you write?",
      "Why do you think writing letters helps Leigh deal with his problems?"],
  h: ["리는 자신이 좋아하는 작가에게 쓴 편지에서 어떤 세 가지 문제에 대해 이야기하나요?",
      "속상한 일에 대해 누군가에게 편지를 써 본 적이 있나요? 무엇을 썼나요?",
      "편지를 쓰는 것이 리가 문제를 해결하는 데 왜 도움이 될까요?"] };
ACT["S4125"] = { s: "In a series of diary entries, Leigh tells how he comes to terms with his parents' divorce, and joins the track team at school.",
  q: ["What two things does Leigh write about in his diary entries?",
      "Have you ever kept a diary or journal? What kinds of things did you write about?",
      "How do you think joining the track team might help Leigh deal with his parents' divorce?"],
  h: ["리는 일기에서 어떤 두 가지에 대해 쓰나요?",
      "일기나 다이어리를 써 본 적이 있나요? 어떤 내용을 썼나요?",
      "육상팀에 들어간 것이 리가 부모님의 이혼을 받아들이는 데 어떻게 도움이 될 것 같나요?"] };
ACT["S4126"] = { s: "Four-year-old Ramona has an imagination that makes her a menace to everyone around her, particularly her older sister, nine-year-old Beezus.",
  q: ["Who does Ramona's wild imagination bother the most?",
      "Do you have a younger brother or sister, cousin, or friend with a big imagination? What do they do?",
      "Do you think having a big imagination like Ramona's is more of a good thing or a problem? Explain."],
  h: ["라모나의 엉뚱한 상상력이 가장 힘들게 하는 사람은 누구인가요?",
      "상상력이 풍부한 동생이나 사촌, 친구가 있나요? 그 아이는 어떤 행동을 하나요?",
      "라모나처럼 상상력이 풍부한 것이 좋은 점이 더 많을까요, 아니면 문제가 더 많을까요? 설명해 보세요."] };
ACT["S4127"] = { s: "Now that her daddy has a job, Ramona hopes that her mother will stop working. If Mrs. Quimby stays home again, Ramona won't have to stay with Howie's grandmother after school.",
  q: ["Why does Ramona hope her mother will stop working now?",
      "Have your parents ever both worked? How did that change your daily schedule?",
      "Do you think it's fair for Ramona to want her mother to stay home? Explain your opinion."],
  h: ["라모나는 왜 지금 엄마가 일을 그만두기를 바라나요?",
      "부모님이 두 분 다 일을 하신 적이 있나요? 그것이 내 하루 일과를 어떻게 바꾸었나요?",
      "라모나가 엄마가 집에 있기를 바라는 것이 공평하다고 생각하나요? 내 생각을 설명해 보세요."] };
ACT["S4128"] = { s: "Ramona is back and funnier than ever as she prepares for her aunt's wedding and the move her family might make.",
  q: ["What two big events is Ramona getting ready for in this book?",
      "Have you ever been to a wedding or helped a family member prepare for one? What was it like?",
      "How do you think Ramona feels about her family possibly moving? Explain your thinking."],
  h: ["이 책에서 라모나가 준비하고 있는 두 가지 큰 일은 무엇인가요?",
      "결혼식에 가 보거나 가족의 결혼 준비를 도와 본 적이 있나요? 어땠나요?",
      "가족이 이사할지도 모른다는 것에 대해 라모나는 어떤 기분일 것 같나요? 내 생각을 설명해 보세요."] };
ACT["S4129"] = { s: "Six-year-old Ramona tries to cope with an unkind first-grade teacher.",
  q: ["What is Ramona trying to cope with in this book?",
      "Have you ever had a teacher who was hard to get along with? How did you handle it?",
      "What advice would you give Ramona for dealing with her unkind teacher?"],
  h: ["이 책에서 라모나가 견뎌 내려고 애쓰는 것은 무엇인가요?",
      "함께 지내기 힘든 선생님을 만난 적이 있나요? 어떻게 해결했나요?",
      "불친절한 선생님 때문에 힘들어하는 라모나에게 어떤 조언을 해 주고 싶나요?"] };
ACT["S4130"] = { s: "This story follows the adventures of nine-year-old Ramona at home with her sisters, and at school in Mrs. Meacham's fourth grade class.",
  q: ["Where does this story follow Ramona's adventures?",
      "What is your own life like both at home with your family and at school with your class?",
      "If you could join Ramona for one day, would you rather spend it at her home or at her school? Explain."],
  h: ["이 이야기는 라모나의 모험을 어디에서 따라가나요?",
      "나의 생활은 집에서 가족과 있을 때, 그리고 학교에서 반 친구들과 있을 때 각각 어떤가요?",
      "하루 동안 라모나와 함께한다면 그녀의 집과 학교 중 어디를 선택하고 싶나요? 이유를 설명해 보세요."] };
ACT["S4131"] = { s: "Henry's life turns upside down when he meets a lovable puppy with a nose for mischief. He names the dog Ribsy, and the two become inseparable. But Henry faces the possibility of losing his new best friend when Ribsy's original owner appears and tries to reclaim his dog.",
  q: ["What name does Henry give the puppy he meets?",
      "Have you ever met an animal that you instantly loved? What happened?",
      "How do you think Henry feels when Ribsy's original owner tries to reclaim the dog? Explain your thinking."],
  h: ["헨리가 만난 강아지에게 지어 준 이름은 무엇인가요?",
      "만나자마자 사랑에 빠진 동물이 있었나요? 무슨 일이 있었나요?",
      "립시의 원래 주인이 나타나 개를 데려가려고 할 때 헨리는 어떤 기분일 것 같나요? 내 생각을 설명해 보세요."] };
ACT["S4132"] = { s: "Henry tries anything to get the bike of his dreams, but every idea keeps falling flat. But anything is possible with the help of his best friend, Beezus.",
  q: ["What does Henry try many different ideas to get?",
      "Have you ever tried many different plans to get something you really wanted? What happened?",
      "Why do you think having a best friend like Beezus helps Henry in the end?"],
  h: ["헨리가 여러 가지 방법을 시도하며 얻으려고 하는 것은 무엇인가요?",
      "정말 갖고 싶은 것을 얻으려고 여러 계획을 시도해 본 적이 있나요? 어떻게 됐나요?",
      "비저스 같은 가장 친한 친구가 있다는 것이 왜 결국 헨리에게 도움이 될까요?"] };
ACT["S4133"] = { s: "In this novel, Henry asks his dad if he can go along on the big fishing trip, and Mr. Huggins agrees on one condition that Ribsy must stay out of mischief for the two whole months.",
  q: ["What condition does Henry's dad set before Henry can go on the fishing trip?",
      "Have your parents ever set a condition before you could do something you wanted? What was it?",
      "Do you think it will be easy or hard for Ribsy to stay out of mischief for two months? Explain."],
  h: ["낚시 여행을 가기 전에 헨리의 아빠가 내건 조건은 무엇인가요?",
      "부모님이 내가 원하는 것을 하기 전에 조건을 내건 적이 있나요? 무엇이었나요?",
      "립시가 두 달 동안 말썽을 피우지 않는 것이 쉬울까요, 어려울까요? 설명해 보세요."] };
ACT["S4134"] = { s: "Abigail and her friends have to find Sacagawea, figure out what her dream is, and convince her to stick with it, -- all in just two hours.",
  q: ["What three things do Abigail and her friends have to do in just two hours?",
      "Have you ever had to finish something important in a very short amount of time? Describe what happened.",
      "Why do you think it might be hard to convince someone to stick with their dream?"],
  h: ["애비게일과 친구들이 단 두 시간 안에 해내야 하는 세 가지 일은 무엇인가요?",
      "아주 짧은 시간 안에 중요한 일을 끝내야 했던 적이 있나요? 무슨 일이 있었는지 설명해 보세요.",
      "누군가에게 자신의 꿈을 포기하지 말라고 설득하는 일이 왜 어려울 수 있을까요?"] };
ACT["S4135"] = { s: "Abigail and her friends travel back in time to meet General George Washington. They try to convince the general to continue fighting the Revolutionary War in Valley Forge.",
  q: ["Who do Abigail and her friends travel back in time to meet?",
      "Have you ever had to convince someone to keep trying at something hard? What did you say?",
      "Why do you think it might have been difficult for General Washington to keep fighting at Valley Forge?"],
  h: ["애비게일과 친구들이 과거로 가서 만나는 사람은 누구인가요?",
      "누군가에게 힘든 일을 포기하지 말고 계속하라고 설득해 본 적이 있나요? 무슨 말을 했나요?",
      "밸리 포지에서 워싱턴 장군이 계속 싸우는 것이 왜 힘들었을 것 같나요?"] };
ACT["S4136"] = { s: "Abigail and her friends travel back in time to meet Betsy Ross. They must stop Babs Magee from taking credit for sewing the first American flag.",
  q: ["What must Abigail and her friends stop Babs Magee from doing?",
      "Has anyone ever tried to take credit for something you did? How did that feel?",
      "Why do you think it is important to give credit to the person who really did the work?"],
  h: ["애비게일과 친구들은 밥스 마기가 하려는 어떤 일을 막아야 하나요?",
      "누군가 내가 한 일의 공을 가로채려고 한 적이 있나요? 그때 기분이 어땠나요?",
      "실제로 그 일을 한 사람에게 공을 돌리는 것이 왜 중요할까요?"] };
ACT["S4137"] = { s: "A wire-haired dachshund puppy named Howie is mysteriously invited to attend the Dogwiz Academy for Canine Conjurers. Together, Howie and his best friend Delilah discover that they must fight a sinister foe, The-Evil-Force-Whose-Nam-C'not-Be-Spoke!",
  q: ["What kind of school is Howie mysteriously invited to attend?",
      "Have you ever received a surprising or mysterious invitation to something? What was it?",
      "Would you want to attend a school for magic like Howie's academy? Why or why not?"],
  h: ["하위가 신비롭게 초대받아 다니게 되는 학교는 어떤 학교인가요?",
      "놀랍거나 신비한 초대를 받아 본 적이 있나요? 무엇이었나요?",
      "하위가 다니는 것 같은 마법 학교에 다니고 싶나요? 이유는 무엇인가요?"] };
ACT["S4138"] = { s: "Daisy, the newest member of Alphabet Club, is desperate to fit in and get along with the girls in the club. When Daisy's birthday comes around, the girls plan elaborate sleepover parties at her house. Daisy dreads the time as she doesn't know what her friends will make of sleeping over at her home, with her rather special older sister.",
  q: ["Why does Daisy dread the sleepover parties her friends plan for her birthday?",
      "Have you ever worried about what friends would think if they came to your house? What did you worry about?",
      "What advice would you give Daisy about introducing her friends to her special older sister?"],
  h: ["데이지는 왜 친구들이 계획한 생일 파티가 걱정되나요?",
      "친구들이 우리 집에 왔을 때 어떻게 생각할지 걱정해 본 적이 있나요? 무엇이 걱정되었나요?",
      "특별한 언니를 친구들에게 소개하는 것에 대해 데이지에게 어떤 조언을 해 주고 싶나요?"] };
ACT["S4139"] = { s: "Nine-year-old Sadie's Mum is a childminder. When her Mum gets the flu, Sadie gets the chance to mind her and help with all the babies!",
  q: ["What job does Sadie's mum have?",
      "Have you ever had to take on a grown-up's job or responsibility for a while? What did you do?",
      "Do you think it would be fun or hard to help take care of babies like Sadie does? Explain."],
  h: ["세이디 엄마의 직업은 무엇인가요?",
      "잠시라도 어른의 일이나 책임을 맡아 본 적이 있나요? 무엇을 했나요?",
      "세이디처럼 아기들을 돌보는 것이 재미있을까요, 힘들까요? 설명해 보세요."] };
ACT["S4140"] = { s: "In January 1916, Henry Yewbeam, who has been sent to the Bloor's Academy, disappears when he rolls his marbles. Charlie is shocked when Henry appears, twisted through time from the icy winter of 1916.",
  q: ["What is Henry Yewbeam doing when he disappears in 1916?",
      "Have you ever been shocked when something unexpected suddenly happened? Describe it.",
      "If someone from a hundred years ago suddenly appeared in front of you like Henry, what would you want to ask them first?"],
  h: ["1916년 헨리 유빔이 사라질 때 그는 무엇을 하고 있었나요?",
      "예상하지 못한 일이 갑자기 벌어져서 놀란 적이 있나요? 그 일을 설명해 보세요.",
      "헨리처럼 백 년 전 사람이 갑자기 내 앞에 나타난다면 가장 먼저 무엇을 물어보고 싶나요?"] };
ACT["S4141"] = { s: "It's the summer semester at Bloors, and Charlie Bone gets into more trouble. A mysterious pretty girl named Belle is plotting against him, and a strange invisible boy named Ollie Sparks seems to be in danger. Charlie and his friends plan to save Ollie's life.",
  q: ["Who is plotting against Charlie Bone this summer semester?",
      "Have you ever helped a friend who was in danger or trouble? What did you do?",
      "Why do you think Charlie and his friends decide to help Ollie even though it might be risky?"],
  h: ["이번 여름 학기에 찰리 본에게 음모를 꾸미는 사람은 누구인가요?",
      "위험하거나 곤란한 상황에 처한 친구를 도와준 적이 있나요? 무엇을 했나요?",
      "위험할 수 있는데도 찰리와 친구들이 올리를 돕기로 한 이유는 무엇일까요?"] };
ACT["S4142"] = { s: "In this book, Charlie, his relatives, and friends cooperate to rescue Billy Raven, a young orphan from a child-hating couple who have adopted him. They are pressuring Billy to sign an oath of obedience.",
  q: ["What are Billy Raven's adoptive parents pressuring him to sign?",
      "Have you ever worked together with others to help someone who needed rescuing? What did you do?",
      "Why do you think it is wrong for the couple to pressure Billy to sign an oath of obedience?"],
  h: ["빌리 레이븐의 양부모가 그에게 서명하라고 압박하는 것은 무엇인가요?",
      "도움이 필요한 누군가를 구하기 위해 다른 사람들과 힘을 합친 적이 있나요? 무엇을 했나요?",
      "그 부부가 빌리에게 복종 서약에 서명하라고 압박하는 것이 왜 잘못됐다고 생각하나요?"] };
ACT["S4143"] = { s: "On the day Charlie turns twelve, the Flame Cats give him a grave warning that he must be watchful of an ancient enchanter released from the grounds of Bloor’s Academy. Finding the Red King is the only way Charlie and his friends can defeat him.",
  q: ["What warning do the Flame Cats give Charlie on his twelfth birthday?",
      "Have you ever received an important warning from someone? What was it about?",
      "Why do you think finding the Red King is the only way Charlie and his friends can defeat the enchanter?"],
  h: ["화염 고양이들이 찰리의 열두 번째 생일에 주는 경고는 무엇인가요?",
      "누군가로부터 중요한 경고를 받아 본 적이 있나요? 무엇에 대한 경고였나요?",
      "붉은 왕을 찾는 것이 왜 찰리와 친구들이 마법사를 이길 유일한 방법일까요?"] };
ACT["S4144"] = { s: "It's report card day that Hank dreads the most in his school year. He accidentally gets his report card with Ds ground in a meat grinder at Mom's deli. The meat with Hank's report card is being made into a big salami for a very important client. How will Hank Zipzer get out of this one? #2",
  q: ["What accidentally happens to Hank's report card at his mom's deli?",
      "Have you ever dreaded getting a report card or test back? How did you feel waiting for it?",
      "How do you think Hank could get out of this salami problem? Share your own idea."],
  h: ["엄마의 델리 가게에서 행크의 성적표에 우연히 무슨 일이 일어나나요?",
      "성적표나 시험지를 받는 것이 두려웠던 적이 있나요? 기다리는 동안 기분이 어땠나요?",
      "행크가 이 살라미 문제를 어떻게 해결할 수 있을까요? 내 생각을 말해 보세요."] };
ACT["S4145"] = { s: "Hank doesn't like his sister's pet iguana. When it lays its eggs inside his science project, their relationship worsens. Book #3",
  q: ["What does the iguana do inside Hank's science project?",
      "Has a pet or sibling ever ruined something you were working on? What happened?",
      "How do you think Hank and his sister could make their relationship better after this problem?"],
  h: ["이구아나가 행크의 과학 프로젝트 안에서 하는 일은 무엇인가요?",
      "반려동물이나 형제자매가 내가 하던 일을 망친 적이 있나요? 무슨 일이 있었나요?",
      "이 문제 이후 행크와 여동생의 사이가 좋아지려면 어떻게 하면 좋을까요?"] };
ACT["S4146"] = { s: "This abridged edition follows the life of the famous horse, Black Beauty. As he moves from owner to owner, he encounters new experiences and new friends who reveal their histories.",
  q: ["What happens to Black Beauty again and again throughout his life?",
      "Have you ever had to get used to a new place or new people, like Black Beauty moving to new owners? Describe it.",
      "Why do you think the new friends Black Beauty meets each have their own histories to reveal?"],
  h: ["블랙 뷰티의 삶에서 계속 반복되는 일은 무엇인가요?",
      "블랙 뷰티가 새 주인에게 가듯, 새로운 장소나 사람들에게 적응해야 했던 적이 있나요? 그 경험을 설명해 보세요.",
      "블랙 뷰티가 만나는 새 친구들이 저마다 자기 이야기를 가지고 있는 이유는 무엇일까요?"] };
ACT["S4147"] = { s: "This abridged edition shares the joys and sorrows of the four March sisters as they grow into young women in mid-nineteenth-century New England.",
  q: ["How many March sisters does this book follow as they grow up?",
      "Do you have sisters or close friends who share both joys and sorrows with you? Describe your relationship.",
      "What do you think might be some of the joys and sorrows the March sisters share as they grow up?"],
  h: ["이 책은 몇 명의 마치 자매가 자라나는 이야기를 따라가나요?",
      "기쁨과 슬픔을 함께 나누는 자매나 가까운 친구가 있나요? 그 관계를 설명해 보세요.",
      "마치 자매들이 자라면서 겪을 기쁨과 슬픔에는 어떤 것들이 있을 것 같나요?"] };
ACT["S4148"] = { s: "This abridged edition shares the legend of Robin Hood, who robbed from the rich and gave to the poor.",
  q: ["What did Robin Hood do with what he took from the rich?",
      "Have you ever given something of yours to someone who needed it more? What did you give?",
      "Do you think what Robin Hood did was right, even though stealing is against the law? Explain your opinion."],
  h: ["로빈 후드는 부자에게서 빼앗은 것을 어떻게 했나요?",
      "내가 가진 것을 더 필요한 사람에게 준 적이 있나요? 무엇을 주었나요?",
      "도둑질은 법을 어기는 일인데도, 로빈 후드가 한 일이 옳았다고 생각하나요? 내 생각을 설명해 보세요."] };
ACT["S4149"] = { s: "This abridged edition retells how the detective Sherlock Holmes solves several mysteries with the help of his friend, Dr. John Watson.",
  q: ["Who helps Sherlock Holmes solve the mysteries in this book?",
      "Have you ever worked with a friend to solve a puzzle or figure something out? Describe what happened.",
      "What do you think makes a good detective? Explain your thinking."],
  h: ["이 책에서 셜록 홈즈가 사건을 해결하도록 돕는 사람은 누구인가요?",
      "친구와 함께 퍼즐을 풀거나 무언가를 알아낸 적이 있나요? 무슨 일이 있었는지 설명해 보세요.",
      "훌륭한 탐정이 되려면 무엇이 필요할까요? 내 생각을 설명해 보세요."] };
ACT["S4150"] = { s: "This abridged edition shares the adventures of Tom and his friends growing up in a small Missouri town in the 19th century.",
  q: ["Where do Tom and his friends grow up in this book?",
      "What is your own town or neighborhood like? Describe a favorite spot where you and your friends play.",
      "What kind of adventure do you think would be fun to have with your friends, like Tom does in this book?"],
  h: ["이 책에서 톰과 친구들이 자라는 곳은 어디인가요?",
      "내가 사는 동네는 어떤 모습인가요? 나와 친구들이 즐겨 노는 곳을 설명해 보세요.",
      "이 책 속 톰처럼 친구들과 함께 해 보면 재미있을 모험은 어떤 것일까요?"] };
ACT["S4151"] = { s: "This book is an abridged edition of the science fiction novel, The Time Machine. A scientist invents the time machine and uses it to travel to the year 802701 A.D. There, he discovers the childlike Eloi and the hideous underground Morlocks.",
  q: ["What two groups does the scientist discover in the year 802701 A.D.?",
      "If you invented a time machine, what year would you travel to and why?",
      "Why do you think the future the scientist finds has two very different groups living above and below ground?"],
  h: ["과학자가 서기 802701년에 발견하는 두 무리는 누구인가요?",
      "내가 타임머신을 발명한다면 몇 년도로 가고 싶고, 이유는 무엇인가요?",
      "과학자가 발견한 미래에 땅 위와 땅 아래에 서로 다른 두 무리가 사는 이유는 무엇일까요?"] };
ACT["S4152"] = { s: "Clementine is having a disastrous week. After Clementine cuts off Margaret's hair, she is sent to the principal's office, and her mother is mad at her. After a few days, even Margaret stops speaking to her. Will she find a way to make it better?",
  q: ["What does Clementine do that starts her disastrous week?",
      "Have you ever made a mistake that caused a lot of trouble? How did you try to fix it?",
      "What do you think Clementine could do to make things better with Margaret?"],
  h: ["클레멘타인의 끔찍한 한 주가 시작되게 만든 그녀의 행동은 무엇인가요?",
      "큰 말썽을 일으킨 실수를 해 본 적이 있나요? 어떻게 해결하려고 했나요?",
      "클레멘타인이 마가렛과의 사이를 다시 좋게 만들려면 어떻게 해야 할까요?"] };
ACT["S4153"] = { s: "This book presents unique plants that poison and eat insects.",
  q: ["What two things do the unique plants in this book do to insects?",
      "Have you ever seen or heard of a plant that eats insects? What do you know about it?",
      "Why do you think some plants evolved to poison and eat insects instead of just making food from sunlight?"],
  h: ["이 책에 나오는 특이한 식물들은 곤충에게 어떤 두 가지 일을 하나요?",
      "곤충을 잡아먹는 식물을 보거나 들어 본 적이 있나요? 무엇을 알고 있나요?",
      "어떤 식물들이 햇빛으로 양분을 만드는 대신 곤충을 독으로 마비시키고 잡아먹도록 진화한 이유는 무엇일까요?"] };
ACT["S4154"] = { s: "A little girl named Fern and a beautiful grey spider struggle to save a pig from being butchered. This tender novel tells of friendship, love, life, and death.",
  q: ["What are Fern and the spider trying to save the pig from?",
      "Have you ever tried hard to protect or save something you cared about? Describe what happened.",
      "This story is about friendship, love, life, and death. Which of these do you think is most important in the story, and why?"],
  h: ["펀과 거미는 돼지를 무엇으로부터 구하려고 애쓰나요?",
      "내가 아끼는 것을 지키거나 구하려고 애써 본 적이 있나요? 무슨 일이 있었는지 설명해 보세요.",
      "이 이야기는 우정, 사랑, 삶, 죽음에 대해 이야기해요. 이 중 이야기에서 가장 중요하다고 생각하는 것은 무엇이고, 이유는 무엇인가요?"] };
ACT["S4155"] = { s: "Louis, the Trumpeter Swan, lacks a voice. Since he can't trumpet his love, the beautiful swan Serena pays no attention to him. To help Louis win his love, his dad steals him an authentic brass trumpet. Will the musical instrument help Louis?",
  q: ["Why does Louis's father steal him a brass trumpet?",
      "Have you ever had trouble expressing how you felt to someone? What did you do about it?",
      "Do you think the trumpet will really help Louis win Serena's attention? Explain your prediction."],
  h: ["루이스의 아빠는 왜 그에게 놋쇠 트럼펫을 훔쳐다 주나요?",
      "누군가에게 내 마음을 표현하기 어려웠던 적이 있나요? 그때 어떻게 했나요?",
      "트럼펫이 정말로 루이스가 세레나의 관심을 얻는 데 도움이 될 것 같나요? 내 예상을 설명해 보세요."] };
ACT["S4156"] = { s: "The twins, James and Laura, move to Connecticut with their family. After discovering an old well that seems magical in their backyard, they begin a series of unusual adventures.",
  q: ["What do James and Laura discover in their backyard after moving to Connecticut?",
      "Have you ever moved to a new place or explored a new backyard or neighborhood? What did you find?",
      "Do you think the well is really magical, or do you think there could be another explanation? Explain your thinking."],
  h: ["코네티컷으로 이사한 뒤 제임스와 로라가 뒷마당에서 발견하는 것은 무엇인가요?",
      "새로운 곳으로 이사했거나 새로운 뒷마당이나 동네를 탐험해 본 적이 있나요? 무엇을 발견했나요?",
      "그 우물이 정말 마법일까요, 아니면 다른 이유가 있을까요? 내 생각을 설명해 보세요."] };
ACT["S4157"] = { s: "The people of Ember escapes and they are given a safe haven in a small village called Sparks. New darkness lurks as tempers escalate between the two struggling groups, the people of Ember and Sparks. Will Lina and Doon successfully work together to avoid a disaster for everyone?",
  q: ["What village gives the people of Ember a safe haven?",
      "Have you ever seen two groups of people disagree or have trouble getting along? What happened?",
      "What do you think Lina and Doon could do to help the two groups avoid disaster?"],
  h: ["엠버 사람들에게 안전한 피난처를 주는 마을은 어디인가요?",
      "두 무리가 서로 갈등을 겪거나 잘 지내지 못하는 것을 본 적이 있나요? 무슨 일이 있었나요?",
      "리나와 둔이 두 무리가 재앙을 피하도록 도우려면 무엇을 할 수 있을까요?"] };
ACT["S4158"] = { s: "When her mom says every mad scientist needs a lab assistant, she gets Igor, a dog of many breeds, for her new assistant on Valentine's Day. But things get worse when Igor accidentally lets loose a giant, fifty-foot, arrow-shooting cupid. Book #2",
  q: ["What does Igor accidentally let loose on Valentine's Day?",
      "Have you or someone you know ever had an accident while helping with a project? What happened?",
      "If a fifty-foot cupid were loose in your neighborhood, what do you think would happen?"],
  h: ["밸런타인데이에 이고르가 실수로 풀어놓는 것은 무엇인가요?",
      "나나 내가 아는 사람이 프로젝트를 돕다가 실수를 한 적이 있나요? 무슨 일이 있었나요?",
      "50피트짜리 큐피드가 우리 동네에 풀려난다면 무슨 일이 벌어질 것 같나요?"] };
ACT["S4159"] = { s: "Franny K. Stein attempts to go back in time to change her name since her embarrassing middle name is revealed in front of the whole school at the Science Fair award ceremony. Book #4",
  q: ["Why does Franny try to go back in time to change her name?",
      "Has something about you ever been embarrassingly revealed in front of others? How did you feel?",
      "Do you think going back in time is a good way for Franny to solve her problem? Why or why not?"],
  h: ["프래니는 왜 과거로 돌아가 자신의 이름을 바꾸려고 하나요?",
      "나에 대한 무언가가 다른 사람들 앞에서 창피하게 드러난 적이 있나요? 그때 기분이 어땠나요?",
      "과거로 돌아가는 것이 프래니의 문제를 해결하는 좋은 방법이라고 생각하나요? 이유는 무엇인가요?"] };
ACT["S4160"] = { s: "When Igor, Franny's faithful lab assistant, swallows the Doomsday Device, Franny K. Stein shrinks herself with her miniaturization machine and goes into the body of a ticking time-dog! Book #5",
  q: ["What does Franny do after Igor swallows the Doomsday Device?",
      "Have you ever had to act fast to fix a big problem? What did you do?",
      "How do you think Franny feels while she is shrunk down inside Igor's body?"],
  h: ["이고르가 종말 장치를 삼킨 뒤 프래니는 무엇을 하나요?",
      "큰 문제를 해결하기 위해 빠르게 행동해야 했던 적이 있나요? 무엇을 했나요?",
      "이고르의 몸속에서 작아져 있는 동안 프래니는 어떤 기분일 것 같나요?"] };
ACT["S4161"] = { s: "To get all her tasks done, such as creating monsters and dealing with overgrown babies, mad scientist Franny decides to invent Franbots. She starts an experiment to make copies of herself. Book #6",
  q: ["What does Franny invent to help her get all her tasks done?",
      "Have you ever wished you had a copy of yourself to help get things done? What would you have your copy do?",
      "What problems do you think could happen if Franny makes copies of herself?"],
  h: ["프래니는 자신의 모든 일을 끝내기 위해 무엇을 발명하나요?",
      "내 복제품이 있어서 일을 도와주면 좋겠다고 생각해 본 적이 있나요? 있다면 그 복제품에게 무엇을 시키고 싶나요?",
      "프래니가 자기 복제품을 만들면 어떤 문제가 생길 수 있을까요?"] };
ACT["S4162"] = { s: "A British schoolboy named Tim travels to a dangerous foreign country to return a small dog found on the street to its rightful owner. Book #1",
  q: ["Why does Tim travel to a dangerous foreign country?",
      "Have you ever found a lost animal? What did you do to help it?",
      "Do you think it is worth taking a big risk to return a dog to its rightful owner, like Tim does? Explain your opinion."],
  h: ["팀은 왜 위험한 외국으로 여행을 떠나나요?",
      "길을 잃은 동물을 발견한 적이 있나요? 그 동물을 돕기 위해 무엇을 했나요?",
      "팀처럼 개를 원래 주인에게 돌려주기 위해 큰 위험을 감수할 가치가 있다고 생각하나요? 내 생각을 설명해 보세요."] };
ACT["S4163"] = { s: "In New York City, Tim and his dog Grk seek to discover who stole the Golden Dachshund from the National Museum. Book #3",
  q: ["What was stolen from the National Museum in this book?",
      "Have you ever tried to figure out who did something, like solving a small mystery? Describe it.",
      "What clues do you think Tim and Grk might look for to find out who stole the Golden Dachshund?"],
  h: ["이 책에서 국립 박물관에서 도난당한 것은 무엇인가요?",
      "누가 어떤 일을 했는지 알아내려고 한 적이 있나요? 그 이야기를 해 보세요.",
      "황금 닥스훈트를 훔친 사람을 찾기 위해 팀과 그크는 어떤 단서를 찾을 것 같나요?"] };
ACT["S4164"] = { s: "In the jungles of Brazil, as they pursue a gang of escaped bank robbers, twelve-year-old Tim and his dog, Grk, face kidnapping, a plane crash, and more.  Book #2",
  q: ["What three dangers do Tim and Grk face while chasing the gang of bank robbers?",
      "Have you ever felt scared while trying to do something brave? Describe that time.",
      "Would you want to go on a dangerous chase through the jungle like Tim and Grk? Why or why not?"],
  h: ["은행 강도 무리를 쫓는 동안 팀과 그크가 겪는 세 가지 위험은 무엇인가요?",
      "용감한 일을 하려고 애쓰면서 무서웠던 적이 있나요? 그때를 설명해 보세요.",
      "팀과 그크처럼 정글에서 위험한 추격전을 벌이고 싶나요? 이유는 무엇인가요?"] };
ACT["S4165"] = { s: "Gemma and Alice, who share the same birthday, have been best friends forever. When Gemma hears the news that Alice is moving far away to Scotland, she is distraught.",
  q: ["What news makes Gemma distraught?",
      "Has a close friend of yours ever moved away? How did you feel about it?",
      "What do you think Gemma and Alice could do to stay close even after Alice moves to Scotland?"],
  h: ["젬마를 몹시 슬프게 만드는 소식은 무엇인가요?",
      "친한 친구가 멀리 이사 간 적이 있나요? 그때 기분이 어땠나요?",
      "앨리스가 스코틀랜드로 이사한 뒤에도 젬마와 앨리스가 계속 친하게 지내려면 어떻게 하면 좋을까요?"] };
ACT["S4166"] = { s: "Elsa's family loses their lovely house and moves into a bed and breakfast hotel. Despite her effort to encourage her family by telling jokes, no one seems to feel better.",
  q: ["How does Elsa try to encourage her family after they lose their house?",
      "Have you ever tried to cheer up your family or friends during a hard time? What did you do?",
      "Why do you think jokes are not enough to make Elsa's family feel better?"],
  h: ["집을 잃은 뒤 엘사는 가족을 어떻게 격려하려고 하나요?",
      "힘든 시기에 가족이나 친구를 위로하려고 해 본 적이 있나요? 무엇을 했나요?",
      "농담만으로는 엘사의 가족 기분이 나아지지 않는 이유는 무엇일까요?"] };
ACT["S4167"] = { s: "Charlie is starting a new school year, and her new teacher assigns a challenging school project on the uninteresting Victorian period. But her research and imagination lead to some intriguing discoveries.",
  q: ["What time period does Charlie's new project have to be about?",
      "Have you ever done a school project on a topic that seemed boring at first? What did you discover?",
      "Why do you think research and imagination together can turn a boring topic into something interesting?"],
  h: ["찰리의 새 프로젝트는 어느 시대에 대한 것이어야 하나요?",
      "처음에는 지루해 보이는 주제로 학교 프로젝트를 해 본 적이 있나요? 무엇을 알게 되었나요?",
      "조사와 상상력이 함께하면 왜 지루한 주제도 흥미롭게 바뀔 수 있을까요?"] };
ACT["S4168"] = { s: "This book contains six wonderful short stories about Mr. Speed’s class members and their special website called Worry Website. On this website, everyone can type in their worries anonymously and receive advice from their peers.",
  q: ["What can students do anonymously on the Worry Website?",
      "If you could post a worry anonymously and get advice from classmates, what worry would you post?",
      "Do you think it helps to share worries with others, even when they don't know it's you? Explain your opinion."],
  h: ["학생들은 걱정 웹사이트에서 이름을 밝히지 않고 무엇을 할 수 있나요?",
      "이름을 밝히지 않고 걱정을 올려서 친구들에게 조언을 받을 수 있다면 나는 어떤 걱정을 올리고 싶나요?",
      "누가 썼는지 몰라도 걱정을 다른 사람들과 나누는 것이 도움이 된다고 생각하나요? 내 생각을 설명해 보세요."] };
ACT["S4169"] = { s: "Streaker is no ordinary dog. Trevor has to train the dog until the end of the holidays. If he fails and loses his bet with Charlie, then something very, very yucky will happen.",
  q: ["What does Trevor have to do with Streaker before the end of the holidays?",
      "Have you ever made a bet or a challenge with a friend? What happened?",
      "What do you think Trevor could do to make sure he wins his bet with Charlie?"],
  h: ["트레버는 방학이 끝나기 전에 스트리커와 관련해 무엇을 해야 하나요?",
      "친구와 내기나 도전을 해 본 적이 있나요? 어떻게 됐나요?",
      "트레버가 찰리와의 내기에서 이기려면 무엇을 하면 좋을까요?"] };
ACT["S4170"] = { s: "It's time for the annual Olympiad: the most anticipated day of the school year! Hank Zipzer is chosen as a pitcher for the softball team, but he thinks he's the worst athlete in the history of the world. Can Hank overcome the pressure and lead his team to victory? Book #4",
  q: ["What position is Hank chosen for on the softball team?",
      "Have you ever been chosen for something important even though you doubted yourself? What happened?",
      "What do you think Hank could do to overcome the pressure he feels?"],
  h: ["행크는 소프트볼 팀에서 어떤 포지션으로 뽑히나요?",
      "스스로를 의심했지만 중요한 일을 맡게 된 적이 있나요? 무슨 일이 있었나요?",
      "행크가 느끼는 부담감을 이겨내려면 어떻게 하면 좋을까요?"] };
ACT["S4171"] = { s: "No matter how hard he tries, Joey can't sit still for more than a minute. A lot of times, he ends up bouncing around. Joey often makes wrong choices. Everyone knows that he is a great kid, but hardly anyone knows what he's going to do next. But he is determined not to bring constant disappointment to his mother and his teachers. Book #1",
  q: ["What is Joey determined not to keep bringing to his mother and teachers?",
      "Have you ever tried hard not to disappoint someone even though it was difficult? Describe what happened.",
      "Why do you think people know Joey is a great kid even though he often makes wrong choices?"],
  h: ["조이는 엄마와 선생님들에게 계속 무엇을 안겨 주지 않으려고 굳게 결심하나요?",
      "힘들었지만 누군가를 실망시키지 않으려고 애써 본 적이 있나요? 무슨 일이 있었는지 설명해 보세요.",
      "조이가 자주 잘못된 선택을 하는데도 사람들이 그를 좋은 아이라고 아는 이유는 무엇일까요?"] };
ACT["S4172"] = { s: "Joey, who has trouble controlling himself, is taking medication to keep him from going off too far. When they spend the summer together, his dad insists that Joey should stop taking his medication. And Joey ends up losing control when he tries to help his baseball team. Book #2",
  q: ["What does Joey's dad insist that Joey should stop doing during the summer?",
      "Have you ever disagreed with a grown-up about what was best for you? What happened?",
      "Why do you think it might be risky for Joey to stop taking his medication?"],
  h: ["여름 동안 아빠는 조이에게 무엇을 그만하라고 고집하나요?",
      "어른과 나에게 무엇이 최선인지에 대해 의견이 달랐던 적이 있나요? 무슨 일이 있었나요?",
      "조이가 약 먹는 것을 그만두는 것이 왜 위험할 수 있을까요?"] };
ACT["S4173"] = { s: "Matty's Village, which once welcomed newcomers, votes to close it to outsiders after something sinister seeps into it. And now Matty must risk everything to make his last journey through the treacherous forest. This is a masterful third novel in the Giver Quartet.",
  q: ["What does Matty's Village vote to do after something sinister seeps into it?",
      "Have you ever had to risk something to help other people? Describe what happened.",
      "Why do you think a village that once welcomed newcomers would change and close itself off?"],
  h: ["무언가 불길한 것이 스며든 뒤 매티의 마을은 무엇을 하기로 투표하나요?",
      "다른 사람들을 돕기 위해 무언가를 무릅써 본 적이 있나요? 무슨 일이 있었는지 설명해 보세요.",
      "낯선 이들을 반갑게 맞이하던 마을이 왜 문을 닫아 버리게 되었을까요?"] };
ACT["S4174"] = { s: "During the German occupation of Denmark, the Jews of Denmark are being relocated, so is ten-year-old Annemarie's best friend, Ellen. To help Ellen's family escape from the Nazis, Annemarie takes courage and goes on a life-risking mission.",
  q: ["Why does Annemarie go on a life-risking mission?",
      "Have you ever had to be brave to help a close friend? What did you do?",
      "Why do you think Annemarie's friendship with Ellen gives her the courage to take such a big risk?"],
  h: ["애너마리는 왜 목숨을 건 임무를 떠나나요?",
      "가까운 친구를 돕기 위해 용기를 내야 했던 적이 있나요? 무엇을 했나요?",
      "엘렌과의 우정이 애너마리에게 그런 큰 위험을 감수할 용기를 주는 이유는 무엇일까요?"] };
ACT["S4175"] = { s: "On their way home, Elmer and a flying dragon land on an island and help some canaries uncover a buried treasure.",
  q: ["What do Elmer and the flying dragon help the canaries do on the island?",
      "Have you ever helped someone search for something they had lost or wanted to find? Describe it.",
      "What kind of buried treasure would you most like to find on an island like this?"],
  h: ["엘머와 하늘을 나는 용은 섬에서 카나리아들이 무엇을 하도록 돕나요?",
      "누군가 잃어버렸거나 찾고 싶어 하는 것을 찾도록 도와준 적이 있나요? 그 일을 설명해 보세요.",
      "이런 섬에서 발견한다면 어떤 보물을 가장 찾고 싶나요?"] };
ACT["S4176"] = { s: "Elmer saves the dragon's family from hunters.",
  q: ["Who does Elmer save the dragon's family from?",
      "Have you ever helped protect an animal or its family from danger? What did you do?",
      "Why do you think Elmer is willing to risk helping the dragon's family?"],
  h: ["엘머는 용의 가족을 누구로부터 구해 주나요?",
      "동물이나 그 가족을 위험으로부터 지켜 준 적이 있나요? 무엇을 했나요?",
      "엘머가 위험을 무릅쓰고 용의 가족을 도와주려는 이유는 무엇일까요?"] };
ACT["S4177"] = { s: "To a thirteen-year-old Vermont farm boy whose father slaughters pigs for a living, maturity comes early as he learns 'doing what's got to be done.'",
  q: ["What does the thirteen-year-old boy's father do for a living?",
      "Have you ever had to do something difficult just because it needed to be done? Describe what happened.",
      "What do you think it means to learn 'doing what's got to be done' at such a young age?"],
  h: ["이 열세 살 소년의 아빠는 생계를 위해 어떤 일을 하나요?",
      "꼭 해야 하기 때문에 힘든 일을 해 본 적이 있나요? 무슨 일이 있었는지 설명해 보세요.",
      "이렇게 어린 나이에 '해야 할 일을 하는 것'을 배운다는 것은 어떤 의미일까요?"] };
ACT["S4178"] = { s: "Meg Murry and her family receive a surprise visit from a weird stranger out of another dimension in time.",
  q: ["Who visits Meg Murry and her family from another dimension in time?",
      "Have you ever had a surprise visitor who changed your day? Describe what happened.",
      "If a stranger from another dimension suddenly visited you, what would you want to ask them?"],
  h: ["메그 머리와 그녀의 가족을 다른 시공간에서 찾아온 손님은 누구인가요?",
      "예상치 못한 손님이 찾아와 하루가 달라진 적이 있나요? 무슨 일이 있었는지 설명해 보세요.",
      "다른 차원에서 온 낯선 존재가 갑자기 나를 찾아온다면 무엇을 물어보고 싶나요?"] };
ACT["S4179"] = { s: "In 1996, in the New York City, three girls bond over their shared love of Tupac Shakur's music as together they try to make sense of the unpredictable world in which they live.",
  q: ["What do the three girls in this book share a love for that brings them together?",
      "Have you ever bonded with a friend over a shared love of music or something else? Describe it.",
      "Why do you think shared music can help friends make sense of a hard or unpredictable world?"],
  h: ["이 책의 세 소녀를 하나로 묶어 주는, 그들이 함께 좋아하는 것은 무엇인가요?",
      "음악이나 다른 무언가를 함께 좋아하며 친구와 가까워진 적이 있나요? 그 이야기를 해 보세요.",
      "함께 좋아하는 음악이 힘들고 예측할 수 없는 세상을 이해하는 데 왜 도움이 될까요?"] };
ACT["S4180"] = { s: "A twelve-year-old boy named Moose moves to an Island in 1935 when guards' families were housed there, and has to contend with his new environment in addition to life with his autistic sister.",
  q: ["Where does Moose move to in 1935?",
      "Have you ever had to get used to a new home or a new place? What was hard about it?",
      "Do you have a brother or sister who needs extra care? What is that like for your family?"],
  h: ["무스는 1935년에 어디로 이사하나요?",
      "새로운 집이나 새로운 곳에 적응해야 했던 적이 있나요? 무엇이 힘들었나요?",
      "특별한 돌봄이 필요한 형제자매가 있나요? 우리 가족에게 그것은 어떤 모습인가요?"] };
ACT["S4181"] = { s: "When Woodrow's mom suddenly disappears, he goes to his grandparents' home in a small town where he befriends his cousin and together they find the strength to face the terrible losses and fears in their lives.",
  q: ["Where does Woodrow go after his mom suddenly disappears?",
      "Have you ever had to stay with grandparents or other relatives during a hard time? Describe what that was like.",
      "Why do you think Woodrow and his cousin are able to find strength together to face their losses and fears?"],
  h: ["엄마가 갑자기 사라진 뒤 우드로는 어디로 가나요?",
      "힘든 시기에 조부모님이나 다른 친척 집에서 지내야 했던 적이 있나요? 어땠는지 설명해 보세요.",
      "우드로와 사촌이 함께 힘을 내어 상실과 두려움에 맞설 수 있는 이유는 무엇일까요?"] };
ACT["S4182"] = { s: "The life of a ten-year-old boy in rural Virginia expands when he becomes friends with a newcomer, who subsequently meets an untimely death trying to go their hideaway, Terabithia.",
  q: ["How does the ten-year-old boy's life expand when the newcomer arrives?",
      "Have you ever had a special hideaway or secret place with a friend? Describe it.",
      "How do you think the boy might feel after losing his friend on the way to their hideaway?"],
  h: ["새로 온 친구가 나타나면서 열 살 소년의 삶은 어떻게 넓어지나요?",
      "친구와 함께 특별한 아지트나 비밀 장소를 가져 본 적이 있나요? 설명해 보세요.",
      "아지트로 가던 길에 친구를 잃은 뒤 소년은 어떤 기분일 것 같나요?"] };
ACT["S4183"] = { s: "Although Vernon joins his friends in making fun of the neighborhood outcasts, he develops a social conscience after all.",
  q: ["What does Vernon join his friends in doing at first?",
      "Have you ever changed your mind about how you treated someone? What changed it?",
      "Do you think it is easy or hard to stand up for someone your friends are making fun of? Explain."],
  h: ["버논은 처음에 친구들과 함께 무엇을 하나요?",
      "누군가를 대하는 내 태도를 바꾼 적이 있나요? 무엇이 그것을 바꿨나요?",
      "친구들이 놀리는 사람을 위해 나서는 것이 쉬울까요, 어려울까요? 설명해 보세요."] };
ACT["S4184"] = { s: "After learning that humans are headed toward his home, Firedrake, a brownie, a silver dragon and an orphan boy encounter various creatures during a quest to find the legendary valley known as the Rim of Heaven.",
  q: ["What are Firedrake and his companions searching for on their quest?",
      "Have you ever gone on a search or quest for something important with friends? Describe it.",
      "Who do you think would be the most helpful companion on a quest like this: a brownie, a dragon, or an orphan boy? Explain."],
  h: ["파이어드레이크와 동료들이 여정에서 찾고 있는 것은 무엇인가요?",
      "친구들과 함께 중요한 것을 찾아 여정을 떠나 본 적이 있나요? 설명해 보세요.",
      "이런 여정에서 브라우니, 용, 고아 소년 중 누가 가장 도움이 될 동료일 것 같나요? 이유를 설명해 보세요."] };
ACT["S4185"] = { s: "In this novel based on the famous story Cinderella, Ella struggles against the childhood curse that forces her to obey any order given.",
  q: ["What curse does Ella struggle against in this book?",
      "Have you ever had to do something you didn't want to do just because someone told you to? Describe it.",
      "If you had a curse that forced you to obey any order, what do you think would be the hardest part?"],
  h: ["엘라가 이 책에서 맞서 싸우는 저주는 무엇인가요?",
      "누군가 시켰다는 이유만으로 하고 싶지 않은 일을 해야 했던 적이 있나요? 설명해 보세요.",
      "누구의 명령이든 따라야 하는 저주에 걸린다면 가장 힘든 점은 무엇일 것 같나요?"] };
ACT["S4186"] = { s: "Thirteen-year-old Annabel sees her mother's 'easy' life much differently when she becomes her mother one day.",
  q: ["What happens to Annabel that changes how she sees her mother's life?",
      "Have you ever thought someone else's life looked easy, but then found out it was harder than you thought? Describe it.",
      "If you switched places with a parent for one day, what do you think would surprise you the most?"],
  h: ["애나벨이 엄마의 삶을 다르게 보게 만드는 일은 무엇인가요?",
      "다른 사람의 삶이 편해 보였지만 알고 보니 더 힘들었던 적이 있나요? 설명해 보세요.",
      "하루 동안 부모님과 자리를 바꾼다면 무엇이 가장 놀라울 것 같나요?"] };
ACT["S4187"] = { s: "Claudia and her brother Jamie run away from home and stay in the Metropolitan Museum of Art.",
  q: ["Where do Claudia and her brother Jamie stay after they run away from home?",
      "Have you ever imagined running away to a special place for a while? Where would you go?",
      "What do you think would be the hardest part of secretly living inside a museum?"],
  h: ["클라우디아와 남동생 제이미는 가출한 뒤 어디에서 지내나요?",
      "잠시 특별한 곳으로 떠나는 상상을 해 본 적이 있나요? 어디로 가고 싶나요?",
      "박물관 안에서 몰래 지내는 것 중 가장 힘든 점은 무엇일 것 같나요?"] };
ACT["S4188"] = { s: "A young dream giver, who is being trained to bestow dreams, tries to save an eight-year-old boy from the effects of the nightmares and his abusive past.",
  q: ["What is the young dream giver being trained to do?",
      "Have you ever tried to help someone feel better after a scary dream or a hard memory? What did you do?",
      "Why do you think dreams might be a powerful way to help someone heal from a hard past?"],
  h: ["어린 꿈 요정은 무엇을 하도록 훈련받고 있나요?",
      "무서운 꿈이나 힘든 기억 때문에 힘들어하는 누군가를 도와준 적이 있나요? 무엇을 했나요?",
      "꿈이 힘든 과거를 치유하는 데 강력한 방법이 될 수 있는 이유는 무엇일까요?"] };
ACT["S4189"] = { s: "Harriet's notebook of her feelings and thought about classmates and neighbors is found by her classmates.",
  q: ["What is found by Harriet's classmates in this book?",
      "Have you ever written down private thoughts and worried about someone else reading them? Describe it.",
      "Why do you think it caused trouble when Harriet's classmates read her private notebook?"],
  h: ["이 책에서 해리엇의 반 친구들이 발견하는 것은 무엇인가요?",
      "다른 사람이 읽을까 봐 걱정하며 나만의 생각을 적어 본 적이 있나요? 설명해 보세요.",
      "해리엇의 반 친구들이 그녀의 개인적인 노트를 읽었을 때 왜 문제가 생겼을까요?"] };
ACT["S4190"] = { s: "After inheriting her uncle's homesteading claim, sixteen-year-old orphan Hattie Brooks travels from Iowa in 1917 to make a home for herself and encounters some problems related to the war being fought in Europe.",
  q: ["What does Hattie inherit from her uncle that leads her to travel west?",
      "Have you ever had to start over and build a new life somewhere unfamiliar? Describe it.",
      "How do you think the war in Europe might have made things harder for Hattie as she tries to build her new home?"],
  h: ["해티가 삼촌에게서 물려받아 서쪽으로 떠나게 만드는 것은 무엇인가요?",
      "낯선 곳에서 새로 시작해서 삶을 꾸려야 했던 적이 있나요? 설명해 보세요.",
      "해티가 새 보금자리를 일구는 동안 유럽의 전쟁이 왜 상황을 더 힘들게 만들었을 것 같나요?"] };
ACT["S4191"] = { s: "As further evidence of his family's bad fortune, Stanley is sent to a terrible correctional camp in the Texas desert. The story contains profanity, sexual situations, violence, slurs, and negative stereotypes.",
  q: ["Where is Stanley sent as further evidence of his family's bad fortune?",
      "Have you ever felt like bad luck kept following you or your family? Describe what happened.",
      "Why do you think Stanley's family believes they have bad fortune?"],
  h: ["가족의 나쁜 운을 보여 주는 또 하나의 증거로 스탠리는 어디로 보내지나요?",
      "나쁜 운이 나나 우리 가족을 계속 따라다니는 것 같았던 적이 있나요? 무슨 일이 있었는지 설명해 보세요.",
      "스탠리의 가족은 왜 자신들이 나쁜 운을 타고났다고 믿을까요?"] };
ACT["S4192"] = { s: "Lonely Elizabeth decides to be an apprentice witch to Jennifer, and that's when the exciting life starts.",
  q: ["What does lonely Elizabeth decide to become to Jennifer?",
      "Have you ever felt lonely and then made a new friend who changed things for you? Describe it.",
      "Why do you think becoming an apprentice witch makes Elizabeth's life so exciting?"],
  h: ["외로웠던 엘리자베스는 제니퍼에게 무엇이 되기로 결심하나요?",
      "외로웠다가 새 친구를 사귀며 상황이 달라진 적이 있나요? 설명해 보세요.",
      "견습 마녀가 되는 것이 왜 엘리자베스의 삶을 그렇게 신나게 만들까요?"] };
ACT["S4193"] = { s: "Twelve-year-old Jeremy Thatcher is small for his age but artistically talented. He unknowingly buys a dragon's egg.",
  q: ["What does Jeremy unknowingly buy?",
      "Have you ever bought or found something that turned out to be more special than you expected? Describe it.",
      "If you unknowingly bought a dragon's egg like Jeremy, what do you think you would do when you found out?"],
  h: ["제레미가 자신도 모르게 사게 되는 것은 무엇인가요?",
      "샀거나 주운 물건이 생각보다 훨씬 특별했던 적이 있나요? 설명해 보세요.",
      "제레미처럼 나도 모르게 용의 알을 샀다는 것을 알게 된다면 나는 무엇을 할 것 같나요?"] };
ACT["S4194"] = { s: "Seven-year-old Just Grace prides herself on being empathic, but when she tries to help a neighbor feel better, her good intentions backfire.",
  q: ["What is Just Grace trying to do for her neighbor when her good intentions backfire?",
      "Have you ever tried to help someone but it did not turn out the way you hoped? Describe what happened.",
      "Why do you think good intentions can sometimes backfire, even when someone really wants to help?"],
  h: ["저스트 그레이스는 좋은 의도가 어긋날 때, 이웃을 위해 무엇을 하려고 했나요?",
      "누군가를 도우려 했지만 바라던 대로 되지 않은 적이 있나요? 무슨 일이 있었는지 설명해 보세요.",
      "정말로 돕고 싶었는데도 좋은 의도가 때때로 어긋나는 이유는 무엇일까요?"] };
ACT["S4195"] = { s: "This book tells the close friendship between two Japanese American sisters growing up in rural Georgia during the late 1950s and early 1960s and the despair when one sister becomes ill.",
  q: ["What happens to one of the sisters that brings despair into the story?",
      "Have you ever felt worried or sad because someone in your family was sick? Describe it.",
      "Why do you think a close friendship between sisters can help during such a hard and despairing time?"],
  h: ["이야기에 절망을 가져오는, 자매 중 한 명에게 일어나는 일은 무엇인가요?",
      "가족 중 누군가 아파서 걱정되거나 슬펐던 적이 있나요? 설명해 보세요.",
      "자매 사이의 끈끈한 우정이 이렇게 힘들고 절망적인 시간에 왜 도움이 될까요?"] };
ACT["S4196"] = { s: "Leon tries to outwit the school bully and learn to sew for fanatical teacher Miss Hagmeyer, with unexpected help from his final project ? a doll with magical powers.",
  q: ["What does Leon try to do about the school bully?",
      "Have you ever had to deal with a bully at school? What did you do?",
      "What unexpected kind of help does Leon get from his sewing project?"],
  h: ["레온은 학교 불량배를 상대로 어떤 시도를 하나요?",
      "학교에서 불량배를 상대해야 했던 적이 있나요? 나는 무엇을 했나요?",
      "레온은 바느질 프로젝트에서 뜻밖에 어떤 도움을 받나요?"] };
ACT["S4197"] = { s: "During a summer spent at Rockaway Beach in 1944, Lily's meets a young Hungarian refugee and it causes her to see the war and her own world differently.",
  q: ["Who does Lily meet at Rockaway Beach that changes how she sees the war?",
      "Have you ever met someone whose story changed how you saw the world? Describe that person.",
      "Why do you think meeting a refugee would change the way Lily sees the war?"],
  h: ["락어웨이 해변에서 릴리가 만나 전쟁을 다르게 보게 되는 사람은 누구인가요?",
      "그 이야기를 듣고 세상을 보는 눈이 달라진 사람을 만난 적이 있나요? 그 사람을 설명해 보세요.",
      "난민을 만난 것이 릴리가 전쟁을 보는 방식을 왜 바꿔 놓을까요?"] };
ACT["S4198"] = { s: "Even though his classmates from first grade on have considered him strange and a loser, Donald Zinkoff's optimism and liveness and the support of his family do not allow him to feel that way about himself.",
  q: ["What two things keep Donald Zinkoff from feeling like a loser, even though his classmates call him that?",
      "Have you ever been called something unkind by classmates but did not let it change how you felt about yourself? Describe it.",
      "Why do you think family support makes such a big difference when others are unkind to you?"],
  h: ["반 친구들이 도널드 진코프를 루저라고 불러도, 그가 스스로를 그렇게 느끼지 않게 해 주는 두 가지는 무엇인가요?",
      "반 친구들에게 나쁜 말을 들었지만 그것 때문에 나에 대한 생각이 바뀌지 않았던 적이 있나요? 설명해 보세요.",
      "다른 사람들이 불친절할 때 가족의 지지가 왜 그렇게 큰 차이를 만들까요?"] };
ACT["S4199"] = { s: "After his parents pass away, Jeffrey Lionel Magee's life becomes legendary as he accomplishes athletic and other feats which awe his rivals.",
  q: ["What happens to Jeffrey Lionel Magee's parents at the start of this story?",
      "Have you ever done something so impressive that it amazed the people around you? Describe it.",
      "Why do you think Jeffrey's feats become legendary to everyone around him?"],
  h: ["이야기 시작에서 제프리 라이오넬 마기의 부모님에게 무슨 일이 일어나나요?",
      "주변 사람들이 놀랄 만큼 대단한 일을 해낸 적이 있나요? 설명해 보세요.",
      "제프리가 이룬 업적들이 주변 사람들에게 전설처럼 여겨지는 이유는 무엇일까요?"] };
