// 간이 학습 질문 — Book No. S42 묶음. 사람이 아니라 AI 가 한 번 쓰고 굳힌 파일이다.
window.ACT = window.ACT || {};
var ACT = window.ACT;
ACT["S4200"] = { s: "In this novel of the American Revolution, a young man is torn between his father and his brother.",
  q: ["What is one difficult choice the young man in this story has to face between his father and his brother?",
      "Have you ever had trouble deciding between two people you love, or two ideas you believe in? Describe what happened.",
      "If you were torn between family members during a war, what would guide your decision? Explain your thinking."],
  h: ["이 이야기에서 주인공이 아버지와 형 사이에서 겪는 어려운 선택은 무엇인가요?",
      "사랑하는 두 사람 사이에서, 또는 두 가지 생각 사이에서 고민해 본 적이 있나요? 무슨 일이 있었는지 설명해 보세요.",
      "전쟁 중에 가족들 사이에서 갈등한다면 나는 무엇을 기준으로 결정을 내릴까요? 이유도 함께 적어 보세요."] };
ACT["S4201"] = { s: "When a terrible blight attacks Ireland's potato crop in 1845, a young girl Nory Ryan's courage and creativity help her family and neighbors survive.",
  q: ["What problem do Nory Ryan's family and neighbors face when the potato crop fails?",
      "Have you ever used courage or creativity to help your family or friends through a hard time? What did you do?",
      "What do you think helps Nory Ryan the most to survive this crisis — her courage, her creativity, or something else? Explain your thinking."],
  h: ["감자 농사가 망했을 때 노리 라이언의 가족과 이웃은 어떤 문제를 겪나요?",
      "용기나 창의력을 발휘해서 가족이나 친구가 힘든 시기를 넘기도록 도와준 적이 있나요? 무엇을 했나요?",
      "노리 라이언이 위기를 이겨 내는 데 가장 크게 도움이 된 것은 용기일까요, 창의력일까요, 아니면 다른 것일까요? 내 생각을 설명해 보세요."] };
ACT["S4202"] = { s: "Friends George and Lennie crave land of their own while working on a ranch in California's Salinas Valley.",
  q: ["What do George and Lennie dream of owning together?",
      "Have you ever dreamed of having a place of your own, or shared a big dream with a friend? Describe it.",
      "Why do you think having land of their own matters so much to George and Lennie? Share your thoughts."],
  h: ["조지와 레니는 함께 무엇을 갖기를 꿈꾸나요?",
      "나만의 공간을 갖고 싶다고 꿈꾸거나, 친구와 큰 꿈을 나눠 본 적이 있나요? 설명해 보세요.",
      "조지와 레니에게 자기 땅을 갖는 것이 왜 그렇게 중요할까요? 내 생각을 적어 보세요."] };
ACT["S4203"] = { s: "Andy and Terry have a whole week to finish their next book, and Andy even knows what it should be about, the story of how he and Terry first met.",
  q: ["What are Andy and Terry trying to finish in one week?",
      "Have you ever had to finish a big project in a short time? What was it like?",
      "If you were writing a book about how you met your best friend, what part would you want to tell first? Explain why."],
  h: ["앤디와 테리는 일주일 안에 무엇을 끝내려고 하나요?",
      "짧은 시간 안에 큰 과제를 끝내야 했던 적이 있나요? 그때 어땠나요?",
      "내가 가장 친한 친구와 어떻게 만났는지 책을 쓴다면, 어떤 부분을 가장 먼저 이야기하고 싶나요? 이유를 설명해 보세요."] };
ACT["S4204"] = { s: "When his best friend drowns while they are both swimming in a dangerous river, Joel is devastated and terrified at having to tell both sets of parents the terrible consequences of their disobedience.",
  q: ["What terrible thing happens to Joel's best friend in this story?",
      "Have you ever had to tell someone difficult news, or kept a promise even when it was hard? Describe what happened.",
      "Why do you think Joel is so afraid to tell both sets of parents what happened? Share your thoughts about his feelings."],
  h: ["이 이야기에서 조엘의 가장 친한 친구에게 어떤 끔찍한 일이 일어나나요?",
      "누군가에게 어려운 소식을 전해야 했거나, 힘들어도 약속을 지킨 적이 있나요? 무슨 일이 있었는지 설명해 보세요.",
      "조엘이 양쪽 부모님께 사실을 말하기를 그토록 두려워하는 이유는 무엇일까요? 조엘의 마음에 대한 내 생각을 적어 보세요."] };
ACT["S4205"] = { s: "As the only girl in a Finnish American family of seven brothers, May Amelia Jackson get mad at being expected to act like a lady while growing up.",
  q: ["Why does May Amelia get mad at her family?",
      "Have you ever been asked to act a certain way just because of being a girl or a boy? How did you feel?",
      "What do you think May Amelia would want to say to her family about how she wants to be treated? Explain your thinking."],
  h: ["메이 아멜리아는 왜 가족에게 화가 나나요?",
      "여자아이라서, 또는 남자아이라서 특정한 방식으로 행동하라는 말을 들은 적이 있나요? 그때 기분이 어땠나요?",
      "메이 아멜리아가 자신을 어떻게 대해 주길 바라는지 가족에게 말한다면 뭐라고 할까요? 내 생각을 설명해 보세요."] };
ACT["S4206"] = { s: "Dorian's innocent appearance conceals corruption deep enough to charm those about him into a life of wanton sensuality.",
  q: ["What is the difference between how Dorian Gray appears to others and what he truly is inside, according to this story?",
      "Have you ever met someone, in real life or in another story, whose outward appearance did not match their true character? Describe the situation.",
      "Why do you think appearances can be so deceiving, as shown in Dorian Gray's story? Share your own opinion on why people are sometimes fooled by appearances."],
  h: ["이 이야기에서 도리안 그레이가 겉으로 보이는 모습과 그의 진짜 속마음은 어떻게 다른가요?",
      "실제로나 다른 이야기에서, 겉모습과 진짜 성격이 달랐던 사람을 만난 적이 있나요? 그 상황을 설명해 보세요.",
      "도리안 그레이의 이야기처럼, 겉모습이 사람을 속일 수 있는 이유는 무엇일까요? 사람들이 왜 겉모습에 속는지 내 생각을 적어 보세요."] };
ACT["S4207"] = { s: "A troublesome twelve-year-old orphan, staying with an elderly artist, remembers the only other time she was happy in a foster home, with a family that truly seemed to adore her.",
  q: ["What does Hollis Woods remember about the foster family that once made her happy?",
      "Have you ever had a memory of a time you felt truly happy and cared for? Describe that memory.",
      "Why do you think Hollis keeps thinking back to that one foster family instead of others? Share your thoughts."],
  h: ["할리스 우즈는 자신을 행복하게 해 주었던 위탁 가족에 대해 무엇을 기억하고 있나요?",
      "정말 행복하고 사랑받는다고 느꼈던 순간의 기억이 있나요? 그 기억을 설명해 보세요.",
      "할리스가 다른 가족들이 아니라 유독 그 위탁 가족을 계속 떠올리는 이유는 무엇일까요? 내 생각을 적어 보세요."] };
ACT["S4208"] = { s: "As a school play actor, Leo is poised and ready for the curtain to open. But in the play that is his life, Leo is eager to discover what part will be his.",
  q: ["What is Leo waiting to find out in this story?",
      "Have you ever waited nervously to find out your role or part in something important? Describe how you felt.",
      "What do you think it means that \"the play\" in this story is really Leo's own life? Share your own idea."],
  h: ["이 이야기에서 레오는 무엇을 알게 되기를 기다리고 있나요?",
      "중요한 일에서 내 역할이나 자리를 알게 되기를 긴장하며 기다린 적이 있나요? 그때 기분이 어땠는지 설명해 보세요.",
      "이 이야기 속 '연극'이 사실은 레오 자신의 인생이라는 것은 어떤 의미일까요? 내 생각을 적어 보세요."] };
ACT["S4209"] = { s: "13-year-old twins have grown up in an orphanage, but their lives change when a weird but sweet older couple invites them each on an adventure, beginning in an almost magical place.",
  q: ["What kind of invitation changes the twins' lives in this story?",
      "Have you ever been invited somewhere new and exciting that changed how you felt about life? Describe it.",
      "Why do you think the twins' lives change so much after meeting this older couple? Share your thoughts."],
  h: ["이 이야기에서 쌍둥이의 삶을 바꾼 초대는 어떤 것인가요?",
      "새롭고 신나는 곳에 초대받아서 삶을 대하는 마음이 바뀐 적이 있나요? 설명해 보세요.",
      "이 노부부를 만난 뒤 쌍둥이의 삶이 그토록 크게 바뀌는 이유는 무엇일까요? 내 생각을 적어 보세요."] };
ACT["S4210"] = { s: "Frustrated at life with an autistic brother, twelve-year-old Catherine longs for a normal life, but her world is further complicated by a friendship with a boy in a wheelchair.",
  q: ["Who does Catherine become friends with in this story?",
      "Do you have a friend who is different from you in some way?",
      "What is one rule you think is important in your own life?"],
  h: ["이 이야기에서 캐서린은 누구와 친구가 되나요?",
      "나와 다른 점이 있는 친구가 있나요?",
      "내 삶에서 중요하다고 생각하는 규칙 하나는 무엇인가요?"] };
ACT["S4211"] = { s: "An Indian boy who cares llamas in a hidden valley in Peru learns the traditions and secrets of his Inca ancestors.",
  q: ["What does the boy in this story learn from living in the hidden valley?",
      "Have you ever learned an important tradition or story from your family or ancestors? Describe what you learned.",
      "Why do you think the secrets of his ancestors are kept hidden in a valley? Share your own idea about why traditions are protected."],
  h: ["이 이야기 속 소년은 숨겨진 골짜기에서 살면서 무엇을 배우게 되나요?",
      "가족이나 조상으로부터 중요한 전통이나 이야기를 배운 적이 있나요? 무엇을 배웠는지 설명해 보세요.",
      "조상들의 비밀이 골짜기 속에 숨겨져 있는 이유는 무엇일까요? 전통이 보호받는 이유에 대한 내 생각을 적어 보세요."] };
ACT["S4212"] = { s: "Armpit tries to keep his life on track after being released from Camp Green Lake. But when his old buddy X-Ray shows up with a tempting plan to make easy money scalping concert tickets, Armpit reluctantly goes along.",
  q: ["What tempting plan does X-Ray offer Armpit in this story?",
      "Have you ever been tempted to do something you knew might not be a good idea because a friend suggested it? Describe what happened.",
      "Why do you think Armpit reluctantly goes along with X-Ray's plan even though he is trying to keep his life on track? Share your thoughts."],
  h: ["이 이야기에서 엑스레이는 암핏에게 어떤 솔깃한 계획을 제안하나요?",
      "친구가 제안해서 좋지 않은 일인 줄 알면서도 유혹을 느낀 적이 있나요? 무슨 일이 있었는지 설명해 보세요.",
      "삶을 바르게 지키려던 암핏이 마지못해 엑스레이의 계획에 따라가는 이유는 무엇일까요? 내 생각을 적어 보세요."] };
ACT["S4213"] = { s: "In this story about the danger of popularity, the courage of nonconformity, and the thrill of first love, a weird student named Stargirl changes Mica High School.",
  q: ["How does Stargirl change Mica High School, according to this story?",
      "Have you ever met someone who was different from everyone else and changed how you saw things? Describe that person.",
      "What do you think is more important — fitting in with everyone or being true to yourself, like Stargirl? Share your own opinion."],
  h: ["스타걸은 마이카 고등학교를 어떻게 바꾸어 놓나요?",
      "다른 사람들과 달랐지만 나에게 새로운 생각을 하게 해 준 사람을 만난 적이 있나요? 그 사람에 대해 설명해 보세요.",
      "다른 사람들과 맞추는 것과 스타걸처럼 나답게 사는 것 중에 무엇이 더 중요할까요? 내 생각을 적어 보세요."] };
ACT["S4214"] = { s: "A 65-story treehouse has a pet-grooming salon, a birthday room where it's always your birthday, a room full of exploding eyeballs, a lollipop shop, a quicksand pit, an ant farm, and a time machine. But this fantastic house just fails safety inspection.",
  q: ["What are some of the strange rooms found in the 65-storey treehouse?",
      "If you could build one amazing room in your own treehouse or house, what would it be?",
      "Why do you think this fantastic treehouse fails its safety inspection? Share your own guess and explain your thinking."],
  h: ["65층 나무 집에는 어떤 신기한 방들이 있나요?",
      "내 나무 집이나 우리 집에 놀라운 방을 하나 만들 수 있다면 어떤 방을 만들고 싶나요?",
      "이렇게 멋진 나무 집이 안전 검사에 통과하지 못하는 이유는 무엇일까요? 내 생각과 이유를 적어 보세요."] };
ACT["S4215"] = { s: "Unusual things happen around Paul as his family moves to Tangerine County, Florida. Constant harassment from his football-star brother has affected Paul in many ways, but Paul gains the courage to face the secrets as he goes through many events.",
  q: ["What kind of trouble does Paul face from his football-star brother in this story?",
      "Have you ever had to find courage to face a difficult secret or problem? Describe what happened.",
      "Why do you think Paul finally finds the courage to face his family's secrets? Share your thoughts on what might have helped him."],
  h: ["이 이야기에서 폴은 미식축구 스타인 형에게 어떤 어려움을 겪나요?",
      "어려운 비밀이나 문제를 마주할 용기를 찾아야 했던 적이 있나요? 무슨 일이 있었는지 설명해 보세요.",
      "폴이 결국 가족의 비밀을 마주할 용기를 찾는 이유는 무엇일까요? 폴에게 도움이 되었을 것 같은 것에 대한 내 생각을 적어 보세요."] };
ACT["S4216"] = { s: "Budding cartoonist Junior leaves his school on the Indian Reservation to attend an all-white farm town school where the only other Indian is the school mascot.",
  q: ["Why does Junior decide to leave his school on the reservation?",
      "Have you ever changed schools or a familiar place and felt like you didn't quite belong at first? Describe that experience.",
      "How do you think Junior feels being one of very few Indian students at his new school? Share your own thoughts about his feelings."],
  h: ["주니어는 왜 보호구역에 있는 학교를 떠나기로 결심하나요?",
      "학교나 익숙한 곳을 옮기면서 처음에는 잘 어울리지 못한다고 느낀 적이 있나요? 그 경험을 설명해 보세요.",
      "새 학교에서 인디언 학생이 거의 없는 상황에서 주니어는 어떤 기분일까요? 주니어의 마음에 대한 내 생각을 적어 보세요."] };
ACT["S4217"] = { s: "When Soren is pushed from his family's nest, he is rescued by agents from a mysterious school for orphaned owls. He and his new friend find out that there is more to the school than meets the eye.",
  q: ["What happens to Soren that leads him to the mysterious owl school?",
      "Have you ever discovered that a place was very different from what you first expected? Describe what you found out.",
      "Why do you think the school for orphaned owls has more going on than it first appears? Share your own guess."],
  h: ["소렌에게 어떤 일이 일어나서 신비로운 올빼미 학교로 가게 되나요?",
      "어떤 곳이 처음 생각과는 아주 다르다는 것을 알게 된 적이 있나요? 무엇을 알게 되었는지 설명해 보세요.",
      "고아 올빼미들을 위한 이 학교에 겉으로 보이는 것보다 더 많은 사연이 있는 이유는 무엇일까요? 내 생각을 적어 보세요."] };
ACT["S4218"] = { s: "William has a fantastic gift that is able to transport him to another land and another time for a challenging and exciting adventure.",
  q: ["What does William's fantastic gift let him do in this story?",
      "If you had a gift that could transport you to another land or time, where would you want to go?",
      "What do you think makes William's adventure so challenging and exciting? Share your own idea."],
  h: ["윌리엄의 놀라운 선물은 그가 무엇을 할 수 있게 해 주나요?",
      "다른 나라나 다른 시대로 데려다주는 선물이 있다면 나는 어디로 가고 싶나요?",
      "윌리엄의 모험이 그토록 어렵고도 신나는 이유는 무엇일까요? 내 생각을 적어 보세요."] };
ACT["S4219"] = { s: "Chester the cricket lives in a newsstand. He has many adventures, climaxing with the rescue of the newsstand owner from financial disaster.",
  q: ["How does Chester the cricket help the newsstand owner in this story?",
      "Have you ever helped someone solve a big problem, even in a small way? Describe what you did.",
      "Why do you think a small cricket is able to make such a big difference for the newsstand owner? Share your own thoughts."],
  h: ["귀뚜라미 체스터는 신문 가판대 주인을 어떻게 도와주나요?",
      "작은 방법으로라도 누군가의 큰 문제를 해결하도록 도와준 적이 있나요? 무엇을 했는지 설명해 보세요.",
      "작은 귀뚜라미가 신문 가판대 주인에게 그토록 큰 도움을 줄 수 있는 이유는 무엇일까요? 내 생각을 적어 보세요."] };
ACT["S4220"] = { s: "Lily, her sister Sam, and their mother move in with her sick grandmother. There, Lily meets a tiger, and she deals with the tiger to heal Halmoni.",
  q: ["What does Lily do to try to heal her grandmother, Halmoni?",
      "Have you ever tried to help a sick family member feel better? Describe what you did.",
      "Why do you think Lily meets a tiger in this story? Share your own idea about what the tiger might mean."],
  h: ["릴리는 할머니를 낫게 하려고 무엇을 하나요?",
      "아픈 가족을 낫게 하려고 도와준 적이 있나요? 무엇을 했는지 설명해 보세요.",
      "이 이야기에서 릴리가 호랑이를 만나는 이유는 무엇일까요? 호랑이가 무엇을 의미하는지 내 생각을 적어 보세요."] };
ACT["S4221"] = { s: "An eleven-year-old foster child tries to cope with her longings and fears as she schemes against everyone who tries to be friendly.",
  q: ["How does Gilly react to people who try to be friendly to her?",
      "Have you ever pushed away someone who was trying to be kind to you, even though part of you wanted their kindness? Describe what happened.",
      "Why do you think Gilly schemes against people who are trying to help her? Share your own thoughts about her fears."],
  h: ["길리는 자신에게 친절하게 대해 주려는 사람들에게 어떻게 반응하나요?",
      "마음 한편으로는 원했으면서도, 친절하게 대해 주는 사람을 밀어낸 적이 있나요? 무슨 일이 있었는지 설명해 보세요.",
      "길리가 자신을 도와주려는 사람들에게 오히려 못되게 구는 이유는 무엇일까요? 길리의 두려움에 대한 내 생각을 적어 보세요."] };
ACT["S4222"] = { s: "A young girl living in a Hispanic neighborhood in Chicago thinks of the advantages and disadvantages of her environment and evaluates her relationships with family and friends.",
  q: ["What does the girl in this story think about her neighborhood?",
      "What do you think are the advantages and disadvantages of the neighborhood where you live?",
      "Why do you think it is important for her to evaluate her relationships with family and friends? Share your own opinion."],
  h: ["이 이야기 속 소녀는 자신의 동네에 대해 어떤 생각을 하나요?",
      "내가 사는 동네의 좋은 점과 아쉬운 점은 무엇이라고 생각하나요?",
      "소녀가 가족이나 친구와의 관계를 돌아보는 것이 왜 중요할까요? 내 생각을 적어 보세요."] };
ACT["S4223"] = { s: "Edward Tulane, a cold-hearted and proud toy rabbit, loves only himself. He travels across the country, acquiring new owners and listening to their hopes, dreams, and histories.",
  q: ["What kind of rabbit is Edward Tulane at the start of this story?",
      "Have you ever had a favorite toy that felt like part of your family? Describe it.",
      "Why do you think listening to so many people's hopes and dreams might change Edward over his journey? Share your own thoughts."],
  h: ["이야기가 시작될 때 에드워드 튤레인은 어떤 토끼인가요?",
      "가족처럼 느껴질 만큼 소중한 장난감이 있었나요? 그 장난감에 대해 설명해 보세요.",
      "수많은 사람들의 희망과 꿈을 들으면서 에드워드가 여행 중에 변할 수도 있다면, 그 이유는 무엇일까요? 내 생각을 적어 보세요."] };
ACT["S4224"] = { s: "Rivalry between rich and poor gangs in 1960s leads to the deaths of three teenagers and intense soul-searching for one of the kids involved, a sensitive 14-year-old writer named Ponyboy.",
  q: ["What does the rivalry between the two gangs lead to in this story?",
      "Have you ever seen or experienced rivalry between two groups of people? Describe what happened.",
      "Why do you think this story causes such deep soul-searching for Ponyboy? Share your own thoughts."],
  h: ["두 패거리 사이의 다툼은 이 이야기에서 어떤 결과로 이어지나요?",
      "두 무리 사이의 다툼을 보거나 겪은 적이 있나요? 무슨 일이 있었는지 설명해 보세요.",
      "이 사건이 포니보이에게 그토록 깊은 고민을 남기는 이유는 무엇일까요? 내 생각을 적어 보세요."] };
ACT["S4225"] = { s: "Siblings Carter and Sadie Kane have to defeat the god Set after the gods are accidentally released in the present.",
  q: ["What do Carter and Sadie Kane have to do after the gods are released?",
      "If ancient gods suddenly appeared in the modern world, what do you think would happen?",
      "Why do you think it takes two siblings working together to defeat the god Set? Share your own idea."],
  h: ["신들이 풀려난 뒤 카터와 세이디 케인 남매는 무엇을 해야 하나요?",
      "고대의 신들이 갑자기 현대 세계에 나타난다면 어떤 일이 벌어질 것 같나요?",
      "신 세트를 물리치는 데 남매 두 사람이 함께 힘을 합쳐야 하는 이유는 무엇일까요? 내 생각을 적어 보세요."] };
ACT["S4227"] = { s: "The Traveling Pants and the Sisterhood that wears them embark on their 16th summer.",
  q: ["What do the Traveling Pants and the Sisterhood do together in this story?",
      "Do you have something special that connects you and your friends, like the pants connect the Sisterhood?",
      "Why do you think sharing one pair of pants can keep these friends so close? Share your own thoughts."],
  h: ["여행하는 청바지와 그 친구들은 이 이야기에서 함께 무엇을 하나요?",
      "청바지가 자매들을 이어 주듯이, 나와 친구들을 이어 주는 특별한 무언가가 있나요?",
      "청바지 한 벌을 함께 나눠 입는 것이 이 친구들을 그토록 가깝게 만드는 이유는 무엇일까요? 내 생각을 적어 보세요."] };
ACT["S4228"] = { s: "A boy rescued by an Indian chief must decide whether to spend the winter alone in the woods waiting for his family or live a new life with new friends.",
  q: ["What difficult decision does the boy have to make in this story?",
      "Have you ever had to choose between waiting for something familiar or trying something completely new? Describe your choice.",
      "What do you think the boy should choose, and why? Share your own opinion."],
  h: ["이 이야기에서 소년은 어떤 어려운 결정을 내려야 하나요?",
      "익숙한 것을 기다리는 것과 완전히 새로운 것을 시도하는 것 중에 선택해야 했던 적이 있나요? 그때 무엇을 선택했는지 설명해 보세요.",
      "소년은 무엇을 선택해야 한다고 생각하나요? 이유와 함께 내 생각을 적어 보세요."] };
ACT["S4229"] = { s: "Four best friends stay in touch through a shared pair of jeans that magically adapts to each of their figures and affects their attitudes to their summer experiences.",
  q: ["How do the four best friends stay connected during their summer apart?",
      "How do you stay connected with your friends when you are apart from them?",
      "Why do you think the magic pants affect each girl's attitude toward her summer? Share your own idea."],
  h: ["네 명의 가장 친한 친구들은 여름 동안 떨어져 있으면서 어떻게 서로 연결되어 있나요?",
      "친구들과 떨어져 있을 때 나는 어떻게 연락을 이어 가나요?",
      "마법의 청바지가 각 소녀의 여름을 대하는 마음가짐에 영향을 주는 이유는 무엇일까요? 내 생각을 적어 보세요."] };
ACT["S4230"] = { s: "A girl gains new insight into herself and her family when her mentally handicapped brother gets lost.",
  q: ["What happens to the girl's brother that changes how she sees her family?",
      "Have you ever learned something important about yourself or your family during a difficult moment? Describe it.",
      "Why do you think finding her brother gives the girl new insight into herself? Share your own thoughts."],
  h: ["소녀의 동생에게 어떤 일이 일어나서 가족을 보는 눈이 달라지나요?",
      "힘든 순간에 나 자신이나 가족에 대해 중요한 것을 깨달은 적이 있나요? 설명해 보세요.",
      "동생을 찾는 과정에서 소녀가 자기 자신에 대해 새롭게 깨닫는 이유는 무엇일까요? 내 생각을 적어 보세요."] };
ACT["S4231"] = { s: "This book tells of the adventure of Despereaux Tilling, a small mouse of unusual talents, the princess he loves, the servant girl who wants to be a princess.",
  q: ["Who are the three main characters connected in this story?",
      "Have you ever admired someone very different from you, the way Despereaux admires the princess? Describe who and why.",
      "Why do you think a small mouse with unusual talents can have such a big adventure? Share your own idea."],
  h: ["이 이야기 속 세 명의 주요 인물은 어떻게 서로 연결되어 있나요?",
      "데스퍼로가 공주를 우러러보듯이, 나와는 많이 다른 누군가를 존경해 본 적이 있나요? 누구인지, 왜인지 설명해 보세요.",
      "특별한 재능을 가진 작은 쥐가 이렇게 큰 모험을 할 수 있는 이유는 무엇일까요? 내 생각을 적어 보세요."] };
ACT["S4232"] = { s: "Prosper and Bo are orphans run away from their cruel aunt and uncle. The brothers decide to hide out in Venice, where they meet a mysterious boy who calls himself the 'Thief Lord.'",
  q: ["Why do Prosper and Bo run away and hide in Venice?",
      "Have you ever had to find a safe place away from someone unkind? Describe what you did.",
      "Why do you think the mysterious boy calls himself the \"Thief Lord\"? Share your own guess."],
  h: ["프로스퍼와 보는 왜 베네치아로 도망쳐 숨나요?",
      "불친절한 누군가로부터 벗어나 안전한 곳을 찾아야 했던 적이 있나요? 무엇을 했는지 설명해 보세요.",
      "그 신비로운 소년이 스스로를 '도둑 왕'이라고 부르는 이유는 무엇일까요? 내 짐작을 적어 보세요."] };
ACT["S4233"] = { s: "When a strange man comes to the Coven Tree Church Social promising he can give people what they ask for, three young believers-in-magic each make a wish that comes true in a surprising way.",
  q: ["What does the strange man at the Church Social promise to do?",
      "If you could make one wish that would truly come true, what would you wish for?",
      "Why do you think the wishes in this story come true in surprising, maybe not perfect, ways? Share your own thoughts."],
  h: ["교회 모임에 나타난 낯선 남자는 무엇을 해 주겠다고 약속하나요?",
      "정말로 이루어질 소원을 하나 빌 수 있다면 나는 무엇을 빌고 싶나요?",
      "이 이야기 속 소원들이 뜻밖의, 어쩌면 완벽하지 않은 방식으로 이루어지는 이유는 무엇일까요? 내 생각을 적어 보세요."] };
ACT["S4235"] = { s: "After her mother leaves home suddenly, Sal and her grandparents take a car trip retracing her mother's route. Along the way, Sal recounts the story of her friend Phoebe, whose mother also left.",
  q: ["What are Sal and her grandparents doing on their car trip?",
      "Have you ever taken a trip to understand something or someone better? Describe it.",
      "Why do you think Sal tells the story of her friend Phoebe during this trip? Share your own idea."],
  h: ["샐과 조부모님은 자동차 여행에서 무엇을 하고 있나요?",
      "무언가를, 또는 누군가를 더 잘 이해하기 위해 여행을 떠난 적이 있나요? 설명해 보세요.",
      "샐이 이 여행 중에 친구 피비의 이야기를 들려주는 이유는 무엇일까요? 내 생각을 적어 보세요."] };
ACT["S4236"] = { s: "Billy Coleman saves to buy two red-bone hunting hounds while his grandfather provides him with support and lessons in growing up.",
  q: ["What does Billy Coleman save his money to buy?",
      "Have you ever saved up for something you really wanted? Describe what it was and how you got it.",
      "Why do you think Billy's grandfather is important to his growing up? Share your own thoughts."],
  h: ["빌리 콜먼은 돈을 모아 무엇을 사려고 하나요?",
      "정말 갖고 싶었던 것을 위해 돈을 모아 본 적이 있나요? 그것이 무엇이었고 어떻게 얻었는지 설명해 보세요.",
      "빌리가 자라는 데 할아버지가 중요한 이유는 무엇일까요? 내 생각을 적어 보세요."] };
ACT["S4237"] = { s: "Whittington, a descendant of Dick Whittington's famous cat of English folklore, appears at a rundown barnyard plagued by rats and tries to restore harmony.",
  q: ["What problem does Whittington the cat try to solve at the barnyard?",
      "Have you ever tried to fix a problem or bring peace to a group of people or animals? Describe what happened.",
      "Why do you think a cat descended from a famous folklore cat is able to restore harmony? Share your own idea."],
  h: ["고양이 위팅턴은 농장에서 어떤 문제를 해결하려고 하나요?",
      "사람들 사이나 동물들 사이의 문제를 해결하거나 평화를 가져오려고 애쓴 적이 있나요? 무슨 일이 있었는지 설명해 보세요.",
      "유명한 전래동화 속 고양이의 후손인 위팅턴이 평화를 되찾아 줄 수 있는 이유는 무엇일까요? 내 생각을 적어 보세요."] };
ACT["S4238"] = { s: "6,000 years ago, Torak and his guide, a wolf cub, set out on a journey to fulfill an oath the boy made to his dying father. They will travel to the mountain seeking a way to kill a demon-possessed bear.",
  q: ["What oath does Torak set out to fulfill in this story?",
      "Have you ever made a promise to someone that was hard to keep? Describe what happened.",
      "Why do you think Torak needs a wolf cub as his guide for this dangerous journey? Share your own thoughts."],
  h: ["토락은 이 이야기에서 어떤 맹세를 지키려고 하나요?",
      "누군가에게 지키기 어려운 약속을 한 적이 있나요? 무슨 일이 있었는지 설명해 보세요.",
      "토락에게 이 위험한 여정에 늑대 새끼가 길잡이로 필요한 이유는 무엇일까요? 내 생각을 적어 보세요."] };
ACT["S4239"] = { s: "As Palmer comes of age, he must either accept the violence of being a wringer at his town's annual Pigeon Day or find the courage to be against it.",
  q: ["What difficult choice does Palmer face about Pigeon Day?",
      "Have you ever had to decide whether to go along with something everyone else was doing, or stand against it? Describe your choice.",
      "Why do you think it takes courage for Palmer to be against Pigeon Day? Share your own opinion."],
  h: ["파머는 피전 데이를 앞두고 어떤 어려운 선택을 해야 하나요?",
      "모두가 하는 일을 따라야 할지, 반대해야 할지 결정해야 했던 적이 있나요? 그때 무엇을 선택했는지 설명해 보세요.",
      "파머가 피전 데이에 반대하려면 왜 용기가 필요할까요? 내 생각을 적어 보세요."] };
ACT["S4240"] = { s: "Twelve-year-old Percy Jackson learns he is a demigod. His mother sends him to a camp for demigods, where he and his new friends set out on a quest to prevent a war between the gods.",
  q: ["What does Percy Jackson learn about himself at the start of this story?",
      "If you found out you had a surprising hidden identity, how do you think you would react?",
      "Why do you think Percy and his friends need to prevent a war between the gods? Share your own thoughts."],
  h: ["이야기 초반에 퍼시 잭슨은 자기 자신에 대해 무엇을 알게 되나요?",
      "내게 놀라운 숨겨진 정체가 있다는 것을 알게 된다면 나는 어떻게 반응할 것 같나요?",
      "퍼시와 친구들이 신들 사이의 전쟁을 막아야 하는 이유는 무엇일까요? 내 생각을 적어 보세요."] };
ACT["S4241"] = { s: "Percy finds 7th grade unnervingly quiet. His biggest problem is dealing with his new friend, Tyson, a mentally challenged, homeless kid who follows Percy everywhere.",
  q: ["What is Percy's biggest problem in this story?",
      "Have you ever had a new friend who needed extra help or patience from you? Describe that friendship.",
      "Why do you think Percy's life becomes complicated because of Tyson? Share your own idea."],
  h: ["이 이야기에서 퍼시의 가장 큰 고민은 무엇인가요?",
      "더 많은 도움이나 인내심이 필요했던 새 친구가 있었나요? 그 우정에 대해 설명해 보세요.",
      "타이슨 때문에 퍼시의 삶이 복잡해지는 이유는 무엇일까요? 내 생각을 적어 보세요."] };
ACT["S4242"] = { s: "When Artemis disappears, her followers joins Percy in an attempt to find and rescue her before the winter solstice, when her influence is needed to sway the Olympian Council.?",
  q: ["What is Percy's group trying to do before the winter solstice?",
      "Have you ever had to work as a team to solve a problem before a deadline? Describe what happened.",
      "Why do you think it is so important to rescue Artemis before the winter solstice? Share your own thoughts."],
  h: ["퍼시 일행은 동지가 되기 전에 무엇을 해내려고 하나요?",
      "정해진 시간 안에 팀을 이루어 문제를 해결해야 했던 적이 있나요? 무슨 일이 있었는지 설명해 보세요.",
      "동지 전에 아르테미스를 구해야 하는 것이 왜 그렇게 중요할까요? 내 생각을 적어 보세요."] };
ACT["S4243"] = { s: "When devilish cheerleaders invade his high school, Percy hurries to Camp Half Blood while the war between the Olympians and the evil Titan Lord Kronos draws near.",
  q: ["What strange danger invades Percy's high school in this story?",
      "Have you ever had to leave somewhere quickly because of an unexpected danger? Describe what happened.",
      "Why do you think Percy hurries to Camp Half Blood instead of staying at his school? Share your own idea."],
  h: ["이 이야기에서 퍼시의 고등학교에 어떤 이상한 위험이 닥치나요?",
      "예상치 못한 위험 때문에 어딘가를 급히 떠나야 했던 적이 있나요? 무슨 일이 있었는지 설명해 보세요.",
      "퍼시가 학교에 머무르지 않고 하프블러드 캠프로 서둘러 가는 이유는 무엇일까요? 내 생각을 적어 보세요."] };
ACT["S4244"] = { s: "Percy Jackson and his army of young demigods do battle with Kronos on the streets of Manhattan as Percy's sixteenth birthday approaches and his fate looms even closer.",
  q: ["Where does Percy's final battle against Kronos take place?",
      "Have you ever faced a big challenge right before an important birthday or event? Describe it.",
      "Why do you think Percy's fate is connected to his sixteenth birthday? Share your own thoughts."],
  h: ["퍼시가 크로노스와 벌이는 마지막 전투는 어디에서 일어나나요?",
      "중요한 생일이나 행사를 앞두고 큰 도전을 마주한 적이 있나요? 설명해 보세요.",
      "퍼시의 운명이 열여섯 번째 생일과 연결되어 있는 이유는 무엇일까요? 내 생각을 적어 보세요."] };
ACT["S4245"] = { s: "Charlie, his family, and Mr. Wonka find themselves launched into space in the great glass elevator.",
  q: ["Where do Charlie, his family, and Mr. Wonka end up traveling in this story?",
      "If you could travel into space in a magical elevator, what would you want to see first?",
      "Why do you think Mr. Wonka's glass elevator ends up going into space? Share your own imaginative idea."],
  h: ["찰리와 가족, 웡카 씨는 이 이야기에서 결국 어디로 여행을 떠나게 되나요?",
      "마법의 엘리베이터를 타고 우주로 간다면 가장 먼저 무엇을 보고 싶나요?",
      "웡카 씨의 유리 엘리베이터가 결국 우주까지 가게 되는 이유는 무엇일까요? 내 상상력을 담아 적어 보세요."] };
ACT["S4246"] = { s: "A young English boy describes his relationship with his father and the special adventure they share together.",
  q: ["What kind of relationship does the boy describe with his father in this story?",
      "Have you ever shared a special adventure with one of your parents? Describe what you did together.",
      "Why do you think this adventure is so special for the boy and his father? Share your own thoughts."],
  h: ["이 이야기에서 소년은 아버지와의 관계를 어떻게 이야기하나요?",
      "부모님과 특별한 모험을 함께한 적이 있나요? 함께 무엇을 했는지 설명해 보세요.",
      "이 모험이 소년과 아버지에게 그토록 특별한 이유는 무엇일까요? 내 생각을 적어 보세요."] };
ACT["S4247"] = { s: "Shy Mr. Hoppy devises a plan to win the heart of his true love by teaching her a magic to make her tortoise grow bigger.",
  q: ["What plan does Mr. Hoppy come up with to win his true love's heart?",
      "Have you ever come up with a clever plan to make someone happy? Describe your plan.",
      "Why do you think Mr. Hoppy chooses such an unusual plan involving a tortoise? Share your own idea."],
  h: ["호피 씨는 사랑하는 사람의 마음을 얻기 위해 어떤 계획을 세우나요?",
      "누군가를 기쁘게 해 주려고 기발한 계획을 세운 적이 있나요? 그 계획을 설명해 보세요.",
      "호피 씨가 거북이를 이용한 특이한 계획을 선택하는 이유는 무엇일까요? 내 생각을 적어 보세요."] };
ACT["S4248"] = { s: "Wonderful adventures abound after James escapes from his fearsome aunts by rolling away inside a giant peach.",
  q: ["How does James escape from his fearsome aunts?",
      "If you could escape into a giant fruit for an adventure, which fruit would you choose and why?",
      "Why do you think James needs such an unusual way to escape his aunts? Share your own thoughts."],
  h: ["제임스는 무서운 이모들로부터 어떻게 도망치나요?",
      "거대한 과일 속으로 들어가 모험을 떠날 수 있다면 어떤 과일을 고르고 싶나요? 이유도 적어 보세요.",
      "제임스가 이모들에게서 벗어나기 위해 이렇게 특이한 방법이 필요한 이유는 무엇일까요? 내 생각을 적어 보세요."] };
ACT["S4249"] = { s: "Kidsnatched from her orphange by a BFG (Big Friendly Giant), who spends his life blowing happy dreams to children, Sophie concocts with him a plan to save the world from nine other man-gobbling cannybull giants.",
  q: ["What plan do Sophie and the BFG come up with together?",
      "Have you ever teamed up with someone very different from you to solve a big problem? Describe what happened.",
      "Why do you think the BFG, who blows happy dreams, is willing to help save the world from the other giants? Share your own idea."],
  h: ["소피와 상냥한 거인은 함께 어떤 계획을 세우나요?",
      "나와는 많이 다른 누군가와 힘을 합쳐 큰 문제를 해결한 적이 있나요? 무슨 일이 있었는지 설명해 보세요.",
      "행복한 꿈을 불어넣어 주는 상냥한 거인이 다른 거인들로부터 세상을 구하려고 나서는 이유는 무엇일까요? 내 생각을 적어 보세요."] };
ACT["S4250"] = { s: "When Billy joined the Ladderless Cleaning Company, he had no idea what was in store for him.",
  q: ["What company does Billy join in this story?",
      "Have you ever joined something new without knowing what to expect? Describe what happened.",
      "Why do you think the story is called the \"Ladderless\" Cleaning Company? Share your own guess."],
  h: ["이 이야기에서 빌리는 어떤 회사에 들어가나요?",
      "무엇을 기대해야 할지 모른 채 새로운 것에 참여한 적이 있나요? 무슨 일이 있었는지 설명해 보세요.",
      "이 회사가 '사다리 없는' 청소 회사라고 불리는 이유는 무엇일까요? 내 짐작을 적어 보세요."] };
ACT["S4251"] = { s: "Two terrible old people who enjoy playing nasty tricks are finally outwitted by a family of monkeys.",
  q: ["Who finally outwits the terrible Twits in this story?",
      "Have you ever seen someone who plays unkind tricks finally get outsmarted? Describe what happened.",
      "Why do you think it takes a family of monkeys, not just one, to outwit the Twits? Share your own thoughts."],
  h: ["끔찍한 트윗 부부를 결국 이기는 것은 누구인가요?",
      "짓궂은 장난을 치던 사람이 결국 더 똑똑한 상대에게 당하는 것을 본 적이 있나요? 무슨 일이 있었는지 설명해 보세요.",
      "트윗 부부를 이기는 데 원숭이 한 마리가 아니라 원숭이 가족 전체가 필요한 이유는 무엇일까요? 내 생각을 적어 보세요."] };
ACT["S4252"] = { s: "In spite of everything his grandmother has taught him about witches, a young boy gets turned into a mouse but does manage to interrupt their plans.",
  q: ["What happens to the boy in this story, and what does he still manage to do?",
      "Have you ever used a difficult situation to still find a way to help others? Describe what happened.",
      "Why do you think being turned into a mouse still allows the boy to stop the witches' plans? Share your own idea."],
  h: ["이 이야기에서 소년에게 어떤 일이 일어나고, 그럼에도 그는 무엇을 해내나요?",
      "어려운 상황 속에서도 다른 사람을 도울 방법을 찾아낸 적이 있나요? 무슨 일이 있었는지 설명해 보세요.",
      "생쥐로 변한 뒤에도 소년이 마녀들의 계획을 막을 수 있는 이유는 무엇일까요? 내 생각을 적어 보세요."] };
ACT["S4253"] = { s: "This book presents a biography of Albert Einstein, chronicling his childhood and Jewish background, his early interest in science and math, and his emigration to the United States.",
  q: ["What are some parts of Albert Einstein's life this book describes?",
      "Have you ever been very interested in a subject like science or math, the way young Einstein was? Describe your interest.",
      "Why do you think learning about Einstein's childhood helps us understand his later genius? Share your own thoughts."],
  h: ["이 책은 알베르트 아인슈타인의 삶 중 어떤 부분들을 이야기하나요?",
      "어린 아인슈타인처럼 과학이나 수학 같은 과목에 큰 관심을 가진 적이 있나요? 나의 관심사를 설명해 보세요.",
      "아인슈타인의 어린 시절을 아는 것이 그의 나중 천재성을 이해하는 데 왜 도움이 될까요? 내 생각을 적어 보세요."] };
ACT["S4254"] = { s: "From the first flight conducted by Orville and Wilbur Wright in 1903 to today's supersonic jets, you are provided with fascinating facts and spectacular images of aircraft.",
  q: ["What kind of aircraft does this book describe, from the earliest to the newest?",
      "Have you ever seen an airplane up close or flown on one? Describe that experience.",
      "Why do you think aircraft have changed so much since the Wright brothers' first flight? Share your own thoughts."],
  h: ["이 책은 가장 오래된 것부터 가장 최신까지 어떤 항공기들을 소개하나요?",
      "비행기를 가까이서 본 적이 있거나 타 본 적이 있나요? 그 경험을 설명해 보세요.",
      "라이트 형제의 첫 비행 이후로 항공기가 이렇게 많이 변한 이유는 무엇일까요? 내 생각을 적어 보세요."] };
ACT["S4255"] = { s: "In this humorous version of \"Beauty and the Beast,\" Billy Beast wonders if the clean and proper Beauty will ever be the beast of his dreams.",
  q: ["What does Billy Beast wonder about in this silly story?",
      "Have you ever read or heard a funny, twisted version of a classic story? Describe it.",
      "Why do you think this silly version of Beauty and the Beast switches who is the \"beast\"? Share your own idea."],
  h: ["이 우스꽝스러운 이야기에서 빌리 비스트는 무엇을 궁금해하나요?",
      "고전 이야기를 재미있게 비틀어 놓은 버전을 읽거나 들은 적이 있나요? 설명해 보세요.",
      "이 우스운 버전에서는 누가 '야수'인지가 뒤바뀌어 있는데, 그 이유는 무엇일까요? 내 생각을 적어 보세요."] };
ACT["S4256"] = { s: "In this version of the classic fairytale 'Rumpelstiltskin,' the miller's daughter must guess her helper's name to keep her pet guinea pig.",
  q: ["What must the miller's daughter do to keep her pet guinea pig?",
      "Have you ever had to solve a tricky puzzle or guessing game to keep something you loved? Describe it.",
      "Why do you think guessing a name is such an important test in this story? Share your own thoughts."],
  h: ["방앗간 집 딸은 애완용 기니피그를 지키기 위해 무엇을 해야 하나요?",
      "소중한 것을 지키기 위해 어려운 수수께끼나 맞히기 게임을 풀어야 했던 적이 있나요? 설명해 보세요.",
      "이 이야기에서 이름을 알아맞히는 것이 그토록 중요한 시험이 되는 이유는 무엇일까요? 내 생각을 적어 보세요."] };
ACT["S4257"] = { s: "One day two well dressed strangers appeared in the country where nobody wore any clothes. They offered to make the emperor some warm clothes.",
  q: ["What do the two strangers offer to make for the emperor?",
      "Have you ever met someone who offered to help you with something you did not know you needed? Describe it.",
      "Why do you think it is funny that this story is about clothes in a country where nobody wears any? Share your own idea."],
  h: ["두 낯선 손님은 황제를 위해 무엇을 만들어 주겠다고 제안하나요?",
      "내가 필요한지도 몰랐던 것을 도와주겠다는 사람을 만난 적이 있나요? 설명해 보세요.",
      "아무도 옷을 입지 않는 나라에서 옷 이야기를 하는 것이 왜 재미있을까요? 내 생각을 적어 보세요."] };
ACT["S4258"] = { s: "The Mayor of Hamstring is the bossiest man in the world. He loves making up rules and he's banned many snacks.",
  q: ["What does the Mayor of Hamstring love to make?",
      "Do you think the rules at your school or home are fair?",
      "What snack would you be saddest to have banned?"],
  h: ["햄스트링 마을의 시장은 무엇을 만들기를 좋아하나요?",
      "우리 학교나 집의 규칙이 공평하다고 생각하나요?",
      "어떤 간식이 금지된다면 가장 슬플 것 같나요?"] };
ACT["S4259"] = { s: "One teeny-tiny turnip makes a rather measly meal for the greedy farmer. He wants to munch on a much bigger lunch.",
  q: ["What does the farmer want instead of the small turnip?",
      "Have you ever wished for something bigger than what you had?",
      "What is your favorite vegetable to eat?"],
  h: ["농부는 작은 순무 대신 무엇을 원하나요?",
      "가지고 있는 것보다 더 큰 것을 바란 적이 있나요?",
      "내가 가장 좋아하는 채소는 무엇인가요?"] };
ACT["S4260"] = { s: "This book contains fun facts about the history of chocolate, from the Mayans to Milton Hershey.",
  q: ["What time period and people does this book cover in the history of chocolate?",
      "What is your favorite way to eat or enjoy chocolate?",
      "Why do you think chocolate has stayed popular from the Mayans all the way to today? Share your own thoughts."],
  h: ["이 책은 초콜릿의 역사에서 어떤 시대와 사람들을 다루나요?",
      "초콜릿을 먹거나 즐기는 나만의 방법은 무엇인가요?",
      "마야 사람들부터 오늘날까지 초콜릿이 계속 인기 있는 이유는 무엇일까요? 내 생각을 적어 보세요."] };
ACT["S4261"] = { s: "One of the Impressionist era's best-loved painters, Pierre-Auguste Renoir painted every day for 60 years?that's over 5,000 paintings!",
  q: ["How long did Renoir paint, and how many paintings did he make?",
      "Is there something you do almost every day that you truly love, like Renoir loved painting?",
      "Why do you think painting every single day for 60 years helped Renoir become one of the best-loved painters? Share your own thoughts."],
  h: ["르누아르는 얼마나 오랫동안 그림을 그렸고, 몇 점을 그렸나요?",
      "르누아르가 그림 그리기를 사랑했던 것처럼, 나도 거의 매일 진심으로 좋아하는 일이 있나요?",
      "60년 동안 매일 그림을 그린 것이 르누아르를 사랑받는 화가로 만든 이유는 무엇일까요? 내 생각을 적어 보세요."] };
ACT["S4262"] = { s: "School children present a team project about first ladies to their teacher. The project discusses what it's like to be first lady and how the job of first lady has changed over time.",
  q: ["What do the school children present a project about in this book?",
      "If you did a project on a job that has changed over time, which job would you choose?",
      "Why do you think the role of first lady changed so much over time? Share your own thoughts."],
  h: ["이 책 속 학생들은 선생님께 무엇에 대한 모둠 과제를 발표하나요?",
      "시대에 따라 바뀐 직업을 주제로 과제를 한다면 어떤 직업을 고르고 싶나요?",
      "영부인의 역할이 시간이 지나며 그토록 많이 달라진 이유는 무엇일까요? 내 생각을 적어 보세요."] };
ACT["S4263"] = { s: "This book recounts how the Cherokees were forced to leave and travel 1200 miles to a new settlement in Oklahoma, a terrible journey known as the Trail of Tears.",
  q: ["How far did the Cherokees have to travel on the Trail of Tears?",
      "Have you ever had to leave a place you loved and travel somewhere new and difficult? Describe it.",
      "Why do you think this journey is remembered as such an important and sad part of history? Share your own thoughts."],
  h: ["체로키족은 '눈물의 길'에서 얼마나 먼 거리를 이동해야 했나요?",
      "사랑하는 곳을 떠나 새롭고 힘든 곳으로 이동해야 했던 적이 있나요? 설명해 보세요.",
      "이 여정이 역사 속에서 그토록 중요하고 슬픈 사건으로 기억되는 이유는 무엇일까요? 내 생각을 적어 보세요."] };
ACT["S4264"] = { s: "This book describes how and why such men as Bill Russell, Wilt Chamberlain, and Larry Bird became great basketball stars.",
  q: ["Which basketball players does this book describe?",
      "Do you play or watch any sport that you dream of being great at someday?",
      "Why do you think these players are remembered as some of the greatest in basketball history? Share your own thoughts."],
  h: ["이 책은 어떤 농구 선수들에 대해 이야기하나요?",
      "언젠가 잘하고 싶다고 꿈꾸는 운동이 있나요? 직접 하거나 즐겨 보는 운동이 있나요?",
      "이 선수들이 농구 역사상 가장 위대한 선수로 기억되는 이유는 무엇일까요? 내 생각을 적어 보세요."] };
ACT["S4265"] = { s: "This book explains the science of plate tectonics and its role in the development of earthquakes around the globe.",
  q: ["What scientific idea does this book explain about earthquakes?",
      "Have you ever felt or learned about an earthquake? Describe what you know or experienced.",
      "Why do you think it is important for people to understand plate tectonics? Share your own thoughts."],
  h: ["이 책은 지진에 대해 어떤 과학적인 원리를 설명하나요?",
      "지진을 느껴 보거나 지진에 대해 배운 적이 있나요? 내가 아는 것이나 경험한 것을 설명해 보세요.",
      "판구조론을 이해하는 것이 사람들에게 왜 중요할까요? 내 생각을 적어 보세요."] };
ACT["S4266"] = { s: "This book explains how and where tornadoes hit, and how people protect themselves from life-threatening winds.",
  q: ["How do people protect themselves from tornadoes, according to this book?",
      "What would you do to stay safe if a tornado warning happened where you live?",
      "Why do you think it is important to know how to protect yourself before a tornado hits? Share your own thoughts."],
  h: ["이 책에 따르면 사람들은 토네이도로부터 어떻게 자신을 보호하나요?",
      "내가 사는 곳에 토네이도 경보가 울린다면 안전을 위해 무엇을 할 것 같나요?",
      "토네이도가 닥치기 전에 스스로를 보호하는 방법을 아는 것이 왜 중요할까요? 내 생각을 적어 보세요."] };
ACT["S4267"] = { s: "This book explains the physics behind each sport, describes different techniques and tricks, and traces the history of various styles of boards and bikes.",
  q: ["What kind of science does this book explain about bikes and boards?",
      "Do you enjoy riding a bike, skateboard, or something similar? Describe what you like about it.",
      "Why do you think understanding physics can help someone do better tricks on a bike or board? Share your own thoughts."],
  h: ["이 책은 자전거와 보드에 대해 어떤 과학을 설명하나요?",
      "자전거나 스케이트보드 같은 것을 타는 것을 좋아하나요? 무엇이 좋은지 설명해 보세요.",
      "물리학을 이해하는 것이 자전거나 보드로 더 멋진 기술을 하는 데 왜 도움이 될까요? 내 생각을 적어 보세요."] };
ACT["S4268"] = { s: "This book explores the design and function of electric, magnetic, and motion-powered toys, introduces the six simple machines, and explains how they use forces and motion to get a job done.",
  q: ["What kinds of toys and machines does this book explain?",
      "What is your favorite toy, and how do you think it works?",
      "Why do you think it is useful to know about the six simple machines? Share your own thoughts."],
  h: ["이 책은 어떤 종류의 장난감과 기계들을 설명하나요?",
      "내가 가장 좋아하는 장난감은 무엇이고, 어떻게 작동한다고 생각하나요?",
      "여섯 가지 단순 기계를 아는 것이 왜 유용할까요? 내 생각을 적어 보세요."] };
ACT["S4269"] = { s: "There are many life cycles found within a forest. Learn about the energy pyramid that explains the numbers of forest plants and animals.",
  q: ["What does the energy pyramid in this book explain?",
      "Have you ever visited a forest? Describe what plants or animals you saw.",
      "Why do you think it is important to understand the balance between plants and animals in a forest? Share your own thoughts."],
  h: ["이 책 속 에너지 피라미드는 무엇을 설명하나요?",
      "숲에 가 본 적이 있나요? 그때 본 식물이나 동물에 대해 설명해 보세요.",
      "숲 속 식물과 동물 사이의 균형을 이해하는 것이 왜 중요할까요? 내 생각을 적어 보세요."] };
ACT["S4270"] = { s: "This book explains scientific concepts related to speed, such as motion, gravity, and velocity, and discusses the history of transportation.",
  q: ["What scientific concepts does this book explain about speed?",
      "What is the fastest way you have ever traveled? Describe that experience.",
      "Why do you think understanding motion and gravity helps people build faster vehicles? Share your own thoughts."],
  h: ["이 책은 속도에 대해 어떤 과학 개념들을 설명하나요?",
      "지금까지 가장 빠르게 이동해 본 방법은 무엇인가요? 그 경험을 설명해 보세요.",
      "운동과 중력을 이해하는 것이 더 빠른 탈것을 만드는 데 왜 도움이 될까요? 내 생각을 적어 보세요."] };
ACT["S4271"] = { s: "Amy and Dan explore Egypt and find a statue that gives them another clue in their quest to win the contest.",
  q: ["Where do Amy and Dan travel to find their next clue?",
      "If you were searching for a hidden clue in a contest, which country would you want to explore?",
      "Why do you think the clues in this contest are hidden in different places around the world? Share your own thoughts."],
  h: ["에이미와 댄은 다음 단서를 찾기 위해 어디로 떠나나요?",
      "대회에서 숨겨진 단서를 찾는다면 어느 나라를 탐험하고 싶나요?",
      "이 대회의 단서들이 세계 여러 곳에 숨겨져 있는 이유는 무엇일까요? 내 생각을 적어 보세요."] };
ACT["S4272"] = { s: "A coded sheet of Mozart's music that will help Amy and Dan find the next clue while their relatives follow in close pursuit.",
  q: ["What kind of code do Amy and Dan need to solve in this story?",
      "Have you ever had to solve a puzzle or code to find something important? Describe it.",
      "Why do you think their relatives are chasing after them during this clue hunt? Share your own thoughts."],
  h: ["에이미와 댄은 이 이야기에서 어떤 암호를 풀어야 하나요?",
      "중요한 것을 찾기 위해 퍼즐이나 암호를 풀어야 했던 적이 있나요? 설명해 보세요.",
      "친척들이 이 단서 찾기 동안 그들을 바짝 뒤쫓는 이유는 무엇일까요? 내 생각을 적어 보세요."] };
ACT["S4273"] = { s: "Dan and Amy are on their most dangerous quest yet, one that brings them face to face with the only force capable of scaring the vicious Lucians: the Madrigals.",
  q: ["What group is even the vicious Lucians afraid of in this story?",
      "Have you ever faced something that scared even the people who usually seemed brave? Describe it.",
      "Why do you think the Madrigals are so feared by everyone else in this story? Share your own guess."],
  h: ["사나운 루시안조차 두려워하는 이 무리는 누구인가요?",
      "평소 용감해 보이던 사람들조차 두려워하는 것을 마주한 적이 있나요? 설명해 보세요.",
      "이 이야기에서 매드리갈 가문이 모두에게 그토록 두려운 존재인 이유는 무엇일까요? 내 짐작을 적어 보세요."] };
ACT["S4274"] = { s: "Amy and Dan try to uncover the 39 clues which will reveal the secrets of their lineage and find out what really happened to their parents.",
  q: ["What are Amy and Dan trying to discover about their family?",
      "Have you ever been curious about a secret in your own family's history? Describe what you wondered about.",
      "Why do you think discovering the truth about their parents is connected to the 39 clues? Share your own thoughts."],
  h: ["에이미와 댄은 가족에 대해 무엇을 알아내려고 하나요?",
      "우리 집안의 역사 속 비밀이 궁금했던 적이 있나요? 무엇이 궁금했는지 설명해 보세요.",
      "부모님에 대한 진실을 아는 것이 39가지 단서와 연결되어 있는 이유는 무엇일까요? 내 생각을 적어 보세요."] };
ACT["S4275"] = { s: "Spies report that Amy and Dan seem to be tracking the life of one of the most powerful fighters the world has ever known.",
  q: ["Whose life are Amy and Dan tracking in this story?",
      "If you could learn about the life of a powerful fighter from history, who would you choose?",
      "Why do you think spies are watching Amy and Dan so closely during this part of their quest? Share your own thoughts."],
  h: ["에이미와 댄은 이 이야기에서 누구의 삶을 추적하고 있나요?",
      "역사 속 강력한 전사의 삶에 대해 배울 수 있다면 누구를 고르고 싶나요?",
      "이 모험 중에 스파이들이 에이미와 댄을 그토록 가까이 지켜보는 이유는 무엇일까요? 내 생각을 적어 보세요."] };
ACT["S4276"] = { s: "A queen and a witch foil the plots of an evil wizard in this fantasy novel.",
  q: ["Who works together to stop the evil wizard's plots in this story?",
      "Have you ever teamed up with someone unexpected to solve a problem? Describe what happened.",
      "Why do you think it takes both a queen and a witch to defeat this evil wizard? Share your own thoughts."],
  h: ["이 이야기에서 사악한 마법사의 계획을 막기 위해 누가 함께 힘을 모으나요?",
      "뜻밖의 상대와 힘을 합쳐 문제를 해결한 적이 있나요? 무슨 일이 있었는지 설명해 보세요.",
      "이 사악한 마법사를 물리치는 데 여왕과 마녀가 함께 필요한 이유는 무엇일까요? 내 생각을 적어 보세요."] };
ACT["S4277"] = { s: "Daystar goes on an adventurous journey through the Enchanted Forest with a magic sword, a fire-witch and a baby dragon.",
  q: ["Who travels with Daystar on his journey through the Enchanted Forest?",
      "If you could take three magical companions on a journey, who or what would you choose?",
      "Why do you think Daystar needs such different companions — a sword, a witch, and a dragon — for his journey? Share your own thoughts."],
  h: ["데이스타는 마법의 숲을 지나는 여정에서 누구와 함께하나요?",
      "여행에 마법 같은 동료 셋을 데려갈 수 있다면 누구를, 또는 무엇을 고르고 싶나요?",
      "데이스타의 여정에 검, 마녀, 용처럼 서로 다른 동료들이 필요한 이유는 무엇일까요? 내 생각을 적어 보세요."] };
ACT["S4278"] = { s: "A young boy discovers that his magic cupboard and key can turn toys into live people and animals.",
  q: ["What does the boy discover his magic cupboard and key can do?",
      "If a toy of yours could magically come to life, which toy would you choose?",
      "Why do you think the boy is both excited and careful once he discovers this magic? Share your own thoughts."],
  h: ["소년은 마법 찬장과 열쇠가 무엇을 할 수 있다는 것을 알게 되나요?",
      "내 장난감 하나가 마법처럼 살아난다면 어떤 장난감을 고르고 싶나요?",
      "이 마법을 알게 된 뒤 소년이 신나면서도 조심스러운 이유는 무엇일까요? 내 생각을 적어 보세요."] };
ACT["S4279"] = { s: "In this sequel to THE INDIAN IN THE CUPBOARD, Omri brings Little Bear to life again and begins a spellbinding adventure.",
  q: ["Who does Omri bring back to life in this sequel?",
      "Have you ever been reunited with someone or something you missed? Describe how it felt.",
      "Why do you think Omri decides to bring Little Bear to life again, even after the first adventure? Share your own thoughts."],
  h: ["이 속편에서 옴리는 누구를 다시 살려 내나요?",
      "그리웠던 누군가나 무언가를 다시 만난 적이 있나요? 그때 기분이 어땠는지 설명해 보세요.",
      "첫 모험을 겪고도 옴리가 리틀 베어를 다시 살리기로 하는 이유는 무엇일까요? 내 생각을 적어 보세요."] };
ACT["S4280"] = { s: "Omri digs up an old journal that reveals the mystery of the Indian in the cupboard.",
  q: ["What does Omri find that reveals a mystery?",
      "Have you ever found an old object, like a journal, that revealed something surprising? Describe it.",
      "Why do you think an old journal is the key to understanding this mystery? Share your own thoughts."],
  h: ["옴리는 무엇을 찾아내어 수수께끼를 밝혀내나요?",
      "일기장처럼 오래된 물건에서 놀라운 사실을 발견한 적이 있나요? 설명해 보세요.",
      "오래된 일기장이 이 수수께끼를 이해하는 열쇠가 되는 이유는 무엇일까요? 내 생각을 적어 보세요."] };
ACT["S4281"] = { s: "Omri and his father try to go back 200 years to the time of their friend, Little Bear, whose tribe is in grave danger.",
  q: ["Why do Omri and his father want to travel back 200 years?",
      "If you could travel back in time to help someone in danger, when would you go?",
      "Why do you think it is important for Omri to help Little Bear's tribe even across 200 years of time? Share your own thoughts."],
  h: ["옴리와 아버지는 왜 200년 전으로 돌아가려고 하나요?",
      "위험에 처한 누군가를 돕기 위해 과거로 갈 수 있다면 언제로 가고 싶나요?",
      "200년이라는 시간을 뛰어넘어서라도 옴리가 리틀 베어의 부족을 돕는 것이 중요한 이유는 무엇일까요? 내 생각을 적어 보세요."] };
ACT["S4282"] = { s: "The Ingalls family is snug in their Wisconsin house in spite of blizzards, wolves, and the lonely forest.",
  q: ["What dangers does the Ingalls family face around their Wisconsin home?",
      "Have you ever felt safe and cozy at home even when it was stormy or scary outside? Describe that feeling.",
      "Why do you think the Ingalls family feels snug and safe despite the blizzards and wolves nearby? Share your own thoughts."],
  h: ["잉걸스 가족은 위스콘신 집 주변에서 어떤 위험들을 겪나요?",
      "밖이 폭풍우 치고 무서워도 집 안에서는 안전하고 아늑하다고 느낀 적이 있나요? 그 느낌을 설명해 보세요.",
      "눈보라와 늑대가 가까이 있는데도 잉걸스 가족이 아늑하고 안전하다고 느끼는 이유는 무엇일까요? 내 생각을 적어 보세요."] };
ACT["S4283"] = { s: "Laura and her family journey by covered wagon into Indian territory, and start a farm.",
  q: ["How do Laura and her family travel to start their new farm?",
      "Have you ever moved to a new place or started something completely new? Describe that experience.",
      "Why do you think starting a farm in a new, unfamiliar territory would be both exciting and hard? Share your own thoughts."],
  h: ["로라와 가족은 새 농장을 시작하기 위해 어떻게 이동하나요?",
      "새로운 곳으로 이사하거나 완전히 새로운 일을 시작한 적이 있나요? 그 경험을 설명해 보세요.",
      "낯선 땅에서 농장을 새로 시작하는 것이 신나면서도 힘든 이유는 무엇일까요? 내 생각을 적어 보세요."] };
ACT["S4284"] = { s: "After moving to Minnesota, the Ingalls family encounters a terrible blizzard and a grasshopper plague.",
  q: ["What two disasters does the Ingalls family face after moving to Minnesota?",
      "Have you ever faced two hard things happening close together? Describe what happened.",
      "Why do you think families like the Ingalls kept trying even after facing such big disasters? Share your own thoughts."],
  h: ["미네소타로 이사한 뒤 잉걸스 가족은 어떤 두 가지 재난을 겪나요?",
      "힘든 일 두 가지가 한꺼번에 닥친 적이 있나요? 무슨 일이 있었는지 설명해 보세요.",
      "이렇게 큰 재난을 겪고도 잉걸스 가족 같은 사람들이 계속 노력하는 이유는 무엇일까요? 내 생각을 적어 보세요."] };
ACT["S4285"] = { s: "Ms. Frizzle takes the class on a field trip to the park and they learn about the mini world of microbes.",
  q: ["What do Ms. Frizzle's class learn about on their field trip to the park?",
      "Have you ever learned something surprising about a tiny, invisible world around you? Describe what you learned.",
      "Why do you think it is important to learn about microbes even though we cannot see them? Share your own thoughts."],
  h: ["프리즐 선생님 반 친구들은 공원 현장 학습에서 무엇에 대해 배우나요?",
      "눈에 보이지 않는 작은 세계에 대해 놀라운 사실을 배운 적이 있나요? 무엇을 배웠는지 설명해 보세요.",
      "눈에 보이지 않는 미생물에 대해 배우는 것이 왜 중요할까요? 내 생각을 적어 보세요."] };
ACT["S4286"] = { s: "Ms. Frizzle takes her class to Hawaii to study an active volcano.",
  q: ["Where does Ms. Frizzle take her class to study a volcano?",
      "Have you ever seen a volcano, in real life or in pictures or videos? Describe what you saw.",
      "Why do you think studying an active volcano up close would be both exciting and dangerous? Share your own thoughts."],
  h: ["프리즐 선생님은 화산을 공부하기 위해 반 친구들을 어디로 데려가나요?",
      "실제로나 사진, 영상으로 화산을 본 적이 있나요? 무엇을 보았는지 설명해 보세요.",
      "활화산을 가까이서 연구하는 것이 신나면서도 위험한 이유는 무엇일까요? 내 생각을 적어 보세요."] };
ACT["S4287"] = { s: "Ms. Frizzle's students learn lessons in survival after she accidently turns them into butterflies.",
  q: ["What do the students learn about after being turned into butterflies?",
      "If you were suddenly turned into a butterfly for a day, what do you think would be hardest about it?",
      "Why do you think turning into butterflies helps the students understand survival better than just reading about it? Share your own thoughts."],
  h: ["학생들은 나비로 변한 뒤 무엇에 대해 배우게 되나요?",
      "하루 동안 갑자기 나비로 변한다면 무엇이 가장 힘들 것 같나요?",
      "나비로 직접 변해 보는 것이 책으로만 읽는 것보다 생존에 대해 더 잘 이해하게 해 주는 이유는 무엇일까요? 내 생각을 적어 보세요."] };
ACT["S4288"] = { s: "When he finds a lost beagle in the hills behind his West Virginia home, Marty tries to hide it because its owner is known for a mean-spirited man.",
  q: ["Why does Marty try to hide the beagle he finds?",
      "Have you ever wanted to protect an animal or a person from someone unkind? Describe what you did.",
      "Why do you think Marty is willing to take the risk of hiding the dog from its owner? Share your own thoughts."],
  h: ["마티는 왜 자신이 발견한 비글을 숨기려고 하나요?",
      "불친절한 사람으로부터 동물이나 사람을 지켜 주고 싶었던 적이 있나요? 무엇을 했는지 설명해 보세요.",
      "마티가 위험을 무릅쓰고서라도 강아지를 주인에게서 숨기려는 이유는 무엇일까요? 내 생각을 적어 보세요."] };
ACT["S4289"] = { s: "This book looks closely at the life of legendary aviator Amelia Earhart who became the first woman to fly solo across the Atlantic Ocean.",
  q: ["What amazing thing did Amelia Earhart become the first woman to do?",
      "Is there something you would like to be the first, or among the first, to accomplish? Describe your dream.",
      "Why do you think flying solo across the Atlantic Ocean took such great courage for Amelia Earhart? Share your own thoughts."],
  h: ["아멜리아 에어하트는 여성 최초로 어떤 놀라운 일을 해냈나요?",
      "내가 처음으로, 또는 처음 중 한 명으로 해내고 싶은 일이 있나요? 나의 꿈을 설명해 보세요.",
      "대서양을 혼자 비행하는 데 아멜리아 에어하트에게 그토록 큰 용기가 필요했던 이유는 무엇일까요? 내 생각을 적어 보세요."] };
ACT["S4290"] = { s: "This book covers the life of Anne Frank before the secret annex. Readers can look closely at what life was like in hiding and the legacy of her diary.",
  q: ["What does this book tell about Anne Frank's life before she went into hiding?",
      "Have you ever kept a diary or journal to write down your thoughts and feelings? Describe your experience.",
      "Why do you think Anne Frank's diary became such an important legacy? Share your own thoughts."],
  h: ["이 책은 안네 프랑크가 숨어 지내기 전의 삶에 대해 무엇을 이야기하나요?",
      "생각이나 감정을 적는 일기를 써 본 적이 있나요? 나의 경험을 설명해 보세요.",
      "안네 프랑크의 일기가 그토록 중요한 유산이 된 이유는 무엇일까요? 내 생각을 적어 보세요."] };
ACT["S4291"] = { s: "This book examines the life of Benjamin Franklin, who discovered that lightning is electricity.",
  q: ["What important discovery about lightning did Ben Franklin make?",
      "Have you ever been curious about how something in nature, like lightning, actually works? Describe your question.",
      "Why do you think Ben Franklin's discovery about lightning was so important? Share your own thoughts."],
  h: ["벤저민 프랭클린은 번개에 대해 어떤 중요한 사실을 발견했나요?",
      "번개처럼 자연 속의 무언가가 어떻게 작동하는지 궁금했던 적이 있나요? 나의 궁금증을 설명해 보세요.",
      "번개에 대한 프랭클린의 발견이 그토록 중요했던 이유는 무엇일까요? 내 생각을 적어 보세요."] };
ACT["S4292"] = { s: "This book presents the life of Daniel Boone, who is well-known for opening up the West to settlers through Kentucky.",
  q: ["What is Daniel Boone well known for doing?",
      "If you could open up a new path or place for other people to explore, where would it be?",
      "Why do you think opening up new land for settlers made Daniel Boone so famous? Share your own thoughts."],
  h: ["대니얼 분은 무엇으로 유명한가요?",
      "다른 사람들이 탐험할 수 있도록 새로운 길이나 장소를 열어 줄 수 있다면 어디를 열고 싶나요?",
      "정착민들을 위해 새로운 땅을 개척한 것이 대니얼 분을 그토록 유명하게 만든 이유는 무엇일까요? 내 생각을 적어 보세요."] };
ACT["S4293"] = { s: "This book is a biography of Eleanor Roosevelt, who served as First Lady for the longest time, and who changed the role of First Lady forever.",
  q: ["How did Eleanor Roosevelt change the role of First Lady?",
      "Have you ever changed how a job or role is done, even in a small way, like at school or home? Describe it.",
      "Why do you think Eleanor Roosevelt wanted to change what a First Lady could do? Share your own thoughts."],
  h: ["엘리너 루스벨트는 영부인의 역할을 어떻게 바꾸어 놓았나요?",
      "학교나 집에서 어떤 역할을 하는 방식을 작게나마 바꿔 본 적이 있나요? 설명해 보세요.",
      "엘리너 루스벨트가 영부인이 할 수 있는 일을 바꾸고 싶어 한 이유는 무엇일까요? 내 생각을 적어 보세요."] };
ACT["S4294"] = { s: "This book looks closely at the life of Elvis Presley, who changed popular music forever, ushering in the age of rock and roll.",
  q: ["What kind of music did Elvis Presley help bring to the world?",
      "What is your favorite kind of music, and why do you enjoy it?",
      "Why do you think Elvis Presley's music changed popular music so much? Share your own thoughts."],
  h: ["엘비스 프레슬리는 세상에 어떤 음악을 가져다주었나요?",
      "내가 가장 좋아하는 음악 종류는 무엇이고, 왜 좋아하나요?",
      "엘비스 프레슬리의 음악이 대중음악을 그토록 많이 바꾼 이유는 무엇일까요? 내 생각을 적어 보세요."] };
ACT["S4295"] = { s: "This book presents the life of Portuguese explorer Ferdinand Magellan, who set out from Spain to circumnavigate the world in 1519.",
  q: ["What was Ferdinand Magellan trying to do when he set out from Spain?",
      "If you could sail around the world like Magellan, what part of the journey would excite you most?",
      "Why do you think circumnavigating the world in 1519 was such a dangerous and difficult goal? Share your own thoughts."],
  h: ["페르디난드 마젤란은 스페인을 떠날 때 무엇을 하려고 했나요?",
      "마젤란처럼 세계를 배로 한 바퀴 돌 수 있다면 여정의 어느 부분이 가장 설렐 것 같나요?",
      "1519년에 세계를 한 바퀴 도는 것이 그토록 위험하고 어려운 목표였던 이유는 무엇일까요? 내 생각을 적어 보세요."] };
ACT["S4296"] = { s: "This is a biography of Harriet Tubman, who escaped slavery and helped many other slaves get to freedom on the Underground Railroad.",
  q: ["What did Harriet Tubman do to help other enslaved people find freedom?",
      "Have you ever helped someone else even when it was risky for you? Describe what you did.",
      "Why do you think Harriet Tubman kept going back to help others, even after she herself was free? Share your own thoughts."],
  h: ["해리엇 터브먼은 다른 노예들이 자유를 찾도록 어떻게 도왔나요?",
      "나에게 위험이 따르더라도 다른 사람을 도운 적이 있나요? 무엇을 했는지 설명해 보세요.",
      "해리엇 터브먼이 자신이 자유를 얻은 뒤에도 계속 다시 돌아가 다른 사람들을 도운 이유는 무엇일까요? 내 생각을 적어 보세요."] };
ACT["S4297"] = { s: "This book presents the life of Helen Keller, who achieved success and fame despite being blind and deaf.",
  q: ["What did Helen Keller achieve despite being blind and deaf?",
      "Have you ever kept trying at something even though it seemed very hard? Describe what you did.",
      "Why do you think Helen Keller's success is such an inspiring story for many people? Share your own thoughts."],
  h: ["헬렌 켈러는 앞을 보지 못하고 듣지 못하면서도 무엇을 이루어 냈나요?",
      "아주 어려워 보이는 일이라도 계속 도전한 적이 있나요? 무엇을 했는지 설명해 보세요.",
      "헬렌 켈러의 성공이 많은 사람에게 그토록 감동을 주는 이유는 무엇일까요? 내 생각을 적어 보세요."] };
ACT["S4298"] = { s: "This book covers the story of the ancient Egyptian ruler King Tut and the discovery of his tomb.",
  q: ["What discovery does this book describe about King Tut?",
      "Have you ever been fascinated by ancient history or old discoveries? Describe what interests you.",
      "Why do you think the discovery of King Tut's tomb was such a big event? Share your own thoughts."],
  h: ["이 책은 투탕카멘 왕에 대한 어떤 발견을 이야기하나요?",
      "고대 역사나 오래된 발견에 흥미를 느낀 적이 있나요? 무엇에 관심이 있는지 설명해 보세요.",
      "투탕카멘 왕의 무덤을 발견한 것이 그토록 큰 사건이었던 이유는 무엇일까요? 내 생각을 적어 보세요."] };
ACT["S4299"] = { s: "This book presents the life of Leonardo da Vinci, who lived as a gifted painter, talented musician, and dedicated inventor.",
  q: ["What different talents did Leonardo da Vinci have, according to this book?",
      "Do you have more than one talent or interest, like painting, music, or inventing? Describe them.",
      "Why do you think being skilled in so many different areas helped Leonardo da Vinci become so famous? Share your own thoughts."],
  h: ["이 책에 따르면 레오나르도 다 빈치는 어떤 다양한 재능을 가지고 있었나요?",
      "그림, 음악, 발명처럼 나도 하나 이상의 재능이나 관심사가 있나요? 설명해 보세요.",
      "이렇게 여러 분야에서 뛰어났던 것이 레오나르도 다 빈치를 그토록 유명하게 만든 이유는 무엇일까요? 내 생각을 적어 보세요."] };
