// 간이 학습 질문 — Book No. S43 묶음. 사람이 아니라 AI 가 한 번 쓰고 굳힌 파일이다.
window.ACT = window.ACT || {};
var ACT = window.ACT;
ACT["S4300"] = { s: "This is a biography of Sacagawea, who accompanied explorers Lewis and Clark on their expedition in the early 1800s.",
  q: ["This book is about Sacagawea, who joined Lewis and Clark's expedition in the early 1800s. What do you think was the hardest part of traveling with explorers into unknown land?",
      "Have you ever traveled somewhere you had never been before? What did you take with you, and how did you feel?",
      "If you could join an expedition to explore someplace unknown today, where would you want to go, and why?"],
  h: ["이 책은 1800년대 초 루이스와 클라크의 탐험대와 함께한 새커거위아 이야기예요. 낯선 땅으로 떠나는 탐험에서 가장 힘든 점은 무엇이었을까요?",
      "한 번도 가 본 적 없는 곳으로 여행을 떠나 본 적이 있나요? 무엇을 챙겼고, 기분이 어땠나요?",
      "오늘날 내가 알려지지 않은 곳을 탐험하는 여행에 함께할 수 있다면, 어디로 가고 싶고 그 이유는 무엇인가요?"] };
ACT["S4301"] = { s: "This book explains everything about the world's beloved English rock band Beatles.",
  q: ["This book explains everything about the Beatles, a beloved English rock band. What is one thing about a famous band or musician that makes you curious?",
      "Do you have a favorite song or band? What do you like about it?",
      "If you could ask the Beatles one question, what would you ask them?"],
  h: ["이 책은 사랑받는 영국 록 밴드 비틀즈에 대한 모든 것을 설명해요. 유명한 밴드나 음악가에 대해 궁금한 점 한 가지는 무엇인가요?",
      "내가 가장 좋아하는 노래나 밴드가 있나요? 무엇이 좋은가요?",
      "비틀즈에게 한 가지 질문을 할 수 있다면 무엇을 묻고 싶나요?"] };
ACT["S4302"] = { s: "This book presents the life of world-famous author William Shakespeare.",
  q: ["This book presents the life of William Shakespeare, a world-famous author. What do you think it takes for a writer to become world-famous?",
      "Have you ever written a story, poem, or play of your own? What was it about?",
      "If you wrote a play that people would remember hundreds of years from now, what would it be about?"],
  h: ["이 책은 세계적으로 유명한 작가 윌리엄 셰익스피어의 삶을 보여줘요. 작가가 세계적으로 유명해지려면 무엇이 필요하다고 생각하나요?",
      "이야기나 시, 연극을 직접 써 본 적이 있나요? 무엇에 대한 것이었나요?",
      "수백 년 뒤에도 사람들이 기억할 연극을 쓴다면 무엇에 대해 쓰고 싶나요?"] };
ACT["S4303"] = { s: "As they are about to go on stage, Joe, Fred, and Sam are transported back to the time of Zeus and the other gods in Greek mythology, who, strangely enough, behave much as the characters in the trio's class play.",
  q: ["What do you think Joe, Fred, and Sam felt when they were suddenly transported back to the time of Zeus and the Greek gods?",
      "Have you ever read or heard a story about Greek gods before?",
      "If you were transported into a story you know, which story would you choose?"],
  h: ["조, 프레드, 샘이 갑자기 제우스와 그리스 신들의 시대로 옮겨졌을 때 어떤 기분이었을까요?",
      "그리스 신들에 대한 이야기를 읽거나 들어 본 적이 있나요?",
      "내가 아는 이야기 속으로 들어갈 수 있다면 어떤 이야기를 고르고 싶나요?"] };
ACT["S4304"] = { s: "Paulina and the Thea Sisters journey to Peru to find their missing archaeologist friend, but as they ascend the Andes Mountains, the sisters find clues that lead them to a mysterious hidden city.",
  q: ["Paulina and the Thea Sisters travel through the Andes Mountains searching for their missing friend. What do you think makes searching for someone in the mountains so difficult?",
      "Have you ever looked for something or someone that was hard to find? What did you do?",
      "If you discovered a mysterious hidden city, what do you imagine it would look like inside?"],
  h: ["파울리나와 테아 자매는 사라진 친구를 찾아 안데스 산맥을 오르며 여행해요. 산속에서 누군가를 찾는 일이 왜 어려울 것 같나요?",
      "찾기 힘든 것이나 사람을 찾아본 적이 있나요? 그때 나는 어떻게 했나요?",
      "신비로운 숨겨진 도시를 발견한다면, 그 안이 어떤 모습일지 상상해서 적어 보세요."] };
ACT["S4305"] = { s: "This book introduces some constellations that can be seen from the Earth and the location of our solar system in the Milky Way galaxy.",
  q: ["This book introduces constellations we can see from Earth and where our solar system is in the Milky Way. What constellation or star fact would you like to learn more about?",
      "Have you ever looked up at the night sky and tried to find stars or shapes? What did you see?",
      "If you could name a new constellation, what shape would you choose and what would you call it?"],
  h: ["이 책은 지구에서 볼 수 있는 별자리와 우리 태양계가 은하수 안에서 어디에 있는지 알려줘요. 별이나 별자리에 대해 더 알고 싶은 것은 무엇인가요?",
      "밤하늘을 올려다보며 별이나 모양을 찾아본 적이 있나요? 무엇을 보았나요?",
      "내가 새로운 별자리를 이름 짓는다면 어떤 모양을 고르고 무엇이라 부르고 싶나요?"] };
ACT["S4306"] = { s: "Amber's mother and Max set up their wedding date and prepare to buy a house together. On the day when Amber is meant to see a movie with her dad, he goes out on a date instead. Kids who have parents, who are still together, make Amber green with envy.",
  q: ["Amber feels envious of kids whose parents are still together. What do you think Amber might be feeling on the inside during all these changes in her family?",
      "Have you ever felt jealous or envious of someone else? What happened, and how did you deal with it?",
      "If you were Amber's friend, what would you say to help her feel better?"],
  h: ["앰버는 부모님이 여전히 함께 사는 친구들을 보며 부러움을 느껴요. 가족에게 이런 변화들이 일어나는 동안 앰버는 마음속으로 어떤 기분이었을까요?",
      "누군가를 부러워하거나 질투해 본 적이 있나요? 무슨 일이 있었고, 어떻게 그 마음을 다루었나요?",
      "내가 앰버의 친구라면 앰버의 기분이 나아지도록 어떤 말을 해 주고 싶나요?"] };
ACT["S4309"] = { s: "Each of five children lucky enough to discover an entry ticket into Mr. Willy Wonka's mysterious chocolate factory takes advantage of the situation in their own way.",
  q: ["Each of the five children who find a ticket into the chocolate factory acts differently once they get inside. Why do you think people react in such different ways to the same exciting opportunity?",
      "If you found a golden ticket to a magical factory, how do you think you would act once you got inside?",
      "What kind of amazing factory would you want to visit, and what would you want to see there?"],
  h: ["초콜릿 공장에 들어가는 티켓을 발견한 다섯 아이는 안에서 저마다 다르게 행동해요. 같은 신나는 기회를 두고 사람마다 이렇게 다르게 반응하는 이유는 무엇일까요?",
      "마법 같은 공장으로 들어가는 황금 티켓을 발견한다면, 안에 들어가서 나는 어떻게 행동할 것 같나요?",
      "내가 가 보고 싶은 놀라운 공장은 어떤 곳이고, 그곳에서 무엇을 보고 싶나요?"] };
ACT["S4310"] = { s: "On her first day of a new year at The Princess Academy, Princess Charlotte is accused of stealing a magical bouquet of roses by a rather unpleasant pair of new students.",
  q: ["Princess Charlotte is accused of stealing something she did not take. How do you think it feels to be blamed for something you didn't do?",
      "Has anyone ever accused you of something unfair? What did you do about it?",
      "If you were Princess Charlotte, how would you prove that you did not steal the roses?"],
  h: ["샬롯 공주는 하지도 않은 일로 도둑이라는 의심을 받아요. 하지 않은 일로 오해를 받으면 기분이 어떨까요?",
      "누군가 나에게 억울하게 잘못을 뒤집어씌운 적이 있나요? 그때 나는 어떻게 했나요?",
      "내가 샬롯 공주라면, 장미를 훔치지 않았다는 것을 어떻게 증명하고 싶나요?"] };
ACT["S4311"] = { s: "Princess Sophia encourages a shy prince to dance with her at the Princes' Academy ball.",
  q: ["Princess Sophia encourages a shy prince to dance with her. Why do you think it can be hard for someone to do something new when they feel shy?",
      "Have you ever helped a shy friend feel brave enough to try something? What did you do?",
      "If you were at a ball and saw someone standing alone and shy, what would you do?"],
  h: ["소피아 공주는 부끄러워하는 왕자에게 함께 춤을 추자고 용기를 줘요. 부끄러움을 느낄 때 새로운 것을 시도하기가 왜 어려울까요?",
      "부끄러워하는 친구가 용기를 내도록 도와준 적이 있나요? 그때 나는 무엇을 했나요?",
      "무도회에서 혼자 부끄러워하는 사람을 본다면 나는 어떻게 하고 싶나요?"] };
ACT["S4312"] = { s: "The princesses come down with terrible colds and must take the floral-bouquet design test in the infirmary.",
  q: ["The princesses have to take an important test even while they are sick with colds. How do you think it feels to try your best at something while you don't feel well?",
      "Have you ever had to do something important, like a test or a game, while you were sick or tired? What happened?",
      "If you designed your own flower bouquet for a test like this, what flowers or colors would you choose?"],
  h: ["공주들은 심한 감기에 걸린 채로 중요한 시험을 치러야 해요. 몸이 안 좋을 때 최선을 다해 무언가를 해야 하면 기분이 어떨까요?",
      "아프거나 피곤할 때 시험이나 경기처럼 중요한 일을 해야 했던 적이 있나요? 어떻게 되었나요?",
      "이런 시험을 위해 내가 직접 꽃다발을 디자인한다면 어떤 꽃과 색을 고르고 싶나요?"] };
ACT["S4313"] = { s: "Princess Charlotte causes an accident that ruins the dresses of her new roommates, and unless something can be done, none of them will be able to attend the Birthday Ball.",
  q: ["Princess Charlotte accidentally ruins her roommates' dresses before an important ball. What do you think Charlotte should do to make things right?",
      "Have you ever made a mistake that affected your friends? How did you fix it?",
      "If the dresses could not be fixed in time, what idea would you suggest so everyone could still go to the ball?"],
  h: ["샬롯 공주는 실수로 룸메이트들의 드레스를 망가뜨려 버려요. 중요한 무도회를 앞두고요. 샬롯은 이 일을 바로잡기 위해 무엇을 해야 할까요?",
      "내 실수로 친구들이 곤란해진 적이 있나요? 그 일을 어떻게 해결했나요?",
      "드레스를 제시간에 고칠 수 없다면, 다 함께 무도회에 갈 수 있는 방법으로 어떤 생각을 내놓고 싶나요?"] };
ACT["S4314"] = { s: "Princess Katie and the other princesses must make one carefully chosen wish in order to win a chance to lead the Royal Parade.",
  q: ["Princess Katie has only one wish to use wisely. If you could make just one careful wish to win something special, what would you wish for?",
      "Have you ever had to choose just one thing carefully, knowing you couldn't change your mind? What did you choose?",
      "Why do you think it is important to think carefully before making a wish?"],
  h: ["케이티 공주는 신중하게 고른 소원 하나만 쓸 수 있어요. 특별한 것을 얻기 위해 신중하게 소원 하나를 빈다면 나는 무엇을 빌고 싶나요?",
      "마음을 바꿀 수 없다는 걸 알면서 한 가지만 신중하게 골라야 했던 적이 있나요? 무엇을 골랐나요?",
      "소원을 빌기 전에 신중하게 생각하는 것이 왜 중요하다고 생각하나요?"] };
ACT["S4315"] = { s: "As Princess Sophia and her friends design and create their own ball gowns for the Princess Academy Surprise, a group of snobs plots to ruin them.",
  q: ["Princess Sophia and her friends work hard to design their own gowns, but a group of snobs plots to ruin them. Why do you think some people try to ruin others' hard work?",
      "Have you ever worked hard on making or creating something? How did you feel about it?",
      "If you were Sophia, how would you protect something you worked hard to make?"],
  h: ["소피아 공주와 친구들은 직접 드레스를 만들려고 애쓰지만, 심술궂은 무리가 이를 망치려고 해요. 어떤 사람들은 왜 남이 애써 만든 것을 망치려고 할까요?",
      "무언가를 만들기 위해 열심히 애써 본 적이 있나요? 그때 기분이 어땠나요?",
      "내가 소피아라면, 열심히 만든 것을 어떻게 지키고 싶나요?"] };
ACT["S4316"] = { s: "Princess Emily and her friends at the Royal Academy receive their silver sashes after Emily helps horrible twins, Gruella and Diamonde, make up following a fight.",
  q: ["Princess Emily helps two twins make up after a fight. What do you think Emily might have said or done to help them make peace?",
      "Have you ever helped two friends who were fighting become friends again? What did you do?",
      "Why do you think helping others solve their problems is an important thing to do?"],
  h: ["에밀리 공주는 싸운 쌍둥이 자매가 화해하도록 도와줘요. 에밀리는 그들이 화해하도록 어떤 말이나 행동을 했을 것 같나요?",
      "싸운 친구 두 명이 다시 친해지도록 도와준 적이 있나요? 그때 나는 무엇을 했나요?",
      "다른 사람의 문제를 해결하도록 돕는 일이 왜 중요하다고 생각하나요?"] };
ACT["S4317"] = { s: "Princess Alice is determined to take responsibility when she causes another princess to drop a vase during the school's preparation for the term garden party.",
  q: ["Princess Alice takes responsibility after causing an accident. Why do you think it can be hard to admit a mistake, even by accident?",
      "Have you ever had to take responsibility for something you accidentally caused? What did you do?",
      "What do you think happens to a friendship when someone takes responsibility instead of blaming others?"],
  h: ["앨리스 공주는 사고를 일으킨 뒤 책임을 지려고 해요. 실수로 벌어진 일이라도 잘못을 인정하기가 왜 어려울까요?",
      "실수로 벌어진 일을 내가 책임져야 했던 적이 있나요? 그때 나는 어떻게 했나요?",
      "다른 사람을 탓하지 않고 스스로 책임을 지면 우정에 어떤 일이 생길 것 같나요?"] };
ACT["S4318"] = { s: "Princess Olivia is chosen to demonstrate the best way to cross a puddle by stepping on a prince's cape, with a real, live prince, but the jealous Diamonde isn't going to let Olivia outshine her.",
  q: ["A jealous classmate does not want Princess Olivia to outshine her. Why do you think jealousy can make people act unkindly toward others?",
      "Have you ever felt jealous when someone else did something impressive? How did you handle that feeling?",
      "If you were Olivia, how would you respond to someone trying to stop you from succeeding?"],
  h: ["질투심 많은 친구는 올리비아 공주가 자신보다 돋보이는 것을 못마땅해해요. 질투심은 왜 사람을 못되게 행동하게 만들까요?",
      "다른 사람이 멋진 일을 해냈을 때 질투를 느껴 본 적이 있나요? 그 마음을 어떻게 다루었나요?",
      "내가 올리비아라면, 나를 방해하려는 사람에게 어떻게 대처하고 싶나요?"] };
ACT["S4319"] = { s: "When Goldie the Sunshine Fairy's magic feather disappears, Wetherbury becomes so hot and sunny that the cornfields turn into popcorn.",
  q: ["When Goldie's magic feather disappears, the cornfields in Wetherbury turn into popcorn from the heat! What do you think Rachel and Kirsty need to do to fix this problem?",
      "Have you ever experienced very hot weather? What did it feel like, and what did you do to cool down?",
      "If your town suddenly got as hot as Wetherbury, what funny things do you imagine might happen?"],
  h: ["골디의 마법 깃털이 사라지자 날씨가 너무 뜨거워져서 웨더버리의 옥수수밭이 팝콘으로 변해 버려요. 레이첼과 커스티는 이 문제를 해결하기 위해 무엇을 해야 할까요?",
      "아주 더운 날씨를 겪어 본 적이 있나요? 어떤 느낌이었고, 시원해지려고 무엇을 했나요?",
      "우리 동네가 갑자기 웨더버리처럼 뜨거워진다면 어떤 재미있는 일이 벌어질지 상상해서 적어 보세요."] };
ACT["S4320"] = { s: "A big bash for King Oberon and Queen Titania is underway in Fairyland. The Party Fairies keep everything running smoothly, until Jack Frost's goblins steal their magic party bags.",
  q: ["Jack Frost's goblins steal the Party Fairies' magic bags right before a big celebration. Why do you think the goblins wanted to ruin the party?",
      "Have you ever helped plan or prepare for a party or celebration? What was your job?",
      "If you were a Party Fairy, what would you put in your magic party bag?"],
  h: ["잭 프로스트의 고블린들은 큰 축제를 앞두고 파티 요정들의 마법 가방을 훔쳐요. 고블린들은 왜 파티를 망치고 싶어 했을까요?",
      "파티나 축제를 준비하거나 도와준 적이 있나요? 그때 내가 맡은 일은 무엇이었나요?",
      "내가 파티 요정이라면 마법 가방 안에 무엇을 넣고 싶나요?"] };
ACT["S4321"] = { s: "Melodie the Music Fairy's magic is missing, and party music is hitting all the wrong notes. Rachel and Kirsty have to change the goblins' tune.",
  q: ["Without Melodie's magic, the party music sounds all wrong. Why do you think music can make such a big difference at a celebration?",
      "Do you play an instrument or enjoy singing? What kind of music makes you feel happy?",
      "If you had to fix music that sounded all wrong, what would you do first?"],
  h: ["멜로디의 마법이 사라지자 파티 음악이 온통 엉망이 되어 버려요. 음악은 왜 축제 분위기에 그렇게 큰 영향을 줄까요?",
      "악기를 연주하거나 노래 부르는 것을 좋아하나요? 어떤 음악을 들으면 행복해지나요?",
      "엉망이 된 음악을 고쳐야 한다면 나는 가장 먼저 무엇을 하고 싶나요?"] };
ACT["S4322"] = { s: "Kirsty's friend Charlotte is having a birthday party, but everyone's pretty party outfits are ruined. Phoebe the Fashion Fairy has to track down her magic bag fast.",
  q: ["Everyone's party outfits get ruined right before Charlotte's birthday party. How do you think the girls felt when they saw their outfits were ruined?",
      "Has something you were excited to wear ever gotten ruined or lost? What did you do?",
      "If your outfit got ruined right before a party, what would you wear instead?"],
  h: ["샬럿의 생일 파티를 앞두고 모두의 예쁜 파티 옷이 망가져 버려요. 옷이 망가진 걸 보았을 때 아이들은 어떤 기분이었을까요?",
      "입고 싶어서 기대하던 옷이 망가지거나 없어진 적이 있나요? 그때 나는 어떻게 했나요?",
      "파티를 앞두고 내 옷이 망가진다면 대신 무엇을 입고 싶나요?"] };
ACT["S4323"] = { s: "The goblins are after Jasmin's magic party bag, and Rachel and Kirsty are determined to get things wrapped up in time for the block party.",
  q: ["Rachel and Kirsty race against time to get the party ready. Why do you think it can be stressful to prepare for something with a deadline?",
      "Have you ever had to finish something quickly before a certain time? How did you manage it?",
      "What would you do first if you only had a short time to get a whole party ready?"],
  h: ["레이첼과 커스티는 시간에 쫓기며 파티를 준비해요. 정해진 시간 안에 무언가를 끝내야 하면 왜 스트레스를 받을까요?",
      "정해진 시간 안에 무언가를 서둘러 끝내야 했던 적이 있나요? 그때 나는 어떻게 해냈나요?",
      "짧은 시간 안에 파티 전체를 준비해야 한다면 나는 가장 먼저 무엇을 할까요?"] };
ACT["S4324"] = { s: "A loose lightning bolt could cause terrible trouble in Wetherbury. Can Storm the Lightning Fairy find her magic feather and get things under control before it is too late?",
  q: ["A loose lightning bolt threatens to cause terrible trouble in Wetherbury. Why do you think lightning can be both amazing and dangerous?",
      "Have you ever seen a thunderstorm with lightning? How did it make you feel?",
      "If you had to stop a dangerous lightning bolt before it caused trouble, what would you do?"],
  h: ["웨더버리에서는 풀려난 번개 하나가 큰 사고를 일으킬 위기에 처해요. 번개는 왜 멋지기도 하고 위험하기도 할까요?",
      "번개가 치는 천둥번개를 본 적이 있나요? 그때 기분이 어땠나요?",
      "위험한 번개가 사고를 일으키기 전에 막아야 한다면 나는 무엇을 하고 싶나요?"] };
ACT["S4325"] = { s: "Wetherbury is all fogged up. Nobody can see where they're going! Could Evie the Mist Fairy's magic feather be to blame?",
  q: ["Wetherbury is so foggy that nobody can see where they are going. What do you think it would be like to walk around in very thick fog?",
      "Have you ever been somewhere very foggy or hard to see in? What did you do?",
      "If you got lost in thick fog, what would you do to find your way?"],
  h: ["웨더버리가 온통 안개로 뒤덮여서 아무도 길을 볼 수 없게 돼요. 짙은 안개 속을 걸어 다닌다면 어떤 느낌일까요?",
      "안개가 짙어서 앞이 잘 안 보이는 곳에 가 본 적이 있나요? 그때 나는 어떻게 했나요?",
      "짙은 안개 속에서 길을 잃는다면 길을 찾기 위해 무엇을 하고 싶나요?"] };
ACT["S4326"] = { s: "Rachel and Kirsty have only one magic feather left to find, and it belongs to Hayley the Rain Fairy.",
  q: ["This is the last magic feather Rachel and Kirsty need to find. How do you think they feel now that they are almost done with their big search?",
      "Have you ever almost finished a long task or search? How did you feel as you got close to the end?",
      "What kind of weather do you think Hayley the Rain Fairy's magic controls, and what problems might happen without it?"],
  h: ["이것은 레이첼과 커스티가 찾아야 할 마지막 마법 깃털이에요. 긴 탐색을 거의 끝마친 지금 둘은 어떤 기분일까요?",
      "길게 이어진 일이나 탐색을 거의 끝내 본 적이 있나요? 끝이 다가올 때 기분이 어땠나요?",
      "헤일리라는 비의 요정의 마법은 어떤 날씨를 다스릴 것 같고, 그게 없으면 어떤 문제가 생길까요?"] };
ACT["S4327"] = { s: "Abigail the Breeze Fairy's magic feather is missing. Then, the Summer Festival changes into a windy mess!",
  q: ["The Summer Festival turns into a windy mess when Abigail's magic feather goes missing. What kind of problems do you think strong wind could cause at an outdoor festival?",
      "Have you ever been outside on a very windy day? What happened?",
      "If you were planning an outdoor festival, how would you prepare for bad weather like wind?"],
  h: ["애비게일의 마법 깃털이 사라지자 여름 축제가 바람으로 엉망이 돼요. 야외 축제에서 강한 바람은 어떤 문제를 일으킬 수 있을까요?",
      "바람이 아주 세게 부는 날 밖에 나가 본 적이 있나요? 그때 무슨 일이 있었나요?",
      "야외 축제를 계획한다면 바람 같은 나쁜 날씨에 대비해 어떻게 준비하고 싶나요?"] };
ACT["S4328"] = { s: "When everyone in Wetherbury becomes gloomy, Rachel and Kirsty think the Cloud Feather might be to blame.",
  q: ["Everyone in Wetherbury becomes gloomy at once. Why do you think the weather can affect how people feel?",
      "Has cloudy or gray weather ever made you feel a certain way? How did it affect your mood?",
      "What would you do to cheer up a whole town that suddenly felt gloomy?"],
  h: ["웨더버리의 모든 사람이 한꺼번에 우울해져요. 날씨는 왜 사람의 기분에 영향을 줄까요?",
      "흐리고 회색빛인 날씨가 내 기분에 영향을 준 적이 있나요? 어떤 영향을 주었나요?",
      "갑자기 온 마을이 우울해진다면, 마을을 기운 나게 하기 위해 나는 무엇을 하고 싶나요?"] };
ACT["S4329"] = { s: "Party decorations have lost their sparkle, all because of a grumbling goblin. Rachel and Kirsty are determined to help Grace track him down.",
  q: ["A grumbling goblin causes the party decorations to lose their sparkle. Why do you think the goblin might be grumbling and causing trouble?",
      "Have you ever helped fix something that lost its sparkle or excitement, like a plan gone wrong? What did you do?",
      "If you had to track down a mischievous goblin, what clues would you look for?"],
  h: ["투덜거리는 고블린 때문에 파티 장식들이 반짝임을 잃어버려요. 그 고블린은 왜 투덜거리며 말썽을 부렸을까요?",
      "반짝임이나 신남을 잃어버린 계획을 다시 고쳐 본 적이 있나요? 그때 나는 무엇을 했나요?",
      "장난꾸러기 고블린을 찾아내야 한다면 나는 어떤 단서를 찾아보고 싶나요?"] };
ACT["S4330"] = { s: "It looks like Rachel and Kirsty's outdoor picnic won't be full of fun or games because Polly is missing her party bag.",
  q: ["Without Polly's party bag, the picnic might not be fun anymore. What do you think makes a picnic or outdoor gathering really fun?",
      "What is your favorite game or activity to play at a picnic or outdoor party?",
      "If the fun games and activities disappeared from a picnic, what would you do to make it enjoyable again?"],
  h: ["폴리의 파티 가방이 없으면 소풍이 더 이상 즐겁지 않을 수도 있어요. 소풍이나 야외 모임을 정말 즐겁게 만드는 것은 무엇이라고 생각하나요?",
      "소풍이나 야외 파티에서 내가 가장 좋아하는 놀이나 활동은 무엇인가요?",
      "소풍에서 재미있는 놀이와 활동이 사라진다면, 다시 즐겁게 만들기 위해 나는 무엇을 하고 싶나요?"] };
ACT["S4333"] = { s: "As her mother prepares to be a contestant on the THE $20,000 PYRAMID, a girl tries to make sense of mysterious notes received from an anonymous source that seems to defy the laws of time and space.",
  q: ["The girl receives mysterious notes that seem to defy the laws of time and space. If you received a strange, unexplainable note, how would you feel and what would you do?",
      "Has your family ever prepared for something exciting, like a contest or big event? What was it like?",
      "What do you think it would mean for a note to defy the laws of time and space?"],
  h: ["여자아이는 시간과 공간의 법칙을 뛰어넘는 것처럼 보이는 이상한 쪽지들을 받아요. 설명할 수 없는 이상한 쪽지를 받는다면 어떤 기분이 들고 무엇을 하고 싶나요?",
      "우리 가족이 대회나 큰 행사처럼 신나는 일을 준비해 본 적이 있나요? 어떤 느낌이었나요?",
      "쪽지가 시간과 공간의 법칙을 뛰어넘는다는 것은 어떤 의미일지 생각해서 적어 보세요."] };
ACT["S4334"] = { s: "On a summer visit to her grandmother's cottage by the ocean, twelve-year-old Martha has multiple viewpoints.",
  q: ["Martha visits her grandmother's cottage by the ocean and experiences things from multiple viewpoints. Why do you think seeing something from more than one point of view can change how we understand it?",
      "Have you ever visited a grandparent's house? What is special about that place to you?",
      "If you spent a summer by the ocean, what would you want to spend most of your time doing?"],
  h: ["마사는 바닷가에 있는 할머니 오두막을 방문하며 여러 시각으로 세상을 바라봐요. 어떤 일을 한 가지 이상의 시각으로 보면 이해가 왜 달라질까요?",
      "할아버지나 할머니 댁에 가 본 적이 있나요? 그곳에는 나에게 어떤 특별한 점이 있나요?",
      "바닷가에서 여름을 보낸다면 대부분의 시간을 무엇을 하며 보내고 싶나요?"] };
ACT["S4341"] = { s: "It's Queen Titania's and King Oberon's 1000th jubilee, and the seven Party Fairies are in charge of making the celebratory party extra-special!",
  q: ["The seven Party Fairies are in charge of making a 1000th jubilee extra-special. What do you think it takes to plan a celebration that big and important?",
      "Have you ever helped celebrate a really big or important anniversary? What made it special?",
      "If you were in charge of planning a huge 1000th celebration, what would you want to include?"],
  h: ["일곱 파티 요정은 1000번째 기념 축제를 아주 특별하게 만드는 일을 맡았어요. 그렇게 크고 중요한 축제를 준비하려면 무엇이 필요할까요?",
      "정말 크고 중요한 기념일을 축하하는 데 함께한 적이 있나요? 무엇이 그 행사를 특별하게 만들었나요?",
      "내가 1000번째 기념 축제를 계획한다면 무엇을 포함하고 싶나요?"] };
ACT["S4342"] = { s: "Three friends walk into the past and find themselves in the unknown world of the dinosaurs.",
  q: ["Three friends suddenly find themselves in the unknown world of dinosaurs. What do you think would be the most exciting and the most scary part of finding yourself among dinosaurs?",
      "If you could travel to the time of dinosaurs, which dinosaur would you most want to see up close?",
      "What would you pack if you knew you were about to walk into the past?"],
  h: ["세 친구는 갑자기 낯선 공룡의 세계로 들어가게 돼요. 공룡들 사이에 있게 된다면 가장 신나는 점과 가장 무서운 점은 무엇일까요?",
      "공룡 시대로 여행을 갈 수 있다면 어떤 공룡을 가까이에서 가장 보고 싶나요?",
      "과거로 걸어 들어갈 것을 안다면 나는 무엇을 챙기고 싶나요?"] };
ACT["S4343"] = { s: "Charlie, Nic, and Ali are taken to Spectre's Isle and a spooky tower. There they search for a legendary ghost and phantom treasure.",
  q: ["Charlie, Nic, and Ali search a spooky tower for a legendary ghost and phantom treasure. What do you think would be scarier — searching for the ghost, or searching for the treasure? Why?",
      "Have you ever explored somewhere that felt spooky or mysterious? What was it like?",
      "If you found phantom treasure in a haunted tower, what do you imagine it would look like?"],
  h: ["찰리, 닉, 앨리는 으스스한 탑에서 전설의 유령과 환영 보물을 찾아요. 유령을 찾는 것과 보물을 찾는 것 중 어느 쪽이 더 무서울 것 같고, 왜 그런가요?",
      "으스스하거나 신비롭게 느껴지는 곳을 탐험해 본 적이 있나요? 그곳은 어땠나요?",
      "귀신 들린 탑에서 환영 보물을 찾는다면 그 보물이 어떤 모습일지 상상해서 적어 보세요."] };
ACT["S4344"] = { s: "This book presents the story of the aliens and different planets.",
  q: ["This book tells the story of aliens and different planets. If you visited a planet full of aliens, what do you think would be the strangest thing you might see?",
      "Have you ever imagined what life on another planet might be like? What did you imagine?",
      "If you designed your own alien for this story, what would it look like and what special power would it have?"],
  h: ["이 책은 외계인들과 여러 행성에 대한 이야기를 담고 있어요. 외계인이 가득한 행성을 방문한다면 가장 이상하게 느껴지는 것은 무엇일까요?",
      "다른 행성에서의 삶이 어떨지 상상해 본 적이 있나요? 무엇을 상상했나요?",
      "내가 이 이야기 속 외계인을 직접 디자인한다면 어떤 모습이고 어떤 특별한 능력을 가지고 있을까요?"] };
ACT["S4345"] = { s: "Paul the Pageboy follows instructions left by an unseen hand and arrives at Craggie Castle. There he has to deal with Sir Vile who rules its downtrodden occupants with a rod of iron.",
  q: ["Paul the Pageboy follows instructions from an unseen hand without knowing who is giving them. Would you follow mysterious instructions from someone you couldn't see? Why or why not?",
      "Have you ever had to be brave and do something even though you weren't sure what would happen?",
      "If you were living under a strict ruler like Sir Vile, what do you think you would do to help the other occupants?"],
  h: ["시동 폴은 누구인지 보이지 않는 손이 남긴 지시를 그대로 따라가요. 나라면 보이지 않는 누군가가 남긴 수상한 지시를 따를 것 같나요? 왜 그런가요?",
      "어떻게 될지 잘 모르면서도 용기를 내어 무언가를 해야 했던 적이 있나요?",
      "사일 경처럼 엄격한 지배자 아래에서 산다면, 다른 사람들을 돕기 위해 나는 무엇을 하고 싶나요?"] };
ACT["S4346"] = { s: "Jack and Emma are visiting Wanda Pharr, and she asks for their help in recovering the ancient mask that has been stolen.",
  q: ["Wanda Pharr asks Jack and Emma to help recover a stolen ancient mask. Why do you think ancient objects like this mask are so important to protect?",
      "Have you ever helped someone find or recover something they lost? What did you do?",
      "If you had to search a lost temple for a stolen treasure, what dangers do you imagine you might face?"],
  h: ["완다 파는 잭과 에마에게 도둑맞은 고대 가면을 되찾는 일을 도와달라고 부탁해요. 이런 고대 유물을 지키는 일이 왜 그렇게 중요할까요?",
      "누군가 잃어버린 것을 찾거나 되찾도록 도와준 적이 있나요? 그때 나는 무엇을 했나요?",
      "잃어버린 사원에서 도둑맞은 보물을 찾아야 한다면 어떤 위험을 맞닥뜨릴 것 같은지 상상해서 적어 보세요."] };
ACT["S4347"] = { s: "When Polly gets captured on the tropical island of Exotika, her friends Annie and Joe start an adventure to rescue her.",
  q: ["Annie and Joe start a dangerous adventure to rescue their captured friend, Polly. What do you think it takes to be brave enough to rescue a friend in danger?",
      "Have you ever helped a friend who was in trouble? What did you do to help?",
      "If you had to rescue a friend from a tropical island, what would you need to plan first?"],
  h: ["애니와 조는 사로잡힌 친구 폴리를 구하기 위해 위험한 모험을 떠나요. 위험에 처한 친구를 구할 만큼 용감해지려면 무엇이 필요할까요?",
      "곤경에 처한 친구를 도와준 적이 있나요? 그때 나는 어떻게 도왔나요?",
      "열대 섬에서 친구를 구해야 한다면 가장 먼저 무엇을 계획해야 할까요?"] };
ACT["S4348"] = { s: "Three friends set off on a ghost hunt in creepy Grimstone Manor when a strange apparition appears in a mirror. Find the truth about the ghost in the mirror.",
  q: ["A strange apparition appears in a mirror, and the three friends set off on a ghost hunt. What do you think you would do if you saw something strange appear in a mirror?",
      "Have you ever felt scared in an old or creepy place? What made it feel that way?",
      "If you had to figure out the truth about a ghost in a mansion, how would you go about investigating it?"],
  h: ["거울 속에서 이상한 형체가 나타나고, 세 친구는 유령을 찾아 나서요. 거울 속에서 이상한 것이 나타난다면 나는 어떻게 할 것 같나요?",
      "오래되거나 으스스한 곳에서 무서움을 느낀 적이 있나요? 무엇 때문에 그렇게 느껴졌나요?",
      "저택에 나타난 유령의 진실을 밝혀내야 한다면 어떻게 조사를 시작하고 싶나요?"] };
ACT["S4349"] = { s: "Two kids get invited to Egypt by their father to join him on his dig. When they arrive, they realize something strange is going on regarding one of the pyramids nearby.",
  q: ["The kids join their father's dig in Egypt and sense something strange is happening near a pyramid. What do you think could make an archaeological dig site feel mysterious or strange?",
      "Have you ever visited or learned about ancient Egypt or pyramids? What interested you most?",
      "If you joined a dig near a pyramid and noticed something strange, what would you do first?"],
  h: ["아이들은 아빠의 발굴 작업에 함께하고, 근처 피라미드에서 이상한 일이 벌어지고 있다는 것을 알아채요. 고고학 발굴 현장이 신비롭거나 이상하게 느껴지려면 무엇이 필요할까요?",
      "고대 이집트나 피라미드에 대해 가 보거나 배워 본 적이 있나요? 가장 흥미로웠던 점은 무엇인가요?",
      "피라미드 근처 발굴에 참여했다가 이상한 것을 알아챈다면, 나는 가장 먼저 무엇을 하고 싶나요?"] };
ACT["S4350"] = { s: "Intrepid Ivor pursues his quest for the all-important Papers and tries to escape from Blood Castle.",
  q: ["Ivor is on a quest for important Papers and must escape from Blood Castle. Why do you think the Papers might be so important that Ivor is willing to risk escaping a dangerous castle for them?",
      "Have you ever had to work hard to get or protect something important to you? What was it?",
      "If you had to plan an escape from a dangerous castle, what would your plan be?"],
  h: ["아이버는 아주 중요한 서류를 찾는 임무를 수행하며 위험한 성에서 탈출하려 해요. 이 서류가 위험한 성 탈출까지 감수할 만큼 왜 그렇게 중요할까요?",
      "나에게 중요한 무언가를 얻거나 지키기 위해 애써 본 적이 있나요? 그것은 무엇이었나요?",
      "위험한 성에서 탈출할 계획을 세워야 한다면, 나의 계획은 무엇일까요?"] };
ACT["S4351"] = { s: "Agent Arthur is trapped on an island and needs help to escape. Rescue Arthur by solving the puzzles.",
  q: ["Agent Arthur is trapped on an island and needs the reader's help to escape by solving puzzles. What kind of puzzle do you think would be the trickiest to solve if you were stranded on an island?",
      "Do you enjoy solving puzzles or riddles? What is your favorite kind?",
      "If you were trapped on an island, what is the first thing you would do to try to get help?"],
  h: ["아서 요원은 섬에 갇혀서 독자가 퍼즐을 풀어 자신을 구출해 주기를 기다려요. 섬에 갇힌다면 어떤 퍼즐이 풀기 가장 까다로울 것 같나요?",
      "퍼즐이나 수수께끼 푸는 것을 좋아하나요? 가장 좋아하는 종류는 무엇인가요?",
      "내가 섬에 갇힌다면 도움을 받기 위해 가장 먼저 무엇을 하고 싶나요?"] };
ACT["S4352"] = { s: "Annie is in her quest to solve the strange mystery of the lost idol to prevent the threat of its ancient curse.",
  q: ["Annie must solve the mystery of the lost idol to prevent an ancient curse. What do you think makes solving an old, ancient mystery so difficult?",
      "Have you ever tried to solve a mystery or figure something out on your own? What was it?",
      "If an ancient curse were real, what do you imagine it could do?"],
  h: ["애니는 오래된 저주의 위협을 막기 위해 잃어버린 신상의 수수께끼를 풀어야 해요. 오래된 수수께끼를 푸는 일은 왜 그렇게 어려울까요?",
      "혼자서 수수께끼를 풀거나 무언가를 알아내려고 해 본 적이 있나요? 무엇이었나요?",
      "고대의 저주가 진짜로 있다면 어떤 일이 벌어질지 상상해서 적어 보세요."] };
ACT["S4353"] = { s: "Agent Arthur sets off on a mission to the frontier town of Hudlum Bay. He finds out that he must dive into the freezing arctic wastes to stop an evil plan.",
  q: ["Agent Arthur must dive into freezing arctic wastes to stop an evil plan. What do you think would be the hardest part about being an agent in such a cold, dangerous place?",
      "Have you ever been somewhere very cold? What did it feel like?",
      "If you had to stop an evil plan in the freezing Arctic, what special gear would you want to bring?"],
  h: ["아서 요원은 사악한 계획을 막기 위해 꽁꽁 언 북극의 황무지로 뛰어들어야 해요. 이렇게 춥고 위험한 곳에서 요원으로 활동하는 것은 어떤 점이 가장 힘들 것 같나요?",
      "아주 추운 곳에 가 본 적이 있나요? 그곳은 어떤 느낌이었나요?",
      "얼어붙은 북극에서 사악한 계획을 막아야 한다면, 어떤 특별한 장비를 챙기고 싶나요?"] };
ACT["S4354"] = { s: "Jay and Ben arrive at a ghostly village that disappears without a trace by dawn. They are led into spooky adventures by a mysterious message.",
  q: ["Jay and Ben find a village that disappears without a trace by dawn. Why do you think a vanishing village would be both exciting and scary to explore?",
      "Have you ever received a mysterious message or note that led you somewhere unexpected? What was it?",
      "If a village near you vanished by morning, what clues would you look for to figure out what happened?"],
  h: ["제이와 벤은 새벽이 되면 흔적도 없이 사라지는 마을을 발견해요. 사라지는 마을을 탐험하는 일은 왜 신나면서도 무서울까요?",
      "예상치 못한 곳으로 이어진 신비로운 메시지나 쪽지를 받아 본 적이 있나요? 무엇이었나요?",
      "우리 동네 근처 마을이 아침이 되면 사라진다면, 무슨 일이 있었는지 알아내기 위해 어떤 단서를 찾고 싶나요?"] };
ACT["S4355"] = { s: "Agent Arthur is on his first mission for the Action Agency. In the tropical jungle, he has to outwit his enemies to survive.",
  q: ["This is Agent Arthur's very first mission, and he must outwit his enemies to survive in the jungle. What do you think would be the biggest challenge of surviving in a tropical jungle?",
      "Have you ever had to think quickly to solve a problem or get out of a tricky situation? What happened?",
      "If this were your first mission as an agent, what skills would you want to have ready?"],
  h: ["이번은 아서 요원의 첫 임무예요. 그는 정글에서 살아남기 위해 적들보다 한 수 앞서야 해요. 열대 정글에서 살아남는 일 중 가장 큰 어려움은 무엇일 것 같나요?",
      "곤란한 상황에서 빠르게 생각해 문제를 풀거나 빠져나와 본 적이 있나요? 무슨 일이 있었나요?",
      "이것이 나의 첫 요원 임무라면, 미리 갖추고 싶은 능력은 무엇인가요?"] };
ACT["S4356"] = { s: "Two kids are camping in a tent outside their grandparents' house on the coast. A local fisherman Tom tells them a story of the ship called the Indian Queen that was robbed of its precious treasure.",
  q: ["A fisherman named Tom tells the kids a story about a ship robbed of its precious treasure. Why do you think old stories about lost treasure are so exciting to hear?",
      "Has an older person in your family ever told you an interesting story? What was it about?",
      "If you went searching for the Indian Queen's lost treasure, where would you start looking?"],
  h: ["어부 톰은 아이들에게 소중한 보물을 빼앗긴 배 이야기를 들려줘요. 잃어버린 보물에 관한 옛이야기는 왜 그렇게 흥미진진할까요?",
      "우리 가족의 어른이 흥미로운 이야기를 들려준 적이 있나요? 무엇에 관한 이야기였나요?",
      "인디언 퀸호의 잃어버린 보물을 찾으러 간다면 나는 어디부터 찾아보고 싶나요?"] };
ACT["S4357"] = { s: "Two children travel back to the Medieval period and meet some knights whose leader vanished.",
  q: ["The children meet knights whose leader has vanished. What do you think might have happened to a knight leader who suddenly vanished?",
      "Have you ever learned about knights or the Medieval period? What interested you the most?",
      "If you traveled back to Medieval times, what would you want to see or do first?"],
  h: ["아이들은 지도자가 사라져 버린 기사들을 만나요. 갑자기 사라진 기사 지도자에게 무슨 일이 일어났을 것 같나요?",
      "기사나 중세 시대에 대해 배워 본 적이 있나요? 가장 흥미로웠던 점은 무엇이었나요?",
      "중세 시대로 시간 여행을 간다면 가장 먼저 무엇을 보거나 하고 싶나요?"] };
ACT["S4358"] = { s: "Flic, Toby, and Uncle Ollie discover a wrecked galleon and an old sea chest, and they are surprised by the contents in the chest.",
  q: ["Flic, Toby, and Uncle Ollie are surprised by what they find inside an old sea chest from a wrecked galleon. What do you imagine could be inside a sea chest that has been underwater for a very long time?",
      "Have you ever found something surprising in an unexpected place? What was it?",
      "If you discovered a sunken ship, what would you hope to find inside it?"],
  h: ["플릭, 토비, 올리 삼촌은 난파선에서 나온 오래된 보물 상자 속을 보고 깜짝 놀라요. 아주 오랫동안 물속에 있던 보물 상자 안에는 무엇이 들어 있을 것 같나요?",
      "예상치 못한 곳에서 놀라운 것을 발견해 본 적이 있나요? 무엇이었나요?",
      "가라앉은 배를 발견한다면 그 안에서 무엇을 찾기를 바라나요?"] };
ACT["S4359"] = { s: "Agent Arthur goes to investigate the ship whose crew has gone missing.",
  q: ["Agent Arthur investigates a ship whose entire crew has gone missing. What do you think might have happened to a whole ship's crew that vanished at sea?",
      "Have you ever had to investigate or figure out a mystery, big or small? What happened?",
      "If you were Agent Arthur boarding the empty ship, what would you look for first?"],
  h: ["아서 요원은 선원 전체가 사라진 배를 조사해요. 바다 위에서 배의 선원 전체가 사라진다면 무슨 일이 일어났을 것 같나요?",
      "크든 작든 수수께끼를 조사하거나 풀어 본 적이 있나요? 무슨 일이 있었나요?",
      "내가 아서 요원이 되어 텅 빈 배에 올라탄다면 가장 먼저 무엇을 찾아보고 싶나요?"] };
ACT["S4360"] = { s: "Tom and Mandy are thrown back in time and are forced to work aboard a ship called the Squiffy Sheep.",
  q: ["Tom and Mandy are suddenly thrown back in time and forced to work aboard a ship. What do you think would be the hardest part of suddenly having to work on an old ship?",
      "Have you ever been asked to do a job you weren't prepared for? What did you do?",
      "If you were thrown back in time onto an old sailing ship, what job on the ship would you want to have?"],
  h: ["톰과 맨디는 갑자기 과거로 던져져서 낡은 배에서 일해야만 해요. 갑자기 낡은 배에서 일해야 한다면 무엇이 가장 힘들 것 같나요?",
      "준비되지 않은 일을 해 달라는 부탁을 받은 적이 있나요? 그때 나는 어떻게 했나요?",
      "옛날 항해선으로 시간 여행을 간다면 그 배에서 어떤 일을 맡고 싶나요?"] };
ACT["S4361"] = { s: "Agent Arthur is sent to the desert town of El Taco for a mission. He and his dog Sleuth are after the evil Spider Organization that kidnapped Agent Andrea.",
  q: ["Agent Arthur and his dog Sleuth must rescue Agent Andrea, who was kidnapped by an evil organization. Why do you think having a partner, like a loyal dog, can help someone on a dangerous mission?",
      "Have you ever worked together with a pet or a friend to solve a problem? What happened?",
      "If you had to rescue someone in the desert, what would be the hardest part of the journey?"],
  h: ["아서 요원과 그의 개 슬루스는 사악한 조직에게 납치된 안드레아 요원을 구해야 해요. 충직한 개 같은 파트너가 있으면 위험한 임무에 왜 도움이 될까요?",
      "반려동물이나 친구와 힘을 합쳐 문제를 해결해 본 적이 있나요? 무슨 일이 있었나요?",
      "사막에서 누군가를 구출해야 한다면, 그 여정에서 가장 힘든 부분은 무엇일 것 같나요?"] };
ACT["S4362"] = { s: "When Mr. Happy discovers Mr. Miserable sulking in a room, he convinces him to come outside and cheer up.",
  q: ["Mr. Happy convinces Mr. Miserable to come outside and cheer up. What do you think Mr. Happy might have said to help Mr. Miserable feel better?",
      "Have you ever helped a friend or family member who was feeling sad or grumpy? What did you do?",
      "What is something that always cheers you up when you feel down?"],
  h: ["해피 아저씨는 방 안에서 시무룩해하는 미저러블 아저씨를 밖으로 데리고 나가 기운을 북돋워 줘요. 해피 아저씨는 미저러블 아저씨의 기분을 풀어 주려고 어떤 말을 했을 것 같나요?",
      "슬프거나 짜증 난 가족이나 친구를 도와준 적이 있나요? 그때 나는 무엇을 했나요?",
      "기분이 안 좋을 때 나를 항상 기운 나게 해 주는 것은 무엇인가요?"] };
ACT["S4363"] = { s: "Mr. Sneeze lives in a small snow-covered cottage, and he decides to find a cure for the sneezes.",
  q: ["Mr. Sneeze decides to find a cure for his constant sneezing. What do you think Mr. Sneeze might try in order to find a cure?",
      "Have you ever had a really bad cold or sneezing fit? What did you do to feel better?",
      "If you were trying to help Mr. Sneeze stop sneezing, what advice would you give him?"],
  h: ["스니즈 아저씨는 계속되는 재채기를 고칠 방법을 찾기로 해요. 스니즈 아저씨는 치료법을 찾기 위해 무엇을 시도해 볼 것 같나요?",
      "심한 감기에 걸리거나 재채기가 멈추지 않았던 적이 있나요? 그때 나아지려고 무엇을 했나요?",
      "스니즈 아저씨가 재채기를 멈추도록 돕는다면 나는 어떤 조언을 해 주고 싶나요?"] };
ACT["S4364"] = { s: "When Mr. Neat and Mr. Tidy are to visit, Mr. Messy sets about cleaning his house.",
  q: ["Mr. Messy has to clean his house before Mr. Neat and Mr. Tidy visit. What do you think would be the hardest part of cleaning up a very messy house?",
      "Have you ever had to clean your room before someone visited? How did it go?",
      "If you were Mr. Messy, where would you start cleaning first?"],
  h: ["메시 아저씨는 니트 아저씨와 타이디 아저씨가 오기 전에 집을 치우기 시작해요. 아주 지저분한 집을 치울 때 가장 힘든 부분은 무엇일 것 같나요?",
      "누군가 놀러 오기 전에 내 방을 치워야 했던 적이 있나요? 어떻게 됐나요?",
      "내가 메시 아저씨라면 어디부터 치우기 시작하고 싶나요?"] };
ACT["S4365"] = { s: "Every morning, when Mr. Tickle wakes up, he decides it is Tickling Day.",
  q: ["Mr. Tickle decides every morning that it's Tickling Day. What do you think would happen if you turned every morning into a fun, special day?",
      "Do you like being tickled, or do you not like it? Why?",
      "If you had really long arms like Mr. Tickle, what would you use them for?"],
  h: ["티클 아저씨는 매일 아침 일어나면 오늘은 '간지럼 데이'라고 정해요. 매일 아침을 재미있고 특별한 날로 만든다면 어떤 일이 생길 것 같나요?",
      "간지럼을 태우는 걸 좋아하나요, 싫어하나요? 왜 그런가요?",
      "내게 티클 아저씨처럼 아주 긴 팔이 있다면 무엇을 하는 데 쓰고 싶나요?"] };
ACT["S4366"] = { s: "The wizard helps Mr. Mean, who lives up to his name, to make him just a little bit nicer.",
  q: ["A wizard helps Mr. Mean become just a little bit nicer. What kind of magic do you imagine the wizard might use to make someone nicer?",
      "Have you ever met someone who was mean at first but became nicer over time? What changed?",
      "If you were the wizard, what would you do to help someone become kinder?"],
  h: ["마법사는 이름 그대로 못된 민 아저씨가 조금이라도 더 친절해지도록 도와줘요. 마법사는 누군가를 더 친절하게 만들기 위해 어떤 마법을 쓸 것 같나요?",
      "처음엔 못되게 굴다가 점점 친절해진 사람을 만나 본 적이 있나요? 무엇이 달라지게 했나요?",
      "내가 마법사라면, 누군가 더 친절해지도록 도와주기 위해 무엇을 하고 싶나요?"] };
ACT["S4367"] = { s: "Mr. Greedy gets him into trouble with a giant because of his greed.",
  q: ["Mr. Greedy's greed gets him into trouble with a giant. What do you think Mr. Greedy did that made the giant upset with him?",
      "Have you ever wanted too much of something and it caused a problem? What happened?",
      "What advice would you give Mr. Greedy to help him avoid trouble in the future?"],
  h: ["그리디 아저씨의 욕심은 거인과 말썽을 일으켜요. 그리디 아저씨는 거인을 화나게 할 만큼 무엇을 했을 것 같나요?",
      "무언가를 너무 많이 원해서 문제가 생긴 적이 있나요? 무슨 일이 있었나요?",
      "그리디 아저씨가 앞으로 말썽을 피하도록 나는 어떤 조언을 해 주고 싶나요?"] };
ACT["S4368"] = { s: "When Little Miss Christmas decides she needs a break from the Christmas rush, she asks Santa to wrap the last remaining gifts.",
  q: ["Little Miss Christmas asks Santa for help because she needs a break from the Christmas rush. Why do you think even someone in charge of Christmas might need a break sometimes?",
      "Have you ever felt too busy and needed a break? What did you do to rest?",
      "If you helped Santa wrap the last presents, what would you want to do to make it faster or more fun?"],
  h: ["리틀 미스 크리스마스는 크리스마스 준비로 너무 바빠져서 휴식이 필요하다고 느끼고 산타에게 도움을 청해요. 크리스마스를 책임지는 사람도 가끔 왜 쉬어야 할까요?",
      "너무 바빠서 쉬어야 했던 적이 있나요? 쉬기 위해 무엇을 했나요?",
      "산타의 마지막 선물 포장을 돕는다면, 더 빠르고 재미있게 하기 위해 나는 무엇을 하고 싶나요?"] };
ACT["S4369"] = { s: "Jack and Annie travel back in time to the Paris World’s Fair of 1889, where they manage to protect four scientific pioneers from an evil sorcerer.",
  q: ["Jack and Annie protect four scientific pioneers from an evil sorcerer at the 1889 World's Fair. Why do you think it was important to protect these scientific pioneers?",
      "Have you ever learned about a World's Fair or a big exhibition of new inventions? What amazed you?",
      "If you traveled to the 1889 Paris World's Fair, what new invention would you most want to see?"],
  h: ["잭과 애니는 1889년 파리 세계 박람회에서 네 명의 과학 개척자를 사악한 마법사로부터 지켜 줘요. 이 과학 개척자들을 지키는 일이 왜 중요했을까요?",
      "세계 박람회나 새로운 발명품들을 소개하는 큰 전시회에 대해 배운 적이 있나요? 무엇이 놀라웠나요?",
      "1889년 파리 세계 박람회로 여행을 간다면 어떤 새로운 발명품을 가장 보고 싶나요?"] };
ACT["S4370"] = { s: "Aladdin is surprised when his long-lost uncle Hasan appears. Hasan needs Aladdin to help him find a magic lamp, hidden deep in a dark cave. But Aladdin is afraid that once he is in there, Hasan will never let him out again!",
  q: ["Aladdin is afraid that his uncle Hasan will trap him once he goes into the cave. Why do you think Aladdin doesn't fully trust his long-lost uncle?",
      "Have you ever felt unsure about trusting someone new, even a relative? What made you cautious?",
      "If you were Aladdin, would you go into the dark cave to help your uncle? Why or why not?"],
  h: ["알라딘은 동굴에 들어가면 삼촌 하산이 자신을 가두어 버릴까 봐 두려워해요. 알라딘은 오랫동안 보지 못한 삼촌을 왜 완전히 믿지 못할까요?",
      "친척이라도 새로 나타난 사람을 믿기 어려웠던 적이 있나요? 무엇 때문에 조심스러웠나요?",
      "내가 알라딘이라면 삼촌을 돕기 위해 어두운 동굴에 들어갈 것 같나요? 왜 그런가요?"] };
ACT["S4371"] = { s: "Brothers Ali Baba is kind and poor and Kassim is rich and mean. When Ali Baba spies 40 thieves hiding treasure in a cave, he only takes a little for himself. But Kassim is greedy, and soon the thieves are on their trail!",
  q: ["Ali Baba only takes a little treasure, but his greedy brother Kassim wants more. Why do you think Ali Baba's choice to take only a little was wiser than Kassim's greed?",
      "Have you ever chosen to take only a little of something, even when you could have taken more? What happened?",
      "If forty thieves were chasing you and your brother, what plan would you make to stay safe?"],
  h: ["알리바바는 보물을 조금만 가져가지만, 욕심 많은 형 카심은 더 많이 원해요. 알리바바가 조금만 가져간 선택이 카심의 욕심보다 왜 더 현명했을까요?",
      "더 많이 가질 수 있었는데도 조금만 가지기로 선택해 본 적이 있나요? 그때 무슨 일이 있었나요?",
      "마흔 명의 도둑이 나와 형을 쫓아온다면 안전하게 지내기 위해 나는 어떤 계획을 세우고 싶나요?"] };
ACT["S4372"] = { s: "The Sheriff of Nottingham is holding a contest to find the best bowman. Robin Hood knows it’s a trap to draw him out of hiding, yet is determined to enter. How can Robin win and escape unnoticed?",
  q: ["Robin Hood knows the archery contest is a trap, but he decides to enter anyway. Why do you think Robin Hood chose to take the risk instead of staying safely in hiding?",
      "Have you ever taken a risk even though you knew there might be danger? What happened?",
      "If you were Robin Hood, how would you plan to win the contest and escape the trap safely?"],
  h: ["로빈 후드는 활쏘기 대회가 함정이라는 것을 알면서도 참가하기로 해요. 로빈 후드는 왜 안전하게 숨어 있는 대신 위험을 감수하기로 했을까요?",
      "위험할 수도 있다는 것을 알면서도 위험을 감수해 본 적이 있나요? 무슨 일이 있었나요?",
      "내가 로빈 후드라면 대회에서 이기고 함정에서 안전하게 빠져나가기 위해 어떤 계획을 세우고 싶나요?"] };
ACT["S4373"] = { s: "To win back his father’s kingdom, Jason must find the fabled Golden Fleece. Many have attempted the perilous journey in search of it and never returned. But Jason and his band of Argonauts set sail determined to succeed!",
  q: ["Many people who searched for the Golden Fleece never returned, but Jason sets sail anyway. What do you think gives Jason the courage to attempt such a dangerous journey?",
      "Have you ever tried something difficult that other people had failed at before? What happened?",
      "If you sailed with Jason and the Argonauts, what job on the ship would you want to have?"],
  h: ["황금 양털을 찾으러 떠났던 많은 이들이 돌아오지 못했지만, 제이슨은 그래도 항해를 떠나요. 이렇게 위험한 여정에 나설 용기는 제이슨에게 어디서 나왔을까요?",
      "다른 사람들이 실패했던 어려운 일을 시도해 본 적이 있나요? 어떻게 되었나요?",
      "내가 제이슨과 아르고 원정대와 함께 항해한다면 배에서 어떤 역할을 맡고 싶나요?"] };
ACT["S4374"] = { s: "Young Robinson Crusoe joins a trading ship in the Caribbean. But when he is shipwrecked and left stranded alone on an island, how will he survive?",
  q: ["Robinson Crusoe is shipwrecked and left completely alone on an island. What do you think would be the most important thing to do first if you were stranded alone like Robinson Crusoe?",
      "Have you ever had to figure out how to solve a problem all by yourself, with no one to help? What did you do?",
      "If you were stranded on an island, what three things would you want to have with you?"],
  h: ["로빈슨 크루소는 배가 난파되어 완전히 혼자 섬에 남겨져요. 나라면 로빈슨 크루소처럼 혼자 섬에 남겨졌을 때 가장 먼저 무엇을 해야 한다고 생각하나요?",
      "도와줄 사람 없이 혼자서 문제를 해결해야 했던 적이 있나요? 그때 나는 무엇을 했나요?",
      "무인도에 혼자 남겨진다면 함께 있고 싶은 세 가지는 무엇인가요?"] };
ACT["S4375"] = { s: "Beowulf is determined to become a hero by slaying the evil beast, Grendel. Can Beowulf defeat Grendel, and bring peace to the land?",
  q: ["Beowulf is determined to defeat the evil beast Grendel to bring peace to the land. Why do you think Beowulf is willing to risk his life fighting such a dangerous beast?",
      "Have you ever stood up to something you were afraid of in order to help others?",
      "If you were Beowulf, how would you prepare yourself before fighting Grendel?"],
  h: ["베오울프는 사악한 괴물 그렌델을 무찔러 땅에 평화를 가져오기로 결심해요. 베오울프는 이렇게 위험한 괴물과 싸우는 데 왜 목숨을 걸 만큼 결심했을까요?",
      "다른 사람들을 돕기 위해 두려운 것에 맞서 본 적이 있나요?",
      "내가 베오울프라면 그렌델과 싸우기 전에 어떻게 준비하고 싶나요?"] };
ACT["S4381"] = { s: "This book features a collection of poems about seasons.",
  q: ["This book is a collection of poems about the seasons. Which season do you think would be the most interesting to write a poem about?",
      "What is your favorite season, and what do you like most about it?",
      "Write a short poem or a few lines describing your favorite season."],
  h: ["이 책은 계절에 관한 시들을 모아 놓았어요. 어떤 계절이 시로 쓰기에 가장 흥미로울 것 같나요?",
      "가장 좋아하는 계절은 언제이고, 그 계절의 어떤 점이 가장 좋은가요?",
      "내가 가장 좋아하는 계절을 설명하는 짧은 시나 몇 줄의 글을 적어 보세요."] };
ACT["S4382"] = { s: "This book presents a collection of illustrated rhyming poems about winter.",
  q: ["This book presents illustrated rhyming poems about winter. What images or feelings come to mind when you think about winter?",
      "What do you like to do on a snowy winter day?",
      "Write a short rhyme or a few lines about something you love about winter."],
  h: ["이 책은 겨울에 관한 그림이 있는 운율시들을 담고 있어요. 겨울을 떠올리면 어떤 모습이나 느낌이 떠오르나요?",
      "눈이 오는 겨울날에는 무엇을 하는 것을 좋아하나요?",
      "겨울에서 내가 사랑하는 것에 대해 짧은 운율시나 몇 줄의 글을 적어 보세요."] };
ACT["S4383"] = { s: "This book contains twelve Thanksgiving Day poems.",
  q: ["This book contains twelve poems all about Thanksgiving Day. What part of Thanksgiving do you think would make the best subject for a poem?",
      "What do you enjoy most about Thanksgiving or a similar family gathering you celebrate?",
      "Write a few lines of your own poem about something you are thankful for."],
  h: ["이 책에는 추수감사절에 관한 시 열두 편이 담겨 있어요. 추수감사절의 어떤 부분이 시의 소재로 가장 좋을 것 같나요?",
      "추수감사절이나 그와 비슷한 가족 모임에서 가장 즐거운 것은 무엇인가요?",
      "내가 감사하게 생각하는 것에 대해 몇 줄의 짧은 시를 적어 보세요."] };
ACT["S4384"] = { s: "This book features fourteen humorous poems about bedtime.",
  q: ["This book has fourteen funny poems about bedtime. What do you think makes bedtime such a good topic for funny poems?",
      "Do you ever stay awake thinking or doing something after your parents think you're asleep? What do you do?",
      "Write a few funny lines about what really happens at your bedtime."],
  h: ["이 책에는 잠자리에 대한 열네 편의 재미있는 시가 담겨 있어요. 잠자리는 왜 재미있는 시의 좋은 소재가 될까요?",
      "부모님이 내가 잠들었다고 생각할 때 깨어서 생각하거나 무언가를 한 적이 있나요? 무엇을 하나요?",
      "내가 잠자리에서 진짜로 겪는 일에 대해 재미있는 몇 줄을 적어 보세요."] };
ACT["S4385"] = { s: "Encyclopedia Brown, Idaville's brainy super sleuth, tackles ten new mysteries, including The Case of the Secret UFOs.",
  q: ["Encyclopedia Brown solves ten new mysteries, including one about secret UFOs. What clues do you think a detective would need to solve a mystery about UFOs?",
      "Have you ever tried to solve a mystery, like finding something missing or figuring out what happened? What did you do?",
      "If you were a super sleuth like Encyclopedia Brown, what mystery would you most want to solve?"],
  h: ["엔사이클로피디아 브라운은 비밀 UFO 사건을 포함해 열 가지 새로운 수수께끼를 풀어요. 탐정이 UFO에 관한 수수께끼를 풀려면 어떤 단서가 필요할 것 같나요?",
      "잃어버린 것을 찾거나 무슨 일이 있었는지 알아내려고 수수께끼를 풀어 본 적이 있나요? 그때 나는 무엇을 했나요?",
      "내가 엔사이클로피디아 브라운 같은 명탐정이라면 가장 풀고 싶은 수수께끼는 무엇인가요?"] };
ACT["S4386"] = { s: "Encyclopedia Brown, a ten-year-old crime-buster, locates stolen jewels, retrieves a stuffed tiger, and solves more cases.",
  q: ["Encyclopedia Brown, only ten years old, solves cases like finding stolen jewels. Why do you think a ten-year-old detective can be just as good at solving mysteries as an adult?",
      "Have you ever noticed a small clue that helped you understand or solve something bigger? What was it?",
      "If you had to find stolen jewels like Encyclopedia Brown does, where would you start looking?"],
  h: ["겨우 열 살인 엔사이클로피디아 브라운은 도둑맞은 보석을 찾아내는 등 여러 사건을 해결해요. 열 살짜리 탐정도 어른만큼 수수께끼를 잘 풀 수 있는 이유는 무엇일까요?",
      "더 큰 것을 이해하거나 해결하는 데 도움이 된 작은 단서를 알아챈 적이 있나요? 무엇이었나요?",
      "엔사이클로피디아 브라운처럼 도둑맞은 보석을 찾아야 한다면 나는 어디부터 찾아보고 싶나요?"] };
ACT["S4387"] = { s: "Encyclopedia Brown, Idaville's secret weapon against lawbreakers, helps the police force solve ten new baffling crimes.",
  q: ["Encyclopedia Brown helps the police solve ten baffling crimes. Why do you think the police in Idaville rely on a kid detective to help them?",
      "Have you ever helped an adult solve a problem by noticing something they missed? What happened?",
      "If you were Idaville's secret weapon against crime, what special skill would help you solve mysteries?"],
  h: ["엔사이클로피디아 브라운은 아이드빌 경찰의 비밀 무기가 되어 열 가지 까다로운 사건을 해결하는 것을 도와줘요. 아이드빌 경찰은 왜 어린이 탐정에게 도움을 청할까요?",
      "어른이 놓친 것을 내가 알아채서 문제를 해결하도록 도와준 적이 있나요? 무슨 일이 있었나요?",
      "내가 아이드빌의 비밀 무기라면, 수수께끼를 푸는 데 도움이 될 나만의 특별한 능력은 무엇일까요?"] };
ACT["S4388"] = { s: "Meet three very different dragons in Dragon Tales. The dragons in these action-packed, fantastic funny stories from Libya, China and England, might surprise you.",
  q: ["This book has dragon stories from Libya, China, and England. Why do you think dragon stories look so different depending on which country they come from?",
      "Have you heard other stories about dragons before? How were the dragons different from or similar to these?",
      "If you created your own dragon story from your country, what would your dragon be like?"],
  h: ["이 책에는 리비아, 중국, 영국에서 전해지는 용 이야기가 담겨 있어요. 나라마다 용 이야기가 이렇게 다른 이유는 무엇일까요?",
      "전에 용에 관한 다른 이야기를 들어 본 적이 있나요? 그 용들은 이 책의 용들과 어떻게 다르거나 비슷했나요?",
      "내가 우리나라의 용 이야기를 직접 만든다면, 나의 용은 어떤 모습일까요?"] };
ACT["S4389"] = { s: "The Star Fruit Tree and other stories contains four fruity tales all about how irresistible fruit is, even when you know you shouldn't take it!",
  q: ["These four stories are all about how hard it is to resist fruit, even when you know you shouldn't take it. Why do you think people find it so hard to resist doing something they know they shouldn't?",
      "Have you ever wanted something so badly that it was hard to resist, even though you knew you shouldn't have it? What happened?",
      "If you found a tree of irresistible fruit, would you take some even if you knew you shouldn't? Why or why not?"],
  h: ["이 네 이야기는 하면 안 된다는 걸 알면서도 과일의 유혹을 참기가 얼마나 어려운지 이야기해요. 사람들은 하면 안 된다는 걸 알면서도 왜 그렇게 참기 힘들어할까요?",
      "하면 안 된다는 걸 알면서도 너무 갖고 싶어서 참기 힘들었던 적이 있나요? 무슨 일이 있었나요?",
      "뿌리치기 힘든 과일이 열린 나무를 발견한다면, 안 된다는 걸 알면서도 따 먹을 것 같나요? 왜 그런가요?"] };
ACT["S4390"] = { s: "Beowulf, Grendel and the Dragon tells the story of the heroic warrior Beowulf as he battles a hate-filled demon, then its vengeful mother and a furious fire-breathing dragon.",
  q: ["Beowulf battles three different terrifying creatures — a demon, its mother, and a dragon. Which of these three battles do you think would be the most difficult for Beowulf, and why?",
      "Have you ever faced more than one challenge in a row, right after solving the first one? What was that like?",
      "If you were a hero like Beowulf, which creature would you least want to face, and why?"],
  h: ["베오울프는 악마와 그 복수심에 찬 어머니, 그리고 사나운 불을 뿜는 용까지 세 가지 무서운 존재와 맞서 싸워요. 이 세 싸움 중 베오울프에게 가장 힘들었을 싸움은 무엇이고, 왜 그런가요?",
      "하나의 어려움을 해결하자마자 또 다른 어려움을 연달아 겪어 본 적이 있나요? 그때 어땠나요?",
      "내가 베오울프 같은 영웅이라면, 이 존재들 중 가장 마주하고 싶지 않은 것은 무엇이고 왜 그런가요?"] };
ACT["S4391"] = { s: "This book presents the story of Howard Carter's discovery of the find of the century, the tomb of King Tutankhamun.",
  q: ["Howard Carter made the discovery of the century when he found King Tutankhamun's tomb. What do you think it would feel like to make such an important discovery?",
      "Have you ever discovered or found something that felt exciting, even if it was small? What was it?",
      "If you were an archaeologist searching for a lost tomb, what would you hope to find inside?"],
  h: ["하워드 카터는 투탕카멘 왕의 무덤을 발견하며 세기의 발견을 해냈어요. 이렇게 중요한 발견을 해낸다면 어떤 기분일 것 같나요?",
      "작은 것이라도 무언가를 발견해서 신났던 적이 있나요? 무엇이었나요?",
      "내가 잃어버린 무덤을 찾는 고고학자라면, 그 안에서 무엇을 발견하기를 바라나요?"] };
ACT["S4392"] = { s: "This book recreates Apollo 13's atmosphere on board and at Mission Control by using some of the real spoken words of the astronauts and ground crew.",
  q: ["This book recreates the real words spoken by the Apollo 13 astronauts and ground crew during their crisis. Why do you think it is powerful to read the actual words people said during a dangerous moment?",
      "Have you ever heard about the Apollo 13 mission or another moment in space history? What did you learn?",
      "If you were in Mission Control during an emergency like Apollo 13, how do you think you would feel and act?"],
  h: ["이 책은 아폴로 13호 위기 상황에서 우주비행사와 지상 관제팀이 실제로 나눈 말을 그대로 되살려요. 위험한 순간에 사람들이 실제로 한 말을 읽는 것이 왜 강렬하게 느껴질까요?",
      "아폴로 13호 임무나 우주 역사 속 다른 순간에 대해 들어 본 적이 있나요? 무엇을 알게 되었나요?",
      "내가 아폴로 13호 같은 비상사태에서 관제 센터에 있다면 어떤 기분이 들고 어떻게 행동할 것 같나요?"] };
ACT["S4393"] = { s: "This book retells Sir Ranulph Fiennes' journey across the frozen-wastes of Antarctica with his companion Dr. Mike Stroud.",
  q: ["Sir Ranulph Fiennes journeys across the frozen wastes of Antarctica with his companion. Why do you think having a trusted companion matters so much on a dangerous journey like this?",
      "Have you ever completed a difficult task with the help of a partner or friend? What was it like?",
      "If you crossed Antarctica like Fiennes and Stroud, what would you be most worried about?"],
  h: ["래널프 파인스 경은 동료와 함께 얼어붙은 남극의 황무지를 가로질러요. 이런 위험한 여정에서 믿을 수 있는 동료가 그렇게 중요한 이유는 무엇일까요?",
      "친구나 동료의 도움으로 어려운 일을 해낸 적이 있나요? 그때 어땠나요?",
      "파인스와 스트라우드처럼 남극을 가로지른다면 가장 걱정되는 것은 무엇일까요?"] };
ACT["S4394"] = { s: "This book tells why and how people have painted from the earliest times. And find out the amazing facts about some famous works of art.",
  q: ["This book tells how people have painted since the earliest times. What do you think made early people want to start painting in the first place?",
      "Have you ever painted or drawn something you were proud of? What was it?",
      "If you could paint one amazing work of art for people to remember you by, what would you paint?"],
  h: ["이 책은 아주 먼 옛날부터 사람들이 어떻게 그림을 그려 왔는지 알려줘요. 옛사람들이 처음 그림을 그리고 싶어 했던 이유는 무엇이었을까요?",
      "자랑스러웠던 그림이나 작품을 그려 본 적이 있나요? 무엇이었나요?",
      "사람들이 나를 기억할 멋진 작품 하나를 그린다면, 무엇을 그리고 싶나요?"] };
ACT["S4395"] = { s: "What makes perfect soil? It needs a lot of things and a very long time. Let's find out how perfect soil is formed.",
  q: ["This book explains that soil needs many things and a very long time to form. Why do you think good soil takes so long to make?",
      "Have you ever planted something in soil or played in dirt? What did you notice about it?",
      "If you were trying to make perfect soil yourself, what ingredients or steps do you imagine you would need?"],
  h: ["이 책은 좋은 흙이 만들어지려면 여러 가지와 아주 긴 시간이 필요하다고 알려줘요. 좋은 흙이 만들어지는 데 왜 그렇게 오랜 시간이 걸릴까요?",
      "흙에 무언가를 심거나 흙을 만지며 놀아 본 적이 있나요? 그때 무엇을 알아챘나요?",
      "내가 직접 완벽한 흙을 만들어 본다면, 어떤 재료와 단계가 필요할 것 같나요?"] };
ACT["S4396"] = { s: "This book tells the origin of many sports and games that we play today.",
  q: ["This book tells the origin of many sports and games we play today. Which sport do you think has the most interesting origin story?",
      "What is your favorite sport or game to play, and how did you first learn it?",
      "If you invented a brand-new sport, what would the rules be?"],
  h: ["이 책은 오늘날 우리가 하는 많은 스포츠와 게임이 어디서 시작되었는지 알려줘요. 어떤 스포츠의 기원이 가장 흥미로울 것 같나요?",
      "내가 가장 좋아하는 스포츠나 게임은 무엇이고, 처음에는 어떻게 배웠나요?",
      "내가 완전히 새로운 스포츠를 만든다면 규칙은 어떻게 정하고 싶나요?"] };
ACT["S4397"] = { s: "Plants are very helpful to human life ― food, clothing, housing, and medicines. Let's find out how plants are helpful to humans.",
  q: ["This book explains how plants help humans with food, clothing, housing, and medicine. Which of these uses of plants surprises you the most?",
      "What is a plant in your everyday life that you rely on, like a food or something made from wood or cotton?",
      "If plants suddenly disappeared from the world, what do you think would be the biggest problem people would face?"],
  h: ["이 책은 식물이 음식, 옷, 집, 약으로 사람들에게 얼마나 도움이 되는지 알려줘요. 이 중에서 어떤 쓰임이 가장 놀랍게 느껴지나요?",
      "내 일상에서 의지하고 있는 식물은 무엇인가요? 음식이나 나무·목화로 만든 물건일 수도 있어요.",
      "세상에서 식물이 갑자기 사라진다면 사람들이 겪을 가장 큰 문제는 무엇일 것 같나요?"] };
ACT["S4398"] = { s: "This book tells the life of the young Prince Edward and how the life of the royalty and the poor are different in Tudor times.",
  q: ["This book shows how different the lives of royalty and the poor were in Tudor times. What do you think was the biggest difference between Prince Edward's daily life and a poor child's daily life?",
      "Have you ever thought about how different your life might be if you lived in a different time or place?",
      "If you switched places with someone very different from you for a day, what do you think you would learn?"],
  h: ["이 책은 튜더 시대 왕족과 가난한 사람들의 삶이 얼마나 달랐는지 보여줘요. 에드워드 왕자의 일상과 가난한 아이의 일상 사이 가장 큰 차이는 무엇이었을 것 같나요?",
      "다른 시대나 다른 곳에서 산다면 내 삶이 어떻게 달라질지 생각해 본 적이 있나요?",
      "나와 아주 다른 사람과 하루 동안 자리를 바꾼다면, 무엇을 배우게 될 것 같나요?"] };
ACT["S4399"] = { s: "Experience the thrill of flight, the wonders of modern technology. With this book, you can feel more thrills and spills by being a stunt pilot or flying a fighter plane.",
  q: ["This book lets you experience the thrill of flight, from stunt piloting to flying a fighter plane. Which kind of flying do you think would be more thrilling — stunt flying or fighter flying? Why?",
      "Have you ever been on an airplane or dreamed about flying? What was that experience or dream like?",
      "If you could learn to fly any kind of aircraft, which one would you choose and why?"],
  h: ["이 책은 스턴트 조종사부터 전투기 조종사까지, 비행의 짜릿함을 경험하게 해 줘요. 곡예비행과 전투기 비행 중 어느 쪽이 더 짜릿할 것 같고, 왜 그런가요?",
      "비행기를 타 본 적이 있거나 하늘을 나는 것을 꿈꿔 본 적이 있나요? 그 경험이나 꿈은 어땠나요?",
      "어떤 비행기든 조종하는 법을 배울 수 있다면, 어떤 비행기를 고르고 싶고 왜 그런가요?"] };
