// 간이 학습 질문 — Book No. S44 묶음. 사람이 아니라 AI 가 한 번 쓰고 굳힌 파일이다.
window.ACT = window.ACT || {};
var ACT = window.ACT;
ACT["S4400"] = { s: "Marius, a Roman centurion, takes you on a tour, and show you how Roman soldiers lived.",
  q: ["What part of a Roman soldier's daily life did Marius show you on the tour that you found most interesting? Explain what you learned about it.",
      "If you could ask a Roman soldier one question about his life, what would you ask and why?",
      "Do you think being a Roman soldier would have been an exciting job or a hard job? Give your own reason."],
  h: ["마리우스가 안내한 로마 병사의 하루 중에서 가장 흥미로웠던 부분은 무엇이었나요? 그것에 대해 무엇을 배웠는지 설명해 보세요.",
      "로마 병사에게 한 가지 질문을 할 수 있다면 무엇을 묻고 싶나요? 그 이유는 무엇인가요?",
      "로마 병사가 되는 것은 신나는 일이었을까요, 힘든 일이었을까요? 내 생각과 이유를 적어 보세요."] };
ACT["S4401"] = { s: "Practice some basic skills and learn some top knowledge for surviving.",
  q: ["Which survival skill mentioned in this book do you think would be the most useful to learn, and why?",
      "Have you ever tried to learn a skill that could help you in an emergency or in nature? What was it?",
      "If you had to teach one survival skill to a friend, which one would you choose and how would you explain it?"],
  h: ["이 책에 나온 생존 기술 중 배우면 가장 쓸모 있을 것 같은 것은 무엇이고, 그 이유는 무엇인가요?",
      "위급할 때나 자연 속에서 도움이 될 만한 기술을 배워 본 적이 있나요? 무엇이었나요?",
      "친구에게 생존 기술 한 가지를 가르쳐 준다면 무엇을 고르고 어떻게 설명하고 싶나요?"] };
ACT["S4402"] = { s: "If the Tower of London could speak to us, it would tell us stories of hope and sadness. Find out what happened in the Tower in the past.",
  q: ["What kind of stories - hopeful or sad - do you imagine the Tower of London might tell, based on what this book describes?",
      "Is there an old building or place near you that seems like it could tell stories of the past? What do you imagine it has seen?",
      "Why do you think it's important to learn about the history of a place like the Tower of London?"],
  h: ["이 책의 내용을 바탕으로, 런던탑이 말을 할 수 있다면 어떤 이야기 - 희망찬 이야기일지 슬픈 이야기일지 - 를 들려줄 것 같나요?",
      "내 주변에 과거의 이야기를 들려줄 것 같은 오래된 건물이나 장소가 있나요? 그곳이 무엇을 보았을지 상상해 보세요.",
      "런던탑 같은 장소의 역사를 배우는 것이 왜 중요하다고 생각하나요?"] };
ACT["S4403"] = { s: "Come and have a look inside some jaws, and discover facts about teeth that you would never have believed!",
  q: ["What was the most surprising fact about animal teeth that you learned from this book?",
      "Have you ever looked closely at an animal's teeth, in real life or in a picture? What did you notice?",
      "If you could design your own set of animal teeth, what job would you want them to do?"],
  h: ["이 책에서 동물의 이빨에 대해 배운 것 중 가장 놀라웠던 사실은 무엇인가요?",
      "실제로나 사진으로 동물의 이빨을 자세히 본 적이 있나요? 무엇을 알아차렸나요?",
      "내가 동물의 이빨을 직접 디자인한다면 어떤 일을 하는 이빨을 만들고 싶나요?"] };
ACT["S4404"] = { s: "This book tells stories of courage, sadness, and hope ? of ordinary children who lived and died during the wartime.",
  q: ["What did you learn from this book about how ordinary children experienced war?",
      "Why do you think it's important for children today to read the stories of children who lived through war?",
      "What feeling did the stories in this book leave you with, and why?"],
  h: ["전쟁 중 평범한 아이들이 어떤 삶을 살았는지 이 책에서 무엇을 배웠나요?",
      "오늘날 아이들이 전쟁을 겪은 아이들의 이야기를 읽는 것이 왜 중요하다고 생각하나요?",
      "이 책 속 이야기들은 나에게 어떤 감정을 남겼나요? 그 이유는 무엇인가요?"] };
ACT["S4405"] = { s: "How much do you know about Ancient Egypt? This is a reference book set out like an encyclopedia about Ancient Egypt.",
  q: ["What is one entry or topic from this picture dictionary about Ancient Egypt that you found most interesting?",
      "If you could visit Ancient Egypt, what would you most want to see or learn about?",
      "Why do you think a picture dictionary is a good way to learn about a place like Ancient Egypt?"],
  h: ["이 고대 이집트 그림 사전에서 가장 흥미로웠던 항목이나 주제는 무엇인가요?",
      "고대 이집트를 방문할 수 있다면 가장 보고 싶거나 배우고 싶은 것은 무엇인가요?",
      "고대 이집트 같은 곳을 배우는 데 그림 사전이 좋은 방법인 이유는 무엇이라고 생각하나요?"] };
ACT["S4406"] = { s: "This book introduces a variety of monsters people believe their existence.",
  q: ["Which monster from this book did you find most interesting, and what do people believe about it?",
      "Do you know any monster stories from Korea or other countries? Tell about one.",
      "Why do you think people around the world have believed in monsters for so long?"],
  h: ["이 책에 나온 괴물 중 가장 흥미로웠던 것은 무엇이고, 사람들은 그것에 대해 무엇을 믿나요?",
      "한국이나 다른 나라의 괴물 이야기를 알고 있나요? 하나를 소개해 보세요.",
      "세계 여러 곳의 사람들이 오랫동안 괴물을 믿어 온 이유는 무엇이라고 생각하나요?"] };
ACT["S4407"] = { s: "This book introduces people working in newspapers, radio, and television news. In this book we follow one major news story as a tall ship hits rocks just off the coast of Cornwall, in England.",
  q: ["What did you learn about how news reporters and journalists cover a big story like the shipwreck in this book?",
      "Have you ever watched or read breaking news about an accident or emergency? What was it about?",
      "Why do you think it's important for news to reach people quickly when something like a shipwreck happens?"],
  h: ["이 책에 나온 좌초 사고 같은 큰 사건을 기자들이 어떻게 취재하는지 무엇을 배웠나요?",
      "사고나 긴급 상황에 대한 속보를 보거나 읽은 적이 있나요? 무슨 내용이었나요?",
      "배가 좌초하는 것 같은 일이 일어났을 때 뉴스가 사람들에게 빨리 전해지는 것이 왜 중요하다고 생각하나요?"] };
ACT["S4408"] = { s: "This book looks at some fun and fabulous shapes found in nature, but also explores the water cycle.",
  q: ["What shapes or things did this book find hidden in the clouds, and what did you learn about the water cycle?",
      "Have you ever looked up at clouds and imagined a shape? What did you see?",
      "Why do you think the water cycle is important for our planet?"],
  h: ["이 책은 구름 속에서 어떤 모양들을 찾아냈고, 물의 순환에 대해 무엇을 배웠나요?",
      "하늘을 보며 구름 모양을 상상해 본 적이 있나요? 무엇처럼 보였나요?",
      "물의 순환이 우리 지구에 왜 중요하다고 생각하나요?"] };
ACT["S4409"] = { s: "Do you know what the connection is between the Romans, Anglo-Saxons, and the days of our week? This book explains how they are closely related to.",
  q: ["What connection between the Romans, the Anglo-Saxons, and the days of the week did you learn from this book?",
      "Which day of the week is your favorite, and do you know anything about how it got its name?",
      "Why do you think it's interesting to learn where the names of ordinary things, like days of the week, come from?"],
  h: ["로마인, 앵글로색슨인, 그리고 요일 사이의 관계에 대해 이 책에서 무엇을 배웠나요?",
      "내가 가장 좋아하는 요일은 무엇인가요? 그 이름이 어떻게 생겼는지 알고 있나요?",
      "요일처럼 평범한 것의 이름이 어디서 왔는지 알아보는 것이 왜 재미있다고 생각하나요?"] };
ACT["S4410"] = { s: "Advertising helps people to understand a product or an idea. This book tells a long history of adverts and shows lots of examples.",
  q: ["What did you learn from this book about how advertising has changed throughout history?",
      "What is an advert (commercial or ad) that you remember well? Why do you remember it?",
      "Do you think adverts are always telling the truth about a product? Explain your thinking."],
  h: ["광고가 역사 속에서 어떻게 변해 왔는지 이 책에서 무엇을 배웠나요?",
      "내가 잘 기억하는 광고가 있나요? 왜 그 광고가 기억에 남나요?",
      "광고는 항상 제품에 대한 사실만 말한다고 생각하나요? 내 생각을 적어 보세요."] };
ACT["S4411"] = { s: "Electricity has changed our lives in many ways. Find out how electricity lights up our lives and develops the world.",
  q: ["What did you learn from this book about how electricity has changed people's lives?",
      "Think of one thing in your home that uses electricity. What would your day be like without it?",
      "Why do you think electricity is important for a country to develop?"],
  h: ["전기가 사람들의 삶을 어떻게 바꾸었는지 이 책에서 무엇을 배웠나요?",
      "우리 집에서 전기를 쓰는 물건 하나를 떠올려 보세요. 전기가 없다면 하루가 어떨 것 같나요?",
      "전기가 한 나라가 발전하는 데 왜 중요하다고 생각하나요?"] };
ACT["S4412"] = { s: "How do new words come about? Why does language change? Be prepared to discover everything you wanted to know about words and to be challenged by some Countdown anagrams!",
  q: ["What did you learn from this book about how new words are created and how language changes over time?",
      "Can you think of a new word or slang word that you use that your parents might not know? What does it mean?",
      "Why do you think it's fun to learn about words and how they change?"],
  h: ["새로운 단어가 어떻게 생겨나고 언어가 어떻게 변하는지 이 책에서 무엇을 배웠나요?",
      "내가 쓰지만 부모님은 모를 수도 있는 새로운 단어나 유행어가 있나요? 그것은 무슨 뜻인가요?",
      "단어와 그 변화에 대해 배우는 것이 왜 재미있다고 생각하나요?"] };
ACT["S4413"] = { s: "Read and marvel at how people throughout history, and even today, have lived under the shadow of the volcano.",
  q: ["What did you learn from this book about why people choose to live near volcanoes even though they are dangerous?",
      "Have you ever visited a mountain or seen a volcano in pictures? What did you think of it?",
      "If you lived near a volcano, what would worry you the most, and what would you do to stay safe?"],
  h: ["위험한데도 사람들이 화산 근처에 사는 이유에 대해 이 책에서 무엇을 배웠나요?",
      "산에 가 보거나 사진으로 화산을 본 적이 있나요? 어떤 생각이 들었나요?",
      "내가 화산 근처에 산다면 가장 걱정되는 것은 무엇이고, 안전하기 위해 무엇을 하겠나요?"] };
ACT["S4414"] = { s: "This book looks at the purpose, design, and properties of objects. Perhaps it will inspire you to design and create something precious.",
  q: ["What did you learn from this book about how the purpose and design of an object are connected?",
      "What is one object you own that you think is well designed? What makes it special?",
      "If you could design a new object, what would it be for and what would it look like?"],
  h: ["물건의 목적과 디자인이 어떻게 연결되어 있는지 이 책에서 무엇을 배웠나요?",
      "내가 가진 물건 중에 디자인이 잘 되었다고 생각하는 것은 무엇인가요? 무엇이 특별한가요?",
      "새로운 물건을 디자인한다면 무엇을 위한 것이고 어떤 모습일지 적어 보세요."] };
ACT["S4415"] = { s: "This book tells how we use our coasts and some of the ways in which we are trying to prevent further damage to them.",
  q: ["What did you learn from this book about the ways people use coasts and the damage that can happen to them?",
      "Have you ever visited a beach or coast? What did you notice about how people were using it?",
      "What is one thing you think people could do to help protect coasts?"],
  h: ["사람들이 해안을 어떻게 이용하고, 해안이 어떻게 손상될 수 있는지 이 책에서 무엇을 배웠나요?",
      "바닷가나 해안에 가 본 적이 있나요? 사람들이 그곳을 어떻게 이용하는지 무엇을 보았나요?",
      "해안을 보호하기 위해 사람들이 할 수 있는 일 한 가지를 적어 보세요."] };
ACT["S4416"] = { s: "Some children from poor families living in Victorian times had to work up to 14 hours a day. Read how working conditions gradually improved and how life became better for children.",
  q: ["What did you learn from this book about how working conditions for children changed over time?",
      "How do you think your daily life would be different if you had to work 14 hours a day like children in Victorian times?",
      "Why do you think it's important that children today have the right to go to school instead of working long hours?"],
  h: ["어린이들의 노동 환경이 시간이 지나면서 어떻게 바뀌었는지 이 책에서 무엇을 배웠나요?",
      "빅토리아 시대 아이들처럼 하루 14시간 일해야 한다면 내 일상은 어떻게 달라질 것 같나요?",
      "오늘날 아이들이 오랜 시간 일하는 대신 학교에 갈 권리를 가진 것이 왜 중요하다고 생각하나요?"] };
ACT["S4417"] = { s: "Simon Gunton, a classical trombonist and bass trumpet player, shares his first-hand experiences of making music.",
  q: ["What did you learn from this book about Simon Gunton's experience of making music as a trombonist?",
      "Have you ever played a musical instrument or wanted to learn one? Which one?",
      "Why do you think making music is meaningful to the people who do it?"],
  h: ["트롬본 연주자 사이먼 건튼이 음악을 만드는 경험에 대해 이 책에서 무엇을 배웠나요?",
      "악기를 연주해 본 적이 있거나 배우고 싶은 악기가 있나요? 무엇인가요?",
      "음악을 만드는 것이 그 일을 하는 사람들에게 의미 있는 이유는 무엇이라고 생각하나요?"] };
ACT["S4418"] = { s: "A grumpy, ugly, and occasionally malevolent Psammead, a sand-fairy with ability to grant wishes comes to the five children.",
  q: ["What kind of creature is the Psammead in this book, and what special power does it have?",
      "If a wish-granting creature like the Psammead came to you, what is one wish you would ask for?",
      "Do you think getting your wishes granted would always make you happy? Explain why or why not."],
  h: ["이 책 속 프사미드는 어떤 생물이고, 어떤 특별한 힘을 가지고 있나요?",
      "프사미드 같은 소원을 들어주는 생물이 나에게 온다면, 어떤 소원 하나를 빌고 싶나요?",
      "소원이 이루어지는 것이 항상 나를 행복하게 만들까요? 그렇다면, 혹은 아니라면 그 이유를 적어 보세요."] };
ACT["S4419"] = { s: "Mowgli is hunted by an evil tiger. Mowgli tries to live a peaceful life with other humans, but is too wild for them and too human for the wolves. Eventually Mowgli finds a home in the jungle.",
  q: ["Why does Mowgli struggle to belong with the humans and also with the wolves in this book?",
      "Have you ever felt like you didn't quite fit in with one group of people? What happened?",
      "Where do you think Mowgli truly belongs, and why?"],
  h: ["이 책에서 모글리는 왜 사람들 사이에도, 늑대들 사이에도 완전히 속하지 못하고 힘들어하나요?",
      "한 무리에 완전히 어울리지 못한다고 느낀 적이 있나요? 어떤 일이었나요?",
      "모글리가 진짜로 속한 곳은 어디라고 생각하나요? 그 이유는 무엇인가요?"] };
ACT["S4420"] = { s: "Mary Lennox lives in India with her wealthy British family. She is a selfish and disagreeable 10-year-old girl. When a cholera epidemic kills her parents and the servants, Mary is orphaned.",
  q: ["What kind of girl is Mary Lennox at the beginning of this book, and what happens to her family?",
      "Have you ever had to face a big change in your life, like moving somewhere new? How did you feel?",
      "What do you imagine will happen to Mary now that she has become an orphan?"],
  h: ["이 책의 처음에 메리 레녹스는 어떤 아이였고, 그녀의 가족에게는 무슨 일이 일어났나요?",
      "새로운 곳으로 이사하는 것처럼 삶에서 큰 변화를 겪은 적이 있나요? 어떤 기분이었나요?",
      "메리가 고아가 된 뒤 어떤 일이 일어날 것 같은지 상상해서 적어 보세요."] };
ACT["S4421"] = { s: "Set between 1625 and 1628, it recounts the adventures of a young man named d'Artagnan after he leaves home to travel to Paris, hoping to join the Musketeers of the Guard.",
  q: ["What is d'Artagnan's goal at the beginning of this book, and why does he travel to Paris?",
      "Have you ever left home or your usual place to try to achieve a goal? What was it?",
      "What kind of adventures do you imagine d'Artagnan will have on his way to becoming a Musketeer?"],
  h: ["이 책 처음에 다르타냥의 목표는 무엇이고, 그는 왜 파리로 떠나나요?",
      "어떤 목표를 이루기 위해 집이나 익숙한 곳을 떠나 본 적이 있나요? 무엇이었나요?",
      "다르타냥이 총사가 되기까지 어떤 모험을 겪을 것 같은지 상상해서 적어 보세요."] };
ACT["S4422"] = { s: "A girl befriends the ghost haunting Canterville Chase and helps him go into the afterlife. Horace and his family move into Canterville Chase, which is haunted by the ghost of Sir Simon, who killed his wife there.",
  q: ["How does the girl in this book help the ghost, Sir Simon, in the end?",
      "If you moved into a house you were told was haunted, how would you feel?",
      "Do you think the ghost in this story deserves to be helped, even though he killed his wife? Explain your thinking."],
  h: ["이 책에서 여자아이는 결국 유령인 사이먼 경을 어떻게 도와주나요?",
      "귀신이 나온다는 집으로 이사를 간다면 어떤 기분이 들 것 같나요?",
      "아내를 죽인 유령이지만, 이 이야기 속 유령은 도움을 받을 자격이 있다고 생각하나요? 내 생각을 적어 보세요."] };
ACT["S4423"] = { s: "A wolf dog that is rescued from its brutal owner and becomes domesticated through the patience and kindness?of its new owner.",
  q: ["How does White Fang change from the beginning of this book to the end?",
      "Have you ever seen an animal that was treated badly become gentle after someone was kind to it?",
      "What does this story teach you about the power of patience and kindness?"],
  h: ["이 책에서 화이트 팽은 처음부터 끝까지 어떻게 변하나요?",
      "나쁜 대우를 받던 동물이 누군가의 친절 덕분에 순해지는 것을 본 적이 있나요?",
      "이 이야기는 인내심과 친절의 힘에 대해 무엇을 가르쳐 주나요?"] };
ACT["S4424"] = { s: "This is a biography of the twentieth-century Spanish artist Pablo Picasso.",
  q: ["What is one fact about Pablo Picasso's life or art that you learned from this biography?",
      "Have you ever tried painting or drawing in an unusual style, like Picasso might have? What did you make?",
      "Why do you think Picasso is still remembered as a famous artist today?"],
  h: ["이 전기에서 파블로 피카소의 삶이나 작품에 대해 배운 사실 한 가지는 무엇인가요?",
      "피카소처럼 특이한 방식으로 그림을 그려 본 적이 있나요? 무엇을 그렸나요?",
      "피카소가 오늘날까지 유명한 화가로 기억되는 이유는 무엇이라고 생각하나요?"] };
ACT["S4425"] = { s: "This book presents the life and work of French Impressionist artist Claude Monet.",
  q: ["What did you learn about Claude Monet's life and his art style from this book?",
      "Have you ever seen a painting that looked blurry or made of small brush strokes, like Impressionist art? What did you think of it?",
      "Why do you think painting outdoors, like Monet did, might change the way an artist paints?"],
  h: ["이 책에서 클로드 모네의 삶과 그림 화풍에 대해 무엇을 배웠나요?",
      "인상파 그림처럼 흐릿하거나 작은 붓 자국으로 그려진 그림을 본 적이 있나요? 어떤 생각이 들었나요?",
      "모네처럼 야외에서 그림을 그리는 것이 화가의 그림 방식을 왜 바꿀 수 있다고 생각하나요?"] };
ACT["S4426"] = { s: "This book presents the life of Walt Disney and his affection for small-town life that was later reflected in Disneyland Main Streets.",
  q: ["What did you learn from this book about how Walt Disney's love of small-town life influenced Disneyland?",
      "Have you ever visited a Disney park or watched a Disney movie? What did you like about it?",
      "Why do you think it's interesting that a place someone loved as a child can show up in their later work?"],
  h: ["월트 디즈니가 어릴 적 좋아했던 작은 마을에 대한 사랑이 디즈니랜드에 어떻게 반영되었는지 이 책에서 무엇을 배웠나요?",
      "디즈니 놀이공원에 가 보거나 디즈니 영화를 본 적이 있나요? 무엇이 좋았나요?",
      "어릴 때 사랑했던 장소가 나중에 그 사람의 작품에 나타나는 것이 왜 흥미롭다고 생각하나요?"] };
ACT["S4427"] = { s: "This is a biography of Babe Ruth, one of the most famous players in major league baseball.",
  q: ["What did you learn from this book about what made Babe Ruth one of the most famous baseball players?",
      "Have you ever played or watched baseball? What do you like about the game?",
      "Why do you think some athletes, like Babe Ruth, are remembered for so many years after they stop playing?"],
  h: ["베이브 루스를 가장 유명한 야구 선수 중 한 명으로 만든 것이 무엇인지 이 책에서 무엇을 배웠나요?",
      "야구를 해 보거나 본 적이 있나요? 야구의 어떤 점이 좋은가요?",
      "베이브 루스 같은 선수들이 은퇴한 뒤에도 오랫동안 기억되는 이유는 무엇이라고 생각하나요?"] };
ACT["S4428"] = { s: "Joe Spud, the richest 12-year-old boy in the world, has everything he needs except a true friend, and he desperately wants one.",
  q: ["Why do you think Joe Spud, who has everything money can buy, still wants a true friend so badly?",
      "What do you think makes someone a true friend, more than the things they own?",
      "If you were Joe's first real friend, what would you want him to know about you?"],
  h: ["돈으로 살 수 있는 모든 것을 가진 조 스퍼드가 왜 그렇게 진짜 친구를 간절히 원한다고 생각하나요?",
      "가진 물건보다 더 중요하게, 무엇이 진짜 친구를 만든다고 생각하나요?",
      "내가 조의 첫 진짜 친구가 된다면, 나에 대해 무엇을 알려 주고 싶나요?"] };
ACT["S4429"] = { s: "Dennis has a lonely home life, and he takes comfort from playing soccer at school. One day he discovers his secret passion for fashion and wears a dress to school. But this endangers his chances of playing in the Final Cup.",
  q: ["What risk does Dennis take when he decides to wear a dress to school in this book?",
      "Have you ever done something you loved even though you worried what others might think? What was it?",
      "Do you think Dennis made the right choice? Explain your own opinion."],
  h: ["이 책에서 데니스가 드레스를 입고 학교에 가기로 했을 때 어떤 위험을 감수하나요?",
      "다른 사람이 어떻게 생각할지 걱정되면서도 내가 좋아하는 일을 해 본 적이 있나요? 무엇이었나요?",
      "데니스의 선택이 옳았다고 생각하나요? 내 생각을 적어 보세요."] };
ACT["S4430"] = { s: "Gilbert, Frank's dad, gets thrown into prison for driving the getaway car in a bank robbery. Frank devises a plan to break his father out of jail for the night so they can put the stolen money back. Will his plan succeed?",
  q: ["What plan does Frank come up with to help his dad in this book, and why does he want to do it?",
      "Have you ever tried to help a family member who was in trouble? What did you do?",
      "Do you think Frank's plan is a good idea? What do you think might go wrong?"],
  h: ["이 책에서 프랭크는 아빠를 돕기 위해 어떤 계획을 세우고, 왜 그렇게 하려고 하나요?",
      "어려움에 처한 가족을 도와주려고 해 본 적이 있나요? 무엇을 했나요?",
      "프랭크의 계획이 좋은 생각이라고 보나요? 무엇이 잘못될 수 있을지 적어 보세요."] };
ACT["S4431"] = { s: "When Tom gets a nasty bump on the head in a gym class, he lands in a hospital. When he joins the Midnight Gang, exhilarating adventures are waiting ahead of him.",
  q: ["What happens to Tom at the start of this book, and how does it lead him to the Midnight Gang?",
      "Have you ever been in a hospital, either as a patient or visiting someone? What was it like?",
      "What kind of adventure would you want the Midnight Gang to go on if you could join them?"],
  h: ["이 책 처음에 톰에게 무슨 일이 일어나고, 그 일이 어떻게 그를 미드나잇 갱으로 이끄나요?",
      "환자로든 병문안으로든 병원에 가 본 적이 있나요? 어떤 느낌이었나요?",
      "내가 미드나잇 갱에 들어간다면 어떤 모험을 하고 싶나요?"] };
ACT["S4432"] = { s: "Ben is unpleasant that he has to stay with his most boring grandma every Friday. But when he discovers that she used to be an international jewel thief, he can't wait to spend time at grandma's house.",
  q: ["How does Ben's feeling about visiting his grandma change in this book, and why?",
      "Have you ever discovered a surprising fact about someone in your family? What was it?",
      "If your grandparent had a secret exciting past like Ben's granny, what would you want to know about it?"],
  h: ["이 책에서 할머니를 방문하는 것에 대한 벤의 마음은 어떻게 바뀌고, 그 이유는 무엇인가요?",
      "가족 중 누군가에 대해 놀라운 사실을 알게 된 적이 있나요? 무엇이었나요?",
      "내 할머니나 할아버지에게 벤의 할머니처럼 신나는 비밀 과거가 있다면 무엇을 알고 싶나요?"] };
ACT["S4433"] = { s: "Chloe is unpopular, lonely, and overshadowed by her disgustingly talented sister. When Chloe makes friends with the local tramp, she brings and hides him in her shed.",
  q: ["Why does Chloe decide to help and hide Mr. Stink in her shed, do you think?",
      "Have you ever felt overshadowed by someone else, like a sibling or classmate? How did that feel?",
      "Do you think Chloe is taking a risk by hiding Mr. Stink? What might happen if her family finds out?"],
  h: ["클로이가 스팅크 아저씨를 도와 헛간에 숨겨 주기로 한 이유는 무엇이라고 생각하나요?",
      "형제나 친구처럼 누군가에게 가려진다고 느낀 적이 있나요? 어떤 기분이었나요?",
      "클로이가 스팅크 아저씨를 숨기는 것은 위험한 일이라고 생각하나요? 가족이 알게 되면 무슨 일이 일어날까요?"] };
ACT["S4434"] = { s: "Alfie discovers that kids in his town wake up to icky bugs instead of coins under their pillows from a tooth fairy. The boy suspects Miss Root, the creepy new dentist in town, is behind it all.",
  q: ["What strange thing is happening to kids' teeth in this book, and who does Alfie suspect is behind it?",
      "Have you ever lost a tooth and put it under your pillow? What happened?",
      "If you were Alfie, what would you do to find out the truth about Miss Root?"],
  h: ["이 책에서 아이들의 이에 어떤 이상한 일이 일어나고, 알피는 누구를 의심하나요?",
      "이가 빠져서 베개 밑에 넣어 본 적이 있나요? 무슨 일이 있었나요?",
      "내가 알피라면 미스 루트에 대한 진실을 알아내기 위해 무엇을 하겠나요?"] };
ACT["S4435"] = { s: "The Spanish teacher, Miss Holly, loves to celebrate holidays like Christmas. But when she starts hanging mistletoe everywhere, it seems Miss Holly is taking the holidays to the extreme!",
  q: ["What does Miss Holly do that makes the other characters think she is taking Christmas too far?",
      "What is your favorite way to celebrate a holiday like Christmas or New Year?",
      "Do you think there's a limit to how much someone should celebrate a holiday? Explain your thinking."],
  h: ["미스 홀리가 크리스마스를 지나치게 즐긴다고 다른 등장인물들이 생각하게 만든 행동은 무엇인가요?",
      "크리스마스나 설날 같은 명절을 즐기는 내가 가장 좋아하는 방법은 무엇인가요?",
      "명절을 즐기는 것에도 적당한 정도가 있어야 한다고 생각하나요? 내 생각을 적어 보세요."] };
ACT["S4436"] = { s: "When Jack and Annie get a mysterious invitation from Camelot, they travel to the magical kingdom and find a lost dragon.",
  q: ["What mission do Jack and Annie go on in this book after receiving the invitation from Camelot?",
      "If you received a mysterious invitation to a magical kingdom, would you go? Why or why not?",
      "What do you imagine the lost dragon looks like, and why do you think it got lost?"],
  h: ["카멜롯에서 초대장을 받은 뒤 잭과 애니는 이 책에서 어떤 임무를 떠나나요?",
      "마법의 왕국으로 초대하는 신비한 초대장을 받는다면 나는 가겠나요? 그 이유는 무엇인가요?",
      "길 잃은 용은 어떤 모습일지, 왜 길을 잃었을지 상상해서 적어 보세요."] };
ACT["S4437"] = { s: "Jack and Annie travel to India during the Mogul Empire in the 1600s, where they have to find an emerald needed to break a magic spell.",
  q: ["What do Jack and Annie need to find in India, and why is it so important?",
      "Have you ever had to search hard for something important that you lost? What was it?",
      "What dangers do you imagine Jack and Annie might face while searching for the emerald in a land with cobras?"],
  h: ["잭과 애니는 인도에서 무엇을 찾아야 하고, 그것이 왜 그렇게 중요한가요?",
      "잃어버린 중요한 것을 열심히 찾아본 적이 있나요? 무엇이었나요?",
      "코브라가 있는 곳에서 에메랄드를 찾는 동안 잭과 애니가 어떤 위험을 마주할지 상상해서 적어 보세요."] };
ACT["S4438"] = { s: "The magic tree house takes Jack and Annie back in time to mid-1800's Thebes, where they get help from Florence Nightingale after the accident.",
  q: ["How does Florence Nightingale help Jack and Annie in this book?",
      "Do you know anything about what Florence Nightingale did in real history? What have you heard?",
      "What do you think makes someone a hero, like Florence Nightingale is shown to be in this book?"],
  h: ["이 책에서 플로렌스 나이팅게일은 잭과 애니를 어떻게 도와주나요?",
      "실제 역사 속 플로렌스 나이팅게일이 한 일에 대해 알고 있나요? 무엇을 들어 보았나요?",
      "이 책 속 플로렌스 나이팅게일처럼, 무엇이 사람을 영웅으로 만든다고 생각하나요?"] };
ACT["S4439"] = { s: "Jack and Annie travel to Mexico City at the 1970 World Cup Games in search of the fourth secret of greatness for Merlin the Magician.",
  q: ["What are Jack and Annie searching for during the 1970 World Cup in this book?",
      "Have you ever watched or played in a soccer game? What was exciting about it?",
      "What do you think the \"secret of greatness\" that Jack and Annie are looking for might be?"],
  h: ["이 책에서 1970년 월드컵 동안 잭과 애니는 무엇을 찾고 있나요?",
      "축구 경기를 보거나 뛰어 본 적이 있나요? 무엇이 흥미진진했나요?",
      "잭과 애니가 찾고 있는 \"위대함의 비밀\"은 무엇일 것 같은지 상상해서 적어 보세요."] };
ACT["S4440"] = { s: "Jack and Annie are sent to a luxurious resort in Cozumel, Mexico, but their dream vacation turns into an adventure with ancient Mayans instead.",
  q: ["How does Jack and Annie's vacation in this book turn from relaxing into an adventure?",
      "Have you ever gone on a vacation that turned out different from what you expected? What happened?",
      "What do you imagine Jack and Annie learn from the ancient Mayans they meet?"],
  h: ["이 책에서 잭과 애니의 휴가는 어떻게 편안한 시간에서 모험으로 바뀌나요?",
      "생각했던 것과 다르게 흘러간 여행을 해 본 적이 있나요? 무슨 일이 있었나요?",
      "잭과 애니가 만난 고대 마야인들에게서 무엇을 배웠을지 상상해서 적어 보세요."] };
ACT["S4441"] = { s: "Mama Bear lays down the law when she notices her family is getting chubby.",
  q: ["What rule does Mama Bear make in this book, and why does she make it?",
      "What is your favorite healthy snack, and what is your favorite junk food?",
      "Do you think it's a good idea for families to have rules about food? Explain your thinking."],
  h: ["이 책에서 엄마 곰은 어떤 규칙을 만들고, 왜 그런 규칙을 만드나요?",
      "내가 가장 좋아하는 건강한 간식은 무엇이고, 가장 좋아하는 정크푸드는 무엇인가요?",
      "가족이 음식에 관한 규칙을 정하는 것이 좋은 생각이라고 보나요? 내 생각을 적어 보세요."] };
ACT["S4442"] = { s: "It's Mother's Day, and Papa and the cubs want to do something very special for Mama, but will they be able to keep it a secret?",
  q: ["What do Papa and the cubs plan to do for Mama in this book, and why is it hard to keep it a secret?",
      "What is something special you have done or would like to do for your mom on a special day?",
      "Why do you think surprises can be both fun and difficult to keep?"],
  h: ["이 책에서 아빠와 아기 곰들은 엄마를 위해 무엇을 계획하고, 왜 비밀을 지키기 어려운가요?",
      "특별한 날에 엄마를 위해 해 본 적이 있거나 해 보고 싶은 특별한 일이 있나요?",
      "깜짝 선물이 즐거우면서도 어려운 이유는 무엇이라고 생각하나요?"] };
ACT["S4443"] = { s: "It’s Halloween and Brother and Sister can’t wait to go trick-or-treating with all of their friends, but things don’t go as planned.",
  q: ["What goes wrong for Brother and Sister on Halloween night in this book?",
      "Have you ever gone trick-or-treating or celebrated Halloween? What did you do?",
      "If something didn't go as planned on a fun day for you, how did you handle it?"],
  h: ["이 책에서 할로윈 밤에 브라더와 시스터에게 무슨 일이 잘못되나요?",
      "할로윈에 사탕을 받으러 다니거나 할로윈을 즐겨 본 적이 있나요? 무엇을 했나요?",
      "즐거운 날에 계획대로 되지 않은 적이 있다면, 그때 어떻게 대처했나요?"] };
ACT["S4444"] = { s: "It's November, and the Bear family are entering the Thanksgiving Festival's Big Pumpkin Contest.",
  q: ["What contest does the Bear family enter in this book, and what do you think they need to do to win?",
      "Have you ever entered a contest or competition? What was it?",
      "What size and shape do you imagine the biggest pumpkin in the contest looks like?"],
  h: ["이 책에서 곰 가족은 어떤 대회에 참가하고, 이기려면 무엇을 해야 할 것 같나요?",
      "어떤 대회나 시합에 참가해 본 적이 있나요? 무엇이었나요?",
      "대회에서 가장 큰 호박은 어떤 크기와 모양일지 상상해서 적어 보세요."] };
ACT["S4445"] = { s: "While making their Christmas lists for Santa, Brother and Sister Bear realize that the true meaning of Christmas.",
  q: ["What do Brother and Sister Bear realize about the true meaning of Christmas in this book?",
      "What does Christmas or a winter holiday mean to you, beyond the presents?",
      "What is one thing you could do this year to focus on the true meaning of a holiday?"],
  h: ["이 책에서 브라더와 시스터 베어는 크리스마스의 진짜 의미에 대해 무엇을 깨닫나요?",
      "선물 말고, 크리스마스나 겨울 명절이 나에게 어떤 의미가 있나요?",
      "올해 명절의 진짜 의미에 집중하기 위해 내가 할 수 있는 일 한 가지를 적어 보세요."] };
ACT["S4446"] = { s: "Brother and Sister Bear create Earthsavers Club to deal with pollution in Bear Country.",
  q: ["What does the Earthsavers Club that Brother and Sister create do about pollution in Bear Country?",
      "Have you ever done something to help take care of the environment? What was it?",
      "If you started a club like the Earthsavers, what is the first thing you would want your club to do?"],
  h: ["브라더와 시스터가 만든 어스세이버스 클럽은 베어 컨트리의 오염에 대해 무엇을 하나요?",
      "환경을 돌보기 위해 무언가를 해 본 적이 있나요? 무엇이었나요?",
      "내가 어스세이버스 같은 클럽을 만든다면 가장 먼저 하고 싶은 일은 무엇인가요?"] };
ACT["S4447"] = { s: "Brother and Sister love to play sports, so when Mama becomes the official soccer mom, Papa feels a bit left out.",
  q: ["Why does Papa feel left out in this book, and what is happening with Mama and the cubs?",
      "Has a parent or family member of yours ever helped with a sport or activity you do? What did they do?",
      "What could Papa do to feel more included in the family's soccer activities?"],
  h: ["이 책에서 아빠는 왜 소외감을 느끼고, 엄마와 아기 곰들에게는 무슨 일이 일어나고 있나요?",
      "내가 하는 운동이나 활동을 부모님이나 가족이 도와준 적이 있나요? 무엇을 해 주셨나요?",
      "아빠가 가족의 축구 활동에 더 함께하려면 무엇을 할 수 있을까요?"] };
ACT["S4448"] = { s: "It's vacation time, and the young Bears learn what it's like to live at camp.",
  q: ["What new things do the young Bears learn about living at camp in this book?",
      "Have you ever been to a camp or stayed away from home overnight? What was that like?",
      "If you went to camp, what activity would you be most excited to try?"],
  h: ["이 책에서 아기 곰들은 캠프 생활에 대해 어떤 새로운 것들을 배우나요?",
      "캠프에 가 보거나 집을 떠나 밤을 보내 본 적이 있나요? 어떤 느낌이었나요?",
      "내가 캠프에 간다면 가장 해 보고 싶은 활동은 무엇인가요?"] };
ACT["S4449"] = { s: "It’s time for baseball tryouts and Brother is feeling the pressure.",
  q: ["Why is Brother feeling pressure in this book, and what is he trying out for?",
      "Have you ever felt nervous before trying out for something or taking a test? What helped you?",
      "What advice would you give Brother to help him feel less pressure before his tryout?"],
  h: ["이 책에서 브라더는 왜 부담을 느끼고, 무엇을 위해 시도를 하고 있나요?",
      "무언가를 시도하거나 시험을 보기 전에 긴장한 적이 있나요? 무엇이 도움이 되었나요?",
      "시도를 앞두고 부담을 덜 느끼도록 브라더에게 어떤 조언을 해 주고 싶나요?"] };
ACT["S4450"] = { s: "There’s a new cub at school, Queenie McBear, and Sister really wants to be her friend.",
  q: ["Why does Sister want to be friends with Queenie McBear so much in this book?",
      "Have you ever really wanted to be friends with someone new at school? What did you do?",
      "What do you think Sister should look for in Queenie before deciding to be close friends with her?"],
  h: ["이 책에서 시스터는 왜 퀴니 맥베어와 그렇게 친구가 되고 싶어 하나요?",
      "학교에 새로 온 친구와 정말 친해지고 싶었던 적이 있나요? 나는 어떻게 했나요?",
      "시스터가 퀴니와 친한 친구가 되기 전에 무엇을 살펴봐야 한다고 생각하나요?"] };
ACT["S4451"] = { s: "Lizzy Bruin's slumber party becomes even wilder when Too-Tall Grizzly and his friends decide to attend uninvited.",
  q: ["What happens to Lizzy Bruin's slumber party when Too-Tall Grizzly and his friends show up uninvited?",
      "Have you ever been to a party or sleepover where something unexpected happened? What was it?",
      "What would you do if uninvited guests showed up at your party?"],
  h: ["초대받지 않은 투톨 그리즐리와 친구들이 나타났을 때 리지 브루인의 파자마 파티에 무슨 일이 일어나나요?",
      "파티나 파자마 파티에서 예상치 못한 일이 일어난 적이 있나요? 무엇이었나요?",
      "내 파티에 초대하지 않은 손님들이 나타난다면 나는 어떻게 하겠나요?"] };
ACT["S4452"] = { s: "Brother isn’t doing his schoolwork, and it’s starting to catch up with him. Now that he got a bad grade on his quiz, how is he going to tell Mama and Papa?",
  q: ["What problem is Brother facing in this book, and what is he worried about?",
      "Have you ever gotten a bad grade or made a mistake you were nervous to tell your parents about? What happened?",
      "What advice would you give Brother about telling his parents the truth?"],
  h: ["이 책에서 브라더는 어떤 문제를 겪고 있고, 무엇을 걱정하고 있나요?",
      "나쁜 성적을 받거나 부모님께 말하기 두려운 실수를 한 적이 있나요? 무슨 일이 있었나요?",
      "부모님께 사실대로 말하는 것에 대해 브라더에게 어떤 조언을 해 주고 싶나요?"] };
ACT["S4453"] = { s: "Mama Bear decides to start a Bear Family Politeness Plan with a set of simple rules and penalties.",
  q: ["What is the Bear Family Politeness Plan in this book, and why does Mama Bear start it?",
      "What manners do you think are the most important to remember every day?",
      "If your family made a politeness plan like the Bears, what rule would you suggest?"],
  h: ["이 책에서 베어 가족 예절 계획이란 무엇이고, 엄마 곰은 왜 그것을 시작하나요?",
      "매일 기억해야 할 예절 중에 가장 중요하다고 생각하는 것은 무엇인가요?",
      "우리 가족이 곰 가족처럼 예절 계획을 만든다면 어떤 규칙을 제안하고 싶나요?"] };
ACT["S4454"] = { s: "The entire Bear family becomes involved in an attempt to clean and organize the cubs' messy room.",
  q: ["How does the whole Bear family get involved in cleaning the cubs' room in this book?",
      "How messy or clean is your own room usually? How do you feel about cleaning it?",
      "What is one tip you would give the Bear cubs to keep their room from getting messy again?"],
  h: ["이 책에서 곰 가족 전체가 아기 곰들의 어질러진 방을 치우는 데 어떻게 함께하나요?",
      "내 방은 평소에 얼마나 어질러져 있거나 깨끗한가요? 방 청소에 대해 어떻게 생각하나요?",
      "방이 다시 어질러지지 않도록 아기 곰들에게 해 주고 싶은 조언 한 가지는 무엇인가요?"] };
ACT["S4455"] = { s: "Brother and Sister Bear learn some important lessons about earning and spending money.",
  q: ["What lessons about earning and spending money do Brother and Sister learn in this book?",
      "Have you ever earned or saved money for something you wanted? What did you do?",
      "What is one rule you think is important to follow when spending money?"],
  h: ["이 책에서 브라더와 시스터는 돈을 벌고 쓰는 것에 대해 어떤 중요한 교훈을 배우나요?",
      "원하는 것을 사려고 돈을 벌거나 모아 본 적이 있나요? 어떻게 했나요?",
      "돈을 쓸 때 지키는 것이 중요하다고 생각하는 규칙 한 가지는 무엇인가요?"] };
ACT["S4456"] = { s: "This book introduces the world's big cats, including lions, tigers, cheetahs, jaguars, and so on.",
  q: ["Which big cat from this book - lions, tigers, cheetahs, or jaguars - did you find most interesting, and why?",
      "Have you ever seen a big cat at a zoo or in a video? What did you notice about it?",
      "If you could study one big cat closely for a day, which one would you choose and what would you want to learn?"],
  h: ["이 책에 나온 큰 고양잇과 동물 - 사자, 호랑이, 치타, 재규어 - 중 가장 흥미로웠던 것은 무엇이고, 그 이유는 무엇인가요?",
      "동물원이나 영상에서 큰 고양잇과 동물을 본 적이 있나요? 무엇을 알아차렸나요?",
      "하루 동안 큰 고양잇과 동물 하나를 자세히 관찰할 수 있다면 어떤 동물을 고르고 무엇을 배우고 싶나요?"] };
ACT["S4457"] = { s: "Michaela DePrince was adopted to a family and brought to America. She decided to make her dream of becoming ballerina come true.",
  q: ["What dream does Michaela DePrince have in this book, and what does she do to make it come true?",
      "Do you have a dream you really want to make come true? What is it?",
      "What do you think helped Michaela keep working toward her dream, even when it might have been hard?"],
  h: ["이 책에서 미카엘라 드프린스는 어떤 꿈을 가지고 있고, 그 꿈을 이루기 위해 무엇을 하나요?",
      "나에게도 꼭 이루고 싶은 꿈이 있나요? 무엇인가요?",
      "힘들 때에도 미카엘라가 꿈을 향해 계속 나아갈 수 있었던 것은 무엇 덕분이었을 것 같나요?"] };
ACT["S4458"] = { s: "Until 1947, black baseball players couldn't be on the major-league baseball teams. Jackie Robinson was a great player with a tough mind to be the first black major-league baseball player. The story tells the history of black baseball with many other great black baseball players.",
  q: ["What did Jackie Robinson have to overcome to become the first Black player in Major League Baseball, according to this book?",
      "Why do you think it took courage for Jackie Robinson to be the first player to break this rule?",
      "What do you think we can learn today from Jackie Robinson's story about fairness?"],
  h: ["이 책에 따르면 재키 로빈슨이 메이저리그 최초의 흑인 선수가 되기 위해 이겨내야 했던 것은 무엇인가요?",
      "재키 로빈슨이 이 규칙을 처음으로 깨는 선수가 되는 데 용기가 필요했던 이유는 무엇이라고 생각하나요?",
      "재키 로빈슨의 이야기에서 오늘날 우리가 공정함에 대해 배울 수 있는 것은 무엇이라고 생각하나요?"] };
ACT["S4459"] = { s: "A paleontologist explains interesting facts about a pack of raptors. He talks about giant veggie-saurs, and how the raptors hunt them.",
  q: ["What did you learn from this book about how raptors hunted in packs?",
      "Have you ever learned about dinosaurs from a book, museum, or movie? What did you find most interesting?",
      "If you were a paleontologist studying raptors, what question would you most want to answer?"],
  h: ["랩터들이 무리를 지어 어떻게 사냥했는지 이 책에서 무엇을 배웠나요?",
      "책이나 박물관, 영화를 통해 공룡에 대해 배운 적이 있나요? 무엇이 가장 흥미로웠나요?",
      "내가 랩터를 연구하는 고생물학자라면 가장 알아내고 싶은 질문은 무엇인가요?"] };
ACT["S4460"] = { s: "When Bobby wakes up and finds himself invisible, he and his parents and his new blind friend Alicia try to find out what caused his invisibility and how to reverse it.",
  q: ["What problem does Bobby wake up with in this book, and who helps him try to solve it?",
      "If you suddenly became invisible, what is the first thing you would do?",
      "Why do you think Bobby's friendship with a blind girl, Alicia, might be especially important while he is invisible?"],
  h: ["이 책에서 바비는 눈을 뜨자 어떤 문제를 겪고, 누가 그 문제를 해결하도록 도와주나요?",
      "내가 갑자기 투명인간이 된다면 가장 먼저 무엇을 하고 싶나요?",
      "바비가 투명인간이 된 동안 앞을 보지 못하는 앨리시아와의 우정이 특히 중요할 것 같은 이유는 무엇인가요?"] };
ACT["S4461"] = { s: "Self-described cynic Flora Belle Buckman is not easily surprised, but a flying superhero squirrel and William Spiver put a whole new spin on her life.",
  q: ["What unexpected thing happens to change Flora's life in this book?",
      "Have you ever had an unexpected event completely change your day or your plans? What happened?",
      "Why do you think a squirrel with superpowers would be surprising to a cynic like Flora?"],
  h: ["이 책에서 플로라의 삶을 바꾸는 예상치 못한 일은 무엇인가요?",
      "예상치 못한 일이 내 하루나 계획을 완전히 바꿔 놓은 적이 있나요? 무슨 일이 있었나요?",
      "플로라처럼 냉소적인 사람에게 초능력을 가진 다람쥐가 놀라운 이유는 무엇이라고 생각하나요?"] };
ACT["S4462"] = { s: "Shy Virgil gets trapped at the bottom of a well while he was trying to find his backpack and rescue Gulliver. The universe orchestrates a series of coincidences, and Virgil gets rescued. It may have been his fate.",
  q: ["What series of events leads to Virgil being trapped at the bottom of a well in this book?",
      "Have you ever been helped by a lucky coincidence when you were in trouble? What happened?",
      "Do you believe things can happen because they are \"meant to be,\" like the book suggests about Virgil? Explain your thinking."],
  h: ["이 책에서 버질이 우물 바닥에 갇히게 되는 일련의 사건은 무엇인가요?",
      "어려움에 처했을 때 운 좋은 우연 덕분에 도움을 받은 적이 있나요? 무슨 일이 있었나요?",
      "이 책이 버질에 대해 말하듯, 어떤 일은 \"그렇게 되도록 정해져 있다\"고 믿나요? 내 생각을 적어 보세요."] };
ACT["S4463"] = { s: "This book describes the work scientists do to find out more about these huge prehistoric animals.",
  q: ["What did you learn from this book about how scientists find out information about dinosaurs?",
      "Have you ever wanted to dig for fossils or bones? Where would you want to look?",
      "Why do you think it takes so much careful work for scientists to learn about creatures that lived so long ago?"],
  h: ["과학자들이 공룡에 대한 정보를 어떻게 알아내는지 이 책에서 무엇을 배웠나요?",
      "화석이나 뼈를 파 보고 싶었던 적이 있나요? 어디에서 찾아보고 싶나요?",
      "아주 오래전에 살았던 생물에 대해 알아내는 데 과학자들의 세심한 노력이 많이 필요한 이유는 무엇이라고 생각하나요?"] };
ACT["S4464"] = { s: "Forced to live in the family car after her father leaves, Georgina persuades her younger brother to help her in a scheme to get money by stealing a dog and then claiming a reward.",
  q: ["What difficult situation is Georgina's family in at the start of this book, and what plan does she come up with?",
      "Have you ever been part of a hard family situation that made you want to find a quick solution? What was it?",
      "Do you think Georgina's plan to steal a dog is the right way to solve her family's problem? Explain your own opinion."],
  h: ["이 책 처음에 조지나의 가족은 어떤 어려운 상황에 처해 있고, 그녀는 어떤 계획을 세우나요?",
      "빠른 해결책을 찾고 싶게 만드는 힘든 가족 상황을 겪어 본 적이 있나요? 무엇이었나요?",
      "개를 훔치는 조지나의 계획이 가족 문제를 해결하는 옳은 방법이라고 생각하나요? 내 생각을 적어 보세요."] };
ACT["S4465"] = { s: "The Penderwick sisters spend a summer holiday in Arundel. There they meet the son of Arundel's owner, Jeffrey, who becomes the perfect companion for their adventure.",
  q: ["How do the Penderwick sisters meet Jeffrey in this book, and what kind of companion does he become?",
      "Have you ever made a new friend while on vacation or in a new place? How did you meet?",
      "What kind of summer adventure would you want to have with new friends like Jeffrey?"],
  h: ["이 책에서 펜더윅 자매는 제프리를 어떻게 만나고, 그는 어떤 친구가 되나요?",
      "여행이나 새로운 장소에서 새 친구를 사귀어 본 적이 있나요? 어떻게 만났나요?",
      "제프리 같은 새 친구와 함께 어떤 여름 모험을 하고 싶나요?"] };
ACT["S4466"] = { s: "A witch, a swamp monster, and a perfectly tiny dragon raise a young girl named Luna, who must unlock the powerful magic buried deep inside her to save the people of the Protectorate.",
  q: ["Who raises Luna in this book, and what must she do to save the people of the Protectorate?",
      "If you had powerful magic buried inside you that you didn't know about, how do you think you would discover it?",
      "Why do you think it's interesting that Luna is raised by a witch, a swamp monster, and a dragon instead of a normal family?"],
  h: ["이 책에서 루나를 키우는 것은 누구이고, 프로텍토레이트의 사람들을 구하기 위해 그녀는 무엇을 해야 하나요?",
      "내 안에 숨겨진 강력한 마법이 있다면, 나는 그것을 어떻게 알게 될 것 같나요?",
      "루나가 평범한 가족이 아니라 마녀와 늪 괴물, 용에게 자랐다는 것이 왜 흥미롭다고 생각하나요?"] };
ACT["S4467"] = { s: "Auggie Pullman, who was born with extreme facial abnormalities, enters fifth grade at a private middle school. He struggles to be seen as an ordinary boy, enduring bullying and taunts.",
  q: ["What challenge does Auggie face when he starts fifth grade in this book?",
      "Have you ever seen someone be bullied or teased for being different? What did you do or wish you had done?",
      "What do you think it means to see Auggie as \"an ordinary boy,\" and why is that important to him?"],
  h: ["이 책에서 어기가 5학년을 시작하며 마주하는 어려움은 무엇인가요?",
      "다르다는 이유로 누군가 괴롭힘이나 놀림을 당하는 것을 본 적이 있나요? 나는 무엇을 했거나 하고 싶었나요?",
      "어기를 \"평범한 남자아이\"로 봐 주는 것은 어떤 의미이고, 그것이 어기에게 왜 중요할까요?"] };
ACT["S4468"] = { s: "When Mallory and Jared attempt to rescue Simon from goblins, they use a magical stone which enables them to see things that are normally invisible. The coauthor is Holly Black.",
  q: ["What special ability does the magical stone give Mallory and Jared in this book?",
      "If you had a magical way to see invisible things, what would you most want to look for?",
      "Why do you think rescuing Simon from the goblins would be dangerous, based on what you know from this book?"],
  h: ["이 책에서 마법의 돌은 맬러리와 재러드에게 어떤 특별한 능력을 주나요?",
      "보이지 않는 것을 볼 수 있는 마법이 있다면, 무엇을 가장 찾아보고 싶나요?",
      "이 책의 내용을 바탕으로, 고블린에게서 사이먼을 구하는 것이 왜 위험할 것 같은지 적어 보세요."] };
ACT["S4469"] = { s: "After Mallory is kidnapped at her fencing meet, Jared and Simon search for her in a cave but find themselves surrounded by dwarves and goblins. The book is filled with adventure, suspense, and magical creatures, making it a thrilling read for fans of fantasy and adventure.",
  q: ["What happens to Mallory in this book, and what do Jared and Simon do to try to find her?",
      "Have you ever had to search for something or someone important? What did you do?",
      "What do you imagine it would feel like to be surrounded by dwarves and goblins in a cave?"],
  h: ["이 책에서 맬러리에게 무슨 일이 일어나고, 재러드와 사이먼은 그녀를 찾기 위해 무엇을 하나요?",
      "중요한 무언가나 누군가를 찾아본 적이 있나요? 나는 무엇을 했나요?",
      "동굴 안에서 난쟁이와 고블린들에게 둘러싸인다면 어떤 기분일지 상상해서 적어 보세요."] };
ACT["S4470"] = { s: "Jared, Mallory, and Simon come face to face with a wicked ogre who has taken their mother captive. To bring their family back together, they seek the assistance of a friendly brownie, a hobgoblin, and other allies in their daring journey.",
  q: ["Why do Jared, Mallory, and Simon seek help from a brownie and a hobgoblin in this book?",
      "Have you ever needed help from unusual friends or allies to solve a big problem? Who helped you?",
      "What do you think the children will need to do to save their mother from the ogre?"],
  h: ["이 책에서 재러드, 맬러리, 사이먼은 왜 브라우니와 홉고블린에게 도움을 구하나요?",
      "큰 문제를 해결하기 위해 특이한 친구나 동료의 도움이 필요했던 적이 있나요? 누가 도와주었나요?",
      "아이들이 오우거에게서 엄마를 구하기 위해 무엇을 해야 할 것 같은지 상상해서 적어 보세요."] };
ACT["S4471"] = { s: "Penny, who is about to turn twelve in the summer of 1953, has gained a better understanding of herself and her family. In addition, she has discovered a secret regarding her father's death.",
  q: ["What secret does Penny discover about her father's death in this book?",
      "Have you ever learned a surprising truth about your family's past? What was it?",
      "How do you think discovering this secret changes the way Penny understands her family?"],
  h: ["이 책에서 페니는 아빠의 죽음에 대해 어떤 비밀을 알게 되나요?",
      "우리 가족의 과거에 대해 놀라운 진실을 알게 된 적이 있나요? 무엇이었나요?",
      "이 비밀을 알게 된 것이 페니가 가족을 이해하는 방식을 어떻게 바꿀 것 같은지 적어 보세요."] };
ACT["S4472"] = { s: "This book is an abridged version of the tale about a bellringer named Quasimodo, who has a hunchback. He struggles to rescue a lovely gypsy dancer named Esmeralda from being unfairly punished by the law.",
  q: ["What does Quasimodo try to do for Esmeralda in this book, and why does she need his help?",
      "Have you ever stood up to help someone who was being treated unfairly? What did you do?",
      "Why do you think Quasimodo, even though people are afraid of his appearance, is willing to help Esmeralda?"],
  h: ["이 책에서 콰지모도는 에스메랄다를 위해 무엇을 하려 하고, 그녀는 왜 그의 도움이 필요한가요?",
      "부당한 대우를 받는 누군가를 도와주기 위해 나선 적이 있나요? 무엇을 했나요?",
      "사람들이 그의 외모를 무서워하는데도 콰지모도가 에스메랄다를 기꺼이 돕는 이유는 무엇이라고 생각하나요?"] };
ACT["S4473"] = { s: "During the war between the French and the English, two daughters of an English general are getting ready to go back to their home. However, their safety is at risk when their Native American guide betrays them. They must rely on a clever forest tracker named Hawkeye and his companions, Chingachkook and Uncas, for protection.",
  q: ["What danger do the two daughters face in this book, and who helps to protect them?",
      "Have you ever had to trust someone to keep you safe in a difficult situation? Who was it?",
      "Why do you think being betrayed by their guide makes the daughters' journey even more frightening?"],
  h: ["이 책에서 두 딸은 어떤 위험에 처하고, 누가 그들을 보호하는 데 도움을 주나요?",
      "어려운 상황에서 나를 지켜 줄 누군가를 믿어야 했던 적이 있나요? 누구였나요?",
      "안내인에게 배신당한 것이 두 딸의 여정을 더욱 무섭게 만드는 이유는 무엇이라고 생각하나요?"] };
ACT["S4474"] = { s: "During the Great Depression, Mary Alice, a teenager of fifteen, is sent to live with her formidable grandmother in the countryside of Illinois. Mary Alice gains a deeper understanding and appreciation of her grandmother's true nature through the time spent with her.",
  q: ["How does Mary Alice's opinion of her grandmother change over the course of this book?",
      "Have you ever gotten to know a family member better after spending a lot of time with them? What did you learn about them?",
      "Why do you think grandmothers, like the one in this book, are sometimes seen as tough or scary before people really get to know them?"],
  h: ["이 책이 흘러가는 동안 메리 앨리스의 할머니에 대한 생각은 어떻게 바뀌나요?",
      "오랜 시간을 함께 보낸 뒤 가족을 더 잘 알게 된 적이 있나요? 그 사람에 대해 무엇을 알게 되었나요?",
      "이 책 속 할머니처럼, 할머니들이 진짜 모습을 알기 전에는 때때로 무섭거나 엄해 보이는 이유는 무엇이라고 생각하나요?"] };
ACT["S4475"] = { s: "This story narrates Homer's epic about the Greek hero Odysseus and his challenging journey back home from the Trojan War.",
  q: ["What is the main journey that Odysseus makes in this book, and where is he trying to go?",
      "Have you ever taken a long or difficult trip to get back home? What was it like?",
      "Why do you think Odysseus's journey home became one of the most famous stories ever told?"],
  h: ["이 책에서 오디세우스가 하는 주된 여정은 무엇이고, 그는 어디로 가려고 하나요?",
      "집으로 돌아오기 위해 길고 힘든 여행을 해 본 적이 있나요? 어떤 여행이었나요?",
      "오디세우스의 귀향 이야기가 역사상 가장 유명한 이야기 중 하나가 된 이유는 무엇이라고 생각하나요?"] };
ACT["S4476"] = { s: "Thirteen-year-old Genesis feels self-conscious about her skin color and the challenges her family faces. However, she begins to discover a few aspects about herself that she appreciates.",
  q: ["What is Genesis self-conscious about at the beginning of this book, and what does she discover about herself?",
      "Have you ever felt self-conscious about something about yourself? How did you come to feel better about it?",
      "Why do you think it's important for Genesis to find things about herself that she appreciates?"],
  h: ["이 책 처음에 제네시스는 무엇에 대해 자의식을 느끼고, 자신에 대해 무엇을 발견하게 되나요?",
      "나 자신에 대해 자의식을 느낀 적이 있나요? 그것에 대해 어떻게 더 좋게 느끼게 되었나요?",
      "제네시스가 자신에 대해 좋아할 점들을 찾는 것이 왜 중요하다고 생각하나요?"] };
ACT["S4477"] = { s: "Merci Suarez, a determined sixth-grader, faces challenging family changes as her beloved grandfather's odd behavior goes unexplained. Will her family confront the issue they've been avoiding?",
  q: ["What is happening with Merci's grandfather in this book that worries her family?",
      "Have you ever noticed a family member acting differently and wondered why? What did you do?",
      "Why do you think Merci's family might be avoiding talking about what is happening with her grandfather?"],
  h: ["이 책에서 할아버지에게 일어나는 어떤 일이 메르시의 가족을 걱정시키나요?",
      "가족 중 누군가가 평소와 다르게 행동하는 것을 보고 궁금했던 적이 있나요? 나는 무엇을 했나요?",
      "메르시의 가족이 할아버지에게 일어나는 일에 대해 이야기하는 것을 피하는 이유는 무엇이라고 생각하나요?"] };
ACT["S4479"] = { s: "This abridged edition is a retelling of the adventures of a French professor and his two companions as they sail above and below the world’s oceans as prisoners on the fabulous electric submarine of the deranged Captain Nemo.",
  q: ["What situation are the French professor and his companions in during this book, and who holds them prisoner?",
      "If you were a prisoner on an amazing submarine, what would you be most curious to explore?",
      "Why do you think Captain Nemo might have wanted to keep the professor and his companions on his submarine?"],
  h: ["이 책에서 프랑스인 교수와 동료들은 어떤 상황에 처해 있고, 누가 그들을 포로로 잡고 있나요?",
      "내가 놀라운 잠수함에서 포로가 된다면, 가장 궁금해서 탐험하고 싶은 것은 무엇인가요?",
      "네모 선장이 교수와 동료들을 잠수함에 계속 두고 싶어 했던 이유는 무엇이라고 생각하나요?"] };
ACT["S4480"] = { s: "This abridged retelling of the Charles Dickens classic follows the adventures of an orphaned young man in Victorian England who is given a great deal of money by an unknown benefactor, enabling him to pursue an education and fulfill great expectations.",
  q: ["What opportunity does the young man in this book receive, and who gives it to him?",
      "If an unknown person suddenly gave you money to follow your dreams, what would you choose to do with it?",
      "Why do you think it might feel strange or exciting to not know who is helping you?"],
  h: ["이 책에서 주인공 청년은 어떤 기회를 얻고, 누가 그 기회를 주나요?",
      "알 수 없는 누군가가 갑자기 나에게 꿈을 이루라며 돈을 준다면, 나는 그것으로 무엇을 하고 싶나요?",
      "누가 나를 돕는지 모른다는 것이 이상하면서도 신나게 느껴질 수 있는 이유는 무엇이라고 생각하나요?"] };
ACT["S4481"] = { s: "This abridged retelling of the Herman Melville classic follows the adventures of a young seaman when he joins the crew of the whaling ship \"Pequod,\" led by the fanatical Captain Ahab in pursuit of the white whale Moby-Dick.",
  q: ["What is Captain Ahab determined to do in this book, and what does the young seaman think of joining his crew?",
      "Have you ever joined a group led by someone with a very strong, determined goal? What was that like?",
      "Why do you think chasing one specific whale across the ocean could be a dangerous obsession for Captain Ahab?"],
  h: ["이 책에서 에이헙 선장은 무엇을 하기로 굳게 결심하고, 젊은 선원은 그의 선원이 되는 것에 대해 어떻게 생각하나요?",
      "아주 강한 결심을 가진 누군가가 이끄는 무리에 들어가 본 적이 있나요? 어떤 느낌이었나요?",
      "바다 전체를 가로질러 한 마리의 고래를 쫓는 것이 에이헙 선장에게 위험한 집착이 될 수 있는 이유는 무엇이라고 생각하나요?"] };
ACT["S4482"] = { s: "Fun facts about icebergs, arctic animals, the Earth’s axis, and more.",
  q: ["What is one fun fact about icebergs, arctic animals, or the Earth's axis that you learned from this book?",
      "Have you ever seen ice, snow, or cold weather animals in real life or on TV? What did you notice?",
      "If you visited the North or South Pole, what would you most want to see?"],
  h: ["빙산이나 북극 동물, 지구의 축에 대해 이 책에서 배운 재미있는 사실 한 가지는 무엇인가요?",
      "실제로나 TV에서 얼음, 눈, 추운 지역의 동물을 본 적이 있나요? 무엇을 알아차렸나요?",
      "북극이나 남극을 방문한다면 가장 보고 싶은 것은 무엇인가요?"] };
ACT["S4483"] = { s: "Voting is something we do every day. It’s a way we can choose that gives us our own say.",
  q: ["What did you learn from this book about how voting gives people a say in choices?",
      "Have you ever voted on something, even something small like choosing a game or a snack with friends? What was it?",
      "Why do you think it's important for everyone to have a chance to vote and be heard?"],
  h: ["투표가 사람들에게 선택할 권리를 주는 방법에 대해 이 책에서 무엇을 배웠나요?",
      "친구들과 게임이나 간식을 고르는 것처럼 작은 것이라도 투표해 본 적이 있나요? 무엇이었나요?",
      "모든 사람이 투표하고 자신의 의견을 말할 기회를 가지는 것이 왜 중요하다고 생각하나요?"] };
ACT["S4484"] = { s: "The Cat in the Hat visits with Ice Age mammals on a whirlwind tour of the Pleistocene. Young readers will learn basic facts about the Great Ice Age and early human life, the characteristics of mammals, and the study of fossils.",
  q: ["What did you learn from this book about the animals and people who lived during the Great Ice Age?",
      "Have you ever seen a fossil or a picture of a prehistoric animal? What did you think of it?",
      "Why do you think studying fossils helps scientists understand what life was like long ago?"],
  h: ["대빙하기에 살았던 동물과 사람들에 대해 이 책에서 무엇을 배웠나요?",
      "화석이나 선사시대 동물 사진을 본 적이 있나요? 어떤 생각이 들었나요?",
      "화석을 연구하는 것이 과학자들이 아주 오래전의 삶을 이해하는 데 도움이 되는 이유는 무엇이라고 생각하나요?"] };
ACT["S4485"] = { s: "In the Nelson-Thomas household, three siblings are struggling to figure out their lives in the 1986. The one thing they share is an enthusiastic science teacher named Ms. Salonga, who inspires her students to dream big with endless possibilities as the launch date of the Challenger approaches.",
  q: ["What does Ms. Salonga inspire the siblings in this book to do, as the Challenger launch approaches?",
      "Has a teacher or another adult ever inspired you to dream big about something? What did they do?",
      "Why do you think the excitement of a space launch could help the siblings feel hopeful during a hard time in their family?"],
  h: ["챌린저호 발사가 다가오면서 살롱가 선생님은 이 책 속 삼남매가 무엇을 하도록 영감을 주나요?",
      "선생님이나 다른 어른이 나에게 큰 꿈을 꾸도록 영감을 준 적이 있나요? 그분은 무엇을 해 주셨나요?",
      "가족의 힘든 시기에 우주 발사의 설렘이 삼남매에게 희망을 줄 수 있는 이유는 무엇이라고 생각하나요?"] };
ACT["S4486"] = { s: "Eleven-year-old Barry Tucker faces the devastating impact of Hurricane Katrina in New Orleans. After his family's evacuation plans are halted due to his sister's sudden illness, they return home to endure the storm.",
  q: ["Why does Barry's family have to stay home and endure Hurricane Katrina instead of evacuating, according to this book?",
      "Have you ever experienced a big storm or had to prepare for one? What did your family do?",
      "What do you think would be the hardest part about staying in your home during a hurricane like Katrina?"],
  h: ["이 책에 따르면 배리의 가족은 왜 대피하지 못하고 집에 남아 허리케인 카트리나를 견뎌야 했나요?",
      "큰 폭풍을 겪어 보거나 폭풍에 대비해 본 적이 있나요? 우리 가족은 무엇을 했나요?",
      "카트리나 같은 허리케인 동안 집에 머무는 것에서 가장 힘든 부분은 무엇일 것 같나요?"] };
ACT["S4487"] = { s: "When 11-year-old Danny Crane is alone on his favorite Hawaiian beach, his world changes forever as World War II reaches the United States.",
  q: ["What is Danny Crane doing when the bombing of Pearl Harbor begins in this book, and how does his world change?",
      "Have you ever been somewhere ordinary when something big and unexpected happened? What was it?",
      "Why do you think it's important for readers today to learn about events like the bombing of Pearl Harbor?"],
  h: ["이 책에서 진주만 폭격이 시작될 때 대니 크레인은 무엇을 하고 있었고, 그의 세상은 어떻게 바뀌나요?",
      "평범한 곳에 있을 때 크고 예상치 못한 일이 일어난 적이 있나요? 무슨 일이었나요?",
      "진주만 폭격 같은 사건을 오늘날 독자들이 배우는 것이 왜 중요하다고 생각하나요?"] };
ACT["S4491"] = { s: "A timid boy named Tom reluctantly agrees to help professional ghostbuster Hetty Hyssop dispel an IRG (Incredibly Revolting Ghost) from an old house. Book #1",
  q: ["What job does Tom reluctantly agree to help Hetty Hyssop with in this book?",
      "Have you ever agreed to do something you were nervous about, even though you didn't really want to? What happened?",
      "What do you imagine an \"Incredibly Revolting Ghost\" might look or act like?"],
  h: ["이 책에서 톰은 헤티 히숍을 마지못해 도와 어떤 일을 하게 되나요?",
      "하고 싶지 않았지만 긴장하면서도 하기로 동의한 적이 있나요? 무슨 일이 있었나요?",
      "\"믿을 수 없이 역겨운 유령\"은 어떤 모습이고 어떻게 행동할지 상상해서 적어 보세요."] };
ACT["S4492"] = { s: "Strange and unpleasant things are happening at Gloomsbury Castle. The murderous ghost of the 400-year-old Totally Moldy Baroness has possessed the castle's owner, inflicting him with violent hiccups. Hugo, the moderately spooky ghost, is instantly smitten with the terrifying noblewoman, but Tom must devise a plan to get rid of the decaying royal forever.",
  q: ["What problem does Tom need to solve in this book involving the Totally Moldy Baroness?",
      "Have you ever had to come up with a clever plan to solve a tricky problem? What was your plan?",
      "Why do you think Hugo being smitten with the dangerous Baroness makes Tom's job even harder?"],
  h: ["이 책에서 톰은 완전히 곰팡이 핀 남작 부인과 관련해 어떤 문제를 해결해야 하나요?",
      "까다로운 문제를 해결하기 위해 기발한 계획을 세워 본 적이 있나요? 어떤 계획이었나요?",
      "위험한 남작 부인에게 휴고가 반한 것이 톰의 일을 더 어렵게 만드는 이유는 무엇이라고 생각하나요?"] };
ACT["S4493"] = { s: "In 2194 in Zimbabwe, General Matsika's three children are kidnapped and put to work in a plastic mine while three mutant detectives use their special powers to search for them.",
  q: ["What happens to General Matsika's children in this book, and who is trying to find them?",
      "If you had one special power like the mutant detectives in this book, what power would you want and why?",
      "Why do you think searching for kidnapped children in a future world like this one would be especially difficult?"],
  h: ["이 책에서 마치카 장군의 아이들에게 무슨 일이 일어나고, 누가 그들을 찾으려 하나요?",
      "이 책 속 돌연변이 탐정들처럼 특별한 능력을 하나 가질 수 있다면, 어떤 능력을 원하고 그 이유는 무엇인가요?",
      "이런 미래 세계에서 납치된 아이들을 찾는 것이 특히 어려울 것 같은 이유는 무엇이라고 생각하나요?"] };
ACT["S4494"] = { s: "Photographs, documents, and easy-to-read text look at the life and political career of Abraham Lincoln, the sixteenth president of the United States, and features reproductions of related primary source documents.",
  q: ["What did you learn from this book about Abraham Lincoln's life and his work as president?",
      "Why do you think looking at real photographs and documents helps you understand history better than just reading words?",
      "What is one question you would want to ask Abraham Lincoln if you could meet him?"],
  h: ["에이브러햄 링컨의 삶과 대통령으로서의 일에 대해 이 책에서 무엇을 배웠나요?",
      "실제 사진과 문서를 보는 것이 글만 읽는 것보다 역사를 더 잘 이해하는 데 도움이 되는 이유는 무엇이라고 생각하나요?",
      "에이브러햄 링컨을 만날 수 있다면 묻고 싶은 질문 한 가지는 무엇인가요?"] };
ACT["S4495"] = { s: "Congress passed the Indian Removal Act in 1830 with the intent of moving five large tribes to Indian Territory. The tribes could either move to the reservations or assimilate. As settlers kept moving west, more and more tribes were encountered, and all ultimately found themselves going to reservations. This new way of life was a vast change for the Indians.",
  q: ["What did you learn from this book about the Indian Removal Act and how it affected Native American tribes?",
      "Why do you think being forced to move away from your home would be such a hard experience for a tribe or a family?",
      "What do you think is important for people today to understand about this part of history?"],
  h: ["인디언 이주법과 그것이 원주민 부족들에게 미친 영향에 대해 이 책에서 무엇을 배웠나요?",
      "부족이나 가족이 살던 곳에서 강제로 떠나야 하는 것이 왜 그렇게 힘든 경험일 것 같은가요?",
      "오늘날 사람들이 이 역사에 대해 이해해야 할 중요한 것은 무엇이라고 생각하나요?"] };
ACT["S4496"] = { s: "Great Britain passed the Stamp Act and the Townshend Acts, which made colonists angry. Eventually they boycotted and refused to purchase British goods. Great Britain sent soldiers to the colonies, which caused conflict like the Boston Massacre and the Boston Tea Party. \"Common Sense\" by Thomas Paine helped convince people that they were no longer British citizens. The foundation for the American Revolution had been laid.",
  q: ["What did you learn from this book about the events that led up to the American Revolution?",
      "Which event from this book - the Boston Massacre, the Boston Tea Party, or something else - did you find most interesting, and why?",
      "Why do you think a piece of writing like \"Common Sense\" could help convince people to support a revolution?"],
  h: ["미국 혁명으로 이어진 사건들에 대해 이 책에서 무엇을 배웠나요?",
      "이 책에 나온 사건 중 보스턴 대학살이나 보스턴 차 사건처럼 가장 흥미로웠던 것은 무엇이고, 그 이유는 무엇인가요?",
      "\"상식\" 같은 글이 사람들이 혁명을 지지하도록 설득하는 데 도움이 될 수 있었던 이유는 무엇이라고 생각하나요?"] };
ACT["S4497"] = { s: "Christopher Columbus set out on August 3, 1492, to find the East by sailing west. Over the course of a few years, he convinced the king and queen of Spain to pay for his trip, promising them fame and riches in return. Columbus discovered more than he bargained for-he had found a new continent.",
  q: ["What did Christopher Columbus set out to do in this book, and what did he discover instead?",
      "Have you ever set out to do one thing but ended up discovering something completely different? What happened?",
      "Why do you think Columbus had to work hard to convince the king and queen of Spain to pay for his trip?"],
  h: ["이 책에서 크리스토퍼 콜럼버스는 무엇을 하려고 떠났고, 대신 무엇을 발견했나요?",
      "한 가지를 하려고 떠났다가 완전히 다른 것을 발견하게 된 적이 있나요? 무슨 일이 있었나요?",
      "콜럼버스가 스페인의 왕과 여왕을 설득해 여행 비용을 받아내기 위해 애써야 했던 이유는 무엇이라고 생각하나요?"] };
ACT["S4498"] = { s: "The American Indian culture consisted of specific customs and traditions that regulated everything from who would lead the tribes to who would marry within the tribes. They kept precise, detailed accounts of their tribal histories because they foresaw the importance of passing down their histories.",
  q: ["What did you learn from this book about how American Indian tribes kept and passed down their histories?",
      "Does your family have any stories or traditions that get passed down from older generations? What are they?",
      "Why do you think it was important for these tribes to keep such detailed and precise records of their history?"],
  h: ["아메리카 원주민 부족들이 자신들의 역사를 어떻게 기록하고 전해 왔는지 이 책에서 무엇을 배웠나요?",
      "우리 가족에게도 윗세대로부터 전해 내려오는 이야기나 전통이 있나요? 무엇인가요?",
      "이 부족들이 자신들의 역사를 그렇게 자세하고 정확하게 기록하는 것이 중요했던 이유는 무엇이라고 생각하나요?"] };
ACT["S4499"] = { s: "The westward expansion of the United States included obtaining several areas of land including the Louisiana Territory, Texas, the Gadsden Purchase, and Alaska; these acquisitions changed the course of America forever.",
  q: ["What did you learn from this book about the lands the United States gained during its westward expansion?",
      "If you could travel to see one of these newly added lands - like the Louisiana Territory or Alaska - which would you choose, and why?",
      "Why do you think gaining so much new land changed the course of America forever?"],
  h: ["미국이 서부로 확장하면서 얻은 땅들에 대해 이 책에서 무엇을 배웠나요?",
      "루이지애나 준주나 알래스카처럼 새로 얻은 땅 중 하나를 여행할 수 있다면 어디를 고르고 싶고, 그 이유는 무엇인가요?",
      "그렇게 많은 새로운 땅을 얻은 것이 미국의 앞날을 완전히 바꾸어 놓은 이유는 무엇이라고 생각하나요?"] };
