// 간이 학습 질문 — Book No. S45 묶음. 사람이 아니라 AI 가 한 번 쓰고 굳힌 파일이다.
window.ACT = window.ACT || {};
var ACT = window.ACT;
ACT["S4500"] = { s: "From the Vikings to Henry Hudson, the great explorers sailed across uncharted waters during the Age of Discovery in search of many things, including adventure and wealth. Their exploration not only changed maps of the world but also paved the way for the settlement of the New World.",
  q: ["Choose one explorer mentioned in this book's story of the Age of Discovery and write a paragraph about what you imagine his voyage was like.",
      "The summary says these explorers were looking for adventure and wealth. Write a paragraph about something you would want to explore or discover if you could, and why.",
      "This book says exploration changed maps of the world but also paved the way for settling the New World. Write a paragraph giving your opinion on whether that change was mostly good or mostly harmful, and explain why."],
  h: ["이 책이 다루는 대항해시대의 탐험가 한 명을 골라, 그의 항해가 어땠을지 상상하며 문단으로 써 보세요.",
      "요약에는 탐험가들이 모험과 부를 찾아 나섰다고 나와 있어요. 여러분이 탐험하거나 발견해 보고 싶은 것이 있다면 무엇이고 왜 그런지 문단으로 써 보세요.",
      "이 책은 탐험이 세계 지도를 바꾸었지만 동시에 신대륙 정착의 길을 열었다고 말해요. 그 변화가 대체로 좋았다고 생각하는지 해로웠다고 생각하는지 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S4501"] = { s: "Harriet Tubman was a slave who dreamed of freedom from a very young age. After her escape at 29, she did everything she could to help and rescue other slaves. In her later years, she built a home to take care of elderly African Americans with no place to live and encouraged women to stand together for their rights.",
  q: ["This book describes several things Harriet Tubman did after she escaped: rescuing other slaves, building a home for elderly African Americans, and encouraging women to stand together for their rights. Choose the one you find most impressive and write a paragraph explaining why.",
      "Harriet Tubman dreamed of freedom from a very young age. Write a paragraph about something you have dreamed of for a long time, and what you have done or plan to do to reach it.",
      "Write a paragraph giving your opinion on why Harriet Tubman kept helping others even after she herself was free, using details from the book to support your answer."],
  h: ["이 책은 해리엇 터브먼이 탈출한 뒤 한 일들을 여러 가지 보여줘요 — 다른 노예를 구출한 일, 갈 곳 없는 나이 든 흑인들을 위한 집을 지은 일, 여성들이 함께 뭉쳐 권리를 위해 싸우도록 격려한 일. 그중 가장 인상 깊은 것을 골라 왜 그런지 문단으로 써 보세요.",
      "해리엇 터브먼은 아주 어릴 때부터 자유를 꿈꾸었어요. 여러분이 오랫동안 꿈꿔온 것은 무엇이고, 그것을 이루기 위해 무엇을 했거나 하려고 하는지 문단으로 써 보세요.",
      "해리엇 터브먼은 자신이 자유를 얻은 뒤에도 계속 다른 사람들을 도왔어요. 왜 그렇게 했다고 생각하는지, 책 속 내용을 근거로 들어 여러분의 생각을 문단으로 써 보세요."] };
ACT["S4502"] = { s: "John Jay served in all three branches of the government. Once the Constitution was written, he was a staunch supporter of the document, joining some other men in anonymously writing \"The Federalist Papers,\" which explained to the public why the Constitution should be ratified. Soon after, he was made chief justice of the Supreme Court, and he was given the position of declaring laws unconstitutional for the very first time.",
  q: ["John Jay served in all three branches of government, helped write 'The Federalist Papers,' and became the first chief justice to declare a law unconstitutional. Choose the one accomplishment you think mattered most and write a paragraph explaining your choice.",
      "John Jay and others wrote 'The Federalist Papers' anonymously to explain why the Constitution should be approved. Write a paragraph about a time you had to explain or persuade someone that an idea was a good one.",
      "Write a paragraph giving your opinion on whether it was a good idea for John Jay and the other writers to publish 'The Federalist Papers' without putting their names on it, and explain your reasoning."],
  h: ["존 제이는 정부의 세 부문 모두에서 일했고, '연방주의자 논집'을 쓰는 데 힘을 보탰으며, 법을 위헌이라고 선언한 최초의 대법원장이 되었어요. 그중 가장 중요했다고 생각하는 업적을 골라 이유를 문단으로 써 보세요.",
      "존 제이와 동료들은 헌법이 왜 비준되어야 하는지 설명하려고 이름을 밝히지 않은 채 '연방주의자 논집'을 썼어요. 여러분이 어떤 생각이 좋은 것이라고 누군가를 설득하거나 설명해야 했던 경험을 문단으로 써 보세요.",
      "존 제이와 다른 저자들이 '연방주의자 논집'을 이름 없이 발표한 것이 좋은 선택이었다고 생각하는지 여러분의 의견과 그 이유를 문단으로 써 보세요."] };
ACT["S4503"] = { s: "Laura Ingalls Wilder grew up as a pioneer girl and endured the difficult times in the West. Wilder made important contributions to the West. Other pioneer women contributed as well, including Narcissa Whitman, the first female pioneer.",
  q: ["This book describes Laura Ingalls Wilder as a pioneer girl who endured difficult times in the West, and also mentions Narcissa Whitman, the first female pioneer. Choose one of these two women and write a paragraph about what you imagine her daily life was like.",
      "Laura Ingalls Wilder endured many difficult times as a pioneer. Write a paragraph about a difficult time you have gone through and how you got through it.",
      "Write a paragraph giving your opinion on what you think was the most important contribution pioneer women like Laura and Narcissa made to the West, and explain why you think so."],
  h: ["이 책은 로라 잉걸스 와일더를 서부의 힘든 시절을 견뎌낸 개척자 소녀로 소개하고, 최초의 여성 개척자인 나르시사 휘트먼도 언급해요. 두 사람 중 한 명을 골라 그의 하루하루가 어땠을지 상상해서 문단으로 써 보세요.",
      "로라 잉걸스 와일더는 개척자로서 여러 힘든 시절을 견뎌냈어요. 여러분이 겪었던 힘든 시기와 그것을 어떻게 이겨냈는지 문단으로 써 보세요.",
      "로라와 나르시사 같은 개척자 여성들이 서부에 남긴 가장 중요한 기여가 무엇이라고 생각하는지 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S4504"] = { s: "Lewis and Clark were commissioned by President Thomas Jefferson to find a water route from the Mississippi River to the Pacific Ocean. The men were also asked to explore the newly purchased Louisiana Territory. They never found a water route, but they successfully documented information about the new lands.",
  q: ["Lewis and Clark were sent to find a water route to the Pacific and to explore the Louisiana Territory. Choose one of these two goals and write a paragraph about what you imagine was the hardest part of trying to achieve it.",
      "Lewis and Clark never found the water route they were looking for, but they still succeeded at documenting the new lands. Write a paragraph about a time you tried something and did not get the exact result you wanted, but still learned or gained something.",
      "Write a paragraph giving your opinion on whether Lewis and Clark's expedition should still be considered a success even though they did not find the water route, and explain your reasoning."],
  h: ["루이스와 클라크는 태평양으로 가는 물길을 찾고 루이지애나 준주를 탐사하라는 임무를 받았어요. 이 두 목표 중 하나를 골라 그것을 이루려고 할 때 가장 힘들었을 부분을 상상해서 문단으로 써 보세요.",
      "루이스와 클라크는 찾던 물길을 끝내 발견하지 못했지만, 새로운 땅에 대한 기록은 성공적으로 남겼어요. 여러분이 무언가를 시도했지만 원하던 결과를 얻지 못했음에도 무언가를 배우거나 얻었던 경험을 문단으로 써 보세요.",
      "루이스와 클라크가 물길을 찾지 못했음에도 그들의 탐험을 성공이라고 볼 수 있을지 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S4505"] = { s: "Ignite your students' passion for history through the use of intriguing primary sources! The Primary Source Reader series features purposefully leveled text to increase comprehension for different learner types. Students will learn about the fascinating life and times of Phillis Wheatley and her important contributions to history. This informational text includes captions, a glossary, an index, and other text features that will increase students' reading comprehension. It aligns with state stand",
  q: ["This book describes Phillis Wheatley's life and her important contributions to history. Choose one part of her story you would most like to learn more about, and write a paragraph explaining why.",
      "The book says it aims to increase students' reading comprehension through captions, a glossary, and an index. Write a paragraph about which of these text features helps you understand a nonfiction book best, and why.",
      "Write a paragraph giving your opinion on why you think Phillis Wheatley's story is still taught in schools today."],
  h: ["이 책은 필리스 휘틀리의 삶과 그녀가 역사에 남긴 중요한 기여를 다뤄요. 그녀의 이야기 중 가장 더 알고 싶은 부분을 골라 왜 그런지 문단으로 써 보세요.",
      "이 책은 캡션, 용어 설명, 색인 같은 요소로 학생들의 읽기 이해를 돕는다고 말해요. 이런 요소들 중 여러분이 정보 책을 이해하는 데 가장 도움이 되는 것은 무엇이고 왜 그런지 문단으로 써 보세요.",
      "필리스 휘틀리의 이야기가 오늘날까지도 학교에서 다루어지는 이유가 무엇이라고 생각하는지 여러분의 의견을 문단으로 써 보세요."] };
ACT["S4506"] = { s: "Pioneers experienced hardships during their journey through the West, which led them on the Oregon Trail and the Santa Fe Trail. The moving and travels of these pioneers affected not only their lives, but also the American Indians, America's animals, and the country.",
  q: ["This book says the pioneers' travels affected not only their own lives, but also American Indians, America's animals, and the country. Choose one of these three groups and write a paragraph about how you imagine the Oregon Trail or Santa Fe Trail affected them.",
      "Pioneers on these trails experienced many hardships during their journey. Write a paragraph about a long or difficult journey you have taken, and what made it hard.",
      "Write a paragraph giving your opinion on whether you think the hardships pioneers faced on these trails were worth what they gained, and explain your reasoning."],
  h: ["이 책은 개척자들의 이동이 그들 자신뿐 아니라 아메리카 원주민, 미국의 동물들, 그리고 나라 전체에도 영향을 미쳤다고 말해요. 이 세 대상 중 하나를 골라 오리건 트레일이나 산타페 트레일이 그들에게 어떤 영향을 주었을지 상상해서 문단으로 써 보세요.",
      "이 트레일을 지나던 개척자들은 여정 동안 여러 어려움을 겪었어요. 여러분이 겪었던 길고 힘든 여정과 무엇이 힘들었는지 문단으로 써 보세요.",
      "개척자들이 이 트레일에서 겪은 고난이 그들이 얻은 것과 견줄 만했다고 생각하는지 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S4507"] = { s: "Robert E. Lee was considered by many to be an amazing man of character, determination, and talent. Confederate President Jefferson Davis hired him as his assistant for the war. Soon he was commanding the Army of Northern Virginia, and he commanded until his men could fight no more. In the end, he resigned with dignity and asked his men to do the same.",
  q: ["The book describes Robert E. Lee as a man of character, determination, and talent who resigned with dignity and asked his men to do the same. Choose one of these qualities and write a paragraph about a moment in the book where you think it showed most clearly.",
      "Robert E. Lee commanded his army until his men could fight no more, then resigned with dignity. Write a paragraph about a time you had to accept that something was over and needed to let go with dignity.",
      "Write a paragraph giving your opinion on whether resigning with dignity, as Lee did, is a harder or easier choice than continuing to fight, and explain your reasoning."],
  h: ["이 책은 로버트 E. 리를 인격과 결단력, 재능을 갖춘 사람으로 그리며, 그가 품위 있게 사임하고 부하들에게도 그렇게 하라고 했다고 말해요. 이 특징들 중 하나를 골라 책 속에서 그것이 가장 잘 드러난 순간을 문단으로 써 보세요.",
      "로버트 E. 리는 부하들이 더 이상 싸울 수 없을 때까지 군을 지휘하다가 품위 있게 사임했어요. 여러분이 무언가가 끝났음을 받아들이고 품위 있게 물러나야 했던 경험을 문단으로 써 보세요.",
      "리처럼 품위 있게 물러나는 것이 계속 싸우는 것보다 더 어려운 선택이라고 생각하는지 아니면 더 쉬운 선택이라고 생각하는지, 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S4508"] = { s: "The Declaration of Independence was a document that declared the right to be a country that would make its own decisions, starting with the decision to separate from the British control. From taxation to the Boston Tea Party to Thomas Paine's Common Sense, tension was building against Great Britain. Events finally led to a resolution in Congress that the colonies would form an independent government-a resolution that led to the writing of the Declaration of Independence.",
  q: ["This book mentions several events that built tension with Great Britain: taxation, the Boston Tea Party, and Thomas Paine's Common Sense. Choose one of these events and write a paragraph about why you think it made colonists angrier at British control.",
      "The Declaration of Independence declared the colonies' right to make their own decisions. Write a paragraph about a decision you wish you had more freedom to make for yourself, and why.",
      "Write a paragraph giving your opinion on which single event described in this book — taxation, the Boston Tea Party, or Common Sense — most pushed the colonies toward writing the Declaration of Independence, and explain your reasoning."],
  h: ["이 책은 영국과의 긴장을 키운 여러 사건을 언급해요 — 과세, 보스턴 차 사건, 토머스 페인의 '상식'. 이 사건들 중 하나를 골라 그것이 왜 식민지인들을 영국의 지배에 더 화나게 만들었다고 생각하는지 문단으로 써 보세요.",
      "독립 선언서는 식민지가 스스로 결정을 내릴 권리를 선언했어요. 여러분이 스스로 결정할 자유를 더 갖고 싶은 일은 무엇이고 왜 그런지 문단으로 써 보세요.",
      "이 책에 나온 사건들 — 과세, 보스턴 차 사건, '상식' — 중 어느 것이 식민지를 독립 선언서 작성으로 가장 크게 밀어붙였다고 생각하는지 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S4509"] = { s: "When President James Madison declared war on Great Britain for a second time, the War of 1812 began. Problems started when America sent ships out to sea to trade with other countries. The war eventually ended, and the Treaty of Ghent was signed. America earned the respect of the British as a free, independent nation.",
  q: ["This book says problems started when America sent ships to trade with other countries. Write a paragraph about what you imagine happened to those ships that led to war.",
      "After the war, the Treaty of Ghent was signed and America earned Britain's respect. Write a paragraph about a time a disagreement you had with someone ended with the two of you respecting each other more.",
      "Write a paragraph giving your opinion on whether going to war was the right way for President Madison to solve America's trade problems with Great Britain, and explain your reasoning."],
  h: ["이 책은 미국이 다른 나라와 무역하려고 배를 보내면서 문제가 시작되었다고 말해요. 그 배들에게 무슨 일이 일어나서 전쟁으로 이어졌을지 상상해서 문단으로 써 보세요.",
      "전쟁이 끝난 뒤 겐트 조약이 체결되고 미국은 영국의 존중을 얻었어요. 여러분이 누군가와 다투었지만 그 뒤에 서로를 더 존중하게 되었던 경험을 문단으로 써 보세요.",
      "매디슨 대통령이 영국과의 무역 문제를 전쟁으로 해결한 것이 옳은 방법이었다고 생각하는지 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S4510"] = { s: "Ulysses S. Grant was a warrior, hero, and a compassionate soldier. Grant led the Union army to victory during the Civil War. The North thought of him as a hero for ending the Civil War and elected him president of the United States.",
  q: ["This book calls Ulysses S. Grant a warrior, a hero, and a compassionate soldier. Choose one of these three words and write a paragraph about a moment in the book where you think it fit him best.",
      "The North saw Grant as a hero for ending the Civil War, so they elected him president. Write a paragraph about someone in your own life who became a leader because people trusted what they had already done.",
      "Write a paragraph giving your opinion on whether being a great soldier, like Grant, also means someone will be a great president, and explain your reasoning."],
  h: ["이 책은 율리시스 S. 그랜트를 전사이자 영웅이며 인정 많은 군인이라고 불러요. 이 세 단어 중 하나를 골라 책 속에서 그 모습이 가장 잘 드러났을 순간을 문단으로 써 보세요.",
      "북부 사람들은 남북전쟁을 끝낸 그랜트를 영웅으로 여겨 그를 대통령으로 뽑았어요. 여러분 주변에서 이미 해낸 일 덕분에 사람들의 신뢰를 얻어 리더가 된 사람에 대해 문단으로 써 보세요.",
      "그랜트처럼 훌륭한 군인이었다는 것이 곧 훌륭한 대통령이 될 것이라는 뜻인지 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S4511"] = { s: "You were living it up with Louis XVI and Marie Antoinette, and then the tides turned. Now the king and queen have lost their heads and you're stuck in a filthy jail without a morsel of pate to eat. Quelle horreur! Could anything be worse?",
  q: ["This book puts you in the shoes of an aristocrat during the French Revolution, living well with the king and queen and then losing everything. Write a paragraph imagining what your character's life was like before 'the tides turned.'",
      "The character in this book goes from living it up to being stuck in a filthy jail. Write a paragraph about a time your own situation changed very suddenly, for better or worse.",
      "Write a paragraph giving your opinion on whether you think it was fair that ordinary aristocrats, not just the king and queen, lost everything during the French Revolution, and explain your reasoning."],
  h: ["이 책은 프랑스 혁명 당시 왕과 왕비와 함께 잘 지내다가 모든 것을 잃게 되는 귀족의 입장에 여러분을 세워요. '상황이 뒤바뀌기' 전, 그 인물의 삶이 어땠을지 상상해서 문단으로 써 보세요.",
      "이 책 속 인물은 화려하게 살다가 더러운 감옥에 갇히는 신세가 돼요. 여러분의 상황이 아주 갑작스럽게 바뀌었던 경험을 좋은 쪽이든 나쁜 쪽이든 문단으로 써 보세요.",
      "프랑스 혁명 때 왕과 왕비뿐 아니라 평범한 귀족들까지 모든 것을 잃은 것이 공정했다고 생각하는지 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S4512"] = { s: "Humorous \"Handy Hints\" that relate directly to the text are provided on each spread. - High interest topic for children of all ages. - Includes Table of Contents, glossary, and index. - Draws in even the most reluctant reader with a lightheaded tone and hilarious illustrations. - The cultures and traditions of ancient civilizations spring to life in the pages of this series. - Perfect for struggling readers. Grades K-4 Social Studies Standards II. Time, Continuity, and Change - Accounts of past",
  q: ["This book promises humorous 'Handy Hints' on every page about being an Assyrian soldier. Choose one hint from the book that you found funniest or most surprising, and write a paragraph explaining what it taught you about that soldier's life.",
      "The book says ancient civilizations 'spring to life' in its pages. Write a paragraph about which part of ancient Assyrian life feels most different from your own life today, and why.",
      "Would you have wanted to be an Assyrian soldier after reading this book? Write a paragraph giving your opinion and at least one reason from the book to support it."],
  h: ["이 책은 앗시리아 병사가 되는 것에 대해 페이지마다 재미있는 '핸디 힌트'를 알려줘요. 책에서 가장 웃기거나 놀라웠던 힌트 하나를 골라, 그것이 그 병사의 삶에 대해 무엇을 알려주었는지 문단으로 써 보세요.",
      "이 책은 고대 문명이 책장 속에서 생생하게 살아난다고 말해요. 고대 앗시리아인의 생활 중 오늘날 여러분의 삶과 가장 다르다고 느껴지는 부분은 무엇이고 왜 그런지 문단으로 써 보세요.",
      "이 책을 읽고 나서 여러분은 앗시리아 병사가 되고 싶다고 생각했나요? 여러분의 의견과 책에서 찾은 근거를 최소 한 가지 들어 문단으로 써 보세요."] };
ACT["S4513"] = { s: "You are a 16-year-old boy in the 18th Century. Your well-to-do parents have convinced your cousin, James Cook, to take you on his ship as a cabin boy. Cooks mission is to plot the course of the planet Venus in the skies of Tahiti. He's also looking for a new continent. It sounds pretty exciting, doesn't it? You will spend three years living on this ship. You will eat biscuits filled with worms, watch 41 of your shipmates die of disease and be attacked by islanders. By the end of this voyage you",
  q: ["In this book, you are a 16-year-old cabin boy on Captain Cook's ship, watching shipmates die of disease and facing attacks from islanders. Choose one of these dangers and write a paragraph about how you imagine it felt to face it.",
      "The character spends three years on this voyage, eating biscuits filled with worms. Write a paragraph about a time you had to put up with something unpleasant for a long time in order to do something exciting.",
      "Write a paragraph giving your opinion on whether you would have agreed to go on this three-year voyage if you were the cabin boy, and explain your reasoning."],
  h: ["이 책에서 여러분은 쿡 선장의 배에 탄 16살 사환이 되어, 동료 선원들이 병으로 죽는 것을 보고 섬 주민들의 공격도 마주해요. 이 위험 중 하나를 골라 그것을 마주했을 때 어떤 기분이었을지 상상해서 문단으로 써 보세요.",
      "이 인물은 벌레가 들끓는 비스킷을 먹으며 3년 동안 이 항해를 견뎌요. 여러분이 신나는 일을 하기 위해 오랫동안 불편한 것을 참아야 했던 경험을 문단으로 써 보세요.",
      "여러분이 이 사환이었다면 3년짜리 이 항해를 떠나겠다고 했을지 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S4514"] = { s: "This revised edition combines humorous cartoons and facts to depict what it was like to sail with Christopher Columbus.",
  q: ["This book uses humorous cartoons and facts to show what it was like to sail with Christopher Columbus. Write a paragraph about one part of that voyage you would most like to know more about.",
      "Write a paragraph about a long trip you have taken, and compare one part of it to what you imagine Columbus's crew experienced at sea.",
      "Write a paragraph giving your opinion on whether you think sailing with Columbus would have been more exciting or more frightening, and explain your reasoning."],
  h: ["이 책은 재미있는 만화와 사실들로 크리스토퍼 콜럼버스와 함께 항해하는 것이 어땠는지 보여줘요. 그 항해에서 가장 더 알고 싶은 부분을 문단으로 써 보세요.",
      "여러분이 다녀온 긴 여행에 대해 쓰고, 그중 한 부분을 콜럼버스의 선원들이 바다에서 겪었을 일과 비교해서 문단으로 써 보세요.",
      "콜럼버스와 함께 항해하는 것이 더 신났을지 아니면 더 무서웠을지 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S4515"] = { s: "This book presents a children's story on how to hunt a mammoth and some of the ways ancient people used the animal in addition to food.",
  q: ["This book tells how ancient people hunted mammoths and used them for more than just food. Choose one use of the mammoth described or hinted at in the title and write a paragraph imagining how ancient people might have used it.",
      "Hunting a mammoth would have taken great teamwork among ancient people. Write a paragraph about a time you had to work together with others to do something difficult.",
      "Write a paragraph giving your opinion on whether you think hunting mammoths was the most dangerous part of ancient people's lives, and explain your reasoning."],
  h: ["이 책은 고대 사람들이 매머드를 어떻게 사냥했고 먹이 말고도 어떻게 썼는지 알려줘요. 제목에서 짐작되는 매머드의 쓰임 하나를 골라 고대 사람들이 그것을 어떻게 썼을지 상상해서 문단으로 써 보세요.",
      "매머드를 사냥하려면 고대 사람들 사이에 뛰어난 협동이 필요했을 거예요. 여러분이 어려운 일을 하기 위해 다른 사람들과 함께 힘을 모았던 경험을 문단으로 써 보세요.",
      "매머드 사냥이 고대 사람들의 삶에서 가장 위험한 일이었다고 생각하는지 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S4516"] = { s: "This book takes a humorous look at what life might be like for a Mayan soothsayer.",
  q: ["This book takes a humorous look at the life of a Mayan soothsayer. Write a paragraph imagining one task you think a soothsayer might have had to do.",
      "Write a paragraph about a time someone asked you to predict or guess what would happen next, and how that felt.",
      "Write a paragraph giving your opinion on whether you think being a soothsayer would have been an exciting job or a frightening one, and explain your reasoning."],
  h: ["이 책은 마야 예언자의 삶을 재미있게 들여다봐요. 예언자가 해야 했을 것 같은 일 한 가지를 상상해서 문단으로 써 보세요.",
      "여러분이 앞으로 무슨 일이 일어날지 예측하거나 짐작해 보라는 부탁을 받았던 경험을 문단으로 써 보세요.",
      "예언자가 되는 것이 신나는 일이었을지 아니면 무서운 일이었을지 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S4517"] = { s: "This revised edition combines humorous illustrations and facts to provide a portrait of what life was like aboard an English pirate ship plying the Caribbean Sea during the sixteenth century. The text and illustrations contain references to violence.",
  q: ["This book shows what life was like aboard an English pirate ship in the Caribbean in the sixteenth century. Write a paragraph imagining what you think a prisoner's typical day aboard the ship was like.",
      "Write a paragraph about a time you felt like you had no control over what was happening to you, and how you got through it.",
      "Write a paragraph giving your opinion on whether you think most people captured by pirates managed to escape, and explain your reasoning based on what the book describes."],
  h: ["이 책은 16세기 카리브해를 누비던 영국 해적선 위의 삶이 어땠는지 보여줘요. 포로가 배 위에서 보냈을 하루가 어땠을지 상상해서 문단으로 써 보세요.",
      "여러분이 자신에게 일어나는 일을 스스로 어찌할 수 없다고 느꼈던 경험과 그것을 어떻게 이겨냈는지 문단으로 써 보세요.",
      "해적에게 잡힌 사람들 대부분이 탈출에 성공했을 거라고 생각하는지, 책의 내용을 근거로 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S4518"] = { s: "This book is a humorous and educational exploration of the cultural trials and tribulations experienced in the ancient city of Pompeii.",
  q: ["This book explores the cultural trials and tribulations of being a slave in ancient Pompeii. Write a paragraph imagining one hardship a slave in Pompeii might have faced.",
      "Write a paragraph about a time you had to do something you did not want to do because someone else had power over you, and how it felt.",
      "Write a paragraph giving your opinion on why you think this book chose to teach about ancient Pompeii through the eyes of a slave rather than a wealthy citizen."],
  h: ["이 책은 고대 폼페이에서 노예로 사는 것의 문화적 어려움과 시련을 살펴봐요. 폼페이의 노예가 겪었을 어려움 한 가지를 상상해서 문단으로 써 보세요.",
      "여러분이 다른 사람에게 힘이 있어서 하기 싫은 일을 해야 했던 경험과 그때 기분이 어땠는지 문단으로 써 보세요.",
      "이 책이 부유한 시민이 아니라 노예의 눈으로 고대 폼페이를 가르치기로 한 이유가 무엇이라고 생각하는지 여러분의 의견을 문단으로 써 보세요."] };
ACT["S4519"] = { s: "Fits in well with social studies and U.S. history curricula.- Draws in even the most reluctant reader with a lighthearted tone and hilarious illustrations.- Includes glossary and index.National Social Studies Education Standards: Grades K-4II. Time, Continuity, and Change- Accounts of past events, people, places, and situations contribute to our understanding of the pastVI. Power, Authority, and Governance- Identify factors that contribute to cooperation or cause disputesI. Culture- People, soci",
  q: ["This book fits with social studies standards about how people, places, and situations from the past help us understand history. Write a paragraph about one thing you would want to know about the daily life of a Tudor colonist.",
      "Write a paragraph about a time you had to adjust to a completely new place, and compare it to what you imagine a Tudor colonist felt arriving in a new land.",
      "Write a paragraph giving your opinion on whether you think you would have chosen to become a Tudor colonist if you had lived at that time, and explain your reasoning."],
  h: ["이 책은 과거의 사람과 장소, 상황이 역사를 이해하는 데 어떻게 도움이 되는지를 다루는 사회 교과 기준에 맞아 있어요. 튜더 시대 식민지 개척자의 일상에 대해 가장 알고 싶은 것 한 가지를 문단으로 써 보세요.",
      "여러분이 완전히 새로운 장소에 적응해야 했던 경험을 쓰고, 그것을 튜더 시대 개척자가 새 땅에 도착했을 때 느꼈을 감정과 비교해서 문단으로 써 보세요.",
      "여러분이 그 시대에 살았다면 튜더 시대 개척자가 되기로 선택했을지 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S4520"] = { s: "This book takes a humorous look at what life was like for Victorian mill workers.",
  q: ["This book takes a humorous look at what life was like for Victorian mill workers. Write a paragraph imagining one task a mill worker might have had to do all day.",
      "Write a paragraph about a chore or job you find tiring or boring, and compare it to what you imagine mill work was like.",
      "Write a paragraph giving your opinion on why children today do not have to work in mills the way Victorian children did, and explain your reasoning."],
  h: ["이 책은 빅토리아 시대 방직공장 노동자의 삶을 재미있게 들여다봐요. 공장 노동자가 하루 종일 해야 했을 일 한 가지를 상상해서 문단으로 써 보세요.",
      "여러분이 힘들거나 지루하다고 느끼는 집안일이나 일을 쓰고, 그것을 방직공장 노동이 어땠을지와 비교해서 문단으로 써 보세요.",
      "오늘날 어린이들은 빅토리아 시대 아이들처럼 공장에서 일하지 않아도 되는 이유가 무엇이라고 생각하는지 여러분의 의견을 문단으로 써 보세요."] };
ACT["S4521"] = { s: "Colorful illustrations help describe what life would be like as a servant living in Victorian England.",
  q: ["This book uses colorful illustrations to describe what life would be like as a servant in Victorian England. Write a paragraph imagining one duty you think a Victorian servant had to perform.",
      "Write a paragraph about a time you had to take care of a house or help with chores, and compare it to a Victorian servant's daily work.",
      "Write a paragraph giving your opinion on whether you think being a Victorian servant would have been harder for an adult or for a child, and explain your reasoning."],
  h: ["이 책은 화려한 삽화로 빅토리아 시대 영국에서 하인으로 사는 삶이 어땠는지 보여줘요. 빅토리아 시대 하인이 했을 것 같은 일 한 가지를 상상해서 문단으로 써 보세요.",
      "여러분이 집안일을 돌보거나 도와야 했던 경험을 쓰고, 그것을 빅토리아 시대 하인의 하루 일과와 비교해서 문단으로 써 보세요.",
      "빅토리아 시대 하인으로 사는 것이 어른에게 더 힘들었을지 아이에게 더 힘들었을지 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S4522"] = { s: "This book looks through the eyes of the fictional marshal of an imaginary town called Dustville to show what life was like on the Great Plains just after the Civil War.",
  q: ["This book looks through the eyes of the fictional marshal of Dustville to show life on the Great Plains just after the Civil War. Write a paragraph imagining one problem the marshal might have had to solve in town.",
      "Write a paragraph about a time you had to help keep order or solve a problem for a group of people, and compare it to the marshal's job.",
      "Write a paragraph giving your opinion on whether you think life in a Wild West town would have felt exciting or dangerous, and explain your reasoning."],
  h: ["이 책은 가상의 마을 더스트빌의 보안관 눈으로 남북전쟁 직후 대평원의 삶을 보여줘요. 보안관이 마을에서 해결해야 했을 문제 한 가지를 상상해서 문단으로 써 보세요.",
      "여러분이 여러 사람을 위해 질서를 지키거나 문제를 해결해야 했던 경험을 쓰고, 그것을 보안관의 일과 비교해서 문단으로 써 보세요.",
      "서부 개척 시대 마을에서의 삶이 신나게 느껴졌을지 위험하게 느껴졌을지 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S4523"] = { s: "Nicholas's mum is going to have a baby and it's making her do some really strange things. First it's the sausages, then it's nappy-changing races. Nicholas's family is turned upside down. But there's an even bigger shock to come.",
  q: ["In this book, Nicholas's mum does strange things while pregnant, like sausage cravings and nappy-changing races. Choose the strange thing you find funniest and write a paragraph about why you think it happens.",
      "Nicholas's family is turned upside down by his mum's pregnancy. Write a paragraph about a time your own family's daily life changed a lot because of a new baby or a big event.",
      "The book says there's an even bigger shock to come. Write a paragraph predicting what you think that shock might be, and explain why you think so based on the story so far."],
  h: ["이 책에서 니콜라스의 엄마는 임신 중에 소시지에 집착하거나 기저귀 갈기 경주를 하는 등 이상한 행동을 해요. 그중 가장 재미있다고 생각하는 행동을 골라 왜 그런 일이 일어난다고 생각하는지 문단으로 써 보세요.",
      "니콜라스의 가족은 엄마의 임신으로 온통 뒤죽박죽이 돼요. 새로운 아기나 큰 사건 때문에 여러분 가족의 일상이 크게 바뀌었던 경험을 문단으로 써 보세요.",
      "책은 더 큰 충격이 남아 있다고 말해요. 그 충격이 무엇일지 예측하고, 지금까지의 이야기를 근거로 그 이유를 문단으로 써 보세요."] };
ACT["S4524"] = { s: "A chimpanzee helps Dinah the Mynah rescue her family from the clutches of Divine, a beautiful but evil woman with a sinister plan and little care for the animals or people who get in her way.",
  q: ["In this book, a chimpanzee helps Dinah the Mynah rescue her family from Divine, an evil woman. Write a paragraph imagining how you think the chimpanzee and Dinah worked together to plan the rescue.",
      "Write a paragraph about a time you helped a friend or family member get out of a difficult or scary situation.",
      "Write a paragraph giving your opinion on why you think Divine has little care for the animals or people who get in her way, and what that tells you about her character."],
  h: ["이 책에서 침팬지는 디나 마이나가 디바인이라는 악당 여성으로부터 가족을 구하도록 도와줘요. 침팬지와 디나가 어떻게 힘을 합쳐 구출 계획을 세웠을지 상상해서 문단으로 써 보세요.",
      "여러분이 친구나 가족이 힘들거나 무서운 상황에서 벗어나도록 도왔던 경험을 문단으로 써 보세요.",
      "디바인이 자신을 방해하는 동물이나 사람들을 신경 쓰지 않는 이유가 무엇이라고 생각하는지, 그것이 그의 성격에 대해 무엇을 말해주는지 여러분의 의견을 문단으로 써 보세요."] };
ACT["S4525"] = { s: "Benjamin Franklin was a man of many talents. His mind was constantly working to make things better for the colonists both before and after independence. Franklin was also a great writer, and he contributed to both the Declaration of Independence and the Constitution.",
  q: ["This book says Benjamin Franklin's mind was constantly working to make things better for colonists. Choose one of his known roles — writer, inventor, or contributor to the Declaration and Constitution — and write a paragraph imagining what a typical day of his work in that role looked like.",
      "Write a paragraph about someone in your life whose mind is always working to make things better for others, like Franklin's was, and describe what they do.",
      "Write a paragraph giving your opinion on which of Franklin's many talents — writing, inventing, or contributing to the nation's founding documents — you think mattered most, and explain your reasoning."],
  h: ["이 책은 벤저민 프랭클린의 머리가 식민지인들을 위해 더 나은 것을 만들려고 끊임없이 움직였다고 말해요. 그의 역할 중 하나 — 작가, 발명가, 독립 선언서와 헌법에 기여한 사람 — 를 골라 그 일을 하는 그의 하루가 어땠을지 상상해서 문단으로 써 보세요.",
      "프랭클린처럼 다른 사람들을 위해 항상 더 나은 것을 궁리하는 사람이 여러분 주변에 있나요? 그 사람과 그가 하는 일을 문단으로 써 보세요.",
      "프랭클린의 여러 재능 — 글쓰기, 발명, 건국 문서에 대한 기여 — 중 가장 중요했다고 생각하는 것을 골라 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S4526"] = { s: "James Madison made great contributions to the United States. During his presidency, he declared war on Great Britain. Not all of his decisions met public approval, but he was well respected throughout his lifetime and one of the most influential founding fathers.",
  q: ["This book says not all of James Madison's decisions, including declaring war on Great Britain, met public approval. Write a paragraph imagining the arguments people might have made against his decision to go to war.",
      "Write a paragraph about a decision you made that not everyone around you agreed with, and how you felt about that.",
      "Write a paragraph giving your opinion on whether a leader like Madison should follow public opinion even when they believe a different choice is right, and explain your reasoning."],
  h: ["이 책은 제임스 매디슨의 결정들 — 영국에 전쟁을 선포한 일을 포함해서 — 이 모두 대중의 찬성을 얻지는 못했다고 말해요. 사람들이 그의 전쟁 결정에 반대하며 내세웠을 주장을 상상해서 문단으로 써 보세요.",
      "여러분이 내린 결정 중 주변 사람 모두가 찬성하지는 않았던 결정과 그때 여러분의 기분을 문단으로 써 보세요.",
      "매디슨 같은 지도자가 다른 선택이 옳다고 믿더라도 여론을 따라야 하는지 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S4527"] = { s: "Pocahontas was the daughter of the great Chief Powhatan. Pocahontas was instrumental in helping Jamestown settlers survive a difficult winter and literally keeping peace between two diverse cultures.",
  q: ["This book says Pocahontas helped Jamestown settlers survive a difficult winter and kept peace between two diverse cultures. Choose one of these two roles and write a paragraph imagining what she might have done, specifically.",
      "Write a paragraph about a time you helped bring two people or groups who disagreed closer together.",
      "Write a paragraph giving your opinion on how difficult you think it was for Pocahontas to keep peace between two very different cultures, and explain your reasoning."],
  h: ["이 책은 포카혼타스가 제임스타운 정착민들이 힘든 겨울을 견디도록 도왔고 서로 다른 두 문화 사이에서 평화를 지켰다고 말해요. 이 두 역할 중 하나를 골라 그녀가 구체적으로 무엇을 했을지 상상해서 문단으로 써 보세요.",
      "여러분이 서로 다투던 두 사람이나 두 집단이 가까워지도록 도왔던 경험을 문단으로 써 보세요.",
      "포카혼타스가 아주 다른 두 문화 사이에서 평화를 지키는 것이 얼마나 어려웠을지 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S4528"] = { s: "Sitting Bull was a powerful Hunkpapa Lakota Indian Chief who-along with the Lakota Indians and other nearby tribes-was involved in brutal battles with the United States over land issues. All tribes that were fighting to avoid the reservation eventually surrendered, and the Lakota people were no exception.",
  q: ["This book says Sitting Bull and the Lakota, along with other tribes, fought brutal battles with the United States over land, and eventually surrendered. Write a paragraph imagining what you think Sitting Bull was thinking in the moment he decided to surrender.",
      "Write a paragraph about a time you or your family had to give up something you had fought hard to keep.",
      "Write a paragraph giving your opinion on whether the tribes fighting to avoid the reservation had any real choice other than surrender, and explain your reasoning."],
  h: ["이 책은 시팅 불과 라코타족, 그리고 다른 부족들이 땅을 두고 미국과 치열한 전투를 벌이다 결국 항복했다고 말해요. 시팅 불이 항복을 결심한 순간 무슨 생각을 했을지 상상해서 문단으로 써 보세요.",
      "여러분이나 가족이 지키려고 애썼던 것을 결국 포기해야 했던 경험을 문단으로 써 보세요.",
      "보호구역행을 피하려고 싸우던 부족들에게 항복 말고 다른 진짜 선택지가 있었다고 생각하는지 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S4529"] = { s: "Thomas Jefferson was a gifted writer whose words helped form the country. Although at one time he wanted to be a great speaker, he found comfort and ease in writing. Not only was he a great writer, but also an architect, inventor, surveyor, scientist, and a brilliant politician. He wanted to make life better for all people.",
  q: ["This book says Thomas Jefferson was a writer, architect, inventor, surveyor, scientist, and politician. Choose the role you find most interesting and write a paragraph imagining what a day doing that work looked like for him.",
      "Jefferson once wanted to be a great speaker but found comfort and ease in writing instead. Write a paragraph about something you thought you wanted to be good at, but found you were better at something else.",
      "Write a paragraph giving your opinion on which of Jefferson's many talents you think helped him make life better for people the most, and explain your reasoning."],
  h: ["이 책은 토머스 제퍼슨을 작가이자 건축가, 발명가, 측량사, 과학자, 정치인이라고 말해요. 이 역할 중 가장 흥미로운 것을 골라 그 일을 하는 그의 하루가 어땠을지 상상해서 문단으로 써 보세요.",
      "제퍼슨은 한때 뛰어난 연설가가 되고 싶었지만 오히려 글쓰기에서 편안함을 찾았어요. 여러분이 잘하고 싶었던 것이 있었지만 사실은 다른 것을 더 잘한다는 걸 알게 된 경험을 문단으로 써 보세요.",
      "제퍼슨의 여러 재능 중 사람들의 삶을 더 낫게 만드는 데 가장 크게 도움이 되었다고 생각하는 것을 골라 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S4530"] = { s: "Colorful illustrations help describe what life would be like sailing in the Spanish Armada during the sixteenth century.",
  q: ["This book uses colorful illustrations to describe life sailing in the Spanish Armada during the sixteenth century. Write a paragraph imagining one danger a sailor in the Armada might have faced at sea.",
      "Write a paragraph about a time you were part of a large team working toward one goal, and compare it to being one sailor among many in a huge fleet.",
      "Write a paragraph giving your opinion on whether you think sailing in such a large fleet would have felt safer or more dangerous than sailing alone, and explain your reasoning."],
  h: ["이 책은 화려한 삽화로 16세기 스페인 무적함대에서 항해하는 삶을 보여줘요. 무적함대의 선원이 바다에서 마주했을 위험 한 가지를 상상해서 문단으로 써 보세요.",
      "여러분이 하나의 목표를 위해 큰 팀의 일원으로 함께했던 경험을 쓰고, 그것을 거대한 함대 속 한 명의 선원으로 있는 것과 비교해서 문단으로 써 보세요.",
      "그렇게 큰 함대에서 항해하는 것이 혼자 항해하는 것보다 더 안전하게 느껴졌을지 아니면 더 위험하게 느껴졌을지 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S4531"] = { s: "When twelve-year-old Fern and her mother abruptly leave their isolated, off-the-grid community, Fern wants nothing more than to return, but things get murky as she slowly adjusts to her new life and discovers unsettling truths about her old one.",
  q: ["In this book, Fern's mother suddenly takes her away from their isolated community, and Fern slowly discovers unsettling truths about her old life. Write a paragraph about a moment in the book where you think Fern's feelings about her old community changed.",
      "Fern wants nothing more than to return to her old life at first. Write a paragraph about a time you missed a place or a way of life you had left behind.",
      "Write a paragraph giving your opinion on whether you think it is better to know unsettling truths about your past, even if they are painful, or to stay comfortable not knowing, and explain your reasoning."],
  h: ["이 책에서 펀의 엄마는 갑자기 그녀를 고립된 공동체에서 데리고 나오고, 펀은 서서히 예전 삶에 대한 불편한 진실들을 알게 돼요. 책 속에서 펀이 예전 공동체에 대한 마음이 바뀌었다고 생각하는 순간을 문단으로 써 보세요.",
      "펀은 처음에는 예전 삶으로 돌아가는 것 말고는 아무것도 바라지 않아요. 여러분이 떠나온 장소나 예전 생활 방식을 그리워했던 경험을 문단으로 써 보세요.",
      "과거에 대한 불편한 진실을 아는 것이 고통스럽더라도 아는 편이 나은지, 아니면 모른 채 편안하게 지내는 편이 나은지 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S4532"] = { s: "For twelve-year-old Michael Rosario, life at Fox Run Apartments in Red Knot, Delaware, is as ordinary as ever. Then Michael meets a mysterious boy who changes his life forever. Text has mild profanity, reference to mild violence, criminal activity.",
  q: ["Michael Rosario's ordinary life changes forever when he meets a mysterious boy. Write a paragraph about a moment in the book where you think Michael realized his life was no longer ordinary.",
      "Write a paragraph about a time meeting someone new changed how you saw your own everyday life.",
      "Write a paragraph giving your opinion on whether you think it is exciting or risky to let a mysterious stranger become part of your life, and explain your reasoning using a moment from the book."],
  h: ["마이클 로사리오의 평범한 삶은 한 신비로운 소년을 만나면서 영원히 달라져요. 책 속에서 마이클이 자신의 삶이 더 이상 평범하지 않다는 것을 깨달았다고 생각하는 순간을 문단으로 써 보세요.",
      "새로운 누군가를 만난 일이 여러분의 평범한 일상을 보는 눈을 바꿔 놓았던 경험을 문단으로 써 보세요.",
      "신비로운 낯선 사람을 자신의 삶에 들이는 것이 신나는 일이라고 생각하는지 위험한 일이라고 생각하는지, 책 속 한 순간을 근거로 들어 여러분의 의견을 문단으로 써 보세요."] };
ACT["S4533"] = { s: "Junko Tabei dreamed of climbing mountains, although men refused to climb with her and sponsors told her to stay home. However, Junko was unstoppable and refused to let anything get in her way.",
  q: ["Junko Tabei dreamed of climbing mountains even though men refused to climb with her and sponsors told her to stay home. Write a paragraph about a moment in the book where you think her determination showed the most.",
      "Write a paragraph about a time people doubted you could do something, and how you responded.",
      "Write a paragraph giving your opinion on why you think people told Junko Tabei to stay home, and whether you think their reasons were fair."],
  h: ["준코 다베이는 남자들이 함께 오르기를 거부하고 후원자들이 집에 있으라고 말했지만 산을 오르는 꿈을 꾸었어요. 책 속에서 그녀의 의지가 가장 잘 드러났다고 생각하는 순간을 문단으로 써 보세요.",
      "여러분이 할 수 있다는 것을 사람들이 의심했던 경험과 그때 여러분이 어떻게 반응했는지 문단으로 써 보세요.",
      "사람들이 준코 다베이에게 집에 있으라고 말한 이유가 무엇이었다고 생각하는지, 그 이유가 정당했다고 생각하는지 여러분의 의견을 문단으로 써 보세요."] };
ACT["S4534"] = { s: "This story is a celebration of Langston Hughes and African American authors he inspired, told through the lens of the party held at the New York Public Library's Schomburg Center for Research in Black Culture in 1991.",
  q: ["This book celebrates Langston Hughes and the African American authors he inspired, centered on a real party held at the Schomburg Center in 1991. Write a paragraph imagining what you think that party felt like.",
      "Write a paragraph about someone whose work or words have inspired you, the way Langston Hughes inspired other authors.",
      "Write a paragraph giving your opinion on why you think it is important to hold a celebration like this one for a writer, rather than just reading their books quietly."],
  h: ["이 책은 랭스턴 휴스와 그가 영감을 준 흑인 작가들을 기념하며, 1991년 숌버그 센터에서 열린 실제 파티를 중심으로 이야기해요. 그 파티가 어떤 느낌이었을지 상상해서 문단으로 써 보세요.",
      "랭스턴 휴스가 다른 작가들에게 영감을 주었듯, 여러분에게 영감을 준 누군가의 작품이나 말에 대해 문단으로 써 보세요.",
      "작가의 책을 조용히 읽는 것에 그치지 않고 이런 축하 행사를 여는 것이 왜 중요하다고 생각하는지 여러분의 의견을 문단으로 써 보세요."] };
ACT["S4535"] = { s: "In a mix of Eastern and Western mythologies, a mother tells her child about two forests inhabited by different, but equally enchanting dragons that coexist within the child's heart.",
  q: ["This book describes two forests of dragons from Eastern and Western mythology that live within a child's heart. Choose one of the two kinds of dragons and write a paragraph imagining what it looks like and how it behaves.",
      "Write a paragraph about two very different feelings or ideas that you feel exist together inside you, the way the two kinds of dragons coexist in the child's heart.",
      "Write a paragraph giving your opinion on why you think this book chose to combine Eastern and Western dragon mythology instead of using just one tradition."],
  h: ["이 책은 동양과 서양 신화에서 온 두 숲의 용들이 아이의 마음속에 함께 산다고 이야기해요. 두 종류의 용 중 하나를 골라 그 모습과 행동을 상상해서 문단으로 써 보세요.",
      "두 종류의 용이 아이의 마음속에서 함께 사는 것처럼, 여러분 안에도 서로 다른 두 감정이나 생각이 함께 있다고 느낀 적이 있나요? 그것을 문단으로 써 보세요.",
      "이 책이 한 가지 전통만 쓰지 않고 동양과 서양의 용 신화를 함께 담은 이유가 무엇이라고 생각하는지 여러분의 의견을 문단으로 써 보세요."] };
ACT["S4536"] = { s: "Quarantined with his family as a virus ravages the world, Clay retreats to the woods where he meets a special dog who leads him on surreal adventures. Book has animal cruelty and mild violence.",
  q: ["Clay retreats to the woods during a quarantine and meets a special dog who leads him on surreal adventures. Write a paragraph imagining one adventure the dog might have led Clay on.",
      "Write a paragraph about a time being outdoors or in nature helped you feel better during a difficult time, the way the woods do for Clay.",
      "Write a paragraph giving your opinion on why you think Clay retreats to the woods instead of staying inside with his family during the quarantine, and explain your reasoning."],
  h: ["클레이는 격리 기간 동안 숲으로 피신해 그를 초현실적인 모험으로 이끄는 특별한 개를 만나요. 그 개가 클레이를 이끌었을 법한 모험 한 가지를 상상해서 문단으로 써 보세요.",
      "클레이에게 숲이 그랬던 것처럼, 힘든 시기에 야외나 자연에 있는 것이 여러분의 기분을 나아지게 했던 경험을 문단으로 써 보세요.",
      "격리 기간 동안 클레이가 가족과 함께 집 안에 머무르지 않고 숲으로 피신한 이유가 무엇이라고 생각하는지 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S4537"] = { s: "To prevent the Shadow Dragon from plunging the world into sky-shadow, Drake and Darma seek out a Light Dragon. They learn that to summon a Star Dragon, they must find an object hidden within a dangerous labyrinth.",
  q: ["Drake and Darma seek a Light Dragon and must find a hidden object in a dangerous labyrinth to summon a Star Dragon. Write a paragraph imagining what dangers they might have faced inside the labyrinth.",
      "Write a paragraph about a time you had to search hard for something important, and how you kept going even when it was difficult to find.",
      "Write a paragraph giving your opinion on whether you think Drake and Darma should have asked for help finding the object, or whether facing the labyrinth alone made them stronger, and explain your reasoning."],
  h: ["드레이크와 다르마는 빛의 용을 찾아 나서고, 별의 용을 소환하기 위해 위험한 미로 속에 숨겨진 물건을 찾아야 해요. 그들이 미로 안에서 마주쳤을 위험을 상상해서 문단으로 써 보세요.",
      "여러분이 중요한 것을 애써 찾아야 했던 경험과 찾기 힘들 때도 어떻게 포기하지 않았는지 문단으로 써 보세요.",
      "드레이크와 다르마가 물건을 찾을 때 도움을 청했어야 했는지, 아니면 미로를 혼자 마주한 것이 그들을 더 강하게 만들었는지 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S4539"] = { s: "This is a collection of humorous poems about a variety of unusual and mischievous animals.",
  q: ["This book is a collection of humorous poems about unusual and mischievous animals. Choose the kind of mischievous animal you think would be funniest in a poem, and write a paragraph describing what trouble it might cause.",
      "Write a paragraph about a real animal you know that behaves in a mischievous or unusual way, and describe what it does.",
      "Write a paragraph giving your opinion on why you think poems about mischievous animals are fun to read, and explain your reasoning."],
  h: ["이 책은 특이하고 짓궂은 동물들에 대한 유쾌한 시 모음이에요. 시에 나오면 가장 재미있을 것 같은 짓궂은 동물을 하나 골라 그 동물이 일으킬 법한 소동을 문단으로 써 보세요.",
      "여러분이 아는 동물 중 짓궂거나 특이하게 행동하는 진짜 동물에 대해, 그 동물이 무엇을 하는지 문단으로 써 보세요.",
      "짓궂은 동물에 대한 시를 읽는 것이 왜 재미있다고 생각하는지 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S4540"] = { s: "This is a humorous retelling in verse of six well-known fairy tales featuring surprise endings in place of the traditional happily-ever-after. The texts contain mild profanity and violence.",
  q: ["This book retells six well-known fairy tales in verse with surprise endings instead of the traditional happily-ever-after. Choose one fairy tale you think would be in this book and write a paragraph imagining a surprise ending for it.",
      "Write a paragraph about a story or movie ending you wish had turned out differently, and describe the ending you would have written instead.",
      "Write a paragraph giving your opinion on whether surprise endings make old fairy tales better or worse, and explain your reasoning."],
  h: ["이 책은 여섯 편의 유명한 동화를 운문으로 다시 쓰면서 전통적인 해피엔딩 대신 뜻밖의 결말을 넣어요. 이 책에 실렸을 법한 동화 하나를 골라 그 이야기의 뜻밖의 결말을 상상해서 문단으로 써 보세요.",
      "여러분이 다르게 끝났으면 했던 이야기나 영화의 결말을 쓰고, 대신 어떤 결말을 쓰고 싶은지 문단으로 써 보세요.",
      "뜻밖의 결말이 오래된 동화를 더 낫게 만드는지 아니면 더 별로로 만드는지 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S4541"] = { s: "This is an inventive and irreverent collection of rhymes that twists traditional fairy tales, fables, and nursery rhymes. Roald Dahl takes well-known stories like Aladdin and Hansel and Gretel and adds his signature dark humor and unexpected, hilarious endings.",
  q: ["This book twists familiar stories like Aladdin and Hansel and Gretel with dark humor and unexpected endings. Choose one of these two stories and write a paragraph imagining how Roald Dahl might have given it an unexpected, hilarious ending.",
      "Write a paragraph about a familiar story you know well, and describe how you would twist it to make it funnier or more surprising.",
      "Write a paragraph giving your opinion on whether twisting classic fairy tales and nursery rhymes like this is disrespectful to the original stories or a clever way to make them new, and explain your reasoning."],
  h: ["이 책은 알라딘과 헨젤과 그레텔 같은 친숙한 이야기를 어두운 유머와 예상 밖의 결말로 비틀어요. 이 두 이야기 중 하나를 골라 로알드 달이 어떤 뜻밖의 웃긴 결말을 만들었을지 상상해서 문단으로 써 보세요.",
      "여러분이 잘 아는 익숙한 이야기 하나를 쓰고, 그것을 더 재미있거나 뜻밖의 이야기로 바꾸려면 어떻게 비틀지 문단으로 써 보세요.",
      "이처럼 고전 동화와 전래동요를 비트는 것이 원작에 무례한 일인지 아니면 그것을 새롭게 만드는 영리한 방법인지 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S4542"] = { s: "This book discusses mummies and pyramids and researches the facts behind the fiction. The coauthor is Mary Pope Osborne.",
  q: ["This book researches the facts behind the fiction of mummies and pyramids. Choose one fact you think the book might reveal and write a paragraph about why you find it surprising.",
      "Write a paragraph about something you once believed was pure fiction or legend, but later found out had some real facts behind it.",
      "Write a paragraph giving your opinion on why you think mummies and pyramids still fascinate people so much today, and explain your reasoning."],
  h: ["이 책은 미라와 피라미드에 관한 이야기 뒤에 숨겨진 사실을 연구해요. 이 책이 밝혀낼 법한 사실 하나를 골라 그것이 왜 놀랍다고 생각하는지 문단으로 써 보세요.",
      "여러분이 완전히 꾸며낸 이야기나 전설이라고 믿었지만 나중에 그 뒤에 진짜 사실이 있다는 것을 알게 된 경험을 문단으로 써 보세요.",
      "오늘날에도 사람들이 미라와 피라미드에 여전히 매료되는 이유가 무엇이라고 생각하는지 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S4543"] = { s: "Jack and Annie research the world of pirates and find out the facts behind the fiction. The coauthor is Mary Pope Osborne.",
  q: ["Jack and Annie research the world of pirates to find the facts behind the fiction. Choose one pirate fact you think they might have discovered and write a paragraph about it.",
      "Write a paragraph about a time a movie, book, or story about pirates or adventurers made you curious to learn the real facts.",
      "Write a paragraph giving your opinion on whether you think the real facts about pirates are more exciting or less exciting than the fictional stories about them, and explain your reasoning."],
  h: ["잭과 애니는 해적의 세계를 조사해 이야기 뒤에 숨겨진 사실을 찾아내요. 그들이 발견했을 법한 해적에 관한 사실 하나를 골라 문단으로 써 보세요.",
      "해적이나 모험가를 다룬 영화, 책, 이야기 때문에 실제 사실이 궁금해졌던 경험을 문단으로 써 보세요.",
      "해적에 대한 진짜 사실이 그들을 다룬 꾸며낸 이야기보다 더 흥미롭다고 생각하는지 덜 흥미롭다고 생각하는지 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S4544"] = { s: "Join Jack and Annie as they research rain forests and find out the facts behind the fiction. The coauthor is Mary Pope Osborne.",
  q: ["Jack and Annie research rain forests to find the facts behind the fiction. Choose one fact about rain forests you think they might have learned and write a paragraph about it.",
      "Write a paragraph about why you think protecting rain forests matters, connecting it to something in your own life or the world around you.",
      "Write a paragraph giving your opinion on which is more useful for learning about rain forests: reading a made-up adventure story, like Jack and Annie's, or reading a fact-based research book like this one, and explain your reasoning."],
  h: ["잭과 애니는 열대우림을 조사해 이야기 뒤에 숨겨진 사실을 찾아내요. 그들이 알게 되었을 법한 열대우림에 관한 사실 하나를 골라 문단으로 써 보세요.",
      "열대우림을 보호하는 것이 왜 중요하다고 생각하는지, 여러분의 삶이나 주변 세상과 연결해서 문단으로 써 보세요.",
      "열대우림에 대해 배우는 데 잭과 애니의 꾸며낸 모험 이야기와 이런 사실 기반 조사 책 중 어느 쪽이 더 유용하다고 생각하는지 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S4545"] = { s: "This book describes the changing nature of weather and how meteorologists predict and study such storms as tornadoes, hurricanes, and blizzards. The coauthor is Mary Pope Osborne.",
  q: ["This book describes how meteorologists predict and study storms like tornadoes, hurricanes, and blizzards. Choose one of these three kinds of storms and write a paragraph about what you imagine a meteorologist does to study it.",
      "Write a paragraph about a storm or extreme weather you have experienced, and how it made you feel.",
      "Write a paragraph giving your opinion on why you think it is important for meteorologists to be able to predict these dangerous storms, and explain your reasoning."],
  h: ["이 책은 기상학자들이 토네이도, 허리케인, 눈보라 같은 폭풍을 어떻게 예측하고 연구하는지 설명해요. 이 세 폭풍 중 하나를 골라 기상학자가 그것을 연구하기 위해 무엇을 할지 상상해서 문단으로 써 보세요.",
      "여러분이 겪었던 폭풍이나 극단적인 날씨와 그때 어떤 기분이었는지 문단으로 써 보세요.",
      "기상학자들이 이런 위험한 폭풍을 예측할 수 있는 것이 왜 중요하다고 생각하는지 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S4546"] = { s: "Annie and Jack present information about ancient Greece and the athletic events known as the Olympic Games that were held there. The coauthor is Natalie Pope Boyce.",
  q: ["Annie and Jack present information about ancient Greece and the Olympic Games. Choose one ancient Olympic event you think they might describe and write a paragraph imagining what it was like to compete in it.",
      "Write a paragraph comparing a sport or competition you take part in today to what you imagine the ancient Olympics were like.",
      "Write a paragraph giving your opinion on whether you think the modern Olympics are more similar to or more different from the ancient Greek Olympics, and explain your reasoning."],
  h: ["애니와 잭은 고대 그리스와 올림픽 경기에 대한 정보를 전해줘요. 그들이 설명했을 법한 고대 올림픽 종목 하나를 골라 그 경기에 참가하는 것이 어땠을지 상상해서 문단으로 써 보세요.",
      "여러분이 오늘날 참여하는 스포츠나 대회를 고대 올림픽이 어땠을지 상상한 모습과 비교해서 문단으로 써 보세요.",
      "현대 올림픽이 고대 그리스 올림픽과 더 비슷하다고 생각하는지 더 다르다고 생각하는지 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S4547"] = { s: "This book presents a picture of life in colonial America and reviews the causes and major events of the American Revolution. The coauthor is Natalie Pope Boyce.",
  q: ["This book reviews the causes and major events of the American Revolution and life in colonial America. Choose one cause or event you think it describes and write a paragraph about why you think it was important.",
      "Write a paragraph about a time you or a group you were part of decided to stand up against something you thought was unfair.",
      "Write a paragraph giving your opinion on which cause of the American Revolution you think was the most important, and explain your reasoning."],
  h: ["이 책은 식민지 시대 미국인의 삶과 미국 독립 혁명의 원인과 주요 사건을 살펴봐요. 이 책이 다뤘을 법한 원인이나 사건 하나를 골라 그것이 왜 중요했다고 생각하는지 문단으로 써 보세요.",
      "여러분이나 여러분이 속한 집단이 부당하다고 생각한 것에 맞서기로 했던 경험을 문단으로 써 보세요.",
      "미국 독립 혁명의 원인 중 가장 중요했다고 생각하는 것을 골라 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S4548"] = { s: "This nonfiction companion to SUNSET OF THE SABERTOOTH explores the secrets of the Ice Age including information about the people and animals that lived at that time. The coauthor is Natalie Pope Boyce.",
  q: ["This book explores the secrets of the Ice Age, including the people and animals that lived then. Choose one Ice Age animal, such as the sabertooth, and write a paragraph about what you imagine its daily life was like.",
      "Write a paragraph about how you imagine surviving cold weather without modern heating or clothing, like people did in the Ice Age.",
      "Write a paragraph giving your opinion on whether you think it was harder for Ice Age people or Ice Age animals to survive, and explain your reasoning."],
  h: ["이 책은 그 시대에 살았던 사람과 동물을 포함해 빙하 시대의 비밀을 탐구해요. 검치호처럼 빙하 시대의 동물 하나를 골라 그 동물의 일상이 어땠을지 상상해서 문단으로 써 보세요.",
      "빙하 시대 사람들처럼 현대적인 난방이나 옷 없이 추운 날씨에서 살아남는 것이 어땠을지 상상해서 문단으로 써 보세요.",
      "빙하 시대에는 사람과 동물 중 어느 쪽이 살아남기 더 힘들었을 거라고 생각하는지 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S4549"] = { s: "What was it like to be a passenger on the \"Mayflower\"? How many people survived the first harsh winter in the New World? Find out the answers to these questions and more in this book. The coauthor is Natalie Pope Boyce.",
  q: ["This book asks what it was like to be a passenger on the Mayflower and how many people survived the first harsh winter. Write a paragraph answering what you imagine daily life aboard the Mayflower was like.",
      "Write a paragraph about a time you had to survive a difficult situation with very little help or supplies, and compare it to what the Pilgrims faced.",
      "Write a paragraph giving your opinion on what you think was the most important thing the Pilgrims needed to survive that first winter, and explain your reasoning."],
  h: ["이 책은 메이플라워호의 승객으로 사는 것이 어땠는지, 첫 혹독한 겨울에 몇 명이 살아남았는지 물어요. 메이플라워호 위에서의 일상이 어땠을지 상상해서 문단으로 써 보세요.",
      "여러분이 도움이나 물자가 거의 없는 상태에서 힘든 상황을 견뎌야 했던 경험을 쓰고, 그것을 순례자들이 겪은 일과 비교해서 문단으로 써 보세요.",
      "순례자들이 첫 겨울을 견디는 데 가장 중요했던 것이 무엇이었다고 생각하는지 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S4550"] = { s: "This nonfiction companion to POLAR BEARS PAST BEDTIME looks at the Arctic and the animals and people that live there. The coauthor is Natalie Pope Boyce.",
  q: ["This book looks at the Arctic and the animals and people that live there. Choose the polar bear or one other Arctic animal and write a paragraph about how you imagine it survives the cold.",
      "Write a paragraph about the coldest weather you have ever experienced, and compare it to what you imagine living in the Arctic is like.",
      "Write a paragraph giving your opinion on why you think it is important to protect the Arctic and the animals that live there, and explain your reasoning."],
  h: ["이 책은 북극과 그곳에 사는 동물과 사람들을 살펴봐요. 북극곰이나 다른 북극 동물 하나를 골라 그 동물이 추위 속에서 어떻게 살아남는지 상상해서 문단으로 써 보세요.",
      "여러분이 겪어본 가장 추운 날씨를 쓰고, 그것을 북극에서 사는 것이 어떨지와 비교해서 문단으로 써 보세요.",
      "북극과 그곳에 사는 동물들을 보호하는 것이 왜 중요하다고 생각하는지 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S4551"] = { s: "This book is a research companion to the Magic Tree House story \"Dark Day in the Deep Sea,\" providing facts about sea creatures and the history of underwater exploration. The coauthor is Natalie Pope Boyce.",
  q: ["This book provides facts about sea creatures and the history of underwater exploration. Choose one sea creature you think might be mistaken for a 'sea monster' and write a paragraph about why people might have believed it was a monster.",
      "Write a paragraph about a time something unfamiliar seemed scary or monster-like at first, but turned out to have a normal explanation.",
      "Write a paragraph giving your opinion on why you think people long ago believed in sea monsters, even though most of these creatures were real, explainable animals."],
  h: ["이 책은 바다 생물과 수중 탐험의 역사에 대한 사실을 알려줘요. '바다 괴물'로 오해받았을 법한 바다 생물 하나를 골라 사람들이 왜 그것을 괴물이라고 믿었을지 문단으로 써 보세요.",
      "낯선 무언가가 처음에는 무섭거나 괴물처럼 느껴졌지만 나중에 평범한 이유가 있었다는 것을 알게 된 경험을 문단으로 써 보세요.",
      "이런 생물 대부분이 실제로 설명 가능한 동물이었음에도 옛날 사람들이 바다 괴물을 믿었던 이유가 무엇이라고 생각하는지 여러분의 의견을 문단으로 써 보세요."] };
ACT["S4552"] = { s: "Jack and Annie present facts about penguins and Antarctica. The coauthor is Natalie Pope Boyce.",
  q: ["Jack and Annie present facts about penguins and Antarctica. Choose one fact about penguins you think they might have discovered and write a paragraph about it.",
      "Write a paragraph about an animal you find as interesting as penguins, and explain what makes it interesting to you.",
      "Write a paragraph giving your opinion on whether you think penguins are well suited to life in Antarctica, and explain your reasoning using what you imagine the book describes."],
  h: ["잭과 애니는 펭귄과 남극 대륙에 대한 사실을 전해줘요. 그들이 발견했을 법한 펭귄에 관한 사실 하나를 골라 문단으로 써 보세요.",
      "여러분이 펭귄만큼 흥미롭다고 생각하는 동물을 하나 골라, 그 동물이 왜 흥미로운지 문단으로 써 보세요.",
      "펭귄이 남극 대륙의 삶에 잘 맞는다고 생각하는지, 이 책이 설명했을 법한 내용을 근거로 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S4553"] = { s: "How did Leonardo da Vinci become interested in flight? What are some of his most famous paintings? Do his scientific ideas measure up to what we know today? Find out the answers to these questions in this book. The coauthor is Natalie Pope Boyce.",
  q: ["This book asks how Leonardo da Vinci became interested in flight, what his most famous paintings are, and whether his scientific ideas hold up today. Choose one of these three questions and write a paragraph with your best guess at the answer.",
      "Write a paragraph about someone you know who, like Leonardo da Vinci, is both artistic and interested in how things work.",
      "Write a paragraph giving your opinion on whether you think Leonardo da Vinci is remembered more for his art or for his scientific ideas, and explain your reasoning."],
  h: ["이 책은 레오나르도 다빈치가 어떻게 비행에 관심을 갖게 되었는지, 가장 유명한 그림은 무엇인지, 그의 과학적 아이디어가 오늘날에도 통하는지를 물어요. 이 세 질문 중 하나를 골라 여러분이 생각하는 답을 문단으로 써 보세요.",
      "레오나르도 다빈치처럼 예술적이면서 동시에 사물이 작동하는 원리에도 관심이 많은 사람을 여러분 주변에서 한 명 골라 문단으로 써 보세요.",
      "레오나르도 다빈치가 예술로 더 많이 기억된다고 생각하는지 과학적 아이디어로 더 많이 기억된다고 생각하는지 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S4554"] = { s: "Jack and Annie track down facts about service dogs, such as St. Bernard rescue dogs, famous war dogs, and other canine heroes. The coauthor is Natalie Pope Boyce.",
  q: ["Jack and Annie track down facts about service dogs, St. Bernard rescue dogs, and famous war dogs. Choose one type of hero dog and write a paragraph about what you imagine makes it especially good at its job.",
      "Write a paragraph about a dog or other animal in your own life or community that has helped people in some way.",
      "Write a paragraph giving your opinion on which kind of hero dog — service dogs, rescue dogs, or war dogs — you think does the most important work, and explain your reasoning."],
  h: ["잭과 애니는 봉사견, 세인트버나드 구조견, 유명한 군견에 관한 사실을 조사해요. 영웅견 종류 하나를 골라 그 개가 자신의 일을 특히 잘하게 만드는 것이 무엇일지 상상해서 문단으로 써 보세요.",
      "여러분의 삶이나 주변에서 어떤 식으로든 사람들을 도운 강아지나 다른 동물에 대해 문단으로 써 보세요.",
      "봉사견, 구조견, 군견 중 어느 쪽이 가장 중요한 일을 한다고 생각하는지 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S4574"] = { s: "?After British and Soviet forces occupy Iran, orphans Babak and Sana must use their wits to survive a perilous journey in the mountains. Book has graphic violence and offensive language (racial).",
  q: ["After British and Soviet forces occupy Iran, orphans Babak and Sana must use their wits to survive a perilous journey in the mountains. Write a paragraph about a moment in the book where you think their wits, not just luck, kept them safe.",
      "Write a paragraph about a time you had to rely on your own wits, without much help from adults, to solve a problem.",
      "Write a paragraph giving your opinion on how you think Babak and Sana's being orphans, with no parents to guide them, changed the way they had to survive this journey, and explain your reasoning."],
  h: ["영국군과 소련군이 이란을 점령한 뒤, 고아인 바바크와 사나는 지혜를 발휘해 산속의 위험한 여정에서 살아남아야 해요. 책 속에서 운이 아니라 그들의 지혜가 안전을 지켜주었다고 생각하는 순간을 문단으로 써 보세요.",
      "여러분이 어른의 도움 없이 스스로의 지혜에 의지해 문제를 해결해야 했던 경험을 문단으로 써 보세요.",
      "바바크와 사나가 부모 없이 고아로서 이 여정을 헤쳐나가야 했다는 사실이 그들의 생존 방식을 어떻게 바꾸었다고 생각하는지 여러분의 의견과 이유를 문단으로 써 보세요."] };
