// 간이 학습 질문 — Book No. S50 묶음. 사람이 아니라 AI 가 한 번 쓰고 굳힌 파일이다.
window.ACT = window.ACT || {};
var ACT = window.ACT;
ACT["S5001"] = { s: "A shy twelve-year-old girl must solve a puzzle to free herself from a spell which makes her irresistible to boys. The puzzle is involving characters from Greek Mythology.",
  q: ["This book says Juliet must solve a puzzle involving characters from Greek Mythology to free herself from a spell. Write a paragraph imagining what that puzzle might be like.",
      "The summary says Juliet is shy. Write a paragraph about a time you felt shy, and how you handled it.",
      "Write a paragraph giving your opinion on how you would feel if a spell made everyone suddenly like you."],
  h: ["이 책은 줄리엣이 그리스 신화 속 인물들이 얽힌 퍼즐을 풀어야 저주에서 풀려난다고 해요. 그 퍼즐이 어떤 모습일지 상상하며 문단으로 써 보세요.",
      "요약에는 줄리엣이 수줍음이 많다고 나와요. 여러분이 수줍었던 순간과 그때 어떻게 했는지 문단으로 써 보세요.",
      "저주 때문에 갑자기 모두가 나를 좋아하게 된다면 어떤 기분일지 여러분의 생각을 문단으로 써 보세요."] };
ACT["S5002"] = { s: "The three Baudelaire children must depend on each other after the death of their parents. When the relative who is appointed their guardian tries to get their fortune by any means, they escape the danger by their wits. Book #1",
  q: ["This book's three children worked together to escape danger from their guardian. Write a paragraph imagining how they might have worked together.",
      "The children in this book had to depend on each other after a hard loss. Write a paragraph about a time you depended on your brother, sister, or a friend to get through something hard.",
      "Write a paragraph giving your opinion on why depending on each other was important for the Baudelaire children."],
  h: ["이 책의 세 남매는 위험에서 벗어나려고 서로 힘을 합쳤어요. 그들이 어떻게 힘을 합쳤을지 상상하며 문단으로 써 보세요.",
      "이 책의 아이들은 큰 슬픔을 겪은 뒤 서로에게 의지했어요. 여러분이 힘든 일을 겪을 때 형제나 친구에게 의지했던 경험을 문단으로 써 보세요.",
      "보들레르 남매에게 서로 의지하는 것이 왜 중요했는지 여러분의 생각을 문단으로 써 보세요."] };
ACT["S5003"] = { s: "The peaceful life of ancient Redwall Abbey is shattered when the evil rat Cluny and his villainous hordes arrive. Matthias determines to find the legendary sword of Martin the Warrior. He is sure that it will help destroy the enemy.",
  q: ["Write a paragraph imagining what Matthias's search for the legendary sword of Martin the Warrior might have been like.",
      "The peaceful life at Redwall Abbey is suddenly shattered by danger. Write a paragraph about a time when something peaceful in your life was suddenly interrupted.",
      "Write a paragraph giving your opinion on why Matthias believed the legendary sword could help destroy Cluny and his hordes."],
  h: ["매티어스가 전설의 검을 찾아 나선 여정이 어땠을지 상상하며 문단으로 써 보세요.",
      "평화롭던 레드월 수도원이 갑자기 위험에 빠졌어요. 여러분의 평화로운 일상이 갑자기 흔들렸던 경험을 문단으로 써 보세요.",
      "매티어스가 그 전설의 검이 클루니와 그 무리를 물리치는 데 도움이 될 거라고 믿은 이유를 여러분의 생각으로 문단으로 써 보세요."] };
ACT["S5004"] = { s: "After the death of the uncle who had been his guardian, Alex is coerced to continue his uncle's dangerous work for Britain's intelligence agency. The first in a thrilling new series by British writer Anthony Horowitz, Stormbreaker will have pulses racing from start to finish. Book #1",
  q: ["Write a paragraph imagining how Alex might have felt when he learned about his uncle's dangerous secret work.",
      "Alex is asked to continue work that used to belong to a family member. Write a paragraph about something you learned to do because someone in your family did it first.",
      "Write a paragraph giving your opinion on whether it was fair for the intelligence agency to coerce a boy like Alex into dangerous work."],
  h: ["알렉스가 삼촌의 위험한 비밀 임무를 알게 되었을 때 어떤 기분이었을지 상상하며 문단으로 써 보세요.",
      "알렉스는 가족이 하던 일을 이어받아요. 여러분이 가족이 먼저 하던 일을 보고 따라 배운 경험을 문단으로 써 보세요.",
      "정보기관이 알렉스 같은 소년에게 위험한 일을 강요한 것이 옳았는지 여러분의 생각을 문단으로 써 보세요."] };
ACT["S5005"] = { s: "This book presents the warships, the MONITOR and the VIRGINIA, which confronted each other at the Civil War battle at Hampton Roads. These ironclad ships changed how wars are fought at sea. You can find out about the Monitor's revolutionary design, exciting battle, and intriguing excavation.",
  q: ["This book describes the Monitor's design, its battle, and its excavation. Choose one of these three parts and write a paragraph about what you find most interesting.",
      "Write a paragraph about a time you saw or learned about something with an unusual or 'revolutionary' design.",
      "Write a paragraph giving your opinion on why ironclad ships like the Monitor changed how wars were fought at sea."],
  h: ["이 책은 모니터호의 설계, 전투, 발굴 이야기를 다뤄요. 이 중 하나를 골라 가장 흥미로운 점을 문단으로 써 보세요.",
      "여러분이 보거나 알게 된 특별하고 '혁신적인' 디자인에 대해 문단으로 써 보세요.",
      "모니터호 같은 철갑선이 바다에서의 전쟁 방식을 바꾼 이유를 여러분의 생각으로 문단으로 써 보세요."] };
ACT["S5006"] = { s: "Jason embarks on an epic voyage with his crew to bring back the Golden Fleece.",
  q: ["Write a paragraph imagining what dangers Jason and his crew might have faced on their voyage to bring back the Golden Fleece.",
      "Jason set out on a voyage with his crew to reach a goal. Write a paragraph about a goal you worked toward with a group of people.",
      "Write a paragraph giving your opinion on why the Golden Fleece might have been worth such a difficult and epic voyage."],
  h: ["제이슨과 선원들이 황금 양털을 찾으러 가는 길에 어떤 위험을 만났을지 상상하며 문단으로 써 보세요.",
      "여러분이 여러 사람과 함께 목표를 향해 노력했던 경험을 문단으로 써 보세요.",
      "황금 양털이 그렇게 힘든 항해를 할 만큼 가치 있었을지 여러분의 생각을 문단으로 써 보세요."] };
ACT["S5007"] = { s: "Perseus, who is abandoned at birth, goes on a journey to protect his mother from the wicked King Polydectes. On his adventure, he fights hideous, legendary monsters.",
  q: ["Write a paragraph imagining one of the hideous, legendary monsters Perseus might have fought on his journey.",
      "Perseus goes on a journey to protect his mother. Write a paragraph about a time you tried to protect or help someone in your family.",
      "Write a paragraph giving your opinion on why Perseus was willing to fight monsters to protect his mother from King Polydectes."],
  h: ["페르세우스가 여정에서 맞서 싸웠을 무시무시한 괴물 하나를 상상하며 문단으로 써 보세요.",
      "여러분이 가족을 지키거나 도우려 했던 경험을 문단으로 써 보세요.",
      "페르세우스가 어머니를 지키기 위해 괴물과 싸우기로 한 이유를 여러분의 생각으로 문단으로 써 보세요."] };
ACT["S5008"] = { s: "Hercules, in sheer madness, has killed his family and offended the gods. To punish him, King Eurystheus sets him twelve seemingly impossible jobs.",
  q: ["Write a paragraph imagining what one of Hercules's twelve seemingly impossible jobs might have been like.",
      "Hercules is given very hard tasks as a punishment. Write a paragraph about a hard task you had to complete, and how you felt while doing it.",
      "Write a paragraph giving your opinion on whether it was right for King Eurystheus to give Hercules these jobs as punishment."],
  h: ["헤라클레스에게 주어진 열두 가지 불가능해 보이는 과제 중 하나가 어땠을지 상상하며 문단으로 써 보세요.",
      "여러분이 겪었던 힘든 과제와 그때의 기분을 문단으로 써 보세요.",
      "에우리스테우스 왕이 헤라클레스에게 그런 벌을 준 것이 옳았는지 여러분의 생각을 문단으로 써 보세요."] };
ACT["S5009"] = { s: "After the Trojan War was over, Odysseus wants to sail to the island of Ithaca. But angry gods drive his fleet off course.",
  q: ["Write a paragraph imagining what might happen to Odysseus and his fleet after being driven off course by the angry gods.",
      "Odysseus wanted to reach home but faced many obstacles along the way. Write a paragraph about a time something got in the way of you reaching a place you wanted to go.",
      "Write a paragraph giving your opinion on why the gods might have been angry enough to drive Odysseus's fleet off course."],
  h: ["성난 신들 때문에 항로를 벗어난 오디세우스의 함대에 무슨 일이 일어났을지 상상하며 문단으로 써 보세요.",
      "여러분이 가고 싶은 곳에 무언가가 방해가 되었던 경험을 문단으로 써 보세요.",
      "신들이 오디세우스의 함대를 항로에서 벗어나게 할 만큼 화가 난 이유를 여러분의 생각으로 문단으로 써 보세요."] };
ACT["S5010"] = { s: "Paris, the Trojan prince, abducts Helen, the wife of King Menelaus. The recklessness provokes Greece's armies to unite and declare war.",
  q: ["Write a paragraph imagining how the Greek armies might have felt when they united to declare war after Helen was taken.",
      "This book shows one reckless act leading to a huge war. Write a paragraph about a time a small action caused a much bigger problem.",
      "Write a paragraph giving your opinion on whether Paris should have known his actions would cause such serious consequences."],
  h: ["헬레네가 납치된 뒤 그리스 군대가 힘을 합쳐 전쟁을 선포했을 때 어떤 기분이었을지 상상하며 문단으로 써 보세요.",
      "작은 행동 하나가 훨씬 큰 문제로 번졌던 경험을 문단으로 써 보세요.",
      "파리스가 자신의 행동이 그런 심각한 결과를 낳을 줄 알았어야 했는지 여러분의 생각을 문단으로 써 보세요."] };
ACT["S5011"] = { s: "Every nine years, the Athenians send a sacrifice of seven young men and seven young women to the Minotaur. Theseus takes on the duty to end this vicious cycle.",
  q: ["Write a paragraph imagining how Theseus might have felt as he prepared to end the vicious cycle of sacrifices to the Minotaur.",
      "Theseus decided to take on a difficult duty to help his people. Write a paragraph about a time you took on a difficult duty to help others.",
      "Write a paragraph giving your opinion on why it was important for someone like Theseus to end this cycle of sacrifice."],
  h: ["테세우스가 미노타우로스에게 바쳐지는 잔인한 희생을 끝내려 준비하며 어떤 기분이었을지 상상하며 문단으로 써 보세요.",
      "여러분이 다른 사람을 돕기 위해 어려운 일을 맡았던 경험을 문단으로 써 보세요.",
      "테세우스 같은 사람이 그 희생의 굴레를 끝내는 것이 왜 중요했는지 여러분의 생각을 문단으로 써 보세요."] };
ACT["S5012"] = { s: "The girls and boys in the fifth grade at Laketon Elementary don't get along very well. But the real problem is that these children are noisy. The boys challenge the girls to a contest: Which team can say the fewest words during two whole days?",
  q: ["Write a paragraph imagining how hard it would be to say almost nothing for two whole days like the students in this contest.",
      "This book is about a contest between two teams. Write a paragraph about a fun contest or challenge you have taken part in.",
      "Write a paragraph giving your opinion on whether a no-talking contest would help students get along better."],
  h: ["이 대회의 학생들처럼 이틀 동안 거의 말을 하지 않는 것이 얼마나 힘들지 상상하며 문단으로 써 보세요.",
      "여러분이 참가했던 재미있는 대회나 도전에 대해 문단으로 써 보세요.",
      "말하지 않기 대회가 학생들이 더 잘 지내는 데 도움이 될지 여러분의 생각을 문단으로 써 보세요."] };
ACT["S5013"] = { s: "Ted Hammond is a sixth-grader in a small town who loves mysteries so much. At the moment, the case of the disappearance of a homeless family has his full attention. He searches for clues to solve the mystery.",
  q: ["Write a paragraph imagining what clues Ted Hammond might have found while searching for the missing homeless family.",
      "Ted loves solving mysteries. Write a paragraph about a mystery or puzzle you have tried to solve.",
      "Write a paragraph giving your opinion on why Ted felt it was so important to find out what happened to the homeless family."],
  h: ["테드 해먼드가 사라진 노숙자 가족을 찾으며 발견했을 단서를 상상하며 문단으로 써 보세요.",
      "여러분이 풀어 보려 했던 수수께끼나 미스터리에 대해 문단으로 써 보세요.",
      "테드가 노숙자 가족에게 무슨 일이 있었는지 알아내는 것을 왜 그렇게 중요하게 여겼는지 여러분의 생각을 문단으로 써 보세요."] };
ACT["S5014"] = { s: "Twelve-year-old Greg has always been very talented at moneymaking projects. Now he devises a plan to create a series of comic books to sell at school, teaming up with his lifelong rival, Maura.",
  q: ["Write a paragraph imagining how Greg and Maura, who are rivals, might have worked together to make their comic books.",
      "Greg is talented at moneymaking projects. Write a paragraph about a time you tried to earn or save money.",
      "Write a paragraph giving your opinion on whether it is a good idea for rivals like Greg and Maura to team up on a project."],
  h: ["라이벌인 그렉과 모라가 만화책을 만들며 어떻게 힘을 합쳤을지 상상하며 문단으로 써 보세요.",
      "여러분이 돈을 벌거나 모으려 했던 경험을 문단으로 써 보세요.",
      "그렉과 모라처럼 라이벌끼리 함께 일하는 것이 좋은 생각인지 여러분의 생각을 문단으로 써 보세요."] };
ACT["S5015"] = { s: "Twelve-year-old Natalie has written a short but powerful novel about school. Her best friend Zoe devises a scheme to get it published at a big publishing house where Natalie's mom is actual an editor.",
  q: ["Write a paragraph imagining what Zoe's scheme to get Natalie's novel published might have involved.",
      "Natalie wrote a novel with the help of her best friend's plan. Write a paragraph about a time a friend helped you accomplish something.",
      "Write a paragraph giving your opinion on whether Zoe's scheme to get the novel published was a good idea."],
  h: ["조이가 나탈리의 소설을 출판시키려고 세운 계획이 어떤 것이었을지 상상하며 문단으로 써 보세요.",
      "여러분이 친구의 도움으로 무언가를 해낸 경험을 문단으로 써 보세요.",
      "조이의 출판 계획이 좋은 생각이었는지 여러분의 생각을 문단으로 써 보세요."] };
ACT["S5016"] = { s: "The fact that he has to spend his fifth grade in the building where his father works as a janitor dreads Jack. He schemes for revenge as his father does the unthinkable when they run into each other at school.",
  q: ["Write a paragraph imagining what 'the unthinkable' Jack's father might have done when they ran into each other at school.",
      "Jack feels embarrassed about his father's job. Write a paragraph about a time you felt embarrassed about something, even if it turned out not to matter.",
      "Write a paragraph giving your opinion on whether Jack was right to feel dread about his father's job at his school."],
  h: ["학교에서 마주쳤을 때 잭의 아버지가 했던 '상상도 못 할 일'이 무엇이었을지 상상하며 문단으로 써 보세요.",
      "별일 아니었는데도 창피했던 경험을 문단으로 써 보세요.",
      "잭이 아버지의 직업 때문에 그렇게 걱정한 것이 옳았는지 여러분의 생각을 문단으로 써 보세요."] };
ACT["S5017"] = { s: "Nick gets the inspiration to invent a new word 'frindle' when he learns some interesting information about how words are created. The word frindle goes viral. Everyone in town says 'a frindle' instead of 'a pen.'",
  q: ["Write a paragraph imagining how it would feel if a word you invented, like 'frindle,' became used by everyone in your town.",
      "Nick learned that people, not dictionaries, decide what words mean. Write a paragraph about a word or phrase you and your friends use that not everyone else uses.",
      "Write a paragraph giving your opinion on whether it is a good idea for one person to be able to invent a brand new word."],
  h: ["여러분이 만든 단어 '프린들'처럼 온 동네 사람들이 그 단어를 쓴다면 어떤 기분일지 상상하며 문단으로 써 보세요.",
      "여러분과 친구들만 쓰는 말이나 표현에 대해 문단으로 써 보세요.",
      "한 사람이 완전히 새로운 단어를 만들 수 있다는 것이 좋은 생각인지 여러분의 생각을 문단으로 써 보세요."] };
ACT["S5018"] = { s: "Hart Evans, the popular sixth-grader, is put in charge of the holiday concert. He must use all his skills and wisdom to lead and unite the other students. Finally, the sixth-grade choral concert is born out of chaos, infighting, compromise, idealism, and fragile peace.",
  q: ["Write a paragraph imagining the chaos and infighting Hart Evans had to deal with while organizing the holiday concert.",
      "Hart had to lead and unite other students for a big event. Write a paragraph about a time you had to lead or help organize a group.",
      "Write a paragraph giving your opinion on whether compromise was the most important skill Hart needed to finish the concert."],
  h: ["하트 에번스가 연말 공연을 준비하며 겪은 혼란과 다툼을 상상하며 문단으로 써 보세요.",
      "여러분이 모둠을 이끌거나 행사를 준비하는 것을 도왔던 경험을 문단으로 써 보세요.",
      "타협이 하트가 공연을 마치는 데 가장 중요한 능력이었는지 여러분의 생각을 문단으로 써 보세요."] };
ACT["S5019"] = { s: "It seems Mr. Maxwell is not in favor of Mark, who he decided is rich and know-it-all. When Mark goes on the fifth grade's annual camping trip in the woods, he uses survival skills and his ability to relate to the teacher.",
  q: ["Write a paragraph imagining how Mark used his survival skills during the camping trip in the woods.",
      "Mark had to work on his relationship with a teacher who misjudged him. Write a paragraph about a time someone misunderstood you at first.",
      "Write a paragraph giving your opinion on why the camping trip helped change Mr. Maxwell's opinion of Mark."],
  h: ["숲 캠핑 동안 마크가 생존 기술을 어떻게 활용했을지 상상하며 문단으로 써 보세요.",
      "처음에 여러분을 오해했던 사람이 있었던 경험을 문단으로 써 보세요.",
      "캠핑 여행이 맥스웰 선생님의 마크에 대한 생각을 바꾸는 데 어떻게 도움이 되었을지 여러분의 생각을 문단으로 써 보세요."] };
ACT["S5020"] = { s: "A fifth-grader, Cara Landry is a budding journalist. She posts an editorial that prompts her burnt-out classroom teacher, Mr. Larson, to begin teaching again. Then Mr. Larson challenges his students to create a real newspaper, and they start the Landry News. When the newspaper gets more attention, the principal uses it to get Mr. Larson fired.",
  q: ["Write a paragraph imagining what Cara's editorial might have said to inspire Mr. Larson to start teaching again.",
      "Cara's writing changed how her teacher felt about his job. Write a paragraph about a time your words or actions changed how someone felt.",
      "Write a paragraph giving your opinion on whether it was fair for the principal to use the newspaper to get Mr. Larson fired."],
  h: ["카라의 사설이 지쳐 있던 라슨 선생님을 다시 가르치고 싶게 만들었을 내용을 상상하며 문단으로 써 보세요.",
      "여러분의 말이나 행동이 누군가의 마음을 바꾸었던 경험을 문단으로 써 보세요.",
      "교장 선생님이 신문을 이용해 라슨 선생님을 해고한 것이 공정했는지 여러분의 생각을 문단으로 써 보세요."] };
ACT["S5021"] = { s: "As Aunt Tabby is determined to sell their wonderful old haunted house, Araminta asks two ghost-Sir Horace and Edmund- to stop her! With their help, Araminta plots for a ghoulish ambush that might work!",
  q: ["Write a paragraph imagining what Araminta's ghoulish ambush with Sir Horace and Edmund might have looked like.",
      "Araminta asked for help from friends to solve a big problem. Write a paragraph about a time you asked friends for help with something important.",
      "Write a paragraph giving your opinion on whether Araminta was right to try to stop her aunt from selling the house."],
  h: ["아라민타가 사이 호레이스와 에드먼드와 함께 꾸민 유령 소동이 어떤 모습이었을지 상상하며 문단으로 써 보세요.",
      "여러분이 중요한 일을 해결하려고 친구에게 도움을 청했던 경험을 문단으로 써 보세요.",
      "아라민타가 이모가 집을 파는 것을 막으려 한 것이 옳았는지 여러분의 생각을 문단으로 써 보세요."] };
ACT["S5022"] = { s: "Artemis Fowl, a twelve-year-old criminal mastermind, has discovered a world below ground, where armed, dangerous, and tech-savvy fairies live. He kidnaps fairy Captain Holly Short of the LEPrecon Unit and holds her for ransom to restore his family's fortune.",
  q: ["Write a paragraph imagining the underground world of armed, tech-savvy fairies that Artemis discovered.",
      "Artemis made a risky plan to solve his family's money problem. Write a paragraph about a time your family faced a problem and how you helped, or wished you could help, solve it.",
      "Write a paragraph giving your opinion on whether kidnapping Captain Holly Short was a fair way for Artemis to try to restore his family's fortune."],
  h: ["아르테미스가 발견한 지하의 무장한 첨단 요정 세계를 상상하며 문단으로 써 보세요.",
      "여러분의 가족이 돈 문제를 겪었을 때 도왔거나 돕고 싶었던 경험을 문단으로 써 보세요.",
      "가문의 재산을 되찾으려고 홀리 쇼트를 납치한 것이 아르테미스에게 공정한 방법이었는지 여러분의 생각을 문단으로 써 보세요."] };
ACT["S5023"] = { s: "Artemis rushes to rescue his father, kidnapped by the Russian Mafia. He gets stopped by Captain Holly Short of the LEPrecon fairy police. However, this time he is going to join forces with them instead of battling them.",
  q: ["Write a paragraph imagining how Artemis and Captain Holly Short might have worked together to rescue Artemis's father.",
      "Artemis went from being enemies with Holly Short to being her ally. Write a paragraph about a time you became friends with someone you used to disagree with.",
      "Write a paragraph giving your opinion on why Artemis decided to join forces with the fairy police this time instead of fighting them."],
  h: ["아르테미스와 홀리 쇼트 대장이 아버지를 구하기 위해 어떻게 힘을 합쳤을지 상상하며 문단으로 써 보세요.",
      "예전에 다투던 사람과 친구가 된 경험을 문단으로 써 보세요.",
      "아르테미스가 이번에는 요정 경찰과 맞서지 않고 힘을 합치기로 한 이유를 여러분의 생각으로 문단으로 써 보세요."] };
ACT["S5024"] = { s: "Artemis Fowl has created a super-computer from stolen fairy technology. He plans to show it to a ruthless American businessman with Mafia connections. Butler, his bodyguard, will accompany him to the meeting.",
  q: ["Write a paragraph imagining what might go wrong when Artemis shows his stolen technology to the ruthless businessman.",
      "Artemis brought Butler, his bodyguard, along for protection at an important meeting. Write a paragraph about someone you trust to be by your side when you do something important.",
      "Write a paragraph giving your opinion on whether it was wise for Artemis to build a computer using stolen fairy technology."],
  h: ["아르테미스가 훔친 요정 기술을 그 사업가에게 보여 줄 때 무엇이 잘못될 수 있을지 상상하며 문단으로 써 보세요.",
      "중요한 일을 할 때 곁에 있어 주길 바라는, 믿는 사람에 대해 문단으로 써 보세요.",
      "아르테미스가 훔친 요정 기술로 컴퓨터를 만든 것이 현명했는지 여러분의 생각을 문단으로 써 보세요."] };
ACT["S5025"] = { s: "Criminal mastermind Artemis is preparing to steal a famous impressionist painting from a German bank. Meanwhile, evil pixie Opal Koboi, his old rival, has escaped from prison by cloning herself. She is plotting terrible revenge against her enemies, starting with Artemis Fowl.",
  q: ["Write a paragraph imagining how Opal Koboi might have escaped from prison by cloning herself.",
      "Opal Koboi is plotting revenge against an old rival. Write a paragraph about a disagreement you had with someone and how it was resolved, without seeking revenge.",
      "Write a paragraph giving your opinion on whether Artemis should be worried about Opal Koboi's plan for revenge."],
  h: ["오팔 코보이가 스스로를 복제해 감옥에서 탈출한 방법을 상상하며 문단으로 써 보세요.",
      "누군가와 다투었지만 복수 대신 화해했던 경험을 문단으로 써 보세요.",
      "아르테미스가 오팔 코보이의 복수 계획을 걱정해야 하는지 여러분의 생각을 문단으로 써 보세요."] };
ACT["S5026"] = { s: "Demons begin appearing on Earth, but even the fairy scientists cannot predict the next one. Artemis Fowl, a teenage criminal mastermind, solves temporal equations and meets a confused and frightened demon that pops up in a Sicilian theatre. Unfortunately, there is a second mysterious party that has also solved the equations.",
  q: ["Write a paragraph imagining how the confused, frightened demon might have felt after suddenly appearing in the Sicilian theatre.",
      "Artemis used his intelligence to solve very difficult equations. Write a paragraph about a difficult problem you solved by thinking hard about it.",
      "Write a paragraph giving your opinion on why it might be dangerous that a second mysterious party has also solved the same equations as Artemis."],
  h: ["시칠리아 극장에 갑자기 나타난 당황하고 겁에 질린 악마의 기분을 상상하며 문단으로 써 보세요.",
      "머리를 써서 어려운 문제를 풀었던 경험을 문단으로 써 보세요.",
      "아르테미스와 같은 방정식을 푼 또 다른 세력이 있다는 것이 왜 위험할 수 있는지 여러분의 생각을 문단으로 써 보세요."] };
ACT["S5027"] = { s: "The Herdman children are notorious for being \"the worst kids in the history of the world.\" This year, they take over the Sunday school Christmas pageant and learn the true meaning of Christmas eventually.",
  q: ["Write a paragraph imagining how the Herdman children might have changed the traditional Christmas pageant.",
      "The Herdmans learned the true meaning of Christmas by taking part in something new. Write a paragraph about a holiday or tradition that taught you something important.",
      "Write a paragraph giving your opinion on why children who are seen as 'the worst kids' ended up learning the true meaning of Christmas."],
  h: ["허드먼 남매가 전통적인 크리스마스 공연을 어떻게 바꾸어 놓았을지 상상하며 문단으로 써 보세요.",
      "명절이나 전통을 통해 중요한 것을 배운 경험을 문단으로 써 보세요.",
      "'가장 나쁜 아이들'이라 불리던 허드먼 남매가 왜 크리스마스의 진짜 의미를 배우게 되었는지 여러분의 생각을 문단으로 써 보세요."] };
ACT["S5028"] = { s: "In The Best School Year Ever, the Herdman children are still the worst kids in the world. One day, the teachers ask all the students to think of compliments for their classmates. When Beth Bradley picks Imogene Herdman's name, she feels that it's impossible to think of anything good. But soon, she begins to see something good about Imogene.",
  q: ["Write a paragraph imagining what good qualities Beth Bradley might have discovered about Imogene Herdman.",
      "Beth had to find something good to say about someone she found difficult. Write a paragraph about a compliment you gave, or could give, to someone you find it hard to get along with.",
      "Write a paragraph giving your opinion on why this activity of finding compliments for classmates might be a good idea for a class to do."],
  h: ["베스 브래들리가 이모진 허드먼에게서 발견했을 좋은 점을 상상하며 문단으로 써 보세요.",
      "친해지기 어려운 사람에게 해 주었거나 해 줄 수 있는 칭찬에 대해 문단으로 써 보세요.",
      "반 친구들에게 칭찬거리를 찾아보게 하는 활동이 좋은 생각인지 여러분의 생각을 문단으로 써 보세요."] };
ACT["S5029"] = { s: "The Herdman children, the worst kids in the world, wreak havoc on the town during Halloween. The helpless mayor decides to cancel Halloween. But what's Halloween without trick-or-treating? The Herdmans attempts to turn the worst Halloween ever into the best one ever.",
  q: ["Write a paragraph imagining how the Herdmans might have tried to turn the worst Halloween ever into the best one ever.",
      "The mayor cancelled Halloween because of trouble in the town. Write a paragraph about a time an event or activity you were looking forward to got cancelled, and how you felt.",
      "Write a paragraph giving your opinion on whether canceling Halloween was a fair solution to the trouble the Herdmans caused."],
  h: ["허드먼 남매가 최악의 할로윈을 최고의 할로윈으로 바꾸려 어떻게 했을지 상상하며 문단으로 써 보세요.",
      "기대하던 행사가 취소되었을 때의 기분을 문단으로 써 보세요.",
      "시장이 할로윈을 취소한 것이 허드먼 남매가 일으킨 소동에 대한 공정한 해결책이었는지 여러분의 생각을 문단으로 써 보세요."] };
ACT["S5030"] = { s: "Ralph runs away looking for freedom but winds up a prisoner at a summer camp.",
  q: ["Write a paragraph imagining what Ralph's journey looking for freedom might have been like before he ended up at the summer camp.",
      "Ralph wanted freedom but ended up somewhere unexpected. Write a paragraph about a time something turned out very differently from what you expected.",
      "Write a paragraph giving your opinion on the irony of Ralph running away for freedom but ending up as a prisoner instead."],
  h: ["랠프가 여름 캠프에 갇히기 전, 자유를 찾아 떠난 여정이 어땠을지 상상하며 문단으로 써 보세요.",
      "예상과 전혀 다르게 흘러갔던 경험을 문단으로 써 보세요.",
      "자유를 찾아 떠난 랠프가 오히려 갇히게 된 것이 왜 아이러니한지 여러분의 생각을 문단으로 써 보세요."] };
ACT["S5031"] = { s: "Ralph makes friends with a boy in room 215 of the Mountain View Inn and discovers the joys of motorcycling.",
  q: ["Write a paragraph imagining what it might feel like for a mouse like Ralph to ride a tiny motorcycle for the first time.",
      "Ralph made an unlikely friend, a boy, who shared something exciting with him. Write a paragraph about a friend who introduced you to something you now enjoy.",
      "Write a paragraph giving your opinion on why an unlikely friendship between a mouse and a boy might be able to work."],
  h: ["랠프 같은 생쥐가 처음으로 작은 오토바이를 탈 때 어떤 기분일지 상상하며 문단으로 써 보세요.",
      "친구가 소개해 준 뒤로 지금까지 좋아하게 된 것에 대해 문단으로 써 보세요.",
      "생쥐와 소년 사이의 뜻밖의 우정이 어떻게 가능했을지 여러분의 생각을 문단으로 써 보세요."] };
ACT["S5032"] = { s: "Ralph, the motorcycle-riding mouse, is off on another adventure and acquires a new sports car to replace his broken motorcycle.",
  q: ["Write a paragraph imagining what adventures Ralph might go on now that he has a new sports car.",
      "Ralph had to replace something broken with something new. Write a paragraph about a time something of yours broke and you got, or wished for, a replacement.",
      "Write a paragraph giving your opinion on whether a sports car or a motorcycle would suit a small mouse like Ralph better."],
  h: ["새 스포츠카를 갖게 된 랠프가 어떤 모험을 떠날지 상상하며 문단으로 써 보세요.",
      "물건이 고장 나서 새것으로 바꾸었거나 바꾸고 싶었던 경험을 문단으로 써 보세요.",
      "작은 생쥐에게는 스포츠카와 오토바이 중 무엇이 더 어울릴지 여러분의 생각을 문단으로 써 보세요."] };
ACT["S5033"] = { s: "In this adventure with Beezus and Ramona, Mr. Quimby loses his job, and the entire family learns to cope with hardship.",
  q: ["Write a paragraph imagining how the Quimby family might have worked together to cope after Mr. Quimby lost his job.",
      "The Quimby family faced hardship together. Write a paragraph about a hard time your family went through together and how you supported each other.",
      "Write a paragraph giving your opinion on what might be the hardest part of a family coping with a parent losing a job."],
  h: ["퀴비 가족이 아버지의 실직 이후 함께 어려움을 헤쳐 나간 모습을 상상하며 문단으로 써 보세요.",
      "여러분의 가족이 함께 힘든 시기를 겪고 서로 도왔던 경험을 문단으로 써 보세요.",
      "부모님이 실직했을 때 가족이 견뎌야 할 가장 힘든 점이 무엇일지 여러분의 생각을 문단으로 써 보세요."] };
ACT["S5034"] = { s: "Now in 3rd grade, Ramona rides the school bus alone and helps around the house while her mother works and her father attends college.",
  q: ["Write a paragraph imagining what it might feel like for Ramona to ride the school bus alone for the first time.",
      "Ramona helps around the house while her parents are busy with work and school. Write a paragraph about a way you help out at home.",
      "Write a paragraph giving your opinion on why it might be important for Ramona to take on more responsibility at this age."],
  h: ["라모나가 처음으로 혼자 스쿨버스를 탔을 때 어떤 기분이었을지 상상하며 문단으로 써 보세요.",
      "여러분이 집안일을 돕는 방법에 대해 문단으로 써 보세요.",
      "이 나이에 라모나가 더 많은 책임을 맡는 것이 왜 중요할지 여러분의 생각을 문단으로 써 보세요."] };
ACT["S5035"] = { s: "A lovable five-year-old girl starts kindergarten with a hilarious series of actions.",
  q: ["Write a paragraph imagining one of the hilarious actions Ramona might have done on her first days of kindergarten.",
      "Ramona started kindergarten, a big new experience. Write a paragraph about your first day at a new school or a new class.",
      "Write a paragraph giving your opinion on why young children like Ramona sometimes act in funny or unexpected ways at school."],
  h: ["라모나가 유치원 첫날에 벌였을 법한 우스운 행동 하나를 상상하며 문단으로 써 보세요.",
      "새 학교나 새 반에서의 첫날에 대해 문단으로 써 보세요.",
      "라모나 같은 어린아이들이 학교에서 가끔 엉뚱하게 행동하는 이유를 여러분의 생각으로 문단으로 써 보세요."] };
ACT["S5036"] = { s: "Henry wants to start a paper route, and he tries everything he can think of to show that he's mature and responsible enough for the job. But in the end, it is Ramona Quimby who shows Mr. Capper his suitability for the job.",
  q: ["Write a paragraph imagining what Henry tried to do to prove he was mature and responsible enough for the paper route.",
      "Henry worked hard to prove himself responsible for a job. Write a paragraph about a time you tried to prove you were ready for a responsibility.",
      "Write a paragraph giving your opinion on why it was surprising, or fitting, that Ramona ended up being the one who convinced Mr. Capper."],
  h: ["헨리가 신문 배달원이 될 만큼 책임감 있다는 것을 보이려고 무엇을 했을지 상상하며 문단으로 써 보세요.",
      "여러분이 책임을 맡을 준비가 되었다는 것을 증명하려 했던 경험을 문단으로 써 보세요.",
      "결국 라모나가 카퍼 아저씨를 설득한 것이 왜 뜻밖이면서도 어울렸는지 여러분의 생각을 문단으로 써 보세요."] };
ACT["S5037"] = { s: "Henry and his friends are building a no-girls-allowed hang-out spot. But Henry finds it challenging to keep gutsy Ramona out of their clubhouse.",
  q: ["Write a paragraph imagining how gutsy Ramona might have tried to get into Henry's no-girls-allowed clubhouse.",
      "Henry made a rule to keep someone out of his clubhouse. Write a paragraph about a rule you or your friends made for a game or a special place, and whether you think it was fair.",
      "Write a paragraph giving your opinion on whether a no-girls-allowed clubhouse rule is a fair rule to have."],
  h: ["당찬 라모나가 남자아이만 들어갈 수 있는 클럽하우스에 들어가려고 어떻게 했을지 상상하며 문단으로 써 보세요.",
      "여러분이나 친구들이 놀이나 특별한 장소를 위해 만든 규칙과 그것이 공정했는지에 대해 문단으로 써 보세요.",
      "여자아이는 안 된다는 클럽하우스 규칙이 공정한 규칙인지 여러분의 생각을 문단으로 써 보세요."] };
ACT["S5038"] = { s: "Ribsy the dog accidentally gets separated from his home, but he spends a fantastic month, even becoming the mascot for a second-grade class.",
  q: ["Write a paragraph imagining how Ribsy became the mascot for a second-grade class during his month away from home.",
      "Ribsy was accidentally separated from his home but had unexpected adventures. Write a paragraph about a time you got lost or separated from someone, even for a short while.",
      "Write a paragraph giving your opinion on whether Ribsy's month away from home turned out to be a good experience for him."],
  h: ["립시가 어떻게 2학년 반의 마스코트가 되었을지 상상하며 문단으로 써 보세요.",
      "여러분이 잠깐이라도 길을 잃거나 누군가와 헤어졌던 경험을 문단으로 써 보세요.",
      "집을 떠나 있던 한 달이 립시에게 결국 좋은 경험이었는지 여러분의 생각을 문단으로 써 보세요."] };
ACT["S5039"] = { s: "Sara Crewe is a pupil at Miss Minchin's London school. She is left in poverty when her father dies. But later, she is rescued by a mysterious benefactor.",
  q: ["Write a paragraph imagining who the mysterious benefactor who rescued Sara Crewe might have been.",
      "Sara went from a wealthy life to poverty and then was helped by someone. Write a paragraph about a time someone helped you get through a hard change in your life.",
      "Write a paragraph giving your opinion on how Sara might have felt about her life changing so suddenly after her father's death."],
  h: ["세라 크루를 구해 준 신비한 후원자가 누구였을지 상상하며 문단으로 써 보세요.",
      "인생의 힘든 변화를 겪을 때 누군가가 도와주었던 경험을 문단으로 써 보세요.",
      "아버지가 돌아가신 뒤 삶이 갑자기 바뀐 것에 대해 세라가 어떤 기분이었을지 여러분의 생각을 문단으로 써 보세요."] };
ACT["S5040"] = { s: "Young Jim Hawkins finds the map to a mysterious treasure and sets sail in search of fortune.",
  q: ["Write a paragraph imagining what dangers Jim Hawkins might have faced while sailing in search of the treasure.",
      "Jim found a map that led him on a big adventure. Write a paragraph about a map, clue, or plan that once led you somewhere interesting.",
      "Write a paragraph giving your opinion on whether searching for treasure at sea would be worth the danger."],
  h: ["짐 호킨스가 보물을 찾아 항해하며 맞닥뜨렸을 위험을 상상하며 문단으로 써 보세요.",
      "지도나 단서, 계획이 여러분을 흥미로운 곳으로 이끌었던 경험을 문단으로 써 보세요.",
      "바다에서 보물을 찾는 것이 그 위험을 감수할 만한 가치가 있을지 여러분의 생각을 문단으로 써 보세요."] };
ACT["S5041"] = { s: "It is a new school year. Greg finds himself thrust into middle school, and hopes he and Rowley, his sidekick, survive as undersized weaklings amid boys who need to shave twice daily. This book is the record of his sixth-grade experiences in his school.",
  q: ["Write a paragraph imagining what Greg's first days in middle school might have been like among much bigger boys.",
      "Greg wrote a diary to record his sixth-grade experiences. Write a paragraph about something you would want to record in a diary about your own school year.",
      "Write a paragraph giving your opinion on why starting middle school might feel scary for someone like Greg."],
  h: ["그렉이 훨씬 큰 형들 사이에서 중학교 첫날을 보내는 모습을 상상하며 문단으로 써 보세요.",
      "여러분이 학교생활에 대해 일기에 남기고 싶은 것을 문단으로 써 보세요.",
      "그렉처럼 중학교에 들어가는 것이 왜 무섭게 느껴질 수 있는지 여러분의 생각을 문단으로 써 보세요."] };
ACT["S5042"] = { s: "In this book, Greg tells about his summer vacation that he wants to keep under wraps. The diary shares his attempts to keep his older brother Rodrick from telling everyone about his most humiliating experience of the summer.",
  q: ["Write a paragraph imagining what Greg's most humiliating experience of the summer might have been.",
      "Greg tried hard to keep an embarrassing secret from getting out. Write a paragraph about a time you wanted to keep something private.",
      "Write a paragraph giving your opinion on whether Rodrick should tell everyone about Greg's humiliating experience or keep it a secret."],
  h: ["그렉의 여름에 있었던 가장 창피한 일이 무엇이었을지 상상하며 문단으로 써 보세요.",
      "여러분이 비밀로 하고 싶었던 일이 있었던 경험을 문단으로 써 보세요.",
      "로드릭이 그렉의 창피한 일을 모두에게 말해야 할지, 비밀로 지켜야 할지 여러분의 생각을 문단으로 써 보세요."] };
ACT["S5043"] = { s: "His father wants Greg to be tough. He even threatens Greg to go to military school. Greg realizes he has to shape up or get shipped out.",
  q: ["Write a paragraph imagining what Greg might do to try to 'shape up' and avoid being sent to military school.",
      "Greg's father wanted him to change his behavior. Write a paragraph about a time a parent or adult asked you to change something about how you act.",
      "Write a paragraph giving your opinion on whether threatening military school is a good way to help Greg become tougher."],
  h: ["군사학교에 가지 않으려고 그렉이 '정신 차리기' 위해 무엇을 했을지 상상하며 문단으로 써 보세요.",
      "부모님이나 어른이 여러분의 행동을 바꾸라고 했던 경험을 문단으로 써 보세요.",
      "군사학교로 위협하는 것이 그렉을 강하게 만드는 좋은 방법인지 여러분의 생각을 문단으로 써 보세요."] };
ACT["S5044"] = { s: "In this diary, Greg records his attempts to spend his summer vacation sensibly indoors, playing video games and watching television. But Greg's mom has a different vision for an ideal summer. Whose vision will win out at last?",
  q: ["Write a paragraph imagining how Greg's mom's idea of an ideal summer might be different from his own.",
      "Greg and his mom disagreed about how to spend the summer. Write a paragraph about a time you and a parent disagreed about how to spend your free time.",
      "Write a paragraph giving your opinion on whose vision for summer, Greg's or his mom's, you think is better, and why."],
  h: ["그렉 엄마가 생각하는 이상적인 여름이 그렉과 어떻게 달랐을지 상상하며 문단으로 써 보세요.",
      "여러분과 부모님이 자유 시간을 어떻게 보낼지 의견이 달랐던 경험을 문단으로 써 보세요.",
      "그렉과 엄마 중 누구의 여름 계획이 더 낫다고 생각하는지 여러분의 생각을 문단으로 써 보세요."] };
ACT["S5045"] = { s: "This book describes the triumphs and tragedies of the courageous explorers of the Antarctic.",
  q: ["Choose one triumph or one tragedy this book might describe about Antarctic explorers, and write a paragraph imagining what happened.",
      "Write a paragraph about a time you had to be brave to do something difficult, like the explorers in this book.",
      "Write a paragraph giving your opinion on why exploring a place as dangerous as Antarctica might be worth the risk."],
  h: ["남극 탐험가들의 승리나 비극 중 하나를 골라 무슨 일이 있었을지 상상하며 문단으로 써 보세요.",
      "탐험가들처럼 어려운 일을 하려고 용기를 냈던 경험을 문단으로 써 보세요.",
      "남극처럼 위험한 곳을 탐험하는 것이 그만한 가치가 있을지 여러분의 생각을 문단으로 써 보세요."] };
ACT["S5046"] = { s: "This book introduces the amazing discoveries of the earliest fossil hunters and modern-day geologists who track dinosaurs.",
  q: ["Write a paragraph imagining what an amazing discovery made by an early fossil hunter might have looked like.",
      "Write a paragraph about a time you were curious enough about something to investigate or search for answers, like a fossil hunter.",
      "Write a paragraph giving your opinion on why studying dinosaur fossils is still important today."],
  h: ["초기 화석 사냥꾼이 이루어 냈을 놀라운 발견을 상상하며 문단으로 써 보세요.",
      "화석 사냥꾼처럼 무언가가 궁금해서 직접 조사하거나 찾아본 경험을 문단으로 써 보세요.",
      "공룡 화석을 연구하는 것이 오늘날에도 중요한 이유를 여러분의 생각으로 문단으로 써 보세요."] };
ACT["S5047"] = { s: "Orville and Wilbur Wright, fascinated by all kinds of vehicles, dream of flying in the air.",
  q: ["Write a paragraph imagining what it might have felt like for the Wright brothers to dream of flying before anyone had ever done it.",
      "Write a paragraph about something you dream of doing or achieving, the way the Wright brothers dreamed of flight.",
      "Write a paragraph giving your opinion on why the Wright brothers' fascination with vehicles might have helped them dream of flying."],
  h: ["아무도 하늘을 난 적 없던 시절, 라이트 형제가 비행을 꿈꾸던 기분이 어땠을지 상상하며 문단으로 써 보세요.",
      "라이트 형제처럼 여러분이 꿈꾸는 일이나 이루고 싶은 것에 대해 문단으로 써 보세요.",
      "여러 탈것에 대한 관심이 라이트 형제의 비행에 대한 꿈에 어떻게 도움이 되었을지 여러분의 생각을 문단으로 써 보세요."] };
ACT["S5048"] = { s: "This book introduces how Ancient Egyptians preserved dead bodies to mummify.",
  q: ["Write a paragraph imagining the process Ancient Egyptians might have used to preserve a body as a mummy.",
      "Write a paragraph about another ancient culture or tradition you have learned about and found interesting.",
      "Write a paragraph giving your opinion on why Ancient Egyptians thought it was important to preserve dead bodies this way."],
  h: ["고대 이집트인들이 시신을 미라로 보존한 과정을 상상하며 문단으로 써 보세요.",
      "여러분이 흥미롭다고 느낀 다른 고대 문화나 전통에 대해 문단으로 써 보세요.",
      "고대 이집트인들이 시신을 이런 방식으로 보존하는 것을 왜 중요하게 여겼는지 여러분의 생각을 문단으로 써 보세요."] };
ACT["S5049"] = { s: "This book introduces chocolate from its raw state in cacao trees to candy bars.",
  q: ["Write a paragraph imagining the steps chocolate goes through changing from cacao trees to candy bars.",
      "Write a paragraph about your favorite way to eat chocolate, or a memory you have involving chocolate.",
      "Write a paragraph giving your opinion on which part of turning cacao into chocolate seems the most surprising or difficult."],
  h: ["초콜릿이 카카오나무에서 초콜릿 바가 되기까지 거치는 과정을 상상하며 문단으로 써 보세요.",
      "여러분이 초콜릿을 즐겨 먹는 방법이나 초콜릿에 얽힌 기억을 문단으로 써 보세요.",
      "카카오가 초콜릿으로 바뀌는 과정 중 어떤 부분이 가장 놀랍거나 어려워 보이는지 여러분의 생각을 문단으로 써 보세요."] };
ACT["S5050"] = { s: "Coraline enters a mysterious door into a world that is similar, yet different from her own, where she must challenge a gruesome entity in order to save herself, her family, and the souls of three others.",
  q: ["Write a paragraph imagining what the world behind the mysterious door might look like, similar yet different from Coraline's own world.",
      "Coraline had to be brave to save her family. Write a paragraph about a time you had to be brave to protect someone you love.",
      "Write a paragraph giving your opinion on why Coraline decided to challenge the gruesome entity instead of running away."],
  h: ["그 신비한 문 너머, 코렐라인의 세계와 비슷하지만 다른 세계가 어떤 모습일지 상상하며 문단으로 써 보세요.",
      "여러분이 사랑하는 사람을 지키기 위해 용기를 냈던 경험을 문단으로 써 보세요.",
      "코렐라인이 도망치지 않고 그 끔찍한 존재에게 맞서기로 한 이유를 여러분의 생각으로 문단으로 써 보세요."] };
ACT["S5054"] = { s: "This book introduces hundreds of facts about the fifty states of the United States of America.",
  q: ["Choose one U.S. state you are curious about and write a paragraph imagining a fact this book might tell about it.",
      "Write a paragraph about a state or place in the world you would like to visit, and why.",
      "Write a paragraph giving your opinion on why it might be useful to learn facts about all fifty states."],
  h: ["궁금한 미국의 주 하나를 골라 이 책이 알려 줄 법한 사실을 상상하며 문단으로 써 보세요.",
      "여러분이 가 보고 싶은 주나 장소에 대해 그 이유와 함께 문단으로 써 보세요.",
      "쉰 개 주의 사실을 모두 배우는 것이 왜 유용할지 여러분의 생각을 문단으로 써 보세요."] };
ACT["S5055"] = { s: "This book describes the Pilgrim's journey to America on the Mayflower and their life in the colony of New Plymouth.",
  q: ["Write a paragraph imagining what the Pilgrims' journey to America on the Mayflower might have been like.",
      "The Pilgrims built a new life in a difficult, unfamiliar place. Write a paragraph about a time you had to adjust to a new or unfamiliar place.",
      "Write a paragraph giving your opinion on what might have been the hardest part of starting a new colony like New Plymouth."],
  h: ["청교도들이 메이플라워호를 타고 미국으로 떠난 여정이 어땠을지 상상하며 문단으로 써 보세요.",
      "낯설고 어려운 곳에 적응해야 했던 경험을 문단으로 써 보세요.",
      "새 플리머스 같은 새로운 마을을 세우는 데 가장 힘든 점이 무엇이었을지 여러분의 생각을 문단으로 써 보세요."] };
ACT["S5056"] = { s: "This book introduces some facts about each U.S. president, including their inaugurations and significant political achievements.",
  q: ["Choose one part of a president's story, like an inauguration or achievement, and write a paragraph imagining what this book might describe.",
      "Write a paragraph about a leader, in your school, family, or community, whom you admire, and why.",
      "Write a paragraph giving your opinion on what makes a president's achievement significant."],
  h: ["대통령의 취임식이나 업적 중 하나를 골라 이 책이 무엇을 설명할지 상상하며 문단으로 써 보세요.",
      "학교나 가족, 지역 사회에서 존경하는 지도자에 대해 그 이유와 함께 문단으로 써 보세요.",
      "대통령의 어떤 업적이 의미 있게 만드는지 여러분의 생각을 문단으로 써 보세요."] };
ACT["S5057"] = { s: "This book explains what makes each planet unique and why Earth stands apart from the other planets.",
  q: ["Based on what you already know, write a paragraph imagining what makes one planet in our solar system unique.",
      "Write a paragraph about the planet or part of space you find most interesting and why.",
      "Write a paragraph giving your opinion on why Earth stands apart from the other planets in our solar system."],
  h: ["이미 알고 있는 것을 바탕으로, 태양계의 한 행성을 특별하게 만드는 점을 상상하며 문단으로 써 보세요.",
      "여러분이 가장 흥미롭게 느끼는 행성이나 우주의 한 부분에 대해 문단으로 써 보세요.",
      "지구가 다른 행성들과 다른 이유를 여러분의 생각으로 문단으로 써 보세요."] };
ACT["S5058"] = { s: "Stuart Little is a tiny mouse adopted by a human family. When his best friend, a beautiful little bird named Margalo, disappears from her nest, he sets out on an adventure and tracks her down.",
  q: ["Write a paragraph imagining the adventure Stuart Little went on to track down his missing friend Margalo.",
      "Write a paragraph about a time you missed a friend who moved away or was gone for a while.",
      "Write a paragraph giving your opinion on why Stuart was so determined to find Margalo even though the search would be difficult."],
  h: ["스튜어트 리틀이 사라진 친구 마갈로를 찾아 떠난 모험을 상상하며 문단으로 써 보세요.",
      "멀리 이사 가거나 한동안 못 본 친구가 그리웠던 경험을 문단으로 써 보세요.",
      "찾기 힘들 것을 알면서도 스튜어트가 마갈로를 그렇게 열심히 찾은 이유를 여러분의 생각으로 문단으로 써 보세요."] };
ACT["S5061"] = { s: "Jane, Mark, Katharine, and Martha are stuck to spend their summer in a city apartment. But after Jane discovers an ancient coin that seems to grant wishes, they find themselves involved in a series of fantastic adventures.",
  q: ["Write a paragraph imagining one of the fantastic adventures the four children had because of the magic coin.",
      "Write a paragraph about a time an ordinary day suddenly became exciting.",
      "Write a paragraph giving your opinion on whether finding a wish-granting coin would be more exciting or more dangerous."],
  h: ["마법의 동전 덕분에 네 아이가 겪은 환상적인 모험 하나를 상상하며 문단으로 써 보세요.",
      "평범했던 하루가 갑자기 신나는 하루로 바뀐 경험을 문단으로 써 보세요.",
      "소원을 들어주는 동전을 발견하는 것이 더 신날지, 더 위험할지 여러분의 생각을 문단으로 써 보세요."] };
ACT["S5063"] = { s: "After Mark captures an ancient turtle that seems to have extraordinary powers, the four children find themselves overwhelmed with magical adventures. Will they learn to handle the magic and find a treasure to save their wonderful new stepfather's bookstore?",
  q: ["Write a paragraph imagining how the four children might use the ancient turtle's powers to find treasure and save the bookstore.",
      "Write a paragraph about a time you wanted to help someone in your family save or fix something important to them.",
      "Write a paragraph giving your opinion on whether magic is a good way to solve a real problem like saving a bookstore."],
  h: ["네 아이가 고대 거북의 힘을 이용해 보물을 찾고 서점을 구하는 모습을 상상하며 문단으로 써 보세요.",
      "가족에게 소중한 것을 구하거나 고치도록 돕고 싶었던 경험을 문단으로 써 보세요.",
      "마법이 서점을 구하는 것 같은 실제 문제를 해결하는 좋은 방법인지 여러분의 생각을 문단으로 써 보세요."] };
ACT["S5064"] = { s: "When the Baudelaire orphans are sent to live and work in a sinister lumbermill, accidents and general misfortune abound. Book #4",
  q: ["Write a paragraph imagining the accidents and misfortune the Baudelaire orphans faced at the sinister lumbermill.",
      "Write a paragraph about a time you had to work through a string of bad luck or one problem after another.",
      "Write a paragraph giving your opinion on why sending orphans to work at a mill seems unfair or dangerous."],
  h: ["보들레르 남매가 그 음산한 제재소에서 겪은 사고와 불운을 상상하며 문단으로 써 보세요.",
      "안 좋은 일이 연달아 일어나는 것을 겪어 낸 경험을 문단으로 써 보세요.",
      "고아들을 제재소로 보내 일을 시키는 것이 왜 부당하거나 위험해 보이는지 여러분의 생각을 문단으로 써 보세요."] };
ACT["S5066"] = { s: "Ginger Pye, who Jerry bought for a hard-earned dollar, is the most famous pup in Cranbury. Ginger is intellectual, loyal, and adorable. One day, someone steals him from the Pye family, and a mysterious man in a mustard yellow hat brings excitement to the Pye children.",
  q: ["Write a paragraph imagining who the mysterious man in the mustard yellow hat might be and why he took Ginger.",
      "Jerry worked hard to earn the dollar to buy Ginger Pye. Write a paragraph about something you saved money for or worked hard to earn.",
      "Write a paragraph giving your opinion on how the Pye children might have felt when their beloved dog Ginger was stolen."],
  h: ["겨자색 모자를 쓴 그 수상한 남자가 누구이고 왜 진저를 데려갔을지 상상하며 문단으로 써 보세요.",
      "여러분이 돈을 모으거나 열심히 벌어서 무언가를 산 경험을 문단으로 써 보세요.",
      "사랑하는 개 진저를 도둑맞았을 때 파이 가족 아이들이 어떤 기분이었을지 여러분의 생각을 문단으로 써 보세요."] };
ACT["S5068"] = { s: "Her classmates ridicule a Polish girl named Wanda for wearing the same faded blue dress every day. She claims that she has one hundred dresses at home, but no one believes her. When Wanda moves to another town and gets pulled out of the school, the class feels terrible and realizes it's too late for apologies.",
  q: ["Write a paragraph imagining why Wanda might have claimed to have one hundred dresses at home.",
      "The classmates felt terrible after Wanda left, realizing it was too late to apologize. Write a paragraph about a time you wished you had apologized to someone sooner.",
      "Write a paragraph giving your opinion on why the classmates ridiculed Wanda for wearing the same dress every day."],
  h: ["완다가 집에 드레스가 백 벌 있다고 말한 이유를 상상하며 문단으로 써 보세요.",
      "누군가에게 좀 더 일찍 사과했더라면 좋았을 경험을 문단으로 써 보세요.",
      "반 친구들이 완다가 매일 같은 옷을 입는다고 놀린 이유를 여러분의 생각으로 문단으로 써 보세요."] };
ACT["S5069"] = { s: "Two real little girls, who love to draw witches, build an elaborate world around the imaginary Old Witch and her family. The girls and the witch family blend the worlds of reality and imagination.",
  q: ["Write a paragraph imagining the elaborate world the two girls built around the imaginary Old Witch and her family.",
      "The girls used drawing to build an imaginary world. Write a paragraph about an imaginary world or story you have created through drawing, play, or writing.",
      "Write a paragraph giving your opinion on why it might be fun to blend reality and imagination the way these girls did."],
  h: ["두 소녀가 상상 속 마녀 가족을 중심으로 만든 정교한 세계를 상상하며 문단으로 써 보세요.",
      "그림이나 놀이, 글쓰기로 만들어 본 상상의 세계나 이야기에 대해 문단으로 써 보세요.",
      "이 소녀들처럼 현실과 상상을 섞는 것이 왜 재미있을지 여러분의 생각을 문단으로 써 보세요."] };
ACT["S5070"] = { s: "The city of Ember, built as a last refuge for the human race, is losing its great lamps that light the whole city. Twelve-year-old Lina finds part of an ancient message that holds a secret to save the city, and races to figure out the clues to keep the lights on.",
  q: ["Write a paragraph imagining what might happen to the city of Ember if Lina cannot figure out the clues in time.",
      "Lina had to race against time to solve an ancient message. Write a paragraph about a time you had to solve something quickly under pressure.",
      "Write a paragraph giving your opinion on why it was so important for the city of Ember to keep its lights on."],
  h: ["리나가 단서를 제때 풀지 못한다면 엠버시에 무슨 일이 벌어질지 상상하며 문단으로 써 보세요.",
      "무언가를 빨리 풀어야 했던 긴박한 경험을 문단으로 써 보세요.",
      "엠버시의 불을 계속 켜 두는 것이 왜 그렇게 중요했는지 여러분의 생각을 문단으로 써 보세요."] };
ACT["S5071"] = { s: "Franny K. Stein, a mad scientist, prefers all things spooky and creepy, and everyone in her class thinks she's wacky and weird. Tired of being stared at, she experiments with fitting in. But when a monster erupts from the trash can, everyone knows it's up to the mad scientist to save the day. Book #1",
  q: ["Write a paragraph imagining how Franny used her mad scientist skills to save the day when the monster erupted from the trash can.",
      "Franny felt tired of being stared at for being different, then tried to fit in. Write a paragraph about a time you wanted to fit in, or a time you were proud to be different.",
      "Write a paragraph giving your opinion on whether Franny should try to fit in or stay true to being herself."],
  h: ["쓰레기통에서 튀어나온 괴물을 프래니가 미친 과학자의 솜씨로 어떻게 물리쳤을지 상상하며 문단으로 써 보세요.",
      "남들과 어울리고 싶었던 경험이나, 남과 달라서 자랑스러웠던 경험을 문단으로 써 보세요.",
      "프래니가 남들과 어울리려 애써야 할지, 원래 모습 그대로여야 할지 여러분의 생각을 문단으로 써 보세요."] };
ACT["S5072"] = { s: "Franny makes it her mission to help her classmates discover their own inner mad scientists. But when she creates a robot to show them the joys of science, things don't always turn out as expected. She ends up learning something else from them instead. Book #3",
  q: ["Write a paragraph imagining what might have gone unexpectedly when Franny's robot was supposed to show her classmates the joys of science.",
      "Franny ended up learning something from her classmates instead of just teaching them. Write a paragraph about a time you learned something unexpected from someone you were trying to help.",
      "Write a paragraph giving your opinion on whether Franny's plan to help her classmates discover their inner mad scientists was a good idea."],
  h: ["친구들에게 과학의 즐거움을 보여 주려던 프래니의 로봇에게 예상 밖으로 무슨 일이 일어났을지 상상하며 문단으로 써 보세요.",
      "누군가를 도우려다가 오히려 그 사람에게서 뜻밖의 것을 배운 경험을 문단으로 써 보세요.",
      "반 친구들이 자기 안의 '미친 과학자'를 발견하도록 돕겠다는 프래니의 계획이 좋은 생각이었는지 여러분의 생각을 문단으로 써 보세요."] };
ACT["S5073"] = { s: "In the author's book Hatchet, Brian was rescued at the end of the summer from the Canadian Wilderness. But what would have happened if Brian hadn't been rescued? This book describes Brian's struggle to survive a winter in the wilderness with only his survival pack and hatchet.",
  q: ["Write a paragraph imagining how Brian might have struggled to survive a winter in the wilderness with only his survival pack and hatchet.",
      "Brian had to survive with very few tools. Write a paragraph about a time you had to solve a problem with very limited tools or help.",
      "Write a paragraph giving your opinion on what would be the hardest part of surviving alone in the wilderness through winter."],
  h: ["생존 배낭과 손도끼만 가지고 겨울 숲에서 살아남으려 애쓴 브라이언의 모습을 상상하며 문단으로 써 보세요.",
      "아주 적은 도구로 문제를 해결해야 했던 경험을 문단으로 써 보세요.",
      "겨울 숲에서 홀로 살아남는 것 중 가장 힘든 부분이 무엇일지 여러분의 생각을 문단으로 써 보세요."] };
ACT["S5074"] = { s: "Thirteen-year-old Brian Robeson travels to Canada by plane to visit his father for the first time since the divorce. When the plane crashes, the sole survivor Brian spends 54 days in the wilderness with nothing but his clothing, a tattered windbreaker, and the hatchet.",
  q: ["Write a paragraph imagining Brian's first day alone in the wilderness after the plane crash.",
      "Brian was flying to visit his father for the first time since his parents' divorce. Write a paragraph about a time you visited or reconnected with a family member after being apart.",
      "Write a paragraph giving your opinion on what skill you think would be most important for surviving 54 days in the wilderness."],
  h: ["비행기 사고 후 홀로 남겨진 브라이언의 숲속 첫날을 상상하며 문단으로 써 보세요.",
      "부모님이 이혼한 뒤 가족을 다시 만나거나 오랜만에 함께한 경험을 문단으로 써 보세요.",
      "숲에서 54일을 살아남는 데 가장 중요한 기술이 무엇이라고 생각하는지 여러분의 생각을 문단으로 써 보세요."] };
ACT["S5076"] = { s: "Brian, the sole survivor of the plane crash, is asked to undergo a similar experience by the government to help scientists learn more about the psychology of survival.",
  q: ["Write a paragraph imagining how Brian might have felt about being asked to relive his survival experience for scientists.",
      "Write a paragraph about a time you had to relive or talk about a difficult experience to help someone else understand it.",
      "Write a paragraph giving your opinion on whether it was fair to ask Brian to go through a similar dangerous experience again."],
  h: ["과학자들을 위해 생존 경험을 다시 겪어야 한다는 말을 들었을 때 브라이언이 어떤 기분이었을지 상상하며 문단으로 써 보세요.",
      "다른 사람이 이해하도록 힘든 경험을 다시 이야기해야 했던 경험을 문단으로 써 보세요.",
      "브라이언에게 비슷한 위험한 경험을 다시 겪게 한 것이 공정했는지 여러분의 생각을 문단으로 써 보세요."] };
ACT["S5077"] = { s: "This story is about dogsledding adventures, capped by the story of the author's first Iditarod, an annual sled dog race held in Alaska, USA.",
  q: ["Write a paragraph imagining what the author's first Iditarod race across Alaska might have been like.",
      "Write a paragraph about an adventure with animals, like dogsledding, that you have had or would like to try.",
      "Write a paragraph giving your opinion on what might make racing sled dogs across Alaska so challenging."],
  h: ["작가가 처음 참가한 아이디타로드, 알래스카를 가로지르는 그 경주가 어땠을지 상상하며 문단으로 써 보세요.",
      "개썰매처럼 동물과 함께한 모험이나 해 보고 싶은 모험에 대해 문단으로 써 보세요.",
      "알래스카를 가로지르며 썰매개들과 경주하는 것이 왜 그렇게 힘들지 여러분의 생각을 문단으로 써 보세요."] };
ACT["S5078"] = { s: "For in Harry's second year at Hogwarts, fresh torments and horrors arise. The worst one happens when the Chamber of Secrets gets opened again at Hogwarts School, and Harry Potter finds a dark power turning Hogwarts students to stone. Book #2",
  q: ["Write a paragraph imagining what it would be like to discover a dark power turning students to stone at your school.",
      "Write a paragraph about a time something frightening or mysterious happened at your own school.",
      "Write a paragraph giving your opinion on why the reopening of the Chamber of Secrets might be the worst horror of Harry's second year."],
  h: ["학교에서 학생들을 돌로 만드는 어둠의 힘을 발견한다면 어떤 기분일지 상상하며 문단으로 써 보세요.",
      "여러분의 학교에서 있었던 무섭거나 신비로운 일에 대해 문단으로 써 보세요.",
      "비밀의 방이 다시 열린 것이 해리의 2학년 중 최악의 공포였던 이유를 여러분의 생각으로 문단으로 써 보세요."] };
ACT["S5079"] = { s: "Harry Potter leaves his most loyal friends behind and begins a final perilous journey. He realizes the only solution to free himself and overcome the Dark Lord's forces of evil is destroying Voldemort's remaining Horcruxes. Book #7",
  q: ["Write a paragraph imagining Harry's feelings as he left his most loyal friends behind to begin this final, perilous journey.",
      "Write a paragraph about a difficult journey or challenge you had to face mostly on your own.",
      "Write a paragraph giving your opinion on why destroying all the Horcruxes was the only way for Harry to defeat Voldemort's forces."],
  h: ["가장 믿었던 친구들을 뒤로하고 마지막 위험한 여정을 떠나는 해리의 기분을 상상하며 문단으로 써 보세요.",
      "거의 혼자서 마주해야 했던 힘든 여정이나 도전에 대해 문단으로 써 보세요.",
      "볼드모트를 이기려면 모든 호크룩스를 없애는 것이 왜 유일한 방법이었는지 여러분의 생각을 문단으로 써 보세요."] };
ACT["S5080"] = { s: "In this fourth novel of the Harry Potter Series, Harry returns to Hogwarts for his fourth year. He is picked by the Goblet of Fire, the magical cup, to enter the death-defying competition held at Hogwarts this year. Book #4",
  q: ["Write a paragraph imagining the death-defying competition Harry was chosen to enter by the Goblet of Fire.",
      "Write a paragraph about a competition you took part in, even if you did not expect to be chosen for it.",
      "Write a paragraph giving your opinion on whether it is fair for a magical cup to choose someone for such a dangerous competition."],
  h: ["불의 잔이 해리를 선택한 죽음을 무릅쓴 그 대회가 어땠을지 상상하며 문단으로 써 보세요.",
      "선택될 거라 기대하지 않았는데도 참가했던 대회에 대해 문단으로 써 보세요.",
      "마법의 잔이 그렇게 위험한 대회에 누군가를 선택하는 것이 공정한지 여러분의 생각을 문단으로 써 보세요."] };
ACT["S5081"] = { s: "In his sixth year at Hogwarts, Harry Potter searches for the secret and complex story of the boy who became Lord Voldemort. Professor Dumbledore prepares Harry to find the vulnerability of this sinister magician and face his destiny. Book #6",
  q: ["Write a paragraph imagining what Harry might have learned about the story of the boy who became Lord Voldemort.",
      "Write a paragraph about a mentor or teacher who has prepared you to face something difficult, the way Dumbledore prepared Harry.",
      "Write a paragraph giving your opinion on why understanding Voldemort's past might help Harry find his vulnerability."],
  h: ["볼드모트가 된 소년의 이야기에 대해 해리가 알게 되었을 내용을 상상하며 문단으로 써 보세요.",
      "덤블도어가 해리를 준비시킨 것처럼, 힘든 일에 대비하도록 도와준 스승이나 선생님에 대해 문단으로 써 보세요.",
      "볼드모트의 과거를 이해하는 것이 해리가 그의 약점을 찾는 데 어떻게 도움이 될지 여러분의 생각을 문단으로 써 보세요."] };
ACT["S5082"] = { s: "Fifteen-year-old wizard Harry Potter suspects that Voldemort is gathering an army. He also discovers that Dumbledore is regrouping the Order of the Phoenix - a secret society first formed years ago to fight Voldemort. Book #5",
  q: ["Write a paragraph imagining what it would be like to discover a secret society like the Order of the Phoenix.",
      "Write a paragraph about a time you suspected something was wrong before anyone else believed you.",
      "Write a paragraph giving your opinion on why it might be important to regroup an old secret society to fight a returning danger."],
  h: ["불사조 기사단 같은 비밀 단체를 발견한다면 어떤 기분일지 상상하며 문단으로 써 보세요.",
      "남들이 믿기 전에 무언가 잘못되었다고 먼저 의심했던 경험을 문단으로 써 보세요.",
      "돌아온 위험에 맞서기 위해 오래된 비밀 단체를 다시 모으는 것이 왜 중요할지 여러분의 생각을 문단으로 써 보세요."] };
ACT["S5083"] = { s: "Harry and his best friends go back for their third year at Hogwarts and hear that a mass murderer is on the loose. The sinister guards of Azkaban, called in to guard the school, terrorize the students. Book #3",
  q: ["Write a paragraph imagining how the sinister guards of Azkaban might have terrorized the students at Hogwarts.",
      "Write a paragraph about a time a rule or a person meant to protect you actually made you feel more scared.",
      "Write a paragraph giving your opinion on whether bringing the guards of Azkaban to guard the school was a good decision."],
  h: ["아즈카반의 섬뜩한 간수들이 학생들을 어떻게 두렵게 했을지 상상하며 문단으로 써 보세요.",
      "나를 지켜 주려던 규칙이나 사람이 오히려 더 무섭게 느껴졌던 경험을 문단으로 써 보세요.",
      "학교를 지키려고 아즈카반의 간수들을 데려온 것이 좋은 결정이었는지 여러분의 생각을 문단으로 써 보세요."] };
ACT["S5084"] = { s: "After being rescued from the outrageous neglect of his aunt and uncle, a young boy named Harry Potter proves his worth while attending Hogwarts School of Witchcraft and Wizardry. Book #1",
  q: ["Write a paragraph imagining how Harry proved his worth after arriving at Hogwarts School of Witchcraft and Wizardry.",
      "Write a paragraph about a time you had to prove yourself in a brand new place, like Harry did at Hogwarts.",
      "Write a paragraph giving your opinion on how being neglected by his aunt and uncle might have affected Harry's feelings when he first arrived at Hogwarts."],
  h: ["해리가 호그와트에 도착한 뒤 자신의 가치를 증명한 방법을 상상하며 문단으로 써 보세요.",
      "해리처럼 완전히 새로운 곳에서 자신을 증명해야 했던 경험을 문단으로 써 보세요.",
      "이모와 이모부에게 방치되었던 것이 호그와트에 처음 도착했을 때 해리의 마음에 어떤 영향을 주었을지 여러분의 생각을 문단으로 써 보세요."] };
ACT["S5085"] = { s: "This book follows the adventures of Hiccup Horrendous Haddock the Third, the quiet and thoughtful son of the Chief of the Hairy Hooligans, as he tries to pass an important initiation test by catching and training a dragon. Book #1",
  q: ["Write a paragraph imagining how Hiccup, being quiet and thoughtful, might have approached catching and training his dragon differently from the other Vikings.",
      "Write a paragraph about an important test you had to pass, and how you prepared for it.",
      "Write a paragraph giving your opinion on whether being quiet and thoughtful helps or hurts Hiccup in a Viking initiation test."],
  h: ["조용하고 생각이 깊은 히컵이 다른 바이킹들과는 다르게 용을 잡고 길들이려 한 방법을 상상하며 문단으로 써 보세요.",
      "여러분이 치러야 했던 중요한 시험과 그것을 어떻게 준비했는지 문단으로 써 보세요.",
      "조용하고 생각이 깊은 성격이 바이킹의 입단 시험에서 히컵에게 도움이 될지 방해가 될지 여러분의 생각을 문단으로 써 보세요."] };
ACT["S5086"] = { s: "This book chronicles the further adventures and misadventures of Hiccup Horrendous Haddock the Third as he continues his Viking training and discovers a riddle that will lead to the treasures of the world's greatest pirate. Book #2",
  q: ["Write a paragraph imagining the riddle Hiccup discovered that leads to the greatest pirate's treasure.",
      "Write a paragraph about a riddle or puzzle you enjoyed trying to solve.",
      "Write a paragraph giving your opinion on what kind of treasure you imagine the world's greatest pirate might have hidden."],
  h: ["세상에서 가장 위대한 해적의 보물로 이어지는, 히컵이 발견한 수수께끼를 상상하며 문단으로 써 보세요.",
      "풀면서 즐거웠던 수수께끼나 퍼즐에 대해 문단으로 써 보세요.",
      "세상에서 가장 위대한 해적이 숨겼을 법한 보물이 어떤 것일지 여러분의 생각을 문단으로 써 보세요."] };
ACT["S5087"] = { s: "This book narrates the further escapades of Hiccup Horrendous Haddock the Third as his Viking training continues. During the training, he accidentally boards a Roman galley and uncovers a plot to steal every dragon on the Isle of Berk. Will he escape from a boatload of Roman soldiers and rescue his kidnapped dragon? Book #3",
  q: ["Write a paragraph imagining how Hiccup might escape from the boatload of Roman soldiers to rescue his kidnapped dragon.",
      "Write a paragraph about a time you accidentally found yourself somewhere you did not expect to be, like Hiccup boarding the Roman galley.",
      "Write a paragraph giving your opinion on why someone might want to steal every dragon on the Isle of Berk."],
  h: ["히컵이 로마 병사들에게서 도망쳐 납치된 용을 구하는 모습을 상상하며 문단으로 써 보세요.",
      "히컵이 로마 갤리선에 우연히 올라탄 것처럼, 예상치 못한 곳에 있게 되었던 경험을 문단으로 써 보세요.",
      "누군가가 버크섬의 모든 용을 훔치려 한 이유를 여러분의 생각으로 문단으로 써 보세요."] };
ACT["S5088"] = { s: "In the ruins of a place once known as North America lies the nation called Panem. Its rulers maintain control through an annual survival competition, the Hunger Games. When her little sister is forced to participate in the game, 16-year-old Katniss voluntarily takes her sister's place. Book #1",
  q: ["Write a paragraph imagining what went through Katniss's mind the moment she volunteered to take her sister's place.",
      "Write a paragraph about a time you volunteered to do something difficult in place of someone you care about.",
      "Write a paragraph giving your opinion on why the rulers of Panem might use a survival competition to maintain control."],
  h: ["캣니스가 동생 대신 자원하기로 한 그 순간 무슨 생각이 들었을지 상상하며 문단으로 써 보세요.",
      "소중한 사람을 위해 힘든 일을 대신하겠다고 나섰던 경험을 문단으로 써 보세요.",
      "판엠의 지배자들이 생존 대회로 사람들을 통제하려 한 이유를 여러분의 생각으로 문단으로 써 보세요."] };
ACT["S5089"] = { s: "District 12 tributes Katniss and Peeta have secured a life of safety by winning the Hunger Games. But when they inadvertently become the faces of an impending rebellion, the Capitol gets angry and wants revenge. Book #2",
  q: ["Write a paragraph imagining how Katniss and Peeta might have accidentally become the faces of a rebellion.",
      "Write a paragraph about a time you did something small that had a much bigger effect than you expected, like Katniss and Peeta.",
      "Write a paragraph giving your opinion on whether the Capitol's anger and desire for revenge against Katniss and Peeta was reasonable."],
  h: ["캣니스와 피타가 뜻하지 않게 반란의 얼굴이 된 과정을 상상하며 문단으로 써 보세요.",
      "작은 행동이 캣니스와 피타처럼 생각보다 훨씬 큰 영향을 준 경험을 문단으로 써 보세요.",
      "캐피톨이 캣니스와 피타에게 화가 나서 복수하려 한 것이 타당했는지 여러분의 생각을 문단으로 써 보세요."] };
ACT["S5090"] = { s: "In this final book in The Hunger Games trilogy, District 13 plots to overthrow the Capitol, and the rebellion's success is up to Katniss's willingness to change the future of Panem. Book #3",
  q: ["Write a paragraph imagining what Katniss might have had to do to help change the future of Panem.",
      "Write a paragraph about a time you were part of a bigger group working toward a shared goal, like the rebellion in District 13.",
      "Write a paragraph giving your opinion on how much responsibility one person, like Katniss, should have for the success of a whole rebellion."],
  h: ["판엠의 미래를 바꾸기 위해 캣니스가 해야 했을 일을 상상하며 문단으로 써 보세요.",
      "13구역의 반란처럼, 더 큰 집단의 목표를 위해 함께했던 경험을 문단으로 써 보세요.",
      "캣니스 한 사람이 반란 전체의 성공에 얼마나 큰 책임을 져야 하는지 여러분의 생각을 문단으로 써 보세요."] };
ACT["S5092"] = { s: "After Eragon successfully evades an Urgals ambush, he is adopted into the Ingeitum clan. He gets sent to finish his training so he can further help the Varden in their struggle against the Empire. Book #2",
  q: ["Write a paragraph imagining what Eragon's training with the Ingeitum clan might have been like.",
      "Write a paragraph about a time you trained hard to prepare to help a group or cause you cared about.",
      "Write a paragraph giving your opinion on why finishing his training was necessary before Eragon could truly help the Varden."],
  h: ["에라곤이 인게이팀 부족과 함께한 훈련이 어땠을지 상상하며 문단으로 써 보세요.",
      "여러분이 아끼는 모둠이나 대의를 돕기 위해 열심히 훈련했던 경험을 문단으로 써 보세요.",
      "에라곤이 바르덴을 진정으로 도울 수 있기 전에 훈련을 마치는 것이 왜 필요했는지 여러분의 생각을 문단으로 써 보세요."] };
ACT["S5093"] = { s: "Eragon upholds the oath he made to save Katrina from King Galbatorix. He gets pulled in different directions by everyone who needs his help and strength to rid the land of tyranny and defeat the king. Book #3",
  q: ["Write a paragraph imagining the different directions Eragon was pulled in by everyone who needed his help.",
      "Write a paragraph about a time you felt pulled in different directions by people who all needed your help.",
      "Write a paragraph giving your opinion on how Eragon should decide whose need for help to answer first."],
  h: ["에라곤에게 도움을 청하는 모두에게 이리저리 끌려다닌 모습을 상상하며 문단으로 써 보세요.",
      "여러분에게 도움이 필요한 사람들이 여러 방향으로 여러분을 끌어당겼던 경험을 문단으로 써 보세요.",
      "에라곤이 누구를 먼저 도와야 할지 어떻게 정해야 할지 여러분의 생각을 문단으로 써 보세요."] };
ACT["S5094"] = { s: "When an eager young scientist brings a flesh-eating dinosaur to life by crossing its DNA with that of his pet dog, Secret Agent Jack Stalwart needs to capture the dinosaur before it destroys New York City. Book #1",
  q: ["Write a paragraph imagining how Jack Stalwart might have tried to capture the flesh-eating dinosaur before it destroyed New York City.",
      "Write a paragraph about a time you had to act quickly to stop a problem from getting worse.",
      "Write a paragraph giving your opinion on whether crossing a dinosaur's DNA with a dog's DNA was a good scientific idea."],
  h: ["잭 스톨워트가 뉴욕을 파괴하기 전에 그 육식 공룡을 어떻게 붙잡으려 했을지 상상하며 문단으로 써 보세요.",
      "문제가 더 커지기 전에 빠르게 행동해야 했던 경험을 문단으로 써 보세요.",
      "공룡의 DNA를 개의 DNA와 섞은 것이 좋은 과학적 아이디어였는지 여러분의 생각을 문단으로 써 보세요."] };
ACT["S5095"] = { s: "This book follows the daring exploit of Jack as he goes down under the Great Barrier Reef to investigate the missing diver and treasure. Book #2",
  q: ["Write a paragraph imagining what Jack might have found while diving down under the Great Barrier Reef.",
      "Write a paragraph about a time you explored somewhere unfamiliar, on land or in water, and what you found.",
      "Write a paragraph giving your opinion on whether searching for a missing diver or searching for treasure should be Jack's first priority."],
  h: ["잭이 대보초 아래로 내려가면서 무엇을 발견했을지 상상하며 문단으로 써 보세요.",
      "여러분이 낯선 곳을 육지나 물속에서 탐험하고 무언가를 발견했던 경험을 문단으로 써 보세요.",
      "잭이 사라진 잠수부를 찾는 것과 보물을 찾는 것 중 무엇을 먼저 해야 할지 여러분의 생각을 문단으로 써 보세요."] };
ACT["S5096"] = { s: "This book presents the adventure of Secret agent Jack Stalwart as he travels to France to investigate the disappearance of the MONA LISA from the Louvre. Book #3",
  q: ["Write a paragraph imagining how Jack Stalwart might have investigated the disappearance of the Mona Lisa from the Louvre.",
      "Write a paragraph about a famous painting, place, or object you would like to see in person someday, like the Mona Lisa.",
      "Write a paragraph giving your opinion on why stealing a painting as famous as the Mona Lisa would be such a serious crime."],
  h: ["잭 스톨워트가 루브르에서 사라진 모나리자를 어떻게 조사했을지 상상하며 문단으로 써 보세요.",
      "모나리자처럼 언젠가 직접 보고 싶은 유명한 그림이나 장소, 물건에 대해 문단으로 써 보세요.",
      "모나리자처럼 유명한 그림을 훔치는 것이 왜 그렇게 심각한 범죄인지 여러분의 생각을 문단으로 써 보세요."] };
ACT["S5097"] = { s: "In this book, secret agent Jack Stalwart travels to London to investigate the case of England's missing crown jewels. Book #4",
  q: ["Write a paragraph imagining where England's missing crown jewels might have been hidden.",
      "Write a paragraph about a valuable or special object you would be very worried about losing.",
      "Write a paragraph giving your opinion on why crown jewels might be an especially tempting target for thieves."],
  h: ["잉글랜드의 사라진 왕관 보석들이 어디에 숨겨져 있었을지 상상하며 문단으로 써 보세요.",
      "잃어버릴까 봐 걱정될 만큼 소중하거나 특별한 물건에 대해 문단으로 써 보세요.",
      "왕관 보석 같은 물건이 왜 도둑들에게 특히 매력적인 표적이 되는지 여러분의 생각을 문단으로 써 보세요."] };
ACT["S5098"] = { s: "Secret Agent Jack Stalwart takes the case of the missing archaeologist who guards the priceless thousand-year-old treasures of the temple of Angkor Wat. Book #5",
  q: ["Write a paragraph imagining what might have happened to the missing archaeologist who guarded the temple of Angkor Wat.",
      "Write a paragraph about a place with a long history, like Angkor Wat, that you find interesting.",
      "Write a paragraph giving your opinion on why protecting thousand-year-old treasures like those at Angkor Wat is important."],
  h: ["앙코르와트 사원을 지키던 사라진 고고학자에게 무슨 일이 있었을지 상상하며 문단으로 써 보세요.",
      "앙코르와트처럼 오랜 역사를 지닌, 흥미롭게 느껴지는 장소에 대해 문단으로 써 보세요.",
      "앙코르와트 같은 천 년 된 보물을 지키는 것이 왜 중요한지 여러분의 생각을 문단으로 써 보세요."] };
ACT["S5099"] = { s: "Secret Agent Jack Stalwart is whisked away to the savannah of Kenya. A Masai chief informs Jack of elephant killings where the corpses have been robbed of their tusks. Book #6",
  q: ["Write a paragraph imagining how Jack Stalwart might have investigated the elephant killings in the Kenyan savannah.",
      "Write a paragraph about an animal you care about protecting, and why it matters to you.",
      "Write a paragraph giving your opinion on why poachers might kill elephants just for their tusks, and how that could be stopped."],
  h: ["잭 스톨워트가 케냐 사바나에서 벌어진 코끼리 살해 사건을 어떻게 조사했을지 상상하며 문단으로 써 보세요.",
      "여러분이 지키고 싶은 동물과 그 이유에 대해 문단으로 써 보세요.",
      "밀렵꾼들이 상아 때문에 코끼리를 죽이는 이유와 그것을 막을 방법에 대해 여러분의 생각을 문단으로 써 보세요."] };
