// 간이 학습 질문 — Book No. S51 묶음. 사람이 아니라 AI 가 한 번 쓰고 굳힌 파일이다.
window.ACT = window.ACT || {};
var ACT = window.ACT;
ACT["S5100"] = { s: "Secret agent Jack Stalwart travels to China and investigates the kidnapping of a giant panda. Book #7",
  q: ["What crime does Jack Stalwart investigate in China in this book?",
      "Have you ever seen a panda, in a zoo or in pictures? What was it like?",
      "If you were a secret agent solving this panda case, what is the first clue you would look for?"],
  h: ["이 책에서 잭 스톨워트는 중국에서 어떤 사건을 조사하나요?",
      "너는 동물원이나 사진에서 판다를 본 적이 있나요? 어땠나요?",
      "네가 이 판다 사건을 해결하는 비밀요원이라면, 가장 먼저 어떤 단서를 찾아볼 건가요?"] };
ACT["S5101"] = { s: "Secret agent Jack Stalwart sets off to Italy to protect Morgan Parks, a professional car racer, from an assassin. Book #8",
  q: ["Who does Jack Stalwart travel to Italy to protect, and from what danger?",
      "Have you ever watched a car race, in person or on TV? What did you think of it?",
      "If you had to protect a famous racer from danger, what would you do first?"],
  h: ["잭 스톨워트는 이탈리아에서 누구를 어떤 위험으로부터 지키려고 가나요?",
      "너는 실제로나 TV에서 자동차 경주를 본 적이 있나요? 어땠나요?",
      "네가 유명한 레이서를 위험에서 지켜야 한다면 가장 먼저 무엇을 할 건가요?"] };
ACT["S5102"] = { s: "Secret agent Jack Stalwart tracks down the missing chief rocket engineer in charge of the first manned mission to Mars. Book #9",
  q: ["Who is missing in this book, and what mission was that person in charge of?",
      "Would you like to be part of a mission to Mars someday? Why or why not?",
      "Why do you think someone might want the rocket engineer to disappear?"],
  h: ["이 책에서 누가 사라졌고, 그 사람은 어떤 임무를 맡고 있었나요?",
      "너는 언젠가 화성 탐사에 함께하고 싶나요? 왜 그런가요?",
      "왜 누군가 그 로켓 기술자를 사라지게 하려 했을까요?"] };
ACT["S5103"] = { s: "Secret agent Jack Stalwart travels to Mexico to hunt down a stolen map that reveals where to find hidden Aztec gold. Book #10",
  q: ["What does Jack Stalwart search for in Mexico in this book?",
      "Have you ever looked for something you lost, or played a treasure hunt game? What was it like?",
      "If you found the stolen map, what would you do with it first?"],
  h: ["잭 스톨워트는 멕시코에서 무엇을 찾으려 하나요?",
      "너는 무언가를 잃어버려 찾아본 적이 있나요, 아니면 보물찾기 놀이를 해 본 적이 있나요? 어땠나요?",
      "네가 그 도둑맞은 지도를 찾는다면 가장 먼저 무엇을 할 건가요?"] };
ACT["S5105"] = { s: "When the Baudelaire orphans are shipped off to a miserable boarding school, their outrageous misfortune continues and they find that they have been followed by the dreaded Count Olaf. Book #5",
  q: ["Where are the Baudelaire orphans sent in this book, and who follows them there?",
      "Have you ever started at a new school? How did you feel on the first day?",
      "Why do you think Count Olaf keeps following the Baudelaire orphans everywhere they go?"],
  h: ["보들레어 남매는 이 책에서 어디로 보내지고, 누가 그곳까지 따라오나요?",
      "너는 새 학교에 처음 간 적이 있나요? 그날 기분이 어땠나요?",
      "올라프 백작은 왜 보들레어 남매를 계속 쫓아다닐까요?"] };
ACT["S5106"] = { s: "Joey is desperate not to be eaten up by his chaotic life as his divorced parents cannot stop fighting; his mother sends him to be home-schooled with a hostile blind girl; his grandmother is dying of some serious disease. Book #3",
  q: ["What are some of the hard things happening in Joey's life in this book?",
      "Has your life ever felt chaotic or hard to handle? What helped you get through it?",
      "What advice would you give Joey if you could talk to him?"],
  h: ["이 책에서 조이의 삶을 힘들게 하는 일들은 무엇인가요?",
      "너의 삶이 너무 복잡하고 힘들게 느껴진 적이 있나요? 무엇이 도움이 되었나요?",
      "조이에게 말할 수 있다면 어떤 조언을 해 주고 싶나요?"] };
ACT["S5107"] = { s: "Joey's father apologizes for his bad behavior in the past. He has even changed his name. He convinces Joey and his mom to change their names and become new people. Joey starts to worry that all the changes will make him lose sight of who he is. Book #4",
  q: ["Why does Joey start to worry in this book, after his family changes their names?",
      "Do you think your name is an important part of who you are? Why or why not?",
      "If your family asked you to change your name, how would you feel about it?"],
  h: ["가족이 이름을 바꾼 뒤 조이는 왜 걱정하기 시작하나요?",
      "너의 이름이 네가 어떤 사람인지 보여 주는 중요한 부분이라고 생각하나요? 왜 그런가요?",
      "가족이 너에게 이름을 바꾸자고 하면 너는 어떤 기분일 것 같나요?"] };
ACT["S5108"] = { s: "Tree-ear, an orphan in Korea, lives under a bridge in a potters' village and hopes to learn how to throw the celadon pottery himself.",
  q: ["What does Tree-ear hope to learn in this book, and where does he live?",
      "Have you ever seen Korean celadon pottery, in a museum or a picture? What did it look like?",
      "Why do you think Tree-ear wants so badly to learn to make pottery himself?"],
  h: ["트리 이어는 이 책에서 무엇을 배우고 싶어 하고, 어디에 살고 있나요?",
      "너는 한국 청자를 박물관이나 사진에서 본 적이 있나요? 어떤 모습이었나요?",
      "트리 이어는 왜 그렇게까지 도자기 만드는 법을 배우고 싶어 할까요?"] };
ACT["S5109"] = { s: "Physically flawed and suddenly orphaned, Kira is left with a terrifying, uncertain future. After she is mysteriously moved to live in the palatial Council Edifice, she is expected to use her gifts to save the world. This is the second book in Lois Lowry's Giver Quartet.",
  q: ["What happens to Kira at the beginning of this book, and where is she moved to live?",
      "Have you ever had to move somewhere new and unfamiliar? How did you feel?",
      "What do you think Kira's special gift might be, based on the summary?"],
  h: ["이 책 첫머리에서 키라에게 무슨 일이 일어나고, 그녀는 어디로 옮겨 살게 되나요?",
      "너는 낯설고 새로운 곳으로 이사해 본 적이 있나요? 기분이 어땠나요?",
      "요약을 보면 키라의 특별한 재능은 무엇일 것 같나요?"] };
ACT["S5110"] = { s: "Everything in Jonas's world is perfectly under control. Everyone is assigned a role in the community, and when Jonas becomes twelve, he is chosen to be the Receiver of Memory. During his training, he experiences joy and sadness for the first time.",
  q: ["What role is Jonas chosen for when he turns twelve, and what does he begin to feel for the first time?",
      "If your role in life were assigned to you instead of chosen by you, how would you feel?",
      "Do you think a world with everything under control would be a good place to live? Why or why not?"],
  h: ["조너스는 열두 살이 되었을 때 어떤 역할을 맡게 되고, 그때 처음 느끼는 감정은 무엇인가요?",
      "네 삶의 역할을 네가 고르지 못하고 정해진다면 기분이 어떨 것 같나요?",
      "모든 것이 완전히 통제되는 세상이 살기 좋은 곳일까요? 왜 그렇게 생각하나요?"] };
ACT["S5111"] = { s: "Young Katy makes friends with Jacob, who has autism, and she is the only one who understands him. When a tragic accident happens to his family, she tries to unravel the mystery and comes to realize what Jacob meant to do for his family.",
  q: ["What happens to Jacob's family in this book, and what does Katy try to do afterward?",
      "Have you ever had a friend that other people didn't understand as well as you did?",
      "Why do you think Katy is the only one who understands Jacob?"],
  h: ["이 책에서 제이콥의 가족에게 무슨 일이 일어나고, 그 뒤 케이티는 무엇을 하려고 하나요?",
      "다른 사람들은 잘 이해하지 못하는 친구를 가져 본 적이 있나요?",
      "왜 케이티만 제이콥을 이해할 수 있을까요?"] };
ACT["S5112"] = { s: "Mrs. Piggle-Wiggle cures children of their bad habits, such as excessive television watching and picking on friends.",
  q: ["What kinds of bad habits does Mrs. Piggle-Wiggle cure children of in this book?",
      "Do you have a habit you would like to change? What is it?",
      "If you were Mrs. Piggle-Wiggle, what cure would you invent for a bad habit?"],
  h: ["피글위글 아주머니는 이 책에서 아이들의 어떤 나쁜 습관을 고쳐 주나요?",
      "너에게 고치고 싶은 습관이 있나요? 무엇인가요?",
      "네가 피글위글 아주머니라면 어떤 나쁜 습관을 고치는 마법을 만들고 싶나요?"] };
ACT["S5113"] = { s: "Eight funny and instructive stories in which the magical Mrs. Piggle-Wiggle helps teach children how to behave.",
  q: ["How does Mrs. Piggle-Wiggle help children in this book?",
      "Which of your own habits do you think an adult might want to help you fix?",
      "Which of the eight stories would you most want to read first, and why?"],
  h: ["피글위글 아주머니는 이 책에서 아이들을 어떻게 도와주나요?",
      "어른이 고쳐 주고 싶어할 만한 너의 습관은 무엇일까요?",
      "여덟 가지 이야기 중 가장 먼저 읽고 싶은 이야기는 무엇이고 왜인가요?"] };
ACT["S5114"] = { s: "Seven families are helped out by Mrs. Piggle-Wiggle's magic cures when they are faced with thought-you-saiders, tattletales, bad table manners.",
  q: ["What kinds of problems does Mrs. Piggle-Wiggle's magic solve for the seven families?",
      "Have you ever known a tattletale, or been one yourself? What happened?",
      "What magic cure would you ask Mrs. Piggle-Wiggle for?"],
  h: ["피글위글 아주머니의 마법은 일곱 가족의 어떤 문제들을 해결해 주나요?",
      "고자질하는 친구를 본 적이 있거나 네가 그런 적이 있나요? 무슨 일이 있었나요?",
      "너는 피글위글 아주머니에게 어떤 마법 치료법을 부탁하고 싶나요?"] };
ACT["S5115"] = { s: "A young boy determines to rescue a poor baby dragon who is being used some lazy wild animals to ferry them across the river on Wild Island.",
  q: ["Why do the wild animals need the baby dragon, and what does the boy decide to do about it?",
      "Have you ever wanted to rescue an animal in trouble? What happened?",
      "What do you think the boy will need to bring with him to rescue the dragon?"],
  h: ["야생 동물들에게는 왜 아기 용이 필요하고, 소년은 무엇을 하기로 결심하나요?",
      "위험에 처한 동물을 구해 주고 싶었던 적이 있나요? 무슨 일이 있었나요?",
      "소년이 용을 구하러 가려면 무엇을 챙겨야 할까요?"] };
ACT["S5116"] = { s: "Eternal warfare is the price of dismal prosperity in this satire of totalitarian inhumanity.",
  q: ["What does this book say is the price of the world's prosperity?",
      "Why do you think people in some places might have to live without freedom?",
      "What do you think 'totalitarian' means, based on this summary, and why do you think the author is criticizing it?"],
  h: ["이 책은 세상의 번영을 위해 어떤 대가를 치른다고 말하나요?",
      "왜 어떤 곳의 사람들은 자유 없이 살아야 할까요?",
      "이 요약을 보면 '전체주의'는 무슨 뜻인 것 같고, 작가는 왜 그것을 비판하는 것 같나요?"] };
ACT["S5118"] = { s: "A boy tells his annual summer vacations to rural Illinois with his sister during the Great Depression to visit their larger-than-life grandmother.",
  q: ["Who does the boy visit every summer in this book, and when does the story take place?",
      "Have you ever visited a grandparent for a long stay? What do you remember most?",
      "What do you think makes the grandmother 'larger-than-life'?"],
  h: ["소년은 이 책에서 여름마다 누구를 찾아가고, 이야기는 언제를 배경으로 하나요?",
      "할머니나 할아버지 댁에 오래 머문 적이 있나요? 가장 기억에 남는 일은 무엇인가요?",
      "할머니를 '보통 사람이 아닌 것 같은' 인물로 만드는 것은 무엇일까요?"] };
ACT["S5119"] = { s: "Jeff's mother, who had left the family while he was still very young, returns and drives the wedge even deeper between he and his father.",
  q: ["What happens when Jeff's mother returns in this book?",
      "Have you ever felt caught between two people you love? How did that feel?",
      "Why do you think the mother's return makes things worse instead of better?"],
  h: ["제프의 엄마가 돌아왔을 때 이 책에서 무슨 일이 일어나나요?",
      "사랑하는 두 사람 사이에 끼인 것 같은 기분을 느껴 본 적이 있나요? 어땠나요?",
      "엄마의 귀환이 왜 상황을 더 나쁘게 만들까요?"] };
ACT["S5120"] = { s: "The woeful saga of the Baudelaire orphans continues as evil Count Olaf discovers their whereabouts. He concocts a new plan for stealing their family fortune. Book #6",
  q: ["What does Count Olaf discover in this book, and what does he plan to do?",
      "Have you ever had to hide something or someone from a person who was looking for it?",
      "What new trick do you think Count Olaf will try this time?"],
  h: ["올라프 백작은 이 책에서 무엇을 알아내고, 무엇을 계획하나요?",
      "누군가로부터 사람이나 물건을 숨겨야 했던 적이 있나요?",
      "올라프 백작은 이번에 어떤 새로운 속임수를 쓸까요?"] };
ACT["S5121"] = { s: "Farm animals undergo a revolution against their human master and establish a new government. But it fails because of a corrupt leader tempted by greed and power.",
  q: ["Why does the animals' new government fail in this book?",
      "Have you ever seen someone in charge use their power unfairly? What happened?",
      "What do you think the animals should have done differently to keep their government fair?"],
  h: ["이 책에서 동물들의 새 정부는 왜 실패하나요?",
      "권력을 가진 사람이 그것을 불공평하게 쓰는 것을 본 적이 있나요? 무슨 일이 있었나요?",
      "동물들이 공정한 정부를 지키려면 무엇을 다르게 했어야 할까요?"] };
ACT["S5122"] = { s: "The Baudelaire orphans are adopted by an entire town under a new government program based on the saying 'It takes a village to raise a child.' Book #7",
  q: ["What program leads to the Baudelaire orphans being adopted by an entire town?",
      "Do you agree that 'it takes a village to raise a child'? Why or why not?",
      "What do you think could go wrong when an entire town tries to raise three children together?"],
  h: ["어떤 프로그램 때문에 보들레어 남매는 마을 전체에 입양되나요?",
      "'한 아이를 키우려면 온 마을이 필요하다'는 말에 동의하나요? 왜 그런가요?",
      "마을 전체가 세 아이를 함께 키우려 하면 무엇이 잘못될 수 있을까요?"] };
ACT["S5124"] = { s: "Ten-year-old Bud, a motherless boy, during the Great Depression, escapes a bad foster home and sets out in search of the man he believes to be his father.",
  q: ["What does Bud escape from in this book, and who is he searching for?",
      "Have you ever searched hard for something or someone important to you?",
      "Why do you think Bud believes this man is his father?"],
  h: ["버드는 이 책에서 무엇으로부터 도망치고, 누구를 찾고 있나요?",
      "너에게 소중한 사람이나 물건을 열심히 찾아본 적이 있나요?",
      "버드는 왜 이 남자가 자기 아버지라고 믿을까요?"] };
ACT["S5125"] = { s: "A boy overcomes his fear of the sea and proves his courage to himself and his tribe.",
  q: ["What fear does the boy overcome in this book?",
      "What is something you were once afraid of but later overcame?",
      "Why do you think proving courage to his tribe matters so much to the boy?"],
  h: ["소년은 이 책에서 어떤 두려움을 이겨 내나요?",
      "네가 한때 두려워했지만 지금은 이겨 낸 것은 무엇인가요?",
      "소년에게 부족에게 용기를 증명하는 일이 왜 그렇게 중요할까요?"] };
ACT["S5126"] = { s: "Yossarian wants to escape from the war. His efforts are quite acceptable because as he furiously scrambles, thousands of people he hasn't even met are trying to kill him.",
  q: ["What does Yossarian want to escape from in this book?",
      "Have you ever been in a situation that felt unfair or out of your control?",
      "Why do you think the summary says his efforts to escape are 'acceptable'?"],
  h: ["요사리안은 이 책에서 무엇으로부터 벗어나고 싶어 하나요?",
      "네가 어쩔 수 없다고 느낀 불공평한 상황에 처해 본 적이 있나요?",
      "요약에서는 왜 그의 탈출 노력이 '이해할 만하다'고 말할까요?"] };
ACT["S5127"] = { s: "The daughter of an English knight writes a journal about the events of her life, particularly her longing for adventures beyond the usual role of women and her efforts to avoid being married off.",
  q: ["What does Catherine write about in her journal, and what is she trying to avoid?",
      "Have you ever kept a journal or diary? What did you write about?",
      "Why do you think Catherine longs for adventures beyond the usual role for women in her time?"],
  h: ["캐서린은 일기에 무엇을 쓰고, 무엇을 피하려고 하나요?",
      "일기나 다이어리를 써 본 적이 있나요? 무엇을 적었나요?",
      "캐서린은 왜 당시 여성의 평범한 역할을 넘어서는 모험을 그리워할까요?"] };
ACT["S5128"] = { s: "When a precious Vermeer painting disappears, eleven-year-olds Petra and Calder combine their talents to solve an international art scandal.",
  q: ["What goes missing in this book, and who tries to solve the mystery?",
      "Have you ever worked together with a friend to solve a problem? What happened?",
      "What talents do you think Petra and Calder each bring to solving the case?"],
  h: ["이 책에서 무엇이 사라지고, 누가 그 수수께끼를 풀려고 하나요?",
      "친구와 힘을 합쳐 문제를 해결해 본 적이 있나요? 무슨 일이 있었나요?",
      "페트라와 칼더는 각각 어떤 재능을 사건 해결에 쓸 것 같나요?"] };
ACT["S5131"] = { s: "In the mountains of Switzerland, the wicked Count Karlstein plans to abandon his two nieces in a hunting lodge as prey for the Demon Huntsman.",
  q: ["What does Count Karlstein plan to do to his two nieces in this book?",
      "Have you ever had to protect someone younger than you from danger?",
      "What do you think the two nieces should do to escape the Count's plan?"],
  h: ["카를슈타인 백작은 이 책에서 두 조카에게 무엇을 하려고 계획하나요?",
      "너보다 어린 사람을 위험에서 지켜 준 적이 있나요?",
      "두 조카는 백작의 계획에서 벗어나려면 어떻게 해야 할까요?"] };
ACT["S5132"] = { s: "Falsely accused of theft and murder, an orphaned peasant boy in fourteenth-century England escapes from his village and meets a juggler who keeps a dangerous secret.",
  q: ["What is Crispin falsely accused of, and who does he meet after escaping?",
      "Have you ever been blamed for something you didn't do? How did you feel?",
      "What kind of secret do you think the juggler is keeping?"],
  h: ["크리스핀은 무슨 죄를 억울하게 뒤집어쓰고, 도망친 뒤 누구를 만나나요?",
      "하지 않은 일로 비난받은 적이 있나요? 그때 기분이 어땠나요?",
      "그 저글러는 어떤 비밀을 숨기고 있을 것 같나요?"] };
ACT["S5135"] = { s: "Eleven-year-old Elijah, the first freeborn child in Buxton, Canada, a haven for slaves fleeing the American South, uses his wits to bring to justice the lying preacher who has stolen money.",
  q: ["What does Elijah do in this book to bring the preacher to justice?",
      "Have you ever used your wits to solve a tricky problem?",
      "Why do you think it matters that Elijah is the first freeborn child in Buxton?"],
  h: ["엘라이자는 이 책에서 설교자를 심판받게 하기 위해 무엇을 하나요?",
      "어려운 문제를 재치로 풀어낸 적이 있나요?",
      "엘라이자가 벅스턴에서 태어난 첫 자유인 아이라는 사실이 왜 중요할까요?"] };
ACT["S5136"] = { s: "A seventh-grade girl named Emma-Jean Lazarus discovers some interesting results when she gets involved in the messy everyday problems of her friends.",
  q: ["What kind of problems does Emma-Jean get involved in in this book?",
      "Have you ever helped a friend solve a problem? What did you do?",
      "What interesting results do you imagine Emma-Jean discovers?"],
  h: ["엠마진은 이 책에서 어떤 문제들에 휘말리나요?",
      "친구의 문제를 도와준 적이 있나요? 어떻게 도왔나요?",
      "엠마진은 어떤 흥미로운 결과를 발견하게 될 것 같나요?"] };
ACT["S5138"] = { s: "Eleven-year-old Primrose tells her experiences and all that she learns about human nature and the unpredictability of life in the months after her parents are lost at sea.",
  q: ["What happens to Primrose's parents in this book, and what does she learn afterward?",
      "Have you ever learned something important about life during a hard time?",
      "What do you think 'the unpredictability of life' means, based on this summary?"],
  h: ["프림로즈의 부모님에게는 이 책에서 무슨 일이 일어나고, 그 뒤 그녀는 무엇을 배우나요?",
      "힘든 시간을 겪으며 삶에 대해 중요한 것을 배운 적이 있나요?",
      "이 요약에서 '삶의 예측할 수 없음'은 무슨 뜻일까요?"] };
ACT["S5139"] = { s: "In this futuristic novel, the main character struggles with excessive controls on individual freedom.",
  q: ["What does the main character struggle with in this book?",
      "Is there a freedom in your own life that feels especially important to you? What is it?",
      "Why do you think a future society might want to control people's freedom?"],
  h: ["주인공은 이 책에서 무엇 때문에 힘들어하나요?",
      "네 삶에서 특히 중요하게 느껴지는 자유가 있나요? 무엇인가요?",
      "미래 사회는 왜 사람들의 자유를 통제하고 싶어 할까요?"] };
ACT["S5140"] = { s: "The three Baudelaire orphans are on the run after being falsely accused of murder. In this episode, they find themselves in Heimlich Hospital, with the evil Count Olaf in close pursuit. Book #8",
  q: ["Where do the Baudelaire orphans end up in this book, and who is chasing them?",
      "Have you ever had to hide or run from a problem? What did you do?",
      "Why do you think a hospital is a dangerous place for the orphans to hide?"],
  h: ["보들레어 남매는 이 책에서 어디로 가게 되고, 누가 그들을 쫓아오나요?",
      "문제를 피해 숨거나 도망쳐야 했던 적이 있나요? 어떻게 했나요?",
      "왜 병원이 남매가 숨기에 위험한 곳일까요?"] };
ACT["S5141"] = { s: "Charlie Gordon, born with an unusually low IQ, must face his gradual return to his former state when the surprising results of an experimental surgery.",
  q: ["What happens to Charlie Gordon after his experimental surgery in this book?",
      "Have you ever worked hard to improve at something, only to see it slip away?",
      "How do you think Charlie feels as he realizes he is changing back?"],
  h: ["찰리 고든은 실험 수술을 받은 뒤 이 책에서 어떤 일을 겪나요?",
      "열심히 노력해서 잘하게 되었는데 다시 잃게 된 적이 있나요?",
      "찰리는 자신이 원래대로 돌아가고 있다는 것을 깨달으며 어떤 기분일까요?"] };
ACT["S5142"] = { s: "With their father jailed for sinking a river boat, Noah Underwood and his younger sister, Abbey, must gather evidence to reveal the truth.",
  q: ["Why is the father in jail in this book, and what do Noah and Abbey try to do?",
      "Have you ever tried to prove that something unfair had happened?",
      "What kind of evidence do you think Noah and Abbey need to find?"],
  h: ["아버지는 이 책에서 왜 감옥에 갇혀 있고, 노아와 애비는 무엇을 하려고 하나요?",
      "불공평한 일이 있었다는 것을 증명하려고 한 적이 있나요?",
      "노아와 애비는 어떤 증거를 찾아야 할까요?"] };
ACT["S5143"] = { s: "After Annie sends George a secret message telling him she has been contacted with a terrible warning by aliens.",
  q: ["What warning does Annie's secret message contain in this book?",
      "If you received a secret message about aliens, what would you do first?",
      "What do you think the terrible warning from the aliens could be about?"],
  h: ["애니의 비밀 메시지에는 이 책에서 어떤 경고가 담겨 있나요?",
      "외계인에 대한 비밀 메시지를 받는다면 가장 먼저 무엇을 할 건가요?",
      "외계인의 끔찍한 경고는 무엇에 관한 것일 것 같나요?"] };
ACT["S5144"] = { s: "Thanks to his new friends, Annie and Eric, George discovers a key that opens the universe to him and must eventually use his knowledge to help save Eric from within a black hole.",
  q: ["What does George discover in this book, and what must he do to save Eric?",
      "Have you ever learned something new that helped you help a friend?",
      "What do you imagine a black hole might be like, based on what you know?"],
  h: ["조지는 이 책에서 무엇을 발견하고, 에릭을 구하려면 무엇을 해야 하나요?",
      "새로 배운 것으로 친구를 도운 적이 있나요?",
      "블랙홀은 어떤 곳일 것 같나요? 네가 아는 것을 바탕으로 상상해 보세요."] };
ACT["S5145"] = { s: "Willa Jo and her younger sister come to terms with the death of their family's baby while staying with their Aunt Patty and Uncle Hob.",
  q: ["What are Willa Jo and her sister trying to come to terms with in this book?",
      "Have you ever gone through a sad time with the help of family?",
      "Why do you think staying with their aunt and uncle helps the sisters?"],
  h: ["윌라 조와 동생은 이 책에서 무엇을 받아들이려 하나요?",
      "가족의 도움으로 슬픈 시간을 이겨 낸 적이 있나요?",
      "이모와 삼촌 댁에 머무는 것이 자매에게 왜 도움이 될까요?"] };
ACT["S5146"] = { s: "Julian and Portia spend an unforgettable vacation when they discover an deserted summer colony.",
  q: ["What do Julian and Portia discover during their vacation in this book?",
      "Have you ever explored somewhere new and found something surprising?",
      "What do you imagine the deserted summer colony looks like?"],
  h: ["줄리언과 포샤는 이 책에서 방학 중에 무엇을 발견하나요?",
      "새로운 곳을 탐험하다가 놀라운 것을 발견한 적이 있나요?",
      "그 버려진 여름 마을은 어떤 모습일 것 같나요?"] };
ACT["S5147"] = { s: "After the end of the world and the days that follow it, Ford Prefect and Arthur Dent meet various characters in the universe.",
  q: ["What happens at the start of this book, and who do Ford Prefect and Arthur Dent meet afterward?",
      "If your world ended and you had to travel through the universe, what would you want to bring with you?",
      "What kind of characters do you imagine Ford and Arthur might meet in the universe?"],
  h: ["이 책 시작 부분에서 무슨 일이 일어나고, 포드 프리펙트와 아서 덴트는 그 뒤 누구를 만나나요?",
      "네가 사는 세상이 끝나고 우주를 여행해야 한다면 무엇을 챙기고 싶나요?",
      "포드와 아서는 우주에서 어떤 인물들을 만날 것 같나요?"] };
ACT["S5148"] = { s: "Brilliant young Homer Price captures robbers, solves mysteries, and helps people in trouble.",
  q: ["What kinds of things does Homer Price do in this book?",
      "Have you ever helped solve a problem for someone in trouble?",
      "What mystery would you like to see Homer solve?"],
  h: ["호머 프라이스는 이 책에서 어떤 일들을 하나요?",
      "곤경에 처한 사람을 도와 문제를 해결해 준 적이 있나요?",
      "호머가 풀어 주었으면 하는 수수께끼는 무엇인가요?"] };
ACT["S5149"] = { s: "Roy, who is a newcomer to Florida community, becomes involved in another boy's attempt to save a colony of burrowing owls from construction site.",
  q: ["What is Roy trying to help save in this book, and from what danger?",
      "Have you ever tried to protect an animal or its home?",
      "Why do you think saving the owls matters so much to the other boy?"],
  h: ["로이는 이 책에서 무엇을 지키려 하고, 어떤 위험으로부터인가요?",
      "동물이나 동물의 집을 지켜 주려고 한 적이 있나요?",
      "부엉이를 구하는 일이 다른 소년에게 왜 그렇게 중요할까요?"] };
ACT["S5150"] = { s: "When Hope and the aunt who has raised her move to Wisconsin, to work as waitress and cook in the diner, they become involved in the political campaign to expel the town's corrupt mayor.",
  q: ["What job do Hope and her aunt take in this book, and what political campaign do they join?",
      "Have you ever spoken up about something you thought was unfair?",
      "Why do you think Hope and her aunt decide to get involved in the campaign?"],
  h: ["호프와 이모는 이 책에서 어떤 일을 하고, 어떤 정치 운동에 함께하나요?",
      "불공평하다고 생각한 일에 대해 목소리를 낸 적이 있나요?",
      "호프와 이모는 왜 그 운동에 참여하기로 할까요?"] };
ACT["S5151"] = { s: "This book retells Mark Twain's classic novel about the adventures of a young boy who sets off on a journey down the Mississippi River with Jim, a runaway slave.",
  q: ["Who does the young boy travel down the Mississippi River with in this book?",
      "Have you ever gone on a long trip, by boat, car, or train? What was it like?",
      "Why do you think the boy decides to travel with Jim?"],
  h: ["소년은 이 책에서 누구와 함께 미시시피강을 따라 여행하나요?",
      "배·자동차·기차로 긴 여행을 해 본 적이 있나요? 어땠나요?",
      "소년은 왜 짐과 함께 여행하기로 결심할까요?"] };
ACT["S5152"] = { s: "Ida B's happy life changes when her mother begins cancer treatment. Ida B eventually learns to overcome her anger and sadness.",
  q: ["What changes Ida B's happy life in this book, and what does she learn to overcome?",
      "Have you ever felt angry or sad about something hard happening in your family?",
      "What do you think helps Ida B overcome her anger and sadness?"],
  h: ["아이다 비의 행복한 삶은 이 책에서 무엇 때문에 바뀌고, 그녀는 무엇을 이겨 내는 법을 배우나요?",
      "가족에게 힘든 일이 생겨서 화나거나 슬펐던 적이 있나요?",
      "아이다 비가 화와 슬픔을 이겨 내는 데 무엇이 도움이 될 것 같나요?"] };
ACT["S5153"] = { s: "The true story of Louisa May Alcott, the author of the famous novel 'Little Women.'",
  q: ["Who is this book a true story about, and what famous book did she write?",
      "Have you ever read a book by an author whose life story you wanted to know more about?",
      "What do you think made Louisa May Alcott 'invincible'?"],
  h: ["이 책은 누구의 실화이고, 그 사람은 어떤 유명한 책을 썼나요?",
      "삶의 이야기가 더 궁금했던 작가의 책을 읽어 본 적이 있나요?",
      "루이자 메이 올콧을 '무적'으로 만든 것은 무엇이었을 것 같나요?"] };
ACT["S5154"] = { s: "Left alone on a beautiful but isolated island off the coast of California, a young Indian girl spends 18 years on finding a measure of happiness in her solitary life.",
  q: ["How long does the girl spend alone on the island in this book?",
      "Have you ever spent time completely alone? How did it feel?",
      "How do you think the girl manages to find happiness while living alone for so long?"],
  h: ["소녀는 이 책에서 섬에 혼자 얼마나 오래 지내나요?",
      "완전히 혼자 있어 본 적이 있나요? 그 기분이 어땠나요?",
      "소녀는 그렇게 오랫동안 혼자 지내면서 어떻게 행복을 찾을 수 있었을까요?"] };
ACT["S5155"] = { s: "Feeling deprived all her life of schooling, friends, mother, and even her name by her twin sister, Louise finally begins to search for her identity.",
  q: ["What has Louise felt deprived of by her twin sister in this book?",
      "Have you ever felt overshadowed by someone close to you, like a sibling?",
      "What do you think Louise will discover as she searches for her identity?"],
  h: ["루이스는 이 책에서 쌍둥이 언니 때문에 무엇을 빼앗겼다고 느끼나요?",
      "형제자매처럼 가까운 사람에게 가려진 것 같은 기분을 느껴 본 적이 있나요?",
      "루이스는 자신의 정체성을 찾으며 무엇을 발견하게 될 것 같나요?"] };
ACT["S5156"] = { s: "While living on a Vermont poor farm during 1855 and 1856, Jip learns his identity and that of his mother.",
  q: ["What does Jip learn about himself and his mother in this book?",
      "Have you ever learned a surprising fact about your family?",
      "Why do you think Jip's identity had been kept a secret until now?"],
  h: ["집은 이 책에서 자신과 어머니에 대해 무엇을 알게 되나요?",
      "가족에 대해 놀라운 사실을 알게 된 적이 있나요?",
      "집의 정체는 왜 지금까지 비밀로 남아 있었을까요?"] };
ACT["S5157"] = { s: "Common sense and bravery enable a young Eskimo girl to survive in the Arctic wild.",
  q: ["What qualities help Julie survive in the Arctic in this book?",
      "Have you ever needed courage to get through a difficult situation?",
      "What do you think would be hardest about surviving alone in the Arctic?"],
  h: ["줄리가 북극에서 살아남도록 도와주는 것은 이 책에서 어떤 자질들인가요?",
      "힘든 상황을 이겨 내기 위해 용기가 필요했던 적이 있나요?",
      "북극에서 혼자 살아남는 데 가장 힘든 점은 무엇일 것 같나요?"] };
ACT["S5160"] = { s: "Pi survives a shipwreck with several animals. Pi, whose fear, knowledge, and cunning allow him to coexist with animals 227 days lost at sea.",
  q: ["How many days does Pi survive at sea in this book, and what helps him survive?",
      "Have you ever had to stay calm in a scary situation? What did you do?",
      "Why do you think it is so hard for Pi to coexist with the animals on the boat?"],
  h: ["파이는 이 책에서 바다에서 며칠을 살아남고, 무엇이 그를 도와주나요?",
      "무서운 상황에서 침착함을 유지해야 했던 적이 있나요? 어떻게 했나요?",
      "파이가 배 위의 동물들과 함께 지내는 것이 왜 그렇게 힘들까요?"] };
ACT["S5162"] = { s: "It's 1911, and Turner Buckminster hates his new home. But things improve when he meets Lizzie Bright, a girl from a poor island community.",
  q: ["How does Turner's feeling about his new home change in this book?",
      "Have you ever disliked a new place at first, then grown to like it?",
      "Why do you think meeting Lizzie changes things for Turner?"],
  h: ["터너는 이 책에서 새 집에 대한 생각이 어떻게 바뀌나요?",
      "새로운 곳을 처음엔 싫어했다가 나중에 좋아하게 된 적이 있나요?",
      "리지를 만난 것이 터너에게 왜 변화를 가져올까요?"] };
ACT["S5163"] = { s: "After a plane crash strands them on a tropical island while the rest of the world is ravaged by war, a group of British schoolboys attempts to form a civilized society but it turns into brutal anarchy.",
  q: ["What do the boys try to build after the plane crash in this book, and what does it turn into?",
      "Have you ever been part of a group that had trouble working together fairly?",
      "Why do you think the boys' attempt at a civilized society fails?"],
  h: ["비행기 추락 후 소년들은 이 책에서 무엇을 세우려 하고, 그것은 무엇으로 변하나요?",
      "공평하게 협력하기 힘들었던 단체 활동을 해 본 적이 있나요?",
      "소년들의 문명 사회를 만들려는 시도는 왜 실패할까요?"] };
ACT["S5164"] = { s: "Matilda, an apprentice bonesetter and practitioner of medicine in a village in medieval England, tries to reconcile the various aspects of her life.",
  q: ["What is Matilda's job in this book, and what is she trying to reconcile?",
      "Have you ever had to balance different parts of your life that pulled in different directions?",
      "What do you imagine medicine was like in medieval England, based on this summary?"],
  h: ["마틸다의 직업은 이 책에서 무엇이고, 그녀는 무엇을 조화시키려 하나요?",
      "서로 다른 방향으로 끌어당기는 삶의 여러 부분을 맞춰야 했던 적이 있나요?",
      "이 요약을 보면 중세 영국의 의술은 어떤 모습이었을 것 같나요?"] };
ACT["S5165"] = { s: "The three Baudelaire orphans are still on the run as suspected murderers. They find themselves trapped in the Caligari Carnival, where they must masquerade as freaks in order to hide from the evil Count Olaf. Book #9",
  q: ["Where do the Baudelaire orphans hide in this book, and how do they disguise themselves?",
      "Have you ever had to disguise yourself or pretend to be someone else, like on Halloween?",
      "Why do you think a carnival is a good place for the orphans to hide?"],
  h: ["보들레어 남매는 이 책에서 어디에 숨고, 어떻게 변장하나요?",
      "핼러윈처럼 변장하거나 다른 사람인 척해야 했던 적이 있나요?",
      "카니발이 남매가 숨기에 왜 좋은 장소일까요?"] };
ACT["S5166"] = { s: "After the death of the aunt who has raised her, Summer and her Uncle Ob leave their West Virginia trailer in search of the strength to go on living.",
  q: ["What are Summer and Uncle Ob searching for in this book, after May's death?",
      "Have you ever lost someone important to you? How did you find strength afterward?",
      "Why do you think leaving their home helps Summer and Uncle Ob?"],
  h: ["메이가 세상을 떠난 뒤 서머와 오브 삼촌은 이 책에서 무엇을 찾고 있나요?",
      "소중한 사람을 잃어 본 적이 있나요? 그 뒤 어떻게 힘을 얻었나요?",
      "집을 떠나는 것이 서머와 오브 삼촌에게 왜 도움이 될까요?"] };
ACT["S5167"] = { s: "A breed of wild horses inhabit an island, and one is befriended and raised by the love of two children.",
  q: ["What kind of animal do the two children befriend and raise in this book?",
      "Have you ever taken care of an animal? What was that like?",
      "Why do you think the wild horse comes to trust the two children?"],
  h: ["두 아이는 이 책에서 어떤 동물과 친구가 되어 함께 키우나요?",
      "동물을 돌본 적이 있나요? 어땠나요?",
      "그 야생마는 왜 두 아이를 믿게 될까요?"] };
ACT["S5168"] = { s: "Mr. Popper trains his band of penguins to star in a concert tour.",
  q: ["What does Mr. Popper train his penguins to do in this book?",
      "If you could train an animal to perform, which animal would you choose and what would you teach it?",
      "What do you think is the hardest part of training penguins for a concert tour?"],
  h: ["포퍼 씨는 이 책에서 펭귄들에게 무엇을 훈련시키나요?",
      "동물을 하나 훈련시킬 수 있다면 어떤 동물을 골라 무엇을 가르치고 싶나요?",
      "펭귄들을 공연 투어에 맞게 훈련시키는 데 가장 힘든 점은 무엇일 것 같나요?"] };
ACT["S5169"] = { s: "Mrs. Frisby, enlists the aid of the Rats of NIMH to move their home from the path of the farmer's plow when her son Timothy, youngest of a family of field mice, becomes ill.",
  q: ["Why does Mrs. Frisby need the help of the Rats of NIMH in this book?",
      "Have you ever had to ask someone else for help with an important problem?",
      "Why do you think the Rats of NIMH are able to help Mrs. Frisby move her home?"],
  h: ["프리스비 부인은 이 책에서 왜 님 쥐들의 도움이 필요한가요?",
      "중요한 문제로 다른 사람에게 도움을 청해 본 적이 있나요?",
      "님 쥐들은 왜 프리스비 부인이 집을 옮기는 것을 도울 수 있었을까요?"] };
ACT["S5170"] = { s: "This story is written in the form of a diary of a young boy in the Catskill Mountains.",
  q: ["How does this book tell the boy's story, and where does he live?",
      "Have you ever kept a diary of your daily life? What did you write about?",
      "What do you think would be the hardest part of living alone in the mountains?"],
  h: ["이 책은 소년의 이야기를 어떤 방식으로 전하고, 그는 어디에 사나요?",
      "너의 일상을 일기로 써 본 적이 있나요? 무엇을 적었나요?",
      "산속에서 혼자 사는 것 중 가장 힘든 부분은 무엇일 것 같나요?"] };
ACT["S5171"] = { s: "Thirteen-year-old Anna, conceived to provide blood and bone marrow for her sister Kate who was diagnosed with a rare form of leukemia decides to sue her parents when her mother wants her to donate a kidney.",
  q: ["Why was Anna conceived, according to this book, and what does she decide to do?",
      "Have you ever had to make a hard decision about helping a family member?",
      "Why do you think Anna decides to sue her own parents?"],
  h: ["애나는 이 책에서 왜 태어났고, 그녀는 무엇을 하기로 결심하나요?",
      "가족을 돕는 일로 힘든 결정을 내려야 했던 적이 있나요?",
      "애나는 왜 자신의 부모님을 고소하기로 할까요?"] };
ACT["S5172"] = { s: "James, one of Peter Pan's original Lost Boys, asks George Darling and his wife to help him find a secret cache of starstuff.",
  q: ["What does James ask the Darlings to help him find in this book?",
      "Have you ever asked an adult for help finding something important?",
      "What do you imagine 'starstuff' is, based on the title and summary?"],
  h: ["제임스는 이 책에서 달링 부부에게 무엇을 찾아 달라고 부탁하나요?",
      "중요한 것을 찾기 위해 어른에게 도움을 청해 본 적이 있나요?",
      "제목과 요약을 보면 '스타스터프'는 무엇일 것 같나요?"] };
ACT["S5173"] = { s: "Nightmares are leaking out of Neverland making time start to move, and Wendy tries to save Peter Pan's life.",
  q: ["What strange thing starts happening in Neverland in this book, and what does Wendy try to do?",
      "Have you ever had a nightmare that felt very real? What was it about?",
      "Why do you think time starting to move in Neverland is dangerous for Peter Pan?"],
  h: ["네버랜드에서는 이 책에서 어떤 이상한 일이 일어나기 시작하고, 웬디는 무엇을 하려고 하나요?",
      "아주 생생하게 느껴지는 악몽을 꾼 적이 있나요? 무슨 꿈이었나요?",
      "네버랜드에서 시간이 흐르기 시작하는 것이 왜 피터 팬에게 위험할까요?"] };
ACT["S5174"] = { s: "While attending a strict academy for potential princesses with the other girls, fourteen-year-old Miri discovers unexpected talents and connections to her homeland.",
  q: ["What does Miri discover about herself while attending the academy in this book?",
      "Have you ever discovered a talent you didn't know you had?",
      "Why do you think Miri's connection to her homeland matters in this story?"],
  h: ["미리는 이 책에서 아카데미에 다니며 자신에 대해 무엇을 발견하나요?",
      "네가 가진 줄 몰랐던 재능을 발견한 적이 있나요?",
      "미리와 고향의 연결이 이 이야기에서 왜 중요할까요?"] };
ACT["S5176"] = { s: "The Animals of the Hill prepare for the \"new people\" moving into the Big House.",
  q: ["What are the Animals of the Hill preparing for in this book?",
      "Have you ever felt nervous about new people moving into your neighborhood?",
      "What do you think the animals hope the new people will be like?"],
  h: ["언덕의 동물들은 이 책에서 무엇을 준비하고 있나요?",
      "새로운 사람들이 동네로 이사 온다는 소식에 긴장해 본 적이 있나요?",
      "동물들은 새로운 사람들이 어떤 사람이길 바랄까요?"] };
ACT["S5177"] = { s: "Jess's grandfather insists on returning to the river he had known as a boy to finish a special painting and fulfill his dream.",
  q: ["What does Jess's grandfather want to do in this book, and where does he return to?",
      "Have you ever helped an older family member finish something important to them?",
      "Why do you think this painting and this river matter so much to Jess's grandfather?"],
  h: ["제스의 할아버지는 이 책에서 무엇을 하고 싶어 하고, 어디로 돌아가나요?",
      "나이 드신 가족이 중요한 일을 끝내도록 도와드린 적이 있나요?",
      "왜 이 그림과 이 강이 제스의 할아버지에게 그렇게 중요할까요?"] };
ACT["S5178"] = { s: "Warmth, humor and hard times make a black family strong in Depression-era Mississippi.",
  q: ["What kind of times does this book's family go through, and what keeps them strong?",
      "Has your family ever gotten through a hard time together? What helped?",
      "Why do you think warmth and humor can help a family survive hard times?"],
  h: ["이 책의 가족은 어떤 힘든 시절을 겪고, 무엇이 그들을 강하게 지켜 주나요?",
      "가족이 함께 힘든 시간을 이겨 낸 적이 있나요? 무엇이 도움이 되었나요?",
      "따뜻함과 유머가 왜 가족이 힘든 시절을 버티는 데 도움이 될까요?"] };
ACT["S5179"] = { s: "When his father is jailed for stealing food for his family, a young black boy grows in courage and understanding by learning to read and through his relation with his devoted dog, Sounder.",
  q: ["Why is the boy's father jailed in this book, and how does the boy grow afterward?",
      "Have you ever had a pet or animal that helped you through a hard time?",
      "Why do you think learning to read helps the boy grow in courage and understanding?"],
  h: ["소년의 아버지는 이 책에서 왜 감옥에 갇히고, 그 뒤 소년은 어떻게 성장하나요?",
      "힘든 시간을 함께 이겨 낸 반려동물이 있었나요?",
      "글을 읽는 법을 배우는 것이 왜 소년이 용기와 이해심을 키우는 데 도움이 될까요?"] };
ACT["S5180"] = { s: "This biography tells the life and accomplishments of Apple founder Steve Jobs and discusses the impact of his ideas on life in the twenty-first century.",
  q: ["What does this book say about Steve Jobs's impact on life in the twenty-first century?",
      "Have you ever used a product or idea that changed the way you do something?",
      "What do you think it means to 'think differently,' based on the title of this book?"],
  h: ["이 책은 스티브 잡스가 21세기 삶에 어떤 영향을 미쳤다고 말하나요?",
      "네가 무언가를 하는 방식을 바꿔 준 물건이나 생각을 써 본 적이 있나요?",
      "이 책의 제목을 보면 '다르게 생각한다'는 것은 무슨 뜻일 것 같나요?"] };
ACT["S5181"] = { s: "An Andalusian shepherd boy travels to the Egyptian desert in search of a treasure buried in the Pyramids. The journey to find worldly goods turns into a meditation on the treasures found within.",
  q: ["What does the shepherd boy travel to find in this book, and what does his journey become about instead?",
      "Have you ever gone looking for one thing and found something different but valuable instead?",
      "What do you think 'the treasures found within' means, based on this summary?"],
  h: ["양치기 소년은 이 책에서 무엇을 찾으러 떠나고, 그의 여정은 결국 무엇에 관한 것이 되나요?",
      "다른 것을 찾다가 뜻밖에 더 소중한 것을 발견한 적이 있나요?",
      "이 요약에서 '내면에서 찾은 보물'은 무엇을 뜻할 것 같나요?"] };
ACT["S5182"] = { s: "Klaus and Violet Baudelaire meet another well-read person in the perilous Mortmain Mountains. He helps them try to rescue Sunny from the villainous Count Olaf and his henchmen as they all are near ‘the last safe place.’ Book #10",
  q: ["Who do Klaus and Violet meet in the Mortmain Mountains in this book, and what do they try to do?",
      "Have you ever teamed up with someone new to solve a tough problem?",
      "What do you think 'the last safe place' might be like?"],
  h: ["클라우스와 바이올렛은 이 책에서 모트메인 산맥에서 누구를 만나고, 무엇을 하려고 하나요?",
      "어려운 문제를 풀기 위해 새로운 사람과 힘을 합친 적이 있나요?",
      "'마지막 안전한 곳'은 어떤 곳일 것 같나요?"] };
ACT["S5184"] = { s: "Bored and lonely after his family moves to a place called \"Out-With\" in 1942, Bruno, the son of a Nazi officer, befriends a boy who lives behind a wire fence.",
  q: ["Who does Bruno become friends with in this book, and where does that boy live?",
      "Have you ever made an unexpected friend in a new place?",
      "Why do you think Bruno is bored and lonely after his family's move?"],
  h: ["브루노는 이 책에서 누구와 친구가 되고, 그 친구는 어디에 사나요?",
      "새로운 곳에서 뜻밖의 친구를 사귄 적이 있나요?",
      "브루노는 왜 이사 온 뒤 지루하고 외로워할까요?"] };
ACT["S5186"] = { s: "Buck, a sled dog, must decide whether to stay with his master or listen to his instincts.",
  q: ["What choice must Buck make in this book?",
      "Have you ever had to choose between what felt comfortable and what felt like your true instinct?",
      "Why do you think this decision is so hard for Buck?"],
  h: ["벅은 이 책에서 어떤 선택을 해야 하나요?",
      "익숙하고 편한 것과 진짜 마음이 이끄는 것 사이에서 고민해 본 적이 있나요?",
      "벅에게 이 결정이 왜 그렇게 힘들까요?"] };
ACT["S5187"] = { s: "In seventeenth century England, a terrible accident forces orphaned Phillip to flee London in fear for his life.",
  q: ["What forces Phillip to flee London in this book?",
      "Have you ever had to leave somewhere quickly because of an accident or emergency?",
      "What do you imagine Phillip's life is like after he flees London?"],
  h: ["필립은 이 책에서 무엇 때문에 런던을 떠나야 하나요?",
      "사고나 급한 일 때문에 어딘가를 급히 떠나야 했던 적이 있나요?",
      "런던을 떠난 뒤 필립의 삶은 어떨 것 같나요?"] };
ACT["S5189"] = { s: "It is a game for six children, until an oracle tells the truth and a murderer is seen.",
  q: ["What game do the six children play in this book, and what happens because of it?",
      "Have you ever played a pretend game with friends that felt very real?",
      "Why do you think the game leads to something so serious?"],
  h: ["여섯 아이는 이 책에서 어떤 놀이를 하고, 그로 인해 무슨 일이 일어나나요?",
      "친구들과 아주 진짜처럼 느껴지는 상상 놀이를 해 본 적이 있나요?",
      "그 놀이는 왜 그렇게 심각한 일로 이어질까요?"] };
ACT["S5190"] = { s: "Georgie's dream, to be able to fly, is fleetingly fulfilled when she makes a friend of a Canada goose.",
  q: ["What is Georgie's dream in this book, and how is it fulfilled?",
      "Have you ever had a dream that came true, even for a short time?",
      "Why do you think befriending a goose helps Georgie fly?"],
  h: ["조지의 꿈은 이 책에서 무엇이고, 어떻게 잠깐이나마 이루어지나요?",
      "짧게라도 이루어진 꿈이 있었나요?",
      "기러기와 친구가 되는 것이 조지가 나는 데 왜 도움이 될까요?"] };
ACT["S5191"] = { s: "The Baudelaire orphans are still pursued by the evil Count Olaf. They attempt to reach a very important VFD meeting, but first they have to travel in a rattletrap submarine to the Gorgonian Grotto, a dangerous underwater cave, in order to find the sugar bowl. Book #11",
  q: ["What do the Baudelaire orphans travel to find in this book, and how do they get there?",
      "Have you ever gone on a trip in an unusual vehicle, like a boat or a submarine ride?",
      "Why do you think the sugar bowl is so important to find?"],
  h: ["보들레어 남매는 이 책에서 무엇을 찾으러 가고, 어떻게 그곳까지 가나요?",
      "배나 잠수함처럼 특별한 탈것을 타고 여행해 본 적이 있나요?",
      "설탕 그릇을 찾는 일이 왜 그렇게 중요할까요?"] };
ACT["S5194"] = { s: "Nobody Owens is a normal boy, except that he has been raised by ghosts.",
  q: ["What makes Nobody Owens different from other boys in this book?",
      "Who has taken care of you and raised you? How are they important to you?",
      "What do you think it would be like to be raised by ghosts?"],
  h: ["노바디 오언스는 이 책에서 다른 소년들과 무엇이 다른가요?",
      "너를 돌보고 키워 준 사람은 누구인가요? 그들은 너에게 왜 소중한가요?",
      "유령들에게 키워지는 것은 어떤 느낌일 것 같나요?"] };
ACT["S5197"] = { s: "Fearing that her legal guardian plans to abandon her to return to France, ten-year-old aspiring scientist Lucky Trimble determines to run away to seek the Higher Power.",
  q: ["What does Lucky fear in this book, and what does she decide to do about it?",
      "Have you ever worried that someone important to you might leave?",
      "What do you think Lucky hopes to find by seeking the 'Higher Power'?"],
  h: ["럭키는 이 책에서 무엇을 두려워하고, 그것 때문에 무엇을 결심하나요?",
      "소중한 사람이 떠날까 봐 걱정한 적이 있나요?",
      "럭키는 '높은 힘'을 찾으면서 무엇을 얻고 싶어 할까요?"] };
ACT["S5198"] = { s: "Matt lives a special life as the young clone of El Patron, the 140-year-old leader of a corrupt drug empire nestled between Mexico and the United States.",
  q: ["Who is Matt a clone of in this book, and what kind of life does El Patron lead?",
      "Have you ever felt like people expected you to be like someone else in your family?",
      "Why do you think being a clone of El Patron makes Matt's life 'special'?"],
  h: ["맷은 이 책에서 누구의 복제인간이고, 엘 파트론은 어떤 삶을 사는 사람인가요?",
      "가족 중 누군가처럼 되어야 한다고 느낀 적이 있나요?",
      "엘 파트론의 복제인간이라는 것이 맷의 삶을 왜 '특별하게' 만들까요?"] };
ACT["S5199"] = { s: "An orphan living and repairing clocks within the walls of a Paris train station in 1931, meets a mysterious toyseller.",
  q: ["Where does Hugo live in this book, and what does he do there?",
      "Have you ever met someone mysterious who ended up being important to your life?",
      "What do you imagine the mysterious toyseller's secret is?"],
  h: ["휴고는 이 책에서 어디에 살고, 그곳에서 무엇을 하나요?",
      "신비로운 사람을 만났는데 나중에 너에게 중요한 사람이 된 적이 있나요?",
      "그 신비로운 장난감 장수의 비밀은 무엇일 것 같나요?"] };
