// 간이 학습 질문 — Book No. S52 묶음. 사람이 아니라 AI 가 한 번 쓰고 굳힌 파일이다.
window.ACT = window.ACT || {};
var ACT = window.ACT;
ACT["S5200"] = { s: "This book tells the lives of four Chinese women, and how the death of one brings her daughter into the fold and creates a new understanding for each.",
  q: ["This book tells the lives of four Chinese women, and how the death of one brings her daughter into the fold. Write a paragraph imagining what \"a new understanding\" the daughter and the other women might have reached.",
      "This book is about a daughter who is brought into a group of women after her mother's death. Write a paragraph about a group of people (family, friends, or others) that you feel closely connected to and why.",
      "Write a paragraph giving your opinion on whether losing someone can really bring other people closer together, using this book's story as an example."],
  h: ["이 책은 네 명의 중국인 여성의 삶과, 그중 한 명이 죽은 뒤 그 딸이 무리 안으로 들어오게 되는 이야기를 담고 있어요. 딸과 다른 여성들이 다다랐을 '새로운 이해'가 무엇이었을지 상상해서 문단으로 써 보세요.",
      "이 책은 엄마가 돌아가신 뒤 딸이 한 여성들의 모임 안으로 들어오게 되는 이야기예요. 여러분이 가깝게 느끼는 사람들의 모임(가족, 친구, 또는 다른 무리)은 무엇이고 왜 그런지 문단으로 써 보세요.",
      "누군가를 잃는 일이 정말로 다른 사람들을 더 가깝게 만들어 줄 수 있는지, 이 책의 이야기를 예로 들어 여러분의 의견을 문단으로 써 보세요."] };
ACT["S5201"] = { s: "This book contains selected stories from Kipling's two JUNGLE BOOKS and chronicles the adventures of Mowgli, the boy raised by wolves in the jungle.",
  q: ["This book chronicles the adventures of Mowgli, the boy raised by wolves in the jungle. Choose one adventure you imagine Mowgli having in the jungle and write a paragraph describing it.",
      "Mowgli was raised by wolves instead of humans. Write a paragraph about someone (a person, pet, or even a story character) who raised or took care of you, and what you learned from them.",
      "Write a paragraph giving your opinion on what you think would be the hardest part of growing up raised by wolves in the jungle, and why."],
  h: ["이 책은 늑대들 손에 자란 소년 모글리가 정글에서 겪는 모험을 담고 있어요. 모글리가 정글에서 겪었을 법한 모험 하나를 상상해서 골라, 그 모험을 문단으로 묘사해 보세요.",
      "모글리는 사람이 아니라 늑대들 손에 자랐어요. 나를 키워 주거나 돌봐 준 존재(사람, 반려동물, 또는 이야기 속 인물이라도)와 그에게서 배운 것을 문단으로 써 보세요.",
      "정글에서 늑대들 손에 자라난다면 가장 힘들 부분은 무엇일지 여러분의 생각과 이유를 문단으로 써 보세요."] };
ACT["S5202"] = { s: "Amir, haunted by his betrayal of Hassan, the son of his father's servant and a childhood friend, comes back to Kabul as an adult after he learns Hassan has been killed.",
  q: ["Amir is haunted by his betrayal of his childhood friend Hassan. Write a paragraph imagining what that betrayal might have been, based on what you read in the book.",
      "Amir returns to Kabul as an adult because of something that happened to his childhood friend. Write a paragraph about a childhood friend you still think about, and what you remember most about them.",
      "Write a paragraph giving your opinion on whether it is possible to make up for betraying a friend, even many years later, and explain your reasoning."],
  h: ["아미르는 어린 시절 친구 하산을 배신한 일 때문에 괴로워해요. 책에서 읽은 내용을 바탕으로, 그 배신이 무엇이었을지 상상해서 문단으로 써 보세요.",
      "아미르는 어린 시절 친구에게 일어난 일 때문에 어른이 되어 카불로 돌아가요. 여러분이 아직도 떠올리는 어릴 적 친구와, 그 친구에 대해 가장 기억나는 것을 문단으로 써 보세요.",
      "친구를 배신한 일을 아주 오랜 시간이 지난 뒤라도 되갚거나 만회할 수 있다고 생각하는지, 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S5203"] = { s: "In medieval England, a nameless, homeless girl is taken in by a sharp-tempered midwife, and in spite of obstacles and hardship, eventually gains the three things she most wants.",
  q: ["The homeless girl in this book eventually gains the three things she most wants. Write a paragraph imagining what those three things might be, based on her situation as a nameless, homeless girl.",
      "The girl in this book faces obstacles and hardship before reaching what she wants. Write a paragraph about a goal you worked hard for despite difficulties, and how you felt when you got closer to it.",
      "Write a paragraph giving your opinion on why a sharp-tempered midwife might choose to take in a homeless girl, even though she seems difficult to please."],
  h: ["이 책 속 집 없는 소녀는 결국 자신이 가장 원하던 세 가지를 얻게 돼요. 이름도 집도 없던 소녀의 상황을 바탕으로, 그 세 가지가 무엇이었을지 상상해서 문단으로 써 보세요.",
      "이 책 속 소녀는 원하는 것을 얻기 전에 여러 장애물과 어려움을 겪어요. 여러분이 어려움 속에서도 열심히 노력했던 목표와, 그것에 가까워졌을 때의 기분을 문단으로 써 보세요.",
      "까다롭고 성질이 급한 산파가 왜 집 없는 소녀를 거두었을지, 여러분의 생각을 문단으로 써 보세요."] };
ACT["S5204"] = { s: "Homer P. Figg runs away from his ruthless guardian's home, and sets out to find his beloved older brother, Harold, who has been illegally sold into the Union Army.",
  q: ["Homer P. Figg sets out to find his brother Harold, who was illegally sold into the Union Army. Write a paragraph imagining the journey Homer might take to find him.",
      "Homer runs away to find his beloved older brother. Write a paragraph about a sibling or someone close to you that you would go to great lengths to help.",
      "Write a paragraph giving your opinion on whether Homer was right to run away from his guardian's home to search for his brother, and explain why."],
  h: ["호머 P. 피그는 불법으로 북군에 팔려 간 형 해럴드를 찾아 나서요. 호머가 형을 찾기 위해 떠났을 여정을 상상해서 문단으로 써 보세요.",
      "호머는 사랑하는 형을 찾기 위해 집을 뛰쳐나가요. 여러분이 무슨 일이 있어도 도와주고 싶은 형제자매나 가까운 사람을 문단으로 써 보세요.",
      "호머가 형을 찾기 위해 보호자의 집에서 도망친 것이 옳았다고 생각하는지, 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S5205"] = { s: "After passing a series of mind-bending tests, four children are designated for a secret mission to go undercover at the Learning Institute for the Very Enlightened.",
  q: ["Four children pass mind-bending tests before going undercover at the Learning Institute for the Very Enlightened. Write a paragraph imagining what kind of test you think would be hardest for you to pass.",
      "The children in this book go undercover on a secret mission. Write a paragraph about a secret or a challenge you kept just between yourself and a few close people.",
      "Write a paragraph giving your opinion on whether it is a good idea to send children, rather than adults, on a secret undercover mission, and explain your reasoning."],
  h: ["네 아이는 '아주 계몽된 이들을 위한 학습원'에 잠입하기 전에 머리를 어지럽히는 시험들을 통과해요. 여러분이라면 어떤 시험이 가장 통과하기 어려울지 상상해서 문단으로 써 보세요.",
      "이 책 속 아이들은 비밀 임무를 위해 신분을 숨기고 잠입해요. 여러분이 몇몇 가까운 사람들과만 나눈 비밀이나 도전을 문단으로 써 보세요.",
      "어른이 아니라 아이들을 비밀 잠입 임무에 보내는 것이 좋은 생각이라고 생각하는지, 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S5206"] = { s: "Reynie, Kate, Sticky, and Constance go to Stonetown to investigate an unexplained blackout.",
  q: ["Reynie, Kate, Sticky, and Constance investigate an unexplained blackout in Stonetown. Write a paragraph imagining what clues they might have found as they investigated.",
      "This book is about a team of friends solving a mystery together. Write a paragraph about a time you worked with friends to solve a problem or figure something out.",
      "Write a paragraph giving your opinion on what might cause a whole town's electricity to go out suddenly, and how you would start investigating it."],
  h: ["레이니, 케이트, 스티키, 콘스턴스는 스톤타운에서 일어난 알 수 없는 정전을 조사해요. 이들이 조사하며 찾아냈을 단서들을 상상해서 문단으로 써 보세요.",
      "이 책은 친구들로 이루어진 팀이 함께 수수께끼를 푸는 이야기예요. 여러분이 친구들과 함께 문제를 풀거나 무언가를 알아냈던 경험을 문단으로 써 보세요.",
      "마을 전체의 전기가 갑자기 나가는 원인이 무엇일 수 있는지, 그리고 여러분이라면 어떻게 조사를 시작할지 문단으로 써 보세요."] };
ACT["S5207"] = { s: "An old fisherman catches a giant marlin, only to have sharks strip it to the bone.",
  q: ["The old fisherman in this book catches a giant marlin, but sharks strip it to the bone. Write a paragraph imagining how the fisherman must have felt watching that happen.",
      "The fisherman worked hard to catch something, only to lose almost all of it. Write a paragraph about a time you worked hard for something and did not get to keep or enjoy the full result.",
      "Write a paragraph giving your opinion on whether the fisherman's effort was still worthwhile even though the sharks took the marlin, and explain your reasoning."],
  h: ["이 책 속 늙은 어부는 거대한 청새치를 잡지만, 상어들이 그것을 뼈만 남기고 다 뜯어 먹어요. 그 모습을 지켜보던 어부의 마음이 어땠을지 상상해서 문단으로 써 보세요.",
      "어부는 힘들게 무언가를 잡았지만 거의 다 잃고 말아요. 여러분이 열심히 노력했지만 그 결과를 온전히 가지거나 누리지 못했던 경험을 문단으로 써 보세요.",
      "상어들이 청새치를 빼앗아 갔어도 어부의 노력이 여전히 가치 있었다고 생각하는지, 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S5208"] = { s: "Kino, a poor Mexican pearl-diver, believes he has received the answer to his prayers when he finds a great pearl worth a fortune, but tragedy soon begins.",
  q: ["Kino believes the great pearl he finds is the answer to his prayers, but tragedy soon begins. Write a paragraph imagining what kind of tragedy might follow finding something so valuable.",
      "Kino prays for something that could change his life and then finds it. Write a paragraph about something you have wished or hoped for, and what you think would change if you got it.",
      "Write a paragraph giving your opinion on whether finding sudden wealth, like Kino's pearl, is more likely to help or harm a person's life, and explain why."],
  h: ["키노는 자신이 발견한 커다란 진주가 기도의 응답이라 믿지만, 곧 비극이 시작돼요. 그렇게 값진 것을 발견한 뒤 어떤 비극이 따라올 수 있을지 상상해서 문단으로 써 보세요.",
      "키노는 삶을 바꿀 수 있는 무언가를 기도하다가 결국 그것을 찾아내요. 여러분이 바라거나 소망해 온 것과, 그것을 얻는다면 무엇이 달라질지 문단으로 써 보세요.",
      "키노의 진주처럼 갑작스러운 부를 얻는 것이 사람의 삶에 도움이 될 가능성이 큰지 해가 될 가능성이 큰지, 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S5209"] = { s: "A boy travels through time and space to the Lands Beyond.",
  q: ["A boy in this book travels through time and space to the Lands Beyond. Write a paragraph imagining what kind of place the Lands Beyond might be.",
      "The boy in this book goes on a journey to a completely new place. Write a paragraph about a new place you visited or would like to visit, and what surprised or excited you about it.",
      "Write a paragraph giving your opinion on whether you would want to travel through time and space like the boy in this book, and explain why or why not."],
  h: ["이 책 속 소년은 시간과 공간을 넘어 '저 너머의 땅'으로 여행해요. 그 저 너머의 땅이 어떤 곳일지 상상해서 문단으로 써 보세요.",
      "이 책 속 소년은 완전히 새로운 곳으로 여행을 떠나요. 여러분이 가 보았거나 가 보고 싶은 새로운 곳과, 그곳의 무엇이 놀랍거나 신났는지 문단으로 써 보세요.",
      "이 책 속 소년처럼 시간과 공간을 넘어 여행하고 싶은지, 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S5210"] = { s: "John and Lorraine are two high school students who befriend Mr. Pignati, a lonely old man with an terrible secret.",
  q: ["John and Lorraine befriend Mr. Pignati, a lonely old man with a terrible secret. Write a paragraph imagining what that secret might be.",
      "John and Lorraine become friends with someone much older than them. Write a paragraph about a friendship you have with someone older or younger than you, and what you learned from them.",
      "Write a paragraph giving your opinion on why two teenagers might choose to spend time with a lonely old man, and explain your reasoning."],
  h: ["존과 로레인은 끔찍한 비밀을 가진 외로운 노인 피그나티 씨와 친구가 돼요. 그 비밀이 무엇일지 상상해서 문단으로 써 보세요.",
      "존과 로레인은 자신들보다 훨씬 나이 많은 사람과 친구가 돼요. 여러분이 나이가 훨씬 많거나 어린 사람과 맺은 우정과, 그에게서 배운 것을 문단으로 써 보세요.",
      "두 십 대가 왜 외로운 노인과 시간을 보내기로 했을지, 여러분의 생각과 이유를 문단으로 써 보세요."] };
ACT["S5212"] = { s: "During the 17th century, a woman guilty of adultery is forced to mark an A as a visible sign of her sin.",
  q: ["The woman in this book is forced to wear a mark as a visible sign of her mistake. Write a paragraph imagining how she must have felt having to wear that mark in public every day.",
      "This book is about someone being publicly judged for a mistake. Write a paragraph about a time you made a mistake and how you felt when others knew about it.",
      "Write a paragraph giving your opinion on whether it is fair to force someone to publicly display a symbol of their past mistake, and explain your reasoning."],
  h: ["이 책 속 여성은 자신의 잘못을 보여 주는 표식을 억지로 달고 다녀야 해요. 매일 사람들 앞에서 그 표식을 달고 다녀야 했던 그녀의 마음이 어땠을지 상상해서 문단으로 써 보세요.",
      "이 책은 누군가 잘못 때문에 사람들 앞에서 심판받는 이야기예요. 여러분이 잘못을 저지르고 다른 사람들이 그 사실을 알았을 때 느꼈던 기분을 문단으로 써 보세요.",
      "누군가에게 과거 잘못을 보여 주는 표식을 억지로 달게 하는 것이 공정하다고 생각하는지, 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S5214"] = { s: "Young Jessie, a musician, is hired to play for the slaves aboard a ship bound for America.",
  q: ["Jessie is hired to play music for the slaves aboard a ship bound for America. Write a paragraph imagining how Jessie must have felt playing music in that situation.",
      "Jessie uses music in a very difficult situation. Write a paragraph about a time music made you feel a certain way, whether happy, sad, or something else.",
      "Write a paragraph giving your opinion on how it would feel to be forced to use your musical talent to serve a cruel purpose, and explain your reasoning."],
  h: ["제시는 미국으로 향하는 배에 탄 노예들을 위해 음악을 연주하도록 고용돼요. 그런 상황에서 음악을 연주해야 했던 제시의 마음이 어땠을지 상상해서 문단으로 써 보세요.",
      "제시는 아주 힘든 상황에서 음악을 사용해요. 음악이 여러분에게 어떤 기분(기쁨, 슬픔, 또는 다른 감정)을 느끼게 했던 순간을 문단으로 써 보세요.",
      "자신의 음악적 재능을 잔인한 목적을 위해 억지로 써야 한다면 어떤 기분일지, 여러분의 생각과 이유를 문단으로 써 보세요."] };
ACT["S5215"] = { s: "Rosa knows how to heal sickness with wild plants medicines. But she cannot go outside with a price on her head for helping the rebels. Instead, she turns caves into hospitals for those who know how to find her.",
  q: ["Rosa turns caves into hospitals for people who need her healing help. Write a paragraph imagining what it would be like to run a hospital hidden inside a cave.",
      "Rosa uses her knowledge of wild plant medicine to help others, even at great risk to herself. Write a paragraph about a skill you have that you could use to help someone else.",
      "Write a paragraph giving your opinion on whether Rosa was right to keep helping the rebels even though there was a price on her head, and explain your reasoning."],
  h: ["로사는 동굴을 자신의 도움이 필요한 사람들을 위한 병원으로 바꿔요. 동굴 속에 숨겨진 병원을 운영한다면 어떨지 상상해서 문단으로 써 보세요.",
      "로사는 자신이 위험을 무릅쓰면서도 야생 식물 약초 지식을 이용해 다른 사람들을 도와요. 여러분이 가진, 다른 사람을 돕는 데 쓸 수 있는 재주를 문단으로 써 보세요.",
      "자신에게 현상금이 걸려 있는데도 로사가 계속 반란군을 도운 것이 옳았다고 생각하는지, 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S5216"] = { s: "This tale relates the adventures of Professor William Waterman Sherman, who journeys in a balloon across the Pacific Ocean, survives the volcanic eruption, and is eventually rescued in the Atlantic Ocean.",
  q: ["Professor Sherman survives a volcanic eruption during his balloon journey across the Pacific Ocean. Write a paragraph imagining what that moment of the eruption might have been like for him.",
      "Professor Sherman travels across an ocean and ends up somewhere he never expected. Write a paragraph about a trip or adventure that did not go the way you planned.",
      "Write a paragraph giving your opinion on whether traveling alone by balloon across an ocean, like Professor Sherman did, would be more exciting or more frightening, and explain why."],
  h: ["셔먼 교수는 태평양을 가로지르는 열기구 여행 중에 화산 폭발에서 살아남아요. 그 폭발의 순간이 그에게 어땠을지 상상해서 문단으로 써 보세요.",
      "셔먼 교수는 바다를 건너다 전혀 예상하지 못한 곳에 도착하게 돼요. 여러분이 계획한 대로 흘러가지 않았던 여행이나 모험을 문단으로 써 보세요.",
      "셔먼 교수처럼 혼자 열기구로 바다를 건너는 여행이 더 신날지 더 무서울지, 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S5217"] = { s: "An old hound and two kittens endure separation, danger, and many other tribulations. And they finally end up reunited and free.",
  q: ["The old hound and two kittens in this book are separated and face many dangers before being reunited. Write a paragraph imagining what dangers they might have faced along the way.",
      "This book is about animals who are separated and then finally reunited. Write a paragraph about a time you were separated from someone or something you cared about and then got to be with them again.",
      "Write a paragraph giving your opinion on what helped the hound and the kittens survive their separation and dangers long enough to be reunited, and explain your reasoning."],
  h: ["이 책 속 늙은 사냥개와 새끼 고양이 두 마리는 헤어진 뒤 다시 만나기까지 여러 위험을 겪어요. 그 과정에서 겪었을 위험들을 상상해서 문단으로 써 보세요.",
      "이 책은 헤어졌다가 마침내 다시 만나는 동물들의 이야기예요. 여러분이 소중한 누군가나 무언가와 헤어졌다가 다시 함께하게 된 경험을 문단으로 써 보세요.",
      "사냥개와 새끼 고양이들이 헤어짐과 위험 속에서도 살아남아 다시 만날 수 있었던 이유가 무엇이었을지, 여러분의 생각을 문단으로 써 보세요."] };
ACT["S5218"] = { s: "Four students, with their own individual stories, develop a special bond.",
  q: ["Four students with their own individual stories develop a special bond in this book. Write a paragraph imagining what kind of different stories or backgrounds these four students might have.",
      "The students in this book become close even though they started out different from each other. Write a paragraph about a friend you became close to even though you were different in some way.",
      "Write a paragraph giving your opinion on what usually helps a group of very different people form a special bond, and explain your reasoning."],
  h: ["이 책에서는 저마다 다른 사연을 가진 네 학생이 특별한 유대를 쌓아요. 이 네 학생이 각자 어떤 다른 사연이나 배경을 가졌을지 상상해서 문단으로 써 보세요.",
      "이 책 속 학생들은 서로 달랐지만 결국 가까워져요. 여러분이 서로 다른 점이 있었지만 가까워진 친구에 대해 문단으로 써 보세요.",
      "아주 다른 사람들이 모인 무리가 특별한 유대를 만드는 데 보통 무엇이 도움이 되는지, 여러분의 생각과 이유를 문단으로 써 보세요."] };
ACT["S5220"] = { s: "Eight-year-old Scottish boy Kirstie finds a large egg which hatches into an unusual sea creature, and as he grows her family must decide what to do with him.",
  q: ["Kirstie finds a large egg that hatches into an unusual sea creature. Write a paragraph imagining what this sea creature looks like and how it behaves as it grows.",
      "Kirstie's family must decide what to do with the sea creature as it grows. Write a paragraph about a decision your family has had to make together about a pet or something you found.",
      "Write a paragraph giving your opinion on what a family should do if they found and raised an unusual creature that kept growing bigger, and explain your reasoning."],
  h: ["커스티는 커다란 알을 발견하고, 그 알에서 특이한 바다 생물이 태어나요. 이 바다 생물이 자라면서 어떤 모습이고 어떻게 행동할지 상상해서 문단으로 써 보세요.",
      "바다 생물이 자라면서 커스티의 가족은 그것을 어떻게 할지 결정해야 해요. 여러분의 가족이 반려동물이나 발견한 것을 두고 함께 내려야 했던 결정을 문단으로 써 보세요.",
      "계속 커지는 특이한 생물을 발견해 키우게 된 가족이라면 어떻게 해야 할지, 여러분의 생각과 이유를 문단으로 써 보세요."] };
ACT["S5221"] = { s: "An African American family living in Michigan in 1963 are drastically changed after a trip to Birmingham, Alabama, where racial violence erupts.",
  q: ["The Watson family is drastically changed after a trip to Birmingham, Alabama, where racial violence erupts. Write a paragraph imagining how that trip might have changed the way the family saw the world.",
      "This book shows how a difficult event during a trip changed a family forever. Write a paragraph about an experience that changed the way you think about something.",
      "Write a paragraph giving your opinion on why it is important for children today to read about events like the racial violence described in this book, and explain your reasoning."],
  h: ["왓슨 가족은 인종 폭력이 일어난 앨라배마주 버밍햄 여행을 다녀온 뒤 크게 달라져요. 그 여행이 가족이 세상을 보는 방식을 어떻게 바꾸었을지 상상해서 문단으로 써 보세요.",
      "이 책은 여행 중 겪은 힘든 사건이 한 가족을 영원히 바꿔 놓는 이야기예요. 여러분이 무언가를 생각하는 방식을 바꿔 놓은 경험을 문단으로 써 보세요.",
      "오늘날 아이들이 이 책에 나오는 인종 폭력 같은 사건들에 대해 읽는 것이 왜 중요한지, 여러분의 생각과 이유를 문단으로 써 보세요."] };
ACT["S5223"] = { s: "Sixteen game players, heirs to Sam Westing's fabulous fortune, are all suspected of his death.",
  q: ["Sixteen heirs to Sam Westing's fortune are all suspected of his death. Write a paragraph imagining how you would begin investigating which of the sixteen might be responsible.",
      "In this book, sudden wealth makes a group of people become suspects. Write a paragraph about a time something valuable was involved in a disagreement or mystery among people you know.",
      "Write a paragraph giving your opinion on whether leaving a fortune to sixteen different heirs was a wise decision by Sam Westing, and explain your reasoning."],
  h: ["샘 웨스팅의 재산을 물려받을 열여섯 명의 상속인 모두가 그의 죽음의 용의자예요. 여러분이라면 이 열여섯 명 중 누가 범인인지 어떻게 조사를 시작할지 상상해서 문단으로 써 보세요.",
      "이 책에서는 갑작스러운 재산 때문에 여러 사람이 용의자가 돼요. 여러분이 아는 사람들 사이에서 귀중한 무언가가 다툼이나 수수께끼에 얽혔던 일을 문단으로 써 보세요.",
      "샘 웨스팅이 재산을 열여섯 명의 상속인에게 나눠 남긴 것이 현명한 결정이었다고 생각하는지, 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S5224"] = { s: "The Huns and Magyars migrate from Asia to Europe, where they want to get a permanent home.",
  q: ["The Huns and Magyars migrate from Asia to Europe searching for a permanent home. Write a paragraph imagining what challenges they might have faced during such a long migration.",
      "This book is about a whole people searching for a place to call home. Write a paragraph about what \"home\" means to you and why it matters.",
      "Write a paragraph giving your opinion on what would be the hardest part of leading a whole group of people to find a new permanent home, and explain your reasoning."],
  h: ["훈족과 마자르족은 영원히 머물 곳을 찾아 아시아에서 유럽으로 이주해요. 이렇게 긴 이주 동안 그들이 겪었을 어려움을 상상해서 문단으로 써 보세요.",
      "이 책은 한 민족 전체가 고향이라 부를 곳을 찾는 이야기예요. 여러분에게 '집'이란 무엇을 의미하고 왜 중요한지 문단으로 써 보세요.",
      "한 무리의 사람들을 이끌고 새로 영원히 머물 곳을 찾는 일에서 가장 힘든 부분이 무엇일지, 여러분의 생각과 이유를 문단으로 써 보세요."] };
ACT["S5225"] = { s: "Toad, Mole, Badger, and Ratty have adventures on the river, wild times in the wood, and on the open road.",
  q: ["Toad, Mole, Badger, and Ratty have adventures on the river, in the wood, and on the open road. Choose one of these settings and write a paragraph imagining an adventure that might happen there.",
      "These four friends share many different adventures together. Write a paragraph about a friend or friends you like to share adventures or fun times with.",
      "Write a paragraph giving your opinion on which of the three settings (the river, the wood, or the open road) sounds most exciting to you for an adventure, and explain why."],
  h: ["토드, 몰, 배저, 래티는 강, 숲, 그리고 탁 트인 길 위에서 모험을 겪어요. 이 중 한 장소를 골라, 그곳에서 일어날 법한 모험을 상상해서 문단으로 써 보세요.",
      "이 네 친구는 함께 여러 모험을 나눠요. 여러분이 모험이나 즐거운 시간을 함께 나누고 싶은 친구(들)를 문단으로 써 보세요.",
      "강, 숲, 탁 트인 길 중 어디에서의 모험이 여러분에게 가장 신날 것 같은지, 의견과 이유를 문단으로 써 보세요."] };
ACT["S5226"] = { s: "Puritan neighbors regard Kit Tyler with suspicion, fear, and anger when she makes friends with an old woman accused of witchcraft.",
  q: ["Kit Tyler's neighbors regard her with suspicion, fear, and anger after she befriends a woman accused of witchcraft. Write a paragraph imagining why Kit chose to be friends with the accused woman despite the risk.",
      "Kit is treated differently because of a friendship she chose to keep. Write a paragraph about a time you stood by a friend even though others disapproved.",
      "Write a paragraph giving your opinion on whether Kit was right to keep her friendship with the accused woman, even knowing how her neighbors would react, and explain your reasoning."],
  h: ["키트 타일러는 마녀로 몰린 여인과 친구가 된 뒤 이웃들에게 의심과 두려움, 분노의 시선을 받아요. 위험을 무릅쓰고 키트가 그 여인과 친구가 되기로 한 이유를 상상해서 문단으로 써 보세요.",
      "키트는 자신이 지키기로 한 우정 때문에 다르게 대우받아요. 다른 사람들이 반대해도 친구 곁을 지켰던 경험을 문단으로 써 보세요.",
      "이웃들의 반응을 알면서도 키트가 그 여인과의 우정을 지킨 것이 옳았다고 생각하는지, 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S5227"] = { s: "Nine-year-old Garnet Linden finds the silver thimble by the river and believes it has brought luck to her whole family.",
  q: ["Garnet finds a silver thimble by the river and believes it brings luck to her whole family. Write a paragraph imagining what lucky things might happen to Garnet's family after she finds it.",
      "Garnet believes a small object brought good luck to her whole family. Write a paragraph about an object you have that feels special or lucky to you, and why.",
      "Write a paragraph giving your opinion on whether you believe a small object like a thimble can really bring luck to a family, and explain your reasoning."],
  h: ["가넷은 강가에서 은 골무를 발견하고 그것이 온 가족에게 행운을 가져다준다고 믿어요. 골무를 찾은 뒤 가넷의 가족에게 일어났을 법한 행운을 상상해서 문단으로 써 보세요.",
      "가넷은 작은 물건 하나가 가족 전체에게 행운을 가져다주었다고 믿어요. 여러분이 가진 물건 중 특별하거나 행운처럼 느껴지는 것과 그 이유를 문단으로 써 보세요.",
      "골무처럼 작은 물건이 정말로 가족에게 행운을 가져다줄 수 있다고 생각하는지, 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S5229"] = { s: "This book is based on the author's real story. The author tries to help impoverished villages in Pakistan and Afghanistan build schools for their children.",
  q: ["The author of this true story helps impoverished villages in Pakistan and Afghanistan build schools for their children. Write a paragraph imagining what challenges the author might have faced while trying to build these schools.",
      "This book is about someone using their time and effort to help children in other countries get an education. Write a paragraph about why you think education matters for children, using your own life as an example.",
      "Write a paragraph giving your opinion on why the author of this true story chose to spend his life helping build schools in other countries, and explain your reasoning."],
  h: ["이 실화 속 저자는 파키스탄과 아프가니스탄의 가난한 마을들이 아이들을 위한 학교를 짓도록 도와요. 저자가 학교를 지으려 애쓰는 동안 겪었을 어려움을 상상해서 문단으로 써 보세요.",
      "이 책은 다른 나라 아이들이 교육받도록 시간과 노력을 쏟은 사람의 이야기예요. 아이들에게 교육이 왜 중요한지, 여러분 자신의 삶을 예로 들어 문단으로 써 보세요.",
      "이 실화의 저자가 왜 다른 나라에 학교를 짓는 데 자기 삶을 바치기로 했을지, 여러분의 생각과 이유를 문단으로 써 보세요."] };
ACT["S5231"] = { s: "Two children observe the effects of racial prejudice as their father courageously defends an innocent black man who has been accused of raping a white woman.",
  q: ["The children in this book observe their father courageously defend an innocent man who has been falsely accused. Write a paragraph imagining what it must have been like for the children to watch their father take on this difficult case.",
      "The father in this book stands up for what is right even though it is difficult. Write a paragraph about a time you or someone you know stood up for what was right even when it was hard.",
      "Write a paragraph giving your opinion on why courage, like the father's in this book, is important when defending someone who is innocent but unfairly accused, and explain your reasoning."],
  h: ["이 책 속 아이들은 아버지가 억울하게 고발당한 죄 없는 사람을 용기 있게 변호하는 모습을 지켜봐요. 아버지가 이 힘든 사건을 맡는 모습을 지켜보는 것이 아이들에게 어땠을지 상상해서 문단으로 써 보세요.",
      "이 책 속 아버지는 힘들어도 옳은 일을 위해 나서요. 여러분이나 아는 사람이 힘들어도 옳은 일을 위해 나섰던 경험을 문단으로 써 보세요.",
      "억울하게 고발당한 죄 없는 사람을 변호할 때 이 책 속 아버지 같은 용기가 왜 중요한지, 여러분의 생각과 이유를 문단으로 써 보세요."] };
ACT["S5232"] = { s: "Winnie Foster is faced with difficult decisions after she is kidnapped by the Tuck family, who have found a spring that gives eternal life.",
  q: ["Winnie is kidnapped by the Tuck family, who have found a spring that gives eternal life. Write a paragraph imagining what difficult decisions Winnie might have to make once she learns this secret.",
      "The Tuck family's spring gives eternal life, which brings both a gift and difficult choices. Write a paragraph about a time you had to make a difficult decision, and how you decided what to do.",
      "Write a paragraph giving your opinion on whether you would want to drink from a spring that gives eternal life if you had the chance, and explain your reasoning."],
  h: ["위니는 영원한 생명을 주는 샘을 발견한 터크 가족에게 납치돼요. 이 비밀을 알게 된 뒤 위니가 마주하게 될 어려운 결정들을 상상해서 문단으로 써 보세요.",
      "터크 가족의 샘은 영원한 생명을 주지만, 그것은 선물이면서 동시에 어려운 선택을 가져와요. 여러분이 어려운 결정을 내려야 했던 경험과 어떻게 결정했는지 문단으로 써 보세요.",
      "기회가 있다면 영원한 생명을 주는 샘물을 마시고 싶은지, 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S5233"] = { s: "This book is a chronicle of the time the author spent with his former college professor, in the last months of the older man's life.",
  q: ["The author spends time with his former college professor during the last months of the older man's life. Write a paragraph imagining what kinds of things they might have talked about together.",
      "The author chooses to spend meaningful time with someone important to him near the end of that person's life. Write a paragraph about someone important in your life that you would want to spend more time with, and why.",
      "Write a paragraph giving your opinion on why spending time with an older person who has much life experience, like the professor in this book, can be valuable, and explain your reasoning."],
  h: ["저자는 예전 대학 교수님의 마지막 몇 달 동안 그와 함께 시간을 보내요. 두 사람이 함께 나누었을 법한 대화들을 상상해서 문단으로 써 보세요.",
      "저자는 소중한 사람의 삶이 끝나 갈 무렵 그와 뜻깊은 시간을 보내기로 해요. 여러분 삶에서 더 많은 시간을 함께 보내고 싶은 소중한 사람과 그 이유를 문단으로 써 보세요.",
      "이 책 속 교수님처럼 인생 경험이 많은 어른과 시간을 보내는 것이 왜 가치 있을 수 있는지, 여러분의 생각과 이유를 문단으로 써 보세요."] };
ACT["S5234"] = { s: "This book is the twelfth novel in the children's novel series, A Series of Unfortunate Events by Lemony Snicket. The Baudelaires disguise themselves as hotel concierges while trying to uncover the mysteries surrounding VFD.",
  q: ["The Baudelaires disguise themselves as hotel concierges to uncover the mysteries surrounding VFD. Write a paragraph imagining what challenges they might face while working undercover at the hotel.",
      "The Baudelaires must pretend to be someone else in order to solve a mystery. Write a paragraph about a time you had to act differently than usual to reach a goal, or imagine a situation where you might need to.",
      "Write a paragraph giving your opinion on whether disguising themselves as hotel concierges was a smart strategy for the Baudelaires, and explain your reasoning."],
  h: ["보들레르 남매는 VFD를 둘러싼 수수께끼를 밝히기 위해 호텔 안내원으로 변장해요. 호텔에서 신분을 숨기고 일하는 동안 그들이 마주했을 어려움을 상상해서 문단으로 써 보세요.",
      "보들레르 남매는 수수께끼를 풀기 위해 다른 사람인 척해야 해요. 여러분이 목표를 이루려고 평소와 다르게 행동했던 경험, 또는 그래야 할 상황을 상상해서 문단으로 써 보세요.",
      "호텔 안내원으로 변장한 것이 보들레르 남매에게 영리한 전략이었다고 생각하는지, 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S5235"] = { s: "Having fled to a family friend's trailer after his mother's boyfriend tried to throw his baby sister against a wall, Jamie finds himself living an existence full of unstability and fear.",
  q: ["Jamie and his family flee to a family friend's trailer after a frightening event at home. Write a paragraph imagining what daily life might feel like for Jamie living with instability and fear.",
      "Jamie's family relies on a family friend for a safe place to stay during a difficult time. Write a paragraph about a person or place that has made you feel safe during a hard time.",
      "Write a paragraph giving your opinion on how a family friend's help, like the trailer offered to Jamie's family, can make a difference for someone going through a scary situation, and explain your reasoning."],
  h: ["제이미와 가족은 집에서 일어난 무서운 사건 뒤 가족의 친구가 사는 트레일러로 피신해요. 불안과 두려움 속에서 살아가는 제이미의 일상이 어떨지 상상해서 문단으로 써 보세요.",
      "제이미의 가족은 힘든 시기에 가족의 친구에게 기대어 머물 안전한 곳을 얻어요. 힘든 시기에 여러분을 안전하게 느끼게 해 준 사람이나 장소를 문단으로 써 보세요.",
      "제이미 가족에게 내어 준 트레일러처럼, 가족 친구의 도움이 무서운 상황을 겪는 사람에게 어떤 변화를 줄 수 있는지, 여러분의 생각과 이유를 문단으로 써 보세요."] };
ACT["S5237"] = { s: "Minli, an adventurous girl from a poor village, buys a magical goldfish and then joins a dragon on a quest to find the Old Man of the Moon.",
  q: ["Minli buys a magical goldfish and joins a dragon on a quest to find the Old Man of the Moon. Write a paragraph imagining what obstacles Minli and the dragon might meet on their journey.",
      "Minli is described as an adventurous girl from a poor village who goes on a big quest. Write a paragraph about a time you were adventurous or tried something new despite not having much.",
      "Write a paragraph giving your opinion on what you think Minli hopes to ask the Old Man of the Moon, based on the fact that she comes from a poor village, and explain your reasoning."],
  h: ["민리는 마법의 금붕어를 사고, 용과 함께 달의 노인을 찾는 여정에 나서요. 민리와 용이 여정에서 마주쳤을 장애물들을 상상해서 문단으로 써 보세요.",
      "민리는 가난한 마을 출신이지만 모험심 많은 소녀로, 큰 여정에 나서요. 여러분이 가진 것이 많지 않아도 모험을 하거나 새로운 것을 시도했던 경험을 문단으로 써 보세요.",
      "가난한 마을 출신이라는 점을 생각할 때 민리가 달의 노인에게 무엇을 묻고 싶어 할지, 여러분의 생각과 이유를 문단으로 써 보세요."] };
ACT["S5238"] = { s: "This book tells the adventures of a dog that is part wolf as he eventually makes his peace with man in the wilderness of northern Canada.",
  q: ["The dog in this book is part wolf and eventually makes peace with man in the wilderness of northern Canada. Write a paragraph imagining what kind of experiences might lead a half-wild dog to trust humans.",
      "This book is about an animal learning to trust and live alongside humans. Write a paragraph about a pet or animal you know that had to learn to trust people, or about how you built trust with an animal.",
      "Write a paragraph giving your opinion on whether a wild animal can truly make peace with humans, like the dog in this book, and explain your reasoning."],
  h: ["이 책 속 개는 늑대의 피가 섞였고, 캐나다 북부의 황야에서 결국 사람과 화해하게 돼요. 반쯤 야생인 개가 사람을 믿게 되기까지 어떤 경험들을 했을지 상상해서 문단으로 써 보세요.",
      "이 책은 한 동물이 사람을 믿고 함께 사는 법을 배우는 이야기예요. 사람을 믿는 법을 배워야 했던 반려동물이나 동물, 또는 여러분이 동물과 신뢰를 쌓았던 경험을 문단으로 써 보세요.",
      "이 책 속 개처럼 야생 동물이 정말로 사람과 화해할 수 있다고 생각하는지, 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S5239"] = { s: "Pippi Longstocking is going on a ship to the South Seas and gets unexpected companion.",
  q: ["Pippi is going on a ship to the South Seas and gets an unexpected companion. Write a paragraph imagining who or what this unexpected companion might be.",
      "Pippi's journey brings her an unexpected companion along the way. Write a paragraph about an unexpected friend or surprise you had during a trip or new experience.",
      "Write a paragraph giving your opinion on whether unexpected companions on a journey make the trip better or more difficult, and explain your reasoning."],
  h: ["삐삐는 남태평양으로 가는 배를 타고, 뜻밖의 동행을 얻게 돼요. 그 뜻밖의 동행이 누구 또는 무엇일지 상상해서 문단으로 써 보세요.",
      "삐삐의 여정은 그녀에게 뜻밖의 동행을 가져다줘요. 여러분이 여행이나 새로운 경험 중에 얻었던 뜻밖의 친구나 깜짝 놀랄 일을 문단으로 써 보세요.",
      "여행 중 뜻밖의 동행이 생기면 여행이 더 좋아질지 더 힘들어질지, 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S5240"] = { s: "Christmas is coming, and Pippi and her friends want to celebrate. Can Pippi have Christmas on the island in the South Seas?",
  q: ["Pippi and her friends want to celebrate Christmas on an island in the South Seas. Write a paragraph imagining how Pippi might celebrate Christmas somewhere so different from a usual Christmas setting.",
      "Pippi wants to celebrate a favorite holiday even far from home. Write a paragraph about how your family celebrates a holiday you love, and what makes it special.",
      "Write a paragraph giving your opinion on whether Christmas can still feel special on a warm island in the South Seas without snow, and explain your reasoning."],
  h: ["삐삐와 친구들은 남태평양의 섬에서 크리스마스를 보내고 싶어 해요. 보통의 크리스마스 풍경과는 전혀 다른 곳에서 삐삐가 크리스마스를 어떻게 보낼지 상상해서 문단으로 써 보세요.",
      "삐삐는 집에서 멀리 떨어져 있어도 좋아하는 명절을 보내고 싶어 해요. 여러분 가족이 좋아하는 명절을 어떻게 보내는지, 무엇이 특별한지 문단으로 써 보세요.",
      "눈이 없는 남태평양의 따뜻한 섬에서도 크리스마스가 여전히 특별하게 느껴질 수 있을지, 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S5241"] = { s: "This is the story of a lucky little girl who lives with a horse and a monkey at the edge of a Swedish village.",
  q: ["Pippi lives with a horse and a monkey at the edge of a Swedish village. Write a paragraph imagining what a day in Pippi's life with these two animals might look like.",
      "Pippi is described as a lucky girl who lives with unusual animal companions. Write a paragraph about an animal you would love to live with, and why.",
      "Write a paragraph giving your opinion on whether living with a horse and a monkey instead of with parents, like Pippi does, would be exciting or difficult, and explain your reasoning."],
  h: ["삐삐는 스웨덴 마을 끝자락에서 말과 원숭이와 함께 살아요. 이 두 동물과 함께하는 삐삐의 하루가 어떨지 상상해서 문단으로 써 보세요.",
      "삐삐는 특이한 동물 친구들과 사는 운 좋은 소녀로 그려져요. 여러분이 함께 살고 싶은 동물과 그 이유를 문단으로 써 보세요.",
      "삐삐처럼 부모님 대신 말과 원숭이와 함께 사는 것이 신날지 힘들지, 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S5242"] = { s: "As a young man working in East Africa, Roald Dahl recounts his adventures living in the jungle and later flying a fighter plane in World War II.",
  q: ["Roald Dahl recounts his adventures living in the jungle in East Africa and later flying a fighter plane in World War II. Choose one of these two adventures and write a paragraph imagining what it might have been like.",
      "This book describes big changes in someone's life, from living in the jungle to flying in a war. Write a paragraph about a big change you have experienced in your own life, and how it felt.",
      "Write a paragraph giving your opinion on which sounds more dangerous, living in the jungle or flying a fighter plane during a war, and explain your reasoning."],
  h: ["로알드 달은 동아프리카 정글에서 살았던 경험과, 이후 제2차 세계대전에서 전투기를 몰았던 경험을 이야기해요. 이 두 경험 중 하나를 골라 어땠을지 상상해서 문단으로 써 보세요.",
      "이 책은 정글에서의 삶부터 전쟁 속 비행까지, 한 사람의 삶에 일어난 큰 변화들을 그려요. 여러분 삶에서 겪은 큰 변화와 그때의 기분을 문단으로 써 보세요.",
      "정글에서 사는 것과 전쟁 중 전투기를 모는 것 중 어느 쪽이 더 위험하게 들리는지, 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S5243"] = { s: "Thousands of tiny Minpins live in the forest trees, but so does the Terrible Bloodsuckling Toothpluckling Stonechuckling Spittler.",
  q: ["Thousands of tiny Minpins live in the forest trees alongside the Terrible Bloodsuckling Toothpluckling Stonechuckling Spittler. Write a paragraph imagining what it would be like for the Minpins to share their forest with such a creature.",
      "The Minpins must find ways to stay safe while living near a dangerous creature. Write a paragraph about a time you had to be careful or clever to stay safe from something or someone.",
      "Write a paragraph giving your opinion on what the Minpins should do to protect themselves from the Terrible Bloodsuckling Toothpluckling Stonechuckling Spittler, and explain your reasoning."],
  h: ["수천 마리의 작은 민핀들은 무시무시한 괴물 '블러드서클링 투스플러클링 스톤처클링 스피틀러'와 함께 숲의 나무들 속에서 살아요. 그런 괴물과 숲을 나눠 써야 하는 민핀들의 삶이 어떨지 상상해서 문단으로 써 보세요.",
      "민핀들은 위험한 괴물 곁에서 안전하게 지낼 방법을 찾아야 해요. 여러분이 무언가나 누군가로부터 안전하려고 조심하거나 꾀를 냈던 경험을 문단으로 써 보세요.",
      "민핀들이 그 무시무시한 괴물로부터 자신을 지키려면 어떻게 해야 할지, 여러분의 생각과 이유를 문단으로 써 보세요."] };
ACT["S5244"] = { s: "It provides an overview of Egyptian pyramids and the burial practices associated with them, along with a brief introduction to pyramids of other countries.",
  q: ["This book gives an overview of Egyptian pyramids and the burial practices associated with them. Write a paragraph about one burial practice or fact from the book that you found most interesting.",
      "This book also briefly introduces pyramids of other countries besides Egypt. Write a paragraph about a building or structure from your own country that you think is impressive, and why.",
      "Write a paragraph giving your opinion on why ancient people might have built such large pyramids for burial practices, and explain your reasoning."],
  h: ["이 책은 이집트 피라미드와 그와 관련된 장례 풍습을 개괄적으로 보여 줘요. 책 속 장례 풍습이나 사실 중 가장 흥미로웠던 것을 하나 골라 문단으로 써 보세요.",
      "이 책은 이집트 외 다른 나라의 피라미드도 간단히 소개해요. 여러분 나라의 건축물 중 인상 깊다고 생각하는 것과 그 이유를 문단으로 써 보세요.",
      "고대 사람들이 왜 장례를 위해 그렇게 거대한 피라미드를 지었을지, 여러분의 생각과 이유를 문단으로 써 보세요."] };
ACT["S5245"] = { s: "Explore the amazing feats of space flight, from the earliest satellites and moon landings to the contemporary shuttle and Space Station missions.",
  q: ["This book explores space flight from the earliest satellites and moon landings to shuttle and Space Station missions. Choose one of these space achievements and write a paragraph about why you find it amazing.",
      "This book covers many different stages of space exploration history. Write a paragraph about whether you would want to travel to space someday, and what you would want to see or do there.",
      "Write a paragraph giving your opinion on which era of space flight described in this book, early satellites, moon landings, shuttles, or the Space Station, was the most important step for humans, and explain your reasoning."],
  h: ["이 책은 최초의 인공위성과 달 착륙부터 우주왕복선과 우주정거장 임무까지 우주 비행을 탐구해요. 이 중 하나를 골라 왜 놀랍다고 생각하는지 문단으로 써 보세요.",
      "이 책은 우주 탐사 역사의 여러 단계를 다뤄요. 언젠가 우주로 여행 가고 싶은지, 간다면 무엇을 보거나 하고 싶은지 문단으로 써 보세요.",
      "이 책이 다룬 우주 비행의 시기들(초기 인공위성, 달 착륙, 우주왕복선, 우주정거장) 중 인류에게 가장 중요한 단계는 무엇이었다고 생각하는지, 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S5246"] = { s: "In this version of the classic fairy tale RAPUNZEL, the daughter of two hair dressers is locked in a tower by the Bad Hair Witch.",
  q: ["In this version of Rapunzel, the daughter of two hair dressers is locked in a tower by the Bad Hair Witch. Write a paragraph imagining how being the daughter of hair dressers might change the story compared to the original tale.",
      "This book is a silly, twisted version of a classic fairy tale. Write a paragraph about a story or fairy tale you know well, and how you might change it to make it funnier.",
      "Write a paragraph giving your opinion on whether being locked in a tower by the Bad Hair Witch would be easier or harder to escape than the original Rapunzel's tower, and explain your reasoning."],
  h: ["이 라푼젤 이야기 속에서는 미용사 부부의 딸이 나쁜 머리 마녀에게 붙잡혀 탑에 갇혀요. 미용사의 딸이라는 점이 원래 이야기와 비교해 어떻게 다르게 이야기를 바꿀지 상상해서 문단으로 써 보세요.",
      "이 책은 고전 동화를 우스꽝스럽게 비튼 이야기예요. 여러분이 잘 아는 이야기나 동화를 골라, 더 재미있게 바꾼다면 어떻게 바꿀지 문단으로 써 보세요.",
      "나쁜 머리 마녀가 가둔 탑이 원래 라푼젤 이야기의 탑보다 탈출하기 쉬울지 어려울지, 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S5247"] = { s: "This book is the thirteenth and final book in A Series of Unfortunate Events, written by Lemony Snicket. The Baudelaires and Count Olaf end up being trapped on a castaway island, where its islanders attempt to create a peaceful utopia.",
  q: ["The Baudelaires and Count Olaf end up trapped together on a castaway island where the islanders attempt to create a peaceful utopia. Write a paragraph imagining what problems might arise from being trapped with Count Olaf on this island.",
      "The islanders in this book attempt to create a peaceful utopia, a perfect and peaceful place. Write a paragraph describing what your own idea of a peaceful, perfect place to live would look like.",
      "Write a paragraph giving your opinion on whether a truly peaceful utopia could work if someone like Count Olaf were living there too, and explain your reasoning."],
  h: ["보들레르 남매와 올라프 백작은 섬사람들이 평화로운 유토피아를 만들려는 외딴섬에 함께 갇히게 돼요. 올라프 백작과 함께 이 섬에 갇힌다면 어떤 문제가 생길지 상상해서 문단으로 써 보세요.",
      "이 책 속 섬사람들은 완벽하고 평화로운 곳, 유토피아를 만들려고 해요. 여러분이 생각하는 평화롭고 완벽한 살 곳은 어떤 모습일지 문단으로 써 보세요.",
      "올라프 백작 같은 사람이 함께 산다면 정말 평화로운 유토피아가 이루어질 수 있을지, 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S5248"] = { s: "This book tells each of the presidents and includes facts about the White House, the vice presidents and first ladies, and impeachment.",
  q: ["This book includes facts about the White House, the vice presidents, first ladies, and impeachment. Choose one of these topics and write a paragraph about what you would like to learn about it.",
      "This book is filled with facts about the presidents and the people around them. Write a paragraph about a leader (in your school, family, or community) that you admire, and why.",
      "Write a paragraph giving your opinion on which job seems more difficult, being president or being vice president, based on what this book covers, and explain your reasoning."],
  h: ["이 책은 백악관, 부통령, 영부인, 탄핵에 관한 사실들을 담고 있어요. 이 중 하나를 골라 무엇을 더 알고 싶은지 문단으로 써 보세요.",
      "이 책은 대통령과 그 주변 사람들에 관한 사실들로 가득해요. 여러분이 존경하는 지도자(학교, 가족, 또는 공동체 속에서)와 그 이유를 문단으로 써 보세요.",
      "이 책이 다룬 내용을 바탕으로 대통령과 부통령 중 어느 쪽 일이 더 힘들어 보이는지, 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S5249"] = { s: "Amelia Earhart was the world's first heroine of the aviation age, and this fascinating biography captures her determination to chart her own path.",
  q: ["This biography captures Amelia Earhart's determination to chart her own path as the world's first heroine of the aviation age. Write a paragraph imagining what obstacles she might have faced as a woman entering aviation.",
      "Amelia Earhart is remembered for her determination to chart her own path. Write a paragraph about a time you showed determination to do something your own way.",
      "Write a paragraph giving your opinion on why it mattered for someone like Amelia Earhart to become the first heroine of the aviation age, and explain your reasoning."],
  h: ["이 전기는 세계 최초의 항공 시대 여성 영웅 아멜리아 에어하트가 자신만의 길을 개척하려는 결단력을 담고 있어요. 여성으로서 항공 분야에 뛰어들며 그녀가 마주했을 장애물들을 상상해서 문단으로 써 보세요.",
      "아멜리아 에어하트는 자신만의 길을 개척하려는 결단력으로 기억돼요. 여러분이 자신만의 방식으로 무언가를 해내려고 결단력을 보였던 경험을 문단으로 써 보세요.",
      "아멜리아 에어하트 같은 사람이 항공 시대 최초의 여성 영웅이 된 것이 왜 중요했는지, 여러분의 생각과 이유를 문단으로 써 보세요."] };
ACT["S5253"] = { s: "When Digory and Polly try to return the wicked witch Jadis to her own world, the magic is mixed up and they all land in Narnia where they witness Aslan blessing the animals with human speech.",
  q: ["Digory and Polly witness Aslan blessing the animals with human speech in Narnia. Write a paragraph imagining what it would be like to see animals suddenly gain the power of speech.",
      "Digory and Polly try to send the wicked witch Jadis back to her own world, but the magic goes wrong. Write a paragraph about a time a plan you made did not go the way you expected.",
      "Write a paragraph giving your opinion on whether it was a good idea for Digory and Polly to try to handle the wicked witch Jadis themselves, and explain your reasoning."],
  h: ["디고리와 폴리는 아슬란이 나니아의 동물들에게 사람의 말을 할 수 있는 능력을 주는 모습을 지켜봐요. 동물들이 갑자기 말하는 능력을 얻는 모습을 본다면 어떨지 상상해서 문단으로 써 보세요.",
      "디고리와 폴리는 사악한 마녀 제이디스를 그녀의 세계로 돌려보내려 하지만 마법이 잘못돼요. 여러분이 세운 계획이 예상과 다르게 흘러갔던 경험을 문단으로 써 보세요.",
      "디고리와 폴리가 사악한 마녀 제이디스를 스스로 처리하려 한 것이 좋은 생각이었다고 생각하는지, 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S5254"] = { s: "Four children enter the land of Narnia. There they must help Aslan, the noble lion, free Narnia from the spell of the White Witch.",
  q: ["The four children must help Aslan free Narnia from the spell of the White Witch. Write a paragraph imagining what kind of spell the White Witch might have placed over Narnia.",
      "The four children work together with Aslan to fix a big problem in Narnia. Write a paragraph about a time you worked together with others to solve a big problem.",
      "Write a paragraph giving your opinion on whether the children were brave to help Aslan fight against the powerful White Witch, and explain your reasoning."],
  h: ["네 아이는 아슬란이 흰 마녀의 마법에서 나니아를 구하는 것을 도와야 해요. 흰 마녀가 나니아에 걸었을 마법이 어떤 것일지 상상해서 문단으로 써 보세요.",
      "네 아이는 아슬란과 함께 나니아의 큰 문제를 해결하려고 힘을 모아요. 여러분이 다른 사람들과 힘을 모아 큰 문제를 해결했던 경험을 문단으로 써 보세요.",
      "아이들이 강력한 흰 마녀에 맞서 아슬란을 돕기로 한 것이 용감한 일이었다고 생각하는지, 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S5255"] = { s: "A boy prince and a talking horse share an adventurous and dangerous journey to save Narnia from invasion.",
  q: ["A boy prince and a talking horse share a dangerous journey to save Narnia from invasion. Write a paragraph imagining how a boy and a talking horse might work together during this journey.",
      "This book shows an unusual pair, a boy and a talking horse, becoming partners on a journey. Write a paragraph about a partner (a person, or even a pet) you have worked with to get through something difficult.",
      "Write a paragraph giving your opinion on whether a boy prince and a talking horse would make good partners for a dangerous journey, and explain your reasoning."],
  h: ["소년 왕자와 말하는 말은 침략으로부터 나니아를 구하기 위한 위험한 여정을 함께해요. 소년과 말하는 말이 이 여정 동안 어떻게 힘을 합칠지 상상해서 문단으로 써 보세요.",
      "이 책은 소년과 말하는 말이라는 특이한 짝이 여정의 동반자가 되는 이야기예요. 여러분이 힘든 일을 함께 헤쳐 나간 동반자(사람이나 반려동물이라도)를 문단으로 써 보세요.",
      "소년 왕자와 말하는 말이 위험한 여정을 함께하기에 좋은 짝일지, 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S5256"] = { s: "Four children help Prince Caspian and his army of Talking Beasts to free Narnia from evil.",
  q: ["Four children help Prince Caspian and his army of Talking Beasts to free Narnia from evil. Write a paragraph imagining what kind of help the children might give to an army of Talking Beasts.",
      "In this book, children join forces with Talking Beasts to fight for something good. Write a paragraph about a team you have been part of, and what made that team work well together.",
      "Write a paragraph giving your opinion on whether an army of Talking Beasts would be stronger or weaker than an army of regular soldiers, and explain your reasoning."],
  h: ["네 아이는 캐스피언 왕자와 그의 말하는 짐승 군대가 나니아를 악으로부터 구하는 것을 도와요. 아이들이 말하는 짐승 군대에게 어떤 도움을 줄 수 있을지 상상해서 문단으로 써 보세요.",
      "이 책에서 아이들은 좋은 일을 위해 말하는 짐승들과 힘을 합쳐요. 여러분이 속했던 팀과, 그 팀이 잘 뭉칠 수 있었던 이유를 문단으로 써 보세요.",
      "말하는 짐승들의 군대가 보통 군인들의 군대보다 강할지 약할지, 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S5257"] = { s: "Lucy and Edmund, accompanied by their peevish cousin Eustace, sail to the land of Narnia, where Eustace is temporarily transformed into a green dragon because of his selfish behavior and skepticism.",
  q: ["Eustace is temporarily transformed into a green dragon because of his selfish behavior and skepticism. Write a paragraph imagining how being turned into a dragon might change the way Eustace behaves afterward.",
      "Eustace's selfish behavior leads to a big change for him. Write a paragraph about a time your own behavior led to a consequence, good or bad, and what you learned from it.",
      "Write a paragraph giving your opinion on whether turning Eustace into a dragon was a fitting way for him to learn a lesson about his selfish behavior, and explain your reasoning."],
  h: ["유스터스는 이기적인 행동과 의심 많은 태도 때문에 잠시 초록 용으로 변해요. 용으로 변한 일이 그 뒤 유스터스의 행동을 어떻게 바꿀지 상상해서 문단으로 써 보세요.",
      "유스터스의 이기적인 행동은 그에게 큰 변화를 가져와요. 여러분의 행동이 좋거나 나쁜 결과로 이어졌던 경험과, 그로부터 배운 것을 문단으로 써 보세요.",
      "유스터스를 용으로 만든 것이 그의 이기적인 행동에 대한 교훈을 주기에 알맞은 방법이었다고 생각하는지, 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S5258"] = { s: "Two English children undergo hair-raising adventures as they go on a search and rescue mission for the missing Prince Rilian, who is held captive in the underground kingdom of the Emerald Witch.",
  q: ["The two English children go on a search and rescue mission for Prince Rilian, who is held captive in the underground kingdom of the Emerald Witch. Write a paragraph imagining what dangers they might face in an underground kingdom.",
      "The children in this book take on the responsibility of rescuing someone who is captive. Write a paragraph about a time you helped rescue or stand up for someone who needed help.",
      "Write a paragraph giving your opinion on what would be the scariest part about going on a rescue mission into an underground kingdom, and explain your reasoning."],
  h: ["두 영국 아이는 에메랄드 마녀의 지하 왕국에 갇힌 릴리언 왕자를 찾아 구출하는 임무에 나서요. 지하 왕국에서 마주했을 위험들을 상상해서 문단으로 써 보세요.",
      "이 책 속 아이들은 갇혀 있는 누군가를 구출할 책임을 맡아요. 여러분이 도움이 필요한 누군가를 구하거나 그 편에 서 주었던 경험을 문단으로 써 보세요.",
      "지하 왕국으로 구출 임무를 떠난다면 가장 무서운 부분이 무엇일지, 여러분의 생각과 이유를 문단으로 써 보세요."] };
ACT["S5259"] = { s: "Aslan leads his people to a glorious new paradise after defeating the evil that had infested Narnia.",
  q: ["Aslan leads his people to a glorious new paradise after defeating the evil that had infested Narnia. Write a paragraph imagining what this new paradise might look like.",
      "This book ends with Aslan's people finally reaching a peaceful new home after a long struggle. Write a paragraph about a time something difficult finally ended well for you.",
      "Write a paragraph giving your opinion on why a \"new paradise\" might feel especially meaningful after such a long fight against evil, and explain your reasoning."],
  h: ["아슬란은 나니아를 뒤덮었던 악을 물리친 뒤 자신의 백성들을 영광스러운 새 낙원으로 이끌어요. 이 새 낙원이 어떤 모습일지 상상해서 문단으로 써 보세요.",
      "이 책은 아슬란의 백성들이 긴 싸움 끝에 마침내 평화로운 새 보금자리에 이르며 끝나요. 여러분이 겪은 힘든 일이 마침내 잘 마무리되었던 경험을 문단으로 써 보세요.",
      "그토록 오랜 악과의 싸움 끝에 얻은 '새 낙원'이 왜 특별히 의미 있게 느껴질지, 여러분의 생각과 이유를 문단으로 써 보세요."] };
ACT["S5260"] = { s: "Three children on a holiday in Cornwall find an ancient manuscript which sends them on a dangerous quest for a grail that would reveal the true story of King Arthur.",
  q: ["The three children find an ancient manuscript that sends them on a dangerous quest for a grail. Write a paragraph imagining what dangers they might face while searching for the grail.",
      "The children's holiday turns into an unexpected adventure because of what they find. Write a paragraph about a vacation or holiday that turned out very differently than you expected.",
      "Write a paragraph giving your opinion on whether finding the grail and the true story of King Arthur is worth the danger the children face, and explain your reasoning."],
  h: ["세 아이는 고대 문서를 발견하고 그것 때문에 성배를 찾는 위험한 여정에 나서요. 성배를 찾는 동안 마주했을 위험들을 상상해서 문단으로 써 보세요.",
      "아이들의 휴가는 그들이 발견한 것 때문에 뜻밖의 모험으로 바뀌어요. 여러분이 예상과 전혀 다르게 흘러갔던 휴가나 여행을 문단으로 써 보세요.",
      "성배와 아서 왕의 진짜 이야기를 찾는 것이 아이들이 겪는 위험을 감수할 만한 가치가 있는지, 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S5261"] = { s: "On his eleventh birthday, Will Stanton discovers that he is the last of the Old Ones, destined to seek the six magical Signs that will enable the Old Ones to triumph over the evil forces of the Dark.",
  q: ["On his eleventh birthday, Will discovers he is destined to seek six magical Signs. Write a paragraph imagining how Will must have felt learning this on what should have been an ordinary birthday.",
      "Will suddenly learns he has an important destiny to fulfill. Write a paragraph about a responsibility you were given that felt bigger than you expected.",
      "Write a paragraph giving your opinion on whether finding out you have a huge destiny, like Will's, would feel more exciting or more frightening, and explain your reasoning."],
  h: ["윌은 열한 번째 생일에 여섯 개의 마법 표식을 찾아야 할 운명임을 알게 돼요. 평범해야 할 생일에 이 사실을 알게 된 윌의 마음이 어땠을지 상상해서 문단으로 써 보세요.",
      "윌은 갑자기 자신이 이뤄야 할 중요한 운명이 있다는 것을 알게 돼요. 여러분이 예상보다 크게 느껴졌던 책임을 맡았던 경험을 문단으로 써 보세요.",
      "윌처럼 자신에게 거대한 운명이 있다는 것을 알게 된다면 더 신날지 더 무서울지, 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S5262"] = { s: "Simon, Jane, and Barney discover the whereabouts of a priceless golden grail, possessed by a dreadful, vengeful power.",
  q: ["Simon, Jane, and Barney discover the whereabouts of a priceless golden grail possessed by a dreadful, vengeful power. Write a paragraph imagining what this vengeful power might do to protect the grail.",
      "The three children find something valuable that is guarded by a dangerous force. Write a paragraph about a time you found or wanted something that was hard or risky to get.",
      "Write a paragraph giving your opinion on whether the children should try to take the grail away from such a dangerous, vengeful power, and explain your reasoning."],
  h: ["사이먼, 제인, 바니는 끔찍하고 복수심 강한 힘이 지키는 값을 매길 수 없는 황금 성배가 어디 있는지 알아내요. 그 복수심 강한 힘이 성배를 지키기 위해 무엇을 할지 상상해서 문단으로 써 보세요.",
      "세 아이는 위험한 힘이 지키고 있는 귀중한 것을 발견해요. 여러분이 얻기 힘들거나 위험했던 것을 찾았거나 원했던 경험을 문단으로 써 보세요.",
      "아이들이 그렇게 위험하고 복수심 강한 힘으로부터 성배를 가져오려 해야 할지, 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S5263"] = { s: "Will Stanton, visiting in Wales, is swept into a desperate quest to find the golden harp and to awaken the ancient Sleepers.",
  q: ["Will is swept into a desperate quest to find the golden harp and awaken the ancient Sleepers. Write a paragraph imagining what the ancient Sleepers might be like once they are awakened.",
      "Will's visit to Wales turns into a desperate quest he did not expect. Write a paragraph about a trip that turned into something much bigger or more important than you planned.",
      "Write a paragraph giving your opinion on why finding a golden harp might be the key to waking the ancient Sleepers, and explain your reasoning."],
  h: ["윌은 황금 하프를 찾아 고대의 잠든 자들을 깨우는 절박한 여정에 휘말려요. 잠든 자들이 깨어나면 어떤 모습일지 상상해서 문단으로 써 보세요.",
      "윌의 웨일스 방문은 예상하지 못한 절박한 여정으로 바뀌어요. 여러분이 계획보다 훨씬 크고 중요한 일이 되어 버린 여행을 문단으로 써 보세요.",
      "황금 하프를 찾는 것이 왜 고대의 잠든 자들을 깨우는 열쇠일 수 있는지, 여러분의 생각을 문단으로 써 보세요."] };
ACT["S5264"] = { s: "Will Stanton, the Welsh boy Bran, and the Drew children try to locate the crystal sword that alone can vanquish the strong forces of Dark.",
  q: ["Will, Bran, and the Drew children try to locate the crystal sword that alone can vanquish the forces of Dark. Write a paragraph imagining where such a powerful sword might be hidden.",
      "This group of children works together to find one very important object. Write a paragraph about a time you and others searched hard for something important.",
      "Write a paragraph giving your opinion on why only the crystal sword can defeat the forces of Dark, and what you imagine makes it so powerful."],
  h: ["윌, 브랜, 그리고 드류가 아이들은 어둠의 세력을 물리칠 수 있는 유일한 수정검을 찾으려 해요. 그렇게 강력한 검이 어디에 숨겨져 있을지 상상해서 문단으로 써 보세요.",
      "이 아이들 무리는 힘을 합쳐 아주 중요한 물건 하나를 찾아요. 여러분과 다른 사람들이 힘을 합쳐 중요한 무언가를 열심히 찾았던 경험을 문단으로 써 보세요.",
      "왜 오직 수정검만이 어둠의 세력을 물리칠 수 있는지, 그리고 그 검이 왜 그렇게 강력할지 여러분의 생각을 문단으로 써 보세요."] };
ACT["S5265"] = { s: "Bored with traditional palace life, a princess goes off to live with a group of dragons and soon becomes involved with fighting against some disreputable wizards who want to steal away the dragons' kingdom.",
  q: ["The princess, bored with traditional palace life, goes off to live with a group of dragons. Write a paragraph imagining what daily life with dragons might be like compared to palace life.",
      "The princess chooses an unusual life because she is bored with the traditional one expected of her. Write a paragraph about a time you chose to do something different from what was expected of you.",
      "Write a paragraph giving your opinion on whether the princess made a good choice leaving palace life to live with dragons, and explain your reasoning."],
  h: ["공주는 전통적인 궁전 생활에 지루함을 느껴 용들과 함께 살러 떠나요. 용들과 함께하는 일상이 궁전 생활과 비교해 어떨지 상상해서 문단으로 써 보세요.",
      "공주는 자신에게 기대되던 전통적인 삶이 지루해 특이한 삶을 선택해요. 여러분이 기대와 다른 것을 선택했던 경험을 문단으로 써 보세요.",
      "공주가 궁전 생활을 떠나 용들과 사는 것을 선택한 것이 좋은 선택이었다고 생각하는지, 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S5266"] = { s: "With the aid of King Mendanbar, Princess Cimorene rescues the dragon Kazul and saves the Enchanted Forest from a band of wicked wizards.",
  q: ["Princess Cimorene rescues the dragon Kazul and saves the Enchanted Forest from wicked wizards. Write a paragraph imagining how Cimorene and King Mendanbar might have worked together during the rescue.",
      "Cimorene works together with King Mendanbar to save both her dragon friend and the forest. Write a paragraph about a time you teamed up with someone to help save or protect something important.",
      "Write a paragraph giving your opinion on why saving a friend, like Cimorene saving Kazul, might matter more than just defeating the wizards, and explain your reasoning."],
  h: ["시모렌 공주는 용 카줄을 구하고 사악한 마법사들로부터 마법의 숲을 구해요. 시모렌과 멘단바르 왕이 구출 과정에서 어떻게 힘을 합쳤을지 상상해서 문단으로 써 보세요.",
      "시모렌은 용 친구와 숲 모두를 구하기 위해 멘단바르 왕과 힘을 합쳐요. 여러분이 소중한 것을 구하거나 지키기 위해 누군가와 팀을 이루었던 경험을 문단으로 써 보세요.",
      "시모렌이 카줄을 구한 것처럼, 친구를 구하는 것이 그저 마법사들을 물리치는 것보다 왜 더 중요할 수 있는지, 여러분의 생각과 이유를 문단으로 써 보세요."] };
ACT["S5268"] = { s: "Frank and Joe uncover the clues in this case that they seem to have been led to by mysterious happenings.",
  q: ["Frank and Joe uncover clues that they seem to have been led to by mysterious happenings. Write a paragraph imagining what kind of mysterious happenings might have guided them.",
      "Frank and Joe follow clues to solve a mystery. Write a paragraph about a time you had to follow clues or pay close attention to figure something out.",
      "Write a paragraph giving your opinion on whether it is safer for Frank and Joe to investigate mysterious happenings on their own or with the help of adults, and explain your reasoning."],
  h: ["프랭크와 조는 알 수 없는 일들에 이끌려 단서들을 찾아낸 것처럼 보여요. 그들을 이끌었을 신비한 일들이 무엇이었을지 상상해서 문단으로 써 보세요.",
      "프랭크와 조는 단서를 따라 수수께끼를 풀어요. 여러분이 단서를 따라가거나 꼼꼼히 살펴 무언가를 알아냈던 경험을 문단으로 써 보세요.",
      "프랭크와 조가 신비한 일들을 혼자 조사하는 것과 어른들의 도움을 받아 조사하는 것 중 어느 쪽이 더 안전할지, 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S5269"] = { s: "Frank and Joe manage to escape from a hostage situation with a band of smugglers and, of course, solve another mystery.",
  q: ["Frank and Joe manage to escape from a hostage situation with a band of smugglers. Write a paragraph imagining how they might have planned their escape.",
      "Frank and Joe stay calm and think clearly even in a dangerous hostage situation. Write a paragraph about a time you had to stay calm during a stressful or scary moment.",
      "Write a paragraph giving your opinion on what quality helped Frank and Joe escape from the smugglers, and explain your reasoning."],
  h: ["프랭크와 조는 밀수꾼 무리에게 인질로 잡힌 상황에서 탈출해요. 그들이 어떻게 탈출을 계획했을지 상상해서 문단으로 써 보세요.",
      "프랭크와 조는 위험한 인질 상황에서도 침착하게 생각을 이어가요. 여러분이 힘들거나 무서운 순간에 침착함을 지켜야 했던 경험을 문단으로 써 보세요.",
      "프랭크와 조가 밀수꾼들에게서 탈출할 수 있었던 데는 어떤 자질이 도움이 되었을지, 여러분의 생각과 이유를 문단으로 써 보세요."] };
ACT["S5270"] = { s: "Frank and Joe investigate numerous crimes in their town that may or may not be related.",
  q: ["Frank and Joe investigate numerous crimes in their town that may or may not be related. Write a paragraph imagining how they might figure out whether the crimes are connected.",
      "Frank and Joe have to consider many different crimes at once. Write a paragraph about a time you had to keep track of several things happening at once, and how you managed it.",
      "Write a paragraph giving your opinion on whether it is more difficult to solve one big crime or several smaller crimes that might be connected, and explain your reasoning."],
  h: ["프랭크와 조는 마을에서 일어난 여러 사건을 조사하는데, 그 사건들이 서로 관련 있는지는 알 수 없어요. 이들이 사건이 서로 연결되었는지 어떻게 알아낼지 상상해서 문단으로 써 보세요.",
      "프랭크와 조는 여러 사건을 한꺼번에 살펴야 해요. 여러분이 한꺼번에 여러 가지 일을 챙겨야 했던 경험과 어떻게 해냈는지 문단으로 써 보세요.",
      "하나의 큰 사건을 푸는 것과 서로 연결되어 있을지 모르는 여러 작은 사건을 푸는 것 중 어느 쪽이 더 어려울지, 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S5271"] = { s: "The warning 'Drop case or else danger for you and your family.' addressed to Fenton Hardy not only alarms the famous investigator and his detective sons, but also puzzles them because Mr. Hardy is working on more than one case.",
  q: ["Fenton Hardy receives a warning that threatens danger to him and his family, but he is working on more than one case. Write a paragraph imagining how the Hardys might figure out which case the warning is actually about.",
      "The Hardy family faces a threat because of Mr. Hardy's dangerous work. Write a paragraph about a time your family faced a challenge together and how you handled it.",
      "Write a paragraph giving your opinion on whether Fenton Hardy should drop the case after receiving such a warning, or keep investigating, and explain your reasoning."],
  h: ["펜튼 하디는 자신과 가족에게 위험이 닥칠 거라는 경고를 받지만, 그는 여러 사건을 동시에 맡고 있어요. 하디 가족이 그 경고가 어느 사건 때문인지 어떻게 알아낼지 상상해서 문단으로 써 보세요.",
      "하디 가족은 아버지의 위험한 일 때문에 위협을 받아요. 여러분의 가족이 함께 어려움을 겪었던 경험과 어떻게 헤쳐 나갔는지 문단으로 써 보세요.",
      "그런 경고를 받은 뒤 펜튼 하디가 사건을 포기해야 할지 계속 수사해야 할지, 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S5272"] = { s: "Omri and his friend Patrick must risk grown-ups discovering their secret when they find themselves in need of a friend whose toy plastic doctors can be brought to life to save wounded people.",
  q: ["Omri and Patrick risk grown-ups discovering their secret in order to save wounded people. Write a paragraph imagining what might happen if the grown-ups discovered their secret.",
      "Omri and Patrick take a big risk to help someone who is hurt. Write a paragraph about a time you took a risk to help someone else.",
      "Write a paragraph giving your opinion on whether keeping their secret was more important than the risk of it being discovered, and explain your reasoning."],
  h: ["오므리와 패트릭은 다친 사람들을 구하기 위해 어른들에게 비밀이 들킬 위험을 무릅써요. 어른들이 그 비밀을 알게 된다면 어떤 일이 벌어질지 상상해서 문단으로 써 보세요.",
      "오므리와 패트릭은 다친 사람을 돕기 위해 큰 위험을 무릅써요. 여러분이 누군가를 돕기 위해 위험을 무릅썼던 경험을 문단으로 써 보세요.",
      "비밀을 지키는 것이 그것이 들킬 위험보다 더 중요했다고 생각하는지, 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S5273"] = { s: "Young Meggie learns that her father, who repairs and binds books for a living, can \"read\" fictional characters to life.",
  q: ["Meggie learns that her father can \"read\" fictional characters to life. Write a paragraph imagining what kind of fictional character you would want your father's power to bring to life.",
      "Meggie discovers a surprising secret about someone in her own family. Write a paragraph about a surprising thing you learned about someone in your family.",
      "Write a paragraph giving your opinion on whether the power to read fictional characters to life would be more wonderful or more dangerous, and explain your reasoning."],
  h: ["메기는 아버지가 이야기 속 인물을 현실로 '읽어낼' 수 있다는 것을 알게 돼요. 여러분이라면 어떤 이야기 속 인물을 아버지의 그런 능력으로 현실로 불러오고 싶은지 상상해서 문단으로 써 보세요.",
      "메기는 자기 가족의 누군가에 대해 놀라운 비밀을 알게 돼요. 여러분이 가족 중 누군가에 대해 알게 된 놀라운 사실을 문단으로 써 보세요.",
      "이야기 속 인물을 현실로 불러오는 능력이 멋진 일일지 위험한 일일지, 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S5274"] = { s: "Meggie can't stop thinking of INKHEART, the book whose characters became real. But for Dustfinger, the fire-eater brought into being from words, the need to return to the tale has become desperate.",
  q: ["Dustfinger, who was brought into being from words, feels a desperate need to return to the tale he came from. Write a paragraph imagining why Dustfinger might want so badly to go back into the story.",
      "Meggie can't stop thinking about a book that changed her life. Write a paragraph about a book or story that you can't stop thinking about, and why it stays with you.",
      "Write a paragraph giving your opinion on whether a character brought to life from a book, like Dustfinger, truly belongs in the real world or in the story, and explain your reasoning."],
  h: ["글자에서 태어난 더스트핑거는 자신이 나온 이야기로 돌아가고 싶은 절박한 마음을 느껴요. 더스트핑거가 그토록 간절하게 이야기 속으로 돌아가고 싶어 하는 이유를 상상해서 문단으로 써 보세요.",
      "메기는 자신의 삶을 바꿔 놓은 책을 계속 떠올려요. 여러분이 계속 떠올리게 되는 책이나 이야기와, 그것이 왜 마음에 남는지 문단으로 써 보세요.",
      "더스트핑거처럼 책에서 현실로 나온 인물이 진짜로 있어야 할 곳이 현실 세계인지 이야기 속인지, 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S5275"] = { s: "As Bluejay tries to keep the Book of Immortality from unraveling, Adderhead kidnaps all the children in the kingdom, asking for Bluejay's surrender, or the children will be doomed to slavery in the silver mines.",
  q: ["Adderhead kidnaps all the children in the kingdom to force Bluejay to surrender. Write a paragraph imagining what Bluejay might be thinking as he decides how to respond.",
      "Bluejay faces a difficult choice between his own safety and the safety of many children. Write a paragraph about a difficult choice you had to make between what was easy for you and what would help others.",
      "Write a paragraph giving your opinion on whether Bluejay should surrender to save the children or find another way to stop Adderhead, and explain your reasoning."],
  h: ["애더헤드는 블루제이를 항복시키려고 왕국의 모든 아이를 납치해요. 블루제이가 어떻게 대응할지 결정하며 무슨 생각을 할지 상상해서 문단으로 써 보세요.",
      "블루제이는 자기 자신의 안전과 많은 아이의 안전 사이에서 어려운 선택을 마주해요. 여러분에게 쉬운 것과 다른 사람에게 도움이 되는 것 사이에서 내려야 했던 어려운 선택을 문단으로 써 보세요.",
      "블루제이가 아이들을 구하기 위해 항복해야 할지, 아니면 애더헤드를 막을 다른 방법을 찾아야 할지, 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S5276"] = { s: "Young Almanzo lives with his family on a big farm in New York State at the end of the nineteenth century where he raises his own two calves, helps cut ice and shear sheep, and longs for the day he can have his own colt.",
  q: ["Almanzo raises his own two calves, helps cut ice and shear sheep, and longs for the day he can have his own colt. Choose one of these farm activities and write a paragraph imagining what a day doing that chore would be like.",
      "Almanzo longs for something he hopes to have someday, his own colt. Write a paragraph about something you have been looking forward to having or achieving.",
      "Write a paragraph giving your opinion on whether growing up doing hard farm work like Almanzo's would be a good way for a child to learn responsibility, and explain your reasoning."],
  h: ["앨먼조는 자기 소 두 마리를 키우고, 얼음 자르는 일과 양털 깎는 일을 도우며, 언젠가 자기 망아지를 갖게 될 날을 손꼽아 기다려요. 이 농사일 중 하나를 골라 그 일을 하는 하루가 어떨지 상상해서 문단으로 써 보세요.",
      "앨먼조는 언젠가 자기 망아지를 갖게 되기를 간절히 바라요. 여러분이 언젠가 갖거나 이루기를 기대해 온 것을 문단으로 써 보세요.",
      "앨먼조처럼 힘든 농사일을 하며 자라는 것이 아이에게 책임감을 가르치는 좋은 방법일지, 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S5277"] = { s: "The Ingalls family leaves Minnesota, travels to the Dakota Territory, and lives at a railroad camp until Pa can file their claim to a homestead near Silver Lake.",
  q: ["The Ingalls family lives at a railroad camp until Pa can file their claim to a homestead near Silver Lake. Write a paragraph imagining what daily life at a railroad camp might have been like for the family.",
      "The Ingalls family moves to a whole new place to start a new life. Write a paragraph about a time you or your family moved somewhere new, or imagine what that experience might feel like.",
      "Write a paragraph giving your opinion on whether it was a good decision for the Ingalls family to leave Minnesota for the unknown Dakota Territory, and explain your reasoning."],
  h: ["잉걸스 가족은 아버지가 실버 레이크 근처 땅을 정식으로 신청할 수 있을 때까지 철도 캠프에서 지내요. 철도 캠프에서 가족의 하루하루가 어땠을지 상상해서 문단으로 써 보세요.",
      "잉걸스 가족은 새로운 삶을 시작하려고 완전히 새로운 곳으로 이사해요. 여러분이나 가족이 새로운 곳으로 이사했던 경험, 또는 그런 경험이 어떨지 상상해서 문단으로 써 보세요.",
      "잉걸스 가족이 미네소타를 떠나 알지 못하는 다코타 준주로 향한 것이 좋은 결정이었다고 생각하는지, 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S5278"] = { s: "A blizzard and a warning from a Native American compel Charles Ingalls to move his family to town in the winter of 1880-1881. When the supply train doesn't arrive, Almanzo Wilder and his brother make a dangerous trip to save the town from starvation.",
  q: ["Almanzo Wilder and his brother make a dangerous trip to save the town from starvation when the supply train doesn't arrive. Write a paragraph imagining the dangers they might have faced on that trip.",
      "A warning from a Native American helps Charles Ingalls decide to protect his family by moving to town. Write a paragraph about a time someone's warning or advice helped keep you or your family safe.",
      "Write a paragraph giving your opinion on whether Almanzo and his brother were right to risk a dangerous trip to save the whole town, and explain your reasoning."],
  h: ["보급 열차가 오지 않자 앨먼조 와일더와 그의 형은 마을을 굶주림에서 구하기 위해 위험한 여행을 떠나요. 그 여행에서 마주했을 위험들을 상상해서 문단으로 써 보세요.",
      "아메리카 원주민의 경고 덕분에 찰스 잉걸스는 가족을 지키기 위해 마을로 이사하기로 해요. 누군가의 경고나 조언이 여러분이나 가족을 안전하게 지켜 준 경험을 문단으로 써 보세요.",
      "앨먼조와 그의 형이 마을 전체를 구하기 위해 위험한 여행을 떠난 것이 옳았다고 생각하는지, 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S5279"] = { s: "Laura gets her first job in town, blackbirds eat the crops, Mary goes to college, and Laura gets into trouble at school but still becomes a certified schoolteacher.",
  q: ["Laura gets into trouble at school but still becomes a certified schoolteacher. Write a paragraph imagining what kind of trouble Laura might have gotten into, and how she still succeeded.",
      "This book shows several different family members reaching new milestones, a first job, going to college, becoming a teacher. Choose one and write a paragraph about a similar milestone you hope to reach someday.",
      "Write a paragraph giving your opinion on which event in this summary, Laura's first job, the blackbirds eating the crops, Mary going to college, or Laura becoming a teacher, would change the family's life the most, and explain your reasoning."],
  h: ["로라는 학교에서 말썽을 일으키지만 결국 정식 교사 자격을 얻어요. 로라가 어떤 말썽을 일으켰을지, 그럼에도 어떻게 해냈을지 상상해서 문단으로 써 보세요.",
      "이 책은 첫 직장, 대학 진학, 교사 되기 등 가족 여러 명이 각자 새로운 이정표에 이르는 모습을 보여 줘요. 이 중 하나를 골라 언젠가 이루고 싶은 비슷한 이정표를 문단으로 써 보세요.",
      "로라의 첫 직장, 찌르레기 떼가 농작물을 먹어 치운 일, 메리의 대학 진학, 로라의 교사 되기 중 가족의 삶을 가장 크게 바꿀 사건은 무엇이었을지, 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S5280"] = { s: "Fifteen-year-old Laura begins teaching and is courted by her future husband, Almanzo.",
  q: ["Fifteen-year-old Laura begins teaching and is courted by her future husband, Almanzo. Write a paragraph imagining what it would be like to start working as a teacher at such a young age.",
      "Laura takes on a big responsibility, becoming a teacher, at a young age. Write a paragraph about a responsibility you have taken on that felt like a lot for your age.",
      "Write a paragraph giving your opinion on whether fifteen is too young to begin working as a teacher, and explain your reasoning."],
  h: ["열다섯 살 로라는 교사 일을 시작하고, 훗날 남편이 될 앨먼조에게 구애받아요. 그렇게 어린 나이에 교사로 일을 시작한다면 어떨지 상상해서 문단으로 써 보세요.",
      "로라는 어린 나이에 교사가 되는 큰 책임을 맡아요. 여러분이 나이에 비해 크게 느껴졌던 책임을 맡았던 경험을 문단으로 써 보세요.",
      "열다섯 살은 교사로 일을 시작하기에 너무 어린 나이라고 생각하는지, 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S5281"] = { s: "During their first four years of marriage, Laura and Almanzo Wilder have a child and fight a losing battle in their attempts to succeed at farming on the South Dakota prairie.",
  q: ["Laura and Almanzo fight a losing battle in their attempts to succeed at farming on the South Dakota prairie. Write a paragraph imagining what troubles might have caused their farming attempts to fail.",
      "Laura and Almanzo keep trying even though their farming struggles do not go well. Write a paragraph about a time you kept trying at something even though it was not going well.",
      "Write a paragraph giving your opinion on whether Laura and Almanzo should have kept farming or tried something else, based on their losing battle, and explain your reasoning."],
  h: ["로라와 앨먼조는 사우스다코타 대초원에서 농사를 성공시키려 애쓰지만 결국 지고 마는 싸움을 벌여요. 그들의 농사가 실패한 원인이 되었을 어려움들을 상상해서 문단으로 써 보세요.",
      "로라와 앨먼조는 농사가 잘 안 풀려도 계속 노력해요. 여러분이 일이 잘 풀리지 않아도 계속 노력했던 경험을 문단으로 써 보세요.",
      "계속되는 패배를 볼 때 로라와 앨먼조가 농사를 계속해야 했을지 다른 일을 시도해야 했을지, 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S5282"] = { s: "Frodo Baggins, a young hobbit, sets out on a perilous journey with a band of warriors from different kingdoms to the Cracks of Doom to destroy the Dark Lord's Ring of Power.",
  q: ["Frodo sets out with a band of warriors from different kingdoms to destroy the Dark Lord's Ring of Power at the Cracks of Doom. Write a paragraph imagining what dangers this band might face traveling to such a place.",
      "Frodo joins a group of warriors from many different kingdoms who must work together. Write a paragraph about a time you worked with people who were very different from you toward one shared goal.",
      "Write a paragraph giving your opinion on why a small hobbit like Frodo, rather than one of the warriors, might be chosen to carry such a dangerous and powerful Ring, and explain your reasoning."],
  h: ["프로도는 어둠의 군주의 절대반지를 파멸의 틈으로 가져가 없애기 위해 여러 왕국에서 온 전사들과 함께 길을 떠나요. 이 일행이 그런 곳으로 가는 동안 마주했을 위험들을 상상해서 문단으로 써 보세요.",
      "프로도는 여러 다른 왕국에서 온 전사들과 함께 힘을 모아야 해요. 여러분과 아주 다른 사람들과 함께 하나의 목표를 위해 일했던 경험을 문단으로 써 보세요.",
      "왜 전사가 아니라 프로도 같은 작은 호빗이 그토록 위험하고 강력한 반지를 나르는 역할을 맡게 되었을지, 여러분의 생각과 이유를 문단으로 써 보세요."] };
ACT["S5283"] = { s: "Sam and Frodo must make their way deep into Mordor to destroy the Ring of Power in the fires of Mount Doom.",
  q: ["Sam and Frodo make their way deep into Mordor to destroy the Ring of Power in the fires of Mount Doom. Write a paragraph imagining what the journey through Mordor might look and feel like.",
      "Sam stays by Frodo's side through this dangerous journey. Write a paragraph about a friend who has stayed with you through a hard time, and what that meant to you.",
      "Write a paragraph giving your opinion on why it might take two companions, Sam and Frodo, instead of just one, to complete such a dangerous mission, and explain your reasoning."],
  h: ["샘과 프로도는 절대반지를 운명의 산 불길 속에서 없애기 위해 모르도르 깊숙이 나아가요. 모르도르를 지나는 여정이 어떤 모습이고 어떤 느낌일지 상상해서 문단으로 써 보세요.",
      "샘은 이 위험한 여정 내내 프로도 곁을 지켜요. 힘든 시기에 여러분 곁을 지켜 준 친구와, 그것이 여러분에게 어떤 의미였는지 문단으로 써 보세요.",
      "그런 위험한 임무를 완수하는 데 왜 한 명이 아니라 샘과 프로도, 두 동료가 필요했을지, 여러분의 생각과 이유를 문단으로 써 보세요."] };
ACT["S5285"] = { s: "A normal girl, Mia is shocked to learn that her father is the Prince of Genovia, a small European country, and that she is a princess and the heir to the throne.",
  q: ["Mia is shocked to learn that her father is a prince and that she is a princess and heir to the throne. Write a paragraph imagining how you would feel if you suddenly learned this kind of news about your own family.",
      "Mia's ordinary life suddenly changes because of news about her family. Write a paragraph about a piece of surprising news that changed something in your life, or imagine how you would react to big news.",
      "Write a paragraph giving your opinion on whether becoming a princess and heir to a throne would be exciting or stressful for a normal girl like Mia, and explain your reasoning."],
  h: ["미아는 아버지가 왕자이고 자신이 공주이자 왕위 계승자라는 사실을 알고 충격을 받아요. 여러분이 갑자기 자기 가족에 대해 이런 소식을 알게 된다면 어떤 기분일지 상상해서 문단으로 써 보세요.",
      "미아의 평범한 삶은 가족에 관한 소식 때문에 갑자기 바뀌어요. 여러분의 삶에서 무언가를 바꿔 놓은 놀라운 소식, 또는 큰 소식에 어떻게 반응할지 문단으로 써 보세요.",
      "미아 같은 평범한 소녀가 공주이자 왕위 계승자가 되는 것이 신날지 부담스러울지, 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S5286"] = { s: "Mia is swept up in a whirlwind of royal intrigue when she receives an unexpected announcement from her mother and an exasperating letter from a secret admirer.",
  q: ["Mia receives an unexpected announcement from her mother and an exasperating letter from a secret admirer. Write a paragraph imagining what these two events might be.",
      "Mia has to deal with two surprising things happening in her life at the same time. Write a paragraph about a time you had to deal with more than one surprising or stressful thing at once.",
      "Write a paragraph giving your opinion on which would be harder to handle, an unexpected family announcement or a letter from a secret admirer, and explain your reasoning."],
  h: ["미아는 엄마로부터 뜻밖의 발표를 듣고, 비밀 팬에게서 짜증 나는 편지를 받아요. 이 두 사건이 무엇일지 상상해서 문단으로 써 보세요.",
      "미아는 놀라운 두 가지 일을 한꺼번에 겪어야 해요. 여러분이 놀랍거나 부담스러운 일 두 가지 이상을 한꺼번에 겪었던 경험을 문단으로 써 보세요.",
      "뜻밖의 가족 발표와 비밀 팬의 편지 중 어느 쪽을 감당하기가 더 힘들지, 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S5287"] = { s: "Princess Mia lately she spends all her time doing one of three things: preparing for entering into Genovian society, slogging through Manhattan in December, and avoiding further smooches from her boyfriend, Kenny.",
  q: ["Mia spends her time preparing for Genovian society, getting through Manhattan in December, and avoiding smooches from her boyfriend, Kenny. Choose one of these three things and write a paragraph imagining what it is like for Mia.",
      "Mia is juggling several very different parts of her life at once. Write a paragraph about the different things you have to juggle in your own life, like school, family, and friends.",
      "Write a paragraph giving your opinion on which of Mia's three activities would be hardest for you personally, and explain your reasoning."],
  h: ["미아는 제노비아 사교계를 준비하는 일, 12월의 맨해튼을 헤쳐 나가는 일, 남자친구 케니의 입맞춤을 피하는 일로 시간을 보내요. 이 세 가지 중 하나를 골라 미아에게 그것이 어떨지 상상해서 문단으로 써 보세요.",
      "미아는 자기 삶의 여러 다른 부분을 한꺼번에 챙기고 있어요. 여러분이 한꺼번에 챙겨야 하는 학교, 가족, 친구 같은 여러 가지를 문단으로 써 보세요.",
      "미아의 세 가지 일 중 여러분에게 가장 힘들 것 같은 일은 무엇인지, 의견과 이유를 문단으로 써 보세요."] };
ACT["S5288"] = { s: "Taran, Assistant Pig-Keeper goes to find out who his parents are.",
  q: ["Taran, an Assistant Pig-Keeper, goes to find out who his parents are. Write a paragraph imagining what kind of parents Taran might hope or expect to find.",
      "Taran sets out on a search to learn about his own identity and family. Write a paragraph about something you would like to know more about regarding your own family or where you come from.",
      "Write a paragraph giving your opinion on why knowing who your parents are might matter so much to someone like Taran, and explain your reasoning."],
  h: ["돼지치기 조수 타란은 자신의 부모가 누구인지 알아내려 떠나요. 타란이 바라거나 기대했을 부모의 모습을 상상해서 문단으로 써 보세요.",
      "타란은 자신의 정체성과 가족을 알아보려고 여정을 떠나요. 여러분이 자신의 가족이나 뿌리에 대해 더 알고 싶은 것을 문단으로 써 보세요.",
      "타란 같은 사람에게 부모가 누구인지 아는 것이 왜 그렇게 중요할지, 여러분의 생각과 이유를 문단으로 써 보세요."] };
ACT["S5289"] = { s: "In Prydain, a young Assistant Pig-Keeper achieves honor in a quest to destroy the evil Black Cauldron.",
  q: ["The young Assistant Pig-Keeper achieves honor in a quest to destroy the evil Black Cauldron. Write a paragraph imagining what makes the Black Cauldron so evil and dangerous.",
      "An ordinary Assistant Pig-Keeper achieves something honorable through a difficult quest. Write a paragraph about a time you achieved something you were proud of, even though it seemed hard at first.",
      "Write a paragraph giving your opinion on whether an ordinary person, like an Assistant Pig-Keeper, can accomplish something as great as destroying an evil cauldron, and explain your reasoning."],
  h: ["어린 돼지치기 조수는 사악한 검은 가마솥을 없애는 여정에서 명예를 얻어요. 검은 가마솥을 그토록 사악하고 위험하게 만드는 것이 무엇일지 상상해서 문단으로 써 보세요.",
      "평범한 돼지치기 조수가 힘든 여정을 통해 명예로운 일을 해내요. 처음에는 힘들어 보였지만 자랑스럽게 해낸 일을 문단으로 써 보세요.",
      "돼지치기 조수 같은 평범한 사람이 사악한 가마솥을 없애는 것처럼 대단한 일을 해낼 수 있다고 생각하는지, 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S5290"] = { s: "Taran sets out with some strange companions to save his beloved land.",
  q: ["Taran sets out with some strange companions to save his beloved land. Write a paragraph imagining what these strange companions might be like.",
      "Taran cares deeply about protecting his land and works with unusual companions to do it. Write a paragraph about a place you care about, and what you would do to protect it.",
      "Write a paragraph giving your opinion on whether strange or unusual companions could still make a good team for such an important quest, and explain your reasoning."],
  h: ["타란은 특이한 동료들과 함께 자신이 사랑하는 땅을 구하러 떠나요. 이 특이한 동료들이 어떤 모습일지 상상해서 문단으로 써 보세요.",
      "타란은 자신의 땅을 지키는 일을 깊이 소중히 여기며, 그를 위해 특이한 동료들과 함께해요. 여러분이 소중히 여기는 장소와, 그곳을 지키기 위해 무엇을 할지 문단으로 써 보세요.",
      "특이하고 낯선 동료들이라도 그런 중요한 여정에 좋은 팀이 될 수 있을지, 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S5291"] = { s: "While undergoing training to be a princess, Eilonwy learns about magic for evil purposes.",
  q: ["While training to be a princess, Eilonwy learns about magic being used for evil purposes. Write a paragraph imagining how Eilonwy might react to discovering this dangerous magic.",
      "Eilonwy is training for one role, becoming a princess, but ends up learning something unexpected. Write a paragraph about a time you were learning or training for one thing and ended up discovering something else along the way.",
      "Write a paragraph giving your opinion on what Eilonwy should do with the knowledge of evil magic she has learned, and explain your reasoning."],
  h: ["공주가 되기 위한 훈련을 받는 동안, 에일로니는 마법이 나쁜 목적으로 쓰이고 있다는 것을 알게 돼요. 이 위험한 마법을 알게 된 에일로니가 어떻게 반응할지 상상해서 문단으로 써 보세요.",
      "에일로니는 공주가 되는 훈련을 받다가 뜻밖의 것을 알게 돼요. 여러분이 한 가지를 배우거나 훈련하다가 그 과정에서 다른 것을 알게 된 경험을 문단으로 써 보세요.",
      "에일로니가 알게 된 나쁜 마법에 관한 지식을 가지고 무엇을 해야 할지, 여러분의 생각과 이유를 문단으로 써 보세요."] };
ACT["S5293"] = { s: "When a group of young cats gets called by StarClan to fulfill a new prophecy, they take courage and set out on a long and dangerous journey to save Clans. Book #1",
  q: ["A group of young cats is called by StarClan to fulfill a new prophecy and set out on a long, dangerous journey. Write a paragraph imagining what dangers these young cats might face on their journey.",
      "The young cats take courage to set out on a journey to save their Clans. Write a paragraph about a time you needed courage to do something important for a group you cared about.",
      "Write a paragraph giving your opinion on whether young cats, rather than older, more experienced ones, were the right choice to carry out this important prophecy, and explain your reasoning."],
  h: ["젊은 고양이 무리는 스타클랜의 부름을 받아 새로운 예언을 이루기 위해 길고 위험한 여정에 나서요. 이 젊은 고양이들이 여정에서 마주했을 위험들을 상상해서 문단으로 써 보세요.",
      "젊은 고양이들은 자기 무리를 구하기 위해 용기를 내어 여정에 나서요. 여러분이 소중히 여기는 무리를 위해 중요한 일을 하려고 용기가 필요했던 경험을 문단으로 써 보세요.",
      "더 나이 많고 경험 많은 고양이가 아니라 젊은 고양이들이 이 중요한 예언을 이룰 적임자였다고 생각하는지, 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S5294"] = { s: "The six cats who are guided by StarClan's prophecy are coming back home to warn their clans of the coming destruction. On their way, they meet an unfamiliar tribe of cats with their own mysterious prophecy. Book #2",
  q: ["The six cats meet an unfamiliar tribe of cats with their own mysterious prophecy on their way home. Write a paragraph imagining what this unfamiliar tribe's prophecy might be about.",
      "The six cats must hurry home to warn their clans of coming destruction. Write a paragraph about a time you had to deliver important or urgent news to someone.",
      "Write a paragraph giving your opinion on whether the six cats should stop to learn about the unfamiliar tribe's prophecy or hurry straight home with their warning, and explain your reasoning."],
  h: ["여섯 고양이는 집으로 돌아가는 길에 자신들만의 신비한 예언을 가진 낯선 부족 고양이들을 만나요. 이 낯선 부족의 예언이 무엇에 관한 것일지 상상해서 문단으로 써 보세요.",
      "여섯 고양이는 다가오는 재앙을 무리에게 알리려고 서둘러 집으로 돌아가야 해요. 여러분이 누군가에게 중요하거나 급한 소식을 전해야 했던 경험을 문단으로 써 보세요.",
      "여섯 고양이가 낯선 부족의 예언을 알아보려고 멈춰야 할지, 아니면 곧장 집으로 서둘러 경고를 전해야 할지, 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S5295"] = { s: "The questing cats return to a forest with a chilling message: the Clans must move to a new home or risk extermination. But the problem is they have no idea where to go. Book #3",
  q: ["The cats return with a chilling message that the Clans must move to a new home or risk extermination, but they have no idea where to go. Write a paragraph imagining how the cats might begin searching for a new home with so little information.",
      "The Clans face a huge, urgent problem with no clear solution yet. Write a paragraph about a time you or your family faced a big problem without knowing right away how to solve it.",
      "Write a paragraph giving your opinion on what the Clans should do first now that they know they must move but do not know where, and explain your reasoning."],
  h: ["고양이들은 무리가 새 보금자리로 옮기지 않으면 몰살당할 수도 있다는 섬뜩한 소식을 가지고 돌아오지만, 어디로 가야 할지는 전혀 몰라요. 이렇게 아는 것이 거의 없는 상태에서 고양이들이 새 보금자리를 어떻게 찾기 시작할지 상상해서 문단으로 써 보세요.",
      "무리는 뚜렷한 해결책이 없는 크고 급한 문제를 마주해요. 여러분이나 가족이 바로 해결 방법을 알지 못한 채 큰 문제를 마주했던 경험을 문단으로 써 보세요.",
      "옮겨야 한다는 것은 알지만 어디로 가야 할지 모르는 지금, 무리가 가장 먼저 해야 할 일이 무엇일지, 여러분의 생각과 이유를 문단으로 써 보세요."] };
ACT["S5296"] = { s: "The Clans finally arrive at their new home, and they struggle to settle in the unfamiliar territory. Book #4",
  q: ["The Clans finally arrive at their new home but struggle to settle in the unfamiliar territory. Write a paragraph imagining what kinds of struggles they might face while settling into unfamiliar territory.",
      "The Clans have to adjust to living somewhere completely new and unfamiliar. Write a paragraph about a time you had to get used to a new place, like a new school, home, or neighborhood.",
      "Write a paragraph giving your opinion on what would help the Clans settle into their unfamiliar new territory more quickly, and explain your reasoning."],
  h: ["무리는 마침내 새 보금자리에 도착하지만 낯선 땅에 적응하느라 어려움을 겪어요. 낯선 땅에 자리 잡으며 겪었을 어려움들을 상상해서 문단으로 써 보세요.",
      "무리는 완전히 새롭고 낯선 곳에서 사는 것에 적응해야 해요. 여러분이 새 학교, 새집, 새 동네처럼 새로운 곳에 적응해야 했던 경험을 문단으로 써 보세요.",
      "무리가 낯선 새 땅에 더 빨리 자리 잡는 데 무엇이 도움이 될지, 여러분의 생각과 이유를 문단으로 써 보세요."] };
ACT["S5297"] = { s: "After the Clans settle into their new homes, they start fighting each other until their common enemy invades their territory. Book #5",
  q: ["The Clans start fighting each other until their common enemy invades their territory. Write a paragraph imagining how the Clans might react when the common enemy suddenly appears.",
      "The Clans stop fighting each other once they face a common enemy together. Write a paragraph about a time a shared problem brought you and others together instead of apart.",
      "Write a paragraph giving your opinion on whether the Clans will be able to set aside their fighting to face the common enemy successfully, and explain your reasoning."],
  h: ["무리는 서로 다투다가 공동의 적이 자신들의 땅을 침략하고 나서야 멈춰요. 공동의 적이 갑자기 나타났을 때 무리가 어떻게 반응할지 상상해서 문단으로 써 보세요.",
      "무리는 공동의 적을 함께 마주하자 서로 다투기를 멈춰요. 함께 겪은 문제가 여러분과 다른 사람들을 멀어지게 하는 대신 가깝게 만들어 준 경험을 문단으로 써 보세요.",
      "무리가 다툼을 내려놓고 공동의 적에 성공적으로 맞설 수 있을지, 여러분의 의견과 이유를 문단으로 써 보세요."] };
ACT["S5298"] = { s: "This book introduces Albert Einstein's life in a fun, engaging way and explores the world he lived in and changed.",
  q: ["This book explores the world Albert Einstein lived in and how he changed it. Write a paragraph about one way you imagine Einstein changed the world, based on what you have heard about him.",
      "This book shows how one person's life and ideas changed the world around him. Write a paragraph about how you would like to make a change in your own world someday.",
      "Write a paragraph giving your opinion on why it is important to learn about people like Albert Einstein who changed the world they lived in, and explain your reasoning."],
  h: ["이 책은 알베르트 아인슈타인이 살았던 세상과 그가 그 세상을 어떻게 바꾸었는지 탐구해요. 여러분이 들어 본 것을 바탕으로, 아인슈타인이 세상을 바꾼 방법 하나를 상상해서 문단으로 써 보세요.",
      "이 책은 한 사람의 삶과 생각이 그를 둘러싼 세상을 어떻게 바꾸었는지 보여 줘요. 여러분이 언젠가 자신의 세상에 어떤 변화를 만들고 싶은지 문단으로 써 보세요.",
      "알베르트 아인슈타인처럼 자신이 살던 세상을 바꾼 사람들에 대해 배우는 것이 왜 중요한지, 여러분의 생각과 이유를 문단으로 써 보세요."] };
ACT["S5299"] = { s: "This book presents the life of Annie Oakley, who was born in 1860 and became one of the best-loved and most famous women of her generation.",
  q: ["Annie Oakley became one of the best-loved and most famous women of her generation. Write a paragraph imagining what she might have done to earn that kind of fame.",
      "This book is about a woman who became famous doing something remarkable. Write a paragraph about a woman you admire, from history, your family, or your own life, and why you admire her.",
      "Write a paragraph giving your opinion on what qualities you think helped Annie Oakley become one of the most famous women of her generation, and explain your reasoning."],
  h: ["애니 오클리는 그 시대에 가장 사랑받고 가장 유명한 여성 중 한 명이 되었어요. 그녀가 그런 명성을 얻기 위해 무엇을 했을지 상상해서 문단으로 써 보세요.",
      "이 책은 놀라운 일을 해내어 유명해진 한 여성의 이야기예요. 역사 속, 가족, 또는 여러분 삶 속에서 존경하는 여성과 그 이유를 문단으로 써 보세요.",
      "어떤 자질이 애니 오클리를 그 시대 가장 유명한 여성 중 한 명으로 만들었다고 생각하는지, 여러분의 생각과 이유를 문단으로 써 보세요."] };
