// 간이 학습 질문 — Book No. S53 묶음. 사람이 아니라 AI 가 한 번 쓰고 굳힌 파일이다.
window.ACT = window.ACT || {};
var ACT = window.ACT;
ACT["S5300"] = { s: "This book introduces the life of Charles Darwin, the nineteenth-century British naturalist, and his accomplishments.",
  q: ["According to this book, what made Charles Darwin an important naturalist, and what accomplishments does the book describe?",
      "If you could study nature like Darwin did, what plants or animals would you want to observe closely? Explain why.",
      "Why do you think it is important for people to study the natural world carefully?"],
  h: ["이 책에 따르면 찰스 다윈은 왜 중요한 박물학자였나요? 이 책은 그의 어떤 업적을 설명하나요?",
      "다윈처럼 자연을 관찰할 수 있다면 어떤 식물이나 동물을 자세히 관찰하고 싶나요? 이유를 설명해 보세요.",
      "사람들이 자연 세계를 자세히 연구하는 것이 왜 중요하다고 생각하나요?"] };
ACT["S5301"] = { s: "This book introduces the life of Harry Houdini, the famous escape artist.",
  q: ["What does this book say made Harry Houdini famous as an escape artist?",
      "Have you ever felt stuck or trapped in a situation and had to find a clever way out? Describe what happened.",
      "Why do you think people were so amazed by Houdini's escapes?"],
  h: ["이 책에 따르면 해리 후디니는 무엇으로 탈출 마술사로 유명해졌나요?",
      "곤란하거나 갇힌 것 같은 상황에서 영리한 방법으로 빠져나온 적이 있나요? 그때 있었던 일을 적어 보세요.",
      "사람들이 후디니의 탈출을 그렇게 놀라워한 이유는 무엇이라고 생각하나요?"] };
ACT["S5302"] = { s: "This book presents the life of John F. Kennedy, including his military career and historic presidency.",
  q: ["What does this book say about John F. Kennedy's military career and his presidency?",
      "Have you ever admired a leader in your school or community? What did that person do that you admired?",
      "Why do you think Kennedy's presidency is remembered as historic?"],
  h: ["이 책은 존 F. 케네디의 군 경력과 대통령 시절에 대해 무엇을 말하고 있나요?",
      "학교나 우리 동네에서 존경했던 지도자가 있나요? 그 사람이 한 일 중에 존경스러웠던 점은 무엇인가요?",
      "케네디의 대통령 시절이 역사적으로 기억되는 이유는 무엇이라고 생각하나요?"] };
ACT["S5303"] = { s: "This book introduces the life of Johnny Appleseed, the famous American folk hero and nature lover.",
  q: ["What does this book describe about Johnny Appleseed as an American folk hero and nature lover?",
      "Have you ever planted a seed or taken care of a plant? Describe what you did and what happened.",
      "Why do you think people still tell stories about Johnny Appleseed today?"],
  h: ["이 책은 미국의 민속 영웅이자 자연을 사랑한 조니 애플시드에 대해 무엇을 설명하나요?",
      "씨앗을 심거나 식물을 돌본 적이 있나요? 무엇을 했고 어떤 일이 있었는지 적어 보세요.",
      "사람들이 오늘날에도 조니 애플시드 이야기를 하는 이유는 무엇이라고 생각하나요?"] };
ACT["S5304"] = { s: "This book presents the life of Louis Armstrong, including his childhood and legendary career as a musician and songwriter.",
  q: ["What does this book say about Louis Armstrong's childhood and his career as a musician and songwriter?",
      "Do you play a musical instrument or enjoy singing? Describe your experience with music.",
      "Why do you think Louis Armstrong's music became so legendary?"],
  h: ["이 책은 루이 암스트롱의 어린 시절과 음악가·작곡가로서의 전설적인 경력에 대해 무엇을 말하나요?",
      "악기를 연주하거나 노래하는 것을 좋아하나요? 음악과 관련된 나의 경험을 적어 보세요.",
      "루이 암스트롱의 음악이 그렇게 전설적으로 된 이유는 무엇이라고 생각하나요?"] };
ACT["S5305"] = { s: "This book presents the life of Maria Tallchief, the Osage Indian ballerina, and her affection for ballet.",
  q: ["What does this book say about Maria Tallchief's life as an Osage Indian ballerina and her love for ballet?",
      "Have you ever tried dancing or watched a dance performance? Describe how it made you feel.",
      "Why do you think it is important to follow something you love, like Maria Tallchief did with ballet?"],
  h: ["이 책은 오세이지족 발레리나 마리아 탈치프의 삶과 발레에 대한 그녀의 애정에 대해 무엇을 말하나요?",
      "춤을 춰 보거나 춤 공연을 본 적이 있나요? 그때 기분이 어땠는지 적어 보세요.",
      "마리아 탈치프처럼 좋아하는 것을 계속 따라가는 것이 왜 중요하다고 생각하나요?"] };
ACT["S5306"] = { s: "This is a biography of Mark Twain's fascinating life - the author of The Adventures of Huckleberry Finn.",
  q: ["What does this book describe about Mark Twain's fascinating life as the author of The Adventures of Huckleberry Finn?",
      "Have you ever read a book that made you want to learn more about its author? What did you want to know?",
      "Why do you think Mark Twain's life is considered fascinating enough to write a whole book about?"],
  h: ["이 책은 <허클베리 핀의 모험>의 작가 마크 트웨인의 흥미로운 삶에 대해 무엇을 설명하나요?",
      "어떤 책을 읽고 그 작가에 대해 더 알고 싶어진 적이 있나요? 무엇이 궁금했는지 적어 보세요.",
      "마크 트웨인의 삶이 책 한 권으로 쓰일 만큼 흥미롭다고 생각되는 이유는 무엇인가요?"] };
ACT["S5307"] = { s: "This book is a biography of Martin Luther King Jr. and discusses his childhood, schooling, beliefs, role in the civil rights movement, etc.",
  q: ["What does this biography describe about Martin Luther King Jr.'s childhood, schooling, beliefs, and role in the civil rights movement?",
      "Have you ever stood up for something you believed was right, even if it was difficult? Describe what happened.",
      "Why do you think Martin Luther King Jr.'s beliefs and actions are still remembered today?"],
  h: ["이 전기는 마틴 루서 킹 주니어의 어린 시절, 학교생활, 신념, 그리고 시민권 운동에서의 역할에 대해 무엇을 설명하나요?",
      "어려운 상황에서도 옳다고 믿는 것을 위해 나선 적이 있나요? 무슨 일이 있었는지 적어 보세요.",
      "마틴 루서 킹 주니어의 신념과 행동이 오늘날까지 기억되는 이유는 무엇이라고 생각하나요?"] };
ACT["S5308"] = { s: "This book presents the life of Ronald Reagan, including his childhood, career as a film star, and popular presidency.",
  q: ["What does this book say about Ronald Reagan's childhood, his career as a film star, and his presidency?",
      "Have you ever known someone who had two very different careers, like acting and then politics? What do you think that would be like?",
      "Why do you think Reagan's presidency is described as popular?"],
  h: ["이 책은 로널드 레이건의 어린 시절, 영화배우로서의 경력, 그리고 대통령 시절에 대해 무엇을 말하나요?",
      "연기와 정치처럼 완전히 다른 두 가지 일을 한 사람을 알고 있나요? 그런 삶은 어떨 것 같나요?",
      "레이건의 대통령 시절이 인기가 많았다고 표현되는 이유는 무엇이라고 생각하나요?"] };
ACT["S5309"] = { s: "This is a biography of Thomas Edison, who has changed the world with revolutionary inventions.",
  q: ["What does this book say about how Thomas Edison changed the world with his inventions?",
      "If you could invent something to make life easier, what would you invent? Describe your idea.",
      "Why do you think Edison's inventions are still important today?"],
  h: ["이 책은 토머스 에디슨이 혁신적인 발명품으로 세상을 어떻게 바꾸었는지 무엇을 말하나요?",
      "삶을 더 편리하게 만들 발명품을 만들 수 있다면 무엇을 만들고 싶나요? 내 아이디어를 적어 보세요.",
      "에디슨의 발명품이 오늘날에도 여전히 중요한 이유는 무엇이라고 생각하나요?"] };
ACT["S5310"] = { s: "This book introduces the life of Thomas Jefferson - including his historic involvement in the writing of the Declaration of Independence.",
  q: ["What does this book describe about Thomas Jefferson's historic involvement in writing the Declaration of Independence?",
      "Have you ever helped write something important, like a class rule or a letter? Describe what you wrote.",
      "Why do you think writing the Declaration of Independence was such an important task?"],
  h: ["이 책은 토머스 제퍼슨이 독립선언서를 쓰는 데 역사적으로 어떤 역할을 했는지 무엇을 설명하나요?",
      "학급 규칙이나 편지처럼 중요한 글을 써 본 적이 있나요? 무엇을 썼는지 적어 보세요.",
      "독립선언서를 쓰는 일이 그렇게 중요한 과제였던 이유는 무엇이라고 생각하나요?"] };
ACT["S5311"] = { s: "This book covers the life of Wolfgang Amadeus Mozart, the eighteenth-century Austrian composer.",
  q: ["What does this book describe about Wolfgang Amadeus Mozart's life as an eighteenth-century Austrian composer?",
      "Have you ever listened to classical music? Describe how it made you feel.",
      "Why do you think Mozart's music is still played and admired hundreds of years later?"],
  h: ["이 책은 18세기 오스트리아 작곡가 볼프강 아마데우스 모차르트의 삶에 대해 무엇을 설명하나요?",
      "클래식 음악을 들어 본 적이 있나요? 그때 기분이 어땠는지 적어 보세요.",
      "모차르트의 음악이 수백 년이 지난 지금도 연주되고 사랑받는 이유는 무엇이라고 생각하나요?"] };
ACT["S5321"] = { s: "After narrowly escaping the threatening clutches of the wicked Count Olaf, the three Baudelaire orphans are taken in by a kindly herpetologist. They live happily for a short time. Book #2",
  q: ["In this book, the three Baudelaire orphans escape Count Olaf and are taken in by a kindly herpetologist. What do you think their life with him might have been like?",
      "Have you ever stayed with a relative or family friend for a while? Describe what that experience was like.",
      "Why do you think the orphans' happiness with the herpetologist is described as only lasting 'a short time'? What do you think might happen next?"],
  h: ["이 책에서 보들레르 남매는 올라프 백작에게서 도망쳐 친절한 파충류학자에게 맡겨져요. 그와 함께한 생활은 어땠을 것 같나요?",
      "친척이나 가족의 친구 집에서 한동안 지내 본 적이 있나요? 그 경험이 어땠는지 적어 보세요.",
      "파충류학자와 지낸 행복한 시간이 '짧은 기간'이었다고 하는 이유는 무엇일까요? 다음에 무슨 일이 일어날 것 같나요?"] };
ACT["S5322"] = { s: "After the Baudelaire orphans are sent to live with fearful Aunt Josephine, still Catastrophes and misfortune continue to torment them. Aunt Josephine offers little protection against Count Olaf's treachery. Book #3",
  q: ["The Baudelaire orphans go to live with fearful Aunt Josephine in this book. What kind of person does the summary suggest she is?",
      "Have you ever met someone who was very fearful or worried about many things? Describe that person.",
      "Why do you think Aunt Josephine offers little protection against Count Olaf, even though she is the orphans' guardian?"],
  h: ["보들레르 남매는 이 책에서 겁 많은 조세핀 이모에게 가게 돼요. 요약을 보면 이모는 어떤 사람일 것 같나요?",
      "많은 것을 두려워하고 걱정하는 사람을 만난 적이 있나요? 그 사람에 대해 적어 보세요.",
      "조세핀 이모가 남매의 보호자인데도 올라프 백작으로부터 남매를 거의 지켜 주지 못하는 이유는 무엇일까요?"] };
ACT["S5324"] = { s: "Franny K. Stein, the Mad Scientist, is determined to be elected class president to put everything under her control. She uses her Atomic Combiner to create The Frandidate, the special suit that helps her seem to be whatever a voter wants her to be. Book #7",
  q: ["Franny uses her Atomic Combiner to create the Frandidate, a suit that makes her seem like whatever a voter wants. Why do you think she came up with this plan?",
      "Have you ever wanted to be chosen for something, like a class job or a team? What did you do to try to be chosen?",
      "Do you think it is fair for a candidate to change to seem like whatever people want, like Franny does? Explain your thinking."],
  h: ["프래니는 원자 결합기로 유권자가 원하는 대로 변신하는 '프랜디데이트' 옷을 만들어요. 그녀가 왜 이런 계획을 세웠을까요?",
      "학급 임원이나 팀원처럼 무언가에 뽑히고 싶었던 적이 있나요? 뽑히려고 무엇을 했나요?",
      "프래니처럼 후보가 사람들이 원하는 대로 변하는 것이 공정하다고 생각하나요? 내 생각을 적어 보세요."] };
ACT["S5326"] = { s: "Matilda applies her untapped mental powers to rid the school of the evil, child-hating headmistress, Miss Trunchbull, in order to save her teacher, Miss Honey.",
  q: ["Matilda uses her untapped mental powers to get rid of the evil headmistress Miss Trunchbull. What do you think Matilda's powers might let her do?",
      "Have you ever wanted to help a teacher or friend who was being treated unfairly? What did you do or wish you could do?",
      "Why do you think Matilda works so hard to save her teacher, Miss Honey?"],
  h: ["마틸다는 숨겨진 정신적인 힘을 사용해 사악한 교장 트런치불 선생님을 없애려 해요. 마틸다의 힘은 무엇을 할 수 있을 것 같나요?",
      "부당한 대우를 받는 선생님이나 친구를 돕고 싶었던 적이 있나요? 무엇을 했거나 하고 싶었나요?",
      "마틸다가 허니 선생님을 구하려고 그렇게 애쓰는 이유는 무엇이라고 생각하나요?"] };
ACT["S5327"] = { s: "Frank and Joe Hardy look for clues after their friend's father is accused of stealing a treasure.",
  q: ["Frank and Joe Hardy look for clues after their friend's father is accused of stealing a treasure. What kind of clues do you imagine they might search for?",
      "Have you ever tried to solve a mystery or figure out what really happened in a confusing situation? Describe it.",
      "Why do you think Frank and Joe want to help their friend so much?"],
  h: ["프랭크와 조 하디는 친구 아버지가 보물을 훔쳤다는 혐의를 받은 뒤 단서를 찾아요. 어떤 단서를 찾을 것 같나요?",
      "수수께끼를 풀거나 혼란스러운 상황에서 진짜 무슨 일이 있었는지 알아내려 한 적이 있나요? 그 경험을 적어 보세요.",
      "프랭크와 조가 친구를 그렇게까지 도우려는 이유는 무엇이라고 생각하나요?"] };
ACT["S5329"] = { s: "This book tells the story of Sojourner Truth, discussing her childhood as a slave and looking at her work to secure the rights of all women after she gained her freedom.",
  q: ["This book tells about Sojourner Truth's childhood as a slave and her work to secure the rights of all women after she gained her freedom. What do you think that work involved?",
      "Have you ever spoken up for someone else's rights or fairness? Describe what you did.",
      "Why do you think Sojourner Truth continued fighting for rights even after she gained her own freedom?"],
  h: ["이 책은 소저너 트루스가 노예로 보낸 어린 시절과 자유를 얻은 뒤 모든 여성의 권리를 지키기 위해 한 일을 말해요. 그 일은 어떤 것이었을까요?",
      "다른 사람의 권리나 공정함을 위해 목소리를 낸 적이 있나요? 무엇을 했는지 적어 보세요.",
      "소저너 트루스가 자신의 자유를 얻은 뒤에도 계속 권리를 위해 싸운 이유는 무엇이라고 생각하나요?"] };
ACT["S5330"] = { s: "Read about the fascinating life of our nation's second First Lady, a woman who helped shape the early history of the United States.",
  q: ["What does this book describe about Abigail Adams's life as the second First Lady and her role in shaping early American history?",
      "Have you ever supported someone close to you while they did something important, like Abigail Adams supported her husband? Describe what you did.",
      "Why do you think it is important to remember the First Ladies' contributions to history, not just the presidents'?"],
  h: ["이 책은 두 번째 퍼스트레이디였던 애비게일 애덤스의 삶과 초기 미국 역사를 만드는 데 한 역할에 대해 무엇을 설명하나요?",
      "애비게일 애덤스가 남편을 도왔듯, 가까운 사람이 중요한 일을 할 때 곁에서 도와준 적이 있나요? 무엇을 했는지 적어 보세요.",
      "대통령뿐 아니라 퍼스트레이디들의 공헌도 기억하는 것이 왜 중요하다고 생각하나요?"] };
ACT["S5335"] = { s: "In this book, middle-school slacker Greg suddenly finds himself dealing with the pressures of increased responsibilities. He even goes through the awkward changes that come with getting older--all without his best friend, Rowley, at his side.",
  q: ["In this book, Greg deals with the pressures of growing up without his best friend Rowley by his side. What kinds of pressures do you think he faces?",
      "Have you ever gone through a change without your best friend there to help you? Describe how that felt.",
      "Why do you think having a best friend around makes it easier to deal with awkward changes?"],
  h: ["이 책에서 그렉은 가장 친한 친구 로울리 없이 자라면서 여러 부담을 겪어요. 어떤 부담들을 겪을 것 같나요?",
      "가장 친한 친구가 곁에 없는 상태에서 어떤 변화를 겪어 본 적이 있나요? 그때 기분이 어땠는지 적어 보세요.",
      "친한 친구가 곁에 있으면 힘든 변화를 견디기가 더 쉬워지는 이유는 무엇이라고 생각하나요?"] };
ACT["S5336"] = { s: "Greg accidentally damages school property while he is trying to earn money. He believes that the police are looking for him. When a surprise blizzard hits, he gets stuck indoors with his family for the holidays.",
  q: ["Greg accidentally damages school property and believes the police are looking for him. Why do you think he feels so worried about it?",
      "Have you ever made a mistake and worried a lot about getting in trouble for it? Describe what happened.",
      "Do you think being stuck indoors during a blizzard with your family for the holidays would be fun or stressful? Explain your answer."],
  h: ["그렉은 실수로 학교 시설물을 망가뜨리고 경찰이 자기를 찾고 있다고 믿어요. 왜 그렇게 걱정한다고 생각하나요?",
      "실수를 하고 혼날까 봐 많이 걱정한 적이 있나요? 무슨 일이 있었는지 적어 보세요.",
      "눈보라 때문에 명절 동안 가족과 집 안에 갇혀 있는 것이 재미있을까요, 힘들까요? 내 생각을 적어 보세요."] };
ACT["S5337"] = { s: "Greg's middle school life turns upside down when there is Valentine's Day Dance. He scrambles to find a date, worrying he may get left out in the cold on the big night. Who will arrive at the dance triumphantly, and who will end up being the third wheel?",
  q: ["Greg scrambles to find a date for the Valentine's Day dance in this book. Why do you think he worries about being left out?",
      "Have you ever worried about being left out of an event with your friends? Describe how you felt.",
      "Why do you think school dances can feel like such a big deal to middle schoolers like Greg?"],
  h: ["그렉은 이 책에서 밸런타인데이 댄스파티에 갈 상대를 찾느라 허둥대요. 왜 소외될까 봐 걱정한다고 생각하나요?",
      "친구들 사이에서 나만 빠질까 봐 걱정한 적이 있나요? 그때 기분이 어땠는지 적어 보세요.",
      "그렉 같은 중학생들에게 학교 댄스파티가 그렇게 큰일처럼 느껴지는 이유는 무엇이라고 생각하나요?"] };
ACT["S5338"] = { s: "When his best friend Rowley ditches him, Greg attempts to find new friends only to know that the task is challenging. To change his luck, Greg decides to take a leap of faith and turn his decisions over.",
  q: ["When Rowley ditches him, Greg tries to find new friends but finds it challenging. Why do you think making new friends can be difficult?",
      "Have you ever had to make new friends after losing touch with an old friend? Describe your experience.",
      "What do you think about Greg's idea of turning his decisions over to chance instead of choosing carefully?"],
  h: ["로울리가 그렉을 떠난 뒤 그렉은 새 친구를 사귀려 하지만 쉽지 않아요. 새 친구를 사귀는 것이 어려운 이유는 무엇일까요?",
      "오래된 친구와 멀어진 뒤 새로운 친구를 사귀어야 했던 적이 있나요? 그 경험을 적어 보세요.",
      "그렉이 신중히 선택하는 대신 운에 결정을 맡기려는 생각에 대해 나는 어떻게 생각하나요?"] };
ACT["S5339"] = { s: "This book explores the life of Neil Armstrong, the American astronaut who became the first person ever to set foot on the Moon.",
  q: ["What does this book describe about Neil Armstrong's journey to becoming the first person to set foot on the Moon?",
      "If you could travel to space like Neil Armstrong, where would you want to go and what would you want to see?",
      "Why do you think being the first person to walk on the Moon was such an important moment in history?"],
  h: ["이 책은 닐 암스트롱이 달에 첫발을 디딘 사람이 되기까지의 여정에 대해 무엇을 설명하나요?",
      "닐 암스트롱처럼 우주로 갈 수 있다면 어디로 가서 무엇을 보고 싶나요?",
      "달에 첫발을 디딘 것이 역사적으로 그렇게 중요한 순간이었던 이유는 무엇이라고 생각하나요?"] };
ACT["S5340"] = { s: "This is a biography of Marco Polo, who traveled from Venice to the kingdom of Kublai Khan more than seven hundred years ago.",
  q: ["What does this book describe about Marco Polo's journey from Venice to the kingdom of Kublai Khan?",
      "Have you ever traveled somewhere far from home? Describe what the journey was like.",
      "Why do you think traveling such a long distance more than seven hundred years ago would have been so difficult?"],
  h: ["이 책은 마르코 폴로가 베네치아에서 쿠빌라이 칸의 왕국까지 간 여정에 대해 무엇을 설명하나요?",
      "집에서 멀리 떨어진 곳으로 여행해 본 적이 있나요? 그 여정이 어땠는지 적어 보세요.",
      "칠백 년도 더 전에 그렇게 먼 거리를 여행하는 것이 왜 그렇게 힘들었을 것 같나요?"] };
ACT["S5341"] = { s: "This book presents the life of Steve Jobs, who was the founder of Apple, and his obsession with a computer.",
  q: ["What does this book say about Steve Jobs founding Apple and his obsession with a computer?",
      "Do you use any devices or apps made by Apple? Describe how you use them.",
      "Why do you think being obsessed with an idea can help someone build something as big as Apple?"],
  h: ["이 책은 스티브 잡스가 애플을 세운 것과 컴퓨터에 대한 그의 집착에 대해 무엇을 말하나요?",
      "애플이 만든 기기나 앱을 사용하고 있나요? 어떻게 사용하는지 적어 보세요.",
      "하나의 아이디어에 몰두하는 것이 애플 같은 큰 회사를 만드는 데 어떻게 도움이 되었을까요?"] };
ACT["S5342"] = { s: "This is a biography of the beloved writer Theodor Geisel, better known as Dr. Seuss.",
  q: ["What does this book describe about the life of Theodor Geisel, the beloved writer known as Dr. Seuss?",
      "What is your favorite Dr. Seuss book or story? Describe why you like it.",
      "Why do you think Dr. Seuss's books are still loved by children today?"],
  h: ["이 책은 닥터 수스로 더 잘 알려진 시어도어 가이젤의 삶에 대해 무엇을 설명하나요?",
      "내가 가장 좋아하는 닥터 수스의 책이나 이야기는 무엇인가요? 왜 좋아하는지 적어 보세요.",
      "닥터 수스의 책들이 오늘날 아이들에게도 여전히 사랑받는 이유는 무엇이라고 생각하나요?"] };
ACT["S5343"] = { s: "This book introduces the life of Queen Elizabeth, including her time imprisoned in the Tower of London.",
  q: ["What does this book describe about Queen Elizabeth's life, including the time she was imprisoned in the Tower of London?",
      "Have you ever felt trapped or unable to do what you wanted? Describe how you handled it.",
      "Why do you think it is surprising that a future queen was once imprisoned?"],
  h: ["이 책은 런던탑에 갇혀 있던 시절을 포함해 엘리자베스 여왕의 삶에 대해 무엇을 설명하나요?",
      "하고 싶은 것을 할 수 없이 갇힌 듯한 기분을 느낀 적이 있나요? 어떻게 견뎌냈는지 적어 보세요.",
      "미래의 여왕이 한때 갇혀 있었다는 것이 놀랍다고 생각하는 이유는 무엇인가요?"] };
ACT["S5344"] = { s: "This is a biography of Barack Obama, the first African-American president.",
  q: ["What does this book describe about Barack Obama becoming the first African-American president?",
      "Have you ever been the first person in your family or class to do something? Describe what it was.",
      "Why do you think it was an important moment in history when Obama became president?"],
  h: ["이 책은 버락 오바마가 최초의 아프리카계 미국인 대통령이 된 과정에 대해 무엇을 설명하나요?",
      "가족이나 반에서 처음으로 무언가를 해낸 적이 있나요? 그것이 무엇이었는지 적어 보세요.",
      "오바마가 대통령이 된 것이 역사적으로 중요한 순간이었던 이유는 무엇이라고 생각하나요?"] };
ACT["S5345"] = { s: "When a baby rat becomes Zoe's pet, she tries her best to keep him safe from all who would do him harm, especially Burt, the burger-van man.",
  q: ["Zoe tries her best to keep her pet rat safe from Burt, the burger-van man. Why do you think Burt might be a danger to the rat?",
      "Have you ever had a pet, or wished for one, that you wanted to protect? Describe your feelings about that animal.",
      "Why do you think Zoe cares so much about protecting a rat, an animal many people are afraid of?"],
  h: ["조는 버거 트럭을 운영하는 버트로부터 애완용 쥐를 지키려고 최선을 다해요. 버트가 쥐에게 왜 위험한 존재일까요?",
      "지켜 주고 싶었던 반려동물이 있거나, 갖고 싶었던 적이 있나요? 그 동물에 대한 내 마음을 적어 보세요.",
      "많은 사람이 무서워하는 쥐를 조가 그렇게 애써 지키려는 이유는 무엇이라고 생각하나요?"] };
ACT["S5346"] = { s: "Stella Saxby, a little girl, is the only heir to Saxby Hall. But her awful Aunt Alberta is on her way to take it from her. Luckily, Stella meets a secret weapon, which is a little spooky, up her sleeve.",
  q: ["Stella's awful Aunt Alberta is trying to take Saxby Hall away from her. Why do you think Aunt Alberta wants the hall so badly?",
      "Have you ever had to stand up to someone older who was being unfair to you? Describe what happened.",
      "What do you imagine Stella's spooky secret weapon might be, based on the summary?"],
  h: ["스텔라의 못된 알베르타 이모는 색스비 저택을 빼앗으려 해요. 이모가 그 저택을 그렇게 원하는 이유는 무엇일까요?",
      "나이 많은 사람이 나에게 부당하게 굴 때 맞서 본 적이 있나요? 그때 무슨 일이 있었는지 적어 보세요.",
      "요약을 보면 스텔라의 으스스한 비밀 무기는 무엇일 것 같나요? 상상해서 적어 보세요."] };
ACT["S5347"] = { s: "Jack's grandpa used to fly Spitfire in the war, but now he wears his slippers to the supermarket and often forgets Jack's name. Jack's grandpa plots a daring escape when he is forced to stay in a dreadful home for the elderly.",
  q: ["Jack's grandpa plots a daring escape from the home for the elderly. Why do you think he wants to escape so badly?",
      "Have you ever spent time with a grandparent or older relative who told you stories about the past? Describe what you learned.",
      "Why do you think it is sad that Jack's grandpa, who once flew planes in the war, now forgets Jack's name?"],
  h: ["잭의 할아버지는 노인 요양원에서 탈출할 계획을 세워요. 할아버지가 왜 그렇게 절실히 탈출하고 싶어 할까요?",
      "할머니나 할아버지 같은 어른 친척과 시간을 보내며 옛날이야기를 들은 적이 있나요? 무엇을 배웠는지 적어 보세요.",
      "전쟁 때 비행기를 몰던 할아버지가 지금은 잭의 이름조차 잊어버린다는 것이 왜 슬프다고 생각하나요?"] };
ACT["S5348"] = { s: "This book is about a boy named Jack Gantos, who gets grounded for the whole summer vacation. Instead of planning for a vacation, he has to help his elderly neighbor write obituaries.",
  q: ["Jack gets grounded for the whole summer and has to help his elderly neighbor write obituaries instead of going on vacation. Why do you think this punishment might teach him something unexpected?",
      "Have you ever been given a chore or punishment that ended up teaching you something you didn't expect? Describe what happened.",
      "Why do you think writing obituaries about people's lives could be an interesting way to spend a summer?"],
  h: ["잭은 여름 방학 내내 외출 금지를 당해서, 방학 대신 나이 든 이웃이 부고 기사 쓰는 것을 도와야 해요. 이 벌이 뜻밖의 것을 가르쳐 줄 것 같은 이유는 무엇인가요?",
      "예상하지 못한 것을 배우게 된 집안일이나 벌이 있었나요? 무슨 일이 있었는지 적어 보세요.",
      "사람들의 삶에 대한 부고 기사를 쓰는 것이 여름을 보내는 흥미로운 방법이 될 수 있다고 생각하는 이유는 무엇인가요?"] };
ACT["S5349"] = { s: "This book shows evidence that confirms and refutes the existence of Bigfoot, featuring photographs, and illustrations and describing the role of Bigfoot in North American folklore.",
  q: ["This book shows evidence that both confirms and refutes the existence of Bigfoot. What kind of evidence do you think people use to argue for or against Bigfoot?",
      "Have you ever heard a story or legend, like Bigfoot, that you were not sure was true? Describe it.",
      "Do you think Bigfoot is real or just a folklore legend? Explain your thinking."],
  h: ["이 책은 빅풋의 존재를 확인해 주기도 하고 부정하기도 하는 증거들을 보여줘요. 사람들은 빅풋을 두고 어떤 증거를 사용해 찬반을 주장할까요?",
      "빅풋처럼 진짜인지 아닌지 확신할 수 없었던 이야기나 전설을 들어 본 적이 있나요? 그것에 대해 적어 보세요.",
      "빅풋이 진짜라고 생각하나요, 아니면 그냥 전설이라고 생각하나요? 내 생각을 설명해 보세요."] };
ACT["S5350"] = { s: "This book consists of humorous tales from the author's childhood, including summer vacation in Norway and life in English boarding schools.",
  q: ["This book has humorous tales from Roald Dahl's childhood, including his summer vacations in Norway and his time in English boarding schools. What kind of stories do you imagine he might tell about boarding school?",
      "Have you ever had a funny or memorable experience during a summer vacation? Describe what happened.",
      "Why do you think childhood memories, even ordinary ones, can make for such entertaining stories?"],
  h: ["이 책에는 로알드 달의 노르웨이 여름 방학과 영국 기숙학교 시절을 포함한 유머러스한 어린 시절 이야기들이 담겨 있어요. 기숙학교에 대해 어떤 이야기를 했을 것 같나요?",
      "여름 방학 동안 재미있거나 기억에 남는 일이 있었나요? 무슨 일이 있었는지 적어 보세요.",
      "평범해 보이는 어린 시절의 기억도 왜 이렇게 재미있는 이야기가 될 수 있다고 생각하나요?"] };
ACT["S5351"] = { s: "This book discusses evidence from paleontologists showing that T.rex both scavenged and hunted for food.",
  q: ["This book discusses evidence showing that T. rex both scavenged and hunted for food. What do you think scavenging means compared to hunting?",
      "Have you ever changed your mind about something after learning new evidence? Describe what happened.",
      "Why do you think scientists study fossil evidence carefully before deciding how an ancient animal like T. rex behaved?"],
  h: ["이 책은 티라노사우루스가 먹이를 찾아다니는 청소 동물이면서 동시에 사냥꾼이었다는 것을 보여주는 증거를 다뤄요. 청소 동물이라는 것은 사냥과 어떻게 다르다고 생각하나요?",
      "새로운 증거를 알게 된 뒤 생각을 바꾼 적이 있나요? 무슨 일이 있었는지 적어 보세요.",
      "과학자들이 티라노사우루스 같은 고대 동물의 행동을 판단하기 전에 화석 증거를 꼼꼼히 조사하는 이유는 무엇이라고 생각하나요?"] };
ACT["S5352"] = { s: "Thirteen-year-old Sophie and her cousin Cody record their transatlantic crossing aboard \"The Wanderer,\" a forty-five-foot sailboat.",
  q: ["Sophie and her cousin Cody record their transatlantic crossing aboard the sailboat 'The Wanderer.' What do you imagine that journey across the ocean might be like?",
      "Have you ever kept a journal or recorded something important that happened to you? Describe what you wrote about.",
      "Why do you think sailing across the ocean on a boat would be both exciting and difficult?"],
  h: ["소피와 사촌 코디는 '더 원더러'라는 배를 타고 대서양을 건너는 항해를 기록해요. 그 바다를 건너는 여정은 어떤 모습일 것 같나요?",
      "나에게 있었던 중요한 일을 일기나 기록으로 남긴 적이 있나요? 무엇에 대해 썼는지 적어 보세요.",
      "배를 타고 바다를 건너는 것이 왜 신나면서도 힘든 일일 것 같나요?"] };
ACT["S5353"] = { s: "Gen, the ingenious thief, goes on an adventure to steal a precious stone hidden in a remote temple of god.",
  q: ["Gen, the ingenious thief, goes on an adventure to steal a precious stone hidden in a remote temple. What challenges do you imagine he might face trying to steal something so well hidden?",
      "Have you ever gone on a difficult mission or task that required cleverness to complete? Describe what you did.",
      "Why do you think Gen is described as 'ingenious'? What do you think that means about how he solves problems?"],
  h: ["영리한 도둑 겐은 외딴 신전에 숨겨진 보석을 훔치러 모험을 떠나요. 그렇게 꽁꽁 숨겨진 것을 훔치려면 어떤 어려움을 겪을 것 같나요?",
      "영리함이 필요했던 어렵고 힘든 임무를 해낸 적이 있나요? 무엇을 했는지 적어 보세요.",
      "겐이 '영리하다'고 불리는 이유는 무엇일까요? 그가 문제를 어떻게 해결할 것 같은지 적어 보세요."] };
ACT["S5354"] = { s: "The book features the crisscrossing lives of four teenagers in a small town in the 1960s. They search for the meaning of life as they experience new feelings and thoughts.",
  q: ["This book features the crisscrossing lives of four teenagers searching for the meaning of life in a small town during the 1960s. What kinds of new feelings and thoughts do you think teenagers might experience?",
      "Have you ever felt like your life crossed paths with someone else's in an important way? Describe what happened.",
      "Why do you think searching for the meaning of life is something many teenagers think about?"],
  h: ["이 책은 1960년대 작은 마을에서 인생의 의미를 찾는 네 청소년의 엇갈리는 삶을 다뤄요. 청소년들은 어떤 새로운 감정과 생각을 경험할 것 같나요?",
      "누군가의 인생과 내 인생이 중요하게 얽힌다고 느낀 적이 있나요? 무슨 일이 있었는지 적어 보세요.",
      "많은 청소년이 인생의 의미를 고민하는 이유는 무엇이라고 생각하나요?"] };
ACT["S5355"] = { s: "During the 1967 school year, on Wednesday afternoons when all his classmates go to religion classes, seventh-grader Holling stays in Mrs. Baker's classroom where they read the plays of Shakespeare and he learns about the world he lives in.",
  q: ["While his classmates go to religion classes, Holling stays with Mrs. Baker reading Shakespeare's plays. What do you think he might learn from reading Shakespeare?",
      "Have you ever been left alone with a teacher while your classmates did something else? Describe how that felt.",
      "Why do you think reading old plays like Shakespeare's could help Holling learn about the world he lives in?"],
  h: ["친구들이 종교 수업을 들으러 갈 때, 홀링은 베이커 선생님과 함께 남아 셰익스피어 희곡을 읽어요. 셰익스피어를 읽으며 무엇을 배울 것 같나요?",
      "반 친구들이 다른 것을 할 때 선생님과 단둘이 남아 본 적이 있나요? 그때 기분이 어땠는지 적어 보세요.",
      "셰익스피어 같은 오래된 희곡을 읽는 것이 홀링이 자신이 사는 세상을 이해하는 데 어떻게 도움이 될 것 같나요?"] };
ACT["S5356"] = { s: "Ali Baba and the Forty Thieves, Aladdin, Sinbad the Sailor: these are just some of the strange and amazing stories that clever Scheherazade tells to captivate her husband, King Shahryar...and to save her own life. Each one is more fantastic than the last, filled with demons and dervishes, caliphs and genies, men transformed into dogs and monsters with eyes that glow. Like the king, children will find themselves enchanted by every tale.",
  q: ["Scheherazade tells amazing stories, like Ali Baba, Aladdin, and Sinbad the Sailor, to save her own life. Why do you think telling stories could help save someone's life?",
      "Have you ever told a story to entertain someone or to get out of a difficult situation? Describe what happened.",
      "Which of the fantastic elements described, like genies, demons, or monsters with glowing eyes, sounds most interesting to you? Explain why."],
  h: ["셰헤라자드는 알리바바, 알라딘, 신드바드의 선원 같은 놀라운 이야기들을 들려주며 자신의 목숨을 구해요. 이야기를 들려주는 것이 왜 누군가의 목숨을 구할 수 있다고 생각하나요?",
      "누군가를 즐겁게 하거나 어려운 상황에서 벗어나기 위해 이야기를 해 본 적이 있나요? 무슨 일이 있었는지 적어 보세요.",
      "요약에 나온 지니, 악마, 빛나는 눈을 가진 괴물 같은 환상적인 요소들 중 가장 흥미로운 것은 무엇인가요? 이유를 적어 보세요."] };
ACT["S5357"] = { s: "At the beginning of eighth grade, learning disabled Max and his new friend Freak, whose birth defect has affected his body but not his mind, find that when they combine forces they make a powerful team.",
  q: ["Max, who has a learning disability, and Freak, whose birth defect has affected his body but not his mind, combine forces to make a powerful team. What strengths do you think each of them brings to the team?",
      "Have you ever teamed up with someone whose strengths were different from yours? Describe what you accomplished together.",
      "Why do you think combining different strengths, like Max and Freak do, can make a team more powerful than either person alone?"],
  h: ["학습장애가 있는 맥스와 몸에만 장애가 있고 마음은 그렇지 않은 프리크는 힘을 합쳐 강력한 한 팀이 돼요. 두 사람은 각각 어떤 장점을 팀에 가져다줄 것 같나요?",
      "나와 다른 장점을 가진 사람과 함께 힘을 합쳐 본 적이 있나요? 함께 무엇을 이루었는지 적어 보세요.",
      "맥스와 프리크처럼 서로 다른 강점을 합치는 것이 혼자일 때보다 팀을 더 강하게 만드는 이유는 무엇이라고 생각하나요?"] };
ACT["S5358"] = { s: "Aramis is on the most dangerous mission ever. He is to dethrone King Louis XIV of France and replace him with his twin brother Phillip who is locked in the infamous prison in the Bastille.",
  q: ["Aramis is on a dangerous mission to dethrone King Louis XIV and replace him with his twin brother Phillip. Why do you think this plan is described as the most dangerous mission ever?",
      "Have you ever helped plan something risky that required careful secrecy? Describe what you did.",
      "Why do you think keeping Phillip locked away in the Bastille would have been part of a larger plot?"],
  h: ["아라미스는 루이 14세를 폐위시키고 그의 쌍둥이 형제 필립으로 대신하려는 위험한 임무를 맡아요. 이 계획이 '가장 위험한 임무'로 불리는 이유는 무엇일까요?",
      "철저한 비밀이 필요한 위험한 일을 계획하는 데 도움을 준 적이 있나요? 무엇을 했는지 적어 보세요.",
      "필립을 바스티유 감옥에 가둬 둔 것이 더 큰 음모의 일부였을 것이라고 생각하는 이유는 무엇인가요?"] };
ACT["S5360"] = { s: "This abridged edition is a retelling of the fortunes of a shipwrecked family as they imaginatively adapt to life on an island with abundant animal and plant life.",
  q: ["This book retells the story of a shipwrecked family adapting to life on an island with abundant animal and plant life. What do you imagine they had to figure out first to survive?",
      "If you were stranded on an island like this family, what would you build or create first? Explain your choice.",
      "Why do you think the family had to be so imaginative to adapt to their new island life?"],
  h: ["이 책은 배가 난파된 가족이 동식물이 풍부한 섬에서 적응해 가는 이야기를 다시 들려줘요. 그들이 살아남기 위해 가장 먼저 알아내야 했던 것은 무엇이었을까요?",
      "이 가족처럼 무인도에 갇힌다면 가장 먼저 무엇을 만들거나 만들어 내고 싶나요? 이유를 설명해 보세요.",
      "이 가족이 새로운 섬 생활에 적응하기 위해 왜 그렇게 상상력이 필요했다고 생각하나요?"] };
ACT["S5361"] = { s: "Trying to make sense of the horrors of World War II, Death relates the story of Liesel, a young German girl whose book-stealing and story-telling talents help sustain her family and the Jewish man they are hiding",
  q: ["In this book, Death narrates the story of Liesel, whose book-stealing and storytelling talents help sustain her family and the Jewish man they are hiding. How do you think stories could help people survive difficult times?",
      "Have you ever used a story or book to comfort yourself or someone else during a hard time? Describe what happened.",
      "Why do you think the author chose to have Death narrate this story, instead of a person?"],
  h: ["이 책에서는 죽음이 화자가 되어, 책을 훔치고 이야기를 들려주는 리젤의 재능이 그녀의 가족과 그들이 숨겨 준 유대인 남자를 어떻게 버티게 해 주었는지 이야기해요. 이야기가 힘든 시기를 버티는 사람들을 어떻게 도울 수 있을 것 같나요?",
      "힘든 시기에 나 자신이나 다른 사람을 위로하려고 이야기나 책을 사용한 적이 있나요? 무슨 일이 있었는지 적어 보세요.",
      "작가가 이 이야기의 화자를 사람이 아닌 '죽음'으로 정한 이유는 무엇이라고 생각하나요?"] };
ACT["S5362"] = { s: "As Hillary works in the miniature village allegedly built by elves in Sara-Kate's backyard, she becomes more and more curious about Sara-Kate's real life inside her big, gloomy house with her mysterious, silent mother.",
  q: ["Hillary becomes curious about Sara-Kate's real life inside her big, gloomy house with her mysterious, silent mother. What do you think Hillary might discover about Sara-Kate's family?",
      "Have you ever been curious about a friend's home life that seemed different or mysterious to you? Describe what you wondered about.",
      "Why do you think Sara-Kate might have told others that elves built the miniature village in her backyard?"],
  h: ["힐러리는 사라케이트의 크고 음침한 집과 신비롭고 말없는 어머니 곁에서의 진짜 삶에 점점 호기심을 갖게 돼요. 힐러리는 사라케이트의 가족에 대해 무엇을 알게 될 것 같나요?",
      "친구의 가정생활이 나와 다르거나 신비롭게 느껴져 궁금했던 적이 있나요? 무엇이 궁금했는지 적어 보세요.",
      "사라케이트가 뒷마당의 작은 마을을 요정들이 만들었다고 다른 사람들에게 말한 이유는 무엇일까요?"] };
ACT["S5363"] = { s: "For generations, the Beaumont family has harbored a magical secret. They each possess a \"savvy\"--a special supernatural power that strikes when they turn thirteen. Grandpa Bomba moves mountains, her older brothers create hurricanes and spark electricity . . . and now it's the eve of Mibs's big day. As if waiting weren't hard enough, the family gets scary news two days before Mibs's birthday: Poppa has been in a terrible accident. Mibs develops the singular mission to get to the hospital and prov",
  q: ["In the Beaumont family, everyone gets a special magical power called a 'savvy' when they turn thirteen. If you were about to discover your own savvy like Mibs, what power do you imagine you might wish for?",
      "Have you ever felt a strong need to reach someone you cared about during an emergency, like Mibs wanting to get to the hospital? Describe how you felt.",
      "Why do you think Mibs feels such a strong mission to get to the hospital despite the challenges she faces?"],
  h: ["보몬트 가족은 열세 살이 되면 '새비'라는 특별한 마법 능력이 생겨요. 밉스처럼 내 새비를 곧 발견하게 된다면 어떤 능력을 갖고 싶을 것 같나요?",
      "밉스가 병원에 가려고 한 것처럼, 응급 상황에서 소중한 사람에게 꼭 가고 싶었던 적이 있나요? 그때 기분이 어땠는지 적어 보세요.",
      "여러 어려움에도 불구하고 밉스가 병원에 가야 한다는 강한 사명감을 느끼는 이유는 무엇이라고 생각하나요?"] };
ACT["S5364"] = { s: "From the wheel to the World Wide Web, the Cat in the Hat looks at inventors and inventions that have changed our lives.",
  q: ["From the wheel to the World Wide Web, this book looks at inventors and inventions that have changed our lives. Which invention mentioned do you think changed the world the most?",
      "What invention do you use every day that you think has changed your life? Describe how you use it.",
      "Why do you think learning about how inventions were created can inspire people to invent new things themselves?"],
  h: ["바퀴부터 월드와이드웹까지, 이 책은 우리 삶을 바꾼 발명가와 발명품들을 살펴봐요. 언급된 발명품 중 세상을 가장 많이 바꾼 것은 무엇이라고 생각하나요?",
      "내 삶을 바꾸었다고 생각하는, 매일 사용하는 발명품이 있나요? 어떻게 사용하는지 적어 보세요.",
      "발명품이 만들어진 과정을 배우는 것이 사람들에게 새로운 것을 발명하도록 영감을 주는 이유는 무엇이라고 생각하나요?"] };
ACT["S5367"] = { s: "Artemis's mother has contracted a deadly disease--and the only cure lies in the brain fluid of African lemurs. Unfortunately, Artemis himself was responsible for making the lemurs extinct five years ago. Now he must enlist the aid of his fairy friends to travel back in time and save the lemur. Not only that, but he must face his deadliest foe yet: his younger self.",
  q: ["Artemis must travel back in time to save the very lemur species that he made extinct five years ago. Why do you think this creates such a difficult problem for him to solve?",
      "Have you ever had to fix a mistake you made in the past? Describe what you did to make things right.",
      "Why do you think facing his younger self is described as Artemis's deadliest foe yet?"],
  h: ["아르테미스는 오 년 전 자신이 멸종시킨 여우원숭이 종을 구하기 위해 시간을 거슬러 가야 해요. 이것이 왜 그렇게 어려운 문제가 될 것 같나요?",
      "과거에 저지른 실수를 바로잡아야 했던 적이 있나요? 무엇을 했는지 적어 보세요.",
      "자신의 어린 시절 모습과 맞서는 것이 아르테미스에게 가장 치명적인 적이라고 표현되는 이유는 무엇이라고 생각하나요?"] };
ACT["S5369"] = { s: "Trainee ghost hunter Tom must catch the Deadly Messenger, one of the hardest ghosts to catch, as part of his final exam. However, his hunt leads him to stumble into the lair of a sludge-covered Minotaur demon who is gathering a ghost army and plotting world domination. Tom faces a high-stakes, must-not-fail test where the fate of the world is on the line.",
  q: ["Tom must catch the Deadly Messenger as part of his final exam, but he stumbles into a Minotaur demon's lair instead. Why do you think this makes his test even more high-stakes than expected?",
      "Have you ever taken an important test or challenge where you felt a lot of pressure to succeed? Describe how you felt.",
      "Why do you think the fate of the world being on the line makes this story more exciting to read?"],
  h: ["톰은 기말 시험의 일부로 '치명적인 메신저'를 잡아야 하는데, 대신 미노타우로스 악마의 소굴에 빠지게 돼요. 이 일이 왜 시험을 더욱 위험하게 만들까요?",
      "성공해야 한다는 부담을 크게 느꼈던 중요한 시험이나 도전이 있었나요? 그때 기분이 어땠는지 적어 보세요.",
      "세상의 운명이 걸려 있다는 설정이 이 이야기를 더 흥미롭게 만드는 이유는 무엇이라고 생각하나요?"] };
ACT["S5370"] = { s: "This is a collection of imaginative origin stories explaining how various animals and features of the world came to be. Through fantastical tales, it answers questions like how the leopard got its spots, how the camel got its hump, and how the whale got its tiny throat.",
  q: ["This book has imaginative stories explaining how the leopard got its spots, how the camel got its hump, and how the whale got its tiny throat. Which of these origin stories are you most curious to read?",
      "Have you ever wondered why an animal looks or acts the way it does, and made up your own explanation? Describe your idea.",
      "Why do you think people long ago told imaginative stories like these to explain the natural world?"],
  h: ["이 책에는 표범이 어떻게 점무늬를 갖게 되었는지, 낙타가 어떻게 혹을 갖게 되었는지, 고래가 어떻게 작은 목구멍을 갖게 되었는지를 설명하는 이야기들이 있어요. 이 중 어떤 이야기가 가장 궁금한가요?",
      "어떤 동물이 왜 그런 모습이나 행동을 하는지 궁금해서 나만의 설명을 지어낸 적이 있나요? 내 생각을 적어 보세요.",
      "옛날 사람들이 왜 이런 상상력 넘치는 이야기로 자연 세계를 설명하려 했다고 생각하나요?"] };
ACT["S5371"] = { s: "Twain's masterpiece. Its background is the Mississippi, and there is a marvellous picture of the great river as Huck on his raft drifts down it to adventure.",
  q: ["This book gives a marvellous picture of the Mississippi River as Huck drifts down it on his raft to adventure. What do you imagine Huck might see and experience along the river?",
      "Have you ever traveled along a river, lake, or the ocean? Describe what you saw and how it felt.",
      "Why do you think traveling by raft down a big river would lead to so many different adventures?"],
  h: ["이 책은 허크가 뗏목을 타고 미시시피 강을 따라 내려가며 모험을 하는 멋진 모습을 그려요. 허크는 강을 따라가며 무엇을 보고 겪을 것 같나요?",
      "강이나 호수, 바다를 따라 여행해 본 적이 있나요? 무엇을 보았고 기분이 어땠는지 적어 보세요.",
      "뗏목을 타고 큰 강을 따라가는 것이 왜 그렇게 다양한 모험으로 이어질 것 같나요?"] };
ACT["S5372"] = { s: "Ramon Salazar, a young pearl diver in Baja California, finds the magnificent, yet feared, Black Pearl of the Sea of Cortez. His pride in the pearl brings him into a bitter rivalry with a skilled diver, triggering a series of tragic events. When a giant, legendary Manta Diablo attacks, Ramon must face the powerful forces of nature and superstition to protect his life and honor.",
  q: ["Ramon's pride in finding the Black Pearl brings him into a bitter rivalry and leads to an attack by the legendary Manta Diablo. Why do you think finding something valuable can cause both pride and danger?",
      "Have you ever felt proud of something you found or achieved, only to have it cause problems with someone else? Describe what happened.",
      "Why do you think Ramon has to face both the forces of nature and superstition to protect his life and honor?"],
  h: ["라몬은 검은 진주를 찾은 것에 자부심을 느끼다가 심한 경쟁과 전설의 만타 디아블로의 공격을 겪게 돼요. 귀한 것을 발견하는 일이 왜 자부심과 위험을 동시에 가져올 수 있다고 생각하나요?",
      "무언가를 찾거나 이루어 자랑스러웠는데, 그것 때문에 다른 사람과 문제가 생긴 적이 있나요? 무슨 일이 있었는지 적어 보세요.",
      "라몬이 자신의 목숨과 명예를 지키기 위해 자연의 힘과 미신 둘 다를 맞서야 하는 이유는 무엇이라고 생각하나요?"] };
ACT["S5373"] = { s: "Despite his overwhelming fear of interacting with people, Christopher, a mathematically gifted, autistic fifteen-year-old boy, decides to investigate the murder of a neighbor's dog and uncovers secret information about his mother.",
  q: ["Despite his overwhelming fear of interacting with people, Christopher decides to investigate the murder of his neighbor's dog. Why do you think he chooses to do something so difficult for him?",
      "Have you ever done something that scared you because you felt it was important? Describe what happened.",
      "Why do you think investigating the dog's murder leads Christopher to uncover secret information about his mother?"],
  h: ["사람과 어울리는 것을 몹시 두려워하면서도 크리스토퍼는 이웃집 개의 죽음을 조사하기로 해요. 그가 왜 이렇게 자신에게 어려운 일을 하기로 했을까요?",
      "무섭지만 중요하다고 느껴서 한 일이 있나요? 무슨 일이 있었는지 적어 보세요.",
      "개의 죽음을 조사하는 것이 크리스토퍼가 엄마에 대한 비밀을 알게 되는 것으로 이어지는 이유는 무엇이라고 생각하나요?"] };
ACT["S5374"] = { s: "A crippled boy in fourteenth-century England proves his courage and earns recognition from the king.",
  q: ["A crippled boy in fourteenth-century England proves his courage and earns recognition from the king. What kind of courage do you imagine he had to show?",
      "Have you ever had to prove yourself even though people doubted you because of a challenge you faced? Describe what happened.",
      "Why do you think earning recognition from the king would have been especially meaningful for a boy who was crippled?"],
  h: ["14세기 영국의 다리가 불편한 소년이 용기를 증명해 왕의 인정을 받아요. 그는 어떤 용기를 보여 주었을 것 같나요?",
      "어려움 때문에 사람들이 나를 의심했는데도 스스로를 증명해야 했던 적이 있나요? 무슨 일이 있었는지 적어 보세요.",
      "다리가 불편한 소년에게 왕의 인정을 받는 것이 특히 더 의미 있었을 이유는 무엇이라고 생각하나요?"] };
ACT["S5375"] = { s: "More men lost their lives during the battles of the Civil War than in any other war involving the United States. No one suspected that it would last four long years. At the beginning of the war, the battles were fought in southern territory. Each conflict brought more death and despair. In the end, the South surrendered, but everyone actually lost. Together, everyone faced the tremendous challenge of forgiving each other and rebuilding the nation.",
  q: ["This book says that everyone actually lost the Civil War, even though the South surrendered. Why do you think the author describes it this way?",
      "Have you ever had a disagreement with someone that took a long time to resolve and left both sides hurt? Describe what happened.",
      "Why do you think forgiving each other was such a tremendous challenge after the Civil War ended?"],
  h: ["이 책은 남부가 항복했지만 결국 모두가 진 것이라고 말해요. 작가가 왜 이렇게 표현했다고 생각하나요?",
      "누군가와 다툼이 오래 걸려 해결되었고 양쪽 다 상처를 입었던 적이 있나요? 무슨 일이 있었는지 적어 보세요.",
      "남북전쟁이 끝난 뒤 서로 용서하는 것이 왜 그렇게 큰 도전이었다고 생각하나요?"] };
ACT["S5376"] = { s: "This book provides a brief overview of the events leading up to the secession of states from the Union and the beginning of the Civil War.",
  q: ["This book gives a brief overview of the events that led up to the secession of states from the Union. What kinds of events do you imagine might lead a group of states to want to leave the country?",
      "Have you ever seen a disagreement grow bigger and bigger until it caused a big split, like a group breaking apart? Describe what happened.",
      "Why do you think it is important to understand the events leading up to a war, not just the war itself?"],
  h: ["이 책은 주들이 연방을 탈퇴하게 된 사건들을 간단히 살펴봐요. 어떤 사건들이 주들을 나라에서 떠나고 싶게 만들었을 것 같나요?",
      "다툼이 점점 커져서 결국 큰 분열로 이어지는 것을 본 적이 있나요? 무슨 일이 있었는지 적어 보세요.",
      "전쟁 자체뿐 아니라 전쟁으로 이어진 사건들을 이해하는 것이 왜 중요하다고 생각하나요?"] };
ACT["S5377"] = { s: "Who were the Civil War leaders, how did they attain their positions, and why did they fight? As the details of their lives unfold, these men become more than just names from history.",
  q: ["This book explains how the Civil War leaders attained their positions and why they fought. Why do you think learning these details makes them 'more than just names from history'?",
      "Have you ever learned more about a leader you only knew by name, like a president or historical figure? Describe what you learned.",
      "Why do you think it is important to understand a leader's reasons for fighting, not just what they did?"],
  h: ["이 책은 남북전쟁 지도자들이 어떻게 그 자리에 오르게 되었고 왜 싸웠는지 설명해요. 이런 자세한 내용을 아는 것이 왜 그들을 '역사 속 이름 이상의 존재'로 만든다고 생각하나요?",
      "대통령이나 역사 속 인물처럼 이름만 알던 지도자에 대해 더 자세히 알게 된 적이 있나요? 무엇을 알게 되었는지 적어 보세요.",
      "지도자가 무엇을 했는지뿐 아니라 왜 싸웠는지 이해하는 것이 왜 중요하다고 생각하나요?"] };
ACT["S5378"] = { s: "As Great Britain taxed the colonists without representation, the colonists became angry. Groups of men in the colonies began writing to each other about this unfair treatment. These spirited men became the first congress and led the colonies to declare their independence.",
  q: ["The colonists became angry because Great Britain taxed them without representation. Why do you think this made the colonists feel so unfairly treated?",
      "Have you ever felt like a rule was unfair because you had no say in making it? Describe what happened.",
      "Why do you think writing letters to each other helped these 'spirited men' become powerful enough to lead the colonies to declare independence?"],
  h: ["영국이 대표권 없이 식민지 사람들에게 세금을 매기자 그들은 분노했어요. 이것이 왜 그렇게 부당하게 느껴졌을 것 같나요?",
      "내가 만드는 데 전혀 참여하지 못한 규칙이 불공평하다고 느낀 적이 있나요? 무슨 일이 있었는지 적어 보세요.",
      "서로 편지를 주고받은 것이 이 '열정적인 사람들'이 식민지를 독립선언으로 이끌 만큼 힘을 갖게 된 데 어떻게 도움이 되었을까요?"] };
ACT["S5379"] = { s: "After problems developed with the Articles of Confederation, America's leaders wrote the U.S. Constitution. Although our founding fathers were happy with their work on the Constitution, it was missing an important part. The Bill of Rights was soon added to protect individual American rights.",
  q: ["The founding fathers were happy with the Constitution, but it was missing an important part. Why do you think the Bill of Rights needed to be added to protect individual rights?",
      "Have you ever made a plan or rule that seemed complete at first, but then you realized something important was missing? Describe what happened.",
      "Why do you think protecting individual rights is such an important part of a country's laws?"],
  h: ["건국의 아버지들은 헌법에 만족했지만 중요한 부분이 빠져 있었어요. 권리장전이 왜 개인의 권리를 지키기 위해 꼭 필요했다고 생각하나요?",
      "처음에는 완벽해 보였던 계획이나 규칙에서 중요한 무언가가 빠졌다는 것을 나중에 깨달은 적이 있나요? 무슨 일이 있었는지 적어 보세요.",
      "개인의 권리를 지키는 것이 한 나라의 법에서 왜 그렇게 중요한 부분이라고 생각하나요?"] };
ACT["S5380"] = { s: "This fun and interesting, interactive series will enthrall young readers by making them a part of the story. Readers will become the main character and can revel in the gory, dark, horrific side of life throughout important moments in history. Humorous \"Handy Hints\" that relate directly to the text are provided on each spread. You (the reader) are an English gentleman eager to join a group of settlers planning to start a new colony in the New World. You have heard the tales of previous expeditio",
  q: ["This book's title warns readers to avoid being in Alexander the Great's army. Based on the title, what kinds of dangers do you imagine soldiers in his army might have faced?",
      "Have you ever done something difficult or risky that required you to be brave, like joining an army might require? Describe what you did.",
      "Why do you think books like this one use a funny, 'avoid being' style to teach readers about dangerous jobs from history?"],
  h: ["이 책의 제목은 독자에게 알렉산더 대왕의 군대에 있지 말라고 경고해요. 제목을 보면 그의 군대 병사들이 어떤 위험을 겪었을 것 같나요?",
      "군대에 들어가는 것처럼 용기가 필요한 어렵거나 위험한 일을 해 본 적이 있나요? 무엇을 했는지 적어 보세요.",
      "이 책처럼 '되지 마라' 식의 재미있는 방식으로 역사 속 위험한 일을 가르치는 이유는 무엇이라고 생각하나요?"] };
ACT["S5381"] = { s: "You (the reader) are a small boy living near Athens during the mid-5th century B.C. Your father sends you off to school to learn about the arts and athletics. It is his hope that someday you will honor the family by competing in the Olympic Games. As you train and compete in the games you will get an insider's look at what events are held, such as the pentathlon, running, and wrestling. After reading this book there will be no doubt in your mind that this is definitely a race you'd rather not ru",
  q: ["As the reader, you train and compete in events like the pentathlon, running, and wrestling for the ancient Greek Olympics. Which of these events do you think would be hardest to train for?",
      "Have you ever trained hard for a sport or competition your family hoped you would do well in? Describe your experience.",
      "Why do you think the book says this is 'definitely a race you'd rather not run'? What might make the ancient Olympics so difficult?"],
  h: ["독자인 나는 고대 그리스 올림픽을 위해 5종 경기, 달리기, 레슬링 같은 종목을 훈련하고 겨뤄요. 이 중 어떤 종목이 훈련하기 가장 힘들 것 같나요?",
      "가족이 잘하기를 바라는 운동이나 대회를 위해 열심히 훈련한 적이 있나요? 그 경험을 적어 보세요.",
      "이 책이 왜 '결코 뛰고 싶지 않은 경주'라고 말한다고 생각하나요? 고대 올림픽의 어떤 점이 그렇게 힘들었을 것 같나요?"] };
ACT["S5382"] = { s: "This series meets National Curriculum Standards for: Science: History and Nature of Science Social Studies: Time, Continuity, & Change",
  q: ["Based on the title, what do you think might have gone wrong on the Apollo 13 mission that this book warns you to avoid?",
      "Have you ever been part of a plan that suddenly did not go the way everyone expected? Describe what happened.",
      "Why do you think missions to space, like Apollo 13, are described as dangerous even with careful planning?"],
  h: ["제목을 보면, 이 책이 피하라고 경고하는 아폴로 13호 임무에서 무슨 일이 잘못되었을 것 같나요?",
      "모두가 예상한 대로 흘러가지 않고 갑자기 틀어진 계획에 참여한 적이 있나요? 무슨 일이 있었는지 적어 보세요.",
      "아폴로 13호처럼 철저히 계획된 우주 임무도 왜 위험하다고 표현될까요?"] };
ACT["S5383"] = { s: "This book takes a humorous and gory look at the ancient Aztec tradition of sacrificing enemy warriors to the gods.",
  q: ["This book takes a humorous and gory look at the Aztec tradition of sacrificing enemy warriors to the gods. Why do you think the Aztecs believed this tradition was important?",
      "Have you ever learned about a tradition from long ago that seemed shocking or strange to you? Describe what it was.",
      "Why do you think the author chose to write about this difficult topic in a humorous way?"],
  h: ["이 책은 적군 전사를 신에게 제물로 바치던 아즈텍 전통을 유머러스하면서도 섬뜩하게 다뤄요. 아즈텍인들은 왜 이 전통을 중요하게 여겼을까요?",
      "충격적이거나 이상하게 느껴진 옛날 전통을 배운 적이 있나요? 무엇이었는지 적어 보세요.",
      "작가가 이렇게 어려운 주제를 유머러스하게 다룬 이유는 무엇이라고 생각하나요?"] };
ACT["S5384"] = { s: "Using brief text, labeled illustrations, and humorous cartoons, this book depicts life and events as they might have been during the Boston Tea Party, which helped to spawn the American Revolution.",
  q: ["This book depicts the events of the Boston Tea Party, which helped spawn the American Revolution. Why do you think this event was powerful enough to help start a revolution?",
      "Have you ever been part of a protest or a group standing up for something they believed was unfair? Describe what happened.",
      "Why do you think the author uses humorous cartoons to depict such a serious historical event?"],
  h: ["이 책은 미국 혁명이 시작되는 데 도움을 준 보스턴 차 사건의 사건들을 보여줘요. 이 사건이 혁명을 일으킬 만큼 강력했던 이유는 무엇일까요?",
      "부당하다고 생각하는 것에 맞서는 시위나 모임에 참여해 본 적이 있나요? 무슨 일이 있었는지 적어 보세요.",
      "작가가 이렇게 심각한 역사적 사건을 유머러스한 만화로 그린 이유는 무엇이라고 생각하나요?"] };
ACT["S5385"] = { s: "Humorous \"Handy Hints\" that relate directly to the text are provided on each spread. - High interest topic for children of all ages. - Includes Table of Contents, glossary, and index. - Draws in even the most reluctant reader with a lightheaded tone and hilarious illustrations. - The cultures and traditions of ancient civilizations spring to life in the pages of this series. - Perfect for struggling readers. Grades K-4 Social Studies Standards II. Time, Continuity, and Change - Accounts of past",
  q: ["Based on the title, why do you think this book warns readers to avoid being Cleopatra?",
      "Have you ever wished you could be a powerful or famous person from history, only to realize their life might have also been hard? Describe your thinking.",
      "Why do you think this series draws in even reluctant readers with humor and hints, according to the summary?"],
  h: ["제목을 보면, 이 책이 왜 클레오파트라가 되지 말라고 경고한다고 생각하나요?",
      "역사 속 힘 있고 유명한 인물이 되고 싶었지만, 그들의 삶도 힘들었을 수 있다고 깨달은 적이 있나요? 내 생각을 적어 보세요.",
      "요약을 보면 이 시리즈가 읽기 싫어하는 독자까지 유머로 끌어들인다고 하는데, 그 이유는 무엇이라고 생각하나요?"] };
ACT["S5386"] = { s: "Colorful illustrations help describe what life would be like as a convict sentenced to serve time in a penal colony in Australia during the eighteenth century.",
  q: ["This book describes life as a convict sentenced to a penal colony in Australia during the eighteenth century. What kind of hardships do you imagine a convict might have faced there?",
      "Have you ever had to go somewhere far from home that you did not want to go? Describe how you felt.",
      "Why do you think being sent to a penal colony far away was considered such a harsh punishment?"],
  h: ["이 책은 18세기 오스트레일리아 유형지로 보내진 죄수의 삶을 설명해요. 그곳에서 죄수는 어떤 고난을 겪었을 것 같나요?",
      "가고 싶지 않은데 집에서 멀리 떠나야 했던 적이 있나요? 그때 기분이 어땠는지 적어 보세요.",
      "머나먼 유형지로 보내지는 것이 왜 그렇게 가혹한 벌로 여겨졌다고 생각하나요?"] };
ACT["S5387"] = { s: "You (the reader) are an Egyptian peasant who farms for your wealthy landlord. During the wet season you are ordered to help build the pharaoh's tomb. As a pyramid builder you will get an insider's look at what it took to build these massive monuments, such as excavating stone blocks, hauling stones to the site and setting them, masonry work, painting, and sculpting. After reading this book there will be no doubt in your mind that this is definitely a hazardous job you'd rather not have.",
  q: ["As the reader, you are ordered to help build the pharaoh's tomb, from excavating stone blocks to painting and sculpting. Which part of this work do you think would be the most hazardous?",
      "Have you ever had to do a hard physical job or chore that took a lot of effort? Describe what you did.",
      "Why do you think the book concludes that being a pyramid builder is 'definitely a hazardous job you'd rather not have'?"],
  h: ["독자인 나는 돌덩이를 캐는 일부터 그림 그리고 조각하는 일까지, 파라오의 무덤을 짓는 일을 명령받아요. 이 중 어떤 일이 가장 위험할 것 같나요?",
      "많은 힘이 드는 육체노동이나 집안일을 해 본 적이 있나요? 무엇을 했는지 적어 보세요.",
      "이 책이 피라미드를 짓는 일을 '결코 하고 싶지 않은 위험한 일'이라고 결론짓는 이유는 무엇이라고 생각하나요?"] };
ACT["S5388"] = { s: "People are evacuating to the countryside, fleeing the war in 1939. However, war grants no rest. How can they overcome hardships like bombs and food shortages?",
  q: ["People evacuate to the countryside to flee the war, but the book says 'war grants no rest.' Why do you think even the countryside wasn't completely safe?",
      "Have you ever had to leave home suddenly because of an emergency? Describe what that was like.",
      "Why do you think facing hardships like bombs and food shortages would be especially hard for a child evacuee?"],
  h: ["사람들은 전쟁을 피해 시골로 피난 가지만, 이 책은 '전쟁은 쉼을 허락하지 않는다'고 말해요. 시골도 완전히 안전하지 않았던 이유는 무엇일까요?",
      "긴급한 일 때문에 갑자기 집을 떠나야 했던 적이 있나요? 그때 어땠는지 적어 보세요.",
      "폭탄과 식량 부족 같은 고난이 피난 간 아이에게 특히 더 힘든 이유는 무엇이라고 생각하나요?"] };
ACT["S5389"] = { s: "This book describes the experiences of European knights fighting in the Crusades, covering the reasons men became Crusaders, how they prepared to leave home, what kind of armor and weapons they used, and what the Turks were fighting for.",
  q: ["This book describes the reasons men became Crusaders and how they prepared to leave home. What do you think would be the hardest part of preparing to leave home for a long war?",
      "Have you ever had to prepare for something that would take you far away from home for a long time? Describe how you prepared.",
      "Why do you think it is important for this book to explain what the Turks were fighting for too, not just the Crusaders?"],
  h: ["이 책은 사람들이 십자군이 된 이유와 집을 떠나기 위해 어떻게 준비했는지 설명해요. 오랫동안 집에서 멀리 떠나기 위한 준비 중 가장 힘든 부분은 무엇일 것 같나요?",
      "오랫동안 집에서 멀리 떠나기 위해 준비해 본 적이 있나요? 어떻게 준비했는지 적어 보세요.",
      "이 책이 십자군뿐 아니라 튀르크인들이 무엇을 위해 싸웠는지도 설명하는 것이 왜 중요하다고 생각하나요?"] };
ACT["S5390"] = { s: "This book presents a humorous account of what it might have been like to sail with Sir Francis Drake on a voyage to find the Northwest Passage to the Spice Islands in 1577 and raid a few Spanish ships along the way.",
  q: ["This book gives a humorous account of sailing with Sir Francis Drake to find the Northwest Passage and raid Spanish ships. Which part of this voyage sounds most dangerous to you?",
      "Have you ever gone on a long trip or adventure with an uncertain destination? Describe what happened.",
      "Why do you think raiding ships along the way made this voyage even riskier than just searching for a new route?"],
  h: ["이 책은 프랜시스 드레이크 경과 함께 항해하며 스페인 배들을 습격한 이야기를 유머러스하게 들려줘요. 이 항해에서 어떤 부분이 가장 위험해 보이나요?",
      "목적지가 확실하지 않은 긴 여행이나 모험을 해 본 적이 있나요? 무슨 일이 있었는지 적어 보세요.",
      "가는 길에 배를 습격하는 것이 새로운 항로를 찾는 것보다 더 위험을 키운 이유는 무엇이라고 생각하나요?"] };
ACT["S5391"] = { s: "You are a poor peasant boy who works with your father to help support your family. You are living in the third century BC under the ruler Qin. He has declared himself the Emperor of China. Emperor Qin is not the most pleasant person. Qin expected total loyalty to the state and this is confusing to you because you know that you are supposed to be loyal to your family first. The Emperor has many unfair laws. Unfortunately, you break one of those laws and are given the punishment of hard labor. You",
  q: ["As the reader, you break one of Emperor Qin's unfair laws and are punished with hard labor. Why do you think the emperor's laws felt so confusing and unfair to you?",
      "Have you ever had to follow a rule that conflicted with what you believed was right, like being loyal to family versus a leader? Describe what happened.",
      "Why do you think Emperor Qin expected total loyalty to the state instead of to family?"],
  h: ["독자인 나는 진시황의 부당한 법을 어겨 강제 노동형을 받아요. 황제의 법이 왜 그렇게 혼란스럽고 부당하게 느껴졌을까요?",
      "황제 같은 지도자와 가족 중 누구에게 충성해야 하는지처럼, 옳다고 믿는 것과 충돌하는 규칙을 따라야 했던 적이 있나요? 무슨 일이 있었는지 적어 보세요.",
      "진시황이 가족이 아닌 국가에 대한 완전한 충성을 요구한 이유는 무엇이라고 생각하나요?"] };
ACT["S5392"] = { s: "This book takes a lighthearted look at what life may have been like for an Inca ruler, including mummification after death.",
  q: ["This book takes a lighthearted look at life for an Inca ruler, including what happened to their body after death. What do you imagine mummification might have involved?",
      "Have you ever learned about a tradition surrounding death from a different culture that surprised you? Describe what it was.",
      "Why do you think the Incas practiced mummification for their rulers?"],
  h: ["이 책은 잉카 지배자의 삶과 죽은 뒤의 미라화 과정을 가볍게 다뤄요. 미라화 과정은 어떤 것이었을 것 같나요?",
      "다른 문화의 죽음에 관한 전통을 배우고 놀란 적이 있나요? 그것이 무엇이었는지 적어 보세요.",
      "잉카인들이 지배자를 미라로 만든 이유는 무엇이라고 생각하나요?"] };
ACT["S5393"] = { s: "It is 1620, and you and your parents are about to emigrate from England and sail to the New World to avoid being persecuted for your religious beliefs. It will be a long and hazardous voyage, and not everyone will survive.",
  q: ["You and your parents are emigrating to the New World in 1620 to avoid being persecuted for your religious beliefs. Why do you think this made the difficult, hazardous voyage worth the risk to them?",
      "Have you ever had to leave something familiar behind to be somewhere safer? Describe what happened.",
      "Why do you think the book warns that 'not everyone will survive' this voyage?"],
  h: ["1620년, 나와 부모님은 종교적 박해를 피해 새로운 땅으로 이민을 떠나려 해요. 이것이 왜 위험한 항해를 무릅쓸 만큼 가치 있었다고 생각하나요?",
      "더 안전한 곳에 있기 위해 익숙한 것을 떠나야 했던 적이 있나요? 무슨 일이 있었는지 적어 보세요.",
      "이 책이 '모두가 살아남지는 못할 것'이라고 경고하는 이유는 무엇이라고 생각하나요?"] };
ACT["S5394"] = { s: "This revised edition combines humorous cartoons and facts to depict what life was like in medieval dungeons during the late fifteenth century, as seen through the eyes of the jailer.",
  q: ["This book shows what life in a medieval dungeon was like through the eyes of the jailer, not the prisoner. Why do you think seeing it from the jailer's perspective might be different from what you expect?",
      "Have you ever imagined what a job would be like from someone else's point of view? Describe what you imagined.",
      "Why do you think the author combines humorous cartoons with facts to teach about such a dark topic?"],
  h: ["이 책은 죄수가 아니라 간수의 눈으로 중세 지하 감옥의 삶을 보여줘요. 간수의 시점으로 보는 것이 내가 예상한 것과 왜 다를 것 같나요?",
      "다른 사람의 입장에서 어떤 일이 어떨지 상상해 본 적이 있나요? 무엇을 상상했는지 적어 보세요.",
      "작가가 이렇게 어두운 주제를 유머러스한 만화와 함께 다루는 이유는 무엇이라고 생각하나요?"] };
ACT["S5395"] = { s: "Being a knight in shining armor is not as glamorous as it looks. Follow the progress of a young English boy at the beginning of the fifteenth century as he goes through the rigorous training to become a knight and faces the dangers of sieges and jousts.",
  q: ["This book says being a knight is 'not as glamorous as it looks,' and follows a boy through rigorous training that leads to dangerous sieges and jousts. What part of knight training do you think would be hardest?",
      "Have you ever trained hard for something that turned out to be more difficult than you expected? Describe what happened.",
      "Why do you think people imagine knights as glamorous, even though the training and dangers were so harsh?"],
  h: ["이 책은 기사가 되는 것이 '보이는 것만큼 화려하지 않다'고 말하며, 힘든 훈련 끝에 위험한 공성전과 마상 창시합을 겪는 소년의 이야기를 따라가요. 기사 훈련 중 어떤 부분이 가장 힘들 것 같나요?",
      "예상보다 훨씬 힘들었던 일을 위해 열심히 훈련한 적이 있나요? 무슨 일이 있었는지 적어 보세요.",
      "훈련과 위험이 그렇게 가혹했는데도 사람들이 기사를 화려하다고 상상하는 이유는 무엇이라고 생각하나요?"] };
ACT["S5396"] = { s: "Using brief text, labeled illustrations, and humorous cartoons, this book depicts life and events one might experience as a Roman soldier.",
  q: ["This book depicts the life and events a person might experience as a Roman soldier. What kind of experiences do you imagine a Roman soldier had to go through?",
      "Have you ever imagined what it would be like to serve in an army from long ago? Describe your thoughts.",
      "Why do you think books like this use humorous cartoons to teach about the harsh life of a soldier?"],
  h: ["이 책은 로마 병사로서 겪을 만한 삶과 사건들을 보여줘요. 로마 병사는 어떤 경험을 했을 것 같나요?",
      "옛날 군대에서 복무한다면 어떨지 상상해 본 적이 있나요? 내 생각을 적어 보세요.",
      "이런 책들이 병사의 힘든 삶을 가르치기 위해 유머러스한 만화를 사용하는 이유는 무엇이라고 생각하나요?"] };
ACT["S5397"] = { s: "This fun and interesting, interactive series will enthrall young readers by making them a part of the story. Readers will become the main character and can revel in the gory, dark, horrific side of life throughout important moments in history. Humorous \"Handy Hints\" that relate directly to the text are provided on each spread. You (the reader) are an English gentleman eager to join a group of settlers planning to start a new colony in the New World. You have heard the tales of previous expeditio",
  q: ["This book's title warns readers to avoid being a Sumerian slave. Based on the title, what kinds of hardships do you imagine a slave in ancient Sumer might have faced?",
      "Have you ever had to do work you did not want to do, with little choice in the matter? Describe how that felt.",
      "Why do you think learning about the hard lives of slaves in ancient history is important, even though it can be a difficult topic?"],
  h: ["이 책의 제목은 독자에게 수메르 노예가 되지 말라고 경고해요. 제목을 보면 고대 수메르의 노예는 어떤 고난을 겪었을 것 같나요?",
      "선택의 여지 없이 하기 싫은 일을 해야 했던 적이 있나요? 그때 기분이 어땠는지 적어 보세요.",
      "어려운 주제이지만 역사 속 노예들의 힘든 삶을 배우는 것이 왜 중요하다고 생각하나요?"] };
ACT["S5398"] = { s: "This revised edition combines humorous cartoons and facts to depict what life was like on the maiden voyage of the \"Titanic.\"",
  q: ["This book depicts life on the maiden voyage of the Titanic using humorous cartoons and facts. What do you already know or imagine about what happened on that voyage?",
      "Have you ever been excited about a big trip or first-time event that did not go as planned? Describe what happened.",
      "Why do you think it is difficult to make a book about the Titanic's tragedy humorous, and how do you think the author manages it?"],
  h: ["이 책은 유머러스한 만화와 사실을 함께 사용해 타이타닉호의 첫 항해 당시의 삶을 보여줘요. 그 항해에서 무슨 일이 있었는지 이미 알고 있거나 상상되는 것이 있나요?",
      "큰 여행이나 처음 하는 일에 신났지만 계획대로 되지 않은 적이 있나요? 무슨 일이 있었는지 적어 보세요.",
      "타이타닉호의 비극을 유머러스하게 만드는 것이 왜 어려울 것 같나요? 작가는 그것을 어떻게 해냈을 것 같나요?"] };
ACT["S5399"] = { s: "This book presents a humorous account of what it might have been like to live in ancient Egypt in the time of Tutankhamen, providing an introduction to the royal family and discussing religion, childhood, entertainment, and mummification.",
  q: ["This book gives a humorous account of what it was like to live in ancient Egypt during the time of Tutankhamun, discussing his childhood, religion, entertainment, and mummification. Which of these topics are you most curious to read about?",
      "Have you ever wondered what it would be like to live as royalty, like a king or queen? Describe what you imagine that life would be like.",
      "Why do you think discussing mummification is an important part of understanding ancient Egyptian royal life?"],
  h: ["이 책은 투탕카멘 시대 고대 이집트의 삶을 유머러스하게 다루며 그의 어린 시절, 종교, 오락, 미라화 과정을 소개해요. 이 중 어떤 주제가 가장 궁금한가요?",
      "왕이나 여왕 같은 왕족으로 사는 것이 어떨지 상상해 본 적이 있나요? 그 삶이 어떨 것 같은지 적어 보세요.",
      "미라화 과정을 다루는 것이 고대 이집트 왕족의 삶을 이해하는 데 왜 중요한 부분이라고 생각하나요?"] };
