// 간이 학습 질문 — Book No. S54 묶음. 사람이 아니라 AI 가 한 번 쓰고 굳힌 파일이다.
window.ACT = window.ACT || {};
var ACT = window.ACT;
ACT["S5400"] = { s: "This volume covers world history from the Earliest Nomads to the Last Roman Emperor (around 5000 BC to 400 AD), introducing children to major ancient civilizations like Egypt, Babylon, Greece, China, and Rome through engaging, narrative stories.",
  q: ["Which ancient civilization in this book, such as Egypt, Babylon, Greece, China, or Rome, sounds most interesting to you? Explain why.",
      "Have you ever learned about ancient history in school or from another book? Write about it.",
      "If you could travel back in time to visit one ancient civilization from this book, which one would you choose? Explain your idea in a paragraph."],
  h: ["이 책에 나온 고대 문명(이집트, 바빌론, 그리스, 중국, 로마) 중에 가장 흥미로운 곳은 어디인가요? 이유도 함께 써 보세요.",
      "학교나 다른 책에서 고대 역사에 대해 배운 적이 있나요? 그 이야기를 적어 보세요.",
      "이 책에 나온 고대 문명 중 한 곳으로 시간여행을 갈 수 있다면 어디를 고를까요? 내 생각을 한 문단으로 적어 보세요."] };
ACT["S5401"] = { s: "This volume explores the time from the Fall of Rome to the Rise of the Renaissance (around 400 AD to 1600 AD). It details the development of Medieval Europe, the rise of Islam, the Crusades, the Vikings, the kingdoms of Asia and Africa, and the beginning of the European Renaissance.",
  q: ["Which topic in this book, such as knights, Vikings, the Crusades, or medieval kingdoms, sounds most interesting to you? Explain why.",
      "Have you ever read a story about knights or castles before? Write about it.",
      "If you lived during the Middle Ages, which topic in this book would you want to learn more about? Explain your idea in a paragraph."],
  h: ["이 책에 나온 주제(기사, 바이킹, 십자군, 중세 왕국) 중에 가장 흥미로운 것은 무엇인가요? 이유도 함께 써 보세요.",
      "기사나 성에 대한 이야기를 읽어 본 적이 있나요? 그 이야기를 적어 보세요.",
      "내가 중세 시대에 살았다면 이 책의 주제 중 무엇을 더 알고 싶을까요? 내 생각을 한 문단으로 적어 보세요."] };
ACT["S5402"] = { s: "This volume covers the era from the Renaissance to the Napoleonic Wars (around 1600 AD to 1850 AD). Key topics include the Age of Exploration, the Reformation, colonization of the Americas, the Scientific Revolution, the Enlightenment, the American Revolution, and the French Revolution.",
  q: ["Which event in this book, such as the Age of Exploration, the Scientific Revolution, or a revolution, sounds most exciting to you? Explain why.",
      "Have you ever heard of explorers sailing to new lands? Write about what you know.",
      "If you could ask a question to someone who lived through one event in this book, what would you ask? Explain your idea in a paragraph."],
  h: ["이 책에 나온 사건(대항해 시대, 과학 혁명, 여러 혁명) 중에 가장 흥미로운 것은 무엇인가요? 이유도 함께 써 보세요.",
      "새로운 땅을 향해 배를 탄 탐험가들에 대해 들어 본 적이 있나요? 아는 것을 적어 보세요.",
      "이 책에 나온 사건을 겪은 사람에게 질문을 할 수 있다면 무엇을 물어보고 싶나요? 내 생각을 한 문단으로 적어 보세요."] };
ACT["S5403"] = { s: "This final volume narrates events from the mid-1800s up to the late 20th/early 21st century. It covers the Victorian Era, the American Civil War, Japan's Meiji Restoration, the two World Wars, the Great Depression, the Cold War, and contemporary history.",
  q: ["Which period in this book, such as the World Wars, the Great Depression, or the Cold War, would you like to learn more about? Explain why.",
      "Have you ever heard your family talk about an event from modern history? Write about it.",
      "Why do you think it is important to learn about events like the ones in this book? Explain your idea in a paragraph."],
  h: ["이 책에 나온 시대(세계대전, 대공황, 냉전) 중에 무엇을 더 알고 싶나요? 이유도 함께 써 보세요.",
      "가족이 현대 역사의 어떤 사건에 대해 이야기하는 것을 들어 본 적이 있나요? 그 이야기를 적어 보세요.",
      "이 책에 나온 것 같은 사건들을 배우는 것이 왜 중요할까요? 내 생각을 한 문단으로 적어 보세요."] };
ACT["S5404"] = { s: "Five children find a mysterious, blank, red magic book at their library that grants wishes. They only have seven days to keep it. As they wish for dragons, trips to the Wild West, and other fantasy adventures, they must learn to control the book's chaotic magic before their week with it ends.",
  q: ["What kinds of wishes do the five children make with the magic book in this story?",
      "If you found a library book that could grant wishes for seven days, what would you wish for first?",
      "Why do you think the children need to learn to control the book's chaotic magic? Write your own idea in a paragraph."],
  h: ["이 이야기에서 다섯 아이들은 마법 책으로 어떤 소원들을 비나요?",
      "일주일 동안 소원을 들어주는 도서관 책을 발견한다면 가장 먼저 무슨 소원을 빌고 싶나요?",
      "아이들이 왜 그 책의 통제하기 어려운 마법을 다스리는 법을 배워야 할까요? 내 생각을 한 문단으로 적어 보세요."] };
ACT["S5405"] = { s: "The colonies were the birthplace of the United States and they were made up of people that came from various backgrounds seeking religious freedom, wealth, and success. Daily life for the colonists was different depending on the region in which they lived, yet they established a united nation built on freedom and the pursuit of happiness.",
  q: ["Why did people come to the colonies, according to this book?",
      "Have you ever moved to a new place, or heard a story about someone starting a new life somewhere? Write about it.",
      "What do you think was hardest about starting a new life in the colonies? Explain your idea in a paragraph."],
  h: ["이 책에 따르면 사람들은 왜 식민지로 왔나요?",
      "새로운 곳으로 이사를 하거나, 누군가 새로운 삶을 시작하는 이야기를 들어 본 적이 있나요? 적어 보세요.",
      "식민지에서 새로운 삶을 시작하는 것 중 가장 힘들었을 점은 무엇일까요? 내 생각을 한 문단으로 적어 보세요."] };
ACT["S5406"] = { s: "Slavery was a complicated issue that divided the country to the point of war. Even after the war, slavery was not totally resolved. Freedom came because of the foresight of many people like Abraham Lincoln, the Quakers, and the abolitionists who believed that people were all created equal.",
  q: ["What did the Quakers and abolitionists in this book believe about people?",
      "Have you ever learned about people who fought for fairness before? Write about what you remember.",
      "Why do you think it took the courage of many people, as this book describes, to bring freedom? Explain your idea in a paragraph."],
  h: ["이 책에 나온 퀘이커교도와 노예제 폐지론자들은 사람에 대해 무엇을 믿었나요?",
      "공정함을 위해 싸운 사람들에 대해 배운 적이 있나요? 기억나는 것을 적어 보세요.",
      "이 책이 말하듯 자유를 가져오는 데 왜 많은 사람의 용기가 필요했을까요? 내 생각을 한 문단으로 적어 보세요."] };
ACT["S5407"] = { s: "The American Revolution was the colonists' fight for freedom in the New World. It involved the help of spies, women, and people from other countries. The colonists fought against a giant, and they won their freedom from Great Britain against all odds. After winning the impossible, the colonists had a new battle to fight: setting up a new government and nation.",
  q: ["Who are some of the people who helped the colonists in the American Revolution, according to this book?",
      "Have you ever worked with a team to accomplish something difficult? Write about it.",
      "Why do you think setting up a new government was called a new battle after winning the war? Explain your idea in a paragraph."],
  h: ["이 책에 따르면 미국 독립혁명에서 식민지 사람들을 도운 사람들은 누구인가요?",
      "어려운 일을 이루기 위해 여러 사람과 함께 일해 본 적이 있나요? 그 이야기를 적어 보세요.",
      "전쟁에서 이긴 뒤 새로운 정부를 세우는 일이 왜 새로운 싸움이라고 불렸을까요? 내 생각을 한 문단으로 적어 보세요."] };
ACT["S5408"] = { s: "This fun and interesting, interactive series will enthrall young readers by making them a part of the story. Readers will become the main character and can revel in the gory, dark, horrific side of life throughout important moments in history. Humorous \"Handy Hints\" that relate directly to the text are provided on each spread. You (the reader) are an English gentleman eager to join a group of settlers planning to start a new colony in the New World. You have heard the tales of previous expeditio",
  q: ["This book turns you into the main character living through a dangerous time in history. Based on the title, what job do you think you would have?",
      "Have you ever visited a palace or a place that felt like a whole different world? Write about it.",
      "What do you think would be the most difficult part of working in the Forbidden City? Explain your idea in a paragraph."],
  h: ["이 책은 읽는 사람을 역사 속 위험한 시대를 사는 주인공으로 만들어 줍니다. 제목을 보면 어떤 일을 하게 될 것 같나요?",
      "궁전이나 완전히 다른 세상처럼 느껴지는 곳에 가 본 적이 있나요? 그 이야기를 적어 보세요.",
      "자금성(紫禁城)에서 일하는 것 중 가장 힘들 것 같은 점은 무엇인가요? 내 생각을 한 문단으로 적어 보세요."] };
ACT["S5409"] = { s: "Cartoons and facts combine to explain what it was like to be a farmer during the Irish Potato Famine and to travel across the Atlantic Ocean onboard a ship to America.",
  q: ["What was it like to travel across the Atlantic during the Irish Potato Famine, according to this book?",
      "Have you ever heard of people leaving their home country to find a better life? Write about what you know.",
      "Why do you think the journey across the ocean during the famine was so difficult? Explain your idea in a paragraph."],
  h: ["이 책에 따르면 아일랜드 감자 대기근 시기에 대서양을 건너는 것은 어땠나요?",
      "사람들이 더 나은 삶을 찾아 고향을 떠났다는 이야기를 들어 본 적이 있나요? 아는 것을 적어 보세요.",
      "대기근 시기의 바다 여행이 왜 그렇게 힘들었을까요? 내 생각을 한 문단으로 적어 보세요."] };
ACT["S5410"] = { s: "This book is a humorous and educational exploration of the cultural trials and tribulations experienced in the sixteenth century during Mary, Queen of Scotland's, rule.",
  q: ["What kind of trials and tribulations does this book describe about Mary, Queen of Scots' rule?",
      "Have you ever read a funny book about a serious topic before? Write about it.",
      "Why do you think the author chose to make a difficult time in history funny? Explain your idea in a paragraph."],
  h: ["이 책은 메리 여왕의 통치에 대해 어떤 시련과 고난을 설명하나요?",
      "심각한 주제를 다룬 재미있는 책을 읽어 본 적이 있나요? 그 이야기를 적어 보세요.",
      "작가가 왜 역사 속 힘든 시기를 재미있게 표현했을까요? 내 생각을 한 문단으로 적어 보세요."] };
ACT["S5411"] = { s: "The simple text and illustrations in this book teach young readers about Ernest Shackleton's expedition to Antarctica in 1912.",
  q: ["What does this book teach you about Ernest Shackleton's expedition to Antarctica?",
      "Have you ever read about explorers who traveled to a very cold or dangerous place? Write about it.",
      "Why do you think people like Shackleton wanted to explore such a dangerous place? Explain your idea in a paragraph."],
  h: ["이 책은 어니스트 섀클턴의 남극 탐험에 대해 무엇을 알려주나요?",
      "아주 춥거나 위험한 곳을 탐험한 사람들에 대해 읽어 본 적이 있나요? 그 이야기를 적어 보세요.",
      "섀클턴 같은 사람들은 왜 그렇게 위험한 곳을 탐험하고 싶어 했을까요? 내 생각을 한 문단으로 적어 보세요."] };
ACT["S5412"] = { s: "Using brief text, labeled illustrations, and humorous cartoons, this book depicts life and events during the four years of the Civil War.",
  q: ["What does this book show about a soldier's life during the four years of the Civil War?",
      "Have you ever learned about the Civil War in school? Write about what you remember.",
      "Why do you think the author used humorous cartoons to explain such a serious war? Explain your idea in a paragraph."],
  h: ["이 책은 남북전쟁 4년 동안 군인의 삶에 대해 무엇을 보여주나요?",
      "학교에서 남북전쟁에 대해 배운 적이 있나요? 기억나는 것을 적어 보세요.",
      "작가는 왜 그렇게 심각한 전쟁을 재미있는 만화로 설명했을까요? 내 생각을 한 문단으로 적어 보세요."] };
ACT["S5413"] = { s: "This book explains what it was like to be a cabin boy on a whaling ship in 1819, discussing the realities of life aboard ship, the catching and processing of the whale, being shipwrecked, and coming home again.",
  q: ["What jobs and dangers does a cabin boy face on the whaling ship in this book?",
      "Have you ever read about a job that seemed exciting but also dangerous? Write about it.",
      "Would you want to be a cabin boy on a whaling ship in 1819? Explain your reasons in a paragraph."],
  h: ["이 책에서 선실 소년은 고래잡이 배에서 어떤 일과 위험을 마주하나요?",
      "신나 보이지만 위험하기도 한 일에 대해 읽어 본 적이 있나요? 그 이야기를 적어 보세요.",
      "1819년 고래잡이 배의 선실 소년이 되고 싶나요? 이유와 함께 한 문단으로 적어 보세요."] };
ACT["S5414"] = { s: "Do you think being a Roman galdiator seems glamorous? Does exploring the wild frontier as an American pioneer sound exciting? Think again! As you'll discover in this lively series, history definitely has a dark side. These revised titles include helpful new features-along with the same hilarious illustrations, captions, and sidebars that have made this series a hit with kids everywhere! You've heard that there are fortunes to be made out West. But are you tough enough to survive months on the tr",
  q: ["What does this book say you need to survive months on the trail to the Wild West?",
      "Have you ever been on a long or difficult trip? Write about what it was like.",
      "Why do you think people were willing to risk so much to search for fortune out West? Explain your idea in a paragraph."],
  h: ["이 책은 서부로 가는 길에서 몇 달을 버티려면 무엇이 필요하다고 말하나요?",
      "길고 힘든 여행을 해 본 적이 있나요? 그때 어땠는지 적어 보세요.",
      "사람들은 왜 그렇게 많은 위험을 무릅쓰고 서부에서 부를 찾으려 했을까요? 내 생각을 한 문단으로 적어 보세요."] };
ACT["S5415"] = { s: "Spanning over five hundred years, this novel tells the stories of four girls from different generations of a Jewish family, many of them forced to leave their country and start a new life.",
  q: ["What do the four girls in this book have in common, even though they live in different generations?",
      "Have you ever had to leave a place you loved and start over somewhere new? Write about it.",
      "Why do you think the author chose to tell the stories of four different girls instead of just one? Explain your idea in a paragraph."],
  h: ["이 책에 나온 네 소녀는 서로 다른 시대에 살지만 어떤 공통점이 있나요?",
      "사랑하던 곳을 떠나 새로운 곳에서 다시 시작해야 했던 적이 있나요? 그 이야기를 적어 보세요.",
      "작가는 왜 한 소녀가 아니라 네 소녀의 이야기를 들려주기로 했을까요? 내 생각을 한 문단으로 적어 보세요."] };
ACT["S5416"] = { s: "A self-proclaimed sock detective inside her parents' laundromat, Magnolia Wu sets off across New York City with her new friend Iris to solve the mystery of each lost sock, meeting people and uncovering the unimaginable along the way.",
  q: ["What mystery does Magnolia Wu try to solve in this book?",
      "Have you ever lost something and wondered what happened to it? Write about it.",
      "If you were a sock detective like Magnolia, what clues would you look for to solve a lost sock mystery? Explain your idea in a paragraph."],
  h: ["매그놀리아 우는 이 책에서 어떤 미스터리를 풀려고 하나요?",
      "무언가를 잃어버리고 그것이 어떻게 되었을지 궁금했던 적이 있나요? 그 이야기를 적어 보세요.",
      "내가 매그놀리아 같은 양말 탐정이라면 잃어버린 양말의 미스터리를 풀기 위해 어떤 단서를 찾을까요? 내 생각을 한 문단으로 적어 보세요."] };
ACT["S5417"] = { s: "The remarkable true story of Jovita Valdovinos, a Mexican revolutionary who fought for her rights. Text has violence and religious bias.",
  q: ["What did Jovita Valdovinos fight for, according to this book?",
      "Have you ever stood up for something you believed was right? Write about it.",
      "Why do you think Jovita decided to fight for her rights even though it was unusual at the time? Explain your idea in a paragraph."],
  h: ["이 책에 따르면 호비타 발도비노스는 무엇을 위해 싸웠나요?",
      "내가 옳다고 믿는 것을 위해 나선 적이 있나요? 그 이야기를 적어 보세요.",
      "호비타는 그 시절 흔치 않은 일이었는데도 왜 자신의 권리를 위해 싸우기로 했을까요? 내 생각을 한 문단으로 적어 보세요."] };
ACT["S5418"] = { s: "Young Monk and his newfound guardian, Samir, a larger-than-life character and the so-called \"Seller of Dreams,\" take an exciting journey along the Silk Road. Text has mild profanity, violence and cultural bias.",
  q: ["Who are Monk and Samir, and where do they travel together in this book?",
      "Have you ever gone on a big trip or adventure with someone who taught you something along the way? Write about it.",
      "Why do you think the author calls Samir \"the Seller of Dreams\"? Explain your idea in a paragraph."],
  h: ["몽크와 사미르는 누구이며, 이 책에서 함께 어디로 여행을 떠나나요?",
      "여행이나 모험을 함께하며 무언가를 배우게 해 준 사람이 있었나요? 그 이야기를 적어 보세요.",
      "작가는 왜 사미르를 '꿈을 파는 사람'이라고 불렀을까요? 내 생각을 한 문단으로 적어 보세요."] };
ACT["S5419"] = { s: "Johannes is a free dog, who lives in an urban park with?three ancient Bison, the Keepers of the Equilibrium. Text includes self-harm, animal abuse and disturbing imagery.",
  q: ["Who is Johannes, and who does he live with in the urban park?",
      "Have you ever had an animal friend or pet that you felt close to? Write about it.",
      "What do you think it means for the Bison to be called the \"Keepers of the Equilibrium\"? Explain your idea in a paragraph."],
  h: ["요하네스는 누구이며, 도시 공원에서 누구와 함께 사나요?",
      "가깝게 느꼈던 동물 친구나 반려동물이 있었나요? 그 이야기를 적어 보세요.",
      "들소들이 '균형의 지킴이'라고 불리는 것은 무슨 뜻일까요? 내 생각을 한 문단으로 적어 보세요."] };
ACT["S5420"] = { s: "The story the world wants to tell about Simon is the one he'd do anything to forget.?This book is a testament to the courage of moving forward without forgetting the past. Text has mild profanity, disturbing imagery, and references to a school shooting.",
  q: ["What kind of story does this book say Simon wants to forget?",
      "Have you ever wanted to forget something that happened to you, but couldn't? Write about it if you feel comfortable.",
      "Why do you think it takes courage to move forward without forgetting the past? Explain your idea in a paragraph."],
  h: ["이 책에 따르면 사이먼은 어떤 이야기를 잊고 싶어 하나요?",
      "나에게 일어난 일을 잊고 싶었지만 잊을 수 없었던 적이 있나요? 괜찮다면 그 이야기를 적어 보세요.",
      "과거를 잊지 않으면서 앞으로 나아가는 데 왜 용기가 필요할까요? 내 생각을 한 문단으로 적어 보세요."] };
ACT["S5442"] = { s: "Jack and Annie explain about all the different types of dinosaurs. The coauthor is Mary Pope Osborne.",
  q: ["What do Jack and Annie explain about in this book?",
      "What is your favorite dinosaur? Write about it.",
      "If you could ask Jack and Annie one question about dinosaurs, what would you ask? Explain your idea in a paragraph."],
  h: ["잭과 애니는 이 책에서 무엇에 대해 설명하나요?",
      "내가 가장 좋아하는 공룡은 무엇인가요? 그 공룡에 대해 적어 보세요.",
      "잭과 애니에게 공룡에 대해 한 가지 질문을 할 수 있다면 무엇을 묻고 싶나요? 내 생각을 한 문단으로 적어 보세요."] };
ACT["S5443"] = { s: "Jack and Annie look at knights, armor, and life in a castle. The coauthor is Mary Pope Osborne.",
  q: ["What three things do Jack and Annie look at in this book?",
      "Have you ever seen a picture of a knight or a castle? Write about what you remember.",
      "If you lived in a castle like the ones in this book, what would your day be like? Explain your idea in a paragraph."],
  h: ["잭과 애니는 이 책에서 어떤 세 가지를 살펴보나요?",
      "기사나 성의 그림을 본 적이 있나요? 기억나는 것을 적어 보세요.",
      "내가 이 책에 나온 성에서 산다면 하루가 어떨까요? 내 생각을 한 문단으로 적어 보세요."] };
ACT["S5444"] = { s: "Jack and Annie track the facts about space and find out about the planets, stars, and the universe.",
  q: ["What do Jack and Annie find out about in this book?",
      "Have you ever looked up at the night sky and wondered about space? Write about it.",
      "Which planet or part of space would you most like to learn more about? Explain your idea in a paragraph."],
  h: ["잭과 애니는 이 책에서 무엇에 대해 알아보나요?",
      "밤하늘을 보며 우주에 대해 궁금해한 적이 있나요? 그 이야기를 적어 보세요.",
      "어떤 행성이나 우주의 어떤 부분을 더 알고 싶나요? 내 생각을 한 문단으로 적어 보세요."] };
ACT["S5445"] = { s: "This book explores the history of the steamship \"Titanic,\" from Thomas Andrews' plans for \"the safest ship on the ocean\" to the lingering questions concerning its disastrous maiden voyage in 1912. The coauthor is Mary Pope Osborne.",
  q: ["What does this book explore about the Titanic's plans and its 1912 voyage?",
      "Have you ever heard the story of the Titanic before? Write about what you know.",
      "Why do you think there are still lingering questions about the Titanic's disaster? Explain your idea in a paragraph."],
  h: ["이 책은 타이타닉호의 계획과 1912년 항해에 대해 무엇을 살펴보나요?",
      "타이타닉호 이야기를 들어 본 적이 있나요? 아는 것을 적어 보세요.",
      "타이타닉호의 사고에 대해 왜 아직도 풀리지 않은 질문들이 남아 있을까요? 내 생각을 한 문단으로 적어 보세요."] };
ACT["S5446"] = { s: "This book discusses dolphins and sharks, their ocean habitats, and general information about oceans and oceanography. The coauthor is Natalie Pope Boyce.",
  q: ["What does this book discuss about dolphins and sharks?",
      "Have you ever seen a dolphin or a shark, in real life or on TV? Write about it.",
      "Which ocean animal from this book would you like to learn more about? Explain your idea in a paragraph."],
  h: ["이 책은 돌고래와 상어에 대해 무엇을 다루나요?",
      "실제로나 TV에서 돌고래나 상어를 본 적이 있나요? 그 이야기를 적어 보세요.",
      "이 책에 나온 바다 동물 중 무엇을 더 알고 싶나요? 내 생각을 한 문단으로 적어 보세요."] };
ACT["S5447"] = { s: "What was it like to be a gladiator? How many people died in the destruction of Pompeii? Find out the answers to these questions in this research guide to VACATION UNDER THE VOLCANO (Magic Tree House #13). The coauthor is Natalie Pope Boyce.",
  q: ["What two questions does this book try to answer about gladiators and Pompeii?",
      "Have you ever learned about a place that was destroyed by a natural disaster? Write about it.",
      "Why do you think people are still interested in what happened in Pompeii so long ago? Explain your idea in a paragraph."],
  h: ["이 책은 검투사와 폼페이에 대해 어떤 두 가지 질문에 답하려고 하나요?",
      "자연재해로 파괴된 곳에 대해 배운 적이 있나요? 그 이야기를 적어 보세요.",
      "사람들은 왜 그렇게 오래전 폼페이에서 일어난 일에 여전히 관심을 가질까요? 내 생각을 한 문단으로 적어 보세요."] };
ACT["S5448"] = { s: "Join Jack and Annie as they research tsunamis and other natural disasters and find out the facts behind the fiction. The coauthor is Natalie Pope Boyce.",
  q: ["What do Jack and Annie research in this book?",
      "Have you ever experienced or heard about a natural disaster? Write about it.",
      "Why do you think it is important to learn the facts about natural disasters like tsunamis? Explain your idea in a paragraph."],
  h: ["잭과 애니는 이 책에서 무엇을 조사하나요?",
      "자연재해를 겪었거나 들어 본 적이 있나요? 그 이야기를 적어 보세요.",
      "쓰나미 같은 자연재해에 대한 사실을 아는 것이 왜 중요할까요? 내 생각을 한 문단으로 적어 보세요."] };
ACT["S5449"] = { s: "This book describes some of the most famous ghost sightings, including those in New Orleans, Washington, D.C., and Great Britain. The coauthor is Natalie Pope Boyce. Book #20",
  q: ["Where are some of the famous ghost sightings described in this book?",
      "Have you ever heard a ghost story? Write about it.",
      "Do you think the ghost sightings described in this book could be real? Explain your idea in a paragraph."],
  h: ["이 책에 나온 유명한 유령 목격 사건들은 어디에서 일어났나요?",
      "유령 이야기를 들어 본 적이 있나요? 그 이야기를 적어 보세요.",
      "이 책에 나온 유령 목격담이 진짜일 수 있다고 생각하나요? 내 생각을 한 문단으로 적어 보세요."] };
ACT["S5450"] = { s: "It's a new kind of adventure for Jack and Annie as they research leprechauns and Irish folklore and find out the facts behind the fiction. The coauthor is Natalie Pope Boyce.",
  q: ["What do Jack and Annie research in this book?",
      "Have you ever heard a story about a leprechaun or another folklore creature? Write about it.",
      "Why do you think people created stories about leprechauns long ago? Explain your idea in a paragraph."],
  h: ["잭과 애니는 이 책에서 무엇을 조사하나요?",
      "레프러콘이나 다른 전설 속 생명체에 대한 이야기를 들어 본 적이 있나요? 그 이야기를 적어 보세요.",
      "옛날 사람들은 왜 레프러콘 이야기를 만들었을까요? 내 생각을 한 문단으로 적어 보세요."] };
ACT["S5451"] = { s: "This book discusses facts behind Mary Pope Osborne's A GHOST TALE FOR CHRISTMAS TIME, covering topics such as the Victorian lifestyle and the lives of children during the time of Charles Dickens. The coauthor is Natalie Pope Boyce.",
  q: ["What does this book discuss about the Victorian lifestyle and children's lives at that time?",
      "Have you ever read a story set in a different time period, like the Victorian era? Write about it.",
      "How do you think a child's life back then was different from your life now? Explain your idea in a paragraph."],
  h: ["이 책은 빅토리아 시대의 생활과 그 시절 아이들의 삶에 대해 무엇을 다루나요?",
      "빅토리아 시대처럼 다른 시대를 배경으로 한 이야기를 읽어 본 적이 있나요? 그 이야기를 적어 보세요.",
      "그때 아이의 삶은 지금 내 삶과 어떻게 달랐을까요? 내 생각을 한 문단으로 적어 보세요."] };
ACT["S5452"] = { s: "Join Jack and Annie as they find out the facts behind the fiction about snakes and other reptiles. The coauthor is Natalie Pope Boyce.",
  q: ["What do Jack and Annie find out about in this book?",
      "Have you ever seen a snake or another reptile? Write about it.",
      "Which reptile from this book would you like to learn more about? Explain your idea in a paragraph."],
  h: ["잭과 애니는 이 책에서 무엇에 대해 알아보나요?",
      "뱀이나 다른 파충류를 본 적이 있나요? 그 이야기를 적어 보세요.",
      "이 책에 나온 파충류 중 무엇을 더 알고 싶나요? 내 생각을 한 문단으로 적어 보세요."] };
ACT["S5453"] = { s: "Jack and Annie investigate questions about the time period they visited, from what it was like to grow up in a log cabin, what Lincoln's family life was like, and how Lincoln became president. The coauthor is Natalie Pope Boyce.",
  q: ["What three things do Jack and Annie investigate about Abraham Lincoln in this book?",
      "Have you ever learned about Abraham Lincoln before? Write about what you remember.",
      "What do you think was hardest about growing up in a log cabin, based on this book? Explain your idea in a paragraph."],
  h: ["잭과 애니는 이 책에서 에이브러햄 링컨에 대해 어떤 세 가지를 조사하나요?",
      "링컨에 대해 배운 적이 있나요? 기억나는 것을 적어 보세요.",
      "이 책을 보면 통나무집에서 자라는 것 중 가장 힘든 점은 무엇이었을까요? 내 생각을 한 문단으로 적어 보세요."] };
ACT["S5454"] = { s: "What do pandas eat? Where do they live? Why are leatherback sea turtles so scarce? How can we help? Find out the answers to these questions and more as Jack and Annie track the facts. The coauthor is Natalie Pope Boyce.",
  q: ["What questions about pandas and other endangered species does this book answer?",
      "Have you ever learned about an endangered animal? Write about it.",
      "What do you think people can do to help endangered animals like the ones in this book? Explain your idea in a paragraph."],
  h: ["이 책은 판다와 다른 멸종 위기 동물에 대해 어떤 질문에 답하나요?",
      "멸종 위기에 처한 동물에 대해 배운 적이 있나요? 그 이야기를 적어 보세요.",
      "이 책에 나온 동물들을 돕기 위해 사람들이 무엇을 할 수 있을까요? 내 생각을 한 문단으로 적어 보세요."] };
ACT["S5455"] = { s: "Find the answers to the questions Jack and Annie have about horses. The coauthor is Natalie Pope Boyce.",
  q: ["What kind of questions about horses does this book answer?",
      "Have you ever ridden a horse or seen one up close? Write about it.",
      "What do you think makes a horse a hero? Explain your idea in a paragraph."],
  h: ["이 책은 말에 대한 어떤 질문에 답하나요?",
      "말을 타 보거나 가까이서 본 적이 있나요? 그 이야기를 적어 보세요.",
      "말이 영웅이 되는 것은 어떤 모습일까요? 내 생각을 한 문단으로 적어 보세요."] };
ACT["S5456"] = { s: "Jack and Annie track the facts behind six amazing people who have changed history, including Florence Nightingale, Martin Luther King Jr., Gandhi, Harriet Tubman, Susan B. Anthony, and John Muir. The coauthor is Natalie Pope Boyce.",
  q: ["Name one of the six heroes described in this book and what they are known for.",
      "Have you ever learned about one of these heroes before? Write about what you remember.",
      "Which of these six heroes would you most like to learn more about, and why? Explain your idea in a paragraph."],
  h: ["이 책에 나온 여섯 명의 영웅 중 한 명을 골라 그가 무엇으로 유명한지 적어 보세요.",
      "이 영웅들 중 한 명에 대해 배운 적이 있나요? 기억나는 것을 적어 보세요.",
      "여섯 영웅 중 누구를 가장 더 알고 싶나요? 이유와 함께 한 문단으로 적어 보세요."] };
ACT["S5457"] = { s: "How did soccer get started? Who are some of its players? What is the World Cup? Find out the answers to these questions and more as Jack and Annie track the facts behind one of the world's most popular sports. The coauthor is Natalie Pope Boyce.",
  q: ["What three things does this book explain about soccer?",
      "Have you ever played or watched a soccer game? Write about it.",
      "What do you think makes soccer one of the world's most popular sports? Explain your idea in a paragraph."],
  h: ["이 책은 축구에 대해 어떤 세 가지를 설명하나요?",
      "축구를 해 보거나 본 적이 있나요? 그 이야기를 적어 보세요.",
      "축구가 세계에서 가장 인기 있는 스포츠 중 하나인 이유는 무엇일까요? 내 생각을 한 문단으로 적어 보세요."] };
ACT["S5458"] = { s: "What did it mean to be a ninja or a samurai? What was life like for them in ancient Japan? Find out the answers to these questions and more as Jack and Annie track the facts behind history's secretive figures. The coauthor is Natalie Pope Boyce.",
  q: ["What does this book explain about being a ninja or a samurai?",
      "Have you ever read or watched a story about ninjas or samurai? Write about it.",
      "Would you rather have been a ninja or a samurai in ancient Japan? Explain your reasons in a paragraph."],
  h: ["이 책은 닌자나 사무라이가 되는 것에 대해 무엇을 설명하나요?",
      "닌자나 사무라이가 나오는 이야기를 읽거나 본 적이 있나요? 그 이야기를 적어 보세요.",
      "고대 일본에서 닌자와 사무라이 중 무엇이 되고 싶나요? 이유와 함께 한 문단으로 적어 보세요."] };
ACT["S5459"] = { s: "Jack and Annie share information about China, the Great Wall, Chinese New Year, and other Chinese traditions. The coauthor is Natalie Pope Boyce.",
  q: ["What information does this book share about China?",
      "Have you ever celebrated or learned about Chinese New Year? Write about it.",
      "Why do you think the Great Wall of China was built so long? Explain your idea in a paragraph."],
  h: ["이 책은 중국에 대해 어떤 정보를 알려주나요?",
      "중국 설날을 기념하거나 그것에 대해 배운 적이 있나요? 그 이야기를 적어 보세요.",
      "중국의 만리장성은 왜 그렇게 길게 지어졌을까요? 내 생각을 한 문단으로 적어 보세요."] };
ACT["S5460"] = { s: "When Jack and Annie returned from their adventure in SHADOW OF THE SHARK, they had lots of questions. Find out the answers to their questions and more as Jack and Annie track the facts about sharks and other predators. The coauthor is Natalie Pope Boyce.",
  q: ["What kind of questions did Jack and Annie have after their shark adventure?",
      "Have you ever been afraid of a shark or another predator animal? Write about it.",
      "Which predator from this book would you like to learn more about, and why? Explain your idea in a paragraph."],
  h: ["잭과 애니는 상어 모험을 다녀온 뒤 어떤 질문들을 가졌나요?",
      "상어나 다른 포식 동물을 무서워한 적이 있나요? 그 이야기를 적어 보세요.",
      "이 책에 나온 포식 동물 중 무엇을 더 알고 싶나요? 이유와 함께 한 문단으로 적어 보세요."] };
ACT["S5461"] = { s: "Jack and Annie track down facts about Vikings, including where they went on raids, whether they really wore horned helmets, and what Viking ships were like. The coauthor is Natalie Pope Boyce. Book #15",
  q: ["What three things about Vikings does this book explore?",
      "Have you ever heard that Vikings wore horned helmets? Write about what you thought.",
      "What do you think Viking ships needed to be able to do, based on this book? Explain your idea in a paragraph."],
  h: ["이 책은 바이킹에 대해 어떤 세 가지를 살펴보나요?",
      "바이킹이 뿔 달린 투구를 썼다는 말을 들어 본 적이 있나요? 그때 어떻게 생각했는지 적어 보세요.",
      "이 책을 보면 바이킹 배는 무엇을 할 수 있어야 했을까요? 내 생각을 한 문단으로 적어 보세요."] };
ACT["S5462"] = { s: "Returning from their adventure in \"Balto of the Blue Dawn,\" Jack and Annie learn fun facts about sled dogs, the Iditarod, and other extreme sports, such as the X Games and Ironman competitions. The coauthor is Natalie Pope Boyce.",
  q: ["What extreme sports does this book talk about?",
      "Have you ever tried or watched an extreme sport? Write about it.",
      "Which extreme sport from this book sounds the most exciting to you, and why? Explain your idea in a paragraph."],
  h: ["이 책은 어떤 익스트림 스포츠에 대해 이야기하나요?",
      "익스트림 스포츠를 해 보거나 본 적이 있나요? 그 이야기를 적어 보세요.",
      "이 책에 나온 익스트림 스포츠 중 가장 신나 보이는 것은 무엇인가요? 이유와 함께 한 문단으로 적어 보세요."] };
ACT["S5463"] = { s: "What do tales about dragons have in common? Are mermaids real? Find out the answers to these questions and more as Jack and Annie track the facts about their favorite creatures from myths and legends. The coauthor is Natalie Pope Boyce.",
  q: ["What question about mermaids does this book try to answer?",
      "Have you ever heard a story about dragons or mermaids? Write about it.",
      "Why do you think people around the world tell similar stories about dragons? Explain your idea in a paragraph."],
  h: ["이 책은 인어에 대해 어떤 질문에 답하려고 하나요?",
      "용이나 인어에 대한 이야기를 들어 본 적이 있나요? 그 이야기를 적어 보세요.",
      "전 세계 사람들이 왜 비슷한 용 이야기를 만들었을까요? 내 생각을 한 문단으로 적어 보세요."] };
ACT["S5464"] = { s: "When was baseball invented? What are the rules of the game? Who was Jackie Robinson? Who are some other baseball greats? Become a fact tracker with Jack and Annie. The coauthor is Natalie Pope Boyce.",
  q: ["What does this book explain about the history of baseball?",
      "Have you ever played or watched baseball? Write about it.",
      "Why do you think Jackie Robinson is an important person in baseball history? Explain your idea in a paragraph."],
  h: ["이 책은 야구의 역사에 대해 무엇을 설명하나요?",
      "야구를 해 보거나 본 적이 있나요? 그 이야기를 적어 보세요.",
      "재키 로빈슨이 야구 역사에서 중요한 인물인 이유는 무엇일까요? 내 생각을 한 문단으로 적어 보세요."] };
ACT["S5465"] = { s: "What is a ghost town? Why do we call the Old West wild? What are cowboys? Who was Billy the Kid? Find out the answers to these questions and more as Jack and Annie track the facts about the American West. The coauthor is Natalie Pope Boyce.",
  q: ["What does this book explain about ghost towns and cowboys?",
      "Have you ever watched a movie or read a story set in the Wild West? Write about it.",
      "What do you think life was like for a cowboy in the Wild West? Explain your idea in a paragraph."],
  h: ["이 책은 유령 마을과 카우보이에 대해 무엇을 설명하나요?",
      "서부를 배경으로 한 영화나 이야기를 본 적이 있나요? 그 이야기를 적어 보세요.",
      "서부 시대 카우보이의 삶은 어땠을까요? 내 생각을 한 문단으로 적어 보세요."] };
ACT["S5466"] = { s: "Jack and Annie share facts about the Alamo, the Galveston hurricane, and the great state of Texas. The coauthor is Natalie Pope Boyce.",
  q: ["What facts does this book share about the Alamo and the Galveston hurricane?",
      "Have you ever heard about a hurricane or a big storm? Write about it.",
      "Why do you think the Alamo is an important part of Texas history? Explain your idea in a paragraph."],
  h: ["이 책은 알라모와 갤버스턴 허리케인에 대해 어떤 사실을 알려주나요?",
      "허리케인이나 큰 폭풍에 대해 들어 본 적이 있나요? 그 이야기를 적어 보세요.",
      "알라모가 텍사스 역사에서 중요한 부분인 이유는 무엇일까요? 내 생각을 한 문단으로 적어 보세요."] };
ACT["S5467"] = { s: "When Jack and Annie come back from their adventure in Warriors in Winter, they have lots of questions. Find out the answers to these questions and more as they track the facts about ancient warriors. The coauthor is Natalie Pope Boyce.",
  q: ["What kind of questions do Jack and Annie have about ancient warriors in this book?",
      "Have you ever read a story about warriors from long ago? Write about it.",
      "What do you think it took to become an ancient warrior? Explain your idea in a paragraph."],
  h: ["잭과 애니는 이 책에서 고대 전사들에 대해 어떤 질문들을 가지나요?",
      "먼 옛날 전사에 대한 이야기를 읽어 본 적이 있나요? 그 이야기를 적어 보세요.",
      "고대 전사가 되려면 무엇이 필요했을까요? 내 생각을 한 문단으로 적어 보세요."] };
ACT["S5468"] = { s: "When Jack and Annie came back from their adventure meeting Ben Franklin, they had a lot of questions. Readers will learn more about Ben's life, his most famous inventions, nicknames, and other interesting facts. The coauthor is Natalie Pope Boyce.",
  q: ["What three things does this book teach about Benjamin Franklin?",
      "Have you ever used something that was invented a long time ago? Write about it.",
      "Which of Benjamin Franklin's inventions do you think was the most useful, and why? Explain your idea in a paragraph."],
  h: ["이 책은 벤저민 프랭클린에 대해 어떤 세 가지를 알려주나요?",
      "아주 오래전에 발명된 물건을 사용해 본 적이 있나요? 그 이야기를 적어 보세요.",
      "벤저민 프랭클린의 발명품 중 가장 쓸모 있었던 것은 무엇일까요? 이유와 함께 한 문단으로 적어 보세요."] };
ACT["S5469"] = { s: "When Jack and Annie came back from their adventure in Magic Tree House #33-Narwhal on a Sunny Night, they had lots of questions about narwhals. Book #42 The coauthor is Natalie Pope Boyce.",
  q: ["What kind of questions did Jack and Annie have about narwhals after their adventure?",
      "Have you ever seen a whale or a narwhal in a picture or video? Write about it.",
      "What do you think makes narwhals different from other whales? Explain your idea in a paragraph."],
  h: ["잭과 애니는 모험을 다녀온 뒤 일각고래에 대해 어떤 질문들을 가졌나요?",
      "사진이나 영상에서 고래나 일각고래를 본 적이 있나요? 그 이야기를 적어 보세요.",
      "일각고래는 다른 고래와 무엇이 다를까요? 내 생각을 한 문단으로 적어 보세요."] };
ACT["S5470"] = { s: "This book gives an overview of llamas, chinchillas, and other Andean animals, as well as a general look at the region and its people. The coauthor is Natalie Pope Boyce.",
  q: ["What animals and region does this book give an overview of?",
      "Have you ever seen a llama, in real life or in a picture? Write about it.",
      "What do you think life is like for animals living high in the Andes mountains? Explain your idea in a paragraph."],
  h: ["이 책은 어떤 동물들과 지역에 대해 전반적으로 알려주나요?",
      "실제로나 사진에서 라마를 본 적이 있나요? 그 이야기를 적어 보세요.",
      "안데스산맥 높은 곳에 사는 동물들의 삶은 어떨까요? 내 생각을 한 문단으로 적어 보세요."] };
ACT["S5471"] = { s: "Readers will get to track the facts about snow leopards and other amazing wild cats. The coauthor is Jenny Laird.",
  q: ["What wild cats does this book help you track facts about?",
      "Have you ever seen a wild cat, like a leopard or a tiger, in a zoo or a picture? Write about it.",
      "Why do you think snow leopards are hard for people to see in the wild? Explain your idea in a paragraph."],
  h: ["이 책은 어떤 야생 고양잇과 동물들에 대한 사실을 알아보게 해 주나요?",
      "동물원이나 사진에서 표범이나 호랑이 같은 야생 고양이를 본 적이 있나요? 그 이야기를 적어 보세요.",
      "눈표범은 왜 야생에서 사람들 눈에 잘 띄지 않을까요? 내 생각을 한 문단으로 적어 보세요."] };
ACT["S5486"] = { s: "When thirteen-year-old Sage's best friend dies, Sage struggles with grief and feels that she is at fault, but when she joins a grief group, she slowly learns to heal.",
  q: ["What does Sage join to help her deal with her feelings in this book?",
      "Have you ever felt sad about losing someone or something important? Write about it if you feel comfortable.",
      "Why do you think it helped Sage to share her feelings with a group instead of dealing with them alone? Explain your idea in a paragraph."],
  h: ["세이지는 이 책에서 자신의 감정을 다루기 위해 무엇에 참여하나요?",
      "소중한 사람이나 것을 잃어서 슬펐던 적이 있나요? 괜찮다면 그 이야기를 적어 보세요.",
      "세이지가 혼자가 아니라 여러 사람과 함께 감정을 나눈 것이 왜 도움이 되었을까요? 내 생각을 한 문단으로 적어 보세요."] };
ACT["S5487"] = { s: "Based on a true story, twelve-year-old Roberto Alvarez stands up for justice for his Mexican American community in a 1931 lawsuit challenging school segregation in Lemon Grove, California. Book has offensive language (Racial).",
  q: ["What did Roberto Alvarez stand up for in this true story?",
      "Have you ever seen someone treated unfairly and wanted to help? Write about it.",
      "Why do you think a twelve-year-old like Roberto was able to make a difference in his community? Explain your idea in a paragraph."],
  h: ["이 실화에서 로베르토 알바레스는 무엇을 위해 나섰나요?",
      "누군가 부당하게 대우받는 것을 보고 돕고 싶었던 적이 있나요? 그 이야기를 적어 보세요.",
      "로베르토처럼 열두 살 아이가 어떻게 자기 지역사회를 변화시킬 수 있었을까요? 내 생각을 한 문단으로 적어 보세요."] };
ACT["S5488"] = { s: "An undead fox serving as the usher of souls has his life upended when a mysterious badger soul appears.",
  q: ["What job does the undead fox have in this story?",
      "Have you ever read a fantasy story with animal characters that have special jobs? Write about it.",
      "What do you think happens when the mysterious badger soul appears and changes the fox's life? Explain your idea in a paragraph."],
  h: ["이 이야기에서 되살아난 여우는 어떤 일을 맡고 있나요?",
      "특별한 일을 맡은 동물 캐릭터가 나오는 판타지 이야기를 읽어 본 적이 있나요? 그 이야기를 적어 보세요.",
      "수수께끼 같은 오소리 영혼이 나타나 여우의 삶을 바꾸면 무슨 일이 벌어질까요? 내 생각을 한 문단으로 적어 보세요."] };
